### ISSUE TITLE
How to disable the "multi-subscribe" feature of xep-0060

### ISSUE THREAD

**Issue by rytong-HuangXin** [processone/ejabberd#100]
Hi,

I have setup a Ejabberd 2.1.11 with mod_pubsub. The "multi-subscribe" feature is supported but it preferes to be disabled in my application.

Is it possible without changing source codes, please?

Thanks.

**Comment by cromain** [comment]
solution for this: create your own node module (fork node_flat or node_hometree)
then remove "multi-subscribe" line in the features() function.
finally configure mod_pubsub to use your node module instead of flat/hometree.
