### ISSUE TITLE
Segmentation fault on raspberry pi armv6

### ISSUE THREAD

**Issue by zarere** [processone/ejabberd#1000]
Hi all,

I'm trying to run the latest version 16.2 but when i start the server with ejabberdctl foreground i got this:

    ejabberdctl foreground
    10:09:41.564 [info] Application lager started on node ejabberd@localhost
    10:09:41.834 [info] Application crypto started on node ejabberd@localhost
    10:09:42.055 [info] Application sasl started on node ejabberd@localhost
    10:09:42.457 [info] Application asn1 started on node ejabberd@localhost
    10:09:42.467 [info] Application public_key started on node ejabberd@localhost
    10:09:42.780 [info] Application ssl started on node ejabberd@localhost
    10:09:42.878 [info] Application fast_yaml started on node ejabberd@localhost
    10:09:43.028 [info] Application fast_tls started on node ejabberd@localhost
    10:09:43.212 [info] Application fast_xml started on node ejabberd@localhost
    10:09:43.326 [info] Application stringprep started on node ejabberd@localhost
    10:09:43.518 [info] Application ezlib started on node ejabberd@localhost
    10:09:43.720 [info] Application cache_tab started on node ejabberd@localhost
    10:09:47.201 [info] Application mnesia started on node ejabberd@localhost
    10:10:05.080 [info] Application inets started on node ejabberd@localhost
    /sbin/ejabberdctl: line 259:  2939 Segmentation fault      $EXEC_CMD "$CMD"

My hardware is
raspberry pi with 512ram
root@raspberry:~# lscpu
Architecture: armv6l
Byte Order: Little Endian
CPU(s): 1
On-line CPU(s) list: 0
Thread(s) per core: 1
Core(s) per socket: 1
Socket(s): 1

I installed ejabberd from source.Please advise

**Comment by zarere** [comment]
Here is the core file created from the above command.
[erl_crash.dump.zip](https://github.com/processone/ejabberd/files/171594/erl_crash.dump.zip)

**Comment by zarere** [comment]
Note that the core file attached here is with version 15.11 since I tried with 16.02,16.01,15,11 and the results are still the same **segmentation fault**

**Comment by mremond** [comment]
What's your Erlang version ?

**Comment by zarere** [comment]
dpkg -l |grep erla
ii  erlang                                1:18.2                                  all          Concurrent, real-time, distributed functional language
ii  erlang-appmon                         1:18.1                                  armhf        Erlang/OTP application monitor
ii  erlang-asn1                           1:18.1                                  armhf        Erlang/OTP modules for ASN.1 support
ii  erlang-base                           1:18.1                                  armhf        Erlang/OTP virtual machine and base applications
ii  erlang-common-test                    1:18.1                                  armhf        Erlang/OTP application for automated testing
ii  erlang-corba                          1:18.1                                  armhf        Erlang/OTP applications for CORBA support
ii  erlang-crypto                         1:18.1                                  armhf        Erlang/OTP cryptographic modules
ii  erlang-debugger                       1:18.1                                  armhf        Erlang/OTP application for debugging and testing
ii  erlang-dev                            1:18.1                                  armhf        Erlang/OTP development libraries and headers
ii  erlang-dialyzer                       1:18.1                                  armhf        Erlang/OTP discrepancy analyzer application
ii  erlang-diameter                       1:18.1                                  armhf        Erlang/OTP implementation of RFC 3588 protocol
ii  erlang-edoc                           1:18.1                                  armhf        Erlang/OTP module for generating documentation
ii  erlang-eldap                          1:18.1                                  armhf        Erlang/OTP LDAP library
ii  erlang-erl-docgen                     1:18.1                                  armhf        Erlang/OTP documentation stylesheets
ii  erlang-et                             1:18.1                                  armhf        Erlang/OTP event tracer application
ii  erlang-eunit                          1:18.1                                  armhf        Erlang/OTP module for unit testing
ii  erlang-gs                             1:18.1                                  armhf        Erlang/OTP graphics system
ii  erlang-ic                             1:18.1                                  armhf        Erlang/OTP IDL compiler
ii  erlang-inets                          1:18.1                                  armhf        Erlang/OTP Internet clients and servers
ii  erlang-inviso                         1:18.1                                  armhf        Erlang/OTP trace tool
ii  erlang-jinterface                     1:18.2                                  all          Java communication tool to Erlang
ii  erlang-megaco                         1:18.1                                  armhf        Erlang/OTP implementation of Megaco/H.248 protocol
ii  erlang-mnesia                         1:18.1                                  armhf        Erlang/OTP distributed relational/object hybrid database
ii  erlang-mode                           1:18.2                                  all          Erlang major editing mode for Emacs
ii  erlang-observer                       1:18.1                                  armhf        Erlang/OTP application for investigating distributed systems
ii  erlang-odbc                           1:18.1                                  armhf        Erlang/OTP interface to SQL databases
ii  erlang-os-mon                         1:18.1                                  armhf        Erlang/OTP operating system monitor
ii  erlang-parsetools                     1:18.1                                  armhf        Erlang/OTP parsing tools
ii  erlang-percept                        1:18.1                                  armhf        Erlang/OTP concurrency profiling tool
ii  erlang-pman                           1:18.1                                  armhf        Erlang/OTP process manager
ii  erlang-public-key                     1:18.1                                  armhf        Erlang/OTP public key infrastructure
ii  erlang-reltool                        1:18.1                                  armhf        Erlang/OTP release management tool
ii  erlang-runtime-tools                  1:18.1                                  armhf        Erlang/OTP runtime tracing/debugging tools
ii  erlang-snmp                           1:18.1                                  armhf        Erlang/OTP SNMP applications
ii  erlang-ssh                            1:18.1                                  armhf        Erlang/OTP implementation of SSH protocol
ii  erlang-ssl                            1:18.1                                  armhf        Erlang/OTP implementation of SSL
ii  erlang-syntax-tools                   1:18.1                                  armhf        Erlang/OTP modules for handling abstract Erlang syntax trees
ii  erlang-test-server                    1:18.1                                  armhf        Erlang/OTP server for automated application testing
ii  erlang-toolbar                        1:18.1                                  armhf        Erlang/OTP graphical toolbar
ii  erlang-tools                          1:18.1                                  armhf        Erlang/OTP various tools
ii  erlang-tv                             1:18.1                                  armhf        Erlang/OTP table viewer
ii  erlang-typer                          1:18.1                                  armhf        Erlang/OTP code type annotator
ii  erlang-webtool                        1:18.1                                  armhf        Erlang/OTP helper for web-based tools
ii  erlang-wx                             1:18.1                                  armhf        Erlang/OTP bindings to wxWidgets
ii  erlang-xmerl                          1:18.1                                  armhf        Erlang/OTP XML tools

**Comment by cromain** [comment]
Hello

As you are building from sources, then you need gcc5.
By the way, did you tried our official ARM installer ? it works on rpi2. (we did not tested it on armv6 as we use an armv7 build chain, but maybe it just works)

**Comment by zarere** [comment]
Great 10x but it will be nice if the needed version og gcc is mentioned in the requirements .About 
official ARM installer:

 
    root@raspberry:/home/pi/update# chmod +x ejabberd-16.02-linux-armhf-installer.run 
    root@raspberry:/home/pi/update# ./ejabberd-16.02-linux-armhf-installer.run 
    installing ejabberd-16.02...
    * Generate bin/ejabberd.init
    * Generate bin/erl
    * Generate bin/ejabberdctl
    * Set default config in conf/ejabberd.yml
    * Terminate ejabberd installation

Done
root@raspberry:/home/pi/update/ejabberd-16.02/bin# ./ejabberdctl start
Segmentation fault
Segmentation fault

So the only option is update gcc to 5?

**Comment by zarere** [comment]
```
gdb /home/pi/update/ejabberd-16.02/bin/beam.smp core 
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/pi/update/ejabberd-16.02/bin/beam.smp...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 2005]
Core was generated by `/home/pi/update/ejabberd-16.02/bin/erlexec -sname ejabberd@raspberry -noinput -'.
Program terminated with signal 11, Segmentation fault.

```

**Comment by cromain** [comment]
indeed your only option is to use gcc5

**Comment by zarere** [comment]
Thank you for your help.After installing gcc5 everythig is working as expected.I'm closing the issue.
