### ISSUE TITLE
randoms,get_string crash

### ISSUE THREAD

**Issue by njnuwjq** [processone/ejabberd#1003]
Please answer these questions before submitting your issue. It may help !

Thanks!

1. What version of ejabberd are you using ?
R14

2. What operating system are you using ?
$ cat /proc/version 
Linux version 3.10.0-229.7.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Jun 23 22:06:11 UTC 2015

3. How did you install ejabberd (source, package, distribution) ?
source

4. What did not work as expected ? What that error in the log ?
   What that unexpected behaviour ? What was the expected result ?

run exmpp example echo_client:start, but got following messages for several times,
Error in process <0.66.0> with exit value: {{case_clause,tcp_closed},[{exmpp_session,connect_TCP,4,[{file,"./network/exmpp_session.erl"},{line,272}]},{echo_client,init,2,[{file,"echo_client.erl"},{line,90}]}]}

 there's no debug in ejabberd.log, but a crash report
2016-03-14 14:21:25.429 [error] <0.7733.10> CRASH REPORT Process <0.7733.10> with 0 neighbours exited with reason: bad argument in randoms:get_string/0 line 48 in p1_fsm:init_it/6 line 39

looking into the crash, 
2016-03-14 14:22:16 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.7888.10>
    registered_name: []
    exception exit: {{badarg,[{randoms,get_string,0,[{file,"src/randoms.erl"},{line,48}]},{ejabberd_c2s,init,1,[{file,"src/ejabberd_c2s.erl"},{line,357}]},{p1_fsm,init_it,6,[{file,"src/p1_fsm.erl"},{line,376}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},[{p1_fsm,init_it,6,[{file,"src/p1_fsm.erl"},{line,391}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.1067.1>,ejabberd_listeners,ejabberd_sup,<0.384.1>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 238
  neighbours:

and which caused ejabberd_c2s,init failed, and the tcp connection down.

looking into the randoms:get_string, but can't found any error, so could you pls help looking into this problem? thanks~

**Comment by mremond** [comment]
R14 is the version of Erlang, not ejabberd.
Please note that latest version of ejabberd are compliant only with Erlang R17+

Can you please clarify and let us know which version of ejabberd you are using ?

Thanks !

**Comment by mremond** [comment]
Closing now, as it seems you are using an Erlang version that is too old for latest ejabberd.
