### ISSUE TITLE
odbc_username does not work properly for mssql

### ISSUE THREAD

**Issue by mrfrostfire** [processone/ejabberd#1008]
I am setting up an ejabberd 16.02 server on rhel7 using the standard rpm package and mssql as db.
The documentation states that if you are using an ip to the server, you might have to set the username to user@host. This however does not work properly.
The problem is that mssql is only asking for the username as is, not as user@host.
Since the username will get the @ip as suffix if you don't enter one yourself, this means any entered username will fail to authenticate unless you create a login with @ in the name, like  "ejabberd@ejabberd".

**Comment by zinid** [comment]
So you want us to remove the automatic addition of @ip ?

**Comment by mrfrostfire** [comment]
yes please.

tis 22 mars 2016 kl 10:34 skrev Evgeny Khramtsov <notifications@github.com>:

**Comment by zinid** [comment]
Done
