### ISSUE TITLE
Documentation lacks mention to mssql in some odbc required options

### ISSUE THREAD

**Issue by mrfrostfire** [processone/ejabberd#1009]
I'm setting up an ejabberd 16.02 instance on rhel 7 using mssql as db.
At first, I set up the connection following the odbc part of the documentation, but ran into a few issues, and decided to try it out using mssql as db_type.
However, the documentation is kind of missing when it comes to mssql.
It only refers to the odbc string, and then a note that if using mssql, some parameters most be set in a certain way. Parameters that according to the documentation isn't even used or used that way by mssql.
It would be appreciated if the documentation was updated to properly reflect what needs to be set in the config file to use mssql as db.

To get around this issue, I used the same config as the mysql example, but with mssql as db_type, and except for an issue (that i've filed) with odbc_username, it connected fine.

**Comment by mremond** [comment]
Where do you see it is wrong ?

I see this:
https://docs.ejabberd.im/admin/guide/configuration/#microsoft-sql-notes

With example:

``` yaml
odbc_type: mssql
odbc_server: "1.2.3.4"
...
odbc_username: "user1@host"
```

Do you have more precise reference about your report ?

**Comment by mrfrostfire** [comment]
Not sure if the documentation has changed since I created the ticket. There is one line about the mssql/odbc example I can't find anymore.
But if you look at the example you linked to, it states that you can use odbc_type, odbc_server and odbc_username + whatever is covered by "...".
But if you look at the parameters list, some of the parameters, including odbc_username states that "The option is only valid for mysql and pgsql."

So, without any example, except the one in the note, there is no way to know how to configure an mssql instance, and clearly some of the parameters marked as only to be used by mysql and pgsql is also used by mssql.

I managed to solve my configuration by copying the mysql example, but the documentation should be updated so that mssql users know what parameters are valid and required.
