### ISSUE TITLE
SIP module fails to authenticate against LDAP

### ISSUE THREAD

**Issue by theodotos** [processone/ejabberd#1010]
I have activated the SIP module on an active ejabberd installation:

```
listen:
  ...
  - 
    port: 5060
    transport: udp
    module: ejabberd_sip

  - 
    port: 5060
    module: ejabberd_sip

  - 
    port: 5061
    module: ejabberd_sip
    certfile: "/etc/ejabberd/wildcard.investme.com.pem"
    tls: true

...

modules:
  ...
  mod_sip: {}
```

But when I try to connect I get errors like this:

* With Jitsi and Ring

    ```
SIP/2.0 401 Unauthorized^M
    ```
* With Linphone I get:

    ```
SIP/2.0 407 Proxy Authentication Required
    ```

* Trying with *sipsak* I get this:

    <pre>
<strong>sipsak -vv -s sip:john.doe@example.com</strong>
No SRV record: _sip._tcp.example.com
using SRV record: _sip._udp.example.com:5060
warning: need raw socket (root privileges) to receive all ICMP errors
 
message received:
SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/UDP 127.0.1.1:60548;branch=z9hG4bK.29a5139f;alias;received=1.2.3.4;rport=36040
From: <sip:sipsak@127.0.1.1:60548>;tag=3320301c
Call-ID: 857747484@127.0.1.1
CSeq: 1 OPTIONS
Max-Forwards: 70
To: <sip:john.doe@example.com>;tag=100913185-3544120597
Server: ejabberd 14.07
Content-Length: 0
 
 
 
** reply received after 205.126 ms **
   SIP/2.0 480 Temporarily Unavailable
   final received
    </pre>

You can see the detailed logs here:
http://pastebin.com/KrQHrm2s

XMPP works and authenticates correctly against LDAP. I have the suspicion that mod_sip does not support LDAP authentication (at least the version I am using).

Any ideas?

----------------------------------------------------

1. What version of ejabberd are you using ?

14.07-4+deb8u3

2. What operating system are you using ?

Debian Jessie (8.3 64 bit)

3. How did you install ejabberd (source, package, distribution) ?

apt-get install ejabberd

4. What did not work as expected ? What that error in the log ?
   What that unexpected behaviour ? What was the expected result ?

SIP fails to authenticate after activation 

These are the logs using different SIP clients:

http://pastebin.com/KrQHrm2s

**Comment by zinid** [comment]
Yes, there is a problem with LDAP, because in order to authenticate against SIP digest we need to have plain user password, which cannot be fetched from LDAP server. To authenticate XMPP users via LDAP we're using a password from SASL PLAIN stanza provided by a client and perform LDAP Bind query. And this is also not available for SIP, because Digest request doesn't have a password, but only and md5 hash.

**Comment by theodotos** [comment]
Thanks @zinid 

So even using the latest version will probably not help...

**Comment by mremond** [comment]
@theodotos yes this is a compliance issue between auth mecanism requirements and LDAP. We do not wee a way to solve this at the moment.
