### ISSUE TITLE
the messages stored in ejabberd disappear with a period of time

### ISSUE THREAD

**Issue by MetalZoa0** [processone/ejabberd#1014]
the messages stored in ejabberd disappear with a period of time, what should be done for the messages to be saved permanently? i am using ejabberd 15.10 with client jappix 1.1.6. and mysql database.

**Comment by badlop** [comment]
If you refer to mod_mam, looking at its source code, I see only two cases where messages are removed:
* When an account is removed, all its messages are also removed
* There is an ejabberd command: "delete_old_messages TYPE DAYS". It is intended for system admins, to delete very old messages. Nowhere in ejabberd source code that command is called automatically.

**Comment by MetalZoa0** [comment]
but and the standard mnesia database? which is the setting that leave the saved messages permanently, as there is a default message limit ejabberd with mnesia database.

**Comment by weiss** [comment]
How did you verify that messages disappear?  Have you checked the database contents at two points in time?

**Comment by MetalZoa0** [comment]
yes, the messages disappear in a period of 8 and 12 hours

**Comment by MetalZoa0** [comment]
i am using database mnesia currently

**Comment by weiss** [comment]
> the messages disappear in a period of 8 and 12 hours

My question was how you're *verifying* that.  Did you, for example, dump the Mnesia data (using a command such as `ejabberdctl --no-timeout dump /tmp/ejabberd.dmp`), and another one 12 hours later, and did you then find some messages only in the first one?  If that's not what you've done, how else did you notice that messages disappear?

**Comment by MetalZoa0** [comment]
good, just disappear, so I asked if there is any limitation on the question of the number of messages stored per node in ejabberd, because from time to time they just disappear, so I think it is something related to a limitation of quantity or cache

**Comment by weiss** [comment]
There's the following Mnesia limit mentioned [in the documentation][1]:

> If `mnesia` is used, the total size of all MAM archives cannot exceed 2 GB. The `delete_old_mam_messages` command could be run periodically to make sure the `mnesia` data won’t grow beyond that limit. To support larger archives, `odbc` storage must be used.

But if you hit that limit, Mnesia would stop storing new messages (as opposed to dropping old ones), so this doesn't explain the behavior you're describing.

> I asked if there is any limitation on the question of the number of messages

Apart from that 2 GB limit, there's no such limitation, as @badlop told you.

I asked you [a question][2] to track the issue down.  If you don't answer that question, I don't know how to help you.

[1]: https://docs.ejabberd.im/admin/guide/configuration/#modmam
[2]: https://github.com/processone/ejabberd/issues/1014#issuecomment-198097607

**Comment by ygz012** [comment]
我要退订

发自我的 iPhone

**Comment by mremond** [comment]
Please, reopen the ticket if you have more information to provide on the issue.
Thanks !
