### ISSUE TITLE
Error executing post installation script [v:16.02 OS: windows 10]

### ISSUE THREAD

**Issue by s1Moinuddin** [processone/ejabberd#1018]
> What version of ejabberd are you using?
-- 16.02

> What operating system (version) are you using?
-- windows 10 64 bit

> How did you install ejabberd (source, package, distribution)?
-- distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
-- 
![untitled](https://cloud.githubusercontent.com/assets/10473280/13856783/10d10f8a-eca1-11e5-9b28-37239d3999d3.jpg)

Unpacking C:\Program Files\ejabberd-16.02\bin\libiconv-2.dll
Creating Desktop Shortcut for Start ejabberd
Creating Desktop Shortcut for Stop ejabberd
Executing final installation script
Error executing post installation script
C:\Program Files\ejabberd-16.02\bin\postinstall.cmd
\Program ended with an error exit code
Creating Uninstaller
Creating uninstaller 25%
Creating uninstaller 50%
Creating uninstaller 75%
Creating uninstaller 100%
Uninstaller icon changed
Installation completed
Log finished 03/18/2016 at 01:17:21

**Comment by mremond** [comment]
Do you have msvcrt100.dll on your system ?

It was reported on https://github.com/processone/ejabberd/issues/960 that on some windows instance it need to be installed separately.

**Comment by s1Moinuddin** [comment]
Yes I have it in my system. 
![2](https://cloud.githubusercontent.com/assets/10473280/13857137/c33eb1c6-eca2-11e5-9653-302d84f995d8.jpg)

**Comment by cromain** [comment]
problem is due to wrong location of %AppData%
some data are copied in user's appdata, other in admin appdata.
it seems windows 10 does not behave the same way as older windows server on that regards. this needs investigations

**Comment by cromain** [comment]
installer works fine as long as ejabberd is run as administrator

**Comment by cromain** [comment]
closing this now.
post-installation is now more tolerant and will not trigger install error.
support to run ejabberd as standard user will be covered by #666

**Comment by arockiasamy1990** [comment]
i m also facing this same issue post installation failed in windows 7 32 bit ejabberd version 15.09 help me out to fix that issue

**Comment by mremond** [comment]
You should try with ejabberd 16.09.

**Comment by arockiasamy1990** [comment]
i m tried ejabberd 16.09 same error occur please help me

**Comment by Mtali** [comment]
I tried installing ejabberd 16.09 i get the same error. I am using windows 10 - 64bit

**Comment by solodyagin** [comment]
I tried installing 16.09, 16.12 and 17.01 and get the same error. I am using windows 10 64 bit too.

**Comment by rickysut** [comment]
I have the same problem win 10 64 bit

**Comment by Moussawi90** [comment]
I have the same error with ejabberd 17.12 on windows 10

**Comment by Moussawi90** [comment]
I have the same error with ejabberd 17.12 on windows 10

**Comment by Moussawi90** [comment]
I have the same error with ejabberd 17.12 on windows 10

**Comment by Gh0stts0hg** [comment]
still get the error. ran as admin, C: drive... error running post install....
