### ISSUE TITLE
mod_irc: long messages are silently truncated by the server

### ISSUE THREAD

**Issue by l29ah** [processone/ejabberd#1019]
According to https://tools.ietf.org/html/rfc2812, irc commands shouldn't be longer than 512 characters, and they're being truncated by Freenode which is the most popular irc network nowadays. I suggest they should either be split or an error should be shown to the user to prevent silent data loss.

**Comment by badlop** [comment]
Apparently, there is not much interest in this improvement.

**Comment by l29ah** [comment]
For the record: biboumi splits the messages.
