### ISSUE TITLE
Change ejabberd host name and node name

### ISSUE THREAD

**Issue by netknokt** [processone/ejabberd#1023]
> What version of ejabberd are you using?
2.1.11-1ubuntu2.1

> What operating system (version) are you using?
Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I'm trying to change the hostname of the host and following the instructions here (https://docs.ejabberd.im/admin/guide/managing/#change-computer-hostname) 
but it doesn't work at all.
I get to Step 4&5 which looks like this:
```
root@m:~# mv /var/lib/ejabberd/*.* /var/lib/ejabberd/oldfiles/
root@m:~# ejabberdctl start
The node ejabberd@m is started with status: started
ejabberd is not running in that node
Check for error messages: ejabberd.log
or other files in that directory.
```

Error in ejabberd ctl process: 'error' badarg

I've tried lots of variations, to no avail. If the node won't run ejabberd, I can't get anywhere. 

And removing all the files from /var/lib/ejabberd really seems to not help at all

**Comment by badlop** [comment]
> Error in ejabberd ctl process: 'error' badarg

Is the error message longer? I mean, does it provide anything else other than just "error badarg"?

> And removing all the files from /var/lib/ejabberd really seems to not help at all

I assume that dir is where ejabberd creates the mnesia spool files when starts the first time in your system: 
caps_features.DAT irc_custom.DCD last_activity.DCD LATEST.LOG motd.DCD ...

Please note that maybe the Ubuntu package for ejabberd uses another path for those files.

**Comment by netknokt** [comment]
>I assume that dir is where ejabberd creates the mnesia spool files when starts the first time in your system: 
caps_features.DAT irc_custom.DCD last_activity.DCD LATEST.LOG motd.DCD ...

You are correct.

Old host name of machine: "mail"

New host name of machine "m"

Thanks.

****** Log file *******
=INFO REPORT==== 2016-03-19 01:42:51 ===
I(<0.41.0>:ejabberd_app:89) : ejabberd 2.1.11 is stopped in the node ejabberd@mail

=ERROR REPORT==== 2016-03-19 01:45:05 ===
E(<0.37.0>:ejabberd_config:554) : Error reading Mnesia database spool files:
The Mnesia database couldn't read the spool file for the table 'config'.
ejabberd needs read and write access in the directory:
   /var/lib/ejabberd
Maybe the problem is a change in the computer hostname,
or a change in the Erlang node name, which is currently:
   ejabberd@m
Check the ejabberd guide for details about changing the
computer hostname or Erlang node name.


=INFO REPORT==== 2016-03-19 01:45:05 ===
    application: ejabberd
    exited: {bad_return,{{ejabberd_app,start,[normal,[]]},
                         {'EXIT',"Error reading Mnesia database"}}}
    type: temporary

=ERROR REPORT==== 2016-03-19 01:47:56 ===
E(<0.37.0>:ejabberd_config:554) : Error reading Mnesia database spool files:
The Mnesia database couldn't read the spool file for the table 'config'.
ejabberd needs read and write access in the directory:
   /var/lib/ejabberd
Maybe the problem is a change in the computer hostname,
or a change in the Erlang node name, which is currently:
   ejabberd@m
Check the ejabberd guide for details about changing the
computer hostname or Erlang node name.


=INFO REPORT==== 2016-03-19 01:47:56 ===
    application: ejabberd
    exited: {bad_return,{{ejabberd_app,start,[normal,[]]},
                         {'EXIT',"Error reading Mnesia database"}}}
    type: temporary

**Comment by badlop** [comment]
So, you get those problems when trying to do step 5. Let's ensure all went well until there:
* The directory /var/lib/ejabberd must exist
* That directory must not have Mnesia files (*.DAT, *.DCD...)
* The system account that runs ejabberd must have read and write access to that directory, so that ejabberd can create new Mnesia files

**Comment by netknokt** [comment]
Ok.

Looks god on all three points I think:

> root@m:/var/lib/ejabberd# ls -al
> total 16
> drwx------  3 ejabberd ejabberd 4096 Mar 26 00:07 .
> drwxr-xr-x 57 root     root     4096 Dec  9 19:48 ..
> -r--------  1 ejabberd ejabberd   20 May 15  2011 .erlang.cookie
> drwxr-xr-x  2 root     root     4096 Mar 26 00:07 oldfiles

**Step 5:**
> root@m:/var/lib/ejabberd# ejabberdctl start
The node ejabberd@m is started with status: started
ejabberd is not running in that node
Check for error messages: ejabberd.log
or other files in that directory.
>
> Error in ejabberd ctl process: 'error' badarg
root@m:/var/lib/ejabberd#

**Comment by badlop** [comment]
Oh, then now I ran out of ideas where the problem can be. So I'll give you two different ideas.

First:

> I'm trying to change the hostname of the host and following the instructions here 

If I remember correctly, ejabberd 2.1.11 already supported the option ERLANG_NODE in the file ejabberdctl.cfg. This would allow you to coninue running ejabberd with a node name completely unrelated to whatever hostname your machine may have. By setting this option to the old no name, you can change your machine hostname as much as you want, because erlang will read that option anyway.

So, you can try to put the old Mnesia spool files back in the path, and set the old nodename in that file, and start ejabberd.

Second:

Make a backup for all your ejabberd files (Mnesia spool files, configuration files...), then uninstall ejabberd, make sure all the files are removed, then install ejabberd from zero, start it, check it runs correctly. Then put back your old mnesia spool files, and try to start ejabberd. If it complains, set the option ERLANG_NODE that i mentioned in First.

**Comment by netknokt** [comment]
> If I remember correctly, ejabberd 2.1.11 already supported the option ERLANG_NODE in the file **ejabberdctl.cfg**. This would allow you to coninue running ejabberd with a node name completely unrelated to whatever hostname your machine may have. By setting this option to the old node name, you can change your machine hostname as much as you want

Thanks, that worked. 

ejabberdctl.cfg didn't exist, so I created it and added the one line:
ERLANG_NODE=ejabberd@mail

**Comment by badlop** [comment]
The old mnesia db files keeps old user accounts if you used default configuration.

**Comment by sarthak875** [comment]
Failed RPC connection to the node ejabberd@localhost: nodedown
I am getting this error

**Comment by sarthak875** [comment]
i am using windows10 and latest version of ejabberd 18 plss help me out from this

**Comment by maxmaxmaximus2** [comment]
@sarthak875 

ejabberd 18 is not correct program
just dont use ejabberd
I spent 3 days on this shit
