### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1026]
> What version of ejabberd are you using?
15.04

> What operating system (version) are you using?
Fedora 22

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
TLS error = SSL_do_handshake failed: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

TLS error = SSL_do_handshake failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

randomly on random clients

Conf file
certfile: "/opt/ejabberd/ssl/lighttpd.pem"
    starttls: true

   protocol_options:
       - "no_sslv3"
       - "no_tlsv1"
       - "no_sslv2"
       - "no_tlsv1_1"

starttls_required: true

> was the unexpected behavior? What was the expected result?

**Comment by rraptorr** [comment]
You have disabled TLS 1.0 and TLS 1.1. The only available protocol on your servers is TLS 1.2.
Many clients still do not support TLS 1.2 (especially on older Windows) and can only talk TLS 1.0.
Given that the errors are exactly the result of your configuration. If you really want to support only TLS 1.2 you must accept that many clients will not connect to your server. Otherwise reenable TLS 1.0 and TLS 1.1 (SSL 3.0 should be left disabled).

**Comment by nOmi7** [comment]
Even when I don't keep no tls 1.0 and tls 1.1 I get the error also i have my custom client which uses tls 1.2 no other client connects to my system apart from what we have developed

**Comment by rraptorr** [comment]
You are aware that if your server is accessible over the Internet then anyone can try to connect? There are tons of bots, scanners and other stuff on the Internet that will eventually try to connect to your server and they will try various SSL/TLS versions (scanning whole IPv4 address space is nowadays not uncommon).

If your server is not accesible over the Internet then make a traffic dump (tcpdump/wireshark) and see what is trying to connect and using which version of SSL/TLS.

**Comment by nOmi7** [comment]
Yes this is my companies internal network so only we are allowed .
I do getInstance("TLS") on my java client so that only TLS , TLSv1  ,  TLSV1.1 ,TLSV1.2  can be used.
and then changed config to 

protocol_options:
- "no_sslv3"
- "no_sslv2"

Still i see the issue randomly . moreover i tried to check tcp dump and i see client is using TLS 1.2 
but randomly i get this issue and the same client which gets this issue can later connect

**Comment by rraptorr** [comment]
Well, no more ideas. Provide a traffic dump of a failed connection attempt, and maybe this will shed some light.

**Comment by mremond** [comment]
Please, reopen the issue if you have more information to provide.
