### ISSUE TITLE
ejabberd_app.erl doesn't need to be a process. Why register as a local process named ejabberd?

### ISSUE THREAD

**Issue by wudixiaotie** [processone/ejabberd#1028]
> What version of ejabberd are you using?

Lastest

> What operating system (version) are you using?
Ubuntu 15.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberd_app.erl doesn't need to be a process. Why register as a local process named ejabberd?

**Comment by zinid** [comment]
This probably can be removed now. Back in the days there was drivers initialization so this process was kept to get drivers running.
