### ISSUE TITLE
Presence not sent 

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1030]
> What version of ejabberd are you using?
15.04

> What operating system (version) are you using?
Fedora 22

> How did you install ejabberd (source, package, distribution)?
Soruce

> What did not work as expected? Are there error messages in the log? 
NA
> What was the unexpected behavior? What was the expected result?
NA 

I have this scenario . my current users in DB are 
A,B,C system is up and running 
I registerd a new user K and subscribed user A , B , C 
So now Rosterusers table  of K has 
F -- NULL
T -- A, B , C 
and A, B C 's rosters have K as F.

When this is the case and no privacy is set i.e K's prence updates are open to A, B , C still 
they do not get the available presence updates.

After checking code i see that during first broadcast from C2S it creates a list of pres_a for user's state.

In this it addes all the users which meets privacy from Pres_f  of the users state  and DOES NOT add all l the users which meets privacy from Pres_T  so at the end pres_a contains nothing for K and it does not send the pres updates.

When I add K to roster of A,B,C 
Updates are sent properly.

Is there anything that i am doing wrong or missing ? basically i want pres to users who have subscribme tough i have not subscribed to them.

**Comment by zinid** [comment]
It's really hard to understand what all that means.
1. Why do you need so many users (A, B and C) just to check interaction with K?
2. What does "prence updates are open to" mean?
3. Why are you messing with pres_* values?
And finally, you didn't describe the problem you have. At least I don't understand what your problem is.

**Comment by nOmi7** [comment]
Ok sorry @zinid  for being unclear,  I was wrong r, ead some docs I am clear now
