### ISSUE TITLE
mod_mam service unavailable error

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1032]
> What version of ejabberd are you using?

ejabberd 15.07

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
mod_mam is enabled with the following configuration
 mod_mam:
    default: always
    db_type: odbc
> was the unexpected behavior? What was the expected result?
When i query for messages i got error as service-unavailable error code 503

But in mysql database messages are stored

**Comment by mremond** [comment]
Hard to give any info as indentation is wrong. I am even not sure that mod_mam is properly in modules section. Moreover, you would need to show the query you are making, as it could be wrong as well.

**Comment by vijayaa** [comment]
mod_mam is properly configured. Messages are stored in database.But when i send the following iq i am getting error as service unavailable

`<iq type='set' id='juliet1'>
  <query xmlns='urn:xmpp:mam:1' queryid='f27' />
</iq>'

**Comment by mremond** [comment]
You should upgrade ejabberd. This was fixed in version 15.10 I think, but it is probably best to get to latest version directly.

**Comment by mremond** [comment]
I am closing the ticket as the issue was already fixed. Please, reopen it if you still have issues with latest version.
