### ISSUE TITLE
Setup for ejabberd + Riak

### ISSUE THREAD

**Issue by clintonm9** [processone/ejabberd#1043]
ejabberd-16.02-0.x86_64.rpm
CentOs 7.2 1511
riak-2.1.3-1.el7.centos.x86_64.pm

I have done a lot of searching online about getting ejabberd and riak working together. After a lot of digging I think I have it working somewhat, but still have questions?

First off I have riak on a different server than ejabberd. It looks like erlang is a slightly different version. 

The documentation is a little outdated (https://docs.ejabberd.im/admin/guide/configuration/)

```
Second, Riak should be pointed to ejabberd Erlang binary files (*.beam). As described in Install, by default those are located in /lib/ejabberd/ebin directory. So you should add the following to /etc/riak/vm.args:
```

I had to do this instead

```
 cat /etc/riak/advanced.config 
[
{riak_kv, [{add_paths, ["/opt/ejabberd/lib/ejabberd-16.02/ebin"]}]}
].
```

I installed ejabberd rpm on the riak server to be able to point to the ebin dir. 

I wont explain everything I did, but I followed most of the instruction from the documentation. 
This is what I added to the ejabberd.yml

```
### Riak
riak_server: "10.200.0.6"
#riak_port: 8098
riak_pool_size: 10
riak_start_interval: 30

default_db: riak
```

I am thinking the default_db should make ejabberd use Riak for all modules.

Doing the following I can see some of the buckets ejabberd has created

```
curl http://10.200.0.6:8098/buckets?buckets=true  ]#       
{"buckets":["contributors","passwd","__riak_client_test__","muc_room","caps_features","last_activity","welcome"]}[root@nbadeveast hitcents]# 
```

But I can not look inside the buckets without getting a utf8 error:

```
curl -XGET -i http://10.200.0.6:8098/buckets/muc_room/keys?keys=true
HTTP/1.1 500 Internal Server Error
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.8 (that head fake, tho)
Date: Wed, 30 Mar 2016 21:47:44 GMT
Content-Type: text/html
Content-Length: 1103

<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,{exit,{ucs,{bad_utf8_character_code}},
             [{xmerl_ucs,from_utf8,1,[{file,"xmerl_ucs.erl"},{line,185}]},
              {mochijson2,json_encode_string,2,
                          [{file,"src/mochijson2.erl"},{line,200}]},
              {mochijson2,'-json_encode_array/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,171}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
              {mochijson2,json_encode_array,2,
                          [{file,"src/mochijson2.erl"},{line,173}]},
              {mochijson2,'-json_encode_proplist/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,181}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
              {mochijson2,json_encode_proplist,2,
...
```

So two questions:
1) when I logout and back into the ejabberd server the chat history in a persistent room stays. Once I restart the server the chat history no longer their.
2) is there some way to make sure all of the did is really being saved into riak and not using the local Mnesia db?

Thanks!

**Comment by ratnagithub** [comment]
Me too getting the same error when trying to see the data added by Ejabberd. But looks like data is getting saved in Riak. Its just that we are not able to see. How can we avoid this error and view data?

**Comment by cromain** [comment]
closing old thread. Please create a new thread if you have issues with 17.07 with riak.
