### ISSUE TITLE
How to get timestamp in the message packet from server

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1045]
> What version of ejabberd are you using?
15.07

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by mremond** [comment]
Not sure what you want to do, but server does not add timestamp to message unless it is delayed message (i.e. Message stored in offline table and resend on login).

**Comment by vijayaa** [comment]
we need to do localization on the client. If we receive timestamp in the message packet we can convert it to local time zone and display

**Comment by badlop** [comment]
Either you modify the client, so it adds a timestamp to each message it sends. Or modify ejabberd soure code, to add a timestamp to each message it routes.

**Comment by mremond** [comment]
To complete the answer: Timestamp is only added by ejabberd when needed, that is on delayed message. When messages are transferred in real time, client does not need a timestamp. The timestamp is just the reception time.
As Badlop says, if you absolutely need a timestamp on all messages, you have to have either the client or the server add it. In all cases, it will be custom.
