### ISSUE TITLE
Dependency not available with make

### ISSUE THREAD

**Issue by Doemela** [processone/ejabberd#1047]
> What version of ejabberd are you using?
ejabberd 15.11.87
Erlang/OTP 18 [erts-7.1] [source-2882b0c] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

> What operating system (version) are you using?
Operating system 	Ubuntu Linux 14.04

> How did you install ejabberd (source, package, distribution)?
git clone git://github.com/processone/ejabberd.git

> What did not work as expected? Are there error messages in the log? What
On make:
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
Dependency not available: fast_tls-.* ({git,
                                        "https://github.com/processone/fast_tls",
                                        {tag,"1.0.1"}})
Dependency not available: stringprep-.* ({git,
                                          "https://github.com/processone/stringprep",
                                          {tag,"1.0.2"}})
Dependency not available: fast_xml-.* ({git,
                                        "https://github.com/processone/fast_xml",
                                        {tag,"1.1.3"}})
Dependency not available: stun-.* ({git,"https://github.com/processone/stun",
                                       {tag,"1.0.1"}})
Dependency not available: fast_yaml-.* ({git,
                                         "https://github.com/processone/fast_yaml",
                                         {tag,"1.0.3"}})
Dependency not available: p1_oauth2-.* ({git,
                                         "https://github.com/processone/p1_oauth2",
                                         {tag,"0.6.1"}})
Dependency not available: p1_xmlrpc-.* ({git,
                                         "https://github.com/processone/p1_xmlrpc",
                                         {tag,"1.15.1"}})
Dependency not available: luerl-.* ({git,"https://github.com/rvirding/luerl",
                                     {tag,"v0.2"}})
Dependency not available: ezlib-.* ({git,
                                     "https://github.com/processone/ezlib",
                                     {tag,"1.0.1"}})
Dependency not available: iconv-.* ({git,
                                     "https://github.com/processone/iconv",
                                     {tag,"1.0.0"}})
ERROR: compile failed while processing /root/sources/ejabberd: rebar_abort
make: *** [src] Error 1

**Comment by prefiks** [comment]
You may want to call 'make deps' or 'rebar get-deps'. That first one should be called when you do execute 'make' for first time, but maybe there was some kind of problem with it?
