### ISSUE TITLE
[16.03] Using srg_get_info through xmlrpc is not obvious to parse.

### ISSUE THREAD

**Issue by CyrilPeponnet** [processone/ejabberd#1048]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Centos7

> How did you install ejabberd (source, package, distribution)?

RPM from processone.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

With 16.02 and before, getting `srg_get_info` through xmlrpc was returning something like:

```
{'information': [{'key': 'name'}, {'value': '"All Users"'}]}
{'information': [{'key': 'displayed_groups'}, {'value': '["All Virtual Machines","All Hypervisors"]'}]}
{'information': [{'key': 'description'}, {'value': '"Automatic group"'}]}
```
Which was _kind_ of easy to split into a list in python.

Since 16.03 the same request give me:

```
{'information': [{'key': 'name'}, {'value': '["\\"All Users\\""]'}]}
{'information': [{'key': 'displayed_groups'}, {'value': '[[91,["\\"All Virtual Machines\\"",44,"\\"All Hypervisors\\""],93]]'}]}
{'information': [{'key': 'description'}, {'value': '["\\"Automatic group\\""]'}]}
```

Which is a mess to parse and also very hard to ensure back compatibility with older ejabberd versions.

Is that expected?

Not an expert but could be related to https://github.com/processone/ejabberd/commit/16c1b9a5c2a6c45ee0724830fa8c38a8a6e5e833 @badlop

**Comment by mremond** [comment]
I think, no, it should not be escaped that way. We will have a look before next release. Thanks !

**Comment by badlop** [comment]
Let's see if this one solves the formatting better.
