### ISSUE TITLE
mod_irc: when a user changes its nick, it gets lost

### ISSUE THREAD

**Issue by iwalkalone69** [processone/ejabberd#1050]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

jessie-backports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When a nick changes, the new nick is not inserted in the stanza and future nick changes from the same user, are only sent with role information and without nicks.

I've managed to fix the stanza the first time user changes its nick with:

```
diff --git a/src/mod_irc_connection.erl b/src/mod_irc_connection.erl
index 45daa21..8234c9b 100644
--- a/src/mod_irc_connection.erl
+++ b/src/mod_irc_connection.erl
@@ -1369,7 +1369,7 @@ process_kick(StateData, Chan, From, Nick, String) ->

 process_nick(StateData, From, NewNick) ->
     [FromUser | _] = str:tokens(From, <<"!">>),
-    [Nick | _] = binary:split(NewNick, <<":">>),
+    [Nick | ToNick] = binary:split(NewNick, <<":">>),
     NewChans = dict:map(fun (Chan, Ps) ->
                                case (?SETS):is_member(FromUser, Ps) of
                                  true ->
@@ -1406,7 +1406,7 @@ process_nick(StateData, From, NewNick) ->
                                                                                                {<<"role">>,
                                                                                                 <<"participant">>},
                                                                                                {<<"nick">>,
-                                                                                                Nick}],
+                                                                                                ToNick}],
                                                                                           children
                                                                                               =
                                                                                               []},
```

But only works for the first time. I think the problem is few lines after in this code:

```
                                      (?SETS):add_element(Nick,
                                                          remove_element(FromUser,
                                                                         Ps));
```

I suspect the old nick (FromUser) is removed correctly, but Nick is not added. I believe the solution is to create a new object like FromUser but replacing nick with ToNick but I'm not really good with erlang. Can anyone help me?

Thanks.

**Comment by badlop** [comment]
Maybe this problem is similar to the other ticket, and can be solved simply this way?
```
-  [Nick | _] = binary:split(NewNick, <<":">>),
+  [_, Nick] = binary:split(NewNick, <<":">>),
```

**Comment by iwalkalone69** [comment]
It only works for the first nick change of the user. Since the first time, you loose the user. You stop receiving anything from him.

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
