### ISSUE TITLE
OpenSSL on Mac OS X

### ISSUE THREAD

**Issue by e-t-h-a-n** [processone/ejabberd#1055]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Mac OS X 10.11.4

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My old `ejabberd-16.01` installation used my system's openssl libraries (OpenSSL 0.9.8zh) and I couldn't get TLSv1.1 or TLSv1.2 support on `ejabberd`. I uninstalled `ejabberd-16.01` and tried to upgrade to `ejabberd-16.03` while trying to get it to use my version of OpenSSL (1.0.2g) installed in `/usr/local/ssl`. I read about the issue [here](https://github.com/processone/ejabberd/issues/393), but having compiled with `make CFLAG="-I/usr/local/ssl/include" LDFLAGS="-L/usr/local/ssl/lib"` my `ejabberd` installation will not start. Thanks in advance for any help. I can confirm that both `
lib/p1_tls-1.0.0/priv/lib/p1_sha.so` and `lib/p1_tls-1.0.0/priv/lib/fast_tls_drv.so` have no dependancies on any system OpenSSL shared libraries. I also tried with `ejabberd-16.01` but with the same result.

My log: [ejabberd.log.txt](https://github.com/processone/ejabberd/files/207878/ejabberd.log.txt)

**Comment by mremond** [comment]
Your compilation probably was incorrect, but you did not what the log of the compilation.
For the record, I am using ejabberd on OSX every day without any issue, so this must be some issue specific to your environment. Please provide more details.

**Comment by e-t-h-a-n** [comment]
Fixed by installing OpenSSL with shared libraries and symlinking them into `/usr/local/lib` (along with headers into `/usr/local/include`)
