### ISSUE TITLE
muc messages are not stored in archive. mod_mam enabled

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1058]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**mod_mam and mod_muc  modules are configured as below**
 mod_mam:
    default: always
    db_type: odbc
mod_muc:
 history_size: 0
    default_room_options:
      persistent: true
      logging: false
      mam: true
      max_user_conferences: 50
    db_type: odbc

muc messages are not stored in archive table in database

**Comment by zinid** [comment]
I think you have indentation issue.

**Comment by vijayaa** [comment]
in configuration file indentation is correct 
mod_muc: 
    access: all   
    history_size: 0
    default_room_options:
      persistent: true
      logging: false
      mam: true
      max_user_conferences: 50
    db_type: odbc

**Comment by zinid** [comment]
How do you know they are not stored? `archive` SQL table is empty?

**Comment by vijayaa** [comment]
yes

**Comment by vijayaa** [comment]
mod_mam is enabled and normal p2p messages are stored in archive table. i am using mysql database. mam is set to true under default_room_options: 
But messages are not stored in archive table. i am not finding any error in the eajbberd.log
