### ISSUE TITLE
The MySQL database script of last version 16.03 is not compatible

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1059]
### What version of ejabberd are you using?
16.03

### What operating system (version) are you using?
Debian Jessie

### How did you install ejabberd (source, package, distribution)?
Docker Container: rroemhild/ejabberd

### What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?
The mysql.sql script is incompatible with the last MySQL version (5.7.11) with errors like setting a 'DEFAULT' value to types like 'TEXT' which is not allowed. And also more errors.

Try to review this MySQL script to make it compatible, please.

Thanks!

**Comment by mremond** [comment]
Did you try to adapt the script to your need ? Do you have some changes that you want us to review ?

**Comment by mremond** [comment]
Note: Despite the name ERROR, it should be a warning.

**Comment by joanlopez** [comment]
Not, in my case there is an error, not a warning.

Did you try to run this SQL script on a MySQL database?

**Comment by prefiks** [comment]
I pushed change that did remove that warning/error for me.

**Comment by prefiks** [comment]
That was commit b4739396ec785591feb3d029d1529e064eba5635

**Comment by mremond** [comment]
@joanlopez Yep, we did test that against a mySQL database and it was a warning for us.

Anyway, we changed the type to restrict it more.
