### ISSUE TITLE
Ejabberdctl overrides HOME environment variable

### ISSUE THREAD

**Issue by jkingsbery** [processone/ejabberd#106]
It's not clear why, but the ejabberdctl overwrites the HOME environment variable with the SPOOLDIR value. This means that there is no reliable way to get the actual HOME directory of the user running the process. This seems superfluous because the SPOOLDIR itself could be used instead.

**Comment by badlop** [comment]
Since this commit, ejabberdctl does not override HOME. I guess that solves this issue.
https://github.com/processone/ejabberd/commit/40ef406ec7412f7a81240d1e7567953ca11ffe43#diff-24ee795aed79c4b023e5d12276c97c80L108

**Comment by jkingsbery** [comment]
cool, thanks.
