### ISSUE TITLE
One or two sql_pool connection process does not restart properly after a crash caused by query timeout or connection closed.

### ISSUE THREAD

**Issue by everimbaq** [processone/ejabberd#1061]
> What version of ejabberd are you using?
Ejabberd-14.12

> What operating system (version) are you using?
centos 6.5

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
One or two sql_pool connection process does not restart properly after a crash caused by
query timeout or connection closed.
error log:
    "2016-03-21 16:09:22.594 [error] <0.19878.1217>@ejabberd_odbc:log:583 p1_mysql_conn: Received close signal, exiting."
    "{timeout,{p1_fsm,sync_send_event,[<0.379.0>,{sql_cmd,{sql_transaction,#Fun<mod_stats.0.20785778>},{1458,547894,547662}},60000]}} in p1_fsm:sync_send_event/3 line 237"

 I installed ejabberd-14.12 from  source with configure "--enable-mysql", and use mysql.
Mysql server sometimes become too slow because bad use by others(I share mysql with others),
and sql_pool process crashes. when mysql server recovers, most process get back to normal state.
But one or two of them does not automaticlly restart, and still exist in sql_pool, sql query to the process always return a timeout.
Did my usage caused some bug of erlang mysql lib?

**Comment by mremond** [comment]
Why do you say they do not restart properly ? They are supervised and should be restarted by the supervisor.

Moreover, you should probably try on 16.03 and report as many changes has been made since ejabberd 14.12.

**Comment by everimbaq** [comment]
I found the process pid in the sql_pool table, and the process is alive. but all ejabberd_odbc:sql_query/2 
calls to the process fail (because the process is not connected to mysql server).

I didn't upgrade ejabberd because we had developed our own features on 14.12 and not so  compatibile with new version.

**Comment by karlmendes** [comment]
Hi, do you know if has a rule of pool_connections x users ? Say this because i have 20 virtual hosts on my server, its overload mysql connections and down many times, has different count users in this virtual hosts.

**Comment by mremond** [comment]
@karlmendes You would have queries queued and delay. If queue becomes too big, queries are dropped. It is better to size your database properly.

**Comment by HoneyShyam** [comment]
Hi There,
I am getting the issue with sql connection 
[error] <0.513.0>@ejabberd_sql:log:910 p1_mysql_conn: init error 1045: "#28000Access denied for user 'root'@'localhost' (using password: YES)"
2016-10-06 16:20:14.608 [info] <0.375.0>@ejabberd_sql:connecting:301 mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds

Please help how to fix this asap.

Thanks
Shyam

**Comment by marinakr** [comment]
@HoneyShyam probably you have no user 'root'@'localhost' with password from your ejabberd.yml

**Comment by marinakr** [comment]
@mremond I have same issue 
`18:36:09.193 [info] Application p1_mysql started on node 'nodeej@infopulse-desktop'
18:36:09.264 [error] p1_mysql_conn: Received close signal, exiting.
18:36:09.264 [error] p1_mysql_conn: Received close signal, exiting.
18:36:09.264 [info] Closing connection #Port<0.15009>: ok
18:36:09.264 [info] Closing connection #Port<0.15011>: ok
18:36:09.264 [error] p1_mysql_conn: Received close signal, exiting.
18:36:09.265 [error] p1_mysql_conn: Received close signal, exiting.
18:36:09.265 [info] Closing connection #Port<0.15010>: ok
18:36:09.265 [info] Closing connection #Port<0.15008>: ok
18:36:09.265 [error] p1_mysql_conn: Received close signal, exiting.
18:36:09.265 [info] Closing connection #Port<0.15012>: ok
`
with ejabberd 16.06 on ubuntu, user 'ejabberd'@'localhost' with password 'ejabberd' exists and I can check it by connection via `mysql -u ejabberd -D ejabberd -h localhost -p`
Mysql logs: `171003 18:36:09 [Warning] Aborted connection 201 to db: 'ejabberd' user: 'ejabberd' host: 'localhost' (Got an error reading communication packets)
`
