### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1062]
>What version of ejabberd are you using?
15.04

>What operating system (version) are you using?
Fedora 22

>How did you install ejabberd (source, package, distribution)?
source

I want the updated state for self how can i get it ?
for eg .
User requested add user to roster -   using Userstate1 - adds user to rosters -> mod_roster send sync event for {broadcast for roster change } -  it then updates the userstate1 to Usersate2 how can i get the userstate 2  while on the same call ?

**Comment by mremond** [comment]
I have no idea what you are trying to achieve, sorry.

**Comment by nOmi7** [comment]
@mremond  when i  do ejabberd_c2s:get_subscribed(self())  it does not get me the result it just timeouts i wanto to get the updated state for self()

**Comment by mremond** [comment]
I already replied on your other ticket. You are doing a sync call on a process from a process itself. This cannot work, as it is just a deadlock. You are in a single thread context, you simply cannot do that.

**Comment by nOmi7** [comment]
thanks @mremond  i saw the reply however so can i achieve it or its impossible  i want the updated state ?

**Comment by weiss** [comment]
I don't think the ejabberd bug tracker is a good place to get into Erlang programming.  Such questions are really not specific to ejabberd at all.

**Comment by nOmi7** [comment]
@weiss  Sorry will take care of this going forward
