### ISSUE TITLE
16.03 anonymous login request responds with not-authorised

### ISSUE THREAD

**Issue by paradisaeidae** [processone/ejabberd#1063]
> What version of ejabberd are you using?
16.02 and 16.03

> What operating system (version) are you using?
Linux

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
16.02 responds with anonymous auth method with a random jid and valid session.
16.03 responds with not-authorised.

**Comment by mremond** [comment]
I think this should already be fixed in current code (HEAD of master branch).

**Comment by paradisaeidae** [comment]
Confirmed fixed in master.
Thanks!
