### ISSUE TITLE
mod_mam and messages limit

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1065]
Could You add an option to limit max MAM messages per user (just like it is in mod_offline and access_max_user_messages)? I know that I can delete old mam messages by using delete_old_mam_messages commad BUT some user can send spam and 2GB mnesia database limit is exceeded in short time.

**Comment by weiss** [comment]
I have [a patch][1] that adds an access rule to limit the number of archive messages per user.  If the limit is exceeded, `mod_mam` stops storing messages for that user.

But do we really want that?  MAM usage will stop working and people won't understand why.  If a `delete_old_mam_messages` cron job kicks in, users might end up with "holes" in their archives.

The `mod_mam_mnesia` module removed the oldest message of that user before storing the new one when the limit was reached.  But when Mnesia is used with `mod_mam`, this operation is really (too) expensive.

[1]: https://github.com/weiss/ejabberd/commit/71cfeffd82985ff17881c8c414412c7ebeceb8f8

**Comment by beherit** [comment]
For me this patch is really needed. Yesterday mod_mam stop saving new messages because one of user send a lot of messages. Command delete_old_mam_messages doesn't work in that situations.

**Comment by beherit** [comment]
It would be great that this patch worked like it is in mod_mam_mnesia.

**Comment by weiss** [comment]
> It would be great that this patch worked like it is in mod_mam_mnesia.

With the current layout of the Mnesia table, you'd have to read all messages of a user into memory and then write all but one back just to delete his oldest one, so that's not an option.

Maybe we could log an `[info]` message whenever a message isn't stored due to the limit being reached (so that the admin will notice), and then also provide a `delete_user_mam_messages` command (so that the admin can purge the user's messages).

**Comment by beherit** [comment]
So current layout of the Mnesia table must be changed.

Provide another command? I looking for some automatic solution, I don't have time to look at log many times in a day.

**Comment by weiss** [comment]
> So current layout of the Mnesia table must be changed.

I won't implement this myself then, but I'll happily review any patches.

> Provide another command? I looking for some automatic solution, I don't have time to look at log many times in a day.

My idea was to use provide this as a last resort protection against message floods, not as a day-to-day admin task.  If a user runs into this case and complains, the admin has a chance to figure out the issue and resolve it.

**Comment by beherit** [comment]
Again my mam messages database grown up to 2G :/ I added couple weeks ago command 'ejabberd delete_user_mam_messages 21' to cron and I don't know why the problem apper again.

**Comment by weiss** [comment]
I'd suggest switching to SQL storage for MAM if you run into such trouble repeatedly.  Mnesia is really not designed for storing large amounts of data.

**Comment by beherit** [comment]
@weiss I don't have a lot of messsages! Only 17,130 messages and database have 2gb! There is some bug...

**Comment by beherit** [comment]
I try to delete mam messages older than 14 days, then older than 7 and when I try delete older than 2 days I have error:
```
root@xxx:/var/lib/ejabberd# ejabberdctl delete_old_mam_messages all 2
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{lists,foreach,
                    [#Fun<mod_mam.9.6253463>,
                     {error,{{bad_object,read_buckets},
                             "/var/lib/ejabberd/archive_msg.DAT"}}],
                    [{file,"lists.erl"},{line,1336}]},
             {mod_mam,'-delete_old_messages/2-fun-0-',4,
                      [{file,"src/mod_mam.erl"},{line,374}]},
             {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
             {mod_mam,delete_old_messages,2,
                      [{file,"src/mod_mam.erl"},{line,369}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,410}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,295}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,220}]}]
```

**Comment by weiss** [comment]
> I don't have a lot of messsages! Only 17,130 messages and database have 2gb!

How do you know the number of messages given your `archive_msg` table is corrupt?

> I try to delete mam message

Once you reached the 2 GB limit, the table must be recreated.

**Comment by beherit** [comment]
How to repair database? The namber of messages is shown in WebAdmin. I try to restart ejabberd when database reached  2GB and nothing has changed. Then I try to delete messages older than 21, older than 14 and finally older than 7 days. When I try to delete older than < 7 days I have error. Ok, I restarted ejabberd once again and now database have ~14MB and 15,841 messages stored.

**Comment by beherit** [comment]
I see only 1 error in logs:
```
2016-05-04 10:30:31.982 [error] <0.29308.5>@gen_iq_handler:process_iq:129 {{case_clause,{error,{{bad_object,read_buckets},"/var/lib/ejabberd/archive_msg.DAT"}}},[{lists,keysort,2,[{file,"lists.erl"},{line,752}]},{mod_mam,select,9,[{file,"src/mod_mam.erl"},{line,977}]},{mod_mam,select_and_send,10,[{file,"src/mod_mam.erl"},{line,922}]},{gen_iq_handler,process_iq,6,[{file,"src/gen_iq_handler.erl"},{line,128}]},{gen_iq_handler,handle_info,2,[{file,"src/gen_iq_handler.erl"},{line,172}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```

**Comment by beherit** [comment]
P.S. I don't have a lot of users that use mam, I have problem with mam database after switching from mod_mam_mnesia to mod_mam.

**Comment by weiss** [comment]
> How to repair database?

Open an `ejabberdctl debug` shell and enter the following calls (don't forget the trailing dot, and press `Ctrl`+`C` twice when you're done):

    mnesia:delete_table(archive_msg).
    mnesia:create_table(archive_msg, [{disc_only_copies, [node()]}, {type, bag}, {attributes, [us,id,timestamp,peer,bare_peer,packet,nick,type]}]).

> I have problem with mam database after switching from mod_mam_mnesia to mod_mam.

There was a lot of code in `mod_mam_mnesia` that tried to work around the limitations of Mnesia for this sort of use case.  I have no plans to add such workarounds to `mod_mam`.  The recommended solution is to switch to SQL storage.

**Comment by beherit** [comment]
@weiss I have problem with run ejabberdctl debug. Anyway, on my server I have ~1400 registered users but only 45 have enabled MAM. To reach 2 GB limit is need to storage a lot of messages, maybe even 1 000 000? This 45 users can't send such amount of messages, it's imposible! Somewhere in mod_mam is some error that damages the database. Yes, I can switch to SQL but take a look at jabber.at - they using mnesia and have many registered users and I think they have storage a lot of MAM messages.

**Comment by weiss** [comment]
> Somewhere in mod_mam is some error that damages the database.

I think we can safely say that (a) you reached the 2 GB limit and that (b) we both have no idea why.  It may be some client(s) suddenly filling your archives, or some bug in `mod_mam`, or some bug elsewhere in ejabberd, or some bug in the Erlang version you're using.  If you find a way to reproduce the issue, we may be able to debug it.  Otherwise, I'm not sure what we can do for you; except for telling you how to avoid the issue in the future.

**Comment by beherit** [comment]
Okay, I will try to reproduce the issue. Maybe to resolve this issue can help the archive_msg.DAT file? I can send it to You.

**Comment by weiss** [comment]
> Maybe to resolve this issue can help the archive_msg.DAT file? I can send it to You.

Well, that may contain lots of sensitive data of course.  You might get a broad idea of the contents by just running `strings archive_msg.DAT | less`.

**Comment by beherit** [comment]
I checked the ``archive_msg.DAT`` as You wrote and I see many messages from this same user, so I think the 2 GB limit was really reached... That You can see it is very important to add limitation that was in ``mod_mam_mnesia``. This limitation could be disabled by default. Or maybe is the way to block MAM for some users?

**Comment by weiss** [comment]
> Or maybe is the way to block MAM for some users?

Not currently, but I could create a variant of my [original patch][1] that allows for simply enabling/disabling MAM storage per user (or for everyone) with an access rule.  I think that would address other use cases as well (e.g., I remember someone wanting to enable MUC MAM without allowing user archives).

Apart from that, I'd suggest checking the size of the `archive_msg` table whenever a message is stored in Mnesia.  If the size exceeds, say, 1,8 GB, I'd log a `[warning]` that tells the admin to `delete_old_mam_messages` whenever a message is stored.  When it exceeds 1,9 GB, I'd stop storing messages and log a `[critical]` error message.  This would at least make sure the archive is not corrupted.

I know that other solutions may sound more appealing, but these two have the big advantage that they are relatively cheap.  The proper solution is switching to SQL storage.

[1]: https://github.com/weiss/ejabberd/commit/71cfeffd82985ff17881c8c414412c7ebeceb8f8

**Comment by beherit** [comment]
``mod_mam`` and mnesia without any limit is terrible - to block mod_mam is needed only two Android devices with installed Conversations and two account on this same server. Then just talk for a long time (~a day) across this two account...

P.S. It is possible to use mnesia but only for mod_mam SQL storage?

**Comment by weiss** [comment]
> It is possible to use mnesia but only for mod_mam SQL storage?

Yes, that will work just fine.

**Comment by beherit** [comment]
@weiss I have an idea - could You add command that will check the number of mam messages for each user and will delete oldest messages when user have more messages than we put in command attributes? E.g. user XYZ have 2100 mam messages and when we run ``delete_xxx_mam_messages 2000`` wil delete 100 messages that are oldest.

**Comment by beherit** [comment]
Again I have this same issue. Now dabaase reach 2GB when after use ``ejabberdctl delete_old_mam_messages all 14``! Before dabase have ~400MB.

**Comment by weiss** [comment]
This also happened on jabber.at again, and it looked like it was triggered by a `delete_old_mam_messages` call there as well.

I have [a patch][1] that uses [transactions][2] whenever the `archive_msg` table is modified.  From reading the Mnesia docs this should not be strictly necessary, but I can well imagine this change will nevertheless avoid that issue.

Apart from that, I have [another patch][3] that tells ejabberd to quit storing messages when the table size reach about 1.9 GiB.  But that won't help for this case where it seems like a single call trashes the table.

I'll probably push both changes if nobody objects.

[1]: https://github.com/weiss/ejabberd/commit/edc76517663acdb51b3f86bf28498534b51485b0
[2]: http://erlang.org/doc/apps/mnesia/Mnesia_chap4.html
[3]: https://github.com/weiss/ejabberd/commit/c6f010c479980787a8a21f2c1addfa3764b22533

**Comment by beherit** [comment]
@weiss thanks for the fix. But what with the main problem - setting limmit for user or/and removing messages via ejabberdctl as I wrote in https://github.com/processone/ejabberd/issues/1065#issuecomment-217660895 ?

**Comment by weiss** [comment]
> But what with the main problem - setting limmit for user or/and removing messages via ejabberdctl

The former seems to expensive to me, the latter sounds okay.  You might want to open a separate feature request for that.
