### ISSUE TITLE
compile issue when embedded ejabberd in Elixir project under linux 

### ISSUE THREAD

**Issue by sulphur** [processone/ejabberd#1066]
> What version of ejabberd are you using?
16.3

> What operating system (version) are you using?
Linux chat 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> How did you install ejabberd (source, package, distribution)?
i'm following these steps:
https://blog.process-one.net/how-to-use-ejabberd-as-an-elixir-application-dependency/

> What did not work as expected? Are there error messages in the log? What

`mix compile` fails to compile `ejabberd` dependency. There aren't any specific errors 
```
Compiled src/cyrsasl_scram.erl
Compiled src/eldap_pool.erl
Compiled src/cyrsasl_plain.erl
could not compile dependency :ejabberd, "mix compile" failed. You can recompile this dependency with "mix deps.compile ejabberd", update it with "mix deps.update ejabberd" or clean it with "mix deps.clean
 ejabberd"
==> ejapp
** (Mix) Encountered compilation errors
```

however launching the `mix compile` again is successful and my app is starting so it might be a wired `mix` issue rather that ejaberd. 

> was the unexpected behavior? What was the expected result?
the expected behaviour is the `mix compile` succeeds after the first launch.

On my OS X machine i don't have this issue

**Comment by mremond** [comment]
I followed latest up to date version of the documentation for Elixir support, found here: https://docs.ejabberd.im/developer/elixir/#embedding-ejabberd-in-an-elixir-application

and I do not have any issue.

**Comment by eathrow** [comment]
I'm having this same issue on Ubuntu Erlang/OTP 19 [erts-8.1] Elixir (1.3.3).
Ejabberd version: 16.06

`could not compile dependency :ejabberd`
`src/mod_ping.erl:32: Warning: behaviour gen_mod undefined
src/ejabberd_access_permissions.erl:32: Warning: behaviour ejabberd_config undefined
src/nodetree_tree_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd.erl:109: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
src/ejabberd.erl:143: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/http_p1.erl:156: Warning: type header() is unused
src/http_p1.erl:166: Warning: type option() is unused
src/mod_client_state.erl:31: Warning: behaviour gen_mod undefined
src/ejabberd_auth_riak.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd_auth_mnesia.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd_ctl.erl:314: Warning: variable 'AccessCommands' is unused
src/mod_mam_sql.erl: undefined parse transform 'ejabberd_sql_pt'
include/mod_offline.hrl:3: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
include/mod_offline.hrl:4: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
include/mod_offline.hrl:3: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
include/mod_offline.hrl:4: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/mod_offline_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/mod_announce_sql.erl: undefined parse transform 'ejabberd_sql_pt'
include/mod_offline.hrl:3: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
include/mod_offline.hrl:4: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/ejabberd_auth_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd_oauth_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd_service.erl:138: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/ejabberd_service.erl:144: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/mod_http_api.erl:506: Warning: function outofscope_response/0 is unused
src/mod_roster_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/sql_queries.erl: undefined parse transform 'ejabberd_sql_pt'
src/mod_vcard_xupdate_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/mod_echo.erl:175: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/mod_shared_roster_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/ejabberd_xmlrpc.erl:219: Warning: variable 'CommOpts' is unused
src/mod_muc_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/node_flat_sql.erl: undefined parse transform 'ejabberd_sql_pt'
src/extauth.erl:105: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
src/extauth.erl:106: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
src/ejabberd_s2s_out.erl:1102: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
src/ejabberd_s2s_out.erl:1108: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
include/mod_offline.hrl:3: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
include/mod_offline.hrl:4: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/cyrsasl_scram.erl:90: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/cyrsasl_scram.erl:104: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1`

However, I'm able to run it without any problems on OSX Erlang/OTP 19 [erts-8.0.2] Elixir (1.3.2).
