### ISSUE TITLE
MUC notification when clustered node goes down

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd#1068]
I'm using Ejabberd version 16.03.58 on CentOS release 6.5 (Final) built from source from GitHub.

I have a cluster of three nodes: chat1, chat2 and chat3

I have a MUC that was created on chat1 and a client joins it from chat2 or chat3.

If ejabberd on chat1 is closed down nicely the client is notified:

```
<presence from="test@conference.komogvind.dk/betatester01"
          to="betatester01@komogvind.dk/674556418344607218616468"
          type="unavailable">
<x xmlns="http://jabber.org/protocol/muc#user">
<item affiliation="none"
      role="none">
<reason>
You are being removed from the room because of a system shutdown
</reason>
</item>
<status code="332"/>
</x>
</presence>
```

This does not happen if ejabberd on chat1 dies unexpectedly such as if I use `kill -9`. In that case the client is not notified unless he explicitly tries to communicate with the room:

```
<message from="test@conference.komogvind.dk"
         to="betatester01@komogvind.dk/1559857117402131037516952"
         type="error">
<body>
test
</body>
<error code="404"
       type="cancel">
<item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
Conference room does not exist
</text>
</error>
</message>
```

It would be nice if the remaining nodes could send the presence unavailable on behalf of chat1 when they notice that it is gone.

**Comment by RobertLarsen** [comment]
...or better yet, have the MUC room stay available on the surviving part of the cluster.

**Comment by badlop** [comment]
> have the MUC room stay available on the surviving part of the cluster.

This is implemented in ejabberd Business Edition, even if it isn't explicitly mentioned anywhere in https://www.process-one.net/en/ejabberd/
