### ISSUE TITLE
mod_http_upload with virtual hosts

### ISSUE THREAD

**Issue by mapama** [processone/ejabberd#1072]
How can I use mod_http_upload with two virtual hosts?

My config is like this:

host_config:
  "first_domain.de":
    domain_certfile: "/etc/ejabberd/first_domain.pem"
  "second_domain.de":
    domain_certfile: "/etc/ejabberd/second_domain.pem"

...

    port: 5443
    module: ejabberd_http
    request_handlers:
        "": mod_http_upload
    certfile: "/etc/ejabberd/first_domain.pem"
    tls: true

...

  mod_http_upload:
    docroot: "/var/www/xmpp/upload"
    put_url: "https://@HOST@:5443"

Using I try http_upload from conversations with a JID bla@second_domain then I get a waring that the certificate does not match.

What can I do?

I am using ejabberd version 16.02 under debian jessie (backports)

Thanks very much

Patrik

**Comment by weiss** [comment]
You could

- add all host names to a single certificate, or
- use a separate IP address and a separate `ejabberd_http` listener (and certificate file) for each host name, or
- let a web server that supports SNI [proxy][1] the upload requests.

See also #773.

[1]: https://raw.githubusercontent.com/processone/ejabberd-contrib/e9a014a6cb49f723f24d33d0dcafb92b6d096c92/mod_http_upload/examples/nginx-upload.conf

**Comment by mapama** [comment]
Thank you Holger (@weiss). That helped.

Patrik

**Comment by alexander-schranz** [comment]
@weiss can you maybe give an example to have 2 listeners one on domain-one.com:5443 and second on domain-second.com:5443?

**Comment by weiss** [comment]
> can you maybe give an example to have 2 listeners one on domain-one.com:5443 and second on domain-second.com:5443?

Assuming domain-one.com has the IP address 192.0.2.1, and domain-second.com 192.0.2.2:

    listen:
      -
        module: ejabberd_http
        port: 5443
        ip: "192.0.2.1"
        tls: true
        certfile: "/etc/ejabberd/domain-one.pem"
        dhfile: "/etc/ejabberd/dh-param.pem"
        request_handlers:
          "share": mod_http_upload
      -
        module: ejabberd_http
        port: 5443
        ip: "192.0.2.2"
        tls: true
        certfile: "/etc/ejabberd/domain-second.pem"
        dhfile: "/etc/ejabberd/dh-param.pem"
        request_handlers:
          "share": mod_http_upload
      # [...]
    
    modules:
      mod_http_upload:
        docroot: "/var/www/@HOST@/share"
        put_url: "https://@HOST@:5443/share"

**Comment by alexander-schranz** [comment]
@weiss I think my problem is that I dont have 2 IPs?

**Comment by weiss** [comment]
> I think my problem is that I dont have 2 IPs?

What about the other options I mentioned [above][1]?

Alternatively, with ejabberd 16.01 and newer you can also specify a `put_url` such as `"https://domain-one.com/share/@HOST@/"` with just a single listener.

[1]: https://github.com/processone/ejabberd/issues/1072#issuecomment-210907182
