### ISSUE TITLE
persistent roles to muc users 

### ISSUE THREAD

**Issue by sulphur** [processone/ejabberd#1073]
> What version of ejabberd are you using?
16.02

> What operating system (version) are you using?
ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i', playing with moderated rooms. From what i saw there was un issuer about persisted roles for muc users 
https://support.process-one.net/browse/EJAB-1471?jql=text%20~%20%22moderated%20room%22

Are there any new on that issue ? will the roles be persistent any time soon ? or the are now and it is me who is doing something wrong ? 

best regards
Piotr

**Comment by badlop** [comment]
The situation is exactly like it was back then: in the MUC protocol, by design, affiliations are persistent and roles are temporary. The ejabberd code didn't change in that sense, and I am not aware of any plan to modify it.
