### ISSUE TITLE
Missing ejabberd.yml

### ISSUE THREAD

**Issue by thakurinbox** [processone/ejabberd#1076]
> **What version of ejabberd are you using?**
I am using ejabberd version 16.03

> **What operating system (version) are you using?**
Ubuntu 14.04

> **How did you install ejabberd (source, package, distribution)?**
I have installed it from command line. Using following command: 
`sudo apt-get install ejabberd
`

> **What did not work as expected? Are there error messages in the log?**
I want to configure it with mysql and for that I need ejabberd.yml file in ejabberd folder. I can not find this file and it was mentioned in ejabberd doc site that this file get created when we first time run ejabberd. Which I have done already. Why ejabberd.yml file is not loaded yet?

> **Was the unexpected behavior? What was the expected result?**
ejabberd.yml file should have been loaded by default when I installed ejabberd from command line.

**Comment by cromain** [comment]
if installed from our deb file, check /opt/ejabberd-16.03/conf/ejabberd.yml
else ask the ubuntu package maintainer (maybe check /etc/ejabberd/ejabberd.yml ?)

**Comment by thakurinbox** [comment]
It's not there in /etc/ejabberd/ I have been trying all different ways to install it. But using only ubuntu package manger it works. I can't find your deb file for installation. Can you provide me the link where I can download its deb file.

**Comment by cromain** [comment]
man, just check out official ejabberd download page
