### ISSUE TITLE
mod_mam retrieve archive messages

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1077]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i need to query archive messages based time and jid. i am able to retrieve those messages. 
We are using mod_multicast message also. Those messages are also stored in archive. How to query from message archive without multicast messages.

**Comment by badlop** [comment]
I think XEP-0313 does not provide anyway to perform that multicast filter, and mod_mam does not implement anything like that either.
