### ISSUE TITLE
ejabberd_c2s process didn't clear session data in some case

### ISSUE THREAD

**Issue by yzf** [processone/ejabberd#1078]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

debian 8.0

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log?

I use ejabberd for mobile app's im server, after running for a long time, I found that, the session number **keep increasing**, thought slowly. I debug into ejabberd's erlang shell, and found that **some session haven't been delete even thought the corresponding `ejabberd_c2s` process is terminate**. And there is **no error log**, it seems that those `ejabberd_c2s` terminate normally, except **leaving the session data behind**. Besides, the priority of all these sessions left behind are all `undefined`.

> was the unexpected behavior? What was the expected result?

The expected result is that `ejabberd_c2s` should delete the corresponding session data when it terminate.

---

After debug for a while, I found that there is some **logical error in the login progress**. 

Noticing that, in the commit https://github.com/processone/ejabberd/commit/a150bf8fdc8061bc60e5cb1a64a1e06f962d6a4e

the `session iq` is made to be optional, and session data is change to be created when receiving `iq bind`.

After receiving `bind iq` of the client, ejabberd create session data for it, and then send `iq result`. The problem is that, **if the connection is closed at that time, the send operation will fail**. Also,  `ejabberd_socket:send/2` will call `exit(normal)` if failed, this makes the `ejabberd_c2s` process jump into the `terminate/3` without update the `StateData`. So, **the state of this `ejabberd_c2s` process is still `wait_for_bind`, not `session_stablished`**. As a result, **it wouldn't delete its session data**.

**Comment by zhchbin** [comment]
The steps to reproduce:
```diff
--- a/src/ejabberd_c2s.erl
+++ b/src/ejabberd_c2s.erl
@@ -1150,6 +1150,9 @@ wait_for_bind({xmlstreamelement, El}, StateData) ->
                                                       children =
                                                       [{xmlcdata,
                                                         jid:to_string(JID)}]}]}]},
+                                ?INFO_MSG("Sleeping....", []),
+                                timer:sleep(30000),
+                                ?INFO_MSG("Wake up....", []),
                                 send_element(StateData3, jlib:iq_to_xml(Res)),
                                 fsm_next_state_pack(
                                   session_established,
@@ -1918,6 +1921,7 @@ terminate(_Reason, StateName, StateData) ->
                 end,
                 bounce_messages();
             true ->
+                ?INFO_MSG("Ternimate without clear up", []),
                 ok
          end
     end,
```

Use Psi+ Client to connect, when c2s process is sleeping, modify the tcp keepalive config and use `iptables` to block traffic,
```bash
$ sudo sysctl -p
net.ipv4.tcp_keepalive_time = 10
net.ipv4.tcp_keepalive_intvl = 3
net.ipv4.tcp_keepalive_probes = 5

$ sudo iptables -A INPUT -p tcp --destination-port 5222 -j DROP
```

Result:
```bash
15:34:30.478 [info] Sleeping....

(ejabberd@localhost)1> 
(ejabberd@localhost)1> 
(ejabberd@localhost)1> 15:35:00.479 [info] Wake up....
15:35:00.479 [info] Ternimate without clear up

(ejabberd@localhost)1> ejabberd_sm_mnesia:get_sessions().
[{session,{{1461,224070,221795},<0.443.0>},
          {<<"test1">>,<<"localhost">>,<<"MYPC">>},
          {<<"test1">>,<<"localhost">>},
          undefined,
          [{ip,{{192,168,114,1},55983}},
           {conn,c2s},
           {auth_module,xxx}]}]
```

**Comment by zinid** [comment]
Yes, there is clearly a problem after that commit.

**Comment by meteorzxt** [comment]
I have met the same issue with ejabberd16.04.

**Comment by yzf** [comment]
Yes, ejabberd 16.04 haven't fix this bug. And it occurs frequently especially in the mobile network. You can refer to the pull request #1083 which haven't been accepted yet and fix it by yourself.
