### ISSUE TITLE
Transfer Chat from user to another

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#1079]
Hello,

I am creating support interface using C# and ejabberd for chatting, one of its issues is that when client need support he start chatting and if the supporter cant help him, the supporter should transfer the client to other support user, is it possible in ejabberd/xmpp??

Thank you

**Comment by badlop** [comment]
There isn't such a "transfer conversarion" thing that I'm aware. You could do it manually: enable mod_mam, configure to store all conversations, and develop in your client a feature that "requests all messages from a conversation and sends them to a new contact".

But I think there's a better way:
1. configure mod_muc history_size to a big value
2. When a customer has a problem, he creates a new room
3. When a new room is created, a bored supporter joins the room manually, or gets invited to the room (the invitation system is supported by mod_muc, but it isn't send automatically, you'll have to write some code to send the invitation)
4. If the supporter wants to transfer the conversation to supporter2: sends invitation to supporter2 to the room; or leaves the room, so some other bored supporter joins it
5. When the new supporter joins the room, he gets automatically the previous conversation (thanks to history_size option)

**Comment by hassanzreik** [comment]
thank you @badlop for your support, i think about this solution and i was about to ask here if it is work, also i want to ask you what is the best c# .net framework that support these features

**Comment by badlop** [comment]
Sorry, no idea about XMPP libraries.
