### ISSUE TITLE
MUC does not destroy room after canceling initial configuration

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#1082]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Debian (wheezy)

> How did you install ejabberd (source, package, distribution)?

ejabberd-16.03-linux-x86_64-installer.run

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

According to XEP-0045 (http://xmpp.org/extensions/xep-0045.html#createroom), when creating a room, the client can either send an IQ "set" with `<x type="submit"/>` to accept the default configuration, or request a full configuration form by sending an IQ "get" with `<query xmlns='http://jabber.org/protocol/muc#owner'/>`.

However, if the full configuration form is requested, and then canceled (by sending an IQ "set" with `< type="cancel"/>`), then

> If the room owner cancels the initial configuration, the service MUST destroy the room, making sure to send unavailable presence to the room owner (see the "Destroying a Room" use case for protocol details).

However, ejabberd only acknowledges the cancel request and leaves the room in place.

**Comment by zinid** [comment]
What problem do you want to solve? Why do you need the behaviour described in the XEP? If you don't configure room as persistent it will be destroyed when you leave it anyway.

**Comment by cburschka** [comment]
Okay, I guess you're right; it's not essential. :)

**Comment by zinid** [comment]
Yes. Let's assume a user creates a room, requests the configuration, then got the phone call, "ah, ok, will configure a bit later" and closes the form. The room gets destroyed. WTF?

**Comment by cburschka** [comment]
As far as I can tell, this is because the XEP also assumes the room remains locked (in a sort of "unfinished" state) until the form has been submitted, effectively making it a required step in room creation. Of course if the server doesn't do things that way, then destroying the room on canceling doesn't make sense either.
