### ISSUE TITLE
xmpp spam still exists and no way to globally block entire domains from ejabberd.yml

### ISSUE THREAD

**Issue by kamijoutouma** [processone/ejabberd#1084]
This is more of a feature request than anything.

Recently my users and i have been getting spam from different users on the domain qip.ru (someone with the id paul.rizer and a few others)

I know that xmpp has a way for a user to block all messages from a domain https://books.google.com/books?id=ChTCQYLIDfoC&pg=PA56&lpg=PA56&dq=block+all+xmpp+messages+from+a+domain&source=bl&ots=sA9-Dmbyp1&sig=f641rdGps98hEMAWqjMbYzyOE2E&hl=en&sa=X&ved=0ahUKEwimnuDx6KPMAhVFWhoKHTXLCk0Q6AEIQjAF#v=onepage&q=block%20all%20xmpp%20messages%20from%20a%20domain&f=false

however i was hoping for a way to globally block all messages from domains like qip.ru (that is clearly listed as a comprimised node known for spam on xmpp when you google it) that could be set in ejabberd.yml.

I tried adding this domain to the "bad domains" list in ejabberd.yml however they were still able to message me and my users so im going to guess that either it doesnt work or it isnt used for that?

My ejabberd version is 16.03

I'm running Ubuntu Wily Werewolf.

**Comment by kamijoutouma** [comment]
Screenshot of the message http://i.imgur.com/Rau7f6D.png

**Comment by kamijoutouma** [comment]
screenshot of another message (different domain) http://i.imgur.com/uM1BjRk.png

**Comment by badlop** [comment]
How did you configure? I didn't test myself, but looking at the documentation, this should work:
```
acl:
  bad_servers:
    server:
      - "qip.ru"
access:
  s2s:
    bad_servers: deny
    all: allow
s2s_access: s2s
```

**Comment by kamijoutouma** [comment]
Aha thats why. I thought it would block them if i just added them to the bad servers list. The parts of the config you set are commented out and i didn't even notice them.

Thanks badlop

**Comment by zinid** [comment]
> I thought it would block them

Well, actually this will block them :) i.e. s2s won't be established with those servers

**Comment by kamijoutouma** [comment]
@badlop Just received another message even though i did what you showed. So they are still spamming me :|

**Comment by beherit** [comment]
@kamijoutouma are You reload ejabberd configuration (or restart ejabberd)? For me such ACLs works and I don't receive spam messages anymore.

**Comment by kamijoutouma** [comment]
i restarted ejabberd from ejabberdctl after making the changes

**Comment by kamijoutouma** [comment]
Should be noted that websocket and http_bind connections are enabled

**Comment by belldandu** [comment]
@badlop still receiving spam with the config you gave.

**Comment by badlop** [comment]
In my local tests, that config disables incoming and outgoing s2s connections. I login to an account in the server, then I try to discover a good server, and the ejabberd log file shows the connection attempt [1], and the response waits a second to come back. But when I try to discover the blocked server, nothing is logged, and the response is shown immediately: "Service unavailable".

Knowing what I described, try in your server Start it, login, try to discover the blocked server, and see what is logged related to that server. Notice that maybe some other user in your server may attempt to establish a conection to qip.ru, or qip.ru to you before you do it.


[1] Logged when discovering a non-blocked remote server:
```
19:02:02.483 [info] New s2s connection started <0.1082.0>
19:02:02.483 [info] Trying to open s2s connection: 80.201.75.129 -> jabber.org with TLS=false
```
