### ISSUE TITLE
is editing  mysql users table possible?

### ISSUE THREAD

**Issue by hamdiwanis** [processone/ejabberd#1085]
> What version of ejabberd are you using?
16

> What operating system (version) are you using?
windows 8.1

> How did you install ejabberd (source, package, distribution)?
binary package

I was wondering if i added more rows like email or mobile to the user table of ejabberd  MySQL db of the same schema, would it still works?

**Comment by zinid** [comment]
Yes, it would work.

**Comment by hamdiwanis** [comment]
ok then thanks you
