### ISSUE TITLE
mod_sip crash ejabberd 

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1091]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Debian 8.4

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After upgrade ejabberd from 16.02 to 16.03 I have problem with mod_sip - sometimes this module crash and there is no possible to connect with server (c2s, s2s stop working) and I must restart ejabberd. In log file I see erros:
```
2016-04-25 20:22:32.728 [error] <0.6327.0> CRASH REPORT Process <0.6327.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in inet:tcp_controlling_process/2 line 1532
2016-04-25 20:22:32.728 [error] <0.4702.0> Supervisor ejabberd_listeners had child {5061,{0,0,0,0},tcp} started with ejabberd_listener:start({5061,{0,0,0,0},tcp}, esip_socket, [{certfile,<<"/etc/ejabberd/certs/ejabberd.pem">>},{tls,true}]) at <0.6327.0> exit with reason {badmatch,{error,einval}} in context child_terminated
2016-04-25 20:22:32.729 [error] <0.21504.7>@ejabberd_listener:socket_error:580 Failed to open socket:
  {5061,esip_socket,[inet,{ip,{0,0,0,0}}]}
Reason: IP address and port number already used: 0.0.0.0 5061
```
```
2016-04-25 20:22:32 =CRASH REPORT====
  crasher:
    initial call: ejabberd_listener:init/3
    pid: <0.6327.0>
    registered_name: []
    exception error: {{badmatch,{error,einval}},[{inet,tcp_controlling_process,2,[{file,"inet.erl"},{line,1532}]},{ejabberd_socket,start,4,[{file,"src/ejabberd_socket.erl"},{line,119}]},{ejabberd_listener,accept,4,[{file,"src/ejabberd_listener.erl"},{line,343}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [ejabberd_listeners,ejabberd_sup,<0.3551.0>]
    messages: [{tcp_closed,#Port<0.279074>}]
    links: [<0.4702.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1173845
  neighbours:
2016-04-25 20:22:32 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_listeners}
     Context:    child_terminated
     Reason:     {badmatch,{error,einval}}
     Offender:   [{pid,<0.6327.0>},{name,{5061,{0,0,0,0},tcp}},{mfargs,{ejabberd_listener,start,[{5061,{0,0,0,0},tcp},esip_socket,[{certfile,<<"/etc/ejabberd/certs/ejabberd.pem">>},{tls,true}]]}},{restart_type,transient},{shutdown,brutal_kill},{child_type,worker}]
```
On ejabberd 16.02 everything work ok and I don't have such problems.

**Comment by zinid** [comment]
There is in the log:
```Reason: IP address and port number already used: 0.0.0.0 5061```
Please check if ports are released before starting ejabberd.

**Comment by beherit** [comment]
@zinid I think You are don't understand me - this error appear instant after mod_sip crash not when I try to restart ejabberd.

**Comment by zinid** [comment]
What erlang version are you using?

**Comment by beherit** [comment]
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:8:2] [async-threads:10] [kernel-poll:false]

**Comment by zinid** [comment]
Could you please post somewhere the content of file `/usr/lib/erlang/lib/kernel-X.Y/src/inet.erl`? I really do not see how `badmatch` error can occur in that file. Also seems like line number doesn't match the file from R17.

**Comment by zinid** [comment]
Ah, it seems like badmatch occurs at this line: https://github.com/erlang/otp/blob/OTP-17.0/lib/kernel/src/inet.erl#L1509
And this has been fixed in recent erlang version, at least R18 doesn't have such bug: https://github.com/erlang/otp/blob/OTP-18.0/lib/kernel/src/inet.erl#L1535
Please update your Erlang version.

**Comment by weiss** [comment]
> at least R18 doesn't have such bug

Indeed.  This was actually [fixed by us][1] :-)

[1]: https://github.com/erlang/otp/commit/c1780b76cdfefbb52025afcf27f6eab01a464e90

**Comment by beherit** [comment]
There is one problem - on Debian 8.4 in official repos is only Erlang/OTP 17.
