### ISSUE TITLE
Error "call to undefined function ejabberd_auth_odbc:start(<<"coopens.com">>) in application_master:init/4 line 134" 

### ISSUE THREAD

**Issue by zyfmix** [processone/ejabberd#1092]
> What version of ejabberd are you using?

ejabberdv16.3.0

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when i update ejabberd from 16.02 to 16.03,and start ejabberd,it aways crashed sub error:

`
09:24:12.606 [debug] SQL: "delete from sm where node='ejabberd@coopens.com'"
09:24:12.607 [debug] Supervisor ejabberd_sup started ejabberd_sm:start_link() at pid <0.368.0>
09:24:12.610 [debug] Supervisor inet_gethost_native_sup started undefined at pid <0.390.0>
09:24:12.611 [debug] Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.389.0>
09:24:12.619 [info] FQDN used to check DIGEST-MD5 SASL authentication: localhost.localdomain
09:24:12.637 [error] CRASH REPORT Process <0.41.0> with 0 neighbours exited with reason: call to undefined function ejabberd_auth_odbc:start(<<"coopens.com">>) in application_master:init/4 line 134
09:24:12.638 [info] Application ejabberd exited with reason: call to undefined function ejabberd_auth_odbc:start(<<"coopens.com">>)
`
i kown "ejabberd_auth_odbc.erl" changed to "ejabberd_auth_sql.erl" and i do not had found "ejabberd_auth_odbc:start" anywhere  in my new ejabberd16.3.0 src.
but when i annotation my ejabberd.yml of "auth_method" like below:

`
##auth_method: odbc
`
and start ejabberd again,it does not crashed again.
so what's wrong and how to configure "auth_method: odbc" in my ejabberd.yml?

**Comment by zinid** [comment]
There is indeed a regression introduced in 1aae8a9fda184b8a8fa139d9fc4bf2aa2c6ba8a0
But this code is not in 16.03 yet, afaik.

**Comment by zinid** [comment]
By the way, you can use `auth_method: sql` if you don't want to update to the latest revision.

**Comment by zyfmix** [comment]
Thank you for your answer @zinid .But when i update my ejabberd src with [1aae8a9](https://github.com/processone/ejabberd/commit/1aae8a9fda184b8a8fa139d9fc4bf2aa2c6ba8a0) just now and change ejabberd.yml to "auth_method: sql",when i start ejabberd again,it crashed another error:
`
17:33:12.045 [critical] Problem starting the module mod_carboncopy for host <<"coopens.com">>
 options: []
 error: undef
[{mod_carboncopy_sql,init,[<<"coopens.com">>,[]],[]},
 {mod_carboncopy,start,2,[{file,"src/mod_carboncopy.erl"},{line,72}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,114}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,74}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
17:33:12.046 [critical] ejabberd initialization was aborted because a module start failed.

Crash dump is being written to: //var/log/ejabberd/erl_crash_20160427-173307.dump...done
Problem starting the module mod_carboncopy for host <<"coopens.com">>
 options: []
 error: undef
[{mod_carboncopy_sql,init,[<<"coopens.com">>,[]],[]},
 {mod_carboncopy,start,2,[{file,"src/mod_carbon
`
how can i fix for it?

**Comment by zinid** [comment]
You can set `db_type: mnesia` explicitly for mod_carboncopy for now. I'm working on the fix.

**Comment by zyfmix** [comment]
Thank you very much, @zinid Thank you for your work.
