### ISSUE TITLE
error "unauthorized" for administrator api

### ISSUE THREAD

**Issue by mitec** [processone/ejabberd#1093]
Hello,

I wanted to use the api (https://docs.ejabberd.im/admin/api/), but I ended with "unauthorized" error. I am guessing, the api requires authentication via oauth (but the documentation doesn't say anything about that).

Is there a way how to turn off the authentication?
I will call the api from within internal network (there are other security rules, which will handle missing oauth).

Thanks a lot!

Peter Mitko

P.S.:
> What version of ejabberd are you using?
16.01

> What operating system (version) are you using?
ubuntu 14.04.3 LTS

> How did you install ejabberd (source, package, distribution)?
ejabberd_16.01-0_amd64.deb

**Comment by badlop** [comment]
How are you making the requests? ejabberdctl, xmlrpc, rest...? Show an example request.
