### ISSUE TITLE
admin api command ejabberdctl check_account doesn't return a readable result

### ISSUE THREAD

**Issue by mitec** [processone/ejabberd#1094]
Hello,

I tried the comand "ejabberdctl check_account user host" according the documentation, but it doesn't return any value, or the value is interpreted as some white char.

For example the command "ejabberdctl register user host password" works fine.

Could you help me?

Thank you in advance.

Peter Mitko

> What version of ejabberd are you using?
    16.01

> What operating system (version) are you using?
    ubuntu 14.04.3 LTS

> How did you install ejabberd (source, package, distribution)?
    ejabberd_16.01-0_amd64.deb

**Comment by beherit** [comment]
Check this https://github.com/processone/ejabberd/issues/1042#issuecomment-213335621

**Comment by cromain** [comment]
this command returns a rescode. this means you heve to check exit code of the command, like any other shell command. example
```
$ true
$ echo $?
0
$ false
$ echo $?
1
$ ejabberdctl checl_account doesnotexists domain
$ echo $?
1
```
if you want a tet output, you can use this in shell
`ejabberdctl check_account user host && echo true || echo false`
