### ISSUE TITLE
Installetion fails

### ISSUE THREAD

**Issue by marinakr** [processone/ejabberd#1095]
My erlang version:
17.5
OS: Ubuntu 14.04

Ejabberd version: 14.07
git clone  https://github.com/processone/ejabberd.git
git checkout 14.07
autogen  run successfully, 

but fails with configure:
user@marinakr:~/workspace/ejabberd$ ./configure 
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking Erlang/OTP version... conftest.erl: internal error in expand_module;
crash reason: undef

  in function  erl_parse:new_anno/1
     called as erl_parse:new_anno({function,0,module_info,0,
           [{clause,0,[],[],
                    [{call,0,
                           {remote,0,{atom,0,erlang},{atom,0,get_module_info}},
                           [{atom,0,conftest}]}]}]})
  in call from sys_pre_expand:'-module_predef_funcs/1-lc$^0/1-0-'/1 (sys_pre_expand.erl, line 119)
  in call from sys_pre_expand:module_predef_funcs/1 (sys_pre_expand.erl, line 119)
  in call from sys_pre_expand:module/2 (sys_pre_expand.erl, line 81)
  in call from compile:expand_module/1 (compile.erl, line 1202)
  in call from compile:'-internal_comp/4-anonymous-1-'/2 (compile.erl, line 295)
  in call from compile:fold_comp/3 (compile.erl, line 321)
  in call from compile:internal_comp/4 (compile.erl, line 305)
configure: error: "Could not compile Erlang/OTP version check program using '/usr/local/bin/erlc'"

And when  I create symlinks on /usr/local/bin/erlc, configure works, 

but make fails:

user@marinakr:~/workspace/ejabberd$ make
rm -rf deps/.got
rm -rf deps/.built
/usr/local/lib/erlang/bin/escript rebar get-deps && :> deps/.got
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,143}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,752}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,276}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}

=ERROR REPORT==== 28-Apr-2016::18:24:43 ===
Unable to load crypto library. Failed with error:
"bad_lib, Library version (2.8) not compatible (with 2.7)."
OpenSSL might not be installed on this system.
make: *** [deps/.got] Ошибка 1

Any help could be usefull

**Comment by prefiks** [comment]
Hello,

You probably are missing some erlang related packages, i think crypto module is available in erlang-crypto ubuntu package. In general you may want install "erlang" metapackage that should pull everything that is usually distributed with erlang system.

**Comment by prefiks** [comment]
Ah i see you want to use custom erlang you can pass --with-erlang=/path/to/my/erlang to configure script which should make it pick it up.

**Comment by marinakr** [comment]
erlang related pakeges installed, and apt-get write that

**Comment by marinakr** [comment]
I changed rebar.config to fix error preview commet, and got  error 
Compiling /home/user/workspace/ejabberd/deps/p1_tls/c_src/p1_sha.c
In file included from /home/user/workspace/ejabberd/deps/p1_tls/c_src/p1_sha.c:21:0:
/usr/include/erl_nif.h:31:40: fatal error: erl_native_features_config.h: Нет такого файла или каталога
 #include "erl_native_features_config.h"
                                        ^
compilation terminated.
ERROR: compile failed while processing /home/user/workspace/ejabberd/deps/p1_tls: rebar_abort
make: *** [deps/.built] Ошибка 1

**Comment by prefiks** [comment]
Can you tell me why you want to use version 14.07?

There may be problem with getting this version from git since i think we didn't use versioned deps at that time - we always used latest version of dependency, which may be not compatible with that version of ejabberd, if you really want to use that version i would suggest grabbing tar.gz with source of that version from https://www.process-one.net/en/ejabberd/archive/

**Comment by prefiks** [comment]
Also that problem with header suggest that something is missing in your erlang installation, do you have "erlang-dev" package installed?

**Comment by marinakr** [comment]
erlang-dev newest version already installed
on our test server, we have this version of erlang(17.5) and 14.07 ejabberd I can't understand what the problem is

I installed erlang with wget and make, make install

**Comment by marinakr** [comment]
@prefiks, Thank you for participating
Problem was I have 3 erlngs(17.5, 18.0 downloaded and installed with wget, make install and 17 fron ubuntu sources), and it was fixed by removing all erlangs and install 17.5

Also, configure script that works for me:
[rebar.config.script.txt](https://github.com/processone/ejabberd/files/242104/rebar.config.script.txt)
(configure script from repo fails)
