### ISSUE TITLE
mod_mam: function_clause error

### ISSUE THREAD

**Issue by petmue** [processone/ejabberd#1098]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

By source: 
`./configure --prefix=/opt/ejabberd/16.04/ --enable-user=ejabberd --enable-pam --enable-zlib`
Then copied the old ejabberd.yml config file from 16.03.
Finally I restored the backup of the DB by `ejabberedctl restore ejabberd.backup`

> What did not work as expected? Are there error messages in the log?

From the config file:
` mod_mam:
    default: always
    assume_mam_usage: on_request`

From time to time I now find the following error in the ejabberd.log

`2016-04-30 12:31:42.430 [error] <0.489.0>@ejabberd_hooks:run_fold1:368 {function_clause,[{mod_mam,select,[<<"jabber.domain.tld">>,{jid,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>},{jid,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>},{1459,714394,0},{1462,19502,0},none,{rsm_in,50,before,<<>>,undefined},{groupchat,moderator,{state,<<"conference">>,<<"conference.jabber.domain.tld">>,<<"jabber.domain.tld">>,{all,all,none,all},{jid,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>},{config,<<>>,<<>>,true,true,true,anyone,true,true,true,true,true,true,false,true,true,false,false,<<>>,false,[moderator,participant,visitor],true,1800,200,false,<<>>,{0,nil},true},{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[[{<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>}|{user,{jid,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>},<<"alice">>,moderator,{xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"from">>,<<"alice@jabber.domain.tld/mobile">>},{<<"to">>,<<"conference@conference.jabber.domain.tld/alice">>}],[]}}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},nil,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[[<<"alice">>,{<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,4,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[[{<<"alice">>,<<"jabber.domain.tld">>,<<>>}|{owner,<<>>}]],[],[[{<<"donald">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}],[{<<"bob">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}]],[],[],[],[[{<<"carl">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}]],[],[],[],[]}}},{lqueue,{[],[]},0,20},<<"conference">>,<<"alice">>,false,{...},...}}],...},...]}
running hook: {muc_process_iq,[{state,<<"conference">>,<<"conference.jabber.domain.tld">>,<<"jabber.domain.tld">>,{all,all,none,all},{jid,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>},{config,<<>>,<<>>,true,true,true,anyone,true,true,true,true,true,true,false,true,true,false,false,<<>>,false,[moderator,participant,visitor],true,1800,200,false,<<>>,{0,nil},true},{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[[{<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>}|{user,{jid,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>},<<"alice">>,moderator,{xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"from">>,<<"alice@jabber.domain.tld/mobile">>},{<<"to">>,<<"conference@conference.jabber.domain.tld/alice">>}],[]}}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},nil,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[[<<"alice">>,{<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,4,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[[{<<"alice">>,<<"jabber.domain.tld">>,<<>>}|{owner,<<>>}]],[],[[{<<"donald">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}],[{<<"bob">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}]],[],[],[],[[{<<"carl">>,<<"jabber.domain.tld">>,<<>>}|{member,<<>>}]],[],[],[],[]}}},{lqueue,{[],[]},0,20},<<"conference">>,<<"alice">>,false,{{83466786,{<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>}},{1,-1462019506339659},{activity,0,1462019502339588,none,none,undefined,undefined},nil,nil},none,{[],[]}},{jid,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>,<<"alice">>,<<"jabber.domain.tld">>,<<"mobile">>},{jid,<<"conference">>,<<"conference.jabber.domain.tld">>,<<>>,<<"conference">>,...}]}
`

> What was the unexpected behavior? What was the expected result?

The error didn't appear in 16.03

**Comment by weiss** [comment]
You should have a proper trace in your crash.log file.  Could you paste that?

**Comment by petmue** [comment]
> You should have a proper trace in your crash.log file. Could you paste that?

Unfortunately I do not have a proper trace in my crash.log file. There's only one error from mod_offline:

> ejabberd@host:~/16.04$ cat var/log/ejabberd/crash.log 
 2016-04-30 13:31:39 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_sup}
     Context:    shutdown_error
     Reason:     noproc
     Offender:   [{pid,<0.719.0>},{name,ejabberd_offline_localhost},{mfargs,{mod_offline,start_link,[<<"localhost">>,[{access_max_user_messages,max_user_offline_messages}]]}},{restart_type,transient},{shutdown,1000},{child_type,worker}]

There's also no more information despite log level 5 (debug).

**Comment by zinid** [comment]
There is a typo in the code after refactoring: https://github.com/processone/ejabberd/commit/52571e8624b0a48797ca24ec05e47a5c9477a12a#diff-429b4ba127d21213c8ad69c1c2585bf9R815
this should be `From, To`, not `From, From`. My bad.

**Comment by petmue** [comment]
@zinid In line 774 is another "From, From", which you haven't changed yet. Is that one correct or did you oversee it?

https://github.com/processone/ejabberd/blob/3493a874695749072522c5a36d363b1f84475569/src/mod_mam.erl#L774

**Comment by zinid** [comment]
@petmue that one is correct. That's why you don't have function clause on regular chat messages, only on MUC ones.
