### ISSUE TITLE
mod_http_upload fails while trying to PUT an image

### ISSUE THREAD

**Issue by sshisk** [processone/ejabberd#1099]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Linux (custom systemd-based distribution, kernel 4.4.5)

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Uploading test file to server with mod_http_upload fails with error:
```
2016-05-02 01:57:32.748 [info] <0.464.0>@mod_http_upload:create_slot:634 Got HTTP upload slot for foo@bar.net/Gajim (file: test.png)
2016-05-02 01:57:33.371 [info] <0.583.0>@ejabberd_listener:accept:333 (#Port<0.15645>) Accepted connection 127.0.0.1:35678 -> 127.0.0.1:5443
2016-05-02 01:57:33.371 [info] <0.924.0>@ejabberd_http:init:158 started: {gen_tcp,#Port<0.15645>}
2016-05-02 01:57:33.371 [error] <0.924.0>@mod_http_upload:process:434 Cannot handle PUT request from 127.0.0.1 for bar.net: {'EXIT',{noproc,{gen_server,call,['mod_http_upload_bar.net/upload',{use_slot,[<<"big-hash-1">>,<<"big-hash-2">>,<<"test.png">>]}]}}}
```

Relevant configuration snippets:
```
listen:
  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      "/upload": mod_http_upload
modules:
  mod_http_upload:
    docroot: "/srv/http/nginx/uploads"
    get_url: "https://bar.net/uploads"
    put_url: "https://xmpp.bar.net/upload"
```

`xmpp.bar.net` is a subdomain pointing to same server. HTTP listener is behind a nginx proxy for TLS and several hosts:
```
server {
  listen 443 ssl;
  server_name xmpp.bar.net;

  location / {
    proxy_pass http://localhost:5443/;
    proxy_set_header Host bar.net;
  }
}
```

On client, the request fails with a 500 error. nginx log:
```
"PUT /upload/big-hash-1/big-hash-2/test.png HTTP/1.1" 500 23 "-" "Gajim 0.16.5"
```

Any ideas? Thank for help!

**Comment by weiss** [comment]
Do you have multiple virtual hosts in ejabberd?

And could you please run an `ejabberdctl debug` shell and check the output of the following call (don't forget the trailing `.`, and press `Ctrl`+`C` twice to get out of the shell):

    process_info(list_to_pid("<0.464.0>"), registered_name).

The Erlang process ID in that call (`<0.464.0>`) is taken from the first line of your log snippet.  If you restarted ejabberd since then, you'd replace that PID with the one you see in new `@mod_http_upload:create_slot` log lines.

**Comment by sshisk** [comment]
Yay! Running that, I noticed process name: `{registered_name,'mod_http_upload_xmpp.fmap.me/upload'}`
So I changed Host header that nginx passes from `bar.net` to `$host`, aka `xmpp.bar.net`. It works now!

For the record, no, I don't have multiple hosts. This could use a better error message, but otherwise looks like entirely my problem. Thank you!
