### ISSUE TITLE
Best way to implement an incoming muc messages reroute

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1100]
Related with the answer made by @sh-al on the issue #697 

Which could be the best option to reroute to all room users all the incoming MUC messages filtered by the "muc_filter_message" hook?

I have the Stanza caught by the hook/handle function.

Thanks!

**Comment by joanlopez** [comment]
Any suggestion?

**Comment by badlop** [comment]
Apparently there aren't suggestions
