### ISSUE TITLE
Unexpected Crash  

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#1101]
> What version of ejabberd are you using?
15.11

> What operating system (version) are you using?
Linux (ubuntu)

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What
unexpected crash occurring 
  
> was the unexpected behavior? What was the expected result?
Below is the error which started to appear recently on my  ejab server log . help me to understand the issue .

**Error log:**

CRASH REPORT Process <0.2960.1658> with 0 neighbours exited with reason: no such process or port in call to gen_fsm:sync_send_all_state_event(<22346.9232.23>, {http_put,1385321984,[{<<"xmlns">>,<<"http://jabber.org/protocol/httpbind">>},{<<"rid">>,<<"138532...">>},...],...}, 30000) in gen_fsm:sync_send_all_state_event/3 line 242
2016-05-03 14:31:16.394 [error] <0.25287.856> Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.2960.1658> exit with reason no such process or port in call to gen_fsm:sync_send_all_state_event(<22346.9232.23>, {http_put,1385321984,[{<<"xmlns">>,<<"http://jabber.org/protocol/httpbind">>},{<<"rid">>,<<"138532...">>},...],...}, 30000) in context child_terminated

**Comment by synotna** [comment]
What was the cause/solution of your issue?

**Comment by kishoreacesurf** [comment]
Any solution? I have exactly the same issue

**Comment by zinid** [comment]
Whatever the reason, there is a new implementation of BOSH in ejabberd (`mod_bosh` instead of `mod_http_bind`), so nobody will fix obsoleted code.
