### ISSUE TITLE
Extauth script can log sensitive information if the call fails

### ISSUE THREAD

**Issue by richardardrichard** [processone/ejabberd#1103]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Linux

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

If the call to an external auth script fails, Ejabberd logs the entire message that was sent to the auth script (https://github.com/processone/ejabberd/blob/master/src/extauth.erl#L131-L132). This can include sensitive user information such as a password being written to the logs.

**Comment by badlop** [comment]
Try this patch, and enable the hide_sensitive_log_data option. Does it work correctly for you?
```
diff --git a/src/extauth.erl b/src/extauth.erl
index 50330b4..fb5f2e7 100644
--- a/src/extauth.erl
+++ b/src/extauth.erl
@@ -129,7 +129,7 @@ loop(Port, Timeout, ProcessName, ExtPrg) ->
 		loop(Port, ?CALL_TIMEOUT, ProcessName, ExtPrg)
 	    after Timeout ->
 		      ?ERROR_MSG("extauth call '~p' didn't receive response",
-				 [Msg]),
+				 [ejabberd_config:may_hide_data(Msg)]),
 		      Caller ! {eauth, false},
 		      Pid = restart_instance(ProcessName, ExtPrg),
 		      flush_buffer_and_forward_messages(Pid),
```

**Comment by mremond** [comment]
@richardardrichard Is this fine for you ?
