### ISSUE TITLE
/usr/local/lib/erlang/bin/escript rebar get-deps && :> deps/.got

### ISSUE THREAD

**Issue by varun-naharia** [processone/ejabberd#1105]
> What version of ejabberd are you using?
Master from github

> What operating system (version) are you using?
CentOS 7

> How did you install ejabberd (source, package, distribution)?

I download the master source code and tried to build as explained here is the command and output
[ejabberd]$ ./autogen.sh
[ejabberd]$ ./configure
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /usr/bin/sed
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking for epmd... /usr/local/bin/epmd
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking Erlang/OTP version... ok
checking for Erlang/OTP root directory... /usr/local/lib/erlang
checking for escript... /usr/local/lib/erlang/bin/escript
checking for make... make
checking whether Erlang is using deprecated types... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
config.status: creating src/ejabberd.app.src
[ejabberd]$ make
rm -rf deps/.got
rm -rf deps/.built
/usr/local/lib/erlang/bin/escript rebar get-deps && :> deps/.got
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,163}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,757}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: *** [deps/.got] Error 1
[ejabberd]$ 
 

> What did not work as expected? Are there error messages in the log? What
Source code is not complied and installed as expected.

**Comment by zinid** [comment]
You have some problems with Erlang installation. You don't have `crypto` library installed which is a part of Erlang distribution (but in some distros are placed in a separate package).

**Comment by varun-naharia** [comment]
Can you please explain me how I can check and install Erlang ?

**Comment by varun-naharia** [comment]
I think crypto is installed, List of erlang pakages

$ rpm -qa | grep erlang
erlang-public_key-18.3-1.el7.centos.x86_64
erlang-gs-18.3-1.el7.centos.x86_64
erlang-snmp-18.3-1.el7.centos.x86_64
erlang-erl_docgen-18.3-1.el7.centos.x86_64
erlang-ose-18.3-1.el7.centos.x86_64
erlang-os_mon-18.3-1.el7.centos.x86_64
erlang-crypto-18.3-1.el7.centos.x86_64
erlang-eunit-18.3-1.el7.centos.x86_64
erlang-debugger-18.3-1.el7.centos.x86_64
erlang-orber-18.3-1.el7.centos.x86_64
erlang-percept-18.3-1.el7.centos.x86_64
erlang-webtool-18.3-1.el7.centos.x86_64
erlang-erts-18.3-1.el7.centos.x86_64
erlang-runtime_tools-18.3-1.el7.centos.x86_64
erlang-cosEvent-18.3-1.el7.centos.x86_64
erlang-otp_mibs-18.3-1.el7.centos.x86_64
erlang-eldap-18.3-1.el7.centos.x86_64
erlang-odbc-18.3-1.el7.centos.x86_64
erlang-tools-18.3-1.el7.centos.x86_64
erlang-reltool-18.3-1.el7.centos.x86_64
erlang-hipe-18.3-1.el7.centos.x86_64
erlang-ssl-18.3-1.el7.centos.x86_64
erlang-cosProperty-18.3-1.el7.centos.x86_64
erlang-wx-18.3-1.el7.centos.x86_64
erlang-jinterface-18.3-1.el7.centos.x86_64
erlang-et-18.3-1.el7.centos.x86_64
erlang-typer-18.3-1.el7.centos.x86_64
erlang-compiler-18.3-1.el7.centos.x86_64
erlang-inets-18.3-1.el7.centos.x86_64
erlang-edoc-18.3-1.el7.centos.x86_64
erlang-cosTransactions-18.3-1.el7.centos.x86_64
erlang-erl_interface-18.3-1.el7.centos.x86_64
erlang-observer-18.3-1.el7.centos.x86_64
erlang-common_test-18.3-1.el7.centos.x86_64
erlang-solutions-1.0-1.noarch
erlang-syntax_tools-18.3-1.el7.centos.x86_64
erlang-asn1-18.3-1.el7.centos.x86_64
erlang-cosTime-18.3-1.el7.centos.x86_64
erlang-cosEventDomain-18.3-1.el7.centos.x86_64
erlang-parsetools-18.3-1.el7.centos.x86_64
erlang-test_server-18.3-1.el7.centos.x86_64
erlang-18.3-1.el7.centos.x86_64
erlang-stdlib-18.3-1.el7.centos.x86_64
erlang-cosNotification-18.3-1.el7.centos.x86_64
erlang-ic-18.3-1.el7.centos.x86_64
erlang-dialyzer-18.3-1.el7.centos.x86_64
erlang-kernel-18.3-1.el7.centos.x86_64
erlang-diameter-18.3-1.el7.centos.x86_64
erlang-sasl-18.3-1.el7.centos.x86_64
erlang-xmerl-18.3-1.el7.centos.x86_64
erlang-cosFileTransfer-18.3-1.el7.centos.x86_64
erlang-examples-18.3-1.el7.centos.x86_64
erlang-mnesia-18.3-1.el7.centos.x86_64
erlang-ssh-18.3-1.el7.centos.x86_64
erlang-megaco-18.3-1.el7.centos.x86_64

**Comment by zinid** [comment]
> Can you please explain me how I can check and install Erlang ?

$ erl
...
> crypto:start().

**Comment by zinid** [comment]
Also, according to `configure` output Erlang is found in `/usr/local` directory, but typically system erlang is installed in `/usr` directory. Try the same as about but with `/usr/local/bin/erl`.

**Comment by varun-naharia** [comment]
I got this by entering command given by you

$ erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> crypto:start().
** exception error: undefined function crypto:start/0
2>

**Comment by zinid** [comment]
@varun-naharia you clearly have problems with Erlang installation.

**Comment by VijayJaybhay** [comment]
@zinid though this issue was closed (as it is problem with erlang installation), I think this will help to some one:
Try installing erlang from source code [at https://www.erlang.org/downloads].  Refer  this http://erlang.org/doc/installation_guide/INSTALL.html documentation (You can ignore Test section, as it wasn't worked for me , so I just skipped this part and moved to next step)
This will install erlang at /usr/local/bin .After successful installation, check this:
```
$ erl
Erlang/OTP 19 [erts-8.0] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V8.0  (abort with ^G)
1> crypto:start().
ok
2>
```
