### ISSUE TITLE
Module 'mod_carboncopy' doesn't support database 'sql' defined in option 'default_db', using 'mnesia' as fallback

### ISSUE THREAD

**Issue by drixter** [processone/ejabberd#1106]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

RPM from ejabberd home page

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Module 'mod_carboncopy' doesn't support database 'sql' defined in option 'default_db', using 'mnesia' as fallback

Also tried with odbc, how to fix that error?

Regards,

**Comment by varun-naharia** [comment]
I am getting problem in installing ejabberd on cent OS  7 can please help to install ?

**Comment by zinid** [comment]
@drixter `mod_carboncopy` only supports `mnesia` database, so this is a notice for you.

**Comment by zinid** [comment]
Also, you can set `db_type: mnesia` explicitly for `mod_carboncopy` if this warning annoys you.

**Comment by drixter** [comment]
Roger.
