### ISSUE TITLE
Support reloading TLS certificate file

### ISSUE THREAD

**Issue by lp0** [processone/ejabberd#1109]
Let's Encrypt certificates expire after 90 days, there needs to be a command to reload the certificate without having to restart the server.

**Comment by weiss** [comment]
ejabberd reloads the certificate automatically if the modification time of the PEM file changes.

**Comment by pjanouch** [comment]
@weiss Could you say more about how that feature works, e.g. where exactly the check is done? It's not exactly easy to find any information about it.

**Comment by dioobr** [comment]
@weiss How long to verify that the certificate has been replaced? I did this now, and still continues with the expired certificate.

**Comment by weiss** [comment]
> How long to verify that the certificate has been replaced?

It should be auto-reloaded immediately.

> I did this now, and still continues with the expired certificate.

WIth recent ejabberd versions, you might have to call `ejabberdctl reload-config` after replacing the certificate (if you're on Linux and don't have `inotifywait` installed, or if you're e.g. on a BSD).

**Comment by paradisaeidae** [comment]
I've attempted to refresh certificates using: ejabberdctl reload-config
However with 18.09 this has no effect if a directory is used in config.

**Comment by zinid** [comment]
> However with 18.09 this has no effect if a directory is used in config.

What do you mean? Show your `certfiles` section.
