### ISSUE TITLE
Installing new module error mod_opt_type(db_type)

### ISSUE THREAD

**Issue by philipmoniaga** [processone/ejabberd#1113]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

OSx el capitan

> How did you install ejabberd (source, package, distribution)?
source using make && make install

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I try install example module helloworld in erlang and elixir but have an error while start ejabberd
```
11:53:55.693 [info] Application sasl started on node ejabberd@localhost
11:53:55.799 [info] Application asn1 started on node ejabberd@localhost
11:53:55.799 [info] Application public_key started on node ejabberd@localhost
11:53:55.869 [info] Application ssl started on node ejabberd@localhost
11:53:55.987 [info] Application fast_yaml started on node ejabberd@localhost
11:53:56.099 [info] Application fast_tls started on node ejabberd@localhost
11:53:56.149 [info] Application fast_xml started on node ejabberd@localhost
11:53:56.177 [info] Application stringprep started on node ejabberd@localhost
11:53:56.200 [info] Application cache_tab started on node ejabberd@localhost
11:53:57.852 [info] Application mnesia started on node ejabberd@localhost
11:54:00.408 [info] Application inets started on node ejabberd@localhost
11:54:02.880 [error] CRASH REPORT Process <0.37.0> with 0 neighbours exited with reason: call to undefined function mod_filter:mod_opt_type(db_type) in application_master:init/4 line 134
```

Any solutions
?
Thanks

**Comment by mremond** [comment]
ejabberd does not seem to have any mod_filter module in it. Why do you think it is a problem with ejabberd ? It looks like a mod_filter problem.

**Comment by philipmoniaga** [comment]
Sorry , I just installed through ejabberdctl but it seem i must add these in my mod_filter

```
def mod_opt_type(_db)
 ok.
end
```
to resolve the problem
