### ISSUE TITLE
ejabberd says erl node is already in use

### ISSUE THREAD

**Issue by joe-liberty** [processone/ejabberd#1116]
> What version of ejabberd are you using?
2.1.11

> What operating system (version) are you using?
Ubuntu 14.04 

> How did you install ejabberd (source, package, distribution)? Distribution apt package manager

> What did not work as expected? Will not start

> Are there error messages in the log? Yes, posted below. 
> What  was the unexpected behavior? It says a node is already in use
> What was the expected result? Failure to start

I have even tried uninstalling and reinstalling everything:

{error_logger,{{2016,5,11},{21,17,13}},"Protocol: ~tp: the name ejabberd@foo seems to be in use by another Erlang node",["inet_tcp"]}

**Comment by cromain** [comment]
you should kill epmd
