### ISSUE TITLE
How ejabberdctl export2sql and export_sql works?

### ISSUE THREAD

**Issue by timeos** [processone/ejabberd#1118]
> What version of ejabberd are you using?

ejabberd-16.04-0.x86_64

> What operating system (version) are you using?

CentOS Linux release 7.2.1511 (Core)

> How did you install ejabberd (source, package, distribution)?

package from ejabberd web page

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I would like to migrate from Mnesia to MySQL. I found that there is command "export2sql" available in ejabberdctl. per ejabberdctl it should be used this way:

`ejabberdctl export2sql host directory`

the problem is, that whatever "host" statement I used (ejabberd@im, im.exmaple.com, example.com) , I always get: 

```
$ ejabberdctl export2sql ejabberd@im /tmp/
Problem 'exit {error,eisdir}' occurred executing the command.
tacktrace: [{ejd2sql,prepare_output,2,[{file,"src/ejd2sql.erl"},{line,279}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,67}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]
```

Same issue I have for another - similar - command: "export_sql". It has exactly the same parameters, but error is same:

```
$ ejabberdctl export_sql ejabberd@im /tmp/
Problem 'exit {error,eisdir}' occurred executing the command.
Stacktrace: [{ejd2sql,prepare_output,2,[{file,"src/ejd2sql.erl"},{line,279}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,67}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]
```

please can anybody advise?

thanks

**Comment by badlop** [comment]
Thanks for reporting. Things to note:

* Both commands are equivalent. export_sql is useless, please use export2sql from now on.
* export2sql requires a file, not a directory: ejabberdctl export2sql localhost /tmp/eja_localhost.sql
* Looking at the source code, use this command after you have configured ejabberd to use SQL storage, in order to read from old Mnesia database, and you will get a SQL file to import in your existing empty SQL database.

**Comment by timeos** [comment]
thanks for follow up and advice. 
> use this command after you have configured ejabberd to use SQL storage

ok, I have preconfigured mysql server, created user, set privilege, import SQL schema and finally created odbc section in ejabberd.yml following way:
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "ejabberd"
odbc_password: "xxxxx"

shall I restart ejabberd processes or can I try to export immediately? my point is that if I do restart, the beam.smp will immediately use new database and probably ignore mnesia statements. 
if I execute export2sql command now (without process restart), I get following error:

$ ejabberdctl export2sql HOST /tmp/im.sql
Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_announce_mnesia,export,[<<"HOST">>],[]},
             {ejd2sql,export,3,[{file,"src/ejd2sql.erl"},{line,80}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,68}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]}]

where HOST are following strings I have tried: ejabberd@im (nodename), im.example.com (servername), example.com (used domain), localhost - all the time same error. what is meant with "host" parameter for this export2sql command? 

mod_announce is configured this way:

  mod_announce: # recommends mod_adhoc
    access: announce

thanks

**Comment by badlop** [comment]
> shall I restart ejabberd processes or can I try to export immediately?

Yes, when I tried it last week I first had to restart ejabberd so it read SQL config.

**Comment by timeos** [comment]
Ok, I have restarted ejabberd with enabled mysql configuration in ejabberd.yml as described above and tried export2sql command, but the result is completely same - i.e. like my last error message:

```
# ejabberdctl export2sql HOST /tmp/im.sql
Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_announce_mnesia,export,[<<"HOST">>],[]},
             {ejd2sql,export,3,[{file,"src/ejd2sql.erl"},{line,80}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,68}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]}]
```

where HOST are following strings I have tried: ejabberd@im (nodename), im.example.com (servername), example.com (used domain), localhost.

**Comment by badlop** [comment]
As HOST use the virtual host you defined in option "hosts" at the beginning of ejabberd.yml.

Then, for mod_announce, configure it to use sql like this:
```
  mod_announce:
    db_type: sql
```

When you run again the command, it will complain about other modules. Configure all them to use sql.

**Comment by timeos** [comment]
many thanks badlop. yes, that **db_type: sql** has to be added to all following modules:

```
mod_announce
mod_caps
mod_irc
mod_last
mod_muc
mod_offline
mod_privacy
mod_private
mod_pubsub
mod_roster
mod_shared_roster
mod_vcard
mod_vcard_xupdate (even if I havent enabled this module it before)
```

then the export2sql command has been successfully completed. and I have imported that sql file into mysql and restarted ejabberd.

many thanks again.
