### ISSUE TITLE
some users unable to log in; bad argument in call to crypto:sha_mac_n

### ISSUE THREAD

**Issue by db48x** [processone/ejabberd#1123]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Fedora 23

> How did you install ejabberd (source, package, distribution)?

distro package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The problem is that several people cannot connect. Every time they do try, the server logs the following:

    2016-05-18 13:59:41.052 [info] <0.475.0>@ejabberd_listener:accept:333 (#Port<0.18604>) Accepted connection 71.205.14.244:59923 -> 192.241.205.184:5222
    2016-05-18 13:59:41.399 [error] <0.1046.0> gen_fsm <0.1046.0> in state wait_for_feature_request terminated with reason: bad argument in call to crypto:sha_mac_n(error, <<33,...,118,10,0,0,0,1>>, 20) in scram:hi/3 line 73
    2016-05-18 13:59:41.399 [error] <0.1046.0> CRASH REPORT Process <0.1046.0> with 0 neighbours exited with reason: bad argument in call to crypto:sha_mac_n(error, <<33,...,118,10,0,0,0,1>>, 20) in scram:hi/3 line 73

The client is Pidgin 2.10.12. One odd thing is that some people who are using Pidgin 2.10.12 have no difficulties; presumably this means that the client isn't at fault.

**Comment by rbarlow** [comment]
Hello @db48x!

I work on Fedora's ejabberd package, and I was wondering where you got 16.04 for Fedora 23 from? Are you using the package from Rawhide perhaps?

**Comment by db48x** [comment]
No, just the normal Fedora 23/Fedora 23 Updates repos.

**Comment by db48x** [comment]
Looking at the code it's pretty evident that the password these users are supplying isn't passing the resourceprep step. Turns out that they copied and pasted it from the email and got a newline into it. That's probably not fixable, but the error should be handled better so that it can return an authorization failure rather than just dropping the connection.

**Comment by badlop** [comment]
If I provide a password with a newline character when registering account or when trying to login, ejabberd complains as usual:
```
12:04:45.173 [info] ({socket_state,fast_tls,{tlssock,#Port<0.27701>,#Port<0.27702>},<0.1278.0>})
 Failed authentication for user112@localhost from 127.0.0.1
```

Do you have more details how to reproduce your problem?

**Comment by mremond** [comment]
Please, reopen if you have more details.
