### ISSUE TITLE
Error using Lager

### ISSUE THREAD

**Issue by pupoxcu** [processone/ejabberd#1124]
> What version of ejabberd are you using?

16.3.0

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Via `mix deps.get` from github

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Im tryin to use ejabberd inside a phoenix application, when I run `mix phoenix.server` it throws the error : 
```
[info] Ignoring ejabberd logger options, using Elixir Logger.
[info] Application lager exited: exited in: :lager_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :lager_app.start_error_logger_handler/3
            (lager) src/lager_app.erl:141: :lager_app.start_error_logger_handler(false, 50, [Logger.ErrorHandler])
            (lager) src/lager_app.erl:217: :lager_app.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
[error] Process #PID<0.289.0> raised an exception
** (ArgumentError) argument error
    (stdlib) gen_event.erl:232: :gen_event.send/2

Crash dump is being written to: erl_crash.dump...*** stack smashing detected ***:
 /usr/lib/erlang/erts-7.3/bin/beam.smp terminated
Aborted (core dumped) 
```

**Comment by pupoxcu** [comment]
Fixed with PR #355 .

**Comment by mremond** [comment]
This is a bug in lager 3.2, fixed by this commit: https://github.com/basho/lager/commit/4c87abcd4f9d70a1136fff8f573dc7adcc833e43

**Comment by mremond** [comment]
Until lager is updated, we will be using older version. ejabberd 16.4.1 is released on hex.pm and should help: https://hex.pm/packages/ejabberd/16.4.1
