### ISSUE TITLE
16.04 installation failed on Windows 2012 R2

### ISSUE THREAD

**Issue by yankaiqian** [processone/ejabberd#1128]
> What version of ejabberd are you using?

ejabberd Community Server 16.04 windows 64bit installer
Download URL: https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.04/ejabberd-16.04-windows-installer.exe

> What operating system (version) are you using?

Windows 2012 R2 standard, Microsoft Windows [Version 6.3.9600]

> How did you install ejabberd (source, package, distribution)?

Windows 64bits Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Installation failed with APPCRASH error, firstly, it popup error window "epmd.exe has stopped working", after I click "Close the program", it then popup error window "erl.exe has stopped working".
please find the screen captures in attachment. I also copied the contents of the error window and windows event log (only tampered with Computer Name).

Content of the error window "epmd.exe has stopped working":

>  Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	epmd.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	56e73552
>   Fault Module Name:	MSVCR120.dll
>   Fault Module Version:	6.3.9600.18146
>   Fault Module Timestamp:	5650b9bb
>   Exception Code:	c0000135
>   Exception Offset:	00000000000ec540
>   OS Version:	6.3.9600.2.0.0.272.7
>   Locale ID:	2052
>   Additional Information 1:	ac05
>   Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
>   Additional Information 3:	ac05
>   Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

Event log of epmd.exe stopped working:

> Log Name:      Application
> Source:        Application Error
> Date:          2016/5/24 11:51:35
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      XXX-XXX-XXX.CORP.DOMAIN
> Description:
> Faulting application name: epmd.exe, version: 0.0.0.0, time stamp: 0x56e73552
> Faulting module name: MSVCR120.dll, version: 6.3.9600.18146, time stamp: 0x5650b9bb
> Exception code: 0xc0000135
> Fault offset: 0x00000000000ec540
> Faulting process id: 0x4f8
> Faulting application start time: 0x01d1b56f913314fd
> Faulting application path: C:\Program Files\ejabberd\bin\epmd.exe
> Faulting module path: MSVCR120.dll
> Report Id: cefc3e3e-2162-11e6-80be-00505696677c
> Faulting package full name: 
> Faulting package-relative application ID:

Content of the error window "erl.exe has stopped working":

>   Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	erl.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	56e73526
>   Fault Module Name:	MSVCR120.dll
>   Fault Module Version:	6.3.9600.18146
>   Fault Module Timestamp:	5650b9bb
>   Exception Code:	c0000135
>   Exception Offset:	00000000000ec540
>   OS Version:	6.3.9600.2.0.0.272.7
>   Locale ID:	2052
>   Additional Information 1:	ac05
>   Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
>   Additional Information 3:	ac05
>   Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900
> 

Event log of erl.exe stopped working:

> Log Name:      Application
> Source:        Application Error
> Date:          2016/5/24 11:54:34
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      XXX-XXX-XXX.CORP.DOMAIN
> Description:
> Faulting application name: erl.exe, version: 0.0.0.0, time stamp: 0x56e73526
> Faulting module name: MSVCR120.dll, version: 6.3.9600.18146, time stamp: 0x5650b9bb
> Exception code: 0xc0000135
> Fault offset: 0x00000000000ec540
> Faulting process id: 0xb4c
> Faulting application start time: 0x01d1b56ffc4625ae
> Faulting application path: C:\Program Files\ejabberd\bin\erl.exe
> Faulting module path: MSVCR120.dll
> Report Id: 39f50c88-2163-11e6-80be-00505696677c
> Faulting package full name: 
> Faulting package-relative application ID: `
> 

![ejabberd_error_epmd](https://cloud.githubusercontent.com/assets/3888149/15493907/aff0f06a-21b9-11e6-8c45-14bafaa7296b.png)
![ejabberd_error_erl](https://cloud.githubusercontent.com/assets/3888149/15493908/aff119dc-21b9-11e6-9ec8-014b4a4e7870.png)

**Comment by posixx** [comment]
Install Visual C++ Redistributable Packages for Visual Studio 2013 before running eJabberd installer, problem solved

**Comment by cromain** [comment]
msvcr100.dll is now included in installer
