### ISSUE TITLE
not able to create account and get roster entries in android application

### ISSUE THREAD

**Issue by bhartimuley** [processone/ejabberd#1129]
> What version of ejabberd are you using?
16.02

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What

I am not able to create account from android client side and i tried by creating user manually on server and login using application but then not able to get the roster entries in the client application.

> was the unexpected behavior? What was the expected result?
We must be able to create account using client application.

**Comment by badlop** [comment]
If you can use ejabberd correctly with a desktop client, but have problems with some less used application, maybe the problem is in that app.
