### ISSUE TITLE
Cannot install .RPM binary on CentOS 6.7

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1130]
> What version of ejabberd are you using?

ejabberd v16.04

> What operating system (version) are you using?

[root@localhost opt]# cat /etc/centos-release 
CentOS release 6.7 (Final)

> How did you install ejabberd (source, package, distribution)?

I'm trying to install ejabberd through your supplied .RPM file

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Here are few simple steps on a vanilla CentOS v6.7, ejabberd is not installed in this machine, it's a plain new installation, not an upgrade.

>[root@localhost opt]# wget https://www.process-one.net/downloads/ejabberd/16.04/ejabberd-16.04-0.x86_64.rpm
>--2016-05-24 17:53:16--  https://www.process-one.net/downloads/ejabberd/16.04/ejabberd-16.04-0.x86_64.rpm
> Resolving www.process-one.net... 54.235.202.77
> Connecting to www.process-one.net|54.235.202.77|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 19965350 (19M) [application/x-redhat-package-manager]
>Saving to: “ejabberd-16.04-0.x86_64.rpm”
>2016-05-24 17:58:43 (59,9 KB/s) - “ejabberd-16.04-0.x86_64.rpm” saved [19965350/19965350]
>
>[root@localhost opt]# rpm -ivh ejabberd-16.04-0.x86_64.rpm
>Preparing...                ########################################### [100%]
>   1:ejabberd               ########################################### [100%]
>error: unpacking of archive failed on file /opt/ejabberd-16.04/lib/kernel: cpio: rename failed - Is a directory
>

That's it.

RPM package seems to be wrong but I don't understand what should I report you more in order to solve this issue. Seems to be like #634 but I cannot understand what should I do with it.

Any hints ?

Kind Regards
Ben

**Comment by volga629** [comment]
I think it all related  -home directory issue ticket

Is possible put high priority on ticket https://github.com/processone/ejabberd/issues/882, because it breaks all installation here are good example .

```
[root@canlmsg01 ejabberd-16.03]# systemctl status ejabberd.service  -l
● ejabberd.service - XMPP Server
   Loaded: loaded (/usr/lib/systemd/system/ejabberd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-05-25 09:51:01 CDT; 13s ago
  Process: 9647 ExecStop=/opt/ejabberd-16.03/bin/ejabberdctl stop (code=exited, status=1/FAILURE)
  Process: 9584 ExecStart=/opt/ejabberd-16.03/bin/ejabberdctl start (code=exited, status=0/SUCCESS)
 Main PID: 9584 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ejabberd.service

May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: {error_logger,{{2016,5,25},{9,51,1}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: {error_logger,{{2016,5,25},{9,51,1}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,165}],[]]}
May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: {error_logger,{{2016,5,25},{9,51,1}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{\"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent\",[{auth,init_cookie,0,[{file,\"auth.erl\"},{line,285}]},{auth,init,1,[{file,\"auth.erl\"},{line,139}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}}}"}
May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: Crash dump was written to: /opt/ejabberd-16.03/logs/erl_crash_20160525-095101.dump
May 25 09:51:01 canlmsg01.networklab.prod ejabberdctl[9647]: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt

```

**Comment by andreabenini** [comment]
I guess RPM is just wrong, I performed a binary install through ejabberd-16.04-linux-x86_64-installer.run and installation went fine.
Just a quick note about that .run file: contained /etc/init.d/ejabberd file is still pointing to previous v16.02, you need to change:

`DIR=/opt/ejabberd-16.02`

to

`DIR=/opt/ejabberd-16.04`

May I submit a simple push request for it ?

**Comment by andreabenini** [comment]
Little hint after some investigation.
As you wrote in your download area .RPM file requires glibc v1.13 but on a common CentOS 6.7 x64 fully upgraded you only have v1.12:

> opt]# ldd --version
> ldd (GNU libc) 2.12
> ...

So this may lead to a problem but please note that 6.7 is latest 6.x LTS with stock CentOS glibc

**Comment by cromain** [comment]
3 points in this ticket:
- #634 now permanently fixed (closed)
- #882 being worked on
- libc 2.12 (Centos 6) compatibility.

We'll not build universal binary installer compatible with glibc older than 2.13. You can still give it a try when 16.06 will be released (as other RPM related issues should be fixed), it may work, but we'll not test nor maintain binary installers for that version.
If 16.06 will not work on Centos 6, you'll have to build it from sources.

**Comment by andreabenini** [comment]
Thanks cromain,
Binary installer is fine and I'm now using it with CentOS 6.8 release (fully upgraded but std packages only). I'm now happily using 16.04, we'll see what happens with 16.06 when ready.

**Comment by rom1dep** [comment]
wfm w/ 16.06 rpms.
Thanks!
