### ISSUE TITLE
Incorrect message type error

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1134]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Debian 8.4 (jessie)

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Related with the issue #1100. I'm routing (ejabberd_router:route method) the MUC messages in order to avoid the messages lost when there are users offline. My intention is handle this situation with the offline_message hook. But now, the problem is that i'm getting an "Incorrect message type" error.

Could be because i'm rerouting a type="groupchat" message to a personal jid (not conference)?

If this is the problem. How i can handle this situation? I need to avoid the messages lost on the muc rooms when there are users offline.

Thanks ;)

**Comment by weiss** [comment]
This is probably not what you wanted to hear, but the proper solution would be to query [MUC MAM][1] archives.  Is there a reason that won't work for you?

[1]: https://xmpp.org/extensions/xep-0313.html#sect-idp1643408

**Comment by joanlopez** [comment]
Well, my idea is not to store the messages on the server.

The only thing that I need is a behaviour similar as with offline messages: storing the messages only until the user has received it.

Is this behaviour possible with MUC MAM?

Many thanks ;)

**Comment by weiss** [comment]
> my idea is not to store the messages on the server.

Why not?

> The only thing that I need is a behaviour similar as with the offline messages: storing the messages only till the user has received the message.

The downside is that solutions based on offline storage fail as soon as the user has multiple clients.  And you store n copies of a given message for n offline users instead of just one in the archive

> Is this behaviour posible with MUC MAM?

No.

You can of course work around your problem by patching `mod_offline` to also store `groupchat` messages (or by creating a separate offline storage module that takes care of them).  Or you could of course change the type of those messages before routing them to offline storage (and modify the client to still recognize those as MUC messages if necessary).  But you might run into other issues by applying such hacks.

**Comment by joanlopez** [comment]
@weiss 

If I've understood well, the procedure is:

1. Enable the MOD_MAM
2. Enable the MAM parameter on the MOD_MUC config.

Is it possible to store only the messages of the MUC rooms? How I have to do it?

Many thanks!

**Comment by weiss** [comment]
Yes, you could use the following `mod_muc` configuration to enable MUC MAM for new rooms by default:

    mod_muc:
      default_room_options:
        mam: true
        persistent: true

And with the following `mod_mam` configuration, user archives (for 1:1 chat) would not be created unless explicitly requested by the client:

    mod_mam:
      default: never

**Comment by joanlopez** [comment]
Many thanks @weiss !!

Only one more thing,

Has the client (application) do something to retrieve this stored messages? Or it should receive it as the pending offline messages?

Thanks!

**Comment by weiss** [comment]
You (or the XMPP library you're using) would have to request them as described in [XEP-0313][1].

[1]: http://xmpp.org/extensions/xep-0313.html
