### ISSUE TITLE
problems with postgres/odbc and special characters (- .) in database names

### ISSUE THREAD

**Issue by dl8bh** [processone/ejabberd#1136]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

FreeBSD 10.3

> How did you install ejabberd (source, package, distribution)?

FreeBSD Ports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

On our testsystem using postgres as database:
I tried
> ejabberdctl delete_old_users 365

which lead to error messages from postgres:
```
May 27 16:59:56 xmpp postgres[88092]: [4-1] ERROR:  syntax error at or near "-" at character 19
May 27 16:59:56 xmpp postgres[88092]: [4-2] STATEMENT:  alter database some-exmaple.de set standard_conforming_strings='off';
May 27 16:59:56 xmpp postgres[88092]: [6-1] WARNING:  there is no transaction in progress
```
and a whole bunch of missing prepared_statements 

after renaming the db to "someexamplede", everything works fine.

Suggested fix: mask the db name in the respective psql queries with "" signs

**Comment by badlop** [comment]
So, a change like this solves the problem in your case?
```
--- a/src/ejabberd_sql.erl
+++ b/src/ejabberd_sql.erl
@@ -790,7 +790,7 @@ pgsql_connect(Server, Port, DB, Username, Password) ->
                         {port, Port},
                         {as_binary, true}]) of
         {ok, Ref} ->
-            pgsql:squery(Ref, [<<"alter database ">>, DB, <<" set ">>,
+            pgsql:squery(Ref, [<<"alter database \"">>, DB, <<"\" set ">>,
                                <<"standard_conforming_strings='off';">>]),
             pgsql:squery(Ref, [<<"set standard_conforming_strings to 'off';">>]),
             {ok, Ref};
```

**Comment by dl8bh** [comment]
Without beeing able to test this (migrated the postgres db names to something without special chars), I would say yes, this should be fixed with your patch. Thanks for caring!

**Comment by mremond** [comment]
@badlop This is now fine in latest ejabberd version, right ?

**Comment by badlop** [comment]
@mremond I didn't apply this patch, because I am not SQL expert, and maybe the patch should be applied in several other places. As I am not sure, can somebody with more knowledge in ejabberd's SQL code look at it?

**Comment by cromain** [comment]
Jérôme, please check if ok, and it there are other missing place to add this.

**Comment by jsautret** [comment]
Indeed, quoting the database name solves the problem. It is the only place where a database name is used in a SQL query.
