### ISSUE TITLE
ejabberdctl delete_old_messages silently fails

### ISSUE THREAD

**Issue by dl8bh** [processone/ejabberd#1137]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

FreeBSD 10.3

> How did you install ejabberd (source, package, distribution)?

FreeBSD ports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberdctl delete_old_messages <numberofdays> silently fails
postgres query log shows:
```
May 27 17:50:51 xmpp postgres[89113]: [8-2] STATEMENT:  DELETE FROM spool WHERE created_at < DATE_SUB(CURDATE(), INTERVAL 365 DAY);
May 27 17:50:57 xmpp postgres[89053]: [13-1] ERROR:  syntax error at or near "365" at character 67
```
note: postgres does not have DATE_SUB function, see
https://www.postgresql.org/docs/9.1/static/functions-datetime.html

**Comment by dl8bh** [comment]
suggested fix: 

DELETE FROM spool WHERE created_at < NOW() - INTERVAL '$NUMBER DAYS';

should work both on mysql and postgres

**Comment by cromain** [comment]
query seems to work on mysql also, should be fixed now.
