### ISSUE TITLE
When going to LDAP auth, get config file error

### ISSUE THREAD

**Issue by wankelmonkay** [processone/ejabberd#1138]
> What version of ejabberd are you using?

14.07-4+deb8u3

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

apt repo from debian

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The service will not star with ldap auth, here is sanitized config
```
auth_method: ldap
ldap_servers:
 - “127.0.0.1”
ldap_encrypt: none
ldap_port: 389
ldap_rootdn: "CN=chatauth,OU=Wankelers,DC=bronet,DC=net”
ldap_password: “secret“
ldap_base: "CN=Users,DC=bronet,DC=net"
ldap_uids: {"mail": “%u@bronet.net”}
```
here is error
```
[error] <0.38.0>@ejabberd_config:get_plain_terms_file:176
 Cannot load /etc/ejabberd/ejabberd.yml:
 Syntax error on line 216 at position 13: did not find expected key
```
Position 13 line 216 is the capital C for CN=Users

I have this exact same configuration on another server i put together a couple of months ago.

I am at a complete loss and have no idea where to go from here.

**Comment by zinid** [comment]
Maybe problems with quotation marks?
