### ISSUE TITLE
Can't boot ejabberd 16.04 on Ubuntu 14.04 with installer

### ISSUE THREAD

**Issue by CallMeSH** [processone/ejabberd#1140]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

I used the installer from the website

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I try to boot the app, I just get this crash logs:

```
2016-05-30 23:41:50.223 [error] <0.37.0> CRASH REPORT Process <0.37.0> with 0 neighbours exited with reason: call to undefined function mod_mam_mnesia:mod_opt_type(db_type) in application_master:init/4 line 134
2016-05-30 23:41:50.224 [info] <0.7.0> Application ejabberd exited with reason: call to undefined function mod_mam_mnesia:mod_opt_type(db_type)
```

I assume this logs are linked to mod_mam but unfortunately, this happens on a fresh install where it's not activated.
If you had any insights on where it can come from...

Thanks!

**Comment by weiss** [comment]
Try `ejabberdctl module-uninstall mod_mam_mnesia`.

**Comment by CallMeSH** [comment]
I'm trying to run the command from the bin directory like this:
`./ejabberdctl module_uninstall mod_mam_mnesia`
I also tried
`./ejabberdctl module-uninstall mod_mam_mnesia`

But both unfortunately fail to run.

```
Failed RPC connection to the node ejabberd@localhost: node down

Commands to start an jabbed node:
  start      Start an ejabberd node in server mode
  debug      Attach an interactive Erlang shell to a running jabbed node
  iexdebug   Attach an interactive Elixir shell to a running jabbed node
  live       Start an ejabberd node in live (interactive) mode
  iexlive    Start an ejabberd node in live (interactive) mode, within an Elixir shell
  foreground Start an ejabberd node in server mode (attached)
```

**Comment by weiss** [comment]
Ah indeed, that won't work if ejabberd isn't running :-)

Then you'll have to remove the old `mod_mam_mnesia` module manually.  It's below the `CONTRIB_MODULES_PATH`, which should be something like `~ejabberd/.ejabberd-modules` by default.

**Comment by CallMeSH** [comment]
That was the issue, I installed 15.11 a few month ago. It probably left that module there.
I didn't know that folder existed.
Thanks!
