### ISSUE TITLE
get_roster and get_offline_count not working with mod_rest

### ISSUE THREAD

**Issue by hdminh247** [processone/ejabberd#1143]
> What version of ejabberd are you using?

I am using ejabberd version 16.02 on Windows 10, I installed by setup.exe packet downloaded from ejabberd home page, 
I already configure mod_rest and mod_offline but I can not use get_roster and get_offine_count. It returns that "Error: the command "get_offline_count" requires 1 less argument."
if I use this "get_offline_count user1 localhost" while posting to http://localhost:5285/rest

**Comment by badlop** [comment]
Yes, there were changes in commands in March, so both ejabberd and the contributed modules were updated. So, if you try to use an old ejabberd from before March with recent modules, they may not work correctly. Try with 16.04
