### ISSUE TITLE
Why does ejabberd stop modules before closing c2s process

### ISSUE THREAD

**Issue by everimbaq** [processone/ejabberd#1144]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

centos 6.5

> How did you install ejabberd (source, package, distribution)?

source

I asked this question on stackoverflow:
http://stackoverflow.com/questions/37539342/why-does-ejabberd-stop-modules-before-closing-c2s-process

**Here is my question:**

I add some modules following the gen_mod behaviour in ejabberd to realize my private service, and add some hooks in these modules. This works well most time.
```
  ejabberd_hooks:add(unset_presence_hook, Host,
    ?MODULE, unset_presence_hook, 10),
```

But When I call ejabberdctl stop, ejabberd excecute the following code, I found that gen_mod:stop_modules() was done before broadcast_c2s_shutdown(), some hooks in ejabberd_c2s e.g. "unset presence hook" , cannot be excecuted because of my modules had been closed.

```
prep_stop(State) ->
    ejabberd_listener:stop_listeners(), 
    gen_mod:stop_modules(),
    ejabberd_admin:stop(),
    broadcast_c2s_shutdown(),
    timer:sleep(5000),
    State.
```

I would like to know Why does ejabberd stop modules before closing c2s process, or what is the purpose of this design?

**Comment by badlop** [comment]
Probably it was just a mistake. It's surprising nobody noticed since it was first committed six years ago: https://support.process-one.net/browse/EJAB-425

You can try to switch the order, does that solve your problem?:
```
--- a/src/ejabberd_app.erl
+++ b/src/ejabberd_app.erl
@@ -84,9 +84,9 @@ start(_, _) ->
 %% before shutting down the processes of the application.
 prep_stop(State) ->
     ejabberd_listener:stop_listeners(),
-    gen_mod:stop_modules(),
     ejabberd_admin:stop(),
     broadcast_c2s_shutdown(),
+    gen_mod:stop_modules(),
     timer:sleep(5000),
     State.
 
```

**Comment by everimbaq** [comment]
Thanks , it solved my problem.
I found this problem for days,  and it was easy to fix it. But I'm not sure about this, as ejabberd is very very stable and rarely has a problem, especially such an obovious problem.

**Comment by weiss** [comment]
It's probably just not a common case that some functionality relies on modules cleaning up session-related things during shutdown, so nobody noticed.  (But the fix looks good to me.)

**Comment by zinid** [comment]
The patch definitely worth commiting
