### ISSUE TITLE
No EJABBERD_BYPASS_WARNINGS option in YAML

### ISSUE THREAD

**Issue by perryao** [processone/ejabberd#1145]
> What version of ejabberd are you using?

16.04.43

> What operating system (version) are you using?

OS X El Capitan

> How did you install ejabberd (source, package, distribution)?
https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.04/ejabberd-16.04-osx-installer.app.zip

> What did not work as expected? Are there error messages in the log? What
When starting the server, I get the following message: 

```
IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue
```

As the message says, I can disable this warning with EJABBERD_BYPASS_WARNINGS=true in a .cfg file. I'm using YAML though, and I can't seem to get this option to work. I've tried adding the following to my config.yaml:

`EJABBERD_BYPASS_WARNINGS: true`

> was the unexpected behavior? What was the expected result?

I'd expect that a config option available in .cfg files would work in .yml files. Is there any documentation about all of the available config options using YAML? If not, where in the source might I look to determine available options.

**Comment by weiss** [comment]
> As the message says, I can disable this warning with EJABBERD_BYPASS_WARNINGS=true in a .cfg file. I'm using YAML though, and I can't seem to get this option to work.

This is an ejabberdctl (not ejabberd) configuration setting, and you specify that in the [ejabberdctl.cfg][1] file.  There's no YAML equivalent to that.

[1]: https://raw.githubusercontent.com/processone/ejabberd/master/ejabberdctl.cfg.example
