### ISSUE TITLE
RSM not working from 15.* onwards.

### ISSUE THREAD

**Issue by ggozad** [processone/ejabberd#1147]
Hey when upgrading from 14.* to anything > 15, inluding latest 16.04:

Everything seems to work fine migration wise and all our modules work fine.
When we use RSM for PubSub however the queries return no results and we cannot page.
On the same postgres db, running on 14.12:

```
<iq to="pubsub.localhost" type="get" xmlns="jabber:client" id="e82ee47a-7351-47ec-864e-c5ebc58497d9:sendIQ">
    <pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="/spaces/tx0igswlfpq6ug6938llubg51/infostream"/>
        <set xmlns="http://jabber.org/protocol/rsm">
            <max>20</max>
            <after>modification@001464:862157:793068</after>
        </set>
    </pubsub>
</iq>

<iq xmlns="jabber:client" from="pubsub.localhost" to="par5dkwuj1quf053h5ph6bx23@localhost/kxd9dfan0r1p9rbvj8j7gkw6a" id="e82ee47a-7351-47ec-864e-c5ebc58497d9:sendIQ" type="result">
    <pubsub xmlns="http://jabber.org/protocol/pubsub">
        <items node="/spaces/tx0igswlfpq6ug6938llubg51/infostream">
            <item id="5B8D27CD7D064">
               ....
            </item>
               ....
        </items>
        <set xmlns="http://jabber.org/protocol/rsm">
            <first index="20">modification@001464:862157:513534</first>
            <last>modification@001464:350313:393383</last>
            <count>25</count>
        </set>
    </pubsub>
</iq>
```

On > 14.12 we get as a response:
```
<iq xmlns="jabber:client" from="pubsub.localhost" to="par5dkwuj1quf053h5ph6bx23@localhost/qlp1f6qb4fk5dhj15oofkz1q0" id="cd599a75-6281-49f5-bf10-c6078467ff95:sendIQ" type="result">
    <pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="/spaces/tx0igswlfpq6ug6938llubg51/infostream"/></pubsub>
</iq>
```

With no entries.

ejabberd is installed from source in all cases, tried on Debian and OSX.

**Comment by ggozad** [comment]
Let me know if I can provide any additional feedback. I didn't see anything happening in the logs.

**Comment by cromain** [comment]
can you dump sql queries on your pgsql corresponding to that rsm request ?

**Comment by ggozad** [comment]
Hey @cromain ,
You are right this is a db issue.

The offending query is:

``select itemid, publisher, creation, modification, payload from pubsub_item where nodeid='1' and modification is not '001464:862157:793068' order by modification desc limit 20 ;``

which leads to a syntax error on "is not".

For reference, in 14.12 the query is:

``select itemid, publisher, creation, modification, payload from pubsub_item where nodeid='1' and modification < '001464:862157:793068' order by modification desc limit 20 ;``

**Comment by cromain** [comment]
Thanks for confirming this, this bug was injected after 15.06 as part of cleanup in e0563e39.
I'll fix this.

**Comment by ggozad** [comment]
A pleasure, let me know if I can help further.

**Comment by cromain** [comment]
there are two things to check if we apply original tests to build rsm request (patch bellow)
```
--- a/src/node_flat_sql.erl
+++ b/src/node_flat_sql.erl
@@ -686,13 +686,11 @@ get_items(Nidx, _From,
            #rsm_in{max = M, direction = Direction, id = I, index = IncIndex}) ->
     Max = ejabberd_sql:escape(jlib:i2l(M)),
     {Way, Order} = case Direction of
-       %     aft -> {<<"<">>, <<"desc">>};
-       %     before when I == <<>> -> {<<"is not">>, <<"asc">>};
-       %     before -> {<<">">>, <<"asc">>};
-       %     _ when IncIndex =/= undefined ->
-       %         {<<"<">>, <<"desc">>}; % using index
-       _ ->
-           {<<"is not">>, <<"desc">>}% Can be better
+            aft -> {<<"<">>, <<"desc">>};
+            before when I == <<>> -> {<<"is not">>, <<"asc">>};
+            before -> {<<">">>, <<"asc">>};
+            _ when IncIndex =/= undefined -> {<<"<">>, <<"desc">>};
+            _ -> {<<"is not">>, <<"desc">>}
     end,
     SNidx = integer_to_binary(Nidx),
     [AttrName, Id] = case I of
```

while it make rsm request work again it raises two questions to me:
- if you ask rsm after X, we get items with modification older than X. this is correct from rsm point of view but the reverse order from item date point of view. i'm not expert with rsm but the actual implementation looks good anyway.
- we still have "is not" cases which produce broken sql query, we still need to fix the "is not" case

**Comment by cromain** [comment]
order looks good, and "is not" can only be used as "is not null" and it works as expected. all seems fixed.
