### ISSUE TITLE
Extendable mod_roster

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd#1148]
The mod_roster module is not extendable. It is hardcoded via gen_mod to have implementations named 'mod_roster_mnesia', 'mod_roster_riak' or 'mod_roster_sql'.

I've been trying to add a new implementation working like extauth so that we can load rosters via an external script but this does not seem possible without modifying either mod_roster.erl or gen_mod.erl.

**Comment by RobertLarsen** [comment]
I just realized that this is a quite large feature request but I stand by it. Having a fourth "_ext" database type for all modules that require storage would provide the user with a much broader flexibility.

**Comment by zinid** [comment]
Why isn't it possible? Isn't mod_roster behaviour not enough for your goal?

**Comment by RobertLarsen** [comment]
I'm on thin ice here as I'm only just beginning to learn Erlang, but as I read the code mod_roster will load an initialize a roster implementation named mod_roster_(db_type) and the only values accepted as db_type are 'sql', 'mnesia' or 'riak' and those names are taken and implemented. If I tried loading my such as:

         mod_roster:
             db_type: ext

...I get this in the ejabberd.log file:
    @gen_mod:validate_opts:275 ignoring invalid value 'ext' for option 'db_type' of module 'mod_roster'

Or am I just reading it wrong?

**Comment by RobertLarsen** [comment]
Surprise surprise. It turns out I didn't read the code correctly and you can put anything as the db_type as long as you have installed a module by that name.
