### ISSUE TITLE
Database got slow and started  droping   queries 

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#1150]
> What version of ejabberd are you using?

Ejabberd 15.11

> What operating system (version) are you using?

Linux (ubuntu 14.04 )

> How did you install ejabberd (source, package, distribution)?

package 

> What did not work as expected? Are there error messages in the log? What
mod
> was the unexpected behavior? What was the expected result?

i am using postgres 9.3 database , recently started facing this issue of database not available or too slow and all queries getting drop after this appears on my error log . 

 Error log : 
 ```
2016-06-07 05:51:42.339 [error] <0.393.0>@ejabberd_odbc:run_sql_cmd:382
 Database was not available or too slow, discarding 102474 milliseconds old request
 {sql_query,[<<"select xml from motd where username='';">>]}
2016-06-07 05:51:42.339 [error] <0.393.0>@ejabberd_odbc:run_sql_cmd:382
 Database was not available or too slow, discarding 102447 milliseconds old request
 {sql_query,[<<"select xml from motd where username='';">>]}
2016-06-07 05:51:42.339 [error] <0.393.0>@ejabberd_odbc:run_sql_cmd:382
 Database was not available or too slow, discarding 102269 milliseconds old request
 {sql_query,[<<"select password from users where username='">>,<<"918528886518">>,<<"';">>]}
2016-06-07 05:51:42.339 [error] <0.393.0>@ejabberd_odbc:run_sql_cmd:382
 Database was not available or too slow, discarding 101491 milliseconds old request
 {sql_query,[<<"select name from privacy_default_list where username='">>,<<"vhcvhvjsdv4388769">>,<<"';">>]}
```

**Comment by mremond** [comment]
It does not seem to be an ejabberd issue, right ? It looks like ejabberd is doing the right thing.
