### ISSUE TITLE
Messages lost: Maybe incorrect usage of Stream Management

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1151]
> What version of ejabberd are you using?

ejabberd 16.03.92

> What operating system (version) are you using?

Debian GNU/Linux 8.4 (jessie)

We are experiencing some problems of messages lost on dead connections.
Basing myself on your article: https://www.ejabberd.im/faq/tcp
I've enabled Stream Management on my system. Also I've configured _resend\_on\_timeout_ to **true** (it seems a safer option than **if_offline**). However we are still losing some messages.

So my questions are:

- Is it true that _resend\_on\_timeout_: **true** is "safer" than **if_offline**?
- Which could be a proper value to be assigned to the variable _resume\_timeout_?
- Is there any other variable that could be involved, and that maybe we have to adjust?

And a bonus question:

The problem exposed on your FAQ (linked above) is also solved for MUC rooms with the Stream Management? I mean if the messages sent on a room while the user is offline, have to be received (resent) when the client resumes the connection? Do I have to change any other setting to prevent this messages lost on MUC rooms with Stream Management?

Many thanks,

Joan

**Comment by weiss** [comment]
> Is it true that `resend_on_timeout: true` is "safer" than `if_offline`?

Depends on your definition of "safe".  As I tried to explain in that FAQ entry, I would *only* consider setting this to `true` if you *know* that none of your users will be online with multiple clients in parallel (i.e., only if you control the clients).

> Which could be a proper value to be assigned to the variable `resume_timeout`?

The default value (300 seconds) should usually be fine.  From looking at my own logs, most clients that resume their session do that within this timeframe.

> Is there any other variable that could be involved, and that maybe we have to adjust?

Are you sure the client is actually using stream management?  What client/library are you using?

If you're sure, and if you're nevertheless experiencing message loss (without error bounces being generated), you should try to track down whether the lost messages made it to the server in the first place.  You could set `loglevel: 5` or use the [`mod_logxml`][1] module on the server side, and if possible also dump the XML stream on the client side.

> The problem exposed on your FAQ (linked above) is also solved for MUC rooms with the Stream Management?

The stream management code handles incoming MUC messages just like incoming 1:1 stanzas.  So if the client resumes the session during the `resume_timeout` period, it will receive any MUC messages it missed.  If the client doesn't resume the session, it won't receive those messages.

The main XEP-0198 feature is session resumption.  For reliable message delivery, you will (also) want to use XEP-0313 both for 1:1 and for MUC messages.

[1]: https://github.com/processone/ejabberd-contrib/tree/master/mod_logxml

**Comment by joanlopez** [comment]
Thanks @weiss.

Reviewing my Ejabberd's config I've seen that the resume_timeout is set to zero.

Could it be the problem? 

Thanks!!!

**Comment by weiss** [comment]
> Reviewing my Ejabberd's config I've seen that the `resume_timeout` is set to zero.

That way, clients won't be able to resume a session.  The code should still make sure that all messages are either delivered or bounced (depending on `resend_on_timeout`).

**Comment by joanlopez** [comment]
Yes, if I understood well the functionality, yes.

Theoretically the messages loss only should appear on MUC rooms, no? (The resume timeout was set to zero).

Could be a problem of the client-side libraries?

Do you have knowledge on XMPPFramework (iOS) and/or Smack (Android)?

We think that theoretically we are doing a right usage of Stream Managament on these libraries.

Many thanks @weiss

**Comment by weiss** [comment]
> Do you have knowledge on XMPPFramework (iOS) and/or Smack (Android)?

I've never used either of those libraries, no.  But I know that stream management works with both of them for others.

**Comment by joanlopez** [comment]
Does it mean that I shouldn't lost messages?

So, If I have configured well the parameters mentioned above and I'm still losing messages, the problem is with the client?

Thanks!

**Comment by weiss** [comment]
> So, If I have configured well the parameters mentioned above and I'm still losing messages, the problem is with the client?

I'd try to track down what's happening as I [suggested above][1].

[1]: https://github.com/processone/ejabberd/issues/1151#issuecomment-224682624

**Comment by joanlopez** [comment]
Hi @weiss, i'm still reviewing this issue and I have some questions related:

- What do you mean by ```without error bounces being generated```?
Where I can find more info about these error messages?
Should the clients make any additional check?

- If we have set Stream Management to true but we have ```resume_timeout``` equal to 0, does it mean we are really not using Stream Management? And only relying on ```resend_on_timeout```?

We are still experiencing loss but very very occasional and only with few users, but I don't know how to track it neither how to reproduce it.

If we have the following configuration:

```
    stream_management: true
    resend_on_timeout: true
    resume_timeout: 0
```

In what situations we could have a loss?

Thanks a lot!

**Comment by weiss** [comment]
> Where I can find more info about these error messages?

You won't receive them with `resend_on_timeout: true`.

> If we have set Stream Management to true but we have ```resume_timeout``` equal to 0, does it mean we are really not using Stream Management? And only relying on ```resend_on_timeout```?

I responded to this in [one of my comments above][1].  You still get the guarantee that all messages received by the server are either delivered to the recipient or bounced back as an error to the sender (depending on `resend_on_timeout`).  But the server closes the session as soon as it notices the connection is lost, so at that point, the client no longer has the chance to [resume][2] it.

> We are still experiencing loss but very very occasional and only with few users, but I don't know how to track it

I made some suggestions [above][3].  

[1]: https://github.com/processone/ejabberd/issues/1151#issuecomment-224686057
[2]: https://xmpp.org/extensions/xep-0198.html#resumption
[3]: https://github.com/processone/ejabberd/issues/1151#issuecomment-224682624
