### ISSUE TITLE
mod_mam callback failed - archive_prefs

### ISSUE THREAD

**Issue by ronnicek** [processone/ejabberd#1153]
> What version of ejabberd are you using?

ejabberd v3.4.0.160 (16.04-r1)

> What operating system (version) are you using?

Alpine Linux in Docker

> How did you install ejabberd (source, package, distribution)?

distribution (edge/testing)

> What did not work as expected?

Client (Gajim) says Online (not synced) and I can't load messages in client on mobile (Monal)

> Are there error messages in the log? 

Yes every message I send generate following error:

```
ejabberd_1     | 23:23:37.657 [error] callback failed:
ejabberd_1     | ** Tab: archive_prefs
ejabberd_1     | ** Owner: <0.38.0>
ejabberd_1     | ** Operation: lookup
ejabberd_1     | ** Args: [{<<"MYUSERNAME">>,<<"DOMAIN.net">>}]
ejabberd_1     | ** Reason: {aborted,{no_exists,[sql_pool,<<"DOMAIN.net">>]}}
```

> What was the unexpected behavior? What was the expected result?

Client should be synced and I should be able to load old messages on another client which have implemented support of mod_mam

> Configuration file looks like this:

  mod_mam:
    db_type: odbc

**Comment by qimingzhizuimafanle** [comment]
Client should be synced and I should be able to load old messages on another client which have implemented support of mod_mam
