### ISSUE TITLE
ejabberd mysql timeout

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1154]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

CentOS Linux release 7.1.1503 (Core)

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

error.log is printing continuously @ejabberd_odbc:log:665 p1_mysql_conn: post_start timeout
ejabberd is crashing.
crash dump is as follows
```
=erl_crash_dump:0.3
Tue Jun 14 17:34:25 2016
Slogan: Kernel pid terminated (application_controller)
 ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,
  {shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
System version: Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe]
 [kernel-poll:false]
Compiled: Tue Jan 19 13:05:22 2016`
```

> was the unexpected behavior? What was the expected result?

**Comment by badlop** [comment]
The EXIT nodistribution error is tracked here: https://github.com/processone/ejabberd/issues/1158
