### ISSUE TITLE
Enable STUN/TURN feature in ejabberd

### ISSUE THREAD

**Issue by bigoloo** [processone/ejabberd#1155]
I am using ejabberd 16.04 /Ubuntu/Docker and source compiled version 
I have installed ejabberd_stun with the following configuration:

  port: 3478
  transport: udp
  use_turn: true
  auth_type: user
  auth_realm: "X.X.X.X"
  turn_ip: "same as above(my public ejabberd ip)"
  module: ejabberd_stun
Things are working as expected in development (local) but when we move to production voice call doesn't seems to work .

It seems NAT is not working.

Do I have to configure anything specific to production environments? If not then what could be the possible reason & how to proceed to debug it further? Any help would be appreciated.

**Comment by bigoloo** [comment]
PS: my server is in a public server ,it is okay when both of my client exist in a same network, but in public they can't have voice call .

**Comment by zinid** [comment]
Note that STUN/TURN server should not be NAT'ed.

**Comment by bigoloo** [comment]
@zinid  do you mean ejabberd as STUN/TURN shouldn't install in docker !?

**Comment by zinid** [comment]
If docker is NAT'ed, then yes.
Actually, no STUN/TURN server can operate behind NAT, this is by design.
