### ISSUE TITLE
Pubsub performance issue

### ISSUE THREAD

**Issue by sezuan** [processone/ejabberd#1156]
> What version of ejabberd are you using?

15.07

> What operating system (version) are you using?

Ubuntu 12.04

> How did you install ejabberd (source, package, distribution)?

Source

It appears that with a large number of nodes and very large number of subscriptions and/or configured members and publishers publishing becomes very slow.

Some numbers: I've about 10-15k nodes with about 200k entries in pubsub_state. The iq response needs about 30-40 seconds. etop shows a large message queue in mod_pubsub in the function ets:select. That's probably in https://github.com/processone/ejabberd/blob/4ccc40bce/src/node_flat.erl#L677. This saturates one cpu core.

**Comment by cromain** [comment]
Hello

with such volumes on ejabberd Community Server, you should switch your pubsub backend to sql, as mnesia backend is not supposed to handle this load.
