### ISSUE TITLE
modules_available returns nothing after modules_update_specs

### ISSUE THREAD

**Issue by ygoodmn** [processone/ejabberd#1157]
> What version of ejabberd are you using?

ejabberd-16.01 (also tried ejabberd-16.04)

> What operating system (version) are you using?

CentOS Linux release 7.2.1511 (Core)

> How did you install ejabberd (source, package, distribution)?

RPM via ansible
```
_- name: install the ejabberd rpm from a remote repo
  yum: name=https://www.process-one.net/downloads/ejabberd/16.01/ejabberd-16.01-0.x86_64.rpm state=present
  when: not ejabberd_installed.stat.exists
  sudo: yes_
```

> What did not work as expected? Are there error messages in the log? What

Ran 
```
$/opt/ejabberd-16.01/bin/ejabberdctl modules_update_specs
ok
$/opt/ejabberd-16.01/bin/ejabberdctl modules_available
$
```
Does not return anything.
No, no errors in log, did see connection to github in tcpdump.

> was the unexpected behavior? What was the expected result?

available would return available modules, 
we need mod_restful

**Comment by badlop** [comment]
The problem is that ejabberd can't download the repository. How to reproduce:
```
httpc:request(get, {"https://github.com/processone/ejabberd-contrib/archive/master.zip", []}, []++[]++[], []).
{ok,{{"HTTP/1.1",400,"Bad Request"},
     [{"date","Fri, 17 Jun 2016 09:30:33 GMT"},
      {"vary","Authorization,Accept-Encoding"},
      {"content-length","21"},
      {"access-control-allow-origin",
       "https://render.githubusercontent.com"},
      {"content-security-policy",
       "default-src 'none'; style-src 'unsafe-inline'"},
      {"strict-transport-security","max-age=31536000"},
      {"x-content-type-options","nosniff"},
      {"x-frame-options","deny"},
      {"x-xss-protection","1; mode=block"},
      {"x-github-request-id","51CA4B81:0417:3D4B3:5763C339"}],
     "400: Invalid request\n"}}
```

**Comment by undev0** [comment]
I am currently having the same issue on ejabberd-16.04.. Is there another way to install modules ?

**Comment by badlop** [comment]
Until the problem is fixed, you can download yourself the ejabberd-contrib git repository, and copy it to $HOME/.ejabberd-modules/sources/ejabberd-contrib then proceed with the module_install call.

**Comment by undev0** [comment]
Thanks, but when I execute the module_install command I get "Error: not_available". Any ideas ?

**Comment by systemidx** [comment]
I think mod_restful is broken under 16.04 (release) anyway. Make sure that the directory structure is as @badlop specified and that your ejabberd.cfg has the correct root folder you're extracting to specified.

**Comment by undev0** [comment]
Finally, it has to be added in this folder : /opt/ejabberd-16.04/.ejabberd-modules. Thanks.

**Comment by badlop** [comment]
I found a simple workaround: when using HTTP/1.0 instead of the default 1.1, github accepts the request and all works correctly...
