### ISSUE TITLE
ejaberred crashed with Kernel pid terminated

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1158]
> What version of ejabberd are you using?
ejabberd 16.02

> What operating system (version) are you using?
CentOS Linux release 7.1.1503 (Core)

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Below is the crash dump

`=erl_crash_dump:0.3
Thu Jun 16 14:44:30 2016
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
System version: Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
Compiled: Tue Jan 19 13:05:22 2016
Taints:
Atoms: 5156
=memory
total: 9313160
processes: 3434448
processes_used: 3421520
system: 5878712
atom: 140441
atom_used: 127112
binary: 149232
code: 2933604
ets: 64264`

**Comment by vijayaa** [comment]
what is the reason behind this.Continuously it is crashing when we try to register users

**Comment by badlop** [comment]
Erlang found a problem setting up the node connection, that is, the small ejabberdctl node couldn't connect to your existing ejabberd node.

I found a similar error report in this old thread:
http://erlang.org/pipermail/erlang-questions/2015-October/086270.html
And replied himself the problem in his case, and his solution:
> problem solved. it turns out that it was due to a faulty iptables rule set.  whew!

**Comment by vijayaa** [comment]
But my issue is we are using a node.js child_process.exec to execute `ejabberdctl register <username> <host> <password>'  in a loop, which is causing ejabberd to crash

**Comment by badlop** [comment]
Using a node.js in a loop: if you run the command only one time, does the problem appear? Or it only appears if you run the command many times in a small moment?

Maybe ejabberdctl needs a full commandline console to work correctly, and doesn't work correctly in that node.js thing. In that case, you can try to execute the command using other methods instead of ejabberdctl. Try ejabberd_xmlrpc, or mod_rest.

**Comment by vijayaa** [comment]
if i run command only one at a time there is no problem. As node.js works asynchronously this is giving problem

**Comment by cromain** [comment]
calling ejabberdctl in a loop is bad practice and raises several issues such as yours.
you are fireing up more node than allowed by calling too fast (maybe iptables limitation, reach ulimit, etc...) each ejabberdctl node needs to be able to open a socket. here you can't open socket.

if you really want to use such process, either add dirty sleep between calls or don't fire ejabberdctl at all. use ejabberd http api as badlop suggested.

**Comment by mremond** [comment]
You should always ensure ejabberdctl cannot be running more than once in parallel. We have an ejabberd API to integrate with backends, which is much more suited than using ejabberdctl script (which is design for manual admin work).
