### ISSUE TITLE
ejabberd xmpp over bosh very slow delay

### ISSUE THREAD

**Issue by ahmetsevinc77** [processone/ejabberd#1159]
> What version of ejabberd are you using?
16.04 (latest)

> What operating system (version) are you using?
debian

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

BOSH has been setup successfully on ejabberd 16.04 and connected through Pidgin clients via BOSH URL as http://myserver:5280/http-bind in the settings. However when sending and receiving messages between clients there is a loooong delay until the message reaches the recipient; almost around the 1 minute mark until it is seen by the receiving party.

Why is this happening this is a very serious problem for instant messaging using BOSH.

Looking forward to your urgent reply..

Kev

**Comment by prefiks** [comment]
This is most likely problem with pidgin plugin, looks like it waits until active request got response from server even if it has data to send, this is not how clients should handle this situation (if they have new data to deliver they should immediately send another requests with that data).

There is nothing server can do to fix this, you may try different client or switch to native xmpp connection in pidgin to get better results.
