### ISSUE TITLE
Suddenly stop and some inet_gethost_native ejabberd stop working

### ISSUE THREAD

**Issue by mckaygerhard** [processone/ejabberd#1164]
> What version of ejabberd are you using?

13.12

> What operating system (version) are you using?

debian 7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

clients of same resource id could not connect, and later after restart if connect few minutes later all clients disconnect, i have 560 users concurrently using postgres by odbc

sysnet:/var/log/ejabberd# tail erlang.log 
             started: [{pid,<0.418.0>},{mfa,{inet_gethost_native,init,[[]]}}]

=PROGRESS REPORT==== 22-Jun-2016::12:27:22 ===
          supervisor: {local,kernel_safe_sup}
             started: [{pid,<0.417.0>},
                       {name,inet_gethost_native_sup},
                       {mfargs,{inet_gethost_native,start_link,[]}},
                       {restart_type,temporary},
                       {shutdown,1000},
                       {child_type,worker}]
sysnet:/var/log/ejabberd#

**Comment by mremond** [comment]
There is not enough information to understand what is your issue. My suggestion would be to start by upgrading to latest version. A lot has changed in nearly three years.
