### ISSUE TITLE
mnesia2sql export fails

### ISSUE THREAD

**Issue by dl8bh** [processone/ejabberd#1166]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

FreeBSD 10.3

> How did you install ejabberd (source, package, distribution)?

FreeBSD Ports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to migrate from mnesia to sql.
Exporting the mnesia tables to sql with
> ejabberdctl export2sql example.com example.sql

failed (see error-message below).
Using the way from processone manual using the ejabberdctl debug console failed with a similar message.
```
root@jabber-1:~ # ejabberdctl export2sql example.com example.sql
Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_announce_mnesia,export,[<<"example.com">>],[]},
             {ejd2sql,export,3,[{file,"src/ejd2sql.erl"},{line,80}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,68}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]}]
```

**Comment by timeos** [comment]
hi
please check here: https://github.com/processone/ejabberd/issues/1118

**Comment by badlop** [comment]
Try this, as explained in #1118:

1. Configure the modules to use SQL. This means adding the option db_type: sql to all those modules:
mod_announce
mod_caps
mod_irc
mod_last
mod_muc
mod_offline
mod_privacy
mod_private
mod_pubsub
mod_roster
mod_shared_roster
mod_vcard
mod_vcard_xupdate

2. Restart ejabberd

3. Execute the export2sql command

**Comment by dl8bh** [comment]
Thank you both, finally I got the time to test your suggestion and it worked perfectly! I think this behaviour should be documented, but for now, this issue can be closed!

**Comment by jhaoheng** [comment]
Hello @badlop 

I set module follow your steps.
but i get an error `unknown option 'db_type' for module 'mod_vcard_xupdate' will be likely ignored, available options are: cache_missed, use_cache, cache_size, cache_life_time`

**Comment by zinid** [comment]
@jhaoheng `mod_vcard_xupdate` doesn't store anything on disc since `17.06`, you can ignore the warning or remove `db_type` option from `mod_vcard_xupdate`.
