### ISSUE TITLE
ERROR: compile failed while processing ejabberd/deps/fast_xml: rebar_abort

### ISSUE THREAD

**Issue by RobWJacob** [processone/ejabberd#1168]
> What version of ejabberd are you using?

todays master on https://github.com/processone/ejabberd.git

> What operating system (version) are you using?

ubuntu server 12.04.5 lts

> How did you install ejabberd (source, package, distribution)?

try to install from source as described on https://github.com/processone/ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

on make i get the error
ERROR: compile failed while processing /root/installs/ejabberd/deps/fast_xml: rebar_abort

i also do /usr/lib/erlang/bin/escript rebar get-deps
and i installed erlang-parsetools
same error

==> fast_xml (compile)
ejabberd/deps/fast_xml/src/fxml.erl:51: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:72: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:82: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:93: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:107: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:132: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:141: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:153: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:162: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:177: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:191: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:203: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:214: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:225: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:239: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:258: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:270: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:293: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:320: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:334: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:345: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:366: syntax error before: '/'
ejabberd/deps/fast_xml/src/fxml.erl:384: syntax error before: '/'
ERROR: compile failed while processing ejabberd/deps/fast_xml: rebar_abort
make: *** [deps/.built] Error 1

**Comment by prefiks** [comment]
Hello, it looks like you trying to compile this using too old version of erlang that don't recognize syntax that we are using, would you be able to tell me what "erl +V" returns on that system?

**Comment by RobWJacob** [comment]
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.0

dpkg -s erlang says
Version: 1:19.0-1
?

ubuntu packages says 
Paket erlang
precise (12.04LTS) (interpreters): Concurrent, real-time, distributed functional language [universe] 
1:14.b.4-dfsg-1ubuntu1: all

**Comment by prefiks** [comment]
This is probably R19 then, this version is right now not supported yet (this version was released two days ago, and we still work on fixing problems that this introduced). Right now you can only use erlang version 17.X or 18.X

**Comment by RobWJacob** [comment]
ah ok.
i installed erlang 18.3.1 and now it works.

**Comment by RobWJacob** [comment]
hm, now i get an error / crash when i start ejabberd
[error] CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: no match of right hand value {error,{bad_lib,"Library version (2.11) not compatible (with 2.10)."}} in fast_tls_app:start/2 line 53 in application_master:init/4 line 13

**Comment by prefiks** [comment]
You probably had parts compiled with r19 and parts with r18, and now some parts that were compiled in r19 can't be loaded when you are using erlang r18 for ejabberd, please try executing "make clean; make", this should give you version without that problem.

**Comment by RobWJacob** [comment]
perfect. thx.

**Comment by mremond** [comment]
Closing, as we are tracking issue in fast_xml repository.

**Comment by zinid** [comment]
@mremond we have also this issue in ejabberd itself (mod_pubsub for instance). It is that compile process doesn't reach ejabberd source because it's failed on dependency building, so we don't face it so far.
