### ISSUE TITLE
MAM mysql: messages with emoticons not stored at all

### ISSUE THREAD

**Issue by v10star** [processone/ejabberd#1172]
On ubuntu 16.04 i've installed ejabberd 16.01 from repo (and all other related dependencies and contribs) (http://packages.ubuntu.com/xenial/net/ejabberd). All is working fine except emoticons on mysql MAM db: the message is not saved at all.

i've found this discussion that speak about this problem: https://github.com/processone/ejabberd/issues/723

Now: how i can fix this?

1 - update ejabberd to 16.04 (this problem is fixed on 16.02) but from ubuntu repo ejabberd 16.01 is the latest version available
2 - correct manually
3 - switch to another db (i don't know postgre and i don't want get rid of mysql for easiest administration)

thanks

**Comment by zinid** [comment]
> 2 - correct manually

^^^ This
Try to apply (using ALTER or whatever) the most recent mysql schema: https://github.com/processone/ejabberd/blob/master/sql/mysql.sql
I'm not sure if this patch is needed as well: https://github.com/processone/ejabberd/commit/b2c6e397fc26ce9dd8372e6a32e1a07bf413875d
Anyway, if it doesn't work without the patch, you can apply it to 16.01 sources, recompile and copy resulting `ejabberd_odbc.beam` into `ebin` directory of running ejabberd. You can restart ejabberd or reload it on the fly. If you choose to reload, you can do it using remsh:
```
$ ejabberdctl debug
...
> l(ejabberd_odbc).
```
This is hacky, but would work for you.

**Comment by zinid** [comment]
Ah, my bad, patching requires restart (either ejabberd or mysql).

**Comment by v10star** [comment]
i'm using mysql only for mam: users and other ejabberd stuff are stored on mnesia. Tecnically, the only table written by ejabberd is "Archive". I need to alter whole db? below actual parameters of db.
p.s.
my knowledge of mysql  is very poor and i apologize for probably silly questions :smile: 
![cattura](https://cloud.githubusercontent.com/assets/20162042/16409962/6f93cfd8-3d20-11e6-9267-06d949c26385.GIF)
![cattura1](https://cloud.githubusercontent.com/assets/20162042/16409961/6f919f24-3d20-11e6-81f6-f4f210016410.GIF)

**Comment by zinid** [comment]
According to the screenshot your table is fine, you don't need to alter anything.

**Comment by v10star** [comment]
so, back to solution nr1/3 or wait repo update?

**Comment by zinid** [comment]
I'm not sure why emojis are not working for you. Try to write some emoji in any table (`archive` for instance) via mysql command line interface to check if mysql is not rejecting them.

**Comment by Nitin3589** [comment]
I just updated with latest release  Mysql5.7 , i was facing the same issue but after upgrade it has been resolved . i think it is related to database only .

**Comment by v10star** [comment]
i've rebuild the server from scratch starting from ubuntu 16.10. With ejabber 16.04 (I've updated yesterday to 16.06 and) the problem is gone. now text with message is correctly written to db and no more text is lost. the only (but for me irrilevant) issue is from android/conversations: all emoticons data are exchanged by a question mark. From gajim this not happen

**Comment by zinid** [comment]
I'll close the current issue. Feel free to open a ticket related to Conversations if you think there is a problem in ejabberd.
