### ISSUE TITLE
Stream start elements sent before errors do not have a version attribute

### ISSUE THREAD

**Issue by SamWhited** [processone/ejabberd#1174]
> What version of ejabberd are you using?

Tested against `conversations.im` and `jabber.at` (both running 16.04):

    conversations.im is running ejabberd version 16.04.95 on unix/linux 3.16.0
    jabber.at is running ejabberd version 16.04 on unix/linux 3.16.0

> What did not work as expected?

When sending a stream start that contains an error (eg. missing `to` attribute) but which clearly specifies `version='1.0'`, ejabberd replies with a start stream that does not contain a version (signifying version 0.9). This causes some strict clients that don't support 0.9 to respond to ejabberd's error with a new terminal stream error (unsupported-version) when they parse the opening stream tag.

> was the unexpected behavior? What was the expected result?

The expected result would be for Ejabberd to always include a version that matches the one advertised by the client (if supported by ejabberd, of course) just as it does when responding successfully (eg. if it sends an open stream tag followed by features, that stream tag contains a version as you'd expect).

```bash
~ $ telnet jabber.at 5222
Trying 128.130.95.26...
Connected to jabber.at.
Escape character is '^]'.
<stream:stream version='1.0' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>
<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='9918549630644049951' from='anon.jabber.at' xml:lang='en'><stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'></host-unknown></stream:error></stream:stream>Connection closed by foreign host.
```

**Comment by prefiks** [comment]
Fixed by commit 3446aba753625060af68396c6edd8e76a4950a61
