### ISSUE TITLE
modules_update_specs command does not retrieve the modules

### ISSUE THREAD

**Issue by BesatZardosht** [processone/ejabberd#1175]
> What version of ejabberd are you using?
16.03

> What operating system (version) are you using?
OS X Yosemite

> How did you install ejabberd (source, package, distribution)?
Binary Installer

> What did not work as expected? Are there error messages in the log? What
installation is done completely and ejabberd starts 
> was the unexpected behavior? What was the expected result?

After installation completed I started ejabberd:

When I try to retrieve the list of available modules:

`./ejabberdctl modules_update_specs`
and it says ok! but it does not get the modules! I get nothing by running this:
`./ejabberdctl modules_available`
And I cannot install any module.

 I cloned the modules form the source and put it in the Users/myuser/.ejabberd-modules/source folder and when I run modules_available it shows the list but if I run modules_update_specs it remove the ejabberd-contrib folder and shows nothing in the module list!!

**Comment by mremond** [comment]
Duplicates #1157
