### ISSUE TITLE
Unable to compile on OSX Maverick.  Libyaml not found

### ISSUE THREAD

**Issue by josephmartin09** [processone/ejabberd#118]
Hello,  I have tried the compilation many times using libyaml installed both via brew (an OSX package manager), and manual compilation via the source at this link: http://pyyaml.org/wiki/LibYAML .  I always get the same error listed below when I run make (after running ./configure) :

checking yaml.h usability... no
checking yaml.h presence... no
checking for yaml.h... no
configure: error: libyaml library was not found

I have manually inspected and verified that yaml.h is in my /usr/local/include directory.  Are there any suggestions you could provide me on this one?

Thanks,
     Joe

**Comment by sushantblobcity007** [comment]
Thanks mahn @sanketsarang you are a live saver!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by andraus** [comment]
Solved it in Yosemite with `brew install libyaml`.

**Comment by cauboy** [comment]
For me just running ```brew install libyaml``` didn't help. I needed to run:
```
export CFLAGS=-I/usr/local/include/
export LDFLAGS=-L/usr/local/lib/
make && make install
```
Reference:
[https://github.com/processone/ejabberd/issues/422](https://github.com/processone/ejabberd/issues/422)
