### ISSUE TITLE
Sending special IRC characters

### ISSUE THREAD

**Issue by iwalkalone69** [processone/ejabberd#1180]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Distribution.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've made modifications in my fork to disable filtering the bold and color special IRC characters. This is working well on received stanzas from websocket and I can display it properly. However, this is not working well when sending messages as it fails with an invalid xml.

The special characters are:
\x02 - Bold
\x03 - Color

I understand that this is also related to the fast_xml library. For us it is important to support colors and the rest of special characters but I can't figure it how to solve this. Can you help, please?

Thanks in advance.

**Comment by mremond** [comment]
It looks indeed like invalid XML. You cannot use them on in XMPP stream. If you need to support color, you would need to map IRC color with XMPP XHTML message rendering and do the conversion possibly in both direction (depending on what you want to achieve).
