### ISSUE TITLE
CRASH REPORT <...> no case clause matching <...> in cyrsasl_plain:prepare/1 line 61 in p1_fsm:terminate/8 line 760

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1181]
> What version of ejabberd are you using?

16.03.

> What operating system (version) are you using?
Linux <scr> 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64 GNU/Linux

Debian Jessie 8.5.

> How did you install ejabberd (source, package, distribution)?

From the Debian repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Since the last update (16.02-2 > 16.03-1) there is one particular crash flooding the log:

`2016-06-30 12:50:35.324 [error] <0.17577.0> CRASH REPORT Process <0.17577.0> with 0 neighbours exited with reason: no case clause matching [<<"SomeUsernameHere">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>,<<"mydomain.tld">>] in cyrsasl_plain:prepare/1 line 61 in p1_fsm:terminate/8 line 760`

There are lot of different usernames in place of _SomeUsernameHere_. The error occurs constantly, 2-5 times per second, and as a result my typical CPU usage of 3-5% raised to enormous 20-30%. And I expect some functionality is not working as expected too.
As far as I understood, the _cyrsasl_plain_ is some ejabberd's module.

**Comment by mremond** [comment]
Which client is generating this trace ?

**Comment by mremond** [comment]
We crash only the relevant session. ejabberd Service itself does not crash.

And yes, it looks like a dumb bot that has broken auth implementation.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
So. Nothing to do with this from the ejabberd's side?

**Comment by IUnderstandLetsChangeMyUsername** [comment]
To those concerned the high CPU load and module crash can be resolved with the activation of ejabberd's fail2ban module:

  mod_fail2ban:
    c2s_auth_ban_lifetime: 259200
    c2s_max_auth_failures: 10
