### ISSUE TITLE
ejabberd 16.06 retrieve offline message via web admin getting "Not Found"

### ISSUE THREAD

**Issue by lxnx0** [processone/ejabberd#1183]
Hi all,

I just upgraded to version 16.06. It could be a possible bug on web admin screen to retrieve offline message for specified user. Getting "Not Found" even there are few offline message for that user.

> What version of ejabberd are you using?
16.06

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
Installer

> What did not work as expected? Are there error messages in the log?
Web admin, retrieve offline message for specified user.

> What was the unexpected behavior? What was the expected result?
All offline message will be displayed correctly.

**Comment by badlop** [comment]
Yes, it was a small bug I introduced last month. It's fixed in git. Thanks for reporting!
