### ISSUE TITLE
Old route record in mnesia's route table haven't been remove when restarting in some cases

### ISSUE THREAD

**Issue by yzf** [processone/ejabberd#1184]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

debian 8

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Recently, I study the route process of ejabberd, as we know, ejabberd routes messages according to the records in mnesia's table `route`. But I happened to find that, some old records in `route` were left behind after I restarted ejabberd, which means that the progresses whose pid is equal to these record's `pid` were not exist any more. Luckly, in ejabberd, these records happen to use the `local_hint` to route instread of sending messages to the `pid`'s progress, **this problem hasn't lead to any error**.

After do some tests, I finally found that this problem is related to the following thins:
1. Cluster
2. `master` node have restarted ever

In my case, I have two nodes in my cluster, `node_1` and `node_2`. And I call `ejabberdctl join_cluster 'ejabberd@node_1'` in `node_2`. If I restart the slave node `node_2` using `ejabberdctl restart`, everything is ok, the old record of `node_2` in mnesia table route is deleted. But if I restart the master node `node_1` using `ejabberdctl restart`, the old record of `node_1` in mnesia table is left behind, after that, as `node_2` become the master node and `node_1` become the slave node, this time, restarting `node_2` will case record left behind. **It seem that the master node should not restart when there are some slave nodes.**

So, after some restarting, the records in table route:

```
(ejabberd@node_1)1> mnesia:dirty_read(route, <<"xxx.xxx.xxx">>).
[{route,<<"xxx.xxx.xxx">>,<13073.278.0>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<0.320.0>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<13073.7790.150>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<0.16033.3>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<13073.30448.153>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<0.330.0>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<13073.327.0>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<0.18042.156>,
        {apply,ejabberd_local,route}},
 {route,<<"xxx.xxx.xxx">>,
        <<"xxx.xxx.xxx">>,<13073.15904.153>,
        {apply,ejabberd_local,route}}]
```

Notice that, **only two records are valid**.

**Comment by yzf** [comment]
**I wonder if there is any gracefully method for restartting the master node without stoping all slave nodes first and won't cause record in route table left behind?**

**Comment by xmppjingle** [comment]
I experienced similar issue, incurring in weird behavior of ejabberd routing specially to connected external components:

`2016-08-04 18:48:30.977 [error] emulator Discarding message {route,{jid,<<"executor">>,<<"xmpp.stg.capulet.net">>,<<"fs-dal-01">>,<<"executor">>,<<"xmpp.stg.capulet.net">>,<<"fs-dal-01">>},{jid,<<"fs-dal-01">>,<<"grandcentral.xmpp.stg.lay
ered.net">>,<<>>,<<"fs-dal-01">>,<<"grandcentral.xmpp.stg.capulet.net">>,<<>>},{xmlel,<<"iq">>,[{<<"type">>,<<"set">>},{<<"id">>,<<"executor@fs-dal-01%exmpp-3635012710">>},{<<"to">>,<<"fs-dal-01@grandcentral.xmpp.stg.capulet.net">>},{<<"f
rom">>,<<"executor@xmpp.stg.capulet.net/fs-dal-01">>}],[{xmlel,<<"call">>,[{<<"xmlns">>,<<"urn:xmpp:capulet:1">>},{<<"call-uri">>,<<"00ffc966-b346-4d73-9bb7-896f81c932b4@fs-dal-01.stg.capulet.net">>},{<<"caller">>,<<"sip:+18032201489@66.6
2.162.238">>},{<<"number">>,<<"sip:+13852084025@50.23.219.190">>}],[]}]}} from <0.423.0> to <0.464.0> in an old incarnation (3) of this node (1)`

**Comment by genexp** [comment]
We've experienced this too

**Comment by xmppjingle** [comment]
Still happening here. Affecting Production environments. Do we have a palliative suggestion to work this around?

**Comment by fabricapo** [comment]
We are seeing the same problem. If we start and stop a node, the "old incarnation" messages start popping up. We tried with leave_cluster and join_cluster, but it happens anyway. The only way to make everything work again is to stop all the nodes and restart them.

**Comment by fabricapo** [comment]
BTW, in our case mnesia:dirty_read(route, <<"xxx.xxx.xxx">>). is always empty, even when the "old incarnation" messages pop up

**Comment by genexp** [comment]
Have you tried 16.09?  It's out as of a few days ago.

On Sep 23, 2016, at 7:50 PM, processone/ejabberd <reply@reply.github.com> wrote: BTW, in our case mnesia:dirty_read(route, <<"xxx.xxx.xxx">>). is always empty, even when the "old incarnation" messages pop up

**Comment by fabricapo** [comment]
Hi Brian, we have not upgraded yet. We looked at the release notes and we did not find anything related to this. We were planning to do it anyway, and at this point we might accelerate it (it is a production system with millions of users...).

Could you point me to the commit that might fix this issue?

Thanks,

    fabrizio

**Comment by marcphilipp** [comment]
We're experiencing the same issue when the master node goes down or is stopped.

@badlop @mremond Would running `ejabberdctl leave_cluster` help to prevent this?

**Comment by weiss** [comment]
Are you stopping nodes with `ejabberdctl stop` or using systemd?

**Comment by fabricapo** [comment]
We use ejabberd stop, always. 

One big question: which one is the master node?? I was always under the impression ejabberd is master-master, and there are no slaves. However, people sometimes refer to one node as the master. And ejabberdctl has a "set_master nodename" command, which makes me think there is actually a master and some slaves... Shall we set the master to one of the cluster machine, the one that is never stopped?

**Comment by genexp** [comment]
Yeah, one thing I've noticed in production too is that it takes quite a
while for a node to re-enter production depending on the number of users
and persistent rooms.  Don't forget, stoping and starting a node requires
mnesia to sync back up.  If you stop the other node before this happens,
you split brain the system.  As an experiment: Stop one, start it up, wait
a long long time, and see if the messages go away.

**Comment by klomo24** [comment]
seeing this issue with v17.01

**Comment by cromain** [comment]
PR was merged in HEAD 14d ago.
This should fix this issue. Please test HEAD or wait 17.08
