### ISSUE TITLE
ejabberdctl start crashes after install from source

### ISSUE THREAD

**Issue by littleguga** [processone/ejabberd#1185]
> What version of ejabberd are you using?

last built from sources

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

```
sudo -i
cd /usr/src
git clone https://github.com/processone/ejabberd
./autogen.sh
./configure --enable-mysql 
make
make install
```

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried: `ejabberdctl start` and get no output.
in `/var/log/ejabberd/` i got erl_crash_dump: http://pastebin.com/JsWjq0bW

**Comment by littleguga** [comment]
/usr/sbin/ejabberdctl:

```
#!/bin/bash

# define default configuration
POLL=true
SMP=auto
ERL_MAX_PORTS=32000
ERL_PROCESSES=250000
ERL_MAX_ETS_TABLES=1400
FIREWALL_WINDOW=""
ERLANG_NODE=ejabberd@localhost

# define default environment variables
SCRIPT_DIR=`cd ${0%/*} && pwd`
ERL=/usr/bin/erl
IEX=//bin/iex
EPMD=/usr/bin/epmd
INSTALLUSER=
ERL_LIBS=//lib

...
```

**Comment by mremond** [comment]
You seem to have rights issues on your file system: "Failed to create cookie file '/roo..."

Your install is likely incorrect.

**Comment by littleguga** [comment]
@mremond from which user it's recommended to:
```
cd /usr/src
git clone https://github.com/processone/ejabberd
./autogen.sh
./configure --enable-mysql 
make
```

?

**Comment by zinid** [comment]
@littleguga from any unpriviledged user. The only build command you need root is `make install`. Also, you can pass a user running ejabberd in `configure` script, like:
```sh
$ ./configure --enable-user=some_user --enable-mysql
```
Make sure `some_user` exists.

**Comment by littleguga** [comment]
This helps for me:
```
apt-get purge erlang*
apt-get purge ejabberd*
```
Then find and remove all files for ejabberd:
```
find -name "ejabberd*"
rm -rf {each file/dir here}
```

**Be carefull, don't remove backups/fail2ban configs and other independent stuff!**

Reboot server:
`reboot`

Install erlang
`apt-get install erlang`

and then repeat installation from sources again. And it works okay!
