### ISSUE TITLE
Offline Messages not purged

### ISSUE THREAD

**Issue by ncioj10** [processone/ejabberd#1188]
> What version of ejabberd are you using?

16.06 

> What operating system (version) are you using?

Ubuntu 16.04 LTS and on Android (5.0.1) Smack 4.1.7
Stream management and auto reconnect is activated. 
The server has resend_messages activated.

> How did you install ejabberd (source, package, distribution)?

Package and Guide

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

It seems that the purge command send by Smack from Android is being ignored on the server side. The items don't get deleted and are delivered again. However, they are purged once I disable OfflineMessage retrieval and activate a initial sendPresence(). After being delivered to the smartphone they are deleted in that case.

These are the XMPP Messages in chonological order (offline message capability is returned true and messages are being received before):

```
SMACK: SENT (0): 
<iq id='5oeXa-17' type='get'>
  <offline xmlns='http://jabber.org/protocol/offline'>
    <purge/>
  </offline>
</iq>

SMACK: RECV (0): 
<iq from='user5@192.168.32.131' to='user5@192.168.32.131/Smack' id='5oeXa-17' type='result'/>

SMACK: SENT (0): 
<a xmlns='urn:xmpp:sm:3' h='9'/>

SMACK: SENT (0): 
<iq id='5oeXa-21' type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info' node='http://jabber.org/protocol/offline'>
  </query>
</iq>

SMACK: RECV (0): 
<iq from='user5@192.168.32.131' to='user5@192.168.32.131/Smack' id='5oeXa-21' type='result'> 
  <query xmlns='http://jabber.org/protocol/disco#info' node='http://jabber.org/protocol/offline'>
  <identity category='automation' type='message-list'/>
  <identity category='account' type='registered'/>
  <x xmlns='jabber:x:data' type='result'>
    <field var='FORM_TYPE' type='hidden'>
      <value>http://jabber.org/protocol/offline</value>
    </field>
    <field var='number_of_messages'>
      <value>2</value>
    </field>
  </x>
  <feature var='http://jabber.org/protocol/offline'/>
  </query>
</iq>
```

**Comment by badlop** [comment]
Looking in your queries, your client sends the Purge element in an IQ query of type Get.

But looking in http://xmpp.org/extensions/xep-0013.html#remove-all the example sends it in an IQ query of type Set. Also in ejabberd source code, file mod_offline.erl, line 338, the query expected is of type Set.

**Comment by ncioj10** [comment]
Ah thank you very much! That seems to be a bug in SMACK then. Actually the problem seems to be quite new, since the bug report on SMACK Jira was yesterday (https://issues.igniterealtime.org/projects/SMACK/issues/SMACK-726?filter=allopenissues), before that I couldn't find anyone who was reporting that issue.
