### ISSUE TITLE
Error configuration after fresh install

### ISSUE THREAD

**Issue by Catskan** [processone/ejabberd#1189]
> What version of ejabberd are you using?
ejabberd 16

> What operating system (version) are you using?
Debian 8 x64

> How did you install ejabberd (source, package, distribution)?
Source

I downloaded and installed ejabberd with source and the official documentation, but when I try to access on the web admin on http://localhost:5280/admin. But I'have " Connection failed ".

In my error.log, I have `2016-07-04 16:38:52.896 [error] <0.38.0>@ejabberd_config:get_plain_terms_file:260 Cannot load //etc/ejabberd/ejabberd.yml: Syntax error on line 423 at position 3: did not find expected key`

The line 423 is a blank line ...

My config File : 
[ejabberd.zip](https://github.com/processone/ejabberd/files/346509/ejabberd.zip)

I don't understand where is this error.

THanks you so much for your help :).

**Comment by prefiks** [comment]
It may be problem with indentation of acl rule above (admin), it has one space more than further rules, and this may cause problem for yaml parser, please try make them consistent and see if this helps.

**Comment by Catskan** [comment]
Ok thanks for that. My config file is correct now.

But, I can't login in the web admin. I have the authentification popup but any username works.
I make `ejabberdctl register admin courstream.unice.fr password`

In my config file, acl are : 

`admin:
       user:
         - "admin": "courstream.unice.fr"
         - "Administrateur@courstream.unice.fr"`

But any username works. 


I forgot to add something in ejabberd.yml ?

**Comment by Catskan** [comment]
Oh Thanks :). It's works now :).
