### ISSUE TITLE
How to configure mod_register_web ?

### ISSUE THREAD

**Issue by Catskan** [processone/ejabberd#1194]
> What version of ejabberd are you using?

16.07.11

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

Source

I compiled and install mod_register_web in ejabberd.cfg (`mod_register_web: {}`)

But now, how can I configure in ejabberd.cfg for access at the registration page ?

Thanks you in advance

**Comment by badlop** [comment]
> But now, how can I configure in ejabberd.cfg for access at the registration page ?

It is a very basic module, there is not access option implemented: Everybody can view the page.

The good news is that this module calls mod_register to create the account, so the ACCESS option defined in mod_register decides if the account can be created or not.
