### ISSUE TITLE
Prevents new users from logging in after some time

### ISSUE THREAD

**Issue by aidecoe** [processone/ejabberd#1195]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Gentoo

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After some time this thing happens in log during new clients login:

```
Accepted connection 10.0.0.213:44578 -> 10.1.0.61:5222
2016-07-07 17:30:24.825 [info] <0.31849.1>@ejabberd_c2s:wait_for_sasl_response:875 ({socket_state,fast_tls,{tlssock,#Port<0.59011>,#Port<0.59012>},<0.31848.1>}) Accepted authentication for pinkbyte by ejabberd_auth_mnesia from 10.0.0.213
2016-07-07 17:30:25.085 [info] <0.31849.1>@ejabberd_c2s:open_session:1101 ({socket_state,fast_tls,{tlssock,#Port<0.59011>,#Port<0.59012>},<0.31848.1>}) Opened session for pinkbyte@jabber.dstu.local/oas1
2016-07-07 17:30:25.087 [info] <0.31849.1>@ejabberd_c2s:handle_enable:2671 Stream management with resumption enabled for pinkbyte@jabber.dstu.local/oas1
2016-07-07 17:30:25.151 [info] <0.31849.1>@ejabberd_c2s:terminate:1762 ({socket_state,fast_tls,{tlssock,#Port<0.59011>,#Port<0.59012>},<0.31848.1>}) Close session for pinkbyte@jabber.dstu.local/oas1
2016-07-07 17:30:25.152 [info] <0.31849.1>@ejabberd_c2s:handle_unacked_stanzas:2841 4 stanzas were not acknowledged by pinkbyte@jabber.dstu.local/oas1
2016-07-07 17:30:25.153 [error] <0.31849.1> gen_fsm <0.31849.1> in state session_established terminated with reason: bad argument in call to fxml:element_to_binary({xmlel,<<"message">>,[{<<"from">>,<<"bard@jabber.dstu.local">>},{<<"to">>,<<"pinkbyte@jabber.dstu....">>},...],...}) in ejabberd_c2s:send_element/2 line 1831
2016-07-07 17:30:25.154 [error] <0.31849.1> CRASH REPORT Process <0.31849.1> with 0 neighbours exited with reason: bad argument in call to fxml:element_to_binary({xmlel,<<"message">>,[{<<"from">>,<<"bard@jabber.dstu.local">>},{<<"to">>,<<"pinkbyte@jabber.dstu....">>},...],...}) in ejabberd_c2s:send_element/2 line 1831
```

If currently connected user will try to relogin - same thing will happen for him.

After restarting ejabberd - everything works fine, but after some time this problem pops up again.

Contents of `ejabberd.yml` (which was autogenerated during migration from 2.1.13):

```
hosts: 
  - "jabber.dstu.local"
access: 
  announce: 
    admin: allow
  c2s: 
    blocked: deny
    all: allow
  c2s_shaper: 
    admin: none
    all: normal
  configure: 
    admin: allow
  local: 
    local: allow
  max_user_offline_messages: 
    admin: 5000
    all: 100
  max_user_sessions: 
    all: 10
  mod_register_networks: 
    ip_10.0.0.0/8: allow
    ip_0.0.0.0/0: deny
  muc: 
    all: allow
  muc_admin: 
    admin: allow
  muc_create: 
    local: allow
  pubsub_createnode: 
    local: allow
  register: 
    blocked: deny
    all: allow
  s2s_shaper: 
    all: fast
acl: 
  admin: 
    user: 
      - "pinkbyte": "jabber.dstu.local"
      - "bard": "jabber.dstu.local"
      - "admin": "jabber.dstu.local"
  blocked: 
    user: 
      - "user": "jabber.dstu.local"
  ip_0.0.0.0/0: 
    ip: 
      - "0.0.0.0/0"
  ip_10.0.0.0/8: 
    ip: 
      - "10.0.0.0/8"
  local: 
    user_regexp: 
      - ""
auth_method: 
  - mnesia
language: "ru"
listen: 
  - 
    port: 5222
    module: ejabberd_c2s
#    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    starttls: true
    starttls_required: true
    certfile: "/etc/ssl/dstu/JABBER_server.pem"
  - 
    port: 5280
    module: ejabberd_http
    web_admin: true
    http_poll: true
    http_bind: true
loglevel: 4
max_fsm_queue: 1000
modules: 
  mod_register: 
    ip_access: mod_register_networks
    welcome_message: 
      subject: "Welcome!"
      body: "Welcome to DSTU Jabber server."
    registration_watchers: 
      - "bard@jabber.dstu.local"
    access: register
  mod_adhoc: []
  mod_announce: 
    access: announce
  mod_blocking: []
  mod_caps: []
  mod_configure: []
  mod_disco: []
  mod_http_bind: []
  mod_last: []
  mod_muc: 
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
  mod_ping: []
  mod_privacy: []
  mod_private: []
  mod_pubsub: 
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: true
    max_items_node: 100
    plugins: 
      - "flat"
      - "hometree"
      - "pep"
  mod_roster: []
  mod_shared_roster: []
  mod_time: []
  mod_vcard: 
    search: true
    matches: infinity
    allow_return_all: true
  mod_version: []
shaper: 
  normal: 1000
  fast: 50000
```

**Comment by weiss** [comment]
You should find full traces in your `crash.log` file.  Could you post one of them?

**Comment by Pinkbyte** [comment]
Original reporter here(this bug report was redirected from Gentoo by aidecoe, https://bugs.gentoo.org/show_bug.cgi?id=588244)

Here is crash log:
2016-07-08 15:57:53 =ERROR REPORT====
** State machine <0.3786.0> terminating 
** Last message in was {send_filtered,{pep_message,<<"http://jabber.org/protocol/activity+notify">>},{jid,<<"bard">>,<<"jabber.dstu.local">>,<<>>,<<"bard">>,<<"jabber.dstu.local">>,<<>>},{jid,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>},{xmlel,<<"message">>,[{<<"type">>,<<"headline">>}],[{xmlel,<<"event">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/pubsub#event">>}],[{xmlel,<<"items">>,[{<<"node">>,<<"http://jabber.org/protocol/activity">>}],[{xmlel,<<"item">>,[{<<"id">>,"current"}],[{xmlelement,"activity",[{"xmlns","http://jabber.org/protocol/activity"}],[{xmlelement,"drinking",[],[]},{xmlelement,"text",[],[]}]}]}]}]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"from">>,<<"bard@jabber.dstu.local/Work">>},{<<"stamp">>,<<"2009-06-24T13:07:03Z">>}],[{xmlcdata,<<>>}]}]}}
** When State == session_established
**      Data  == {state,{socket_state,fast_tls,{tlssock,#Port<0.27138>,#Port<0.27139>},<0.3785.0>},ejabberd_socket,#Ref<0.0.1.37705>,false,<<"4747957529193719083">>,undefined,c2s,c2s_shaper,false,true,true,true,[verify_none,compression_none,{certfile,<<"/etc/ssl/dstu/JABBER_server.pem">>}],true,{jid,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>},<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>,{{1467,982672,1262},<0.3786.0>},{pres_t,18},{pres_f,18},{pres_a,18},{xmlel,<<"presence">>,[{<<"xml:lang">>,<<"ru">>}],[{xmlel,<<"priority">>,[],[{xmlcdata,<<"0">>}]},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://miranda-ng.org/caps">>},{<<"ver">>,<<"0.94.9.8010">>},{<<"ext">>,<<"x86 mood activity mir_notes">>}],[]},{xmlel,<<"x">>,[{<<"xmlns">>,<<"vcard-temp:x:update">>}],[{xmlel,<<"photo">>,[],[]}]},{xmlel,<<"status">>,[],[{xmlcdata,<<208,148,208,176,44,32,209,143,32,208,183,208,180,208,181,209,129,209,140,46>>}]}]},{1467,982673,874723},{userlist,none,[],false},c2s_tls,undefined,{{10,34,0,5},51734},[{caps_resources,{5,{{<<"victoria">>,<<"jabber.dstu.local">>,<<"TEMP">>},{caps,<<"http://miranda-ng.org/caps">>,<<"0.95.1.9705">>,<<>>,[<<"x86">>,<<"mood">>,<<"activity">>,<<"mir_notes">>]},{{<<"slopatin">>,<<"jabber.dstu.local">>,<<"A401C001">>},{caps,<<"http://miranda-ng.org/caps">>,<<"0.94.9.8010">>,<<>>,[<<"x86">>,<<"mood">>,<<"activity">>,<<"mir_notes">>]},{{<<"pinkbyte">>,<<"jabber.dstu.local">>,<<"oas1">>},{caps,<<"http://psi-dev.googlecode.com/caps">>,<<"XZtybsFMx2jAuScb1DXHs9PCPlI=">>,<<"sha-1">>,[]},{{<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>},{caps,<<"http://miranda-ng.org/caps">>,<<"0.94.9.8010">>,<<>>,[<<"x86">>,<<"mood">>,<<"activity">>,<<"mir_notes">>]},nil,{{<<"bard">>,<<"jabber.dstu.local">>,<<"BLACK">>},{caps,<<"http://miranda-ng.org/caps">>,<<"0.95.5.17000">>,<<>>,[<<"x64">>,<<"mood">>,<<"tune">>,<<"activity">>,<<"mir_notes">>]},nil,nil}},nil},nil},nil}}}],active,[],inactive,undefined,undefined,1000,undefined,300,300,false,0,0,true,<<"ru">>}
** Reason for termination = 
** {badarg,[{fxml,element_to_binary,[{xmlel,<<"message">>,[{<<"from">>,<<"bard@jabber.dstu.local">>},{<<"to">>,<<"akarasev@jabber.dstu.local/BLACK">>},{<<"type">>,<<"headline">>}],[{xmlel,<<"event">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/pubsub#event">>}],[{xmlel,<<"items">>,[{<<"node">>,<<"http://jabber.org/protocol/activity">>}],[{xmlel,<<"item">>,[{<<"id">>,"current"}],[{xmlelement,"activity",[{"xmlns","http://jabber.org/protocol/activity"}],[{xmlelement,"drinking",[],[]},{xmlelement,"text",[],[]}]}]}]}]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"from">>,<<"bard@jabber.dstu.local/Work">>},{<<"stamp">>,<<"2009-06-24T13:07:03Z">>}],[{xmlcdata,<<>>}]}]}],[]},{ejabberd_c2s,send_element,2,[{file,"src/ejabberd_c2s.erl"},{line,1831}]},{ejabberd_c2s,send_stanza,2,[{file,"src/ejabberd_c2s.erl"},{line,1841}]},{ejabberd_c2s,handle_info,3,[{file,"src/ejabberd_c2s.erl"},{line,1702}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2016-07-08 15:57:53 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.3786.0>
    registered_name: []
    exception exit: {{badarg,[{fxml,element_to_binary,[{xmlel,<<"message">>,[{<<"from">>,<<"bard@jabber.dstu.local">>},{<<"to">>,<<"akarasev@jabber.dstu.local/BLACK">>},{<<"type">>,<<"headline">>}],[{xmlel,<<"event">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/pubsub#event">>}],[{xmlel,<<"items">>,[{<<"node">>,<<"http://jabber.org/protocol/activity">>}],[{xmlel,<<"item">>,[{<<"id">>,"current"}],[{xmlelement,"activity",[{"xmlns","http://jabber.org/protocol/activity"}],[{xmlelement,"drinking",[],[]},{xmlelement,"text",[],[]}]}]}]}]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"from">>,<<"bard@jabber.dstu.local/Work">>},{<<"stamp">>,<<"2009-06-24T13:07:03Z">>}],[{xmlcdata,<<>>}]}]}],[]},{ejabberd_c2s,send_element,2,[{file,"src/ejabberd_c2s.erl"},{line,1831}]},{ejabberd_c2s,send_stanza,2,[{file,"src/ejabberd_c2s.erl"},{line,1841}]},{ejabberd_c2s,handle_info,3,[{file,"src/ejabberd_c2s.erl"},{line,1702}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.505.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: [{send_filtered,{pep_message,<<"http://jabber.org/protocol/mood+notify">>},{jid,<<"bard">>,<<"jabber.dstu.local">>,<<>>,<<"bard">>,<<"jabber.dstu.local">>,<<>>},{jid,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>,<<"akarasev">>,<<"jabber.dstu.local">>,<<"BLACK">>},{xmlel,<<"message">>,[{<<"type">>,<<"headline">>}],[{xmlel,<<"event">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/pubsub#event">>}],[{xmlel,<<"items">>,[{<<"node">>,<<"http://jabber.org/protocol/mood">>}],[{xmlel,<<"item">>,[{<<"id">>,"current"}],[{xmlelement,"mood",[{"xmlns","http://jabber.org/protocol/mood"}],[{xmlelement,"calm",[],[]},{xmlelement,"text",[],[]}]}]}]}]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"from">>,<<"bard@jabber.dstu.local/Work">>},{<<"stamp">>,<<"2009-06-24T13:06:56Z">>}],[{xmlcdata,<<>>}]}]}}]
    links: [#Port<0.27139>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 303863
  neighbours:

**Comment by weiss** [comment]
The PubSub database contains entries that weren't properly converted from ejabberd 2.x.  You could either try to do that [manually][1], or simply delete the PubSub tables (e.g., by removing all `pubsub*` files in Mnesia's spool directory, after taking a backup of the database).

[1]: https://github.com/processone/ejabberd/issues/479#issuecomment-124497456

**Comment by prefiks** [comment]
Looks like that client has pubsub data stored using old xml structures, we do have code that should perform migration to new format, i wonder why this is not triggered here...
