### ISSUE TITLE
Unable to start ejabberd server

### ISSUE THREAD

**Issue by mithunraman** [processone/ejabberd#1196]
> What version of ejabberd are you using?
16.06

> What operating system (version) are you using?
Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
Source

Ejabberd fails to start with the following error.

13:14:38.511 [error] CRASH REPORT Process <0.417.0> with 0 neighbours exited with reason: bad argument in call to erlang:node(undefined) in ejabberd_sm_redis:'-clean_table/0-fun-2-'/1 line 146
13:14:38.512 [info] FQDN used to check DIGEST-MD5 SASL authentication: <<"ubuntuMaster">>
13:14:38.725 [info] Application oauth2 started on node ejabberd@localhost
13:14:38.791 [critical] Problem starting the module mod_adhoc for host <<"192.168.1.150">> 
 options: []
 error: badarg
[{ejabberd_sm,register_iq_handler,5,[{file,"src/ejabberd_sm.erl"},{line,341}]},
 {mod_adhoc,start,2,[{file,"src/mod_adhoc.erl"},{line,53}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,154}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,75}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
13:14:38.791 [critical] ejabberd initialization was aborted because a module start failed.

Crash Log:
    initial call: ejabberd_sm:init/1
    pid: <0.417.0>
    registered_name: []
    exception exit: {{badarg,[{erlang,node,[undefined],[]},{ejabberd_sm_redis,'-clean_table/0-fun-2-',1,[{file,"src/ejabberd_sm_redis.erl"},{line,146}]},{lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1285}]},{ejabberd_sm_redis,'-clean_table/0-fun-9-',1,[{file,"src/ejabberd_sm_redis.erl"},{line,143}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_sm,init,1,[{file,"src/ejabberd_sm.erl"},{line,354}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [ejabberd_sup,<0.42.0>]
    messages: []
    links: [<0.333.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 470

Any idea on as to how to proceed ?

Thanks,

**Comment by zinid** [comment]
The regression is introduced in this commit: 30e814dd4bf414314ff611452362582419f3f05d

**Comment by zinid** [comment]
I am actually not sure how to fix this as we lose information about record creating node when `pid()` is set to undefined in `sid()`. We probably can safely ignore this, I'm not sure, it depends on the logic. Holger might know more.

**Comment by zinid** [comment]
For the record, seems like `ejabberd_sm_sql.erl` is also affected.

**Comment by weiss** [comment]
I'll have a look.

**Comment by zinid** [comment]
@mithunraman as a temporary solution you need to clean the corresponding Redis database before starting ejabberd (should not be a terrible problem if you have a single node).

**Comment by mithunraman** [comment]
flushing all the keys in redis did the trick. 
Thanks @zinid 
Thanks all.
