### ISSUE TITLE
converting database from prosody to ejabberd

### ISSUE THREAD

**Issue by smoebody** [processone/ejabberd#1199]
Hi, 

currently i am using prosody as xmpp server and now i want to switch to ejabberd. my concerns are about the user data currently hosted in prosody. is there a reliable way to convert it to ejabberd's database? i found the file [prosody2ejabberd.erl](https://github.com/processone/ejabberd/blob/master/src/prosody2ejabberd.erl) in the sources, but no documentation on how to use it or any other mention somewhere. maybe @zinid or @mremond could give me a hint?

thanks in advance.

**Comment by badlop** [comment]
There's an ejabberd command, mentioned in 
https://docs.ejabberd.im/admin/guide/managing/#list-of-ejabberd-commands

Other people found it, and are having some problem, do you see that same problem?https://www.ejabberd.im/forum/25526/how-import-prosody

**Comment by smoebody** [comment]
it was not working out of the box. i had to rename the domain-name folder since prosody created the folder with `%20` as `.` (dot) and ejabberd refused to create the users with the mentioned error. after renaming the folder to contain the dot instead `%20` importing worked flawlessly
