### ISSUE TITLE
connecting to mod_rest remotly

### ISSUE THREAD

**Issue by bobnino** [processone/ejabberd#1200]
> What version of ejabberd are you using?

16
> What operating system (version) are you using?

ubuntu 14.04
> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

mod_rest works ok when connecting to it from localhost however if i connect remotely to it from another instance i get the following 

/# wget http://52.11.3.240:5285/rest/ --server-response --post-data ' registered_users localhost'
--2016-07-18 13:54:01--  http://52.11.3.240:5285/rest/
Connecting to 52.11.3.240:5285... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 406 Not Acceptable
  Content-Type: text/html; charset=utf-8
  Content-Length: 43
2016-07-18 13:54:01 ERROR 406: Not Acceptable.

any thoughts why this is happening ??

**Comment by badlop** [comment]
Maybe the problem is that ejabberd does not know to that vhost the request should be sent, notice that you send the request to an IP address, and there is no Host option in your request.

Try:
> wget http://52.11.3.240:5285/rest/ --header='Host: localhost' --server-response --post-data ' registered_users localhost'

**Comment by bobnino** [comment]
tried your solution badlop and results still the same , it doesn't work yet.

**Comment by bobnino** [comment]
i also tried this but still no data returned this time 

wget http://52.11.3.240:5285/rest/ --header='Host:  http://52.11.3.240' --server-response --post-data ' registered_users localhost'
--2016-07-19 06:02:26--  http://52.11.3.240:5285/rest/
Connecting to 52.11.3.240:5285... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2016-07-19 06:02:27--  (try: 2)  http://52.11.3.240:5285/rest/
Connecting to 52.11.3.240:5285... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

**Comment by mremond** [comment]
Note: mod_rest is not part of ejabberd. This is an ejabberd-contrib

**Comment by bobnino** [comment]
I realize that mremond , I don't get your point tho ?

**Comment by mremond** [comment]
My point is that you reported the issue in the wrong repository :) You do not give the chance to people working on ejabberd rest in ejabberd-contribs to reply.

**Comment by bobnino** [comment]
Oh sorry I didn't realize that I should  have reported it else where, thought modrest was part of contrib that's why I reported on here

**Comment by mremond** [comment]
This is the repository for ejabberd-contribs: https://github.com/processone/ejabberd-contrib

**Comment by bobnino** [comment]
lol!! your right !!, i must be staring at the screen for too long, ill move the issue to the contrib now, thanks

**Comment by bobnino** [comment]
this issue have been moved to ejabberd contrib repo
