### ISSUE TITLE
MUC Rooms with non ASCII chars in title cannot removed

### ISSUE THREAD

**Issue by poeserdaddler** [processone/ejabberd#1203]
> What version of ejabberd are you using?

15.04 (MySQL ODBC with utf8-mb4 encoding)

> What operating system (version) are you using?

Debian/Wheezy

> How did you install ejabberd (source, package, distribution)?

Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Whenever I try to delete MUC rooms containing umlauts (öäüÖÄÜ) using:
./ejabberdctl "röömnäme" "conference.example.de" "host.example.de" the rooms won't get deleted.

Rooms without umlauts get properly deleted and I expect that rooms containing umlauts can be deleted as well.

**Comment by badlop** [comment]
Using ejabberd 16.06, I see no problem using the command, maybe it got fixed in the last year
```
$ ejabberdctl create_room "röömnäme" "conference.localhost" "localhost"
$ ejabberdctl muc_online_rooms "localhost"
sala1@conference.localhost
sala2@conference.localhost
röömnäme@conference.localhost
$ ejabberdctl destroy_room "röömnäme" "conference.localhost"
$ ejabberdctl muc_online_rooms "localhost"
sala1@conference.localhost
sala2@conference.localhost
$
```

**Comment by cromain** [comment]
can not reproduce
