### ISSUE TITLE
mod_mam with postgres and muc fails in some cases

### ISSUE THREAD

**Issue by dl8bh** [processone/ejabberd#1204]
> What version of ejabberd are you using?
16.04

> What operating system (version) are you using?

FreeBSD

> How did you install ejabberd (source, package, distribution)?

source (from FreeBSD ports)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

fetching history via mod_mam from one muc (history from other mucs loads fine) fails with lots of SQL related error messages (see attached file)
[bugreport.txt](https://github.com/processone/ejabberd/files/375869/bugreport.txt)

**Comment by weiss** [comment]
> {error,undef,[{ejabberd_odbc,to_bool,[<<"1">>],[]}

This means the function `ejabberd_odbc:to_bool/1` is called, but the call fails because no such function exists.  The 16.04 code doesn't contain a call to that function, as the `ejabberd_odbc` module was renamed to `ejabberd_sql`.  So there's something wrong with your installation.

**Comment by dl8bh** [comment]
could it be, that the call was being put together from some config-file-values? as https://blog.process-one.net/ejabberd-16-04/ states, there is no need to change the odbc keywords to sql, but thats the only issue i can figure out at my side.
