### ISSUE TITLE
ejabberd produces lots of warnings in the postgres error log

### ISSUE THREAD

**Issue by dl8bh** [processone/ejabberd#1205]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

FreeBSD

> How did you install ejabberd (source, package, distribution)?

FreeBSD ports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

/var/log/messages shows lots of warnings regarding postgres queries with ejabberd being the only process using postgres:

Jul 21 11:08:52 xmpp postgres[2171]: [368-1] WARNING:  nonstandard use of escape in a string literal at character 171
Jul 21 11:08:52 xmpp postgres[2171]: [368-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:10:39 xmpp postgres[2171]: [369-1] WARNING:  nonstandard use of escape in a string literal at character 162
Jul 21 11:10:39 xmpp postgres[2171]: [369-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:10:51 xmpp postgres[2175]: [437-1] WARNING:  nonstandard use of escape in a string literal at character 162
Jul 21 11:10:51 xmpp postgres[2175]: [437-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:20:31 xmpp postgres[2176]: [388-1] WARNING:  nonstandard use of escape in a string literal at character 163
Jul 21 11:20:31 xmpp postgres[2176]: [388-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:20:31 xmpp postgres[2176]: [389-1] WARNING:  nonstandard use of escape in a string literal at character 404
Jul 21 11:20:31 xmpp postgres[2176]: [389-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:20:31 xmpp postgres[2176]: [390-1] WARNING:  nonstandard use of escape in a string literal at character 169
Jul 21 11:20:31 xmpp postgres[2176]: [390-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 11:20:31 xmpp postgres[2176]: [391-1] WARNING:  nonstandard use of escape in a string literal at character 410
Jul 21 11:20:31 xmpp postgres[2176]: [391-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 12:00:28 xmpp postgres[2167]: [355-1] WARNING:  nonstandard use of escape in a string literal at character 170
Jul 21 12:00:28 xmpp postgres[2167]: [355-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Jul 21 12:00:28 xmpp postgres[2169]: [361-1] WARNING:  nonstandard use of escape in a string literal at character 195
Jul 21 12:00:28 xmpp postgres[2169]: [361-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.

**Comment by cromain** [comment]
hello

the postgress schema has been improved in 16.09, maybe this if already fixed. can someone confirm ?

**Comment by dl8bh** [comment]
I am sorry, does not seem to be solved... 

root@xmpp:~ # portmaster -L |grep ejabberd
===>>> ejabberd-16.09
root@xmpp:~ # tail /var/log/messages
Nov 28 16:52:49 xmpp postgres[51525]: [650-1] WARNING:  nonstandard use of escape in a string literal at character 172
Nov 28 16:52:49 xmpp postgres[51525]: [650-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Nov 28 16:52:50 xmpp postgres[51525]: [651-1] WARNING:  nonstandard use of escape in a string literal at character 172
Nov 28 16:52:50 xmpp postgres[51525]: [651-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Nov 28 16:58:18 xmpp postgres[51528]: [603-1] WARNING:  nonstandard use of escape in a string literal at character 172
Nov 28 16:58:18 xmpp postgres[51528]: [603-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Nov 28 17:09:19 xmpp postgres[51526]: [627-1] WARNING:  nonstandard use of escape in a string literal at character 172
Nov 28 17:09:19 xmpp postgres[51526]: [627-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
Nov 28 17:25:18 xmpp postgres[51530]: [687-1] WARNING:  nonstandard use of escape in a string literal at character 172
Nov 28 17:25:18 xmpp postgres[51530]: [687-2] HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.

**Comment by zinid** [comment]
ejabberd tries to [disable](https://github.com/processone/ejabberd/blob/master/src/ejabberd_sql.erl#L793) these warnings on startup, but seems like the query fails on your system. You can try to set it manually via postgresql config or something.

**Comment by dl8bh** [comment]
I enabled these settings via sql console a few days ago:

domaindatabasede=# alter database domaindatabasede set standard_conforming_strings='off';
ALTER DATABASE
and also:
domaindatabasede=# set standard_conforming_strings to 'off';
SET

But it did not have any effect on these warnings beeing shown…

**Comment by zinid** [comment]
I don't know, refer to postgresql documentation.

**Comment by zinid** [comment]
BTW, wasn't this fixed in recent versions (after SQL refactoring)?

**Comment by dl8bh** [comment]
I took every version that landed in the freebsd ports since then and unfortunately this issue has not been fixed for my environment.
Even applying https://github.com/processone/ejabberd/blob/master/src/ejabberd_sql.erl#L793 manually to the db did not stop those log messages.

**Comment by zinid** [comment]
Are you using pgsql erlang driver? Are you sure you're not using odbc driver?

**Comment by zinid** [comment]
You should have `sql_type: pgsql` in `ejabberd.yml`

**Comment by cromain** [comment]
do you have this warning for every queries, or only some of them ?
you can put ejabberd in debug to see what query triggers this

**Comment by dl8bh** [comment]
@zinid 
root@xmpp:~ # head /usr/local/etc/ejabberd/ejabberd.yml
host_config: 
  "somedomain.de": 
    sql_username: "ejabberd"
    sql_type: pgsql
    sql_server: "127.0.0.1"
    sql_port: 5432
    sql_password: "someotherpassword"
    sql_database: "somedatabase"
root@xmpp:~ # grep odbc /usr/local/etc/ejabberd/ejabberd.yml
root@xmpp:~ #
@cromain 
I don't know which queries trigger those warnings - the respective log entries come and go over the time.
Which loglevel should I set for investigation?

**Comment by alexeyshch** [comment]
You can set `log_statement = 'all'` in Postgres, so you'll see problematic queries right before the warning in logs.

**Comment by cromain** [comment]
I can not reproduce with ejabberd master, freebsd11, postgresql96.
there should be something wrong/old in your schema or postgres settings.

**Comment by cromain** [comment]
please post if you have more details on the problematic queries. also please check fresh install of db+ejabberd 17.01 works in your case.

**Comment by zinid** [comment]
There are actually SQL queries whose still bypass pgsql interface, you can grep `ejabberd_sql:escape` to find them. I think those are triggering the issue.
