### ISSUE TITLE
How to add users in multi user chat ?

### ISSUE THREAD

**Issue by ankitcode** [processone/ejabberd#1207]
> What version of ejabberd are you using?
16.06

> What operating system (version) are you using?
kubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
source

Issue : 

I was working on ejabberd chat, I'm able to create multiple user chat room with command
`sudo ejabberdctl create_room mychat localhost xmpp_domain`
I want to know how to create that in virtual host as it is not being created in virtual host and how to add user of virtual host to it.

**Comment by badlop** [comment]
From what I know, it isn't possible to force a user to join a room. What you can do is to invite the user to the room, for example using the command send_direct_invitation

**Comment by ankitcode** [comment]
Can you tell me is there any ejabberd rest api support to create room and send invite to users.

**Comment by badlop** [comment]
Yes, the create_room command to create the room, and then the send_direct_invitation command to send invitations.

**Comment by prashanthviru** [comment]
is it possible to add user directly to muc room without invite
