### ISSUE TITLE
How to send invite to user through rest api to join chat room ?

### ISSUE THREAD

**Issue by ankitcode** [processone/ejabberd#1209]
> What version of ejabberd are you using?
16.06
> What operating system (version) are you using?
Kubuntu 16.04
> How did you install ejabberd (source, package, distribution)?
source

Is there any ejabberd rest api support to create chat room and send invite to users. if it is there, then how to do that, I'm using `oauth` and `mod_http_api`.

**Comment by badlop** [comment]
Already replied in https://github.com/processone/ejabberd/issues/1207#issuecomment-234547719
