### ISSUE TITLE
crash with some clients

### ISSUE THREAD

**Issue by p5n** [processone/ejabberd#121]
I need to apply following patch to make them work

https://projects.archlinux.org/svntogit/community.git/tree/trunk/crash-fix.patch?h=packages/ejabberd

Some clients (mostly miranda) cause crashes on get_conn_type().

Not sure if this patch is correct, but it works.

**Comment by mremond** [comment]
It seems the patch is not available. Is this patch still needed for you ?

**Comment by p5n** [comment]
No, I think it is already fixed.
