### ISSUE TITLE
ejabberd commands not being loaded

### ISSUE THREAD

**Issue by xmppjingle** [processone/ejabberd#1210]
> What version of ejabberd are you using?
master at HEAD

> What operating system (version) are you using?
ubuntu

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Occurence: 20% (1 out of 5) of the nodes upon all nodes restart, have this unusual erratic behavior. A graceful stop/start on the affected nodes, seems to fix the problem most of the time.

Expected ejabberd_commands to load as expected.
Not working/loading as expected.

Node is running and operational, even being listed as part of the cluster and routing messages. But extra commands are broken. In summary ejabberdctl is not usable at this state.

**Example of command:**
```
thiago@xmpp-03:~
$ sudo ejabberdctl list_cluster
The node 'ejabberd@xmpp-03' is started with status: started
ejabberd is not running in that node
Check for error messages: //var/log/ejabberd/ejabberd.log
or other files in that directory.

Error in ejabberd ctl process: 'error' badarg
```

**Error in Log:**
`2016-07-23 03:52:48.727 [error] <0.392.0> CRASH REPORT Process <0.392.0> with 0 neighbours exited with reason: {aborted,{no_exists,ejabberd_commands}} in gen_server:init_it/6 line 352
2016-07-23 03:52:48.727 [error] <0.365.0> Supervisor ejabberd_sup had child ejabberd_s2s started with ejabberd_s2s:start_link() at undefined exit with reason {aborted,{no_exists,ejabberd_commands}} in context start_error
2016-07-23 03:52:48.728 [error] <0.38.0> CRASH REPORT Process <0.38.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(ejabberd_sup, {start_child,{ejabberd_sm,{ejabberd_sm,start_link,[]},transient,1000,worker,[ejabberd_sm]}}, infinity) in application_master:init/4 line 134
2016-07-23 03:52:48.729 [info] <0.7.0> Application ejabberd exited with reason: no such process or port in call to gen_server:call(ejabberd_sup, {start_child,{ejabberd_sm,{ejabberd_sm,start_link,[]},transient,1000,worker,[ejabberd_sm]}}, infinity)`

**Comment by xmppjingle** [comment]
Also happening in random cases as:

```$ sudo ejabberdctl list_cluster
Problem 'exit {aborted,
                  {no_exists,
                      [ejabberd_commands,
                       [{{ejabberd_commands,'$1','_','_','_','$2','_','_',
                             '_','_','_','_','_','_','_'},
                         [{'==','$1',{const,list_cluster}},
                          {'=<','$2',{const,1000000}}],
                         [{{'$2','$_'}}]}]]}}' occurred executing the command.
Stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,313}]},
             {ejabberd_commands,get_command_definition,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,398}]},
             {ejabberd_commands,get_command_format,3,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,360}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,318}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]```

**Comment by badlop** [comment]
When ejabberd starts, it recreates the Mnesia table "ejabberd_commands", and then adds commands definitions to it. This way, when at any time the list of commands is requested, or a command wants to be executed, ejabberd reads the information from that Mnesia table.

If that table gets destroyed, then the feature doesn't work. For example, if I start ejabberd and execute this: mnesia:delete_table(ejabberd_commands). Then I get the same errors that you mention.

In your case, investigate when does that table get destroyed, maybe you have some error in the log pointing to the case. Maybe you have that mnesia table replicated in several nodes? Notice that table is only relevant for the local node, so don't replicate it.

**Comment by srikanth231** [comment]
Hi Badlop,

The table gets destroyed and recreated on every start. In our case the problem happens when we have a cluster of 2 nodes node1 and node2 and when node 2 is restarted node1 has this problem.
Please refer to my original post https://www.ejabberd.im/forum/25502/question-regarding-clustering.

Yes we agree with you that the table should not be replicated, however it looks like the table(all the tables infact) is being replicated in ejabberd_cluster:join() function.Is there a way not to replicate other than modifying the code?

**Comment by xmppjingle** [comment]
Notice that I'm using a vanilla version of ejabberd from master. And that is what I get:
It seems to be a remote table. We might have a bug here.

`(ejabberd@xc-01)1> mnesia:system_info().
===> System info in version "4.13.3", debug level = none <===
opt_disc. Directory "/var/lib/ejabberd" is used.
use fallback at restart = false
running db nodes   = ['ejabberd@x-02','ejabberd@x-01','ejabberd@xc-01']
stopped db nodes   = []
master node tables = []
remote             = [ejabberd_commands]
ram_copies         = [access,acl,iq_response,local_config,reg_users_counter,
                      route,route_multicast,s2s,session,session_counter,
                      shaper,temporarily_blocked]
disc_copies        = [last_activity,oauth_token,passwd,privacy,roster,
                      roster_version,schema]
disc_only_copies   = [offline_msg,private_storage]
[] = [ejabberd_commands]`

Regarding logs, nothing is printed regarding mnesia.

**Comment by badlop** [comment]
Yes, ejabberd_cluster:join() clusters all the mnesia tables including ejabberd_commands, which is undesired. That is solved later, when it starts ejabberd application, which calls ejabberd_commands:init, which deletes and creates the table with only local RAM.

I can reproduce your problem, so there may be some bug. I haven't investigated further, as I think there might be a more simple solution: don't cluster that table at all. I've written this simple patch, which apparently solves the problem in my case (I only tested a few times):
```
diff --git a/src/ejabberd_cluster.erl b/src/ejabberd_cluster.erl
index 1e3f02a..e28173f 100644
--- a/src/ejabberd_cluster.erl
+++ b/src/ejabberd_cluster.erl
@@ -69,7 +69,7 @@ join(Node) ->
                 lists:foreach(fun(Table) ->
                             Type = call(Node, mnesia, table_info, [Table, storage_type]),
                             mnesia:add_table_copy(Table, node(), Type)
-                    end, mnesia:system_info(tables)--[schema])
+                    end, mnesia:system_info(tables)--[schema, ejabberd_commands])
                 end),
             application:start(ejabberd);
         _ ->
diff --git a/src/ejabberd_commands.erl b/src/ejabberd_commands.erl
index 33edcb7..e0adf2f 100644
--- a/src/ejabberd_commands.erl
+++ b/src/ejabberd_commands.erl
@@ -274,7 +274,6 @@ get_commands_spec() ->
                            args_example = ["/home/me/docs/api.html", "mod_admin", "java,json"],
                            result_example = ok}].
 init() ->
-    mnesia:delete_table(ejabberd_commands),
     mnesia:create_table(ejabberd_commands,
                         [{ram_copies, [node()]},
                          {local_content, true},
```
I'll forward the proposal to the original source code developer, because maybe this patch is not definitive. In the meantime, ca you apply that patch, test it, and report your results?

**Comment by xmppjingle** [comment]
This patch worked fine! Thanks @badlop

**Comment by palmertime** [comment]
Just for a work around ...

1) Start node1
2) Start node2
3) On node2 join_cluster 'node1'
4) On node1 stop/start ejabberd

After that list_cluster command works on both nodes.
