### ISSUE TITLE
mix test not work

### ISSUE THREAD

**Issue by indie21** [processone/ejabberd#1212]
> What version of ejabberd are you using?

16.06.0

> What operating system (version) are you using?

mac osx 

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

** (Mix) Cannot run tests because test helper file "test/test_helper.exs" does not exist

> was the unexpected behavior? What was the expected result?

mix test should work

**Comment by mremond** [comment]
We use Elixir test from Erlang. To run them you need to do: `make quicktest`

**Comment by indie21** [comment]
DONE
Testing services.ejabberd.elixir_SUITE: TEST COMPLETE, 0 ok, 0 failed of 0 test cases


0 ok, 0 failed of 0 test cases ??  zero case ??

**Comment by mremond** [comment]
https://docs.ejabberd.im/developer/testing/

**Comment by mremond** [comment]
`mix test` now works with commit https://github.com/processone/ejabberd/commit/2a8005e47fdb7dbeff27dde41550221823bdb75d

It will likely be included into ejabberd 16.08.

**Comment by mremond** [comment]
Code merged to master. mix test should work in 16.08.

**Comment by indie21** [comment]
make quicktest or make test take too much time ....
waiting for 30 minutes not finish... 
please tell em how long it almost taken, otherwise does something went wrong in my test...
