### ISSUE TITLE
reCAPTCHA Support

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1214]
> What version of ejabberd are you using?
> 16.06.
> 
> What operating system (version) are you using?
> Debian Stable.
> 
> How did you install ejabberd (source, package, distribution)?
> Official Debian Repository.
> 
> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Due to the recent surge in registrations of fraudulent and bot accounts, there is a strong necessity to get an adequate method to restrict automatic registrations.

There is a Google-backed [reCAPTCHA](https://www.google.com/recaptcha/intro/index.html) method which shows very good results of fending off autoregistrations, but currently ejabberd only ships with a rather simple captcha-generating script.

Please add support of reCAPTCHA in the future release.

**Comment by weiss** [comment]
> currently ejabberd only ships with a rather simple captcha-generating script.

Out of curiosity: Have you seen automatic registrations cope with ejabberd's CAPTCHAs in practice?  I haven't heard of that yet.  (reCAPTCHA support might be nice anyway, of course.)

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Sure, I'm finding automatically registered bot accounts on my server from time to time, last time over 1000 of those. And the captcha is enabled.

**Comment by badlop** [comment]
Another example captcha script `captcha-ng.sh` was added in b41ce8828c579f06a33ca93a7af4fd5984997e16 for ejabberd 21.04. It's better than the minimal `captcha.sh`, even if it's isn't as good as image-based CAPTCHAs. At least it doesn't require third-party setups...
