### ISSUE TITLE
Improper display of users in admin panel

### ISSUE THREAD

**Issue by drixter** [processone/ejabberd#1217]
> What version of ejabberd are you using?

16.06

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Wrong formating, improper display of userlist in admin panel
No error in logs.

![przechwytywanie](https://cloud.githubusercontent.com/assets/5471983/17152699/3d38f0f8-5379-11e6-8252-60fd0221caff.PNG)

**Comment by badlop** [comment]
Sorry, I don't understand what exactly is wrong. Can you please explain?

**Comment by drixter** [comment]
It should be formatted and shoud looks like below, example from another host. It's looks that doesn't query SQL well or wrong parse the data and then generate HTML.

![przechwytywanie2](https://cloud.githubusercontent.com/assets/5471983/17306440/5e45d872-5830-11e6-953c-3f694a100a43.PNG)

**Comment by badlop** [comment]
That's not a bug, it's a feature. If the host has few users, they are listed. If there are many users, it lists links to ranges of them. Do you want to receive a list with 1 million links? Your browser will crash.

**Comment by drixter** [comment]
OK :-) my fault.
