### ISSUE TITLE
Deployment from source

### ISSUE THREAD

**Issue by lxnx0** [processone/ejabberd#1218]
Thus is not exactly an issue. I just need to know is there any way how can I easily deploy the customised compiled version of ejabberd into production?

Is there any tool similar that can generate something like ejabberd-xx-installer.run (similar to https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.06/ejabberd-16.06-linux-x86_64-installer.run). So that, I can bring this `run` and install directly the compiled and tested version of ejabberd into production without recompile it in production machine.

**Comment by weiss** [comment]
After running `./configure && make`, you can run `make rel`.  That will populate a `rel/ejabberd` directory with ejabberd and all dependencies, including the required parts of Erlang/OTP.  You can tar up and copy that directory into an arbitrary location on other (binary-compatible) systems, and then use it as-is.  You need to [make sure][1] ejabberd is started/stopped (using the included `bin/ejabberdctl` script) yourself, though.

[1]: https://github.com/processone/ejabberd/blob/master/ejabberd.service.template

**Comment by lxnx0** [comment]
Hi weiss,

thank you for the guide provided. I keep getting the following : 

$ make rel
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
/usr/lib/erlang/bin/escript rebar generate
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/x86_64-linux-gnu-gcov-tool.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /path/source/ejabberd/rel: rebar_abort
Makefile:284: recipe for target 'rel' failed
make: *** [rel] Error 1

**Comment by weiss** [comment]
> It seems like something related to: https://bugs.launchpad.net/ubuntu/+source/erlang/+bug/1600780

Maybe the workaround described in that bug report works for you?

If all else fails, you could of course install [Erlang/OTP][1] from source.

[1]: https://www.erlang.org/downloads

**Comment by lxnx0** [comment]
Yes, the workaround works for me. Sorry for the late giving confirmation after running the workaround.
