### ISSUE TITLE
MUC Sub behavior

### ISSUE THREAD

**Issue by vikram17000** [processone/ejabberd#1220]
> What version of ejabberd are you using?

Latest commit from ejabberd-master.

> What operating system (version) are you using?

Ubuntu.

> How did you install ejabberd (source, package, distribution)?

Source.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

This is probably not a bug but rather a gap in my understanding.

I've started to integrate the latest ejabberd source to try and leverage the new MUC-Sub functionality. The feature looks very promising... many thanks for the initiative!

Post taking the new codebase, I find that each time a user creates a room, the recipient does not seem to be receiving any incoming message at all (I am using XMPPFramework on the iOS side). This wasn't the case of course earlier when if a new room was created, the recipient received an invite and a message representing the invite. I have made the user creating the room subscribed to MUC/Sub events per this documentation (https://docs.ejabberd.im/developer/proposed-extensions/muc-sub/). Plus I've set allow_subscription to be true in the yml file as well. Any pointers please as to why this might be happening?

Note that the room is indeed created successfully on the server....

Or am I missing something here?

**Comment by mremond** [comment]
The format of messages you receive when subscribed are different. You need to add client support for them.

**Comment by vikram17000** [comment]
I think I found another bug, wherein no messages were getting received at all. Cancelling this issue for now as clearly not an issue with the server. Thanks!
