### ISSUE TITLE
Syncing issue between database and admin panel

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#1224]
> What version of ejabberd are you using?

ejabberd 15.11

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

deb.package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In our admin panel the total number of registered users are not same as total in database , table data  synchronization  with  view  in admin panel has stopped. 
My concern is how it has stopped working and is it possible to know what could be the possible reason to triggered this behavior .

**Comment by badlop** [comment]
> In our admin panel the total number of registered users

In exactly what page do you get that number?

> are not same as total in database 

What database are you using, and how do you get that number?

**Comment by Nitin3589** [comment]
Hi  badlop,
I am using postgres 9.3.11 as database  and  page displaying is registered users and online users under it to which link is          http://xyz122131.mydcxgeapp.com:5280/admin/vhosts/    

I have one more query regarding database that ejabberd using text  type for each jid column in postgres while in mysql it is varchar  only  thus  if you make search on jid column query will take too long  , is there any perticular reason to keep it as text type?

**Comment by badlop** [comment]
I hope the problem was solved in the last two years, since 15.11 to 17.07, otherwise you can open it again. Regarding the second question, sorry, I don't know the reasons, but surely there must be, as PostgreSQL is the preferred database to use with ejabberd.
