### ISSUE TITLE
Connect to ejabberd servers using a Tor onion services

### ISSUE THREAD

**Issue by herbsmn** [processone/ejabberd#1227]
Is there a way to do what mod_onion does in ejabberd? https://modules.prosody.im/mod_onions.html

If so, can someone make the info easier to find, because I'm not seeing any information about it.

A lot of xmpp servers now are making it so you can connect to them via Tor Onion Services. https://www.torproject.org/docs/hidden-services.html.en

Are they all using Prosody to do this?

**Comment by zinid** [comment]
No, there is no such functionality that I'm aware of

**Comment by herbsmn** [comment]
I was told by @inputmice that this feature works out of the box. If this is true, it would be nice to have it mentioned or documented a little bit.

**Comment by weiss** [comment]
There's nothing specific to be implemented on the server side to allow clients to connect to an XMPP Onion Service.  That's probably what @iNPUTmice meant.

The Prosody module supports server-to-server connections to *other* XMPP Onion Services.  As @zinid said, that's currently not implemented for ejabberd (as far as I know).
