### ISSUE TITLE
[Feature Request] Add localhost To Exceptions Of mod_fail2ban

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1228]
> What version of ejabberd are you using?

16.06

> What operating system (version) are you using?

Debian Stable 8.5.

> How did you install ejabberd (source, package, distribution)?

Distribution.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Module mod_fail2ban should have exception list of addresses not to ban at all. My server has both public ICANN-registered domain name and additionally onion-address for security-minded users. So the connections to the hidden address appears to mod_fail2ban as originating from localhost.

When some rogue user tries to bruteforce password of some account using hidden address connection, and runs out of authentication attempts, mod_fail2ban triggers lock out for the localhost, thus disconnects the entire hidden address and all its users. That's why I had to disable mod_fail2ban.

If we will have option to ignore some IPs, or at least ignore localhost, that'll help greatly.

**Comment by zinid** [comment]
`mod_fail2ban` has `access` option, refer to the documentation https://docs.ejabberd.im/admin/guide/configuration/#modfail2ban
I think that's what you need.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Oh, missed this one. Thanks.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
If anyone is interested, that's how to whitelist localhost:

```
modules:
  mod_fail2ban:
    c2s_auth_ban_lifetime: 259200
    c2s_max_auth_failures: 10
    access: fail2ban

access:
  fail2ban:
    loopback: allow
```
