### ISSUE TITLE
push_alltoall string/binary conversion

### ISSUE THREAD

**Issue by dhofer** [processone/ejabberd#1229]
> What version of ejabberd are you using?
16.06

> What operating system (version) are you using?
Debian Jessie

> How did you install ejabberd (source, package, distribution)?
package (https://jabber.at/en/apt-repository)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Looks like this commit https://github.com/processone/ejabberd/commit/4ccc40bce53f177a862224b50d21dee8965e729d broke push_alltoall.

(ejabberd@jabber01)1> mod_admin_extra:push_alltoall(<<"example.com">>, <<"example.com">>).
** exception error: bad argument
     in function  list_to_binary/1
        called as list_to_binary(<<"user1">>)
     in call from mod_admin_extra:subscribe_roster/2 (src/mod_admin_extra.erl, line 1169)
     in call from mod_admin_extra:subscribe_all/2 (src/mod_admin_extra.erl, line 1159)
     in call from mod_admin_extra:push_alltoall/2 (src/mod_admin_extra.erl, line 1176)

**Comment by cromain** [comment]
indeed, thanks for reporting !
