### ISSUE TITLE
MUC/Sub behavior - user not subscribed after reconnection

### ISSUE THREAD

**Issue by vikram17000** [processone/ejabberd#1230]
> What version of ejabberd are you using?

ejabberd-master

> What operating system (version) are you using?

Ubuntu 16.04 Xenial

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi - I'm testing MUC/Sub and could subscribe to a room, thereby ensuring that if the user connection goes down, the room does not get destroyed. However, when I relogin back, fetching the room occupant list (using ejabberdctl get_room_occupants) returns the original user but with the status "none" instead of participant / moderator. That doesn't seem like the expectation? Is there anything specific I need to do here...

Similarly, if I reconnect the user and send the subscription get IQ at start-up, the client receives only the roster IQ result, not the mucsub subscriptions. That leads me to believe that after session re-connect, the subscriptions are not getting renewed... Is that something I am missing here?

**Comment by mremond** [comment]
It seems you also crossposted you issue on Stackoverflow, so I will not give more details here:
Please see: http://stackoverflow.com/questions/38748283/ejabberd-muc-and-muc-sub-clarification/38762649#38762649

Bottom line: If you want the room not to be destroyed when last occupant leave, make it persistent and not temporary. This is an room option, defined in XEP-0045.
