### ISSUE TITLE
ejabberd commands 'register' no longer working

### ISSUE THREAD

**Issue by xmppjingle** [processone/ejabberd#1231]
> What version of ejabberd are you using?
master branch

> What operating system (version) are you using?
osx and debian (occurs in both)

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
`ejabberdctl register user my-domain.com password`
Used to work fine, after master branch from August 4, it doesn't work anymore followed by the following error message:

```
Thiagos-MacBook-Pro:~ root# ejabberdctl register thiago localhost password
{error,access_rules_unauthorized}
```

> was the unexpected behavior? What was the expected result?
expected to have user registered, it doesn't get registered.

**Comment by mremond** [comment]
Sorry, we added by error check of access_rules and credential on the command line as well. We commited a fix to restore previous behaviour in master.

**Comment by jrdemasi** [comment]
How long until we can expect a tagged release that includes this?  Kind of a big one....

**Comment by orbifx** [comment]
Is there a workaround until the various packages manager catch up?

**Comment by jrdemasi** [comment]
You can temporarily enable in-band registration and if necessary update
firewall rules to only allow a certain IP in, add an account, make said
account an admin user, then add other through the web interface.  Does that
make sense?

**Comment by orbifx** [comment]
Yes, thanks. Used the web interface.
-- 
    SP

**Comment by ScrumpyJack** [comment]
Can we have a tagged release for this patch? ejabberd packages need rebuilding

**Comment by jrdemasi** [comment]
Agreed 100% on that..

**Comment by mremond** [comment]
ejabberd 16.09 will be released shortly and will include that fix.

**Comment by jonasv** [comment]
How soon is shortly ? You distributing software which doesn't work.

**Comment by asimrk** [comment]
you can use any client software to register admin account.

**Comment by ThangPM** [comment]
Hi mremond,
I am using ejabberd 16.09 and struggling with a problem like this:
`A problem '{error,account_unprivileged}' occurred executing the command register with arguments
[{user,<<"123456_dev">>},
 {password,<<"341343">>},
 {host,<<"domain.com">>}]` 
I got this error when I create new user by java application. Could you help me resolve this problem. Thank you!

**Comment by mremond** [comment]
Make sure you are passing the X-Admin header flag in the HTTP request.

**Comment by ThangPM** [comment]
@mremond Thanks for your answer.
I got the above error when I use these line in this config 
`port: 4560
     module: ejabberd_xmlrpc
     maxsessions: 10
     timeout: 5000
     access_commands: 
       admin:
         commands: all
         options: []`
I did remove last 3 lines and set config `access_commands: {}` but it wouldn't work. Now I already fixed this problem by changing minor thing in ejabberd.yml like this `access_commands: []`. Do you think this is a right solution?

**Comment by badlop** [comment]
Configure like this:
```
listen:
  - 
    port: 4560
    module: ejabberd_xmlrpc
    maxsessions: 10
    timeout: 5000
    access_commands:
      configure:
        commands: all
        options: []

commands_admin_access: configure

access_rules:
  configure: 
    - allow: admin

acl:
  admin:
    user:
      - "user1@localhost"
```

Then a client like this:
```
import xmlrpclib

server_url = 'http://127.0.0.1:4560'
server = xmlrpclib.ServerProxy(server_url)

LOGIN = {'user': 'user1', 'server': 'localhost', 'password': 'pa11', 'admin': True}

def ejabberdctl(command, data):
    fn = getattr(server, command)
    return fn(LOGIN, data)

print "Calling with auth details..."
result = ejabberdctl('registered_users', {'host':'localhost'})
print "Results: "
print result
```

Should work correctly:
```
$ python test.py 
Calling with auth details...
Results: 
{'users': [{'username': 'user1'}, {'username': 'user1www'}, {'username': 'user2'}]}
```

**Comment by ThangPM** [comment]
@badlop 
Hello,
Thank you for your answer!
I already configured as your way but my client is written in java. Unfortunately, I still got the account_unprivileged error.  Here is my code:
`
public int createAccount(String phoneNumber, String host, String xmppPassword) {
	XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
	config.setServerURL(new URL("127.0.0.1" + ":" + 4560));

	XmlRpcClient client = new XmlRpcClient();
	client.setConfig(config);

    List<Object> roster_params = new ArrayList<Object>();
    Hashtable<String, Object> params = new Hashtable<String, Object>();
    params.put("user", phoneNumber);
    params.put("host", host);
    params.put("password", xmppPassword);

    roster_params.add(params);
    try {
        Object result = Object response = (Object) client.execute("register", roster_params);
        
        if (result.toString().contains("res=0")) {
            return 1;
        }
    }
    catch (XmlRpcException e) {
        e.printStackTrace();
    }
    return 0;
}
`
Could you help me check this issue? Thank you!
Have a nice weekend!
