### ISSUE TITLE
Where is stored ejabberd version

### ISSUE THREAD

**Issue by Zarratustra** [processone/ejabberd#1234]
When I uninstalled old ejabberd version and tried to install the newest ejabberd it still says that there is version `v2.1.8.2363` even though Im sure that there is 16.06.64 running.
I know that ejabberd version for `ejabberd.app.src` file is generated by autoconf tool. Where is the value stored so that I could set it manually?

**Comment by ludwikbukowski** [comment]
looks like the version is taken from the latest commit tag:
https://github.com/processone/ejabberd/blob/master/configure.ac#L5
I suppose you have old ejabberd tags in your ejabberd git repo.

**Comment by cromain** [comment]
you have to regenerate configure using autogen.sh
