### ISSUE TITLE
MUC disco_items "Empty Rooms" behavior change in 16.x

### ISSUE THREAD

**Issue by gardenia** [processone/ejabberd#1236]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debian Jessie (64 bit)

> How did you install ejabberd (source, package, distribution)?

binary distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have been testing 16.08 with a view to upgrading (from 14.12).  I have noticed that MUC behavior has changed in 16.0x as follows:

in EJAB-343 (https://support.process-one.net/browse/EJAB-343) the behavior of iq_disco_items (in mod_muc.erl) was changed such that rather than returning all rooms applicable to a user the behavior is now to first check to see if the total number of rooms in the vhost exceeds a maximum in which case the query falls back to querying only non-empty rooms:

https://github.com/processone/ejabberd/blob/master/src/mod_muc.erl#L626

in the case where only non-empty rooms are queried the additional disco item "Empty Rooms" is returned to enable empty rooms to be explicitly queried.

My quesiton is: it looks like the decision to show all applicable vs only non-empty rooms is based on the total number of rooms in the virtual host.  but shouldn't that decision be made based on the number of rooms that would be returned for a given query? 

I guess with public rooms it may be different.  but I'm thinking of a case where all rooms are private.  so for example: lets say there are 300 rooms in a given vhost, all non-public and lets also say that a given user (Alice) is the owner of 1 room and a member of 1 room but those rooms are currently empty.

if there had been 99 rooms in total in the vhost then Alice would get returned the expected 2 rooms when discovering her rooms.

However, if there are 101 rooms in the vhost then Alice will get returned only the "Empty Rooms" result.

I'm wondering if that divergence outlined above is on the wrong factor.  i.e. shouldn't it be established how many results would be applicable to Alice before deciding to limit/filter the returned results? 

my interpretation of https://support.process-one.net/browse/EJAB-343 and http://www.xmpp.org/extensions/xep-0045.html#disco-rooms is that the limiting of the result set should be based on the size of the eventual result set rather than the total number of rooms in the vhost.

in particular I would argue that I should be able to discover rooms I am an admin of whether they are empty or not with the normal disco query.

what do you think?  tagging @badlop and @cromain who were involved in the original code change.  I'd really appreciate your feedback in particular.

Thanks.

**Comment by badlop** [comment]
What you propose is extreme accuracy. The code was designed for extreme efficiency. Notice that in order to know the details of a room (whether it's public, if it has occupants, and if you're admin), it is necessary to query the room.

In the case you describe, the current code efficiency isn't necessary (just a hundred rooms), and its accuracy is very very low. You are right on that.

But when you have thousands or millions of rooms with random settings (public/notpublic, empty/notempty...), the current code efficiency is very good and the accuracy is good enough.

**Comment by gardenia** [comment]
ok that is pretty much what I thought.

I would propose a compromise whereby the MAX_ROOMS_DISCOITEMS is made configurable.  that way in the scenario I outlined if there are only a few hundred private rooms on a given deployment then the MAX_ROOMS_DISCOITEMS could be re-configured to (say) 1000 on that particular deployment which would yield the required accuracy without any compromise to the millions of rooms use-case.

if you agree I will put together a PR to make it configurable.  Thanks.

**Comment by badlop** [comment]
Ok.

**Comment by marcphilipp** [comment]
We've also discovered this issue. Any news?

**Comment by gardenia** [comment]
@marcphilipp in my case I did a termporary workaround by forking mod_muc.erl and changing the MAX_ROOMS_DISCOITEMS define as per this patch:

[ejd_muc_discoitems.txt](https://github.com/processone/ejabberd/files/458935/ejd_muc_discoitems.txt)

I looked briefly at making it configuration driven a while back.  the changes were a little more far-reaching than I expcted becaue the usage of MAX_ROOMS_DISCOITEMS is a few levels deep and would require changing a few prototypes (including process_iq_disco_items/4 exported function).  I hope revisit it soon.

**Comment by gardenia** [comment]
see PR #1343
