### ISSUE TITLE
Can't register user with ejabberdctl

### ISSUE THREAD

**Issue by sailerinteractive** [processone/ejabberd#1237]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.08/ejabberd_16.08-0_amd64.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After a fresh install and no changes to the config file i can not register a user from the command line:

ejabberdctl register florian server_name password
Error is: {error,access_rules_unauthorized}

server_name matches host in config file.

Exactly the same workflow works fine with 16.06

**Comment by debalance** [comment]
This is a duplicate of #1231, fixes are already commited to master.

**Comment by sailerinteractive** [comment]
Alright... sorry did not check for closed issues.
