### ISSUE TITLE
make rel failed

### ISSUE THREAD

**Issue by indie21** [processone/ejabberd#1238]
> What version of ejabberd are you using?
> 
> What operating system (version) are you using?

mac os x 

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

make rel failed ->

➜  ejabberd_dev git:(jhqc-master) make rel
/usr/local/Cellar/erlang/18.3/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (pre_compile)
==> rel (compile)
==> ejabberd_dev (pre_compile)
==> ejabberd_dev (compile)
/usr/local/Cellar/erlang/18.3/lib/erlang/bin/escript rebar generate
==> rel (generate)
ERROR: Unable to generate spec: read file info /Users/zhuoyikang/source/services/ejabberd_dev/_build/dev/lib/bbmustache/ebin failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /Users/zhuoyikang/source/services/ejabberd_dev/rel: rebar_abort

**Comment by badlop** [comment]
In my case, `make rel` fails due to other reason:
```
$ make rel
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
/usr/lib/erlang/bin/escript rebar generate
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/x86_64-linux-gnu-gcov-tool.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /f/jabber/p1/git/ejabberd/rel: rebar_abort
Makefile:285: recipe for target 'rel' failed
make: *** [rel] Error 1
```
By why is this a problem? In the last year nobody else complained.

**Comment by weiss** [comment]
FWIW, I use `make rel` as well, but can't reproduce the problem with the current `master` code (and OTP 19).
