### ISSUE TITLE
Windows Install failure for Ejabberd - 16.08

### ISSUE THREAD

**Issue by wakerb** [processone/ejabberd#1239]
> What version of ejabberd are you using?

ejabberd-16.08
> What operating system (version) are you using?
Windows 7, 8, 10 and 2008R2
> How did you install ejabberd (source, package, distribution)?
“ejabberd-16.08-windows-installer.exe” downloaded from Process One.

> was the unexpected behavior? What was the expected result?

I am trying to install ejabberd in a windows environment. I am using
“ejabberd-16.08-windows-installer.exe” downloaded from Process One.

On a fully updated Windows 7 machine I get the message “erl.exe has
stopped working” at the very end of the install process:

The problem details are as follows :
Problem signature:
Problem Event Name: APPCRASH
Application Name: erl.exe
Application Version: 0.0.0.0
Application Timestamp: 56e73526
Fault Module Name: MSVCR120.dll
Fault Module Version: 12.0.21005.1
Fault Module Timestamp: 524f83ff
Exception Code: c0000005
Exception Offset: 000000000003c798
OS Version: 6.1.7601.2.1.0.256.48
Locale ID: 4105
Additional Information 1: 0fec
Additional Information 2: 0fecfbdee4b4e2f296291b395a3061e1
Additional Information 3: b420
Additional Information 4: b4206e631e4193273c882a1e62a3d5d8

On a Windows 8 laptop, the install completes but when I launch the “Start
Ejabberd”, it complains about a missing MSVCR120.dll file then in says
epmd.exe has stopped working. I found a copy of MSVCR120.dll in a folder for
another application and when I copy it into the ejabberd/bin folder,
ejabberd does start but I cannot log into the admin interface using the
credentials I specified. It simply re-asks for the username and password.

On a newly installed Windows 10 desktop, the install completes but generally
operates much like the Windows 8 machine above. However the MSVCR120.dll on
that machine causes ejabberd to crash when copied to the ejabberd folder.

On a fully updated Windows 2008 R2 server. Ejabberd appears to install
correctly and starts, but I cannot log into the admin interface. It simply re-asks for the username and password.

**Comment by QomariSanjaya** [comment]
I am using ejabberd 16.08 and Windows 7 Ultimate 64 bit, got same error.
I fixed it by installing Visual C++ Redistributable Packages for Visual Studio 2013 (http://www.microsoft.com/en-us/download/details.aspx?id=40784)

**Comment by wakerb** [comment]
Thanks QomariSanjaya

Installing the Visual C++ package seemed to fix the install errors but I can not login into the system using the username and password I assigned:
localhost:5280/admin/
It simply re-asks for the username and password
I have installed and uninstalled a few times.

**Comment by QomariSanjaya** [comment]
16.08 has some bugs with windows. Try using 16.06 instead.

**Comment by wakerb** [comment]
I tried 16.06 on both Windows 10 and Server 2008R2 machines with no success.  Attached are the install log and the ejabberd log.  The ejabberd log simply says the admin account does not exist. 

[ejabberd-logs.zip](https://github.com/processone/ejabberd/files/420902/ejabberd-logs.zip)

**Comment by wakerb** [comment]
Thank you for your help QomariSanjaya
Installing the C++ Redistributable Packages fixed the erl errors.  I will close this case and open another for the admin login problem which appears to be a separate issue.
