### ISSUE TITLE
Stream management behind a load balancer

### ISSUE THREAD

**Issue by kishoreacesurf** [processone/ejabberd#1243]
> What version of ejabberd are you using?

16.08 

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am running 3 nodes of Ejabberd in ejabberd cluster. I have configured a load balancer on azure to route the traffic among the 3 servers. Stream was showing as connected for the client but actually the user is not online. When I take out the load balancer it works as expected. Let me know the catch here

**Comment by weiss** [comment]
> Stream was showing as connected for the client but actually the user is not online.

Does he appear as online despite being offline for longer than 5 minutes (or if you configured a `resume_timeout`, longer than the specified number of seconds)?
