### ISSUE TITLE
CRASH ejabberd_oauth:init/1

### ISSUE THREAD

**Issue by hamano** [processone/ejabberd#1246]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

OTP/17 on Linux

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

send_after/3 timer limit 0 <= Time <= 4294967295 on OTP 17,
So, oauth module doesn't work even if configureed disable_sasl_mechanisms: ["X-OAUTH2"]

~~~
18:12:44.088 [error] CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason:
 bad argument in call to erlang:send_after(31536000000, <0.402.0>, clean)
 in ejabberd_oauth:init/1 line 172
~~~

**Comment by badlop** [comment]
Ah right, erlang documentation says:
> The Time value can, in the current implementation, not be greater than 4294967295.

Can you try if this change is enough to solve it?
```
diff --git a/src/ejabberd_oauth.erl b/src/ejabberd_oauth.erl
index ca06936..a19f75c 100644
--- a/src/ejabberd_oauth.erl
+++ b/src/ejabberd_oauth.erl
@@ -66,7 +66,7 @@
 %%   * Using the command line and oauth_issue_token command, the token is generated in behalf of ejabberd' sysadmin
 %%    (as it has access to ejabberd command line).
 
--define(EXPIRE, 31536000).
+-define(EXPIRE, 4294967).
 
 start() ->
     DBMod = get_db_backend(),
```

**Comment by hamano** [comment]
OK, solved. Thank you!
