### ISSUE TITLE
Elixir application not started

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1250]
> What version of ejabberd are you using?

16.08.

> What operating system (version) are you using?

Debian Jessie.

> How did you install ejabberd (source, package, distribution)?

Debian testing repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After updating ejabberd to the version 16.08 there is one error in `error.log`:

`2016-08-16 13:47:48.349 [error] <0.38.0>@ejabberd_app:start_elixir_application:245 Elixir application not started.`

but seems like ejabberd is up and running. This is crucial or can be ignored?

**Comment by idl0r** [comment]
I can confirm that. 16.08. Same error.

**Comment by savek-cc** [comment]
+1

**Comment by debalance** [comment]
Hi,
please report issues with Debian's Jessie-Backports to the Debian BTS, the best way to do that is using "reportbug", that will include valuable additional information.

The ejabberd package in Debian doesn't have Elixir support enabled. So far this hasn't been an issue, I'm curious myself why this is logged as an error.

If you think you need Elixir support in Debian's ejabberd you're welcome to help out!
See https://bugs.debian.org/767874

**Comment by IUnderstandLetsChangeMyUsername** [comment]
I personally don't think that I need Elixir support (honestly I even don't know what good it does) so if I understood you right, I can just ignore this error.

**Comment by weiss** [comment]
Elixir support is still optional, so this should probably not be an `[error]` message.  I'll therefore reopen this issue, but you can ignore the message either way, yes.
