### ISSUE TITLE
flood control on message stanza

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1252]
> What version of ejabberd are you using?
> 16.06
> 
> What operating system (version) are you using?
> Fedora
> 
> How did you install ejabberd (source, package, distribution)?
> Source - master branch
> 
> What did not work as expected? Are there error messages in the log? 
> NA
> was the unexpected behavior? What was the expected result?
> NA

Wanted to know if i can prevent flooding for message stanza from a user say max 1000 message stanzas per min later we block messages stanzas only for sometime ?

**Comment by cromain** [comment]
This is what shapers do in terms of allowed bytes/secs.
There is no module that counts messages and allow each users a given number of message per unit of time.
This could be done by a module. Feel free to create a PR if you write such module.
