### ISSUE TITLE
XEP-0334 store processing hint in MUC room

### ISSUE THREAD

**Issue by mhofman** [processone/ejabberd#1258]
> What version of ejabberd are you using?
16.08

> What operating system (version) are you using?
N/A

> How did you install ejabberd (source, package, distribution)?
N/A

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Messages sent to MUC rooms without a body or subject, but with a Message Processing Hints (XEP-0334) `store` element should be archived by the room.

It looks like the current logic doesn't honor the `store` processing hints: https://github.com/processone/ejabberd/blob/16.08/src/mod_muc_room.erl#L943

**Comment by weiss** [comment]
> https://github.com/processone/ejabberd/blob/16.08/src/mod_muc_room.erl#L943

This is where messages are added to the [discussion history][1], while you probably had [MAM][2] archives in mind?  For those, the `<store/>` hint should [be honored][3].

[1]: https://xmpp.org/extensions/xep-0045.html#enter-history
[2]: https://xmpp.org/extensions/xep-0313.html
[3]: https://github.com/processone/ejabberd/commit/5ce0b062ffb804bb81ec4e68bd0f9656a5ce3f3e

**Comment by mhofman** [comment]
Indeed, my bad. Thanks for the quick clarification.
