### ISSUE TITLE
mod_http_upload_quota and custom max_days options for different groups of users

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1259]
> What version of ejabberd are you using?

16.08.

> What operating system (version) are you using?

Debian Jessie (Stable).

> How did you install ejabberd (source, package, distribution)?

Testing Repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

There is a `mod_http_upload_quota` module and it has `max_days` option. It is possible to set this on a per-group basis, for example some days for all users and unlimited for some selected users?

If not, consider this issue a feature request.

**Comment by badlop** [comment]
> It is possible to set this on a per-group basis, for example some days for all users and unlimited for some selected users?

Not possible with the module options. But I think there is a dirty way to accomplish something similar: Set another vhost in ejabberd, and for it, define as specific modules mod_http_upload and _quota with different options: different docroot, max_days... and call it uploadvip.example.com Then tell your premium users to use that one.
