### ISSUE TITLE
Failed to module_install on Windows.

### ISSUE THREAD

**Issue by jinq0123** [processone/ejabberd#1264]
> What version of ejabberd are you using?

ejabberd-16.08

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

ejabberd-16.08-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
C:\Program Files\ejabberd-16.08\bin>ejabberdctl module_install mod_cron

src/mod_cron.erl:12: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
src/mod_cron.erl:12: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
src/mod_cron.erl:65: Warning: erlang:now/0: Deprecated BIF.
 See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.

Problem 'error {case_clause,volumerelative}' occurred executing the command.
Stacktrace: [{ejabberd_config,get_absolute_path,1,
                              [{file,"src/ejabberd_config.erl"},{line,316}]},
             {ejabberd_config,get_plain_terms_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,226}]},
             {ejabberd_config,include_config_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,513}]},
             {lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},
             {ejabberd_config,include_config_files,1,
                              [{file,"src/ejabberd_config.erl"},{line,493}]},
             {ejabberd_config,read_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,150}]},
             {ejabberd_config,load_file,1,
                              [{file,"src/ejabberd_config.erl"},{line,168}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,172}]}]

C:\Program Files\ejabberd-16.08\bin>
```

**Comment by jinq0123** [comment]
And ejabberd can not restart after module_install error:
<pre>
2016-08-23 15:48:17.363 [error] <0.36.0> CRASH REPORT Process <0.36.0> with 0 neighbours exited with reason: no case clause matching volumerelative in ejabberd_config:get_absolute_path/1 line 319 in application_master:init/4 line 134
</pre>

Delete "AppData\Roaming\ejabberd\" and reinstall will not solve the problem.
Finally I found ```C:\.ejabberd-modules\``` and deleted it.

**Comment by badlop** [comment]
First, I've fixed the warnings about now().

Regarding the main problem, if we call filename:pathtype/1 
with values like /bar/foo.erl in Linux, it returns:
> filename:pathtype("/bar/foo.erl").
> absolute

But in Windows, apparently the function returns 'volumerelative'. And our ejabberd_config:get_absolute_path/1 doesn't know to handle that.

**Comment by jinq0123** [comment]
Why not use ```filename:absname/1```?

**Comment by cromain** [comment]
problem what double:

1/ if CONTRIB_MODULES_PATH is not defined (default behaviour) then we check for HOME
but HOME is not defined in windows, so it results as a volumerelative path instead of expected absolute path.
=> I fixed this by exporting HOME to ejabberd's AppData directory on windows by default. so if CONTRIB_MODULE_PATH is not defined, we use an absolute path anyway.

2/ ejabberd_config was not able to cope with volumerelative path type. This is still possible to generate a volumerelative path on windows if user explicitely set something like CONTRIB_MODULES_PATH="/some/where", so in that case, i force use of filename:absname, which converts the path to an absolute path.
