### ISSUE TITLE
ps: command not found

### ISSUE THREAD

**Issue by jinq0123** [processone/ejabberd#1265]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

ejabberd-16.08-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

<pre>
C:\Program Files\ejabberd-16.08\bin>ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 16.08 is running in that node

C:\Program Files\ejabberd-16.08\bin>ejabberdctl start
ejabberdctl: ps: command not found
ejabberdctl: ps: command not found

C:\Program Files\ejabberd-16.08\bin>
</pre>

**Comment by cromain** [comment]
indeed, ps.exe is missing from the packaging

**Comment by cromain** [comment]
i won't be able to get ps for windows, so we'll just assume ejabberd is really running if epmd detects the node, displaying the correct error message.
change is included in the package.
