### ISSUE TITLE
Register to MUC using mysql and php

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#1266]
> What version of ejabberd are you using?
> ejabberd 15.11.43
> 
> What operating system (version) are you using?
> centos
> 
> How did you install ejabberd (source, package, distribution)?
> source

Is it possible to insert manual to the database in muc_room and it will be created as room?

kindly i am using archiving in database i would ask you how can i get MUC history form DB and in what table is stored, also note if there is a description for the mysql tables and the role of each one,

Last question, is there a trusted php API library that i can use from your side?

Thank you,

**Comment by badlop** [comment]
> Is it possible to insert manual to the database in muc_room and it will be created as room?

If you enable mod_muc_admin in the ejabberd configuration file, you can create rooms by calling the ejabberd command: create_room name service host. You can call commands using the ejabberdctl shell script, or using XMLRPC with ejabberd_xmlrpc, or ReST with mod_rest...

For example, in the shell:
```
$ ejabberdctl create_room room7 conference.localhost localhost

$ ejabberdctl muc_online_rooms localhost
room7@conference.localhost
```

> Last question, is there a trusted php API library that i can use from your side?

mod_muc_admin provides commands for many other operations, like destroying rooms, setting room options... If you enable ejabberd_xmlrpc, you can call them using any language and any XMLRPC library...

> kindly i am using archiving in database i would ask you how can i get MUC history form DB and in what table is stored, 

If you mean mod_mam, it is stored in table 'archive'. If you mean the temporary room history, it is only keep in RAM, not stored permanently in database.

> also note if there is a description for the mysql tables and the role of each one,

Not documented.
