### ISSUE TITLE
mod_vcard_ldap empty response after updating from 16.03 to 16.08

### ISSUE THREAD

**Issue by AKorezin** [processone/ejabberd#1267]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debian 8 amd64

> How did you install ejabberd (source, package, distribution)?

apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm using ejabberd from debian 8 backports.

After upgrading ejabberd from 16.03 to 16.08 mod_vcard_ldap responses with empty vcard.
Mod_vcard_ldap search works.

I've created a clean installation with this config.
http://pastebin.com/Kc0Mxazb
or
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/433426/ejabberd.yml.txt)

And I'm receiving this error on vcard request.
http://pastebin.com/xUfwJsNY
or
[error.txt](https://github.com/processone/ejabberd/files/433443/error.txt)

The same in 16.06.

**Comment by frh** [comment]
I can confirm this issue after upgrading from 16.04 to 16.09. No change in the relevant configuration, yet vCards are now empty.

**Comment by PF4Public** [comment]
Any updates on this?

**Comment by Neustradamus** [comment]
@AKorezin, @frh, @PF4Public: It is solved in last current version?

**Comment by AKorezin** [comment]
@Neustradamus didn't use ejabberd for a year. As far as I remember there were no issue since 18.x

So I think this issue can be closed, because in 20.x everything works ok.

**Comment by frh** [comment]
> @AKorezin, @frh, @PF4Public: It is solved in last current version?

I don't use LDAP with ejabberd anymore, so I can't check. Sorry.
