### ISSUE TITLE
Block other xmpp client from accessing my ejabberd server

### ISSUE THREAD

**Issue by jeeva-sil** [processone/ejabberd#1269]
The server connection i used for my chat application is https://mydomainname.com:5280/http-bind so how to protect this to access only by my client application not others.

Now my server is accessible by any client like pidgin, adium etc How to block this.

I already asked this question in [http://stackoverflow.com/questions/38714030/block-other-xmpp-client-from-accessing-my-ejabberd-server/38714545#38714545](url) But i struggling to fix this

**Comment by badlop** [comment]
A quick and dirty solution that may work would be you slightly modify ejabberd source code, so your server isn't standard compliant. And also modify your client, of course. Something like this maybe does the trick?
```
diff --git a/src/ejabberd_http_bind.erl b/src/ejabberd_http_bind.erl
index 758c1ce..7e9b874 100644
--- a/src/ejabberd_http_bind.erl
+++ b/src/ejabberd_http_bind.erl
@@ -127,10 +127,10 @@
 
 -define(NS_CLIENT, <<"jabber:client">>).
 
--define(NS_BOSH, <<"urn:xmpp:xbosh">>).
+-define(NS_BOSH, <<"urn:xmpp:xboshjeeva">>).
 
 -define(NS_HTTP_BIND,
-	<<"http://jabber.org/protocol/httpbind">>).
+	<<"http://jabber.org/protocol/httpbindjeeva">>).
 
 -define(MAX_REQUESTS, 2).
 
```
