### ISSUE TITLE
Stream trailer behavior change in 16.04

### ISSUE THREAD

**Issue by gardenia** [processone/ejabberd#1270]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Linux Debian 64bit

> How did you install ejabberd (source, package, distribution)?

binary distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am using jitsi videobridge and one of its components (the jicofo agent) has a "focus" user which remains persistently connected to ejabberd (to facilitate its role in watching MUC rooms).

the problem I am having is that if that users TCP connection is timed-out due to failed pings (mod_ping) the behavior has changed in newer versions of ejabberd and I am trying to determine if this is to be expected.

in previous versions of ejabberd (I believe < 16.04) the behavior was for a mod_ping to terminate a session and for that to include a stream trailer ( "</stream:stream>").  the jicofo agent (or to be more specific, smack 3.2.x which it uses) appears to depend on the stream trailer to trigger its reconnection logic.  without the stream trailer the reconnection logic does not trigger in Smack (to be more speciifc it looks like that if a trailer is presence then Smack 3.2.x will throw an exception on this which will be caught and trigegr the reconnection logic).

as of 16.04, and I believe it may be a consequence of this change:
https://github.com/processone/ejabberd/commit/b83ec483e932cb11cfd547afa91afa43b0f6a2fb

there is no longer a stream trailer accomping the close from a mod_ping connection close/kick.

it seems the above code change is concerned with not sending a stream trailer if it is possible to resume the stream.  in fact I do have stream resumption enabled.

so my question is:
* is this change of behavior intended / correct
* if so then is jicofo (Smack 3.2.x) wrong in expecting a stream trailer to kick-off its recconnection logic

i believe the answer to the second point is "yes" it is wrong.  but I'm not sure if that is mutually exclusive with the first point.

Thanks.

**Comment by weiss** [comment]
> in previous versions of ejabberd (I believe < 16.04) the behavior was for a mod_ping to terminate a session and for that to include a stream trailer

No, both in earlier and later versions, it depends on whether stream management is enabled for that session.  If it is, `mod_ping` will just close the TCP connection but not the stream, so that the client has a chance to resume the session.  So the answers to your questions depend on whether the jicofo agent enables stream management.

**Comment by gardenia** [comment]
I don't believe jicofo enables stream management.  or not unless it is somehow implicitly enabled.

I don't believe stream management is even supported by Smack 3.2.x

**Comment by gardenia** [comment]
I checked a tcpdump I have from the jicofo conversation with ejabberd and it does not have any client-side enable of stream management as per here:

http://xmpp.org/extensions/xep-0198.html#enable

**Comment by weiss** [comment]
In that case, from reading the code, I'd expect ejabberd 16.08 to send a stream trailer before closing the connection just like earlier versions did.  But I didn't actually test this myself.  What makes you assume that no trailer is sent?

**Comment by gardenia** [comment]
apologies.  you are quite correct.

my initial bug report facts were inverted.  

in fact it is the case that:
* in ejabberd >= 16.04 there *is* a stream trailer when jicofo is kicked by mod_ping
* in ejabberd < 16.04 there is not a stream trailer in the same scenario

so your expectation is correct and it seems like this trailer issues was a but in ejabberd < 16.04?

in terms of the jicofo problem - it seems like jicofo (or really smack 3.2.x) was depending on the lack of a stream trailer which caused the XML pull parser to throw an expectation when the stream closed without the trailer.  and that expectation was caught and triggered the reconnection code.

when ejabberd started sending the trailer there was no mismatched stream so the XML parser had nothing to complain about and so no expectation was thrown/caught.

**Comment by weiss** [comment]
Ah, yes, that way round it makes sense :-)  And that's indeed a side effect of b83ec483e932cb11cfd547afa91afa43b0f6a2fb.

But as the new behavior seems fine to me, I guess this issue should rather be addressed in jicofo?

**Comment by gardenia** [comment]
yes agreed.  I can't quibble with ejabberd behavior so I will close this issue.

Thanks for your help.
