### ISSUE TITLE
modules_update_specs generates {error, unknown_command}

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1273]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debian 8.5.0

> How did you install ejabberd (source, package, distribution)?

Deb package

> What did not work as expected? Are there error messages in the log? What

I was using 16.06 then I've installed 16.08 with deb package from process one website. Then try to make the configuration again and found out when I execute the command
ejabberdctl modules_update_specs

it says {error, unknown_command) and I cannot install the modules that I want so I cannot use ejabberd

> was the unexpected behavior? What was the expected result?

**Comment by weiss** [comment]
In the title of this issue, the trailing "s" is missing from the command name.  Could you double-check by copy-pasting the command line `ejabberdctl modules-update-specs`?

**Comment by tolgatanriverdi** [comment]
I've just misspelled it while writing on the github, actually I'm executing ejabberdctl modules-update-specs command but the result is same (unknown_command)

**Comment by tolgatanriverdi** [comment]
I think I've found the problem when I check the man page of the ejabberdctl it says the command is
modules_update_specs
but what you've suggested worked instead modules-update-specs (with regular -)

**Comment by weiss** [comment]
No, both should work just fine (`-` and `_` is interchangeable on the `ejabberdctl` command line).

**Comment by tolgatanriverdi** [comment]
I've one last question 
When I try to execute "./ejabberdctl register admin localhost 123456" command  ejabberd says
{error, access_rules_unauthorized) 
So I cannot add users to ejabberd and therefore I cannot add admin user
There wasnt any problem in the past versions, why did this happened?
What can I do to fix that?

**Comment by weiss** [comment]
> I've one last question 

Does that mean your original issues is resolved?

> When I try to execute "./ejabberdctl register admin localhost 123456" command ejabberd says
{error, access_rules_unauthorized)

See #1231 and https://github.com/processone/ejabberd/issues/1263#issuecomment-241690168.
