### ISSUE TITLE
ejabberd loses connectivity to MySQL

### ISSUE THREAD

**Issue by DeerBeer** [processone/ejabberd#1274]
> What version of ejabberd are you using?
16.04.99

> What operating system (version) are you using?
CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have setup two ejabberd instances working in cluster and I'm using MySQL for database to for users, history,.... Everything works fine but after a while server can't communicate with database, every query attempt is returning 1033 error
log:
2016-08-15 08:48:36.685 [debug] <0.23542.9>@ejabberd_sql:sql_query_internal:570 SQL: "select password from users where username='some_username'"
2016-08-15 08:48:36.685 [error] <0.29991.18>@ejabberd_sql:check_error:1033 SQL query 'Q9525209' at {sql_queries,145} failed: <<"Failed sending data on socket : closed">>

**Comment by cdroege** [comment]
It could be that your sql server closes the connection after a period of time with no data.. Did you set the option "sql_keepalive_interval" in your configuration file?

**Comment by DeerBeer** [comment]
I have set now the "sql_keepalive_interval" to 600, for now is good. If happens again I'll write. Thx

**Comment by DeerBeer** [comment]
it fixed the problem, it stable enough to conclude that. Thx
