### ISSUE TITLE
Admin account not recognized on installation (windows)

### ISSUE THREAD

**Issue by johnnyAnd** [processone/ejabberd#1276]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

window s 7

> How did you install ejabberd (source, package, distribution)?

direct installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When i try to login at http://localhost:5280/admin/
with default admin user and password I added while installation, it keeps reloading the page.

What should be the solution, i saw other questions but this is windows specific.

Thanks

**Comment by badlop** [comment]
There was a bug in ejabberd 16.08, and the installer cannot register the account that you configured to be admin. Check in the ejabberd logs to confirm that there was a problem when trying to register that account.

In that case, the solution is that you register that account using any Jabber client. Once you register it, try again to login in the webadmin.

**Comment by johnnyAnd** [comment]
@badlop any idea when this is going to resolve or when 16.09 is coming up ?

**Comment by cromain** [comment]
fixed by #1231
