### ISSUE TITLE
Crash: no match of right hand value in ejabberd_sql

### ISSUE THREAD

**Issue by apalacheno** [processone/ejabberd#1277]
> What version of ejabberd are you using?

**16.08**

> What operating system (version) are you using?

**Ubuntu 14.04.5**

> How did you install ejabberd (source, package, distribution)?

**Linux x86 64-bits DEB Package**

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberd with PostgreSQL backend (connected via ODBC) crashes sometimes when a client tries to register. Only certain users are affected. From what I've seen I suspect that happens whenever the client (using a mobile device) changes connections, e.g. from WIFI to mobile network. The error message is repeated roughly every 30 seconds for this user. This happens since the migration from 15.11 to 16.08.

Error message in ejabberd.log:

```
2016-09-01 19:38:58.201 [debug] <0.417.0>@ejabberd_sql:sql_query_internal:570
 SQL: "select usec, pid, username, resource, priority, info from sm
 where username='alice' and resource='mobile'"
2016-09-01 19:38:58.205 [debug] <0.1354.0>@ejabberd_c2s:send_text:1866
 Send XML on stream = <<"</stream:stream>">>
2016-09-01 19:38:58.206 [error] <0.1354.0> gen_fsm <0.1354.0>
 in state wait_for_bind terminated with reason:
 no match of right hand value {error,{1,erl_parse,["syntax error before: ","'\\\\'"]}}
 in ejabberd_sql:decode_term/1 line 239
2016-09-01 19:38:58.207 [error] <0.1354.0> CRASH REPORT
 Process <0.1354.0> with 0 neighbours exited with reason:
 no match of right hand value {error,{1,erl_parse,["syntax error before: ","'\\\\'"]}}
 in ejabberd_sql:decode_term/1 line 239 in p1_fsm:terminate/8 line 760
```

This is the relevant SQL configuration:

```
sql_type: odbc
sql_server: "DSN=PSQLejabberd;UID=jabber;PWD=secret"

sql_keepalive_interval: 60
sql_start_interval: 30
sm_db_type: sql
```

The exactly same ODBC configuration (albeit using the old '_odbc_' expression instead of '_sql_') was used with ejabberd 15.11 without problems. The PostgreSQL database schema has been updated with the latest changes.

This is how the database side of things looks like:

```
ejabberd=> select usec, pid, username, resource, priority, info from sm where username='alice';
       usec       |     pid     | username | resource | priority |                                         info                                          
------------------+-------------+----------+----------+----------+---------------------------------------------------------------------------------------
 1472815890000272 | <0.18510.0> | alice    | mobile   | 0        | [{ip,{{80,187,118,116},23832}},\n {conn,c2s_tls},\n {auth_module,ejabberd_auth_ldap}]
 1472814865000233 | <0.2163.0>  | alice    | mobile   |          | [offline,{num_stanzas_in,14}]
(2 rows)
```

---

Additionally, ejabberd crashes once immediately after startup:

```
2016-09-02 11:42:31.451 [error] <0.461.0> CRASH REPORT
 Process <0.461.0> with 0 neighbours exited with reason:
 no match of right hand value {error,{1,erl_scan,{string,34,"alice\">>,<<\"examp"}},1}
 in ejabberd_sql:decode_term/1 line 238 in gen_server:init_it/6 line 352
```

At this point, the database looks like this:

```
ejabberd=> select usec, pid, username, resource, priority, info from sm where username='alice';
 usec | pid | username | resource | priority | info 
------+-----+----------+----------+----------+------
(0 rows)
```

The full debug output upon startup is attached:
[startup_debug_log.txt](https://github.com/processone/ejabberd/files/451752/startup_debug_log.txt)

The full configuration is also attached:
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/451753/ejabberd.yml.txt)

Let me know if you need additional info or debug output.

**Comment by apalacheno** [comment]
The described error does not appear with every user. As noted, I suspect that it occurs when the client changes its network. The error message is repeated roughly every 30 seconds for this user. During this time, this is what is stored in the database:

```
ejabberd=> select usec, pid, username, resource, priority, info from sm where username='alice';
       usec       |     pid     | username | resource | priority |                                         info                                          
------------------+-------------+----------+----------+----------+---------------------------------------------------------------------------------------
 1472815890000272 | <0.18510.0> | alice    | mobile   | 0        | [{ip,{{81,188,128,106},23832}},\n {conn,c2s_tls},\n {auth_module,ejabberd_auth_ldap}]
 1472814865000233 | <0.2163.0>  | alice    | mobile   |          | [offline,{num_stanzas_in,14}]
(2 rows)
```

**Comment by apalacheno** [comment]
Having tested ejabberd versions between 15.11 and 16.08, it seems that this bug has been introduced with ejabberd 16.06, as with 16.04 this error does not occur (using exactly the same configuration and database, of course).

**Comment by cromain** [comment]
we'll check if there is some typo around the odbc connector.
Keep in mind, when using mysql or pgsql you should use the native driver instead. ODBC connector should only be used when connecting to mssql. the combination of pgsql with odbc driver is not tested and out of scope.

**Comment by apalacheno** [comment]
Agreed, ODBC is suboptimal, but currently it's the only option when an encrypted connection to the database is required.

**Comment by cromain** [comment]
I have to postpone this to 17.01 as we can't handle this by now.
note: you still can use an ssh tunnel to encrypt your connection to db server.

**Comment by apalacheno** [comment]
Alright, thanks for working on it!

**Comment by zinid** [comment]
Why are you using ODBC in the first place? The native driver doesn't have such problems (there is a different escaping mechanism, that is pgsql compliant).

**Comment by zinid** [comment]
SSL support for pgsql is added: 03667d0c737f4de24f569edeeb33a480404026b0

**Comment by zinid** [comment]
Please use native driver for pgsql in the upcoming `17.01`. The configuration is quite simple:
```
...
sql_ssl: true
sql_ssl_certfile: "/path/to/cert.pem"
sql_ssl_verify: true
sql_ssl_cafile: "/path/to/caf.pem"
...
```
Only `sql_ssl` option is required to enable SSL (others are optional).

I'm closing the issue because we're not willing to fix this escaping mess.
