### ISSUE TITLE
Module extauth seems to start twice as many external auth processes as configured

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1278]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have the following entries in our `ejabberd.yml`:

```yml
auth_method: external
extauth_program: "/opt/ejabberd/bin/auth.pl"
extauth_instances: 5
```

However, when we start ejabberd it does not start 5 but 10 perl processes:
```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  11644  2664 ?        Ss   09:51   0:00 /bin/bash /opt/ejabberd/bin/start.sh
ejabberd    66  0.0  0.0  11584   104 ?        S    09:52   0:00 /opt/ejabberd-16.08/bin/epmd -daemon
root       267  0.0  0.0   4364   672 ?        S    09:52   0:00 tail -n +1 -F /opt/ejabberd/logs/ejabberd.log
root       268  0.0  0.1  11780  2960 ?        Ss   09:52   0:00 bash
ejabberd   396  0.0  4.9 1227736 101944 ?      Sl   11:10   0:00 /opt/ejabberd-16.08/bin/beam.smp -K true -P 250000 -- -root /opt/ejabberd-16.08 -progname /opt/ejabberd-16.08/bin/erl --
ejabberd   417  0.0  0.0  11544   972 ?        Ss   11:10   0:00 inet_gethost 4
ejabberd   418  0.0  0.0  13668  1564 ?        S    11:10   0:00 inet_gethost 4
ejabberd   419  0.0  0.0  17892  1884 ?        S    11:10   0:00 inet_gethost 4
ejabberd   420  0.0  0.6  60020 12848 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   421  0.0  0.6  60020 12888 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   422  0.0  0.6  60020 12768 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   423  0.0  0.6  60020 12884 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   424  0.0  0.6  60020 12752 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   425  0.0  0.6  60020 12864 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   426  0.0  0.6  60020 12820 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   427  0.0  0.6  60020 12828 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   428  0.2  0.6  60020 12828 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
ejabberd   429  0.0  0.6  60020 12748 ?        Ss   11:10   0:00 /usr/bin/perl /opt/ejabberd/bin/auth.pl
root       441  0.0  0.1  47432  3360 ?        R+   11:16   0:00 ps aux
```

When we change `extauth_instances` to 2 it starts 4, without specifying it it starts 2 (even though the default is [documented](https://docs.ejabberd.im/admin/guide/configuration/#external-script) to be 1).

Is this intentional? If so, why?

**Comment by badlop** [comment]
The option documentation says:
> Indicate how many instances of the script to run simultaneously to serve authentication in the virtual host. The default value is the minimum number: 1.

So, it starts those instances  for each vhost. So, I guess you have two vhosts defined in ejabberd configuration file, right?

**Comment by marcphilipp** [comment]
Thanks for the explanation. Makes sense after reading the documentation again. Maybe it would be more clear if you would change it to

> Indicate how many instances of the script _per_ virtual host to run simultaneously to serve authentication. The default value is the minimum number: 1.

**Comment by badlop** [comment]
> Indicate how many instances of the script per virtual host

But that's only in your case, you configured extauth as authentication script for all your vhosts. This is also shown in the simple configuration example provided just after the option explanation:
> This example ... starts three instances of the script for each virtual host defined in ejabberd:

This is not the case when ejabberd serves several vhosts each configured differently: one with extauth, others with sql, ...

**Comment by marcphilipp** [comment]
Point taken. Thanks again!
