### ISSUE TITLE
Can't install ejabberd on mint Rafaela

### ISSUE THREAD

**Issue by kkoci** [processone/ejabberd#1279]
> What version of ejabberd are you using?

Latest

> What operating system (version) are you using?

Linux Mint Rafaela

> How did you install ejabberd (source, package, distribution)?

sudo apt-get -y install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

It should install it, but the error message is as follows:

The following packages have unmet dependencies:
ejabberd : Depends: erlang-abi-15.b
E: Unable to correct problems, you have held broken packages.

There's no way to come around this, even with sudo apt-get -f install

Anyone knows how to fix this?

I'm very new to ejabberd, so any help would be greatly appreciated

Thanks in advance!

**Comment by badlop** [comment]
It may be some dependency problem between the packages and your current system. If you don't find any solution, you can try to install ejabberd from a binary package provided by ejabberd, or compiling ejabberd yourself. And after some time (weks, months), try again if the package can be installed correctly.

**Comment by kkoci** [comment]
Yes, I just installed the source, compiled it and everything went Ok, Thank You very much.
