### ISSUE TITLE
ejabberdctl: C:\Program: command not found

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#1280]
> What version of ejabberd are you using?

ejabberd-16.08-windows

> What operating system (version) are you using?

Windows 8.1 Pro x64 (8.3 Build 9600)

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.08/ejabberd-16.08-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I start or stop ejabberd with start.cmd/stop.cmd I get the following messages:

> C:\Program Files\ejabberd-16.08\bin>start.cmd
> Starting ejabberd...
> ejabberdctl: C:\Program: command not found
> ejabberdctl: C:\Program: command not found

> C:\Program Files\ejabberd-16.08\bin>stop.cmd
> Stopping ejabberd...
> ejabberdctl: C:\Program: command not found
> ejabberdctl: C:\Program: command not found

In the textfile ejabberdctl, I changed the line

>     INET_DIST_INTERFACE2=$($ERL -noshell -eval 'case inet:parse_address("'$INET_DIST_INTERFACE'") of {ok,IP} -> io:format("~p",[IP]); _ -> ok end.' -s erlang halt)

and put $ERL into double quotes:

>     INET_DIST_INTERFACE2=$("$ERL" -noshell -eval 'case inet:parse_address("'$INET_DIST_INTERFACE'") of {ok,IP} -> io:format("~p",[IP]); _ -> ok end.' -s erlang halt)

Then the messages "C:\Program: command not found" disappeard.

**Comment by cromain** [comment]
indeed, good catch !
the change is applyed to the packaging.
