### ISSUE TITLE
pam auth fails after upgrading from 16.06 to 16.08

### ISSUE THREAD

**Issue by JasperWallace** [processone/ejabberd#1281]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debian jessie 8.5

> How did you install ejabberd (source, package, distribution)?

jessie-backports package version 16.08-1~bpo8+1

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

pam authentication does not work, the epam process is running as ejabberd:ejabberd even tho the binary is setgid shadow. Without group shadow pam cannot access /etc/shadow and so it can't authenticate the user.

I've had a dig around in the ejabberd and epam source code and can't see anything obvious unfortunately.

Note that the epam binary was not changed by the upgrade (or downgrade to 16.06)

Debian bug report is here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836711

**Comment by debalance** [comment]
Your problem originates here: #1178 
I suggest you close this issue and join the discussion in #1178.

**Comment by cromain** [comment]
Holger's changes are merged, this can be closed now.
