### ISSUE TITLE
PubSub publish forbidden with subscriber publish model and ODBC backend

### ISSUE THREAD

**Issue by digislayer** [processone/ejabberd#1284]
> What version of ejabberd are you using?

16.06

> What operating system (version) are you using?

Ubuntu/Debian

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

PubSub doesn't work with ODBC. It works with the same configuration using mnesia, but not with ODBC. ODBC causes "forbidden" error upon publishing an item to a node.

I've checked the logs, and this is what I think is the problem:
```
2016-09-07 13:15:41.866 [debug] <0.5848.0>@ejabberd_sql:sql_query_internal:570
 SQL: "select affiliation from pubsub_state where nodeid=16
 and jid='57af5b73-b0c1-40d8-b669-e6e88aa8ee98@domain.com'"
2016-09-07 13:15:41.866 [debug] <0.5848.0>@ejabberd_sql:sql_query_internal:570
 SQL: "select subscriptions from pubsub_state where nodeid=16
 and jid='57af5b73-b0c1-40d8-b669-e6e88aa8ee98@domain.com/12584'"
```

Now, if you see, Affiliations are queried using the bare-jid but Subscriptions are queried using the full-jid. The MySql table "pubsub_state" actually contains only bare-jids. Thus, any valid subscriptions are not fetched and auth fails.

**Comment by cromain** [comment]
I confirm subscriptions are checked when node configured with subscriber publish model, but the check is uncomplete when subscribers are bare jid. This will be fixed.
Thanks for reporting this !

**Comment by digislayer** [comment]
Thank you for the acknowledgement, glad to hear this would be fixed! In the mean-time while I wait for 16.09, is there any fix/patch for 16.06? I would like to patch my server and keep it running.

Also, as another doubt based on your statement, wouldn't it be better to always perform these privilege checks using bare-jids? I ask this because, a user doesn't always connect using the same resource. Hence, if he subscribes while on resource "1234", but later logs in from resource "6789", wouldn't his publish requests still fail?

**Comment by cromain** [comment]
here is the patch.
to answer your question, in this situation there is no problem as long a user always subscribe bare jid (which should be default anyway)

**Comment by cromain** [comment]
syntaxic typo was injected by mistake... you have to contact both commits.
