### ISSUE TITLE
ejabberd adds online members to MUC name when using service discovery

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1286]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We're using service discovery to list available MUCs.
### Request

``` xml
<iq to='conference.example.com' from='alice@example.com/resource' type='get' xmlns='jabber:client' id='uuid'>
    <query xmlns='http://jabber.org/protocol/disco#items' />
</iq>
```
### Response

``` xml
<iq xmlns='jabber:client' from='conference.example.com' to='alice@example.com/resource' id='uuid' type='result'>
    <query xmlns='http://jabber.org/protocol/disco#items'>
...
        <item jid='chatroom@conference.example.com' name='room name (2)'/>
...
    </query>
</iq>
```

We want to show "room name" to our users, not "room name (2)". Why does ejabberd add `(2)` to the group name? Is there a way to avoid/configure this?

There's no mention of this behavior in [XEP-0045](http://xmpp.org/extensions/xep-0045.html#disco-rooms). After all `(2)` does not belong to the _name_ of the room.

**Comment by badlop** [comment]
> Why does ejabberd add (2) to the group name?

It indicates the number of room occupants, and also appends (private) if the room is private and the user has permission to view it.

> Is there a way to avoid/configure this?

Not configurable, but of course it can be removed in the source code:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index e5ed4cc..86761d2 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -723,8 +723,7 @@ handle_sync_event({get_disco_item, Filter, JID, Lang}, _From, StateName, StateDa
                     StateData#state.users),
     Reply = case (Filter == all) or (Filter == Len) or ((Filter /= 0) and (Len /= 0)) of
        true ->
-           get_roomdesc_reply(JID, StateData,
-                              get_roomdesc_tail(StateData, Lang));
+           get_roomdesc_reply(JID, StateData, <<"">>);
        false ->
            false
     end,
```

**Comment by marcphilipp** [comment]
We don't want to fork/patch ejabberd to change this. Would you consider a pull request where this is turned into a configuration option?

**Comment by badlop** [comment]
This is the first time I remember anybody asks for such an option, so I guess it will have almost no common use. So I prefer not to add such an option.
