### ISSUE TITLE
mod_http_upload Unexpected size (413 File size doesn't match requested size)

### ISSUE THREAD

**Issue by jeeva-sil** [processone/ejabberd#1289]
> What version of ejabberd are you using?

ejabberd 16.08.10

> What operating system (version) are you using?

Ubuntu Linux 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to upload file to the server using **mod_http_upload** but always i am getting error as _Unexpected size_

listen: 
  -
    port: 5443
    module: ejabberd_http
    tls: true
    certfile: "/home/cert/ejabberd.pem"
    request_handlers:
      "upload": mod_http_upload

access_rules:
  soft_upload_quota:
    - 1000: all # MiB
  hard_upload_quota:
    - 1100: all # MiB

modules: 
  mod_http_upload:
    docroot: "/home/files/xmpp/upload"
    put_url: "https://my.domain.in:5443/upload"
    get_url: "https://my.domain.in:5443/download"
    max_size: infinity
  mod_http_upload_quota:
    max_days: 100

Always getting info in ejabberd.log as

2016-09-09 18:14:07.682 [info] <0.18344.1>@mod_http_upload:process:433 Rejecting file from 110.172.170.241 for my.domain.in: Unexpected size (111650)

How to solve this problem ?. Is i am missing any configuration ?

**Comment by weiss** [comment]
The size of the data submitted in the HTTP PUT request doesn't match the size specified in the [slot request][1].

> i am missing any configuration ?

No.  This is a client issue, so you should ask the developer(s) to fix it.  Or, if you're the developer, fix it yourself :-)

[1]: http://xmpp.org/extensions/xep-0363.html#request

**Comment by jeeva-sil** [comment]
Yes i did the mistake, i unexpectedly set wrong file size while requesting slot. Now i fixed that and its working fine. Thanks WEISS ..
