### ISSUE TITLE
How to publish and subscribe in multi-user-chat rooms?

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1293]
The situation is the next:

On one hand, we have a room with ```William``` and ```Charles``` named ```Publishers```.
On the other hand we have a room with ```Alice``` and ```Bob``` named ```Subscribers```.

The default  behaviour of these rooms is correct.

Furthermore, I want to "resend" the messages of ```William``` and ```Charles``` from ```Publishers``` to ```Subscribers```. But at the same time, I don't want ```William``` and ```Charles``` receive the messages sent on ```Subscribers```.

This is why, for me, what i'm trying to do is something like a publish & subscribe between rooms. In this case, the ```Subscribers``` are subscribed to the ```Publishers```' messages.

It is possible with default XMPP and default Ejabberd? How?
Otherwise, how can I implement it? Any idea?

Thanks a lot!

**Comment by joanlopez** [comment]
Any idea @badlop?

Thanks!

**Comment by joanlopez** [comment]
Any idea @badlop @weiss ?

Thanks!

**Comment by badlop** [comment]
Not possible in practice.

It is possible to subscribe room2 to room1, so it receives events:
> ejabberdctl subscribe_room subscribers@conference.example/aa Susu publishers@conference.example urn:xmpp:mucsub:nodes:messages

And it is possible to grant room1 permission to send messages to room2 even if it isn't an occupant. However, the messages sent from room1 to room2 are of MUCsub format, so room2 simply discards them. It would be necessary to add some code to handle them.

**Comment by joanlopez** [comment]
Thanks @badlop, but i'm a bit confused.

What does a simple subscription from room2 to room1?
Which kind of events will receive the room2?

What do you mean is that with the subscription, the room2 will receive the messages but it will discard them? In this case, where I have to modify (add some code) this logic?

Any suggestion?

Thanks a lot!

**Comment by badlop** [comment]
> What does a simple subscription from room2 to room1? Which kind of events will receive the room2?

The kind of events that you subscribe it. See the command example I posted, it subscribes to messages.

> What do you mean is that with the subscription, the room2 will receive the messages but it will discard them? In this case, where I have to modify (add some code) this logic? 

Somewhere in mod_muc_room.erl where the incoming stanza is processed.

**Comment by ironydips** [comment]
Hi @badlop  when using the command ejabberdctl subscribe_room subscribers@conference.example/aa Susu publishers@conference.example urn:xmpp:mucsub:nodes:messages
I get the error:- Subscriptions are not allowed. I am using 16.09 .
When I referred to MUC SUB docs:- https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/ I am able to "Discovering support on MUC service" and in return I am getting <feature var="urn:xmpp:mucsub:0" /> in return but when i query "Discovering support on a specific MUC" I am not getting that feature. Am i missing anything?

**Comment by badlop** [comment]
By default a room has disabled "Allow subscription". So, first you create the room, then you configure it using a powerful Jabber client that allows room configuration (like Gajim, Psi...), to enable that option, then finally users can subscribe to its events.

**Comment by ironydips** [comment]
Thanks for the reply @badlop. I figured out I was missing "allow_subscription: true" config in .yml file.

**Comment by jithin-pits** [comment]
Hi @badlop 

Is subscribing to a group using subscribe_room api permanent ?

here https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/
in the drawbacks section, it says the muc subscription is not permanent, 

is the subscription permanent if we use the api ie https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#unsubscribe-room
