### ISSUE TITLE
Archive messages in mssql

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#1294]
> What version of ejabberd are you using?

latest version

> What operating system (version) are you using?

windows

Dears,

Kindly i want to ask if there is a way to store messages in mssql table just like mysql

Thanks,

**Comment by zinid** [comment]
Yes, MSSQL is supported for mod_mam

**Comment by hassanzreik** [comment]
good news, but i cant find the table structure of it like mysql
https://www.ejabberd.im/mssql
do you have any idea?

**Comment by zinid** [comment]
The schema can be found here: https://github.com/processone/ejabberd/blob/master/sql/mssql.sql
MSSQL specific configuration can be found here: https://docs.ejabberd.im/admin/guide/configuration/#database-and-ldap-configuration
