### ISSUE TITLE
How to send a message to all the users?

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1296]
Like a broadcast message. for example, to inform about system updates or something similar.

It's something usual on IM apps like Telegram.

Is it possible? How?

If it is not possible by default, what could be a good way to do it?

Thanks!

**Comment by weiss** [comment]
Yes, this is possible by using special JIDs or ad-hoc commands.  See the [`mod_announce` documentation][1].

[1]: https://docs.ejabberd.im/admin/guide/configuration/#modannounce

**Comment by joanlopez** [comment]
Thanks a lot @weiss !!! :) 👍

**Comment by joanlopez** [comment]
One question @weiss,

Is there any way to define new hosts (like ```/announce/online```)?

As documentation suggests, it is not recommended to send a message to all the users in huge systems.

So, what could be a good approach to notify all the users, chunk by chunk?

Thanks!
