### ISSUE TITLE
mod_http_upload docroot failed

### ISSUE THREAD

**Issue by thfree** [processone/ejabberd#1297]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debina 8.5 (OpenVZ container)

> How did you install ejabberd (source, package, distribution)?

deb https://apt.jabber.at jessie ejabberd                                                                                                                                             

> What did not work as expected? Are there error messages in the log? What

Сeased to upload files after update

```
2016-09-14 14:19:07.060 [error] <0.637.0>@mod_http_upload:process:428 Cannot store file /home/ejabber/storage/***/***/***.jpg from ::FFFF:***.***.*.* for upload.thfree.ru: "permission denied"
```

If you change the root directory

/etc/ejabberd/ejabberd.yml

```
  mod_http_upload:
...
#    docroot: "/home/ejabber/storage/"
    docroot: "/tmp/"
...

```

it creates a

```
/tmp/systemd-private-d09f46d7664643bd81ded58a2c506075-ejabberd.service-fkQ25u/tmp/***/***/***.jpg
```

**Comment by weiss** [comment]
You must either move your document root outside `/home` and `/tmp` or remove the following line from the systemd unit:

    ProtectHome=true

See #1178.

**Comment by thfree** [comment]
Thanks!
You are right moved the directory in `/var/ejabber/storage/` and a problem was gone.

And why it is created?
```
/var/tmp/systemd-private-d09f46d7664643bd81ded58a2c506075-ejabberd.service-qkiNQ0/tmp
```

**Comment by weiss** [comment]
> And why it is created?

See the [description of the `PrivateTmp` setting][1] in the `systemd.exec(5)` man page.

[1]: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=

**Comment by thfree** [comment]
Thanks. A question it is closed.
But all the same I received unexpected behavior.
