### ISSUE TITLE
MUC/SUB: Room option "allow_subscription" is not persisted

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1301]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When restarting mod_muc all MUC rooms that previously had `allow_subscription` set to `1` lose this setting. It seems to be missing in mod_muc_room:make_opts/1. We would like to keep this setting between module/server restarts.

**Comment by marcphilipp** [comment]
Thanks!

**Comment by zinid** [comment]
My bad, I forgot to add this piece of code :)
