### ISSUE TITLE
Account Register from Console can't allow login after saving MySql

### ISSUE THREAD

**Issue by HoneyShyam** [processone/ejabberd#1302]
> What version of ejabberd are you using?

ejabberd-16.06

> What operating system (version) are you using?

Windows 8.1 

> How did you install ejabberd (source, package, distribution)?

From Installer

> What did not work as expected? Are there error messages in the log? What

I register an account using command, info saved into databse. Trying login from client **Pidgin**
Getting Error Incorrect Password

> was the unexpected behavior? What was the expected result?

It should connect the login as the login is saved into database and info is correct.

Please help me, how can the server work in case of MySql Authentication, from where I can find more info for the MySql Commands and Queries to write custom.
Is there a way to run it on local host with RESTful API to trace the login.

Thank you,
Shyam

**Comment by mremond** [comment]
Enable debug log and inspect the logs.

**Comment by xerest** [comment]
What need to do, to can add users from web interface?

**Comment by HoneyShyam** [comment]
Thank you, now I have resolved the issue, and another issue how to access
the Application running on server from remote client app.
Thank you,
Regards
Shyam

**Comment by weiss** [comment]
@xerest 
> What need to do, to can add users from web interface?

If you're using internal or SQL authentication, you should be able to add users under _Virtual Hosts_ -> _$domain_ -> _Users_ in the web interface.

@HoneyShyam
> Thank you, now I have resolved the issue

Glad to hear you solved it.
