### ISSUE TITLE
s2s_user_starttls: required_truested Failed connection

### ISSUE THREAD

**Issue by kikacaty** [processone/ejabberd#1304]
> What version of ejabberd are you using?

15.03-2

> What operating system (version) are you using?

Ubuntu 15.10

> How did you install ejabberd (source, package, distribution)?

apt-get

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

s2s_user_starttls: required_trusted will lead to error of 

`self signed certificate in certificate chain` if this server is being tried to connect by others and 

`cannot get peer certificate` if the server is trying to connect others.

Everything can work under setting `s2s_user_starttls: required`.

Actually I didn't find out a place to configure which certificate or host to trust. So I am pretty confused about what is the meaning of option `required_trusted`.

**Comment by zinid** [comment]
ejabberd relies on [this](https://github.com/processone/fast_tls/blob/master/c_src/fast_tls_drv.c#L669) function of OpenSSL. Thus,
> SSL_CTX_set_default_verify_paths() specifies that the default locations from which CA certificates are loaded should be used. There is one default directory and one default file. The default CA certificates directory is called "certs" in the default OpenSSL directory. Alternatively the SSL_CERT_DIR environment variable can be defined to override this location. The default CA certificates file is called "cert.pem" in the default OpenSSL directory. Alternatively the SSL_CERT_FILE environment variable can be defined to override this location.

**Comment by kikacaty** [comment]
@zinid Thanks for clarifying! I actually tried to add certificate through OpenSSL (using [this](http://superuser.com/a/719047). I also tested it with OpenSSL but still ended in getting
`cannot get peer certificate`.

**Comment by zinid** [comment]
Does this command work ok for you after added CA certificate to the path?
`$ openssl verify -verbose -CApath /etc/ssl/certs server.pem`

**Comment by zinid** [comment]
Ah, cannot get peer certificate is another problem.

**Comment by zinid** [comment]
For what server do you get this error? Is it a public server?

**Comment by kikacaty** [comment]
No, it is not. I use custom DNS server and two ejabberd servers under my local network.

**Comment by zinid** [comment]
Is it resolved yet?

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:40077 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cMZmM-0004Fi-1K
	for zero@thezeroworld.com; Thu, 29 Dec 2016 07:25:54 -0500
Date: Thu, 29 Dec 2016 04:25:13 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1483014313;
	bh=rHqaUQ2rc/10jEM9woa3y06LHVNiT26SppFqKY5L+GI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iv8ZL5t9XLT/jIyPwlbiimBYafWyWv4qsDwoeRfecRCg8GJrX1I7/NSHCDdoTenem
	 MEnM1nK2lsvU9UUzEKbXk02dyx0gy0ddYgQ2EI5SJ3LN120n9Y65EkLo2vRFVnD75X
	 gSnOc7/3Au0ayewTCt8JABL/tHCK4p6uU9sHRPPE=
