### ISSUE TITLE
MUC/SUB: How to limit access?

### ISSUE THREAD

**Issue by Kaggggggga** [processone/ejabberd#1306]
> What version of ejabberd are you using?
> 16.09
> 
> What operating system (version) are you using?
> Debian 8.4
> 
> How did you install ejabberd (source, package, distribution)?
> source

Hello, I wonder how to limit access to MUC/SUB.
1. according to the blog, MUC/SUB is reusing XMPP PubSub protocol, but I couldn't find a way to make PubSub configuration on the MUC SUB node. Wish to get some advises. (maybe my understanding of XEP 0060 is not enough)
2. alternatively, I try to use password protection from MUC to limit access, which will ask for password when I try to subscribe the MUC SUB node. But based on my understanding of source code, MUC/SUB will not take password when subscribing.

btw, found a minor crash bug in src/mod_http_api.erl line 229, the exception is not properly formatted by json_format() when command is not found. hope it helps! 

Thanks!

**Comment by badlop** [comment]
@Kaggggggga In case 2 you are right: there isn't any way to provide room password when subscribing to a password-protected room.

@mremond  Do you think this feature request is acceptable? I can imagine this possible stanza, does it look good?
```
<iq type='set' to='room1@conference.localhost'>
  <subscribe xmlns='urn:xmpp:mucsub:0' nick='mynick'>
    <event node='urn:xmpp:mucsub:nodes:messages' />
    <event node='urn:xmpp:mucsub:nodes:affiliations' />
    <event node='urn:xmpp:mucsub:nodes:subject' />
    <event node='urn:xmpp:mucsub:nodes:config' />
    <x xmlns='http://jabber.org/protocol/muc'>
      <password>aaa</password>
    </x>
  </subscribe>
</iq>
```
To support such a stanza, this small patch is required:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index fc2aeeb..b6c1d88 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -4652,7 +4652,8 @@ process_iq_mucsub(From, Packet,
 		    NewStateData = set_subscriber(From, Nick, Nodes, StateData),
 		    {result, subscription_nodes_to_events(Nodes), NewStateData};
 		error ->
-		    add_new_user(From, Nick, Packet, StateData)
+		    Packet2 = copy_password_xelement(Packet),
+		    add_new_user(From, Nick, Packet2, StateData)
 	    end;
 	_ ->
 	    Err = ?ERRT_NOT_ALLOWED(Lang, <<"Subscriptions are not allowed">>),
@@ -4696,6 +4697,11 @@ process_iq_mucsub(_From, _Packet, #iq{lang = Lang}, _StateData) ->
     Txt = <<"Unrecognized subscription command">>,
     {error, ?ERRT_BAD_REQUEST(Lang, Txt)}.
 
+copy_password_xelement(Packet) ->
+    SubsEl = fxml:get_subtag_with_xmlns(Packet, <<"subscribe">>, ?NS_MUCSUB),
+    XEl = fxml:get_subtag_with_xmlns(SubsEl, <<"x">>, ?NS_MUC),
+    fxml:append_subtags(Packet, [XEl]).
+
 remove_subscriptions(StateData) ->
     if not (StateData#state.config)#config.allow_subscription ->
 	    StateData#state{subscribers = ?DICT:new(),
```

**Comment by Kaggggggga** [comment]
thanks for the reply and the fix!
