### ISSUE TITLE
MUC room disco#info node x-roomuser-item not handled properly.

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#131]
From XEP-0045 http://xmpp.org/extensions/xep-0045.html#reservednick:

> A user SHOULD discover his or her reserved nickname before attempting to enter the room. This is done by sending a Service Discovery information request to the room JID while specifying a well-known Service Discovery node of "x-roomuser-item".

```
<iq from='hag66@shakespeare.lit/pda'
    id='getnick1'
    to='coven@chat.shakespeare.lit'
    type='get'>
   <query xmlns='http://jabber.org/protocol/disco#info'
         node='x-roomuser-item'/>
</iq>
```

> It is OPTIONAL for a multi-user chat service to support the foregoing service discovery node. If the room or service does not support the foregoing service discovery node, it MUST return a `<feature-not-implemented/>` error to the user.

Instead, ejabberd appears to ignore the node attribute and respond as if to a regular disco#info request, listing the room features.

**Comment by badlop** [comment]
I think this ticket can be closed, as current ejabberd does not ignore the attribute, now it returns an error. When sent to a room, the user receives:
```xml
<iq xml:lang='es'
	to='user2@localhost/tka1'
	from='room1@conference.localhost'
	type='error'
	id='getnick1'>
  <query node='x-roomuser-item'
	xmlns='http://jabber.org/protocol/disco#info'/>
  <error code='503'
	type='cancel'>
    <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    <text xml:lang='es'
	xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>The feature requested is not supported by the conference</text>
  </error>
</iq>
```
When sent to the MUC service, the user receives:
```xml
<iq xml:lang='es'
	to='user2@localhost/tka1'
	from='conference.localhost'
	type='error'
	id='getnick1'>
  <query node='x-roomuser-item'
	xmlns='http://jabber.org/protocol/disco#info'/>
  <error code='404'
	type='cancel'>
    <item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    <text xml:lang='es'
	xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Nodo no encontrado</text>
  </error>
</iq>
```
