### ISSUE TITLE
Archive MUC messages in DB

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#1310]
Dears,

Kindly i want to ask if it is possible to store muc messages in db and not in RAM

Best Regards,

**Comment by badlop** [comment]
If you refer to the room recent discussion history, which is a feature described in http://xmpp.org/extensions/xep-0045.html#enter-history and is only designed to inform new occupants of the past recent conversation: no, it is implemented in ejabberd to be stored only in RAM, because it is temporary information.

If you just want to keep room messages stored in a SQL database (so that you can search in it), then you can try mod_mam, which can be used together with mod_muc. Or if you just want to keep room messages, you can use something like mod_muc_log which writes into plain text files.

**Comment by xerest** [comment]
How to install mod_mam? by default is not in the modules list.

**Comment by zinid** [comment]
There is no need to install anything if you have recent ejabberd version.
https://docs.ejabberd.im/admin/guide/configuration/#modmam

**Comment by hassanzreik** [comment]
Thank you @zinid , also a question how can i enable mam for muc in configuration file?

**Comment by xerest** [comment]
Hi,

What is the table, when messages are saving with the mod_mam?

**Comment by badlop** [comment]
>  how can i enable mam for muc in configuration file?

In the modules section of your ejabberd configuration file, simply add mod_mam like you have for other modules. For configurable options see https://docs.ejabberd.im/admin/guide/configuration/#modmam

> where messages are saving with the mod_mam?

In table archive_msg when using Mnesia, in table archive when using SQL.

**Comment by xerest** [comment]
Thanks @badlop, I check the archive table and it is empty, maybe I need additional settings?

**Comment by badlop** [comment]
Your configuration looks correct: the relevant options are the sql_* ones that define your database, and the two mod_mam options that set storing to sql, and store always.

I set those options in my ejabberd 16.09 test server, and set loglevel to 5, then I create two accounts, subscribe them mutually, and then send a message from one to the other. The message is stored in the 'archive' mysql table. This is logged:
```
11:50:51.029 [debug] Received XML on stream = <<"<message id='41:993229'
 xml:lang='es' type='chat' to='user1@localhost'><body>uuuu</body></message>">>
11:50:51.030 [debug] State: {maxrate,1000,999.9455308638687,1475833847121066},
 Size=98 M=97.9946623153982, I=3909.03
11:50:51.031 [debug] SQL: "select def, always, never from archive_prefs where username='user2'"
11:50:51.041 [debug] SQL: "insert into archive (username, timestamp, peer, bare_peer, xml,
 txt, kind, nick) values ('user2', 1475833851040565, 'user1@localhost', 'user1@localhost',
 '<message from=''user2@localhost/tka1'' to=''user1@localhost'' id=''41:993229''
 xml:lang=''es'' type=''chat''><body>uuuu</body></message>', 'uuuu', 'chat', '')"
11:50:51.083 [debug] route
        from {jid,<<"user2">>,<<"localhost">>,<<"tka1">>,<<"user2">>,<<"localhost">>,<<"tka1">>}
        to {jid,<<"user1">>,<<"localhost">>,<<>>,<<"user1">>,<<"localhost">>,<<>>}
        packet {xmlel,<<"message">>,[{<<"id">>,<<"41:993229">>},{<<"xml:lang">>,<<"es">>},
{<<"type">>,<<"chat">>},{<<"to">>,<<"user1@localhost">>}],
[{xmlel,<<"body">>,[],[{xmlcdata,<<"uuuu">>}]}]}
11:50:51.083 [debug] local route
        from {jid,<<"user2">>,<<"localhost">>,<<"tka1">>,<<"user2">>,<<"localhost">>,<<"tka1">>}
        to {jid,<<"user1">>,<<"localhost">>,<<>>,<<"user1">>,<<"localhost">>,<<>>}
        packet {xmlel,<<"message">>,[{<<"id">>,<<"41:9"...>>},{<<"xml:"...>>,<<...>>},{<<...>>,...},{...}],[{xmlel,<<...>>,...}]}
11:50:51.084 [debug] session manager
        from {jid,<<"user2">>,<<"localhost">>,<<"tka1">>,<<"user2">>,<<"localhost">>,<<"tka1">>}
        to {jid,<<"user1">>,<<"localhost">>,<<>>,<<"user1">>,<<"localhost">>,<<>>}
        packet {xmlel,<<"message">>,[{<<"id">>,<<"41:9"...>>},{<<"xml:"...>>,<<...>>},{<<...>>,...},{...}],[{xmlel,<<...>>,...}]}

```

**Comment by xerest** [comment]
Thank you very much @badlop
