### ISSUE TITLE
Ejabberd 16.09 Install hangs on "Executing final installation script"

### ISSUE THREAD

**Issue by wakerb** [processone/ejabberd#1311]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Windows 10

> How did you install ejabberd (source, package, distribution)?

Windows installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The install process appears to hang at the "Executing final installation script" stage.  While the process appears to have hung, it is in fact still running since I can click cancel and it will wind back the installation.  No log is produced on the initial install and the installation process will never complete or error even e after a day or so.  When I re-install, the process will error out eventually and a log will be produced if I cancel the installation.  I have attached a screen shot and a copy of the log file.  

Thanks for your help in advance.

[ejabberd_Install.zip](https://github.com/processone/ejabberd/files/498717/ejabberd_Install.zip)

**Comment by cromain** [comment]
I can not reproduce this, you should at least see some output from the postinstall script. It seems it can not be run for some reasons.
Can you run a test on your platform, start installer, and while it's stuck, go into ejabberd's bin directory.
then call postinstall.cmd manually with cmd.exe and see what is the output.

**Comment by cromain** [comment]
can not reproduce
