### ISSUE TITLE
Roster names truncated to fixed length in bytes, sometimes generating broken utf-8?

### ISSUE THREAD

**Issue by aleth** [processone/ejabberd#1312]
> What version of ejabberd are you using?

Unfortunately this is not known. I'm investigating a Thunderbird XMPP bug report filed by a user who doesn't know the version, unless ver="kxldlsZuzEZzrZKi50X/YdUuN44=" is sufficient for you.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The user is seeing roster items like

```
<item subscription="both" name="Каменск-Уральский, Добролюбо�" jid="aa@yyyyyyy.ru">
```

where it appears that the name has been truncated to a fixed number of bytes (as opposed to utf-8 characters), generating broken utf-8.

Is this a known issue (possibly fixed in some newer version)? Thanks for your feedback.

**Comment by zinid** [comment]
ejabberd doesn't manipulate roster `name` attributes, so the problem might come from:
1) database, especially if mysql is used
2) a client is truncating the field itself when setting the roster item

**Comment by zinid** [comment]
The reporter doesn't respond. I close.
