### ISSUE TITLE
16.09- Memory Leak

### ISSUE THREAD

**Issue by genexp** [processone/ejabberd#1315]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu 16.04 - Latest Patches

> How did you install ejabberd (source, package, distribution)?

I installed using the .deb distribution.  Specifically, here are my steps:

```
sysctl -w fs.file-max=12000500
sysctl -w fs.nr_open=20000500
ulimit -n 20000000
sysctl -w net.core.rmem_max=16384
sysctl -w net.core.wmem_max=16384
sysctl -w net.ipv4.ip_local_port_range='1024 65000'
sysctl -w net.ipv4.tcp_mem='10000000 10000000 10000000'
sysctl -w net.ipv4.tcp_rmem='1024 4096 16384'
sysctl -w net.ipv4.tcp_tw_recycle=1
sysctl -w net.ipv4.tcp_tw_reuse=1
sysctl -w net.ipv4.tcp_wmem='1024 4096 16384'
locale-gen en_US.UTF-8
/usr/sbin/update-locale LANG=en_US.UTF-8
echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
mkdir -m 700 -p /root/cloudinit
cd /root/cloudinit
aws s3 cp s3://${bucket}/cloud-config/ejabberd/ejabberd_16.09-0_amd64.deb /root/cloudinit/ejabberd_16.09-0_amd64.deb --region=us-west-1
aws s3 cp s3://${bucket}/cloud-config/ejabberd/ejabberd-contrib-master.zip   /root/cloudinit/ejabberd-contrib-master.zip --region=us-west-1
dpkg -i ejabberd_16.09-0_amd64.deb
unzip ejabberd-contrib-master
mkdir -p /opt/ejabberd-16.09/.ejabberd-modules/sources
cp -R ejabberd-contrib-master/* /opt/ejabberd-16.09/.ejabberd-modules/sources
ln -s /opt/ejabberd-16.09/conf /etc/ejabberd
ln -s /opt/ejabberd-16.09/logs /var/log/ejabberd
```

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I seem to be having a consistent memory leak, and I'm not sure how to go about solving it.  We are configured as follows:
- AWS m4.xlarge machines, 16GB ram, enhanced networking, 4 core
- 3 Node Cluster, all in the same subnet
- MySQL for mod_mam
- Redis for Sessions (sm_db_type: redis)
- We use a single module, namely: ejabberd_http_auth

Relevant configs are here:
- [ejabberd.yml](https://gist.github.com/genexp/46d30ce711a2b1e14d698e8cce0eced0)
- [ejabberdctl.cfg](https://gist.github.com/genexp/d86290c388a1c53a7bfd3e44e8f763e9)

Here are some graphs of the servers:

_Connected Users_
The following shows used connected users over a two day period.
![screen shot 2016-10-02 at 4 46 48 pm](https://cloud.githubusercontent.com/assets/816/19023583/e6a6fe70-88bf-11e6-84d6-8cf21ca28d32.png)

_Used Memory_
The following shows used memory on a series of servers over a 2 day period.  At any time there are never more than 3 servers, but my auto scaling group kills them when they run out of ram and creates new ones.
![screen shot 2016-10-02 at 4 32 51 pm](https://cloud.githubusercontent.com/assets/816/19023559/1fcc5d40-88bf-11e6-880b-b9c749a90937.png)

_Connected Users against Used Memory_
The following shows connected users (highlighted) against used memory.  This is interesting to me, in that it shows memory continuing to increase sometimes as users drop off.  
![screen shot 2016-10-02 at 4 49 25 pm](https://cloud.githubusercontent.com/assets/816/19023612/9b4d4104-88c0-11e6-93ec-fc2a18d571e5.png)

You can see that they climb to about 75% used, then get deleted and recreated by our autoscaling group.  If some don't reach 75%, its probably me rolling out new ones manually.  I had been trying various config options in `ejabberdct.cfg` to no avail.  

NOTE: If I let them go to 100%, the ejabberd service dies completely. I manually restart the ejabberd service, I start getting another error "[error] emulator Discarding message {{ the message  is here }}in an old incarnation of this node"  For that reason I've simply let the autoscaling group recreate them.

I have no errors in crash, ejabberd, or error log.

At this point I suspect that there's either a bug in Ejabberd, the ODBC module, mod_mam, mod_offline, or ejabberd_http_auth.

I'm not sure how to proceed.  Anyone else having this issue on 16.09?

**Comment by genexp** [comment]
I'm pretty sure at this point that this has something to do with garbage collection not being triggered.  I'm not sure why, interested in any thoughts.  

Note: I have found the  ERL_FULLSWEEP_AFTER option, and have set it to 0. So far, no noticeable improvement.  In addition, I found info on Transparent Huge Pages and have disabled them too.

**Comment by weiss** [comment]
> I seem to be having a consistent memory leak, and I'm not sure how to go about solving it.

I'd run an `ejabberdctl debug` shell and execute the following calls (don't forget the trailing dots; end exit the shell by pressing `Ctrl`+`C` twice):

    erlang:memory().
    erlang:system_info(allocated_areas).

What's the output?  And what's the output of `ps -C beam.smp -o rss` during that time?

The "leaked" memory *might* be allocated on the heap(s) of one or more individual Erlang processes.  In that case, the following calls would spit out the process that allocates most of the memory:

    application:start(os_mon).
    {_, _, {Pid, Size}} = memsup:get_memory_data().
    application:stop(os_mon).
    erlang:process_info(Pid).

> I'm pretty sure at this point that this has something to do with garbage collection not being triggered.

You can verify that theory by calling:

    lists:foreach(fun erlang:garbage_collect/1, processes()).

Does that reduce memory consumption considerably?

**Comment by genexp** [comment]
Hi @weiss Thank you for the help.  Running the garbage collector absolutely helps.  I actually wrote up a little module [mod_garbageman](https://github.com/madglory/mod_garbageman) so that we could run it alongside `mod_cron`.  Incidentally, we also delete_unused_rooms in a cron as well.

This morning we disabled all unused modules, increased RAM on the servers, and I'll monitor today to see if we can get to a steady state.

I'm a little worried that I'm running with 15GB of ram for 15K users.  From what I can find online, that's very high.  Looking at `erlang:memory()`, after I run garbage collection manually, I see that almost all of the memory is taken up by processes.

I will run the bits and pieces you shared above to see what I come up with.  Again, *really* appreciate the help!

**Comment by genexp** [comment]
## Erlang VM Memory

```erlang
(ejabberd@host1)3> erlang:memory().
[{total,13629088568},
 {processes,9443293712},
 {processes_used,9442878192},
 {system,4185794856},
 {atom,883633},
 {atom_used,874502},
 {binary,1266625832},
 {code,21441535},
 {ets,1176474032}]
(ejabberd@host1)4> erlang:system_info(allocated_areas).
[{sys_misc,1600213141},
 {static,2098336},
 {atom_space,491640,482509},
 {atom_table,391993},
 {module_table,191952},
 {export_table,502116},
 {export_list,1928432},
 {register_table,3268},
 {fun_table,38594},
 {module_refs,26496},
 {loaded_code,18753945},
 {dist_table,105059},
 {node_table,1187},
 {bits_bufs_size,0},
 {bif_timer,0},
 {link_lh,3552},
 {process_table,100663296},
 {port_table,12582912},
 {ets_misc,32777216}]
```

## Linux Memory
```erlang
ubuntu@host1:~$ ps -C beam.smp -o rss
  RSS
10100016
157604
```

## Erlan OS Mon
```erlang
(ejabberd@ip-10-66-1-158.ap-southeast-1.compute.internal)5> application:start(os_mon).
ok
(ejabberd@ip-10-66-1-158.ap-southeast-1.compute.internal)6> {_, _, {Pid, Size}} = memsup:get_memory_data().
{32168357888,13304168448,{<0.2211.0>,4751009064}}
(ejabberd@ip-10-66-1-158.ap-southeast-1.compute.internal)7> application:stop(os_mon).
ok
```

## Graphs
This shows # of Erlang Processes (ejabberdctl stats processes), against amount of used RAM as reported by the OS.  The spikes are the VM taking more, and my cron which runs garbage collection every minute now.  A few things I notice:
  1. The number of total processes continues to grow continually over time.  This seems to be the cause of the underlying problem, though I have no idea why something would be started and not killed
  1. RAM spikes sometimes up to 5GB between the time we run the garbage collection cron (currently set to run every 60 seconds).  This is really surprising, but maybe related to 1 in some way.
  1. I removed unused eJabberd modules from our `ejabberd.yml`. No change really.

Is there way to get a count of processes, by name, and watch that over time to see which are being created and not killed?  I'm not sure how to isolate the issue further.

**Comment by weiss** [comment]
> `(ejabberd@host1)6> {_, _, {Pid, Size}} = memsup:get_memory_data().`
> `{32168357888,13304168448,{<0.2211.0>,4751009064}}`

So 4.5 GB are allocated for a single Erlang process.  This number looks too large as well.

Did you also call `erlang:process_info(Pid).`?  What was the output?

**Comment by genexp** [comment]
Hey @weiss sorry, I didn't really explain that well in the response here it is:

https://gist.github.com/genexp/c11f204e4d3f95870ff55c06517b5360

**Comment by weiss** [comment]
The process that handles MAM requests is hanging (with more than 800,000 queued requests).  You said you're using MySQL (only) for `mod_mam`?  It looks like there's some issue with the SQL communication.

**Comment by genexp** [comment]
Hey @weiss I have the MySQL log enabled, I'm seeing *some* queries come from the nodes.  For example:

```sql
select def, always, never from archive_prefs where username='111-111-111'
```
Note: Guid changed to protect the innocent. :)

This would indicate that the connection info and such is correct.  However, you're right, the general log doesn't contain any queries that I would expect to see specifically querying the archive table for content (ie: select * from archive, or whatever).  

I wonder why some archive queries would work, but not others. 

Note: I know our server occasionally goes down for maintenance (it's an Amazon RDS server, it's taken down once a week on Sunday morning for maintenance, for maybe 10 seconds).  Other than that, it's had 100% uptime.

**Comment by genexp** [comment]
Does it make any sense to change the `iqdisc` value to parallel?

**Comment by genexp** [comment]
Ok, as of 10 minutes ago, I decided to completely destroy all eJabberd servers, and let our autoscaling group recreate them (takes about 5 minutes, but its a completely clean slate).  The new ones are correctly querying SQL, i now see both archive_pref and archive queries going through.

In addition I changed two settings:
  * `iqdisc: 50`
  * I deleted the assume_mam_usage option since we aren't using stream management.

I will continue to monitor ram.

**Comment by genexp** [comment]
Hey @weiss - I wanted a day or two to gather more data, but here's where we stand today.  Keep in mind, all three servers were new as of Friday, so all settings and such are consistent.

## SQL Connectivity Check
First, I checked the SQL server to ensure queries are still happening.  I see this in the query log:

```sql
| 2016-10-09 12:23:12.632458 | admin[admin] @  [1.1.1.1] |       619 | 728125832 | Query        | SELECT COUNT(*) FROM archive WHERE username='1234' and bare_peer='1111@mycorp.net'
```
Note: Names and IPs obscured.

## Graph
![screen shot 2016-10-09 at 8 29 07 am](https://cloud.githubusercontent.com/assets/816/19220416/8880967c-8dfa-11e6-984e-f9964fa12df3.png)

Of note, memory is still climbing at the same rate

Note: This looks smoother, because I'm running the garbage collection script manually every minute.  The spikes were causing the OOM killer to run once the baseline started to get near 60, spikes would hit 100%.  

## Erlang VM Memory:
```erlang
(ejabberd@host1)1> erlang:memory().
[{total,7043795328},
 {processes,3947128392},
 {processes_used,3947072576},
 {system,3096666936},
 {atom,859057},
 {atom_used,826087},
 {binary,390280752},
 {code,20881022},
 {ets,1015918312}]
(ejabberd@host1)2> erlang:system_info(allocated_areas).
[{sys_misc,1600212697},
 {static,2098336},
 {atom_space,491640,458738},
 {atom_table,367417},
 {module_table,188496},
 {export_table,502116},
 {export_list,1904672},
 {register_table,3268},
 {fun_table,38594},
 {module_refs,25920},
 {loaded_code,18221224},
 {dist_table,105779},
 {node_table,1139},
 {bits_bufs_size,0},
 {bif_timer,0},
 {link_lh,3552},
 {process_table,100663296},
 {port_table,12582912},
 {ets_misc,32777216}]
```

## Linux Memory
```bash
ubuntu@host1:~$ ps -C beam.smp -o rss
  RSS
13361992
157624
```

## Erlang OS Mon
```erlang
(ejabberd@host1)1> application:start(os_mon).
ok
(ejabberd@host1)42> {_, _, {Pid, Size}} = memsup:get_memory_data().
** exception error: no match of right hand side value {32168357888,17170853888,{<0.14490.254>,7637480}}(ejabberd@host1)3> application:stop(os_mon).
ok
(ejabberd@host1)4> erlang:process_info(Pid).
undefined
```
Note: Strange, no match?   From reading the docs, I think this means that it didn't find a "Worst" offender, so maybe this is an improvement.

Conclusion: Process count, and by proxy memory continues to grow out of control, over about a two day period.

Any further suggestions? It still feels like processes should stop climbing.  Something feels wrong :(

**Comment by genexp** [comment]
Alright, so I think I found the problem.  We're setting *all* muc rooms to be persistent by default.  This is spawning a new erlang process and eating up ram for each one.  We plan to enable room subscriptions, so we believe we need room persistence.  We had also been relying on mod_offline rather than mod_mam for room history.  Another reason to make them persistent.  

To mitigate keeping around unused rooms, we had been calling rooms_unused_destroy via cron (not mod_cron) hourly.  However, this was failing due to a timeout.  

Action items:
  * Set default persistence to temporary.
  * Move rooms_unused_destroy into mod_cron, instead of cron proper.

I'll report back.

**Comment by colossalman** [comment]
Have you tried adjusting fs.nr_open?

We were using that exact same value and having a lot of inconsistencies in mnesia and mysql connection times outs, as well as an 8+ second delay every time ejabberdctl was called.  Finally tracked it down to that setting.  Anything over 19999999 cause problems so we set it to 12000500 as fs.file-max.

 sysctl -w fs.nr_open=12000500

Everything just worked like magic after that.  Ejabberd 16.04 and Ubuntu 14.04.

This may not give you any benefit in your case but thought I would pass it on just in case.  Please see attaches screenshot of how long it takes to do a simple list_cluster query, using 20000500 and 12000500.
![post-sysctl](https://cloud.githubusercontent.com/assets/11789579/19774036/95ef7ae2-9c20-11e6-8432-927464433024.png)

**Comment by genexp** [comment]
Wow, thanks for the response and sharing. I made the change those morning
and it helped quite a bit!

**Comment by cromain** [comment]
I suggest to close this issue now
