### ISSUE TITLE
Option for disabling postgresql prepared statements

### ISSUE THREAD

**Issue by sabudaye** [processone/ejabberd#1316]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

`
-bash-4.1$ cat /etc/redhat-release
CentOS release 6.7 (Final)
`
`
-bash-4.1$ uname -a
Linux 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We use PgBouncer in transaction pooling mode, and only option to deal with prepared statements is disabling them. It would be great to have configuration option in ejabberd.yml for that.

**Comment by alexeyshch** [comment]
Thank you, your changes are now in master.
