### ISSUE TITLE
Error: bad argument in call to io_lib:format

### ISSUE THREAD

**Issue by synopsisdevs** [processone/ejabberd#1318]
> What version of ejabberd are you using?

`16.09`

> What operating system (version) are you using?

`Debian 8 (Jessie)`

> How did you install ejabberd (source, package, distribution)?

`source (https://hub.docker.com/r/rroemhild/ejabberd/~/dockerfile/)`

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I try modify user from web admin interface. I got error page "Connection refused".
Other pages are working correctly.
In log file was error:
```
CRASH REPORT Process <0.529.0> with 0 neighbours crashed with reason:
 bad argument in call to io_lib:format(<<>>, [<<"test@example.com">>]) line 154
 in ejabberd_web_admin:user_info/4 line 1689
```

**Comment by badlop** [comment]
According to my source code, the error happens in this line:
```
    [?XC(<<"h1">>, list_to_binary(io_lib:format(?T(<<"User ~s">>),
                                                [us_to_list(US)])))]
```
In your case, the string <<"User ~s">> gets translated to an empty string: <<>>.

In what language is the WebAdmin shown to you? English, or other? Maybe the translation file is incomplete or buggy.

**Comment by synopsisdevs** [comment]
WebAdmin in czech language

**Comment by synopsisdevs** [comment]
When I change browser language to english everything works. Thanks for hint.

**Comment by badlop** [comment]
Right, there were two small typos in the Czech translation file. You can fix the lines in your local cs.msg file manually, and continue using Czech.

**Comment by azurit** [comment]
The same typos are also in sk.msg (version16.09, didn't check any newer one).

**Comment by badlop** [comment]
I don't see the problem using a recent ejabberd version, setting the sk language and visiting the WebAdmin pages that require the "User ~s" string.
