### ISSUE TITLE
Client disconnects after 5 minutes of inactivity

### ISSUE THREAD

**Issue by DeerBeer** [processone/ejabberd#1319]
> What version of ejabberd are you using?
16.04

> What operating system (version) are you using?
centos 7

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

client are connecting with socket connection on port 5222 not changed the default yml settings fro that port. Our Android client (which is using smack-android) after 5 minutes of inactivity client receives "Connection closed with error"
the same thing is with our iOS app
In logs first log on loglevel 5 is:
2016-10-03 11:32:08.946 [info] <0.18132.0>@ejabberd_c2s:terminate:1778 ({socket_state,fast_tls,{tlssock,#Port<0.32330>,#Port<0.32331>},<0.18131.0>}) Close session for some_user@host/resource

**Comment by weiss** [comment]
You could run `tcpdump` and/or enable debug output in ejabberd (`ejabberdctl set-loglevel 5`) to figure our which side is closing the TCP connection and whether an error message is sent before that happens.

**Comment by DeerBeer** [comment]
found the issue, someone setup the F5 to kill all idle connection after 5 minutes. 

Thank you
