### ISSUE TITLE
PubSub items non-retractable and ends up in other nodes

### ISSUE THREAD

**Issue by mrfrostfire** [processone/ejabberd#1320]
> What version of ejabberd are you using?

16.02, 16.09

> What operating system (version) are you using?

Red hat

> How did you install ejabberd (source, package, distribution)?

rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have found that there sometimes becomes a mismatch of pubsub_items and pubsub_states, where an item exists but without a state reffering to it.

This affects the pubsub system in 2 very visible and dangerous ways.
1. When fetching a list of items on a node, it'll return all items using the internal node, and the item will appear. But when trying to retract the item, it will return that the item doesn't exist.
2. When the node the stray item belongs to is removed, the item will persist. Thereby, as the new node will  get the same internal id as the previous, the item will turn up on the new node when fetching the items for that node.

Here's an example of fetching items for a node and trying to retract it:

```
<iq id="MX_19" type="get" to="pubsub.domain.com" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="111.222.333" />
  </pubsub>
</iq>
<iq from="pubsub.domain.com" to="xxx@yyy/zzz" id="MX_19"
     type="result" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="111.222.333">
      <item id="5C01FE06DF6B9">
        <TheObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
            ...
        </TheObject>
      </item>
    </items>
  </pubsub>
</iq>
<iq id="MX_23" to="pubsub.domain.com" type="set" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <retract node="111.222.333">
      <item id="5C01FE06DF6B9" />
    </retract>
  </pubsub>
</iq>
<iq from="pubsub.domain.com" to="xxx@yyy/zzz"
      type="error" id="MX_23" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <retract node="111.222.333">
      <item id="5C01FE06DF6B9" />
    </retract>
  </pubsub>
  <error code="404" type="cancel">
    <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
  </error>
</iq>
```

And here is an example where a node is created, the item turns up on it, then the node is destroyed and a new one created, and the same item is returned on that node.

```
<iq from="pubsub.domain.com" to="xxx@domain.com/yyy" id="MX_4"
     type="result" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="1261">
      <item id="5C379092C68B1">
        <AnotherObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
            ...
        </AnotherObject>
      </item>
      <item id="5C3778738CE25">
        <TheObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
              ...
        </TheObject>
      </item>
    </items>
  </pubsub>
</iq>
```

```
<iq from="pubsub.domain.com" to="xxx@domain.com/yyy" id="MX_4" type="result"
     xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="1262">
      <item id="5C3791013CF2E">
        <AnotherObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
        ...
        </AnotherObject>
      </item>
      <item id="5C3778738CE25">
        <TheObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
          ...
        </TheObject>
      </item>
    </items>
  </pubsub>
</iq>
```

As you can see, the object with the same id turns up on both nodes

The names are fake, and the content of the objects has been replaced by ... as you probably understood.

There are no errors that we've found in the logs, and there are no errors other than the ones reported back of the items missing.
We started tracing the erl code for node destruction and found that it's using the states to determine what items should be removed, but when we did a dump of the mnesia db, we could see that the stray items does not have a corresponding state reference. Either the state is never created, or it was removed without removing the item.
We were using 16.02 and have replicated this in multiple environments, and have upgraded to 16.09 hoping the problem to go away, but we still get the stray items.

As a workaround, we will stop destroying nodes until this has been fixed.

**Comment by mrfrostfire** [comment]
apparently, you're only allowed to have one "code" per comment

`
<iq from="pubsub.domain.com" to="xxx@domain.com/yyy" id="MX_4" type="result" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="1261">
      <item id="5C379092C68B1">
        <AnotherObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
...
        </AnotherObject>
      </item>
      <item id="5C3778738CE25">
        <TheObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
...
        </TheObject>
      </item>
    </items>
  </pubsub>
</iq>


<iq from="pubsub.domain.com" to="xxx@devrelay.domain.com/yyy" id="MX_4" type="result" xmlns="jabber:client">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="1262">
      <item id="5C3791013CF2E">
        <AnotherObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
...
        </AnotherObject>
      </item>
      <item id="5C3778738CE25">
        <TheObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="">
...
        </TheObject>
      </item>
    </items>
  </pubsub>
</iq>
`

**Comment by cromain** [comment]
I confirm this. Thanks for reporting !
This occurs when a publisher published some items, but has no affiliation anymore when node is purged or removed.

simple fix would not be efficient.
with actual architecture, best fix would be removing items of an entity when its affiliation is removed. XEP-0060 says nothing about entity's items on affiliation removal, so i guess that the way i'll fix this.

**Comment by mrfrostfire** [comment]
Personally I don't think that removing items from an entity on affiliation removal is a good choice.
Let's say that a team is collaborating on a node, and one of the teammembers quit or gets reassigned, we still want to keep the teammembers contributions to the node. 

Items on a node in my opinion should stay on the node until specifically removed or node is purged/removed. Removing them on affiliationchange is a big change that may cause lots of issues to people who are using pubsub today and upgrades to the version where this is fixed.

**Comment by cromain** [comment]
yes i was wondering this, and XEP really does not cover that point, it's up to interpretation.
this patch does removal, but is indeed quite aggressive. i'm checking if we can improve this by just enforcing node removal without too much performance impact.

**Comment by cromain** [comment]
issue impacts only mnesia backend, it's possible to perform a correct node purge/remove using an extra table which will list "orphaned items" without any performance imapct. let's go that way instead.

**Comment by mrfrostfire** [comment]
Would it be possible to have the upgrade run a script that removes any orphans already in the database? Or get a script that does that, which we can run manually?
Currently, the only way to do it we know of is to dump the database, remove the orphans manually and then re-import the database again. Which is not doable for us in production as it would cause a significant maintenancewindow.
