### ISSUE TITLE
ejabberd_sql:check_error:1033 SQL query 'QXXXXXXX' at {sql_queries,XXX} failed: <<"Unknown Host">>`

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1321]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian 8.6 Jessie

> How did you install ejabberd (source, package, distribution)?

Testing repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

There is one particular ejabberd error, which I can track back to at least 11.08.2016:

`[error] <0.710.0>@ejabberd_sql:check_error:1033 SQL query 'Q118654331' at {sql_queries,210} failed: <<"Unknown Host">>`

What does it mean and is it crucial?

**Comment by marinakr** [comment]
I have same issue with 16.06 on ubuntu for postgres. Ejabberd was configured with --enable-pgsql

**Comment by badlop** [comment]
Do you know when does it happen, or how to reproduce it?
