### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by KunaPrime** [processone/ejabberd#1323]
> What version of ejabberd are you using?

latest source from gitub repo

> What operating system (version) are you using?

ubutnu 16.04

> How did you install ejabberd (source, package, distribution)?
from source

> What did not work as expected? Are there error messages in the log? What
make install failed:

`my_location` is edited part of my file system

==> rel (compile)                                                                                                                                     
==> ejabberd (compile)                                                                                                                                
make copy-files-sub                                                                                                                                   
make[1]: Entering directory '`my_location`/ejabberd'                                                                                                
Makefile:152: *** multiple target patterns.  Stop.                                                                                                    
make[1]: Leaving directory '`my_location`/ejabberd'                                                                                                 
Makefile:169: recipe for target 'copy-files' failed                                                                                                   
make: *** [copy-files] Error 2

also maybe related 
command `make` could not download rebar dependencies so i hat to to `rebar get-deps`           

> was the unexpected behavior? What was the expected result?

**Comment by weiss** [comment]
> command `make` could not download rebar dependencies

Please start from scratch with a clean state (`cd my_location && git reset --hard && git clean -fxd && rm -rf deps`).  If you still run into an error (e.g., with downloading a dependency), please post the error output of the first issue the build is running into.

**Comment by KunaPrime** [comment]
@weiss thank you for solution, everything works fine now
