### ISSUE TITLE
Handling pgsql instance failure in case of max_queue size is reached

### ISSUE THREAD

**Issue by gsojitra** [processone/ejabberd#1324]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am using ejabberd with postgres as backend for all modules.When so many sql queries are pushed to ejabberd_sql module, you can see below error:

```
[error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours
 exited with reason: {process_limit,{max_queue,1004}} in p1_fsm:terminate/8 line 755 
[error] <0.293.0> Supervisor 'ejabberd_sql_sup_test.com' had child undefined
 started with ejabberd_sql:start_link(<<"test.com">>, 30000) at <0.295.0>
 exit with reason {process_limit,{max_queue,1004}} in context child_terminated
```

Above error is because of max_fsm_queue size is lower.It should have higher value.

The issue is that once this happens ejabberd_sql_sup will try to restart sql instance.In this case old pgsql connection to server will not be closed until ejabberd server is stopped.It will initiate one new connection without properly closing the previous connection.

This can be solved by linking ejabberd_sql process with p1_pgsql application.But pgsql is not linking process to ejabberd_sql.If ejabberd_sql is linked to pgsql then boh will go down and there will not be any stale client connection from server side.

**Comment by oxoWrk** [comment]
This problem does not allow the server to work without stopping  because there is a limit on the connection to the database server and this limit will be exhausted by ejabberd

**Comment by badlop** [comment]
Maybe this got solved by https://github.com/processone/ejabberd/commit/209f5d32e198416b62ef18407dd04138a44bd4ad
