### ISSUE TITLE
Allow writing custom modules in parent app when ejabberd embedded using elixir

### ISSUE THREAD

**Issue by ukutaht** [processone/ejabberd#1327]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

MacOS Sierra

> How did you install ejabberd (source, package, distribution)?

Mix Dependency

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've created a github repo to exemplify the desired behaviour:
https://github.com/ukutaht/example_ejabberd_mix_module

 It would be neat if users could write custom modules for ejabberd in the same project when it is embedded using mix. The current mechanism to use external modules in `ext_mod` does not seem sufficient for this use case but I may be wrong.
### Implementation notes

Currently the list of available modules is a concatenation of `ext_mod:installed()` and `application:get_key(ejabberd, modules)` ([source](https://github.com/processone/ejabberd/blob/master/src/ejabberd_config.erl#L917))

This list will not include modules written in the parent application. They are neither part of the `ejabberd` application or installed as an external module. However, they are available at runtime so it feels like it should be possible to use them.

I have a branch that solves this by searching through all loaded code at runtime instead of just the `ejabberd` application:
https://github.com/ukutaht/ejabberd/commit/775fd938eaab8ed95595e1fb44b2151259fd4f38

Are there any security implications to doing this? Any better ways to implement this?

**Comment by zinid** [comment]
Your patch will not work, because detecting supported databases of the modules will fail. For example, you don't have `mod_offline_sql` in `code:all_loaded()` list, so ejabberd knows nothing about `sql` database for `mod_offline`.

**Comment by ukutaht** [comment]
@zinid You're right, I gave it a try and it failed to find `mod_offline_sql`

Would you agree, though, that the example I've provided should work? It seems that embedding ejabberd is a fairly new use-case and I wonder if loading modules from other erlang applications is aligned with the vision.

If you think it's a good idea, I'd be happy to put some more effort into finding a good solution.

**Comment by zinid** [comment]
Of course it's a good idea. It's just at the moment I was writing this "db_type by suffix search" the only stuff came to my head was application:get_key(ejabberd, modules).

**Comment by cromain** [comment]
using ejabberd's env as proposed on #1351 is a possible path. we need to check if there is a possible better approach.

**Comment by cromain** [comment]
in ejabberdctl, just add this to EJABBERD_OPTS:
external_beams /path/to/my/beams

then all beams file /path/to/my/beams/*.beam will be allowed by ejabberd_config to be loaded
