### ISSUE TITLE
muc#roomconfig_maxusers doesn't work

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#1328]
As I can see in [xep-0045][1] there is option to limit max users in room:

    <field
          var='muc#roomconfig_maxusers'
          type='list-single'
          label='Maximum Number of Room Occupants'/>

I'm using Smack lib for Java to create rooms. And I send form during creation process like this:

    [...]
	List<String> list = new ArrayList<String>();
	list.add("3");
	submitForm.setAnswer("muc#roomconfig_maxusers", list);
    [...]
    muc.sendConfigurationForm(submitForm);

And it doesn't work. In one room I can see 4 ppl, for exmple, but server shouldn't accepted 4th invite, right?

Other options (`muc#roomconfig_persistentroom`, `muc#roomconfig_membersonly`, etc.) work fine. There is the problem only with `muc#roomconfig_maxusers`.

I'm using last version of ejabberd.

How can I limit max users in MUC? Or, what am I doing wrong?
  [1]: http://xmpp.org/extensions/xep-0045.html#registrar-formtype-owner

**Comment by zinid** [comment]
You cannot set random numbers there, because `muc#roomconfig_maxusers` field is of type `list-single`, so a user should choose a number from the list provided by the server (included as a bunch of `<option/>` elements). The defaults are here: https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L58

**Comment by Suvitruf** [comment]
Even if I've set 5, I still can invite new members after I have 5 members in room.

**Comment by zinid** [comment]
What value do you have in the config after submitting your new value?

**Comment by zinid** [comment]
Also, XML output would be great.

**Comment by Suvitruf** [comment]
Screen from Pidgin client:
![wqewq](https://cloud.githubusercontent.com/assets/1946939/19211015/85840022-8d6d-11e6-83e3-1e11daf1ea00.png)

same 5 in ctl output for `get_room_options` command:

> title
> description
> allow_change_subj       true
> allow_query_users       true
> allow_private_messages  true
> allow_private_messages_from_visitors    anyone
> allow_visitor_status    true
> allow_visitor_nickchange        true
> public  true
> public_list     true
> persistent      false
> moderated       true
> captcha_protected       false
> members_by_default      true
> members_only    true
> allow_user_invites      true
> allow_subscription      false
> password_protected      false
> password
> anonymous       true
> presence_broadcast      [moderator,participant,visitor]
> allow_voice_requests    true
> voice_request_min_interval      1800
> max_users       5
> logging false
> vcard
> captcha_whitelist       {0,nil}
> mam     false


As you can see, there is 5 in config, but still have 6 ppl in room.

**Comment by zinid** [comment]
If there are admins, the maximum participants number is counted as sum of `max_users` and `max_users_admin_threshold` (configuration value, default is 5).
So, if you have only one admin in your room, the behaviour of ejabberd is still valid in your case.

**Comment by Suvitruf** [comment]
Oh, thanks for clarity.

Btw, are you planning in future releases to make it possible set different value for `muc#roomconfig_maxusers` (not `[5, 10, 20, 30, 50, 100, 200, 500, 1000, 2000, 5000]`)?

**Comment by zinid** [comment]
I personally am not planning this.
