### ISSUE TITLE
Unable to get onlineUsers

### ISSUE THREAD

**Issue by spidyamit** [processone/ejabberd#1329]
> What version of ejabberd are you using?

ejabberd 2.1.10 

> What operating system (version) are you using?

ubuntu12.04

> How did you install ejabberd (source, package, distribution)?

Ubunutu distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I recently move my server to clustered one, earlier it was standalone server which is still working way fine. As per client request to handle 25K users concurrent connection we setup this clustered server. _Purpose of this server is push notification and real time chat._

I am using 

```
<query xmlns='http://jabber.org/protocol/disco#items' node='online users'/>
```

 to get all online users from standalone its working fine but after clustered server its giving me error 

```
<error code='404' type='cancel'>
  <item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
```

Is there anything need to configure differently with clustered server?

I have 3 clustered node which is getting called from LoadBalancer.

Any suggestion !!

**Comment by spidyamit** [comment]
Also want to know, does installing Erlang OTP before ejabberd on the server enhances the performace?

**Comment by badlop** [comment]
> to get all online users from standalone its working fine but after clustered server its giving me error

Oh. The WebAdmin has a page that shows the list of users. Does it work correctly?

> Also want to know, does installing Erlang OTP before ejabberd on the server enhances the performace?

No.

**Comment by spidyamit** [comment]
> Oh. The WebAdmin has a page that shows the list of users. Does it work correctly?
Yes, its listing all users at single place no matter of node its connected to. Only failing at the time calling from script via library.

**Comment by badlop** [comment]
Ok, it probably is a bug in mod_configure.erl.

When you perform that call and get an error response, do you see anything relevant in the ejabberd log files? Maybe some crash report?
