### ISSUE TITLE
Ejabberd sorts stanzas by type when received within the same Bosh envelope

### ISSUE THREAD

**Issue by vcarel** [processone/ejabberd#133]
When sending a request like this on Bosh:

``` xml
<body rid='someRID' xmlns='http://jabber.org/protocol/httpbind' sid='someSID'>
<message to='someUser@someDomain' type='chat' xmlns='jabber:client'>
<body>123</body>
</message>
<presence type='unavailable' xmlns='jabber:client' />
</body>
```

... the presence is always executed first, then the message follows.
This behaviour is not compliant with the RFC 6120, which says in section 10.1:
"An XMPP server MUST ensure in-order processing of the stanzas and
other XML elements it receives over a given input stream from a
connected client or remote server."

(see https://support.process-one.net/browse/EJAB-1665)

**Comment by prefiks** [comment]
This seems to work fine now.
