### ISSUE TITLE
 my client can't select to ejabberd server

### ISSUE THREAD

**Issue by qimingzhizuimafanle** [processone/ejabberd#1330]
> What version of ejabberd are you using?

ejabberd 16.09

> What operating system (version) are you using?

ubuntu 12.04

> How did you install ejabberd (source, package, distribution)?

source
> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i'm going to do a server use ejabberd, all is ok, but my client can't select to ejabberd server. what should i do?The client connect to the server to respond when the server, but can't log in successfully, the problem is the ejabberd.yml?How do I go to change it? or other reasons? my select is pidgin, the ejabberd version is 16.09. first of all, thank you.

When I click on client login button, the server will respond:
```
21:33:56.315 [info] (#Port<0.14803>) Accepted connection
 192.168.177.1:8423 -> 192.168.177.132:5222
```

However, the client login failed.
What should I do now?
PS: English learning is not good, sorry!

**Comment by qimingzhizuimafanle** [comment]
I have already connected to the server. But I didn't do anything, I just put the client has Pindion. Pidgin the client still even can't do it, Why?

**Comment by badlop** [comment]
Maybe your ejabberd configuration file requires tls or starttls, Pandion can use it, but Pidgin cannot. Or maybe the version of Pidgin you use have some bug when authenticating.

Try other clients like Psi, Gajim, Tkabber. If all they work correctly, then you know the problem is probably only in Pidgin. If they don't work, then the problem is probably in ejabberd.

**Comment by qimingzhizuimafanle** [comment]
@badlop  Really thank you very much.  Other client can log in, I think it is Pidgin problem in itself. And I found Pidgin for Linux can log in, just Pidgin for Windows has a problem.
