### ISSUE TITLE
MUC sub for multiple resources of the same user.

### ISSUE THREAD

**Issue by srikanth231** [processone/ejabberd#1332]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We are trying to use MUC sub to build persistent whatsapp like rooms. Our requirement is for the messages to be in sync on multiple devices. 

According to the Blog, MUC SUB is exposed as a pubsub node. But the message events are only sent to the highest priority resource as normal xmpp messages.  Where as normal pubsub events by default are sent with type="headline" and broadcasted to all the resources. 

Is there is way to change this behavior as normal pubsub messages and the events will be sent with type='headline' by default and broadcasted to all the resources of the client.

Thanks,
Srikanth V

**Comment by badlop** [comment]
That is not configurable. But a simple patch like this can do the trick for you:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index fc2aeeb..7ec92e4 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -5219,7 +5219,8 @@ wrap(From, To, Packet, Node) ->
     Event = #xmlel{name = <<"event">>,
 		   attrs = [{<<"xmlns">>, ?NS_PUBSUB_EVENT}],
 		   children = [Items]},
-    #xmlel{name = <<"message">>, children = [Event]}.
+    Attrs2 = [{<<"type">>, <<"headline">>}],
+    #xmlel{name = <<"message">>, attrs = Attrs2, children = [Event]}.
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %% Multicast
```

**Comment by srikanth231** [comment]
Thanks Badlop. I will try that.
