### ISSUE TITLE
MUC <subject> still doesn't quite match XEP spec

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#1333]
From XEP-0045:

> After the room has optionally sent the discussion history to the new occupant, it SHALL send the current room subject. This is a <message/> stanza from the room JID (or from the occupant JID of the entity that set the subject)

&nbsp;

> If there is no subject set, the room MUST return an empty <subject/> element.

&nbsp;

> After a client sends presence to join a room, the MUC service MUST send it events in the following order:
> 1.   In-room presence from other occupants
> 2.   In-room presence from the joining entity itself (so-called "self-presence")
> 3.   Room history (if any)
> 4.   The room subject

As far as I can understand ejabberd's current (as of 16.08) behavior, it will include subject changes in the room history (which is really useful, btw, and that shouldn't be altered), and then send the current subject if and only if
1. it is non-empty and
2. the most recent subject change is no longer in the room history.

Unfortunately, this requires some workarounds if the client wants to use and react to the current subject, or recognize the end of the room history. The `<subject/>` serves to mark that end just as the self-presence marks the end of the roster.

Without it, I have no idea if any given `<delay/>` message is the final one (and especially, whether a given `<subject/><delay/>` message is the last subject change) until the first live message arrives.

The only change would be to always send a non-delay `<subject/>` message (even if empty) in addition to and **after** the room history.

**Comment by cburschka** [comment]
Update: I just built 16.09 and this seems to be fixed, so I'm tentatively closing. :)

**Comment by cburschka** [comment]
(Sorry, updating just cleared the room history. The logic is still the same.)

**Comment by zinid** [comment]
I have already fixed this in `xml-ng` branch. So this will be fixed in 16.11 or something like this.

**Comment by zinid** [comment]
This is now fixed in 16.12.
