### ISSUE TITLE
ejabberdctl segmentation error from shell after upgrade

### ISSUE THREAD

**Issue by v10star** [processone/ejabberd#1334]
> What version of ejabberd are you using?
16.08

> What operating system (version) are you using?
ubuntu 16.10

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

from shell i cannot get command ejabberdctl work: they gave me those two errors: 

/usr/sbin/ejabberdctl: row 385: /proc/sys/kernel/random/uuid: Permession denied
/usr/sbin/ejabberdctl: row 366:  5904 Segmentation error $EXEC_CMD "$CMD"

the first one is not new (gettin' this from two months after an upgrade) but the second one is brandnew, after a dist-upgrade i cannot administer ejabberd from shell and command exit with the two errors above. Service is running and clients are functional.

**Comment by debalance** [comment]
That's AppArmor blocking access, should be obvious after a look into syslog. Disable AppArmor for ejabberd or adjust the permissions.

This is no upstream bug.
