### ISSUE TITLE
[cmd] ejabberdctl user_resources

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#1336]
> What version of ejabberd are you using?

The node ejabberd@localhost is started with status: started
ejabberd 16.09 is running in that node

> What operating system (version) are you using?

mac osx 10.11

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I got a problem about get user resource.

when i use ejabberdctl user_resources [user] [server] in my command line.
->ejabberdctl user_resources test@xmpp localhost

**It is no any response to me.**

I am sure that test@xmpp was register already. and i could see the resource on website-xmpp:5280

Does anyone could help me to solve this problem? Thanks

**Comment by badlop** [comment]
If the account is user@xmpp, then what is "localhost" in your request? Try:
```
$ ejabberdctl user_resources user1 shakespeare.example
tka1
```

**Comment by jhaoheng** [comment]
hi @badlop 
Thanks your review.
just change [localhost] to [vhost_Name] and it is work.
Because the cmd info describe [server] and it let me confused.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:26906)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1buJyY-00021r-Dh
	for zero@thezeroworld.com; Wed, 12 Oct 2016 09:53:42 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kVTWxyjl7HTf/rofshxW4EYmfNE=; b=plGOhwKVsVp8TgrP
	XhMdSg89TjHrtbCL1kSXddJnU3urUkg+x5Xeih5sQZbLUQEQDGONFyzBej8+8cyY
	6bUwdbI6B3MUFl6wWm605822krhcCgbNU0YtTgpAYU9q0cP53CN+im6UKaovVo9l
	LExMNG0ZDv08dMFD96vplrTX75g=
Received: by filter0969p1mdw1.sendgrid.net with SMTP id filter0969p1mdw1.11926.57FE40394A
        2016-10-12 13:52:57.612117475 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id R5Hwxl51QWe94Q77nCUJmw
	for <zero@thezeroworld.com>; Wed, 12 Oct 2016 13:52:57.286 +0000 (UTC)
Date: Wed, 12 Oct 2016 06:52:57 -0700

**Comment by jhaoheng** [comment]
@badlop 
By the way.
Do you know which api/plugin like the cmd [user_resources] have the same feature?
Thank you

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46745 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1buK2L-00058t-Iy
	for zero@thezeroworld.com; Wed, 12 Oct 2016 09:57:37 -0400
Date: Wed, 12 Oct 2016 06:56:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1476280617;
	bh=h0H5mpDEAMu8kGjJSEDzKiTltqXu8+T6Vxvo3prap6U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=dSGNP9o4qp5oumiByBLeuTJAoMPFy1ah6/hWqRGk5IHfwGSa0CcZAZzlqBsnqmnU1
	 VUYAsN02mSwHjCul5+yKwI8wt1u+b4OjrN0nzLBqjmGsvKaQzkogng9LtsayUk3Aiw
	 IZOCF4oyZ+O2sRXnDPZxUAtNdnxqEwyodCq4uvk4=
