### ISSUE TITLE
Supporting RETURNING clause in INSERT, UPDATE, DELETE statements (pgsql)

### ISSUE THREAD

**Issue by iAchilles** [processone/ejabberd#1339]
Hi there!
It would be nice to use RETURNING clause in the queries like that:

```
INSERT INTO t (city, name) VALUES ('Santa Monica', 'Igor') RETURNING id;
UPDATE t SET city = 'New York'  WHERE name = 'Chris' RETURNING id;
DELETE FROM t WHERE city = 'Abu Dhabi' RETURNING id;
```

**Comment by badlop** [comment]
Where could that feature be used? What advantage does it have?

**Comment by iAchilles** [comment]
In an INSERT, the data available to RETURNING is the row as it was inserted. This is not so useful in trivial inserts, since it would just repeat the data provided by the client. But it can be very handy when relying on computed default values. For example, when using a serial column to provide unique identifiers, RETURNING can return the ID assigned to a new row.
