### ISSUE TITLE
I am not able to list ejabberIDs from a specific Roster group

### ISSUE THREAD

**Issue by RajDubey** [processone/ejabberd#1341]
> What version of ejabberd are you using?

ejabberd-16.06

> What operating system (version) are you using?

Redhat linux

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am not able to list ejabberIDs from a specific Roster group.

**Comment by badlop** [comment]
How do you attempt to list them? What exactly does not work? Do you get any relevant line in the ejabberd log files when you attempt it?
