### ISSUE TITLE
 unable to load fast_yaml NIF

### ISSUE THREAD

**Issue by jianjyan** [processone/ejabberd#1342]
> What version of ejabberd are you using?

ejabberd 16.09

> What operating system (version) are you using?

CentOS release 6.6 (Final)
OTP 18.1

> How did you install ejabberd (source, package, distribution)?

from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Expected reulst: ejabberd should be started successfully
Unexpected behavior: can't be started successfully
log:
```
[warning] unable to load fast_yaml NIF: {error,{bad_lib,"Library module name 'fast_yaml' does not match calling module 'application_master'"}}
08:12:58.357 [error] CRASH REPORT Process <0.105.0> with 0 neighbours exited with reason:
 {{bad_lib,"Library module name 'fast_yaml' does not match calling module 'application_master'"},
  {fast_yaml_app,start,[normal,[]]}} in application_master:init/4 line 134

08:12:58.357 [critical] failed to start application 'fast_yaml':
 {error, {{bad_lib,
      "Library module name 'fast_yaml' does not match calling module 'application_master'"},
      {fast_yaml_app,start,[normal,[]]}}}

08:12:58.357 [info] Application fast_yaml exited with reason:
 {{bad_lib,"Library module name 'fast_yaml' does not match calling module 'application_master'"},
   {fast_yaml_app,start,[normal,[]]}}

Crash dump is being written to: /data/ejabberd/var/log/ejabberd/erl_crash_20161018-081256.dump...done
failed to start application 'fast_yaml': {error,
                                          {{bad_lib,
                                            "Library module name 'fast_yaml' does not match calli
```

**Comment by jianjyan** [comment]
I copied the ejabberd.cfg into etc/ejabberd folder and  updated EJABBERD_CONFIG_PATH=$ETC_DIR/ejabberd.cfg in ejabberdctl.template;  then recompile and restarted.

but other error occurs:
[warning] unable to load sha NIF: {error,{bad_lib,"Library module name 'p1_sha' does not match calling module 'application_master'"}}
09:02:52.955 [error] CRASH REPORT Process <0.105.0> with 0 neighbours exited with reason: no match of right hand value {error,{bad_lib,"Library module name 'p1_sha' does not match calling module 'application_master'"}} in fast_tls_app:start/2 in application_master:init/4 line 134
09:02:52.955 [critical] failed to start application 'fast_tls': {error,
                                         {bad_return,
                                          {{fast_tls_app,start,[normal,[]]},
                                           {'EXIT',
                                            {{badmatch,
                                              {error,
                                               {bad_lib,
                                                "Library module name 'p1_sha' does not match calling module 'application_master'"}}},
                                             [{fast_tls_app,start,2,[]},
                                              {erlang,fun_info,1,[]}]}}}}}
09:02:52.955 [info] Application fast_tls exited with reason: no match of right hand value {error,{bad_lib,"Library module name 'p1_sha' does not match calling module 'application_master'"}} in fast_tls_app:start/2

Crash dump is being written to: /data/ejabberd/var/log/ejabberd/erl_crash_20161018-090251.dump...done
failed to start application 'fast_tls': {error,
                                         {bad_return,
                                          {{fast_tls_app,start,[normal,[]]},

**Comment by weiss** [comment]
Did you compile ejabberd with `./configure --enable-hipe` and does it work if you omit that flag?

**Comment by jianjyan** [comment]
Yes, It's now started without --enable-hipe flag! So, what happened?

**Comment by jianjyan** [comment]
The performance may get degraded without this flag; any suggestion?

**Comment by weiss** [comment]
> The performance may get degraded without this flag

What makes you believe that?  ejabberd is usually not CPU-bound.  And there's downsides to using HiPE; e.g., you don't (necessarily) get proper error traces.

> any suggestion?

You should be able to compile with `--enable-hipe` when using the current `master` branches of some of ejabberd's dependencies.  You could try this patch to do that (please report back if you do):

    curl http://sprunge.us/bNBA | git apply
    make update
    make install

**Comment by jianjyan** [comment]
can't make it:

curl http://sprunge.us/bNBA | git apply
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
102  2368  102  2368    0     0   5575      0 --:--:-- --:--:-- --:--:--  5678
error: patch failed: rebar.config:10
error: rebar.config: patch does not apply

**Comment by weiss** [comment]
Please try again from scratch:

    git checkout 16.09
    git reset --hard
    git clean -fdx
    rm -rf deps
    ./autogen.sh
    curl http://sprunge.us/bNBA | git apply
    ./configure --enable-hipe # [...]
    make
    make install

**Comment by jianjyan** [comment]
Hi, I have recompiled both the original code and the modified code as per your guide. both can be started now. 
However, I can start them even with -enable-hipe and not doing anything special such as your guide. how strange it is.

**Comment by weiss** [comment]
It works with current development versions of some of the dependencies compiled below the `deps` folder.  I guess you updated that folder (by using my patch) and then recompiled the code without my patch, but without clearing the `deps` folder.  In that case you would still end up with the newer dependency versions.

Anyway, thanks for the feedback.
