### ISSUE TITLE
Problem with PID file and setcap

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1347]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian 8.6

> How did you install ejabberd (source, package, distribution)?

From package provided by jabber.at.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After upgrading from version 16.04 to 16.09 ejabberd stops writing PID file - I spent a few hour to fix it and I found that the problem lies with caps that I set for erlang:

```
setcap 'cap_net_bind_service=+ep' /usr/lib/erlang/erts*/bin/beam
setcap 'cap_net_bind_service=+ep' /usr/lib/erlang/erts*/bin/beam.smp
```

When I removed caps ejabberd start writing PID file again. I don't upgraded erlang with upgrading ejabberd, is there any way to fix it?

P.S. I need this to set listening port 80 and 443 in ejabberd.

**Comment by weiss** [comment]
Does it help if you apply [this change][1] to the systemd unit file?  (Thanks to @mathiasertl for this idea.)

> P.S. I need this to set listening port 80 and 443 in ejabberd.

You could specify two `DNAT` rules with iptables instead, or (even better) use a reverse proxy such as Nginx.

[1]: https://github.com/weiss/ejabberd/commit/c3b62d2f75d70a6a6069f4e6a49c374e2fd52809.patch

**Comment by beherit** [comment]
Yes, this change works perfect.

**Comment by beherit** [comment]
After upgrade ejabberd from version 17.04 to 17.08 again I have this issue. Is something changed?
