### ISSUE TITLE
Offline message doesn't make it to MAM archive of receiving user

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1348]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have the following scenario with two users, let's name them Alice and Bob.
1. Alice sends Bob a message while he's offline.
2. Our custom module that adds a `offline_message_hook` receives the message and handles it without any errors.
3. The message is written to the Alice's MAM archive.
4. Bob connects again and queries his MAM archive.
5. Alice's message is not included in the response.

I'm assuming something happens in between (3) and (4). In order to reproduce this issue I would like to know what it might be. I've briefly looked into the code and it looks like messages for receivers are only written when they are actually received by the user, right?

Would it be possible that the message was dropped because the offline message limit was reached, it was therefore never received by Bob, and thus never written to Bob's MAM archive?

**Comment by badlop** [comment]
> Would it be possible that the message was dropped because the offline message limit was reached, it was therefore never received by Bob, and thus never written to Bob's MAM archive?

Right, or maybe your code stops the hook, so mod_offline never really stores the message, and is never _delivered_ to Bob, consequently is never written to MAM.

**Comment by marcphilipp** [comment]
Thanks for the quick reply! Would it make sense to always store messages in the archive regardless whether they were received yet?

**Comment by weiss** [comment]
> Would it make sense to always store messages in the archive regardless whether they were received yet?

I [suggested][1] that in the context of issue #1344, but this would require some changes.

[1]: https://github.com/processone/ejabberd/issues/1344#issuecomment-254819549

**Comment by marcphilipp** [comment]
We would certainly welcome such a change!

Do you want to track that in #1344 so we can close this issue?

**Comment by marcphilipp** [comment]
@weiss Any news on always storing messages in the MAM archive?

**Comment by weiss** [comment]
> Do you want to track that in #1344 so we can close this issue?

I'd keep both open.  They are different issues and we might or might not end up with a single solution to both.

> @weiss Any news on always storing messages in the MAM archive?

Not from me.  I have this on my to-do list, but right now I'm busy with other things.  But maybe others have an opinion on this ...

**Comment by zinid** [comment]
Done

**Comment by marcphilipp** [comment]
@zinid I've commented on the commit: 68cf45a8b9e91a9d543816ca024bfc6aa26cb5df

**Comment by zinid** [comment]
I replied there, although it's better to discuss the issue here.
