### ISSUE TITLE
Order of messages is not preserved in MUC history

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1352]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Failure scenario:
1. Send a large number of messages in a short time period to an MUC from user Alice
2. When previously offline user Bob signs in a again, he receives the messages from Alice.
3. Sometimes, one or more of the messages are not in the order they were sent in.

**Comment by iAchilles** [comment]
@marcphilipp,
The received messages in wrong order are placed close to each other in the list?
For example:

| Alice (Sender)  | Bob (Recipient) |
| ------------- | ------------- |
| A  | A |
| B  | B  |
| C  | C |
| D  | D  |
| E  | E |
| F  | F  |
| **G**  | H|
| H  | **G**  |
| I  | I |
| J  | J  |
| K  | K |
| L  | L  |

**Comment by marcphilipp** [comment]
Yes, exactly.

**Comment by marcphilipp** [comment]
This is still happening for us.

@badlop @weiss @mremond Can you please take a look?

**Comment by zinid** [comment]
What database are you using for MAM?

**Comment by marcphilipp** [comment]
We're using SQL (MySQL).

**Comment by cromain** [comment]
Closing this old issue. archive code changed a lot since 16.09 and we have no known ordering issues in recent releases.
