### ISSUE TITLE
Use ejabberd-erlang modules in ejabberd-elixir.

### ISSUE THREAD

**Issue by eathroat** [processone/ejabberd#1354]
> What version of ejabberd are you using?
>  ejabberd elixir - 16.09.0 

I'm trying to use [mod_push](https://github.com/royneary/mod_push) from ejabberd-elixir, I placed source files in lib/ but ejabberd throws error. However it works fine when I try using with elixir modules, I tried mod_presence_demo.ex from https://blog.process-one.net/ejabberd-joins-the-elixir-revolution which works fine. 

Thanks.

**Comment by weiss** [comment]
This version of mod_push won't work with ejabberd 16.09, sorry.

**Comment by eathroat** [comment]
@weiss Using [mod_gcm](https://github.com/mrDoctorWho/ejabberd_mod_gcm) also give the same error, tried with standalone ejabberd module installation and it works fine.

>[warn] module 'mod_gcm' doesn't export mod_opt_type/1
[error] Problem starting the module mod_gcm for host <<"localhost">> 
 options: [{gcm_api_key,<<"">>}]
 error: undef
[{mod_gcm,start,
          [<<"localhost">>,
           [{gcm_api_key,<<"">>}]],
          []},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,154}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,78}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
[error] ejabberd initialization was aborted because a module start failed.

**Comment by kuchhadiyaa** [comment]
I am getting same error... 

Any fix?

**Comment by mremond** [comment]
It seems those contributed modules need to be updated to work with latest version of ejabberd.

**Comment by kuchhadiyaa** [comment]
Ok thanks for quick replay.

Which latest previous version supports this module?
I have modified [https://github.com/dirkmoors/mod_interact](url) according to my needs.

**Comment by zinid** [comment]
It should work with 16.09.
