### ISSUE TITLE
Messages are intermittently not saved to MAM archive table

### ISSUE THREAD

**Issue by karoldanutama** [processone/ejabberd#1356]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-67-generic x86_64)

> How did you install ejabberd (source, package, distribution)?

Linux distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
# Background

We are using Ejabberd 16.02 to host a chat application with mobile (Android and iOS) and web clients. We have been using for around a year. The following is our use case and technical implementation at a glance:
1. We allow 1 user to logs in from multiple devices at the same time. The user is assigned a unique resource for each device.
2. We use `mod_mam` as primary message history source. To help improving performance we have local cache for Android and iOS clients. However web client still requests to MAM.
3. Android and iOS clients are disconnected from Ejabberd when the app goes background to save up battery and network traffic.
4. We create our own module, hooked to `offline_message_hook` for sending push notification via GCM and APNS so that Android and iOS users get notified when there is a message for them when the app is disconnected.
# Problem Description

Around 2 months ago there was a noticeable report from users that they receive private chat push notification to their mobile device, but the messages were absent from their MAM archive. Looking directly into the database, we found out that lost messages were present in the **sender's** archive but not in the **recipient's** archive, i.e: there is only 1 message instead of a pair of messages.
# What We Have Done
## 1. mod_offline Investigation

From all occurrences, we learnt that the lost messages only happened when offline messages were flushed to the recipient when the recipient was connected and had the session opened. We learnt that message archive is saved when the recipient receives the packet. Hence we create a module hooked to `user_receive_packet` to see whether the hook was properly called. It turned out the hook was properly called for _all_ offline messages. This finding moved our attention from `mod_offline` to `mod_mam` with question: why were the messages not saved?
## 2. mod_mam Investigation

To get a better picture of what happen in `mod_mam`, we first traced the code in [mod_mam:user_receive_packet/5](https://github.com/processone/ejabberd/blob/16.02/src/mod_mam.erl#L201). We learnt that this function is responsible for saving the archive to the database when the packet is received. We also learnt that there are two guards that may prevent `store_msg` from being called: `mod_mam:should_archive/2` and `mod_mam:is_bare_copy/2`. We took a bet on `mod_mam:is_bare_copy/2` since we did not understand what this function was responsible for. We understood that `IsBareCopy` needed to be true and `should_archive` needed to be true for a packet was unsaved to database. One condition that may cause `IsBareCopy` to be true is when `PrioRes` returns empty list. We then modified `mod_mam:user_receive_packet/5` and `mod_mam:is_bare_copy/2` code and add some log. This is the snippet of our modified code:

**mod_mam:user_receive_packet/5**

```
user_receive_packet(Pkt, C2SState, JID, Peer, To) ->
    ?INFO_MSG("user_receive_packet with content ~p", [Pkt]),
    LUser = JID#jid.luser,
    LServer = JID#jid.lserver,
    IsBareCopy = is_bare_copy(JID, To),
    IsShouldArchive = should_archive(Pkt, LServer),
    if (IsBareCopy == true) and (IsShouldArchive == true) ->
        ?INFO_MSG("should archive and is bare copy return true with packet ~p , JID ~p , Peer ~p, To ~p ", [Pkt, JID, Peer, To]);
    true ->
        ok
    end,
    case should_archive(Pkt, LServer) of
    ....
```

**mod_mam:is_bare_copy/2**

```
is_bare_copy(#jid{luser = U, lserver = S, lresource = R}, To) ->
    PrioRes = ejabberd_sm:get_user_present_resources(U, S),
    MaxRes = case catch lists:max(PrioRes) of
         {_Prio, Res} when is_binary(Res) ->
             Res;
         _ ->
             undefined
         end,
    ?INFO_MSG("For user ~p PrioRes contains ~p MaxRes containt ~p", [U, PrioRes, MaxRes]),
    ....
```

We deployed our .beam and monitored for a day. We found out there were tens of messages lost, indicated by should_archive=true and IsBareCopy=true logs spitted out. We traced to `is_bare_copy` log and we found out that `PrioRes` was indeed an empty list! This finding moved our attention once again to Redis.
## 3. SM Backend Investigation

We did the same thing to `ejabberd_sm_redis`. We added log to `ejabberd_sm_redis:set_session/1` and `ejabberd_sm_redis:delete_session/4`. We deployed it and we found the following log trails.

```
1. We got 6 messages flushed from Offline Storage to user tsaqovanbasten@host, all with IsBareCopy true and should_archive true. Time:
  - 2016-10-19 19:15:19.746
  - 2016-10-19 19:15:19.749
  - 2016-10-19 19:15:19.753
  - 2016-10-19 19:15:19.759
  - 2016-10-19 19:15:19.756
  - 2016-10-19 19:15:19.762
2. ejabberd_sm:get_present_resources always returned empty list since 2016-10-19 19:15:19.746 - 2016-10-19 19:15:25.747
  - 2016-10-19 19:15:19.749 [info] <0.30314.148>@mod_mam:is_bare_copy:1109 For user <<"tsaqovanbasten">> PrioRes contains [] MaxRes containt undefined
  - ...
  - 2016-10-19 19:15:25.747 [info] <0.30314.148>@mod_mam:is_bare_copy:1109 For user <<"tsaqovanbasten">> PrioRes contains [] MaxRes containt undefined
3. ejabberd_sm_get_present_resources did return non-empty list after this point and forth
  - 2016-10-19 19:15:26.154 [info] <0.30314.148>@mod_mam:is_bare_copy:1109 For user <<"tsaqovanbasten">> PrioRes contains [{0,<<"resource-582546bfdfa6b5e5">>}] MaxRes containt <<"resource-582546bfdfa6b5e5">>
4. ejabberd_sm_redis:set_session was called successfully several times
  - 2016-10-19 19:15:18.946 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},undefined,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
  - 2016-10-19 19:15:19.715 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},undefined,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
  - 2016-10-19 19:15:19.620 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},0,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
  - 2016-10-19 19:15:26.082 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},0,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
  - and so on...
5. However, ejabberd_sm_redis:delete_session was called only twice
  - 2016-10-19 19:15:26.952 [info] <0.30314.148>@ejabberd_sm_redis:delete_session:87 Delete session for user <<"tsaqovanbasten">> server <<"host">>, resource <<"resource-582546bfdfa6b5e5">>, sid {{1476,904514,383616},<0.30314.148>}
  - 2016-10-19 19:15:40.793 [info] <0.26035.663>@ejabberd_sm_redis:delete_session:87 Delete session for user <<"tsaqovanbasten">> server <<"host">>, resource <<"resource-582546bfdfa6b5e5">>, sid {{1476,904527,119370},<0.26035.663>}
6. No errors logged from ejabberd_sm_redis, including: set, get and delete
7. We found an error when cleaning Redis table yesterday
  - 2016-10-19 03:43:30.632 [error] <0.7530.145>@ejabberd_sm_redis:clean_table:205 failed to clean redis table for server host: [{error,<<"ERR wrong number of arguments for 'hdel' command">>}]
```

According to the log above Redis constantly returned empty list for 6 seconds after being set. We suspected our Redis experienced a read delay, albeit we were unsure because the _delay_ was massive. Milliseconds delay is reasonable, but 6 seconds delay is just wrong. Not to mention we do not have read replica for our Redis yet.

We later at that day moved for a while to ODBC SM DB to upgrade our Redis instance type. We also tested a fallback plan (ODBC) in case we could not rely on Redis. We were with ODBC SM DB for about 3 hours. Moving to ODBC only left us with a fact that it happened again. At this point we were sure it is not on Redis. Back to square one...
## 4. Workaround Solution

On Monday we accepted the fact that we can not find a fix for this. We then decided to find a temporary work around while waiting for the real fix. Our workaround was implemented like this:
1. Creating a module hooked to `user_receive_packet` with order just before `mod_mam:user_receive_packet/5`.
2. In the hook function, we check if the user present resource is empty. If true, we requeue the message to `spool` table. We think that if `user_receive_packet` is called and session is empty, the message will not be saved to MAM.

We have been monitoring the logs for 4 days and all suspected lost messages were successfully saved to recipient's archive.
# Call for Help

We understand our solution is just temporary. We call for help to trace the root cause and hopefully it will be fixed in the future release of Ejabberd.
# Technical Information
- Redis on AWS Elasticache for Ejabberd Session Manager
- MariaDB 10.0.17 on AWS RDS for archive, roster, etc
# Credits
- @weiss for early tracing leads.

**Comment by badlop** [comment]
> we found out that PrioRes was indeed an empty list! 

This may happen when the client is logging in the server, as it receives some stanzas but the session is not yet fully set, so no presence is yet available. Those messages that surely are not stored are IQ stanzas regarding session setup, no important message stanzas.

See:
```
19:53:46.196 [info] ({socket_state,gen_tcp,#Port<0.21093>,<0.19124.2>})
 Accepted authentication for user2 by undefined from 127.0.0.1
19:53:46.282 [info] ({socket_state,gen_tcp,#Port<0.21093>,<0.19124.2>})
 Opened session for user2@localhost/tka1
19:53:46.336 [info] For user <<"user2">> PrioRes contains [] MaxRes containt undefined for packet
 {xmlel,<<"iq">>,[{<<"from">>,<<"user2@localhost">>},{<<"to">>,...
19:53:46.461 [info] For user <<"user2">> PrioRes contains [] MaxRes containt undefined for packet
 {xmlel,<<"iq">>,[{<<"from">>,<<"user2@localhost">>},{<<"to">>,...
19:53:46.583 [info] For user <<"user2">> PrioRes contains [{3,<<"tka1">>}] MaxRes containt <<"tka1">> for packet
 {xmlel,<<"iq">>,[{<<"from">>,<<"user2@localhost">>},{<<"to">>,...
...
```

It seems you have two problems here. One is the 6 seconds delay when using Redis. This may be caused by ejabberd waiting 6 seconds for some kind of response that the client doesn't send, and then following on other stuff. Or with the client waiting 6 seconds for something that ejabberd doesn't send, etc. You should check what is the traffic exactly before and after that delay, and if it's always the same kind of stanzas.

The second and major problem is that some received mesages are not stored in MAM. From what I understand, you traced the problem to is_bare_copy becoming true when it shoudn't. If you look carefully at is_bare_copy last Case, it returns true when:
1. the TO attribute in the original stanza was a bare JID, or the provided resource is not online right now,
2. AND there isn't a valid PrioRes.

Maybe your stanzas are hitting point 1?

In case you suspect the problem is point 2, you can finetune your debugging line:
```
--- a/src/mod_mam.erl
+++ b/src/mod_mam.erl
@@ -224,7 +224,7 @@ set_room_option(Acc, _Opt, _Vals, _Lang) ->
 user_receive_packet(Pkt, C2SState, JID, Peer, To) ->
     LUser = JID#jid.luser,
     LServer = JID#jid.lserver,
-    IsBareCopy = is_bare_copy(JID, To),
+    IsBareCopy = is_bare_copy(JID, To, Pkt),
     case should_archive(Pkt, LServer) of
 	true when not IsBareCopy ->
 	    NewPkt = strip_my_archived_tag(Pkt, LServer),
@@ -921,7 +921,7 @@ maybe_update_from_to(#xmlel{children = Els} = Pkt, JidRequestor, JidArchive,
 maybe_update_from_to(Pkt, _JidRequestor, _JidArchive, _Peer, chat, _Nick) ->
     Pkt.
 
-is_bare_copy(#jid{luser = U, lserver = S, lresource = R}, To) ->
+is_bare_copy(#jid{luser = U, lserver = S, lresource = R}, To,Pkt) ->
     PrioRes = ejabberd_sm:get_user_present_resources(U, S),
     MaxRes = case catch lists:max(PrioRes) of
 		 {_Prio, Res} when is_binary(Res) ->
@@ -948,6 +948,8 @@ is_bare_copy(#jid{luser = U, lserver = S, lresource = R}, To) ->
 	    %% only from the resource where R equals MaxRes.
 	    ?DEBUG("Additional recipient of message to bare JID: ~s@~s/~s",
 		   [U, S, R]),
+	    ?INFO_MSG("For user ~s@~s/~s PrioRes contains ~p"
+		" MaxRes containt ~p~n and the packet was ~p", [U,S,R, PrioRes, MaxRes,Pkt]),
 	    true;
 	{false, _R} ->
 	    false
```

**Comment by weiss** [comment]
@badlop

> This may happen when the client is logging in the server, as it receives some stanzas but the session is not yet fully set, so no presence is yet available.

But the `ejabberd_c2s` process will only receive messages from `ejabberd_sm` once the `ejabberd_c2s` PID was added to the session table.  How would `ejabberd_sm` look up the destination PID before that happened?

@karoldanutama

    2016-10-19 19:15:18.946 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},undefined,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
    2016-10-19 19:15:19.715 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},undefined,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}

This is where the session is opened.  But why is this called twice, by the same Erlang process (`<0.30314.148>`)?  I would've said this "cannot happen".

    2016-10-19 19:15:19.620 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},0,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}
    2016-10-19 19:15:26.082 [info] <0.30314.148>@ejabberd_sm_redis:set_session:69 Set session for {session,{{1476,904514,383616},<0.30314.148>},{<<"tsaqovanbasten">>,<<"host">>,<<"resource-582546bfdfa6b5e5">>},{<<"tsaqovanbasten">>,<<"host">>},0,[{ip,{{10,0,1,11},27791}},{conn,c2s_tls},{auth_module,undefined}]}

This could happen twice if your client sends two presence stanzas (both with a priority of 0 or with no explicit priority), but it seems more likely this is happening due to the same issue as above.

    2016-10-19 19:15:26.952 [info] <0.30314.148>@ejabberd_sm_redis:delete_session:87 Delete session for user <<"tsaqovanbasten">> server <<"host">>, resource <<"resource-582546bfdfa6b5e5">>, sid {{1476,904514,383616},<0.30314.148>}
    2016-10-19 19:15:40.793 [info] <0.26035.663>@ejabberd_sm_redis:delete_session:87 Delete session for user <<"tsaqovanbasten">> server <<"host">>, resource <<"resource-582546bfdfa6b5e5">>, sid {{1476,904527,119370},<0.26035.663>}

This looks wrong in a different way: The second call is coming from a different Erlang process (`<0.26035.663>`).  Otherwise, it should be impossible a new `ejabberd_c2s` process to use the same resource string (`resource-582546bfdfa6b5e5`) before the old session was closed.

> We understand our solution is just temporary.

And you can easily run into other issues if the session table contents are incorrect.

**Comment by weiss** [comment]
> But the `ejabberd_c2s` process will only receive messages from `ejabberd_sm once the ejabberd_c2s` PID was added to the session table. How would ejabberd_sm look up the destination PID before that happened?

Ah sorry, the PID might've been added, but `ejabberd_sm:get_user_present_resources/2` won't return it until presence was sent.
