### ISSUE TITLE
unable to connect to mysql, greeting badmatch

### ISSUE THREAD

**Issue by jianjyan** [processone/ejabberd#1357]
> What version of ejabberd are you using?

ejabberd 16.09

> What operating system (version) are you using?

centos 6.8， otp18.1
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64)

> How did you install ejabberd (source, package, distribution)?

from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

expect: connect to mysql
unexpect: unable to connect

log:

```
02:30:11.703 [error] Error in process <0.400.0> on node ejabberd@localhost with exit value:
  {{badmatch,<<>>},[{p1_mysql_conn,greeting,2,[{file,"src/p1_mysql_conn.erl"},{line,440}]},
  {p1_mysql_conn,mysql_init,5,[{file,"src/p1_mysql_conn.erl"},{line,400}]},
  {p1_mysql_conn,init,7,[{file,"src/p1_mysql_conn.erl"},{line,301}]}]}
```

customized log:

```
p1_mysql_conn, greeting Protocol 255, Rest <<105,4,72,111,115,116,32,39,116,
                                             101,108,97,45,116,117,114,110,115,
                                             101,114,118,101,114,39,32,105,115,
                                             32,98,108,111,99,107,101,100,32,
                                             98,101,99,97,117,115,101,32,111,
                                             102,32,109,97,110,121,32,99,111,
                                             110,110,101,99,116,105,111,110,32,
                                             101,114,114,111,114,115,59,32,117,
                                             110,98,108,111,99,107,32,119,105,
                                             116,104,32,39,109,121,115,113,108,
                                             97,100,109,105,110,32,102,108,117,
                                             115,104,45,104,111,115,116,115,39>>
p1_mysql_conn, greeting Version [105,4,72,111,115,116,32,39,116,101,108,97,45,
                                 116,117,114,110,115,101,114,118,101,114,39,
                                 32,105,115,32,98,108,111,99,107,101,100,32,
                                 98,101,99,97,117,115,101,32,111,102,32,109,
                                 97,110,121,32,99,111,110,110,101,99,116,105,
                                 111,110,32,101,114,114,111,114,115,59,32,117,
                                 110,98,108,111,99,107,32,119,105,116,104,32,
                                 39,109,121,115,113,108,97,100,109,105,110,32,
                                 102,108,117,115,104,45,104,111,115,116,115,
                                 39], Rest2 <<>>
```

**Comment by jianjyan** [comment]
It works in centos6.6;
Btw, I have customized my data table in db, and the sql execution returns: 

 08:05:31.778 [error] Error while processing SQL query result: {error,function_clause,[{sql_queries,'-get_user/2-fun-1-',[[<<"13388196473">>,<<"0">>,<<"blackjack">>]]

**Comment by jianjyan** [comment]
I have commented the code block:
sql_query_format_res({selected, _, Rows}, SQLQuery) ->
   % Res =
        %lists:flatmap(
          %fun(Row) ->
                  %try
                     % [(SQLQuery#sql_query.format_res)(Row)]
                  %catch
                      %Class:Reason ->
                          % ST = erlang:get_stacktrace(),
                         % ?ERROR_MSG("Error while processing "
                               %      "SQL query result: ~p~n"
                            %         "row: ~p",
                         %            [{Class, Reason, ST}, Row]),
                      %    []
                 % end
          %end, Rows),
    %{selected, Res};
{selected, Rows};


and it works normally,  I've no idea why this code issues error..

**Comment by cromain** [comment]
do you still have this issue with 17.07 ?
