### ISSUE TITLE
Which is the best way to add metadata to messages?

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1362]
Hi,

We're exploring some different ways to add metadata to our messages. In our case, we're talking about, for example, adding reactions to the messages, such as likes or unlikes. Let's say, in a muc room where anyone can add a like or an unlike to any message.

The implementation of this feature implies some tasks such as:

-  Communication to add/delete a new reaction
-  Communication to retrieve/get the reactions of a message
-  Mechanism to persist the metadata related with a message

What you consider a good way to implement this feature in Ejabberd and in the XMPP framework?

Any idea, suggestion or advice will be welcome.

Thanks a lot!

**Comment by zinid** [comment]
Do you want to attach metadata to internal ejabberd representation of packets (`#xmlel{}` structure) or want to send this metadata inside XML messages in an XML stream?

**Comment by zinid** [comment]
I close this as there is no response from the reporter.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:51404 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cMZ7L-0006ZX-Lr
	for zero@thezeroworld.com; Thu, 29 Dec 2016 06:43:32 -0500
Date: Thu, 29 Dec 2016 03:42:51 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1483011771;
	bh=y+RCUYJSUVV3p84o2AU8rkTuav3ZBVWQjtRktnpeiH4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=X3k/Wsr3YRSkkUKZIxkLiLK6GIv1thet+m10LlbqOeGBIPfVHDDX/XYo8RZibCbFc
	 8v9RYQ9gCUU9T/3DRYmMTDDht7bBnff18UqK6BbSjWFieLltuZvIXkUNoswINHZvai
	 wAfMjqOH7VZ8wq3giu0kmr1WrsjdLEKCB3wRMxsg=

**Comment by BesatZardosht** [comment]
I have almost same problem! I used metadata for my messages all over the place but from ejabberd 16.12 all of them are being removed from message xml by ejabberd. Is there any way to prevent ejabberd from removing them and preserve the whole xml?

for example I have sth like:

`<message type='chat' to='user2@host.com' from='user1@host.com' id='some_id' myAttribute='some value here'/>
`
but user2 gets:

`<message type='chat' to='user2@host.com' from='user1@host.com' id='some_id' />
`
I would appreciate any help.

**Comment by zinid** [comment]
No, there is no way.
Actually, adding foreign attribute inside `<message/>` violates the RFC schema. And new ejabberd code is designed to keep these rules in mind.
