### ISSUE TITLE
Add 16.09 to Hex

### ISSUE THREAD

**Issue by safwank** [processone/ejabberd#1363]
Hi,

16.09 has been out for awhile now, but apparently not on hex.pm. Is there a specific reason why this is the case? If not, can someone please publish it?

Thanks heaps.

**Comment by safwank** [comment]
Bueller?

**Comment by mremond** [comment]
No reason. We just need to find the time to package and test for hex.pm. It is usually lengthy process and we need to find a moment to do it.

**Comment by safwank** [comment]
@mremond No worries. Let me know how I can help.

**Comment by mremond** [comment]
@safwank It is now up to date:
https://hex.pm/packages/ejabberd
