### ISSUE TITLE
OCSP Stapling

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1364]
It would be nice if ejabberd would support OCSP Stapling. Nowadays there is even a [way to force this stapling](https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/) via special certificates, but for this to work you should support OCSP Stapling.
OCSP Stapling is very much recommend and is going to be the default in the web today.

**Comment by zinid** [comment]
We have this in ebe (commercial version of ejabberd), I'm not sure if the featrue is supposed to be ported to open source version.

BTW, in the meantime Google is getting rid of OCSP support in Chrome :)

**Comment by rugk** [comment]
> BTW, in the meantime Google is getting rid of OCSP support in Chrome :)

OCSP is different to [OCSP Stapling](https://en.wikipedia.org/wiki/OCSP_stapling). AFAIK "OCSP Stapling" is still used by Chrome if supplied.

In any way this is really a basic feature of TLS, so I'd highly suggest to make this available in the open source version. All web bigger web servers have it and for an XMPP server it would also be very useful.

**Comment by zinid** [comment]
OK, my bad, commercial version has pure "OCSP" support, i.e. it has PKIX client authentication support with OCSP/CRL validation.
OCSP Stapling looks like much better way to validate at least server certificates.

**Comment by rugk** [comment]
> OCSP Stapling looks like much better way to validate at least server certificates.

It is also a much better solution concerning privacy (as the CA does not have to be contacted) and it is faster too.

**Comment by strugee** [comment]
I'm interested in working on this. My guess is that the change to fix this should be introduced in fast_tls, right?

**Comment by zinid** [comment]
I don't know. Maybe in `fast_tls`, maybe in [xmpp_stream_pkix](https://github.com/processone/ejabberd/blob/master/src/xmpp_stream_pkix.erl), depending on complexity.
