### ISSUE TITLE
Please remove the MD5 from website

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1365]
[Here](https://www.process-one.net/en/docs/verifying_process_one_downloads_integrity/) you document how to use your MD5 hashes for "verifying" the downloaded files.

However please search for "md5" with your favourite search engine and you'll see that this is broken for years! Nowadays it's trivial to fake an MD5 hash.
Currently even SHA-1 hashes are depreciated, so please either publish SHA-256 hashes (and hash files) for your downloads and change the documentation or just remove the hash verification and recommend gpg.

**Comment by zinid** [comment]
The best price of SHA-1 collision-attack is considered around 75-120 **thousands** of dollars. Who the hell in the world would attack ejabberd download files for this price?

**Comment by rugk** [comment]
Processing power is rising. The world  [is depreciating SHA-1](https://konklone.com/post/why-google-is-hurrying-the-web-to-kill-sha-1) and here I am quoting the linked article:
> In 2005, cryptographers proved that SHA-1 could be cracked 2,000 times faster than predicted. It would still be hard and expensive — but since computers always get faster and cheaper, it was time for the internet to stop using SHA-1.

>Then the internet just kept using SHA-1. In 2012, Jesse Walker wrote an estimate, reprinted by Bruce Schneier, of the cost to forge a SHA-1 certificate. The estimate uses Amazon Web Services pricing and Moore's Law as a baseline.

>Walker's estimate suggested then that a SHA-1 collision would cost $2M in 2012, $700K in 2015, $173K in 2018, and $43K in 2021. Based on these numbers, Schneier suggested that an "organized crime syndicate" would be able to forge a certificate in 2018, and that a university could do it in 2021.

The article is of course about the use of SHA-1 in TLS certificates, but the issues of SHA-1 are still valid. The issue is not that it is broken right now, but given the rapid development in processing power it will be soon.

> Who the hell in the world would attack ejabberd download files for this price?

This really does not matter. The price is realistic, it has been done in similar cases (see the article) for ssl/tls certs and nation states have much money for this.

In any case there is no need to argue about the security of SHA-1 when you currently use MD5, which is way worse. And I have nothing against additionally publishing SHA-1 hashes, but to be ready for the future you should certainly publish SHA-256 hashes (too) and using/recommending them by-default.
At least all quite up-to-date systems nowadays have `sha256sum` available so there is no argument against not using SHA-256 instead of SHA-1.

**Comment by zinid** [comment]
> This really does not matter. The price is realistic

This does matter, because at the moment the price is not realistic.

**Comment by rugk** [comment]
Come on, just publish the hashes. *At least* SHA-1 and everything is fine.

**Comment by cromain** [comment]
use SHA256 instead of MD5 is no big deal. I think we can schedule next release to use this

**Comment by cromain** [comment]
our release will be published with SHA256 instead of MD5 sum file. The web site will be updated accordingly at next release.
