### ISSUE TITLE
roomconfig_roomowners provide.

### ISSUE THREAD

**Issue by xiaoyulee** [processone/ejabberd#1369]
> What version of ejabberd are you using?

16.06

> What operating system (version) are you using?

Ubuntu 

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

unkown option "muc#roomconfig_roomowners"

**Comment by badlop** [comment]
When do you get the error? How can I reproduce the problem? How do configure ejabberd?

**Comment by zinid** [comment]
This is a stupidity in the XEP-0045. This field is mentioned in the xdata spec, but it's not said that we're obligated to support it.
Also, you can always get the affiliation list (including owners) via a special command.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:16576)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cMZ6P-0006R4-Rg
	for zero@thezeroworld.com; Thu, 29 Dec 2016 06:42:34 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=hGuYGnGnSOVSYIR4ONlo7mKV2lA=; b=kxe9FfF8IXsiZLGh
	kJldyrxjw9uRuFkC+ufClXOVirheJGgY6EVbpZHXUBay9Jt7jerrO1Vo7NmTF/Hw
	DQuuITR8l8RtCCzZGqayNBxUn6rlgmfuABg+szsNoDR8xjlfTGAMLB2cyEa19jsD
	6sOA6hX2iI4OPFw2FY8chmUQ3kg=
Received: by filter0535p1mdw1.sendgrid.net with SMTP id filter0535p1mdw1-30376-5864F674-2
        2016-12-29 11:41:40.105672483 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id T3ybgILpQ9-ZR8uWAAhdqA
	for <zero@thezeroworld.com>; Thu, 29 Dec 2016 11:41:40.136 +0000 (UTC)
Date: Thu, 29 Dec 2016 03:41:40 -0800
