### ISSUE TITLE
Compilation: By default paths begin with two /

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1370]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected?

By default (with no parameters affecting this) all paths (e.g. [here](https://github.com/processone/ejabberd/blob/master/ejabberd.init.template#L19)) begin with two slashes: In my example `DIR=//sbin`.

> What was the unexpected behavior? What was the expected result?

One slash is enough. It looks better, at least. :smiley:

**Comment by rugk** [comment]
ALos BTW as a side note as it is not worth a new issue: On https://docs.ejabberd.im/admin/configuration/ the "Firewall Settings" (https://docs.ejabberd.im/admin/security/#firewall-settings) results in a 404.

**Comment by zinid** [comment]
@rugk for such minor/cosmetic stuff PRs are highly welcome. You don't need to be Erlang guru for this :)

**Comment by badlop** [comment]
Ok, I'm trying to fix the 404 links.

**Comment by cromain** [comment]
1/ fixed by setting AC_PREFIX_DEFAULT(/usr/local) in configure.ac (00c613b3)
2/ 404 link fixed in doc repos, will be propagated at next doc update.
