### ISSUE TITLE
Store muc room and muc registered in Mysql database

### ISSUE THREAD

**Issue by gopalfinoit** [processone/ejabberd#1372]
> What version of ejabberd are you using? 

2.1.11

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

Package
Using command: apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Everything is working fine. I have used mysql database and i want to store modules of ejabberd in mysql database. Currently, Every tables are stored in ejabberd default database(mnesia). I have configured the ejabberd configuration file and added "default_db: sql" but still every modules are stored in mnesia instead of mysql. So please tell me how can i store the modules(muc_room, muc_registered) in mysql database

**Comment by badlop** [comment]
You installed ejabberd 2.1.11, so you must refer to its specific Guide, not using the most recent documentation because that one is focused in the most recent ejabberd.

According to your documentation, you should use a mod_muc option like this: {db_type, odbc}

**Comment by gopalfinoit** [comment]
yes i used that in ejabberd configuration file(ejabberd.cfg). Below is the configuration of mod_muc module:

     {mod_muc,  [
                  {host, "conference.@HOST@"},
                  {db_type, odbc},
                  {access, muc},
                  {access_create, muc},
                  {access_persistent, muc},
                  {access_admin, muc_admin},
                  {max_users, 500}
                 ]
     }

But still it is not storing the modules muc_room in mysql database.

**Comment by badlop** [comment]
That's weird.

Confirm that config file is the one used by ejabberd, and that the options you provide there are used by the module. For example, in the 'host' option, instead of "conference." put "confis". Then start ejabberd. Does this change take effect, or is the service still called with the old name?

Also check in the ejabberd log files when ejabberd is starting, and when a new room is created, maybe it shows some relevant error message.
