### ISSUE TITLE
16.09 installation failed on Windows 2012 R2

### ISSUE THREAD

**Issue by ashum81** [processone/ejabberd#1373]
The same bug like https://github.com/processone/ejabberd/issues/1128

Installing Visual C++ Redistributable Packages for Visual Studio 2013 before running eJabberd installer solved the problem.

**Comment by cromain** [comment]
odd, i'll try to check for next release

**Comment by cromain** [comment]
indeed, ejabberd needs msvcr120.dll, and mscvr100.dll was included. This will be fixed by next release

**Comment by cromain** [comment]
replacement of dll tested successfully on system without Visual C++ Redistributable Packages installed
