### ISSUE TITLE
certfile seems to be opened with write mode

### ISSUE THREAD

**Issue by bowlofeggs** [processone/ejabberd#1375]
> What version of ejabberd are you using?

ejabberd-16.08-2.fc25.x86_64

> What operating system (version) are you using?

Fedora 25 (pre-release)

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hello! I am one of the ejabberd maintainers for Fedora, and I've been working on a mission to get it running with a restricted SELinux context. One of the AVC denials I'm seeing are due to ejabberd attempting to open my certfile with write mode:

```
type=AVC msg=audit(1478751171.862:648): avc:  denied  { write } for  pid=2989 comm="async_2" name="ejabberd.pem" dev="dm-1" ino=44546 scontext=system_u:system_r:rabbitmq_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file permissive=0
type=AVC msg=audit(1478751171.863:649): avc:  denied  { write } for  pid=2989 comm="async_2" name="ejabberd.pem" dev="dm-1" ino=44546 scontext=system_u:system_r:rabbitmq_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file permissive=0
```

I don't believe ejabbed should need to write the certfile, so I would like to request that we adjust ejabberd to open the file in read mode. However, it's not obvious to me why ejabberd is opening the file in write mode (and I'm an Erlang noob). In what is a completely wild guess, it might be related to:

https://github.com/processone/ejabberd/blob/16.08/src/ejabberd_listener.erl#L548

which calls into:

https://github.com/processone/ejabberd/blob/16.08/src/ejabberd_config.erl#L970-L980

Going further into my wild guessing game, is it perhaps trying to open the file in write mode just to see if it can, and then falling back to read? Or is the write open() happening somewhere else in the code?

Either way, I'm happy to make a pull request to get this file opened in a read-only fashion if someone would be willing to point me in the right direction!

**Comment by weiss** [comment]
> I don't believe ejabbed should need to write the certfile, so I would like to request that we adjust ejabberd to open the file in read mode.

The file contents are only accessed [via OpenSSL][1], so I don't think there's anything we can do about this.

[1]: https://github.com/processone/fast_tls/blob/1.0.7/c_src/fast_tls_drv.c#L644

**Comment by prefiks** [comment]
It doesn't look like pem files are opened with write flag from what i see. I see that they are only opened with O_RDONLY flag, but there is call to access(name, W_OK) (that i guess file:read_file_info does) that maybe trigger this?

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:35585)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1c4veq-0005fm-Gw
	for zero@thezeroworld.com; Thu, 10 Nov 2016 15:10:46 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=fHpAdGZKV3hFsfoC/k3mup2f0Ms=; b=wn7mJ2F5N5l4Do7d
	pGBFFvxmQXaReIk0l4/2d0YtPF9qUGw5RtqQo20mBA9Dq3ZXXlMAW+G7rlunZu28
	c395FGwVrYh57o3qHC/clHyQMQ45ud9KbTjSlha2zYNPuo3RvUlyT/yU0ufgypWk
	qLnQrwyzFEFQBNKm3sqDQXqmoaA=
Received: by filter0074p1las1.sendgrid.net with SMTP id filter0074p1las1-17301-5824C75C-3
        2016-11-10 19:15:40.12175361 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id aDzuxPAyQSmKEb2umsXP1Q
	for <zero@thezeroworld.com>; Thu, 10 Nov 2016 19:15:39.765 +0000 (UTC)
Date: Thu, 10 Nov 2016 11:15:39 -0800

**Comment by zinid** [comment]
@prefiks yes, this is a known problem in SELinux: http://www.spinics.net/lists/selinux/msg06180.html

**Comment by bowlofeggs** [comment]
For the record, this is the Fedora bug that is tracking the effort to run ejabberd in a constrained mode:

https://bugzilla.redhat.com/show_bug.cgi?id=1393649
