### ISSUE TITLE
NoNewPrivileges=true disallows ejabberd to start on systems with SELinux enforcing

### ISSUE THREAD

**Issue by bowlofeggs** [processone/ejabberd#1376]
> What version of ejabberd are you using?

ejabberd-16.08-2.fc25.x86_64

> What operating system (version) are you using?

Fedora 25 (pre-release)

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Fedora has been using a systemd unit file very similar to the [ejabberd.service.template](https://github.com/processone/ejabberd/blob/16.09/ejabberd.service.template) file provided in this repository. There is an [issue filed against systemd](https://github.com/systemd/systemd/issues/3845) since this wasn't clear in its documentation that reports that ```NoNewPrivileges=true``` will lead to denials upon the process attempting to alter its context:

```
type=SELINUX_ERR msg=audit(1478750215.370:619): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:rabbitmq_t:s0
```

For now, I recommend dropping the ```NoNewPrivileges=true``` line from the unit file. I decided to file an issue instead of a pull request in case discussion was warranted first.

This downstream issue tracks this problem in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1393587

**Comment by weiss** [comment]
> For now, I recommend dropping the `NoNewPrivileges=true` line from the unit file.

Agreed.  This is done in PR #1346 for other reasons as well.
