### ISSUE TITLE
Option to only log ip for "access denied"

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1377]
That you can strip the IP from the log files is nice, however I'd still like to log the ip if the access fails (& only in this case!), because of an authentication failure as this could then be processed by fail2ban, which may then enforce stricter restrictions to the ip than ejabberd is possible to do.

**Comment by badlop** [comment]
You can already acomplish that by logging IPs, then filtering by the keywords "Failed legacy authentication":
```
12:47:14.702 [info] ({socket_state,gen_tcp,#Port<0.21886>,<0.675.0>})
 Accepted legacy authentication for user1@localhost/tka1 by ejabberd_auth_mnesia from 127.0.0.1
12:47:20.759 [info] ({socket_state,gen_tcp,#Port<0.21886>,<0.675.0>})
 Close session for user1@localhost/tka1
12:47:24.320 [info] (#Port<0.21887>)
 Accepted connection 127.0.0.1:44163 -> 127.0.0.1:5222
12:47:24.453 [info] ({socket_state,gen_tcp,#Port<0.21887>,<0.678.0>})
 Failed legacy authentication for user1ssss@localhost/tka1 from 127.0.0.1
```

**Comment by rugk** [comment]
And how can I setup this filtering in ejabberd?

**Comment by badlop** [comment]
ejabberd doesn't implement such a thing. You can simply write a script that filters your latest log files for that sentence every night, adds banning lines to your config file, and reloads it.

**Comment by rugk** [comment]
And that's kinda complicated. That's why I am requesting an inclusion for this feature (without auto-banning, just only logging "Failed […] authentication") in ejabberd. The banning could then easily be made with fail2ban.

**Comment by badlop** [comment]
Ok, then you can apply this patch:
```
diff --git a/src/mod_fail2ban.erl b/src/mod_fail2ban.erl
index cc3b4bf..8ba81dd 100644
--- a/src/mod_fail2ban.erl
+++ b/src/mod_fail2ban.erl
@@ -54,6 +54,10 @@ start_link(Host, Opts) ->
 
 -spec c2s_auth_result(boolean(), binary(), binary(),
 		      {inet:ip_address(), non_neg_integer()}) -> ok.
+c2s_auth_result(false, User, LServer, {Addr, Port}) ->
+    ?INFO_MSG("Failed to login ~s@~s from ~s:~p",
+	[User, LServer, jlib:ip_to_list(Addr), Port]),
+    ok;
 c2s_auth_result(false, _User, LServer, {Addr, _Port}) ->
     case is_whitelisted(LServer, Addr) of
 	true ->
```
Then enable the module. Even if you configure to hide sensitive data, those IPs will be logged.
