### ISSUE TITLE
Init file is likely to use root

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1378]
WTF is ejabberd running as root?

![ejabberdroot](https://cloud.githubusercontent.com/assets/11966684/20192753/88419e9a-a78b-11e6-9464-20334a88206b.png)

[REMOVED]

**Comment by rugk** [comment]
Actually I see that running as root is not intended and [this line](https://github.com/processone/ejabberd/blob/master/ejabberd.init.template#L21) might be the issue. When doing `sudo make install` the "installuser" just is usually root...

**Comment by rugk** [comment]
Yes, I could just confirm this behaviour...

I mean the user who is later running ejabberd should really not have access to the file system in a way that is needed for `sudo make install`. Therefore the user there should be changed.

**Comment by weiss** [comment]
You can specify the user that should execute ejabberd via `./configure --enable-user=$USER`, or simply `./configure --enable-user` (which defaults to the user running `./configure`).

Distributions that build ejabberd packages take care of these things.

**Comment by rugk** [comment]
In this case however, you should put a big warning in the installation doc stating that this parameter should be given as otherwise ejabberd may be executed as root.

Additionally you may prevent the execution of ejabberd as root in general and let it exit with an error message or at least write this error to the log.

**Comment by weiss** [comment]
> you should put a big warning in the installation doc

Feel free to [submit a PR][1].

But your alarmist tone sounds a little misguided to me.  Building from source is something developers do.  Admins who can't cope with these things should *really* use a distribution package instead.

Apart from that, the vast majority of Linux admins will start ejabberd via systemd these days, and the [example unit file][2] we provide sets `User=ejabberd`.

[1]: https://github.com/processone/docs.ejabberd.im/compare
[2]: https://github.com/processone/ejabberd/blob/16.09/ejabberd.service.template

**Comment by andreabenini** [comment]
I'm a linux sysadmin and I've compiled (or installed from binary package) a v16.06 on CentOS machines with or without systemd but mine is not running as root. I've simply created an ejabberd user and when the daemon is started from the init (whatever it is) is owned by my user

```
32125 ejabberd  20   0  798m  93m 5604 S  0.0  9.4   8:54.53 beam.smp        
14245 ejabberd  20   0  563m  21m 2968 S  0.0  2.2   0:06.27 beam.smp        
31092 ejabberd  20   0  564m  21m 2960 S  0.0  2.2   0:08.39 beam.smp        
16241 ejabberd  20   0  564m  20m 2972 S  0.0  2.0   0:06.58 beam.smp        
 1028 ejabberd  20   0  564m  19m 2968 S  0.0  2.0   0:38.87 beam.smp        
```

take a look at the ejabberctl file: I also have something like `INSTALLUSER=ejabberd` on it as you can see from my top results above.

**Comment by rugk** [comment]
Yes, I know how to got it working. The doc was just incomplete. See my PR at https://github.com/processone/docs.ejabberd.im/issues/22.
