### ISSUE TITLE
MUC: presence_broadcast option is not well recorded?

### ISSUE THREAD

**Issue by Kaggggggga** [processone/ejabberd#1380]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian 8.4

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hello,  it seems the presence_broadcast room option is not well record
Here is what I tried, 
1) in ejabberd.yml, I set the default room option with empty presence_broadcast 
2) after i create room, i can find the presence_broadcast option is set empty as expected
presence_broadcast      []
3) then I use command line to call change_room_option, on an option(e.g.  persistent true)
4) in command line, I call get_room_options and find it work as expected, while in database, I saw the options are replaced with many options neither set by default room option nor what I updated via command line.
5) More importantly, I find presence_broadcast  is missing in the database record now.
6) After I restart ejabberd, and I call get_room_options again, and found that presence_broadcast  is no longer empty now. 
presence_broadcast      [moderator,participant,visitor]

Wish to know how to fix the issue, thanks!

Btw, I wonder if it is possible to show me an example to call change_room_option with command line and http_api? The example [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/](url) here talked about updating with simple value, but seems not work with list value for presence_broadcast  here.

Thanks again!

**Comment by badlop** [comment]
I think it's a small bug, and this should fix it:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index ac2f5da..265f273 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -4429,6 +4429,7 @@ make_opts(StateData) ->
      ?MAKE_CONFIG_OPT(logging), ?MAKE_CONFIG_OPT(max_users),
      ?MAKE_CONFIG_OPT(allow_voice_requests),
      ?MAKE_CONFIG_OPT(mam),
+     ?MAKE_CONFIG_OPT(presence_broadcast),
      ?MAKE_CONFIG_OPT(voice_request_min_interval),
      ?MAKE_CONFIG_OPT(vcard),
      {captcha_whitelist,
```
Regarding setting presence_broadcast option with ejabberdctl or other frontends that use it (like mod_rest), I guess it isn't possible. You would have to use an XMLRPC client that queries ejabberd_xmlrpc.

**Comment by Kaggggggga** [comment]
Thanks for the fix!
