### ISSUE TITLE
When I run sleekxmpp API and then restart my frappe bench after that my server is not accepting any client request

### ISSUE THREAD

**Issue by waghangad** [processone/ejabberd#1381]
> What version of ejabberd are you using?

ejabberd 2.0.1

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

pip install ejabberd

> What did not work as expected? Are there error messages in the log? What

client prematurely closed connection, so upstream connection is closed too while sending request to upstream (in nginx log)

> was the unexpected behavior? What was the expected result?

after bench restart API should work fine

**Comment by badlop** [comment]
> after that my server is not accepting any client request

Oh, maybe the ejabberd_c2s listener got closed, or crashed? Check the ejabberd log files for any relevant error reports.

> ejabberd 2.0.1

You can try with a newer version.

**Comment by waghangad** [comment]
I solved It

import sys
import logging
import getpass
from optparse import OptionParser
import frappe
from frappe import _
import sleekxmpp

class CreateMucRoom(sleekxmpp.ClientXMPP):
def init(self, jid, password, roomName):
sleekxmpp.ClientXMPP.init(self, jid, password)
self.roomName= roomName
self.add_event_handler("session_start", self.start)

def start(self, event):
    self.send_presence()
    self.get_roster()
    self.plugin['xep_0045'].joinMUC(self.roomName,'test')
self.plugin['xep_0045'].setAffiliation(self.roomName,jid,affiliation='owner')
    self.disconnect(wait=True)
@frappe.whitelist(allow_guest=True)
def createMucRoom():
roomName = 'testroom@conference.hostname'
xmpp = CreateMucRoom(admin, password, roomName)
xmpp.register_plugin('xep_0030')
xmpp.register_plugin('xep_0199')
xmpp.register_plugin('xep_0045')
xmpp.connect()
xmpp.process(block=True)

frappe.msgprint(_("Created Muc Room "+roomName))
return roomName
