### ISSUE TITLE
muc_history how does it works ?

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1383]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

CentOS 6.8 amd64

> How did you install ejabberd (source, package, distribution)?

distribution binary install

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to configure history size for MUCs but I'm getting some troubles.
I have added the param:
> history_size: 200

in my conf/ejabberd.yml file, its properly indented and it seems there's nothing wrong during daemon startup. I'm using PostgreSQL as database backend for my domains and I have applied the proper sql for creating my schema.

After looking around for a while I have seen in the db there're these two tables related to MUCs: muc_room, muc_registered. There isn't a table named muc_history there, is it normal or what ? where are muc history messages stored ? I guess I'm missing a table or looking at the wrong doc

Thanks

**Comment by andreabenini** [comment]
Messages (even from groupchat) are stored in 'archive' table, I guess I'm referring to old docs , is it the right table to look at ? are there any APIs/funcs to use to get message from there ?

**Comment by badlop** [comment]
First of all, recent room history is temporary, and stored in the machine RAM memory only. It gets destroyed when the server restarts. Old messages are forgotten when new messages are received (that's the size you increase). This is implemented by mod_muc_room.erl and follows http://xmpp.org/extensions/xep-0045.html#enter-history

On the other hand, mod_mam can store persistently user messages, and also room messages. In this case, they are stored in Mnesia table archive_msg, or in SQL table archive, as you noticed. This is implemented by mod_mam.erl and follows http://xmpp.org/extensions/xep-0313.html#sect-idp1643408

**Comment by andreabenini** [comment]
Thanks badlop,
I was referring to <a href="https://docs.ejabberd.im/developer/sql-schema/#toc_10">this doc</a> but then I have seen "archive" table in my db. I have mod_mam enabled and running, I'd like to retrieve chatroom messages from it and consume them in my own custom module. How can I do it ?

**Comment by badlop** [comment]
Ahh, I wasn't aware of that table. In fact it is nowhere in ejabberd source code. It was developed for ejabberd Business Edition, and its documentation got copied to the main ejabberd documentation, which is incorrect. Anyway, as you can see in the feature description, it only stores room history when the server is stopping, so it isn't updated everytime, only on server stop, and it doesn't help you.

Try mod_mam, which can store room history persistently.

**Comment by andreabenini** [comment]
Thanks again badlop, but my main question is still there.
I'm now using mod_mam and I'm successfully storing messages in the database. 
I'd like to write a module to read these data already stored with mod_mam. How can I retrieve chatroom messages from db with an erlang module ? what kind of APIs, functions or source code I should use to get for example latest history from a chatroom ? I'm in a module and I can't enter the room (as a user) to get info from there..

Thanks again.
Ben

**Comment by andreabenini** [comment]
Thanks a lot again Badlop,
I have been quiet for a while because I have spent a lot of time and days on your hints reported from this issue/topic and from your kind reply in the support forum, in <a href="https://www.ejabberd.im/forum/28603/retrieve-chat-room-history-module">this link</a>, they were both very helpful. I have solved by not using them ! (just kidding...). I have found a solution without altering the source code. As you noted select_and_send/x is the key point and select/5/6/8 (depending on various ejabberd versions) does the dirty job for us. 
While reading the source code I have detected the inner module (mod_mam_*) used for accessing the database (variable Mod), as mod_mam select/x does to get something like Mod:select(LServer, From, To, ...), Mod might be mod_mam_mnesia or mod_mam_sql for example. Later on I have used the internal select/x in my specific module, mod_mam_sql in my case. ejabberd debug mode is very helpful because I can see the generated SQL statements in the log so I can decide what should I write in every single parameter.
The only problem of this approach might be to keep my source code up to date with the official tree because I have seen a lot of modifications (even in these latest releases) of the select, most changes are related to different parameters or  tuples passed to these functions.
I have also linked the forum issue to this topic as well.

If someone else wants additional details I'm glad to share them to the community
Thanks again from a now happy user

Ben

**Comment by stevenlivz** [comment]
@andreabenini Ben, if you have a gist somewhere i'd be keen to see it. I'm not having to do this quite yet but i may be on the cards in a few weeks and i'd like to think about what may need done. tia.

**Comment by andreabenini** [comment]
@stevenlivz I have spent a lot of hours on it and I guess it could be nice to avoid wasting time twice, it's nice to share code and the next time someone else could help me as well. My first effort was to get the latest message from a chatroom in a module of mine (so I'm not acting as an user) and I don't want to manually patch the source tree, please also note I'm now using v16.04, things has changed with current version, select/8 is now a select/6 so you might need to adapt something if you're running the latest stable.

```erlang
getLatestMessage(RoomName, Domain, ModuleName) ->
    ConferenceHost = <<"conference.", Domain/binary>>,
    RoomJID = #jid{luser=RoomName, user=RoomName, lserver=ConferenceHost, server=ConferenceHost},
    With    = none,
    RSM     = #rsm_in{max=1, direction=before, id=1},
    Type    = {groupchat, moderator, #state{config = #config{anonymous = false}} },        %% group chat
    case ModuleName:select(
                Domain,             %% XMPP Domain / Host
                from,               %% From
                RoomJID,            %% To
                0,                  %% Start (0 = no start).
                0,                  %% End   (0 = no end).
                With,               %% With (or none)
                RSM,                %% RSM   (messages or atom none)
                Type                %% MsgType
            ) of
        {[],true,0} ->              %% NOT FOUND
            ?INFO_MSG("Room ~s@~s not found (ModuleName=~p, RoomJID=~p, With=~p, RSM=~p, Type=~p)",
                         [RoomName, Domain, ModuleName, RoomJID, With, RSM, Type]),
            notfound;
        Message     ->              %% Got it !
            ?INFO_MSG("     Message = ~p", [Message]),
            Message
    end.
```
So: special attention on SELECT/8 (in my case), check it out in your source tree, I have seen a different select in the current stable tree. If you'd like to improve/adapt the code for future release you may try to detect which select() function you need (try..catch block ? maybe)
Where does `ModuleName` comes from ? I have got this idea from [(here)](https://github.com/processone/ejabberd/blob/0f11b1be364e43189e06eeb577750e7d1b0e9fef/src/mod_mam.erl#L778). When you call mod_mam the inner working inside select_and_send/x calls this one and detect what kind of module you're using underneath, in my case it goes through mod_mam_sql.erl because I'm not using mnesia for storing logs. @badlop really rocks, with his hints here and in [the forum](https://www.ejabberd.im/forum/28603/retrieve-chat-room-history-module) I have figured out what should be done.
`ModuleName` is calculated in my code somewhere else to detect the right module to call.
`Type` is focused on chatroom and not on single chat messages, change it accordingly
`RSM` is tailored on getting just the latest msg from the chatroom, you may need to customize it as well

Hope it helps
