### ISSUE TITLE
Flooding Ejabberd with None priority sessions

### ISSUE THREAD

**Issue by encodeltd** [processone/ejabberd#1387]
> What version of ejabberd are you using?

The issue is observed since 15.07, still present in 16.09.

> What operating system (version) are you using?

Linux - Debian Wheezy/Jessie

> How did you install ejabberd (source, package, distribution)?

From source.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In summary:

It is possible to create sessions with priority `None` via WebSocket.

Example:

```
{'sessions':
 [{'jid': 'example@example.com/mc-example'},
  {'connection': 'websocket'},
  {'ip': 'xxx.xxx.xxx.xxx'},
  {'port': xxxxx},
  {'priority': None},
  {'node': 'ejabberd@example.com'},
  {'uptime': xxxxxx}]}
```
I assume the `None` priority is related to a process crash before sessions have their priority assigned.

These sessions stay in the session list and make things like `connected_users_number` incorrect.
Once these sessions grow in number, Ejabberd becomes unresponsive and reboot is required.

The only way to keep things tidy is to use `kick_session` to get rid of these sessions on a regular basis.

I am pretty sure that the issue originates in the WebSocket client that connects to our Ejabberd server.
Nonetheless, the fact that it is possible to create `None` priority sessions should be addressed in Ejabberd.

Here is a log snippet which I think relates to this issue:
```
2016-11-21 XX:XX:XX.XXX [error] <X.XXXXX.XXXX> gen_fsm <X.XXXXX.XXXX>
 in state wait_for_feature_request terminated with reason: no function clause matching
 ejabberd_c2s:wait_for_feature_request({xmlstreamstart,<<"stream:stream">>,
[{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},...]},
 {state,{socket_state,ejabberd_http_ws,{http_ws,<X.XXXXX.XXXX>,
  {{XXX,XXX,XXX,XXX},XXXXX}},<X.XXXXX.XXXX>},...}) line 775

2016-11-21 XX:XX:XX.XXX [error] <X.XXXXX.XXXX>
 CRASH REPORT Process <X.XXXXX.XXXX> with 0 neighbours exited with reason:
 no function clause matching ejabberd_c2s:wait_for_feature_request(
{xmlstreamstart,<<"stream:stream">>,[{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},...]},
 {state,{socket_state,ejabberd_http_ws,{http_ws,<X.XXXXX.XXXX>,{{XXX,XXX,XXX,XXX},XXXXX}},
<X.XXXXX.XXXX>},...}) line 775 in p1_fsm:terminate/8 line 760
```

**Comment by encodeltd** [comment]
Further information from me.

I successfully replicated the issue that is causing those errors.

The errors don't seem to be directly related to the `None` priority sessions.

To cause the errors, I sent another (ie. two in a row) `<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="example.com" version="1.0"/>` after receiving `<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>` after the authentication.

This throws the following errors in Ejabberd:

> XXXX-XX-XX XX:XX:XX.XXX [error] <X.XXXXX.X> gen_fsm <X.XXXXX.X> in state wait_for_bind terminated with reason: no function clause matching ejabberd_cXs:wait_for_bind({xmlstreamstart,<<"stream:stream">>,[{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},...]}, {state,{socket_state,ejabberd_http_ws,{http_ws,<X.XXXXX.X>,{{XXX,XXX,XXXX,XXX},XXXXX}},<X.XXXXX.X>},...}) line XXXX
> XXXX-XX-XX XX:XX:XX.XXX [error] <X.XXXXX.X> CRASH REPORT Process <X.XXXXX.X> with X neighbours exited with reason: no function clause matching ejabberd_cXs:wait_for_bind({xmlstreamstart,<<"stream:stream">>,[{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},...]}, {state,{socket_state,ejabberd_http_ws,{http_ws,<X.XXXXX.X>,{{XXX,XX,XXX,XXX},XXXXX}},<X.XXXXX.X>},...}) line XXXX in pX_fsm:terminate/X line XXX

PS: I am still looking for the cause of the `None` priority sessions. I will follow up here when I have anything new.

**Comment by encodeltd** [comment]
I have now replicated the `None` priority case, too.

Sessions with `None`/`Nil`/`undefined` priority and `unavailable` status are created after

`<iq type='set' id='_bind_auth_2' xmlns='jabber:client'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>mc-test-resource</resource></bind></iq>`

frame is send in to the server and before

`<presence id='abc123' xmlns='jabber:client'><show>chat</show><status>chat</status>' from='test@example.com'/></presence>`

frame is send in to the server.

If I cut off the network connection to the server during that time and then stop the client, these sessions stay in this state on the server, until the network connection is established again. Once the connection is established again the sessions are removed the server.

**Comment by sepasti** [comment]
Hi, I have same problem.

user1@example.com/_98a7e26b47543187	c2s_compressed_tls	192.168.114.216	59877	nil	ejabberd@192-16-11-3	238804
user2@example.com/_5384e26707376e25	c2s_compressed_tls	192.168.114.208	15413	nil	ejabberd@192-16-11-2	340374
user3@example.com/_b8ca8a6cf1802bac	c2s_compressed_tls	192.168.114.229	14679	nil	ejabberd@192-16-11-5	232926
user4@example.com/_2c31b0498c63f11	c2s_compressed_tls	192.168.114.197	33751	nil	ejabberd@192-16-11-1	147817
user5@example.com/_66d15bf3a9ed6508	c2s_compressed_tls	192.168.114.213	26480	nil	ejabberd@192-16-11-3	346142

that's ejabberd bug. when user don't send first presence(priority presence) in connecting time, it's happend.

**Comment by Pouriya-Jahanbakhsh** [comment]
After sending first presence, this detail will change to priority 0-127.
But if you want to kill all connections with nil priority, you need to delete all sessions with priority=undefined in session table of mnesia database.

**Comment by prefiks** [comment]
I think this is now fixed
