### ISSUE TITLE
Custom Elements in MUC Presence

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1389]
Hi

We're implementing an xmpp client and we are using ejabberd as xmpp server. We've implemented muc (multi user chat) functionalities to our app and everything is working fine , only thing we are having problem is a member to leave the group permanently.

I know in XEP 45 says if you want to leave the group just send the unavailable presence to room but this doesnt work in our case because our admins add users of the group to memberList by sending the below xml:

```
<iq from='crone1@shakespeare.lit/desktop'
    id='member1'
    to='coven@chat.shakespeare.lit'
    type='set'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item affiliation='member'
          jid='hag66@shakespeare.lit'
          nick='thirdwitch'/>
  </query>
</iq>
```

So the members of the group can see the other members and moderators in group's member list(Like whatsapp)

When a user leaves the room it only sends unavailable presence to room , so this doesnt remove her/his from room's member list. I want to remove the user from members list when they leave the room(Leaving room is a specific button in our application like whatsapp)
For doing this , I would like to add an extension element to presence and when this element sent to server, ejabberd should remove the user from group's member list.
But I dont know how to do it with ejabberd. 
Is something like that possible ? If it is how?

Thanks

**Comment by badlop** [comment]
> When a user leaves the room it only sends unavailable presence to room , so this doesnt remove her/his from room's member list. I want to remove the user from members list when they leave the room

First apply this patch:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 5b00054..e96db0e 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -2855,6 +2855,9 @@ can_change_ra(owner, _FRole, admin, _TRole, affiliation,
 can_change_ra(owner, _FRole, owner, _TRole, affiliation,
 	      _Affiliation, _ServiceAf) ->
     check_owner;
+can_change_ra(member, participant, member,
+	      participant, affiliation, none, none) ->
+    true; % Allow a member that joined the room to de-member himself
 can_change_ra(_FAffiliation, _FRole, _TAffiliation,
 	      _TRole, affiliation, _Value, _ServiceAf) ->
     false;
```
Then a user that joined the room and is member, can send a query like this:
```
<iq type='set' to='sala1@conference.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item nick='user2' affiliation='none'/>
  </query>
</iq>
```
And finally, he can leave the room as usual.

**Comment by tolgatanriverdi** [comment]
So how can I understand the difference between a member leaving the room because he/she is becoming offline and a member actually want to abandon the room. Is this iq working for the person who actually wants to abandon the group?

```
<iq type='set' to='sala1@conference.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item nick='user2' affiliation='none'/>
  </query>
</iq>
```

**Comment by tolgatanriverdi** [comment]
also I'm using the binary install of ejabberd(not compiled from source code), is it possible to apply this patch to binary install or should I have to remove my ejabberd installation and reinstall from source code ?

**Comment by tolgatanriverdi** [comment]
I've tried something like that

```
1. Cloned the git source for 16.08 release(I'm using ejabberd 16.08) : git clone https://github.com/processone/ejabberd.git 16.08
2. Applied the patch that you suggested with: git apply participant.patch
3. Executed following commands:
    ./autogen.sh
    ./configure
    make

4. Then copied ebin/mod_muc_room.beam file to my already installed ejabberd folder (/opt/ejabberd-16.08/lib/ejabberd-16.08/ebin)

5. Restart the server
```


But when I do that MUC functionality didnt work on my clients so I' ve to roll back to previous configuration.
Did I miss something here?

**Comment by badlop** [comment]
Ah, you are right. That query is meant to be sent to the server by the client before leaving the room, so the user de-members itself. But that is manual, not automatic. So, when a client disconnects abruptly (or the connection gets closed), the room eventually kicks the user, but does not de-member it. In this sense, that isn't good enough for your initial requirement:
> I want to remove the user from members list when they leave the room

Regarding your procedure, it looks perfect. If the patch was correctly applied, and you copied the beam file to overwrite the old one that was used, then the feature should work.

**Comment by tolgatanriverdi** [comment]
So if the patch is right, I didnt understand why it doesnt allow me to send group chat messages any more
My client gives the below error:

```
2016-11-25 20:31:21.987813 Chat2B[6264:2391507] [MC] Reading from public effective user settings.
2016-11-25 20:31:23.780618 Chat2B[6264:2391507] [Common] _BSMachError: port af07; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2016-11-25 20:31:23.783038 Chat2B[6264:2391507] [Common] _BSMachError: port af07; (os/kern) invalid name (0xf) "Unable to deallocate send right"

```

**Comment by tolgatanriverdi** [comment]
any idea about the problem?

**Comment by tolgatanriverdi** [comment]
Ok I've figured out the problem. It seems I didnt checkout the 16.08 tag so the patch I modified was applied to 16.09 which is not my ejabberd version
Now the group chat works , however patch doesnt work. I've sent the below IQ and in result I received affiliation change is not allowed message (nick seems like jid but its same with jid in our system)

`<iq xmlns="jabber:client" from="526384980263@conference.chat.meeapps.com.tr" to="905326650263@chat.meeapps.com.tr/3437347497828855933256" id="0DFFC57D-EBC8-48DB-A555-A2F6B2CC382F" type="error"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="none" nick="905326650263@chat.xxxx.com.tr"/></query><error code="405" type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Changing role/affiliation is not allowed</text></error></iq>`

**Comment by tolgatanriverdi** [comment]
Ok I found the cause of this problem too. 

1. I cannot use this while I was the admin of the group (It works fine , when I was a member of that group)

2. As a member when I remove myself from memberlist , it doesnt send information to other receipants of the group

Can we find a solution to these problems

**Comment by badlop** [comment]
In my test, when an occupant de-members itself (thanks to the patch), other room occupants receive a presence stanza notifying the change.

**Comment by tolgatanriverdi** [comment]
Only the online members are receiving the presence stanza but the offline members are not receiving it.
Even though I'm subscribing the users to muc room to receive the presence info even they were offline
And also if an admin removes a member the presence info sent to all users even if they are offline, but the same message doesnt sent when a user de-member himself
I hope I can make my point clear

**Comment by badlop** [comment]
Another test: user1 created the room, user2 joins the room and gets membered, user3 subscribes to the room [1] and logouts. Then user2 de-members itself [2]. I see in user3's offline queue the stored message [3]. So, I can't still reproduce your problem.

BTW, during this testing I found a bug in 16.12-beta1 that crashed the user2 client, I guess it's unrelated to your problem as you are using a 16.09 or older without the library changes.

[1]
```
<iq to='sala1@conference.localhost'
    type='set' id='asd'>
  <subscribe xmlns='urn:xmpp:mucsub:0'
             nick='user3'>
    <event node='urn:xmpp:mucsub:nodes:messages' />
    <event node='urn:xmpp:mucsub:nodes:affiliations' />
    <event node='urn:xmpp:mucsub:nodes:subject' />
    <event node='urn:xmpp:mucsub:nodes:config' />
  </subscribe>
</iq>
```

[2]
```
<iq type='set' to='sala1@conference.localhost' id='1232312312'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item nick='user2' affiliation='none'/>
  </query>
</iq>
```

[3]
```
<message xmlns='jabber:client'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
    <items node='urn:xmpp:mucsub:nodes:affiliations'>
      <item id='5298320466258086097'>
        <presence xml:lang='es'
                  to='user3@localhost'
                  from='sala1@conference.localhost/user2'
                  id='247:333614'
                  xmlns='jabber:client'>
          <c xmlns='http://jabber.org/protocol/caps'
             hash='sha-1'
             node='http://tkabber.jabber.ru/'
             ver='/9geyFfPVOMWfNsMSIrP9BfFVkQ='/>
          <x xmlns='http://jabber.org/protocol/muc#user'>
            <item role='participant'
                  affiliation='none'/>
          </x>
          <show>dnd</show>
        </presence>
      </item>
    </items>
  </event>
</message>
```

**Comment by tolgatanriverdi** [comment]
Same test , doesnt work on me.
I'm using ejabberd-16.08 can it be related to that?

**Comment by tolgatanriverdi** [comment]
I've installed 16.12 beta 1 version and the result is still the same:

1. User-1 of the group de-member himself with using

```
<iq type='set' to='sala1@conference.localhost' id='1232312312'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item nick='user2' affiliation='none'/>
  </query>
</iq>
```


2. User-2 of the group never receives a message about the user-1 action

**Comment by tolgatanriverdi** [comment]
@badlop 
I've installed ejabberd 16.09 and ejabberd 16.12 with applying the patch that you provided.
However result is the same. When a member de-member himself the message related to de-membering is not sent to offline message queue of the other participants
How can I solve that problem?

**Comment by badlop** [comment]
I've tried again, and it works as previously. Are you sure the user is member before he demembers himself? It should be logged when a room owner user1 makes user111 member:
```
12:19:30.081 [info] Processing MUC admin query
 from user1@localhost/tka1 in room sala1@conference.localhost:
 [[{{jid,<<"user111">>,<<"localhost">>,<<>>,<<"user111">>,<<"localhost">>,<<>>},
 affiliation,member,<<>>}]]
```
Then he himself demembers:
```
12:19:36.413 [info] Processing MUC admin query
 from user111@localhost/tka1 in room sala1@conference.localhost:
 [[{{jid,<<"user111">>,<<"localhost">>,<<>>,<<"user111">>,<<"localhost">>,<<>>},
 affiliation,none,<<>>}]]
```
Notice: If he wasn't member in the first place, subscribers, occupants, nobody will receive a presence update.

**Comment by tolgatanriverdi** [comment]
@badlop 
Is there any way to analyze ejabberd log files other than openning ejabberd.log file with vi (or related text editors). Because its a very complex log file and I cannot understand anything out of it.
Is there any way to see logs from admin panel?

**Comment by kuchhadiyaa** [comment]
@badlop I added the patch you gave 
`+can_change_ra(member, participant, member,
+	      participant, affiliation, none, none) ->
+    true; % Allow a member that joined the room to de-member himself`

But it still gives permission error

Any idea?

**Comment by badlop** [comment]
Apply those lines exactly where I did, as the patch mentions. make sure you compile and copy the resulting beam file, and restart ejabberd: maybe ejabberd is not using that patched beam file.

**Comment by badlop** [comment]
No response in a month, so I close this ticket for now. If you have a chance to try, report if it's fixed or not.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:43775)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1ch2sC-0004jc-R5
	for zero@thezeroworld.com; Thu, 23 Feb 2017 18:32:32 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ELO7jn9g1VhGBHzSkOJUN1Dm2Pk=; b=lAWY+mXyW/iBdpGl
	rwuUc2nGhPC/Ukd2mAi0WrFu4LUr8U7sDUuI2lirCzQXxQgSaNrVmYE0lqjZV752
	5cCBv2JyViPcxK2aFBlkO3Urx3LIXoFp1wKD0LTGjJgEYGcr2d15zpkcY/coSlo2
	oweY27+FNEzQkpZXllbUhZbsFIM=
Received: by filter0920p1mdw1.sendgrid.net with SMTP id filter0920p1mdw1-3600-58AF29DC-4B
        2017-02-23 18:28:44.54033565 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 9trihVwiQ5CMun2QSrcIGw
	for <zero@thezeroworld.com>; Thu, 23 Feb 2017 18:28:44.508 +0000 (UTC)
Date: Thu, 23 Feb 2017 10:28:44 -0800
