### ISSUE TITLE
Crash while http upload

### ISSUE THREAD

**Issue by xi1976github** [processone/ejabberd#1394]
> What version of ejabberd are you using?
16.09
> What operating system (version) are you using?
Linux alarmpi 4.1.12-1-ARCH #1 PREEMPT Tue Oct 27 19:16:04 MDT 2015 armv6l GNU/Linux
> How did you install ejabberd (source, package, distribution)?
arch package
> What did not work as expected? Are there error messages in the log? What

HTTP Upload terminates

error.log
=======
2016-11-26 19:58:18.987 [error] <0.23050.0> CRASH REPORT Process <0.23050.0> with 0 neighbours crashed with reason: no match of right hand value <<>> in ejabberd_http:extract_path_query/1 line 399

crash.log
=======
2016-11-26 19:50:02 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.23024.0>
    registered_name: []
    exception error: {{badmatch,<<>>},[{ejabberd_http,extract_path_query,1,[{file,"src/ejabberd_http.erl"},{line,399}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,427}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,296}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,216}]},{ejabberd_http,init,2,[{file,"src/ejabberd_http.erl"},{line,169}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.610.0>,ejabberd_listeners,ejabberd_sup,<0.63.0>]
    messages: []
    links: [#Port<0.35656>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 652
  neighbours:
2016-11-26 19:58:19 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.23050.0>
    registered_name: []
    exception error: {{badmatch,<<>>},[{ejabberd_http,extract_path_query,1,[{file,"src/ejabberd_http.erl"},{line,399}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,427}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,296}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,216}]},{ejabberd_http,init,2,[{file,"src/ejabberd_http.erl"},{line,169}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.610.0>,ejabberd_listeners,ejabberd_sup,<0.63.0>]
    messages: []
    links: [#Port<0.35657>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 653
  neighbours:

Any Ideas?

Thank you

**Comment by suchatorg** [comment]
The same problem in debian 8, erlang 18.3

**Comment by weiss** [comment]
This has been [fixed][1] (shortly) after the 16.09 release.

[1]: https://github.com/processone/ejabberd/commit/d4b4f35a0ecff8fdad416a7f3bab85a2b7a7e375
