### ISSUE TITLE
Temp MUC Room Destroy with PubSub Subscriptions

### ISSUE THREAD

**Issue by tquackenbush** [processone/ejabberd#1396]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu 15.04

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have enabled room subscriptions in temporary MUC rooms with the 'persistent: false' and 'allow_subscription: true' attributes.

I was expecting if no user is present in the room that the room would be destroyed.
What I'm seeing is that if someone has subscribed to the room, the room persists even if a user joins/parts the room. If the user unsubscribes from the room, and join/parts again, the room is destroyed. Is this expected behavior?

When the room is created I see in the logs:
2016-11-29 02:31:37.585 [info] <0.2405.0>@mod_muc_room:init:117 Created MUC room my_cool_room@conference.myhost by bar@myhost/Foo

When there are no subscriptions and the user join/parts the room I see in the logs:
2016-11-29 02:32:46.643 [info] <0.2405.0>@mod_muc_room:close_room_if_temporary_and_empty:1202 Destroyed MUC room my_cool_room@conference.myhost because it's temporary and empty
2016-11-29 02:32:46.643 [info] <0.2405.0>@mod_muc_room:terminate:891 Stopping MUC room my_cool_room@conference.myhost

Is the room not considered 'empty' if there are active subscriptions?

**Comment by tquackenbush** [comment]
Doing a little digging, the answer might be 'yes, it is not empty with subscriptions'...
https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L1097

**Comment by tquackenbush** [comment]
Should the room be destroyed when the last subscription is unsubscribed?

**Comment by badlop** [comment]
I wondered if a temporary room can exist without occupants, just subscribers. And I guess yes, because subscribers are like occupants without presence, they still have messages.

So a temporary room without occupants and with only one subscriber can exist. But a temporary room without occupants and without subscribers makes no sense: when the last subscriber unsubscribes, the room should get automatically destroyed.

**Comment by badlop** [comment]
Try the patch I just committed, and reopen this issue if it has any problem.
