### ISSUE TITLE
why do we need to send <r/> in stream managment?

### ISSUE THREAD

**Issue by pnuzyf** [processone/ejabberd#1398]
1. Why do we need to send `<r/>`? I think the recipient could send out the ack directly once it handles a new stanza.

**Comment by weiss** [comment]
> Why do we need to send `<r/>`? I think the recipient could send out the ack directly once it handles a new stanza.

The [idea][1] is that we might not need an immediate acknowledgement for each and every stanza, so some traffic can be saved by having the recipient send ACKs only on demand.

You can discuss such protocol-related questions on the [XMPP standards mailing list][2].

[1]: https://xmpp.org/extensions/xep-0198.html#scenarios-efficient
[2]: https://mail.jabber.org/mailman/listinfo/standards

**Comment by pnuzyf** [comment]
Dear weiss, thank you very much for your kind reply! Following what you said, I think the recipient still can send ACKs on demand without the receipt of <r/>. <r/> just link a special stanza, it sounds like that the recipient sends the ACKs once it receives two stanzas. On the other hand, using <r/> could bring additional processing complexity. It is possible that the recipient just receives the <r/>and fails to receive the corresponding stanza. 
I have one more question stated as follows:
2: Let's image the following scenario: client A sends out three stanzas(1, 2,3) to server B. Unfortunately, only the 3rd stanza is received by B, then B would respond to B with h = 1.  According to the xep-198, "When receiving an <a/> element with an 'h' attribute, all stanzas whose paired value (X at the time of queueing) is less than or equal to the value of 'h' can be removed from the unacknowledged queue.", A then would remove 1st and 2nd stanzas from its unacknowledged queue, and keep 3rd stanza in this queue.  In this case, it is not reasonable.

**Comment by zinid** [comment]
@pnuzyf your question has been answered. If you have additional questions regarding the protocol, go ask the XSF folks. ejabberd implements what is written in the XEP.

**Comment by weiss** [comment]
> client A sends out three stanzas(1, 2,3) to server B. Unfortunately, only the 3rd stanza is received by B

TCP guarantees that this won't happen.
