### ISSUE TITLE
Question : Better message delivery

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1399]
> What version of ejabberd are you using?
16.X

> What operating system (version) are you using?
FreeBSD

> How did you install ejabberd (source, package, distribution)?
source

Android 6.0 closed the connection to ejabberd server when in deep sleep mode. Is there anyway that ejabberd can send push to the offline android clients apart from GCM ?

**Comment by weiss** [comment]
> Is there anyway that ejabberd can send push to the offline android clients apart from GCM ?

You could [whitelist the app to excempt it from Doze][1].  Other than that, GCM is the way to go.

[1]: https://www.cnet.com/how-to/stop-specific-apps-from-using-doze-on-android-6-0-marshmallow/
