### ISSUE TITLE
how to store rooms and chat in mysql ?

### ISSUE THREAD

**Issue by tvankit** [processone/ejabberd#1401]
> What version of ejabberd are you using?

ejabberd-16.12.beta

> What operating system (version) are you using?

centos 6

> How did you install ejabberd (source, package, distribution)?

Binary Installer

> What did not work as expected? Are there error messages in the log? What

No error in log.I have changed DB to MYSQL and one to one chat working properly now i want to create rooms and store the room as well as chat of rooms in mysql.What are the changes need to make in yml file to store data of rooms in mysql. 

> was the unexpected behavior? What was the expected result?

No data available in mysql when i create a room from admin.If i am creating a room than it should be present in muc_rooms or muc_registered table in mysql but no data present.

**Comment by badlop** [comment]
In the ejabberd configuration file, in modules, in mod_muc, add the option db_type, like:
```
modules:
  ...
  mod_muc:
    db_type: sql
    ...
```
