### ISSUE TITLE
ejabberd unix account uid in system range

### ISSUE THREAD

**Issue by DavidePrincipi** [processone/ejabberd#1402]
> What version of ejabberd are you using?

``ejabberd-16.01-0.x86_64``

...but I see it is still unchanged in ``postinstall.sh`` shipped with ``ejabberd-16.12.beta1-0.x86_64``.

> What operating system (version) are you using?

Linux CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The ``ejabberd`` unix account takes uid > 1000, as normal users. I'd expect an uid in the reserved system range is used.

In ``/etc/passwd``:

    ejabberd:x:1003:5204::/opt/ejabberd-16.01:/bin/bash

In postinstall.sh, I propose to use the -r flag, instead of -M (which would be implied, according to useradd manpage):

```
--- ./opt/ejabberd-16.12.beta1/bin/postinstall.sh.orig	2016-11-30 16:38:11.295185410 +0100
+++ ./opt/ejabberd-16.12.beta1/bin/postinstall.sh	2016-11-30 16:39:59.736046932 +0100
@@ -7,7 +7,7 @@
 echo "* Checking ejabberd installation"
 id=$(id -u)
 [ $id -eq 0 ] && {
-  useradd -M ejabberd 2>/dev/null
+  useradd -r ejabberd 2>/dev/null
   usermod -d @@INSTALLDIR@@ ejabberd
   chown -R ejabberd @@INSTALLDIR@@/database
   chown -R ejabberd @@INSTALLDIR@@/conf
```

**Comment by cromain** [comment]
This is indeed a good change. It's now applied.
thanks !
