### ISSUE TITLE
Muc/Sub : No notification to subscribers/participants when user subscribes to room

### ISSUE THREAD

**Issue by gsojitra** [processone/ejabberd#1405]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

When user subscribes to room, other subscribers are not getting any notification that other user has subscribed the room.
> was the unexpected behavior? What was the expected result?

When user subscribes to room, other subscribers are should get indication about that user.

**Comment by badlop** [comment]
> When user subscribes to room, other subscribers are should get indication about that user.

I don't see that requirement in the protocol documentation
https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/

So that isn't a bug, it's a feature request, right?

**Comment by gsojitra** [comment]
Yes. If it is not a bug then can be a feature.

**Comment by prefiks** [comment]
This was added in commit 2b363c7aee23ec0d4a446ded312b5356deeeefb5
