### ISSUE TITLE
Failed to load NIF library lib/linux-armhf/libssl.so.1.0.0

### ISSUE THREAD

**Issue by marcelklehr** [processone/ejabberd#1406]
Hi,

I'm sorry to bother you.

> What version of ejabberd are you using?

16.12-beta1,16.09,16.04

> What operating system (version) are you using?

Linux 3.2.40

> How did you install ejabberd (source, package, distribution)?

Linux ARMv7 installer from https://www.process-one.net/en/ejabberd/downloads/

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
~/ejabberd-16.12-beta1$ bin/ejabberdctl foreground
00:22:08.267 [info] Application lager started on node ejabberd@host
00:22:08.342 [info] Application crypto started on node ejabberd@host
00:22:08.394 [info] Application sasl started on node ejabberd@host
00:22:08.472 [info] Application asn1 started on node ejabberd@host
00:22:08.473 [info] Application public_key started on node ejabberd@host
00:22:08.543 [info] Application ssl started on node ejabberd@host
00:22:08.651 [info] Application fast_yaml started on node ejabberd@host
00:22:08.740 [warning] unable to load sha NIF: {error,{load_failed,"Failed to load NIF library /.../ejabberd-16.12-beta1/lib/fast_tls-1.0.8/priv/lib/p1_sha: '/.../ejabberd-16.12-beta1/lib/linux-armhf/libssl.so.1.0.0: symbol COMP_CTX_free, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference'"}}
00:22:08.742 [error] CRASH REPORT Process <0.105.0> with 0 neighbours exited with reason: no match of right hand value {error,{load_failed,"Failed to load NIF library /.../ejabberd-16.12-beta1/lib/fast_tls-1.0.8/priv/lib/p1_sha: '/.../ejabberd-16.12-beta1/lib/linux-armhf/libssl.so.1.0.0: symbol COMP_CTX_free, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference'"}} in fast_tls_app:start/2 line 53 in application_master:init/4 line 134
00:22:08.744 [info] Application fast_tls exited with reason: no match of right hand value {error,{load_failed,"Failed to load NIF library /.../ejabberd-16.12-beta1/lib/fast_tls-1.0.8/priv/lib/p1_sha: '/.../ejabberd-16.12-beta1/lib/linux-armhf/libssl.so.1.0.0: symbol COMP_CTX_free, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference'"}} in fast_tls_app:start/2 line 53
```

I'm not sure if this is an error on my part, I've tested some older versions and they seem to not work as well :/ Let me know if I need to provide more details that I haven't thought of. I saw similar errors seem to have been fixed a while ago and wondered whether that fix just targeted other architectures.

**Comment by marcelklehr** [comment]
I don't get this error with 15.07.

**Comment by cromain** [comment]
Hello

What Linux distribution are you running ?
What version of glibc is installed ?

**Comment by cromain** [comment]
you can make sure ejabberd is using included libssl using 'pmap PID | grep libssl' command (or 'pmap -p PID') where PID is pid of beam process.
if should output full path to lib/linux-armhf/libssl.so.1.0.0

**Comment by cromain** [comment]
just one idea: your path looks odd '/.../ejabberd-16.12-beta1
you should have modified something, maybe around ROOT_DIR variable in ejabberdctl ?

**Comment by marcelklehr** [comment]
Sorry, I should have clarified: I modified the paths prior to posting. I didn't modify anything in ejabberdctl.

I'm running synology_armadaxp_ds214. pmap is not available on that machine, it seems. `uname -m` returns `armv7l`, I noticed this would match two entries in the switch statement in ejabberdctl? Id armhf the right lib path in that case?

Can confirm hash:
> ffd9cba25637ae991e9fbc52718fef7f  lib/linux-armhf/libssl.so.1.0.0

**Comment by marcelklehr** [comment]
(Ping) Is there an alternative to pmap? What can I do to help debug this?

**Comment by marcelklehr** [comment]
The fact that 15.07 works splendidly to me shows that it's not a problem on my end. Correct me if I'm wrong. What could have gone wrong, where should I look for errors?

**Comment by marcelklehr** [comment]
Running ejabberd on that machine in a chrooted archlinux seems to have solved the problem.

**Comment by marinakr** [comment]
I have same issue with ejabberd 16.06 and CentOS 7 - 
My openssl:
`rpm -qa | grep openssl
openssl-libs-1.0.1e-60.el7_3.1.x86_64
openssl-1.0.1e-60.el7_3.1.x86_64
openssl-devel-1.0.1e-60.el7_3.1.x86_64
`
Error: 
` Application fast_tls exited with reason: no match of right hand value {error,{load_failed,"Failed to load NIF library deps/fast_tls/priv/lib/p1_sha: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"}} in fast_tls_app:start/2 line 53
`
