### ISSUE TITLE
ejabberd 16.12 beta1 cannot install mod_rest

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1408]
Hi
I've tried to install ejabberd 16.12 and then tried to install mod_rest with module_install mod_rest command
And ejabberd gave the following error output
It was working fine on ejabberd 16.08, do you know what may be the reason:
I've installed ejabberd with deb package

```
/opt/ejabberd-16.12.beta1/lib/ejabberd-16.12.beta1/include/jlib.hrl:21: can't find include file "ns.hrl"
/opt/ejabberd-16.12.beta1/lib/ejabberd-16.12.beta1/include/jlib.hrl:22: can't find include file "fxml.hrl"
/opt/ejabberd-16.12.beta1/lib/ejabberd-16.12.beta1/include/jlib.hrl:426: record xmlel undefined
/opt/ejabberd-16.12.beta1/lib/ejabberd-16.12.beta1/include/jlib.hrl:466: type xmlel() undefined
Error: {compilation_failed,"src/mod_rest.erl"}
```

**Comment by cromain** [comment]
Yes this is a known problem which was fixed yesterday in 1883a98

**Comment by tolgatanriverdi** [comment]
When I pulled the source code and execute
./autogen.sh

./configure

make

it gives the folloing error output

```
src/mod_muc_room.erl:2031: variable 'Password' is unbound
src/mod_muc_room.erl:2031: field password undefined in record muc_subscribe
ERROR: compile failed while processing /home/meeapps/ejabberd_source/ejabberd-git/ejabberd: rebar_abort
```

**Comment by tolgatanriverdi** [comment]
any idea about this problem?

**Comment by badlop** [comment]
The record muc_subscribe is defined in the library 'xmpp' that ejabberd gets from git and downloads to deps/. And it got a new field called 'password' a few days ago. Probably you need to also run something like:
```
./rebar get-deps
./rebar compile
```
So that the updated library is downloaded and compiled.

**Comment by tolgatanriverdi** [comment]
Thanks that worked. Can you also help me about this issue:
#1412
