### ISSUE TITLE
ejabberd 16.12 compile error

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1412]
When I pulled the source code from master repository and execute the following commands:

./autogen.sh

./configure

make

it gives the folloing error output

```
src/mod_muc_room.erl:2031: variable 'Password' is unbound
src/mod_muc_room.erl:2031: field password undefined in record muc_subscribe
ERROR: compile failed while processing /home/meeapps/ejabberd_source/ejabberd-git/ejabberd: rebar_abort
```

How can I solve that?

**Comment by zinid** [comment]
./configure --enable-latest-deps

**Comment by tolgatanriverdi** [comment]
Tried that but still the same result

**Comment by zinid** [comment]
clean everything first: `$ make distclean`, then repeat

**Comment by tolgatanriverdi** [comment]
That worked thanks

**Comment by tolgatanriverdi** [comment]
Ejabberd compiled and installed succesfully but now , when I try to compile my additional modules such as mod_offline_post
it gives the following error

```
/lib/ejabberd-16.12.beta1-25/include/jlib.hrl:21: can't find include file "ns.hrl"
/lib/ejabberd-16.12.beta1-25/include/jlib.hrl:22: can't find include file "fxml.hrl"
/lib/ejabberd-16.12.beta1-25/include/jlib.hrl:426: record xmlel undefined
/lib/ejabberd-16.12.beta1-25/include/mod_muc_room.hrl:97: type xmlel() undefined
src/mod_offline_post.erl:31: Warning: behaviour gen_mod undefined
src/mod_offline_post.erl:51: Warning: variable 'Opts' is unused

```

And the make file script for that module is like below:

```
%%% On Ubuntu
{'src/mod_offline_post', [{outdir, "ebin"},{i,"/lib/ejabberd-16.12.beta1-25/include/"}]}.

```


And this is the build script of that module

`erl -pa /lib/lager-3.2.1/ebin -pz ebin -make`

Do you know how can I solve that problem?

**Comment by mremond** [comment]
mod_offline_post will need to be updated for ejabberd 16.12

**Comment by tolgatanriverdi** [comment]
But the error says jlib.hrl(which is ejabberd class) cannot find include file ns.hrl(which is also ejabberd file)
So I thought its ejabberd related issue because its giving the error in native ejabberd classes

**Comment by cromain** [comment]
external module compilation has been updated for 16.12 refactor.
you should check again when 16.12 will be published.
if you still have errors this means your module has to be updated for ejabberd 16.12.
