### ISSUE TITLE
How to ? : Kill session

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1413]
> What version of ejabberd are you using?
16.x

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
Source

I want to achieve scenario if the there is no incoming packet from peer for X minutes close the connection / kill the session .

Any pointers how can i achieve it at best ? I dont want to send ping from Server to client and wait for timeout . However client does send the ping every 5 minutes when idle.

**Comment by weiss** [comment]
If you [configure][1] a `ping_interval` of, say, six minutes, the server will only ping the client (and eventually close the connection) if no traffic was received from the client during that interval.

[1]: https://docs.ejabberd.im/admin/configuration/#modping

**Comment by nOmi7** [comment]
Hi @weiss i am not willing to do that would be ready to change the default code i  just need some pointers on best way to do it ..  Even i dont configure the ping i would like to kill session if no packet received for x amount of time ..

**Comment by weiss** [comment]
You could of course create a version of `mod_ping` that kills the session immediately rather than pinging the client first.

**Comment by nOmi7** [comment]
ok what would be the best way to put a timer in #state  @ c2s and timeout if no packet rcvd or create hook on packet rcvd and put timer there and kill session ?

**Comment by weiss** [comment]
My suggestion was doing it the way `mod_ping` does it.

**Comment by nOmi7** [comment]
Got it ... thanks Sir for super fast response :)
