### ISSUE TITLE
Include ejabberd version in API responses

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#1414]
It would be great if ejabberd's REST and XMLRPC API responses would include a header stating the ejabberd version. e.g.

```
X-ejabberd-version: 16.09
```

The background is that I maintain a small python library [xmpp-backends](http://xmpp-backends.readthedocs.io/en/latest/) that abstracts a few API calls to make our homepage (which integrates with ejabberd) independent of the API used. Since the API sometimes changes a little over ejabberd versions, it would be great if I could dynamically know the currently used version and change API calls/parse responses depending on the version used.

**Comment by cromain** [comment]
Indeed this is a nice feature to have. Maybe that header should be conditional (display API version always, and ejabberd version if mod_version is enabled)

**Comment by mathiasertl** [comment]
Sounds good to me. HOWEVER I would much prefer separate headers, so they can be parsed easily.

**Comment by rraptorr** [comment]
Just don't use X- prefix: https://tools.ietf.org/html/rfc6648 ;)

**Comment by mathiasertl** [comment]
*bump* Is this going to be implemented? I currently maintain a python library to interface with the ejabberd APIs, and frequent changes and lack of any API versioning makes it very hard to support different versions :-(

**Comment by cromain** [comment]
@weiss Thanks for the patch. We have to include this feature, but i think we must have a way to configure what we expose there. 
1/ Should ejabberd version be displayed only if mod_version is enabled for example ?
2/ Is ejabberd version enough ? not likely: how to handle API provided by extra and/or external modules ?

**Comment by mathiasertl** [comment]
I can live with only including the header if `mod_version` is enabled. I don't think anyone should care about exposing the version, but any client developer can simply require that you enable the module. 

We could also make it an option to the HTTP (and XMLRPC!) API, regardless of mod_version. All is fine for me. 

And for me and my library, the ejabberd version is currently enough. An external module providing an API has to provide its own header anyway.

**Comment by weiss** [comment]
> Should ejabberd version be displayed only if `mod_version` is enabled for example ?

I think I'd rather not depend on `mod_version`.  Your API client might need the version number while you might not want to expose it publicly via XMPP.

> Is ejabberd version enough ? not likely: how to handle API provided by extra and/or external modules ?

Yeah.  And using the ejabberd version number rather than an API revision is a bit hacky anyway.  But it might do the trick for some use cases.

One other idea I had was to address this issue and #517 in one go by supporting listener configurations such as the following:

    listen:
      -
        module: ejabberd_http
        ip: "203.0.113.3"
        port: 8443
        tls: true
        request_handlers:
          "/api": mod_http_api
        custom_headers:
          "Strict-Transport-Security": "max-age=31536000"
          "ejabberd-version": "@VERSION@"
        # [...]

**Comment by prefiks** [comment]
Could we just send standard Server: "ejabberd 17.03" header instead of that special header?

**Comment by mathiasertl** [comment]
I'd very much prefer just the version in a header.

A header indicating a version for API clients should be as easily parseable as possible. This is already an ejabberd specific API, it's something I already know. I want to know the version of ejabberd, because the API changes with every version.
