### ISSUE TITLE
muc/sub-ejabberd 16.12

### ISSUE THREAD

**Issue by sepasti** [processone/ejabberd#1416]
> What version of ejabberd are you using?

16.12.beta

> What operating system (version) are you using?

debian 8.4

> How did you install ejabberd (source, package, distribution)?

 distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,how to admin, owner or member adds Subscriber to group? 
 add myself(u1) to group as Subscriber:
```
iq from='u1@domain.com'
    to='group1@conference.domain.com'
    type='set'
    id='E6E10350-76CF-40C6-B91B-1EA08C332FC7'
  subscribe xmlns='urn:xmpp:mucsub:0'
             nick='u1'>
    event node='urn:xmpp:mucsub:nodes:messages' /
  /subscribe>
/iq
```
but I want to set muc's config with "member_only: true" and others can add subscribers to group. how do that?
in muc, admin or owner can invite another to group:
```
message to='group1@conference.domain.com'
  x xmlns='http://jabber.org/protocol/muc#user'
    invite to='user2@domain.com'/
  /x
message
```

**Comment by badlop** [comment]
The same question was also posted in https://www.ejabberd.im/forum/28627/mucsub-ejabberd-1612-beta
