### ISSUE TITLE
banned subscribers can send message in groupchat !

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [processone/ejabberd#1418]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

linux debian

> How did you install ejabberd (source, package, distribution)?

distribution

banned subscribers can send message in groupchat !

**Comment by badlop** [comment]
Confirmed: a user subscribes to the room, then a room owner sets him outcast affiliation. The user can still send messages to the room without problem.

**Comment by badlop** [comment]
This is not a bug, it may be considered a feature request.

XEP-0045 defines many ways to limit users to participate in the room and are based in the user's presence, role and affiliation: temporal kick, persistent ban, setting the room moderated and revoking voice...

None of those limitations are applied to MUC/Sub, as a subscriber does not have a specific presence, role or affiliation in the room.

**Comment by Pouriya-Jahanbakhsh** [comment]
Your muc/sub hasn't official XEP on xmpp.org. So you have to make it logical. There is not any logic behind this issue.
Combining your own XEP (muc/sub) with original MUC XEP without any bug and good logic, takes a long time and in the future you will have just your own XEP (after many changes).
So my comment is creating your own XEP without coupling to MUC.
