### ISSUE TITLE
Feature request, missing Pubsub metadata

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1421]
The current Pubsub implementation in ejabberd doesn't implement `pubsub#title` and `pubsub#description` like defined in http://www.xmpp.org/extensions/xep-0060.html#entity-metadata.

Implementing `pubsub#owner`, `pubsub#publisher` and  `pubsub#num_subscribers` could also be  a big plus. 

Is it also possible to expose `pubsub#access_model` through this node ? (not in the standard)

**Comment by cromain** [comment]
implemented for now:
title, description, owner, publisher, num_subscribers

**Comment by cromain** [comment]
we still lack dynamic meta map likely stored in node options

**Comment by cromain** [comment]
fully covered by 3162ec0d
