### ISSUE TITLE
Compilation error when extracting nested records in Elixir

### ISSUE THREAD

**Issue by safwank** [processone/ejabberd#1422]
> What version of ejabberd are you using?

16.09.

> What operating system (version) are you using?

Mac OS 10.12.1.

> How did you install ejabberd (source, package, distribution)?

Hex.pm.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm building a custom Elixir module that uses the `muc_filter_message` hook. To do that, I need to extract the `state` record in `mod_muc_room.hrl` so I can inspect the state in the callback every time a MUC message is received, e.g.

```elixir
Record.defrecord :state, Record.extract(:state, from_lib: "ejabberd/include/mod_muc_room.hrl")
```

The problem is the `state` record's `jid` field references the `jid` record in a different file (`jlib.hrl`) without including it explicitly, i.e.

```erlang
-include("jlib.hrl").
```

Without the explicit `include`, the compilation fails with the following error because Elixir doesn't know about `jlib.hrl` and therefore can't extract the nested record.

```
** (ArgumentError) argument error
    (stdlib) dict.erl:131: :dict.fetch(:jid, {:dict, 8, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[], [], ...
```

Is there a specific reason why `jlib.hrl` isn't explicitly included in `mod_muc_room.hrl`? If not, can we include it? I can submit a PR for this if required.

Thanks.

**Comment by zinid** [comment]
`jlib.hrl` is not used anymore in ejabberd 16.12beta.

**Comment by safwank** [comment]
@zinid Thanks for getting back to me. Ah I didn't know that. So which record does the following reference?

https://github.com/processone/ejabberd/blob/master/include/mod_muc_room.hrl#L106

**Comment by zinid** [comment]
jid.hrl

**Comment by safwank** [comment]
@zinid I see. That's good news. Unfortunately that still doesn't solve this specific problem :(. Is it possible to include `jid.hrl` in `mod_muc_room.hrl`?

**Comment by safwank** [comment]
I can submit a PR if you want.

**Comment by zinid** [comment]
No, it's not possible, because including headers in headers is in general a bad practice, since this may lead to conflicts. E.g. if you include `jid.hrl` in `mod_muc_room.hrl` and in, let's say, `mod_roster.hrl`, the following will not compile:
```
-include("mod_muc_room.hrl").
-include("mod_roster.hrl").
```

**Comment by zinid** [comment]
I actually do not understand your problem, maybe someone with Elixir skills can help.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:52533 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cH3Qc-0005Pr-5B
	for zero@thezeroworld.com; Wed, 14 Dec 2016 01:52:38 -0500
Date: Tue, 13 Dec 2016 22:51:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481698317;
	bh=SAWDV6I2YgMA76z9+CI6E/T/w4ODkDIdOBCRuNN5FHk=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=L3YzR0adeYZiSI2oFa1W7r6ZUgQxYtTGAEJVq2k/f9mqBIpmGG3mcOGoOrkY6S3DN
	 pxPU+kORf748KZDz8EicvXENsfXEe6/GaOlDLGPGj9zOPubMvSVrFKGwXaaX1LUG7R
	 6xEYfqoz+08msR6mdm3O7/sMMasGAmdQ1TBHrq5w=

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:56979)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cH3PK-00058x-NN
	for zero@thezeroworld.com; Wed, 14 Dec 2016 01:51:18 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=CgwP1v1kRvWxVPw1fhx2RZA27us=; b=Qtyo1rCyWf73kyf4
	0RKEC/yPUH3ak7DAuVuKQo5AzWFzbLpeUxxy5pRoqFi0M3wXj/u/yDn/rjs125bR
	dXXoSHxzmXfPV9gZZTnl4C2OAevxj1T9YVGCWIc+6FoKzW/ExBMPRtV54DhZ3swn
	zAcgyEewrr1pqfHDG7cflGAIiHk=
Received: by filter0432p1mdw1.sendgrid.net with SMTP id filter0432p1mdw1-10703-5850EBBD-28
        2016-12-14 06:50:37.802924525 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id SelpZLkFSkiwUf4r1DVFWQ
	for <zero@thezeroworld.com>; Wed, 14 Dec 2016 06:50:37.794 +0000 (UTC)
Date: Tue, 13 Dec 2016 22:50:37 -0800

**Comment by safwank** [comment]
> No, it's not possible, because including headers in headers is in general a bad practice

Understood. 

> also, this = #jid{} can be safely removed now, because dialyzer now becomes more clever.

I tried that and it actually works :). I'm wondering what the default value would be if you remove `#jid{}`?

**Comment by zinid** [comment]
It's irrelevant, because the field is always initialized at startup:
https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L129
https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L147

**Comment by safwank** [comment]
@zinid OK. Hmmm, I'm actually thinking that it'd be easier if I just "duplicated" the records in my module. It's not ideal, but definitely better than removing the default value as it sounds a bit hacky and inconsistent, at least as far as `ejabberd` is concerned. Until a more complete Elixir integration is introduced I'm afraid I just need to work around the issue. If I keep running into Elixir-specific issues I reckon I'll just rewrite the module in Erlang.

Thanks for your help.

**Comment by leeicmobile** [comment]
@safwank sorry to bump this issue a year later but we are doing the exact same thing and was wandering if you came up with a neat solution to this?
