### ISSUE TITLE
How to use tls 

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1423]
> What version of ejabberd are you using?

16.x

> What operating system (version) are you using?

Ubuntu 

> How did you install ejabberd (source, package, distribution)?

Source 

I am using ejabberd to use chat internally and will not be federating with other xmpp servers 
We would have mobile based clients and to connect and open session as fast as possible I would like to use direct tls instead of starttls is it possible to configure ejabberd for using direct tls instead of starttls?

**Comment by zinid** [comment]
Yes, set `tls: true` in ejabberd_c2s listener's section.

**Comment by nOmi7** [comment]
https://blog.process-one.net/securing-ejabberd-with-tls-encryption/  says 
tls: This option specifies that traffic on the port will be encrypted using SSL immediately after connecting. This method is nowadays deprecated and not recommended

Why is that ? Is not good to have TLS from the start of connection instead of Plain to TLS securing ?
Is there any know security vulnerability ?

**Comment by zinid** [comment]
There are no security issues if you verify the server's certificate. The problem arises in multi-domain environments:
1) SNI is not always supported
2) Even if SNI is supported, it's not always possible or desirable for the server to have access to all domain certificates.

**Comment by nOmi7** [comment]
May be a dumb question but multi domain is not when its clustered env right? I can use TLS with normal ejabberd clustered env yes?

**Comment by zinid** [comment]
Yes. Multi-domain means when you have serveral virtual hosts configured, e.g:
```yaml
hosts:
    - "host1"
    - "host2"
    - ...
```

**Comment by nOmi7** [comment]
I am good can be closed .. I tested this and works I want.
