### ISSUE TITLE
PubSub MUC messages are being stored if subscriber of room is offline

### ISSUE THREAD

**Issue by gsojitra** [processone/ejabberd#1428]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log?

In MUC-Sub, if subscriber is not online, pubsub messages will be stored in offline storage(spool table in sql, offline_msg in mnesia).
> What was the unexpected behavior? What was the expected result?

Should muc-pubsub messages be stored in spool table if subscriber is offline ? 
Is it expected behavior as per muc sub ?

**Comment by cromain** [comment]
Yes this is expected behaviour when mod_offline is enabled.
