### ISSUE TITLE
MUC Room Discovery Problem

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1434]
Hi

We're using IOS XMPP Framework and Android Smack Library to connect our ejabberd server in our mobile application.
Both of them has the similar problem.

When we create the room as admin, we add users to member list by sending ejabberd
`<item affiliation='member' jid='xxx@yyy.com'>`
Then users can send and receive messages to group without any problem. 
And if a user removes the app from device and reinstall it, we are using muc discovery protocol to discover which rooms he/she were joined before he/she uninstall the app

However there is a problem at this point, If a user uses the muc discovery  when all the participants of the group became offline. Server doesn't return muc discovery result about that group to user as he/she is a participant of it.

And when I check the admin console those groups seems to have 0 participants(Because all the participants are offline, but they are in the memberlist). And I think muc discovery returns only the groups which have more than 0 participants

Does anyone know why does it happen and how can I find a solution to that? @badlop 

We're using ejabberd 16.09

**Comment by badlop** [comment]
Right, when there are more than 100 rooms, only the non-empty ones are returned in a Service Discovery query. You can configure that number with the mod_muc option max_rooms_discoitems. You can set it to a very high number.

**Comment by tolgatanriverdi** [comment]
So I need to upgrade ejabberd 16.09 to  16.12 in order to set this configuration right?
This muc service discovery returns the groups which are only the requesting user is participant. Is that right? (This is what I want to achieve)

**Comment by badlop** [comment]
> So I need to upgrade ejabberd 16.09 to 16.12 in order to set this configuration right?

There's still another solution: to edit the source code of your 16.09, and change in src/mod_muc.erl this line:
```
-define(MAX_ROOMS_DISCOITEMS, 100).
```
Then recompile the module, install it and restart ejabberd.

> This muc service discovery returns the groups which are only the requesting user is participant. Is that right? (This is what I want to achieve)

Service Discovery returns all the existing rooms, regardless of the user affiliation with them.

**Comment by tolgatanriverdi** [comment]
So how can we understand which rooms are the user participated
So we can list those groups after user uninstall the app

**Comment by badlop** [comment]
I don't know any way to get a list of rooms where the user has some affiliation. I also see that those affiliations are not deleted when the account is deleted...

**Comment by zinid** [comment]
Those are not deleted because:
1) in general not only local users have MUC affiliations
2) it's extremely inefficient with current database schemas design.

**Comment by tolgatanriverdi** [comment]
@badlop  if I make the changes you suggested below:

`-define(MAX_ROOMS_DISCOITEMS, 100).`

Should I also have to add a configuration property to ejabberd.yml file?

**Comment by badlop** [comment]
No. Just change that source code, put 10000 or whatever, recompile that file (or all ejabberd), then copy the mod_muc.beam file to overwrite old one, and restart ejabberd.

**Comment by tolgatanriverdi** [comment]
Thanks that worked,
I've one more question When I use muc service discovery
Some group names returns like this

`groupname (private, 1)`

and some of them returns like this

`groupname(0)`

Do you know what is the difference

**Comment by badlop** [comment]
The first room is configured to be private, the second is public.
I'll describe this in the corresponding room option:
> public: true|false: The room is public in the list of the MUC service, so it can be discovered.

**Comment by tolgatanriverdi** [comment]
Ok. Now I think I understand the difference
If we make the rooms private, when we use service discovery it only fetches the rooms that we are participant
But if we make the rooms public , when we use service discovery it doesnt matter if we are participant or not.
So in my case, making the room private can fix my problem
Is that right?
