### ISSUE TITLE
Ejabberd 16.09 Muc Bugs

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1435]
Hi

I was using ejabberd 16.08 before and there were only 1 problem in MUC (mod_offline_post module wasnt seeing some of the participants unavailable, so it wasnt sending information to our webservers)

So I've upgraded to 16.09 and that problem fixed.
However I've found some other problems which werent exist on 16.08
Which are

When an admin kick someone from group with **affiliation='outcast'**  or affiliation='none'. The person who is kicked from group cannot receive messages from group(as it should be),  but can still send message to that group( this shouldnt be happening).

**Kick user from group:**
```
<iq type='set' id='mod4'  to='coven@chat.shakespeare.lit'>
       <query xmlns='http://jabber.org/protocol/muc#admin'>
		<item jid='hag66@shakespeare.lit/pda' affiliation='none'/>
		<item jid='hecate@shakespeare.lit/broom' affiliation='none'/>
	</query>
</iq>
```

**Add member to group:**

```
<iq type='set' id='mod4'  to='coven@chat.shakespeare.lit'>
       <query xmlns='http://jabber.org/protocol/muc#admin'>
		<item jid='hag66@shakespeare.lit/pda' affiliation='member'/>
		<item jid='hecate@shakespeare.lit/broom' affiliation='member'/>
	</query>
</iq>
```

Do you know why can it be and how can I solve that?

**Comment by tolgatanriverdi** [comment]
any idea about the problem ? @badlop

**Comment by badlop** [comment]
I try what you say, but I don't see that problem. I install 16.09, create two accounts, set one as admin, it creates a room, the second user joins it, gets kicked, then tries to send a message to the room, which is rejected.

Does the problem reproduce for you 10% of the times? Try with the default mod_muc config, does the problem happen? If so, then describe in more detail your steps, or if you configure the room somehow, or if the second user is also subscriber...

**Comment by tolgatanriverdi** [comment]
It happens %100 of the times without any exception.
This problem wasnt happening while using 16.08 with same configuration

**Comment by badlop** [comment]
That's a good detail, if 16.08 works but 16.09 is broken in your tests. In that case, the suspicious commit is one of those:
```
$ git log --oneline 16.08..16.09 src/mod_muc_room.erl
1aca541 Fix nick-to-jid mapping for MUC subscribers
d076103 Support multiple room invitations (#1285)
36ab9cc Fix message routing from subscribers
3803a8d Link MUC subscription to bare JID
c6afb97 Handle <subscriptions/> request to list MUC subscribers
5ec2874 Do not update muc_online_users table on MUC/Sub operations
417284a Add get_subscribers command to list MUC subscribers
1fc58ac Add commands for MUC subscriptions management
```
As I explained, I tried to reproduce your problem, but it didn't appear. Either you investigate yourself, or give detailed steps to reproduce your problem, so that we can also investigate it.
