### ISSUE TITLE
TLS / SSL resumption

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1436]
> What version of ejabberd are you using?
16.x

> What operating system (version) are you using?
Debian 8.1

> How did you install ejabberd (source, package, distribution)?
Source

Does ejabberd support TLS/SSL resumption ? if yes then is it uinsg TLS session id or tickets  where can I configure it .

If no it would be great if we can add this ejabberd it helps on Slow mobile networks for faster connects and auths.

If this cannot be taken up a little direction on where can i make the changes in code ill may be try and then create a pull request.

Thanks

**Comment by zinid** [comment]
No, ejabberd doesn't support it and the implementation would not be that easy even for core ejabberd developers, so no direction.

**Comment by nOmi7** [comment]
@zinid  thanks will try to see if we can help in this case and hope to create pull request in near future if all goes well
