### ISSUE TITLE
Problem on pubsub module(publish,update,retrieve) - 16.09

### ISSUE THREAD

**Issue by tonibagur** [processone/ejabberd#1439]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

debian:jessie
postgresql for database

> How did you install ejabberd (source, package, distribution)?

I installed it with docker using this docker image:
https://github.com/rroemhild/docker-ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The steps to reproduce the problem are the following.
1. Create a pubsub node of type=flat(using sql backend, postgres)
2.Subscribe some users to its 
3.Publish an item in this new node(At this point, as expected, all subscribed users receive the new item with its associated item_id
4.Update this item with a new payload(At this point, as expected, all subscribed users receive the updated item)
5. A new subscriber to the node, requests all existing items on the node, with something like 
<iq type='get'
    from='francisco@denmark.lit/barracks'
    to='pubsub.shakespeare.lit'
    id='items1'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <items node='princely_musings'/>
  </pubsub>
</iq>
Here we found the bug, the server returns all existing items but with the old payload instead of the new payload. The curious thing if that if we search the item in the table pubsub_item, we found the new payload, not the old one. Any ideas? Is this a bug that may be solved by the 16.12 version? 
Many thanks on advance

**Comment by cromain** [comment]
Impossible to reproduce this. tested with Mnesia MySQL and PgSQL backend.
