### ISSUE TITLE
Publish v17.01 to hex.pm

### ISSUE THREAD

**Issue by safwank** [processone/ejabberd#1445]
Thanks for releasing v16.12. I've been waiting for it for sometime as it fixes a number of bugs that have been bugging (no pun intended) me .

Unfortunately for us Elixir developers, the release isn't yet on hex.pm. Could you please publish the latest Hex package so we're not left out?

Thanks!

**Comment by cromain** [comment]
We'll need to update some deps for 17.01 to fix few bugs. To avoid duplicated tasks, we'll directly jump to 17.01 on hex.pm.

**Comment by safwank** [comment]
@cromain No worries, even better :)

**Comment by cromain** [comment]
3b2c2b5c prepare the upcoming package.
it will be published on hex.pm after ejabberd release
