### ISSUE TITLE
Docker image outdated

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#1450]
The Docker image at https://hub.docker.com/r/ejabberd/ecs/ is still at 16.12-beta1.

**Comment by cromain** [comment]
we'll upgrade to 17.01 when it will be released

**Comment by mbirth** [comment]
While you're at it: Could you add the sqlite3 libraries, too? I think they're missing because ejabberd didn't like it when I wanted to switch to sqlite database.

**Comment by cromain** [comment]
good point, this will be added

**Comment by urzds** [comment]
Any news about this?

**Comment by cromain** [comment]
preparing updates for 17.03, with sqlite libs, mysql and pgsql drivers, and inets for http api.

**Comment by cromain** [comment]
preparing updates for 17.03, with sqlite libs, mysql and pgsql drivers, and inets for http api.

**Comment by cromain** [comment]
upgrade ready, docker images will be published after 17.03 release

**Comment by firstthumb** [comment]
Waiting for it

**Comment by cromain** [comment]
docker image is updated and available on docker hub

**Comment by urzds** [comment]
Is this repository abandoned? https://hub.docker.com/r/processone/ejabberd/

**Comment by mremond** [comment]
Official repository is at: https://hub.docker.com/r/ejabberd/ecs/

**Comment by mbirth** [comment]
What's the difference between "latest" and "17.03"? They have different sizes so they seem to point to different images?
