### ISSUE TITLE
Server detect wrong status of user

### ISSUE THREAD

**Issue by truyet** [processone/ejabberd#1453]
> What version of ejabberd are you using?

ejabberd 3.13

> What operating system (version) are you using?
Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
package

Clusters have 2 server:
- User A connected to server 1.
- User B connected to server 2.

- User A has online status, who receives message well to user B but user A send message to user B, server detected user B offline.
- User B connected to stream, user B can send message to user A but server detected user B offline and didn't push message of user A to user B.

**Comment by zinid** [comment]
Such problems are virtually impossible to investigate, because they look like "nothing is working".

**Comment by zinid** [comment]
Also, there is no such ejabberd version: 3.13

**Comment by truyet** [comment]
it's a business version.

**Comment by zinid** [comment]
You should have ProcessOne support for bussiness edition, no?
In that case you better contact our support team directly to resolve your problem.

**Comment by truyet** [comment]
Ok, I will contact with support team. Thank you :)
