### ISSUE TITLE
Module mod_http_offline failed to start

### ISSUE THREAD

**Issue by chandan9roy** [processone/ejabberd#1455]
> What version of ejabberd are you using?

ejabberd 2.1.11

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

sudo apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What

=ERROR REPORT==== 2017-01-10 06:11:16 ===
File operation error: eacces. Target: /usr/lib/ejabberd/ebin/mod_http_offline.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 2017-01-10 06:11:16 ===
C(<0.40.0>:gen_mod:75) : Problem starting the module mod_http_offline for host "35.161.51.66" 
 options: []
 error: undef

=ERROR REPORT==== 2017-01-10 06:11:16 ===
C(<0.40.0>:gen_mod:80) : ejabberd initialization was aborted because a module start failed.

> was the unexpected behavior? What was the expected result?

Module mod_http_offline should work.

**Comment by zinid** [comment]
> File operation error: eacces. Target: /usr/lib/ejabberd/ebin/mod_http_offline.beam

This means ejabberd has insufficient rights to access the file `/usr/lib/ejabberd/ebin/mod_http_offline.beam`

**Comment by chandan9roy** [comment]
so what should be right to access /usr/lib/ejabberd/ebin/mod_http_offline.beam

**Comment by chandan9roy** [comment]
okay thanks solved the problem.
