### ISSUE TITLE
Custom property for a MUC

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1456]
Hi guys,
This is not a bug report but a question related to the inner MUC system.
I'm using v16.04 (Linux AMD64 binary installer) but this is not strictly related to this specific version.
I'd like to add few custom properties/fields to a MUC, here are few examples: date_expiry, enabled, room_type, ... I'd like to add these new properties to the "opts" field stored on muc_room table (no matter if sql, mnesia or something else).
Obiously I need to write my own module for reading/writing/dealing with these fields but I'd like to use the same db field so I don't need to rewrite everything or keep my own parallel structure in memory.
I have looked at the inner ejabberd source code and it seems to be a viable option. has anyone ever tried to do this ? do you have any suggestion for me ?

In the startup phase every MUC is loaded into memory and when the call gen_fsm:sync_send_all_state_event(RoomPID, get_state) is issued I can get the whole room state.
I'd like to use the "opts" field so my changes are kept (persistent muc) after reboot, any advice ?

Thanks 
Ben

**Comment by zinid** [comment]
I would avoid using synchronous calls to MUC room processes because it can block for a significant amount of time. In recent ejabberd version there is a hook which makes it possible to read/write fields from/into the configuration x:data form. See how mod_mam does this: https://github.com/processone/ejabberd/blob/master/src/mod_mam.erl#L189

**Comment by zinid** [comment]
If you don't need to process x:data configuration, then there is no easy way to store arbitrary values in the MUC room state (or on disc).

**Comment by andreabenini** [comment]
Thanks @zinid,
I was looking at `gen_fsm:sync_send_all_state_event(<THE.ROOM.PID>, get_state)` and the returned record is `state`, inside it I can see the record `config` where muc information are kept. On ejabberd startup each single room is a fsm and its information are loaded from db (sql in my case) on startup and then stored in memory. I was trying to add more info in the db but unfortunately I cannot keep personal info without modifying the record `config` (as noted from [your link](https://github.com/processone/ejabberd/blob/master/src/mod_mam.erl#L192) ). I guess I need to create an alternative mnesia memory table (on startup) and store my own personal data there. My module should have a mod_server behaviour in order to avoid sync locks or have performance issues. Is it the right approach ?


_btw: Thumbs up for this amazing project ! It has a really steep learning curve but there're a lot of hidden gems in it._


Ben

**Comment by andreabenini** [comment]
Seems pretty slack but I have decided to solve it in another way.
I'm now trying (under construction) to use muc vcard for storing extra fields and my module act as a wrapper between client and server so I can decide to save/restore/add/delete my own fields when needed
