### ISSUE TITLE
How can I create shared_group with "@" character in group name.

### ISSUE THREAD

**Issue by bvhoang91** [processone/ejabberd#1457]
Hi all,

I created some shared_roster_group like that "group@123", but when mod_shared_roster:split_grouphost is called, host and group name are converted to {123, group}. I googled this case but there are no document  mention "@" in group name. So, how can I fix issue without rename group?

Thanks,
Hoang.

**Comment by badlop** [comment]
I guess this is related to this feature mentioned in https://docs.ejabberd.im/admin/configuration/#modsharedroster:
> Displayed groups: A list of groups that will be in the rosters of this group’s members. A group of other vhost can be identified with groupid@vhost

So, in practice a groupid cannot contain the @ character, similarly to a username cannot contain the @ character, same happens with the roomname, etc.

> how can I fix issue without rename group?

Not possible.
