### ISSUE TITLE
Clustering Problem

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1459]
Hi

I'm using ejabberd 16.09 and I'm trying to setup a cluster with 2 nodes.
I've followed the guideline from this link:  https://docs.ejabberd.im/admin/guide/clustering/

1. I've made copy of my first node to another machine (with different host name of course), so the .erlang.cookie file is the same
2. Then I've executed the ejabberdctl join_cluster ejabberd@masternode  

And that worked so I can check with ejabberdctl list_cluster and see 2 nodes.

However while my clients are using the ejabberd server. If I stop the master node with /etc/init.d/ejabberd stop command all of my clients are disconnecting.
In case I would expect that clients continue to work because second node is still alive.

Do you know how can I solve that problem?
Thanks

**Comment by weiss** [comment]
The most common setup is that you have [SRV records][1] pointing to each of your nodes, and if one of them goes down, the clients connected to this one should auto-reconnect to one of the others.

[1]: https://wiki.xmpp.org/web/SRV_Records#XMPP_SRV_records

**Comment by tolgatanriverdi** [comment]
How can I add srv records in the computer which runs ejabberd master node

**Comment by cdroege** [comment]
You have to add it to your domain name, not the computer. Here is a description what a SRV record is: https://en.wikipedia.org/wiki/SRV_record

How you add it to your domain name depends who is running the dns server of your domain. If you run your own dns server, you add it there. If you are using a dns server provided by your domain name registrar or some other entity you add it there
