### ISSUE TITLE
Ejabberd Mysql config failed

### ISSUE THREAD

**Issue by maseruka** [processone/ejabberd#1460]
> What version of ejabberd are you using?
Ejabberd 16.12 (latest)

> What operating system (version) are you using?
Ubuntu 15.04 amd64

> How did you install ejabberd (source, package, distribution)?
ejabberd.run package

> What did not work as expected?

I have tried to configure sql connection to my sql server in my yml file but it gives me syntax error at line sql_type: mysql.
Attarched is my yml file and my error log file in a zip

[files.zip](https://github.com/processone/ejabberd/files/701231/files.zip)

**Comment by weiss** [comment]
The indentation is wrong: You must remove the space characters preceding the `sql_*` options.
