### ISSUE TITLE
Problem with ejabberd_mnesia

### ISSUE THREAD

**Issue by zinid** [processone/ejabberd#1461]
It seems like index processing in `ejabberd_mnesia.erl` is incorrect. For example, seems like this [line](https://github.com/processone/ejabberd/blob/master/src/ejabberd_mnesia.erl#L77) always deletes all indexes, at least `NewIndexes` is always an empty list, while `Indexes` is a list of all indexes. The function also consumes some time on loading `vcard_search` table.

**Comment by zinid** [comment]
Also, ejabberd_mnesia.erl slows down startup of ejabberd significantly. For example, without this file ejabberd loads modules for 3 vhost in several milliseconds, while with this module it loads them several *seconds*.

**Comment by cromain** [comment]
indeed, mnesia list indexes as list of integer while we maintain list if atoms, i fixed this.
also atted minor path to avoid i/o when this is needless, and removed manual attempts to add_table_index in the code.
