### ISSUE TITLE
Filter for `delete_old_users[_vhost]` command

### ISSUE THREAD

**Issue by rcoup** [processone/ejabberd#1462]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Linux; Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Source (https://github.com/rroemhild/docker-ejabberd)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

`ejabberdctl delete_old_users_vhost {host} {days}` works as described, but I suspect nearly everyone ends up creating a script to do this with some filtering. For me I want to filter the inactive users to prevent deleting administration/RPC accounts which don't "log in" regularly. Maybe via regex patterns?

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:26592)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1ch32t-00052q-0c
	for zero@thezeroworld.com; Thu, 23 Feb 2017 18:43:35 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=e4DbGK+oboAg8tzbWxG7CAJ7RuA=; b=tWaTBGthU5sE7WLX
	uRpDd6qYgbC72FElQDyJRf5s1cEyxHXWIFIFmEt3fU97ZMhA0DXfb7GhvmZu7kqm
	l9ZAJp0biwgthc5TLVmkQAPPGstniK5PPSto9CNa2qN2zFYVqypBUBlm7/bSodMG
	/4eil/8i3nQ6UfWGco58J1yt1+4=
Received: by filter0800p1mdw1.sendgrid.net with SMTP id filter0800p1mdw1-9211-58AF2C56-41
        2017-02-23 18:39:18.983578748 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id Q0OSYmqOQXOfEh6hwjpRxw
	for <zero@thezeroworld.com>; Thu, 23 Feb 2017 18:39:18.962 +0000 (UTC)
Date: Thu, 23 Feb 2017 10:39:18 -0800
