### ISSUE TITLE
mod_offline shutdown_error with reason noproc.

### ISSUE THREAD

**Issue by monkeyfdude** [processone/ejabberd#1464]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

ubuntu-14.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I found following in crash.log

     Supervisor: {local,ejabberd_sup}
     Context:    shutdown_error
     Reason:     noproc
     Offender:   [{pid,<0.413.0>},{id,'ejabberd_offline_localhost'},{mfargs,{mod_offline,start_link,[<<"localhost">>,[{access_max_user_messages,max_user_offline_messages}]]}},{restart_type,transient},{shutdown,1000},{child_type,worker}]

Why would this error occur? How can I prevent this from happening?

**Comment by zinid** [comment]
Do you have other errors?

**Comment by zinid** [comment]
Also, what erlang version?

**Comment by zinid** [comment]
Anyway, I think this [line](https://github.com/processone/ejabberd/blob/16.03/src/mod_offline.erl#L107) is redundant and may cause such side effects.

**Comment by monkeyfdude** [comment]
Thank you.
