### ISSUE TITLE
muc_invite hook is not being called

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1467]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Pull request #1338 introduced a new `muc_invite` hook that is documented (https://docs.ejabberd.im/developer/extending-ejabberd/hooks/) and mentioned in the release notes (https://blog.process-one.net/ejabberd-16-12/).

However, the code that calls the registered hooks was removed from `mod_muc_room.erl` in a recent merge commit (78a44e01762e00102f5e3e3f0b49690cc7866c31).

Please add the code that calls this hook again and a test that ensure it does not accidentally get removed in a future version. This blocks us and prevents upgrading to 16.12.

**Comment by marcphilipp** [comment]
Thanks for the quick turnaround! Is there an ETA for 17.01?

**Comment by zinid** [comment]
Tomorrow.
That's why I'm in hurry :)
