### ISSUE TITLE
Please provide a migration strategy for renamed room options

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1469]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

A number of room options, e.g. `muc#roomconfig_allow_subscription` and `muc#roomconfig_mam`, have been renamed from 16.09. Clients that try to set these options will get an error response. Would it be possible to support the old name, e.g. `muc#roomconfig_allow_subscription`, and the new name, e.g. `allow_subscription`, in parallel for at least one official release? This way, clients could be updated independently from the server while on that release.

**Comment by zinid** [comment]
Probably it would be easier to rename these fields back.
However, this is clearly a client bug, because it should not try to interpret/validate a data form.

**Comment by marcphilipp** [comment]
Well, when the client depends on MAM and MUC/SUB to work correctly it needs to set these options. When the names it expects are not present in the form, how should it guess the new names?

**Comment by zinid** [comment]
Are you OK if ejabberd doesn't provide old values in the form, but will accept them?
I'm searching for a cleaner way to fix this.

**Comment by marcphilipp** [comment]
If by accept you mean it will "map" them to the new field names and treat them in the same way, that should work for us.

**Comment by marcphilipp** [comment]
Thanks! 😊
