### ISSUE TITLE
Is there available send chat/group chat using HTTP?

### ISSUE THREAD

**Issue by bvhoang91** [processone/ejabberd#1471]
Hi all,

Because of some reasons, I want to send message via HTTP.
So, is there any option to enable this, if not, please give me some advice to build this fuction (I mean the flow it should be).

Tks,

**Comment by zinid** [comment]
There are HTTP transports implemented in ejabberd: BOSH (XEP-0206, XEP-0124) and Websocket (RFC7395).
However, there is no simple way to "just send a message": you need to login first which requires several round-trips.
Or you can use ejabberd HTTP API, which, AFAIR, has a method to "just send a message".

**Comment by badlop** [comment]
Looking with more detail, there are two questions here: how to execute an ejabberd command using a HTTP query, and what ejabberd command can you use to send a message.

First: There are two ejabberd frontends that accept HTTP queries to execute commands: mod_http_api, and mod_rest available in ejabberd-contrib repo. There's also ejabberd_xmlrpc which accepts XML-RPC queries.

Second: To send a normal message:
> $ ejabberdctl send_message chat user1@localhost user2@localhost nosubject HiUser2

However, to send a message to a groupchat, the user must first join the room, so this fails:
> $ ejabberdctl send_message groupchat user1@localhost room1@conference.localhost nosubject HiRoomFails

Solution: in the room enable subscriptions, then user1 subscribes to the room (see https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#toc_7 ), and that allows you to do this:
> ejabberdctl send_message groupchat user1@localhost room1@conference.localhost nosubject HiRoomWorks

**Comment by bvhoang91** [comment]
Thanks for response ;).

Because I want to trigger mod_carbon and store history for FromUser, Can I call user_send_message hook before router function?
In case group chat, user joined room in previous step.
What do you think about performance (execute request time) when compare with sending via xmpp in case a lot of request?

**Comment by badlop** [comment]
> Can I call user_send_message hook before router function?

You can try to add it to the source code. The worst that can happen is that it provokes a loop; you would notice that immediately, and better stop ejabberd before it consumes all RAM.

> What do you think about performance (execute request time) when compare with sending via xmpp in case a lot of request?

Looking at the command code in mod_admin_extra.erl, it is extremely simple, it just builds a basic packet and calls the router code. So, I guess it is as efficient as sending by xmpp.

**Comment by bvhoang91** [comment]
Yes, I seen. I call user_send_message hook with full FromUser JID, code work well. I think this code like xmpp flow where you call hook in ejabberd_c2s.
