### ISSUE TITLE
How to bypass ejabberd authentication based on resources using erlang module?

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1475]
Hello, 

I am new in ejabberd learning, I am using ejabberd community version source code, Operating system ejabberd installed is centOs 7. I am trying to bypass ejabberd sql authentication and also don't want to user external auth_method, for that i have created my own erlang module ejabberd_auth_test(this module is replica of sql auth module just added some customization) and set auth_method to 'test', this implementation works fine. 

Now, I want to bypass some of users (using some business logic to sort out users) from authentication based on resources, for client xmpp client i used strophe js processone (connect through http-binding). 
```js
function Connect() { 
                        var userId = userInfo.UserId; 
                        xmpp_user = userId + "@" + xmpp_Domain + "/" + getRandomResourceId(); 
                        var xmpp_password = ''; 

                        if (xmpp_ServerConnection !== null) { 

                                try { 
                                        delete xmpp_ServerConnection; 
                                        console.log("deleted existing connection"); 
                                } 
                                catch (err) { 
                                        console.log(err); 
                                } 

                        } 

                        xmpp_ServerConnection = new Strophe.Connection(xmpp_Server); 
                        xmpp_ServerConnection.connect(xmpp_user, xmpp_password, conn_callback); 
                } 
```
can anyone suggest how it can be done ?, 

Thanks in advance !! 

-Veer

**Comment by zinid** [comment]
The problem is that authentication precedes resource binding, so during authentication (SASL) phase server knows nothing about resources.

**Comment by Veerbhadra277** [comment]
Thanks for reply zinid,
ok, but only based on username how can we bypass authentication from my custom authentication module 
ejabberd_auth_test ?

**Comment by zinid** [comment]
you can always return `true` in check_password callback.

**Comment by Veerbhadra277** [comment]
Thanks zinid for quick response and I appreciate your suggestion !!

but check_password method doesn't get call at all, only get_password method called, here are the snippet of my code, 
![check_password](https://cloud.githubusercontent.com/assets/8426382/22138731/182da7e8-df08-11e6-84ae-c0aa9185df1f.PNG)

I put logs to check, for client i am using stropeJS which uses httpbind for connection.

-Veer

**Comment by zinid** [comment]
This probably means the backend isn't get called at all. Do you have other functions called? `is_user_exists` for example.

**Comment by Veerbhadra277** [comment]
No, is_user_exists also not get called, only get_password method get called. please find following snippet for client side

![image](https://cloud.githubusercontent.com/assets/8426382/22141313/752960b8-df17-11e6-8482-c8db65ea74e4.png)

in yml i have put auth_method as test

![image](https://cloud.githubusercontent.com/assets/8426382/22141395/e854661e-df17-11e6-94b8-59ec56b7c6bf.png)

-Veer

**Comment by zinid** [comment]
I cannot say anything from the Strophe snippet, as I'm not into Javascript.
It would be much better if you show XML stream output.

**Comment by Veerbhadra277** [comment]
please find logs below:-

[ejabberd.txt](https://github.com/processone/ejabberd/files/718994/ejabberd.txt)

following is yml file :-

[ejabberd.txt](https://github.com/processone/ejabberd/files/719013/ejabberd.txt)

I hope this will help, 
-Veer

**Comment by zinid** [comment]
It's indeed hard to understand why other callbacks are not called.
Can you post your ejabberd_auth_test.erl if possible?

**Comment by zinid** [comment]
And what exact ejabberd version are you using?

**Comment by Veerbhadra277** [comment]
I am using ejabberd community version 16.09 source code, please find attached ejabberd_auth_test below.

[ejabberd_auth_test.txt](https://github.com/processone/ejabberd/files/719116/ejabberd_auth_test.txt)

**Comment by zinid** [comment]
OK, I now see the problem is in SCRAM authentication, seems like for this auth check_password is not needed, only get_password. Is it important for you to use SCRAM SASL? If not, you can disable it in ejabberd and Strophe should automatically pick another available mechanism (I think):
```yaml
disable_sasl_mechanisms:
  - "SCRAM"
```

**Comment by Veerbhadra277** [comment]
No I don't want SRAM SASL, I have put above entry in ejabberd.yml, right ?

**Comment by zinid** [comment]
Right, sorry I didn't mention it ;)

**Comment by zinid** [comment]
Ah, not "SCRAM", it's "SCRAM-SHA-1".

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:29669)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cUXUP-0002Y9-7S
	for zero@thezeroworld.com; Fri, 20 Jan 2017 06:36:17 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6r6K2w8hwPj9Y9jtPsnw1bYYEus=; b=hJXPATlkkfWqjJvg
	FK4ldcb1+t23s5WLvvFHv1X2nWkXs0FVeGe1F4QMFnfPITZFyHldss3BDDzXEa10
	+wvQlT2a2lDEAjBb+5AnH2xFJgkL57/0HGS/EESuEAH3BXOmogp4JdIpx3GyvKD7
	jCafa24recXyIvOB6b6M50xLN0w=
Received: by filter1136p1mdw1.sendgrid.net with SMTP id filter1136p1mdw1-4296-5881F5FB-36
        2017-01-20 11:35:23.215413363 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id i-tuHsxTRv6zswpn82lB9w
	for <zero@thezeroworld.com>; Fri, 20 Jan 2017 11:35:23.147 +0000 (UTC)
Date: Fri, 20 Jan 2017 03:35:23 -0800

**Comment by Veerbhadra277** [comment]
Hi zinid,

@zinid Sorry for the delay in replying, 

I tried with suggestions given by you, and it worked for me, thanks a lot for your precious time. 

I couldn't find 'disable_sasl_mechanisms' in latest ejabberd.yml example from ProcessOne community version source code.

Regards,
Veer

**Comment by zinid** [comment]
It's indeed not in [ejabberd.yml.example](https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example), but is described in the [documentation](https://docs.ejabberd.im/admin/configuration)

**Comment by Veerbhadra277** [comment]
Thanks again !! :) 
I am closing this issue.
