### ISSUE TITLE
Message Archive Management (mod_mam) does not handle Query with <before/> correctly

### ISSUE THREAD

**Issue by anagromataf** [processone/ejabberd#1476]
To get the recent messages I'm creating a request with a RSM using an empty `<before/>` element as documented in [XEP-0059 2.5. Requesting the Last Page in a Result Set](https://xmpp.org/extensions/xep-0059.html#last):

```
<?xml version="1.0"?>
<iq xmlns="jabber:client" from="romeo@example.com" to="romeo@example.com" type="set" id="367b2">
  <query xmlns="urn:xmpp:mam:1" queryid="4a5d">
    <set xmlns="http://jabber.org/protocol/rsm">
      <max>20</max>
      <before/>
    </set>
  </query>
</iq>
```

The server responses with the first 20 messages in the archive (at leat I'm sure that the server does not respond with the last 20 messages). I would expect the last messages to easily get the recent conversation and start paging backwards in time.

I'm using the master branch build from sources on Ubuntu.

**Comment by zinid** [comment]
It's strange, this case is quite common and is tested in our test suite.
What database backend are you using? Mnesia or SQL?

**Comment by anagromataf** [comment]
I'm using the mnesia backend. I can double check and have a look what's actually stored in the database. But I'm sure, that the last messages I write via that server/account where not returned.

**Comment by zinid** [comment]
I'll double check too. But only tomorrow, it's too late here.

**Comment by zinid** [comment]
Here is what I get:
```xml
<message id="aac8a" to="user1@localhost" type="chat">
  <body>1</body>
  <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>

<!-- here goes 2,3,4,5,6,7,8,9 -->

<message id="aad1a" to="user1@localhost" type="chat">
  <body>10</body>
  <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>

<iq id="juliet1" type="set">
  <query queryid="f27" xmlns="urn:xmpp:mam:1">
    <set xmlns="http://jabber.org/protocol/rsm">
      <max>5</max>
      <before/>
    </set>
  </query>
</iq>

<message from="user1@192.168.1.1" to="user1@192.168.1.1/zinid">
  <result id="1484899476474154" queryid="f27" xmlns="urn:xmpp:mam:1">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message from="user1@192.168.1.1/zinid" id="aacda" to="user1@localhost" type="chat" xml:lang="en" xmlns="jabber:client">
        <active xmlns="http://jabber.org/protocol/chatstates"/>
        <body>6</body>
      </message>
      <delay from="192.168.1.1" stamp="2017-01-20T08:04:36.474154Z" xmlns="urn:xmpp:delay"/>
    </forwarded>
  </result>
</message>

<!-- Here goes 7,8,9 -->

<message from="user1@192.168.1.1" to="user1@192.168.1.1/zinid">
  <result id="1484899482650598" queryid="f27" xmlns="urn:xmpp:mam:1">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message from="user1@192.168.1.1/zinid" id="aad1a" to="user1@localhost" type="chat" xml:lang="en" xmlns="jabber:client">
        <active xmlns="http://jabber.org/protocol/chatstates"/>
        <body>10</body>
      </message>
      <delay from="192.168.1.1" stamp="2017-01-20T08:04:42.650598Z" xmlns="urn:xmpp:delay"/>
    </forwarded>
  </result>
</message>

<iq from="user1@192.168.1.1" id="juliet1" to="user1@192.168.1.1/zinid" type="result" xml:lang="en">
  <fin complete="false" queryid="f27" xmlns="urn:xmpp:mam:1">
    <set xmlns="http://jabber.org/protocol/rsm">
      <count>10</count>
      <first>1484899476474154</first>
      <last>1484899482650598</last>
    </set>
  </fin>
</iq>
```

**Comment by anagromataf** [comment]
Hm … I just did the same test. I created a new account and send the messages "1" to "30". After requesting the recent 20 messages, I got the correct result "11" to "30". Will have a look at the other account, where I mentioned an issue.

**Comment by anagromataf** [comment]
I added some detailed logging to my client to get all transmitted stanzas. The problem is still there with an existing (old account). Could it be, that this is some kind of migration issue from an older version of jabbed to a newer version?

To verify the issue, I send a message with the text "1234" right now (~ 20 Jan 2017 12:00 ).

```
<message xmlns="jabber:client" from="info@tobias-kraentzer.de" to="romeo@intercambio.im" id="1807137e-1bb1-4d00-9614-70a8179f0b4e" type="chat">
  <body>1234</body>
  <origin-id xmlns="urn:xmpp:sid:0" id="68837baf-9c54-4305-9779-220d21bf66d4"/>
</message>
```

Doing the request for the recent messages, I get the following response (I removed the content, because those are real messages):

```
<iq xmlns="jabber:client" from="info@tobias-kraentzer.de" to="info@tobias-kraentzer.de" type="set" id="3ec1b1ee-e617-4e43-b15e-25462a43f58d">
  <query xmlns="urn:xmpp:mam:1" queryid="5e2048e3-217f-4208-b9c7-36b242720bef">
    <set xmlns="http://jabber.org/protocol/rsm">
      <max>20</max>
      <before/>
    </set>
  </query>
</iq>

<message xmlns="jabber:client" to="info@tobias-kraentzer.de/4034304139082696687182" from="info@tobias-kraentzer.de">
  <result xmlns="urn:xmpp:mam:1" id="1477687885482818" queryid="5e2048e3-217f-4208-b9c7-36b242720bef">
    <forwarded xmlns="urn:xmpp:forward:0">
      <!-- message --> 
      <delay xmlns="urn:xmpp:delay" from="tobias-kraentzer.de" stamp="2016-10-28T20:51:25.482818Z"/>
    </forwarded>
  </result>
</message>

<!--
    all the other messages
-->

<message xmlns="jabber:client" to="info@tobias-kraentzer.de/4034304139082696687182" from="info@tobias-kraentzer.de">
  <result xmlns="urn:xmpp:mam:1" id="1478557814655396" queryid="5e2048e3-217f-4208-b9c7-36b242720bef">
    <forwarded xmlns="urn:xmpp:forward:0">
      <!-- message -->
      <delay xmlns="urn:xmpp:delay" from="tobias-kraentzer.de" stamp="2016-11-07T22:30:14.655396Z"/>
    </forwarded>
  </result>
</message>

<iq xmlns="jabber:client" to="info@tobias-kraentzer.de/4034304139082696687182" from="info@tobias-kraentzer.de" type="result" id="3ec1b1ee-e617-4e43-b15e-25462a43f58d">
  <fin xmlns="urn:xmpp:mam:1" complete="false" queryid="5e2048e3-217f-4208-b9c7-36b242720bef">
    <set xmlns="http://jabber.org/protocol/rsm">
      <count>264</count>
      <first>1477687885482818</first>
      <last>1478557814655396</last>
    </set>
  </fin>
</iq>
```

The first message returned is from `2016-10-28` the last form `2016-11-07`. Non of them is from today.

**Comment by zinid** [comment]
Why would you expect messages from today? `<before/>` means the archive gets searched from oldest to newest messages. In order to get the newest message you should remove `<before/>` and set `max=1`

**Comment by zinid** [comment]
See https://xmpp.org/extensions/xep-0059.html#last

**Comment by anagromataf** [comment]
Isn't this, what I did?

I have messages 1…n, n+1 in my archive. Where message 1 is the first (from the past) and n+1 is the last (most recent one form today).

> The requesting entity MAY ask for the last page in a result set by including in its request an empty &lt;before/&gt; element, and the maximum number of items to return.

If I'm doing the request as described above (empty &lt;before/&gt, max=5) I'm expecting the last 5 messages (n-3 …, n, n+1) which is in my understanding the last page (including the most recent message I just send today). But the most recent message is not included in the response.

The same issue is with (empty &lt;before/&gt, max=1). I don't get the most recent message.

**Comment by anagromataf** [comment]
It really might be a issue of the format of the record of the archive in mnesia. Has this changed in the past?

If I want to delete old messages I get the following error:

```
>>> /opt/sbin/ejabberdctl delete_old_mam_messages chat 30
Problem 'exit {aborted,{badarg,[archive_msg,
                                {<<"liseb92">>,<<"intercambio.im">>}]}}' occurred executing the command.
Stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,318}]},
             {mod_mam_mnesia,delete_old_user_messages,3,
                             [{file,"src/mod_mam_mnesia.erl"},{line,96}]},
             {mod_mam_mnesia,delete_old_messages,3,
                             [{file,"src/mod_mam_mnesia.erl"},{line,72}]},
             {lists,map,2,[{file,"lists.erl"},{line,1239}]},
             {mod_mam,delete_old_messages,2,
                      [{file,"src/mod_mam.erl"},{line,370}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,329}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]}]
```

If this is a problem with the format, it's fine for me to just delete the archive. There not so much on that server.

**Comment by weiss** [comment]
> It really might be a issue of the format of the record of the archive in mnesia. Has this changed in the past?

It has changed with ejabberd 15.09 when MUC MAM was added.

**Comment by zinid** [comment]
> If I'm doing the request as described above (empty <before/&gt, max=5) I'm expecting the last 5 messages (n-3 …, n, n+1) which is in my understanding the last page (including the most recent message I just send today).

No

**Comment by anagromataf** [comment]
I think the media table was corrupted or not correctly migrated. I did these days an update to ejabberd 16.12 and don't know, which version I used before (last update was some time ago).
