### ISSUE TITLE
Stanza-id (XEP-0359) in archived Messages

### ISSUE THREAD

**Issue by anagromataf** [processone/ejabberd#1477]
> What version of ejabberd are you using?

current master branch (16.12.42)

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In order to identify the messages, all messages (also those send in response to an archive query) should contain a stanza-id. Without the stanza-id it is not possible to finde duplicates reliably.

In the current implementation, the stanza-id is not contained in the response form the archive query.

For example, I received the carbon copy

```xml
<message xmlns="jabber:client" to="romeo@example.com/client" from="romeo@example.com" type="chat">
  <sent xmlns="urn:xmpp:carbons:2">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message xmlns="jabber:client" to="juliet@example.com" from="romeo@example.com/client" type="chat" id="C9D5C21A-76E1-4A86-A0DA-322E8876D0CA">
        <archived xmlns="urn:xmpp:mam:tmp" by="romeo@example.com" id="1484932689806334"/>
        <stanza-id xmlns="urn:xmpp:sid:0" by="romeo@example.com" id="1484932689806334"/>
        <body>...</body>
      </message>
    </forwarded>
  </sent>
</message>
```

then this result is missing the stanza-id

```xml
<message xmlns="jabber:client" to="romeo@example.com/client" from="romeo@example.com">
  <result xmlns="urn:xmpp:mam:1" id="1484932689806334" queryid="4120e0ae-cf47-47f5-b839-f2ce16fba6a8">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message xmlns="jabber:client" to="juliet@example.com" from="romeo@example.com/client" type="chat" id="C9D5C21A-76E1-4A86-A0DA-322E8876D0CA">
        <active xmlns="http://jabber.org/protocol/chatstates"/>
        <body>...</body>
      </message>
      <delay xmlns="urn:xmpp:delay" from="romeo@example.com" stamp="2017-01-20T17:18:09.806334Z"/>
    </forwarded>
  </result>
</message>
```

I don't know, if this is related to https://github.com/processone/ejabberd/issues/1344

In general each message should contain an stanza-id when entering the system. Maybe this could be done independently of the mam archiving of the message.

**Comment by zinid** [comment]
Done
