### ISSUE TITLE
Missing stanza-id in Message (from offline storage)

### ISSUE THREAD

**Issue by anagromataf** [processone/ejabberd#1480]
> What version of ejabberd are you using?

17.01.45

> What operating system (version) are you using?

Ubuntu Linux

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm receiving a message without a stanza-id. It might be from the offline storage.

```xml
<message xmlns="jabber:client" to="romeo@example.com" from="juliet@example.com" type="chat" id="402466435698">
    <delay xmlns="urn:xmpp:delay" from="example.com" stamp="2017-01-23T16:37:22.445939Z">Offline storage</delay>
    <body>...</body>
</message>
```

To not having duplicate messages in the local client archive, the stanza-is are needed in all messages.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:44175 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1ch288-00036c-IA
	for zero@thezeroworld.com; Thu, 23 Feb 2017 17:44:56 -0500
Date: Thu, 23 Feb 2017 08:36:12 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1487867772;
	bh=Y8srR05IkgE1HkZUNDYFX4ye1h1CTa66QE1ATAGzOA0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rGtjVknHVPcYnRMysSdvJdPRzoafBlLhRJhqNmgD2FLxBCGalfoV+56ZHRPlADuXF
	 6Tjp3OESfS2eetnJThwYFkYcIba5lLPaBOgZa+05ryY6WjAOlHKmfKODyM+De4aqtQ
	 wiXj9C7tl9Y+a9XA5jbv3vUSTAZJtAIcgdEID99Y=
