### ISSUE TITLE
vcard get hook ?

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1481]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Linux AMD64

> How did you install ejabberd (source, package, distribution)?

downloaded binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'd like to place an hook, an handler or whatever it's possible to detect this kind of messages:
```
<iq to='redroom@conference.myowndomain' id='get1' type='get'>
    <vCard xmlns='vcard-temp'/>
</iq>
```
This is obviously a vcard get request for a conference room, I'm not interested in **that** particular room, I need an hook to get them all. Is it possible with an hook, I'd like to avoid `filter_packet` hook because I guess it's too cpu/memory intensive. Is there something else I could/should use ?
There's `vcard_set`, I do not necessarily need its counterpart but is there something I should use to get it ?

**Comment by zinid** [comment]
If you need to track MUC vcards, you can use `muc_process_iq` hook.
Otherwise, you probably have to use `filter_packet` (but maybe `user_send_packet` is enough, depending on the exact requirements).

**Comment by andreabenini** [comment]
Thanks for your ultrafast reply,
I'll probably use muc_process_iq (tomorrow morning, it's late) because user_send_packet is user related and hopefully muc_process_iq is executed even when rooms are loaded from the engine itself.
I'll keep you updated
Thanks

**Comment by andreabenini** [comment]
Thanks Zinid, I have solved.
There're other hooks (muc_filter_packet and filter_packet) but I'll keep muc_process_iq as you suggested because is triggered as a vcardGet (iq, get, vcard-temp) and it seems to be less invasive.
BTW, I was thinking to upgrade my source project to get latest news from upcoming 17.01 (mostly because I need pubsub/mucsub features) but it seems I'll have a lot of pain with it because hooks parameters are slightly changed in these months (2 params instead of 4 !)

**Comment by zinid** [comment]
In 17.02 there will be even more changes, please wait for 17.02-beta.

**Comment by andreabenini** [comment]
So if I need to pickup my next "stable/LTS" version should it be nice to wait for upcoming 17.02 ?
I'm aware that my modules/code wouldn't last forever and few edits are always needed, but I'm trying to minimize these efforts and (hopefully) benefit from newer features (mobile/pubsub mostly), it's not a trouble for me to wait for a while. I have only few (~10) custom modules (quite big ones) but I have a lot of process/2 (HTTP), add_iq_handler, SQL select/4/5/6 so my upgrade must be wisely planned :)

**Comment by zinid** [comment]
Current interface (already present in `master` branch) will not be changed drastically. So you can slowly investigate new API and probably start rewriting.
Let us know if you have question. We can help on migration.
