### ISSUE TITLE
mod_http_upload custom_headers config not loaded from ejabberd.yml

### ISSUE THREAD

**Issue by lbadias** [processone/ejabberd#1482]
I'm new to ejabberd, I'm trying to get mod_http_upload running, from an Android client file upload is working ok, but from a web client I'm getting an error, something like: No 'Access-Control-Allow-Origin' header is present on the requested resource.
I have already modified the config file like this:

mod_http_upload:
    ...
    custom_headers: 
        "Access-Control-Allow-Origin": "*" 
        "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
 
But nothing happen, no headers are returned when the OPTIONS query is executed.

Any idea?

I set loglevel to 5, but the response is not fully logged out

...
2017-01-23 16:26:35.030 [debug] <0.651.0>@mod_http_upload:process:489 Responding to OPTIONS request from 192.168.0.85 for 192.168.0.85

Thanks in advance

**Comment by weiss** [comment]
Yes, currently the `custom_headers` option is ignored unless the domain part of the `put_url` matches the XMPP domain.

**Comment by lbadias** [comment]
Thanks for clarifying that out! Just one more question, this will not impact when you have multiple virtual hosts? I'm pretty new to ejabberd, so maybe I'm making an absurd question, if that's the case, please feel free to close this issue.
Thanks

**Comment by weiss** [comment]
> this will not impact when you have multiple virtual hosts?

This will work:

    hosts:
      - "example.com"
      - "example.net"
    # [...]
    modules:
      mod_http_upload:
        put_url: "https://@HOST@/share"
        custom_headers: # [...]

So it will also work with multiple virtual hosts as long as the domain part of the `put_url` is `@HOST@`.

> I'm pretty new to ejabberd, so maybe I'm making an absurd question, if that's the case, please feel free to close this issue.

No, this should definitely work with arbitrary URLs, you just stumbled over a bug :-)  The issue should remain open until it's fixed.

**Comment by weiss** [comment]
As another workaround, with ejabberd 17.04 and newer you can also specify `custom_headers` as a listener option, e.g.:

    listen:
      -
        module: ejabberd_http
        request_handlers:
          "upload": mod_http_upload
        custom_headers:
          "Access-Control-Allow-Origin": "*"
          "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
          "Access-Control-Allow-Headers": "Authorization"
          "Access-Control-Allow-Credentials": "true"
        # [...]
