### ISSUE TITLE
TLS not working in 17.01

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1484]
> What version of ejabberd are you using?

17.01.45

> What operating system (version) are you using?

debian

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I was using direct TLS  instead of starttls using tls option in ejabberd.yml for my 16.x version 
with upgrade its not working after analysing found there is no option for 
TLSEnabled = proplists:get_bool(tls, Opts) as it was in 16.x  can we have this 17.x  we have a large deployment and changing this will affect many clients.
```
Accepted connection xxx.xxx.97.119:7598 -> xxx.xxx.0.2:5222
11:45:11.445 [error] CRASH REPORT Process <0.342.0>
 with 0 neighbours exited with reason: no_certfile in gen_server:init_it/6 line 322
11:45:11.445 [error] Supervisor ejabberd_c2s_sup had child undefined
 started with {ejabberd_c2s,start_link,undefined} at <0.342.0>
 exit with reason no_certfile in context child_terminated
```

Thanks

**Comment by nOmi7** [comment]
```
TLSOpts1 = case ejabberd_config:get_option(
		      {c2s_certfile, LServer},
		      fun iolist_to_binary/1,
		      ejabberd_config:get_option(
			{domain_certfile, LServer},
			fun iolist_to_binary/1)) of
		   undefined -> [];
		   CertFile -> lists:keystore(certfile, 1, DefaultOpts,
					      {certfile, CertFile})
	       end,
```

looks like above code always returns [] .... is this how it should be ... i thought it should work something like ejabberd_c2s_config:get_c2s_limits()

**Comment by nOmi7** [comment]
changed to 
```
TLSOpts1 = case ejabberd_config:get_option(
		      {c2s_certfile, LServer},
		      fun iolist_to_binary/1,
		      ejabberd_config:get_option(
			{domain_certfile, LServer},
			fun iolist_to_binary/1)) of
		   undefined -> DefaultOpts;  /// added defaultopts here
		   CertFile -> lists:keystore(certfile, 1, DefaultOpts,
					      {certfile, CertFile})
	       end,
```

after making above change its working is correct ? can i open pull request for the same ?

**Comment by zinid** [comment]
Yes, open please.

**Comment by zinid** [comment]
Please also check if s2s code is ok in this regard.

**Comment by nOmi7** [comment]
ok i have changed in s2s too however is the change i made correct ? 
How do i create a pull request I have a fork on internal gitlab server

**Comment by zinid** [comment]
> ok i have changed in s2s too however is the change i made correct ?

I don't know, I didn't see your changes :)

> How do i create a pull request I have a fork on internal gitlab server

I'm not sure it's possible to create PRs from gitlab to github.

**Comment by nOmi7** [comment]
how to use new 
     domain_certfile, c2s_certfile, c2s_ciphers, c2s_cafile,
     c2s_protocol_options, c2s_tls_compression
options
change i made was 
undefined -> DefaultOpts;  from existing  undefined -> [];

**Comment by zinid** [comment]
I didn't understand, just pull the request.
Or don't bother, I will fix it later myself.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (8/7 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:44182)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cW2LC-0005OR-NC
	for zero@thezeroworld.com; Tue, 24 Jan 2017 09:44:59 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=SRIz692dt1Nozuh+QX6ZANwKjJg=; b=MN+04hQsIdkVAhHS
	riPrSxroSapE3TnBFsFPEbGrcRl2C776Jvb7CqVLzQBsvEiJgF1V6HYCLV4pAr+1
	u6WiUP6V05XTU3SqnmRJyxFdfp8bPo/tpEl9wkh7BoRWl6Fkxb8kYziwpXHuSxyc
	HYL/SlxCtAbXnJc7qy7cz3OHgTc=
Received: by filter0418p1mdw1.sendgrid.net with SMTP id filter0418p1mdw1-16829-58876841-17
        2017-01-24 14:44:17.190418014 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id YIQAI6SmRUyrbL3hq7IFEQ
	for <zero@thezeroworld.com>; Tue, 24 Jan 2017 14:44:17.226 +0000 (UTC)
Date: Tue, 24 Jan 2017 06:44:17 -0800
