### ISSUE TITLE
[mod_service_log] logging to bandersnatch broken

### ISSUE THREAD

**Issue by p5n** [processone/ejabberd#1489]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

ArchLinux

> How did you install ejabberd (source, package, distribution)?

package ejabberd 17.01-2

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

on 16.08 logging to bandersnatch worked:
```
mod_service_log:
    loggers: ["bandersnatch.domain..."]
```
however on 17.01 it produces:
```
2017-01-25 18:30:08.491 [error] <0.962.0>@ejabberd_router:route:81
 failed to decode xml element
 {xmlel,<<"route">>,[],[{iq,<<"291">>,error,<<"en">>,{jid,<<"...">>,<<"...">>,<<>>,<<"...">>,<<"...">>,<<>>},{jid,<<"...">>,<<"...">>,<<"Gajim">>,<<"...">>,<<"...">>,<<"Gajim">>},[{pubsub_owner,undefined,undefined,undefined,undefined,<<"storage:bookmarks">>,undefined},{stanza_error,cancel,404,<<>>,'item-not-found',{text,<<"en">>,<<"Node not found">>},[]}],#{}}]}
 when routing from .... to bandersnatch....: Unknown tag <route/> qualified by namespace 'jabber:client'

```
When I commented out mod_service_log module from config ejabberd works but obviously without logging to bandersnatch.

**Comment by p5n** [comment]
I already posted full config in https://github.com/processone/ejabberd/issues/1410#issuecomment-271401356

**Comment by zinid** [comment]
I can't believe somebody is using it.
Yes, it's broken in 17.01, because it's using awkward nonza (`<route/>`) within 'jabber:client' namespace.

**Comment by p5n** [comment]
Is there any way now to pass all messages to some script?

**Comment by zinid** [comment]
No, but there is mod_mam now, you should store message there.

**Comment by p5n** [comment]
It is bad :S. I store jabber message history to IMAP Chats folder similar to gmail.
