### ISSUE TITLE
question: muc change_config, how can I change a room configuration ?

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1490]
Hi,
I'm trying to change a muc configuration while running, under certain circumstances I need to manually update the room VCARD, after looking at mod_muc_room source code I have seen what it does.
MUCs are using the gen_fsm behaviour so I have tried to get muc PID
```
{value, #muc_online_room{pid=RoomPID}} = lists:keysearch({RoomName, ConferenceHost}, 2, ets:tab2list(muc_online_room)),
```
Now with the PID I can change the room config:
```
Result = gen_fsm:sync_send_all_state_event(RoomPID, {change_config, Config}),
```
Where `Config` contains a valid configuration for that room. This usually works on debug command line but I'm trying to use it after from a function called in a **muc_process_iq** hook.
In this situation _Result_ is not set and an exception is raised (`Throw=exit, Error={timeout,{gen_fsm,sync_send_all_state_event,[<0.7423.2>,{change_config,{config,<<"...`), just like what Erlang does when you call a gen_server:call inside another gen_server:call.
I can understand this kind of error so the real question is: how can I change a room configuration when called from a muc_process_iq hook ?

Thanks
Ben

**Comment by andreabenini** [comment]
additional info:
What I'm trying to do is change the room config between this request
```
<iq to='redroom@conference.mydomain' id='get1' type='get'>
    <vCard xmlns='vcard-temp'/>
</iq>
```
and the server reply
```
<iq from="redroom@conference.mydomain" type="result" to="user@mydomain/psiRes" id="get1">
<vCard xmlns="vcard-temp">
....
</vCard>
</iq>
```

**Comment by zinid** [comment]
It seems like you cannot do this in a clean way.

**Comment by andreabenini** [comment]
I have seen it and I really don't know how to circumvent it.
I'm using **muc_process_iq** hook and when I get a package like ``<iq to='someroom@conference.mydomain' type='get|set'>`` I'd like to change something in my room, how can I do that ? mod_muc is a FSM so I guess the only way to change its internal memory data is to use `gen_fsm:sync_send_all_state_event` from that hook, is there any other way ?

Thanks

**Comment by tsaqova** [comment]
@cromain @andreabenini 
I got the same issue like @andreabenini state above, I need to change a room configuration via **muc_process_iq** hooks, is there any solution to this problem before it's closed?
