### ISSUE TITLE
ejabberd installation

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1492]
1)  We have 2 servers debian 7 (development) and debian 8 (production).
In debian 7 the repository installs ejabberd 2.1.10 but in debian 8 version 14. is available.

In 2.1.10 mod_mam is not available? But i do want to see my message archive from all platforms, this means I do need to upgrade to debian 8 or is there another way to install the same version.

2) I also want to send push notifications when a user is offline, but mod_zeropush does not exist anymore. Is there another module available?

Thx in advance.

**Comment by badlop** [comment]
1. mod_mam is included only in recent ejabberd versions. You can compile ejabberd from source code, just make sure your debian 7 has an erlang version supported by the ejabberd you want to compile. Or you can download compiled ejabberd binaries, which include erlang.

**Comment by cromain** [comment]
As badlop said, in your case best option is to use our binary installer, or our .deb if it works on your older version.
