### ISSUE TITLE
ejabberd_http /admin creates complaints "The process <0.876.0> is consuming too much memory:"

### ISSUE THREAD

**Issue by haegar** [processone/ejabberd#1498]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?
debian jessie

> How did you install ejabberd (source, package, distribution)?
source (git from tag 17.01), erlang 1:18.3.4.4+dfsg-1~bpo8+1
using mysql with scram'ed passwords as the backend storage

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Was just clicking around in the webinterface below /admin, defined as

  - 
    port: 5281
    ip: "::"
    module: ejabberd_http
    ## request_handlers:
    ##   "/pub/archive": mod_http_fileserver
    web_admin: true
    http_poll: true
    http_bind: true
    ## register: true
    captcha: true
    tls: true
    certfile: 'CERT_LOCATION'
    dhfile: 'DHPARAM_LOCATION'
    ciphers: 'TLS_CIPHERS'
    protocol_options: 'TLS_OPTIONS'

and then the jabber server started sending me (as the admin) a lot of messages:

[22:00:45] <jabber.sdinet.de> (ejabberd@jabber) The process <0.876.0> is consuming too much memory:
[{old_heap_block_size,833026},
 {heap_block_size,318187},
 {mbuf_size,0},
 {stack_size,18071},
 {old_heap_size,791062},
 {heap_size,81703}]
[{current_function,{scram,hi_round,3}},
 {initial_call,{proc_lib,init_p,5}},
 {message_queue_len,0},
 {links,[#Port<0.21818>,#Port<0.21819>]},
 {dictionary,[{'$ancestors',[<0.511.0>,ejabberd_listeners,ejabberd_sup,
                             <0.38.0>]},
              {'$initial_call',{ejabberd_http,init,2}}]},
 {heap_size,318187},
 {stack_size,19741}] 

Did not see any real functional problems, or really high daemon memory usage, just receiving annoying messages.

So the question if not a real bug is more like: how to silence this?

Greetings
Haegar

**Comment by zinid** [comment]
Do you have `watchdog_large_heap` option set?

**Comment by haegar** [comment]
watchdog_admins:
  - "haegar@jabber.sdinet.de"

was the only option with "watchdog" in the name set. I have disabled it now.

Thanks.
