### ISSUE TITLE
Separate list of strings with \n for srg_get_info in mod_http_api

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#1500]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Jessie-Backports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

srg_get_info works correctly via XML-RPC and ejabberdctl, but not via HTTP API, where the field "displayed_groups" is returned as a single string without separation of groups (should be a list).

Here's an example for the problem with srg_get_info:
```
### ejabberdctl:
 name Group1
 displayed_groups        **["Group1","Group2","Group3"]**
 description whatever

### XML-RPC:
{'informations': [{'information': [{'key': 'name'}, {'value': 'Group1'}]},
  {'information': [{'key': 'displayed_groups'},
    {'value': '**["Group1","Group2","Group3"]**'}]},
  {'information': [{'key': 'description'}, {'value': 'whatever'}]}]}

### HTTP API:
[{'key': 'name', 'value': 'Group1'},
 {'key': 'displayed_groups',
  'value': **'Group1Group2Group3'**},
 {'key': 'description',
  'value': 'whatever'}]
```

As you can see, the result for displayed_groups obtained via HTTP API is impossible to parse (as arbitrary group names are possible) and thus quite useless.

Note: as long as Holger's mod_push hasn't been ported to newer releases I cannot upgrade to newer ejabberd versions.

**Comment by badlop** [comment]
Right, this happens because result should be string, but in this case it's a list of strings, and mod_http_api.erl does this:
```
iolist_to_binary(["group1","group2","group3"]).                   
<<"group1group2group3">>
```
I guess this special circumstance could be detected, and separate the group ids with \n characters, for example:
```
iolist_to_binary(string:join(["group1","group2","group3"], "\n")).
<<"group1\ngroup2\ngroup3">>
```
Would that be an acceptable solution?

**Comment by debalance** [comment]
Yes it would!

**Comment by badlop** [comment]
I've committed a fix, and I tested it works. Anyway, when you have a chance, try it and report if it works correctly, or there's any problem with it.
