### ISSUE TITLE
ejabberdctl: UUID Shell Script Permission Denied - Ubuntu 14.04 to 16.04 Upgraded

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#1504]
> What version of ejabberd are you using?

self compiled latest version 17.01; and since version 16.04

> What operating system (version) are you using?

Ubuntu 16.04 upgraded from 14.04

> How did you install ejabberd (source, package, distribution)?

compiled from source with configuration options:
sudo ./configure --exec_prefix=/usr --enable-pam --enable-mysql –-enable-elixir --enable-user=ejabberd

> What did not work as expected? Are there error messages in the log? What

Manual starting up ejabberd with $sudo /etc/init.d/ejabberd start
will produce the following error on terminal:
```
Starting jabber server: ejabberd/usr/sbin/ejabberdctl:
 line 385: /proc/sys/kernel/random/uuid:
 Permission denied erl_child_setup closed
```
Except for the error message on terminal, the ejabberd server seems to work properly.
Note: start ejabberd with "$sudo /etc/init.d/ejabberd live" is ok OR on system reboot.
 
> was the unexpected behavior? What was the expected result?

Manual start up ejabberd should run without the above error messages:

More info as shown below (reported back in July 14th, 2016 on Ubuntu forum but receive no reply):
======================================
The ejabberd has a bash script (/usr/sbin/ejabberdctl) with properties as
"-r-xr-x--- 1 root root 14287 Jul 14 10:01 ejabberdctl" 
containing a statement to generate a uuid as below:

#!/bin/bash
...
uuid=$(uuidgen 2>/dev/null)
[ -z "$uuid" -a -f /proc/sys/kernel/random/uuid ] && uuid=$(</proc/sys/kernel/random/uuid)
....

After launched the application (ejabberd - source compiled with version 16.07 and now 17.01);
$ cd /var/sbin
then issues
$ sudo ./ejabberdctl status
will always aborted due to "permission denied" on the above two uuidgen statement. (found the root cause/reason after extensive debug)

However if I issue "$ sudo bash ./ejabberdctl status" then the script returns the correct status result i.e.
The node ejabberd@engsvr is started with status: started
ejabberd 16.07 is running in that node

Alternative if I copy the ejabberdctl to ejabberdctl_new file, then I can just issue "$ sudo ./ejabberdctl_new status" and also get the correct returned results.

=====earlier ejabberdctl script =========
Strangely the similar problem also happens with the earlier ejabberdctl script which use sh script:
#!/bin/sh 
CTL_LOCKFILE=/var/lock/ejabberdctl/ejabberdctl-1 #(example)
...
exec 8>"$CTL_LOCKFILE"
.....

The exact solution described above also applied in the case i.e. "$ sudo bash ./ejabberdctl status" or execute the duplicated file e.g. ejabberdctl_org
Note: $ "sudo sh ./ejabberdctl status" also works in this case for sh script file

============

I am not sure if the problem arises because of the Ubuntu 14.04 to 16.04 upgrading process. I do not have the problem with old script before the 16.04 upgrade.
Any help is appreciated.

**Comment by cromain** [comment]
There are several possible fixes:
1/ get uuidgen binary
2/ or, in ejabberdctl, comment the line checking for /proc/sys/kernel/random/uuid
3/ or check ejabberd's user rights to access /proc/sys/kernel/random/uuid

in any case, you should not sudo.
option 1 or 2 should fix your problem.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:33615)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1ceOTA-0004u5-8I
	for zero@thezeroworld.com; Thu, 16 Feb 2017 10:59:44 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=eD1lmbKy3u+TPJLbkQ8TtnxOoK8=; b=fAoZAN+/1HP99g5+
	fPrpcRlUQK0J+voW4vJEepjyqXjIZAfDlrbCxjRYdO4KhhPj3v7EdItaKQIPYX0J
	udnq+sO4UWW0g8Cr70DCmHyW+Ev659l6/yAcnBLFEQ4BIpCHX1BDsWXXmbkl33Rc
	BUKj0Q5L5GCciF4Gzz/ZyE3GXsM=
Received: by filter0469p1mdw1.sendgrid.net with SMTP id filter0469p1mdw1-29183-58A5CBF9-30
        2017-02-16 15:57:45.619685023 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0023p1mdw1.sendgrid.net (SG) with ESMTP id -H-h6RSvTqyckTdKBxBYKQ
	for <zero@thezeroworld.com>; Thu, 16 Feb 2017 15:57:45.616 +0000 (UTC)
Date: Thu, 16 Feb 2017 07:57:45 -0800

**Comment by cmeng-git** [comment]
Thanks for the feedback. I started using ejabberd since 2.17 with package installed directly from Ubuntu 14.04 Ubuntu Software Center. The default directory and user installed was different from the ejabberd source build. Since then I have been configured the ejabberd source build with the following option: 
sudo ./configure --exec_prefix=/usr --enable-user=ejabberd
This may have created some unique problem in my case.

1/ get uuidgen binary
The system is already installed with uuid-runtime.

2/ or, in ejabberdctl, comment the line checking for /proc/sys/kernel/random/uuid
Below is the code in ejabberdctl, I am not sure what is the side effect to command out as it is being used in many other ejabberdctl commands. I really like to understand why copying ejabberdctl to ejabberdctl_new, even both has the same access right and owner, behave differently i.e. ejabberdctl_new work without the explicit 'bash' in the command. Also /etc/init.d/ejabberd uses ejabberdctl and may cause problem when starting up ejabberd without the uuid in place.

-----------
uid()
{
    uuid=$(uuidgen 2>/dev/null)
    [ -z "$uuid" -a -f /proc/sys/kernel/random/uuid ] && uuid=$(</proc/sys/kernel/random/uuid)
    [ -z "$uuid" ] && uuid=$(printf "%X" $RANDOM$(date +%M%S)$$)
    uuid=${uuid%%-*}
    [ $# -eq 0 ] && echo ${uuid}-${ERLANG_NODE}
    [ $# -eq 1 ] && echo ${uuid}-${1}-${ERLANG_NODE}
    [ $# -eq 2 ] && echo ${uuid}-${1}@${2}
}
--------------

3/ or check ejabberd's user rights to access /proc/sys/kernel/random/uuid
cmeng@engsvr:~$ ls -la /usr/sbin/ejabberdctl
-r-xr-x--- 1 root ejabberd 13926 Feb 14 22:01 /usr/sbin/ejabberdctl

The above is the default access right and owner for ejabberdctl assigned during source build, This is the reason why I need sudo to execute the ejabberdctl.

**Comment by digz6666** [comment]
@cmeng-git I've had same issue with my Ubuntu 16.04.03 as I copied ejabberdctl to ejctl and it's working now.
