### ISSUE TITLE
ejabberd 17.01 has problem in starting up when captcha is enabled

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#1505]
> What version of ejabberd are you using?

version 17.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Compiled from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

On system startup, ejabberd 17.01 has error in captcha option initialization: Following is the log of the problem.
Manual start up the ejabberd with $sudo /etc/init.d/ejabberd start is OK.

---------------- ejabberd.log ---------------------
```
2017-01-31 10:13:24.769 [debug] <0.410.0> Supervisor ejabberd_sup started
 ejabberd_local:start_link() at pid <0.433.0>
2017-01-31 10:13:29.773 [error] <0.435.0>@ejabberd_captcha:do_create_image:342
 Failed to process an output from "/usr/lib/ejabberd/priv/bin/captcha.sh 357921": timeout
2017-01-31 10:13:29.773 [critical] <0.435.0>@ejabberd_captcha:check_captcha_setup:489
 Captcha is enabled in the option captcha_cmd, but it can't generate images.
2017-01-31 10:13:29.773 [error] <0.435.0> CRASH REPORT
 Process ejabberd_captcha with 0 neighbours exited with reason:
 bad return value: {error,captcha_cmd_enabled_but_fails} in gen_server:init_it/6 line 356
2017-01-31 10:13:29.774 [error] <0.410.0>
 Supervisor ejabberd_sup had child ejabberd_captcha
 started with ejabberd_captcha:start_link() at undefined exit with reason
 bad return value: {error,captcha_cmd_enabled_but_fails} in context start_error
2017-01-31 10:13:30.386 [info] <0.31.0> Application p1_mysql started on node ejabberd@engsvr
2017-01-31 10:13:30.386 [error] <0.62.0> CRASH REPORT
 Process <0.62.0> with 0 neighbours exited with reason:
 no such process or port in call to
 gen_server:call(ejabberd_sup, {start_child,{'ejabberd_sql_sup_atalk.org',
 {ejabberd_sql_sup,start_link,[<<"atalk.org">>]},transient,...}}, infinity)
 in application_master:init/4 line 134
2017-01-31 10:13:30.387 [info] <0.31.0> Application ejabberd exited with reason:
 no such process or port in call to gen_server:call(ejabberd_sup,
 {start_child,{'ejabberd_sql_sup_atalk.org',
 {ejabberd_sql_sup,start_link,[<<"atalk.org">>]},transient,...}}, infinity)
```

**Comment by badlop** [comment]
Try executing this, it should return a lot of weird characters:
> /usr/lib/ejabberd/priv/bin/captcha.sh 357921

Then, if you execute this, it should produce a valid image than you can view with any program:
> /usr/lib/ejabberd/priv/bin/captcha.sh 357921 >image.png

**Comment by github-tomster** [comment]
i had a similar issue. it was caused by app-armor. i had to re-profile the /etc/apparmor.d/local/usr.sbin.ejabberdctl profile.

**Comment by cmeng-git** [comment]
Hi tomster:
Would appreciate if you can provide more information on how to resolve the issue. i.e.
What are the changes made to the profile and steps taken to resolve the problems.

**Comment by github-tomster** [comment]
first check your syslog for errormessages regarding apparmor when starting ejabberd.service
and related to ejabberdctl and captcha.sh
if yes follow this guide: http://wiki.apparmor.net/index.php/Documentation

**Comment by github-tomster** [comment]
hi cmeng
any progress?

**Comment by cmeng-git** [comment]
Thanks for checking back. The reported problem does not appear anymore. I am not sure what has actually happened. However I did performed a few software updates triggered from Ubuntu Software Updater - not sure if this has actually resolved the problem. I am running Ubuntu 16.04. 

Actually I have another problem when I upgraded from ejabberd 16.08 to 17.01. I am facing ejabberd bound_offline_messages when I send a message from my android aTalk xmpp chat client to an offline contact; similar error message also happen on other xmpp clients that I have tested.. I did not experienced such problem in ejabberd 16.08 (actually I did some customization on ejabberd 16.08 to allow sending messages to an offline group member). I did not make any customization in ejabberd 17.01. I did not spent much time to debug the ejabberd actual cause, as I also developing aTalk.
Not sure if you also see the problem in ejabberd 17.01 for offline message support.

Note: aTalk is an android xmpp client developed by me, it is a fork from jitsi-android. aTalk is free (will release as open source in future) and  can be downloaded from my home server. Any interest parties are welcome to use the aTalk application:
http://atalk.sytes.net/releases/atalk-android/aTalk-release.apk

==== error log for offline message ================
2017-02-09 06:50:32.323 [debug] <0.912.0>@ejabberd_c2s:send_text:1629 Send XML on stream = <<"<message xml:lang='en' to='leopard@atalk.org/atalk' from='abc123@atalk.org' type='error' id='14865942506081029985539'><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User session not found</text></error><body>Testing offline message</body><thread>X9egu0</thread></message>">>

**Comment by badlop** [comment]
The original problem does not appear, so this ticket is closed. If there is another problem, it takes another ticket.
