### ISSUE TITLE
Failing SSL request through httpc

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1506]
> What version of ejabberd are you using?

Ejabberd Community Version source code 16.09 release

> What operating system (version) are you using?

CentOs 7

> How did you install ejabberd (source, package, distribution)?

source

from one of the module i am giving call to ssl api through 'httpc' please find http
```
try httpc:request(get,  {"Https://www.testchat.com/home/getDetails",
 [{"Cookie", binary_to_list(Context)}]}, [], [{sync, true}]) of
    {ok, {{_, 200, _}, _Headers, Body}} ->
      ?INFO_MSG("Body --> ~p~n", [Body]),
```
for above call I am getting following error:
```
2017-01-30 15:03:19.955 [error] <0.4484.0>@ejabberd_auth_test:is_test_web_authorized:457
 Error in request. Reason was:
 {failed_connect,[{to_address,{"www.testchat.com",443}},{inet,[inet],closed}]}
```
I have enabled TLS in yml, following is 
```
   certfile: "/home/testusr/Certificates/Ejabberd_cert/server.pem"
   tls: true
   s2s_certfile: "/home/testusr/Certificates/Ejabberd_cert/server.pem"
```

can anyone help me to solve this issue? I am new in ejabberd wold !

Regards,
Veer

**Comment by badlop** [comment]
I start ejabberd in live mode by running: ejabberdctl live

So I have ejabberd started and an erlang console to execute erlang calls, in it I run this, and it connects correctly:
```
(ejabberd@localhost)2> httpc:request(get, {"Https://www.testchat.com/home/getDetails", []}, [], [{sync, true}]).

{ok,{{"HTTP/1.1",403,"Forbidden"},
     [{"connection","keep-alive"},
      {"date","Wed, 01 Feb 2017 11:54:27 GMT"},
      {"server","nginx"},
      {"vary","Accept-Encoding"},
      {"content-length","162"},
      {"content-type","text/html"},
      {"keep-alive","timeout=5"}],
     "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"}}
```

**Comment by Veerbhadra277** [comment]
can you please try with this url 

https://www.staytunedchat.com/StayTuned/Account/Login

-Veer

**Comment by Veerbhadra277** [comment]
Also observer weird behavior server hosted on azure cloud platform giving same error, I got same error for following url
https://azure.microsoft.com/en-in/services/app-service/web/

where as hosted with aws workes fine, for example following url
https://aws.amazon.com/ 

Thanks,
Veer

**Comment by Veerbhadra277** [comment]
Worked !!! 

force TLS version here:

httpc:request(get, {"https://api.datamarket.azure.com", []}, [{ssl, [{versions, ['tlsv1']}]}, {autoredirect, false}], []).

Refered following mail thread
http://erlang.org/pipermail/erlang-questions/2016-September/090244.html

-Veer
