### ISSUE TITLE
/bin/sh: 1: @ctlscriptpath@/ejabberdctl: not found

### ISSUE THREAD

**Issue by github-tomster** [processone/ejabberd#1511]
> What version of ejabberd are you using?

17.01
i upgraded from 16.09

> What operating system (version) are you using?

ubuntu 16.04.1 LTS x86_64

> How did you install ejabberd (source, package, distribution)?

apt.jabber.at
https://apt.jabber.at/pool/ejabberd/e/ejabberd/ejabberd_17.01-1~ubuntu16.04_amd64.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

after the update the `sudo service ejabberd restart` failed with exitcode 127 not found
i researched and finally came across this:
`/lib/systemd/system/ejabberd.service` before update:
```
[Unit]
Description=A distributed, fault-tolerant Jabber/XMPP server
After=epmd.service network.target
Requires=epmd.service

[Service]
Type=forking
User=ejabberd
Group=ejabberd
LimitNOFILE=65536
Restart=on-failure
RestartSec=5
ExecStart=/bin/sh -c '/usr/sbin/ejabberdctl start && /usr/sbin/ejabberdctl started'
ExecStop=/bin/sh -c '/usr/sbin/ejabberdctl stop && /usr/sbin/ejabberdctl stopped'
PIDFile=/run/ejabberd/ejabberd.pid
PrivateDevices=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
Alias=ejabberd.service
```
`/lib/systemd/system/ejabberd.service `after the update:
```
[Unit]
Description=A distributed, fault-tolerant Jabber/XMPP server
After=epmd.service network.target
Requires=epmd.service

[Service]
Type=forking
User=ejabberd
Group=ejabberd
LimitNOFILE=65536
Restart=on-failure
RestartSec=5
ExecStart=/bin/sh -c '@ctlscriptpath@/ejabberdctl start && @ctlscriptpath@/ejabberdctl started'
ExecStop=/bin/sh -c '@ctlscriptpath@/ejabberdctl stop && @ctlscriptpath@/ejabberdctl stopped'
PIDFile=/run/ejabberd/ejabberd.pid
PrivateDevices=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
Alias=ejabberd.service
```

the error in systemlog showed: `/bin/sh: 1: @ctlscriptpath@/ejabberdctl: not found`
however `sudo ejabberctl start` worked and started the node working.
i manually edited the ejabberd.service
did a reload service et voila: `sudo service ejabberd restart`
is working again.

so why are these `@ctlscriptpath@` inside?

**Comment by badlop** [comment]
The file ejabberd.service is built from ejabberd.service.template when running "make install", see Makefile.in:
```
        # Service script
        $(SED) -e "s*@ctlscriptpath@*$(SBINDIR)*g" ejabberd.service.template \
                > ejabberd.service
        chmod 644 ejabberd.service
```
When I compile and install ejabberd 17.01 from git repo, the file is built correctly. Maybe in your system sed is not installed, or not detected correctly, or the package simply copies the file without replacing that string...?

**Comment by github-tomster** [comment]
in my package list it lists::
```
Package Details
Description 	Unknown
Package 	sed 	Class 	P-T
Version 	4.2.2-7 	Vendor 	Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture 	amd64 	Installed 	Unknown
```
strange though.
is there a hint what i should also check/verify. although my errorlog has no entrys so far.
