### ISSUE TITLE
Segmentation fault on Ejabberd 14.07

### ISSUE THREAD

**Issue by shanjianping** [processone/ejabberd#1513]
We're using ejabberd 14.07, with fast_xml 1.1.15, run on Amazon Linux AMI CentOS 64 bit. We build the ejabberd from source code ourself

We've 3 nodes, recently there was the crashes in all of the nodes, following is the callstack:
(gdb) bt
#0  sweep_one_area (n_hp=0x7f550b831970, n_hp@entry=0x7f550b7d2028, n_htop=0x7f550b831990, n_htop@entry=0x7f550b7d21b8, src=src@entry=0x7f5107f1b028 "T\001", src_size=src_size@entry=1572752) at beam/erl_gc.c:1811
#1  0x000000000055d45c in do_minor (nobj=9, objv=0x7f58bf04e2c0, new_sz=196650, p=<optimized out>) at beam/erl_gc.c:1096
#2  minor_collection (recl=<synthetic pointer>, nobj=9, objv=0x7f58bf04e2c0, need=2, p=<optimized out>) at beam/erl_gc.c:880
#3  erts_garbage_collect (p=0x7f549cb96b50, need=2, objv=0x7f58bf04e2c0, nobj=9) at beam/erl_gc.c:452
#4  0x000000000043f2df in process_main () at x86_64-unknown-linux-gnu/opt/smp/beam_hot.h:1845
#5  0x00000000004cfcaa in sched_thread_func (vesdp=0x7f58ca13df40) at beam/erl_process.c:8021
#6  0x000000000061fe3b in thr_wrapper (vtwd=<optimized out>) at pthread/ethread.c:114
#7  0x00007f58cc5addc5 in start_thread (arg=0x7f58a9d74700) at pthread_create.c:308
#8  0x00007f58cc0d2c9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

(gdb) etp-stacktrace p
% Stacktrace (56): #Cp<lists:umergel/3+0x388>.
#Cp<gb_sets:from_list/1+0x48>.
#Cp<zxm_util:remove_dups/1+0x58>.
#Cp<zxm_mem_cacher:get_online_group_users/2+0x100>.
#Cp<zxm_mem_cacher:get_all_online_group_users/2+0x88>.
#Cp<mod_zxm_presence:get_presence_notify_list/3+0x190>.
#Cp<ejabberd_c2s:presence_broadcast/4+0x160>.
#Cp<ejabberd_c2s:terminate/3+0x1000>.
#Cp<p1_fsm:terminate/8+0x1a0>.
#Cp<proc_lib:init_p_do_apply/3+0x58>.
#Cp<terminate process normally>.

(gdb) etp-stackdump p
% Stackdump (56): #Cp<lists:umergel/3+0x388>.
#Cp<gb_sets:from_list/1+0x48>.
......
session_established.
ejabberd_c2s.
{'$gen_event',{xmlstreamerror,<<"XML stanza is too big">>}}.
<0.25176.1135>.
normal.
#Cp<terminate process normally>.
#Catch<129>.

**Comment by prefiks** [comment]
Hello, problems with garbage collection are pretty hard to diagnose but i will see what i can do with it, could you please tell me which erlang version is used in your deployment?

**Comment by shanjianping** [comment]
otp 18.2.1, thanks

**Comment by cromain** [comment]
this duplicates #1420
