### ISSUE TITLE
chat history

### ISSUE THREAD

**Issue by stephensworld** [processone/ejabberd#1515]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

ubuntu

> How did you install ejabberd (source, package, distribution)?

from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is it possible to receive messages on all my devices with the same user logged in.
and if I (User A) write a message to User B the written message should be also available on other devices where User A is logged in.

The same as skype or imessage...

Thank you very much.

Stephan

**Comment by badlop** [comment]
For that, the message should be sent to the bare JID address (just providing username and host, not the resource), for example, instead of sending to user2@localhost/HomeResource, just send like this:
```
<message id='333:537459'
	type='chat'
	to='user2@localhost'>
  <body>Hi</body>
</message>
```
In that case, the message is delivered by all the clients where user2@localhost is logged in.

**Comment by Langlife2** [comment]
Very good answer
