### ISSUE TITLE
RSM doesn't work properly for PubSub if we update item.

### ISSUE THREAD

**Issue by shahdarshan1711** [processone/ejabberd#1516]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Cent OS 7.1

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Suppose, particular pubsub node has 4 items. I queried items giving max=3 in RSM. It will send me recent 3 items with _first_ and _last_ tag and _count_ as 4. After that, I update 4th item. Now if I query next set of item using _after_ tag giving the _last_ value, it doesn't return any Item. 

Reason is, here pagination is done based on modification time, So that we get recent published/updated item first. But in this case it is not working as modification time is changed for 4th item. Shouldn't it be based on creation time which doesn't change during item's lifecycle? 

Darshan

**Comment by cromain** [comment]
that's a good question ! let's think about it

**Comment by cromain** [comment]
This make sense, change was applied.
