### ISSUE TITLE
clustering ejabberd_commands

### ISSUE THREAD

**Issue by sepasti** [processone/ejabberd#1519]
> What version of ejabberd are you using?

ejabberd 16.06 
ejabberd 16.08
ejabberd 16.09

> What operating system (version) are you using?

> How did you install ejabberd (source, package, distribution)?

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi.   ejabberd 16.06 , 16.08,16.09 not working after clustering.After restart nodes in cluster,node crash 
Nodes is running and operational, In summary ejabberdctl is not usable at this state. 
Except ejabberdctl status is working and anothers command return this error:

ejabberdctl list_cluster command:
################################################################
Problem 'exit {aborted,
                  {no_exists,
                      [ejabberd_commands,
                       [{{ejabberd_commands,'$1','_','_','_','$2','_','_',
                             '_','_','_','_','_','_','_','_'},
                         [{'==','$1',{const,list_cluster}},
                          {'=<','$2',{const,1000000}}],
                         [{{'$2','$_'}}]}]]}}' occurred executing the command.
Stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,313}]},
             {ejabberd_commands,get_command_definition,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,419}]},
             {ejabberd_commands,get_command_format,3,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,381}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,318}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]
###################################################################
 Ejabberd 16.04 and 16.02  work fine.when restart ejabberd node in cluster, it return this error and is not started:
###############################################################
0.20064.1> CRASH REPORT Process <0.20064.1> with 0 neighbours exited 
with reason: {aborted,{bad_type,{ejabberd_commands,gen_html_doc_for_commands,[documentation],"Generates html documentation for ejabberd_commands",[],0,ejabberd_commands_doc,generate_html_output,[{file,binary},{regexp,binary},{examples,binary}],restricted,[],{res,rescode},["Path to file where generated documentation should be stored","Regexp matching names of commands or modules that will be included inside generated document","Comma separated list of languages (choosen from java, perl, xmlrpc, json)that ..."],...}}} in application_master:init/4 line 134
2017-02-06 15:58:36.195 [info] <0.20033.1> Application ejabberd exited with reason: {aborted,{bad_type,{ejabberd_commands,gen_html_doc_for_commands,[documentation],"Generates html documentation for ejabberd_commands",[],0,ejabberd_commands_doc,generate_html_output,[{file,binary},{regexp,binary},{examples,binary}],restricted,[],{res,rescode},["Path to file where generated documentation should be stored","Regexp matching names of commands or modules that will be included inside generated document","Comma separated list of languages (choosen from java, perl, xmlrpc, json)that ..."],...}}}
#######################################################################
I change src/ejabberd_cluster.erl from this link(https://github.com/processone/ejabberd/issues/1210) but not working.
How fix that, 
thanks in advance.

**Comment by badlop** [comment]
> I change src/ejabberd_cluster.erl from this link(#1210) but not working.

Are you sure your patched beam is being used?

Clustering works correctly for me using ejabberd git (a little more updated than 17.01), and all commands work.

> Hi. ejabberd 16.06 , 16.08,16.09 not working after clustering.After restart nodes in cluster,node crash
Nodes is running and operational, In summary ejabberdctl is not usable at this state.

In which order do you restart the nodes? First the master and later the slave? Or first the slave? Reduce the steps to produce the error, and tell me the steps so I can reproduce it.

Also, try ejabberd 17.01 if you can try it.

**Comment by cromain** [comment]
I guess you upgraded from a previous version and may have missed some upgrade process.
If unsure, while running on 1 node only, you should explicitly remove the command table with this ejabberd debug command
mnesia:delete_table(ejabberd_commands). 
then, restart that node.
then, start other node and call join_cluster.
