### ISSUE TITLE
17.x changes 

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1523]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

in older version when there was change in roster , or privacy list the mod_roster . mod_priv used to send a broadcast with {item,xxx} and {privacylist,xxx}  how does this happen now ?

I new version hows this taken care how do i update the map from c2s on change of my custom key of c2s map

**Comment by zinid** [comment]
This is now handled via `c2s_handle_info` hook. You can look into mod_roster or mod_privacy in order to understand how to work with it.

**Comment by zinid** [comment]
Ah, sorry, it rewrote it, it's now handled using `meta` fields in stanzas. For example, in mod_privacy see `push_list_update/3` and `user_recieve_packet/1`.

**Comment by zinid** [comment]
However, `c2s_handle_info` hook is still an option in the case you don't want to route any stanzas, but just update c2s state.

**Comment by nOmi7** [comment]
Sure thanks will try it out

**Comment by nOmi7** [comment]
@zinid one more thing .. 
Is there a way i can execute in parallel without writing a pid code for message passing as in 

Say i got packet p1 for updating username 
what i do currently
rcv p1 packet -> update username -> broadcast changes to p1 contacts  -> reply success to the p1 sender

what i want to do 

rcv p1 packet -> update username  |  ---> reply success to the p1 sender
                                                         |
                                                         |
                                                         | --->  broadcast changes to p1's contact 

do both independent things in parallel ?

**Comment by zinid** [comment]
How do you update a username? Inserting something into database?

**Comment by zinid** [comment]
I'm also not sure why you bother about parallel evaluation. If you use `ejabberd_router:route/3` the packets get dispatched into relevant c2s/s2s pids automatically and thus, will be almost executed in a parallel.

**Comment by nOmi7** [comment]
> How do you update a username? Inserting something into database?
    yes update in db 

> I'm  also not sure why you bother about parallel evaluation. If you use ejabberd_router:route/3 the packets get dispatched into relevant c2s/s2s pids automatically and thus, will be almost executed in a parallel.

   before pushing it to router_multicast I do some privacy check (this is custom implementation) 
so if a user has 50 members in its contact it does check for 50 ppl and till then response to sender is blocked.

Its not just about sending tho .. If i want to process some function independently how can i do it ?

**Comment by zinid** [comment]
Well, from the scarce info I have, I would say you need to craft some parallel eval via process spawning.

**Comment by nOmi7** [comment]
for the original issue where i need to update c2sstate you said it should be handled by put_meta ..
I see how its implemented in mod_privacy and mod_roster however I dont see any instance where get_meta is used as in get the change is routed via put_meta but i dont see anywhere in c2s / sm / that its retrived and state is changed.

**Comment by zinid** [comment]
There is direct mattern matching `#meta{some_field => Value}`. You're not obligated to use `xmpp:get_meta()`.
