### ISSUE TITLE
Re-authing SIP in a cluster.

### ISSUE THREAD

**Issue by Polidore22** [processone/ejabberd#1525]
> What version of ejabberd are you using?

 16.09

> What operating system (version) are you using?

 Ubuntu 16.04 - Latest Patches

> How did you install ejabberd (source, package, distribution)?

 I installed using the .deb distribution.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hey guys. I have a question about clustering using SRV records with SIP. During each request we are resolving the IP address. Then when we have to re-auth it's resolving to the other IP from the SRV record and results in an endless loop since the initial request is from a different IP than the second one resolved. Is there anything on the ejabberd side we could try to solve this?

Thank you,
Andy

**Comment by Polidore22** [comment]
Relevant RFC: https://www.ietf.org/rfc/rfc3263.txt

**Comment by zinid** [comment]
I do not understand why this loop occurs. Could you elaborate? Do you mean the UAC (client) is unable to authenticate at all?
We also have deployed `mod_sip` in a 2-node cluster with SRV balancing and don't face this problem.

**Comment by Snwspeckle** [comment]
The issue being asked is the same as this issue: https://github.com/alfredh/baresip/issues/39.

**Comment by zinid** [comment]
On the ticket, it is said, that a proxy server doesn't accept the nonce, but ejabberd doesn't generate node-specific nonces, so it should be accepted.

**Comment by zinid** [comment]
The reporter is inactive, I close the issue.
