### ISSUE TITLE
Compile fails when included as an Elixir dependency

### ISSUE THREAD

**Issue by safwank** [processone/ejabberd#1526]
> What version of ejabberd are you using?

17.1

> What operating system (version) are you using?

Mac OS 10.12.3

> How did you install ejabberd (source, package, distribution)?

Hex.pm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

@mremond Starting in 16.12, compiling `ejabberd` as a dependency fails because it can't find `fast_xml` and `xmpp` headers. After some digging, I narrowed it down to the following line in `mix.exs`

https://github.com/processone/ejabberd/blob/master/mix.exs#L60

which works fine if you compile `ejabberd` directly as the main application, but fails if it's included as a dependency because the location of `deps` is obviously different. To work around the problem, I've done the following

https://github.com/safwank/ejabberd/blob/deps_includes_17.1/mix.exs#L59 

It's definitely not ideal, but it works. I'm wondering if there's a better way of going about it, or if you're happy with the "fix", I can submit a PR for it.

**Comment by safwank** [comment]
Should I submit a PR for this?

**Comment by cromain** [comment]
Hi,

We are aware of this and are looking for a good fix for 17.03. If we don't get good design solution, we'll apply change like yours which just works.

**Comment by safwank** [comment]
@cromain Thanks. I look forward to the fix.

**Comment by cromain** [comment]
I do not master mix yet, but this version looks a bit better anyway.
