### ISSUE TITLE
jabberd 17.01 offline message hook gives error

### ISSUE THREAD

**Issue by ForGuru** [processone/ejabberd#1527]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

Centos

> How did you install ejabberd (source, package, distribution)?

Package Installed

> What did not work as expected? Are there error messages in the log? What

```
-module(mod_imran_offline).
-author('iggg').

-behaviour(gen_mod).

%% Required by ?INFO_MSG macros
-include("logger.hrl").

-export([start/2, stop/1,on_offline/4]).

start(_Host, _Opts) ->
    ?INFO_MSG("Hello, ejabberd world!", []),
    ejabberd_hooks:add(offline_message_hook, _Host, ?MODULE, on_offline, 10),
    ok.

stop(_Host) ->
    ?INFO_MSG("Bye bye, ejabberd world!", []),
    ejabberd_hooks:delete(offline_message_hook, _Host, ?MODULE, on_offline, 10),
    ok.

on_offline(_User, _Server, _Resource, _Packet) ->
    ?INFO_MSG("Posting From ~p Body ~p~n",[_User, _Packet]),
    none.
```

> was the unexpected behavior? What was the expected result?

> 2017-02-09 05:36:45.825 [error] <0.660.0>@ejabberd_hooks:run1:332 
{undef,[{mod_offline_test,on_offline,[{jid,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>},{jid,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>},{message,<<"B094705E-3F0B-4AA2-9630-C5A6DEEE7033">>,chat,<<>>,{jid,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>},{jid,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>},[],[{text,<<>>,<<"Rrrrrrr">>}],undefined,[],#{}}],[]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},{ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},{ejabberd_sm,route,3,[{file,"src/ejabberd_sm.erl"},{line,126}]},{ejabberd_local,route,3,[{file,"src/ejabberd_local.erl"},{line,110}]},{ejabberd_router,route,3,[{file,"src/ejabberd_router.erl"},{line,87}]},{ejabberd_c2s,check_privacy_route,5,[{file,"src/ejabberd_c2s.erl"},{line,1886}]},{ejabberd_c2s,session_established2,2,[{file,"src/ejabberd_c2s.erl"},{line,1170}]}]} running hook: {offline_message_hook,[{jid,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>},{jid,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>},{message,<<"B094705E-3F0B-4AA2-9630-C5A6DEEE7033">>,chat,<<>>,{jid,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>,<<"FROM-JID">>,<<"MY-SERVER-NAME">>,<<"RESOURCE">>},{jid,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>,<<"TO-JID">>,<<"MY-SERVER-NAME">>,<<>>},[],[{text,<<>>,<<"Rrrrrrr">>}],undefined,[],#{}}]}

**Comment by badlop** [comment]
In 17.01, your function receives only three arguments: From, To and Packet.
In the next release (and in git), your function will receive four arguments:  Acc, From, To, and Packet.

As example, see the function store_packet in mod_offline.erl

**Comment by zinid** [comment]
I'd like to add that in the upcoming release there will be only a single argument.
So probably it's better to wait for 17.02 (or whatever the version it will be).

**Comment by badlop** [comment]
So, the code that was like
> offline_message_hook(From, To, Packet) ->

now, since ejabberd 17.03, looks like
> offline_message_hook({Action, Packet}) ->

**Comment by closedDoor** [comment]
I modified the original offline post module to work with Ejabberd 17.04.
https://gist.github.com/closedDoor/bd7f10b7e426142f0e117015cf754a7b

```
-module(mod_offline_post).
-author('test@test.org').
-behaviour(gen_mod).


-export([start/2,
	 init/2,
	 stop/1,
	 send_notice/1]).

-define(PROCNAME, ?MODULE).


-include("ejabberd.hrl").
-include("xmpp.hrl").
-include("logger.hrl").

start(Host, Opts) ->
    ?INFO_MSG("Starting mod_offline_post", [] ),
    register(?PROCNAME,spawn(?MODULE, init, [Host, Opts])),  
    ok.

init(Host, _Opts) ->
    inets:start(),
    ssl:start(),
    ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 100),
    ok.

stop(Host) ->
    ?INFO_MSG("Stopping mod_offline_post", [] ),
    ejabberd_hooks:delete(offline_message_hook, Host,
			  ?MODULE, send_notice, 10),
    ok.


send_notice({Action,Packet}) ->	
		
	From = element(5,Packet),
	To = element(6,Packet),
	
	From1 = From#jid.luser,
	To1 = To#jid.luser,
		
	Body = binary_to_list(element(3,lists:nth(1,element(8,Packet)))),
		
    PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url,fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	Token = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, auth_token, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	
	Data = string:join(["to=", binary_to_list(To1), "&from=", binary_to_list(From1), "&body=", Body], ""),
	Request = {binary_to_list(PostUrl), [{"Authorization", binary_to_list(Token)}], "application/x-www-form-urlencoded", Data},
	httpc:request(post, Request,[],[]),
			
	ok.
```
