### ISSUE TITLE
ejabberd_sm or ejabberd_router

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1528]
> What version of ejabberd are you using?
17,x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

When to use ejabberd_sm:route and when to user ejabberd_router:route ?

I have custom module which does some processing and later sends packet to processed members 
I am not sure should i used route from sm or route from router ? some light would help me to route my packet right way.

**Comment by zinid** [comment]
I assume the question is answered.
