### ISSUE TITLE
Problem using ejabberd on windows 10

### ISSUE THREAD

**Issue by Okezie** [processone/ejabberd#1530]
> What version of ejabberd are you using?

version 17.01

> What operating system (version) are you using?

windows 10

> How did you install ejabberd (source, package, distribution)?

through binary

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

each time i try to run the ejabberd server it displays
```
ERROR: The ejabberd node ejabberd@localhost is registered
       and should be running.
If ejabberd is already stopped and you still get this
message, then call 'epmd -kill'.
```

thanks and await your response

**Comment by cromain** [comment]
message is self explanatory, you have an ejabberd process already running, or an old process were not stopped correctly and is still registered in epmd.

If you don't have any ejabberd process running (check for beam process), then just force kill epmd process. If you don't see epmd, try kill it manually in command prompt
C:
cd \Program Files\ejabberd-17.01\bin
epmd -kill

this will solve your error.
