### ISSUE TITLE
Can't modify default node (ejabberd@localhost)

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1532]
What version of ejabberd are you using?

Ejabberd Community Version source code 16.09 release

    What operating system (version) are you using?

CentOs 7

    How did you install ejabberd (source, package, distribution)?

source

Hi,
I am trying to implement clustering and when i try to start ejabberd with mysql config it says this:

16:35:16.512 [critical] Node name mismatch: I'm [ejabberd@osboxes], the database is owned by [ejabberd@localhost]
16:35:16.512 [critical] Either set ERLANG_NODE in ejabberdctl.cfg or change node name in Mnesia
16:35:16.579 [error] CRASH REPORT Process <0.39.0> with 0 neighbours exited with reason: node_name_mismatch in ejabberd_app:db_init/0 line 120 in application_master:init/4 line 138
16:35:16.630 [info] Application ejabberd exited with reason: node_name_mismatch in ejabberd_app:db_init/0 line 120

can anyone pls help me to resolve this issue?
@zinid  I am expecting some precious suggestions from you, previously your suggestions helped me lot.

Regards,
Veer

**Comment by zinid** [comment]
Not enough info, dude. Are your trying to add a new node to the existing one, or are you trying to build a cluster from scratch? Did you use related `ejabberdctl` commands to join nodes?

**Comment by zinid** [comment]
There is ejabberdctl's `mnesia_change_nodename` command. Did you run it?

**Comment by Veerbhadra277** [comment]
yes, I followed steps from following link
https://docs.ejabberd.im/admin/guide/managing/

I could run mnesia_change_nodename step 6

but got following error for step 7
Failed RPC connection to the node ejabberd@osboxes: {'EXIT',
                                                     {badarg,
                                                      [{ets,lookup,
                                                        [local_config,
                                                         {ejabberdctl_access_commands,
                                                          global}],
                                                        []},
                                                       {ejabberd_config,
                                                        get_option,3,
                                                        [{file,
                                                          "src/ejabberd_config.erl"},
                                                         {line,852}]},
                                                       {ejabberd_ctl,process,
                                                        2,
                                                        [{file,
                                                          "src/ejabberd_ctl.erl"},
                                                         {line,224}]},
                                                       {rpc,
                                                        '-handle_call_call/6-fun-0-',
                                                        5,
                                                        [{file,"rpc.erl"},
                                                         {line,187}]}]}}


and got ejabberd error log 

[ejabberd.log.txt](https://github.com/processone/ejabberd/files/769569/ejabberd.log.txt)

am I missing something ?

-Veer

**Comment by Veerbhadra277** [comment]
please let me know, if you need more information @zinid

**Comment by zinid** [comment]
@Veerbhadra277 sorry, I'm not very familar with `ejabberdctl` scripting. I'll assign the issue to @badlop.

**Comment by Veerbhadra277** [comment]
ok @zinid thanks a lot, @badlop can you please help me in this issue ? 

Thanks,
Veer

**Comment by badlop** [comment]
I tried those steps, and it worked for me using the recent ejabberd 17.01. From what I remember, nothing has changed in this feature since 16.09 and older, so it should work.

> and got ejabberd error log ejabberd.log.txt

You got again the same errors? Then obviously you missed some step. Either forgot to remove old database in step 4... Or maybe you forgot to set NEWNODE in ejabberdctl.cfg

**Comment by Veerbhadra277** [comment]
Thanks @badlop for your reply,

I am still facing same issue it seems new node doesn't have permission to access db(Mnesia), please find file diff between old node and new node

1. oldnode i.e. localhost on which ejabberd running successfully 
![foroldnode](https://cloud.githubusercontent.com/assets/8426382/23296376/ab41458c-fa9a-11e6-8409-4925314a1d84.PNG)

2. newnode i.e. osboxes on which ejabberd giving error like "Node name mismatch: I'm [ejabberd@osboxes], the database is owned by [ejabberd@localhost"
![fornewnode](https://cloud.githubusercontent.com/assets/8426382/23296424/ffb424ae-fa9a-11e6-8607-1cc78cff3b0a.PNG)

it will be grate if you share from scratch steps to create node and include same in clustering,

Regards,
Veer

**Comment by Veerbhadra277** [comment]
uninstalled ejabberd and installed cleanly and it is worked, i could modify default name localhost by following link
https://docs.ejabberd.im/admin/guide/managing/

Thanks !!!

**Comment by tianxu0836** [comment]
Can anyone tell me, How to configure cluster exactly step by step?
I've been search the entire internet, nobody talking about how to setup cluster.
Why is so complicated??

**Comment by myluckyapps** [comment]
> Can anyone tell me, How to configure cluster exactly step by step?
> I've been search the entire internet, nobody talking about how to setup cluster.
> Why is so complicated??

Even I am also looking to cluster configuration. I will try make tutorial once I learned.
