### ISSUE TITLE
ejabberd 16.x service crashed all of sudden

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1536]
> What version of ejabberd are you using?
16.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

> What did not work as expected? Are there error messages in the log? What
ejabberd server crashed and stopped working
crash.log
-----------

```
2017-02-12 17:06:49 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.5717.0>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1611}},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,755}]},{p1_fsm,loop,1
0,[{file,"src/p1_fsm.erl"},{line,433}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.391.0>,ejabberd_listeners,ejabberd_sup,<0.37.0>]
    messages: [{'$gen_event',{xmlstreamelement,{xmlel,<<"presence">>,[{<<"id">>,<<"6386269338139535360-51">>},{<<"type">>,<<"of
f">>}],[]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"to">>,<<"glabbr.co.in">>},{<<"id">>,<<"ping1486919203">>},{<<
"type">>,<<"get">>}],[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"xmpp:ping">>}],[]}]}}}]
    links: [#Port<0.18170>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 196650
    stack_size: 27
    reductions: 25938765
  neighbours:
2017-02-12 17:07:03 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.6687.0>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1692}},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,755}]},{p1_fsm,loop,1
0,[{file,"src/p1_fsm.erl"},{line,433}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.391.0>,ejabberd_listeners,ejabberd_sup,<0.37.0>]
    messages: []
    links: [#Port<0.18205>]
    dictionary: [{'$internal_queue_len',776}]
    trap_exit: false
    status: running
    heap_size: 121536
    stack_size: 27
    reductions: 15418597
  neighbours:
2017-02-12 17:07:08 =ERROR REPORT====
** State machine <0.4251.0> terminating 
** Last message in was {'EXIT',<0.4251.0>,{error,{process_limit,{max_queue,13059}}}}
** When State == session_established
**      Data  == {state,{socket_state,ezlib,{zlibsock,fast_tls,{tlssock,#Port<0.18093>,#Port<0.18094>},#Port<0.18095>},<0.4250.0>},ejabberd_socket,#Ref<0.0.1.153238>,false,<<"6188840213740128477">>,undefined,c2s,c2s_shaper,true,true,true,true,[verify_none,compression_none,{protocol_options,<<"no_sslv2|no_sslv3">>},{dhfile,<<"/opt/ejabberd/ssl/dh2048.pem">>},{certfile,<<"/opt/ejabberd/ssl/cert1.pem">>}],true,{jid,<<"143461">>,<<"glabbr.co.in">>,<<"A-1.1">>,<<"143461">>,<<"glabbr.co.in">>,<<"A-1.1">>},<<"143461">>,<<"glabbr.co.in">>,<<"A-1.1">>,{{1486,919168,535894},<0.4251.0>},{pres_t,24},{pres_f,27},{pres_a,35},{xmlel,<<"presence">>,[{<<"xml:lang">>,<<"en">>},{<<"id">>,<<"6386269009372674048-45">>},{<<"type">>,<<"unavailable">>}],[{xmlel,<<"status">>,[],[{xmlcdata,<<"1486907755">>}]}]},{1486,919170,261992},{userlist,none,[{}],[]},c2s_compressed_tls,undefined,{{42,106,75,188},39758},[],active,disabled,undefined,undefined,1000,undefined,600,600,false,0,0,true,<<"en">>}
```
error.log
-----------
2017-02-12 17:06:49.081 [error] <0.5717.0> CRASH REPORT Process <0.5717.0> with 0 neighbours exited with reason: {process_limit,{max_queue,1611}} in p1_fsm:terminate/8 line 755
2017-02-12 17:07:03.050 [error] <0.6687.0> CRASH REPORT Process <0.6687.0> with 0 neighbours exited with reason: {process_limit,{max_queue,1692}} in p1_fsm:terminate/8 line 755

**Comment by zinid** [comment]
This is not a crash report, you should have `erl_crash.dump` somewhere, find it and read its slogan.

**Comment by zinid** [comment]
But from the log I see your c2s connections are overloaded by incoming stanzas. This might be a cause or a consequence, it's hard to say.

**Comment by nOmi7** [comment]
ok so may be it was not a crash .. but the services did went down i dont see .dump file under logs how can find the reason for its stoppage ?

**Comment by zinid** [comment]
core dump maybe? Is there anything reported by `dmesg` or  in `/var/log/messages`?

**Comment by nOmi7** [comment]
/var/log/messages i checked this it has nothing inside there was no coredump either.

**Comment by zinid** [comment]
Anyway, we need the following to investigate the crash:
1) `error.log`
2) `crash.log`
3) `erl_crash.dump` (if any)
4) core dump (if any).

**Comment by zinid** [comment]
So you have nothing in `ejabberd.log`/`crash.log` except those stuff you have already shown? And neither `erl_crash.dump` nor `core` dump?
Then it is impossible to investigate, at least from my side.

**Comment by nOmi7** [comment]
ok ill try to dig more during stop time and let you know if i find anything

**Comment by nOmi7** [comment]
ok i just checked my offline.dat mnesia was bumped to 1.8gig  can that be a reason to stop ?

**Comment by zinid** [comment]
Maybe. Is there mnesia core around?

**Comment by nOmi7** [comment]
i dont see mnesia core either.

**Comment by zhaohansprt** [comment]
it seems since R17 mnesia is not reliable anymore

**Comment by zinid** [comment]
It never was reliable, lol :)
