### ISSUE TITLE
Develop new module with ejabberd 17.01

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#1541]
The default module add the db_type in the config , is no problem.
But it doesn't work in my new module.

This is the debug info:
 [warning] incorrect value 'sql' of option 'db_type', using 'undefined' as fallback

**Comment by zinid** [comment]
AFAIR, if a backend module is not listed in `ebin/ejabberd.app`, then ejabberd doesn't see it. Maybe this is your case, who knows, you provided too little info.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:62663)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cdZsz-0007OK-Cv
	for zero@thezeroworld.com; Tue, 14 Feb 2017 04:59:01 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=M7um9dflVrREoe6s6slg5JmIUz8=; b=mufPrNwZ9Ho7Bq7e
	bJyMSA30f1uvqmStIIrzF2Aq9p0lZLZSCFmYR3WODJF0UNact4/aIuz8ku7r/Yse
	ViA0neOGGnHbewTy/kEFCIM/sm7q0LB0vLoLh5y4EIo9XrZG6lEOCgCElXjk4gON
	BWjdI0az1LUBWp/k/EgQzJcXePc=
Received: by filter1012p1mdw1.sendgrid.net with SMTP id filter1012p1mdw1-19198-58A2D4B9-2A
        2017-02-14 09:58:17.606978999 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id _1WgSa4VQwGFaAiTTWV3xQ
	for <zero@thezeroworld.com>; Tue, 14 Feb 2017 09:58:17.515 +0000 (UTC)
Date: Tue, 14 Feb 2017 01:58:17 -0800

**Comment by zinid** [comment]
Closed due to inactivity.
