### ISSUE TITLE
Subscription Outcast in pubSubNode still receive mesage

### ISSUE THREAD

**Issue by lucabecchetti** [processone/ejabberd#1545]
> What version of ejabberd are you using?

16.03

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What

i change subscription for a user from publisher to outcast or none, in mysql table i see "n" or "c" for subscription, the user are not able to send, but still receive message

**Comment by brokeniceinteractive** [comment]
news?

**Comment by cromain** [comment]
i'll check this right after 17.03-beta

**Comment by cromain** [comment]
publisher / outcast / none is entity's affiliation.
an entity can subscribe, then node owner can change it's affiliation, but this does not remove the subscriptions.
What you describe is expected result. When affiliation unset, user can not publish (until node publish model is set to open) but can still receive the items if he's still subscribed.
As node owner, if you want to "kick" a user, you have to remove it's subscription and affiliation also.

I see no bug here.
