### ISSUE TITLE
postgresql support in docker image

### ISSUE THREAD

**Issue by zh99998** [processone/ejabberd#1547]
> What version of ejabberd are you using?

16.12

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

Docker

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

currently can't use postgresql with ejabberd/ecs image.

```
08:42:26.846 [critical] failed to start application 'p1_pgsql': {error,
                                         {"no such file or directory",
                                          "p1_pgsql.app"}}
```

**Comment by cromain** [comment]
fixed in our official ejabberd/ecs image which will be uploaded after 17.03 release.
