### ISSUE TITLE
Support scrammed passwords in ejabberdctl import_prosody

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1549]
When using mod_auth_internal_hashed (https://prosody.im/doc/modules/mod_auth_internal_hashed) in Prosody (and Metronome), passwords are stored in a hashed format. The `import_prosody` tool of ejabberd doesn't seems to support this format when importing accounts.

Here is an example of the flat file with stored information.
```
root@movim:/var/lib/prosody/server%2ecom/accounts# cat test.dat 
return {
	["iteration_count"] = 4096;
	["stored_key"] = "c37d5ff38d6dd3f4f6a6256a6ef47bcfba03dd45";
    	["salt"] = "2ac8fd26-80b3-43e4-96d7-b6c6667f33eb";
    	["server_key"] = "df107cdda477e3f7ca03b749bd9ed168bbbfd2f9";
};

```

**Comment by badlop** [comment]
I've pushed a commit to ejabberd git master that implements this improvement. I've tested it with your example and works for Mnesia auth. If you try, confirm it works, and what auth method you use.

**Comment by edhelas** [comment]
Thanks! I'll give it a try when I'll have some time and come back to you.

**Comment by cromain** [comment]
Closing for now, please reopen if you have issues with your tests

**Comment by edhelas** [comment]
Hi, I tried an import using your script and it seems that the data are slightly different.

Here is a user imported using the prosody2ejabberd script
```
 username |                 password                 |                serverkey                 |                 salt                 | iterationcount |         created_at         
----------+------------------------------------------+------------------------------------------+--------------------------------------+----------------+----------------------------
 test     | c37d5ff38d6dd3f4f6a6256a6ef47bcfba03dd45 | df107cdda477e3f7ca03b749bd9ed168bbbfd2f9 | 2ac8fd26-80b3-43e4-96d7-b6c6667f33eb |           4096 | 2017-03-10 16:16:23.930604
```

And here is a user created using ejabberdctl

```
   username   |           password           |          serverkey           |           salt           | iterationcount |         created_at         
--------------+------------------------------+------------------------------+--------------------------+----------------+----------------------------
 test_imporrt | LA3Zgby05smZrZAQFFC8AEWbj6Q= | H78m0M+bBJzzWtNEOrdImizr4ks= | 6jHiuiSq14WjDfU+yCKrCQ== |           4096 | 2017-03-10 16:18:50.010558

```

**Comment by badlop** [comment]
The important thing is, can the imported users login correctly? And the locally created users too?

**Comment by edhelas** [comment]
The locally created users can login properly not the imported ones.

**Comment by badlop** [comment]
Ah, right. ejabberd stores in base64, prosody does not.

I've committed a fix for that, it converts the example data you provided, but of course I can't ensure it finally works. Please test and comment.

**Comment by edhelas** [comment]
Hello, it doesn't seems to work either. It seems that the Prosody stored key is in hexadecimal (see http://hg.prosody.im/trunk/file/tip/plugins/mod_auth_internal_hashed.lua#l126). I'll try to investigate.

**Comment by edhelas** [comment]
Ok, I've converted manually one account and it seems to work with this conversion chain:
```
ejabberd_password = base64_encode(hex2bin(prosody_password))
ejabberd_serverkey = base64_encode(hex2bin(prosody_serverkey))
ejabberd_salt = base64_encode(prosody_salt)
```
