### ISSUE TITLE
Best way to achieve ?

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1551]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

To prevent message loss I am storing all the outgoing messages in mysql even if user is online as we are not sure if the user online due to connection loss. and delete from mysql once the peer sends delivery ack.
due to this there are many reads and writes to DB.
I wanted to know what is the best practise to do the processing in memory mostly and touch the mysql as least as possible  like when we know peer is 100% offline .
Only concern with main memory processing If the session  or the server crashes to some reason the messages would be lost which is un-acceptable 
I would love to know how people are doing this . or any better way of doing it.

**Comment by zinid** [comment]
Many people are not so anal about message lost. A crash could occur everywhere, so what?

**Comment by nOmi7** [comment]
> Many people are not so anal about message lost. 
did not understand you
A crash could occur everywhere, so what?
thats true but application servers until the become robust they have high chances also when we start and stop the server the in memory state is lost  if its DB chances are less.

@zinid  what is your thought on this how can we achieve the best of both world ? I know you always have a diff solution to the problem :) any help would be really greatful

**Comment by zinid** [comment]
I would use mmap'ed file buffer as a message queue.

**Comment by nOmi7** [comment]
https://en.wikipedia.org/wiki/Mmap ??   
do you know any erlang or implementation with ejabberd ?

**Comment by zinid** [comment]
Even if an implementation existed, you cannot just get a wrapper, because you need to craft a lot of stuff in C (Erlang NIF) for this in order to get efficient code.
On the other hand, you can craft pure file queue (via `file.erl`) interface. It will be several times faster than writing to a database anyway, because you read the same data almost immediately after write, so it will be cached by OS buffers and you read from this RAM cache.
This is just my thoughts, mind you.

**Comment by nOmi7** [comment]
ok to complicated for my tiny mind also looks gonna take some time.
What you think of below approach or 
1) Create ETS table to store messages
Write data from ETS to DB / File  on condtion
     user is offline 
     user goes offline
     No response from user for x amount of time
     when stopping the ejabberd server
     make ETS  under diff sup so even if session crash occurs the data is preserved 
     Only condition i am missing how to persist data when execption occurs that can crash the ejabberd service . (any idea on this )
or any condition that i may be missing

**Comment by zinid** [comment]
Just write to a file everytime and even if a server gets crashed you still keep the data in those files. There is already a queue in XEP-0198 implementation, just implement queue API above file interface and you will get drop-in replacement.

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:11588)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.88)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1ceh0P-0004FG-AG
	for zero@thezeroworld.com; Fri, 17 Feb 2017 06:47:17 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=I6JGKPw86XUntCw/In5fORkBiJo=; b=A95qV0NIo+bjtuNC
	cweC1/zuSo7sHsx8F9rTx/k+PNLqp6C6xPevvMUWVRT3DkUdJZpjLmvZAWm8Gw2c
	fgZAaKflod0WWK8gVFH6N5QlQpABU1n1qJoYddSwJF/lLlDj+LIMMFskUHE9cloE
	F1KjOqX6CeuXZnZQRS642mKKuTs=
Received: by filter1136p1mdw1.sendgrid.net with SMTP id filter1136p1mdw1-22629-58A6E29C-4F
        2017-02-17 11:46:36.403019791 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 2JZkSuhdQOehZQg3GiGKcQ
	for <zero@thezeroworld.com>; Fri, 17 Feb 2017 11:46:36.306 +0000 (UTC)
Date: Fri, 17 Feb 2017 03:46:36 -0800

**Comment by nOmi7** [comment]
the issue with file writes is i am not sure how it will work in clustered env  ? would that not create a problem ? as user can connect to any of the server in the cluster   i have not yet tried but i may try to create geo-distributed cluster of ejabberd

**Comment by zinid** [comment]
Well I have no easy solution for you then.
And you cannot build geo-clustering with SQL anyway.

**Comment by nOmi7** [comment]
even if we dorp geo cluster idea even is same diff datacenter  cluster writing to file would be a problem as it would need shared file ..

can this not work ?
Write data from ETS to DB / File on condtion
user is offline
user goes offline
No response from user for x amount of time
when stopping the ejabberd server
make ETS under diff sup so even if session crash occurs the data is preserved
Only condition i am missing how to persist data when execption occurs that can crash the ejabberd service . (any idea on this )
or any condition that i may be missing

**Comment by zinid** [comment]
> Only condition i am missing how to persist data when execption occurs that can crash the ejabberd service . (any idea on this )

This is almost the same as to say: what to do if the machine gets suddenly broken :)
And we didn't even touch network partitioning problems yet :smile:

**Comment by nOmi7** [comment]
:D alright i understand there is no way to stop failure it can happen in any way .. 
so apart from  

> Only condition i am missing how to persist data when execption occurs that can crash the ejabberd service . (any idea on this )

can this work ?
Write data from ETS to DB / File on condtion
user is offline
user goes offline
No response from user for x amount of time
when stopping the ejabberd server
make ETS under diff sup so even if session crash occurs the data is preserved
or any condition that i may be missing

**Comment by zinid** [comment]
I think this will work, but implementing it not very trivial, so most likely there will be bugs.

**Comment by nOmi7** [comment]
thanks for allowing me to bug with my thoughts and you being patient in answering them :)  @zinid
