### ISSUE TITLE
Cannot use mod_muc_admin:get_room_occupants

### ISSUE THREAD

**Issue by aghasoroush** [processone/ejabberd#1552]
> What version of ejabberd are you using?

17

> What operating system (version) are you using?

ubuntu

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi guys. I'm trying to develop a simple module to send a post request to somewhere else on muc_filter_presence event.

Here it is the function:

       `on_muc_presence(Stanza, _MudState, RoomJID, _FromJID, _FromNick) ->
	
        RoomName = element(2, RoomJID),

	Service = element(3, RoomJID),

	?ERROR_MSG("RoomName -> ~p, Service -> ~p~n", [RoomName, Service]),

	Occupants = mod_muc_admin:get_room_occupants(RoomName, Service),

 	?ERROR_MSG("Occupants -> ~p~n~n~n~n~n~n", [Occupants]),

	Stanza.`

But I get this error on console and I can't see the `?ERROR_MSG("Occupants -> ~p~n~n~n~n~n~n", [Occupants]),` output

here it is the error :
[error] {timeout,{gen_fsm,sync_send_all_state_event,[<0.393.0>,get_state]}}

**Comment by aghasoroush** [comment]
Any help?????

**Comment by Pouriya-Jahanbakhsh** [comment]
It might be from your module definition Not the Ejabberd application itself.
Show more about Error (show the Erlang stacktrace of it) and code.

**Comment by aghasoroush** [comment]
Here it is the stacktrace: 
{timeout,{gen_fsm,sync_send_all_state_event,\n                                [<0.393.0>,get_state]}}' occurred executing the command.\nStacktrace: [{gen_fsm,sync_send_all_state_event,2,\n                      
[{file,\"gen_fsm.erl\"},{line,249}]},\n             {mod_muc_admin,get_room_state,1,\n                            
[{file,\"src/mod_muc_admin.erl\"},{line,641}]},\n             {mod_muc_admin,get_room_occupants,1,\n                            
[{file,\"src/mod_muc_admin.erl\"},{line,727}]},\n             {ejabberd_ctl,call_command,4,\n                           
[{file,\"src/ejabberd_ctl.erl\"},{line,329}]},\n             {ejabberd_ctl,try_call_command,4,\n                           
[{file,\"src/ejabberd_ctl.erl\"},{line,298}]},\n             {ejabberd_ctl,process2,4,\n                           
[{file,\"src/ejabberd_ctl.erl\"},{line,247}]},\n             {ejabberd_ctl,process,2,\n                           
[{file,\"src/ejabberd_ctl.erl\"},{line,225}]},\n             {rpc,'-handle_call_call/6-fun-0-',5,\n                  
[{file,\"rpc.erl\"},{line,206}]}]\n"

But I'm sure there isn't any error in my module, coz I can handle the hook I registered so everything is working well with registering the hook and catching it.

It's related to finite state machine and broadcasting events on it.

**Comment by Pouriya-Jahanbakhsh** [comment]
Generic calls come from The `gen.erl` module [exactly here](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen.erl#L150) and 'timeout` error comes from [here](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen.erl#L180).  

Getting this error all the time is imminent (the `call` function of the `gen.erl` module does not change for many years).
I think you may have some problem in your network among nodes of your cluster or among `ejabberd_ctl` and the node.

**Comment by aghasoroush** [comment]
It's all about `sync_send_all_state_event`. In mod_muc_admin trying to call it with default timeout value, while I'm trying to deal with it synchronously. This is the problem. Gonna change the code and recompile it to make it available with a timeout option.
