### ISSUE TITLE
Unable to configure ejabberd on remote server using only ip address

### ISSUE THREAD

**Issue by Hemant0601** [processone/ejabberd#1554]
Used this link here to configure ejabberd server, tried everything but whenever I open home page using my ip address http://[ip_address]:5280/admin I get below response

The [ip_address] page isn’t working

[ip_address] didn’t send any data. ERR_EMPTY_RESPONSE

**Comment by Pouriya-Jahanbakhsh** [comment]
You could not demonstrate that this problem is from Ejabberd.
1. Check your Ejabberd config file `e.g. /opt/ejabberd-*.*/config/ejabber.yml` and find the linked part and edit it.
2. Check your network or firewall if you are sure about Ejabberd functionality.

**Comment by Hemant0601** [comment]
I am sure about ejabberd, I cant understand about firewall on remote, 5280 port not showing in used list, netstat

**Comment by Hemant0601** [comment]
Checked , Everything seems fine. Still no luck.

**Comment by badlop** [comment]
With a quick review to your config, I suspect the problem is here:
```
  - 
    port: 5280
    module: ejabberd_http
    ip: "::"
    web_admin: true
    tls: true
    certfile: "/etc/ejabberd/ejabberd.pem"
```
You have configured ejabberd to listen in port 5280 of IPv6 addresses, for HTTP queries that use TLS encryption. But then you send a non-TLS query:
> ip address http://[ip_address]:5280/admin I get below response

If this is the problem, then either:
A) Use https://[ip_address]:5280/admin/
B) Set the tls option to false

If none of this works, then add a comment, to think other possible problems.

**Comment by Hemant0601** [comment]
Since, I don't have SSL so I tried 2nd option and that too didnt hlep, any other solution

**Comment by badlop** [comment]
Set loglevel to 5 in ejabberd.yml, restart ejabberd and try to browse the webadmin. I get something like this in the log file. And you?
```
13:03:56.318 [debug] (#Port<0.17500>) http query: 'GET' <<"/admin/">>
13:03:56.318 [debug] [<<"admin">>] matches [<<"admin">>]
13:03:56.322 [debug] (#Port<0.17500>) http query: 'GET' <<"/admin/">>
13:03:56.322 [debug] [<<"admin">>] matches [<<"admin">>]
13:03:56.387 [info] (<0.509.0>) Accepted connection 127.0.0.1:56146 -> 127.0.0.1:5280
13:03:56.387 [debug] S: [{[<<"admin">>],ejabberd_web_admin},{[<<"http-bind">>],mod_bosh}]
13:03:56.387 [info] started: {gen_tcp,#Port<0.17501>}
```
