### ISSUE TITLE
Hint: debug from console howto

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1557]
Hi guys,
I usually start/stop/debug modules from debug console (./bin/ejabberd_ctl debug), erlang is there and it's easy to debug or execute code from there. I'd like to evaluate #xmlel record expressions from console so I should `rr(includesomefile)` to include #xmlel definition, where is it defined ? 

Thanks
Ben

**Comment by zinid** [comment]
Type in erlang console:
```erlang
> rr(fxml).
```
Or, with ejabberd 16.12+, use records from `xmpp` library instead:
```erlang
> rr(xmpp).
```

**Comment by andreabenini** [comment]
Tried them but:
```
(ejabberd@localhost)119> rr(fxml).
{error,beam_lib, {missing_chunk,'/opt/ejabberd/lib/fast_xml-1.1.3/ebin/fxml.beam', "Abst"}}                                                                           
(ejabberd@localhost)120> rr(xmpp).
{error,nofile}
```

**Comment by zinid** [comment]
Regarding `xmpp` nofile: you should have 16.12+ for this.
Regarding missing_chunk: seems like you have stripped BEAM files or you compiled `fast_xml` without `debug_info`.

**Comment by andreabenini** [comment]
I have a v16.04 from binary installer

**Comment by zinid** [comment]
Well then you need to provide a full path to the location of your "fxml.hrl":
```erlang
> rr("/path/to/fxml.hrl").
```

**Comment by andreabenini** [comment]
thanks :)
