### ISSUE TITLE
making custom async call.

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1559]
> What version of ejabberd are you using?
17

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

I am trying to write a module for message processing before routing with some customizations and using reference module as mod_sm particularly (acking , queuing)  
so basically when i rcv message  I am sending ack to the client currently is a sync call as

```
c2s_authenticated_packet(State, Pkt)
  when ?is_message(Pkt) ->
	{Ack,UploadedMedia}  = get_ack_and_media(Pkt),
        send_ack(Ack),  // make asyc call and process message further
        process_message(),
        NewState;

send_ack(Ack) ->
   ejabberd_c2s:call(self(), {send_ack, Ack , timer:seconds(10)).

c2s_handle_call(#{mod := Mod} = State, {send_ack, Ack}, From) ->
    Mod:reply(From, {sending_ack, Ack}),
    State;
c2s_handle_call(State, _Call, _From) ->
    State.

c2s_handle_info(#{jid := JID} = State, {_, {sending_ack, AckPkt}}) ->
   send(State,AckPkt);
c2s_handle_info(State, _) ->
    State.

```

after doing this  i get 2 errors
1) got unexpected info: sending_ack
2) Timout may be bcz of self() pid ref that i am sending 

I am learning erlang and need community help to get this in right way . on making right async call for sending ack.

**Comment by zinid** [comment]
You should *never* patch `ejabberd_c2s` in the first place.
And yes, you call to yourself, so the call will crash with `timeout`.

**Comment by zinid** [comment]
Just call `ejabberd_c2s:send()` directly in `send_ack` function.
Note: `ejabberd_c2s:send()` returns new C2S state, you should take this into consideration.

**Comment by zinid** [comment]
So, in fact, you only need this in your module (assuming `c2s_authenticated_packet` is a hooked function):
```erlang
c2s_authenticated_packet(State, Pkt) when ?is_message(Pkt) ->
	{Ack, UploadedMedia}  = get_ack_and_media(Pkt),
        State1 = ejabberd_c2s:send(State, Ack),
        process_message(),
        State1;
```

**Comment by nOmi7** [comment]
Thanks @zinid
