### ISSUE TITLE
configure mod_http_offline

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1564]
On ejabberd17, in installed mod_http_offline by commandline, but i don't see it on the webportal where the modules are listed. How can i activate it?

If in the ejabberd.yml I manually add mod_http_offline {} i can't restart ejabberd.

Furthermore I see that I need to add the API url in  this file:
lib/ejabberd/.ejabberd-modules/sources/mod_http_offline/mod_http_offline.erl

Can this be different for different virtual hosts?

**Comment by badlop** [comment]
> How can i activate it?

Looking at its documentation in https://github.com/raelmax/mod_http_offline You must enable the module as many others.

> If in the ejabberd.yml I manually add mod_http_offline {} i can't restart ejabberd.

Check the indentation of your line, the blankspaces in it. This is correct:
```
modules:
  mod_http_offline: {}
  mod_adhoc: {}
  ...
```

> Furthermore I see that I need to add the API url in this file: lib/ejabberd/.ejabberd-modules/sources/mod_http_offline/mod_http_offline.erl

Right, it seems you must modify the module source code because that URL is hardcoded.

> Can this be different for different virtual hosts?

You would have to improve the module so it reads this URL as an option from ejabberd.yml

**Comment by PH-F** [comment]
In ejabberd 17 I installed mod_offline
./ejabberdctl module_install mod_http_offline

When i check with ./ejabberdctl modules_installed I see that this went well.

After that i added to the section   modules:
  mod_http_offline: {}

But when i restart ejabberd it fails:
Feb 27 14:21:59 honker ejabberd[3347]: Starting ejabberd...
Feb 27 14:23:08 honker systemd[1]: ejabberd.service: control process exited, code=exited status=1
Feb 27 14:23:08 honker systemd[1]: Failed to start LSB: Starts ejabberd jabber server.
Feb 27 14:23:08 honker systemd[1]: Unit ejabberd.service entered failed state.

When i remove the line in ejabberd.yml it starts again. 
What can i do to enable this module? 
ps. I also asked this on the gir-repo of this module.  

Thank you for your reply!

**Comment by PH-F** [comment]
The crahs log shows:  Problem starting the module mod_http_offline for host  <<....etc >>

Do I still need to compile this module somehow in order to get it to work?

**Comment by PH-F** [comment]
I just can't get this module to work, i just installed it with
./ejabberdctl module_install mod_http_offline

and added   mod_http_offline: {}

Is there a manual somewhere that shows how to install it? It is an available module for ejabberd.

**Comment by badlop** [comment]
You are right: ejabberd downloads the module, but is not capable of compiling it. This simple workaround alllos ejabberd to compile it:
```
--- a/src/ext_mod.erl
+++ b/src/ext_mod.erl
@@ -520,7 +520,7 @@ compile(LibDir) ->
     Bin = filename:join(LibDir, "ebin"),
     Inc = filename:join(LibDir, "include"),
     Lib = filename:join(LibDir, "lib"),
-    Src = filename:join(LibDir, "src"),
+    Src = LibDir,
     Options = [{outdir, Bin}, {i, Inc} | compile_options()],
     filelib:ensure_dir(filename:join(Bin, ".")),
     [copy(App, Bin) || App <- filelib:wildcard(Src++"/*.app")],
```
However, notice that the module has some bug, as compilation complains:
```
$ ejabberdctl module_install mod_http_offline
/home/bernar/.ejabberd-modules/sources/mod_http_offline/mod_http_offline.erl:31:
 variable 'SubType' is unbound
```
So, you have to also edit the file $HOME/.ejabberd-modules/sources/mod_http_offline/mod_http_offline.erl in line 31, replace SubType with Type.
Finally, you can enable the module in ejabberd configuration, and the compiled file should be loaded automatically from that location.

**Comment by PH-F** [comment]
Thank you, will this be fixed in a new version of eJabberd?

**Comment by badlop** [comment]
I don't consider it a bug of ejabberd, instead that this module does not match the expected file structure: source code should be is in src/.

Does the module work correctly with recent ejabberd for you? I could send a Pull Request with this change to the author project.

**Comment by PH-F** [comment]
Okay that sounds plausible.
Yes, I would appreciate it If you would be so kind to send a pull request to the author of this project.

Thank you in advance.

**Comment by badlop** [comment]
Or even better, have you seen that a guy has forked and improved that module? Maybe we should point to that fork, as it seems more updated: https://github.com/Nimrodda/mod_offline_http_post Try it and report if it's a better replacement.

**Comment by PH-F** [comment]
Hi there, how can I install a module (probably a simple question)?
I tried the commands below, but i get the error: Error: not_available

cd /var/lib/ejabberd/.ejabberd-modules
>>ok

git clone https://github.com/Nimrodda/mod_offline_http_post.git
chown -R ejabberd:ejabberd mod_offline_http_post
>>ok

bash /var/ejabberd-17.01/bin/ejabberdctl modules_update_specs
>>ok

bash /var/ejabberd-17.01/bin/ejabberdctl module_install mod_offline_http_post
>>Error: not_available

**Comment by badlop** [comment]
You forgot to enter sources/, and don't need modules_update_specs:
```
$ cd whatever/.ejabberd-modules
$ cd sources
$ git clone https://github.com/Nimrodda/mod_offline_http_post.git
$ ejabberdctl modules_available | grep http_post
mod_offline_http_post   HTTP POST user's messages to target URL when user is offline
$ ejabberdctl module_install mod_offline_http_post
```

**Comment by PH-F** [comment]
Thank you, thats works, unfortunately I get one other error. 
I hope you can help me one more time, than I'm done!. I use ejabbard 17.01

**after: $ ejabberdctl module_install mod_offline_http_post**

/var/lib/ejabberd/.ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl:5: Warning: undefined callback function depends/2 (behaviour 'gen_mod')

/var/lib/ejabberd/.ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl:5: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')


**In ejabberd.yml i added**
  mod_offline_http_post:
    auth_token: "secret"
    post_url: "http://patrick.fastguide.org/log"

_When i send a message to an offline user the following error occurs in the error.log_

```
2017-03-30 22:01:00.899 [error] <0.746.0>@ejabberd_hooks:run1:332 {function_clause,[{fxml,get_tag_attr_s,[<<"type">>,{message,<<"purpleae49e550">>,chat,<<>>,{jid,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>},{jid,<<"alexandra">>,<<"-cut-servername-">>,<<>>,<<"alexandra">>,<<"-cut-servername-">>,<<>>},[],[{text,<<>>,<<"This is a testmessage!">>}],undefined,[{xmlel,<<"active">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{}}],[{file,"src/fxml.erl"},{line,169}]},{mod_offline_http_post,create_message,3,[{file,"/var/lib/ejabberd/.ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl"},{line,24}]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},{ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},{ejabberd_sm,route,3,[{file,"src/ejabberd_sm.erl"},{line,126}]},{ejabberd_local,route,3,[{file,"src/ejabberd_local.erl"},{line,110}]},{ejabberd_router,route,3,[{file,"src/ejabberd_router.erl"},{line,87}]},{ejabberd_c2s,check_privacy_route,5,[{file,"src/ejabberd_c2s.erl"},{line,1886}]}]}
running hook: {offline_message_hook,[{jid,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>},{jid,<<"alexandra">>,<<"-cut-servername-">>,<<>>,<<"alexandra">>,<<"-cut-servername-">>,<<>>},{message,<<"purpleae49e550">>,chat,<<>>,{jid,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>,<<"patrick">>,<<"-cut-servername-">>,<<"Patricks-MacBook-Pro">>},{jid,<<"alexandra">>,<<"-cut-servername-">>,<<>>,<<"alexandra">>,<<"-cut-servername-">>,<<>>},[],[{text,<<>>,<<"This is a testmessage!">>}],undefined,[{xmlel,<<"active">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{}}]}
```

**Comment by badlop** [comment]
Obviously that module isn't ready for ejabberd 17.01. It would require at least this change, and probably others:
```diff
--- a/src/mod_offline_http_post.erl
+++ b/src/mod_offline_http_post.erl
@@ -7,7 +7,7 @@
 -export([start/2, stop/1, create_message/3]).
 
 -include("ejabberd.hrl").
--include("jlib.hrl").
+-include("xmpp.hrl").
 -include("logger.hrl").
 
 start(_Host, _Opt) ->
@@ -20,14 +20,12 @@ stop (_Host) ->
 	?INFO_MSG("stopping mod_offline_http_post", []),
 	ejabberd_hooks:delete(offline_message_hook, _Host, ?MODULE, create_message, 1).
 
-create_message(_From, _To, Packet) ->
-	Type = fxml:get_tag_attr_s(list_to_binary("type"), Packet),
-	Body = fxml:get_path_s(Packet, [{elem, list_to_binary("body")}, cdata]),
-	MessageId = fxml:get_tag_attr_s(list_to_binary("id"), Packet),
-
-	if (Type == <<"chat">>) and (Body /= <<"">>) ->
-		post_offline_message(_From, _To, Body, "SubType", MessageId)
-	end.
+create_message(_From, _To, Packet)
+    when (Packet#message.type == chat) and (Packet#message.body /= []) ->
+	[{text, _, Body}] = Packet#message.body,
+	post_offline_message(_From, _To, Body, "SubType", Packet#message.id);
+create_message(_From, _To, _Packet) ->
+	ok.
 
 post_offline_message(From, To, Body, SubType, MessageId) ->
 	?INFO_MSG("Posting From ~p To ~p Body ~p SubType ~p ID ~p~n",[From, To, Body, SubType, MessageId]),
```

**Comment by PH-F** [comment]
I got the module working for ejabberd 17.01 with a few extra adjustments
https://github.com/PH-F/mod_offline_http_post
