### ISSUE TITLE
get_last command returns system time, not UTC

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#1565]
I am currently running ejabberd 17.01. `ejabberdctl get_last` currently says:

```
Description:  Get last activity information (timestamp and status)

Timestamp is the seconds since1970-01-01 00:00:00 UTC, for example: date +%s
```

But when I execute the command, I get this:

```
# when I'm online:
root@host: ~ $ ejabberdctl get_last user example.com
Online
# When I'm offline
root@host: ~ $ ejabberdctl get_last user example.com
2017-02-23 19:10:48 Last Status (if any)
```

Most importantly, the timestamp does not reflect UTC time, but the local systems time. I went offline at 19:10 in the "Europe/Vienna" Timezone, which is 18:10 in UTC.

Also, the format of the timestamp is not the same in the documentation, and excluded if the user is currently online (which makes it less parseable for API clients.

I'm not sure if it's possible to have different output for different administration backends, but if it is, I'd argue that the actual behavior for `ejabberdctl` should stay the same (except for always including the timestamp - in the current format), while the Rest API should return a JSON like this (with the timestamp actually being in UTC):

```
{
    "status": "Online",
    "timestamp": 1487874270
}
```

**Comment by badlop** [comment]
I think I've fixed or improved everything you mentioned

> the timestamp does not reflect UTC time, but the local systems time.

Fixed, that was easy.

> the format of the timestamp is not the same in the documentation,

Right, now it returns in format defined by XEP-0082, and documentation is updated.

> and excluded if the user is currently online (which makes it less parseable for API clients.

Right, that was because, otherwise, how do you know that the user is online? Maybe that's not a matter of that command, and it should simply return the last time when the user was known to be online, which may be now(). Fixed.

> I'm not sure if it's possible to have different output for different administration backends,

Not possible in a clean way. But that output format seems reasonable for any frontend anyway.

**Comment by mathiasertl** [comment]
@badlop - that sounds great - thank you!

**Comment by mathiasertl** [comment]
@badlop is 57181c0a76f52334fe903c6680e4debb5b6f1c13 the only commit related to this change? (I would patch my 17.01 then)

**Comment by badlop** [comment]
Right, the only one.
