### ISSUE TITLE
PubSub: Last published item not sent when presence subscription is one-way

### ISSUE THREAD

**Issue by cromain** [processone/ejabberd#1572]
Precondition:
B is subscribed to A's presence but A isn't to B's (subscription='to').

Steps:
A logs in.
A publishes mood.
A logs out.
B logs in (initial presence advertising interest in mood data).
B should receive A's latest mood but doesn't.

Notes:
If B logs in when A is still online then he does receive A's mood.
If the presence subscription is of type 'both', it works ok.

was initially reported on https://support.process-one.net/browse/EJAB-1215

**Comment by shenjun100** [comment]
After 17.01, even if both A & B are online and subscribed to each other, if A changes the mood, B doesn't receive and vice versa.

**Comment by cromain** [comment]
latest comment is unrelated, and was temporary regression fixed on march 3

**Comment by cromain** [comment]
all cases should be fixed now. B publish mood, A receive it only after B accept subscription.
please reopen if you see some problematic cases.
