### ISSUE TITLE
ejabberd http-bind repeating rid error

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1576]
> What version of ejabberd are you using?

ejabberd 16.02

> What operating system (version) are you using?

centos 7.0.1406

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

 We have a system setup where we use Stophe to connect to ejabberd over 
BOSH running through HA-Proxy. When our clients are idle, they seem to 
be hitting the timeout (@ 1.1 * 60 seconds), which aborts the 
outstanding long-poll. The library then appears to make the next 
long-poll using the same rid. ejabberd shows repeating RID and returns error.

> was the unexpected behavior? What was the expected result?

**Comment by vijayaa** [comment]
As per this specification https://xmpp.org/extensions/xep-0124.html#rids-broken  

If the network connection is broken or closed before the client receives a response to a request from the connection manager, then the client MAY resend an exact copy of the original request. Whenever the connection manager receives a request with a **'rid' that it has already received, it SHOULD return an HTTP 200 (OK) response** that includes the buffered copy of the original XML response to the client (i.e., a <body/> wrapper possessing appropriate attributes and optionally containing one or more XML payloads).

Is this bug in ejabberd ?

**Comment by zinid** [comment]
Old mod_http_bind is unsupported, could you try with recent ejabberd (17.01) and report if the bug still exists.

**Comment by vijayaa** [comment]
i have tested with 17.01 also.Same issue

**Comment by cromain** [comment]
with 17.01 you should be using mod_bosh instead of mod_http_bind. do you get this with mod_bosh ?
