### ISSUE TITLE
postinstall script not setting the home directory correctly

### ISSUE THREAD

**Issue by rafael-driutti-olx** [processone/ejabberd#1579]
> What version of ejabberd are you using?

17.01-0

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

.deb package from https://www.process-one.net/downloads/

> What did not work as expected? Are there error messages in the log? What
> What was the unexpected behavior? What was the expected result?

The home for the ejabberd user is not set to the install dir of ejabberd, i.e. instead of 

`ejabberd:x:1212:1212::/opt/ejabberd-17.01:`
 
I get 

`ejabberd:x:1212:1212::/home/ejabberd:`

This causes the clustering to fail since it looks for the .erlang.cookie at the wrong path.

From what I could see this is caused by the postinstall.sh script on the package:

```
id=$(id -u)
[ $id -eq 0 ] && {
  useradd -r ejabberd 2>/dev/null
  [ -d "@@INSTALLDIR@@" ] || usermod -d "@@INSTALLDIR@@" ejabberd
```

Shoud be 

```
id=$(id -u)
[ $id -eq 0 ] && {
  useradd -r ejabberd 2>/dev/null
  [ -d "@@INSTALLDIR@@" ] && usermod -d "@@INSTALLDIR@@" ejabberd
```

I can't find those scripts on the repo though.

**Comment by cromain** [comment]
the home dir change is now enforced when installed by root (or installing .rpm/.deb)
