### ISSUE TITLE
User can not create own account

### ISSUE THREAD

**Issue by Thomas301263** [processone/ejabberd#1582]
> What version of ejabberd are you using?

ejabberd Version (16.01-2)

> What operating system (version) are you using?

Ubuntu 16.04.02
Kernel 4.4.0-64-generic

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have upgraded my Ubuntu from 12.04 to 16.04 as well ejabberd installed from repository.
I am using mysql to keep all datas. Before a user was able to create an account by itself.
Now it can be done only by admin and am getting a error message in ejabberd. Maybe it is a mistake in configuration of mysql but why was it working before the upgrade.

[logs.zip](https://github.com/processone/ejabberd/files/814502/logs.zip)

**Comment by badlop** [comment]
In those log files I see a lot of errors like
> 2017-03-01 22:22:37.065 [error] <0.1197.0>@ejabberd_odbc:log:665 p1_mysql_recv: Failed connecting to "localhost":3306 : {error,econnrefused}

Maybe the port is wrong, or the updated server has that port blocked...

If the connection works correctly, and existing users can login and see their contacts... then the problem is in the mod_register configuration: maybe when Ubuntu updated, it used a more restrictive mod_register configuration, to prevent abuse of spammers.

**Comment by Thomas301263** [comment]
I know that there are a lot of errors in the logfile.
It is possible to create users only by admin. Users then can login and work with their chat program.
I know usually everybody should be able to create their own account cause it was working in
Ubuntu 12.04. 
I will put here my config file and hope maybe there is the mistake. I checked it several times and did not see any mistakes. Maybe you will see it immediately if you have a look at it.
[ejabberd.yml.zip](https://github.com/processone/ejabberd/files/816030/ejabberd.yml.zip)

**Comment by suchatorg** [comment]
mod_register disables ip_access: trusted_network

`    ## ip_access: trusted_network`

**Comment by Thomas301263** [comment]
Thanks for your answer.
changed it into      ## ip_access: trusted_network      
[ejabberd_files.zip](https://github.com/processone/ejabberd/files/816443/ejabberd_files.zip)
 but no user can registrate by itself.
ejabberd.yml and ejabberd.log are in the zip file

**Comment by Thomas301263** [comment]
Sorry made a mistake. After reloading the machine it is working. 
Many thanks to all.

**Comment by joaolima** [comment]
It's not workin for me..
