### ISSUE TITLE
Please consider adding more examples to ejabberd.yml.template

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#1583]
Hi,
there is a report at https://bugs.debian.org/855493#5 that has some IMHO sensible suggestions how ejabberd.yml.template can be improved to make configuring ejabberd faster and easier.

I would like to see them added upstream as I try to keep the default ejabberd.yml in Debian as close as possible to the ejabberd.yml.template you provide. The current diff is available at http://git.deb.at/w/pkg/ejabberd.git/blob/HEAD:/debian/patches/ejabberd.yml.example.diff

**Comment by zinid** [comment]
Feel free to create a PR.
We also should consider improving default cipher suites, btw.

**Comment by zinid** [comment]
Regarding `s2s_use_starttls: optional`. I think we can set to `required` in `ejabberd.yml.example`. We won't face problems with self-signed certs, because dialback will still work in this case. The problem with bad certs would occur only if we set it to `required_trusted`.

**Comment by debalance** [comment]
Unless you run into an old Openfire server with an incompatible dialback implementation ;)

Do the p1 installer + packages provide a self-signed cert? I assued they don't and that was the reason that s2s encryption is disabled by default.

**Comment by zinid** [comment]
Indeed, legacy software is a problem. However, seems like encryption is a trendy stuff nowadays, we probably want to jump on the bandwagon (I see virtually no technical benefits, this is pure marketing decision).
Regarding providing certs: we consider adding ACME protocol support in future releases (#1503).

**Comment by cromain** [comment]
some suggestions are good and injected in ejabberd.yml.example and will be applied to default configuration when possible
