### ISSUE TITLE
ejd2sql error exception

### ISSUE THREAD

**Issue by tejayson** [processone/ejabberd#1584]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

Linux 2.6.32-573.18.1.el6.x86_64

> How did you install ejabberd (source, package, distribution)?

rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to switch the database to mysql according to the guideline [here](https://docs.ejabberd.im/admin/guide/databases/mysql/).  It looks fine all the way except that at the last step of this procedure (i.e. to run ejd2sql from erlang debug shell),  it gives me such an error:
```
(ejabberd@localhost)1> ejd2sql:export("mydomain.com", sql)
(ejabberd@localhost)1> .
** exception error: no case clause matching {atomic,{atomic,ok}}
     in function  ejd2sql:'-export/3-fun-2-'/4 (src/ejd2sql.erl, line 81)
     in call from lists:foreach/2 (lists.erl, line 1337)
     in call from ejd2sql:export/3 (src/ejd2sql.erl, line 79)
     in call from lists:foreach/2 (lists.erl, line 1337)
     in call from ejd2sql:export/2 (src/ejd2sql.erl, line 70)
(ejabberd@localhost)2> 
```
At the mysql database I could still find some data migrated but not all.   Any idea about this? Thx in advance.

**Comment by badlop** [comment]
Problem confirmed. This simple patch should solve it:
```
diff --git a/src/ejd2sql.erl b/src/ejd2sql.erl
index ae37a9b..66411ef 100644
--- a/src/ejd2sql.erl
+++ b/src/ejd2sql.erl
@@ -172,7 +172,8 @@ export(LServer, Table, IO, ConvertFun) ->
 output(_LServer, _Table, _IO, []) ->
     ok;
 output(LServer, _Table, sql, SQLs) ->
-    ejabberd_sql:sql_transaction(LServer, SQLs);
+    {atomic, ok} = ejabberd_sql:sql_transaction(LServer, SQLs),
+    ok;
 output(_LServer, Table, Fd, SQLs) ->
     file:write(Fd, ["-- \n-- Mnesia table: ", atom_to_list(Table),
                     "\n--\n", SQLs]).
```
You can download ejabberd source code, apply this small change, compile that file (or all ejabberd), then copy ej2sql.beam to the ejabberd ebin dir, restart ejabberd, and try it again.

**Comment by tejayson** [comment]
Many thanks for the fix!  I tried compiling in my own environment and the compilation looks smooth.
Anyway here comes another error:

(ejabberd@localhost)1> ejd2sql:export("mydomain.com", sql).
** exception error: undefined function mod_pubsub:export/1
     in function  ejd2sql:export/3 (ejd2sql.erl, line 87)
     in call from lists:foreach/2 (lists.erl, line 1337)
     in call from ejd2sql:export/2 (ejd2sql.erl, line 70)
(ejabberd@localhost)2>

Is it necessary to further apply the fix in [#1571](https://github.com/processone/ejabberd/issues/1571)?  Thanks again.

**Comment by badlop** [comment]
You have two alternatives, apply the patch that I've commented in #1571, but doesn't produce valid SQL. Or preferably, remove mod_pubsub in the file ejd2sql.erl

**Comment by zinid** [comment]
@badlop I think this is basically a bad recommendation to patch anything for someone who is clueless. We should fix this ourselves.

**Comment by badlop** [comment]
Right. As pubsub export is not ieven implemented, that line must be removed in ejd2sql.erl. Implementing that feature is handled in #1571.

**Comment by cromain** [comment]
@badlop i think this is fixed now. Please reopen if we miss anything.
