### ISSUE TITLE
Include shared groups also when contact is is personal roster

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#1585]
When a JID would appear several times in a user's roster because of a manual contact and/or several shared roster groups with (partially) the same members, ejabberd simply filters out all but the first occurrence:

https://github.com/processone/ejabberd/blob/master/src/mod_shared_roster.erl#L175-L176

This causes incomplete shared roster groups in the users' contact list.
Instead of just deleting the duplicate contact, please add a corresponding \<group/\> element to the first  occurrence of the JID, so the contact shows up in all groups it is supposed to be in.
IMO this would improve shared roster groups a lot.

I have noticed the above behaviour in all versions from at least 14.07 until current master,
in both mod_shared_roster and mod_shared_roster_ldap.

According to https://tools.ietf.org/html/rfc6121#section-2.1.2.6
"An \<item/\> element MAY contain more than one \<group/\> element, which means that roster groups are not exclusive."

**Comment by badlop** [comment]
This is already done when the contact is in several shared roster groups, but not in the user roster: all groups are returned. The problem is only when the contact is not only in shared groups, but also in the user roster.

**Comment by debalance** [comment]
Thank you @badlop !
