### ISSUE TITLE
can't make a dump of the database..

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1587]
> What version of ejabberd are you using?
17

> What operating system (version) are you using?
Debian 8

./ejabberdctl backup /var/log/tmp/dump.txt
Can't store backup in "/var/www/log/tmp/dump.txt" at node ejabberd@localhost: {'EXIT',
                                                                                  {error,
                                                                                   {file_error,
                                                                                    "/var/www/log/tmp/dump.txt.BUPTMP",
                                                                                    eacces}}}

./ejabberdctl dump_table /var/www/log/test.txt vcard
Can't store dump in "/var/www/fastguide/tmp/test.txt" at node ejabberd@localhost: eacces

What am i doing wrong?

**Comment by zinid** [comment]
`eaccess` means you don't have enough permissions on file system to perform write.

**Comment by PH-F** [comment]
ok, but the folder is 777, so had no restrictions.

**Comment by haegar** [comment]
Check that the user-account running the ejabberd also has at least rx permissions on the directories below the tmp, like /var/www and /var/www/log.
Perhaps try it out first writing directly into /tmp.

Also make sure that you are not using something like acl, selinux or apparmor which can introduce further restrictions besides the posix file permissions and may need specific settings to allow the write into the target directory.

**Comment by PH-F** [comment]
Thx did the trick, thanks
