### ISSUE TITLE
Can't login with 17.03-beta

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#1588]
> What version of ejabberd are you using?

17.03-beta via Docker image (built using ecs/mix)

> What operating system (version) are you using?

Docker on Synology

> How did you install ejabberd (source, package, distribution)?

Docker image [mbirth/ejabberd-ecs](https://hub.docker.com/r/mbirth/ejabberd-ecs/) 17.03-beta built using official toolchain.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When a client tries to login, the following error appears:

```
19:20:28.711 [info] (<0.1875.0>) Accepted connection 172.17.0.1:46363 -> 172.17.0.2:5222
19:20:28.740 [info] (<0.1877.0>) Accepted connection 172.17.0.1:46364 -> 172.17.0.2:5222
19:20:28.741 [info] (<0.1879.0>) Accepted connection 172.17.0.1:46365 -> 172.17.0.2:5222
19:20:29.140 [info] (tls|<0.1879.0>) Accepted c2s SCRAM-SHA-1 authentication for user@example.org by mnesia backend from 172.17.0.1
19:20:29.157 [info] (tls|<0.1875.0>) Accepted c2s SCRAM-SHA-1 authentication for user@example.org by mnesia backend from 172.17.0.1
19:20:29.492 [error] gen_server <0.1876.0> terminated with reason: call to undefined function jid:encode/1 from ejabberd_c2s:bind/2 line 405
19:20:29.492 [error] CRASH REPORT Process <0.1876.0> with 0 neighbours exited with reason: call to undefined function jid:encode({jid,<<"user">>,<<"example.org">>,<<"gajim.8BRBU6TM">>,<<"user">>,<<"example.org">>,<<"gajim.8BRBU...">>}) in p1_server:terminate/7 line 874
19:20:29.492 [error] Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.1876.0> exit with reason call to undefined function jid:encode({jid,<<"user">>,<<"example.org">>,<<"gajim.8BRBU6TM">>,<<"user">>,<<"example.org">>,<<"gajim.8BRBU...">>}) in context child_terminated
19:20:29.642 [error] gen_server <0.1880.0> terminated with reason: call to undefined function jid:encode/1 from ejabberd_c2s:bind/2 line 405
19:20:29.642 [error] CRASH REPORT Process <0.1880.0> with 0 neighbours exited with reason: call to undefined function jid:encode({jid,<<"user">>,<<"example.org">>,<<"phone">>,<<"user">>,<<"example.org">>,<<"phone">>}) in p1_server:terminate/7 line 874
19:20:29.642 [error] Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.1880.0> exit with reason call to undefined function jid:encode({jid,<<"user">>,<<"example.org">>,<<"phone">>,<<"user">>,<<"example.org">>,<<"phone">>}) in context child_terminated
```

**Comment by zinid** [comment]
`xmpp` library is outdated.
I would say `make distclean`, but I don't know the building process for docker/mix/etc.

**Comment by mbirth** [comment]
Seems like the https://github.com/processone/ejabberd/blob/master/mix.lock isn't updated. This is the file the docker/mix-tool uses.

**Comment by mbirth** [comment]
What I did to make it work:

Change `mix.exs`:

```
     {:fast_xml, git: "https://github.com/processone/fast_xml.git", tag: "1.1.21", override: true},
     {:xmpp, git: "https://github.com/processone/xmpp.git", tag: "1.1.8"},
```

And then, after it pulled `fast_xml` from the GitHub, it complained about a missing `rebar` binary (used in the Makefile). So I copied the one from `deps/xmpp/rebar` to `deps/fast_xml` and changed all occurrences in `Makefile` from `rebar` to `./rebar` and that made it compile.

**Comment by cromain** [comment]
this should now be fixed without need to change mix.exs nor copy rebar.
we'll also improve this by releasing the corresponding new deps as clean hex.pm package, but this may come a bit after 17.03 release, and this should not impact the build process anyway.
