### ISSUE TITLE
Ejabberd Security?

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1589]
Hi

We re going to release our chat product soon to the market. And before going to production I would like to make sure that our ejabberd community server is secure enough (version 16.09)

As a first step I've checked our xmpp servers security through this website
https://xmpp.net/result.php?domain=chat.xxx.com.tr&type=client

Then I've recevied some ssl certificate issues, now I'm trying to solve them.

But other than the certificate I would like to learn something

1. I'm planning to disable xmpp clients registration to our servers. Because we are using our custom registration system. How can I do that?
2. I want to disable anonymous login to our server. How can I do that?
3. I wonder are there anything more to check as a security precaution?

Thanks

**Comment by zinid** [comment]
> I'm planning to disable xmpp clients registration to our servers. Because we are using our custom registration system. How can I do that?

Make sure `mod_register` is not loaded.

> I want to disable anonymous login to our server. How can I do that?

It's disabled by default.

**Comment by tolgatanriverdi** [comment]
Thanks
