### ISSUE TITLE
Roster item with subscription 'none' doesn't have subscribe attribute

### ISSUE THREAD

**Issue by davideko** [processone/ejabberd#1590]
> What version of ejabberd are you using?
```
17.01
```
> What operating system (version) are you using?
```
ubuntu 14.04 LTS
```
> How did you install ejabberd (source, package, distribution)?

```
distribution
```
> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

By doing this fetch roster IQ in Ejabberd 17.01 : 
```
<iq id='r1h3vzp7' type='get'>
  <query xmlns='jabber:iq:roster'/>
</iq>
```

Expected
```
...
  <item subscription='none' name='aloy' jid='aloy@lalala.id'/>
...
```

Actual
```
...
  <item name='aloy' jid='aloy@lalala.id'/>
...
```
 I think that's a bug, because in the Ejabberd version < 16.12 it's always contain `subscription` attribute event it's subscription is `none`

**Comment by zinid** [comment]
From [RFC6121, Secion 2.1.2.5](https://tools.ietf.org/html/rfc6121#section-2.1.2.5):
```
none:  the user does not have a subscription to the contact's
      presence, and the contact does not have a subscription to the
      user's presence; this is the default value, so if the subscription
      attribute is not included then the state is to be understood as
      "none"
...
Inclusion of the 'subscription' attribute is OPTIONAL
```

**Comment by davideko** [comment]
Thank you for the explanation @zinid !
