### ISSUE TITLE
ejabberd does not deliver RHOST to pam

### ISSUE THREAD

**Issue by dorchain** [processone/ejabberd#1591]
> What version of ejabberd are you using?
16.09-4

> What operating system (version) are you using?
Debian testing

> How did you install ejabberd (source, package, distribution)?
distro

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

With references to https://support.process-one.net/browse/EJAB-1720, the relevant code of ejabberd has not changed.

I use ejabberd with pam authentication.
As with other network services, I like to have ejabberd to to use different pam stacks depending on the remote side, e.g. with the help of pam_access(8)
ejabberd however does not set the PAM_RHOST, thus making all connectings appear to come from LOCAL.
Please make the epam helper forward the remote end.

**Comment by jeffWelling** [comment]
This may be blocked by https://github.com/processone/epam/pull/3

**Comment by zinid** [comment]
Hum, I somehow mislooked the PR.
The PR is actually ok, I merged it.
