### ISSUE TITLE
Unable to use ejabberdctl for sending messages from commandlline

### ISSUE THREAD

**Issue by kalabantas** [processone/ejabberd#1592]
> What version of ejabberd are you using?

17.01 or 17.03 beta

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

From Ubuntu deb installer

> What did not work as expected? 

ejabberdctl send_message

> Are there error messages in the log?

No error messages in the log file. The message seems to go through, however it is not archived in the mam, and not delivered.

> What was the unexpected behavior? What was the expected result?

The expected result was to deliver the message as previous versions.

**Comment by prefiks** [comment]
Hello,

When you did call this command did you get any output in console?
Do you have api_permissions: option in your config file?

**Comment by kalabantas** [comment]
Hello, 
I get no output on the console whatsoever, as if the message goes through. I don't have any api_permisssions in the configuration file.

And here is the output from ejabberd.log with debug enabled. Shows that as if the message has gone through. 
from = {jid,<<"user1">>,<<"my.domain.tlc">>,
                     <<>>,<<"user1">>,
                     <<"my.domain.tlc">>,<<>>},
         to = {jid,<<"user2">>,
                   <<"my.domain.tlc">>,<<>>,
                   <<"user2">>,
                   <<"my.domain.tlc">>,<<>>},
         subject = [#text{lang = <<"en">>,data = <<"subject">>}],
         body = [#text{lang = <<"en">>,data = <<"Hello">>}],
         thread = undefined,sub_els = [],meta = #{}}
2017-03-06 03:37:56.857 [debug] <0.617.0>@ejabberd_sm:do_route:561 processing message to bare JID:
#message{id = <<>>,type = chat,lang = <<>>,
         from = {jid,<<"user1">>,<<"my.domain.tlc">>,
                     <<>>,<<"user1">>,
                     <<"my.domain.tlc">>,<<>>},
         to = {jid,<<"user2">>,
                   <<"my.domain.tlc">>,<<>>,
                   <<"user2">>,
                   <<"my.domain.tlc">>,<<>>},
         subject = [#text{lang = <<"en">>,data = <<"subject">>}],
         body = [#text{lang = <<"en">>,data = <<"Hello">>}],
         thread = undefined,sub_els = [],meta = #{}}
2017-03-06 03:37:56.857 [debug] <0.617.0>@ejabberd_sm:route_message:631 sending to process <13799.1853.0>

I searched for the message in the database, it is not archived, and is not delivered.
I tried with emtpy subject, with chat as subject, no luck.

**Comment by badlop** [comment]
Hi, I try with ejabberd 17.03-beta and works correctly. In your log it shows the message is sent to a client connected to another ejabberd node of your cluster. Just for curiosity, try to connect to the same node where you execute the command, is it then delivered?

**Comment by kalabantas** [comment]
I tried this as well, I connected to the same node as the cluster, however, it doesn't get delivered.

**Comment by kalabantas** [comment]
Does anyone have any suggestions?

**Comment by cromain** [comment]
maybe you added that user to privacy list, and so message gets dropped by server.
