### ISSUE TITLE
Ejabberd Logs in Admin Panel

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1594]
Hi

I'm using ejabberd 16.09 and I wonder if is there any way to see ejabberd logs through web admin panel.
Because now each time I need to check the logs. I have to login the computer which ejabberd is installed and then through command line I need to check the log files(which is becoming very hard)
Is there any plugin for that?

Thanks

**Comment by zinid** [comment]
No, there is no such plugin.
And I'm not sure what the plugin should do. Dumping logs in a web-browser is not a good idea, because it's much better to read it via SSH using convenient tools like grep/sed/awk/etc.

**Comment by tolgatanriverdi** [comment]
I thought it may be something like cloud  management systems log panel(Google cloud, Amazon cloud etc..) They are formatting the log files and showing it to users with a beatiful user interface.
So the developers doesnt spend much time to get  what the actual problem is  from the log files

**Comment by zinid** [comment]
Yeah :)
The task in formatting logs is not very simple, Google and Amazon can afford it for sure :)

**Comment by badlop** [comment]
In such a situation, I have mod_shcommands installed and go to
http://localhost:5280/admin/node/ejabberd@localhost/shcommands/
where I can execute shell queries like: cat /...log | grep -C 3 ERROR
