### ISSUE TITLE
restrict connect from different machine

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1597]
> What version of ejabberd are you using?
17

> What operating system (version) are you using?
Debian 8

I have 2 servers with ejabberd
When i connect with <user>@server1    I am able to send a message to <user2>@server2
This i find very strange. It is not only a different vhost it is different server.
How can i restrict this?

**Comment by zinid** [comment]
As I understand you want to disable s2s at all?
Then add the following to the config:
```yaml
s2s_access: deny
```
