### ISSUE TITLE
mod_auth_external vs. apparmor

### ISSUE THREAD

**Issue by sualko** [processone/ejabberd#1598]
> What version of ejabberd are you using?

ejabberd 16.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to use an [external python script](https://docs.ejabberd.im/admin/configuration/#external-script) to authenticate my users. After 2 days of searching, testing, stracing and so on, [I found out](http://lists.jabber.ru/pipermail/ejabberd/2015-October/008840.html) that ejabberd comes with an apparmor profile :imp:. At least this should be documented somewhere...

**Comment by zinid** [comment]
We do not maintain Ubuntu's packages.

**Comment by debalance** [comment]
Just for the record, this IS documented in /usr/share/doc/ejabberd/NEWS.Debian.gz,
you can install and configure apt-listchanges accordingly if you want to be shown these automatically during upgrades.

Also, AppArmor pretty much jumps you in the face in dmesg, which is one of the first things I check when things are not working as they should.

**Comment by sualko** [comment]
People (non-high end linux freaks) get frustrated by such things. Please reconsider this.

**Comment by zinid** [comment]
By what things? We do not have enough human resources to maintain packages for linux distros.

**Comment by lemenkov** [comment]
Looks like a downstream (not upstream) bug. This should be addressed by Debian maintainer, not here.

**Comment by zinid** [comment]
@lemenkov the Debian maintainer replied in this thread already :)

**Comment by sualko** [comment]
I think a small notice in the documentation would not hurt and would help so many people, but this is your decision.

**Comment by debalance** [comment]
@sualko, what documentation are you talking about?

**Comment by sualko** [comment]
https://docs.ejabberd.im/admin/configuration/#external-script

**Comment by zeigerpuppy** [comment]
This looks like an issue for me too.  I'm not sure how to solve it (maybe by adding permission for running xauth.py in the ejabberd apparmour profile?)
I agree it would be good to document it somewhere with a suggestion of how to fix.
On that note if anyone has fixed this, could you please also post the fix here (I will if I manage to sort it out!)

**Comment by zeigerpuppy** [comment]
a simple way to test this is to remove the apparmor profile.
In my case: `apparmor_parser -R /etc/apparmor.d/usr.sbin.ejabberdctl`

It looks like apparmor is not the problem for me but I thought I'd add this here to help others debug anyway...
