### ISSUE TITLE
Possibility to disable in-band account unregister?

### ISSUE THREAD

**Issue by haegar** [processone/ejabberd#1599]
> What version of ejabberd are you using?
17.01, with mysql storage

> What operating system (version) are you using?
Debian

> How did you install ejabberd (source, package, distribution)?
source, git tag

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have multiple users that suffered from their accounts beeing deleted. Could be because of the psi(plus) bug https://github.com/psi-plus/main/issues/671, but was also reported from users with only pidgin and conversations.

To avoid this, is it somehow possible to disable in-band account unregistration, but leave registration and password-changing possible? (So not just removing mod_register)

**Comment by zinid** [comment]
Alas, it's not supported, but quite useful feature indeed.

**Comment by zinid** [comment]
Fixed in a8dc5f80d11305fc73d866d1cc3ecff9ecb2e1bd

**Comment by zinid** [comment]
So the simplest configuration to disable in-band registration will look like:
```yaml
mod_register:
  access_remove: deny
```
