### ISSUE TITLE
Test ejabberd clustering, how load distributed within nodes added within single cluster.

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1601]
> What version of ejabberd are you using?

Ejabberd Community Version source code 16.09 release

> What operating system (version) are you using?

CentOs 7

> How did you install ejabberd (source, package, distribution)?

source

Hi I have added nodes in ejabberd and implemented clustering as guided by following link
https://docs.ejabberd.im/admin/guide/clustering/

1. I have added two nodes node1 and node2, but how do I test clustering ?
2. At what criteria connections get switched between nodes ? 
3. Can clustering take care of load distribution among node present in cluster ?
4. Is it possible to add/remove node in cluster dynamically (i mean depending upon load)?
5. Is there any documentation to test ejabberd clustering successful?

can anyone @badlop @zinid  guide me, I am new in ejabberd world.

Regards,
Veer.

**Comment by badlop** [comment]
> I have added two nodes node1 and node2, but how do I test clustering ?
> Is there any documentation to test ejabberd clustering successful?

One idea  for simple testing:
Some Jabber clients allow the user to specify not only the server name, but also the IP address and port number to connect. So, you can specify to what exact node you want your client to connect. 

In this sense, register an account in a node, then try to login to that account in that node, and also in the other node. Add contacts to its roster, and check if they are shown regardless of the node where the client connects.

> At what criteria connections get switched between nodes ?
> Can clustering take care of load distribution among node present in cluster ?
> Is it possible to add/remove node in cluster dynamically (i mean depending upon load)?

From what I know, ejabberd itself does not perform load balancing. It is your clients the ones that must connect to one or the other node. Of course, the clients don't know beforehand which node is less loaded, and don't need to know at all there are several nodes. So, it is your task to install a DNS load balancer program in the server, that checks periodically the load of your nodes, and tells the clients the IP address where they can connect.

**Comment by Veerbhadra277** [comment]
Thanks @badlop for response,

still have not cleared few points, it would be great if you can guide me

1. Can we add node at run time (programatically)? 
2. I tried to login to specific node with spark client by providing node ip address but still it logins to first node though i have provided ip address of second node, do you recommend other clients?

Thanks for your help !! 

Regards,
Veer

**Comment by badlop** [comment]
> 1. Can we add node at run time (programatically)?

Yes, in your new node, run something like:
* ejabberdctl join_cluster ejabberd@host1


> 2. I tried to login to specific node with spark client by providing node ip address but still it logins to first node though i have provided ip address of second node, 

Strange, so you have two nodes, in two different IP addresses, and it doesn't care which IP address you provide to the client, it always logins to the same node (and you can see that in the ejabberd logs)?

> do you recommend other clients?

Yes, you can try:
* Gajim, in Accounts -> Connection -> Use custom hostname/port: ...
* Psi, in Account Properties -> Connection -> Manually Specify server host/port: ...
* Tkabber, in Start -> Connection -> Specify explicit host and port: ...

**Comment by Veerbhadra277** [comment]
Thank for your guidance @badlop, but it still facing same issue, let me explain my current setup,

I have configure ejabberd on Node1 and done same setup on Node2, now I implemented custering between two nodes, so Node1(IP: 192.168.3.111) and Node2(IP: 192.168.3.113) are the part of cluster. Now I want to connect some connection with Node1 and some with Node2. both node have same yml configuration(exactly same, not single line of word)

As ejabberd is running on Node1 by default, I tried connect with spark and Tkabber client to Node2 by providing following configuration,
![image](https://cloud.githubusercontent.com/assets/8426382/24044931/5127db9c-0b43-11e7-9436-2e1978e281e9.png)

but when i observed  in web admin UI, it is still showing client is connected to Node1.
Is there configuration i have missed here ? 

Regards,
Veer

**Comment by badlop** [comment]
> when i observed in web admin UI, it is still showing client is connected to Node1.

In what page do you read that information? And what exactly does it show?

You should also check the ejabberd log files in both nodes. Only the node where the client actually connect will show the typical lines regarding the 5222 connection, and user authentication.
