### ISSUE TITLE
Unable to see user status

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1605]
> What version of ejabberd are you using?
17 

> What operating system (version) are you using?
Debian

> How did you install ejabberd (source, package, distribution)?
deb package

I can't see the status of a user, everybody stays offline. Yet, in the admininterface i see that the users are online. In the firewall I opened ports 5222, 5269, 5280 for our IPddresses

**Comment by zinid** [comment]
What exact version of ejabberd are you using?
What clients are you using? Are you sure the clients are sending inital presences?

**Comment by PH-F** [comment]
v 17.01, but i noticed that if both users send a contact request and add each other to the buddies group it works. (in ejabberd 2. this was not necessary.

Is there some kind of auto accept option?

**Comment by zinid** [comment]
It shouldn't have worked in ejabberd 2.x (otherwise this is RFC violation).
Anyway, there is `mod_shared_roster` module, if you put both users in a shared roster, no subscription is required.
