### ISSUE TITLE
User not functioning properly after receiving a flood of messages

### ISSUE THREAD

**Issue by mithunraman** [processone/ejabberd#1606]
> What version of ejabberd are you using?
16.09

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

An Ejabberd client logged into the system after a really long time period of inactivity and received around 1.5k+ messages. Ever since that, the client is unable to send messages and interact with other clients.

Ejabberd Logs
CRASH REPORT Process <0.16454.0> with 0 neighbours exited with reason: {process_limit,{max_queue,1017}} in p1_fsm:terminate/8 line 755
2017-03-14 17:36:08.833 [info] <0.14348.0>@ejabberd_c2s:terminate:1851 ({socket_state,gen_tcp,#Port<0.19485>,<0.14347.0>}) Close session for 58520a849b754a7d052aad63@domain.com/Smack

Crash Logs
2017-03-14 17:35:55 =CRASH REPORT====
  crasher:
    initial call: ejabberd_c2s:init/1
    pid: <0.16454.0>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1017}},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,755}]},{p1_fsm,loop,10,[{file,"src/p1_f
sm.erl"},{line,433}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.414.0>,ejabberd_listeners,ejabberd_sup,<0.62.0>]
    messages: [{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"id">>,<<"xXhie-10">>},{<<"type">>,<<"set">>}],[{xmlel,<<"query">>,[{<<"xmlns"
>>,<<"jabber:iq:privacy">>}],[{xmlel,<<"list">>,[{<<"name">>,<<"public">>}],[{xmlel,<<"item">>,[{<<"action">>,<<"deny">>},{<<"order">>,<<"9">>},{
<<"type">>,<<"subscription">>},{<<"value">>,<<"both">>}],[{xmlel,<<"presence-in">>,[],[]}]}]}]}]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq"
>>,[{<<"to">>,<<"pubsub.chat.domain.com">>},{<<"id">>,<<"xXhie-11">>},{<<"type">>,<<"get">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"http://jabbe
r.org/protocol/disco#info">>},{<<"node">>,<<"ojas.global">>}],[]}]}}}]
    links: []
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 999631
    stack_size: 27
    reductions: 23472789
  neighbours:
2017-03-14 17:46:12 =CRASH REPORT====
  crasher:
    initial call: ejabberd_c2s:init/1
    pid: <0.16748.0>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1023}},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,755}]},{p1_fsm,loop,10,[{file,"src/p1_fsm.erl"},{line,433}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.414.0>,ejabberd_listeners,ejabberd_sup,<0.62.0>]
messages: [{'$gen_event',{xmlstreamelement,{xmlel,<<"r">>,[{<<"xmlns">>,<<"urn:xmpp:sm:3">>}],[]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"id">>,<<"xXhie-10">>},{<<"type">>,<<"set">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"jabber:iq:privacy">>}],[{xmlel,<<"list">>,[{<<"name">>,<<"public">>}],[{xmlel,<<"item">>,[{<<"action">>,<<"deny">>},{<<"order">>,<<"9">>},{<<"type">>,<<"subscription">>},{<<"value">>,<<"both">>}],[{xmlel,<<"presence-in">>,[],[]}]}]}]}]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"to">>,<<"pubsub.chat.domain.com">>},{<<"id">>,<<"xXhie-11">>},{<<"type">>,<<"get">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/disco#info">>},{<<"node">>,<<"ojas.global">>}],[]}]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"presence">>,[{<<"id">>,<<"xXhie-12">>},{<<"type">>,<<"unavailable">>}],[]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"id">>,<<"xXhie-13">>},{<<"type">>,<<"set">>}],[{xmlel,<<"bind">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-bind">>}],[{xmlel,<<"resource">>,[],[{xmlcdata,<<"Smack">>}]}]}]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"presence">>,[{<<"id">>,<<"xXhie-15">>}],[{xmlel,<<"status">>,[],[]},{xmlel,<<"priority">>,[],[{xmlcdata,<<"1">>}]},{xmlel,<<"show">>,[],[{xmlcdata,<<"away">>}]},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"hash">>,<<"sha-1">>},{<<"node">>,<<"http://www.igniterealtime.org/projects/smack">>},{<<"ver">>,<<"rKysqnxDz2Bth9nptrGfKC/YJAo=">>}],[]}]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"r">>,[{<<"xmlns">>,<<"urn:xmpp:sm:3">>}],[]}}},{'$gen_event',{xmlstreamelement,{xmlel,<<"iq">>,[{<<"id">>,<<"xXhie-16">>},{<<"type">>,<<"set">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"jabber:iq:privacy">>}],[{xmlel,<<"list">>,[{<<"name">>,<<"public">>}],[{xmlel,<<"item">>,[{<<"action">>,<<"deny">>},{<<"order">>,<<"9">>},{<<"type">>,<<"subscription">>},{<<"value">>,<<"both">>}],[{xmlel,<<"presence-in">>,[],[]}]}]}]}]}}}]
    links: []
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 999631
    stack_size: 27
    reductions: 23731418
  neighbours:

Not sure what is causing this issue. Any idea on as to how to proceed ?

Thanks,

**Comment by zinid** [comment]
You should nothing to do with it.
That means the client doesn't process data at all (i.e. it doesn't read the socket, or reads it very slowly). Once an internal queue of the corresponding c2s process is overloaded, this error is logged.

**Comment by mithunraman** [comment]
Hi Zinid,

Thank you for the response.

I tried doubling up the value of max_fsm_queue. Things started working fine after that. Are there any side effects of increasing the mentioned limit?

**Comment by zinid** [comment]
Too large `max_fsm_queue` value makes your server vulnerable for some type of DoS attacks. I do not recommend setting it larger than 5000, because anyway a client will likely get its ass destroyed receiving an avalanche of 5000+ messages.

**Comment by mithunraman** [comment]
True true. Thanks a lot for the advice. :)

Will close the issue now.
