### ISSUE TITLE
Error in Gajim if am using http upload

### ISSUE THREAD

**Issue by Thomas301263** [processone/ejabberd#1607]
> What version of ejabberd are you using?
ejabberd 16.01 is running in that node

> What operating system (version) are you using?
Ubuntu 16.04 server
Kernel   4.4.0-66-generic

> How did you install ejabberd (source, package, distribution)?
Installed from source code

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to manage http_upload but it was not working. I got an error in Gajim if am trying to use it
![bildschirmfoto vom 2017-03-15 13-44-33](https://cloud.githubusercontent.com/assets/15796948/23948965/a2e331d0-0985-11e7-8f70-b2af79179138.png)
.
I am using gajim between two laptop one is Ubuntu 16.04 and the other Kubuntu 16.04
I want to use the server now internally and later maybe over Internet as well.
[ejabberd_and_nginx_files.tar.gz](https://github.com/processone/ejabberd/files/844453/ejabberd_and_nginx_files.tar.gz)

**Comment by zinid** [comment]
So you have the **ERROR**. Great. What should we do with this?
Also, in general we only accept bug reports for current ejabberd version.

**Comment by Thomas301263** [comment]
What can I do with that error. 
Basically it is not working and I do not know why.

**Comment by weiss** [comment]
> What can I do

- You could check your `ejabberd.log` for any messages related to the upload attempt.
- You could start Gajim from a terminal window and check the output while this is happening.
- You could open Gajim's XML console (`Actions` -> `Advanved` -> `Show XML Console`) before this is happening to see the traffic.
- If this doesn't help, please [ask the Gajim guys][1] how to get a proper error message.

[1]: https://dev.gajim.org/gajim/gajim-plugins/issues/new

**Comment by lovetox** [comment]
you can also start gajim with `-l gajim.plugin_system.httpupload=DEBUG`

**Comment by Thomas301263** [comment]
@weiss 
I haven't seen something strange in the log files of ejabberd. It seems to be normal.
If I start Gajim from the console it seems to be normal too. That is what I have done and as far as I read if all is working propably there should be an entry at /home/ejabberd/upload  but there is nothing so I thought somehing is wrong in my config but I checked it many times and didn't see a problem.
Maybe my eyes are not able to focus on that. I uploaded all files and it could be that my nginx confguration will not work together with the rest but am not sure.
@lovetox 
Have done like you wrote.
The output is a bit strange for me.

15.03.2017 18:11:06 (I) gajim.plugin_system.httpupload Encryption is: False / OMEMO not found
15.03.2017 18:11:06 (I) gajim.plugin_system.httpupload Detected MIME Type of file: image/jpeg
15.03.2017 18:11:06 (I) gajim.plugin_system.httpupload jid_to_servers of test@sielstetten: upload.sielstetten ; connection: <nbxmpp.client_nb.NonBlockingClient instance at 0x7f5b5810a950>
15.03.2017 18:11:06 (D) gajim.plugin_system.httpupload sending httpupload slot request iq...
15.03.2017 18:11:06 (I) gajim.plugin_system.httpupload Uploading file to 'https://sielstetten:5443/upload/09e0286ece2788b0d55c46620673d8d1f44fe10a/OM9g02h4sV3eKniOjeSfMIdBCvQlhleEqqxhuCHh/IMG_0118.JPG'...
15.03.2017 18:11:06 (I) gajim.plugin_system.httpupload Please download from 'https://sielstetten:5443/upload/09e0286ece2788b0d55c46620673d8d1f44fe10a/OM9g02h4sV3eKniOjeSfMIdBCvQlhleEqqxhuCHh/IMG_0118.JPG' later...
15.03.2017 18:11:06 (D) gajim.plugin_system.httpupload opening urllib2 upload request...
15.03.2017 18:11:06 (E) gajim.plugin_system.httpupload Error
Traceback (most recent call last):
  File "/home/thomas/.local/share/gajim/plugins/httpupload/httpupload.py", line 477, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
15.03.2017 18:11:23 (I) gajim.plugin_system.httpupload Account sielstetten: httpupload is_supported: True
15.03.2017 18:11:23 (I) gajim.plugin_system.httpupload Account sielstetten: httpupload is_supported: True

**Comment by lovetox** [comment]
yeah looks strange too me too, we have traceback but no error message even in the traceback.

this is definitly a gajim issue as i see it
can you open a issue with this traceback here

https://dev.gajim.org/gajim/gajim-plugins/issues/new

and close this one here.

thanks

**Comment by Thomas301263** [comment]
Yepp I will open a ticket there but 
the link to open an issue for gajim is wrong. 
Can you give me another one pls.
Thanks

**Comment by lovetox** [comment]
https://dev.gajim.org/gajim/gajim-plugins/issues

**Comment by Thomas301263** [comment]
That works thanks 
will close that issue here.
