### ISSUE TITLE
mod_block_strangers blocks messages from contacts in my roster with partial subscription

### ISSUE THREAD

**Issue by srgcdev** [processone/ejabberd#1609]
> What version of ejabberd are you using?

17.03 beta

> What operating system (version) are you using?

debian 8

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have a contact in my roster but I don't want this contact see my state for privacy reasons. I think is an A subscription. 
The problem is that I can't receive his messages until I let him to see my state. Also, I can't receive his messages but I receive his typing notifications.

**Comment by zinid** [comment]
So that's the goal of mod_block_strangers.

**Comment by srgcdev** [comment]
@zinid, I think this is not the goal of mod_block_strangers. The goal should be block messages from people who are not in your roster.
The case I describe is that I have a contact who is in my roster (I can see his status, available, busy, away...) but I don't want he knows what is my status (available, busy, away...), so I don't send him presence updates.

**Comment by zinid** [comment]
Ah, so the user stays with subscription `to` in your roster. You should have said this right away.
In this case yes, the module's behaviour is incorrect.

**Comment by alexeyshch** [comment]
Fixed in 9fb188afbceb5cb54f61d007ffdf5fca411bc1a5
