### ISSUE TITLE
How to stop packet processing

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1612]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb 

> How did you install ejabberd (source, package, distribution)?
 soruce

I have a custom packet that is coming from client say 
`<custom  attr1='value1'  to='jid1@host.com' from='jid2@host.com' type='t1' id='UX24s2s96-19'/>`
as the to here is jid the packet is processed and sent to jid2@host.com
however what i want to do if the custom packet is of type = 't1' I want to just recv it and then do some processing and then stop  so that its not sent further to jid2@host.com.
if i remove the to field after processing it becomes undfined and then gives me error on c2s  jid:to_lower()
what is the right way to stop the processing and discard the packet and in which hook should i do it ?
user_send / c2s_handle_rcv etc ?

Also after 17.x the packet always has 3 attrs xml:lang , to and from ... when sending packet i want to remove some fields like lang and to  just as to save some data on phone  how can i do this ?

**Comment by zinid** [comment]
Return `{stop, drop}` from your function hooked on `user_send_packet` hook.

**Comment by nOmi7** [comment]
i think its  {drop,State}  just saw c2s.

{Pkt2, State2} = ejabberd_hooks:run_fold(
		       user_send_packet, LServer, {Pkt1, State1}, []),
    case Pkt2 of
drop ->
    State2;

**Comment by nOmi7** [comment]
also how do i remove the extra attrs when sending final packet on network stream like lang and  jid string without resource which are put always by xmpp:encode i guess?

**Comment by zinid** [comment]
You can use `c2s_filter_send` hook. But removing 'from'/'to' is a terribly bad idea. You should not design a protocol like that.

**Comment by nOmi7** [comment]
i wont remove from .. only resource from from to jid and xml lang i dont need them .

**Comment by BesatZardosht** [comment]
I have some custom attribute on my messages which from ejabberd 16.12 is being removed. How can I prevent ejabberd from eliminating my custom attributes?
