### ISSUE TITLE
Some applications missing in "make rel" tree

### ISSUE THREAD

**Issue by weiss** [processone/ejabberd#1615]
> What version of ejabberd are you using?

Current Git code (2d67ff2249c3d6104f908246d7d53bedb5e0701e).

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Since commit 2f3f6f8b71e40954c44b81e15f637a2abe36ee35, the release generated by running `./configure && make && make rel` is missing `iconv` and another few applications (see the `ls rel/ejabberd/lib` output).

**Comment by prefiks** [comment]
Fixed by b9cd5ca07f75cc96ee847f25ebf273dff304e04f
