### ISSUE TITLE
Cannot establish S2S connections with Google Apps XMPP users

### ISSUE THREAD

**Issue by K0HAX** [processone/ejabberd#1618]
> What version of ejabberd are you using?

17.03.beta

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM Package from the website

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I cannot federate with GMail servers, I was able to on 16.12 right up until I upgraded.
2017-03-17 16:19:25.110 [info] <0.2122.0>@ejabberd_s2s_out:process_closed:153 Failed to establish outbound s2s connection <CENSORED MY DOMAIN> -> <CENSORED GOOGLE APPS>: Stream closed by us: unsupported-version; bouncing for 128 seconds

**Comment by zinid** [comment]
I believe this is fixed in c3ef56702a30d7315437f80c58a13316292f4b5a

**Comment by zinid** [comment]
Or, another issue might be that you have either `s2s_use_starttls: required` or don't have `mod_s2s_dialback` loaded.
