### ISSUE TITLE
Server does not process stanza

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1619]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

During load testing what we did is 
1) set fsm to 10000 (64GB RAM 8Cores) 
2) In offline storage saved 3000 messages for one user
3) Client connects , authenticates -> server retrieves 3000 messages and starts sending it ..
however durting this time when server is processing it and trying to send it over stream any stanza that is sent by the client is stalled , client sent ping when server is processing this offline messages server does not respond.
Why is that during offline processing the incoming stanzas are blocked ?

**Comment by zinid** [comment]
Use profiler, we have no crystall balls.

**Comment by zinid** [comment]
Also, cannot reproduce, just checked it. The server doesn't feel anything, but a client (Psi) is pretty much dead.
