### ISSUE TITLE
Load balancing of ejabberd server

### ISSUE THREAD

**Issue by rahul-l** [processone/ejabberd#1622]
I am new to ejabberd server. I have install 2 instances of ejabberd on Ubunto -16.04
apt-get install ejabberd.

My Configuration with cluster is also successful by following https://docs.ejabberd.im/admin/guide/clustering/

Now I want to have load balancing between these two nodes like round-robin for my clients

I read in one post that ejabberd does not support load balancing but I found one document which specify something about default load balancing
https://docs.ejabberd.im/admin/guide/advanced/

but not clear what it is. Can you help me to specify how to perform load balancing in ejabberd

**Comment by zinid** [comment]
There are two common way to accomplish the task
1. Use SRV DNS balancing: it's pretty straightforward, just set up several SRV records pointing to your nodes.
2. Use balancing proxies, such as haproxy. [Here](http://blog.onefellow.com/post/76702632637/haproxy-and-ejabberd) is a good blogpost about it.

**Comment by rahul-l** [comment]
Thanks zinid for sharing the details. I will look into haproxy
