### ISSUE TITLE
module xml

### ISSUE THREAD

**Issue by imilanovic** [processone/ejabberd#1623]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?
Debian 8.7

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I have module that i compiled but I get error whet i use it {undef,[{xml,get_tag_attr_

**Comment by zinid** [comment]
There is no such module `xml`, there is `fxml`.
