### ISSUE TITLE
Redis Connection Pool Size

### ISSUE THREAD

**Issue by genexp** [processone/ejabberd#1624]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We're seeing a maximum of 7 connections to our Redis server, used for sessions, on our 3 node cluster.

From what I can tell, there's no way to configure the pool size.  Under heavy load, we believe Redis connections are getting backed up and the connection is timing out.  Is there a way to increase the size of the pool? 1 or 2 seems very small.

**Comment by zinid** [comment]
No, there is no way doing this.
There are several Redis pool libraries available for Erlang, but of unknown quality. So I'm not sure ejabberd should use them.

**Comment by genexp** [comment]
Hmm. But a single connection is pretty limiting right?

**Comment by zinid** [comment]
That's why I marked the issue as a feature request :)
But I don't know who will handle that.

**Comment by genexp** [comment]
Understood!  Thank you Evgeny!

On Tue, Mar 21, 2017 at 10:06 AM, Evgeny Khramtsov <notifications@github.com

**Comment by zinid** [comment]
Use `redis_pool_size` global option. The default value is `10`.

**Comment by genexp** [comment]
Hey @zinid Thanks very much!  Lovely change! 🍰 🎈 🎂 👏 🎆
