### ISSUE TITLE
communication between two different ejabberd domin users

### ISSUE THREAD

**Issue by rahul-l** [processone/ejabberd#1628]
Hi I have setup two instances of ejabberd on Ubunto by calling
apt-get install ejabberd

Both instances are running different domins like
1. one.example.com
2. two.expample.com

I have created few users like test1 and test2 in one.example.com and test3 and test4 in  two.expample.com

both ejabberd nodes are not in cluster 
however in setting file (ejabberd.yml) of server 2 (two.expample.com). i have specified value for 
ejabberd_service (like port, module, access, shaper_rule, ip as 127.0.0.1 hosts as "one.example.com" and password: "secret", privilege_access (roster: get and message to outgoing).

When I send a request to connect user from test3@two.example.com user to test1@one.example.com it is not successful.

Can you please help me in how to achieve cross domain communication

**Comment by rahul-l** [comment]
To simplify my question, is it possible two instances of ejabberd which are not under cluster can communicate with each other?

If yes what steps are needed to configure

**Comment by zinid** [comment]
Both domains should be DNS-resolvable

**Comment by rahul-l** [comment]
yes I have added DNS entries for both servers in /etc/hosts file

**Comment by zinid** [comment]
There is a log file, ya know.
Also, there is no need to add the domain to ejabberd_service.

**Comment by rahul-l** [comment]
Hi @zinid 
Thanks for your help after commiting ejabberd_service it worked
