### ISSUE TITLE
which ejabberd module has the messages sent by the xmpp client

### ISSUE THREAD

**Issue by blacklightknight** [processone/ejabberd#1629]
> What version of ejabberd are you using?
ejabberd 17.01

> What operating system (version) are you using?
Windows 10

> How did you install ejabberd (source, package, distribution)?
through ejabberd installer

I am using ejabberd as server application and Pidgin on the client side.When I start a new chat between two clients,I wanted to gather the messages sent between them on ejabberd side, but i actually can't figure out to which ejabberd module does these messages go to.
Does anybody has  some Ideas on this?

**Comment by weiss** [comment]
> When I start a new chat between two clients,I wanted to gather the messages sent between them on ejabberd side

You could use [`mod_mam`][1] for dumping messages into SQL.

> i actually can't figure out to which ejabberd module does these messages go to

They go through [a number of modules][2].  You could use the `user_send_packet` and/or `user_receive_packet` if you want to write your own module for logging them.

[1]: https://docs.ejabberd.im/admin/configuration/#modmam
[2]: https://docs.ejabberd.im/developer/extending-ejabberd/stanza-routing/
