### ISSUE TITLE
Is ejabberd supports Sharding ?

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1630]
I was testing load between multiple ejabberd nodes, is database sharding possible in ejabberd ?

**Comment by zinid** [comment]
In commercial version only

**Comment by Veerbhadra277** [comment]
I mean node based sharding, as each node contains its own Mnesia database with it, and for external db i am using MySQL, for external database we are managing sharding at MySQL, but still want node based sharding, irrespective of external DB sharding.

**Comment by zinid** [comment]
No, this is also not supported.
Wait a bit, there will be fully implemented RAM backends for SQL and Redis for any transient shared data (not only for sessions, like now): internal API is ready, the modules are only to be implemented. So you can get rid of Mnesia and use sharded in-memory data with whatever backend you choose.

**Comment by Veerbhadra277** [comment]
Sorry, I didn't get you exactly, 

do you mean we will get this functionality in new release in which we can get rid from internal Mnesia db (currently using  each node to store sessions, routing info etc) and we will get implemented RAM backends for SQL and Redis for any transient shared data.
Or Do we need to implement those components to get rid of Mnesia ?

Suppose there are 4 ejabberd nodes that are taking care of 4 millions of user and if we are splitting users  in between nodes 1 million users to each node, and all nodes are communicating through S2S communication (as all nodes are in subdomain), can we call this "Node based sharding"? and does it work (performance wise)?

**Comment by zinid** [comment]
> do you mean we will get this functionality in new release in which we can get rid from internal Mnesia db (currently using each node to store sessions, routing info etc) and we will get implemented RAM backends for SQL and Redis for any transient shared data.

Yes.

> Suppose there are 4 ejabberd nodes that are taking care of 4 millions of user and if we are splitting users in between nodes 1 million users to each node, and all nodes are communicating through S2S communication (as all nodes are in subdomain), can we call this "Node based sharding"? and does it work (performance wise)?

This will work, but there will no be "backup" for a particular subdomain. So if a node service the subdomain goes down, users from this domain suck.

**Comment by Veerbhadra277** [comment]
Thanks @zinid 

> Suppose there are 4 ejabberd nodes that are taking care of 4 millions of user and if we are splitting users in between nodes 1 million users to each node, and all nodes are communicating through S2S communication (as all nodes are in subdomain), can we call this "Node based sharding"? and does it work (performance wise)?

If we take care of backup n fail-over of each node, is this setup reliable / production worthy?

**Comment by zinid** [comment]
I cannot say, never tried something like this, sorry.

**Comment by Veerbhadra277** [comment]
Ok, No problem, Thanks a lot for your guidance, every time  it helps me lot !!
