### ISSUE TITLE
Ejabberd 17.01 and mod_offline_post plugin

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1634]
Hi
I was using ejabberd 16.09 with mod_offline_post plugin to send push notification to offline users ( https://github.com/diamondbybold/ejabberd_mod_offline_post) 

After ejabberd releases the 17.01 I've tried to upgrade our server to 17.01 version everything worked fine besides mod_offline_post. It stopped working so our users cannot send push notifications,  but doesnt give any error while launching ejabberd.
I dont know erlang so I didnt understand what may be the problem

Is there anyone who can point me to the right direction for finding a solution to this problem. Or should I have to rollback to 16.09 version?

Thanks

**Comment by nixxcode** [comment]
The developers have changed the arguments passed to `offline_message_hook` and failed to mention this compatibility breaking change in any release notes 😒

I suggest rolling back to 16.09 until `mod_offline_post` has been fixed to work with the latest version.

See issue #1527 for more information

**Comment by PH-F** [comment]
I wrote an offlne post plugin for ejabberd17.01 based upon information i got from processone.
https://github.com/PH-F/mod_offline_http_post

**Comment by closedDoor** [comment]
I modified the original offline post module to work with Ejabberd 17.04.
[https://gist.github.com/closedDoor/bd7f10b7e426142f0e117015cf754a7b](mod_offline_post)

`-module(mod_offline_post).`
`-author('test@test.org').`
`
-behaviour(gen_mod).`
```

-export([start/2,
	 init/2,
	 stop/1,
	 send_notice/1]).

-define(PROCNAME, ?MODULE).
```
```

-include("ejabberd.hrl").
-include("xmpp.hrl").
-include("logger.hrl").

start(Host, Opts) ->
    ?INFO_MSG("Starting mod_offline_post", [] ),
    register(?PROCNAME,spawn(?MODULE, init, [Host, Opts])),  
    ok.

init(Host, _Opts) ->
    inets:start(),
    ssl:start(),
    ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 100),
    ok.

stop(Host) ->
    ?INFO_MSG("Stopping mod_offline_post", [] ),
    ejabberd_hooks:delete(offline_message_hook, Host,
			  ?MODULE, send_notice, 10),
    ok.
```
```

send_notice({Action,Packet}) ->	
		
	From = element(5,Packet),
	To = element(6,Packet),
	
	From1 = From#jid.luser,
	To1 = To#jid.luser,
		
	Body = binary_to_list(element(3,lists:nth(1,element(8,Packet)))),
		
    PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url,fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	Token = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, auth_token, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	
	Data = string:join(["to=", binary_to_list(To1), "&from=", binary_to_list(From1), "&body=", Body], ""),
	Request = {binary_to_list(PostUrl), [{"Authorization", binary_to_list(Token)}], "application/x-www-form-urlencoded", Data},
	httpc:request(post, Request,[],[]),
			
	ok.
```
