### ISSUE TITLE
Connection attempt from disallowed node '176f3765-ctl-ejabberd@node1'

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1635]
> What version of ejabberd are you using?
https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.03-beta/ejabberd-17.03.beta-0.x86_64.rpm

> What operating system (version) are you using?
CentOs7.2

> How did you install ejabberd (source, package, distribution)?
package (rpm file)

> What did not work as expected? Are there error messages in the log? What
ejabberd not running

> was the unexpected behavior? What was the expected result?
ejabberd should run on respective node

I have done following steps
1. Installed ejabberd package on CentOs 7.2
2. Modified .erlang.cookie (took backup)
3. run ejabberdctl start
4. got error  2017-03-24 15:39:01.162 [error] <0.685.0> ** Connection attempt from disallowed node '176f3765-ctl-ejabberd@Node1'

i am seeing same error even after re-installing ejabberd. I have not ran any command related clustering

can anyone please help me

Regards,
Veer

**Comment by zinid** [comment]
This means cookie mismatch, please double check this.

**Comment by Veerbhadra277** [comment]
I have joined node yet, then how it would be mismatch?

**Comment by zinid** [comment]
The cookie of ejabberd user doesn't match the cookie of ejabberctl user.

**Comment by Veerbhadra277** [comment]
Thanks @zinid
