### ISSUE TITLE
mod_mam db type for large user base and archive

### ISSUE THREAD

**Issue by karoldanutama** [processone/ejabberd#1639]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu 14.04 64-bit

> How did you install ejabberd (source, package, distribution)?

Distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Just a simple questions regarding `mod_mam`.

1. Let's say I would like to support message archiving for 5 million users and 200 million message archives. What is the best `mod_mam` db type to use?
2. I have been looking for Riak support by `mod_mam` and I can not find any. Why is it no supported yet or is there any plan to support it in the future?

**Comment by zinid** [comment]
1. Currently there is no much choice: definitely not Mnesia because of 2Gb limit, so only SQL left
2. Riak is not supported because we have no enough time to work on it.
