### ISSUE TITLE
MUC: Manage MUC on nodes in cluster

### ISSUE THREAD

**Issue by Kaggggggga** [processone/ejabberd#1640]
> What version of ejabberd are you using?
16.09

> What operating system (version) are you using?
4.4.16-27.56.amzn1.x86_64

> How did you install ejabberd (source, package, distribution)?
source

We have a cluster around 10 servers, one ejabberd node per server,  and around 5000 persistent MUCs are hosting. And groupchat is our main service.
Recently we are in the situation that occasionally ejabberd will be killed by kernel because too much memory are allocated to it according to system message log file. 
Also, I read the memory usage statistics on server, and found the usage level vary on each node, some are mostly over 80%, some are around 60%.

We suspect the MUC distribution on nodes could be the problem, since MUC is stored in ram, and the activeness are different in MUCs, so
1. We wish to know which node is hosting a MUC or the way to specify node to host newly created MUC. I cannot find it on the API document. (I guess 'host' parameter in create_room is to specify the xmpp host, not the ejabberd node?)

2. Is is correct that, if I execute create_room command on node1, the new MUC will be on node1?

3. Are the any other possible cause to this situation?

4. Moreover, after 4 months of hosting, we have once suffered a period of message loss in our service, (e.g. the groupchat message stanza (from user to MUC) is sent, but we didn't get the message back(from MUC to user)),  and finally, we had to restart the whole cluster as a temporary fix. So I wonder if there are any suggestions to situation like this?

Looking forward to the reply, and thanks a lot!

**Comment by zinid** [comment]
The problem you're describing is quite complex and requires some investigation. I don't think we can provide comprehensive help on the issue as it will require some time and effort from our side.
I also don't think open source version of ejabberd is able to handle your deployment: the clustering implementation is pretty naive and is not scaled well above 2-3 nodes. Hence, you have the problems.

**Comment by Kaggggggga** [comment]
Thanks for the reply.

So the node number matters, we will try to reduce the node number and see if it works.

About the MUC distribution management, is there anything we can do to know which node an MUC is on or to specify the node to host an MUC?

Thanks!

**Comment by zinid** [comment]
Well, an Erlang process serving a MUC room is created on the node where "creation request" is received (that is, either `<presence/>` stanza or an admin action). However, you can load `mod_muc` on some nodes only, in that case creation requests (and all further requests) will be routed to those nodes base on `domain_balancing` option.

**Comment by zinid** [comment]
Here is the description of the option: https://docs.ejabberd.im/admin/guide/advanced/

**Comment by Kaggggggga** [comment]
Thanks for the explanation. We will try to balance the room loading with admin action and see if it helps!

Thanks again!
