### ISSUE TITLE
Ejabberd 16.09 Mod Rest Installation

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1641]
Hi 
I'm using ejabberd 16.09 and I've tried to make a fresh install today.(download the deb package from ejabberd.im website)
Then I 've executed the following commands to install mod_rest

```
ejabberdctl modules_update_specs
ejabberdctl module_install mod_rest
```

However it gave an error like this:

`src/mod_rest.erl:40: can't find include file "xmpp.hrl"`

I wasnt getting this error before, I dont know what has changed?

**Comment by ttwwaaoo** [comment]
@tolgatanriverdi did you resolve this problem? I have the same problem
