### ISSUE TITLE
Corrupted libtinfo.so file

### ISSUE THREAD

**Issue by NileshPS** [processone/ejabberd#1647]
> What version of ejabberd are you using?

17.03

> What operating system (version) are you using?

Linux Mint 18

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
sudo ./ejabberdctl start
bash: /opt/ejabberd-17.03/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)

sudo ./ejabberdctl register admin localhost admin123
bash: /opt/ejabberd-17.03/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
Error: cannot_register
```

**Comment by NileshPS** [comment]
Solved that by adding a symlink to the actual libtinfo.so file. 
New Problem : Can't register a new user ... I get the error 
> Error: cannot_register

**Comment by badlop** [comment]
```
$ ejabberdctl register adasd localhost666 asd
Error: cannot_register

$ ejabberdctl register adasd localhost asd
User adasd@localhost successfully registered

$ ejabberdctl register adasd localhost asd
Error: conflict
```

**Comment by cromain** [comment]
1/ libtinfo is from debian old-stable, for backward compatibility and also to provide it for linux distributions which does not have it (ArchLinux for example). It will be upgraded soon tu current debian stable version. We won't cover compatibility with all possible linux distributions as we do not statically link beam. In your case, symlink to your libtinfo is the solution.

2/ we do not reproduce. also please don't mix unrelated topics into the same issue.
