### ISSUE TITLE
Support of MSSQL instead of MySQL

### ISSUE THREAD

**Issue by rahul-l** [processone/ejabberd#1648]
does ejabberd supports mssql as backend database instead of mysql. 
If yes what configuration do we need to do in ejabberd.yml file. Also where I will get a schema setup file for mssql.

I am using community version source code for ejabberd setup.

**Comment by mremond** [comment]
Yes, there is a mssql backend configuration. It is documented here: https://docs.ejabberd.im/admin/configuration/#database-and-ldap-configuration

**Comment by rahul-l** [comment]
Hi @mremond 

Thanks for confirmation. I will test that.
