### ISSUE TITLE
Multiple errors while executing mssql script.

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1649]
I am trying to deploy mssql tables for ejabberd but scripts throwing error

`Incorrect syntax near '('.`

I corrected above error by removing semicolon at line 149, now its throwing another error 

`Cannot use TEXTIMAGE_ON when a table has no text, ntext, image, varchar(max), nvarchar(max), non-FILESTREAM varbinary(max), xml or large CLR type columns. Line 532`

I am using MSSQL server 2014, don't want to mess original mssql script so avoiding my fixes.

Can anyone guied me how to resolve this.

**Comment by zinid** [comment]
We do not have available MSSQL server at the moment, so PRs are highly welcome.
