### ISSUE TITLE
[warning] got unexpected cast: {close,true}

### ISSUE THREAD

**Issue by coolfeature** [processone/ejabberd#1652]
> What version of ejabberd are you using?

 ejabberd-17.03.beta

> What operating system (version) are you using?

linux

> How did you install ejabberd (source, package, distribution)?

rpm package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I enabled mod_ping and I started seeing messages like the one below:

[warning] <0.502.0>@ejabberd_c2s:handle_unexpected_cast:251 got unexpected cast: {close,true}

**Comment by zinid** [comment]
Confirmed

**Comment by coolfeature** [comment]
Thanks! Can you advise if mod_ping is expecing an IQ back? The docs do not explicitly say...

I am asking because when I send IQ back
 ```
 var iq = $iq({type: 'result', to: from,	id: id});
  this.connection.sendIQ(iq);
```

I get this:

`[warning]` <0.458.0>@mod_ping:handle_cast:156 unexpected cast: {iq_pong,{`

**Comment by zinid** [comment]
Ah, that's another bug introduced recently, I'll fix it in a moment.

**Comment by zinid** [comment]
Fixed in f5b0cd1793887541a8974bea63d13f2f1c78bdd8
Thanks for the bug report.

**Comment by coolfeature** [comment]
Thank you! So I assume if I send a result iq back, it will cancel some timer in mod_ping and the
```
    ping_ack_timeout: 20
    timeout_action: kill
```
options will not fire therefore keeping the connection alive?

**Comment by zinid** [comment]
Yes

**Comment by coolfeature** [comment]
Cool, thank you!
