### ISSUE TITLE
Instructions for container image

### ISSUE THREAD

**Issue by urzds** [processone/ejabberd#1655]
I am trying to figure out how to run ejabberd as a container, but there seem to be two competing setups, both provided by @processone:
* In this GitHub repository, `processone/ejabberd`
  - Contains detailed instructions in the `/docker` directory of this repository
  - From the docs it appears to be a charm to setup, with a lot of automation
  - The container image is rooted at `docker.io/rroemhild/ejabberd`on Docker Hub, not `docker.io/processone/...` or `docker.io/ejabberd/...` -- thus it appears to not be official and controlled by @processone, despite the documentation being available in the official ejabberd repository...?!
  - The version provided by @rroemhild is 17.01, which is outdated since a while
* In the `processone/docker-ejabberd` GitHub repository
  - Comes with almost no instructions
  - Configuration appears to be very cumbersome, me having to replace the entire configuration file
  - This is what `docker.io/ejabberd/ecs`, the official image on Docker Hub, appears to be created from (but the container image repository on Docker Hub provides no link to it's source repository, i.e. this one)

It would be great if @processone could move forward with one image and drop the other. I would very much prefer if it would be the easy-to-use version @rroemhild built.

**Comment by cromain** [comment]
the /docker directory inside ejabberd sources is a port of contributed container by @rroemhild. we agreed with Raphael this could be included in ejabberd. While we maintain the necessary files to build your container from this, we do not push anything to the hub for this container.

containers from docker-ejabberd are a new approach we provide on our official docker hub, which targets developers for now. it allows to build ejabberd without local dependencies, and will be improved to get a simple and configurable runnable environment.

**Comment by cromain** [comment]
Added some details in the readme. Will fix and improve ecs images on the hub also.
