### ISSUE TITLE
Linear slowdown in mod_shared_roster with a lot of groups (sql backend)

### ISSUE THREAD

**Issue by gardenia** [processone/ejabberd#1656]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

Debian Jessie (64 bit)

> How did you install ejabberd (source, package, distribution)?

Linux x86 64-bits Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when getting the roster a helper function called get_user_displayed_groups() is called which in turn calls get_special_users_groups(Host) which loops over all the hosts groups and asks each one of it is "special" by checking if it has either the "all_users" or "online_users" option set.

```
get_special_users_groups(Host) ->
    lists:filter(fun (Group) ->
             get_group_opt(Host, Group, all_users, false) orelse
               get_group_opt(Host, Group, online_users, false)
         end,
         list_groups(Host)).
```

I am finding that with the SQL backend this results in a linear slowdown with a lot of groups.  i.e. in my case the host has about 2K groups.  list_groups() pulls back all the group names and then loops over each group individiually doing a get_group_opt() query for each group (in fact twice per group). with thie SQL backend this results in N * 2 queries where N is the number of groups when loading each roster.

Does that seem reasonable so far?

I am happy to try to provide some patch/workaround but thought it best to discuss the best course of action here first.

a few unstructured thoughts I had:

* in get_special_users_groups() rather than using list_groups(Host) we could use  groups_with_opts(Host) which pulls back both the groups and the opts in one shot which seems like it should reduce most of the pain.  is there any downsides I'm missing here?

* ideally it would be good if you could do something like filter_groups_with_opts(Host, Opt) which could then be translated into a clause in the query to pull back only the matching groups from the DB and dispense with the need to loop over all groups to filter out the "special" ones (and which could be optimized appropriately on each backend).

* in my case I don't have any special groups - it might be nice to have a "I don't have any special groups" type configuration or perhaps more generally "here are my special group names hard-coded in config, which may also be empty".

Any thoughts appreciated.

**Comment by gardenia** [comment]
PS, further to my first bullet point, I am thinking something like this:
```
get_special_users_groups(Host) ->
    lists:filtermap(fun ({Group, Opts}) ->
             case proplists:get_value(all_users, Opts, false) orelse
                  proplists:get_value(online_users, Opts, false) of
               true -> {true, Group};
               false -> false
             end
         end,
         groups_with_opts(Host)).
```

untested.  I need to do some testing on this and will report back.

**Comment by zinid** [comment]
The bug exists since stone age I think.

**Comment by cromain** [comment]
any PR is welcome for this
