### ISSUE TITLE
Problem receiving the archive.

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1658]
> What version of ejabberd are you using?
17.01

> When trying to get the archive and sending the after paramater an error occurs "feature-not-implemented"  I can only retreive the full archive but this is too big, i just want a part of it if possible.  Also the paramater max does not do anything.  Am i doing something wrong? Or is it not possible to get messages after a certain message / of certain timestamp?

```xml
<iq xmlns="jabber:client" to="...." from="..." type="error" id="....">
<query xmlns="urn:xmpp:mam:1" queryid="....">
<set xmlns="http://jabber.org/protocol/rsm">
<index>0</index>
<max>100</max>
<before></before>
<after>sTdPm-1197</after>
</set>
<x xmlns="jabber:x:data" type="submit">
<field var="FORM_TYPE" type="hidden">
<value>urn:xmpp:mam:1</value>
</field>
</x>
</query>
<error code="501" type="cancel">
<feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">
</feature-not-implemented>
</error>
</iq>
```

Thanks in advance

**Comment by zinid** [comment]
Just remove `<index/>` element

**Comment by zinid** [comment]
Improved in ad948d33c0827e1c86b1e81ee313b655c2c0439d

**Comment by PH-F** [comment]
The error is gone, but the response is empty. Is there something else wrong in the request?
