### ISSUE TITLE
[warning] got unexpected info: {item,{<<"someuser">>,<<"server.com">>,<<>>},both}

### ISSUE THREAD

**Issue by coolfeature** [processone/ejabberd#1659]
Opening again cause my last issue was closed without resolution.

> What version of ejabberd are you using?
master

> What operating system (version) are you using?
linux

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

[warning] <0.508.0>@ejabberd_c2s:process_info:247 got unexpected info: {item,{<<"someuser">>,<<"server.com">>,<<>>},both}

Looks like shared roster items issue.

**Comment by cromain** [comment]
#1651 reopened.
closing #1659 duplicate
