### ISSUE TITLE
Oauth Not Working On 17.03

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1661]
> What version of ejabberd are you using?
17.03

> What operating system (version) are you using?
Ubuntu 16.04.1

> How did you install ejabberd (source, package, distribution)?
Linux Installer

> The listening port config
```
======================
**port: 5281
ip: "0.0.0.0"
module: ejabberd_http
request_handlers:
   "/api": mod_http_api
   "/oauth": ejabberd_oauth
   oauth_db_type: sql
   commands_admin_access: configure
   commands:
      - add_commands: [status, register]
   oauth_expire: 3600
   oauth_access: all**

> The ACL config
==============
**acl:
   admin:
      user:
         - "admin@example.com"
   access:
      configure:
         admin: allow**

> The API Permission config
========================
**api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - ip: "0.0.0.0"
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - ip: "0.0.0.0"
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
      ## - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
      - "connected_users"
      - "get_cookie"
      - "modules_available"
      - "modules_installed"**
```

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

If without OAUTH, i try using wget http://example.com:5281/api/status, it will return me the server status without problem.  However if I use wget http://example.com:5281/api/register, the log files returns as @mod_http_api:log:543 API call register [ ] ({172.119.111.155}) and the error appear as **{"status":"error","code":32,"message":"AccessRules: Account does not have the right to perform the operation."}**

I wish to know why for other api command is working but not for "register"?  Plus I have read through all your ejabberd docs and follow the method, it still don't work for me.  I have also read through other users comments on stackoverflow but problem still remains.

If i call to the endpoint http://example.com:5281/oauth/authorization_token, it did appear to me the oauth screen but when i key in admin or admin@example.com and with the password i use as admin, it does not work.  The error returns as "access denied".

I wish to know what is jid require on oauth token and what are we suppose to do to get the oauth token?

**Comment by prefiks** [comment]
Status is allowed by "public commands" section, it allows everyone call one of command that is in what section (you have status here). Register is not listed here, so that rule won't accept it.

Rule "console command" will allow only accept commands from ejabberdctl (as specified by from: section), and to use "admin access" rules (which will allow executing register) you need to authenticate as someone who belong to acl: admin (and also request must come from ip 0.0.0.0, which is most certainly wrong, if you don't want to limit on ip just remove that line with it).

If you want to allow more commands without authentication add them to what: of "public commands" or start using authentication to be allowed by "admin access"

**Comment by molochmike** [comment]
Hi @prefiks 

I have followed all the 3 paragraphs you mentioned and now all the ejabberdctl commands works when i do curl with POST and also GET.

However, when i try it on my browser for "http://example.com:5281/oauth/authorization_token" or even tried those from stackoverflow mentioned by other members, I still get access denied like this below on the bar.

"http://example.com:5281/oauth/authorization_token?error=access_denied&state="

<img width="653" alt="oauth-error" src="https://cloud.githubusercontent.com/assets/15246261/24782412/a449bd46-1b78-11e7-8a35-3aaf740c91e5.png">


I want to know the use of this token and how to make it work based on the settings that i have change now on the API PERMISSION layer.

Here is my the current settings for the Api Permission".

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            ## - ip: "0.0.0.0"
            - acl: admin@example.com
      - oauth:
	- scope: "ejabberd:admin"
        - access:
          - allow:
              ## - ip: "0.0.0.0"
              - acl: admin@example.com
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
      ## - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"

**Comment by molochmike** [comment]
Hi @prefiks 

I just checked and realized that the ejabberd mysql schema that i have now with my localhost DB does not contain the other 9 tables supposely in the schema.  Total DB schema supposely is 36 tables but I only have 27 tables.  Reason being I am using old mysql version 5.5.54 and the engine for the DB is MyISAM.  Ejabberd mysql schema supposely default as INNODB.

I just get to know when I look at the mysql table schema and thought something is not right and so the 9 tables that was not in the ejabberd schema are as follows:-

1) irc_custom
2) motd
3) caps_features
4) sm
5) oauth_token
6) route
7) bosh
8) carboncopy
9) proxy65

I am not sure whether is it because "oauth_token" table was missing here and my authentication is based on SQL, so the oauth_token not working and return me access denied?  Perhaps yes and no.  Anyway will be upgrading the mysql to 5.6 later, dump the mysql ejabberd DB and upgrade the mysql to 5.6.  Then once done, will re-import into the new ejabberd schema and use innodb default engine and will see how it goes later.

I will update in here again.  Thanks.

**Comment by badlop** [comment]
The oauth_token table was added to MySQL schema in ejabberd 16.08. It seems you updated ejabberd code from older versions, but you didn't create that table (probably because you didn't need it last year)

See https://docs.ejabberd.im/admin/upgrade/from_16.06_to_16.08/

**Comment by molochmike** [comment]
Hi @badlop 

Reason being is because I use mysql version 5.5.54 so oauth_token table was not in the mysql ejabberd database because due to limitation support under myisam engine which supposely i have to use innodb engine for ejabberd database.

Now that i have successfully upgrade mysql to version 5.6.35 and i have drop the previous ejabberd database after backup, so now i put back the mysql schema into the new database and all the table that was missing above has work with successful.  So now i have total of 36 tables complete in the ejabberd database.

The one that you mention for the oauth_token schema is in the current table same as your link.

But problem is now i try to generate the oauth token, it still show me access denied. My configuration on the server-side did not change and still the same.  Can you help me on this?   Thanks.

**Comment by molochmike** [comment]
Hi @prefiks & @badlop 

Good day to you guys.

Any help regarding the question above on oauth token?  A million thanks.

**Comment by prefiks** [comment]
I am guessing you don't have acl rule named "admin@example.com", if you want to use jid use user: "admin@example.com" instead of acl: "admin@example.com". Also did you create you oauth token for that user? You also need to create that token with scope "ejabberd:admin" to make "admin access" rule be able to accept it.

**Comment by molochmike** [comment]
Hi @prefiks 

Good day to you.

I will try out the suggestion you provide.  However, I am still confuse how to go about creating a token with the scope "ejabberd:admin" and make admin able to access it.

**Comment by molochmike** [comment]
Hi @prefiks 

I have tried and modify some of the settings in the ACL and access rules but still I get "access denied" when i try to create token for admin user in the console command using command "ejabberdctl oauth_issue_token".  Below is my current ejabberd.yml configuration.

Host Section
================
hosts:
- "jabberchat.example.com"

Listen Port Section
===================
listen:
-
port: 5281
module: ejabberd_http
request_handlers:
"/api": mod_http_api
"/oauth": ejabberd_oauth

Global Section
=================
default_db: sql

Access Control List Section
==========================
acl:
admin:
user:
- "admin@jabberchat.example.com"
access:
configure:
admin: allow
commands_admin_access:
- allow:
- user: "admin@jabberchat.example.com"
commands:
- add_commands: [user, admin, open]
oauth_expire: 31536000
oauth_access: all

Access Rules Section
====================
oauth:
- scope: "ejabberd:admin"
- allow: admin

API Permission Section
======================

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            ## - ip: "0.0.0.0"
            - acl: admin@dev.bondwith.me
      - oauth:
        - scope: "ejabberd:admin"
      - access:
          - allow:
              ## - ip: "0.0.0.0"
            - acl: admin@dev.bondwith.me
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
      ## - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"
      - "!register"
      - "!unregister"

There is a link on github by processone on ejabberd-api, where i follow to the methods of doing the oauth but still don't work for me.  The link as below.

https://github.com/processone/ejabberd-api

Please let me know what am i missing.  Thanks.

**Comment by molochmike** [comment]
Hi @prefiks & @badlop 

Any help guys?  Saw ejabberd release new version 17.04, will it fix this issue i am currently facing?  Thanks.

**Comment by prefiks** [comment]
You still are using
```
  "admin access":
    who:
      - access:
          - allow:
            ## - ip: "0.0.0.0"
            - acl: admin@jabberchat.example.com
      - oauth:
        - scope: "ejabberd:admin"
      - access:
          - allow:
              ## - ip: "0.0.0.0"
            - acl: admin@jabberchat.example.com
```
but you don't have acl with name admin@...
try this:
```
  "admin access":
    who:
      - access:
          - allow:
            - user: admin@jabberchat.example.com
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - user: admin@jabberchat.example.com

**Comment by molochmike** [comment]
Hi @prefiks 

I have tried your suggestion above.  I have added the quote " " for "admin@jabberchat.example.com" otherwise log file shows error.  I try to use command "ejabberdctl oauth_issue_token admin@jabberchat.example.com 31536000 ejabberd:admin, it says "Error : access_denied".

I try again "ejabberdctl oauth_issue_token "admin@jabberchat.example.com" 31536000 "ejabberd:admin" and the result is same "Error: access_denied".

**Comment by prefiks** [comment]
You must have  oauth_access specified in your config (for example oauth_access: all to allow everyone create token). This is top level option, it shouldn't have any indentation before it.

**Comment by molochmike** [comment]
Hi @prefiks 

I do not get what you mean.  If you see my config as stated earlier I have done everything but yet I am not able to generate token.

When i issue command for example "ejabberdctl oauth_issue_token admin@jabberchat.example.com 31536000 ejabberd:admin, i still get "Error: access_denied".  This command is from the ejabberd console commands I execute from the server localhost itself.

If you see my config above I have actually set "oauth_expire: 31536000" and "oauth_access: all" under the ACL section, but I still can't generate token.  Even if i set this parameters under Listening port section is also same token can't be generated.  What is the wrong thing here?

**Comment by molochmike** [comment]
Hi @prefiks @badlop 

Any help on the above?   I'm still not able to get it work.  Still on Error: Access Denied.

**Comment by molochmike** [comment]
Hi @prefiks @badlop,

Any help?  Still not able to get it work.  Still on same error i get.

**Comment by prefiks** [comment]
That error that you are getting is almost certainly from missing  `oauth_access: all` in your config, make sure it is at start of line, and there is no spaces before it.

**Comment by molochmike** [comment]
Hi @prefiks 

I don't quite get your meaning about "start of line"?  Which section you refer to?  This oauth_access: all refer to which section that needs to be change?

**Comment by molochmike** [comment]
Hi @prefiks @badlop 

Below is my current ejabberd.yml config for "listen section", "acl section" and "api section".  I still get "Error: Access_denied" when i create token.  I follow some stackoverflow user setup but still get same error.  Which section below I have done wrong?  Can you point out to me specifically?

<img width="397" alt="listen section" src="https://cloud.githubusercontent.com/assets/15246261/25161183/1e0d9de6-24ed-11e7-93ff-59cd3a8949d4.png">

<img width="585" alt="acl section" src="https://cloud.githubusercontent.com/assets/15246261/25161195/288b1938-24ed-11e7-92e5-588ba5a4b709.png">

<img width="501" alt="api section" src="https://cloud.githubusercontent.com/assets/15246261/25161201/2fa0f918-24ed-11e7-947b-581ba55a1d72.png">

**Comment by prefiks** [comment]
This is top level option (like for example api_permission), it shouldn't be in any section, it should start at begin of a line

**Comment by molochmike** [comment]
Hi @prefiks 

What do you mean by 'top level option'?  Are you trying to say this whole api_permission section is to move to the first line on most top of the "ejabberd.yml" file??

**Comment by prefiks** [comment]
```
api_permission:
  "abc":
    ....
```

You see api_permission is top level here, as is not inside any other section, it start at begin of a line, "abc" is not top level, it's inside api_permission.

You are supposed to make oauth_access top level as well, so you should have
```
oauth_access: all

api_permission:
  "abc":
  ...
```

This is last time i am explaining that, i don't know how explain that better.

**Comment by molochmike** [comment]
Hi @prefiks 

Thanks for your time, anyway I guess i'll just do my best to test it out.  If there's anymore not able to get the oauth to work i will just ignore it and continue to use without the oauth token.

Perhaps google more around to see if anyone is able to get the oauth working with specs given.

**Comment by prefiks** [comment]
Here you have config snippet that allowed me to create token with oauth_issue_token and later use that token to execute commands:
```
acl:
  admin:
    user:
      - "admin@jabberchat.example.com"

oauth_access: all

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
```
Maybe this will help you

**Comment by molochmike** [comment]
Hi @prefiks,

I try the thing you told me yesterday and now i can generate tokens!   Thank you very much and it works now.

When i issue command "ejabberdctl oauth_issue_token" i got the message out from console command and when i use command "oauth_list_tokens" it show to me as well.   So i try to use it for call to applications and command all works well!

Thank you once again and thank you for the snippet you just provided!   You guys are great!

**Comment by ozwild** [comment]
What helped get going was to remove the "- acl: loopback" lines that were before  "- acl: admin"
