### ISSUE TITLE
Can't install any module after upgrade to 17.03

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#1665]
> What version of ejabberd are you using?

17.03

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After upgrade to 17.03, mod_rest which was configured in the ejabberd.yml didn't work. I tried to reinstall the module but I get the following error.

```
#ejabberdctl module_install mod_rest

Problem 'error function_clause' occurred executing the command.
Stacktrace: [{filename,join,
                       [{error,bad_name},"include"],
                       [{file,"filename.erl"},{line,406}]},
             {ext_mod,'-compile_options/0-lc$^0/1-0-',1,
                      [{file,"src/ext_mod.erl"},{line,544}]},
             {ext_mod,compile_options,0,[{file,"src/ext_mod.erl"},{line,544}]},
             {ext_mod,compile,1,[{file,"src/ext_mod.erl"},{line,524}]},
             {ext_mod,compile_and_install,2,
                      [{file,"src/ext_mod.erl"},{line,495}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,195}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,353}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,322}]}]
```

**Comment by cromain** [comment]
error comes when ejabberd is not installed, and run from development directory, or when a deps dir can not be found. fixed in 17.04.
