### ISSUE TITLE
Email Length

### ISSUE THREAD

**Issue by whoarethebritons** [processone/ejabberd#1670]
> What version of ejabberd are you using?

2.1.11-1ubuntu2.1

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

On an Azure Ubuntu VM, the output of root@$EHOSTNAME.$EDOMAINNAME was 68 characters and the cert was not generated. Output of running openssl by hand was `string is too long, it needs to be less than  64 bytes long`. This is in the ejabberd.postinst

**Comment by cromain** [comment]
This is not a problem with ejabberd, but with ubuntu's package.
Please report this to ubuntu packager.
