### ISSUE TITLE
Module Push (mod_push) Recommendation

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1671]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

Just wish to ask that I would like to implement mod_push for push notification on the current version of ejabberd 17.04, is there any recommendation from your side?  Thanks.

**Comment by weiss** [comment]
> Just wish to ask that I would like to implement mod_push for push notification on the current version of ejabberd 17.04, is there any recommendation from your side?

To my knowledge, there's no XEP-0357 module for ejabberd 17.04 available yet.  You might want to subscribe issue #1379.
