### ISSUE TITLE
Different behaviours of android smack and ios xmppframework on ejabberd

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1673]
Hi
We are using ejabberd as our chat application's xmpp server. (ejabberd 16.09)
We are connecting to ejabberd with using
IOS: XMPPFramework (Robbie Hanson)
Android: Smack API

We've set the ejabberd mod_ping timeout to 20 seconds(10 seconds ping interval, 10 seconds timeout)

In IOS XMPPFramework,  when the internet connection lost(changing device to airplane mode), ejabberd pings the device and when it cannot receive any response from the device (within 20 seconds) it automaticly disconnects the user . (Which is what we exactly wanted)

However in Android Smack API , when the internet connection lost(changing device to airplane mode), the user seems online to all other users for  **5 minutes 20 seconds**  so during that time all messages that this user received will be lost.(Because actually the user is not online).

We dont know what is the difference between connecting with IOS XmppFramework and Android SmackApi. Do you know are there any parameters to bypass ejabberds mod_ping checks.
If there are those kind of parameters, can you tell me what are they and how can we change it

Thanks

**Comment by badlop** [comment]
You can try a network sniffer to see the difference at network level between both libraries. There's Wereshark, or Ethereal, or I use "sudo tcpflow -i lo -Cg port 5222".

**Comment by Jethvasagar** [comment]
@tolgatanriverdi @badlop I have fetching same issue in smack library as you explain above. how can do archive this  XMPPFramework functionality on smack api ?

**Comment by xiifwat** [comment]
Hi. I'm using Smack version 4.3.1 and facing the same issue for Android. Is there any solution?

**Comment by mremond** [comment]
The ticket is about difference of behaviour with ping, so you should ensure that Smack library supports anwering to ping packets and that it is enabled.
