### ISSUE TITLE
Unable to install mod_restful plugin in latest release

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [processone/ejabberd#1674]
> What version of ejabberd are you using?
16.01, 17.03 & 17.04

> What operating system (version) are you using?

Ubuntu 16.04 LTS

> How did you install ejabberd (source, package, distribution)?

From official DEB package and installed 16.01 from Ubuntu 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am not able to install mod_restful plugin on 17.03 and 17.04. It was working fine on 16.01
I am getting following error message::

```
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:48: can't find include file "include/mod_restful.hrl"
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:63: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:64: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:65: variable 'Options' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:70: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:73: variable 'HTTPRequest' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:73: record request undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:79: variable 'ReqHost' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:101: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:102: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:108: variable 'Q' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:109: variable 'GlobalOpts' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:109: variable 'Opts' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:110: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:115: variable 'Format' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:120: variable 'GlobalOpts' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:120: variable 'Opts' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:123: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:129: variable 'Struct' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:141: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:144: variable 'Q' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:158: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:159: variable 'Data' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/gen_restful_api.erl:189: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful.erl:30: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful.erl:30: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:67: can't find include file "include/mod_restful.hrl"
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:69: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:70: variable 'Path' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:104: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:105: variable 'Data' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:127: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:128: variable 'Options' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:175: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:176: record rest_resp undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:177: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:63: Warning: behaviour gen_restful_api undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:175: Warning: variable 'Res' is unused
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:175: Warning: variable 'ResF' is unused
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_admin.erl:181: Warning: function format_result_json/2 is unused
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl:36: can't find include file "include/mod_restful.hrl"
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl:46: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl:47: variable 'Path' is unbound
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl:59: record rest_req undefined
/opt/ejabberd-17.03/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl:60: variable 'Path' is unbound
```

When i look into the folder the file is actually there and it has permissions for ejabberd user and group. The reason for upgrade from 16.01 to 17.04 was that the mod_auth_http module was not working but now mod_restful plugin is not installing

Moreover i am not now able to start stop service using services in ubuntu and ejabberdctl is not accessible as well. I ahve to manually use **ejabberdctl.sh** file inside **/opt/ejabberd-17.03** to start stop ejabberd and install modules. Is there a better way of doing this like before

**Comment by molochmike** [comment]
Hi,

Latest 17.04 already have module http api working (mod_http_api).  In fact since 17.03.  You can use this.  you need to enable it on the config file.

The mod_restful is no longer work as it has some compilation broken issue.  I have try this since 17.03 beta.  I even went to contact the person jonas author for the module, he is no longer able to provide help as he does not get involves in ejabberd stuff anymore.

When you setup 17.04, your config file "ejabberd.yml" should have a section where it states as "API permission" area.   Use that to work out the api.  Good luck.

**Comment by Hassnain-Raza-Alvi** [comment]
I am working on this and it was enabled by default on 17.04. But there is a strange issue i want to enable API level access to all commands via particular IP. Here is my configuration 

```
listen:
  -
    port: 9090
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
```

Here is my API permissions section in ejabberd.yml
```
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - ip: "127.0.0.1/8"
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - ip: "127.0.0.1/8"
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "Expose all commands for localhost":
    - who:
      - ip: "127.0.0.1/8"
      - ip: "127.0.0.1"
      - ip: "localhost"
    - what:
      - "*"
      - "!stop"
      - "!start"
```

but when i do a POST request to URL >>> http://localhost:9090/api/connected_users
I get following response:
```
{
"status": "error",
"code": 32,
"message": "AccessRules: Account does not have the right to perform the operation."
}
```

Can you tell me what i am doing wrong here?

**Comment by molochmike** [comment]
your listen port under 9090, the ip: "::" is to listen to all IPv6 interface, are you on IPv6 interface?  If not you need to set localhost to ip: "127.0.0.1", how do you declare your hosts?  Is your hosts: "localhost" or hosts: "chat.example.com"?  You need to check this area.

You may try the below for API permission to see if it works.

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - ip: "127.0.0.1/8"
            - acl: admin@chat.example.com
      - oauth:
	- scope: "ejabberd:admin"
        - access:
          - allow:
              - ip: "127.0.0.1/8"
              - acl: admin@chat.example.com
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
      - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"

I tried the above when i test localhost on my server and it works.  Should be working for you unless your other area of parameters something is not declare well.  FYI, I do not use port 9090 i use other port 5281 as I do not want too many associate to port 5280.

It is also important that your server firewall allows port to run on 9090 otherwise it won't work and things will continue to get stuck.

**Comment by Hassnain-Raza-Alvi** [comment]
Thanks it worked
I am just curious that if i want it to listen on all interfaces i-e private public IPs of the instance should i bind it to **0.0.0.0** ?

And if call the rest API by the private UP like **10.0.2.15** should it be added to who > IP in ejabberd.yml?

**Comment by molochmike** [comment]
Hi,

If you want to call the API outside from your ejabberd server, then under listen port for 9090 you have to remove away the ip: "127.0.0.1" completely and this will open the ip to outside world but becareful of what command that can be call on the API and security to your server must be properly in place otherwise you will face with security issue.

Once you have done the above then no need anymore 10.0.2.15 otherwise conflict of ip address will happen and API not able to work.  It is your decision whether to use localhost ip or open to outside world.  If you have developer working on the ejabberd, then create user for them in the server and allow them to ssh to the server with their own credentials.

**Comment by Hassnain-Raza-Alvi** [comment]
My use case is that i have applications in separate EC2 instances and ejabberd is in another instance so i want to implement something that the server will be able to call ejabberd REST API through its public or private IP and i can control rules via AWS Security groups. I am asking in context of that when i tried rest API configuration to listen on HTTP interface **0.0.0.0**

and applied **api_permissions** as follows
```
   "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"
```
so when i access sit via instance eprivate IP it says access denied but if i add the private IP of the system into IP whitelist it worked.
By the way instance private IP request is also locally so i am just curious that ejabberd does not figure iit out automatically? i need to add private IP to whitelist as well if i want to access it via private IP and if i want it to access it via public IP i need to add public IP as well?

**Comment by molochmike** [comment]
If thats the case might as well don't restrict the localhost ip 127.0.0.1.  Just define to open all.  What you can do is to ensure proper security is in place to your server and those ports in use and thats it.   Implement something as well to secure your DB and apache web too.

There is no automatically figure it out to ejabberd as calling to those API are already define by the port you set on the ejabberd.  It doesn't matter where the ejabberd runs on which server.  It all depend on how you write those application to call the API.

In aws sec group, those sec you set on those ports are define to what comes in to your instance, whereas if you wish to protect your applications layer such as those in use inside your EC2 such as apache, mysql, ejabberd, you can define them to using iptables and you probably need to write script to well protect those applications.

**Comment by kabirhaxor** [comment]
"public commands":
    who: all
    what:
      - "*"
      - "!stop"
      - "!start"
