### ISSUE TITLE
ejabberd 17.01 not starting on OS X

### ISSUE THREAD

**Issue by lefam** [processone/ejabberd#1675]
> What version of ejabberd are you using?

17.1

> What operating system (version) are you using?

OS X El Capitan (10.11.6)

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am not able to start it. I am running using either `ejabberdctl start` or `ejabberdctl live`. The latter produces the output below:

```
...
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V7.3  (abort with ^G)
(ejabberd@localhost)1> /Applications/ejabberd-17.01/bin/ejabberdctl: line 214:
 67122 Illegal instruction: 4  $EXEC_CMD "$CMD"
```

**Comment by cromain** [comment]
ejabberdctl is a bash script. run it in terminal, not in erlang vm.
