### ISSUE TITLE
mod_http_upload offline  eJabberd 17.01

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1681]
I installed the mod_http_upload module an i can send an image to another user that is online.
The recipient can only receive the image now when we are both online. When I am offline the recipient can not receive it.

How can I solve this?

**Comment by weiss** [comment]
> The recipient can only receive the image now when we are both online.

This would happen if you're using traditional peer-to-peer transfer rather than HTTP upload.

**Comment by PH-F** [comment]
Thank you, how can i do a http upload instead of a peer2peer? 
Is this supported in ejabberd or would this implicate to upload it with a separate  api?

**Comment by weiss** [comment]
> how can i do a http upload instead of a peer2peer?

The client must support and use [XEP-0363][1].

[1]: https://xmpp.org/extensions/xep-0363.html
