### ISSUE TITLE
How to get the groups in ejabberd 17.01

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1683]
I want to get all the persistent groups/rooms form a user.
When i send:

`<iq type="get" from="USER...@HOST.../NR..." id="ID......">
<query xmlns="jabber:iq:private"><storage xmlns="storage:bookmarks"></storage></query></iq>`

i receive

`<iq xmlns="jabber:client" to="USER...@HOST.../NR..." 
from="USER...@HOST.../NR..." type="result" id="ID......">
   <query xmlns="jabber:iq:private">
      <storage xmlns="storage:bookmarks" />
   </query>
</iq>`

or

`<iq type="get" id="ID......"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="storage:bookmarks"></items></pubsub></iq>`

i receive

`<iq xmlns="jabber:client" to="USER...@SERVER.../ID...." 
from="USER...@SERVER.../" type="error" id="ID.....">
   <pubsub xmlns="http://jabber.org/protocol/pubsub">
      <items node="storage:bookmarks" />
   </pubsub>
   <error code="404" type="cancel">
      <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
      <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Node not found</text>
   </error>
</iq>`

Also when i execute commandline:
`ejabberdctl get_user_rooms <user> localhost`
I get nothing.

However when i look in the database i do see my rooms:
`./ejabberdctl dump_table muc_room  muc_room`

**Whats the best way to get all my persistent groups/rooms?**

Other question:
Is there a way to get my bookmarks? Or are bookmarks only stored locally?

**Comment by molochmike** [comment]
Hi,

how do you work with the module on mod_muc?   The documentation provided by ejabberd processone mention on how to work around with the muc room and muc group.  For me i can work with create muc room and also destroy room and also make the room persistent when i test with some different xmpp frontclient such as psi, gajim, adium, monal ios, etc.

**Comment by badlop** [comment]
> ejabberdctl get_user_rooms <user> localhost

Please notice that this command gets the list of rooms where this user is *occupant*. It does not check membership, or owner, or admin. It only checks that the user has joined the rooms right now.

If you want to get the list of rooms where a user has some affiliation (is member, or admin, or...), then sorry, such command does not exist.

> Is there a way to get my bookmarks? Or are bookmarks only stored locally?

This is a client thing. For example, Tkabber uses private storage to store notes about roster contacts as defined in https://xmpp.org/extensions/xep-0049.html 

Tkabber sets a contact note with:
```xml
<iq id='1350:382456' type='set'>
  <query xmlns='jabber:iq:private'>
    <storage xmlns='storage:rosternotes'>
      <note jid='user3@localhost'
	cdate='2017-04-20T14:18:40Z'
	mdate='2017-04-20T14:44:26Z'>Notes about contact User3 guay!</note>
    </storage>
  </query>
</iq>
```
and gets all the notes with:
```xml
<iq id='1332:444495' type='get'>
  <query xmlns='jabber:iq:private'>
    <storage xmlns='storage:rosternotes'/>
  </query>
</iq>
```
To get those notes using ejabberdctl, I run a command like this:
> ejabberdctl private_get user1 localhost storage storage:rosternotes

Important: while testing all this, I found a pair of bugs, and I've fixed them in git right now.

**Comment by PH-F** [comment]
Thank you!
