### ISSUE TITLE
outgoing_s2s_timeout: seconds or milliseconds?

### ISSUE THREAD

**Issue by steffanson** [processone/ejabberd#1684]
Hi!

I use ejabberd 17.04 on Debian 8 installed by source.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In my ejabbery.yml I set  `outgoing_s2s_timeout: 10000` assuming the unit is milliseconds as stated in the docs: 

https://docs.ejabberd.im/admin/configuration/
> outgoing_s2s_timeout: Timeout: The timeout in milliseconds for outgoing S2S connection attempts.

However, the ejabberd log tells me those are seconds:
`2017-04-20 14:34:22.320 [warning] <0.37.0>@ejabberd_s2s_out:maybe_report_huge_timeout:455 value '10000' of option 'outgoing_s2s_timeout' is too big, are you sure you have set seconds?`

Who is right?

**Comment by zinid** [comment]
The log message is correct. The timeout format has been changed from milliseconds to seconds, and the check has been added. Please set the value in **seconds**.

**Comment by zinid** [comment]
The documentation will be corrected.

**Comment by steffanson** [comment]
> The log message is correct. The timeout format has been changed from milliseconds to seconds, and the check has been added. Please set the value in seconds.
> The documentation will be corrected.

Thanks for clarifying!
In this case, the default `ejabberd.yml` template for 17.04+ should also be updated:
```
##
## Outgoing S2S options
##
## Preferred address families (which to try first) and connect timeout
## in milliseconds.
##
## outgoing_s2s_families:
##   - ipv4
##   - ipv6
## outgoing_s2s_timeout: 10000
```

**Comment by zinid** [comment]
Indeed, thanks for the point.

**Comment by zinid** [comment]
I keep it opened until the documentation and config is fixed.

**Comment by cromain** [comment]
change applied in doc (will be readable at next release) and template
