### ISSUE TITLE
My custom attributes are being eliminated from messages since ejabberd 16.12

### ISSUE THREAD

**Issue by BesatZardosht** [processone/ejabberd#1692]
> What version of ejabberd are you using?

ejabberd 16.12 and ejabberd 17.x

> What operating system (version) are you using?

Mac os

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I used metadata for my messages all over the place but from ejabberd 16.12 all of them are being removed from message xml by ejabberd. Is there any way to prevent ejabberd from removing them and preserve the whole xml?

for example I have sth like:

```xml
<message type='chat' to='user2@host.com' from='user1@host.com'
 id='some_id' myAttribute='some value here'/>
```
but user2 gets:

```xml
<message type='chat' to='user2@host.com' from='user1@host.com'
 id='some_id' />
```

I believe it has sth to do with this part:
**Don’t build entire XML element, but rely on common “templates”**
in https://blog.process-one.net/ejabberd-16-12/
I would appreciate any help.

**Comment by badlop** [comment]
As you have noticed, the unknown attributes added to Message, Presence and Iq stanzas will get lost.

What you should do is to define your own XMPP extension: just add a subelement. In this example, yourattr is lost, while myextension is received by user2:
```xml
<message id='111:462851'
	yourattr='value0'
	type='chat'
	to='user2@localhost/tka1'>
  <body>hola</body>
  <myextension attribute1='value1'/>
</message>
```

**Comment by zinid** [comment]
I agree with @badlop: you should redefine your protocol: adding ad-hoc attributes is forbidden by the RFC schema (if you disagree, you shouldn't have picked open standard for your task in the first place). So, indeed, you need to develop your XML extension within some namespace (as the RFC suggests in this case), see https://github.com/processone/xmpp/issues/9 for details.
