### ISSUE TITLE
I cannot install ejabberd 17.04

### ISSUE THREAD

**Issue by BesatZardosht** [processone/ejabberd#1693]
> What version of ejabberd are you using?
ejabberd 17.04

> What operating system (version) are you using?
OS X El Capitan

> How did you install ejabberd (source, package, distribution)?
package installer

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.04/ejabberd-17.04-osx-installer.app.zip

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am getting this error message:
“ejabberd-17.04-osx-installer” is damaged and can’t be opened. You should move it to the Trash.

I have same issue with 17.03.
However 17.03 beta is fine..

**Comment by f0restgump92** [comment]
Im trying to upgreade from 17.03 beta to 17.04 from [source](https://github.com/processone/ejabberd/commit/44ae6bcc83f2a4f1e415f1b673527ab493b0219f)

And facing  
`call to undefined function p1_queue:start("/var/lib/ejabberd/queue") in application_master:init/4 line 134`

Maybe it has to do something with  origicanal issue

**Comment by zinid** [comment]
@f0restgump92 your issue is unrelated, `make distclean` should do the trick in your case, e.g.:
```
$ make distclean
$ ./autogen.sh
$ ./configure --all-your-flags-go-here
$ make
```

**Comment by f0restgump92** [comment]
Yeah i figured out. This solved my issue. Thank you for reply

**Comment by BesatZardosht** [comment]
I had to disable gatekeeper to be able to install

**Comment by cromain** [comment]
I'll add a note in osx README about this.

**Comment by rigalGit** [comment]
I could not find above instructions while going through ejabberd docs . I found OSX README file only after installing ejabberd .
