### ISSUE TITLE
Building the docker image with 17.04 fails

### ISSUE THREAD

**Issue by pipo02mix** [processone/ejabberd#1695]
> What version of ejabberd are you using?
17.04
> What operating system (version) are you using?
Mac Os Sierra 10.12.4
> How did you install ejabberd (source, package, distribution)?
Dockerfile
> What did not work as expected? Are there error messages in the log? What
-----
Writing ssl cert and private key to '/opt/ejabberd/ssl/localhost.pem'...
Generating ejabberd config file...
Generating ejabberdctl config file...
echo "Starting ejabberd..."
/sbin/run: line 92: /sbin/ejabberdctl: No such file or directory
/sbin/run: line 91: /sbin/ejabberdctl: No such file or directory
The command '/bin/sh -c run configure' returned a non-zero code: 1
> was the unexpected behavior? What was the expected result?

ejabberdctl is found and the image can be built.

What I did is change the tag version on the Dockefile because for the branch/tag 17.04 still on 17.03. (For 17.03 the image is built without problem) But with new tag ejabberd fails when it is started because ejabberdctl looks is not there. Any hint?

**Comment by imhotepisinvisible** [comment]
The default installation prefix changed in this release, so you need to edit the configure line in the Docker file to include `prefix=/`

**Comment by pipo02mix** [comment]
Thanks @imhotepisinvisible, it works.
