### ISSUE TITLE
Query: Is it possible to add a contact say admin to any anonymous user logging in?

### ISSUE THREAD

**Issue by sinsharat** [processone/ejabberd#1696]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Windows/Linux

> How did you install ejabberd (source, package, distribution)?

Distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am using a website with anonymous login.
I wanted to know if its possible to add a user say admin(registered user) to the anonymous user by default?

**Comment by badlop** [comment]
That should be possible using mod_shared_roster. See example 3 in https://www.ejabberd.im/shared-roster-all

**Comment by sinsharat** [comment]
@badlop thanks for the suggestion. I wanted to know for annonymous users, like i am an registered user and i want to know all the annonymous users who are online, similar to the users list in admin page, but instead of admin page i want to show it under a group of my login.

**Comment by badlop** [comment]
> For example i am building a CRM, where i have certain customer care executives who are all registered users and i have a website for users which is doing anonymous login. So i would like to have all my customer representatives to see the list of all available users for support.

For that, it would be preferable you define two vhosts in ejabberd, one for persistent users, other for anonymous temporary ones. In the "anon.localhost" vhost, define a group called "anongroup" with members: @online@. In the persistent-users vhost, define a group with members: @all@ and display: anongroup@anon.localhost.

I guess that should work, see example 2 and the module documentation https://docs.ejabberd.im/admin/configuration/#mod-shared-roster

> And once a anonymous user is picked for interaction by one of these customer representatives, the other registered users get notified for the same.

That feature is the only thing that I don't see how to implement using mod_shared_roster...

**Comment by sinsharat** [comment]
@badlop Thanks will try it out. The other part i think i may have to develop at the client side. Something like once a user receives the message ping then we remove that user from the roaster group so people know customer care don't get picked by to customer support people.

**Comment by sinsharat** [comment]
@badlop i tried configuring roaster group using example 2 of https://www.ejabberd.im/shared-roster-all, but it doesn't seem to work. All the users coming in, even the anonymous users get shows as offline, even when they are online. Also when the anonymous users close the website the anon users still get shown in the roaster as offline.

**Comment by badlop** [comment]
Right, they get shown as offline because presence is reciprocal: if the representative cannot see presence of anon user, then anon user cannot see presence of representative. This is mentioned in the example:
> Important: note that boy and boby will not see presence from the other people. They will be on the roster, but always offline because the other people don't have boy and boby in their rosters, and don't share presence with them.

**Comment by sinsharat** [comment]
@badlop but then atleast an option should be there for auto-delete these users from the roaster when they no longer exists. Right now, even when they are available its offline, the reason for which you mentioned above, but when they close the site, means the user doesn't exist, still they get shown in the roaster :(. This makes it extremely difficult to figure out who all are actually available. 
Another things is, when i was using to login the user as anon user a friend request was being sent to admin to notify if the new user has come. Now when using this shared roaster the friend request also doesn't come.

**Comment by badlop** [comment]
> even when they are available its offline, the reason for which you mentioned above, but when they close the site, means the user doesn't exist, still they get shown in the roaster :(. This makes it extremely difficult to figure out who all are actually available.

Instead of @all@, you can use @online@, but that of course requires that persistent accounts and anon accounts to be displayed to each other, so presences are shared

**Comment by sinsharat** [comment]
@badlop thanks for the info. For me making everyone visible is not a problem since i am only displaying to the anon user only the chat window of customer care representative. So the 1st example works fine with me.
The only doubt i have is for opening the chat for annon user i was sending add request to the admin and that doesn't come anymore and instead by default user gets shown in everybody group. What's the reason for this?

**Comment by badlop** [comment]
I guess, if admin already has an anon user as contact (thanks to shared group), your explicit "add request" doesn't get delivered.

**Comment by sinsharat** [comment]
But if thats the case under everybody group i have specified @online@ but once the annon becomes offline, the annon is no longer part of the group, still the request is lost, this seems a bit odd to me.

**Comment by sinsharat** [comment]
@badlop i had one more question, if i wanted to create a roaster with example 4 of below line:
https://www.ejabberd.im/shared-roster-all.
What i need is to have one roaster with all registered users, and another roaster with all anon users. Is it possible somehow? What i mean is like @all@ and @online@, is there any kind of regex supported to decide the various roaster entries?

**Comment by badlop** [comment]
There is not anything like regexp for members of shared group: you can only put explicit user JIDs, or @all@ or @online@.

The trick, that I already mentioned weeks ago, is that you configure two hosts in ejabberd: one only for registered accounts, other only for anonymous authentication. Then, in each vhost, you define a group with @all@. And finally, if you want to show users from one vhost to the other group, you can use Displayed groups: groupid@anonymous.example.com or something like that.
