### ISSUE TITLE
messages don't pass when mod_mam enabled to store into odbc connection and database is not available or database connection is bad

### ISSUE THREAD

**Issue by vkharchevin** [processone/ejabberd#1698]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian Linux

> How did you install ejabberd (source, package, distribution)?

Source code

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

messages don't pass when mod_mam enabled to store into odbc and the database connection is bad or database is not available. In this case mod_mam is stuck in user_receive_packet/user_send_packet hooks on query call until timeout which is high enough. ejabberd becomes unusable. in example client does not receive ping and tries to reconnect continuously.
no error output in logs.
The problem partially solved by adding timeout option into odbc:connect call and setting TRANSACTION_TIMEOUT to lower value in the code
it looks not correct behavior when slow or unavailable database is able to stuck ejabberd.

**Comment by zinid** [comment]
And do you find a lagging database (for more than 1 minute) is a correct behaviour?

**Comment by vkharchevin** [comment]
Everything may happen. networking issues are possible or the database may
go down for time more than 1 minute in example.
I don't think that ejabberd instability because of lagging database is a
good behavior


2017-05-05 11:59 GMT+03:00 Evgeny Khramtsov <notifications@github.com>:

**Comment by vkharchevin** [comment]
even if short database issues like 1 minute or less are blocking whole
ejabberd forcing clients to reconnect is not good behavior
of course message history is important but not as much as core
functionality, isn't it?

2017-05-05 12:18 GMT+03:00 Vladimir Kharchevin <vkharchevin@gmail.com>:

**Comment by zinid** [comment]
OK, here is the problem: we need to fetch archiving preference of a user before making a decision on storing a message in a database. Surprisingly, those preferences are stored in a database too. So, unless the preference are not cached, we anyway need to perform a query and wait for some amount of time: we cannot just store a message blindly. The only thing I can do in this situation is to make the query timeout configurable, so you can set whatever value you want.

**Comment by vkharchevin** [comment]
yep locally we solved the problem in same way adding timeouts to connect
and query calls.
that allowed to minimize database lags impact.
it would be great to have configurable timeouts in the ejabberd

to handle cases Thank you



2017-05-05 12:47 GMT+03:00 Evgeny Khramtsov <notifications@github.com>:

**Comment by zinid** [comment]
`sql_query_timeout: Seconds` can be used now.

**Comment by vkharchevin** [comment]
what about database connect timeout?

2017-05-05 13:22 GMT+03:00 Evgeny Khramtsov <notifications@github.com>:

**Comment by zinid** [comment]
`sql_start_interval` doesn't work for you?

**Comment by vkharchevin** [comment]
not as expected.
when the database is unavailable in some reason it may wait in connect call
too long
and we will have the same problem as described in initial report

2017-05-05 13:51 GMT+03:00 Evgeny Khramtsov <notifications@github.com>:

**Comment by zinid** [comment]
New option `sql_connect_timeout: Seconds` is added.
