### ISSUE TITLE
Cannot register admin "Error: cannot_register"

### ISSUE THREAD

**Issue by ylto** [processone/ejabberd#1705]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.04/ejabberd_17.04-0_amd64.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Useradmin is supposed to be created after I type this command 
`ejabberdctl register admin localhost password` but what I got back from terminal is 
`Error: cannot_register`

No error message in the log.

**Comment by cromain** [comment]
you should run ejabberdctl as 'ejabberd' user, when ejabberd is started and running. I guess you not not meet these requirements.

**Comment by sunnyalxe** [comment]
I am doing same but still same issue is coming.
I can not find any error in log files(ejabberd.log,error.log,crash.log)
My system :Ubuntu 16.4
My System User: hb

To compile ejabberd execute the commands:
./configure --enable-user=hb --enable-mysql

To create user I have used
ejabberdctl register mehul myemail@myhost.com 123456 
Result: Error: cannot_register

**Comment by moekur** [comment]
Hi,

Please ensure your host section on your ejabberd.yml includes your hostname
hosts:
  - "DESKTOP-FJ1ETVN"
  - "localhost"

BR

**Comment by mmehrle** [comment]
This is still broken. And no documentation on how to fix it.
