### ISSUE TITLE
Mod_shared_roster - push roster update on new user registration

### ISSUE THREAD

**Issue by ph4r05** [processone/ejabberd#1706]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Amazon Linux AMI 2017.03 (EC2)

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

 - mod_shared_roster with `@all@` member.
 - our desired situation is all ejabberd users have all other users in the (shared) roster - a complete graph.
 - we use external auth with `extauth_cache: 0`.

The problem we are experiencing is once a new user is registered, shared roster groups with `@all@` members are not updated for already connected clients - no roster update push is sent by the server. Connected clients have to reconnect in order to fetch new roster with new user.

It would be great if `mod_shared_roster` could update connected client rosters when new user is registered or goes online (in case of `@online@` member). It does not have to be default behaviour if it would impose non-negligible performance overhead but it would be nice to have such feature optional, at least, for smaller user groups where performance is not that big issue.

`mod_shared_roster` already does some roster update push - in case of `@online@` member if there are no more connected resources, the user is removed from the roster, server sends roster push. It would be great to have it symmetric -> push roster update if user appears.

Thanks for your opinion and feedback!

**Comment by badlop** [comment]
> It would be great if mod_shared_roster could update connected client rosters when new user is registered 

This works correctly when using internal auth. It fails as you described when using external auth. Apparently this fixes the problem::
```erlang
diff --git a/src/ejabberd_auth_external.erl b/src/ejabberd_auth_external.erl
index 8ba2e2b..153f645 100644
--- a/src/ejabberd_auth_external.erl
+++ b/src/ejabberd_auth_external.erl
@@ -267,6 +267,7 @@ set_password_mnesia(User, Server, Password) ->
 %% @spec (TimeLast, CacheTime) -> true | false
 %%       TimeLast = online | never | integer()
 %%       CacheTime = integer() | false
+    ejabberd_hooks:run(register_user, Server, [User, Server]),
     ejabberd_auth_mnesia:set_password(User, Server,
 					Password).
 

```

**Comment by badlop** [comment]
Since the next ejabberd release, extauth_cache will not be available, because there will be another option that covers all auth methods: auth_use_cache. That also means that my proposed patch will not work for newer versions.

**Comment by badlop** [comment]
This may in fact be a bug, and be related with https://github.com/processone/ejabberd/issues/1846

**Comment by Neustradamus** [comment]
@ph4r05: It is solved in last current version?

**Comment by ph4r05** [comment]
@Neustradamus Unfortunately, I stopped using Ejabberd so I am not able to verify. Maybe @badlop would know.

**Comment by badlop** [comment]
That behavior is not implemented. If anybody is insterested in it, this configuration and patch make it work:

```yaml
auth_method: external
extauth_program: "/home/ejaberd/examples/extauth/check_pass_null.pl"
auth_use_cache: true
```

```diff
diff --git a/src/ejabberd_auth_external.erl b/src/ejabberd_auth_external.erl
index a513c24ba..9c8eeee69 100644
--- a/src/ejabberd_auth_external.erl
+++ b/src/ejabberd_auth_external.erl
@@ -87,7 +87,7 @@ remove_user(User, Server) ->
     end.
 
 check_password_extauth(User, _AuthzId, Server, Password) ->
-    if Password /= <<"">> ->
+    Result = if Password /= <<"">> ->
 	    case extauth:check_password(User, Server, Password) of
 		Res when is_boolean(Res) -> {cache, Res};
 		{error, Reason} ->
@@ -96,7 +96,14 @@ check_password_extauth(User, _AuthzId, Server, Password) ->
 	    end;
        true ->
 	    {nocache, false}
-    end.
+    end,
+    case Result of
+        {_, true} ->
+            ejabberd_hooks:run(register_user, Server, [User, Server]);
+        _ ->
+            ok
+    end,
+    Result.
 
 -spec failure(binary(), binary(), atom(), any()) -> {nocache, {error, db_failure}}.
 failure(User, Server, Fun, Reason) ->


```

**Comment by Neustradamus** [comment]
@badlop: Thanks, can you add it directly instead of this patch?

**Comment by badlop** [comment]
No, because nobody uses it, it isn't tested in practice, I haven't checked its implications, and didn't check if there's another preferable method to accomplish it.

**Comment by Neustradamus** [comment]
Ok but do not close this ticket :)
