### ISSUE TITLE
Ejabberd 17.04 installation crashes - "Error running post install script"

### ISSUE THREAD

**Issue by milospajic** [processone/ejabberd#1707]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

WIndows 7 Professional 64 bit. Tried on two different laptops

> How did you install ejabberd (source, package, distribution)?

Windows 64-bits installer from https://www.process-one.net/en/ejabberd/downloads/ 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I get this message at the end of the installation. 
Ejabberd service is created but not started. 
Running postinstall.cmd manually doesn't help
Here are the log files created after the unsuccessful installation and before manual execution of postinstall.cmd: 

[logs.zip](https://github.com/processone/ejabberd/files/970655/logs.zip)

**Comment by cromain** [comment]
VM crached because it could not create cookie file on h:
Did you stated this installer as Administrator or as normal user ?
If started from normal user, what is h: on your system ? does user have write access to it ?

**Comment by milospajic** [comment]
Hi, thank you for the fast answer. I did start installer as an administrator. 
H: is a network drive. I've also changed H: access rights so everyone has a full control but it didn't help
Why did it try to write cookie there? Can I change location for the cookies?

**Comment by milospajic** [comment]
HOMEDRIVE is set to h: but even if I have right to write there, the installation fails.

**Comment by milospajic** [comment]
I've changed HOMEDRIVE to C: and now I have a different error. 

While "executing final installation script" I got the message that erl.exe stopped working. And few seconds after "error running post install script". Installation was started 'as administrator'

Here is my log file:

[ejabberd.zip](https://github.com/processone/ejabberd/files/983162/ejabberd.zip)

**Comment by milospajic** [comment]
Versions 17.04 and 17.03 are both having this erl.exe error. But version 17.01 doesn't and I've successfully installed it
