### ISSUE TITLE
Query: Command/method to check which all extensions are supported by ejabberd?

### ISSUE THREAD

**Issue by architsinha** [processone/ejabberd#1708]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ububtu 14.04

> How did you install ejabberd (source, package, distribution)?

From source, following the instructions at:  https://github.com/processone/ejabberd#quickstart-guide

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is there a command to check the list of extensions supported by the ejabberd server?

**Comment by zinid** [comment]
I answered here: http://stackoverflow.com/questions/43763048/command-to-check-which-all-xmpp-extension-protocols-does-ejabberd-support/43775444#43775444

**Comment by cromain** [comment]
@zinid i just copy your response here for the record

No direct command, but you can do the following magic from remsh (i.e. ejabberdctl debug):

```
> rp(lists:flatten(
     lists:map(
         fun(M) ->
            [Proto || {protocol, Proto} <- M:module_info(attributes)]
         end,
     element(2, application:get_key(ejabberd, modules))))).
```
