### ISSUE TITLE
Query: How to send message to group of users?

### ISSUE THREAD

**Issue by architsinha** [processone/ejabberd#1709]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
From source, following the instructions at: https://github.com/processone/ejabberd#quickstart-guide

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have just started on with ejabberd server.
My question is how to send message from ejabberd server to multiple clients. I was able to send message to a single client using the command:
_ejabberdctl send_message chat 192.168.33.50 user1@192.168.33.50 "subject" "message from server"_
(where 192.168.33.50 is the IP address of the machine running ejabberd)
However, I could not find a way to send to multiple clients at once. 
I suppose the method would be to create a group, add users to the group and send message to the group.

I tried to the following commands to create a group and add users to it:
_ejabberdctl srg_create group1 192.168.33.50 "group1" "group1" "group1"
ejabberdctl srg_user_add user1 192.168.33.50 group1 192.168.33.50
ejabberdctl srg_user_add user2 192.168.33.50 group1 192.168.33.50_

However, when I tried sending message with the following command using the group name instead of user name, no message was sent from the server:
_ejabberdctl send_message chat 192.168.33.50 group1@192.168.33.50 "subject" "message from server"_

So I wanted to know how I can achieve my use case of sending messages to multiple clients from the ejabberd server?

Regards,
Archit

**Comment by badlop** [comment]
Some responses provided in https://www.ejabberd.im/forum/28762/how-send-message-group-users
