### ISSUE TITLE
0198 Resumption Error

### ISSUE THREAD

**Issue by stevenlivz** [processone/ejabberd#1711]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
Debian Jessie in a Docker Container

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I managed to get a client using the other parts of 0198 and even the ability to enable resumption, but i am not able to actually enable it - i get a "failed" "unexpected-request" error as below. I have tried a load of different ways but no joy. I am probably doing something silly in the order of steps to resume but i have tried so many combinations - anyone know what the issue is? I'm going to debug the code next.

`15:26:33.739 [info] (<0.508.0>) Accepted connection 82.29.30.208:44774 -> 172.18.1.10:5222
15:26:33.804 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:33.828 [debug] (tcp|<0.508.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='14250373398070181395' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:33.829 [debug] (tcp|<0.508.0>) Send XML on stream = <<"<stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls></stream:features>">>
15:26:33.880 [debug] Received XML on stream = <<"<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>">>
15:26:33.880 [debug] State: {maxrate,1000,0.0,1493911593829121}, Size=51
M=25.5, I=51.553
15:26:33.882 [debug] Received XML on stream = <<>>
15:26:33.883 [debug] State: {maxrate,1000,493.8223788682753,1493911593880759}, Size=0
M=0.0, I=2.22
15:26:33.883 [debug] (tcp|<0.508.0>) Send XML on stream = <<"<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>">>
15:26:33.954 [debug] Received XML on stream = <<>>
15:26:33.954 [debug] State: {maxrate,1000,246.91118943413764,1493911593883048}, Size=0
M=0.0, I=71.407
15:26:34.038 [debug] Received XML on stream = <<>>
15:26:34.038 [debug] State: {maxrate,1000,123.45559471706882,1493911593954545}, Size=0
M=0.0, I=83.568
15:26:34.082 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:34.083 [debug] State: {maxrate,1000,61.72779735853441,1493911594038204}, Size=173
M=89.25474954665121, I=44.831
15:26:34.083 [debug] (tls|<0.508.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='17346263023192772765' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:34.084 [debug] (tls|<0.508.0>) Send XML on stream = <<"<stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features>">>
15:26:34.152 [debug] Received XML on stream = <<"<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1'>biwsbj1zdGV2ZW4scj0wYzE2YmRhYmIyOWE0YWZj</auth>">>
15:26:34.152 [debug] State: {maxrate,1000,0.0,1493911594084258}, Size=118
M=59.0, I=68.666
15:26:34.166 [debug] (tls|<0.508.0>) Send XML on stream = <<"<challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj0wYzE2YmRhYmIyOWE0YWZjOUNidndMVzhscW0vNHRDeExITUViUT09LHM9dGFBZTdROGpsaE5DV2hJQWxRTk1rUT09LGk9NDA5Ng==</challenge>">>
15:26:34.245 [debug] Received XML on stream = <<"<response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>Yz1iaXdzLHI9MGMxNmJkYWJiMjlhNGFmYzlDYnZ3TFc4bHFtLzR0Q3hMSE1FYlE9PSxwPTljalJSMTh4WmRTeWZiYzVTTzNwRVc3Z0ZFbz0=</response>">>
15:26:34.245 [debug] State: {maxrate,1000,858.3066627873145,1493911594152998}, Size=170
M=148.90163098878696, I=92.391
15:26:34.246 [debug] (tls|<0.508.0>) Send XML on stream = <<"<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>dj1lN3FKNXFvbTk2YUVsMlZBMGxkT2wyYi8zZnM9</success>">>
15:26:34.246 [info] (tls|<0.508.0>) Accepted c2s SCRAM-SHA-1 authentication for steven@alchemy.local by mnesia backend from 82.29.30.208
15:26:34.303 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:34.303 [debug] State: {maxrate,1000,997.7950804018791,1493911594302477}, Size=173
M=172.61938812810072, I=0.745
15:26:34.303 [debug] (tls|<0.508.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='8815545869350824592' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:34.319 [debug] (tls|<0.508.0>) Send XML on stream = <<"<stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session><c ver='TPQsKzvOdvXq31GtwtWaq//Kfag=' node='http://www.process-one.net/en/ejabberd/' hash='sha-1' xmlns='http://jabber.org/protocol/caps'/><sm xmlns='urn:xmpp:sm:2'/><sm xmlns='urn:xmpp:sm:3'/><csi xmlns='urn:xmpp:csi:0'/></stream:features>">>
15:26:34.476 [debug] Received XML on stream = <<"<iq type='set' id='bind-0'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>mobile</resource></bind></iq>">>
15:26:34.476 [debug] State: {maxrate,1000,0.0,1493911594303978}, Size=113
M=56.5, I=172.373
15:26:34.478 [info] (tls|<0.508.0>) Opened c2s session for steven@alchemy.local/mobile
15:26:34.478 [debug] (tls|<0.508.0>) Send XML on stream = <<"<iq type='result' id='bind-0'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>steven@alchemy.local/mobile</jid></bind></iq>">>
15:26:34.537 [debug] Received XML on stream = <<"<enable xmlns='urn:xmpp:sm:3' resume='true' max='60'/>">>
15:26:34.537 [debug] State: {maxrate,1000,0.0,1493911594476907}, Size=54
M=27.0, I=60.805
15:26:34.537 [info] Stream management with resumption enabled for steven@alchemy.local/mobile
15:26:34.538 [debug] (tls|<0.508.0>) Send XML on stream = <<"<enabled resume='true' max='20' id='g2gCbQAAAAZtb2JpbGVoA2IAAAXVYgAN6OpiAAdF6A==' xmlns='urn:xmpp:sm:3'/>">>
15:26:50.674 [info] (<0.510.0>) Accepted connection 82.29.30.208:41378 -> 172.18.1.10:5222
15:26:50.683 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:50.683 [debug] (tcp|<0.510.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='3469262206442802086' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:50.684 [debug] (tcp|<0.510.0>) Send XML on stream = <<"<stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls></stream:features>">>
15:26:50.753 [debug] Received XML on stream = <<"<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>">>
15:26:50.754 [debug] State: {maxrate,1000,0.0,1493911610684234}, Size=51
M=25.5, I=69.725
15:26:50.754 [debug] Received XML on stream = <<>>
15:26:50.754 [debug] State: {maxrate,1000,365.3347469161449,1493911610754033}, Size=0
M=0.0, I=0.433
15:26:50.754 [debug] (tcp|<0.510.0>) Send XML on stream = <<"<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>">>
15:26:50.802 [debug] Received XML on stream = <<>>
15:26:50.802 [debug] State: {maxrate,1000,182.66737345807246,1493911610754532}, Size=0
M=0.0, I=47.741
15:26:50.853 [debug] Received XML on stream = <<>>
15:26:50.853 [debug] State: {maxrate,1000,91.33368672903623,1493911610802355}, Size=0
M=0.0, I=51.427
15:26:50.890 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:50.890 [debug] State: {maxrate,1000,45.666843364518115,1493911610853875}, Size=173
M=88.52124286620165, I=36.883
15:26:50.891 [debug] (tls|<0.510.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='14531329108661858331' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:50.891 [debug] (tls|<0.510.0>) Send XML on stream = <<"<stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features>">>
15:26:50.943 [debug] Received XML on stream = <<"<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1'>biwsbj1zdGV2ZW4scj1kNWM4M2ZmZWZjMDQ0YmQ4</auth>">>
15:26:50.943 [debug] State: {maxrate,1000,0.0,1493911610891687}, Size=118
M=59.0, I=51.557
15:26:50.950 [debug] (tls|<0.510.0>) Send XML on stream = <<"<challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj1kNWM4M2ZmZWZjMDQ0YmQ4UkVQTm9PR2hPU1dlV1lYblluRGpXUT09LHM9WU5lRGNHeUc2d1hIVlBPYVl3MTBVdz09LGk9NDA5Ng==</challenge>">>
15:26:51.006 [debug] Received XML on stream = <<"<response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>Yz1iaXdzLHI9ZDVjODNmZmVmYzA0NGJkOFJFUE5vT0doT1NXZVdZWG5ZbkRqV1E9PSxwPXpPTWJiY3hMV1ZUU0N0TEc1dDVsdTEyQXJqWT0=</response>">>
15:26:51.007 [debug] State: {maxrate,1000,989.2523599537232,1493911610951328}, Size=170
M=168.1923293852228, I=55.714
15:26:51.008 [debug] (tls|<0.510.0>) Send XML on stream = <<"<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>dj1nS1pqQlVXM1Jaa1ppa2lHdHp1RFZFajZqYnM9</success>">>
15:26:51.008 [info] (tls|<0.510.0>) Accepted c2s SCRAM-SHA-1 authentication for steven@alchemy.local by mnesia backend from 82.29.30.208
15:26:51.121 [debug] Received XML on stream = <<"<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='alchemy.local' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>">>
15:26:51.121 [debug] State: {maxrate,1000,998.1836655069892,1493911611120127}, Size=173
M=172.68634383721655, I=1.149
15:26:51.121 [debug] (tls|<0.510.0>) Send XML on stream = <<"<?xml version='1.0'?><stream:stream id='9848166309257251954' version='1.0' xml:lang='en-GB' xmlns:stream='http://etherx.jabber.org/streams' from='alchemy.local' xmlns='jabber:client'>">>
15:26:51.122 [debug] (tls|<0.510.0>) Send XML on stream = <<"<stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session><c ver='TPQsKzvOdvXq31GtwtWaq//Kfag=' node='http://www.process-one.net/en/ejabberd/' hash='sha-1' xmlns='http://jabber.org/protocol/caps'/><sm xmlns='urn:xmpp:sm:2'/><sm xmlns='urn:xmpp:sm:3'/><csi xmlns='urn:xmpp:csi:0'/></stream:features>">>
15:26:51.294 [debug] Received XML on stream = <<"<iq type='set' id='bind-0'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>mobile</resource></bind></iq>">>
15:26:51.294 [debug] State: {maxrate,1000,0.0,1493911611122048}, Size=113
M=56.5, I=172.18
15:26:51.295 [debug] (tls|<0.508.0>) Send XML on stream = <<"<stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='en-GB' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>">>
15:26:51.295 [debug] (tls|<0.508.0>) Send XML on stream = <<"</stream:stream>">>
15:26:51.295 [info] (tls|<0.508.0>) Closing c2s session for steven@alchemy.local/mobile: Stream closed by us: Replaced by new connection (conflict)
15:26:51.295 [info] (tls|<0.510.0>) Opened c2s session for steven@alchemy.local/mobile
15:26:51.296 [debug] (tls|<0.510.0>) Send XML on stream = <<"<iq type='result' id='bind-0'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>steven@alchemy.local/mobile</jid></bind></iq>">>
15:26:57.339 [debug] Received XML on stream = <<"<resume h=\"0\" previd=\"g2gCbQAAAAZtb2JpbGVoA2IAAAXVYgAN6OpiAAdF6A==\" xmlns=\"urn:xmpp:sm:3\" />">>
15:26:57.340 [debug] State: {maxrate,1000,0.0,1493911611294715}, Size=92
M=46.0, I=6045.317
15:26:57.340 [debug] (tls|<0.510.0>) Send XML on stream = <<"<failed xmlns='urn:xmpp:sm:3'><unexpected-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></failed>">>
`

**Comment by weiss** [comment]
The problem is that you're binding a resource, which creates a new session, before attempting resumption.

**Comment by stevenlivz** [comment]
Wonderful @weiss - that is it working now. Goodness that was simple. I am modifying an existing library to add this support and the binding it right there. Thanks very much.

**Comment by abdelhafiddahhani** [comment]
Hii guys !
how i can fixe this problem
i installed ejabberd in ubuntu and when i try to access to this link : 127.0.0.1:5222 i got this error 

<?xml version='1.0'?><stream:stream id='12847806584895138227' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'><stream:error><not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>syntax error</text></stream:error></stream:stream>

thank you 
Best regards,

**Comment by gabrix73** [comment]
I'm having the same problem, ejabberd 18.12.1-2 ~ bpo9 + 1 on debian stretch.

**Comment by licaon-kter** [comment]
Logs?
