### ISSUE TITLE
Wrong certificate for s2s connections

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1712]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian 8.7

> How did you install ejabberd (source, package, distribution)?

From jabber.at repo

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After upgrade from ejabberd 16.09 to 17.04 s2s connections have wrong certificate - always I see default certificate configured in:

```
s2s_certfile: 'CERT_LOCATION'

define_macro:
  'CERT_LOCATION': "/etc/ejabberd/my_cert.pem"
```
Ejabberd ignore domain configuration:
```
host_config:
  "mydomain.tld":
    domain_certfile: 'CERT_LOCATION_MYDOMAIN_TLD'
```
c2s connections have correct certificate for domain. See this: https://check.messaging.one/result.php?domain=jix.im&type=server

**Comment by zinid** [comment]
Is it for outbound or inbound s2s connections? Or for both?

**Comment by beherit** [comment]
I think is only for inbound because I don't have problem with connect to other servers.

**Comment by zinid** [comment]
Do you have access to remsh (`ejabberdctl debug`)? If yes, please show what the following commands return valid values:
```erlang
> [{D, ejabberd_config:get_option({s2s_certfile, D}, fun(S) -> S end)} || D <- ejabberd_config:get_myhosts() ++ ejabberd_router:get_all_routes()].
> [{D, ejabberd_config:get_option({domain_certfile, D}, fun(S) -> S end)} || D <- ejabberd_config:get_myhosts() ++ ejabberd_router:get_all_routes()].
```

**Comment by zinid** [comment]
Also, do you have `certfile` option configured in `ejabberd_s2s_in` listening section?

**Comment by beherit** [comment]
I have problem with running `ejabberdctl debug`:

```
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [async-threads:10] [kernel-poll:true]

*** ERROR: Shell process terminated! (^G to start new job) ***
```
Maybe some package is required for debbuging?

I don't have `certfile` option configured in `ejabberd_s2s_in`. My config look similar to this config: https://github.com/jabber-at/config

**Comment by zinid** [comment]
No, this probably means you have problem accessing Erlang cookie file. Try to run the command from `ejabberd` user.

**Comment by beherit** [comment]
Unfortunately this doesn't work too :( Maybe is another way to debug this issue?

**Comment by zinid** [comment]
How do you run ejabberdctl commands? Do they work for you?

**Comment by zinid** [comment]
Ah, wait. Actually `s2s_certfile` option has top priority. Try to define it within host_config section.

**Comment by zinid** [comment]
i.e.
```yaml
host_config:
  "mydomain.tld":
    domain_certfile: 'CERT_LOCATION_MYDOMAIN_TLD'
    s2s_certfile: 'CERT_LOCATION_MYDOMAIN_TLD'
```

**Comment by beherit** [comment]
@zinid I have a lot of virutal hosts added so I must remove `s2s_certfile` option from config?

**Comment by zinid** [comment]
That's an option too.

**Comment by beherit** [comment]
Thank You @zinid - this solved my problem :)
