### ISSUE TITLE
ejabberd does not return the PubSub/PEP node identity in disco#info results, although it is required by XEP-0060 § 5.3

### ISSUE THREAD

**Issue by vanitasvitae** [processone/ejabberd#1717]
> What version of ejabberd are you using?

ejabberd 16.09 from raspbian testing repository

> What operating system (version) are you using?

raspbian stable on a raspberry pi model b+

> How did you install ejabberd (source, package, distribution)?

via apt-get from the rapbian testing repository

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I send a pubsub disco#info query on a pubsub node that does not exist, ejabberd does not reply with a item-not-found error. Instead it sends the stanza below, which does not contain information about whether the node is a LeafNode or a CollectionNode, which is required according to the XEP §5.3:

```
A pubsub service MUST allow entities to query individual nodes for the information associated with that node. The Service Discovery protocol MUST be used to discover this information. The "disco#info" result MUST include an identity with a category of "pubsub" and a type of either "leaf" or "collection".
```
Here are the stanzas being sent and received by my client:
````
17:28:02 SENT (0): <iq to='myclient@ejabberd.srv' id='cq41A-75' type='get'><query xmlns='http://jabber.org/protocol/disco#info' node='invalid-node'></query></iq>
17:28:03 RECV (0): <iq from='myclient@ejabberd.srv' to='myclient@ejabberd.srv/17165994385926269896640' id='cq41A-75' type='result'><query xmlns='http://jabber.org/protocol/disco#info' node='invalid-node'><identity category='account' type='registered'/></query></iq>
````

**Comment by vanitasvitae** [comment]
Related Smack bug report: https://issues.igniterealtime.org/projects/SMACK/issues/SMACK-759?filter=allopenissues

**Comment by cromain** [comment]
17.07 is compliant with XEP-0060 (PubSub) chapter 5.3. But it's not with XEP-0163 (PEP) chapter 6.1.

**Comment by cmeng-git** [comment]
Hi cromain,
Thanks for the fix.

**Comment by weiss** [comment]
> 17.07 is compliant with XEP-0060 (PubSub) chapter 5.3.

I think so, too, but I think it doesn't comply with [XEP-0030][1], table 1, which says we should return `<item-not-found/>` if the "JID+NodeID of the specified target entity does not exist".

> it's not with XEP-0163 (PEP) chapter 6.1.

[That `disco#info` query][2] is different because it doesn't have a `node` attribute.  I think the code was correct for existing PEP nodes, i.e. the `leaf` identity should not be removed from the result.

[1]: https://xmpp.org/extensions/xep-0030.html#errors
[2]: https://xmpp.org/extensions/xep-0163.html#support-owner

**Comment by cmeng-git** [comment]
I just pull in the latest source from trunk with your fix, source built and installed.
[#1717](https://github.com/processone/ejabberd/issues/1717)

as what weiss has mentioned, you have removed the XEP-60 5.3  requirements:
> XEP-0163 (PEP) chapter 6.1.
> If the account owner's server supports PEP and the account is provisioned for PEP, the server MUST return an identity of "pubsub/pep" on behalf of the account (**as well as a list of the namespaces and other features it supports, including all supported XEP-0060 features**):

I would like to refer to the following link:
https://community.igniterealtime.org/thread/60987
cmeng Jul 31, 2017 2:59 AM (in response to cmeng);

The response to disco#info for node='urn:xmpp:avatar:data' does not work when there is no pre-stored urn:xmpp:avatar:data' data on the server.

=== aTalk log ==========
08-02 08:12:10.726 D/SMACK: SENT (0): <iq to='leopard@atalk.org' id='7Qn3T-144' type='get'><query xmlns='http://jabber.org/protocol/disco#info' node='urn:xmpp:avatar:data'></query></iq>
08-02 08:12:10.736 D/SMACK: RECV (0): <iq xml:lang='en' to='leopard@atalk.org/atalk' from='leopard@atalk.org' type='result' id='7Qn3T-144'><query node='urn:xmpp:avatar:data' xmlns='http://jabber.org/protocol/disco#info'><identity type='registered' category='account'/></query></iq>

**Comment by cmeng-git** [comment]
Hi,

 

My view is different. Actually ejabberd 17.07 meets both the XEP-0163 6.1 and XEP-0060 5.3;  XEP-0030 only applied if:

 

7. Error Conditions (XEP-0030)

If a specific entity (JID or JID+node) does not support the disco namespace, refuses to return disco results to the specific requesting entity, or refuses to return disco results to any requesting entity, it SHOULD return an appropriate error message (such as <service-unavailable/>, <forbidden/>, or <not-allowed/>, respectively). One example is shown below.

 

which currently does not apply to ejabberd server or  the client intent in current situation. Instead ejabberd should implement as per XEP-0163 6.1 and

 

5.3 Discover Node Information (XEP-006)

A pubsub service MUST allow entities to query individual nodes for the information associated with that node. The Service Discovery protocol MUST be used to discover this information. The "disco#info" result MUST include an identity with a category of "pubsub" and a type of either "leaf" or "collection". 

 

Which currently ejabberd 17.07 meets this requirements, except under one specific condition as below:

If the ejabberd server sql tables “pubsub_item” and “pubsub_node” do not have a  pre-stored entry for 'urn:xmpp:avatar:data' and 'urn:xmpp:avatar:metadata' data, then the following disco#info with attribute node='urn:xmpp:avatar:data' or node='urn:xmpp:avatar:metadata' will fail. The response failed both XEP-0163 and XEP-0060 requirements.

 

08-02 08:12:10.726 D/SMACK: SENT (0): <iq to='leopard@atalk.org' id='7Qn3T-144' type='get'><query xmlns='http://jabber.org/protocol/disco#info' node='urn:xmpp:avatar:data'></query></iq>

08-02 08:12:10.736 D/SMACK: RECV (0): <iq xml:lang='en' to='leopard@atalk.org/atalk' from='leopard@atalk.org' type='result' id='7Qn3T-144'><query node='urn:xmpp:avatar:data' xmlns='http://jabber.org/protocol/disco#info'><identity type='registered' category='account'/></query></iq>

 

You can refer to the link below for more information:

https://community.igniterealtime.org/thread/60987
cmeng Jul 31, 2017 2:59 AM (in response to cmeng);

**Comment by zinid** [comment]
> By way, the rebar.config specifies p1_oauth2 version 0.6.2 failed during compilation. So I have to revert to 0.6.1

Please don't mix several issues into one.

**Comment by cromain** [comment]
@weiss I understand i should just revert the leaf identity removal, and comply about XEP-0030 when providing node which does not exists (now we return default features of PEP service while we should return item-not-found). right ?

**Comment by cmeng-git** [comment]
I think ejabberd needs to comply with both  XEP-0163 and XEP-0060 requirements, and should be independent of data entry in the server table as per XEP-0163 stated below:

6. Determining Support
6.1 Account Owner Service Discovery
If the a**ccount owner's server supports PEP and the account is provisioned for PEP**, the server MUST return an identity of "pubsub/pep" **on behalf of the account** (as well as a list of the namespaces and other features it supports, **including all supported XEP-0060 features**):

**Comment by cromain** [comment]
Last commit fixes XEP-0060 and XEP-0163 compliance.

- When querying disco#info on bare jid without providing PEP node (which is the expected use by the way, as suggested by XEP-0163) the result is correct now as described in 6.1.
- When querying disco#info on bare jid with PEP node, if node is not found we still return the registered account identity. If node exists, we also add the PEP features also. I see this as a "plus" and not a requirement. XEP-0163 does not clearly state server MUST handle this case and XEP-0030 state server SHOULD reply item-not-found.

For a strict XEP-0030 support, when query disco#info on JID+node AND node does not exists, we SHOULD return item-not-found error. While is is not mandatory i see three problems to go that deep:
- XEP-0163 does not clearly state this case SHOULD be implemented
- XEP-0030 notion of node is about caps feature, not PEP node
- handling possible item-not-found would require refactor in mod_pubsub, not sure it's worth it

I consider actual behaviour good enough. If someone think i'm really wrong, please develop and suggest PR.

**Comment by Flowdalic** [comment]
What do you currently return when a node does not exists? Still a result IQ without 'identity'?

**Comment by weiss** [comment]
> What do you currently return when the requested PubSub node does not exists? Still a result IQ without 'identity'?

It will return a result IQ without `category='pubsub'` identity.

Isn't this good enough from the client perspective?  I mean, wouldn't you want to handle a missing `leaf` identity like a non-existent node anyway?  Especially as this is the only strong guarantee you get from the specs (XEP-0060 says that this identity MUST be returned for an existing `leaf` node, whereas XEP-0030 just says that servers SHOULD return `<item-not-found/>` on nonexistent nodes).

**Comment by Flowdalic** [comment]
> Isn't this good enough from the client perspective? 

Probably, I'll look into it. Thanks for the clarification.
