### ISSUE TITLE
Query results datatype are different for same query in two different ejabberd server

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1718]
> What version of ejabberd are you using?
Source code Release 16.02

> What operating system (version) are you using?
CentOs7

> How did you install ejabberd (source, package, distribution)?
source

I have two ejabberd instances when i ran ejabberd instances in debug mode and executed sql qurey 
 ` sql_queries:get_password` for same username and password i am getting to different output

on first instance i got -> <<"admin">>
on second instance i got -> <<97,0,100,0,109,0,105,0,110,0>>

i am confused this kind of behaviour, can anyone guide me ?

**Comment by badlop** [comment]
Well, <<97,100,109,105,110>> is another representation in erlang of <<"admin">>, but those 0, between numbers are strange. There may be some difference between each ejabberd node: maybe different mysql version, or different table definition. Try registering accounts in one node and the other, then check how the passwords are retrieved by your call: is there any relation between where the account was first created, and how it  is retrieved?

**Comment by Veerbhadra277** [comment]
Yup @badlop it's datatype change was using nvarchar instade text, after correction it's working correctly
