### ISSUE TITLE
Offline message in group chat.

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1720]
> What version of ejabberd are you using?
17.01

We use muc_sub and I know which users are in the group (offline and online users). 
I have a hook on mod_offline_post to send a push message when a user is offline. This works fine on 1-on-1 messages.

However, this does not work for group messages.
What I can do perhaps is _connect to a hook_ when a message is send to a group, check each subscriber and "if a user if offline" then send the push message.

However what hook can I use for an incoming group message?
And how can I check the user presence there?

**Comment by badlop** [comment]
When a room receives a message, it runs the muc_filter_message hook. See an example usage in mod_mam. The arguments include the stanza and the room state, where I guess there's a list of Occupants and Subscribers.

**Comment by PH-F** [comment]
Thanks. I started with a module. It gets started but when the hook is called i get an error.
I guess i'm missing a simple thing. Can you please help me a bit?

https://github.com/PH-F/mod_offline_http_post_group/blob/master/src/mod_offline_http_post_group.erl

@ejabberd_hooks:run_fold1:368 {undef,[{mod_offline_http_post_group,muc_filter_message,[{message,<<"purple4b6ed334">>,groupchat,<<>> ...........
running hook: {muc_filter_message,[{state,<<"myroom">>,......

**Comment by badlop** [comment]
How many arguments does the hook pass to your function? You defined the function with 3 arguments, which is correct for current master (as seen in mod_mam example). Your code works correctly for me using ejabberd git master.

However, this is only true for current git master, since commit https://github.com/processone/ejabberd/commit/485aae8134b950218f7e86b80787c94d2dda05d5 . Before that, the hook passed 5 arguments, for example, if you are using 17.01 or older.

**Comment by PH-F** [comment]
Thank you for the feedback, but when i change it to 5 parameters it crashes (in ejabberd 17.01)

See the minor code https://github.com/PH-F/mod_offline_http_post_group/blob/ejabberd-17-01/src/mod_offline_http_post_group.erl


------------------------------------------------------------------------------------
** Reason for termination = 
** {function_clause,[{xmpp,get_els,[[]],[{file,"src/xmpp.erl"},{line,204}]},{xmpp,remove_subtag,2,[{file,"src/xmpp.erl"},{line,429}]},{mod_muc_room,process_groupchat_message,3,[{file,"src/mod_muc_room.erl"},{line,773}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2017-05-22 12:03:03 =CRASH REPORT====
  crasher:
    initial call: mod_muc_room:init/1
    pid: <0.460.0>
    registered_name: []
    exception exit: {{function_clause,[{xmpp,get_els,[[]],[{file,"src/xmpp.erl"},{line,204}]},{xmpp,remove_subtag,2,[{file,"src/xmpp.erl"},{line,429}]},{mod_muc_room,process_groupchat_message,3,[{file,"src/mod_muc_room.erl"},{line,773}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,626}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: ['ejabberd_mod_muc_chat.dev.congredi.eu',ejabberd_sup,<0.39.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 2444
  neighbours:
------------------------------------------------------------------------------------

**Comment by badlop** [comment]
Look at the function spec, and also to the example function in mod_mam that you should immitate, and also the call to the hook in mod_muc_room that you must satisfy: your function must return the original packet, or a modified packet, or the atom 'drop', but not a list []

**Comment by arafat-al-mahmud** [comment]
> Look at the function spec, and also to the example function in mod_mam that you should immitate, and also the call to the hook in mod_muc_room that you must satisfy: your function must return the original packet, or a modified packet, or the atom 'drop', but not a list []

@badlop How to modify a packet inside muc_filter_message to include an additional field, so that the client will receive it ?
