### ISSUE TITLE
Does ejabberd mod_offline support ex auth?

### ISSUE THREAD

**Issue by HeroPD** [processone/ejabberd#1721]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

OS X

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
Yes, as long as an external authentication program implements `is_user_exists` call.

**Comment by HeroPD** [comment]
Thanks it's working as expected
