### ISSUE TITLE
How do i include external libraries in my custom module ?

### ISSUE THREAD

**Issue by HeroPD** [processone/ejabberd#1723]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

OS X 

> How did you install ejabberd (source, package, distribution)?

source in dev env , distribution in prod env

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by badlop** [comment]
See another modules as example Search another one that does something like what you want, and use the same solution.

**Comment by HeroPD** [comment]
i am used `code: add_patha/1 , code:add_path/1` but not exacly sure it is proper solution
