### ISSUE TITLE
Not able to setup ejabberd cluster in the same machine.

### ISSUE THREAD

**Issue by sinsharat** [processone/ejabberd#1724]
> What version of ejabberd are you using?
ejabberd-17.04

> What operating system (version) are you using?
ubuntu 14.04 Trusty

> How did you install ejabberd (source, package, distribution)?
binary package distribution

> What did not work as expected? Are there error messages in the log? 

Steps:
1st ejabberd installation:
-------------------------------
1. install ejabberd in path : /home/sharat/ejabberd-17.04 as a non cluster setup.
2. Cookie generated in /home/sharat/.erlang.cookie
3. Using domain name as crmservice
4. Configured ERLANG_NODE=ejabberd@node1 in ejabberdctl.cfg
5. Configured inetrc file as below:
```
{lookup,["file","native"]}.
{host,{127,0,0,1}, ["node1","node1"]}.
{file, resolv, "/etc/resolv.conf"}.
```
6. started ejabberd. Worked fine.

2nd ejabberd installation:
-------------------------------
1. install ejabberd in path : /home/sharat/ejabberd-17.04_1 as a cluster setup.
2. Using domain name as crmservice and machine name as node2.
3. Copied all the contents of ejabberd.yml from 1st installation to 2nd installation.
4. Changed all the ports to a different port.
3. Configured ERLANG_NODE=ejabberd@node2 in ejabberdctl.cfg
4. Configured inetrc file as below:
```
{lookup,["file","native"]}.
{host,{127,0,0,1}, ["node2","node2"]}.
{file, resolv, "/etc/resolv.conf"}.
```
6. Tried to start ejabberd.
> was the unexpected behavior? What was the expected result?
On trying to start the ejabberd service on the second installation getting the error:
```
sharat@BLR1000011929:~/ejabberd-17.04_1/bin$ ./ejabberdctl start
ERROR: The ejabberd node 'ejabberd@node2' is registered,
       but no related beam process has been found.
Shutdown all other erlang nodes, and call 'epmd -kill'.
```
On shutting down the 1st installation, and starting the second installation it works fine.
But both are not able to run together to join them as a cluster.

Expected behavior:
-----------------------
Both installations should run and should be able to join them as a cluster.

**Comment by badlop** [comment]
See the log files of second node (well, and also of first node), it may show something relevant. In my initial test, the only required difference between first and second nodes are: install path, ERLANG_NODE in ejabberdctl.cfg, and port numbers in ejabberd.yml... and both start correctly.

**Comment by sinsharat** [comment]
@badlop its not writing any logs in the second node and just giving this error message. Thats why posted here. Since without any logs i am not able to understand the problem.

**Comment by sinsharat** [comment]
@badlop I did some digging and found that there is a check_start() method in etcdctl which it performs before calling the start of ejabberd.
I think while running both nodes together some condition is wrong here:
```
# make sure node not already running and node name unregistered
check_start()
{
    "$EPMD" -names 2>/dev/null | grep -q " ${ERLANG_NODE%@*} " && {
        ps ux | grep -v grep | grep -q " $ERLANG_NODE " && {
            echo "ERROR: The ejabberd node '$ERLANG_NODE' is already running."
            exit 4
        } || {
            ps ux | grep -v grep | grep -q beam && {
                echo "ERROR: The ejabberd node '$ERLANG_NODE' is registered,"
                echo "       but no related beam process has been found."
                echo "Shutdown all other erlang nodes, and call 'epmd -kill'."
                exit 5
            } || {
                "$EPMD" -kill >/dev/null
            }
        }
    }
}
```
As the nodes i am running are ejabberd@node1 and trying to start ejabberd@node2. While trying to start ejabberd@node2 the below error is coming:
```
ERROR: The ejabberd node 'ejabberd@node2' is registered,
       but no related beam process has been found.
```
I think the above script check is not proper, since when i shutdown node1 then node2 starts without any problem and vice versa.

Don't have much idea of shell scripts hence need your help.

Thanks!

**Comment by badlop** [comment]
Ahh sorry, your first explanation already had a mistake that I didn't notice: an erlang node name is expected to be like something@machinename. So, you should name the nodes varying the first element, not the second:
* This is desirable for two nodes in the same machine: ejabberd1@machine and ejabberd2@machine
* This is desirable for nodes in different machines: ejabberd@machine1 and ejabberd@machine2

**Comment by sinsharat** [comment]
@badlop from what i understand i just need to change the ERLANG_NODE parameter in ejabberdctl.cfg to node1@ejabberd and node2@ejabberd and it should work right? Or is there any other change required as well?

**Comment by badlop** [comment]
In regard to configuration, yes, only that change. But you may also need to delete the Mnesia database spool directories contents, as those databases were created with old nodenames.

**Comment by sinsharat** [comment]
@badlop ok will delete those and try it. Also i think will need to modify bin/ejabberdctl file since while installing with binary it asks only machine name and by default names it as ejabberd@machine_name. Hence the env variable in the file for ERLANG_NODE gets created there as well with the same name.
Thanks!

**Comment by sinsharat** [comment]
@badlop Thanks it worked.
