### ISSUE TITLE
Register & unregister user

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1725]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 6.5

> How did you install ejabberd (source, package, distribution)?

Installer community edition

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I have the mod_http_api and oauth token working fine.  However, I wish to know how can i control to only allow registered admin users in my ejabberd to register and unregister user and others to be list as "deny".  How can this be done on the API level?  Or can i define a scope using Oauth Token?  Thanks.

**Comment by badlop** [comment]
I see no option in mod_register to control this. Alternatives are:
* Using ip_access option in mod_register, if your admins have specific IP addresses.
* Enable mod_register_web so admins can create accounts, then set a restrictive ip_access option in mod_register

**Comment by molochmike** [comment]
Hi @badlop 

Thanks for the information.  Can i ask is there any example you can provide me for the configuration above?  

I am not able to do and understand how to limit the thing just for admin.

**Comment by badlop** [comment]
For ip_access there is an example in https://docs.ejabberd.im/admin/configuration/#mod-register
For mod_register_web, simply enable it https://docs.ejabberd.im/admin/configuration/#mod-register-web

**Comment by molochmike** [comment]
Hi @badlop 

Thanks for the link but I have read it though.  Just that I was asking if you have any other examples that can share to me.  It's ok anyway.  Thanks.  I will close this topic.
