### ISSUE TITLE
DB write failed on shutdown

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1726]
> What version of ejabberd are you using?

17.x

> What operating system (version) are you using?

deb

> How did you install ejabberd (source, package, distribution)?

src

```
08:08:03.676 [debug] (tls_zlib|<0.426.0>) Send XML on stream = <<"</stream:stream>">>
08:08:03.730 [debug] Supervisor inet_gethost_native_sup started undefined at pid <0.437.0>
08:08:03.730 [debug] Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.436.0>
08:08:05.622 [error] Supervisor ejabberd_gen_mod_sup had child 'mod_offline_example.com'
 started with gen_server:start_link({local,'mod_offline_example.com'},
 mod_offline, [<<"example.com">>,[{db_type,sql}]], []) at <0.369.0>
 exit with reason killed in context shutdown_error
08:08:05.623 [debug] Route unregistered: example.com
08:08:05.636 [info] ejabberd 17.04.247 is stopped in the node ejabberd@localhost
```

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have calling a hook of mod_offline to write to db when we are stopping the server which flushes the cache to db . 
however if there are many stanzas in cache it shut-downs the server without finishing the SQL writes how can make sure that data is committed on shut-down in short have a clean shut down.
Can there be something that can check if mod_offline pid has any requests in process if then delay the shutdown  ?

**Comment by nOmi7** [comment]
Is there a way to know if any db writes are going on from mod_offline process.
The problem i am facing is 
User1 sends messages continously -- peer goes offline -- server waits for 30 seconds for timeout -- on timeout start flushing from cache to  mod_offline process..(not written to db yet) -- during the same time peer comes online .. as messages are in mod_offline process yet and not written to db on online pres it fetched 0 messages and now users start getting messages again from user1 but db write it still going on.
when user now disconnects then he gets all the messages from db.

**Comment by zinid** [comment]
> however if there are many stanzas in cache it shut-downs the server without finishing the SQL writes how can make sure that data is committed on shut-down in short have a clean shut down.

The default period of waiting is 2 seconds, which is clearly seen from your log.
You can change it [here](https://github.com/processone/ejabberd/blob/master/src/gen_mod.erl#L102). Set it to 1 minute or more and you will be fine.

**Comment by nOmi7** [comment]
```
Thanks @zinid  i was going thru gen_mod i also saw there is 
wait_for_stop(Process, MonitorReference) ->
    receive
      {'DOWN', MonitorReference, _Type, _Object, _Info} -> ok
      after 5000 ->
		catch exit(whereis(Process), kill),
		wait_for_stop1(MonitorReference)
    end.
```

What does this do ?? it waits for 5000 and then kills it ? how if it change it would affect ?

**Comment by zinid** [comment]
Ah, this crap probably should be removed, I will try to cope with it tomorrow.

**Comment by nOmi7** [comment]
:) what was this 'crap' doing anyways ... 
@zinid  i need your expert view on a problem that i am facing would be really thankful if you can point me to some direction ..
When a user is sending messages continuously (say 100 msgs per sec.. i know its little impossible to type os fast ..) but we wrote a bot that sends messages continuously for testing purposes) all works good except one place  when the peer disconnects and reconnects again very fast and the sender is still looping 
in this case the db writes are still going on and when peer comes online the messages are not being pulled from spool.... how can i make sure to have consistency with fast sender and slow receiver. 


User------sending msgs in loop---------> server puts in queue when peer is online ---->  peer now disconnects -----> the messages are still going in queue until c2s terminated is called ----> on c2s terminated -->  Queue is being flushed to DB  --------> Db write finished .
                                     |
                                     |
                                     |                                       messages now written to new queue --> sent to peer.                            
                                     |                                             /|\
                                     \|/                                            |
                                  Peer comes  online --> new queue is created -->  resend hook is called --> gets only                              committed message from db --> sends to peer 
 due to this the messages that were not committed as db write in progress stay in db until user re-connects..
Also the order of message is getting disturbed .. 
Not sure if  i am exaggerating the problem or may be you faced it but just trying to write a good code...

**Comment by zinid** [comment]
OK, this 'crap' is used in a single place: [mod_muc](https://github.com/processone/ejabberd/blob/master/src/mod_muc.erl#L117). I won't remove it so far. Anyway, this is irrelevant for mod_offline as long as you didn't customize your code to have a pool of workers, in which case you indeed can return `{wait, WorkerPids}` in `mod_offline:stop/1` callback.
I will increase the supervisor timeout anyway.

**Comment by zinid** [comment]
For the record, `mod_offline` is not a gen_server anymore.
