### ISSUE TITLE
User session not found - error code 503.Offline message.

### ISSUE THREAD

**Issue by smilexcasper** [processone/ejabberd#1727]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

installer

When I write messages to a user who is offline - without sending it - I get an error:
`Your message was not send because of an error`
![error](https://cloud.githubusercontent.com/assets/10852358/26057812/d1c8df12-3983-11e7-8360-4152b39759de.png)
response:
`http-bind/<body xmlns='http://jabber.org/protocol/httpbind'><message xml:lang='en' to='abogdanov@bingo-dev.ru/181473147433257603378' from='jabberadmin@bingo-dev.ru' type='error' xmlns='jabber:client'><paused xmlns='http://jabber.org/protocol/chatstates'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>User session not found</text></error></message></body>`

**Comment by zinid** [comment]
Is `mod_offline` enabled?

**Comment by smilexcasper** [comment]
Sure:
shaper_rules: 
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100

modules:
mod_offline:   
    access_max_user_messages: max_user_offline_messages

**Comment by smilexcasper** [comment]
If you ignore the error and send messages, it will go

**Comment by smilexcasper** [comment]
If you ignore the error and send messages, it will go.
<message xml:lang='en'
         to='user@domen.ru'
         from='jabberadmin@domen.ru/320098345600142698834'
         type='chat'
         id='1494848103615:msg'
         xmlns='jabber:client'>
  <request xmlns='urn:xmpp:receipts'/>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
  <body>sadasd</body>
</message>

**Comment by Ri0n** [comment]
That happened for one of Psi users. It seems they used ejabberd 16.x. and probably it's somehow related if  client supports stream management or not. When stream management is enabled then offline messages stop working.

So the algo.
Have two users and ejabberd 16.x. One of users certainly uses stream management, the other may be not (I have no details on this)
One user goes offline
Second users send a mesage
Server responds with error instead of putting the message to offline storage.

**Comment by zinid** [comment]
So what's the problem here? Receipts are not put into offline storage, so the error is returned. I think a client should handle that correctly.

**Comment by Ri0n** [comment]
yes. but why not put when offline storage is enabled.
I honestly don't know all the details and that перец has leaved our conference long ago and nobody yet complained.
But I saw something similar once though. On jabber.ru for both sides. the contact seemed to be online but probably his connection was disrupted some unusual way.  I sent him a couple messages and got something like this back (I don't remember exact error message text though). I don't know if the messages were put to offile storage or not, I just resent them to anoher his connected resource.

**Comment by zinid** [comment]
You can always set `store_empty_body: true` for `mod_offline`.

**Comment by zinid** [comment]
Another possibility is using [hints](https://xmpp.org/extensions/xep-0334.html).

**Comment by renzhongyiyan** [comment]
My program worked fine at first, and the same problem occured later. My problem is that the offline message capacity exceeds the preset value in my openfire server. I check my openfire server,and in "Server Settings" I find an item called "offline messaging policy",I expanded the offline message storage capacity of single user. Then the app works fine.

**Comment by laszlovl** [comment]
Even with the no-store hint, Ejabberd will return an error:

```xml
<message xml:lang="en" type="error" xmlns="jabber:client">
<active xmlns="http://jabber.org/protocol/chatstates"/>
<no-store xmlns="urn:xmpp:hints"/>
<no-permanent-store xmlns="urn:xmpp:hints"/>
<error code="503" type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">User session not found</text></error>
</message>
```

Is this expected behavior?

**Comment by zinid** [comment]
@laszlovl yes. The client should be prepared to receive such errors.
