### ISSUE TITLE
New configure no long support CFLAGS , LDFLAGS in enviroment?

### ISSUE THREAD

**Issue by HeroPD** [processone/ejabberd#1728]
> What version of ejabberd are you using?

master branch

> What operating system (version) are you using?

OSX

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by HeroPD** [comment]
seems only work in configure
`./configure CFLAGS="-I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/openssl/lib"`

**Comment by badlop** [comment]
Umm, how to reproduce your problem? I try in linux and seems to work:
```
$ export CFLAGS="asdasd"
$ ./configure
...
$ make
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
checking for gcc... cc
checking whether the C compiler works... no
configure: error: in `/f/jabber/p1/git/ejabberd/deps/fast_tls':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: Command [compile] failed!
Makefile:93: recipe for target 'src' failed
make: *** [src] Error 1

$ grep asdasd config.log
ac_cv_env_CFLAGS_value=asdasd
CFLAGS='asdasd'
```

**Comment by HeroPD** [comment]
`export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/lib -L/usr/local/opt/expat/lib"
export CFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include"
export CPPFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include"
`
exporting these flag takes no effect on OSX Sierra

**Comment by HeroPD** [comment]
i am succesfully compiled with 
`cd deps/fast_tls`
`sudo ./configure LDFLAGS="-L/usr/local/opt/openssl/lib" CFLAGS="-I/usr/local/opt/openssl/include" CPPFLAGS="-I/usr/local/opt/openssl/include"`
it seems ejabberd make not hadling fast tls configure

**Comment by cromain** [comment]
can not reproduce on sierra
```
export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/lib -L/usr/local/opt/expat/lib"
export CFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include"
export CPPFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include"
./autogen.sh
./configure && make
otool -L deps/fast_tls/priv/lib/fast_tls.so
deps/fast_tls/priv/lib/fast_tls.so:
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```
