### ISSUE TITLE
Enhancement for c2s terminated

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1729]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

Current when the  ejabberd is stopped the c2s terminated reason comes as normal.
can we have c2s treminated reason as shutdown ?  i think only cast message needs to be changed in xmpp_stream_in and add new func called shutdown like we have stop in c2s ?

**Comment by zinid** [comment]
So we will end up with `close`, `stop` and `shutdown`?
A year after you will not even recall what all this means.

**Comment by nOmi7** [comment]
:) i think adding one for session close should be ok if not globally ... i tried it works like charm and useful for when heading for customizations.  checkout this pull req if its good.

**Comment by zinid** [comment]
The discussion is moved in #1730
