### ISSUE TITLE
File transfer - no Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by smilexcasper** [processone/ejabberd#1732]
What version of ejabberd are you using?
17.04
What operating system (version) are you using?
Centos 7
How did you install ejabberd (source, package, distribution)?
installer

Do you see any errors in your javascript console?
 

> XMLHttpRequest cannot load https://192.168.1.200:5443/upload/5627c20b7457729e75b7a9bebf297dfa7d641042/DEcAUCpmlfBGDjuaHvQzlvHhSff43JjNPy4ugJHD/chat.txt. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.200' is therefore not allowed access.

Config:
port: 5443
    module: ejabberd_http
    tls: true
    certfile: 'CERTFILE'
    request_handlers:     
      "": mod_http_upload     

  mod_http_upload:
    docroot: "/var/www"
    put_url: "https://192.168.1.200:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"

**Comment by smilexcasper** [comment]
Error: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by weiss** [comment]
Sounds like you need to also configure an [Access-Control-Allow-Headers][1] line.

[1]: https://www.w3.org/TR/cors/#access-control-allow-headers-response-header

**Comment by smilexcasper** [comment]
It's work.
I add  "Access-Control-Allow-Headers": "Content-Type"

**Comment by zinid** [comment]
I close the issue then
