### ISSUE TITLE
Undesired update of contrib modules

### ISSUE THREAD

**Issue by joelhess** [processone/ejabberd#1734]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?
Debian:jessie

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We're using the ejabberd_auth_http module from the contrib repo. It appears that when ejabberd starts up, it tries to grab the latest copies of the contrib modules. This resulted in an incompatibility where the `is_user_exists` function was renamed to `user_exists`

now my logs are getting this: 

`2017-05-17 19:27:08.306 [error] <0.1238.0>@ejabberd_sm:route:128 {undef,[{ejabberd_auth_http,is_user_exists,[<<"6193f5af-7032-47c9-81c2-9db25603fb59">>,<<"barg.com">>],[]},{ejabberd_auth,'-is_user_exists/2-fun-2-',3,[{file,"src/ejabberd_auth.erl"},{line,314}]},{lists,any,2,[{file,"lists.erl"},{line,1223}]},{ejabberd_sm,route_message,4,[{file,"src/ejabberd_sm.erl"},{line,598}]},{ejabberd_sm,route,3,[{file,"src/ejabberd_sm.erl"},{line,126}]},{ejabberd_local,route,3,[{file,"src/ejabberd_local.erl"},{line,110}]},{ejabberd_router,route,3,[{file,"src/ejabberd_router.erl"},{line,87}]},{mod_multicast,'-perform/5-lc$^0/1-0-',5,[{file,"src/mod_multicast.erl"},{line,357}]}]}
`

I need to be able to pin the contrib modules to a given revision, or include a specific copy of them with the deployment.

**Comment by badlop** [comment]
Looking at the source code, ext_mod update and upgrade are only called using ejabberdctl commands, not automatically in any other case. That would be weird, and it also surprises me.

Can you confirm the behavior you have mentioned? I mean, get manually an older git version (good for you), then start ejabberd... Does it update contrib again immediately, with you doing anything?

Of course there are tricks so you ensure ejabberd uses the module file you want, but first let's check that auto-update behavior you have seen...

**Comment by joelhess** [comment]
We're using ejabberd via Docker, and it turns out it was one of the "post" scripts that came out of the box updated it. 

https://github.com/processone/ejabberd/blob/master/docker/scripts/post/10_ejabberd_modules_update_specs.sh

I think I've been able to work around it by pulling the code rev prior to the change to the function name, including that source directly into my image and disabling the auto update.
