### ISSUE TITLE
how to rebuild or reinstall ejabberd after pull latest update from repository? 

### ISSUE THREAD

**Issue by kaalees** [processone/ejabberd#1735]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

Ubuntu 16.04 xenial

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I already installed ejabberd from source code and everything configured but I pulled latest update from repository so I need to reinstall or rebuild without deleting anything is this possible?

**Comment by badlop** [comment]
Just repeat the procedure you did before. In my case I do:
```
git pull
./configure 
make
sudo make install
... Then stop and start ejabberd
```
Then read the ejabberd log files. When ejabberd starts, it checks the configuration, and may report some problem if configuration changes. At start it also checks if the mnesia tables require some schema change, and does it automatically. Regarding SQL tables, it's your task to read ejabberd release notes and update the SQL database if required.

**Comment by kaalees** [comment]
Thanks for your reply!
