### ISSUE TITLE
XEP-0355 - mod_delegation is forwarding component messages back to the component

### ISSUE THREAD

**Issue by designtesbrot** [processone/ejabberd#1737]
> What version of ejabberd are you using?

17.04 and latest master

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Given:** Ejabberd is configured using mod_delegation to forward the `jabber:iq:roster` namespace to a component. The component has write access to the roster using privileged entity. 

**Expected:** When the component makes use of that (sending iq#type=set,xmlns=jabber:iq:roster) it should be able to set the roster of any user.

**Is:** mod_delegation actually prohibits processing the stanza and instead forwards it back to the component.

The spec (https://xmpp.org/extensions/xep-0355.html - 4.3.1 Stanzas from managing entity) says:

> If a stanza is sent by the managing entity on a managed namespace, the server MUST NOT forward it. This way, the managing entity can use privileged entity to do specific treatments, a kind of universal plugin (i.e. working with all servers implementing Namespace Delegation (XEP-0355) [4] and Privileged Entity (XEP-0356) [3]).

The current implementation fails for the specs example Use-Case  at step 10, since the set-iq is not processed but rather forwarded back to the component. Example from my tests:

The external component `roster.xmpp.example.org` is authenticated and connected to `xmpp.example.org`. Using privileged entity it has write access to the roster. Using namespace delegation `jabber:iq:roster` requests are delegated to the component. Now component sets the roster of `foo@xmpp.example.org`:

```
 IQ {
  name: 'iq',
  parent: null,
  children:
   [ ... ],
  attrs:
   { to: 'foo@xmpp.example.org',
     from: 'roster.xmpp.example.org',
     type: 'set',
     id: 'roster1' } }
```

And Ejabberd responds with:

```
<iq to="roster.xmpp.example.org" from="xmpp.example.org" type="set" id="roster2" xmlns:stream="http://etherx.jabber.org/streams"><delegation xmlns="urn:xmpp:delegation:1"><forwarded xmlns="urn:xmpp:forward:0"><iq to="fof@xmpp.example.org" from="roster.xmpp.example.org" type="set" id="roster1" xmlns="jabber:client"><query xmlns="jabber:iq:roster"> ... </query></iq></forwarded></delegation></iq>
```
But it should respond with iq#type=result

**Comment by designtesbrot** [comment]
While debugging this issue I was able to gain the following insight:
(disclaimer / I'm neither familiar with ejabberd nor erlang)

`mod_delegation` uses `gen_iq_handler:add_iq_handler/6` to register itself for the configured  namespace. It will then receive the iqs and intercept the flow by wrapping the IQ in the `<delegation><forwarded>…</delegation></forward>` structure as defined in XEP-0355:

*src/mod_delegation.erl::231*
```
-spec process_iq(iq(), ejabberd_local | ejabberd_sm) -> ignore | iq().
process_iq(#iq{to = To, lang = Lang, sub_els = [SubEl]} = IQ, Type) ->
    LServer = To#jid.lserver,
    NS = xmpp:get_ns(SubEl),
    Delegations = get_delegations(LServer),
    case dict:find({NS, Type}, Delegations) of
	{ok, {Host, _}} ->
	    Delegation = #delegation{
			    forwarded = #forwarded{xml_els = [xmpp:encode(IQ)]}},
	    NewFrom = jid:make(LServer),
	    NewTo = jid:make(Host),
	    ejabberd_local:route_iq(
	      #iq{type = set,
		  from = NewFrom,
		  to = NewTo,
		  sub_els = [Delegation]},
	      fun(Result) -> process_iq_result(IQ, Result) end),
	    ignore;
	error ->
	    Txt = <<"Failed to map delegated namespace to external component">>,
	    xmpp:make_error(IQ, xmpp:err_internal_server_error(Txt, Lang))
    end.

```

It feels like here it should be checked if `From === NewTo`. And if so, the delegation should not happen. For testing purposes I changed it to:

```
-spec process_iq(iq(), ejabberd_local | ejabberd_sm) -> ignore | iq().
process_iq(#iq{to = To, from = From, lang = Lang, sub_els = [SubEl]} = IQ, Type) ->
    LServer = To#jid.lserver,
    NS = xmpp:get_ns(SubEl),
    Delegations = get_delegations(LServer),
    #jid{luser = FromUser, lresource = FromResource} = From,

    case dict:find({NS, Type}, Delegations) of
    {ok, {Host, _}} when FromUser == <<>>, FromResource == <<>> ->
        IQ;
	{ok, {Host, _}} ->
        ...

```

The result is that ejabberd is looping. The Iq is being routed to mod_delegate over and over again. At this I point it feels like when mod_delegate is adding the handler for the `jabber:iq:roster` namespace, it actually is completely occupying it.
mod_roster is probably not receiving any iqs anymore at all... 

@zinid git tells me that you are the other (thanks for this contribution by the way!). Do you have any ideas on how to approach this issue? I might have some time to give a solution a shot but I currently do not see a feasible approach ...

**Comment by zinid** [comment]
I'm not the author, the author is a GSoC student, so probably no chance this issue will be supported.

**Comment by alexeyshch** [comment]
Unfortunately you can't currently handle one namespace with more than one module, so using both mod_delegation and mod_roster for jabber:iq:roster won't work.

**Comment by designtesbrot** [comment]
Thanks a lot for your answers. I can see that the underlying problem is burried deeper in ejabberd and its probably not worth tackeling that depency for the sake of this issue. I would anyways suggest to label this issue as a bug and keep it open, since it is a violation of the XEP-0355 spec. The issue should probably revisited in case the 1-to-1 relationship between namespaces on modules would be lifted at some point in the future.

**Comment by zinid** [comment]
I don't think this is an issue. Because I think the XEP is not designed to manage already managed namespaces.
Also, there is no such thing as "violating" an experimental XEP. The XEP (from my knowledge) didn't gain any attention at all in the XSF discussion list and easily can be changed depending on implementers feedback.
