### ISSUE TITLE
is it possible to update module spec from any github repo?

### ISSUE THREAD

**Issue by HeroPD** [processone/ejabberd#1738]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

OSX

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by badlop** [comment]
No, the repository is specified in ext_mod.erl, not configurable

**Comment by cromain** [comment]
ext_mod handles ejabberd-contrib repos.
but you can add your repository using add_sources/2

ext_mod:add_sources(my_mod, "https://github.com/me/my_mod").
