### ISSUE TITLE
ERROR: The ejabberd node 'ejabberd@localhost' is already running in Windows 8

### ISSUE THREAD

**Issue by nitin19** [processone/ejabberd#1739]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Windows 8

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by badlop** [comment]
Maybe the windows installer starts ejabberd itself, so it is already started when you go to start it.

**Comment by cromain** [comment]
without logs and more informations, we can not go further...
you did compiled ejabberd yourself ? i don't think installer has any relation to your error.

**Comment by caneloolivo** [comment]
I have the same error, and the installer was used

**Comment by cromain** [comment]
then this occurs you must:
1/ make sure ejabberd is stopped (check service status, you can also force stop from ejabberd menu)
2/ open the task manager, and keep epmd.exe process if it's still running.

**Comment by caneloolivo** [comment]
Already was did it, if I star ejabberd manually, in empd.exe, doesn't allow remote connection, and if I start with ejabberdctld in cmd says is already run, or says same error, I checked the .cfg file, and it came with Linux path for some propierties
