### ISSUE TITLE
mod_http_upload to aws s3

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1741]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?
Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

In my currently ejabberd.yml config file, I have done the mod_http_upload and mod_http_fileserver to work with media transfer but it is currently on localhost.

How can i go about to configure to allow the media to be store on aws s3 bucket?  How can this be achieve inside the "ejabberd.yml" config file?  Any advice?

Thank you.

**Comment by Immakittycat** [comment]
Hi !
I'm currently working on the same modules, trying to make my media transfer to work properly.
May you send your ejabberd.yml file so I can test it on my side ?

Thanks !

**Comment by weiss** [comment]
> How can i go about to configure to allow the media to be store on aws s3 bucket?

`mod_http_upload` has no built-in support for remote storage, but it can delegate the HTTP communication to an external component that you could build to store things wherever you like.  See the `service_url` description in the [`mod_http_upload` documentation][1] and the [django-xmpp-http-upload][2] project as an example.

[1]: https://docs.ejabberd.im/admin/configuration/#mod-http-upload
[2]: https://github.com/mathiasertl/django-xmpp-http-upload
