### ISSUE TITLE
Flush/remove anons in muc?

### ISSUE THREAD

**Issue by paradisaeidae** [processone/ejabberd#1742]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Linux

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have enabled mod_muc, mod_muc_admin and have anonymous users of a muc room.
Even when the anon id is 'flushed' by a disconnect, the presence in the muc persists.
I have attempted to remove the anonID from the room using various techniques:
```
set_room_affiliation 123123123123.... none
set_room_affiliation 123123123123.... outcast
```
and various attempts using muc_unregister_nick

I suspect these are not working as the anonID is not really a regular registered jabberID?
So 'regular' commands will not touch them.
Is this expected/correct behaviour?

I notice the anonID becomes a 'resource' of the room.
So I attempted a muc_unregister_nick with that format, nope.
There may be an issue when the room is opened by an anonID, thus becomes owner, cannot be removed?

Thanks for ejabberd!
Cya, MarkT

**Comment by badlop** [comment]
> Even when the anon id is 'flushed' by a disconnect, the presence in the muc persists.

I tried a setup similar to yours, and when an anonymous user disconnects, his presence from the room gets removed. Of course, that happens if the user disconnection get noticed by ejabberd. If the disconnection is done in some way that the XMPP session isn't closed, or the TCP connection isn't closed, then weird things may happen.

The affiliation command does not work, because affiliations are long-term relationships with the room; what you want to set is Role to 'none', but such a command does not exist.

Check how does your client close the XMPP session. Also, you may want to enable mod_ping.

**Comment by paradisaeidae** [comment]
Thanks, will explore further soon.Connections are web-strophe.Closing a tab can be caught with a hook.But has an annoying dialog effect.This may have been bypassed in testing.The ping thing was disabled due to being noisy in debug.Some clients return not available though ejd keeps trying.                                                                                                                                                                                                                                                                                                                                         Good clues!-- MarkT                                                                                                                                                                                                                From: badlopSent: Wednesday, 24 May 2017 21:02To: processone/ejabberdReply To: processone/ejabberdCc: MarkT; AuthorSubject: Re: [processone/ejabberd] Flush/remove anons in muc? (#1742)
Even when the anon id is 'flushed' by a disconnect, the presence in the muc persists.

I tried a setup similar to yours, and when an anonymous user disconnects, his presence from the room gets removed. Of course, that happens if the user disconnection get noticed by ejabberd. If the disconnection is done in some way that the XMPP session isn't closed, or the TCP connection isn't closed, then weird things may happen.
The affiliation command does not work, because affiliations are long-term relationships with the room; what you want to set is Role to 'none', but such a command does not exist.
Check how does your client close the XMPP session. Also, you may want to enable mod_ping.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/processone/ejabberd","title":"processone/ejabberd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/processone/ejabberd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@badlop in #1742: \u003e Even when the anon id is 'flushed' by a disconnect, the presence in the muc persists.\r\n\r\nI tried a setup similar to yours, and when an anonymous user disconnects, his presence from the room gets removed. Of course, that happens if the user disconnection get noticed by ejabberd. If the disconnection is done in some way that the XMPP session isn't closed, or the TCP connection isn't closed, then weird things may happen.\r\n\r\nThe affiliation command does not work, because affiliations are long-term relationships with the room; what you want to set is Role to 'none', but such a command does not exist.\r\n\r\nCheck how does your client close the XMPP session. Also, you may want to enable mod_ping. "}],"action":{"name":"View Issue","url":"https://github.com/processone/ejabberd/issues/1742#issuecomment-303691773"}}}
