### ISSUE TITLE
[error] emulator Discarding message ... in an old incarnation (2) of this node (3)

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#1743]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?
CentOS 7

> How did you install ejabberd (source, package, distribution)?
package => ejabberd-17.01-0.x86_64.rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have a two node cluster.
When a node has been stopped and restarted, Ejabberd starts to discard messages.
[error] emulator Discarding message ... in an old incarnation (2) of this node (3)

Could you give me some advice?

**Comment by zinid** [comment]
What database backends are you using for disc and ram?

**Comment by Emilio-Gonzalez** [comment]
Mnesia

**Comment by Emilio-Gonzalez** [comment]
How can I change permanently the storage type for **pubsub_node**?

When I change it to _ram_copy_ it works fine.
But If the node stops and restarts, the value returns to _disc and ram copy_.

I'm changing it at the Ejabberd admin webpage.

**Comment by zinid** [comment]
You can do that in the upcoming release (17.06) via simple Mnesia configuration schema, it will be documented.

**Comment by Emilio-Gonzalez** [comment]
Hi!

Could you tell me where to find the documentation for this issue?

Thanks in advance.
Emilio.

2017-06-06 12:18 GMT+02:00 Evgeny Khramtsov <notifications@github.com>:
