### ISSUE TITLE
Undefined contact in Services group

### ISSUE THREAD

**Issue by damaga** [processone/ejabberd#1744]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian 8.8

> How did you install ejabberd (source, package, distribution)?

binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After updating from 13.09, some users (two with admin privileges and one regular user) got their  [self-contact](http://imgur.com/a/8cLUd) in the "Services" group. After deleting this contact, the account on the server is also deleted without confirmation. Earlier, when you tried to upgrade to 16.04, this contact appeared for all users. This contact is not present in the database, nor is it in the admin web interface.

Do you need any additional information? I can not find anything suspicious in the logs.

**Comment by zinid** [comment]
See https://github.com/psi-plus/main/issues/671
