### ISSUE TITLE
Encoding messages in ejabberd

### ISSUE THREAD

**Issue by iitrsachin** [processone/ejabberd#1745]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi guys,

I have to migrate some data from ajax based chat to ejabberd so need to encode messages in right format before migration.

How ejabberd encodes messages before saving in xml field of archive table. I just checked the mod_mam module code the got El = xmpp:encode(NewPkt) line to enode messages but not get exact encoding method.

Please help me out.

**Comment by zinid** [comment]
After `xmpp:encode/1` the result is serialized into raw XML data via `fxml:element_to_binary/1`.

**Comment by zinid** [comment]
If you're asking about the encoding rules, they are described here: https://github.com/processone/xmpp

**Comment by iitrsachin** [comment]
Thank you Zinid for a reply.

I am sending the following message using pidgin
$ # @ ! ` ^ & * ( ) -{{}'";:.>/?<,\|`~

In the archive table, this message is storing like 
username: user2
 timestamp: 1495648500497693
      peer: user1@localhost/*
 bare_peer: user1@localhost
       xml: <message to='user2@localhost/Gajim' from='user1@localhost/*' type='chat' id='purplefcdc5f31' xmlns='jabber:client'><active xmlns='http://jabber.org/protocol/chatstates'/><body>$ # @ ! ` ^ &amp; * ( ) -{{}&apos;&quot;;:.&gt;/?&lt;,\|`~</body></message>
       txt: $ # @ ! ` ^ & * ( ) -{{}'";:.>/?<,\|`~
        id: 10
      kind: chat
      nick: 

So txt field has exact message but xml field has encoded message in body tag.

@zinid : here my question is - I have a source database with $ # @ ! ` ^ & * ( ) -{{}'";:.>/?<,\|`~
 value. I have written a Java program to migrate messages from source database to Ejabberd so I can not use any Erlang and xmpp library to encode messages.

Is there any direct method to encode messages in body tag like url encode?

**Comment by zinid** [comment]
I bet Java has XML serializers, just use them. You should construct `<message/>` XML element, serialize it into a string and write to `xml` field. The serializer will escape everything as needed.

**Comment by iitrsachin** [comment]
Okay Thanks @zinid

**Comment by iitrsachin** [comment]
@zinid : I have implemented the xml escape logic and it's working fine for all characters except Emoji.
Emoji are not storing in right way and they are storing like &#55357;&#56890; after migration. 
When I send the same Emoji from the app then it is not storing in encoding format. I think encoding logic is different for different types of characters.
Should I read the code of https://github.com/processone/fast_xml repository?
If you have an idea about this please help.
