### ISSUE TITLE
message interception and filtering

### ISSUE THREAD

**Issue by milospajic** [processone/ejabberd#1747]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 16.04.1 LTS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I saw it's possible to use external script (ie java program) for authentication. Is it possible to do the same for interception and filtering of the message stanzas?
What I want to do is to change the content of the message that meets some regular expression condition. 
I've saw mod_pottymouth, but it doesn't do exactly that and learning Erlang to do only this feels like overhead.

**Comment by badlop** [comment]
I see no module to do that, neither in the contributed modules.
