### ISSUE TITLE
MUC & Rest Api Issue

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1748]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 6.5

> How did you install ejabberd (source, package, distribution)?

Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

**Scenario 1**
I am using adium xmpp client to create a muc room and on the mysql database I can see under table "muc_room" has the muc room that I created.  But when I do the similar using REST API it can also create the muc room but when I check over at the mysql table, the muc room does not exist.  On my ejabberd.yml config I have set the room option to be persistent but the REST Api does not seem to be able to pick up the room as persistent.  How can this be resolve?

Thanks.

**Comment by badlop** [comment]
I configure like this:
```yaml
modules:
  mod_muc:
    default_room_options:
      persistent: true
```
Then I call the command in the shell, and confirm it didn't return error:
```
$ ejabberdctl create_room room4 conference.localhost localhost
$ echo $?
0
```
Then the room can be seen in the list of rooms with any Jabber client, and also in the mnesia table with an erlang shell:
```
> ets:tab2list(muc_room).
[{muc_room,{<<"room2">>,<<"conference.localhost">>},[]},
 {muc_room,{<<"room4">>,<<"conference.localhost">>},
           [{persistent,true}]}]
```

**Comment by molochmike** [comment]
Hi @badlop 

i will give it a try first and then update again.  Thanks a lot.

**Comment by molochmike** [comment]
Hi @badlop 

i have done the settings as per say.

I run rest api to create muc room, it can gets into the mysql.  But then when i use rest api to call command send message to the muc room, there is no archive going into the mysql.

**Comment by badlop** [comment]
So, the original problem you reported in this ticket is now solved? How was it solved?

Regarding the new problem that you are now reporting:
* Is archiving enabled in the muc room? otherwise, messages aren't archived
* Is the message actually delivered to the room? In my tests, I need to provide as sender an account with a client already connected, otherwise the message isn't delivered, example:

> ejabberdctl send_message groupchat user1@localhost room1@conference.localhost "" HiAll

**Comment by molochmike** [comment]
Hi @badlop 

Yes, message archiving is enabled in the muc room.  But when i test using rest api "send_message" no message is archived to the mysql db.

Message i assume has been delivered and logs generated rest api call to send message to the muc room but when i refresh mysql db through phpmyadmin, nothing was captured.

For one to one user no problem message can archive, but for muc now we face problem.

**Comment by badlop** [comment]
Confirm that the message is actually received by clients in the room: join the room yourself, then send a message with that command.

If you join the room and send a message to it, is that message archived?

**Comment by molochmike** [comment]
Hi @badlop 

Confirm that when i joined the room message is not archived, even when i re-create new room and i joined in also message is not archived.  It applies the same now eventhough i run on backend mnesia DB as previously it was on MySQL db.

I've done clean remove and re-install ejabberd but nothing seems to rework again.  Me and the team is really stuck now unsure of what to do next.

**Comment by SabrinaMadX** [comment]
hi, @badlop. I'm the developer working with mike on this issue. the problem we're facing is that MUC rooms created via the REST api doesn't get saved into the mysql database. In the event that the server gets restarted, these rooms created via rest API are deleted even though they were declared persistent. By the same token, any groupchat messages sent to these rooms are not archived. 

When we tried using Adium, though, the MUC rooms created were added to the mysql db. Messages sent to these MUCRs were also archived. So we're wondering if there's a solution to this? There were no errors except when we subscribed, where the framework probably couldn't find the MUCR entry in the mysql and threw a write error.

**Comment by badlop** [comment]
I have ejabberd git, almost 17.06-beta that will be released in the next days. I configure like this:
```
modules:
  mod_mam:
    db_type: sql
    default: always
  mod_muc:
    db_type: sql
    default_room_options:
      persistent: true
      mam: true
```

Then run this:
> $ ejabberdctl create_room sala6 conference.localhost localhost

And the room is created and stored in the muc_room SQL table.

> $ ejabberdctl send_message groupchat user1@localhost sala6@conference.localhost "" HiAll

And the message is archived in the archive SQL table.

**Comment by molochmike** [comment]
Hi @badlop 
Thanks for the great news on 17.06.  I hope more features and improvement we can get from the stable release coming soon.  Also thanks for the examples shown on muc setup configuration.

My current setup.  Loglevel i have set back to level 4.  My MUC setup as below.

mod_mam:
     default: always
     request_activates_archiving: false
     assume_mam_usage: false
     cache_size: 1000
     cache_life_time: 3600

mod_muc:
     host: "conference.@HOST@"
     access:
          - allow
     access_admin:
          - allow: admin
     access_create: muc_create
     access_persistent: muc_create
     default_room_options:
          allow_change_subj: true
          allow_private_messages: true
          allow_private_messages_visitors: nobody
          allow_query_users: true
          allow_user_invites: true
          allow_visitor_nickchange: false
          allow_visitor_status: true
          allow_subscription: true
          anonymous: true
          captcha_protected: false
          logging: true
          mam: true
          members_by_default: true
          members_only: true
          moderated: true
          password_protected: false
          persistent: true
          public: false
          public_list: false

Currently test using rest api, ejabberd command line and through xmpp frontend client message works, can be archived, muc_room on mysql db works, etc.  Currently monitoring on it and hope it works well continuously.

I post another question on restart ejabberd server so from now on any modification i have done I look at command "ejabberdctl reload_config".  Observe from log file tells me it is working on reload process.  Some modules that do not support reload_config will restart for that particular services instead of the whole server.
