### ISSUE TITLE
Ejabberd 17.04 xmlrpc using Java - '{error,access_rules_unauthorized}'

### ISSUE THREAD

**Issue by RahulRazdan** [processone/ejabberd#1749]
[ejabberd.zip](https://github.com/processone/ejabberd/files/1037505/ejabberd.zip)

> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Win 7

> How did you install ejabberd (source, package, distribution)?

windows installer 

> What did not work as expected? Are there error messages in the log? What

```
Exception in thread "main" org.apache.xmlrpc.XmlRpcException: Error -118
A problem '{error,access_rules_unauthorized}'
 occurred executing the command check_account with arguments
[{host,<<"DCSDC152">>},{user,<<"rahul@dcsdc152">>}]
```

> was the unexpected behavior? What was the expected result?

Attached my ejabberd.yml file

**From debug level log file**

```
2017-05-30 12:43:42.712 [debug] <0.443.0>@ejabberd_xmlrpc:process:246 got XML-RPC request:
 {call,check_account,[{struct,[{host,<<"DCSDC152">>},{user,<<"rahul@dcsdc152">>}]}]}
2017-05-30 12:43:42.712 [debug] <0.443.0>@ejabberd_xmlrpc:extract_auth:263 AUTHLIST
 [{host,<<"DCSDC152">>},{user,<<"rahul@dcsdc152">>}]
2017-05-30 12:43:42.712 [debug] <0.302.0>@ejabberd_access_permissions:handle_call:150
 Command 'check_account' execution denied (CallerInfo=#{caller_module => 
 ejabberd_xmlrpc,extra_permissions =>
 [{<<"ejabberd_xmlrpc compatibility shim">>,{[ejabberd_xmlrpc],[{access,xmlrpc}],
 [register,set_last,check_account,check_password,change_password,send_message,
 registered_users,unregister]}}],ip => {127,0,0,1}})
2017-05-30 12:43:42.712 [warning] <0.443.0>@ejabberd_xmlrpc:build_fault_response:422
 Error -118 A problem '{error,access_rules_unauthorized}'
 occurred executing the command check_account with arguments
 [{host,<<"DCSDC152">>},{user,<<"rahul@dcsdc152">>}]
```

**Comment by badlop** [comment]
First of all, remove all those misleading lines:
```yaml
commands_admin_access: configure
commands:
  - add_commands:
    - user

  - 
     port: 4560
     module: ejabberd_xmlrpc
     maxsessions: 10
     timeout: 5000
     admin:
      commands: all
      options: []
     access_commands:
      xmlrpc:
        commands:
          - register
          - set_last
          - check_account
          - check_password
          - change_password
          - send_message
          - registered_users
          - unregister

commands_admin_access: configure

access_rules:
  configure: 
    - allow: admin

acl:
  admin:
    user:
      - "rahul@dcsdc152"


acl:
  ##
  ## The 'admin' ACL grants administrative privileges to XMPP accounts.
  ## You can put here as many accounts as you want.
  ##
  admin:
    user:
      - "rahul@DCSDC152"

access:
  xmlrpc_access:
    admin: allow

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "0.0.0.0/8"
    what:
      - "*"
```

Then add in the proper places the barely minimum to get xmlrpc with access restrictions:
```yaml
  - 
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      xmlrpc_access:
        commands: all
        options: [] 

commands_admin_access: xmlrpc_access

acl:
  xmlrpc_acl:
    user:
      - "user1@localhost"

access_rules:
  xmlrpc_access:
    - allow: xmlrpc_acl
```

Then write a simple script like this (in my case, it is user1@localhost who can execute commands, and I provide his valid password):
```python
import xmlrpclib

server_url = 'http://127.0.0.1:4560'
server = xmlrpclib.ServerProxy(server_url)

EJABBERD_XMLRPC_LOGIN = {'user': 'user1', 'server': 'localhost', 'password': 'mypass11', 'admin': True}

def ejabberdctl(command, data):
    fn = getattr(server, command)
    return fn(EJABBERD_XMLRPC_LOGIN, data)

result = ejabberdctl('check_account', {'user':'user57', 'host':'localhost'})
print result
```
Then execute the script. In my case it returns 0, means success, the account exists:
```
$ python test.py 
{'res': 0}
```
Once you get this working, you can try to limit which commands the user can or cannot execute. But only try complex configurations when you have the simple one working correctly.

**Comment by RahulRazdan** [comment]
Hi ,

Thanks for the response.

I have updated the configuration.yml
[ejabberd.zip](https://github.com/processone/ejabberd/files/1041105/ejabberd.zip)

Please find attached.
My Java Code as below

`XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
		URL url = new URL("http://127.0.0.1:4560"); 
		  config.setServerURL(url);
		  config.setConnectionTimeout(0);
		  config.setReplyTimeout(0);
		  config.setBasicUserName("rahul@DCSDC152");
	      config.setBasicPassword("rahul");
		    
		  XmlRpcClient client = new XmlRpcClient();
		  client.setConfig(config);

		  Map<String, Object> struct1 = new HashMap<String, Object>();
		  
		  struct1.put("user", "rahul@DCSDC152");
		  struct1.put("host", "DCSDC152");
		  //struct1.put("oauth","Bearer QMeEV78fCBvXJQ0ukKtQ9pXo0sL00sdp");
			
		  Object[] params = new Object[]{struct1};
		  
		  HashMap<Object, Object> hashMap = (HashMap<Object, Object>) client.execute("check_account", params);`

I'm still getting same error :
`@ejabberd_xmlrpc:process:246 got XML-RPC request: {call,check_account,[{struct,[{host,<<"DCSDC152">>},{user,<<"rahul@DCSDC152">>}]}]}
2017-05-31 16:07:15.807 [debug] <0.465.0>@ejabberd_xmlrpc:extract_auth:263 AUTHLIST [{host,<<"DCSDC152">>},{user,<<"rahul@DCSDC152">>}]
2017-05-31 16:07:15.807 [debug] <0.307.0>@ejabberd_access_permissions:handle_call:150 Command 'check_account' execution denied (CallerInfo=#{caller_module => ejabberd_xmlrpc,extra_permissions => [{<<"ejabberd_xmlrpc compatibility shim">>,{[ejabberd_xmlrpc],[{access,xmlrpc_access}],all}}],ip => {127,0,0,1}})
2017-05-31 16:07:15.807 [warning] <0.465.0>@ejabberd_xmlrpc:build_fault_response:422 Error -118
A problem '{error,access_rules_unauthorized}' occurred executing the command check_account with arguments
[{host,<<"DCSDC152">>},{user,<<"rahul@DCSDC152">>}]`

**Comment by badlop** [comment]
First of all, one recommendation: use lowercase servers and usernames in the configuration.

Second: use my example python client, that I provided for you test. If you can't use it, at least READ it, apparently you didn't take any care about it. See the arguments it provides, you are missing several ones (the struct with a user, server, password and admin:true of an account with permission to execute the command), and other arguments you are providing wrong (username must be a user name, not the account jid).

This is what I get executing my script, compare it toyour log lines:
```
09:56:47.169 [debug] got XML-RPC request:
 {call,check_account,[{struct,[{admin,true},{password,<<"mypass11">>},
 {user,<<"user1">>},{server,<<"localhost">>}]},
 {struct,[{host,<<"localhost">>},{user,<<"user2">>}]}]}
09:56:47.169 [debug] AUTHLIST [{admin,true},{password,<<"mypass11">>},
 {user,<<"user1">>},{server,<<"localhost">>}]
09:56:47.179 [debug] Command 'check_account' execution allowed by rule
 'ejabberd_xmlrpc compatibility shim' (CallerInfo=#{caller_module
 => ejabberd_xmlrpc,caller_server => <<"localhost">>,extra_permissions
 => [{<<"ejabberd_xmlrpc compatibility shim">>,
 {[ejabberd_xmlrpc],[{access,xmlrpc_access}],all}}],ip => {127,0,0,1},
 usr => {<<"user1">>,<<"localhost">>,<<>>}})
09:56:47.179 [debug] Executing command ejabberd_auth:user_exists
 with Args=[<<"user2">>,<<"localhost">>]
```
