### ISSUE TITLE
Delayed Delivery after SM or CSI should come from account

### ISSUE THREAD

**Issue by iNPUTmice** [processone/ejabberd#1750]
> What version of ejabberd are you using?

16.09 - sorry for the old version but I don't think this has changed recently

> What operating system (version) are you using?

Linux

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The CSI module (and I guess the SM module as well - I haven't checked that TBH) add a delayed delivery where from=domain. However that gets us into trouble for reasons described on the [mailing list](https://mail.jabber.org/pipermail/standards/2017-May/032773.html).
If the delayed delivery would come from the accounts bare jid we could avoid a lot of those problems while facing no downsides (That I can see).

**Comment by zinid** [comment]
Is it only related to CSI and SM? What about offline messages?

**Comment by iNPUTmice** [comment]
Hi @zinid 
Sorry I was expecting my mailing list post to be ignored by everyone (as usual) and was trying to back-channel a working solution. Now that the mailing list discussion got some traction maybe we can wait for it to be resolved.

But to answer your question; Following my logic it would make sense to use the users bare jid for offline messages as well. I was trying to less disruptive regarding existing code. (Offline messages exists for far longer than SM and CSI.)

**Comment by zinid** [comment]
Well, the patch is trivial (offline or not). If there is an agreement on the list, then I'm fine to fix it.

**Comment by cromain** [comment]
@zinid did you get consensus on this (then please apply patch) else move to 17.08 or close.

**Comment by weiss** [comment]
I don't think there's a consensus, so I would close this for the moment.
