### ISSUE TITLE
17.04 failed install - erl.exe crush

### ISSUE THREAD

**Issue by smilexcasper** [processone/ejabberd#1752]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?
Windows 2008 R2

> How did you install ejabberd (source, package, distribution)?
Windows 64bits Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I install the program, I get the error erl.exe
![err](https://cloud.githubusercontent.com/assets/10852358/26634134/4f61c3de-461e-11e7-8261-55d238d55d99.png)
![err2](https://cloud.githubusercontent.com/assets/10852358/26634142/54f9f08c-461e-11e7-8684-c304e7a09ce7.png)

I install ALL - Visual C++ Redistributable Packages for Visual Studio 20XX

**Comment by smilexcasper** [comment]
any help?

**Comment by cromain** [comment]
I can not reproduce the error. may you translate in english error messages returned by erl.exe ?
