### ISSUE TITLE
Packaged deb includes system libraries; causes version problems

### ISSUE THREAD

**Issue by MarcelWaldvogel** [processone/ejabberd#1756]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 16.04 LTS

> How did you install ejabberd (source, package, distribution)?

deb from ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

## Scenario 1: Startup error messages (irritating)

```bash
# /etc/init.d/ejabberd restart
Stopping ejabberd...
bash: /opt/ejabberd-17.04/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
bash: /opt/ejabberd-17.04/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
done.
Starting ejabberd...
bash: /opt/ejabberd-17.04/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
bash: /opt/ejabberd-17.04/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
bash: /opt/ejabberd-17.04/lib/linux-x86_64/libtinfo.so.5: no version information available (required by bash)
done.
```

The `libtinfo.so.5` messages should not be there (caused by `LD_LIBRARY_PATH` set to prefer the library shipped with ejabberd over the system libraries)

## Scenario 2: Python extauth modules cannot use SSL (bug)

When running a Python program as an extauth module, it cannot access pages over HTTPS. The reason seems to be a `libssl` incompatibility between ejabberd and the system libraries. (More info in jsxc/xmpp-cloud-auth@c42e7d7e68d8cc24c8cc4a35cffb3e32c8426aee; feel free to guess how many hours it took to track this bug down.)

## Scenario 3: SSL security update missed (security)

It seems that if a security problem is detected in e.g. `libssl`, only the system library will be updated, and ejabberd will continue to use the vulnerable version? (This raises the more general issue of pushing ejabberd security fixes to the users, which does not work well if all one can do is manually download a `.deb` file)

## Questions

1. Why are these libraries included?
1. Can they be used more selectively?
1. What can be done to avoid these problems? (Besides the partial, crude hack described in Scenario 2)

**Comment by cromain** [comment]
1. our .rpm/.deb are generated from our standard binary installer (using same content). Our installer must be generic enough to work on all possible linux distribution without any extra dependencies. That's why some libs are included. (e.g. if you install it on ArchLinux, it does not provide libtinfo, and beam depends on it)

2. we should be able to use system libs, and fallback to the included ones only if missing from host i guess.

3. doing 2/ would solve the glitch.

**Comment by MarcelWaldvogel** [comment]
In my case, I just renamed the `linux-x86_64` away. But probably a better solution (requires testing, of course), would be to include that path in the `DT_RUNPATH` section at link time, so other programs are not affected, after first mentioning the expected system library paths.

**Comment by cromain** [comment]
one "simple but dirty" solution is to let postinstall selectively remove the libs from lib/linux-x86_64 which are already provided by the host. but i'd prefer a cleaner solution.
I'm not sure about rpath. I think we'll keep all our included deps by default, and give option to disable them to use the host ones.

**Comment by cromain** [comment]
it seems best to use LD_FALLBACK_LIBRARY_PATH on unix or DYLD_FALLBACK_LIBRARY_PATH on osx.
so we link to our included library only if symbol could not be found on standard path.

**Comment by cromain** [comment]
The LD_FALLBACK_LIBRARY_PATH way is working fine, and it applied to our packaging.
This fix all issues listed here, and allow libssl update on system being using by ejabberd
