### ISSUE TITLE
Is batch messages route  possible in ejabberd 

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#1760]
> What version of ejabberd are you using?
16.2 Source code

> What operating system (version) are you using?
CentOs7

> How did you install ejabberd (source, package, distribution)?
source

Hi,
I have list of messages queued up, I just want to send all messages as batch in single route instead sending one by one ? right now i am iterating list and sending by `ejabberd_router:route/3` method.

Regards,
Veer

**Comment by badlop** [comment]
To send different stanzas to the same/different destinations, just iterate as you do. To send the same stanza to different destinations, you can use mod_multicast, see https://xmpp.org/extensions/xep-0033.html
