### ISSUE TITLE
Query mod_mam for distinct chats

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1761]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i need to query archive and get all distinct chats a user has done (i.e if a user 'A' has chatted with 'B,C,D,E".i wanted to fetch latest 10 messages with all these users B,C,D,E). is this possible with mod_mam. We have configured ODBC (mysql) for mod_mam
```
 mod_mam:
    default: always
    db_type: odbc
```

**Comment by zinid** [comment]
Everything is possible that's defined in [XEP-0313](https://xmpp.org/extensions/xep-0313.html) and [XEP-0059](https://xmpp.org/extensions/xep-0059.html).

**Comment by vijayaa** [comment]
But as per XEP-0313 **4.1.1 Filtering by JID**  takes only single jid

**Comment by zinid** [comment]
So you should make 4 queries.
