### ISSUE TITLE
Emoji are not migrating in proper way

### ISSUE THREAD

**Issue by iitrsachin** [processone/ejabberd#1763]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
source

Hi Team,
I migrated chat data from Ajax based chat to Ejabberd. All chats are migrated successfully except the chats having Emojis. When I am doing mam query then I am getting '?' instead of Emoji. is there any special way to handle Emoji?

Please do the needful.

Thanks.

**Comment by iitrsachin** [comment]
@zinid @badlop : Am I doing something wrong?

**Comment by zinid** [comment]
@iitrsachin if you are using mysql, check if you have `CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci` on the fields containing emojis (this is now by default in current schema, but double check).

**Comment by zinid** [comment]
The reporter is inactive, I close the issue.
