### ISSUE TITLE
Restart ejabberd Server

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1764]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary Installer Linux

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

Under normal circumstances as I have read the documents on using ejabberdctl command line.  There is a syntax where if i execute "ejabberdctl reload_config" it will only affect for acl and access rules changes.

However, if let say I need to setup media for ejabberd to use and it is a workaround on the mod_http_fileserver and mod_http_upload, once I have complete the setup, my question will be

1)  Do i need to restart the server by issue command "ejabberdctl restart"?
2)  If i restart will it impact to the muc, archive or other services on ejabberd to be deleted?

In what situation I should use "ejabberdctl reload_config" and "ejabberdctl restart"?

Thanks.

**Comment by zinid** [comment]
Since 17.04 `ejabberdctl reload_config` reloads everything, although the feature is experimental (if you don't have something reloaded, report a bug).

**Comment by molochmike** [comment]
Hi @zinid 

Tested yesterday after modify some access rules section and do reload_config.   Check from logs yes it reloads.

Then add in some elements into module section on ejabberd config, run reload_config, it says module does support reload_config and service will be restarted.  I assume it is only for this module changes.

I close this topic now seems working fine at my end.  If there is bugs, will report back to this topic again.

Thanks @zinid
