### ISSUE TITLE
-name : Unknown option No file named ejabberd@localhost when doing iexlive

### ISSUE THREAD

**Issue by IRog** [processone/ejabberd#1765]
> What version of ejabberd are you using?

17.04.160

> What operating system (version) are you using?

Ubuntu 17.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What

`./ejabberdctl iexlive`

> was the unexpected behavior? What was the expected result?
Starting a ejabberd with a iex live shell attached to it

I was also having problems with `iexdebug`
This might be related to my installation. I built it from source and followed the elixir guide to build it in $HOME/my-ejabberd I also did this as a user called ejabberd. Is this something wrong with mnesia or the erlang cookie? `./ejabberdctl live` works...

**Comment by IRog** [comment]
https://github.com/processone/ejabberd/pull/1766

**Comment by cromain** [comment]
good catch, thanks.
