### ISSUE TITLE
mod_shared_roster issue

### ISSUE THREAD

**Issue by xavierba** [processone/ejabberd#1767]
Hi,

I'm migrating a single node ejabberd 2.1.11 to a 2 nodes ejabberd 15.07. I know this is a quite old version, but I can't go above ejabberd 15.07 because I'm currently stuck with erlang R16B, and later versions require a more current erlang version.

The ejabberd 15.07 servers are running over CentOS 7.3.
It has been patched with : 
https://github.com/processone/ejabberd/commit/6ff81946cf7148bbd5c031e3bbbb9c9a3b0d0471
and
https://github.com/processone/ejabberd/commit/70bfc5b4a8ed20197f4f8677dd5a05f40def33c6
to fix an issue with the old mnesia database leading to dropped connection after authentication, as described in : 
https://github.com/processone/ejabberd/issues/1409

With that, I still had an issue with the pubsub_item.DAT conversion, leading to the following error : 
[critical] <0.912.0>@ejabberd_config:report_and_stop:1127 Failed to convert 'pubsub_item' table to binary: {aborted,
                                                  {undef,
                                                   [{fxml,to_xmlel,
                                                     [{xmlelement,"metadata",
                                                       [{"xmlns",
                                                         "urn:xmpp:avatar:metadata"}],
                                                       [{xmlelement,"info",
                                                         [{"id",
                                                           "05c8cc474780c6c27cbcaad490a9fcee6739008e"},
                                                          {"type","image/png"},
                                                          {"bytes","17820"},
                                                          {"width","96"},
                                                          {"height","96"}],
                                                         []}]}],
                                                     []},
                                                    {pubsub_migrate,
                                                     '-convert_list_items/0-lc$^0/1-0-',
                                                     1,
                                                     [{file,
                                                       "src/pubsub_migrate.erl"},
                                                      {line,364}]},
                                                    {pubsub_migrate,
                                                     '-convert_list_items/0-fun-1-',
                                                     1,
                                                     [{file,
                                                       "src/pubsub_migrate.erl"},
                                                      {line,364}]},
                                                    {ejabberd_config,
                                                     '-convert_table_to_binary/5-fun-1-',
                                                     4,
                                                     [{file,
                                                       "src/ejabberd_config.erl"},
                                                      {line,1065}]},
                                                    {lists,foldl,3,
                                                     [{file,"lists.erl"},
                                                      {line,1248}]},
                                                    {mnesia,do_foldl,8,
                                                     [{file,"mnesia.erl"},
                                                      {line,987}]},
                                                    {mnesia,foldl,6,
                                                     [{file,"mnesia.erl"},
                                                      {line,967}]},
                                                    {mnesia_tm,apply_fun,3,
                                                     [{file,"mnesia_tm.erl"},
                                                      {line,832}]}]}}

I somewhat fixed it by removing this file.
I can provide more information on this issue in a separate issue if needed.

At this point, the 2 nodes cluster starts, users are authenticating and according to admittedly limited testing, all seems to run as expected.

However, an error is pilling up in the log : 
[error] <0.616.0>@ejabberd_hooks:run_fold1:371 {function_clause,[{mod_shared_roster,get_rosteritem_name,[[mod_vcard_ldap,mod_vcard],<<"firstname.lastname">>,<<"domain.tld">>],[{file,"src/mod_shared_roster.erl"},{line,187}]},{mod_shared_roster,'-get_user_roster/2-lc$^0/1-0-',5,[{file,"src/mod_shared_roster.erl"},{line,176}]},{mod_shared_roster,get_user_roster,2,[{file,"src/mod_shared_roster.erl"},{line,174}]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,385}]},{ejabberd_hooks,run_fold1,4,[{file,"src/ejabberd_hooks.erl"},{line,368}]},{mod_roster,process_iq_get,3,[{file,"src/mod_roster.erl"},{line,316}]},{gen_iq_handler,process_iq,6,[{file,"src/gen_iq_handler.erl"},{line,119}]},{gen_iq_handler,handle_info,2,[{file,"src/gen_iq_handler.erl"},{line,191}]}]}

The JID and domain have been redacted. This is a recurring error with various JIDs.

I'm stuck at this point and after talking to zinid in ejabberd@conference.jabber.ru, he advised to file an issue to possibly get more help.

Thanks in advance.

Regards,
Xavier

**Comment by xavierba** [comment]
About the mnesia db conversion issue, I worked around it by replacing the 2 calls to fxml:to_xmlel by xml:to_xmlel calls in the backported patch.

**Comment by badlop** [comment]
Do you have enabled mod_vcard and also mod_vcard_ldap in the ejabberd configuration file? You should use only one, either the internal or the ldap one

**Comment by xavierba** [comment]
I did have both mod_vcard and also mod_vcard_ldap in the conf.
Disabling one seems to do the trick. 
I did had both enabled too in the ejabberd 2.1.11 host and no such error there.
I'll keep an eye on it for the next few days and report back.
Thanks.
