### ISSUE TITLE
Manage session on ejabberd server

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1768]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I wish to ask how do I go about managing user session when they connect to ejabberd server?  Can we control something like whatsapp for example only allow and limit user to use single session per device?  Otherwise if there is no control on this then user can have multiple sessions and this will flood the ejabberd server.

Thanks.

**Comment by zinid** [comment]
There is `max_user_sessions` ACL rule which limits the amount of resources a client is able to bind to.

**Comment by molochmike** [comment]
Hi @zinid 

Thanks!
