### ISSUE TITLE
How to make connection between node.js project and ejabberd ?

### ISSUE THREAD

**Issue by SanchiSinghal** [processone/ejabberd#1770]
> What version of ejabberd are you using? 

Latest 
Erlang (ASYNC_THREADS) (BEAM) emulator version 5.10.4

> What operating system (version) are you using? 

14.04

> How did you install ejabberd (source, package, distribution)?

package 

> What did not work as expected?

what is the entry point to call ejabberd APIfrom node.js project ?

**Comment by badlop** [comment]
Why do you assume there is an entry point? Where did you read about that? That place will also point you to the response.

**Comment by SanchiSinghal** [comment]
Not the entry point as in but how to call the API's .

**Comment by badlop** [comment]
There are several ways to interact with ejabberd:
* using an xmpp client, and login to an account
* with a system shell, running ejabberdctl commands
* enabling ejabberd_xmlrpc, and send XMLRPC queries
* enabling mod_rest, and sending ReST queries

**Comment by SanchiSinghal** [comment]
yes, i have enabled the mod_http_api on port 5281 in ejabberd.cfg but the question is to how to tell node that register is an ejabberd administration API .

**Comment by prefiks** [comment]
Which commands and who can execute them is managed by api_permissions: option in ejabberd.yml config file. By default "admin access" rules in that should allow to execute "register" command when you authenticate as admin from local loopback interface.

**Comment by SanchiSinghal** [comment]
I can't found ejabberd.yml file have ejabberd.cfg file. Can you please make me note where to place api permissions in ejabberd.cfg file ?

**Comment by prefiks** [comment]
Ah i see you are using quite old version of ejabberd, i am pretty sure in that version there was no mod_http_api, this is later addition, you would have to use newer version to be able to use it.

**Comment by zinid** [comment]
We do not maintain Ubuntu packages: ejabberd version there can be quite old.

**Comment by SanchiSinghal** [comment]
So what can I do ?Can you guys upgrade ? or can i write api-permissions in ejjaberd.cfg file. if yes ? then where ?

**Comment by SanchiSinghal** [comment]
i cloned the git repo but on web admin it is shwoing me only the virtual host block. seems that it was not installed properly. so how can uninstall it ? I can't even find the uninstall.run file clone repo folder?

**Comment by SanchiSinghal** [comment]
I have uninstalled them manually after doing make uninstall. 
Now, can you please help with calling Ejabberd rest api from node backend. I have done the configurations of API permissions. But how to tell node that its an ejabberd api running on port 5280. Do we need to install other libraries (XMPP) ?

**Comment by SanchiSinghal** [comment]
Can you please help ??
I'm trying to call api/register from node but running node . gives me :--
{ status: 'error',
  code: 32,
  message: 'AccessRules: Account does not have the right to perform the operation.' }

**Comment by zhangcunxiang** [comment]
@SanchiSinghal  the reason your web admin only show the virtual host is your ejabberd.yml has not configure right,you should set your admin user in ejabberd.yml at about line 454 ,uncomment the admin user like this:
```xml
acl:
  ##
  ## The 'admin' ACL grants administrative privileges to XMPP accounts.
  ## You can put here as many accounts as you want.
  ##
  admin:
    user:
      - "aleksey@localhost"
      - "ermine@example.org"
```

**Comment by SanchiSinghal** [comment]
But i need to run the API from node backend server not through command line.

**Comment by SanchiSinghal** [comment]
{ status: 'error',
  code: 10001,
  message: 'Can\'t register user @ at node ejabberd@localhost: not_allowed' }

**Comment by SanchiSinghal** [comment]
Now, getting below error while calling register api from node .
{ status: 'error',
  code: 10001,
  message: 'Can\'t register user @ at node ejabberd@localhost: not_allowed' }
Please help !!

**Comment by yadavanand** [comment]
@SanchiSinghal Did you find any solution?

**Comment by hardiked** [comment]
@SanchiSinghal  if you findout any solution please share here.

**Comment by mremond** [comment]
Did you read this page: https://docs.ejabberd.im/developer/ejabberd-api/simple-configuration/

It seems it addresses your questions.
