### ISSUE TITLE
Receive notification when vcard is updated.

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1771]
> What version of ejabberd are you using?
17.01

Through the API we update the vcard of a user with a setvcard.

In the phone app we should receive a notification through xmpp, all the persons from the roster should receive a message about it.

How can we enable this message or is there another way of knowing that a vcard is updated?

Thank you in advance!

**Comment by badlop** [comment]
When mod_vcard sets a vcard, it runs the event vcard_set. You can write a module that adds a hook to that event: in that case gets the user roster, and sends a message to all its contacts.

For example of how to add a hook to that event, see mod_vcard_xupdate.erl
