### ISSUE TITLE
delete_old_users ejabberdctl command doesn't work

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#1772]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to delete inactive users using the **delete_old_users_vhost** ejabberd command. However, It doesn't work and returns **Deleted 0 users: []**

> #ejabberdctl num_active_users example.com 30 
> 848
> #ejabberdctl num_active_users example.com 7 
> 468
> #ejabberdctl delete_old_users_vhost example.com 7
> Deleted 0 users: []

I am expecting the command to delete the 380 old users but it doesn't work.

**Comment by badlop** [comment]
You can solve this problem by adding to your configuration file:
```yaml
access_rules:
  delete_old_users:
   - deny: admin
   - allow: all
```
I've committed a change that will replace that with protect_old_users, so this option will not be required in the future.

**Comment by dhiru1602** [comment]
Thanks for fixing the issue and making the command work out of the box :+1:
