### ISSUE TITLE
Export to SQL encodes boolean values as integers

### ISSUE THREAD

**Issue by jamestait** [processone/ejabberd#1773]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 17.04, Ubuntu 16.04.

> How did you install ejabberd (source, package, distribution)?

Snap package, compiled from source.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When exporting data using `ejabberdctl export2sql`, boolean values in the insert statements for the `privacy_list_data` table, generated by `mod_privacy_sql.erl`, are provided as integers. This makes PostgreSQL complain about a missing cast. Changing the boolean values to strings instead of integers is one way to work around this for PostgreSQL, but may not be cross-compatible with other DBMS.

**Comment by badlop** [comment]
Right, rows in privacy_list_data are not imported in PostgreSQL because the match_* values are integers, while boolean are expected.

 I found not way to produce a single *.sql file that is accepted by PostgreSQL and the other databases. I could only find dirty solutions, like this one that provides the PostgreSQL lines commented in the exported file, so the admin can remove the generic ones and enable those ones when using PostgreSQL:
```diff
diff --git a/src/mod_privacy_sql.erl b/src/mod_privacy_sql.erl
index 4ee0984a8..84d1b717f 100644
--- a/src/mod_privacy_sql.erl
+++ b/src/mod_privacy_sql.erl
@@ -235,6 +235,18 @@ export(Server) ->
                                  || {SType, SValue, SAction, Order,
                                      MatchAll, MatchIQ,
                                      MatchMessage, MatchPresenceIn,
+                                     MatchPresenceOut} <- RItems] ++
+                                [?SQL("-- POSTGRESQL -- insert into privacy_list_data(id, t, "
+                                      "value, action, ord, match_all, match_iq, "
+                                      "match_message, match_presence_in, "
+                                      "match_presence_out) "
+                                      "values (%(ID)d, %(SType)s, %(SValue)s, %(SAction)s,"
+                                      " %(Order)d, CAST(%(MatchAll)b as boolean), CAST(%(MatchIQ)b as boolean),"
+                                      " CAST(%(MatchMessage)b as boolean), CAST(%(MatchPresenceIn)b as boolean),"
+                                      " CAST(%(MatchPresenceOut)b as boolean));")
+                                 || {SType, SValue, SAction, Order,
+                                     MatchAll, MatchIQ,
+                                     MatchMessage, MatchPresenceIn,
                                      MatchPresenceOut} <- RItems]
                     end,
                     Lists);
```

**Comment by Neustradamus** [comment]
@badlop: Have you found a better solution? Or integrate your patch?
