### ISSUE TITLE
HTTP Upload Error

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1776]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 6.5

> How did you install ejabberd (source, package, distribution)?

Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I register an account on xmpp client on mac using adium connecting to my ejabberd server.  Then on my iphone 4 i install Monal IM another xmpp client which i setup my another xmpp account connected to my ejabberd server.

Now i try sending image which is a source from *.png to adium xmpp client on desktop, it allow me to authenticate to my phone camera and photos folder.

I get this error when i try send a message.  The error message is "There was an error uploading the file to the server".  The certificate for this server is invalid.  You might be connecting to a server that is pretending to be "abc.example.com" which could put your confidential information at risk.

I don't get it the cert is valid and it is use by my apache without problem.   How is it this error can happen now when previously it was not?  Hope someone can help me.  Thanks.

**Comment by molochmike** [comment]
Hi,

I revert not to use tls and ssl to bind to port 5444 for mod http upload & meaning i am now able to send and receive media picture without https.  Problem is I am using Let's Encrypt cert and it will only due in end July 2017 so there's plenty of time.

Other applications that sits on my same server able to work with the SSL cert but not for ejabberd 17.04

Seems weird as when i work on ejabberd 16.12 and beta 17.03 ssl problem does not occur to me on mod_http_upload.  In current 17.04, i basically using back the same setup.

**Comment by badlop** [comment]
So, 17.03 worked correctly and 17.04 complains? Looking at the major changes, I see nothing relevant: https://blog.process-one.net/ejabberd-17-04/

Maybe the certificate verification is more strict in 17.04 If you are able to compile ejabberd from git repository,  you can use "git bisect" between 17.03  and 17.04, to know exactly what commit introduced your problem.

**Comment by molochmike** [comment]
Hi @badlop 

Thanks for the input.  I have try not to use 'macros' define on the ejabberd config rule and directly set the certfile, etc to the listen port 5444 with tls set to true.  Does not seem to work and the same error appears.  As for this moment I will just depend on without secure upload using http will do.

One more question, as me and team is working on this project now, we can't seem to find any standards on how we can work on media stuff on ejabberd.  The rest api does not have support to work on media.  Wish to ask is there any standards that you may have, guideline or structure charts that we can follow to work on media side for photos, video, etc?

**Comment by molochmike** [comment]
Hi @badlop 

The https is working back.   It was my server part problem.  I delete away my custom .pem cert and then regenerate back new one.  Re-enable back the macros define for CERTFILE and then adjust some settings on module http upload section and test with frontend xmpp client gajim and adium is working based on logs file observation.

**Comment by molochmike** [comment]
Hi @badlop 

One more question, as me and team is working on this project now, we can't seem to find any standards on how we can work on media stuff on ejabberd.  The rest api does not have support to work on media.  Wish to ask is there any standards that you may have, guideline or structure charts that we can follow to work on media side for photos, video, etc?

**Comment by badlop** [comment]
Not that I'm aware.
