### ISSUE TITLE
Error while processing SQL Query {error,{badrecord,state}

### ISSUE THREAD

**Issue by prafulbagai** [processone/ejabberd#1777]
> What version of ejabberd are you using?

17.04.105

> What operating system (version) are you using?

Mac

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I created a module using hooks. In it, I fire a SQL query as follow:-

`?INFO_MSG("Packet Type:- `~p` ~n ~n ~n", [sql_queries:get_privacy_list_names_t("praful")]);`

It returns an error saying:-

`11:50:34.790 [error] Internal error while processing SQL query: {error,{badrecord,state},[{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,526}]},{ejabberd_sql,sql_query_t,1,[{file,"src/ejabberd_sql.erl"},{line,180}]},{mod_sunshine,user_receive_packet,1,[{file,"src/mod_sunshine.erl"},{line,27}]},{ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,380}]},{ejabberd_hooks,run_fold1,4,[{file,"src/ejabberd_hooks.erl"},{line,364}]},{ejabberd_c2s,process_info,2,[{file,"src/ejabberd_c2s.erl"},{line,231}]},{ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,380}]},{ejabberd_hooks,run_fold1,4,[{file,"src/ejabberd_hooks.erl"},{line,364}]}]}`

It says, badrecord. What is this? Why am I getting it?

**Comment by zinid** [comment]
> It says, badrecord. What is this? Why am I getting it?

1) Because you typically should not call functions `sql_queries` module directly outside of `ejabberd_sql:sql_query()` or `ejabberd_sql:sql_transaction()`.
2) `sql_queries` module no longer exists in `master` branch, that is, it won't be available in next ejabberd release. So don't use it anyway.

**Comment by prafulbagai** [comment]
Thanks @zinid for the insight. I want to write custom SQL queries and as provided [here](https://github.com/processone/ejabberd/blob/master/src/ejabberd_auth_sql.erl#L167) , I've updated my code accordingly, but still getting the same error. I'm not using `sql_queries` module anymore, but I still feel that its still the same. Apology if the doubt sound so noob(I've just started coding on custom ejabberd modules.)

```
-module(mod_sunshine).
-compile([{parse_transform, ejabberd_sql_pt}]).

-behavior(gen_mod).

-include("ejabberd.hrl").
-include("logger.hrl").
-include("xmpp.hrl").
-include("ejabberd_sql_pt.hrl").

-export([start/2, stop/1, user_receive_packet/1, count_users/0]).

start(_Host, _Opts) ->
    ejabberd_hooks:add(user_receive_packet, _Host, ?MODULE, user_receive_packet, 50),
    ok.

stop(_Host) ->
    ejabberd_hooks:delete(user_receive_packet, _Host, ?MODULE, user_receive_packet, 50),
    ok.


user_receive_packet({Packet, C2SState}) ->
    Type = xmpp:get_type(Packet),
    case Type of
        chat ->
            ?INFO_MSG("Packet Type:- `~p` ~n ~n ~n", [count_users()]);
        _ ->
            ok
    end,

    {Packet, C2SState}.

count_users() ->
    ejabberd_sql:sql_query_t(
        ?SQL("select @(count(*))d from users")).

```

**Comment by zinid** [comment]
Remove `_t` suffix, i.e.:
```erlang
count_users(LServer) ->
    ejabberd_sql:sql_query(
        LServer,
        ?SQL("select @(count(*))d from users")).
```

**Comment by prafulbagai** [comment]
What is `LServer`?

**Comment by prafulbagai** [comment]
Okay, so after looking at the [code](https://github.com/processone/ejabberd/blob/504860f065a889584b0e7b52e3f06cfa486723ac/src/mod_metrics.erl#L100) , this is how I've done.


I modified my hook function as follow:-

`user_receive_packet({Packet, #{jid := #jid{lserver = LServer}} = C2SState}) ->`

And it works like a charm. Kindly confirm if this is the STANDARD way or is there some other way around as well. Thanks

**Comment by zinid** [comment]
Yes, this looks fine
