### ISSUE TITLE
libcrypto.so.1.0.0 is old for Centos 7

### ISSUE THREAD

**Issue by marinakr** [processone/ejabberd#1778]
Hello, 

> What version of ejabberd are you using?

Ejabberd 16.06

> What operating system (version) are you using?

Centos7 
```uname -a
Linux dev.mantu.im 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when I am starting ejabberd after successfull make and make install
```
EJABBERD_CONFIG_PATH=ejabberd.yml erl -sname nodeej -pa ebin -pa deps/*/ebin -pa -s ejabberd
```
I got error 
```
{error,{load_failed,"Failed to load NIF library deps/fast_tls/priv/lib/p1_sha: 'libcrypto.so.1.0.0:
 cannot open shared object file: No such file or directory'"}}
 in fast_tls_app:start/2 line 53 in application_master:init/4 line 134
```
On Centos7 I have installed openssl 1.0.1
> rpm -qa | grep openssl

shows
```
openssl-libs-1.0.1e-60.el7_3.1.x86_64
openssl-1.0.1e-60.el7_3.1.x86_64
openssl-devel-1.0.1e-60.el7_3.1.x86_64
```
and 
```
-rwxr-xr-x. 1 root root 34924 Май 25 18:38 /usr/lib/libcrypt-2.17.so
lrwxrwxrwx. 1 root root    16 Июн 12 13:42 /usr/lib/libcrypt.so.1 -> libcrypt-2.17.so
```

**Comment by badlop** [comment]
So you have the package openssl-libs 1.0.1, but libcrypt is 2.17?

**Comment by marinakr** [comment]
yes
updating fast_tls to master fix it but I am not sure it works correctly

**Comment by badlop** [comment]
So, does ejabberd start without complaining? Can clients login using STARTTLS encryption?

**Comment by marinakr** [comment]
I'll check after set up

**Comment by cromain** [comment]
Closing issue as it's not ejabberd related. When compiling from sources, best to start from a fresh clean new environment (make distclean). Here it seems fast_tls was already compiled at time your OS hosted openssl-1.0.0 (maybe the first time you compiled ejabberd 16.06).
Then you upgraded openssl on your OS, and tried to rebuild ejabberd without 'make distclean'
Upgrading fast_tls just forced it's rebuild (that's why you think it fixed it).

**Comment by marinakr** [comment]
configure files of fast_tls tag 1.0.4 has defined tls version 1.0.0
