### ISSUE TITLE
Ejabberd - Create a custom stanza (GET/SET Subtags)

### ISSUE THREAD

**Issue by prafulbagai** [processone/ejabberd#1779]
> What version of ejabberd are you using?

17.04.105

> What operating system (version) are you using?

Mac

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I receive a message stanza, and want to set/get some tags in it. This is how I do.

    -record(routed, {routed=false}).
    
    user_receive_packet({Packet, #{jid := #jid{lserver = LServer}} = C2SState}) ->
        AlreadyRouted = xmpp:get_subtag(Packet, #routed{}),
        case AlreadyRouted of
            false -> %% set subtag
               xmpp:set_subtag(Packet, #routed{routed = <<"false">>}),
            true -> %% do something.

But when I get the subtag, it says

    ** Reason = {error,undef,[{undefined,do_get_name,[],[{routed,false}]},{xmpp,get_subtag,[{file,"src/xmpp.erl"},{line,420}],2},{mod_sunshine,user_receive_packet,[{file,"src/mod_sunshine.erl"},{line,34}],1},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_c2s,process_info,[{file,"src/ejabberd_c2s.erl"},{line,231}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4}]}

I've followed [this](https://github.com/processone/xmpp/blob/master/doc/API.md#get_subtag2) tutorial for setting and getting the tags, but it fails.

I get the same error while `set_subtag` as well. Why there's an `undefined` error. What is undefined?

**Also, what's the different b/w `set_els` and `set_subtag` ?**

**Comment by zinid** [comment]
You should firstly create a mapping between a record (`#routed{}` in your case) and an XML element, because XMPP codec knows nothing about this record, thus you have `{error, undef, ...}`. How to do this is described [here](https://github.com/processone/xmpp/issues/9).

**Comment by zinid** [comment]
> Also, what's the different b/w set_els and set_subtag ?

The difference is that in the case with `set_els` you replace **all** children elements of a stanza, when in the case with `set_subtag` you only replace a particular one.
