### ISSUE TITLE
Ejabberd Fileserver Content Types

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1781]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 6.5

> How did you install ejabberd (source, package, distribution)?

Binary Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I went to my ejabberd.yml config section and scroll down to mod_http_fileserver section and under "content-types to add in ".pdf": "application/pdf"

I then issue command ejabberdctl reload_config.  Then i went to check the ejabberd log and found this error mention as show below. 

```
[error] <0.8029.1>@gen_mod:validate_opts:488
 unknown option 'content-types' for module 'mod_http_fileserver' will be likely ignored,
 available options are: 'accesslog', 'content_types', 'custom_headers',
 'default_content_type', 'directory_indices', 'docroot', 'must_authenticate_with'
```

I want to allow file transfer support on ejabberd such as pdf, docx, xlsx, etc.  How can i achieve this?

Thanks.

**Comment by badlop** [comment]
content-types is not the same than content_types. Provide the correct option name and try again.

**Comment by molochmike** [comment]
Hi @badlop 

My bad.  Option name should be content_types.  No more error from log files.  Thanks.
