### ISSUE TITLE
Is it possibe to import messages into ejabberd

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1787]
> What version of ejabberd are you using?
14.01

We have an old database with messages, is there a way that i can import this into ejabberd?
Or is this not possible ?

**Comment by zinid** [comment]
What do you mean? Import to where? If you want to export your messages into MAM archive, then consult SQL schema of `archive_msg` table, it's pretty straightforward.

**Comment by PH-F** [comment]
e.g. import old messages from an cvs file into ejabberd.

If it would be possible how could i do this?

**Comment by zinid** [comment]
What kind of messages and in what part of ejabberd? `mod_mam`? `mod_offline`?

**Comment by PH-F** [comment]
It's plain text (e.g. in a csv) with sending user/recipient and message. 
And they should go to mod_mam (if possible)

**Comment by zinid** [comment]
There is obviously no read-to-use script, you should write it yourself. But this is not hard if you are going to use SQL backend for ejabberd: convert your csv into sql file and load it into your SQL database.

**Comment by PH-F** [comment]
Thank you for your reply.
Is this also possible using mnesia as database?

**Comment by zinid** [comment]
This is of course possible, but in this case some Erlang knowledge is required.
However, Mnesia is not recommended as MAM storage anyway (due to 2Gb file limit).

**Comment by PH-F** [comment]
Thank you very much, one last question.

Is it possible to convert from mnesia to mysql?

**Comment by zinid** [comment]
Yes.
