### ISSUE TITLE
ejabberd Community Server 17.06-beta fails to install under Windows

### ISSUE THREAD

**Issue by IIXII78** [processone/ejabberd#1789]
> What version of ejabberd are you using?

ejabberd Community Server 17.06-beta

> What operating system (version) are you using?

Windows 10 Pro

> How did you install ejabberd (source, package, distribution)?

Windows 64-bits Installer

> What did not work as expected?

The installation doesn't complete because:

Error executing post installation script
C:\Program Files\ejabberd\bin\postinstall.cmd
ejabberdctl: C:\Program: command not found

The problem is in the file bin\ejabberdctl, it doesn't properly deal with an installation path containing spaces, like the default "C:\Program Files".
Here's a patch to fix that:

```
@@ -97,17 +97,17 @@
 exec_werl()
 {
     NODE=$1; shift
-    exec_cmd $WERL ${S:--}name $NODE $ERLANG_OPTS "$@"
+    exec_cmd "$WERL" ${S:--}name $NODE $ERLANG_OPTS "$@"
 }
 exec_erl()
 {
     NODE=$1; shift
-    exec_cmd $ERL ${S:--}name $NODE $ERLANG_OPTS "$@"
+    exec_cmd "$ERL" ${S:--}name $NODE $ERLANG_OPTS "$@"
 }
 exec_iex()
 {
     NODE=$1; shift
-    exec_cmd $IEX ${S:---}name $NODE --erl "$ERLANG_OPTS" "$@"
+    exec_cmd "$IEX" ${S:---}name $NODE --erl "$ERLANG_OPTS" "$@"
 }
 
 # usage
@@ -267,7 +267,7 @@
     ping)
         PEER=${2:-$ERLANG_NODE}
         [ "$PEER" = "${PEER%.*}" ] && PS="-s"
-        exec_cmd $ERL ${PS:--}name $(uid ping $(hostname $PS)) $ERLANG_OPTS \
+        exec_cmd "$ERL" ${PS:--}name $(uid ping $(hostname $PS)) $ERLANG_OPTS \
                  -noinput -hidden -eval 'io:format("~p~n",[net_adm:ping('"$PEER"')])' \
                  -s erlang halt -output text
         ;;

```

**Comment by cromain** [comment]
indeed. i did not had time to test the windows build, and the refactor missed that quoting.
thanks for pointing this ! it will be fixed for final release.
