### ISSUE TITLE
ejabberd Community Server 17.06-beta fails to start under Windows

### ISSUE THREAD

**Issue by IIXII78** [processone/ejabberd#1790]
> What version of ejabberd are you using?

ejabberd Community Server 17.06-beta

> What operating system (version) are you using?

Windows 10 Pro

> How did you install ejabberd (source, package, distribution)?

Windows 64-bits Installer

> What did not work as expected?

First of all, the installation doesn't complete, see issue #1789.
But even after fixing that, ejabberd doesn't start, showing this error message:

Could not find entry point "win_erlexec" in C:/Program Files/ejabberd/bin\erlexec.dll

And indeed the DLL in question does not export any function at all, rendering it completely useless!
However, further analysis shows that the DLL **does** contain an export table, but the PE header fields that should point to it are empty!

The files beam.smp.dll and beam.dll exhibit the same problem, something seems to be really broken in the GCC you used to build them.

As a temporary solution, applying the following binary patches fixes the problem:

erlexec.dll, bytes "C0 D1 00 00 4A 00 00 00" at offset 0x108
beam.smp.dll, bytes "40 5E 1F 00  7C 00 00 00" at offset 0x108
beam.dll, bytes "10 D9 1B 00  78 00 00 00" at offset 0x108

**Comment by IIXII78** [comment]
It turns out that beam.smp.dll and beam.dll have another related problem:
They have a section named ".drectve" which has an invalid virtual size so that Windows refuses to load the DLL. This can be patched as well, but the section shouldn't be there in the first place - it contains linker directives and is removed by the linker on completion.

Together with the missing export table entry, this very much looks like the linker aborts due to some error, but your build system doesn't notice that and happily packages DLLs that are almost, but not quite, complete.

Section patches:
beam.smp.dll, bytes "00 C0 02 00" at offset 0x230
beam.dll, bytes "00 80 02 00" at offset 0x230

**Comment by IIXII78** [comment]
... and then it all becomes moot anyway because it turns out that the installer doesn't even include all necessary files, like, uh, say, \ejabberd\lib\xmpp-1.1.11\priv\lib\jid.dll

**Comment by cromain** [comment]
build chain fixed
