### ISSUE TITLE
Ejabberd on web

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1791]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

Like whatsapp it supports both mobile and web version.  I was just wondering such feature does it support under ejabberd version?  Which module allows it to work and is there any reference info you can share?  Thanks.

**Comment by weiss** [comment]
There are web clients such as [Converse.js][1], [JSXC][2], or [Kaiwa][3]; and libraries such as [Strophe.js][4] or [Stanza.io][5].  They all require either ejabberd's [BOSH][6] or [WebSocket][7] support being enabled.

[1]: https://conversejs.org/
[2]: https://www.jsxc.org/
[3]: https://github.com/ForNeVeR/Kaiwa
[4]: http://strophe.im/strophejs/
[5]: https://github.com/legastero/stanza.io
[6]: https://docs.ejabberd.im/admin/configuration/#mod-http-bind
[7]: https://docs.ejabberd.im/admin/configuration/#mod-http-ws

**Comment by molochmike** [comment]
Hi,

I went to this link at www.jsxc.org/example and specify my xmpp domain name chat.example.com and below is specify as endpoint /http-bind/ and the error i got is "BOSH server not reachable or misconfigured" and "internal server error: BOSH module not started".

On my ejabberd.yml config I have done the following.

<b>Listener port
&emsp;port: 5280
&emsp;module: ejabberd_http
&emsp;request_handlers:
          &emsp;&emsp;"/http-bind": mod_bosh
&emsp;http_bind: true

modules:
&emsp;mod_bosh:
&emsp;&emsp;max_inactivity: 50</b>

Despite i follow the jsxc.org documentation to setup stuffs related to apache such as rewrite, proxy_http, etc but there's nothing changed.  Is there something wrong with the docs or ejabberd itself?
