### ISSUE TITLE
Audio / Video with Ejabberd

### ISSUE THREAD

**Issue by Immakittycat** [processone/ejabberd#1792]
> What version of ejabberd are you using?
17.04 

> What operating system (version) are you using?
Windows 7

> How did you install ejabberd (source, package, distribution)?
From the windows installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi again ! I am currently developping a chat application using Ejabberd as my Instant Messaging server.
Thus, I would like to implement audio and video calling and, in order to do so, I need to use Jingle.

However, jingle requires a stun server, so I'm trying to configure Ejabberd to act as one.

In the documentation (_https://docs.ejabberd.im/admin/configuration/#stun-and-turn_), it is said I have to add DNS records as follow : 

> _stun._udp   IN SRV  0 0 3478 stun.example.com.
> _stun._tcp   IN SRV  0 0 3478 stun.example.com.
> _stuns._tcp  IN SRV  0 0 5349 stun.example.com.

My problem is :  I don't know where to put those configurations. 
Can someone help me please ?

Thank you !

**Comment by zinid** [comment]
https://en.wikipedia.org/wiki/Zone_file

**Comment by Immakittycat** [comment]
Thanks but this is not helping much, actually.
I know I have to put those lines somewhere, I just can't figure out where it is, and your link doesn't really specify this point.

**Comment by zinid** [comment]
If you don't know what zone file is then you have not enough experience to build such a system. As simple as that.

**Comment by prefiks** [comment]
Setting up of DNS entries is something that you do outside ejabberd, we can't help you with that, you would need to discuss that with someone who is responsible for DNS for your domain.
