### ISSUE TITLE
bad argument in call to fxml_stream:new(undefined, 65536)

### ISSUE THREAD

**Issue by khadijakarkhanawala** [processone/ejabberd#1796]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I am getting below error in crash.log. I am new to ejabberd and not familiar with erlang. Can anybody help me understand why I am getting this error? 

2017-06-22 04:58:53 =CRASH REPORT====
  crasher:
    initial call: ejabberd_receiver:init/1
    pid: <0.23584.370>
    registered_name: []
    exception exit: {{badarg,[{fxml_stream,new,[undefined,65536],[]},{ejabberd_receiver,handle_call,3,[{file,"src/ejabberd_receiver.erl"},{line,168}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.358.0>,ejabberd_listener,ejabberd_sup,<0.62.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 275
  neighbours:
2017-06-22 07:05:00 =ERROR REPORT====
** Generic server <0.25047.377> terminating
** Last message in was {become_controller,undefined}
** When Server state == {state,#Port<0.5706277>,gen_tcp,none,undefined,65536,undefined,infinity}
** Reason for termination ==
** {badarg,[{fxml_stream,new,[undefined,65536],[]},{ejabberd_receiver,handle_call,3,[{file,"src/ejabberd_receiver.erl"},{line,168}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by zinid** [comment]
Are you using BOSH or Websockets?

**Comment by khadijakarkhanawala** [comment]
Websockets. Using GCDAsyncSocket

**Comment by zinid** [comment]
Do you have other errors (before or after this one)?

**Comment by khadijakarkhanawala** [comment]
Log file is filled with this error from beginning of the month.. I also have another error ** Too many db tables **

**Comment by zinid** [comment]
> I also have another error ** Too many db tables **

This one is easy to fix: increase `ERL_MAX_ETS_TABLES` in `ejabberdctl.cfg`.

**Comment by khadijakarkhanawala** [comment]
@zinid Thank you.. :)

**Comment by zinid** [comment]
I need to see the whole log, the info you provided is scarce. You can mail me at ekhramtsov@process-one.net

**Comment by khadijakarkhanawala** [comment]
okay sure

**Comment by khadijakarkhanawala** [comment]
@zinid I have mailed you my log files.
