### ISSUE TITLE
User is always online

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd#1797]
Hi

We are using ejabberd 16.09 in our project and mostly there is no problem but some of our users stays online and never get disconnected.
We are connecting users with our IOS (Using XMPPFramework) and Android Apps(Using Smack) and when the user press the home button and get application to background we are immediately disconnecting user.
For other situations such as network connection lost etc.. , we are using mod_ping in our ejabberd server with these values
```
ping_interval : 10
ping_ack_timeout: 10
```

So its working fine mostly. But as I said before , for some users they always seem offline even if they remove the app from their device.
I couldnt understand how it is possible?
Is there a bug? Can you point me to right direction to find the source of this problem

Thanks

**Comment by badlop** [comment]
You can try in mod_ping to set
> timeout_action: kill

**Comment by tolgatanriverdi** [comment]
its already kill, our current mod_ping configuration is, but the user is still online for more than 2 days

```
ping_interval : 10
ping_ack_timeout: 10
timeout_action : kill
send_pings: true
```

**Comment by weiss** [comment]
Do you happen to know whether that client [resumed][1] the session at least once before loosing the connection?  I suspect `mod_ping` might stop working after stream resumption.

[1]: https://xmpp.org/extensions/xep-0198.html#resumption

**Comment by tolgatanriverdi** [comment]
its possible, because user was trying to use the app at that time.
But for more than 1 day the user is not using the app(removed it), but he is still seems as online.
And in this case that user isnt able to receive offline messages because he seems online to all other users even he is not

**Comment by tolgatanriverdi** [comment]
İts almost 1 week and user is still online even he is removed the app
But other users dont have the similar problem

**Comment by tolgatanriverdi** [comment]
Does anyone have any idea about this problem? Do you know how I can debug the problem?

**Comment by tolgatanriverdi** [comment]
Any idea about the problem?
User is still online more than 1 month. And I dont know if it happens on other users too

**Comment by badlop** [comment]
Let's assume it's a very rare case, that would not happen again, and that the only problem to care about is to close that exact session. Try the ejabberd commands kick_user and kick_session, do they work for that case?

**Comment by tolgatanriverdi** [comment]
I've tried both commands but the user is still online. I'm not able to make the user offline

**sudo /opt/ejabberd-16.09/bin/ejabberdctl kick_user 905346731873 chat.xxxxx.com

sudo /opt/ejabberd-16.09/bin/ejabberdctl kick_session 905346731873 chat.xxxxx.com 79885034106768799491054 onlineusererror**

**Comment by badlop** [comment]
As the last option, you can simply restart ejabberd, did that help?

**Comment by marinakr** [comment]
We are using ejabberd 16.06 and same issue occurs.
 `  mod_ping:
    send_pings: true
    ping_interval: 9
    timeout_action: kill`
Stream management enable, user online 6 day after application removed
