### ISSUE TITLE
ejabberd 17.04 RPM uses "@@INSTALLDIR@@" in the default configuration file, but it doesn't expand

### ISSUE THREAD

**Issue by frh** [processone/ejabberd#1798]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

RHEL 7

> How did you install ejabberd (source, package, distribution)?

Official RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In older versions, the default paths for things like server certificates would contain the path to the installation directory, e.g. "/opt/ejabberd-16.09/conf/server.pem". In 17.04, this is replaced with e.g. "@@INSTALLDIR@@/conf/server.pem", however this doesn't actually seem to expand, so one has to do a search and replace of @@INSTALLDIR@@.

**Comment by cromain** [comment]
i can not reproduce with 17.04 and 17.06-beta rpm. generated /opt/ejabberd-xx/conf/ejabberd.yml does not contains @@INSTALLDIR@@ pattern. Please reopen if you have a reproductible case.
