### ISSUE TITLE
Can not connect to LDAP server

### ISSUE THREAD

**Issue by tobi7695** [processone/ejabberd#1800]
> What version of ejabberd are you using? 
16.01 

> What operating system (version) are you using?
Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
package (Using "apt-get install ejabberd")

> What did not work as expected? 
I can not connect to LDAP server with config:

....
##auth_method: internal
.....
auth_method: ldap
ldap_servers: 
  \- "192.168.122.229"
ldap_encrypt: none
ldap_port: 389
ldap_rootdn: "cn=admin,dc=ldapcap,dc=com"
ldap_password: "ldapadmin"
ldap_base: "o=ldapcap,dc=ldapcap,dc=com"
ldap_uids:
   \- "mail": "%u@ldapcap.com"
ldap_filter: "(mail=*)"
.....
I used this config on ubuntu 14.04 (ejabberd - 2.1.11) -> work fine;
Pls help me.

**Comment by zinid** [comment]
Try this:
```yaml
ldap_servers: ["192.168.122.229"]
```

**Comment by tobi7695** [comment]
@zinid Thank . It still fail. :(

**Comment by zinid** [comment]
I cannot fail silently, you should have some errors in the log.

**Comment by tobi7695** [comment]
ejabberd running fine 
I config to connect LDAP with this config and ejabberd not run! :(

**Comment by zinid** [comment]
I will close the issue if you're unable to read ejabberd.log/error.log/crash.log, because with this info we cannot address your question.

**Comment by tobi7695** [comment]
- ejabberd.log
2017-06-26 16:37:06.979 [error] <0.38.0>@ejabberd_config:get_plain_terms_file:222 Cannot load /etc/ejabberd/ejabberd.yml: Syntax error on line 271 at position 2: did not find expected key

- error.log
2017-06-26 16:37:06.979 [error] <0.38.0>@ejabberd_config:get_plain_terms_file:222 Cannot load /etc/ejabberd/ejabberd.yml: Syntax error on line 271 at position 2: did not find expected key

- crash.log
2017-06-26 15:26:04 =CRASH REPORT====
  crasher:
    initial call: mod_http_fileserver:init/1
    pid: <0.467.0>
    registered_name: []
    exception exit: {{error_access_docroot,<<"/var/www/html/doc">>,enoent},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [ejabberd_sup,<0.38.0>]
    messages: []
    links: [<0.378.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 124
  neighbours:
2017-06-26 15:26:04 =CRASH REPORT====
  crasher:
    initial call: mod_http_fileserver:init/1
    pid: <0.561.0>
    registered_name: []
    exception exit: {{error_access_docroot,<<"/var/www/html/doc">>,enoent},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [ejabberd_sup,<0.38.0>]
    messages: []
    links: [<0.378.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 124
  neighbours:

**Comment by prefiks** [comment]
Looks like your config file is not correct, probably issue with indentation (check line 271)

**Comment by tobi7695** [comment]
@prefiks 
line 271
auth_method: ldap

**Comment by prefiks** [comment]
Would need to see that in bigger context to see what's wrong. Do you have any spaces before that (there shouldn't be any)?

**Comment by tobi7695** [comment]
[ejabberd.txt](https://github.com/processone/ejabberd/files/1101818/configEjabberd.txt)

**Comment by zinid** [comment]
You have spaces in front of every ldap option, remove them.

**Comment by prefiks** [comment]
So you have space before auth_method and all following ldap options, remove them

**Comment by tobi7695** [comment]
@zinid @prefiks It work! :D thanks you very much
