### ISSUE TITLE
Crash when importing users using prosody2ejabberd

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1803]
> What version of ejabberd are you using?

17.06-beta

> What operating system (version) are you using?

Debian Stable (Stretch)

> How did you install ejabberd (source, package, distribution)?

.deb from ProcessOne + latest prosody2ejabberd.beam from @cromain 

> What did not work as expected? Are there error messages in the log? What
```
$ ./ejabberdctl import_prosody /home/edhelas/transfer/
Problem 'error {badmatch,{error,{fread,unsigned}}}' occurred executing the command.
Stacktrace: [{misc,hex_to_bin,2,[{file,"src/misc.erl"},{line,100}]},
{misc,hex_to_base64,1,[{file,"src/misc.erl"},{line,105}]},
{prosody2ejabberd,maybe_get_scram_auth,1,
[{file,"src/prosody2ejabberd.erl"},{line,118}]},
{prosody2ejabberd,convert_data,4,
[{file,"src/prosody2ejabberd.erl"},{line,127}]},```

**Comment by badlop** [comment]
Can you provide example files, so I can debug it?

**Comment by edhelas** [comment]
Related to #1549

The issue appears with any SCRAM encoded content 
```
cat test.dat 
return {
	["iteration_count"] = 4096;
	["stored_key"] = "96749b85a8b7b43feb0cc7a3773be8fd6ea9fa42";
	["salt"] = "b39e7d71-337c-4925-abb1-62a9715d538b";
	["server_key"] = "845210196a0bed33e7c0baa40029b9f27c16a5c3";
};
```

The faulty line seems to be at https://github.com/processone/ejabberd/blob/5418b37314733d0085d78b220a0408cf4ba29987/src/prosody2ejabberd.erl#L118

The script is applying `hex_to_base64` to the 3 fields but only `stored_key` and `server_key` are in hexadecimal. `salt` can simply be converted to base64 (using `encode_base64`) ?

See also https://github.com/processone/ejabberd/issues/1549#issuecomment-286983184 .

**Comment by badlop** [comment]
Ok, with your test account, this patch fixes the problem:
```diff
diff --git a/src/prosody2ejabberd.erl b/src/prosody2ejabberd.erl
index 1bd28ca..c60f2c2 100644
--- a/src/prosody2ejabberd.erl
+++ b/src/prosody2ejabberd.erl
@@ -115,7 +115,7 @@ maybe_get_scram_auth(Data) ->
            #scram{
                storedkey = misc:hex_to_base64(proplists:get_value(<<"stored_key">>, Data, <<"">>)),
                serverkey = misc:hex_to_base64(proplists:get_value(<<"server_key">>, Data, <<"">>)),
-               salt = misc:hex_to_base64(proplists:get_value(<<"salt">>, Data, <<"">>)),
+               salt = base64:encode(proplists:get_value(<<"salt">>, Data, <<"">>)),
                iterationcount = round(IC)
            };
        _ -> <<"">>
```
