### ISSUE TITLE
ejabberd_mod_mam not correctly handling requests

### ISSUE THREAD

**Issue by jonator** [processone/ejabberd#1807]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
WIN 10 Pro, V 1703

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Stanzas I receive from my ejabberd server, while in compliance with [XEP-0313](https://xmpp.org/extensions/xep-0313.html#filter-jid), are not what is expected.

My config for `mod_mam` is:
```
  mod_mam: 
    default: always
    iqdisc: one_queue
    cache_size: 1000
    cache_life_time: 3600
```
The stanza I send:
```
<iq type='set' xmlns='jabber:client' id='035d7f76-1c06-4430-8445-39fd5213fc80:sendIQ'>
	<query xmlns='urn:xmpp:mam:2'>
		<x xmlns='jabber:x:data' type='submit'>
			<field var='FORM_TYPE' type='hidden'>
				<value>urn:xmpp:mam:2</value>
			</field>
			<field var='with'>
				<value>jator@ILLUM-TRISTAN</value>
			</field>
		</x>
	</query>
</iq>
```

Stanza I receive, notice the `lastChild.textContent`:
```
<iq xmlns='jabber:client' xml:lang='en' to='admin@ILLUM-TRISTAN/48269941764073850834290' from='admin@ILLUM-TRISTAN' type='error' id='035d7f76-1c06-4430-8445-39fd5213fc80:sendIQ'>
	<query xmlns='urn:xmpp:mam:2'>
		<x xmlns='jabber:x:data' type='submit'>
			<field var='FORM_TYPE' type='hidden'>
				<value>urn:xmpp:mam:2</value>
			</field>
			<field var='with'>
				<value>jator@ILLUM-TRISTAN</value>
			</field>
		</x>
	</query>
	<error code='503' type='cancel'>
		<service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
		<text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>No module is handling this query</text>
	</error>
</iq>
```
Is my server not configured correctly? Is it a bug/issue with `ejabberd_mod_mam`? I would like to point out [this](https://github.com/processone/ejabberd/issues/1788) issue. It discusses problems installing `mod_mam`, assuming the step necessary.

**Comment by weiss** [comment]
ejabberd doesn't support `urn:xmpp:mam:2` yet. You must use [one of the older revisions][1] for the moment.

[1]: https://xmpp.org/extensions/attic/xep-0313-0.6.html

**Comment by jonator** [comment]
Thank you that was very helpful!
