### ISSUE TITLE
mnesia to mysql or first upgrade?

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1808]
We use ejabberd 17.01, installed from the debian package (apt-get install ejabberd)

In want to migrate from mnesia to mysql so i can import old custom messages into the archive.

It seems exporting ejabberd17.01 to mysql does not work?
https://github.com/processone/ejabberd/issues/1638
Is that correct?

If so, I need to upgrade. But how do I do this when it is installed as a package without losing data?

**Comment by badlop** [comment]
The data when using Mnesia storage is stored in the Mnesia spool dir, see the ejabberd documentation. Once you find that directory:
1. stop ejabberd
2. copy that dir (just in case something goes wrong later)
3. upgrade ejabberd

Usually you don't have to make anything with the Mnesia database, only update the configuration file (if the release notes mention it).

**Comment by PH-F** [comment]
Thank you for your reply!
Is there a new debian package available for 17.04 or do i need to compile the sourcecode?

_Sent from my HTC 10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cromain** [comment]
you can use our deb package if 17.04 is not available in your distribution
https://www.process-one.net/downloads/ejabberd/17.04/ejabberd_17.04-0_amd64.deb
