### ISSUE TITLE
Erlang observer crashes during attempt to connect to ejabberd node

### ISSUE THREAD

**Issue by jameskentTX** [processone/ejabberd#1812]
> What version of ejabberd are you using?

ejabberd 17.06-beta, erlang 19.2.1

> What operating system (version) are you using?

debian stretch

> How did you install ejabberd (source, package, distribution)?

I compiled ejabberd from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

This is a big problem for me, because I can't connect to ejabberd node and view mnesia tables.
I don't know if this is a general problem, or a specific one, caused by my improper debian configuration (lack of necessary libs, some security issues, services not started, etc.)

To see error execute commends:
1. ./ejabberdctl start
2. erl -sname observer -hidden -setcookie MyCookie -run observer
(in different directory, different shell window, as root)
3. in observer click Nodes in menu, and than select ejabberd node (ejabberd@pc17 in my case).

There are two error window infos: "node down", and "error occured on remote node".
```
Eshell V8.2.1  (abort with ^G)
(observer@pc17)1> 
=ERROR REPORT==== 28-Jun-2017::10:21:01 ===
    node: ejabberd@pc17
    call: {observer_backend,sys_info,[]}
    reason: {badrpc,nodedown}
```
and when I executed rb:start() (also with some strange error), I received more info:
```
** Reason for termination == 
** {{badmatch,{badrpc,nodedown}},
    [{observer_app_wx,handle_info,2,[{file,"observer_app_wx.erl"},{line,273}]},
     {wx_object,handle_msg,5,[{file,"wx_object.erl"},{line,450}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

=ERROR REPORT==== 28-Jun-2017::11:00:22 ===
** Generic server appmon_info terminating 
** Last message in was {'EXIT',<0.75.0>,
                           {{badmatch,{badrpc,nodedown}},
                            [{observer_app_wx,handle_info,2,
                                 [{file,"observer_app_wx.erl"},{line,273}]},
                             {wx_object,handle_msg,5,
                                 [{file,"wx_object.erl"},{line,450}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,247}]}]}}
** When Server state == {state,<0.75.0>,[],28696,[<0.75.0>]}
** Reason for termination == 
** {{badmatch,{badrpc,nodedown}},
    [{observer_app_wx,handle_info,2,[{file,"observer_app_wx.erl"},{line,273}]},
     {wx_object,handle_msg,5,[{file,"wx_object.erl"},{line,450}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

**Comment by badlop** [comment]
* What happens if step 2. is "ejabberdctl debug"?
* Or if you start ejabberd in step 1 in live mode, do those apps work correctly?

**Comment by jameskentTX** [comment]
Hello badlop, thank you for your reply.

As I understand there are two posibillities:
1. You can use observer to inspect mnesia table on ejabberd node,
2. or you can't.

Tell me please if you can view ejabberd mnesia tables, or not.
If you can, I will know that there is my specific problem. And if you can't access mnesia tables - you will know how to check what's wrong.

I'm not very experienced in erlang, so I can't test my problem. I could make a stupid error easily.
Anyway, I tried to run debug as you proposed, the error was the same.

Tell me please if you can view ejabberd mnesia tables using observer, or not.

**Comment by jameskentTX** [comment]
I compiled and instaled erlang from github. Nothing changed, observer crashed.
I guess my ejabberd is incompatible with observer. Maybe specific version of erlang/observer is working with ejabberd, but I do not know which one.

**Comment by badlop** [comment]
I have Debian unstable with an old erlang/OTP 18 packaged from debian. Then I download and compile ejabberd from github, and start it in "live" mode. 

First of all, does this work for you?
```
$ erl
Erlang/OTP 18 [erts-7.3.1.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
Eshell V7.3.1.2  (abort with ^G)
1> observer:start().
2> 
```
Then start ejabberd in "live", and in that erlang shell execute observer:start(). I remember some time ago, when I installed ejabberd as root user, I had some problem related to windows access permissions because that erlang shell was running as root. I don't remember the exact problem and solution, but this may help:
http://www.mail-archive.com/debian-user@lists.debian.org/msg223650.html

The other way is to start ejabberd in the server machine, then in your development machine (where you have X windows), start an ejabberd debug, connect to the server one, and try to start observer. I think I did this some time, should work.

**Comment by jameskentTX** [comment]
Thank you very much, badop!
Even with my newest version of Erlang ( Erlang/OTP 21 [DEVELOPMENT] , Eshell V9.0 ), observer is working!
I simply did as you wrote: "Then start ejabberd in "live", and in that erlang shell execute observer:start(). " and my problem disappeared. I see ejabberd mnesia tables. Wonderful! :)

My previous attempts to start observer: erl -sname observer -hidden -setcookie MyCookie -run observer
was from observer documentation, but it didn't work for me.
Thank you once more badlop, have a good day.
