### ISSUE TITLE
Omemo Encryption

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1816]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I read about omemo as per the link below.
https://conversations.im/omemo/
https://conversations.im/omemo/xep-omemo.html

I wish to implement such onto mobile using ejabberd.  Are there any setup/settings that is require to be set on server-side on ejabberd?  Or this is developed purely from front-end?  Thanks.

**Comment by zinid** [comment]
The latter. Server-side you only need to enable PEP (see `mod_pubsub`).
