### ISSUE TITLE
api/register gives an error (Can\'t register user @ at node ejabberd@localhost: not_allowed')

### ISSUE THREAD

**Issue by SanchiSinghal** [processone/ejabberd#1817]
> What version of ejabberd are you using? 

17.04

> What operating system (version) are you using? 

Ubuntu 14

> How did you install ejabberd (source, package, distribution)?

Binary ( ejabberd-17.04-linux-x86_64-installer.run)

> What did not work as expected? Are there error messages in the log? What

Calling register API from node gives error 
```
{ status: 'error',
  code: 10001,
  message: 'Can\'t register user @ at node ejabberd@localhost: not_allowed' }
```

> was the unexpected behavior? What was the expected result?

I can call the status api it gives me proper result 

o/p :- The node ejabberd@localhost is started. Status: startedejabberd 17.04 is running in that node
but register gives mean error . Even unregister does not gives error but it also does not unregister the user.

Note : Calling API without Authentication.

**Comment by prefiks** [comment]
What's your's config api_permission: option look like? Did you change it form default one? (it wouldn't be permited be default rules).

**Comment by SanchiSinghal** [comment]
Here, how my API permissions look like : 
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
      - mod_http_api
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - ip: "127.0.0.1/8"
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - ip: "127.0.0.1/8"
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "*"
  "API used from localhost allows all calls":
    - who: all
    - what:
      - "*"
      - "!stop"
      - "!start"

**Comment by prefiks** [comment]
Ok, looks like command was executed, but for some reason user registration was not possible, do your config's hosts: section list domain that you want to register? Eventually what authentication method do you have enabled in your config?

**Comment by SanchiSinghal** [comment]
which config's hosts are you talking about ? Can you specify me the line no. 
And I'm using OAuth authentication method . Also sending the Authorization key (access token) and the X-admin : true in headers while calling api from node 

Index.js (just in case you need it)
var express = require('express')
var http = require("http");
var app = express();
var request = require("request");

request.post({
	  url: "http://localhost:5281/api/register",
	  form: {
	  	"user":"aaaa",
	  	"host": "localhost",
	  	"password": "bbbb"
	  },
	  headers:{
	  	"User-Agent":"Super Agent/0.0.1",
    	"Content-Type":"application/x-www-form-urlencoded",
    	"Authorization": Bearer e2oBIWF9cT4bDEdy4owNb5PI7pGaAMHJ,
    	"X-Admin":true
	  },
	  json:"true"
  }, function(error, response, body){
      if (error){
        console.log(error);
      } else {
        console.log( body);
      }
});

**Comment by prefiks** [comment]
hosts: section in your ejabberd.yml file

**Comment by yadavanand** [comment]
@SanchiSinghal from where did you get/put your authorization token
"Authorization": Bearer e2oBIWF9cT4bDEdy4owNb5PI7pGaAMHJ
Please help
