### ISSUE TITLE
bad args with mod_offline:user_queue call get_messages_subset

### ISSUE THREAD

**Issue by zhangchaoeasemob** [processone/ejabberd#1818]
> What version of ejabberd are you using?
17.06.beta-27

> What operating system (version) are you using?
macOs Sierra 10.12.5 (16F73)

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I cannot get offline message of some user through webadmin, some error log like this 
```
16:23:01.819 [error] Hook webadmin_page_host crashed when running mod_offline:webadmin_page/3:
** Reason = {error,function_clause,[{jid,tolower,[{file,"src/jid.erl"},{line,203}],[error]},{acl,match_rule,[{file,"src/acl.erl"},{line,333}],3},{mod_offline,get_max_user_messages,[{file,"/Users/zhangchao/work/ejabberd/ejabberd/src/mod_offline.erl"},{line,192}],2},{mod_offline,get_messages_subset,[{file,"/Users/zhangchao/work/ejabberd/ejabberd/src/mod_offline.erl"},{line,733}],3},{mod_offline,user_queue,[{file,"/Users/zhangchao/work/ejabberd/ejabberd/src/mod_offline.erl"},{line,675}],4},{mod_offline,webadmin_page,[{file,"/Users/zhangchao/work/ejabberd/ejabberd/src/mod_offline.erl"},{line,591}],3},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4}]}
** Arguments = [[],<<"localhost">>,{request,'GET',[<<"user">>,<<"test">>,<<"queue">>],[{nokey,<<>>}],{<<"admin">>,<<"localhost">>},{auth_jid,{<<"admin">>,<<"admin">>},{jid,<<"admin">>,<<"localhost">>,<<>>,<<"admin">>,<<"localhost">>,<<>>}},<<"zh-CN">>,<<>>,{{127,0,0,1},65143},<<"localhost">>,5280,[inet,{captcha,true},{http_bind,true},{http_poll,true},{web_admin,true},{ip,{0,0,0,0}}],http,[{<<"Ra-Sid">>,<<"DAF095FA-20150202-071713-2e178b-497fc7">>},{<<"Ra-Ver">>,<<"3.0.8">>},{'Cookie',<<"bdshare_firstime=1486442114033">>},{'Accept-Language',<<"zh-CN,zh;q=0.8">>},{'Accept-Encoding',<<"gzip, deflate, sdch, br">>},{'Referer',<<"http://localhost:5280/admin/server/localhost/user/test/">>},{'Accept',<<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>},{'User-Agent',<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36">>},{<<"Upgrade-Insecure-Requests">>,<<"1">>},{'Authorization',<<"Basic ******">>},{'Connection',<<"keep-alive">>},{'Host',<<"localhost:5280">>}]}]
```

**Comment by agnihotri7** [comment]
Hi,
i have installed ejabberd 17.08 (working fine). I want to enable offline messages notification on.
i am trying [https://github.com/adamvduke/mod_interact](mod_intract) for this but getting below error .

2017-09-27 12:21:02.894 [error] <0.431.0>@ejabberd_hooks:safe_apply:383 Hook offline_message_hook crashed when running mod_offline_post:send_notice/1:
** Reason = {
                error, undef, [
                    {
                        mod_offline_post,
                        send_notice,
                        [],
                        [{
                            bounce,
                            {
                                message,
                                <<>>,
                                chat,
                                <<"en">>,
                                {
                                    jid,
                                    <<"user1">>,
                                    <<"domain.com">>,
                                    <<"1171133519104699199494">>,
                                    <<"user1">>,
                                    <<"domain.com">>,
                                    <<"1171133519104699199494">>
                                },
                                {
                                    jid,
                                    <<"user3">>,
                                    <<"domain.com">>,
                                    <<>>,
                                    <<"user3">>,
                                    <<"domain.com">>,
                                    <<>>
                                },
                                [],
                                [],
                                undefined,
                                [{
                                    xmlel,
                                    <<"composing">>,
                                    [{
                                        <<"xmlns">>,
                                        <<"http://jabber.org/protocol/chatstates">>
                                    }],
                                    []
                                }],
                                #
                                {
                                    ip => {0,0,0,0,0,65535,3686,1098}
                                }
                            }
                        }]
                    },
                    {
                        ejabberd_hooks,
                        safe_apply,
                        [{
                            file,"src/ejabberd_hooks.erl"
                        },
                        {line,380}
                        ],
                    4},
                    {
                        ejabberd_hooks,
                        run_fold1,
                        [{
                            file,"src/ejabberd_hooks.erl"
                        },{line,364}
                        ],4
                    },
                    {
                        ejabberd_sm,
                        route,
                        [{file,"src/ejabberd_sm.erl"},{line,140}],1
                    },
                    {
                        ejabberd_local,route,
                        [{file,"src/ejabberd_local.erl"},{line,116}],1
                    },
                    {
                        ejabberd_router,do_route,[{file,"src/ejabberd_router.erl"},{line,348}],1
                    },
                    {
                        ejabberd_router,route,[{file,"src/ejabberd_router.erl"},{line,87}],1
                    },
                    {
                        ejabberd_c2s,
                        check_privacy_then_route,
                        [{file,"src/ejabberd_c2s.erl"},{line,816}],2
                    }
                ]
            }
** Arguments = [{bounce,{message,<<>>,chat,<<"en">>,{jid,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>},{jid,<<"user3">>,<<"domain.com">>,<<>>,<<"user3">>,<<"domain.com">>,<<>>},[],[],undefined,[{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {0,0,0,0,0,65535,3686,1098}}}}]

**Comment by zinid** [comment]
@agnihotri7 this is clearly an issue of the module you're using. This is a third-party module, we don't provide support for third-party modules.
