### ISSUE TITLE
Config ejabberd_c2s with starttls: false not running

### ISSUE THREAD

**Issue by tobi7695** [processone/ejabberd#1823]
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

package (apt-get intsall)

> What did not work as expected?

When I config module: ejabberd_c2s with starttls: false, can not connect to server from jitsi client, pls help me!
I am using config in file attach below
[ejabberd_c2s.txt](https://github.com/processone/ejabberd/files/1118904/ejabberd_c2s.txt)

**Comment by badlop** [comment]
Maybe that client requires, or is configured to require STARTTLS encryption.

**Comment by tobi7695** [comment]
I am using gitsi client... I dont know how to disable starttls... Could you
help me?

Vào 04-07-2017 00:25, "badlop" <notifications@github.com> đã viết:

**Comment by badlop** [comment]
I guess you mean Jitsi. Looking at the screenshots, I guess the "Advanced" window here will show some option to disable encryption:
https://desktop.jitsi.org/Documentation/SetUpJitsiAccount

**Comment by tobi7695** [comment]
Oh! I'm Stupid, Thank you for all!

2017-07-07 0:15 GMT+07:00 badlop <notifications@github.com>:
