### ISSUE TITLE
fast_tls dependency is missing files

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#1825]
> What version of ejabberd are you using?

17.06

> What operating system (version) are you using?

Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

as an embedded elixir project

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

using ejabberd as embedded project as follows
```
defp deps do
    [{:ejabberd, git: "https://github.com/processone/ejabberd.git", tag: "17.06"},
     {:p1_pgsql, "~> 1.1"},
     {:eredis, "~> 1.0"}]
  end
```
it fetches the ejabberd correctly but the fast_tls dependency is missing files
> {"priv/lib/fast_tls.so", ["c_src/fast_tls.c", "c_src/hashmap.c"]}

the compilation is going through but when starting it complains about NIF and cant find the file fast_tls.so file.

**Comment by jonni-larjomaa** [comment]
I tried to override this dependency and found out that there were also fast_yml with similar complaints about missing NIF. So I think you should check all dependencies.

**Comment by IRog** [comment]
I also created https://github.com/processone/fast_tls/issues/22 for this

**Comment by cromain** [comment]
this can now be closed
