### ISSUE TITLE
[RPM packaging] wrong versioning information preventing upgrade from beta to final

### ISSUE THREAD

**Issue by rom1dep** [processone/ejabberd#1826]
> What version of ejabberd are you using?

17.06-beta, attempting the installation of 17.06 (final) from the officially distributed RPMs

> What operating system (version) are you using?

Centos-6

> How did you install ejabberd (source, package, distribution)?

package from https://www.process-one.net/en/ejabberd/downloads/

> What did not work as expected?

```
yum install ./ejabberd-17.06-0.x86_64.rpm        
Loaded plugins: changelog, fastestmirror, replace
Setting up Install Process
Examining ./ejabberd-17.06-0.x86_64.rpm: ejabberd-17.06-0.x86_64
./ejabberd-17.06-0.x86_64.rpm: does not update installed package.
Error: Nothing to do
```
alternatively
```
rpm -i ./ejabberd-17.06-0.x86_64.rpm  
        package ejabberd-17.06.beta-0.x86_64 (which is newer than ejabberd-17.06-0.x86_64) is already installed
```

When a beta/pre-release version is installed on the system, one would expect the final release to install seamlessly through yum/rpm -i.
Instead, the current packages seem to be missing a compatible pre-release versioning which would make this possible.

**Comment by cromain** [comment]
rpm are generated from our binary installer and we won't change version scheme for a such low level issue. BTW I'm not even sure it's good idea to .rpm and .deb for a beta release. We have such release once (or two) a year, and using binary installer is best in that situation.

**Comment by rom1dep** [comment]
I believe that encouraging the testing of betas would increase the quality of the final product. Some important bugs slipped into releases this year already (like the breaking of carbons due to bugs in stream management, leading to people missing messages…) and this may have been caught with more testers I think.

How about introducing a dot-dot versioning for the out-of-cycle versions?
It could be:
- 17.08(.0) for the publicly released product,
- which would follow 17.07.8x for the beta(s)
- and 17.07.9x for the RC(s)?
