### ISSUE TITLE
[RPM packaging] rpm uninstallation leaves running processes

### ISSUE THREAD

**Issue by rom1dep** [processone/ejabberd#1827]
> What version of ejabberd are you using?

17.06-beta

> What operating system (version) are you using?

Centos-6

> How did you install ejabberd (source, package, distribution)?

package from https://www.process-one.net/en/ejabberd/downloads/

> What did not work as expected?

Uninstalling ejabberd leaves remnant beam.smp and epmd daemon processes running

**Comment by cromain** [comment]
this was a side effect of #1855 with ejabberdctl unable to be run by root.
this is fixed now.
