### ISSUE TITLE
[RPM packaging] ejabberd's package upgrade deletes user configuration

### ISSUE THREAD

**Issue by rom1dep** [processone/ejabberd#1828]
> What version of ejabberd are you using?

upgraded 17.03 to 17.04

> What operating system (version) are you using?

Centos-6

> How did you install ejabberd (source, package, distribution)?

package from https://www.process-one.net/en/ejabberd/downloads/

> What did not work as expected?

package upgrade leaves a skeletton folder in /opt/ejabberd-release with no hope for data retrieval and reuse of the previous config for the next release.

My very own workaround is to symlink the conf and database folders (which I keep in ejabberd's home), and back it up using a VCS. So after an update I can just `hg up -C` to retrieve the last working configuration, and then, recreate the symlinks by hand into /opt.
Any other backup approach would obviously work fine.
As it is, any new user of the officially distributed RPMs would be surprised (and disappointed) by the default destructive behaviour.

**Comment by cromain** [comment]
both .rpm and .deb we provide are just stub to manage our standard "generic" installer with distribution packaging tool. Our generic packaging make it work everywhere, on any linux distribution, being installed in its own directory.
There are pros and cons for such approach, but this is the option we choose. Direct consequence, when uninstalling, we keep run-time files in /opt so user can apply to any other installation the way he wants.
Most used solution is make /opt/ejabberd default's ejabberd home, and keep database, conf and logs directories here. When installing new version, one can just reuse previous data using symlinks
```
[ -d /opt/ejabberd ] && {
  cd /opt/ejabberd-17.06
  for dir in database conf logs
  do
    rm -Rf $dir
    ln -s ../ejabberd/$dir $dir
  done
}
```
To improve user experience, this is something we can add in postinstall, so it will be done automatically.
The only operation user will need to perform is at first uninstall, move /opt/ejabberd-xxx to /opt/ejabberd, and change ejabberd user home to /opt/ejabberd. At next install, the postinstall script can check this.
Note: this is how it works in the windows installer.

**Comment by cromain** [comment]
postinstall scripts has been modified this way, when running as root (i.e. for .dep and .rpm):
set ejabberd home to /opt/ejabberd, and move conf database and logs if needed.
at start, if /opt/ejabberd/conf/ejabberd.yml exists, we use /opt/database for all runtime files, else we fallback to installation directory.
when upgrading ejabberd, previous database and config are kept, and used with new installation.
when removing ejabberd, it's up to the admin to cleanup /opt/ejabberd and remove ejabberd user if needed.
