### ISSUE TITLE
Errors in error.log from custom module even though it works just fine

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1829]
> What version of ejabberd are you using?
17.04

I updated (through a fork) a module to call an API when an offline message is sent.
This works just fine!! But also an error occurs in the error.log at line 24
https://github.com/PH-F/mod_offline_http_post/blob/master/src/mod_offline_http_post.erl

_I don't know why the error occurs and still the module just works fine, hope you can help me._

07-04 10:56:53.426 [error] <0.1066.0>@ejabberd_hooks:safe_apply:383 Hook offline_message_hook crashed when running mod_offline_http_post:create_message/1:

* * Reason = {error,function_clause,[{mod_offline_http_post,create_message,[{file,"/opt/ejabberd-17.04/.ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl"},
{line,24}],[{bounce,{message,<<"f903c2cd-9af4-4a52-b196-6f2f751d55ba">>,chat,<<"en">>,{jid,...cut....},{jid,...cut....},[],[],
undefined,[{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {80,114,26,62}}}}]},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},
{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_sm,route,[{file,"src/ejabberd_sm.erl"},{line,134}],1},{ejabberd_local,route,
[{file,"src/ejabberd_local.erl"},{line,116}],1},{ejabberd_router,do_route,[{file,"src/ejabberd_router.erl"},{line,298}],1},{ejabberd_router,route,[{file,"src/ejabberd_router.erl"},
{line,90}],1},{ejabberd_c2s,check_privacy_then_route,[{file,"src/ejabberd_c2s.erl"},{line,777}],2}]}

* * Arguments = [{bounce,{message,<<"f903c2cd-9af4-4a52-b196-6f2f751d55ba">>,chat,<<"en">>,{jid,....cut...},{jid,....cut.......},[],[],undefined,[{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {80,114,26,62}}}}]

**Comment by zinid** [comment]
This issue should be opened in ejabberd-contrib repo.

**Comment by PH-F** [comment]
Thx, I did: https://github.com/processone/ejabberd-contrib/issues/217
