### ISSUE TITLE
Delay between user_send_packet and user_receive_packet

### ISSUE THREAD

**Issue by davideko** [processone/ejabberd#1830]
> What version of ejabberd are you using?

Ejabberd 16.09

> What operating system (version) are you using?

Ubuntu 14.04 LTS

> How did you install ejabberd (source, package, distribution)?

Distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi All,

We are experiencing delay when receiving message from Ejabberd. In this case 10 different user concurrently send message to `bot@localhost` with rate 5 message/s for 15s. We also try to set fast mode in c2s shaper with value 200MB but still delayed and also we think it's should not reached the 200MB.

We add some additional log in ejabberd_c2s and below is the example log of message with id = "purple65a0f281", it's delayed around 8s.

```
17:37:42.145 [info] Start process user_send_packet message for message id <<"purple65a0f281">> to <<"bot@localhost">>
17:37:42.148 [info] Ending process user_send_packet message for message id <<"purple65a0f281">> to <<"bot@localhost">>

...

17:37:50.023 [info] Start process user_receive_packet message for message id <<"purple65a0f281">> to <<"bot@localhost">>
17:37:50.023 [info] Before run user_receive_packet for message id <<"purple65a0f281">>
17:37:50.023 [info] State: {maxrate,200000000,344937.18470895814,1499164670022753}, Size=626
M=0.001566350731529001, I=0.158
17:37:50.023 [info] After run user_receive_packet for message id <<"purple65a0f281">>
17:37:50.023 [info] Routing message for message id <<"purple65a0f281">>

```
Can someone kindly help to explain what possibly happened between user_send_packet and user_receive_packet and make the message delayed ?

Thanks.

**Comment by zinid** [comment]
Between these two events almost all ejabberd's routing core is executed along with database processing and almost all loaded modules, it's impossible to answer this question.

**Comment by davideko** [comment]
@zinid thank you for the response. We also tried to minimize database processing by disabling MAM and some of our modules. Is it expected then if the rate of message is super high (but still under max_fsm_queue and shaper limit) to one user and make the message delayed to be received?

**Comment by zinid** [comment]
> Is it expected then if the rate of message is super high to one user and make the message delayed to be received?

Sorry, I failed to understand the question.
Are you experiencing high CPU/memory consumption during this messsages flood?

**Comment by davideko** [comment]
@zinid Sorry for the late response. 
We have two Ejabberd instances (Clustered), our daily cpu consumption is around 20% for each instance and when the event occurred the cpu consumption going to 40% for each instance.
