### ISSUE TITLE
inconsistencies in the behavior of `do_route` functions in different modules

### ISSUE THREAD

**Issue by abunuwas** [processone/ejabberd#1831]
> What version of ejabberd are you using?

16.09, intending to move to 17.03

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log?

I'm working on a custom module that stamps a unique message ID per user in every outgoing Packet (I have powerful reasons to do this). To intercept the Packet, I hook a function to the `filter_packet` event, which is raised by the `ejabberd_route:do_route` function. This works fine with all Packets, except the presence unavailable. The presence unavailable Packet is created in [ejabber_c2s:process_terminated](https://github.com/processone/ejabberd/blob/cc58ce6301a6a60d5b3f67fb17731200572fff4b/src/ejabberd_c2s.erl#L269) and is passed in to `ejabberd_c2s:broadcast_presence_unavailable`, which in turn calls `ejabberd_c2s:route_multiple` -> `ejabberd_router_multicast:route_multicast` -> `ejabberd_router_multicast:do_route`, which doesn't call `ejabberd_router:do_route` neither raises a `filter_packet` event. For comparison, as far as I can see all routing functions in `ejabberd_sm` seem to eventually end up in calls to `ejabberd_router:do_route`, which is what I'd always expect. 

> was the unexpected behavior? What was the expected result?

I'd expect all routing functions to end up in calls to `ejabberd_router:do_route` and raise the `filter_packet` event so that all packets leaving the server can be intercepted and treated the same.

**Comment by zinid** [comment]
`ejabberd_router_multicast:do_route/3` calls `ejabberd_router:route/1` if no multicast services are available. Are you using `mod_multicast`?

**Comment by abunuwas** [comment]
Thank you for your ansswer zinid! I just realized that I ended up in some random branch when looking at the code. Just reviewed the code in master branch and it's certainly as you say.
