### ISSUE TITLE
/opt/ejabberd/bin/ejabberdctl connected-users-number is wrong

### ISSUE THREAD

**Issue by jarbelix** [processone/ejabberd#1832]
> What version of ejabberd are you using?
```
dpkg -l | grep ejabberd
ii  ejabberd                          17.04-0                     amd64        ${msg(ejabberd.desc)}
```

> What operating system (version) are you using?

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
```

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have 4 hosts in my configuration file:
Hosts:
```
  - "example.gov.br"
  - "example.com.br"
  - "example.net.br"
  - "example.net"
```

In your connection logs I have only one logged in user:

```
2017-07-04 13: 18: 52,338 [info] <0.7.0> Application ejabberd started on node ejabberd @ localhost
2017-07-04 13: 19: 04.463 [info] <0.323.0> @ejabberd_listener: accept: 311 (<0.847.0>)
 Accepted connection 10.xx.x.xxx:52867 -> 10.82.0.34:5222
2017-07-04 13: 19: 04.632 [info] <0.848.0> @ ejabberd_c2s: handle_auth_success: 438 (tls | <0.847.0>) 
Accepted c2s PLAIN authentication for jarbas.peixoto@example.gov.br by ldap backend
 From 10.xx.x.xxx
2017-07-04 13: 19: 04.747 [info] <0.848.0> @ ejabberd_c2s: bind: 409 (tls | <0.847.0>)
 Opened c2s session for jarbas.peixoto@example.gov.br/pidgin-windows
2017-07-04 13: 24: 07.894 [info] <0.323.0> @ejabberd_listener: accept: 311 (<0.883.0>)
 Accepted connection 10.xx.x.xx: 56610 -> 10.xx.x. Xx: 5222
```

When I consult connected users I have:
```
Root @ debian-xmpp ~ # /opt/ejabberd/bin/ejabberdctl connected_users_number
4

Root @ debian-xmpp ~ # /opt/ejabberd/bin/ejabberdctl connected_users
Jarbas.peixoto@example.gov.br/pidgin-windows
Jarbas.peixoto@example.com.br/pidgin-windows
Jarbas.peixoto@example.net.br/pidgin-windows
Jarbas.peixoto@example.net/pidgin-windows
```

A simple query via netstat confirms the number of active users:
```
Root @ debian-xmpp ~ # netstat-tapn | grep -E "10. *: 5222" | wc -l
1
```

Did someone also have this problem?

**Comment by badlop** [comment]
* Did you enable some cache option in the ejabberd configuration file?
* Have you configured each host with different LDAP configurations, or just defined LDAP details once (the same for the four vhosts)?
* If you define only one vhost in the configuration file, only one user is reported, correctly?
* If you set auth_method to internal in the configuration file, only one user is reported, correctly?

**Comment by jarbelix** [comment]
My complete configuration file (/opt/ejabberd/conf/ejabberd.yml) I have:

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "example.gov.br"
  - "example.com.br"
  - "example.net.br"
  - "example.net"
listen:
  - 
    port: 5222
    module: ejabberd_c2s
    certfile: "/opt/ejabberd/conf/server.pem"
    starttls_required: true
    protocol_options:
      - "no_sslv3"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  - 
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
auth_method: ldap
ldap_servers:
  - "ldap.example.gov.br"
ldap_encrypt: tls
ldap_port: 636
ldap_rootdn: "uid=XMPPUser,ou=Users,o=Builtin,dc=gov,dc=br"
ldap_password: "XXXXXX"
ldap_base: "dc=gov,dc=br"
ldap_uids:
  - "mail": "%u@%d"
ldap_filter: "(&(objectClass=prevPerson)(accountStatus=active))"
sm_db_type: sql
sql_type: mysql
sql_server: "localhost"
sql_database: "ejabberd"
sql_username: "ejabberd"
sql_password: "password"
sql_port: 3306
shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "jarbas.peixoto@example.gov.br"
      - "josue.soares@example.gov.br"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - deny
  trusted_network:
    - allow: loopback
language: "pt-br"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
    access: announce
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_disco: {}
  mod_last: {}
  mod_mam:
    db_type: sql
    default: roster
    request_activates_archiving: true
    assume_mam_usage: true
  mod_muc:
    host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
  mod_register:
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hi.
        Welcome to this XMPP server.
    ip_access: trusted_network
    access: register
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_version: {}
  mod_vcard:
    search: true
    db_type: ldap
    ldap_servers:
      - "ldap.example.gov.br"
    ldap_encrypt: tls
    ldap_port: 636
    ldap_rootdn: "uid=XMPPUser,ou=Users,o=Builtin,dc=gov,dc=br"
    ldap_password: "XXXX"
    ldap_base: "dc=gov,dc=br"
    ldap_uids:
      "mail": "%u@%d"
    ldap_filter: "(&(objectClass=prevPerson)(accountStatus=active))"
    ldap_vcard_map:
      "FN": {"%s": ["cn"]}
      "NICKNAME": {"%s": ["displayName"]}
      "LAST": {"%s": ["sn"]}
      "FIRST": {"%s": ["givenName"]}
      "ORGNAME": {"%s": ["o"]}
      "ORGUNIT": {"%s": ["businessCategory"]}
      "LOCALITY": {"%s, %s": ["l", "st"]}
      "TITLE": {"%s": ["title"]}
      "TEL": {"%s": ["telephoneNumber"]}
      "EMAIL": {"%s": ["mail"]}
      "BDAY": {"%s": ["birthDay"]}
      "ROLE": {"%s": ["employeeType"]}
      "PHOTO": {"%s": ["jpegPhoto"]}
    ldap_search_fields:
      "User": "%u"
      "Full Name": "cn"
      "Given Name": "givenName"
      "Family Name": "sn"
      "Nickname": "displayName"
      "Birthday": "birthDay"
      "City": "l"
      "Email": "mail"
      "Organization Name": "o"
      "Organization Unit": "businessCategory"
    ldap_search_reported:
      "Full Name": "FN"
      "Given Name": "FIRST"
      "Family Name": "LAST"
      "Nickname": "NICKNAME"
      "Birthday": "BDAY"
      "City": "LOCALITY"
      "Email": "EMAIL"
      "Organization Name": "ORGNAME"
      "Organization Unit": "ORGUNIT"
allow_contrib_modules: true

*) If I define only one vhost in the configuration file, only one user is reported.
*) I can not set auth_method to internal in the configuration file because all users are in LDAP.

**Comment by badlop** [comment]
Ah, it may be this option the one that causes your problem:
```
sm_db_type: sql
```
As you have defined the same database for all the four vhosts, the same single user is reported as online session for each vhost. Remove that option, or define a different SQL database for each vhost.

**Comment by jarbelix** [comment]
Option removed. Worked perfectly. Thank you.
