### ISSUE TITLE
Muc Subscriptions Questions

### ISSUE THREAD

**Issue by IRog** [processone/ejabberd#1835]
I was wondering how subscriptions work with mod_offline/offline messages. It looks like mod_mam is used and that https://docs.ejabberd.im/admin/guide/xep/#xep-0013-flexible-offline-message-retrieval is not supported. Is there anyway to query for the offline messages for muc rooms? I was going to fork mod_mam to behave like mod_offline but would like to not have to do that. Also how does the lifecycle look like for subscriptions in regards to being offline?

**Comment by goldzilla** [comment]
According to the documentation [https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#subscribing-to-muc-sub-events](url)  the stanza being sent is not correct:

Get subscriptions: 
`<iq from='hag66@shakespeare.example'
    to='muc.shakespeare.example'
    type='get'
    id='E6E10350-76CF-40C6-B91B-1EA08C332FC7'>
  <subscriptions xmlns='urn:xmpp:mucsub:0' />
</iq>`

**Comment by IRog** [comment]
I had a typo with subscribe vs subscriptions. I was still wondering about my other questions and will edit. Thanks

**Comment by badlop** [comment]
> Also how does the lifecycle look like for subscriptions in regards to being offline?
> I was wondering how subscriptions work with mod_offline/offline messages.
> Is there anyway to query for the offline messages for muc rooms?

A user subscribed to a room will get a message stanza for each message sent to the room, right? If the user is offline, those messages are catched by mod_offline and stored. When the user logins, mod_offline will throw them to the user, as it does with any offline message.

> and that https://docs.ejabberd.im/admin/guide/xep/#xep-0013-flexible-offline-message-retrieval is not supported.

Do you mean, that XEP works for other offline messages, but doesn't work for mucsub-offline messages?

>  It looks like mod_mam is used 

Right: if the room has archiving enabled, the messages are also archived by mod_mam.

**Comment by IRog** [comment]
Thanks we confirmed that with testing, although it seems like retrieving the messages isn't presence based (maybe we need to explicitly send an online presence?). Mod_offline is working fine, but I was curious why the `offline_message_hook` was called with a single argument and the message was flagged as `bounced` and the 1 arity version of the function invoked.?

**Comment by badlop** [comment]
>  it seems like retrieving the messages isn't blanket presence based (maybe we need to explicitly send an online presence?).

See https://xmpp.org/extensions/xep-0160.html#flow that says:
> Now the recipient authenticates with the server and sends initial presence (with a non-negative priority) to the server.
