### ISSUE TITLE
Module Bosh Error

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1836]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary Installer from processone

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I went to this link at www.jsxc.org/example and specify my xmpp domain name chat.example.com and below is specify as endpoint /http-bind/ and the error i got is "BOSH server not reachable or misconfigured" and "internal server error: BOSH module not started".

On my ejabberd.yml config I have done the following.

<b>Listener port
&emsp;port: 5280
&emsp;module: ejabberd_http
&emsp;request_handlers:
          &emsp;&emsp;"/http-bind": mod_bosh
&emsp;http_bind: true

modules:
&emsp;mod_bosh:
&emsp;&emsp;max_inactivity: 50</b>

Despite i follow the jsxc.org documentation to setup stuffs related to apache such as rewrite, proxy_http, etc but there's nothing changed.  Is there something wrong with the docs or ejabberd itself?

**Comment by prefiks** [comment]
What happens when you open url that you use in your client in browser tab? Do you see mod_bosh landing page?

**Comment by molochmike** [comment]
Hi @prefiks 

Yes, the landing page for processone ejabberd mod_bosh appears.  my url will be example http://chat.example.com:5280/http-bind

But when i try to use the online demo provided by jsxc.org to test the url to my domain it says the "bosh server not reachable or misconfigure".  Both my ejabberd and my hostname plus apache are all on the same server.   By follow to the jsxc docs, I can't get the thing to work.

In jsxc, what do they mean by owncloud and nextcloud?  Is it the owncloud installation which i need to setup in my current ejabberd server?

**Comment by prefiks** [comment]
Sorry it's hard to tell what's the problem without more details, could you check network panel in your browser command console to see if client tries to access your url, and what results it gets?

**Comment by prefiks** [comment]
Also i really don't know how jsxc works, i don't use it.

**Comment by molochmike** [comment]
Hi @prefiks 

Yah i guess so need to check more further for the error.   Find it weird.   Need to ask your opinion since you did not use jsxc, which web client you will recommend that i can easily setup and configure for my xmpp server ejabberd to use?   Thanks.

**Comment by molochmike** [comment]
Manage to setup the jsxc on nextcloud version 12 stable on the same node as my ejabberd 17.04 and configure apache to work with the http-bind.  Works great.

**Comment by arendtio** [comment]
@molochmike I have the same problem (jsxc.org/example responding with that error). So do I understand it corretly that you did not change the above configuration and instead this seems to be a bug in the jsxc.org/example service?
