### ISSUE TITLE
Problem starting the module mod_adhoc for host

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1838]
> What version of ejabberd are you using?

ejabberd 16.02

> What operating system (version) are you using?

centos

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After system reboot when we bring up ejabberd it is trowing the following error
"Problem starting the module mod_adhoc for host"

client session is configured to store in redis. When i modify  **sm_db_type** to mnesia it started working. Below is the log

```
2017-07-06 14:42:09.913 [critical] <0.38.0>@gen_mod:start_module:106
 Problem starting the module mod_adhoc for host <<"ejabberd.test.net">>
 options: []
 error: badarg
[{ejabberd_sm,register_iq_handler,5,[{file,"src/ejabberd_sm.erl"},{line,310}]},
 {mod_adhoc,start,2,[{file,"src/mod_adhoc.erl"},{line,53}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,98}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,74}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2017-07-06 14:42:09.913 [critical] <0.38.0>@gen_mod:start_module:111
 ejabberd initialization was aborted because a module start failed.
```

**Comment by zinid** [comment]
> ejabberd 16.02

I think nobody will try to investigate the issue for such old version.
