### ISSUE TITLE
User Nickname stored in PEP Node not published on initial presence

### ISSUE THREAD

**Issue by IIXII78** [processone/ejabberd#1840]
> What version of ejabberd are you using?

17.06

> What operating system (version) are you using?

Windows 10 Pro

> How did you install ejabberd (source, package, distribution)?

Windows 64-bits Installer

> What did not work as expected?

In my configuration there are a number of users that see each other via a shared roster group. They have all published nicknames to a PEP Node according to XEP-0172. The original publication worked fine for everybody, ejabberd sent PubSub notifications to all online users in the shared roster group and they all saw the new nickname in their buddy list.

However, once a user comes back online after being offline ("initial presence"), he only gets a notification for his own node, but he does not get any for the other users' nodes.

The users now see only bare JIDs in their list again instead of nicknames, and complain to me :(

This problem seems somewhat related to issue #1572, but the presence subscription is definitely "both" via the shared roster group and the problem still shows.

**Comment by cromain** [comment]
Testing this after recent fixes around PEP broadcast. With client being nick+notify able, i can not reproduce. client gets notification at publication time, and at reconnection time.
This should be fixed in 17.08
