### ISSUE TITLE
Querying for MUC Archives

### ISSUE THREAD

**Issue by SabrinaMadX** [processone/ejabberd#1841]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 6.5

> How did you install ejabberd (source, package, distribution)?

Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi. So I'm working on MUC and want to load chat archives. Here https://www.ejabberd.im/forum/25254/getting-muc-messages-ejabberd, its mentioned that filtering is done via 'withroom' in form data. 

i get this error when 
```
<stream:error>
	<not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
	<text xmlns='urn:ietf:params:xml:ns:xmpp-streams' xml:lang='en'>not well-formed (invalid token)</text>
</stream:error>
```
sending this IQ:
```
<iq id='2731L-265' type='set'><query xmlns='urn:xmpp:mam:1' queryid='2414e52d-e9de-4e74-90b4-13019e8bbc61'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>urn:xmpp:mam:1</value></field><field var='withroom’><value>place@conference.host</value></field></x><set xmlns='http://jabber.org/protocol/rsm'><before></before><max>50</max></set></query></iq>
07-
```

sending 
````
<iq type='get' id='juliet1'>
  <query xmlns='urn:xmpp:mam:tmp'>
    <withroom>place@conference.host</withroom>
    <set xmlns='http://jabber.org/protocol/rsm'>
         <max>2</max>
         <before/>
      </set>
  </query>
</iq>

````
gets me a wrong result set altogether.

i'd like to know how to implement xep-0313 in querying MUC archives. Any help is highly appreciated!

**Comment by badlop** [comment]
The example you found is from January 2016, back when the XEP didn't describe any way to query room archives.

Nowadays, in recent ejabberd, the way to query room archives is to send the query directly to that room:
```xml
<iq type='set' id='juliet1' to='room5@conference.localhost'>
  <query xmlns='urn:xmpp:mam:0'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:mam:0</value>
      </field>
    </x>
  </query>
</iq>
```

**Comment by SabrinaMadX** [comment]
hi badlop. thanks for your reply. i tried your suggested answer, but it returns me a not well-formed error
````
<stream:error>
	<not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
	<text xmlns='urn:ietf:params:xml:ns:xmpp-streams' xml:lang='en'>not well-formed (invalid token)</text>
</stream:error>
```

**Comment by badlop** [comment]
Obviously, the problem is that you removed some XML character, maybe a ' or a < in your query.

**Comment by zinid** [comment]
> hi badlop. thanks for your reply. i tried your suggested answer, but it returns me a not well-formed error

Because you're sending a malformed XML: you have malformed quotes around `withroom`
