### ISSUE TITLE
c2s_copy_session crashed when running mod_privacy

### ISSUE THREAD

**Issue by drixter** [processone/ejabberd#1842]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

RPM package from webpage

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I getting a error like below, any hint what is going wrong?

<0.1473.0>@ejabberd_hooks:safe_apply:383 Hook c2s_copy_session crashed when running mod_privacy:c2s_copy_session/2:
** Reason = {error,function_clause,[{mod_privacy,c2s_copy_session,[{file,"src/mod_privacy.erl"},{line,414}],[#{socket => {socket_state,fast_tls,{tlssock,#Port<0.22783>,<<>>},<0.1472.0>},mod => ejabberd_c2s,pres_a => {0,nil},pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"me">>,<<"patchcord.be">>,<<"phone">>,<<"me">>,<<"patchcord.be">>,<<"phone">>},{jid,<<"me">>,<<"patchcord.be">>,<<>>,<<"me">>,<<"patchcord.be">>,<<>>},away,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"ver">>,<<"d2rgtMP0QRwWPU4dGU5DEFz5ZmM=">>},{<<"node">>,<<"http://conversations.im">>},{<<"hash">>,<<"sha-1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,18575,57853}}},stream_restarted => true,pres_timestamp => {1499,447399,592214},mgmt_stanzas_req => 0,sockmod => ejabberd_socket,tls_required => false,resource => <<"phone">>,mgmt_queue_type => ram,mgmt_max_queue => 1000,mgmt_timeout => 300,tls_options => [compression_none,{dhfile,<<"/opt/ejabberd-17.07/conf/dhp4096.pem">>},{ciphers,<<"ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256:AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-SEED-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-CAMELLIA128-SHA:DHE-RSA-AES128-SHA">>},{protocol_options,<<"no_sslv3|no_tlsv1">>},{certfile,<<"/etc/ssl/ec2.e-utp.net/ejabberd.key">>}],lserver => <<"patchcord.be">>,auth_module => ejabberd_auth_sql,jid => {jid,<<"me">>,<<"patchcord.be">>,<<"phone">>,<<"me">>,<<"patchcord.be">>,<<"phone">>},stream_compressed => false,user => <<"me">>,mgmt_resend => false,stream_authenticated => true,stream_id => <<"6058062755753596503">>,conn => c2s_tls,ip => {{0,0,0,0,0,65535,18575,57853},49979},stream_header_sent => true,xmlns => <<"jabber:client">>,socket_monitor => #Ref<0.0.1.29412>,...},...]},...]}
** Arguments = [#{socket => {socket_state,fast_tls,{tlssock,#Port<0.22783>,<<>>},<0.1472.0>},mod => ejabberd_c2s,pres_a => {0,nil},pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"me">>,<<"patchcord.be">>,<<"phone">>,<<"me">>,<<"patchcord.be">>,<<"phone">>},{jid,<<"me">>,<<"patchcord.be">>,<<>>,<<"me">>,<<"patchcord.be">>,<<>>},away,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"ver">>,<<"d2rgtMP0QRwWPU4dGU5DEFz5ZmM=">>},{<<"node">>,<<"http://conversations.im">>},{<<"hash">>,<<"sha-1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,18575,57853}}},stream_restarted => true,pres_timestamp => {1499,447399,592214},mgmt_stanzas_req => 0,sockmod => ejabberd_socket,tls_required => false,resource => <<"phone">>,mgmt_queue_type => ram,mgmt_max_queue => 1000,mgmt_timeout => 300,tls_options => [compression_none,{dhfile,<<"/opt/ejabberd-17.07/conf/dhp4096.pem">>},{ciphers,<<"ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256:AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-SEED-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-CAMELLIA128-SHA:DHE-RSA-AES128-SHA">>},{protocol_options,<<"no_sslv3|no_tlsv1">>},{certfile,<<"/etc/ssl/ec2.e-utp.net/ejabberd.key">>}],lserver => <<"patchcord.be">>,auth_module => ejabberd_auth_sql,jid => {jid,<<"me">>,<<"patchcord.be">>,<<"phone">>,<<"me">>,<<"patchcord.be">>,<<"phone">>},stream_compressed => false,user => <<"me">>,mgmt_resend => false,stream_authenticated => true,stream_id => <<"6058062755753596503">>,conn => c2s_tls,ip => {{0,0,0,0,0,65535,18575,57853},49979},stream_header_sent => true,xmlns => <<"jabber:client">>,socket_monitor => #Ref<0.0.1.29412>,stream_encrypted => true,csi_state => active,server => <<"patchcord....">>,...},...]

**Comment by drixter** [comment]
Another example error in logs:

[error] <0.1840.0>@ejabberd_hooks:safe_apply:383 Hook c2s_copy_session crashed when running mod_privacy:c2s_copy_session/2:
** Reason = {error,function_clause,[{mod_privacy,c2s_copy_session,[{file,"src/mod_privacy.erl"},{line,414}],[#{socket => {socket_state,fast_tls,{tlssock,#Port<0.23092>,<<>>},<0.1839.0>},mod => ejabberd_c2s,pres_a => {1,{{<<"seywqa700vhg">>,<<"conference.patchcord.be">>,<<"sevas">>},nil,nil}},pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"sevas">>,<<"patchcord.be">>,<<"phone">>,<<"sevas">>,<<"patchcord.be">>,<<"phone">>},{jid,<<"sevas">>,<<"patchcord.be">>,<<>>,<<"sevas">>,<<"patchcord.be">>,<<>>},undefined,[],undefined,[{xmlel,<<"x">>,[{<<"xmlns">>,<<"jabber:x:signed">>}],[{xmlcdata,<<"iQI5BAEBCgAjHBxTZXdhcyA8c2V3YTE5OTlnQHlhbmRleC5ydT4FAliBsTEACgkQlu5lR5T1NC80WxAAqVfNnSqDAgDcg7G6ajDFaTN9uhkPl1vBxVKrzqoifHYHMclDqnwrZXWhvMN0KMXpkgedpQAdGsGwUGNp2TR7mL6lOtNl8rEp96MIcW/1fSENarp25+MpnKsmRpARHtURtBwvsy3q5UuDDn/uzRN1uESBs5omjADYqFbVwHsvxhd405g/E6Re6jWsKCQpLBDZOMNTDM82QftCTA3yLEcwbwlkYJ5pVrH83Vc8TaexaAkD0k4QFSmjXmHh3W4xw0hZH4iVvmiIychLZ0dVhPrzcsC1ooMMkFP4Uknep4VWVItGq/Y6qy37pASzKBNX/q+0UgxcfFO4T7s44ikhA4pwdR5h2yldsUBVUXxR6yPDd9KYAc+swktselv7D8nqAMLVHQovHMxmch903ySZDYMil1VKx9gMd2bprx/2flc2Ydxnlqqu8UWGvx4+lWP4/S3uffCnzuoKFtTg+jfY9O+Twfthi0gsoEJ7YWRgokrV5um/dlMAxCvyp/GpVQX2pO9THgunKgFdUww7L9zUFX+TsE8i8flGCT4mkcaQNWjACEd8cGLapAvYe+6YUWQH5McuqY3RRThcQccdMWvJljkHhrk5f9LxYrYI76fJmapK/0w+oHe8aizx8esLIYNN00Rt4zPPXWmNYQ0qfpqdFEvOgj05pR4LXQnredEH8R5p01E==oxUs">>}]},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://conversations.im">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"Evmg1voGIe0yVZK6gRzNHpfYHCQ=">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,54636,36104}}},stream_restarted => true,pres_timestamp => {1499,446485,91559},mgmt_stanzas_req => 0,sockmod => ejabberd_socket,tls_required => false,resource => <<"phone">>,mgmt_queue_type => ram,mgmt_max_queue => 1000,mgmt_timeout => 300,tls_options => [compression_none,{dhfile,<<"/opt/ejabberd-17.07/conf/dhp4096.pem">>},{ciphers,<<"ECDHE-RSA...">>},...],...},...]},...]}
** Arguments = [#{socket => {socket_state,fast_tls,{tlssock,#Port<0.23092>,<<>>},<0.1839.0>},mod => ejabberd_c2s,pres_a => {1,{{<<"seywqa700vhg">>,<<"conference.patchcord.be">>,<<"sevas">>},nil,nil}},pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"sevas">>,<<"patchcord.be">>,<<"phone">>,<<"sevas">>,<<"patchcord.be">>,<<"phone">>},{jid,<<"sevas">>,<<"patchcord.be">>,<<>>,<<"sevas">>,<<"patchcord.be">>,<<>>},undefined,[],undefined,[{xmlel,<<"x">>,[{<<"xmlns">>,<<"jabber:x:signed">>}],[{xmlcdata,<<"iQI5BAEBCgAjHBxTZXdhcyA8c2V3YTE5OTlnQHlhbmRleC5ydT4FAliBsTEACgkQlu5lR5T1NC80WxAAqVfNnSqDAgDcg7G6ajDFaTN9uhkPl1vBxVKrzqoifHYHMclDqnwrZXWhvMN0KMXpkgedpQAdGsGwUGNp2TR7mL6lOtNl8rEp96MIcW/1fSENarp25+MpnKsmRpARHtURtBwvsy3q5UuDDn/uzRN1uESBs5omjADYqFbVwHsvxhd405g/E6Re6jWsKCQpLBDZOMNTDM82QftCTA3yLEcwbwlkYJ5pVrH83Vc8TaexaAkD0k4QFSmjXmHh3W4xw0hZH4iVvmiIychLZ0dVhPrzcsC1ooMMkFP4Uknep4VWVItGq/Y6qy37pASzKBNX/q+0UgxcfFO4T7s44ikhA4pwdR5h2yldsUBVUXxR6yPDd9KYAc+swktselv7D8nqAMLVHQovHMxmch903ySZDYMil1VKx9gMd2bprx/2flc2Ydxnlqqu8UWGvx4+lWP4/S3uffCnzuoKFtTg+jfY9O+Twfthi0gsoEJ7YWRgokrV5um/dlMAxCvyp/GpVQX2pO9THgunKgFdUww7L9zUFX+TsE8i8flGCT4mkcaQNWjACEd8cGLapAvYe+6YUWQH5McuqY3RRThcQccdMWvJljkHhrk5f9LxYrYI76fJmapK/0w+oHe8aizx8esLIYNN00Rt4zPPXWmNYQ0qfpqdFEvOgj05pR4LXQnredEH8R5p01E==oxUs">>}]},{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://conversations.im">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"Evmg1voGIe0yVZK6gRzNHpfYHCQ=">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,54636,36104}}},stream_restarted => true,pres_timestamp => {1499,446485,91559},mgmt_stanzas_req => 0,sockmod => ejabberd_socket,tls_required => false,resource => <<"phone">>,mgmt_queue_type => ram,mgmt_max_queue => 1000,mgmt_timeout => 300,tls_options => [compression_none,{dhfile,<<"/opt/ejabberd-17.07/conf/dhp4096.pem">>},{ciphers,<<"ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-A...">>},...],...},...]

**Comment by weiss** [comment]
This has been [fixed in Git][1].

[1]: https://github.com/processone/ejabberd/commit/f6bdc6fdb2ee4a6bc4323a82f647b8795acab2a2

**Comment by ratnadeep-olx** [comment]
@weiss when are you planning to release this?

**Comment by zinid** [comment]
@ratnadeep-olx it's already available in the latest release.

**Comment by ratnadeep-olx** [comment]
Latest release is 17.07 and I do not see the changes there - https://github.com/processone/ejabberd/blob/17.07/src/mod_privacy.erl

**Comment by zinid** [comment]
Ah, indeed.
Then 17.08 will have it.
