### ISSUE TITLE
Mod_blocking Question: where is the message/packet dropped for a blocked user

### ISSUE THREAD

**Issue by IRog** [processone/ejabberd#1843]
> What version of ejabberd are you using?

Latest from Source

> What operating system (version) are you using?

Mac OS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

This is more of a general question. I am looking over the `mod_blocking` module and am wondering where the actual behavior that filters messages from reaching a user that has another user blocked occurs? I see how the block list is created via privacy lists but I was wondering where in the code the message/packet is dropped from the chain. Nothing in mod_blocking.erl itself seems to jump out at me. I was curious about the `broadcast_event` function and was wondering if it happened there or if there is somewhere else in the code where the block list is checked and it's not actually in the mod_blocking module?

Sorry to ask a general question, but I'd really appreciate more information...

**Comment by zinid** [comment]
It's in `mod_privacy.erl`.

**Comment by IRog** [comment]
Is it in `check_packet`? Thanks a lot! I was expecting it to be in blocking...

**Comment by zinid** [comment]
`check_packet` is hooked on `privacy_check_packet` hook, which can be called from anywhere, not only from `ejabberd_c2s.erl`.
