### ISSUE TITLE
mod_mam wrong timestamps saved in mysql database

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#1845]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am using mod_mam to archive messages and maintain the chat history. The messages are being saved fine in the database, however the timestamp is wrong.

Below is the entry from my archive table in mysql database.

username | timestamp | peer | bare_peer | xml | txt | id | kind | nick | created_at
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
username | 1499613776395044 | username@example.com/MyClient | username@example.com | `<message xml:lang='en' to='senduser@example.com' from='username@example.com/MyClient' type='chat' xmlns='jabber:client'><body>This is a test message</body></message>` | This is a test message | 99254 | chat |   | 2017-07-09 17:44:40

As you can notice from the above, the created date is 2017-07-09 17:44:40 IST (Sunday, July 9, 2017 12:14:40 PM GMT) but the timestamp 1499613776395044 (Sunday, July 9, 2017 3:22:56.395 PM GMT) is wrong.

**Comment by zinid** [comment]
Is it a single server, why do you think the time should match between this two software?

**Comment by dhiru1602** [comment]
It is a single server running mysql instance and ejabberd. If the database timestamp is wrong, the clients are not receiving the latest messages from the message archive until the time difference has passed.

**Comment by weiss** [comment]
> If the database timestamp is wrong, the clients are not receiving the latest messages from the message archive until the time difference has passed.

[Once we implemented][1] support for [`urn:xmpp:mam:2`][2] I'd recommend relying on [stanza IDs][3] rather than timestamps.

[1]: https://github.com/processone/ejabberd/issues/1762
[2]: https://xmpp.org/extensions/xep-0313.html
[3]: https://xmpp.org/extensions/xep-0313.html#archives_id
