### ISSUE TITLE
after 17.04->17.06 or 17.07 upgrade: must set ERLANG_NODE in ejabberdctl script itself

### ISSUE THREAD

**Issue by t-animal** [processone/ejabberd#1847]
> What version of ejabberd are you using?

ejabberd 17.07

> What operating system (version) are you using?

Linux 2.6.32-642.6.2.el6.x86_64

> How did you install ejabberd (source, package, distribution)?

via the installer from the ejabberd homepage

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When updating from 17.04->17.06 and 17.04->17.07 you cannot start ejabberd when using a different ERLANG_NODE than the default.
Expected behaviour: restoring backup should be possible without fiddling with the ejabberdctl.
Unexpected behaviour: 
1) Upgrade from an instance with a ERLANG_NODE like ejabberd_foo@localhost.
2) Set the ERLANG_NODE in conf/ejabberdctl.cfg
3) Start ejabberd to restore database from backup
Result: ejabberd does not start

or

3) Overwrite database-folder from backup folder
4) Start ejabberd
Result: it fails due to
`2017-07-09 18:04:01.256 [critical] <0.175.0>@ejabberd_mnesia:init:76 Node name mismatch: I'm [ejabberd@localhost], the database is owned by [ejabberd_foo@localhost]`

or

3) Remove database directory
4) Start ejabberd, it works this time
5) Restore a backup using `ejabberdctl restore` which was fixed like `ejabberdctl mnesia_change_nodename ejabberd@localhost ejabberd_tanimal@localhost `pwd`/backup_file `pwd`/backup_file_fixed`
Result: users cannot log in, probably due to the database not being restored or not restored correctly

or

3) Remove database directory
4) Start ejabberd, it works this time
5) Restore a backup using `ejabberdctl install_fallback`.
Result: Can't install fallback from ".../backup_file_fixed" at node ejabberd@localhost: {"Cannot install fallback",  {"No disc resident schema on local node", [ejabberd_foo@localhost]}}`

How to fix it: 
1) overwrite ERLANG_NODE in ejabberdctl itself.
2) remove database folder
3) overwrite database-folder from backup folder

I do have say that I'm a bit baffled and I think I might be doing something wrong here. To me the shell-script `ejabberdctl` looks good. But I did just verify twice that this happens and I think it might be a bug. See also: https://www.ejabberd.im/forum/28885/cant-use-mnesia-database-after-1704-1706-or-1707-upgrade-node-name-mismatch

**Comment by badlop** [comment]
I cannot reproduce the problem. I installed 17.04, set as ERLANG_NODE ejabberd1704@localhost, started it. The installed 17.07 in another path, copied the Mnesia database files. The first time it complained. When I set the old ERLANG_NODE in ejabberdctl.cfg, it started correctly.

**Comment by t-animal** [comment]
I do not know what caused the problem, if it's not the upgrade vom 17.04 to 17.06. Anyway, if it does not affect other users, I guess it's a gremlin in my installation. I'll close this issue and if someone else does encounter it, it could be reopened.
