### ISSUE TITLE
Auto subscribe new group members

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1849]
> What version of ejabberd are you using?
17.04

When I add users to a roster they need to confirm in order to receive the messages.
How can i auto subscribe these users to the roster? So they are able to receive the message immediately

**Comment by badlop** [comment]
That is not implemented in ejabberd. Some clients have an option like "auto-accept subscription requests"

**Comment by PH-F** [comment]
Hi There!

In the documentation it states:

> A room moderator can subscribe another user to MUC Room events by providing the user JID as an attribute in the <subscribe/> element.
>https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#subscribing-to-muc-sub-events

This gives back a success message, but the user is not joined.
Does this mean something else?


Other question how can we prevent that a newly joined user sees the archive of the room messages? Is that perhaps possible?

Thank you in advance!

**Comment by badlop** [comment]
Ahh! You didn't specify what kind of subscription you were speaking about, I thought you were speaking about roster contacts subscriptions.

Now speaking about MUC/Sub room subscriptions: that feature requires 17.06 or higher, see commit https://github.com/processone/ejabberd/commit/c0eb85ce539a43ec7bf7114490bd68be780d4132 

> Other question how can we prevent that a newly joined user sees the archive of the room messages? Is that perhaps possible?

I think not possible.

**Comment by PH-F** [comment]
Thanks @badlop 

For ejabberd 17.06 is there a debian package available?

**Comment by badlop** [comment]
I guess the Debian, Ubuntu... distributions have their own packages. You can also find the generic ones published by ProcessOne in the Download Archive: https://www.process-one.net/en/ejabberd/archive/

**Comment by debalance** [comment]
I uploaded 17.07 to Debian Unstable today. It might take a few weeks before Backports for Jessie/Stretch are available. If you don't want to wait, you can head to https://jabber.at/p/apt-repository/.

**Comment by PH-F** [comment]
Thank you !
