### ISSUE TITLE
MUC/SUB List of subscriptions is empty

### ISSUE THREAD

**Issue by luciandragomir** [processone/ejabberd#1851]
> What version of ejabberd are you using?

17.04

I have two different client platforms (iOS and Web). Logged in with the same account on both of them. Created a permanent muc room and subscribed to the Muc/Sub events using iOS. When I query the list of subscriptions from iOS, I get the correct list, but when I do it from the Web it always gives me an empty list.

This is the message that gets sent from iOS:
```xml
<iq type='get' id='13b0ab83-8a06-4fd8-b5da-571f4a5d0193'
 from='myuser@chat-dev.my-host.com'
 to='conference.chat-dev.my-host.com'>
  <subscriptions xmlns='urn:xmpp:mucsub:0'/>
</iq>
```

On web the message is almost the same, the only difference being that the iq element has an extra attribute: _xmlns="jabber:client"_

My question is: Is this a bug or do I need to meet some preconditions to be able to retrieve the list of subscriptions (which are probably met on my iOS client, but not on Web)?

**Comment by luciandragomir** [comment]
After some more playing around, I managed to trigger this error in the logs when I subscribe to Muc/Sub events of a certain room. I think it is related to my first problem with getting the list of subscriptions.

`2017-07-12 11:43:49.673 [error] <0.10177.0> gen_fsm <0.10177.0> in state normal_state terminated with reason: no function clause matching mod_muc_room:process_iq_mucsub({jid,<<"234Albert">>,<<"chat-dev.my-host.com">>,<<"551635576199245942381878">>,<<"234albert">>,<<"...">>,...}, {iq,<<"9f9d42b2-af8c-4646-9536-9492e7f9c7b6">>,set,<<"en">>,{jid,<<"234Albert">>,<<"chat-dev.my-hos...">>,...},...}, {state,<<"f3e9a6e3-191e-4d55-9c3c-4e2cc019cea8">>,<<"conference.chat-dev.my-host.com">>,<<"chat-de...">>,...}) line 3710`

**Comment by badlop** [comment]
Hi, the query works for me, even when I add that xmlns, using 17.07.

I have no key about the problem, but I can give you general ideas to try, maybe you find some more clues when comparing your results:
* Try to login only one client at a time, either one or the other.
* Install a full desktop client, like Psi, Gajim or Tkabber, open their XML console, and send both queries manually.
* Install ejabberd 17.07 and a client in another machine, then play with those queries, is the problem reproducible?
* If all those tests give you no clue, you can try to set loglevel to 5, and search anything relevant when making the query with one or the other client.
* Regarding that error message, it is truncated by the logger module. If you find no clues, I'll provide you a patch to see the full error message.
