### ISSUE TITLE
This command can only be run by root or the user ejabberd

### ISSUE THREAD

**Issue by jarbelix** [processone/ejabberd#1855]
> What version of ejabberd are you using?

dpkg -i ejabberd_17.07-0_amd64.deb

> What operating system (version) are you using?

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.07/ejabberd_17.07-0_amd64.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

/opt/ejabberd-17.07/bin/start 
ERROR: This command can only be run by root or the user ejabberd
ERROR: This command can only be run by root or the user ejabberd

All commands were executed as root.
Until version 17.04 it worked perfectly.

**Comment by jarbelix** [comment]
```
grep ejabberd /etc/passwd
ejabberd:x:1001:1001::/opt/ejabberd-17.07:/bin/sh

grep ejabberd /etc/group
ejabberd:x:1001:

```

**Comment by ambernetas** [comment]
Same issue on Amazon Linux 201.07 and Centos 7 OS with 17.07

**Comment by jarbelix** [comment]
Worked perfectly. Thank you.

**Comment by cromain** [comment]
I have simplified the user check, dropping gid matching and opted for a simpler uid only approach as described in #1716
This case allows to run either by root or install_user (if defined) and only allow current user if install_user not defined (development install for example)
