### ISSUE TITLE
inet_dist_listen_min 4200 : command not found

### ISSUE THREAD

**Issue by ambernetas** [processone/ejabberd#1856]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Amazon Linux 2017.03

> How did you install ejabberd (source, package, distribution)?

Package (rpm)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
bash-4.2$ /opt/ejabberd-17.07/bin/ejabberdctl restart
/opt/ejabberd-17.07/bin/ejabberdctl: line 67: inet_dist_listen_min 4200 : command not found
```
when:
```
FIREWALL_WINDOW=4200-4201
```
Same issue was reported to FreeBSD bug list, so i think it's ejabberd issue:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220627

**Comment by badlop** [comment]
Should be fixed now.

**Comment by cromain** [comment]
thanks badlop, i have applied to packaging also
