### ISSUE TITLE
Question: bounced offline messages for offline_message_hook

### ISSUE THREAD

**Issue by IRog** [processone/ejabberd#1857]
> What version of ejabberd are you using?

HEAD

> What operating system (version) are you using?

Mac OS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I was wondering why offline messages to users were being classified as `bounce`? In an older version of ejabberd the `offline_message_hook(From, To, Packet) -> ok` would properly be called, but now it seems like an arity of 1 version of the same hook is being invoked with the message marked as bounced. Is this new behavior expected and the old hook documentation needs to be updated? This seems to happen both for muc subscriptions (groupchats) when 1 party is offline and also for direct messages when 1 party is offline.

Are there any situations when the older /3 version of the function will still be called?

**Comment by badlop** [comment]
> Are there any situations when the older /3 version of the function will still be called?

I think no, because that information can be easily obtained from the Packet nowadays, see https://github.com/processone/ejabberd/commit/8b2d3084986defd6045a0c02706415e0e7ae4b3f .

**Comment by IRog** [comment]
Thanks!
