### ISSUE TITLE
Problems when working with offline_msg database

### ISSUE THREAD

**Issue by jonator** [processone/ejabberd#1859]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Windows 10

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to request for offline messages from each user on log in.  Normally, messages sent to users that are offline are stored temporarily in offline_msg, then removed when requests are made with the 
`urn:xmpp:mam:1` namespace to the archive_msg DB.

That no longer is the case when I send eJabberd this stanza to get each header as an `<item>` element:
SENT:
```
<iq type='get'>
  <query xmlns='http://jabber.org/protocol/disco#items'
         node='http://jabber.org/protocol/offline'/>
</iq>
```
RECV:
```
<?xml version="1.0" encoding="UTF-8"?>
<iq xmlns="jabber:client" xml:lang="en" to="admin@ILLUM-TRISTAN/illuminate" from="admin@ILLUM-TRISTAN" type="result" id="f6aa40f1-6397-4b6f-9a79-a964b38e4115:sendIQ">
   <query xmlns="http://jabber.org/protocol/disco#items" node="http://jabber.org/protocol/offline">
      <item node="1499803420924000" name="jator@illum-tristan/pidgin" jid="admin@ILLUM-TRISTAN" />
      <item node="1499803428409000" name="jator@illum-tristan/pidgin" jid="admin@ILLUM-TRISTAN" />
      <item node="1499803430737000" name="jator@illum-tristan/pidgin" jid="admin@ILLUM-TRISTAN" />
   </query>
</iq>
```
I succesfully get the headers of who each message is from and how many, but when I use `urn:xmpp:mam:1` to request from archive_msg, the offline_msg DB doesn't update/clear.

Do you know if I am using the `http://jabber.org/protocol/offline` stanza incorrectly?

Any help is greatly appreciated!

**Comment by IRog** [comment]
I don't think the DB is supposed to update/clear https://xmpp.org/extensions/xep-0013.html

```2.5 Removing Specific Messages

A server MUST NOT remove a message simply because it has been requested by and delivered to the user; instead, the user must specifically request to remove a message.```

**Comment by zinid** [comment]
@IRog is right. If you don't want to receive any offline messages you can send any offline related request (like the number of offline messages) right before you're sending initial presence broadcast.
