### ISSUE TITLE
PID file /run/ejabberd/ejabberd.pid not readable (yet?) after start

### ISSUE THREAD

**Issue by jitchavan** [processone/ejabberd#1860]
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

https://www.digitalocean.com/community/tutorials/how-to-install-ejabberd-xmpp-server-on-ubuntu

> What did not work as expected? Are there error messages in the log? What

I'm trying to run ejabber service on ubuntu 16.04. This working fine but PID file not readable (yet?) after start.

Any idea what is going on?

But still giving issue ejabberd.service: PID file /run/ejabberd/ejabberd.pid not readable (yet?) after start

Please help to sort this issue.

Are there error messages in the log? 
>> sudo service ejabberd status
>> ejabberd.service - A distributed, fault-tolerant Jabber/XMPP serve
   Loaded: loaded (/lib/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-07-12 15:20:10 IST; 9s ago
  Process: 17154 ExecStop=/usr/sbin/ejabberdctl stop (code=exited, status=0/SUCCESS)
  Process: 17203 ExecStart=/usr/sbin/ejabberdctl start (code=exited, status=0/SUCCESS)
 Main PID: 17233 (beam.smp)
   CGroup: /system.slice/ejabberd.service
           └─17233 /usr/lib/erlang/erts-7.3/bin/beam.smp -K true -P 250000 -- -root /usr/lib/erlang -progname erl -- -ho

> was the unexpected behavior? What was the expected result?

service error.

**Comment by badlop** [comment]
It works correctly for me, compiling 17.07 from source code, installed, enabled the PID option in ejabberdctl.cfg, and when ejabberd starts, it creates the file readable by everybody.
Looking in the ejabberd change logs, I see nothing relevant between your 16.01 and my 17.07.

**Comment by cromain** [comment]
your question should target the ubuntu packagers instead. maybe they do handle the pid file differently than we do with our installer.
else, try to install 17.07 from our .deb package.

**Comment by Maysi2k** [comment]
I have the same Problem in Debian 9.

This tread is a top Google Search result!

**So here is the Solution:**

ejabberd have the default .PID file in:
`/run/ejabberd/ejabberd.pid`

But Debian and also Ubuntu is using this path:
`/var/run/ejabberd/ejabberd.pid`

Yes... pretty COOL!...

so you must edit the .cfg File from ejabberd (Debian /etc/ejabberd/ejabberdctl.cfg) and uncomment the Line **149**
`EJABBERD_PID_PATH=/var/run/ejabberd/ejabberd.pid`

so i hope it helps everyone.

Bye,
Maysi2k :)

**Comment by haegar** [comment]
But /var/run is a symlink to /run on default Debian, so this difference should not matter, as they target the same end-file...
