### ISSUE TITLE
Jitsi-videobridge

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1861]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

Something to work on the voice / video call conference for ejabberd.  I was looking at this jitsi-videobridge and seems that the repo can be include and setup on server side to install this jitsi-videobridge with other jitsi stuffs such as jitsi-meet and etc.

Want to ask does ejabberd supports this jitsi-videobridge?  How can i configure it on ejabberd.yml?

Thanks.

**Comment by weiss** [comment]
> Want to ask does ejabberd supports this jitsi-videobridge?

Yes.

> How can i configure it on ejabberd.yml?

An example listener configuration for a Jitsi Videobridge running on localhost might look like this:

    module: ejabberd_service
    port: 5275
    ip: "127.0.0.1"
    hosts:
      "jitsi-videobridge.jabber.fu-berlin.de":
        password: "t0t3lly-s3cr3t"

For more information, search [the documentation][1] for `ejabberd_service`.

[1]: https://docs.ejabberd.im/admin/configuration/
