### ISSUE TITLE
Retrieving TLS data

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#1864]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is there any way to retrieve the TLS data shown in the admin page for a user resource?
e.g.: tls://XXX.XX.XX.XX:32997#ejabberd@ip-XXX-XX-XX-XX

It is possible to retrieve registered users, online users, their resources, etc. but I'm not able to retrieve this TLS info and could be quite interesting.
Could you give me some advice?

**Comment by zinid** [comment]
Not, it's not possible, there are simply no functions providing information about TLS connection.
