### ISSUE TITLE
MAM Sync and Timestamps

### ISSUE THREAD

**Issue by econnolly** [processone/ejabberd#1865]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Any

> How did you install ejabberd (source, package, distribution)?

Any

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi.

I have been trying to understand how to use the MAM to sync message history when reconnecting a client. XEP-0313 states that messages in the archive should contain:
> A timestamp of when the message was sent (for an outgoing message) or received (for an incoming message).
> ...
> A server-assigned UID that MUST be unpredictable and unique within the archive.

ejabberd appears to use timestamps as the UIDs which do not meet the above criteria. With this approach is there not a chance, albeit slim, of duplicates occurring and this would be increased when running in a cluster.

While on the topic of clustering, where the system time could potentially vary between machines, could messages be archived in the wrong order? For example, say my client had last seen the message sent at '1500038380203' and then a new message gets added to the MAM by a node that was slightly behind time - at '1500038380103', when my client reconnects and queries the MAM it would miss the new message.

So I have two questions here:
1. Aren't timestamps the wrong thing to use as archive IDs?
2. Am I correct about the order of messages in the MAM and what recommendations do you have around clustering and time issues to ensure that clients do not miss messages? 

I couldn't find a section in the guide containing info about MAM -> client synchronisation.

Many thanks.

**Comment by zinid** [comment]
Making genuinely global clock in distributed systems is quite hard and isn't worth the effort. In practice using NTP synchronized local clocks is just fine. I also think that the XEP just sucks because it doesn't consider this problem.

**Comment by zinid** [comment]
Regarding using timestamps as indexes: using separate ID space will require additional database indexes which will increase database size and write delays.

**Comment by dhiru1602** [comment]
I think this issue is related to https://github.com/processone/ejabberd/issues/1845
