### ISSUE TITLE
Starting a module from OS command line

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1866]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Linux CentOS 7, AMD 64

> How did you install ejabberd (source, package, distribution)?

P1 binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

This is question, not a bug.
I have a module of mine, I'd like to check,compile,install and start it from a linux shell script without using the erlang console or restarting the whole ejabberd server:
- **ejabberdctl module_check mod_testunit**  [Module Check]
- **ejabberdctl module_upgrade mod_testunit** [upgrade previous version, **module_uninstall** and **module_install** do the same]
- **ejabberdctl modules_installed** [installed modules list]

Everything is fine until previous point, now I'd like to start mod_testunit (without parameters) from Linux command shell. Is there a way to do it ?
- I can manually start this module from **ejabberdctl debug** shell by issuing `gen_mod:stop_module(<<"xmppdomain.com">>,mod_testunit),gen_mod:start_module(<<"xmppdomain.com">>,mod_testunit,[]).` manually on erlang shell but I'd like to automate it in a linux bash script.
- I have tried `su -l ejabberd -c "/opt/ejabberd/bin/erl -sname 26939b7b-debug-ejabberd@localhost -remsh ejabberd@localhost -hidden +K true -smp enable +P 250000 -noshell -eval 'gen_mod:start_module(<<\"xmppdomain.com\">>,mod_testunit, []).' -s init stop"` but it doesn't work (even if `su -l ejabberd -c "/opt/ejabberd/bin/erl -sname 26939b7b-debug-ejabberd@localhost -remsh ejabberd@localhost -hidden +K true -smp enable +P 250000 -noshell -eval 'io:fwrite(\"HiThere\", []).' -s init stop"` works)
- same question, **-run** instead of **-eval** `su -l ejabberd -c "/opt/ejabberd/bin/erl -sname 26939b7b-debug-ejabberd@localhost -remsh ejabberd@localhost -hidtrue -smp enable +P 250000 -noshell -run gen_mod start_module \"xmppdomain.com\" mod_testunit"` but it doesn't work too

I need to start a module from linux shell, is there a way to do it ?

Thanks in advance for your reply

**Comment by badlop** [comment]
I think module_install compiles and starts the module itself:
```
$ ejabberdctl module_install mod_muc_log_http
/home/badlop/.ejabberd-modules/sources/
 ejabberd-contrib/mod_muc_log_http/src/mod_muc_log_http.erl:11:
 Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/home/badlop/.ejabberd-modules/sources/
 ejabberd-contrib/mod_muc_log_http/src/mod_muc_log_http.erl:11:
 Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
```
In the ejabberd logs I see immediately an indication that the module was started:
```
12:24:03.766 [warning] module 'mod_muc_log_http' doesn't export mod_opt_type/1
12:24:03.773 [warning] module 'mod_muc_log_http' doesn't export mod_opt_type/1
```
Then, in the WebAdmin, I see the module is started, and finally I attempt to use it and works.

For that to work, you must provide a conf/ dir with the corresponding template configuration file, next to your module src/ dir. See mod_muc_log_http or any other module as example.

**Comment by cromain** [comment]
As badlop said, module is started at install if you provide enough in the sources tree.
You can also try something like this
su -l ejabberd -c "/opt/ejabberd/bin/erl -sname 26939b7@localhost -noshell -eval 'rpc:call(ejabberd@localhost, gen_mod ,start_module, [<<\"xmppdomain.com\">>,mod_testunit, []]).' -s erlang halt"

**Comment by andreabenini** [comment]
I was trying the same thing you mentioned this morning, when a module is installed and loaded (from .yml conf file or from debug console) it works as shown above.
Problem arises when a module is totally new for the server or when it needs startup parameters on command line.
I have decided to rip off everything and instead of dealing with fancy flags or patching erl command line I have rewritten my code for loading my test module in a different way. Now it works and this is what I have done:
- module_check/install/load a dummy module (mod_testunit) for dynamically loading my test modules, I'm exposing register_commands/1 from there
- loaded it on a running system from debug console
Now to load and execute a brand new module 'mod_xyz' I can:
- Validate mod_xyz with module_check
- Install it version with module_install
- Use ejabberdctl and pass some parameters on command line, I'm using the command exposed from register_commands/1(on mod_testunit)
- automate/restart/rebuild my deploy from a linux batch file

PS: I'm not using it on a public production server to few security issue this procedure might arise

Thanks again
