### ISSUE TITLE
Could not reach into Web admin and client

### ISSUE THREAD

**Issue by pworldx** [processone/ejabberd#1870]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu 17.04 on google compute engine

> How did you install ejabberd (source, package, distribution)?

Binary installation

> What did not work as expected? Are there error messages in the log? What

Could not reach into web admin and client.

> was the unexpected behavior? What was the expected result?

After successfully configure my ejabberd.yml. I have successfully registered a user using ejabberdctl command.But both web admin and client is not coming.Suprisingly there is no ejabberd log also to provide.

**Comment by badlop** [comment]
There should be some log file, or at least a crash dump file. Otherwise, it means the server didn't start yet.

**Comment by pworldx** [comment]
Thanks @badlop for your reply...

I have found the problem..The problem is GCP blocks my external Ip address.
