### ISSUE TITLE
export_odbc not working properly

### ISSUE THREAD

**Issue by Sk8nn3r** [processone/ejabberd#1872]
> What version of ejabberd are you using?

ejabberd 14.07

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

Installed it with apt package manager

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to export my mnesia database so I can migrate to another host that will be using diferent domain name and SQL as a database

After running "ejabberdctl export_odbc myhostname.com /tmp/backup.sql"
I'm greeted with
```
Problem 'exit {aborted,{no_exists,[sql_pool,<<"myhostname.com">>]}}'
 occurred executing the command.
Stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,310}]},
             {ejabberd_odbc_sup,get_pids,1,
                                [{file,"src/ejabberd_odbc_sup.erl"},
                                 {line,81}]},
             {ejabberd_odbc_sup,get_random_pid,1,
                                [{file,"src/ejabberd_odbc_sup.erl"},
                                 {line,85}]},
             {ejabberd_odbc,sql_call,2,
                            [{file,"src/ejabberd_odbc.erl"},{line,143}]},
             {mod_privacy,export,1,[{file,"src/mod_privacy.erl"},{line,1164}]},
             {ejd2odbc,export,3,[{file,"src/ejd2odbc.erl"},{line,79}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
             {ejd2odbc,export,2,[{file,"src/ejd2odbc.erl"},{line,67}]}]"
```

**Comment by badlop** [comment]
ejabberd 14? I imagine this has been solved in the last 3 years. What other solution do you expect to receive, except using a more recent ejabberd version? BTW; nowadays the equivalent command is export2sql.

**Comment by Sk8nn3r** [comment]
First of all, thanks for contacting back.
I'm using ejabberd package from Debian 8 on a VPS. 14 is the latest version on the package manager, unless you upgrade it manually, which I do not know how to perform without losing user data.
Could you link me some material that explains how can I upgrade ejabberd without losing user data?
Cheers!

**Comment by Sk8nn3r** [comment]
I have managed to upgrade to the 16.09 using backports.
"ejabberdctl export2sql mydomain.com /tmp/base.sql" outputs an error again

"Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_announce_mnesia,export,[<<"mydomain.com">>],[]},
             {ejd2sql,export,3,[{file,"src/ejd2sql.erl"},{line,86}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,69}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,247}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,225}]}]"

**Comment by badlop** [comment]
Ah, in that case it's known: configure all the possible modules to use sql storage (even if your SQL database is still empty), then run again the command.
