### ISSUE TITLE
Ejabberd silently crashes

### ISSUE THREAD

**Issue by ivishnevsky** [processone/ejabberd#1874]
> What version of ejabberd are you using?

17.04.119

> What operating system (version) are you using?

Ubuntu 16.04.1 LTS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm testing Ejabberd server with Tsung.
Ejabberd is deployed in AWS on t2.micro instance.
MySQL is deployed on the same instance and used as a database for Ejabberd.
Tsung is deployed on separate t2.2xlarge instance.

The users are already created.
Scenario is very simple:
15000 users, arrive with 0,025s interval.
Each user connects, authenticates and waits (thinktime) 1000s.

In between 150-250 seconds after the test starts "ejaberdctl status" command starts showing "nodedown".
It is reflected in Tsung reports: errors start showing in big numbers at that moment (error_abort_max_conn_retries and error_connect_econnrefused)
Number of simultaneously connected users at that moment is in between 
6000-10000
The weirdest behaviour is shown on the "Transaction and page rate" graph. Authenticate transaction rate drops to 0 at about 100s and grows drastically just before the crash.

ejabberd.log doesn't contain any errors.
erl_crash.dump was not created

Why does Ejabberd crash?
Is it possible to configure Ejabberd not to crash, but rather return errors on connections it cannot handle? 
Why I don't see any logs about the crash in the ejabberd.log file?

Complete report (including tsung xml file):

[20170719-1012.zip](https://github.com/processone/ejabberd/files/1158825/20170719-1012.zip)

Some graphs:

![graphes-errors-rate](https://user-images.githubusercontent.com/10668036/28363542-367230c8-6c81-11e7-8a1f-93ef590180e8.png)
![graphes-transactions-rate](https://user-images.githubusercontent.com/10668036/28363562-49e741ac-6c81-11e7-962f-da62145d351b.png)
![graphes-users-simultaneous](https://user-images.githubusercontent.com/10668036/28363609-72035f36-6c81-11e7-90e1-a29d248a6cb2.png)

**Comment by ivishnevsky** [comment]
Tsung xml:

<?xml version="1.0"?><tsung loglevel="notice" dumptraffic="false" version="1.0">

    <clients>
        <client host="localhost" use_controller_vm="true" maxusers="300000">
        </client>
    </clients>

    <servers>
        <server host="10.10.22.205" port="5222" type="tcp"/>
    </servers>

    <load>
        <arrivalphase phase="1" duration="6" unit="minute">
            <users maxnumber="15000" interarrival="0.025" unit="second"/>
            <session_setup name="jabber-example" probability="100"/>
        </arrivalphase>
    </load>

    <options>
<option type="ts_jabber" name="userid_max" value="300000"/>
        <option type="ts_jabber" name="domain" value="loadtest.de"/>
        <option type="ts_jabber" name="username" value="tsung_rowe15_user"/>
        <option type="ts_jabber" name="passwd" value="tsung_pwd"/>
    </options>
    <sessions>
        <session probability="100" name="jabber-example" type="ts_jabber" bidi="true">
            <request>
                <jabber type="connect" ack="local"/>
            </request>

            <thinktime value="2"/>

            <transaction name="authenticate">
                <request>
                    <jabber type="auth_sasl" ack="local"/>
                </request>
                <request>
                    <jabber type="connect" ack="local"/>
                </request>
                <request>
                    <jabber type="auth_sasl_bind" ack="local"/>
                </request>
                <request>
                    <jabber type="auth_sasl_session" ack="local"/>
                </request>
            </transaction>

<thinktime value="1000"/>


<thinktime value="4"/>
        </session>
    </sessions>
</tsung>

**Comment by zinid** [comment]
Lots of useless info while not even ejabberd.yml is provided. Go figure.

**Comment by zinid** [comment]
Also, t2.micro is 1Gb of RAM? No way you can handle such amount of connections on this instance, good luck having 5000 there (especially when mysql is on the same machine).

**Comment by ivishnevsky** [comment]
Here's the yml file
[ejabberd.yml.zip](https://github.com/processone/ejabberd/files/1159072/ejabberd.yml.zip)

**Comment by ivishnevsky** [comment]
> Also, t2.micro is 1Gb of RAM? No way you can handle such amount of connections on this instance, good luck having 5000 there (especially when mysql is on the same machine).

I understand that there's some hardware limit for any type of instance. 
What I don't understand is: how can I prevent the crash?
And also how can I figure out the crash reasons from logs?
It would be very awkward situation if our server silently crashed in production.

**Comment by zinid** [comment]
> What I don't understand is: how can I prevent the crash when the limit is reached?

You cannot: once malloc() or friends return `NULL`, emulator is going to crash. This is actually a common problem of all software, not only of Erlang.

> It would be very awkward situation if our server silently crashed in production

There should be a crash dump. Try to run ejabberd and send it `SIGUSR1` signal. Do you have a `erl_crash.dump` somewhere generated?

**Comment by zinid** [comment]
Also, you didn't mention erlang version. OTP17.x had a bug which prevents crash dump from being generated.

**Comment by ivishnevsky** [comment]
> There should be a crash dump. Try to run ejabberd and send it SIGUSR1 signal. Do you have a erl_crash.dump somewhere generated?

Have tried this. No erl_crash.dump anywhere

> Also, you didn't mention erlang version. OTP17.x had a bug which prevents crash dump from being generated.

It's OTP 18

**Comment by ivishnevsky** [comment]
Do you have any idea how else I can fix/investigate the crash dump generation?

**Comment by zinid** [comment]
Try with empty erlang (i.e. `erl` command) first. Do you have the same effect? Try doing this from the same user. An erlang crash should occur in the directory where you started Erlang.

**Comment by zinid** [comment]
There is also a system variable for fine tuning, from `erl(1)` man page:
> ERL_CRASH_DUMP:
If the emulator needs to write a crash dump, the value of this variable is the filename of the crash dump file. If the variable is not set, the name of the crash dump file is erl_crash.dump in the current directory.

Try to set it in `ejabberdctl.cfg`.

**Comment by ivishnevsky** [comment]
> Try with empty erlang (i.e. erl command) first. Do you have the same effect? Try doing this from the same user. An erlang crash should occur in the directory where you started Erlang.

This works well, erl_crash.dump is created

> Try to set it in ejabberdctl.cfg.

This doesn't work :(
Thank you for the help though.
Do you have any other ideas?

**Comment by zinid** [comment]
My crystal ball tells me ejabberd doesn't have sufficient access to write a crash dump.

**Comment by zinid** [comment]
Attach to ejabberd using `ejabberdctl debug` and run:
```
>  file:get_cwd().
```
The crash dump should be created in this directory.

**Comment by ivishnevsky** [comment]
I did this. Now if I do 
`sudo kill -USR1 20854`
I get
`Crash dump is being written to: /usr/local/var/log/ejabberd/erl_crash_20170719-160549.dump...done`
`Received SIGUSR1`
And the file is there.

But when I run my load test and ejabberd stops working (nodedown) the debug console doesn't show anything. Furthermore, I can see the ejabberd process still running:

`$ ps aux | grep ejabberd`
`root     20845  0.0  0.2  55752  2160 pts/0    S+   16:05   0:00 sudo ejabberdctl debug`
`root     20846  0.0  0.1   4508  1472 pts/0    S+   16:05   0:00 /bin/sh /usr/local/sbin/ejabberdctl debug`
`root     20854  0.0  2.3 379760 24260 pts/0    Sl+  16:05   0:00 /usr/lib/erlang/erts-7.3/bin/beam -K true -P 250000 -- -root /usr/lib/erlang -progname erl -- -home /home/ubuntu -- -sname a21fbd0b-debug-ejabberd@localhost -smp auto -hidden -remsh ejabberd@localhost`
`ubuntu   20909  0.0  0.0  12916  1000 pts/2    S+   16:11   0:00 grep --color=auto ejabberd`

Shouldn't this process be terminated in case of insufficient memory?

**Comment by zinid** [comment]
In `ps` output you see debugging erlang shell, the one you have run with `ejabberdctl debug`. So the main process is not running. Also, you can find some info in `/var/log/messages`.

**Comment by ivishnevsky** [comment]
No, I mean this process:

`root 20854 0.0 2.3 379760 24260 pts/0 Sl+ 16:05 0:00 /usr/lib/erlang/erts-7.3/bin/beam -K true -P 250000 -- -root /usr/lib/erlang -progname erl -- -home /home/ubuntu -- -sname a21fbd0b-debug-ejabberd@localhost -smp auto -hidden -remsh ejabberd@localhost`

If I kill it, then the debugger will stop and show that a new dump file is created.

**Comment by zinid** [comment]
> I mean this process

I mean it too. This is NOT the main ejabberd process, it's an attached debug shell, you can see it by:
* name: `a21fbd0b-debug-ejabberd`
* args: `-hidden -remsh ejabberd@localhost`
