### ISSUE TITLE
Logs flooded with error

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1875]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
rhel

> How did you install ejabberd (source, package, distribution)?
src

All of sudden we see this error in logs server runs fine tho ...

2017-07-19 11:30:23 =ERROR REPORT====
** Generic server <0.8607.71> terminating 
** Last message in was {become_controller,undefined}
** When Server state == {state,#Port<0.19091815>,gen_tcp,none,undefined,65536,undefined,infinity}
** Reason for termination == 
** {badarg,[{fxml_stream,new,[undefined,65536],[]},{ejabberd_receiver,handle_call,3,[{file,"src/ejabberd_receiv
er.erl"},{line,167}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_ms
g,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2017-07-19 11:30:23 =CRASH REPORT====
  crasher:

**Comment by prefiks** [comment]
Seems to be duplicate of #1796, are you using version before 17.6?

**Comment by nOmi7** [comment]
yes its before 17.6 ..
Looks likes the issue is already fixed ... Any workaround before we go ahead and update it in prod.
And the reason why it occurred ?

**Comment by zinid** [comment]
The reason it occured is large refactoring in 17.x

**Comment by prefiks** [comment]
And this is usually result of client closing connection shortly after connecting

**Comment by zinid** [comment]
@prefiks exactly

**Comment by nOmi7** [comment]
Thanks for the clarifications 👍
