### ISSUE TITLE
Mailinglist is defunct

### ISSUE THREAD

**Issue by Quintus** [processone/ejabberd#1876]
The ejabberd mailinglist -- web page under http://lists.jabber.ru/mailman/listinfo/ejabberd -- appears to be defunct, i.e. doesn't work. I am subscribed since months and have successfully posted to it earlier, but when I recently tried to send a mail to the mailinglist on topic of root problems with `ejabberdctl`, it never showed up there. Also, there are no announcements about recent ejabberd versions on the mailinglist anymore. The [archive](http://lists.jabber.ru/pipermail/ejabberd/2017-June/thread.html) lists as the last processing date June 27th, 2017. No newer messages ever hit the mailinglist.

Can somebody please look into this?

**Comment by zinid** [comment]
I think we just need to close the mailing list. It's virtually unused and is not owned by ProcessOne (due to historical reasons), so we cannot maintain it properly.

**Comment by zinid** [comment]
Regarding your problem: you can open an issue with the description here.

**Comment by Quintus** [comment]
As of today, the mailinglist has started to work again. I got a bunch of
old emails at once (including my post), probably someone flushed the
mailqueue after setting things right.

I'll later open an issue on my ejabberdctl problem here if I get no
answers on the mailinglist.
