### ISSUE TITLE
Setting vars.config when ejabberd is a mix dependency

### ISSUE THREAD

**Issue by johnhamelink** [processone/ejabberd#1878]
> What version of ejabberd are you using?

https://github.com/leeicmobile/ejabberd (recently merged with master)

> What operating system (version) are you using?

Arch Linux (Linux 4.11.9-1-ARCH)

> How did you install ejabberd (source, package, distribution)?

Ejabberd is being used as a mix package inside an elixir umbrella app.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When deploying to production, we specify the use of odbc in order to connect to a postgres database. In 17.x, the `vars.config` file was introduced. The only way to set this seems to be to have a vars.config file inside the directory of the dependency at the time that `mix deps.get` is run. We've had to make a fork of `ejabberd` just to include that file.

**Comment by cromain** [comment]
You don't need a fork for this.
If you need to configure ejabberd when used as mix dependency, simplest process to have a local version of your ejabberd configuration and let your Makefile do something like:

deps:
    $(MIX) deps.get ejabberd
    @(cp ejabberd.vars deps/ejabberd/vars.config)
    $(MIX) deps.get

**Comment by johnhamelink** [comment]
@cromain that's not a very satisfying solution to this problem to be honest:

 - Why must ejabberd's configuration be so custom compared with any other package out there? For configuration of optional dependencies, [there is already a way in mix to specify](https://elixirforum.com/t/elixir-proposal-optional-dependencies-for-deploy/3334/2).
 - If the configuration file is absolutely necessary, then why can't its path be specified so that it can at least go in the umbrella's config directory like every other config file?
 - Why is the format of the vars.config file different to the ejabberd.yml config file which is already required?

**Comment by warex03** [comment]
@johnhamelink did you find an alternative way of doing this? Im stuck in the same situation

**Comment by johnhamelink** [comment]
@warex03 no I didn't, we're using a fork right now. We'd very much rather not have one.
