### ISSUE TITLE
get the chat conversations data from mysql

### ISSUE THREAD

**Issue by kapil-bharadwaj** [processone/ejabberd#1879]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?
ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

source version 17.07 with enabling mysql 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hello,
I have configured ejabberd 17.07 with mysql enabled. I am building a chat app.Now i want to get chat conversations from mysql. So i want know where my chat converstaion is stored on database? I can see some tables in configured mysql schema but i am not able to get where message conversation are? I go through some modules like mod_mam,mod_archive but they are not in my admin panel of ejabberd and i do not know how they will help me to achieve my task.so please guide me how can i get my chat data between users and offline messages.
I will be using node.js to fetch data from mysql after seeing where is data being stored.
Any help will be highly appreciated.

**Comment by badlop** [comment]
mod_mam stores stanzas in the SQL table "archive".

**Comment by kapiloodles** [comment]
thanks for replying. but when i check table "archive" in mysql database. it is empty. and there is no table for offline messages in database. i can see a module in mod_mam on my ejabberd admin panel. i am using smack 4.2 libraries on android to chat.

**Comment by kapiloodles** [comment]
if i use mnesia as my database then how can i make a connection to mnesia and get the data from the tables ? by using mysql and updating my ejabberd version from 2.1 to 17.07, i am getting a error when try to register a user from smack api on android devic. the error is as follow:
Connection XMPPTCPConnection[not-authenticated] (5) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: not-authorized You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1046)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980)
at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996)
at java.lang.Thread.run(Thread.java:818)
07-24 16:08:05.668 21112-3080/com.oodles.apprtcandroidoodles E/ExceptionException: org.jivesoftware.smack.SmackException$NotConnectedException: The connection XMPPTCPConnection[not-authenticated] (5) is no longer connected while waiting for response with StanzaIdFilter: id=jq6OD-18

i tried but can not found the reason of this error.so
if anyone can suggest a way out what should i do now then it will be highly appreciated.

**Comment by badlop** [comment]
> thanks for replying. but when i check table "archive" in mysql database. it is empty.

Make sure mod_mam is configured to use sql storage.

> and there is no table for offline messages in database. 

The SQL table used by mod_offline is called "spool". Also make sure mod_offline is configured to use sql db_type.

> if i use mnesia as my database then how can i make a connection to mnesia and get the data from the tables ?

That is a lot harder than using SQL. If you have experience with SQL, and really want to read the table contents, continue using SQL storage.

> by using mysql and updating my ejabberd version from 2.1 to 17.07, i am getting a error when try to register a user from smack api on android devic. the error is as follow:

Maybe mod_register is disabled. Or it is enabled, but does not accet new registrations. Or accepts new registrations, but there' some problem in your client or library.

**Comment by cromain** [comment]
also, when upgrading make sure you follow the procedures:
https://docs.ejabberd.im/admin/upgrade/
