### ISSUE TITLE
17.6 hex package as embedded elixir project wont resolve

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#1880]
> What version of ejabberd are you using?

17.06

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

hex distribution as embedded elixir project

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

$ mix deps.get 

Failed to use "fast_tls" (versions 1.0.1 to 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.1) requires 1.0.0

Failed to use "fast_tls" (versions 1.0.13 and 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.2) requires 1.0.1

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.10) requires 1.0.10

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.11) requires 1.0.11

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.12) requires 1.0.12

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.13) requires 1.0.13

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.3) requires 1.0.2

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.4) requires 1.0.3

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.5) requires 1.0.4

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.6) requires 1.0.5

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.7) requires 1.0.6

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.8) requires 1.0.7

Failed to use "fast_tls" (version 1.0.15) because
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.9) requires 1.0.8

Failed to use "p1_utils" (versions 1.0.0, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.9) because
  cache_tab (version 1.0.1) requires 1.0.1
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.1) because
  cache_tab (version 1.0.1) requires 1.0.1
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.1) requires 1.0.3

Failed to use "p1_utils" (version 1.0.7) because
  cache_tab (versions 1.0.8 to 1.0.10) requires 1.0.9
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (version 1.0.2) requires 1.0.3
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (version 1.0.3) requires 1.0.4
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (version 1.0.4) requires 1.0.5
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (versions 1.0.5 and 1.0.6) requires 1.0.6
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (version 1.0.7) requires 1.0.7
  ejabberd (version 17.6.0) requires ~> 1.0

Failed to use "p1_utils" (version 1.0.9) because
  cache_tab (versions 1.0.8 to 1.0.10) requires 1.0.9
  ejabberd (version 17.6.0) requires ~> 1.0
  esip (version 1.0.1) requires 1.0.3

**Comment by cromain** [comment]
this has been fixed since 17.06
you should build from HEAD or wait 17.08
