### ISSUE TITLE
17.07 anonymous login request responds with not-authorised 

### ISSUE THREAD

**Issue by kishoreacesurf** [processone/ejabberd#1882]
> What version of ejabberd are you using?
17.07 

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
Anonymous auth is being tested in Travis, so I assume it works.
