### ISSUE TITLE
Simplify the configuration of multiple services of the same category on the same domain

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1883]
> What version of ejabberd are you using? 17.06
> What operating system (version) are you using? Debian Stable
> How did you install ejabberd (source, package, distribution)? Package from ProcessOne website

Configuring several services of the same category (MUC, Pubsub…) under the same domain is not very simple and requires a "hack" in the ejabberd.yml file, see https://github.com/movim/movim/wiki/Configure%20ejabberd#how-to-configure-multiple-pubsub-services-on-one-domain

It could be really useful for Pubsub services (pubsub.domain.tld, comments.domain.tld, weather.domain.tld…).

On Prosody it can actually be done in 2 lines.

> Component "comics.movim.eu" "pubsub"
>    name = "Comics feeds"
> Component "sport.movim.eu" "pubsub"
>    name = "Sport feeds"

Is there a way to simplify this configuration maybe by declaring an alias?

**Comment by zinid** [comment]
We can make `host` option accepting a list of names. Would it be ok?

**Comment by edhelas** [comment]
Yeah seems fine, so the end result will look similar to this?
```
modules:
  mod_pubsub:
    host:
      - "sports.@HOST@"
      - "comics.@HOST@"
      - "pubsub.@HOST@"
```

**Comment by zinid** [comment]
Almost. We discussed the feature and decided to keep `host` option for a single host only, while new `hosts` option will accept a list of hosts.

**Comment by edhelas** [comment]
It's ok for me :) Thanks!
