### ISSUE TITLE
Cannot Login After Install - Win7

### ISSUE THREAD

**Issue by ejabnoob** [processone/ejabberd#1884]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

EXE from downloads page

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Install went as expected.  Service starts.  I am able to navigate to http://localhost:5280/admin and get the login prompt.  Login never works.  I check my config file and my ACL shows I am using the correct user (admin@sac-ejabberd01) and that my host is set to the same domain.  

What am I doing wrong for a LAN ejabberd setup that I cannot log into the portal?

When I set it up as admin@blahblah.com, then I am able to log in but my clients then cannot find the host.

Thanks in advance.

**Comment by ejabnoob** [comment]
Looks like this issue is related to #1231 and still an issue.  I'm testing with older versions and it appears to work.

**Comment by ejabnoob** [comment]
Still not working.  How does one manually add an admin user in 17.07 without being able to log into the web GUI?

**Comment by badlop** [comment]
> How does one manually add an admin user in 17.07 without being able to log into the web GUI?

First register the account, for example using the ejabberdctl script:
> ./bin/ejabberdctl register noob example.com somepass

Then edit ejabberd.yml, and add a line in the proper place to give that JID admin rights. There should be already a line grating admin rights to another account, added by the installer... use that as example or see examples in the ejabberd Guide.
