### ISSUE TITLE
SIP compatibility with erlang 20

### ISSUE THREAD

**Issue by p5n** [processone/ejabberd#1885]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Archlinux

> How did you install ejabberd (source, package, distribution)?

from Archlinux repo
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

SIP registration fails, I fixed it but it looks like ejabberd has other issues with recent (20+) erlang

I was able to fix registration using this change:

https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ejabberd&id=27662837f7859b7c6766515f4345ba831fe1cbfa

> REQUIRE_ERLANG_MAX="9.0.1"

and

> sed -i 's|crypto:rand_bytes|crypto:strong_rand_bytes|g' deps/esip/src/esip.erl

But ejabberd anyway works strange with SIP and prints no error messages.

I configured it as

```
  mod_sip:
    always_record_route: true
```

**Comment by zinid** [comment]
I just checked it against OTP20. And while `REQUIRE_ERLANG_MAX` should be obviously fixed (though this is not related to mod_sip), I have mod_sip itself working, at least I pinged it using `sipsak` and it pongs.

**Comment by p5n** [comment]
crypto:rand_bytes vs crypto:strong_rand_bytes issue affects register request as I understand. sipsak probably does not do it.

**Comment by zinid** [comment]
Fixed via https://github.com/processone/esip/commit/a4e6a8f6a66836f62471f7fb6df3cc590689fdfa
