### ISSUE TITLE
auto-subscribe

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1887]
> What version of ejabberd are you using?
17.04 with mysql on debian 8

When I add users to a room I want them to be a participant immediately.
I see they end-up in the spool table. I create a trigger to add as a participant to muc_room.

However i'm only able to see them after i restart ejabberd.
Is there some cache i can clear? Of some command I can call?

Thank you in advance!

**Comment by badlop** [comment]
> When I add users to a room I want them to be a participant immediately.

"add user" is a vague term. Add to a list? Which list? How do you do it?

**Comment by PH-F** [comment]
I add a subscribers to a muc_room.
The subscriber will be in the room when he/she comes online. 

In the database I see that the subscriber is listed in the spool table.
<message to='...' from='...@conference.....' xmlns='jabber:client'>........<body xml:lang='en'>USER ... invites you to the room ....@conference..... (Welcome!) </body></message>

With a trigger I update the muc_room
subscribers,[....]

And this actually does work, but I need to restart ejabberd until the clients see it. I think there is some cache somewhere but i don't know how to clean it.

I hope you can help me.

**Comment by badlop** [comment]
> With a trigger I update the muc_room

I guess you modify the internal state, but you don't perform all the corresponding tasks, like sending that new information to other occupants (send presence stanzas), and also send own presence to own user, etc. When possible, use already existing functions, or even better, ejabberd commands.
