### ISSUE TITLE
Permission issues on New Installation

### ISSUE THREAD

**Issue by mhaseeb-seecs** [processone/ejabberd#1891]
> What version of ejabberd are you using?

ejabberd-17.07-linux-x86_64

> What operating system (version) are you using?

```
# rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
```

> How did you install ejabberd (source, package, distribution)?

I tried to install following Packages. 
* ejabberd-17.07-linux-x86_64-installer.run
* ejabberd-17.07-0.x86_64.rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to install it. Both packages are installed successfully. But when i try to start the service. i ended up with following error. Have checked log but it have only successful installation message out there .

I have installed it as root user in following directory: /opt/ejabberd/

> ERROR: This command can only be run by root or the user ejabberd

**Comment by cromain** [comment]
This is i known issue when ejabberd is installed as root. It has been fixed for 17.08.
Until next release is out, you can install ejabberd with our binary installer, as ejabberd user.
