### ISSUE TITLE
MUC data not storing in MySQL db

### ISSUE THREAD

**Issue by shazvan275** [processone/ejabberd#1893]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

ejabberd-17.07-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

am using sql database everything is working fine. but in muc datas are not storing in mysql database
and i will not find any error in log files.

**and this is my yml config:**
mod_muc:
    host: "conference.@HOST@"
    db_type: odbc
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
**in my log its showing:**
@mod_muc_room:init:136 Created MUC room dgh@conference.localhost by dev@localhost/1753709772139808518536

**

> but data is not storing in mysql database... other than this mam and other data are storing in mysql db

**

**Comment by zinid** [comment]
Only persistent rooms are stored on disc. Make sure a client is making a room persistent upon/after creation.

**Comment by shazvan275** [comment]
thanks for your reply 

after making persistent rooms data storing in "muc_room" table but not in the "muc_registered" table

**Comment by zinid** [comment]
`muc_registered` is only for MUC nick registrations (one should register a nick, globally per the MUC service).
