### ISSUE TITLE
Problem starting the module mod_muc

### ISSUE THREAD

**Issue by shazvan275** [processone/ejabberd#1894]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

ejabberd-17.07-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

*am using oracle database through odbc

after creating a persistent rooms data are stored in  "muc_room" table and working fine but when i restart a server it producing following error:

017-07-30 14:06:37.832 [error] <0.447.0>@ejabberd_sql:decode_term:252 CRASH REPORT Process <0.447.0> with 0 neighbours exited with reason: no match of right hand value {error,{1,erl_scan,{string,34,"test33\">>},\n {de"}},1} in ejabberd_sql:decode_term/1 line 252 in gen_server:init_it/6 line 352
2017-07-30 14:06:37.832 [critical] <0.322.0>@gen_mod:start_module:211 Problem starting the module mod_muc for host localhost 
 options: [{db_type,sql},
           {access,[{allow,[all]}]},
           {access_admin,[{allow,[{acl,admin}]}]},
           {access_create,muc_create},
           {access_persistent,muc_create}]
 error: {error,{{{badmatch,{error,{1,erl_scan,
                                   {string,34,"test33\">>},\n {de"}},
                                  1}},
                 [{ejabberd_sql,decode_term,1,
                                [{file,"src/ejabberd_sql.erl"},{line,252}]},
                  {mod_muc_sql,'-get_rooms/2-fun-3-',2,
                               [{file,"src/mod_muc_sql.erl"},{line,110}]},
                  {lists,map,2,[{file,"lists.erl"},{line,1239}]},
                  {mod_muc,load_permanent_rooms,6,
                           [{file,"src/mod_muc.erl"},{line,610}]},
                  {mod_muc,init,1,[{file,"src/mod_muc.erl"},{line,237}]},
                  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,247}]}]},
                {child,undefined,mod_muc_localhost,
                       {gen_server,start_link,
                                   [{local,mod_muc_localhost},
                                    mod_muc,
                                    [<<"localhost">>,
                                     [{db_type,sql},
                                      {access,[{allow,[all]}]},
                                      {access_admin,[{allow,[{acl,admin}]}]},
                                      {access_create,muc_create},
                                      {access_persistent,muc_create}]],
                                    []]},
                       transient,60000,worker,
                       [mod_muc]}}}
[{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,202}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,78}]},
 {supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
 {supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},
 {supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},
 {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
2017-07-30 14:06:37.832 [critical] <0.322.0>@gen_mod:maybe_halt_ejabberd:293 ejabberd initialization was aborted because a module start failed.

[erl_crash_20170730-141943.dump.txt](https://github.com/processone/ejabberd/files/1185602/erl_crash_20170730-141943.dump.txt)

[crash.log.txt](https://github.com/processone/ejabberd/files/1185606/crash.log.txt)

**When i delete a room records from a database ejabber working fine...**

thanks in advance

**Comment by shazvan275** [comment]
#1893

**Comment by zinid** [comment]
There is a record in `muc_room` table which ejabberd is unable to parse.

**Comment by shazvan275** [comment]
i have tried with various format but its unable to parse pls help me...

and my oracle table schema 

`  CREATE TABLE "ESATBUSINESS"."MUC_ROOM" 
   (	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HOST" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"OPTS" CLOB NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESATBUSINESS" 
 LOB ("OPTS") STORE AS SECUREFILE (
  TABLESPACE "ESATBUSINESS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;`

**Comment by cleon-hillwood** [comment]
Did this get resolved? I am seeing the exact same behaviour where a persistent room created using rest api cannot be loaded (causes crash) after restart.

**Comment by licaon-kter** [comment]
@cleon-hillwood With 18.04?

**Comment by cleon-hillwood** [comment]
@licaon-kter  - Thanks for responding. I am actually using an old version 16.09 and will be looking to upgrade in the future. That said I believe I figured out the issue as it appears the "opts" data that gets persisted in the  muc_room table is different if you use the **ejabberedctl** command, vrs the **rest api,** vrs sending "**presence**" xmpp xml to enter the room.  When restarting the ejabberd node I get a crash for rooms created using rest or presence. I do not get a crash when room created using ejabberdctl.  For my purposes the rooms are persistant and static so I can create them using ejabberedctl as I do not allow end users to create their own rooms.  If I see the same behaviour after I upgrade to the latest version I will initiate a new issue with more details on how to recreate. thanks again for responding.

**Comment by Neustradamus** [comment]
@shazvan275 @cleon-hillwood @softctrl All works with OracleDB and last ejabberd?
It will be nice to have a module in ejabberd-contrib if not in ejabberd directly ^^
https://github.com/softctrl/ejabberd-oracle-odbc
