### ISSUE TITLE
ejabberd chokes on unicode resource names

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#1896]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu 16.04 LTS

> How did you install ejabberd (source, package, distribution)?

package

> Reproduce:

Connect to a MUC room, attempt to nick to "🐎" (`U+1F40E`) by sending presence to `room@conference.example.com/🐎`

Expected: It either works (as per the updated standards [RFC-7622 - 3.4 Resourcepart](https://tools.ietf.org/html/rfc7622#section-3.4), [RFC-7613 - 4.2 OpaqueString](https://tools.ietf.org/html/rfc7613#section-4.2) and [RFC-7564 - 4.3 FreeFormClass](https://tools.ietf.org/html/rfc7564#section-4.3), which permits codepoints classed as "Other Symbols" in resource parts), or returns an error stanza if using the old RFC-6122.

The error stanza should strictly speaking be `jid-malformed` I guess, but in ejabberd 16.12 I got a `bad-request` at least.

Actual: Server closes the connection. From what I can tell, this is a regression between 16.12 and 17.07, since the server used to return an error but keep the connection open.

**Comment by zinid** [comment]
What, just silently closes the connection? There should be at least stream error.

**Comment by cburschka** [comment]
I'm testing this via websocket, and basically don't get anything except a `<close>`:

Sucessful nick change:

```xml
  <presence xmlns="jabber:client" from="username@example.com/cadence/otydc0" to="room@conference.example.com/abc">
    <c xmlns="http://jabber.org/protocol/caps" node="cadence" ver="sc5sapABJ2DGQpy/1caCyQnpgZM=" hash="sha-1"/>
  </presence>
  <presence xmlns="jabber:client" to="username@example.com/cadence/otydc0" from="room@conference.example.com/username" type="unavailable">
    <x xmlns="http://jabber.org/protocol/muc#user">
      <item nick="abc" jid="username@example.com/cadence/otydc0" role="moderator" affiliation="owner"/>
      <status code="303"/>
      <status code="110"/>
    </x>
  </presence>
  <presence xmlns="jabber:client" xml:lang="en" to="username@example.com/cadence/otydc0" from="room@conference.example.com/abc">
    <c xmlns="http://jabber.org/protocol/caps" node="cadence" ver="sc5sapABJ2DGQpy/1caCyQnpgZM=" hash="sha-1"/>
    <x xmlns="http://jabber.org/protocol/muc#user">
      <item jid="username@example.com/cadence/otydc0" role="moderator" affiliation="owner"/>
      <status code="110"/>
    </x>
  </presence>
```

Failed nick change:
```xml
  <presence xmlns="jabber:client" from="username@example.com/cadence/otydc0" to="room@conference.example.com/&#x1F40E;">
    <c xmlns="http://jabber.org/protocol/caps" node="cadence" ver="sc5sapABJ2DGQpy/1caCyQnpgZM=" hash="sha-1"/>
  </presence>
  <close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>
```

Here are ejabberd.log excerpts with `loglevel: 5` for both of the events:

[success.txt](https://github.com/processone/ejabberd/files/1187422/success.txt)
[failure.txt](https://github.com/processone/ejabberd/files/1187421/failure.txt)

The `error.log` file also has these three entries:

```
2017-07-31 11:45:05.699 [error] <0.2628.0>@jid:tolower:203 gen_server <0.2628.0> terminated with reason: no function clause matching jid:tolower(error) line 203
2017-07-31 11:45:05.701 [error] <0.2628.0>@jid:tolower:203 CRASH REPORT Process <0.2628.0> with 0 neighbours exited with reason: no function clause matching jid:tolower(error) line 203 in p1_server:terminate/7 line 878
2017-07-31 11:45:05.702 [error] <0.2614.0>@jid:tolower:203 Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.2628.0> exit with reason no function clause matching jid:tolower(error) line 203 in context child_terminated
```

And the `crash.log` has this: [crash.txt](https://github.com/processone/ejabberd/files/1187441/crash.txt)

**Comment by prefiks** [comment]
This jid is marked as invalid because stringprep thinks that emoji character belongs to class that is not allowed in resources, i am checking if we need to update our unicode tables

**Comment by cromain** [comment]
emoji class it not accepted for resource, and there is nothing in RFC which suppose this to be supported. We won't add this class in the parser.

**Comment by cburschka** [comment]
> there is nothing in RFC which suppose this to be supported.

I linked the relevant RFCs (7622, 7613, 7564) above. Or do you mean the now-superseded 6122 standard?
