### ISSUE TITLE
Problem connecting to Ejabberd Server

### ISSUE THREAD

**Issue by OmPrakash95** [processone/ejabberd#1897]
> What version of ejabberd are you using?

ejabberd 17.07.30 

> What operating system (version) are you using?

Ubuntu 14.04 LTS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log?

I tested my Ejabberd server using one of the XMPP Client ( JWCHAT.org) and it was working fine. I did benchmark test using Jabsimul as mentioned in https://www.ejabberd.im/benchmark
The jabsimul created 150 users/second which exceed the max set value i.e 100 users per second ( I didn't set this explicitly).

I tried connecting my XMPP Client to Ejabberd server and I got the following exception:
    [error] gen_server <0.547.0> terminated with reason: bad arithmetic expression in shaper:update/2 line 140
    [error] CRASH REPORT Process <0.547.0> with 0 neighbours crashed with reason: bad arithmetic expression in shaper:update/2 line 140

Below is my crash.log

    =ERROR REPORT====
    ** Generic server <0.547.0> terminating
    ** Last message in was {tcp,#Port<0.14324>,<<"<starttls xmlns=\"urn:ietf:params:xml:ns:xmpp-tls\"/>">>}
    ** When Server state == {state,#Port<0.14324>,gen_tcp,{maxrate,[{maxrate,10000}],0.0,1501504312553182},<0.548.0>,65536,#Ref<0.347039508.4057333$
    ** Reason for termination ==
    ** {badarith,[{shaper,update,2,[{file,"src/shaper.erl"},{line,140}]},{ejabberd_receiver,process_data,2,[{file,"src/ejabberd_receiver.erl"},{lin$
    =CRASH REPORT====
      crasher:
        initial call: ejabberd_receiver:init/1
        pid: <0.547.0>
        registered_name: []
        exception error: {badarith,[{shaper,update,2,[{file,"src/shaper.erl"},{line,140}]},{ejabberd_receiver,process_data,2,[{file,"src/ejabberd_r$
        ancestors: [<0.333.0>,ejabberd_listener,ejabberd_sup,<0.67.0>]
        message_queue_len: 1
        messages: [{'$gen_call',{<0.548.0>,#Ref<0.347039508.4057202689.16086>},{starttls,{tlssock,#Port<0.14324>,#Ref<0.347039508.4057333761.16085>$
        links: []
        dictionary: []
        trap_exit: false
        status: running
        heap_size: 987
        stack_size: 27
        reductions: 707
       neighbours:

The error says that a bad arithemtic exception has occurred in Shaper.erl line 140. but i never edited that file and all these happened only after the Registration Limit exceeded the Maximmum set value i.e. 100

In my ejabberd.yml i've set the Shaper "normal" maxrate to 10000 and Shaper "fast" to 50000.

May I know what could be the fix for this problem?

> was the unexpected behavior? What was the expected result?

**Comment by alexeyshch** [comment]
It's probably a configuration issue, as in the c2s state `maxrate=[{maxrate,10000}]`, while it should be `maxrate=10000`.

**Comment by OmPrakash95** [comment]
Below is my ejabberd.yml SHAPER RULES Section
    ###.  ============
    ###'  SHAPER RULES
    
    shaper_rules:
      ## Maximum number of simultaneous sessions allowed for a single user:
      max_user_sessions: 10
      ## Maximum number of offline messages that users can have:
      max_user_offline_messages:
        - 5000: admin
        - 100
      ## For C2S connections, all users except admins use the "normal" shaper
      c2s_shaper:
        - none: admin
        - normal
      ## All S2S connections use the "fast" shaper
      s2s_shaper: fast

the **c2s_shaper** is set to **normal** and it points to **TRAFFIC SHAPERS** section which looks like this:

    ###.  ===============
    ###'  TRAFFIC SHAPERS
    
    shaper:
      ## 
      ## The "normal" shaper limits traffic speed to 10000 B/s
      ##
      normal:
        maxrate: 10000
    
      ##
      ## The "fast" shaper limits traffic speed to 50000 B/s
      ##
      fast: 50000
    
    ##
    ## This option specifies the maximum number of elements in the queue
    ## of the FSM. Refer to the documentation for details.
    ##
    max_fsm_queue: 1000
 
The **Maxrate** of **normal** here is already set to 10000 but still, I get this Bad arithmetic error when i connect my XMPP Client to the server.

**Comment by alexeyshch** [comment]
Please replace
```
      normal:
        maxrate: 10000
```
with
```
      normal: 10000
```

**Comment by OmPrakash95** [comment]
Thanks. Now I'm able to connect to the Server. May I know what caused the reason to fail? because it was running fine with `normal: maxrate: 10000` before.

**Comment by alexeyshch** [comment]
AFAIR there was a compatibility code for the old `ejabberd.cfg` format, and it's now gone.
