### ISSUE TITLE
mnesia -> mysql : success export, but have an error

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#1898]
> What version of ejabberd are you using?

ejabberd 17.07

> What operating system (version) are you using?

ubuntu16.04

> How did you install ejabberd (source, package, distribution)?

package

I add `db_type : sql` to all of modules and set mysql argument.
Then i run `ejabberdctl export2sql xmpp.com /tmp/example.sql`,
and i got an error 
```
Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_mam_mnesia,export,[<<"xmpp-stg.example.com">>],[]},
             {ejd2sql,export,3,[{file,"src/ejd2sql.erl"},{line,86}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
             {ejd2sql,export,2,[{file,"src/ejd2sql.erl"},{line,69}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,352}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,321}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,249}]}]
```

but i check the /tmp/example.sql
```
-- 
-- Mnesia table: passwd
--
delete from users where username='admin2';
insert into users(username, password) values ('admin2', 'admin');
delete from users where username='admin';
insert into users(username, password) values ('admin', 'admin');
```

Does it successful?
Indeed, i only use ejabberdctl to add two users.
So, could i use this example.sql to mysql db?

**Comment by badlop** [comment]
The error says that ejabberd is trying to export the MAM table to SQL, but you didn't configure mod_mam to use sql. Configure it and repeat the export. Then it may complain about some other module. Repeat until it doesn't complain. Of course, later, you can switch back to mnesia the modules that you don't want to store in SQL; all this export is only to make sure ejabberd export to SQL all the tables it can export, later you can decide which ones to import in SQL...

**Comment by jhaoheng** [comment]
@badlop 
very very thanks your help!
No any errors.
Thanks a million! 

So i update the steps `how to export mnesia to sql, version 17.07`
1. add `mod_mam` to module
2. Add `db_type: sql` to  all modules that you used. 
3. Restart ejabberd.
4. exec `./ejabberdctl export2sql <host> /tmp/example.sql`
    - notice : <host> is set in ejabberd.yml : hosts
