### ISSUE TITLE
unable to unregister a user with a capital in the username

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1900]
> What version of ejabberd are you using?

17.07 with mysql

Apparently registered users are stored in mnesia
When I run 
> ejabberdctl unregister usernameWith-a-Capital host

The user is not deleted. users with only lowercase are.
In my case i could just stop ejabberd remove the mnesia database and restart because all data is in mysql anyway.

**Comment by badlop** [comment]
From what I see, ejabberd_auth:try_register/3 calls db_try_register with the original username, not the lowercased-prepared username: https://github.com/processone/ejabberd/blob/master/src/ejabberd_auth.erl#L263

So, in the database (Mnesia or SQL), the username gets stored with the case originally provided when registering. Later, when trying to unregister, this case may not match, and the account isn't found and isn't deleted.

**Comment by cromain** [comment]
@badlop it looks like desired behaviour. When registering user with capital letters, you must use same name when unregistering.

**Comment by PH-F** [comment]
That is what I tried but unregistering a user with a capital is not possible. 
It does not give an error, but the user just does not disappear.

e.g. I have 2 users Patrick and peter
`ejabberdctl unregister peter host  >> that works
ejabberdctl unregister Patrick host  >> does not disappear`

Other users with only lowercase can be unregistered.
In my setup i use also mysql, not sure it this has anything to do with it.

**Comment by cromain** [comment]
i can reproduce with mnesia backend

**Comment by vhatzist** [comment]
Is this bug fixed? If yes, then is it fixed in 17.08 or in a later version?

**Comment by badlop** [comment]
Looking at that commit, it was included in 17.08 and newer.

**Comment by vhatzist** [comment]
The reason why I am looking into this issue is because I wonder whether this could be related to the issue I opened in:

https://github.com/processone/ejabberd/issues/2280

Unfortunately I'm not familiar with Erlang to understand whether the fix for this bug ( #1900 ) could have had any impact on issue #2280 ...
