### ISSUE TITLE
Failing to remsh from localhost to deployed ejabberd instance

### ISSUE THREAD

**Issue by IRog** [processone/ejabberd#1901]
> What version of ejabberd are you using?

ejabberd 17.01

> What operating system (version) are you using?

Ubuntu 14

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've been trying to connect to a deployed remote ejabberd instance via remsh and have been running into some issues.

`erl -name 69383c66-debug-ejabberd@MAC_HOSTNAME -remsh ejabberd@HOST1 -hidden -setcookie COOKIE`

I basically copy-pasted the command the command that's run by `ejabberdctl debug` but added in the cookie. I can connect to the node on one of the two nodes in the cluster with basically the same command and only changing @MAC_HOSTNAME to the box's hostname. My local box can telnet on 4369 where epmd is listening on the other box and I can't find out what's going wrong. I just get the cryptic `*** ERROR: Shell process terminated! (^G to start new job) ***` error. The HOST1 is the same as the private hostname on the ejabberd instance though a public IP that I put in my `/etc/hosts` I can't find out what's wrong and the only difference between the working cluster local version and the one run on my mac is the @MAC_HOSTNAME which is a valid hostname (The private instances are using a similar private ip in their `/etc/hosts` so I don't think that's the issue). 

Do you have any ideas? Any debugging tips for better error messages or any help would be greatly appreciated. I know this is likely more of a fail erlang question but I'd really appreciate some help. I want to try running observer locally connected to my remote ejabberd.

Thanks!

**Comment by badlop** [comment]
> I've been trying to connect to a deployed remote ejabberd instance

`ejabberdctl debug` is available for that.

**Comment by IRog** [comment]
I'm trying to connect from a different node than I deployed on with standard erlang tools (I said above that I traced the `ejabberdctl debug` command to find the remsh command being used. I want to be able to open observer on a box with a GUI.

**Comment by cromain** [comment]
make sure `ejabberdctl ping` returns pong. if not, assuming node A and B share same cookie, check node A can resolve node B and B can resolve node A. see conf/inetrc if /etc/hosts does not help.
in your case it seems your "debug" local console can reach ejabberd, but not the reverse.
