### ISSUE TITLE
Existing PubSub node Items not retractable with registered admin user

### ISSUE THREAD

**Issue by brobaniuc** [processone/ejabberd#1902]
> What version of ejabberd are you using?
17.03

> What operating system (version) are you using?

Linux 3.10.0-514.16.1.el7.x86_64 x86_64

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When trying to retract items from a pubsub node it does not work. We use the admin user for this cleanup procedure.
The problem is that event though i can see the items on the pub sub node being returned when performing discoItems and also i can see the details of the item When I try to retract it from the pub sub node I get item not found response.

**Comment by cromain** [comment]
I can not reproduce, either retracting item or purge node, in all cases it work as expected.
note: admin xmpp user may not be able to remove item if that used does not have subscriptions.

**Comment by brobaniuc** [comment]
Hm..,
The strange thing is see here, or maybe i am missing something, is that we can get the item and see all its information with the same user. So the item exists, but when we are trying to remove it it states that is not found.
Thanks for trying i will try to subscribe the admin user to the pubsub node and see afterwards if it can be removed.
