### ISSUE TITLE
cluster join ejabberd@<ip>

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#1904]
> What version of ejabberd are you using?
ejabberd 17.07

> What operating system (version) are you using?
ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
package

---

1. I build two instance, <instance_1> and <instance_2>
2. set node `ERLANG_NODE=ejabberd@<ip>` in each `./conf/ejabberdctl.cfg` 
3. `./ejabberdctl start`
4. instance_1 exec `./ejabberdctl join_cluster ejabberd@<instance_2_ip>` and error is
```
Error: {{shutdown,
            {failed_to_start_child,ejabberd_rdbms,
                {shutdown,
                    {failed_to_start_child,'ejabberd_sql_sup_xmpp.example.com',
                        {'EXIT',badarg}}}}},
        {ejabberd_app,start,[normal,[]]}}
```
5. instance_1 crash , instance_2 running.
6. but when i restart instance_1 ejabberd service, and `./ejabberdctl list_cluster` and it was fine. 
7. I try to exec `./ejabberdctl list_cluster` in each instance. The response 
```
'ejabberd@<instance_1_ip>
'ejabberd@<instance_2_ip>'
``` 

My question is ... How do i fix this error?

Thanks

**Comment by cromain** [comment]
you should not set ip in nodename.
either use a shortname which will be resolved by your /etc/hosts, either use host FQDN names.
