### ISSUE TITLE
mod_last_sql does not store server

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1907]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When using `mod_last` with the `sql` backend, `LServer` does not get stored. When using multiple vhosts, there's no way to distinguish users with the same value of `LServer`. `mod_last_sql` should store `LServer` in a separate database column. Similarly, the `server` column seems to be missing from `archive`, `users`, `vcard` etc.

**Comment by zinid** [comment]
What a new idea :)
@alexeyshch is working on this at the moment

**Comment by marcphilipp** [comment]
Sorry, I don't get it. The issue is that we _do_ use multiple vhosts with the `sql`. Are you suggesting we can only use the `sql` backend for a single vhost? Or different sql servers for different vhosts?

**Comment by alexeyshch** [comment]
You can use the same sql server, but with different databases per vhost.

**Comment by marcphilipp** [comment]
Ok, thanks for the response!

> @alexeyshch is working on this at the moment

So, what are you working on exactly?

**Comment by zinid** [comment]
> So, what are you working on exactly?

He is working on removing the need to keep a separate database per virtual host.

**Comment by marcphilipp** [comment]
Ah, that's great, thanks! Will it make it into the next release (17.09?)?

**Comment by badlop** [comment]
The corresponding ticket is https://github.com/processone/ejabberd/issues/1952
