### ISSUE TITLE
No web interface after Debian 9 upgrade

### ISSUE THREAD

**Issue by sjreilly1960** [processone/ejabberd#1909]
> What version of ejabberd are you using?
16.09-4

> What operating system (version) are you using?
Debian 9

> How did you install ejabberd (source, package, distribution)?
Upgraded during Debian 8 -> 9 upgrade

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I am unable to access the web interface on port 5280.
The only log entries are;

2017-08-03 17:01:39.279 [info] <0.517.0>@ejabberd_listener:accept:333 (#Port<0.11980>) Accepted connection ::FFFF:198.186.31.130:43980 -> ::FFFF:198.186.31.30:5280
2017-08-03 17:01:39.280 [info] <0.2069.0>@ejabberd_http:init:163 started: {fast_tls,{tlssock,#Port<0.11980>,#Port<0.11981>}}

The web browser (firefox - Windows and Linux) says that the connection was reset.
The web interface was working before the Debian upgrade

**Comment by sjreilly1960** [comment]
Or, if someone knows how to add a user to a specific roster from the command line, that would negate the requirement for the web interface.

**Comment by prefiks** [comment]
Did you try to access that as https://ip:5280? (you seems to have ssl enabled on that port)

**Comment by prefiks** [comment]
And you can use add_rosteritem command in ejabberdctl to modify user ("ejabberdctl add_rosteritem me server.com peer server.com buddy friends both" will add peer@server.com to me@server.com roster as buddy in group friends)

**Comment by sjreilly1960** [comment]
prefix, thanks for the reply
Yes, using https did allow me to get to the web interface login page. Though firefox still baulked at the "invalid security certificate" I was able to get to the login page from chrome.
I now, however, have the issue that the account I used to administer ejabber (admin) is now seen as "inexistent"

[warning] <0.3262.0>@ejabberd_web_admin:process:246 Access of <<"admin">> from <<"::FFFF:198.186.31.130">> failed with error: <<"inexistent-account">>

The ejabberd.cfg file still shows admin as the Admin account for the site, so has the password been lost or corrupted.
Steve

**Comment by prefiks** [comment]
You may need to pass full jid in user field (admin@server.com or whatever domain you are using).

**Comment by prefiks** [comment]
And we switched to different config format, so your ejabberd may get its option from ejabberd.yml

**Comment by sjreilly1960** [comment]
You utter STAR!!
admin@server_name was spot-on.
Like the new interface too.
Many, many thanks.
Steve
