### ISSUE TITLE
ejabberd chooses wrong cert with XEP-0368

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#1911]
We are running ejabberd 17.07 on Debian Stretch (= current stable). We have several different VHosts. We chose to enable XMPP over TLS (again, didn't we just disable this five-or-so years ago? ^^) for [XEP-0368](https://xmpp.org/extensions/xep-0368.html). As usual, our config is publicly available [here](https://github.com/jabber-at/config/blob/master/ports.yml#L21-L34).

ejabberd does seem to pick the wrong certificate for direct TLS connections. Even though we configured the jabber.at certificate (I also verified that this is the current configuration via the webinterface), it currently presents the one for fsinf.at:

```
$ openssl s_client -connect xmpp.jabber.at:5223
...
subject=/CN=jabber.fsinf.at
```

Based on @weiss tip, I also did the following, which seems to point to the issue:

```
(ejabberd@titan)1> hd(ejabberd_config:get_myhosts()).
<<"fsinf.at">>
```

(note: fsinf.at and jabber.fsinf.at are both hostnames that use the same cert)

**Comment by zinid** [comment]
ejabberd doesn't support XEP-0368, because SNI is required which is not implemented in fast_tls.

**Comment by mathiasertl** [comment]
The XEP was our motivation, but we just enabled the same XMPP over TLS we had a decade ago. No more no less. We configured one certificate, ejabberd uses another certificate, and *that* is the issue.

**Comment by weiss** [comment]
Just to clarify, the issue is that the `certfile` option [is ignored][1] in the following listener configuration if the `domain_certfile` option is used:

    module: ejabberd_c2s
    tls: true
    certfile: "/path/to/ejabberd.pem"

[1]: https://github.com/processone/ejabberd/blob/101e808124a0bc6bb97f92de4e1961b544c1dd7b/src/ejabberd_c2s.erl#L303

**Comment by zinid** [comment]
This certificate configuration mess is pissing me off.

**Comment by zinid** [comment]
@weiss also, you can fix this easily, I'm busy at the moment. Do what you think is better.

**Comment by zinid** [comment]
Ah, we cannot just change the options priorities, because this will break STARTTLS certificate selection.

**Comment by weiss** [comment]
> @weiss also, you can fix this easily, I'm busy at the moment. Do what you think is better.

Haha, initially I told Mati to post an issue on GitHub because it's probably an easy fix for @zinid and I'm busy right now :-)

I can have a look later.

> Ah, we cannot just change the options priorities, because this will break STARTTLS certificate selection.

Yes it's a PITA.  We could either just change priorities for `tls: true` (ugh) or tell people to not specify the listener `certfile` option if they want `domain_certfile` to win.

**Comment by zinid** [comment]
> Haha, initially I told Mati to post an issue on GitHub because it's probably an easy fix for @zinid and I'm busy right now :-)

In this case the issue will hang around until someone will have spare time to fix it :)

**Comment by zinid** [comment]
So I assigned both

**Comment by weiss** [comment]
> We could either just change priorities for `tls: true`

This is how it worked in the past.  `domain_certfile` was [only used for STARTTLS][1].

[1]: https://github.com/processone/ejabberd/blob/16.09/src/ejabberd_c2s.erl#L851

**Comment by weiss** [comment]
> `domain_certfile` was only used for STARTTLS.

#1914 restores that behavior.

**Comment by mathiasertl** [comment]
@weiss is it possible your patch (deployed on our systems with 17.07) breaks s2s certificate selection. I don't think our config has changed, but all our  hostnames now get jabber.at certificates via s2s but not via c2s. See [jabber.zone c2s](https://check.messaging.one/result.php?id=26696) and [jabber.zone s2s](https://check.messaging.one/result.php?id=26695).

**Comment by weiss** [comment]
> is it possible your patch (deployed on our systems with 17.07) breaks s2s certificate selection.

No, [my patch][1] only touches certificate selection for c2s connections, so I'd assume this is an unrelated issue.

[1]: https://github.com/processone/ejabberd/commit/e1aaa1c99dd543b7a72ed6f62336accb85516214

**Comment by weiss** [comment]
> all our hostnames now get jabber.at certificates via s2s

#1938 should fix this.
