### ISSUE TITLE
host-specific module implementing custom IQ handler breaks mod_ping (possibly others)

### ISSUE THREAD

**Issue by nosnilmot** [processone/ejabberd#1916]
> What version of ejabberd are you using?

17.06, 17.07, git master (17.07-72-g25af3fb0)

> What operating system (version) are you using?

Mac OS X Sierra (10.12.6)

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Installing a module that implements a custom IQ handler only for a single host (ie. in host_config section of ejabberd.yml) causes other IQ handlers to be 'forgotten'.

New IQ handler works:

```
<iq type='get' id='123'>
<query xmlns='urn:test:helloworld'/>
</iq>

<iq xml:lang='en' to='stu@localhost/resource' from='stu@localhost' type='result' id='123'>
	<query xmlns='urn:test:helloworld'>
		<result>hello human</result>
	</query>
</iq>
```

But mod_ping is no longer receiving/responding to ping requests:

```
<iq type='get' id='purpleaff0cfa3'>
	<ping xmlns='urn:xmpp:ping'/>
</iq>

<iq xml:lang='en' to='stu@localhost/resource' from='stu@localhost' type='error' id='purpleaff0cfa3'>
	<ping xmlns='urn:xmpp:ping'/>
	<error code='503' type='cancel'>
		<service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
		<text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>No module is handling this query</text>
	</error>
</iq>
```

Attached [mod_hello_world.zip](https://github.com/processone/ejabberd/files/1204728/mod_hello_world.zip) is source for a stripped down testcase/example plugin to demonstrate this. Load it by putting in ejabberd.yml:

```
host_config:
  "localhost":
    modules:
      mod_hello_world: {}
```

**Comment by nosnilmot** [comment]
To be clear, if this module is loaded server-wide in the top level 'modules:' section of ejabberd.yml this problem does not occur (but then the custom IQ handler is implemented for all virtual hosts, which is not desired).

**Comment by badlop** [comment]
Your configuration says that in localhost, only one module will be defined:
```yaml
host_config:
  "localhost":
    modules:
      mod_hello_world: {}
```

I guess you want to use this one instead, where, in addition to the other modules, this one is also enabled:
```yaml
append_host_config:
  "localhost":
    modules:
      mod_hello_world: {}
```
See https://docs.ejabberd.im/admin/configuration/#virtual-hosting

**Comment by nosnilmot** [comment]
Does this behaviour where host_config overrides all (?) global config apply only to which modules are loaded? is there ever a valid use case for that?

Why not have host_config behave as append_host_config does today, and then where it is desired to have completely different configs per-virtual host don't include anything in the corresponding global config section?

At the very very least the example config should have an explicit note that the host_config section is going to override other settings if uncommented! : 

```
##
## Enable modules with custom options in a specific virtual host
##
## host_config:
##   "localhost":
##     modules:
##       mod_echo:
##         host: "mirror.localhost"
```

If this behaviour is not limited to module loading, and applies to other virtual host specific configuration options, there are several other places in the example/default config file that should be annotated.

**Comment by zinid** [comment]
@nosnilmot please don't jump from topic to topic, your question was answered, please create a new issue if you have feature requests or bug reports for configuration.
