### ISSUE TITLE
Migrate of Mnesia to SqlServer

### ISSUE THREAD

**Issue by ghasemi64** [processone/ejabberd#1918]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?

Win 7

> How did you install ejabberd (source, package, distribution)?
Installing ejabberd with Binary Installer

> What did not work as expected? Are there error messages in the log? What
2017-08-08 15:46:35.820 [warning] <0.437.0>@ejabberd_web_admin:process:246 Access of <<"admin">> from <<"::1">> failed with error: <<"inexistent-account">>
> was the unexpected behavior? What was the expected result?

How can I migration from Mnesia to SqlServer by putting in order the .yml file and Web admin on windows OS?I did it but I con't login?
 In  .yml...

`auth_method: odbc

sql_type: sql

sql_server: "localhost"

sql_database: "Ejabberd"

sql_username: "sa"

sql_password: "a@123456"`

**Comment by cromain** [comment]
maybe reading the doc will help you
https://docs.ejabberd.im/admin/configuration/#microsoft-sql-notes

**Comment by ghasemi64** [comment]
Thanks dear cromain
I read that link and did some changes. There are my .yml codes 
`auth_method: sql
sql_type: mssql
sql_server: "localhost"             
sql_database: "Ejabberd"
sql_username: "sa"
sql_password: "a@123456"
sql_port: 3306
sql_pool_size: 10`
But no work!!
And the error in log file..
2017-08-09 10:21:06.671 [info] <0.374.0>@ejabberd_sql:connecting:324 mssql connection failed:
** Reason: "[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified SQLSTATE IS: IM002 Connection to database failed."

**Comment by ghasemi64** [comment]
Why are you closing this question?????!!!

**Comment by zinid** [comment]
@ghasemi64 because you cannot read the documentation. Which clearly says:
> For now, MS SQL is only supported in Unix-like OS'es

**Comment by ghasemi64** [comment]
Friends, be sure that I've read it.
but why SqlServer that is a product of Microsoft doesn't support Windows!!!!!!!?
What should  I do?
My goal is building 100.000 users and send message to them.

**Comment by zinid** [comment]
You need **ejabberd** to run in unix-like OS, so ejabberd will connect to MS SQL Server running in, obviosly, Windows platform.
Everyone wants to build 100k users chat service nowadays :) Anyway, MS SQL Server is not suitable for such load because ejabberd uses it inefficiently (due to freetds+unixodbc layer). I would recommend using Redis+PostgreSQL instead for such a task.

**Comment by ghasemi64** [comment]
So why do have the other forums this solution?
https://www.ejabberd.im/forum/28980/migrate-mnesia-sqlserver#comment-67631
 ???

**Comment by zinid** [comment]
Ask them. I repeat: ejabberd relies on freetds+unixodbc drivers which are unavailable under Windows. Please stop asking the same question again and again.

**Comment by ghasemi64** [comment]
Thanks but you don't force to replay me...
