### ISSUE TITLE
MucSub affiliation changes not sent? 

### ISSUE THREAD

**Issue by goldzilla** [processone/ejabberd#1919]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Windows Server 2012/Debian8 

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Using MucSub**
1. Create muc with presence (user: 20d8@example.com)
2. Muc owner ( 20d8@example.com) subscribes other user
 ```xml
<iq to='oha16@conference.example.com' type='set' id='E6E10350-76CF-40C6-B91B-1EA08C332FC7'>
  <subscribe xmlns='urn:xmpp:mucsub:0' jid='30d8@example.com' nick='30d8'>
    <event node='urn:xmpp:mucsub:nodes:messages' />
    <event node='urn:xmpp:mucsub:nodes:affiliations' />
    <event node='urn:xmpp:mucsub:nodes:subject' />
    <event node='urn:xmpp:mucsub:nodes:config' />
  </subscribe> 
</iq>
```
3. Muc owner sets affiliation owner to subscribes user

```xml
<iq type="set" to="oha16@conference.example.com" id="asdfiii">
  <query xmlns="http://jabber.org/protocol/muc#admin">
    <item affiliation="owner" jid="30d8@example.com">
    </item>
  </query>
</iq>
```

4. No affiliation stanza is received by the user _30d8@example.com_

I'm expecting that a stanza is in the spool table when an affiliation change is made for the user. The behavior works for subject changes: 

```xml
<message from="oha20@conference.example.com" to="30d8@example.com/30d8">
  <event xmlns="http://jabber.org/protocol/pubsub#event">
    <items node="urn:xmpp:mucsub:nodes:subject">
      <item id="7200733442868691666">
        <message xmlns="jabber:client" from="oha20@conference.example.com/20d8"
                 type="groupchat" xml:lang="en" to="30d8@example.com" id="ae60a">
          <subject>here I am</subject>
        </message>
      </item>
    </items>
  </event>
  <delay xmlns="urn:xmpp:delay" from="example.com" stamp="2017-08-08T12:47:27.207000Z">Offline Storage</delay>
</message>
```

is this assumption correct that it should work for affiliations as well, or is the documentation not accurate? [https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#subscribing-to-muc-sub-events](url)

**Comment by badlop** [comment]
With the default room configuration, affiliation changes are reported to moderators only, by sending them a message stanza. Notice that moderator is a role, and that is a temporary relationship with the room, that requires the user to be a room occupant.

If you want room occupants that are not moderators, and subscribers, to receive affiliation changes, then you must change the "anonymous" room option from "moderators" to "anyone".

**Comment by goldzilla** [comment]
Thanks @badlop 
it works with this setting:
``` mod_muc:
    host: "conference.bmwgroup.com"
    access:
      - allow: all
    access_admin:
      - allow: admin
    access_create: all
    access_persistent: all
    history_size: 0
    default_room_options:
        allow_user_invites: true
        anonymous: false
        members_by_default: true
        members_only: false
        moderated: true
        persistent: true
        public: false
        public_list: true
        allow_subscription: true
        allow_query_users: true

  mod_muc_admin: {}
```

**Comment by abdulmomen-khan** [comment]
@goldzilla @badlop any suggestions ..
