### ISSUE TITLE
ejabberd_stun: auth_* and turn_* do *not* imply use_turn

### ISSUE THREAD

**Issue by MarcelWaldvogel** [processone/ejabberd#1920]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu 17.04

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The [documentation](https://docs.ejabberd.im/admin/configuration/#stun-and-turn) says that `auth_*` and `turn_*` each imply `use_turn`. This is not the case: Neither of `turn_ip`, `turn_min_port`, `turn_max_port`,  `turn_max_allocations`, `turn_max_permissions`, `auth_type`, nor `auth_realm` implies `use_turn`.

I am not sure whether the documentation should be changed (from "implies" to "requires", "only applicable with", or similar) to match the code or the code should be changed to match the documentation.

**Comment by cromain** [comment]
https://github.com/processone/stun/issues/11

**Comment by diegobill** [comment]
@MarcelWaldvogel or @cromain , can you just answer me if when the stun module is running with ejabberd like in this config (ejabberd.yml):

```
  -
    port: 3478
    transport: udp
    user_turn: true
    turn_ip: "10.67.125.28"
    auth_type: anonymous
    module: ejabberd_stun
    certfile: "/opt/ejabberd-16.03/conf/server.pem"
```

Is the port 3478 should be open when the stun is running with ejabberd?

Because I tested and I received connection refused (but for example port 5280 is opened):

```
# nc -zv localhost 3478
nc: connect to localhost port 3478 (tcp) failed: Connection refused
nc: connect to localhost port 3478 (tcp) failed: Connection refused
# nc -zv localhost 5280
Connection to localhost 5280 port [tcp/*] succeeded!
```

**Comment by MarcelWaldvogel** [comment]
You are opening a UDP port, so your TCP connection will fail

**Comment by diegobill** [comment]
@MarcelWaldvogel , thanks. I tested UDP port and is open:

```
$ nc -uv localhost 3478
Connection to localhost 3478 port [udp/*] succeeded!
```
