### ISSUE TITLE
nodetree notification 

### ISSUE THREAD

**Issue by 4i-helpynet** [processone/ejabberd#1921]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? 

PUBSUB nodetree created succesfully.
User subscribed to node:  /home/[host]/[differentuser]
Differentuser succesfully create node /home/[host]/[differentuser]/test
Differentuser succesfully create item in node /home/[host]/[differentuser]/test

User did not get notification about item publication

>What was the expected result?

Subscribed User should get notification about differentuser's  item publication in his subnode

**Comment by cromain** [comment]
this was removed long time ago when switching to flat plugin as default.
for now, hometree is not propagating items, just allows to sort nodes.
propagation to subnodes can be injected back i guess.

**Comment by cromain** [comment]
commit 4745368 should be good enough
