### ISSUE TITLE
[root@localhost ejabberd]# ./bin/ejabberdctl  WARNING: This is not recommended to run ejabberd as root ./bin/ejabberdctl: line 116:

### ISSUE THREAD

**Issue by wwezhuimeng** [processone/ejabberd#1922]
[root@localhost ejabberd]# ./bin/ejabberdctl 
WARNING: This is not recommended to run ejabberd as root
./bin/ejabberdctl: line 116: /erts-9.0/bin/erl: No such file or directory
./bin/ejabberdctl: line 120: exec_cmd: command not found

**Comment by cromain** [comment]
can not reproduce with HEAD
see what's defined at line 13, it should be full path to erl
you likely have an issue with your setup.
