### ISSUE TITLE
register a new account

### ISSUE THREAD

**Issue by xiaoxinba** [processone/ejabberd#1924]
> What version of ejabberd are you using?

ejabberd-17.07

> What operating system (version) are you using?

> How did you install ejabberd (source, package, distribution)?

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when i use strophe.register.js register a account to ejabberd, result :
 `<error code='403' type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Denied by ACL</text></error>`

why??

**Comment by zinid** [comment]
> why??

Because you need to configure `mod_register` properly. By default its ACL is very restrictive in order to avoid massive spam bots registration.
