### ISSUE TITLE
Problem in Instalation

### ISSUE THREAD

**Issue by ghasemi64** [processone/ejabberd#1927]
> What version of ejabberd are you using?17.07
> What operating system (version) are you using?Win7

I’ve recently know Ejabberd and I,ve read its documents.So I’ve faced a lot of problems :
I installed Installing ejabberd with Binary Installer on Win7.
After Installing service with shortcuts it didn’t start and gave some errors.
I tried to use command So I run C:\Program Files\ejabberd-17.07\bin>ejabberdctl ...
But I faced with this error :
Failed RPC connection to the node ejabberd@localhost: nodedown

I forced stop/start the service by handle.
I underestood that I can use web admin interface for managing Ejabberd.
For example for build of limited users.I need to creat 100K users.
Because I didn’t know how do that in Mnesia.so I decided to use Sql Server instead of Mnesia to create users with script .
I run schema Ejabberd and build DB and edded a user in User Table and did below chnages...
auth_method: odbc
sql_type: sql
sql_server: "localhost"
sql_database: "Ejabberd"
sql_username: "sa"
sql_password: "a@123456"
OR------
auth_method: sql
sql_server: "DSN=Ejabberd;UID=sa;PWD=pa@123456"

but I never can login.I saw below error in logs :
2017-08-09 16:07:07.676 [warning] <0.437.0>@ejabberd_web_admin:process:246 Access of <<"admin">> from <<"::1">> failed with error: <<"inexistent-account">>
Colud you please say me a way and say where I did Wrong.

**Comment by cromain** [comment]
you should check this part of the doc
https://docs.ejabberd.im/admin/configuration/#microsoft-sql-notes

sql_type should be mssql

**Comment by ghasemi64** [comment]
Thanks,
I've read this link more and more time.
This setting was like this `sql_type :mssql`  and it was wrong by typing.so where did do I wrong?
