### ISSUE TITLE
Node js external auth script giving error.

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#1929]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?
Ubuntu Server 16.04

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? 
What was the unexpected behavior? What was the expected result?

Im getting a 

> ejabberd extauth script has exitted abruptly with reason 'normal'

from my external script. Im using this [node-ejabberd-auth](https://github.com/derWhity/node-ejabberd-auth).

line from ejabberd.yml is:
```
auth_method: external
extauth_program: "/opt/ejabberd-17.07/node-ejabberd-auth/index.js"
```

What causes this?

**Comment by jjdp** [comment]
i forgot to add node :(

**Comment by faysal515** [comment]
@jjdp I'm using the exact same package and config. but getting no response. any idea what did i do wrong?

**Comment by jjdp** [comment]
extauth_program: node "node-ejabberd-auth/index.js"

**Comment by faysal515** [comment]
as soon as I start ejabberd, I'm getting the following log continuously



```2017-10-30 13:52:32.383 [critical] <0.2501.0>@extauth:loop:137 extauth script has exitted abruptly with reason 'normal'```

here's my config

```
auth_method: external
extauth_program: node "/Users/faysal/development/app/external_auth/index.js"
```

**Comment by jjdp** [comment]
that is your external_auth error and has nothing to do with ejabberd

**Comment by faysal515** [comment]
can you please share a sample of your script? i followed the package documentation and now stuck in here

**Comment by jjdp** [comment]
we don't use external auth anymore.

can you post a log? the package has a logger

**Comment by faysal515** [comment]
surprisingly the package logger writes nothing in the file.

**Comment by jjdp** [comment]
did you add the node-ejabberd-auth log option?

**Comment by faysal515** [comment]
```
require('ejabberd-auth').run({
  log: {
    filename: './auth_log',
    level: 'debug'
  },
  actions: {
    auth: function (done, userName, domain, password) {
      console.log('auth requested')
      // Some auth to be done here
      if (password === 'random') {
        done(false)
      }
      else done(true); // or done(false) if the authentification has failed
    }
  }
})

```

**Comment by jjdp** [comment]
now I have no idea, there are no logs too. maybe it has something to do with your server environment

**Comment by faysal515** [comment]
@jjdp thank you for your effort 👍
