### ISSUE TITLE
Missing options in "mod_muc"

### ISSUE THREAD

**Issue by nekoswag** [processone/ejabberd#1931]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

openSUSE Leap 42.3

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Options you can set according to docs:
https://docs.ejabberd.im/admin/configuration/#mod-muc

ejabberd 17.07 log message:
`2017-08-11 21:51:54.473 [error] <0.283.0>@gen_mod:validate_opts:514 unknown option 'mam' for module 'mod_muc' will be likely ignored, available options are: user_presence_shaper, user_message_shaper, room_shaper, default_room_options, max_users, max_user_conferences, max_rooms_discoitems, max_room_desc, access, regexp_room_id, max_users_admin_threshold, max_room_id, host, access_persistent, queue_type, max_users_presence, max_room_name, history_size, ram_db_type, db_type, access_create, min_presence_interval, min_message_interval, access_admin
`
Where are the missing options?
Could my configuration be wrong or is it a documentation error?

**Comment by zinid** [comment]
The `mam` option is a sub-option of `default_room_options`, e.g.:
```yaml
mod_muc:
    ...
    default_room_options:
        mam: true
```

**Comment by nekoswag** [comment]
Thanks, I just found it a few moments ago here
http://chatlogs.jabber.ru/ejabberd@conference.jabber.ru/2016/01/09.html

Thanks anyway :)

**Comment by zinid** [comment]
You're welcome ;)
