### ISSUE TITLE
Registered users disappears on restart

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#1932]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?
Ubuntu Server 16.04

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I restart the ejabberd server, why does the registered users list on that virtual host gets deleted. Is this the default behavior of mnesia? Would using mysql remedy this?

**Comment by zinid** [comment]
No, this is not normal. Attach to running ejabberd:
```
$ ejabberdctcl debug
```
And run the following command:
```
> mnesia:info().
```

**Comment by jjdp** [comment]
im not getting any output from that command

**Comment by zinid** [comment]
Then we cannot help you

**Comment by jjdp** [comment]
Any idea why im not getting any output? 

> Application mnesia started on node ejabberd@localhost

I'm seeing this on logs

**Comment by jjdp** [comment]
ok I had to run mnesia info using the ctl instead. Here's the output:

---> Processes holding locks <---
---> Processes waiting for locks <---
---> Participant transactions <---
---> Coordinator transactions <---
---> Uncertain transactions <---
---> Active tables <---
route          : with 2        records occupying 359      words of mem
ejabberd_commands: with 115      records occupying 36471    words of mem
mod_register_ip: with 0        records occupying 298      words of mem
caps_features  : with 3        records occupying 11638    bytes on disc
bosh           : with 0        records occupying 298      words of mem
acl            : with 6        records occupying 459      words of mem
access         : with 24       records occupying 934      words of mem
shaper         : with 2        records occupying 320      words of mem
carboncopy     : with 0        records occupying 298      words of mem
last_activity  : with 6        records occupying 7268     bytes on disc
pubsub_index   : with 1        records occupying 307      words of mem
vcard_search   : with 0        records occupying 298      words of mem
archive_prefs  : with 0        records occupying 5464     bytes on disc
motd_users     : with 0        records occupying 5464     bytes on disc
reg_users_counter: with 0        records occupying 298      words of mem
sr_user        : with 0        records occupying 298      words of mem
schema         : with 39       records occupying 5204     words of mem
roster_version : with 0        records occupying 5464     bytes on disc
pubsub_orphan  : with 0        records occupying 298      words of mem
session        : with 0        records occupying 298      words of mem
pubsub_last_item: with 0        records occupying 298      words of mem
offline_msg    : with 0        records occupying 30382    bytes on disc
archive_msg    : with 4        records occupying 12770    bytes on disc
private_storage: with 3        records occupying 6533     bytes on disc
motd           : with 0        records occupying 5464     bytes on disc
sr_group       : with 0        records occupying 298      words of mem
oauth_token    : with 0        records occupying 5464     bytes on disc
pubsub_item    : with 10       records occupying 10725    bytes on disc
privacy        : with 0        records occupying 5464     bytes on disc
pubsub_state   : with 7        records occupying 380      words of mem
iq_response    : with 0        records occupying 298      words of mem
passwd         : with 4        records occupying 6308     bytes on disc
temporarily_blocked: with 0        records occupying 298      words of mem
s2s            : with 0        records occupying 298      words of mem
session_counter: with 0        records occupying 298      words of mem
pubsub_node    : with 7        records occupying 1393     words of mem
vcard          : with 0        records occupying 5464     bytes on disc
route_multicast: with 0        records occupying 298      words of mem
roster         : with 0        records occupying 6680     bytes on disc
===> System info in version "4.14.3", debug level = none <===
opt_disc. Directory "/opt/ejabberd-17.07/database/ejabberd@localhost" is used.
use fallback at restart = false
running db nodes   = [ejabberd@localhost]
stopped db nodes   = []
master node tables = []
remote             = []
ram_copies         = [access,acl,bosh,carboncopy,ejabberd_commands,
                      iq_response,mod_register_ip,pubsub_last_item,
                      reg_users_counter,route,route_multicast,s2s,session,
                      session_counter,shaper,temporarily_blocked]
disc_copies        = [pubsub_index,pubsub_node,pubsub_orphan,pubsub_state,
                      schema,sr_group,sr_user,vcard_search]
disc_only_copies   = [archive_msg,archive_prefs,caps_features,last_activity,
                      motd,motd_users,oauth_token,offline_msg,passwd,privacy,
                      private_storage,pubsub_item,roster,roster_version,vcard]
[{ejabberd@localhost,disc_copies}] = [pubsub_node,pubsub_state,sr_group,
                                      pubsub_orphan,schema,sr_user,
                                      vcard_search,pubsub_index]
[{ejabberd@localhost,disc_only_copies}] = [roster,vcard,passwd,privacy,
                                           pubsub_item,oauth_token,
                                           caps_features,motd,private_storage,
                                           archive_msg,offline_msg,
                                           roster_version,motd_users,
                                           archive_prefs,last_activity]
[{ejabberd@localhost,ram_copies}] = [shaper,route_multicast,mod_register_ip,
                                     session_counter,s2s,temporarily_blocked,
                                     iq_response,bosh,acl,access,
                                     pubsub_last_item,session,
                                     reg_users_counter,carboncopy,
                                     ejabberd_commands,route]
37 transactions committed, 1 aborted, 0 restarted, 4 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []

**Comment by zinid** [comment]
> passwd : with 4 records

So you have 4 users registered. Run the following command:
```erlang
> ejabberd_auth:get_users().
```

**Comment by jjdp** [comment]
ok so apparently this is because the external_auth script but im just returning success on tryregister and I can register successfully on ctl or in the webadmin. Yet the passwd record stays the same. Does it not add to the mnesia db?

**Comment by zinid** [comment]
External authentication has nothing to do with Mnesia.

**Comment by jjdp** [comment]
Oh ok i see that in ejabberd_auth_external.erl, it seems I'll have to modify it myself or just use the REST API which is simpler
