### ISSUE TITLE
Question : How can i extend transport for custom parsing.

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1934]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

As we all know ejabberd is xmpp server so obviously it does xml parsing once the bytes are rcvd on port 5222
I wanted to know there are also other port like 5269 for http and for Stun and trun diff port which does not need xml parsing .
I just wanted to can how can i extend ejabberd for parsing the bytes the way I want on a diff port completely for eg say i want to parse json bytes on 5299  I know this not a standard xmpp implementation but i just wanted to experiment something related to IOT for custom bytes handing.

I just need to know how i can listen on a diff port and use that for custom usage.

Any pointers will be great.

**Comment by zinid** [comment]
> i want to parse json bytes on 5299

If I understand correctly, you need to set `socket_type() -> raw` callback. In this case you will receive raw TCP data from the receiver where you can parse it using whatever parser you need.

**Comment by nOmi7** [comment]
But how do i create a new listener service to listen on a new port ?

**Comment by zinid** [comment]
See `ejabberd_socket` behaviour.

**Comment by nOmi7** [comment]
Okay i went thru few codes ... Just need one input ..
1) Should i implement the way s2s_in / s2s_out  is implemented with socket type raw or  like esip ?
2) Can this be  non blocking IO 
I was trying to implement experimental media streaming with out using external libs.

**Comment by zinid** [comment]
1) I don't see much difference betwee s2s and esip implementation. The API is still the same, it's packets where the difference is: in the case of s2s_in you will receive xmlstreams when in the case of esip (raw type) you will receive raw tcp (or udp) packets.
2) Of course it's non-blocking

**Comment by nOmi7** [comment]
Thanks much @zinid  THE SAVIOUR
