### ISSUE TITLE
Compile error can't find include file

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#1940]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?
Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The .deb file from the download page includes these in the libs when I dpkg unpack, ejabberd-17.07, lager-3.4.2 and xmpp-1.1.13

I compile them using erlc -I ejabberd-17.07/include -I lager-3.4.2/include -I xmpp-1.1.13/include my_mod.erl

When I try to compile, I'm getting these errors (even on the hello world example):

`mod_hello_world.erl: undefined parse transform 'lager_transform'`

and when i remove the logger

```
/xmpp.hrl:29: can't find include file "fxml.hrl"
```

I modified this mod_offline_post for our REST api since I saw one for 17.04, not entirely sure if it will work with 17.07.

```
-module(mod_offline_post).

-behaviour(gen_mod).

-export([start/2,
	 init/2,
	 stop/1,
	 send_notice/1]).

-define(PROCNAME, ?MODULE).

-include("ejabberd.hrl").
-include("xmpp.hrl").
-include("logger.hrl").

start(Host, Opts) ->
	?INFO_MSG("Starting mod_offline_post", [] ),
	register(?PROCNAME,spawn(?MODULE, init, [Host, Opts])),  
	ok.

init(Host, _Opts) ->
	inets:start(),
	ssl:start(),
	ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 100),
	ok.

stop(Host) ->
	?INFO_MSG("Stopping mod_offline_post", [] ),
	ejabberd_hooks:delete(offline_message_hook, Host,
			      ?MODULE, send_notice, 10),
	ok.

send_notice({Action,Packet}) ->	
	From = element(5,Packet),
	To = element(6,Packet),
	
	From1 = From#jid.luser,
	To1 = To#jid.luser,
	
	Body = binary_to_list(element(3,lists:nth(1,element(8,Packet)))),
	
	PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url,fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	AppId = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, app_id, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	ApiKey = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, api_key, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	
	Data = string:join(["to=", binary_to_list(To1), "&from=", binary_to_list(From1), "&body=", Body], ""),
	Request = {binary_to_list(PostUrl), [{"X-Parse-Application-Id", binary_to_list(AppId)}, {"X-Parse-REST-API-Key", binary_to_list(ApiKey)}], "application/json", Data},
	httpc:request(post, Request,[],[]),
			
	ok.
```

**Comment by cromain** [comment]
you must add parameter to erlc: -pa ejabberd-17.07/ebin
or put your module in ~/.ejabberd_contrib and let ejabberd compile your module for you with module_install command

**Comment by jjdp** [comment]
Im getting this ebin error, any idea why is that? There are also no ebin directories in https://github.com/processone/ejabberd-contrib

![err](https://user-images.githubusercontent.com/5244520/29266707-5c6ad9c8-8118-11e7-80e8-d894d65ace7c.png)
