### ISSUE TITLE
Custom module beam error: error writing file: no such file or directory

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#1941]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu Server 16.04 LTS

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Im getting this beam error when i module_check, any idea why is that? There are also no ebin directories in https://github.com/processone/ejabberd-contrib

`ejabberd-17.07/.ejabberd-modules/sources/ejabberd-contrib/mod_offline_post/ebin/mod_offline_post.bea#: error writing file: no such file or directory`

![err](https://user-images.githubusercontent.com/5244520/29268436-5290f660-811f-11e7-92b6-16854d1c2531.png)

the mod_offline_post:

```
-module(mod_offline_post).

-behaviour(gen_mod).

-export([start/2,
	 init/2,
	 stop/1,
	 send_notice/1]).

-define(PROCNAME, ?MODULE).

-include("ejabberd.hrl").
-include("xmpp.hrl").
-include("logger.hrl").

start(Host, Opts) ->
	?INFO_MSG("Starting mod_offline_post", [] ),
	register(?PROCNAME,spawn(?MODULE, init, [Host, Opts])),  
	ok.

init(Host, _Opts) ->
	inets:start(),
	ssl:start(),
	ejabberd_hooks:add(offline_message_hook, Host, ?MODULE, send_notice, 100),
	ok.

stop(Host) ->
	?INFO_MSG("Stopping mod_offline_post", [] ),
	ejabberd_hooks:delete(offline_message_hook, Host,
			      ?MODULE, send_notice, 10),
	ok.

send_notice({Action,Packet}) ->	
	From = element(5,Packet),
	To = element(6,Packet),
	
	From1 = From#jid.luser,
	To1 = To#jid.luser,
	
	Body = binary_to_list(element(3,lists:nth(1,element(8,Packet)))),
	
	PostUrl = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, post_url,fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	AppId = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, app_id, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	ApiKey = gen_mod:get_module_opt(To#jid.lserver, ?MODULE, api_key, fun(S) -> iolist_to_binary(S) end, list_to_binary("")),
	
	Data = string:join(["to=", binary_to_list(To1), "&from=", binary_to_list(From1), "&body=", Body], ""),
	Request = {binary_to_list(PostUrl), [{"X-Parse-Application-Id", binary_to_list(AppId)}, {"X-Parse-REST-API-Key", binary_to_list(ApiKey)}], "application/json", Data},
	httpc:request(post, Request,[],[]),
			
	ok.

```

**Comment by cromain** [comment]
this is out of scope of ejabberd,
please post your issue on https://github.com/processone/ejabberd-contrib

**Comment by cromain** [comment]
you can also read this post, for more details about external modules feature
https://blog.process-one.net/easy-installer-and-structure-for-ejabberd-contributed-modules/

**Comment by jjdp** [comment]
thank you. maybe this is some sort of permission error. i even tried the basic hello world. same error
