### ISSUE TITLE
ejabberdctl Does not Install in deb

### ISSUE THREAD

**Issue by talkinggoat** [processone/ejabberd#1946]
> What version of ejabberd are you using?

17.08 x64

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

First, the package is installing two ejabberd folders in /opt, ejabberd and ejabberd-17.08 which is the correct folder?

I edited the config file, in the 17.08 folder, and started ejabberd, but when I try to set the password, I get ERROR Can Not Register.

sudo ./ejabberdctl register admin localhost MyPassword
Error: cannot_register

```yaml
hosts:
  - "localhost"

acl:
  admin:
    user:
      - "admin@localhost"
```

```
netstat -na | grep 5280
tcp6       0      0 :::5280                 :::*                    LISTEN 
```

**Comment by badlop** [comment]
> First, the package is installing two ejabberd folders in /opt, ejabberd and ejabberd-17.08 which is the correct folder?

You can know the folders used by the running ejabberd here:
```
/opt/ejabberd-17.08/bin> sudo ./ejabberdctl
...
Optional parameters when starting an ejabberd node:
  --config-dir dir   Config ejabberd:    /opt/ejabberd/conf
  --config file      Config ejabberd:    /opt/ejabberd/conf/ejabberd.yml
  --ctl-config file  Config ejabberdctl: /opt/ejabberd/conf/ejabberdctl.cfg
  --logs dir         Directory for logs: /opt/ejabberd/logs
  --spool dir        Database spool dir: /opt/ejabberd/database/ejabberd@localhost
  --node nodename    ejabberd node name: ejabberd@localhost
```

> I edited the config file, in the 17.08 folder, and started ejabberd, but when I try to set the password, I get ERROR Can Not Register.

Looking at the default configuration, it has mod_register enabled, and its 'access' option is set to 'register', which is defined to 'allow'. So all this is correct.

Check what vhost is defined in the default configuration. In my case it was this:
```yaml
hosts:
  - "atenea"
```
I have two options: use that vhost, or change it and restart ejabberd. Notice this works for me:
```
/opt/ejabberd-17.08/bin> sudo ./ejabberdctl register admin22 atenea MyPassword
User admin22@atenea successfully registered
```

**Comment by talkinggoat** [comment]
I have completely uninstalled with --purge and reinstalled ejabberd. Here is a video of what happens, when I try to use it. 

https://youtu.be/hqpVUQ8WvFY

As you can see, it is setup for toshibaS55t in ejabberd.yml, but it's getting localhost from somewhere. Even when I start it using --node toshibaS55t, it still says "Failed RPC connection"

**Comment by badlop** [comment]
There are two independent concepts that you are mixing, let's clarify them:
* The `toshibaS55t` you see in ejabberd.yml is the Jabber/XMPP domain served by ejabberd, and admin@toshibaS55T is a Jabber ID (username and domain name),
* The `localhost` you see in ejabberdctl (and in ejabberdctl.cfg), is the erlang domain, and ejabberd@localhost is the ejabberd node name. This is related to Erlang and Mnesia clustering, not related to Jabber or XMPP.

In some cases, both may be the same, but it's just a coincidence, like in my case. Typically, an ejabberd node like ejabberdproduction@server1.machine.com may seve many Jabber domains, like company1.com, company2.com, organization1.org, etc.

**Comment by cromain** [comment]
since 17.08, when installing as root (from rpm/deb) ejabberd's home is set to /opt/ejabberd and we put here runtime files (conf database and logs). /opt/ejabberd-17.08/database remains empty, /opt/ejabberd-17.08/logs contains only installation logs, /opt/ejabberd-17.08/conf keeps the default configuration for the record, but is not used anymore.

this change allows to be able to upgrade ejabberd without loosing your config and database. see #1828 for details.
calling /opt/ejabberd-17.08/bin/ejabberdctl will read conf in /opt/ejabberd/conf/ejabberd.yml
uninstalling 17.08 or upgrading it will not touch your copy of /opt/ejabberd/conf

I think badlop answered the other points and we can close this issue.
