### ISSUE TITLE
eJabberd ignores cipher settings / ciphers are missing

### ISSUE THREAD

**Issue by ChStoltz** [processone/ejabberd#1947]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Debian Jessie 8.9

> How did you install ejabberd (source, package, distribution)?

package, binary installers

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

For c2s (5222, 5223) and s2s I have cipher settings like:

ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA"

According to xmpp.net -> check.messaging.one only 4 of them are available:

DHE-RSA-AES256-GCM-SHA384
DHE-RSA-CAMELLIA256-SHA
DHE-RSA-AES256-SHA256
DHE-RSA-AES256-SHA

I upgraded from 17.01 to 17.07 to 17.08. In 17.01 it was working for sure. In 17.07 I cant tell.

I upgraded by executing the installer and copying the config file to the new directory. Cert files are always staying in a separate directory outside of the main ejabberd directory.

I tried to remove the ciphers option in the config file but, those specific ciphers are still missing. There is no error message in the logs.

What did I miss?

**Comment by weiss** [comment]
You need OpenSSL 1.0.2 or newer for ECDHE support in 17.08.
