### ISSUE TITLE
Getting an error on using XEP-0191

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#1948]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I block/unblock a JID im getting these errors:

`<iq to="redfish221@mydomain.com" id="push11748480439442204276" type="error"><error type="wait"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>`

XMPP specs say that the server sends an IQ-set to all of the user's resources that have requested the blocklist but I have only 1 connected resource under that JID, I got one successful

`<iq to="redfish221@mydomain.com" id="push12976811032802633816" type="result"/>`

but I'm getting two errors like the above

**Comment by zinid** [comment]
Please show the packet you're trying to send (for which you receive this error). Seems like the payload of the packet you're sending is empty.

**Comment by jjdp** [comment]
```
<iq type='set' id='unblock1'>
  <unblock xmlns='urn:xmpp:blocking'>
    <item jid='romeo@mydomain.com'/>
  </unblock>
</iq>
```

that's it same from the specs

**Comment by zinid** [comment]
I cannot reproduce, here is what I got:
```xml
<iq type='set' id='unblock1'>
  <unblock xmlns='urn:xmpp:blocking'>
    <item jid='romeo@montague.net'/>
  </unblock>
</iq>

...

<iq from="user1@localhost" type="result" xml:lang="en" to="user1@localhost/master" id="unblock1"/>
```

**Comment by zinid** [comment]
It seems like the error you see is generating your client to "blocking" pushes sent by ejabberd.

**Comment by jjdp** [comment]
most likely
