### ISSUE TITLE
Hide LDAP bind password in ejabberd log file

### ISSUE THREAD

**Issue by DwijadasDey** [processone/ejabberd#1953]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

How can i hide/mask LDAP bind password that is appearing in the ejabberd log file ?

**Comment by zinid** [comment]
It only appears if logleve is set to 5 (debug). Increase the loglevel and you won't see it.
