### ISSUE TITLE
auth_method: riak authentication failed after registering a new user and restarting ejabberd.

### ISSUE THREAD

**Issue by Murad-Dry** [processone/ejabberd#1955]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?

Oracle Linux

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What

Authentication failed with riak database after restarting the server.
> was the unexpected behavior? What was the expected result?

Worked as expected in previous versions like 17.03

**Comment by zinid** [comment]
Our testing framework is testing user registrations with Riak and it didn't show any regressions.

**Comment by zinid** [comment]
Once you register a user, you can check if Riak actually keeps it

**Comment by Murad-Dry** [comment]
Which version of Riak have you used?

**Comment by zinid** [comment]
Frankly, I don't know, the one available by default on Travis, but we don't restart ejabberd or riak during tests.
