### ISSUE TITLE
XEP-0016, blocking an individual user not working for MUC?

### ISSUE THREAD

**Issue by MattFoley** [processone/ejabberd#1958]
> What version of ejabberd are you using?

HEAD

> What operating system (version) are you using?

Linux Distro

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

MUC history and MUC messages seem to not be blocked via Privacy Lists correctly. When a user adds a jid of the format "<user@domain>" to a privacy list, of action "deny", with a `<message/>` subelement, they should no longer see any messages from this users.

In this case, I'm not seeing any MUC messages filtered on this. I am setting this list as both default and active. However, still receiving messages while in the room, and from MUC history. Did Ejabberd not implement this, or am I misunderstanding the XEP? I'm including XML examples below of my communication with the Ejabberd.

XMPP Stanza Examples:

IQ for setting the block list:
```
xml sent: 
<iq 
  xmlns="jabber:client" type="set" id="e630a2c8-6dc6-4269-8116-cc6b40eccb06">
  <query 
    xmlns="jabber:iq:privacy">
    <list name="muc_block_list">
      <item value="12679@chat.qa.muc.com" action="deny" type="jid" order="0">
        <presence-in/>
        <presence-out/>
        <message/>
      </item>
      <item value="12761@chat.qa.muc.com" action="deny" type="jid" order="1">
        <presence-in/>
        <presence-out/>
        <message/>
      </item>
    </list>
  </query>
</iq>

xml received: 
<iq 
  xmlns='jabber:client' to='5963849@chat.qa.muc.com/343690935239796469315186' from='5963849@chat.qa.muc.com' type='set' id='push15248698472869265803'>
  <query 
    xmlns='jabber:iq:privacy'>
    <list name='muc_block_list'/>
  </query>
</iq>
```

Setting as default:

```
xml sent:
<iq 
  xmlns="jabber:client" type="set" id="c142b56e-f7af-4d56-b720-024ded8e2cf8">
  <query 
    xmlns="jabber:iq:privacy">
    <default name="muc_block_list"/>
  </query>
</iq>

xml received:
<iq 
  xmlns='jabber:client' xml:lang='en' to='5921040@chat.qa.muc.com/1638418303583851822219218' from='5921040@chat.qa.muc.com' type='result' id='25022ac0-ba27-49d6-96c1-4853d651ea4c'/>
```

Setting as active:
```
xml sent: 
<iq 
  xmlns="jabber:client" type="set" id="553d99ba-0a29-4f28-a3d9-3f0d95529703">
  <query 
    xmlns="jabber:iq:privacy">
    <active name="muc_block_list"/>
  </query>
</iq>

xml received:
<iq 
  xmlns='jabber:client' xml:lang='en' to='5963849@chat.qa.muc.com/200929460774441951813970' from='5963849@chat.qa.muc.com' type='result' id='553d99ba-0a29-4f28-a3d9-3f0d95529703'/>
```

MUC History Stanza (I've tried blocking "conference.chat.qa.muc.com/12679" format as well, based on this format):
```
<message 
  xmlns='jabber:client' xml:lang='en' to='5921040@chat.qa.muc.com/1638418303583851822219218' from='3382@conference.chat.qa.muc.com/12679' type='groupchat' id='435fc112-dd41-4dee-a543-d59a93e199fa'>
  <archived by='3382@conference.chat.qa.muc.com' id='1503350449641799' 
    xmlns='urn:xmpp:mam:tmp'/>
    <stanza-id by='3382@conference.chat.qa.muc.com' id='1503350449641799' 
      xmlns='urn:xmpp:sid:0'/>
      <delay from='3382@conference.chat.qa.muc.com' stamp='2017-08-21T21:20:49.650359Z' 
        xmlns='urn:xmpp:delay'/>
        <body>Hello again</body>
      </message>

```
MUC Message Real Time:
```
<message 
  xmlns='jabber:client' xml:lang='en' to='5921040@chat.qa.muc.com/1638418303583851822219218' from='3382@conference.chat.qa.muc.com/12679' type='groupchat' id='f5ba14d0-6614-4751-9cc1-89d1df33d200'>
  <archived by='3382@conference.chat.qa.muc.com' id='1503351841337098' 
    xmlns='urn:xmpp:mam:tmp'/>
    <stanza-id by='3382@conference.chat.qa.muc.com' id='1503351841337098' 
      xmlns='urn:xmpp:sid:0'/>
      <body>Hi!</body>
    </message>
```

**Comment by MattFoley** [comment]
Small update. If I use the "from" that is exactly what's in the MUC room messages that are received, then I am able to block messages from that user in that room. However, I'd like to be able to block all messages from a given user in all rooms. Is that not supported, or have I not found the magical JID-cantation?

**Comment by zinid** [comment]
> However, I'd like to be able to block all messages from a given user in all rooms. Is that not supported, or have I not found the magical JID-cantation?

That is not supported and technically impossible, because a MUC message doesn't possess a real JID in `from` attribute.

**Comment by MattFoley** [comment]
@zinid Is this not supported by XEP-0191 either? From what I can tell, those are our only two options with regards to blocking.

**Comment by zinid** [comment]
Well you can block by JID from `from` attribute only, no matter XEP-0016 or XEP-0191. Messages of type `groupchat` have conference JIDs in their `from` attributes.

**Comment by MattFoley** [comment]
So both XEPs allow you to provide different formats for a JID, which are then supposed to be used as the search parameters:

```
If the type is "jid", then the 'value' attribute MUST contain a valid Jabber ID. JIDs SHOULD be matched in the following order:

<user@domain/resource> (only that resource matches)
<user@domain> (any resource matches)
<domain/resource> (only that resource matches)
<domain> (the domain itself matches, as does any user@domain or domain/resource)
```

How do these map to Occupant JIDs, (as defined by XEP-0045)? ie: `3382@conference.chat.qa.muc.com/12679`. 

I would assume that one of the above formats could be used to match to this. ie: `conference.chat.qa.muc.com/12679` could match against the `<domain/resource>`, and then all MUC messages from `12679@chat.qa.muc.com` would be blocked as their `from:` would always contain `conference.chat.qa.muc.com/12679` regardless of the room.

**Comment by MattFoley** [comment]
I'm not very good with Erlang, but from what I can tell `is_type_match` in mod_privacy.erl isn't checking against all of the criteria specified in the XEP. I don't see it checking against domain/resource. Am I misreading it? 

Referring to this function:
https://github.com/processone/ejabberd/blob/master/src/mod_privacy.erl#L641-L659

That could be why `conference.chat.qa.muc.com/12679` doesn't block all messages from this user in every MUC room, but `3382@conference.chat.qa.muc.com/12679` blocks all messages from that user in room `3382`. `12679` is that user's nick in my implementation.

**Comment by zinid** [comment]
> I don't see it checking against domain/resource

Ah, ok, I finally got you :)
Yes, indeed, there is incomplete matching in the code, should be fixed.

**Comment by MattFoley** [comment]
Thanks!
