### ISSUE TITLE
Can't remove multiple messages from offline queue

### ISSUE THREAD

**Issue by drequivalent** [processone/ejabberd#1962]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian 8

> How did you install ejabberd (source, package, distribution)?

Package

>  What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

In web administration interface, I was trying to remove multiple messages from user's offline queue.
I tick on all the messages I want gone, and click "Delete selected"

Expected behavior - all the messages I marked should be gone
What achually happens - ejabberd removes only the first message

**Comment by badlop** [comment]
Problem confirmed. It was introduced long ago, when mod_offline was improved in this commit: 901d2e0aed83d195a4d1cf2929114b07dcac0dd8. Thanks for reporting! I can look for a fix later today.
