### ISSUE TITLE
mod_pubsub doesn't sent retract notification with +notify

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1963]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Debian Stable

> How did you install ejabberd (source, package, distribution)?

ProcessOne Debian packages

> What did not work as expected? Are there error messages in the log? What

JID subscribed using +notify to Pubsub nodes doesn't receive retract notifications when an item is deleted. This works for standard subscribed nodes.

**Comment by cromain** [comment]
I assume you are referring to PEP nodes.
In this case this is expected behavior, see node_pep options: notify_retract is set to false.

**Comment by edhelas** [comment]
Oh ok, so I'll see if I can change this behavior on my side
