### ISSUE TITLE
mnesiadb/PREVIOUS.LOG fails when joining cluster.

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#1967]
> What version of ejabberd are you using?

17.06

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

as an embedded elixir project

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Randomly getting following error when calling ejabberd_admin.join_cluster does not happen always but sometimes. and after this failure the whole docker image must be restarted...
```
11:43:00.233 [error] Mnesia(:"ejabberd@ip-172-31-22-236.ec2.internal"):
 ** ERROR ** (core dumped to file: '/opt/app/MnesiaCore.ejabberd@ip-172-31-22-236.ec2.internal_1503_920580_232579')
 ** FATAL ** {:error,
 {'Cannot rename disk_log file', :latest_log, '/opt/app/mnesiadb/PREVIOUS.LOG',
  {:log_header, :trans_log, '4.3', '4.15',
   :"ejabberd@ip-172-31-22-236.ec2.internal", {1503, 920580, 218871}},
  {:file_error, '/opt/app/mnesiadb/PREVIOUS.LOG', :enoent}}}

11:43:10.234 [error] Mnesia(:"ejabberd@ip-172-31-22-236.ec2.internal"):
 ** ERROR ** :mnesia_event got unexpected event: {:EXIT, #PID<0.3053.0>, :killed}
```

**Comment by badlop** [comment]
Looking at erlang documentation:
> enoent: The file does not exist.

Some ideas: Maybe wrong file permissions, or wrong permission to write in that dir and create a new file, or to rename it... ? Or missing disk space.

**Comment by jonni-larjomaa** [comment]
figured it out, during some Mnesia operation, the join_cluster was called. This rare occasion may crash the existing process which is backing up the logs. and crashes the whole app at the same time. I don't know if there could be a way to figure out if amensia is safe to stop as the join_cluster operation stops and starts both ejabberd and Mnesia.

**Comment by badlop** [comment]
So, it's better to call join_cluster when there is low activity in the server, right?

Can this ticket be closed?

**Comment by jonni-larjomaa** [comment]
Yes the ticket can be closed. And yes it seems so that you should first stop all traffic and then call join cluster after a while waiting.
