### ISSUE TITLE
Check message archive

### ISSUE THREAD

**Issue by DwijadasDey** [processone/ejabberd#1970]
> What version of ejabberd are you using?
16.09

> What operating system (version) are you using?
Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
Package

I have enabled the mod_mam for message archiving with the following configuration

```
mod_mam:
    default: always
    cache_size: 1000
    cache_life_time: 3600
```

Restarted the ejabberd. Now i want to test/query the archive. I can find lot of XML file to write query. 
How should i send the xml request to the ejabberd server to check the message archive ? May be this is a very stupid question.
 
Also in the admin console, I did not find any link for database where i can see the archive messages. Shall i need to configure something more so that i can browse message archive?

**Comment by DwijadasDey** [comment]
Oh, I only need to enable xmpp console in pidgin.
"Tools -> XMPP Console -> XMPP Console".

**Comment by zinid** [comment]
The queries to send are described [here](https://xmpp.org/extensions/xep-0313.html).
