### ISSUE TITLE
s2s_use_starttls always checks if certs are self signed and fails s2s ext auth

### ISSUE THREAD

**Issue by james-d-elliott** [processone/ejabberd#1972]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have included a log message and related configuration sections in this issue. I have looked into this for a few days and it appears that the optional and required options act like the required_trusted option is meant to in as much as they reject self signed certs. While I prefer signed certs (letsencrypt) and previously had it set to required_trusted I wanted to change it on a temporary basis.

Interestingly the behavior is slightly different with required_trusted, it sends the client a message explaining why the connection failed. With just required it does not and just fails with the info log message. The first log message is from the option set to optional, second is from required, third is from required_trusted.

s2s_use_starttls: optional
```[info] <0.5134.0>@ejabberd_s2s_in:handle_auth_failure:206 (tls|<0.5133.0>) Failed inbound s2s EXTERNAL authentication conference.jabber.ccc.de -> domain.com (::FFFF:146.255.57.226): self signed certificate in certificate chain```

s2s_use_starttls: required
```[info] <0.3436.0>@ejabberd_s2s_in:handle_auth_failure:206 (tls|<0.3435.0>) Failed inbound s2s EXTERNAL authentication conference.jabber.ccc.de -> domain.com (::FFFF:146.255.57.226): self signed certificate in certificate chain```

s2s_use_starttls: required_trusted
```[info] <0.4044.0>@ejabberd_s2s_out:process_closed:161 Failed to establish outbound s2s connection domain.com -> conference.jabber.ccc.de: Peer certificate rejected: self signed certificate in certificate chain; bouncing for 167 seconds```

```s2s_use_starttls: required
s2s_certfile: "/path/to/certfile.pem"
s2s_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
s2s_dhfile: "/path/to/dhfile.pem"
s2s_tls_compression: false
  -
    port: 5269
    module: ejabberd_s2s_in
    transport: tcp
    ip: "::"
    shaper: s2s_shaper
    protocol_options:
        - "no_sslv2"
        - "no_sslv3"
```

**Comment by james-d-elliott** [comment]
Interesting, maybe it's trying to say my certs are self signed? I'm not 100% sure. IM Observatory says they are valid...

**Comment by zinid** [comment]
> maybe it's trying to say my certs are self signed?

Both. As you see by "inbound" (remote cert is self-signed) or "outbound" (local cert is self-signed).
Regarding inbound: this typically happens when openssl couldn't find a directory with CA root certs. Try to set `ca_path: /path/to/ca-bundle` explicitly in `ejabberd.yml`.
Regarding outbound: that's a problem of the remote side if you think your cert is correct.

**Comment by zinid** [comment]
Ah, sorry, the option is `s2s_cafile`.

**Comment by james-d-elliott** [comment]
```
ca_path: "/etc/ssl/certs"
s2s_cafile: "/etc/ssl/certs/ca-certificates.crt"
s2s_use_starttls: optional
```

I've set both. Still getting the inbound error with starttls as optional. As I understand it the local server is saying the remote cert is self signed by your first reply? 

`[info] <0.12676.0>@ejabberd_s2s_in:handle_auth_failure:206 (tls|<0.12675.0>) Failed inbound s2s EXTERNAL authentication conference.jabber.ccc.de -> domain.com (::FFFF:146.255.57.226): self signed certificate in certificate chain`

**Comment by zinid** [comment]
> Also the remote cert is self signed

So what is the problem then?

> Realistically by reading the documentation the only option that should reject self signed is require_trusted.

This option is absolutely unrelated for s2s SASL authentication. SASL EXTERNAL will fail in any case with invalid certs and dialback will be attempted **if** `mod_s2s_dialback` is loaded and **if** `s2s_use_starttls` is not `require_trusted`.

**Comment by james-d-elliott** [comment]
Yeah it was mod_s2s_dialback not being loaded - thanks for all your help, I disabled a lot of mods in trying to fix something else.

**Comment by zinid** [comment]
On the other hand, I think we should eliminate the option `required_trusted`. Such behaviour can be emulated by not loading `mod_s2s_dialback` and `s2s_use_starttls: required`.

**Comment by james-d-elliott** [comment]
I agree for the most part. required_trusted seems to give more feedback to clients as to why they can't join a muc for example, if you set required and don't have mod_s2s_dialback and the muc server is self signed it just fails to join and doesn't seem to send the client a message as to why.

I would probably look towards having an option(s) just for s2s certificate trust. To me having a whole mod for it seems a bit excessive but there may be a reason for it.

Also don't think it's currently noted in the docs at all: https://docs.ejabberd.im/admin/configuration/
