### ISSUE TITLE
ejabberdctl modules_update_specs Failed RPC connection to the node ejabberd@localhost: timeout

### ISSUE THREAD

**Issue by vitich** [processone/ejabberd#1973]
> What version of ejabberd are you using?

ejabberd-17.08-0.x86_64

> What operating system (version) are you using?

Red Hat Enterprise Linux Server release 7.3 (Maipo)

> How did you install ejabberd (source, package, distribution)?

rpm package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberdctl modules_update_specs 
Failed RPC connection to the node ejabberd@localhost: timeout

ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 17.08 is running in that node

**Comment by cromain** [comment]
I can't reproduce this.
If your network connection is slow, checkout/update of contributed modules can take long, and will trigger ctl timeout. in your case you must force ejabberdctl to not timeout

ejabberdctl --no-timeout modules_update_specs
