### ISSUE TITLE
Where to find documentation for the issue  #1743 => [error] emulator Discarding message ... in an old incarnation (2) of this node (3)

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#1975]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?
CENTOS 7

> How did you install ejabberd (source, package, distribution)?
RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Could you tell me where to find the documentation for this issue? #1743

**Comment by zinid** [comment]
Duplicate of #1743
