### ISSUE TITLE
Feature request, implement mod_register_redirect to return OOB registration URL

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#1976]
> What version of ejabberd are you using?
17.08

There is some administrators, like me, that prefers to handle registrations on a separate web page. In prosody there's a module called mod_register_redirect (https://modules.prosody.im/mod_register_redirect.html) that allows the server to return a OOB URL when the user try to register on the server. 

Having such module on ejabberd as well would help a lot.

See https://xmpp.org/extensions/xep-0077.html#redirect for the XEP details.

**Comment by zinid** [comment]
The new option `redirect_url` is introduced in `mod_register` module, an example config:
```yaml
mod_register:
  redirect_url: "http://my.site.org/register"
```
