### ISSUE TITLE
harden ejabberdctl

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#1977]
Hi,

running shellcheck (http://www.shellcheck.net/) against ejabberd 17.08's ejabberdctl gives me ~77 hints+warnings.

IMO it would be for the best to address those.

**Comment by cromain** [comment]
This is good point, i've applied some improvements (will apply a single commit when done), but there are some warnings what MUST NOT be covered.

Example: we really don't want to quote ERLANG_OPTS and EJABBERD_OPTS as it contains several arguments that must not be passed as a single one. It would be best to use arrays, but i'm not sure this will be compatible with all shells.

Also about this one
```
        as_install_user) su -c '"$0" "$@"' "$INSTALLUSER" -- "$@" ;;
                               ^-- SC2016: Expressions don't expand in single quotes, use double quotes for that.
```
I think actual code is good.

Note: ejabberdctl should also be able to run from bash to busybox's implementation of ash.

**Comment by cromain** [comment]
this commit is a first attempt to harden ctl script
there are thing i'm not sure about, like
`: "${EJABBERD_CONFIG_PATH:="$ETC_DIR/ejabberd.yml"}"`

and also the points i explained before

**Comment by cromain** [comment]
testing with mksh and bash, both ${X:="$Y"} and "${X:="$Y"}" looks to work correctly but only the second one makes shellcheck happy

**Comment by weiss** [comment]
> there are thing i'm not sure about, like
> `: "${EJABBERD_CONFIG_PATH:="$ETC_DIR/ejabberd.yml"}"

This is [standard][1] shell syntax and shoould work on all real-world `/bin/sh`s.

[1]: http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02

**Comment by weiss** [comment]
> `${X:="$Y"}` and `"${X:="$Y"}"` looks to work correctly but only the second one makes shellcheck happy

Well that's the usual issue with POSIX shell variable expansion: If you set `foo='one two'`, `$foo` without quotes will expand to the separate arguments `one` and `two`, so e.g. `[ $foo = 'whatever' ]` would go wrong.  Same is true for `${X:="$Y"}`.

Basically just *always* use double-quotes around `"$foo"`, except when you *want* `$foo` to expand to multiple words, e.g. in `for $element in $foo`.

**Comment by cromain** [comment]
i think last version is good enough.
