### ISSUE TITLE
mod_http_upload stopped working

### ISSUE THREAD

**Issue by Bluberlutsch** [processone/ejabberd#1978]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS Linux release 7.3.1611 (Core)

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When i want to upload a picture it gets a upload slot asigned, but the actual upload process doesn't start. It worked before but suddenly stopped working.

mod_http_upload:create_slot:585 Got HTTP upload slot for jid (file: picture.png)

excerpt from ejabberd.yml:
mod_http_upload:
   docroot: "/opt/ejabberd-17.04/upload"
   put_url: "https://@HOST@:5443/upload"
   access: local
   thumbnail: false

listen
    port: 5443
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "upload": mod_http_upload
    tls: true
    certfile: 'CERTFILE'
    protocol_options: 'TLSOPTS'

Where can be the possible error?

**Comment by weiss** [comment]
Can you access `https://example.com:5443/upload/` (replace `example.com` with your XMPP domain) using a browser?  (You should see a `404 Not found` error.)

**Comment by Bluberlutsch** [comment]
The connection times out and Gajim throws an "Network is unreachable" error message.

**Comment by weiss** [comment]
So it's most probably a networking / firewall issue outside the scope of ejabberd.

I'd start tracking this down by trying to connect to localhost:5443 and if that works example.com:5443 locally on the XMPP server.

**Comment by Bluberlutsch** [comment]
Ok, i will try that. But it's weird, i haven't changed anything regarding networking  or firewalls.

**Comment by KevinR16** [comment]
i have the same issue. but i can access to https://example.com:5443/upload/ with a message "not found".
