### ISSUE TITLE
Special characters insert issue  mod mam module

### ISSUE THREAD

**Issue by ntiseira** [processone/ejabberd#1979]
Hi,

I'm having a problem with mod_mam module when insert special characters in the database. The query sended to sql server is not correct. For example:

Message sended for xmpp:  "Hola como andas?" (spanish). This message ise delivered correctly.
Message saved: "hola. cÃ³mo andÃ¡s?". This message is not the original message.

The collation of the db seted is  sql_latin1_general_cp1_ci_as .

**Comment by zinid** [comment]
We cannot address your question because:
1) We don't know your server version (there were some problems with characterset in the past)
2) We don't know what database you're using

**Comment by ntiseira** [comment]
1.Ejabberd 17.08
2. Sql server 2014

Regards,

**Comment by zinid** [comment]
> Sql server 2014

What is it? MS SQL? Then I'm not sure, you probably you need to make sure the collation is configured to accept UTF-8 encoding (up to all 4 bytes).
