### ISSUE TITLE
Configuring Mysql server for ejabberd

### ISSUE THREAD

**Issue by nikeshkedlaya** [processone/ejabberd#1980]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?
Windows 10

> How did you install ejabberd (source, package, distribution)?
binary source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to setup ejabberd with mysql backend rather than mnesia. I am running ejabberd in my local and mysql setup is there in remote server. How to configure this in ejabberd.yml file? It actually looks like this

sql_type: mysql
sql_server: "xxx.xxx.xxx.xxx"
sql_database: "ejabberd"
sql_username: "root"
sql_password: ""

##
## If you want to specify the port:
sql_port: 3306

If i put remote ip it throws an error as it cannot connect because server ip has username and password. Where do i set username and password for server?

**Comment by zinid** [comment]
> If i put remote ip it throws an error as it cannot connect because server ip has username and password

Who throws this? Please show the error message.

**Comment by nikeshkedlaya** [comment]
@zinid i can see the error in error log file. It says connection failed.

I have a remote ip like xxx.xxx.xxx.xx and my remote server has username and password. I have installed mysql in remote server. In ejabberd.yml file i can define username and password for mysql. How do i specify username password for my remote server? as i can see only server ip i can give (sql_server)

**Comment by zinid** [comment]
Connection failed means your mysql is not acceptable from outside. Just configure ports/firewall properly.

**Comment by nikeshkedlaya** [comment]
No there is no firewall. I am connecting from my web application already. Just tel me how to configure server ip with username and password in ejabberd.yml file. If i configure that i can connect to mysql server which is running in that machine.

**Comment by weiss** [comment]
> Just tel me how to configure server ip with username and password in ejabberd.yml file.

See [the documentation](https://docs.ejabberd.im/admin/databases/mysql/#ejabberd-configuration).

**Comment by nikeshkedlaya** [comment]
@weiss I can add only server ip (sql_server) . How to add server username and password?

**Comment by nikeshkedlaya** [comment]
I am expecting somrthing like this
sql_type: mysql
sql_server: "xxx.xxx.xxx.xxx"
server_username:"abc" /* username for server */
server_password:"pass" /* password for server */
sql_database: "ejabberd" 
sql_username: "root" /* database username */
sql_password: "" /* database password*/

**Comment by zinid** [comment]
So what protocol should ejabberd use to authenticate? :)

**Comment by nikeshkedlaya** [comment]
@zinid I am getting error something like this

`<0.2110.0>@ejabberd_sql:log:933 p1_mysql_conn: Failed connecting to "192.168.0.6":3306 : {error,"connect failed : {error,nxdomain}"}`

192.168.0.6 is my remote ip and it has to be authenticated using username and password

**Comment by nikeshkedlaya** [comment]
I can connect to mysql server now. I have added a user using ejabberdctl but it did not get stored in table. I have enabled the sql general log but no logs are written. In which table user data will get stored ?

**Comment by zinid** [comment]
It's `users` table.

**Comment by nikeshkedlaya** [comment]
I migrated all the data from mnesia to mysql (followed the instructions given in documentation) . No data got migrated. All tables are empty.

**Comment by nikeshkedlaya** [comment]
@zinid , i have used following command to migrate the data to mysql (as per documentation)

1. Connect to a running ejabberd:
    ./ejabberdctl live
    ejd2sql:export(<<"ejabberd@localhost">>, sql)

Node name is ejabberd@localhost 

Virtual hosts are : 
test
msg.kaho.com

We tried putting the msg.kaho.com in ejabberd@localhost and various other combination such as "localhost" etc.. but the tables in mysql are not populating.

**Comment by zinid** [comment]
So nothing works for you, OK.
