### ISSUE TITLE
`redis_reconnect_timeout` is no longer a valid option

### ISSUE THREAD

**Issue by JDiPierro** [processone/ejabberd#1983]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Debian Stretch

> How did you install ejabberd (source, package, distribution)?

From Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have `redis_reconnect_timeout` defined. It looks like this option was removed [here](https://github.com/processone/ejabberd/commit/7129aebe7632468de075d9fc3686d6d692e2347f#diff-8261d91d5340eccaaad2a8e184bd036dL225) and we now see `[error] unknown option 'redis_reconnect_timeout' will be likely ignored` on startup.

I'm not sure if the option was supposed to be removed or was accidentally removed during cleanup. The [admin/configuration documentation](https://docs.ejabberd.im/admin/configuration/) still lists the option.

**Comment by badlop** [comment]
Umm, the redis_reconnect_timeout option and other ones are mentioned in the Guide, and also in `docker/conf/ejabberd.yml.tpl`.

**Comment by zinid** [comment]
There is only `redis_connect_timeout` now.

**Comment by badlop** [comment]
Ok then, option removed in the Guide and the docker example config.
