### ISSUE TITLE
unknown option 'drop_chat_states'  for mysql 

### ISSUE THREAD

**Issue by prabhatpankaj** [processone/ejabberd#1985]
[error] <0.192.0>@gen_mod:validate_opts:529 unknown option 'drop_chat_states' for module 'mod_client_state' will be likely ignored, available options are: queue_pep, queue_chat_states, queue_presence

I am getting this error for mysql configuration .

kindly suggest me the solution for this problem .

**Comment by badlop** [comment]
A year ago that option was removed, and a new one added: https://github.com/processone/ejabberd/commit/4f009e64fc11ca352443e6a9df5fa4d7cb715f5c

But it was still mentioned in the example configuration file. I've fixed that. Thanks for reporting!
