### ISSUE TITLE
SNMP module to monitor ejabberd services

### ISSUE THREAD

**Issue by RamzyVirani** [processone/ejabberd#1989]
> What version of ejabberd are you using?
17.07

> What operating system (version) are you using?
CentOS 7.3

> How did you install ejabberd (source, package, distribution)?
Installer [Process One Linux 64 bit Installer](https://www.process-one.net/downloads/ejabberd/17.07/ejabberd-17.07-linux-x86_64-installer.run)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
**Background**
We are developing custom modules as per our project requirements. One of which is developing a monitoring module with SNMP protocol so that our data center monitoring team can monitor ejabberd services from their standard SNMP monitoring portal, we also want to use SNMP Traps to generate alerts. 
**Already Done**
We developed a statsdb module (inspired by [mod_statsdx](https://github.com/processone/ejabberd-contrib/tree/master/mod_statsdx)) which uses ets tables to manage counters. Now we want to use erlang snmp application to start agent process which will respond to managers Get/Set/Get-Next calls. 
**Problem**
When I try to start the erlang SNMP application with `application:start(snmp)` with basic configuration I get `{error,{"no such file or directory","snmp.app"}}` I tried to set environment variables with `application:set_env(snmp, agent, [...agent configuration...])` but still no success. 

Can someone please guide me how can I use erlang's builtin SNMP application with standard ejabberd package? I tried to install ejabberd from the source but had issues and decided to go with the installer.

**Comment by zinid** [comment]
I'm not sure installer is providing SNMP application inside. Check for `snmp.beam` or `snmp.app` presence in the directory where ejabberd is installed.

**Comment by RamzyVirani** [comment]
Nope, did not find `snmp.beam` or `snmp.app` in ejabberd installation directory.

**Comment by zinid** [comment]
So it's not a part of the installer. Consider building from sources then or use your package manager if possible.

**Comment by RamzyVirani** [comment]
Actually, I am a PHP developer and exploring ejabberd/erlang for my current project. Can you guide me What package manager should I use and how to use it? As I stated earlier, I tried to build ejabberd from source but did not succeed.

**Comment by zinid** [comment]
If you cannot build ejabberd how do you suppose to add SNMP functionality to ejabberd? This is not trivial.

**Comment by RamzyVirani** [comment]
I developed some basic `gen_mod` modules in ejabberd which were needed in our project. I know how to extend ejabberd functionality with hooks and commands, install/uninstall modules. What I do not know is, How can I use package manager to add external libraries (applications) like  [ninenines/gun](https://github.com/ninenines/gun) or snmp. Last month I tried to build it from source and added `{gun,".*",{git, "https://github.com/ninenines/gun",{tag, "1.0.0-pre.2"}}},`  in `rebar.config` under `deps` but could not build it without errors. 

I can try building it again from the source and share errors when I get them. Maybe you can help me.

**Comment by zinid** [comment]
Well, configuring rebar and building third-party Erlang packages are out of scope of our support.

**Comment by RamzyVirani** [comment]
Least you can do is share a good resource (link or document) where I can learn and move on.

**Comment by cromain** [comment]
you should checkout ejabberd repository and follow README about compiling/installing ejabberd.
installing erlang will make your environment able to use SNMP.
then you can follow your usual process with install/uninstall modules.
