### ISSUE TITLE
configure.beam sometimes incorrectly added to ejabberd.app

### ISSUE THREAD

**Issue by satanasov** [processone/ejabberd#199]
Hello guys.

Just now I tried compile ejabberd (master). No problem compiling, but I hit a snag on configureng - it appears that the compiled ```ebin/configure.beam``` is not copied to ```$prefix/lib/ejabberd/ebin```

This is simple corrected by transfering ```$compill_dir/ebin/configure.beam``` to ```$prefix/lib/ejabberd/ebin``` ... could you patch the make file?

**Comment by cromain** [comment]
configure.beam is not used and has been removed from repository.
so this error should not occur anymore.
