### ISSUE TITLE
Ejabberd 17.08 fails to start a cluster

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#1990]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

CENTOS 7

> How did you install ejabberd (source, package, distribution)?

.RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to create a cluster:
_sudo /opt/ejabberd-17.08/bin/ejabberdctl join_cluster 'ejabberd@node1'_

_**Shell message:**_
```
Error: {{shutdown,
            {failed_to_start_child,ejabberd_commands,
                {aborted,{no_exists,ejabberd_commands}}}},
        {ejabberd_app,start,[normal,[]]}}_
```
_**Error.log:**_
```
2017-09-07 14:05:18.165 [error] <0.670.0>@ejabberd_mnesia:mnesia_op:438
 failure on mnesia change_table_copy_type
 [ejabberd_commands,'ejabberd@node_2',ram_copies]:
 {aborted,{no_exists,ejabberd_commands}}
2017-09-07 14:05:18.165 [error] <0.707.0> CRASH REPORT Process <0.707.0>
 with 0 neighbours exited with reason:
 {aborted,{no_exists,ejabberd_commands}} in gen_server:init_it/6 line 352
2017-09-07 14:05:18.165 [error] <0.671.0> Supervisor ejabberd_sup
 had child ejabberd_commands started with ejabberd_commands:start_link()
 at undefined exit with reason {aborted,{no_exists,ejabberd_commands}} in context start_error
2017-09-07 14:05:18.213 [error] <0.609.0> CRASH REPORT Process <0.609.0>
 with 0 neighbours exited with reason:
 {{shutdown,{failed_to_start_child,ejabberd_commands,{aborted,{no_exists,ejabberd_commands}}}},
 {ejabberd_app,start,[normal,[]]}} in application_master:init/4 line 134
```

After this error, if I restart ejabberd@node_2 the cluster works fine, or so it seems.

Could it be related to the issue #1960?

**Additionally**, the cluster is divided in two node-machines.
If I reboot both machines at the same time to simulate a crash, one of the nodes doesn't start.

_**Error.log:**_
```
2017-09-07 14:24:35.331 [error] <0.175.0> gen_server ejabberd_mnesia terminated with reason: {aborted,{no_exists,[sr_group]}} in mnesia:abort/1 line 318
2017-09-07 14:24:35.341 [error] <0.175.0> CRASH REPORT Process ejabberd_mnesia with 0 neighbours exited with reason: {aborted,{no_exists,[sr_group]}} in gen_server:terminate/7 line 812
2017-09-07 14:24:35.342 [critical] <0.250.0>@gen_mod:start_module:212 Problem starting the module mod_shared_roster for host localhost
 options: []
 exit: {{aborted,{no_exists,[sr_group]}},
        {gen_server,call,
                    [ejabberd_mnesia,
                     {create,mod_shared_roster_mnesia,sr_group,
                             [{disc_copies,['ejabberd@node1']},
                              {attributes,[group_host,opts]}]},
                     1800000]}}
[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},
 {mod_shared_roster_mnesia,init,2,
                           [{file,"src/mod_shared_roster_mnesia.erl"},
                            {line,46}]},
 {mod_shared_roster,start,2,[{file,"src/mod_shared_roster.erl"},{line,76}]},
 {gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,200}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},
 {supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
 {supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]}]
2017-09-07 14:24:35.342 [critical] <0.250.0>@gen_mod:maybe_halt_ejabberd:294 ejabberd initialization was aborted because a module start failed.
```

**Comment by ghTravis** [comment]
I'm also experiencing this same issue. I'm running on ubuntu 14.04 LTS and we're using the sql backend module. The initial join cluster seems to fail, but after a restart the cluster appears to be connected and working fine.

**Comment by cromain** [comment]
this should have been fixed by a3da27e included in ejabberd 17.09

**Comment by Emilio-Gonzalez** [comment]
Yes, the second issue have been fixed: both machines of a cluster restart correctly.

But I continue receiving the same error when I try to create a cluster.
Is it correct?
After this error, I restart the node and it seems ok.

_sudo /opt/ejabberd-17.09/bin/ejabberdctl join_cluster 'ejabberd@node1'_

**_Shell message:_**
_Error: {{shutdown,
            {failed_to_start_child,ejabberd_commands,
                {aborted,{no_exists,ejabberd_commands}}}},
        {ejabberd_app,start,[normal,[]]}}__

**Comment by dlameri** [comment]
I'm having the same problem, with the newest version.
