### ISSUE TITLE
call to undefined function ejabberd_auth_sql:start

### ISSUE THREAD

**Issue by mradzinski** [processone/ejabberd#1995]
> What version of ejabberd are you using?
latest

> What operating system (version) are you using?
Ubuntu Server 16.04

> How did you install ejabberd (source, package, distribution)?
package (apt-get install ejabberd)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Given the following configuration:
```
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "ejabberd"
odbc_password: "****"
odbc_port: 3306
```

ejabberd crashes with:
`Application ejabberd exited with reason: call to undefined function ejabberd_auth_sql:start`

MySQL server is up and running, I'm actually able to connect to it.

**Comment by mradzinski** [comment]
My bad, I was following this guide, which says to set `sql` as my auth method, but it should've been `odbc`. Closing.

**Comment by zinid** [comment]
No problem
Consider upgrading the version though :smiley:
