### ISSUE TITLE
Riak Travis Ci tests (question)

### ISSUE THREAD

**Issue by anghiloglu-dmitrii** [processone/ejabberd#2001]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've forked ejabberd 17.08 and I try to run tests on travis ci. But got errors like this
```
[error] database error:
** Function: count_by_index
** Table: passwd
** Index = <<"host">>
** Key: <<"riak.localhost">>
** Error: {"phase":"index","error":"{indexes_not_supported,riak_kv_bitcask_backend}"
```
I found in travis-ci logs a successful build for this revision (https://travis-ci.org/processone/ejabberd/builds/264339577). 

Please help to understand why the same revision in my case fails. (logs https://travis-ci.org/anghiloglu-dmitrii/ejabberd/jobs/276253759)

Thank you.

**Comment by badlop** [comment]
Maybe they use different Riak versions or configurations? I see "dist": "precise" to "trusty".

**Comment by anghiloglu-dmitrii** [comment]
Thank you very much. You saved me a lot of time. I have added
> language: erlang
> **dist: precise**
and tests completed successfully.
