### ISSUE TITLE
Implement XEP-0312: PubSub Since

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2002]
The support of Pubsub Since in ejabberd will reduce the number of stanza send to the clients when they are connecting (for PEP and Pubsub).

I'm planning to implement it in Movim as soon as it is available in ejabberd.

**Comment by cromain** [comment]
this xep is deferred for years. why don't you want to use rsm and get items after given date ?

**Comment by edhelas** [comment]
Because RSM has a different goal than PubSub Since. This is useful especially to filter on login the hundreds of PEP notifications that can be received (or by the node configured using sub_or_presence).

**Comment by cromain** [comment]
When connecting with "big" accounts on Movim a lot of PEP and Pubsub notifications are simply discarded because they were already received before, it would be nice to filter them to speed up this part.

**Comment by edhelas** [comment]
It's also possible to implement that feature using MAM as MAM already cover those use cases https://xmpp.org/extensions/xep-0313.html#business-storeret-pubsub-archives , we have to check for PEP.
