### ISSUE TITLE
Unable to Register SIP client

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#2003]
> What version of ejabberd are you using? 
ejabberd-17.08.35

> What operating system (version) are you using? Debian Jessie 64bits
Debian Jessie 64bits

> How did you install ejabberd (source, package, distribution)?
source

Prior to Erlang/OTP version 20.0 if it worked.

ejabberd.log:

> ** Function: mod_sip:request/3
** Args: [{sip,request,{2,0},<<"REGISTER">>,[{via,[{via,<<"SIP">>,{2,0},<<"TLS">>,<<"192.168.0.15">>,50959,[{<<"branch">>,<<"z9hG4bK-363336-42a05aee7ef59182152ea6291a5bb2c3">>},{<<"received">>,<<"91.117.185.64">>}]}]},{'call-id',<<"1e149a34a092756f36af035cab34efe0@0:0:0:0:0:0:0:0">>},{cseq,1},{from,{<<"\"carlos\"">>,{uri,<<"sip">>,<<"carlos">>,<<>>,<<"suchat.org">>,undefined,[],[]},[{<<"tag">>,<<"d3a3134b">>}]}},{to,{<<"\"carlos\"">>,{uri,<<"sip">>,<<"carlos">>,<<>>,<<"suchat.org">>,undefined,[],[]},[]}},{'max-forwards',70},{'user-agent',<<"Jitsi2.10.5550Windows 10">>},{expires,600},{contact,[{<<"\"carlos\"">>,{uri,<<"sip">>,<<"carlos">>,<<>>,<<"192.168.0.15">>,50959,[{<<"transport">>,<<"tls">>},{<<"registering_acc">>,<<"suchat_org">>}],[]},[{<<"expires">>,<<"600">>}]}]},{'content-length',0}],<<>>,{uri,<<"sip">>,<<>>,<<>>,<<"suchat.org">>,undefined,[],[]},undefined,undefined},{sip_socket,tls,{tlssock,#Port<0.211801>,#Ref<0.1199224770.162660355.73717>},{{0,0,0,0,0,65535,42116,44160},5061},{{0,0,0,0,0,65535,23413,47424},50959},<0.25542.7>},{trid,<0.25543.7>,server}]
** Reason: {'EXIT',{undef,[{crypto,rand_bytes,[20],[]},{esip,make_hexstr,1,[{file,"src/esip.erl"},{line,543}]},{mod_sip,make_auth_hdr,1,[{file,"src/mod_sip.erl"},{line,315}]},{mod_sip,request,4,[{file,"src/mod_sip.erl"},{line,169}]},{esip,callback,3,[{file,"src/esip.erl"},{line,587}]},{esip_server_transaction,trying,2,[{file,"src/esip_server_transaction.erl"},{line,87}]},{gen_fsm,handle_msg,8,[{file,"gen_fsm.erl"},{line,483}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}

In the server logs I have many equal messages from other users.

**Comment by zinid** [comment]
This is fixed in [esip](https://github.com/processone/esip), but the repo url is not updated in ejabberd's `rebar.config`. This will be done prior to 17.09 release.

**Comment by suchatorg** [comment]
Thanks

**Comment by zinid** [comment]
BTW, you can update `rebar.config` manually and recompile ejabberd if you're eager to use it.

**Comment by suchatorg** [comment]
Yes i'm with it

**Comment by suchatorg** [comment]
Yes, now it works fine, thanks for the info
