### ISSUE TITLE
Hooks documentation should be improved.

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#2005]
Hi,

I'm developing custom modules on top of ejabberd, the biggest problem is that there is no good documentation or no documentation at all about all the hooks which are supported by ejabberd. They should be documented more throughly and atleast there should be a actively updated list of all hooks.

**Comment by zinid** [comment]
This is easier to say than to do.

**Comment by jonni-larjomaa** [comment]
I understand, but as said a list of existing hooks would help a lot ( I could figure out its meaning from its name or from code) but now there is no way of knowing what and where to look...

**Comment by zinid** [comment]
If the list is enough, you can run
```
$ ./tools/hook_deps.sh src
```
From ejabberd directory. This will create `src/hooks_type_test.erl` file where hooks will be listed and arranged.

**Comment by jonni-larjomaa** [comment]
Got following errors and no hooks_type_test.erl

[Jonni@farady ejabberd  (master *=)]$ tools/hook_deps.sh src
src/ejabberd_commands_doc.erl:37: Error: syntax error before: '?'
src/ejabberd_ctl.erl:142: Warning: not an atom: Module
src/ejabberd_ctl.erl:142: Warning: not an atom: Function
src/mod_adhoc.erl:46: Error: function mod_adhoc:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_adhoc.erl:49: Error: function mod_adhoc:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_adhoc.erl:93: Error: function mod_adhoc:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_adhoc.erl:95: Error: function mod_adhoc:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_blocking.erl:45: Error: function mod_blocking:process_iq/1 is registered as iq handler, but is not exported
src/mod_blocking.erl:55: Error: function mod_blocking:process_iq/1 is registered as iq handler, but is not exported
src/mod_carboncopy.erl:74: Error: function mod_carboncopy:iq_handler/1 is registered as iq handler, but is not exported
src/mod_carboncopy.erl:100: Error: function mod_carboncopy:iq_handler/1 is registered as iq handler, but is not exported
src/mod_delegation.erl:173: Warning: not an atom: Type
src/mod_disco.erl:54: Error: function mod_disco:process_local_iq_items/1 is registered as iq handler, but is not exported
src/mod_disco.erl:57: Error: function mod_disco:process_local_iq_info/1 is registered as iq handler, but is not exported
src/mod_disco.erl:60: Error: function mod_disco:process_sm_iq_items/1 is registered as iq handler, but is not exported
src/mod_disco.erl:63: Error: function mod_disco:process_sm_iq_info/1 is registered as iq handler, but is not exported
src/mod_disco.erl:133: Error: function mod_disco:process_local_iq_items/1 is registered as iq handler, but is not exported
src/mod_disco.erl:136: Error: function mod_disco:process_local_iq_info/1 is registered as iq handler, but is not exported
src/mod_disco.erl:139: Error: function mod_disco:process_sm_iq_items/1 is registered as iq handler, but is not exported
src/mod_disco.erl:142: Error: function mod_disco:process_sm_iq_info/1 is registered as iq handler, but is not exported
src/mod_irc.erl:216: Error: function mod_irc:process_disco_info/1 is registered as iq handler, but is not exported
src/mod_irc.erl:218: Error: function mod_irc:process_disco_items/1 is registered as iq handler, but is not exported
src/mod_irc.erl:220: Error: function mod_irc:process_register/1 is registered as iq handler, but is not exported
src/mod_irc.erl:222: Error: function mod_irc:process_vcard/1 is registered as iq handler, but is not exported
src/mod_irc.erl:224: Error: function mod_irc:process_command/1 is registered as iq handler, but is not exported
src/mod_last.erl:66: Error: function mod_last:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_last.erl:68: Error: function mod_last:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_last.erl:104: Error: function mod_last:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_last.erl:106: Error: function mod_last:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_mam.erl:206: Error: function mod_mam:process_iq_v0_2/1 is registered as iq handler, but is not exported
src/mod_mam.erl:208: Error: function mod_mam:process_iq_v0_2/1 is registered as iq handler, but is not exported
src/mod_mam.erl:210: Error: function mod_mam:process_iq_v0_3/1 is registered as iq handler, but is not exported
src/mod_mam.erl:212: Error: function mod_mam:process_iq_v0_3/1 is registered as iq handler, but is not exported
src/mod_mam.erl:214: Error: function mod_mam:process_iq_v0_3/1 is registered as iq handler, but is not exported
src/mod_mam.erl:216: Error: function mod_mam:process_iq_v0_3/1 is registered as iq handler, but is not exported
src/mod_mix.erl:141: Error: function mod_disco:process_local_iq_items/1 is registered as iq handler, but is not exported
src/mod_mix.erl:144: Error: function mod_disco:process_local_iq_info/1 is registered as iq handler, but is not exported
src/mod_mix.erl:147: Error: function mod_disco:process_local_iq_items/1 is registered as iq handler, but is not exported
src/mod_mix.erl:150: Error: function mod_disco:process_local_iq_info/1 is registered as iq handler, but is not exported
src/mod_mix.erl:153: Error: function mod_pubsub:iq_sm/1 is registered as iq handler, but is not exported
src/mod_mix.erl:155: Error: function mod_mix:process_iq/1 is registered as iq handler, but is not exported
src/mod_muc.erl:371: Error: function mod_muc:process_register/1 is registered as iq handler, but is not exported
src/mod_muc.erl:373: Error: function mod_muc:process_vcard/1 is registered as iq handler, but is not exported
src/mod_muc.erl:375: Error: function mod_muc:process_mucsub/1 is registered as iq handler, but is not exported
src/mod_muc.erl:377: Error: function mod_muc:process_muc_unique/1 is registered as iq handler, but is not exported
src/mod_muc.erl:379: Error: function mod_muc:process_disco_info/1 is registered as iq handler, but is not exported
src/mod_muc.erl:381: Error: function mod_muc:process_disco_items/1 is registered as iq handler, but is not exported
src/mod_offline.erl:134: Error: function mod_offline:handle_offline_query/1 is registered as iq handler, but is not exported
src/mod_offline.erl:168: Error: function mod_offline:handle_offline_query/1 is registered as iq handler, but is not exported
src/mod_ping.erl:228: Error: function mod_ping:iq_ping/1 is registered as iq handler, but is not exported
src/mod_ping.erl:230: Error: function mod_ping:iq_ping/1 is registered as iq handler, but is not exported
src/mod_privacy.erl:89: Error: function mod_privacy:process_iq/1 is registered as iq handler, but is not exported
src/mod_privacy.erl:119: Error: function mod_privacy:process_iq/1 is registered as iq handler, but is not exported
src/mod_private.erl:63: Error: function mod_private:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_private.erl:83: Error: function mod_private:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:67: Error: function mod_proxy65_service:process_disco_info/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:69: Error: function mod_proxy65_service:process_disco_items/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:71: Error: function mod_proxy65_service:process_vcard/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:73: Error: function mod_proxy65_service:process_bytestreams/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:280: Error: function mod_proxy65_service:process_disco_info/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:282: Error: function mod_proxy65_service:process_disco_items/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:284: Error: function mod_proxy65_service:process_vcard/1 is registered as iq handler, but is not exported
src/mod_proxy65_service.erl:286: Error: function mod_proxy65_service:process_bytestreams/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:285: Error: function mod_pubsub:process_disco_info/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:287: Error: function mod_pubsub:process_disco_items/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:289: Error: function mod_pubsub:process_pubsub/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:291: Error: function mod_pubsub:process_pubsub_owner/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:293: Error: function mod_pubsub:process_vcard/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:295: Error: function mod_pubsub:process_commands/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:331: Error: function mod_pubsub:iq_sm/1 is registered as iq handler, but is not exported
src/mod_pubsub.erl:333: Error: function mod_pubsub:iq_sm/1 is registered as iq handler, but is not exported
src/mod_push.erl:240: Error: function mod_push:process_iq/1 is registered as iq handler, but is not exported
src/mod_register.erl:48: Error: function mod_register:process_iq/1 is registered as iq handler, but is not exported
src/mod_register.erl:50: Error: function mod_register:process_iq/1 is registered as iq handler, but is not exported
src/mod_register.erl:74: Error: function mod_register:process_iq/1 is registered as iq handler, but is not exported
src/mod_register.erl:76: Error: function mod_register:process_iq/1 is registered as iq handler, but is not exported
src/mod_roster.erl:112: Error: function mod_roster:process_iq/1 is registered as iq handler, but is not exported
src/mod_roster.erl:147: Error: function mod_roster:process_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:43: Error: function mod_sic:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:45: Error: function mod_sic:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:47: Error: function mod_sic:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:49: Error: function mod_sic:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:61: Error: function mod_sic:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:63: Error: function mod_sic:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:65: Error: function mod_sic:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_sic.erl:67: Error: function mod_sic:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_stats.erl:42: Error: function mod_stats:process_iq/1 is registered as iq handler, but is not exported
src/mod_time.erl:45: Error: function mod_time:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_time.erl:55: Error: function mod_time:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:92: Error: function mod_vcard:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:94: Error: function mod_vcard:process_sm_iq/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:110: Error: function mod_vcard:process_search/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:112: Error: function mod_vcard:process_vcard/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:114: Error: function mod_disco:process_local_iq_items/1 is registered as iq handler, but is not exported
src/mod_vcard.erl:117: Error: function mod_disco:process_local_iq_info/1 is registered as iq handler, but is not exported
src/mod_version.erl:44: Error: function mod_version:process_local_iq/1 is registered as iq handler, but is not exported
src/mod_version.erl:55: Error: function mod_version:process_local_iq/1 is registered as iq handler, but is not exported
escript: exception error: undefined function ejabberd_auth:module_info/1
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 670)
  in call from erl_eval:expr_list/6 (erl_eval.erl, line 878)
  in call from erl_eval:expr/5 (erl_eval.erl, line 404)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 557)
  in call from erl_eval:expr/5 (erl_eval.erl, line 269)
  in call from lists:foreach/2 (lists.erl, line 1338)
  in call from dict:map_bucket/2 (dict.erl, line 481)

**Comment by zinid** [comment]
You need to have ejabberd compiled in order to run the script.
Anyway, here is the result of current code base: https://gist.github.com/zinid/5fa063f9121cede9ae747a480bce09d5

**Comment by jonni-larjomaa** [comment]
Many thanks for the gist, this helps a lot. for me it would be enough to update that gist with every ejabberd release...
