### ISSUE TITLE
Ejabberd 17.08 Docs & Push Notification

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#2006]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?
Ubuntu 16.04 LTS

> How did you install ejabberd (source, package, distribution)?
Linux Installer from ejabberd community

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

1.  I found out that by looking at the documentation for "Ejabberd for administrator", I see there is not much changes and it is same as what I've read since 17.04.  When will the documentation be updated?

2.  17.08 supports push notification, I was wondering how is the workaround on the current ejabberd 17.08?  Is there any reference?  How should the module works with in this new version?  Any idea?

3.  Can I setup the architecture for push notification let say I only have 1 ejabberd server.  In this ejabberd let say i define the hostname as "abc.domain.com" and then i have another sub-domain let say "push.domain.com" but this domain IP address is referring to the "abc.domain.com" on my DNS.  Is it possible this way?

Thanks.

**Comment by weiss** [comment]
> 17.08 supports push notification, I was wondering how is the workaround on the current ejabberd 17.08? Is there any reference? How should the module works with in this new version? Any idea?

Like in the [example configuration][1].

> Can I setup the architecture for push notification let say I only have 1 ejabberd server. In this ejabberd let say i define the hostname as "abc.domain.com" and then i have another sub-domain let say "push.domain.com" but this domain IP address is referring to the "abc.domain.com" on my DNS. Is it possible this way?

Not sure what setup you have in mind.  Note that `mod_push` just implements the XMPP server part of [XEP-0357][2].  That is, it won't generate APNS or GCM notifications itself (I think the Business Edition has code to do this).  16.08's `mod_push` will just [notify][3] the [app server][4] which must be operated by the mobile app vendor.

[1]: https://github.com/processone/ejabberd/blob/17.08/ejabberd.yml.example#L728
[2]: https://xmpp.org/extensions/xep-0357.html
[3]: https://xmpp.org/extensions/xep-0357.html#publishing
[4]: https://xmpp.org/extensions/xep-0357.html#sect-idm139821460852112
