### ISSUE TITLE
Missing ACK when leaving MUC with several resources from the same JID

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2007]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Debian Stable

> How did you install ejabberd (source, package, distribution)?

DEB packages from the ProcessOne website

> What did not work as expected? Are there error messages in the log? 

When the same JID joined several times the same MUC (using different resources like `test`, `test_`…) and when one of them is leaving it. No ACK is received from the presence unavailable. This causes UI issues in clients like Movim (that relies on this ACK to end properly everything).

```xml
<presence to='ejabberd@conference.jabber.ru/test_' type='unavailable'/>
no ack
```

> was the unexpected behavior? What was the expected result?

Receive a proper ACK, like on Prosody.
```xml
<presence to='jabberfr@chat.jabberfr.org/test_' type='unavailable'/>
<presence lang='en' to='test@movim.eu/94721904338646015664899' from='jabberfr@chat.jabberfr.org/test_' type='unavailable'>
    <x xmlns='http://jabber.org/protocol/muc#user'>
        <item affiliation='none' role='none'/>
        <status code='110'/>
    </x>
</presence>
```

See https://xmpp.org/extensions/xep-0045.html#exit as well.

**Comment by zinid** [comment]
Confirmed
