### ISSUE TITLE
Certificate Error & Ejabberd Folder

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#2009]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Linux installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

1.  I found out that after install the ejabberd 17.08, there are 2 folders.  One is "ejabberd" and the other one is "ejabberd-17.08".  The first one only consist of conf, logs, database while the later consist of the bin, conf, logs, database, etc."  Which is the right one to use in order to modify the "ejabberd.yml"?  Is quite confusing.

2.  Despite having the right method to generate my .pem file using openssl and also since my server is setup with Let's encrypt, I have ensure the certfile and all are in order.  The setup in "ejabberd.yml" for the certfile, ciphers, tlsopts, etc has been properly done but why I still got this error?  Please see below from the ejabberd.log files.

2017-09-24 01:36:26.963 [warning] <0.335.0>@ejabberd_pkix:handle_call:175 No certificate found matching 'conference.dev.example.com': strictly configured clients or servers will reject connections with this host
2017-09-24 01:36:26.975 [warning] <0.335.0>@ejabberd_pkix:handle_call:175 No certificate found matching 'vjud.dev.example.com': strictly configured clients or servers will reject connections with this host

2017-09-24 01:36:27.048 [warning] <0.335.0>@ejabberd_pkix:handle_call:175 No certificate found matching 'upload.dev.example.com': strictly configured clients or servers will reject connections with this host

Appreciate the feedback.   Thanks.

**Comment by badlop** [comment]
Regarding 1, see https://github.com/processone/ejabberd/issues/1971#issuecomment-327400900
Regarding 2, maybethose subdomains require their own certificates, or the existing certificates should cover those subdomains too. But I am not sure, sorry.

**Comment by molochmike** [comment]
Hi @badlop 

Thanks for the info on point 1.  

As for point 2, I have resolve it with using my own subdomain that was generated from Let's Encrypt.  At first I was using the TLS recommendation by ejabberd blogs on this topic https://blog.process-one.net/securing-ejabberd-with-tls-encryption/  I was referring to this ciphers but don't quite seem to work on 17.08.  In 17.04, it works fine.

That's all.  Thanks.
