### ISSUE TITLE
problem exporting from Mnesia into MySQL

### ISSUE THREAD

**Issue by digger14** [processone/ejabberd#2011]
> What version of ejabberd are you using?

16.09-4

> What operating system (version) are you using?

Debian STRETCH 9.1

> How did you install ejabberd (source, package, distribution)?

package (and optional apt install erlang-p1-mysql for mysql support)

> What did not work as expected? 

I wanted to migrate from Mnesia to MySQL. 
First I dumped Mnesia-DB into .dump file with "ejabberdctl export2sql /data/db.dump)
I then installed (using apt-get) MySQL and made sure it was running fine (loosely based on this page: https://docs.ejabberd.im/admin/databases/mysql/)
Then I wanted to import my .dump file into the new MySQL-DB, using mysql -D ejabberd -u ejabberd -p < /data/dump.dump

>Are there error messages in the log? 

I got "error 1064 (42000) at line 647. ... Please refer to the manual for the right syntax to use near 'delete from privacy_default_list where username='something' at line 2" 

>What was the unexpected behavior? What was the expected result?

The (Mnesia-)DB simply would not import into my new MySQL
I inspected closely (and got some help from the nice people over at #ejabberd on IRC :) and after a while noticed that some lines in the .dump file were missing a ; at the end. 
Simply adding all these ; eventually made the error disappear and DB got imported nicely at the end. In total I had to add about 50 ; , in privacy_default_list, but also private_storage and privacy chapters.

**Comment by badlop** [comment]
> error 1064 (42000) at line 647. ... Please refer to the manual for the right syntax to use near 'delete from privacy_default_list where username='something' at line 2"

Yes, there was a problem in some SQL lines generated by mod_privacy, it was fixed long time ago:
https://github.com/processone/ejabberd/commit/149cc9654f17c8edfbcd79a2d1973721a70eafe3

**Comment by digger14** [comment]
I encountered this about a week ago. Not sure why it only happened with a few lines though (according to the code, every line should have ; )

Anyway: probably no big deal then.
