### ISSUE TITLE
Service discovery request fails if comes almost in the same time when MUC room is being destroyed

### ISSUE THREAD

**Issue by ikhvostenkov** [processone/ejabberd#2012]
> What version of ejabberd are you using?
ejabberd-base:17.04

> What operating system (version) are you using?
Linux 3dc850718196 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The problem is reproducible only with low network latency, e.g. running ejabberd locally and making requests to the server as well from the local host. 
## Steps to reproduce:
1. Create any MUC room.
2. Leave the created MUC room in step 1.
3. Immediately after step 2, request list of all rooms using service discovery. 

## Actual Results:
Service discovery request failed.

## Expected Results:
Service discovery request successful.

## Logs:

```
ejabberd       | 2017-09-25 08:39:58.367 [info] <0.1473.0>@mod_muc_room:handle_event:492 Destroyed MUC room 40267d5a-7078-4f2b-9fab-91e0db9f2cf4@conference.chat.local.com with reason: undefined
ejabberd       | 2017-09-25 08:39:58.367 [info] <0.1473.0>@mod_muc_room:terminate:671 Stopping MUC room 40267d5a-7078-4f2b-9fab-91e0db9f2cf4@conference.chat.local.com
ejabberd       | 2017-09-25 08:39:58.368 [error] <0.869.0>@gen_iq_handler:process_iq:149 failed to process iq:
ejabberd       | #iq{id = <<"b0bc5f08-43b9-4331-bd09-a5f6fb4bd2b1">>,type = get,
ejabberd       |     lang = <<"en-US">>,
ejabberd       |     from = {jid,<<"4655854884766286857">>,<<"chat.local.com">>,
ejabberd       |                 <<"513013722840299244910922">>,<<"4655854884766286857">>,
ejabberd       |                 <<"chat.local.com">>,<<"513013722840299244910922">>},
ejabberd       |     to = {jid,<<>>,<<"conference.chat.local.com">>,<<>>,<<>>,
ejabberd       |               <<"conference.chat.local.com">>,<<>>},
ejabberd       |     sub_els = [{xmlel,<<"query">>,
ejabberd       |                       [{<<"xmlns">>,
ejabberd       |                         <<"http://jabber.org/protocol/disco#items">>}],
ejabberd       |                       []}],
ejabberd       |     meta = #{ip => {172,17,0,1}}}
ejabberd       | Reason = {exit,{{shutdown,{gen_fsm,sync_send_all_state_event,[<0.1473.0>,{get_disco_item,all,{jid,<<"4655854884766286857">>,<<"chat.local.com">>,<<"513013722840299244910922">>,<<"4655854884766286857">>,<<"chat.local.com">>,<<"513013722840299244910922">>},<<"en-US">>},100]}},[{gen_fsm,sync_send_all_state_event,3,[{file,"gen_fsm.erl"},{line,257}]},{mod_muc,get_room_disco_item,2,[{file,"src/mod_muc.erl"},{line,749}]},{mod_muc,'-iq_disco_items/7-fun-0-',2,[{file,"src/mod_muc.erl"},{line,723}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},{mod_muc,iq_disco_items,7,[{file,"src/mod_muc.erl"},{line,721}]},{mod_muc,process_disco_items,1,[{file,"src/mod_muc.erl"},{line,606}]},{gen_iq_handler,process_iq,3,[{file,"src/gen_iq_handler.erl"},{line,163}]}]}}
ejabberd       | 2017-09-25 08:39:58.389 [info] <0.1471.0>@ejabberd_c2s:process_terminated:264 (websocket|<0.1470.0>) Closing c2s session for 2086583182258190602@chat.local.com/1445775024730236809711034: Stream reset by peer
ejabberd       | 2017-09-25 08:39:58.389 [info] <0.1461.0>@ejabberd_c2s:process_terminated:264 (websocket|<0.1460.0>) Closing c2s session for 4655854884766286857@chat.local.com/513013722840299244910922: Stream reset by peer
```

**Comment by kamrul10** [comment]
I am getting the following problem when I want to handle iq of a custom module --->
`2018-10-31 13:15:14.606 [error] <0.864.0>@gen_iq_handler:process_iq:79 failed to process iq:
#iq{id = <<"1540970114106">>,type = get,lang = <<"en">>,
    from = #jid{user = <<"+8801000600060">>,server = <<"192.168.1.104">>,
                resource = <<"116665077396712294675381">>,
                luser = <<"+8801000600060">>,lserver = <<"192.168.1.104">>,
                lresource = <<"116665077396712294675381">>},
    to = #jid{user = <<"+8801200020001">>,server = <<"192.168.1.104">>,
              resource = <<>>,luser = <<"+8801200020001">>,
              lserver = <<"192.168.1.104">>,lresource = <<>>},
    sub_els = [#xmlel{name = <<"query">>,
                      attrs = [{<<"xmlns">>,<<"urn:xmpp:mark_as_read">>},
                               {<<"jid">>,
                                <<"+8801000600060@192.168.1.104/116665077396712294675381">>}],
                      children = []}],
    meta = #{ip => {0,0,0,0,0,65535,49320,315}}}`
