### ISSUE TITLE
Compilation failure OTP 19

### ISSUE THREAD

**Issue by aShobhitSingh** [processone/ejabberd#2017]
> What version of ejabberd are you using?
Using git clone latest version

> What operating system (version) are you using?
Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
Using git clone

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Compiling /home/twine_user/ejabberd/deps/fast_yaml/c_src/fast_yaml.c
/home/twine_user/ejabberd/deps/fast_yaml/c_src/fast_yaml.c:18:18: fatal error: yaml.h: No such file or directory
 #include <yaml.h>
                  ^
compilation terminated.
ERROR: compile failed while processing /home/twine_user/ejabberd/deps/fast_yaml:

**Comment by prefiks** [comment]
You are missing libyaml-dev package.
