### ISSUE TITLE
error in offline message hook

### ISSUE THREAD

**Issue by agnihotri7** [processone/ejabberd#2018]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

Hi,
i have installed ejabberd 17.08 (working fine). I want to enable offline messages notification on.
i am trying https://github.com/adamvduke/mod_interact for this but getting below error .
i guess mod_intract is working fine but after hook gets executed ejabberd is giving some error.

2017-09-27 12:21:02.894 [error] <0.431.0>@ejabberd_hooks:safe_apply:383 Hook offline_message_hook crashed when running mod_offline_post:send_notice/1:

** Reason = {error, undef, [{mod_offline_post,send_notice,[],[{bounce,{message,<<>>,chat,<<"en">>,{jid,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>},{jid,<<"user3">>,<<"domain.com">>,<<>>,<<"user3">>,<<"domain.com">>,<<>>},[],[],undefined,[{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {0,0,0,0,0,65535,3686,1098}}}}]},

{ejabberd_hooks,safe_apply,[{**file,"src/ejabberd_hooks.erl"},{line,380**}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_sm,route,[{file,"src/ejabberd_sm.erl"},{line,140}],1},{ejabberd_local,route,[{file,"src/ejabberd_local.erl"},{line,116}],1},{ejabberd_router,do_route[{file,"src/ejabberd_router.erl"},{line,348}],1},{ejabberd_router,route[{file,"src/ejabberd_router.erl"},{line,87}],1},{ejabberd_c2s,check_privacy_then_route,[{file,"src/ejabberd_c2s.erl"},{line,816}],2}]}

** Arguments = [{bounce,{message,<<>>,chat,<<"en">>,{jid,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>,<<"user1">>,<<"domain.com">>,<<"1171133519104699199494">>},{jid,<<"user3">>,<<"domain.com">>,<<>>,<<"user3">>,<<"domain.com">>,<<>>},[],[],undefined,[{xmlel,<<"composing">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/chatstates">>}],[]}],#{ip => {0,0,0,0,0,65535,3686,1098}}}}]

> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
Please stop posting this everywhere.
