### ISSUE TITLE
XEP-0387: XMPP Compliance Suites 2017

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2020]
Please add complete support of https://xmpp.org/extensions/xep-0387.html

**Comment by zinid** [comment]
What exactly? All listed XEPs are implemented, seems like.

**Comment by Neustradamus** [comment]
All XEPs are with last version?

**Comment by zinid** [comment]
No idea.

**Comment by zinid** [comment]
Anyway, if some XEP is not in the last version, a separate ticket should be created.

**Comment by Neustradamus** [comment]
https://www.process-one.net/en/ejabberd/protocols/ has only XEP-0302: XMPP Compliance Suites 2012 :/
