### ISSUE TITLE
Mod offline post for groups

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#2029]
> What version of ejabberd are you using?
17.07

Regarding issue #1720 I put this on hold and will pick now.
I Installed ejebbard 17.07

When I want to install my module (in development)
https://github.com/PH-F/mod_offline_http_post_group.git

I get 5 warning (those i understand) and 1 error that i don't understand. Note I was able to install it on 17.01 even though got an error at runtime.
`Error: {"ebin/mod_offline_http_post_group.beam",enoent}`

**Comment by zinid** [comment]
`enoent` means there is no such file.
