### ISSUE TITLE
SASL EXTERNAL is offered before validating certificates (XEP-0178)

### ISSUE THREAD

**Issue by fgrsnau** [processone/ejabberd#2030]
I observed that a s2s connection to an ejabberd server is failing (I don’t run ejabberd myself). The problem is that the ejabberd server offers EXTERNAL authentication unconditionally, but after negotiating this mechanism, I receive an error due to [unsuccessful certificate validation from the remote end](https://github.com/processone/ejabberd/blob/2732c8f6fcaa2876e5348373985f624a7772cc18/src/xmpp_stream_in.erl#L758). (Just assume that a self-signed certificate is used. The actual problem was a misconfiguration, but this is completely unrelated.)

Offering the EXTERNAL mechanism and failing afterwards is problematic due to the following reasons:

1. [XEP-0178](https://xmpp.org/extensions/xep-0178.html) says that you should close the connection after a failure. So as other servers will try EXTERNAL first and no other authentication schemes can follow afterwards, the connection always fails.
2. I think XEP-0178 is not completely clear, but according to [this conversation on a mailing](https://mail.jabber.org/pipermail/standards/2007-January/013594.html) the intent was to only offer EXTERNAL when the verification already was successful (first validate TLS cert, then offer EXTERNAL).

If certificate validation takes place before offering SASL EXTERNAL, connection could still succeed by using dns dialback or other means.

I don’t know if this is really a "bug" of ejabberd. Nevertheless, I think that with the proposed small modification ejabberd would still be compliant with [XEP-0178](https://xmpp.org/extensions/xep-0178.html) but the compatibility with other server software would be increased. I could be wrong though.

**Comment by zinid** [comment]
This is done intentionally for better diagnostics. We will not change that, instead the XEP should be changed.

**Comment by zinid** [comment]
BTW, I'm not sure why the server fails receiving SASL `<failure/>` and how this can be a problem, furthermore, the XEP pretty much allows to send `<failure/>` (Example 28).
