### ISSUE TITLE
Request to enable push notifications through mod_push returns "No module is handling this query"

### ISSUE THREAD

**Issue by saribe0** [processone/ejabberd#2033]
> What version of ejabberd are you using?

ejabberd 17.08.32

> What operating system (version) are you using?

Ubuntu 16.04.3 LTS

> How did you install ejabberd (source, package, distribution)?

 Ubuntu's package manager.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to use mod_push however when I try to enable push notifications via [Section 5 of XEP-0357](https://xmpp.org/extensions/xep-0357.html#enabling), I get "No module is handling this query."

I'm sending the iq message from an authenticated xmpp stream and the xml is:
`<iq type="set" to="my_server.com" id="x43"><enable xmlns="'urn:xmpp:push:0'" jid="push.my_server.com" node="yxs32uqsflafdk3iuqo"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="secret"><value>1d2c8e6c</value></field></x></enable></iq>`

My ejabberd.yml configuration file has mod_push and mod_pubsub enabled and is shown below:

![screen shot 2017-10-04 at 3 18 05 pm](https://user-images.githubusercontent.com/6515393/31195340-0363a5ee-a918-11e7-9cfa-0085e597ed3d.png)

Finally, my log files show the error message:

![screen shot 2017-10-04 at 3 15 17 pm](https://user-images.githubusercontent.com/6515393/31195374-1a2b2036-a918-11e7-9649-1146419b43b0.png)

Is there anything else I need to do to enable mod_push or is there an issue with how I'm requesting push notifications to be enabled? My end goal is have mod_push publish the notification defined in [Section 7 of XEP-03577](https://xmpp.org/extensions/xep-0357.html#publishing) so I can forward the notification to apns.

**Comment by weiss** [comment]
I don't think Ubuntu ships "ejabberd 17.08.32" as an official package, does it?  And does this include the `mod_push` module that was initially published with ejabberd 17.09?

> `xmlns="'urn:xmpp:push:0'"`

Remove the single quotes there.

**Comment by weiss** [comment]
Ah sorry, `mod_push` was published with 17.08.  Time flies :-)

**Comment by saribe0** [comment]
I'm not quite sure how I installed it- was back in August and I tried a variety of ways. It may have been that Ubuntu's package manager installed an old version and I installed the one I'm currently running from source... hopefully thats not an issue!

Also, looks like I forgot to remove those quote. I've been trying a bunch of things and wanted to see how the library I'm using on my client would interpret them. In all my other attempts they don't exist and the error persists. 

Do you think it might make sense to try a fresh install with 17.09?

**Comment by saribe0** [comment]
Spun up a new vm running Ubuntu 16.04.3 LTS, downloaded and installed the ejabberd 17.09 executable for ubuntu (.deb file installed with dpkg), and tested again. 

Sent the following iq packet and received the same "No module is handling this query" as shown in my original post. 
`<iq type="set" to="my_server.com" id="x43"><enable xmlns="urn:xmpp:push:0" jid="push.my_server.com" node="yxs32uqsflafdk3iuqo"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="secret"><value>a21c6f0f6aa7d42</value></field></x></enable></iq>`

The logs say that mod_push, mod_push_keepalive, and mod_pubsub are all being loaded when the server starts up. Is there something else that has to be configured??

**Comment by weiss** [comment]
> `to="my_server.com"`

Send the IQ to `you@my_server.com` instead.

**Comment by saribe0** [comment]
Thank you!! That worked to enable push notifications.

**Comment by sbuzoianu** [comment]
@saribe0  - you used one secret value "1d2c8e6c4...." that you should have received it from register stanza. But on register stanza you need to specify one node witch in case of royneary mod_push was  node='register-push-apns' . Can you provide me register stanza which you use in this case - ejabberd 17.08?

**Comment by weiss** [comment]
Note that `royneary/mod_push` is unmaintained and won't accept the notifications generated by ejabberd's `mod_push` (as it doesn't cope with a [recent change][1] to the XEP).

[1]: https://github.com/xsf/xeps/pull/483
