### ISSUE TITLE
17.09 packages won't run on CentOS 6

### ISSUE THREAD

**Issue by rom1dep** [processone/ejabberd#2034]
If I understand correctly,

- The latest packages now bundle OpenSSL 1.0.2l,
- An up to date CentOS 6 provides 1.0.1e, so ejabberd will attempt to run the version that it bundles (because more recent),
- This version requires glibc 2.14, so the loading fails (because CentOS 6 provides 2.12).

The proposed workaround for systems running old glibc is to delete these vendored OpenSSL libs so the system falls back to using its own, but then it fails again because ejabberd looks for OpenSSL 1.0.0 while the system has 1.0.1e to offer.

Would it make sense to gracefully fall back to looking for 1.0.0 only after 1.0.1 fails?

**Comment by cromain** [comment]
we can recompile OpenSSL 1.0.2l against older glibc also

**Comment by rom1dep** [comment]
If that's an option, that would be the most reasonable one indeed.

If you want me to test off-cycle packages targeting CentOS6, that'd be my pleasure.

**Comment by cromain** [comment]
I adapted packaging to support older glibc. this will be fixed in next release.
