### ISSUE TITLE
17.09 mod_client_state filter crash

### ISSUE THREAD

**Issue by haegar** [processone/ejabberd#2036]
> What version of ejabberd are you using?

17.09 git snapshot 6f92227

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Source/Git

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

"Hook c2s_filter_send crashed when running mod_client_state:filter_other/1" happens regulary (every 1-2 min for 5k users connected), but does not seem to hit a single user twice - once this happened to one user he gets disconnected, and the next reconnect seems to work.

2017-10-06 12:01:42.776 [info] <0.11224.11>@ejabberd_c2s:handle_auth_success:436 (tls|<0.11223.11>) Accepted c2s legacy authentication for ... by sql backend from ...

2017-10-06 12:01:42.779 [info] <0.11224.11>@ejabberd_c2s:bind:407 (tls|<0.11223.11>) Opened c2s session for ...

2017-10-06 12:01:42.781 [error] <0.11224.11>@ejabberd_hooks:safe_apply:383 Hook c2s_filter_send crashed when running mod_client_state:filter_other/1:
** Reason = {error,function_clause,[{mod_client_state,dequeue_sender,[{file,"src/mod_client_state.erl"},{line,308}],[undefined,#{user => <<"...">>,stream_direction => in,tls_enabled => false,mgmt_stanzas_in => 0,pres_a => {0,nil},resource => <<"...">>,zlib => true,conn => c2s_tls,access => c2s,ip => {{212,9,176,58},48775},xmlns => <<"jabber:client">>,mgmt_ack_timeout => 60000,stream_state => established,mgmt_resend => if_offline,csi_queue => {0,#{}},stream_header_sent => true,tls_options => [compression_none,{certfile,<<"/etc/ejabberd/....pem">>},{protocol_options,<<"no_sslv2|no_sslv3|cipher_server_preference">>},{dhfile,<<"/etc/ejabberd/dh.pem">>},{ciphers,<<"ECDHE+CHACHA20:ECDHE+AESGCM:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:!RC4:HIGH:!MD5:!RC4-SHA:!aNULL:!eNULL:!EDH">>}],socket_monitor => #Ref<0.0.2097153.55460>,server => <<"...">>,stream_restarted => false,mgmt_stanzas_req => 0,mod => ejabberd_c2s,tls_required => false,mgmt_max_timeout => 600,stream_compressed => false,lserver => <<"...">>,tls_verify => false,stream_version => undefined,jid => {jid,<<"...">>,<<"...">>,<<"...">>,<<"...">>,<<"...">>,<<"...">>},mgmt_state => inactive,stream_authenticated => true,auth_module => ejabberd_auth_sql,socket => {socket_state,fast_tls,{tlssock,#Port<0.381080>,<<>>},<0.11223.11>},sockmod => ejabberd_socket,stream_timeout => infinity,lang => <<"en">>,mgmt_queue_type => ram,mgmt_timeout => 600,sid => {{1507,284102,888447},<0.11224.11>},owner => <0.11224.11>,stream_encrypted => true,mgmt_stanzas_out => 0,csi_state => active,mgmt_max_queue => 1000,stream_id => <<"10172300948561412097">>,shaper => c2s_shaper}]},{mod_client_state,filter_other,[{file,"src/mod_client_state.erl"},{line,269}],1},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[...],...},...]}
** Arguments = [{{iq,<<"auth-set">>,result,<<"en">>,undefined,undefined,[],#{}},#{user => <<"...">>,stream_direction => in,tls_enabled => false,mgmt_stanzas_in => 0,pres_a => {0,nil},resource => <<"...">>,zlib => true,conn => c2s_tls,access => c2s,ip => {{...},48775},xmlns => <<"jabber:client">>,mgmt_ack_timeout => 60000,stream_state => established,mgmt_resend => if_offline,csi_queue => {0,#{}},stream_header_sent => true,tls_options => [compression_none,{certfile,<<"/etc/ejabberd/....pem">>},{protocol_options,<<"no_sslv2|no_sslv3|cipher_server_preference">>},{dhfile,<<"/etc/ejabberd/dh.pem">>},{ciphers,<<"ECDHE+CHACHA20:ECDHE+AESGCM:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:!RC4:HIGH:!MD5:!RC4-SHA:!aNULL:!eNULL:!EDH">>}],socket_monitor => #Ref<0.0.2097153.55460>,server => <<"...">>,stream_restarted => false,mgmt_stanzas_req => 0,mod => ejabberd_c2s,tls_required => false,mgmt_max_timeout => 600,stream_compressed => false,lserver => <<"...">>,tls_verify => false,stream_version => undefined,jid => {jid,<<"...">>,<<"...">>,<<"...">>,<<"...">>,<<"...">>,<<"...">>},mgmt_state => inactive,stream_authenticated => true,auth_module => ejabberd_auth_sql,socket => {socket_state,fast_tls,{tlssock,#Port<0.381080>,<<>>},<0.11223.11>},sockmod => ejabberd_socket,stream_timeout => infinity,lang => <<"en">>,mgmt_queue_type => ram,mgmt_timeout => 600,sid => {{1507,284102,888447},<0.11224.11>},owner => <0.11224.11>,stream_encrypted => true,mgmt_stanzas_out => 0,csi_state => active,mgmt_max_queue => 1000,stream_id => <<"10172300948561412097">>,shaper => c2s_shaper}}]

2017-10-06 12:01:42.973 [info] <0.11224.11>@ejabberd_c2s:process_terminated:272 (tls|<0.11223.11>) Closing c2s session for ...: Stream reset by peer

(Private data replaced by "..." in the log cut&paste)

**Comment by zinid** [comment]
What Erlang version?

**Comment by haegar** [comment]
Debian Jessie backports package 1:19.2.1+dfsg-2~bpo8+1

**Comment by zinid** [comment]
Ah, ok, I got the problem.

**Comment by zinid** [comment]
For the record, this is not fatal, everything will work just fine. The bug is produced by `mod_legacy_auth` + `mod_client_state` combo.
