### ISSUE TITLE
Missing documentation for mod_push

### ISSUE THREAD

**Issue by skipper570** [processone/ejabberd#2037]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

macOS 10.12

> How did you install ejabberd (source, package, distribution)?

Installer for macOS

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I want to use the new module mod_push to send push notifications using APNS but I cannot find a documentation about the module. I know it is implemented acording to XEP-0357 but I do not know what kind of push service I need tonuse.

I found out that the Oshiya app server can be used but I am not sure how to set it up. Are there any similar push services? Or what do I need to create an own push service (e.g. in python)? Does the mod_push module just send an xml object to the push service so that I just need to create a server that receives the xml object and then sends the push notification (for a certain user) to the APNS?

I really do not know where to get help so I am asking here, I hope it is not the wrong places.

**Comment by weiss** [comment]
> I found out that the Oshiya app server can be used but I am not sure how to set it up.

I think it's non-functional and unmaintained anyway.

> Does the mod_push module just send an xml object to the push service so that I just need to create a server that receives the xml object and then sends the push notification (for a certain user) to the APNS?

Yes.  The "XML object" is [described][1] in XEP-0357.

[1]: https://xmpp.org/extensions/xep-0357.html#publishing
