### ISSUE TITLE
Blocked ports

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#2038]
> What version of ejabberd are you using?
17.08

We connect to ejabberd via wss (web) and TCP for native android,iOS
For web we use 5282 and for the native-apps we use 5222

Lots of out clients have a firewall where everything is restricted except 80, 443 and some other default ports.

Ejabberd is running on a separate server, so i guess could use 443 for e.g.  WSS.
Is there a way to use port 443 for both TCP and WSS (web)

**Comment by weiss** [comment]
The obvious solution would be separate IP addresses, but if you don't have them you might want to look into [sslh][1].

[1]: http://www.rutschle.net/sslh
