### ISSUE TITLE
Ugly register page on a mobile device

### ISSUE THREAD

**Issue by mako09** [processone/ejabberd#2039]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian 9.2

> How did you install ejabberd (source, package, distribution)?

Debian package
ejabberd                      16.09-4

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Register page looks ugly on a mobile device.

The line
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
should be added.

**Comment by f055** [comment]
Hi @mako09, thanks for the report. Can you provide a screenshot to better understand the problem?

**Comment by mako09** [comment]
I am sorry but my server provides the page in Japanese language.

On a mobile device, the size of the font is uneven among the items in the list.
Input area is very small and inconvenient.

![screenshot_2017-10-09-19-53-00](https://user-images.githubusercontent.com/1195749/31335195-716206ae-ad2c-11e7-8123-69589ea70d3a.png)

**Comment by f055** [comment]
Thanks, this helps!
