### ISSUE TITLE
Migrating from old version with old database

### ISSUE THREAD

**Issue by bopandrade** [processone/ejabberd#2042]
Im running the docker image for 17.08 on a modified ubuntu xenial using ODBC mysql

I have two problems
1. when starting up it sometimes fails on the 
>    Updating module specs... 

step with error
>    20:44:47.876 [info] Update packages from repo https://github.com/processone/ejabberd-contrib: {error,bad_eocd}

i dont know the reason why it fails but sometimes it works. a temporary solution was to use a loop script to restart the server. running docker with the --restart always option did not seem to work.
EDIT: i removed the scripts "11_ejabberd_install_modules.sh" and "10_ejabberd_modules_update_specs.sh" and now the problem is solved. i dont know if i should keep the issue open as it closes ejabberd on failure

2. my database consisted only of user pass and "created at". this causes the sql query to fail after migration and can be fixed my ALTERing the table to add the correspondent fields and default values (NULL as default also causes it to fail). maybe this step could be performed automatically whenever necessary

**Comment by badlop** [comment]
> Update packages from repo https://github.com/processone/ejabberd-contrib: {error,bad_eocd}

Apparently the problem is that it can't get a proper ZIP file from github and uncompress the repository.

> my database consisted only of user pass and "created at".

Your database, or your 'users' table? In the mysql.sql it says how to add the other fields:
```sql
CREATE TABLE users (
    username varchar(191) PRIMARY KEY,
    password text NOT NULL,
    serverkey varchar(64) NOT NULL DEFAULT '',
    salt varchar(64) NOT NULL DEFAULT '',
    iterationcount integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Add support for SCRAM auth to a database created before ejabberd 16.03:
-- ALTER TABLE users ADD COLUMN serverkey varchar(64) NOT NULL DEFAULT '';
-- ALTER TABLE users ADD COLUMN salt varchar(64) NOT NULL DEFAULT '';
-- ALTER TABLE users ADD COLUMN iterationcount integer NOT NULL DEFAULT 0;
```

**Comment by bopandrade** [comment]
indeed i meant the users table. i eventually found the problem and updated the table structure as described. 

in addition, i believe the table "archive" did not contain the fields "kind varchar(10)" and "nick varchar(191)".
