### ISSUE TITLE
Resource-Constraint error when publishing a notification to a pubsub node with a 'secret' field in pubsub#publish-options

### ISSUE THREAD

**Issue by saribe0** [processone/ejabberd#2043]
> What version of ejabberd are you using?

ejabberd 17.09

> What operating system (version) are you using?

Ubuntu 16.04.3 LTS

> How did you install ejabberd (source, package, distribution)?

Package; Downloaded .deb file and installed using dpkg

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am working on implementing mod_push (XEP-0357) however am having trouble getting the pubsub node to accept what mod_push publishes. According to the documentation, I should be able to use a DATA_FORM with a 'secret' field for my device token to be passed. This works fine with mod_push but when the iq packet is published to the node, I get a resource-constraint, unknown field 'secret' of type 'http://jabber.org/protocol/pubsub#publish-options' error.

It looks like this in my logs:
![screen shot 2017-10-09 at 9 58 29 pm](https://user-images.githubusercontent.com/6515393/31366120-7227004c-ad3d-11e7-8b31-54c279a5e9c1.png)

I'd originally thought it was my xmpp library failing to recognize the field, however I've tried the same thing with two different libraries in c++ and python. I have also tested when neither library code was running with the same result so I'm fairly certain it has to do with mod_pubsub. 

Am I missing something that is needed to get this field to work? [XEP-0357 Section 5](https://xmpp.org/extensions/xep-0357.html#enabling) makes it sound like it is optional for the server to implement these fields, however I would assume that most third party push services require some form of token or key which needs to be passed this way. 

The other issue with not receiving this token is that I am also not receiving notification summary and info. I have another issue opened [here](https://github.com/processone/ejabberd/issues/2041) that looks at this situation specifically. If my client does not include the secret field when enabling notifications, the notifications are sent out to subscribers of the node, however without the token and without the notification data, there is no way to actually notify individual users, only to know that a message to an offline user has occurred.

Is there some way to configure mod_pubsub to accept this field in the DATA_FORM? Any advice would be extremely helpful.

**Comment by zinid** [comment]
The field 'secret' is not defined within `pubsub#publish-options` data form, see [XEP-0060 Section 16.4.5](https://xmpp.org/extensions/xep-0060.html#registrar-formtypes-publish). And ejabberd generates code for parser/validator from this form, see [here](https://github.com/processone/xmpp/blob/master/specs/pubsub_publish_options.xdata).
This is a problem of the XSF registering process.

**Comment by zinid** [comment]
Anyway, I fixed it in https://github.com/processone/xmpp/commit/3e212f21efe41c0ec41f86b2c8a9e26165c8628d
