### ISSUE TITLE
Can not receive ack with stream management on 17.09

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#2044]
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

On the latest version with stream management enabled, I can not receive an ack from the server when the other user is offline. If the other user is online then I receive it immediately. 

This did not happen on 17.08

**Comment by weiss** [comment]
Are you sure you're talking about [stream management `<a/>`CKs][1]?  They're completely unrelated to the recipient of the stanza.

If you're sure, could you please show a dump of the relevant XML stream?

[1]: https://xmpp.org/extensions/xep-0198.html#acking

**Comment by jjdp** [comment]
it's because of my module crashing with offline_hook, I don't know why yet it crashes on 17.09 though

**Comment by weiss** [comment]
I'll close this issue then.  If you think you're running into an ejabberd bug, please open a new one.
