### ISSUE TITLE
17.09 mod_push is not supported by the server 

### ISSUE THREAD

**Issue by Ghostw4lk** [processone/ejabberd#2045]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04.3 LTS

> How did you install ejabberd (source, package, distribution)?

Package: .deb file - Installed using dpkg

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The mod_push & mod_push_keepalive are enabled in the ejabberd.yml file (by default).
If I want to check if the push notification service is enabled, I get back "false" (using Smack API).
I used this doc: https://github.com/igniterealtime/Smack/blob/master/documentation/extensions/pushnotifications.md

The expected result should be "true". I did not find any errors in the log files.

If I want to enable the push service, I got no exception on the client side.

Did I miss something to make it work? Because the ejabberd server does not need additional configuration commands to make it work.

**Comment by weiss** [comment]
What exactly did you call?  `pushNotificationsManager.isSupportedByServer();`?

**Comment by weiss** [comment]
Could you get a dump of the traffic?

**Comment by Ghostw4lk** [comment]
Yes, I call the method you posted above to check if the server supports the push notification service.

Here is the complety traffic dump:
`10-11 12:13:52.349 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <iq xml:lang='en' to='HdzY4Zzdp3@localhost/test' from='HdzY4Zzdp3@localhost' type='result' id='8c4J7-36'/>
10-11 12:13:52.359 2990-3663/io.codeseven.eventmessenger D/SMACK: SENT (0): <presence id='8c4J7-38'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.igniterealtime.org/projects/smack' ver='os2Kusj3WEOivn5n4iFr/ZEO8ls='/></presence><r xmlns='urn:xmpp:sm:3'/><iq id='8c4J7-39' type='set'><enable xmlns='urn:xmpp:push:0' jid='hallo@localhost' node='pushnode1234'></enable></iq><r xmlns='urn:xmpp:sm:3'/>
10-11 12:13:52.509 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <r xmlns='urn:xmpp:sm:3'/>
10-11 12:13:52.509 2990-3663/io.codeseven.eventmessenger D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='16'/>
10-11 12:13:52.509 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <a h='17' xmlns='urn:xmpp:sm:3'/>
10-11 12:13:52.519 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <a h='18' xmlns='urn:xmpp:sm:3'/>
10-11 12:13:52.519 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <presence xml:lang='en' to='HdzY4Zzdp3@localhost/test' from='HdzY4Zzdp3@localhost/test' id='8c4J7-38'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.igniterealtime.org/projects/smack' ver='os2Kusj3WEOivn5n4iFr/ZEO8ls='/><x xmlns='vcard-temp:x:update'><photo/></x></presence><iq xml:lang='en' to='HdzY4Zzdp3@localhost/test' from='HdzY4Zzdp3@localhost' type='result' id='8c4J7-39'/>
10-11 12:13:52.889 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <r xmlns='urn:xmpp:sm:3'/>
10-11 12:13:52.899 2990-3663/io.codeseven.eventmessenger D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='18'/>
10-11 12:14:01.429 2990-3663/io.codeseven.eventmessenger D/SMACK: SENT (0): <presence id='8c4J7-43' type='unavailable'></presence><r xmlns='urn:xmpp:sm:3'/><a xmlns='urn:xmpp:sm:3' h='18'/>
10-11 12:14:01.429 2990-3663/io.codeseven.eventmessenger D/SMACK: SENT (0): </stream:stream>
10-11 12:14:01.469 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): <a h='19' xmlns='urn:xmpp:sm:3'/>
10-11 12:14:01.489 2990-3667/io.codeseven.eventmessenger D/SMACK: RECV (0): </stream:stream>`

This shows a snippet of the traffic from that point I call the pushNotificationsManager.enable(pushclient@localhost, pushnodefcm);

**Comment by weiss** [comment]
> This shows a snippet of the traffic from that point I call the pushNotificationsManager.enable(pushclient@localhost, pushnodefcm);

Well but you asked about the `isSupportedByServer()` call.  This call should check the account owner's service discovery output for the `urn:xmpp:push:0` feature.  You could just perform [the request][1] manually (e.g., using the XML console of a client such as Gajim) to double check that ejabberd returns the expected feature and if so, ask the Smack people.

[1]: https://xmpp.org/extensions/xep-0357.html#disco

**Comment by Ghostw4lk** [comment]
I´ve an output from Gajim.


<iq from='admin1@osboxes/Gajim'
    to='admin1@osboxes'
    id='x13'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>


<iq xml:lang='de' to='admin1@osboxes/Gajim' from='admin1@osboxes' type='result' id='x13'>
<query xmlns='http://jabber.org/protocol/disco#info'>
<identity type='pep' category='pubsub'/>
<identity type='registered' category='account'/>
<feature var='http://jabber.org/protocol/disco#info'/>
<feature var='vcard-temp'/>
<feature var='urn:xmpp:push:0'/>
<feature var='msgoffline'/>
<feature var='http://jabber.org/protocol/offline'/>
<feature var='http://jabber.org/protocol/pubsub'/>
<feature var='http://jabber.org/protocol/pubsub#create-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#auto-create'/>
<feature var='http://jabber.org/protocol/pubsub#auto-subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#delete-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#delete-items'/>
<feature var='http://jabber.org/protocol/pubsub#filtered-notifications'/>
<feature var='http://jabber.org/protocol/pubsub#modify-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#outcast-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#persistent-items'/>
<feature var='http://jabber.org/protocol/pubsub#publish'/>
<feature var='http://jabber.org/protocol/pubsub#purge-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#retract-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-subscriptions'/>
<feature var='http://jabber.org/protocol/pubsub#subscribe'/>
<feature var='http://jabber.org/protocol/commands'/>
</query>
</iq>


<r xmlns='urn:xmpp:sm:3'/>


<a xmlns="urn:xmpp:sm:3" h="23" />

Seems the error is on the Smack API side.

**Comment by weiss** [comment]
> Seems the error is related to the Smack API, because urn:xmpp:push:0 is in the feature list.

Indeed.  I'll close this issue.

Unrelated: The `jid` attribute of your `<enable/>` request looked wrong: `jid='pushclient@localhost'`.  This should be the server JID of the actual [push service][1] rather than the user's JID.

[1]: https://xmpp.org/extensions/xep-0357.html#sect-idm139619452566368
