### ISSUE TITLE
mod_push does not trigger if publish-options are included

### ISSUE THREAD

**Issue by Ghostw4lk** [processone/ejabberd#2048]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04.3 LTS

> How did you install ejabberd (source, package, distribution)?

Package: .deb file - Installed using dpkg

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I´ve enabled the push service in my client with publish options.
My XML looks like this:
`11:15:17 SENT (0): <iq id='SxA63-37' type='set'><enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode1234'><x xmlns='jabber:x:data' type='form'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>Some secret content</value></field></x></enable></iq>`

With these publish options enabled I don´t receive any push notifications through the pubsub node.
I don´t get any errors after the push service was enabled.

If I enable the client without publish options, it works perfectly.
Here is the XML:
`11:21:11 SENT (0): <iq id='LyLos-37' type='set'><enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode1234'></enable></iq> `

Expected outcome **with** publish options:
Example 13 - Server publishes a push notification with provided publish options
https://xmpp.org/extensions/xep-0357.html#publishing
Current outcome: Nothing

Outcome **without** publish options: (Works well)
`<message to='hallo@localhost/83125558819277199223378' from='pubsub.localhost' type='headline'><event xmlns='http://jabber.org/protocol/pubsub#event'><items node='pushnode1234'><item id='5E3C321D9B259'><notification xmlns='urn:xmpp:push:0'/></item></items></event></message><r xmlns='urn:xmpp:sm:3'/>`
`org.jivesoftware.smackx.pubsub.PayloadItem | Content [<item id='5E3C321D9B259'><notification xmlns='urn:xmpp:push:0'/></item>]`

Whats wrong that the push mod does not trigger if publish options are enabled, because the XML file, like in example 9 looks correct?

**Comment by weiss** [comment]
> field var='secret'

This publish option should be accepted if you use the [latest][1] processone/xmpp code (update `deps/xmpp` if you build ejabberd from source).  So if you don't include any other options, it should work.

But the real problem is that XEP-0357 says that arbitray custom publish options may be included while XEP-0060 tells the server to [reject unknown options][2].  So basically you can't use a standard PubSub service for implementing an app server.

[1]: https://github.com/processone/xmpp/commit/3e212f21efe41c0ec41f86b2c8a9e26165c8628d
[2]: https://xmpp.org/extensions/xep-0060.html#publisher-publish-options

**Comment by Ghostw4lk** [comment]
Now, I´ve built the ejabberd server from source, but the problem is still exisiting.

**Comment by weiss** [comment]
>  I´ve built the ejabberd server from source

Did you update `deps/xmpp`?  What's the output of `git --git-dir=deps/xmpp/.git rev-parse HEAD`?

**Comment by Ghostw4lk** [comment]
The command returns that there no git repository is existing. 
I´ ve cloned the ejabberd server from git and followed the install instructions. 
Thought that the xmpp library is automatically the latest version.

**Comment by weiss** [comment]
Use `rm -rf deps; ./configure --enable-latest-deps # ...`

**Comment by Ghostw4lk** [comment]
Okay, the deps are no updated. I´ve checked the file manually. 
After the server restart the problem is still existing.

**Comment by zinid** [comment]
What reply do you receive for your IQ request?

**Comment by Ghostw4lk** [comment]
If I enable the push service I get nothing back, what is related to the push request.

**Comment by zinid** [comment]
1) What do you call "push request"?
2) Are there errors in the log?

**Comment by Ghostw4lk** [comment]
1. With push request I mean to enable the push service for the client which looks so:
`11:15:17 SENT (0): <iq id='SxA63-37' type='set'><enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode1234'><x xmlns='jabber:x:data' type='form'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>Some secret content</value></field></x></enable></iq>`

After that request I get no response or error.

2. The error logs are empty.

**Comment by zinid** [comment]
Did you change the code of mod_pubsub? Is there mod_pubsub module handling "pubsub.localhost" after all?

**Comment by weiss** [comment]
> With push request I mean to enable the push service

The client should receive an IQ response after sending the `<enable/>` request.  If it doesn't, we could look into it.  But this would be completely unrelated to `mod_pubsub` and the `<publish-options/>` issue you mentioned above.

You are aware that this should not trigger any

**Comment by zinid** [comment]
That's what I get:
```xml
<iq id='SxA63-37' type='set'><enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode1234'><x xmlns='jabber:x:data' type='form'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>Some secret content</value></field></x></enable></iq>

<iq from="user1@localhost" type="error" xml:lang="en" to="user1@localhost/master" id="SxA63-37">
<enable xmlns="urn:xmpp:push:0" node="pushnode1234" jid="pubsub.localhost">
<x xmlns="jabber:x:data" type="form">
<field var="FORM_TYPE">
<value>http://jabber.org/protocol/pubsub#publish-options</value>
</field>
<field var="secret">
<value>Some secret content</value>
</field>
</x>
</enable>
<error type="cancel" code="503">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">No module is handling this query</text>
</error>
</iq>
```

**Comment by zinid** [comment]
I also think 'to' attribute should be set to push-service rather than self-hosted JID.

**Comment by zinid** [comment]
Ah, this is not a pubsub query :)

**Comment by zinid** [comment]
`mod_push` was not loaded, now I get simple iq-result:
```xml
<iq from="user1@localhost" type="result" xml:lang="en" 
    to="user1@localhost/master" id="SxA63-37"/>
```

**Comment by Ghostw4lk** [comment]
The ejabberd server with the updated xmpp deps is now working. If I enable the push service with the publish option and send a message the push mod triggers it. But the received push item is still empty. The "secret" field is missing.

@zinid I don´t get the response like you. 

Here is my traffic dump after enabling the push service.
`18:00:46 SENT (0): <iq id='4nzjI-37' type='set'><enable xmlns='urn:xmpp:push:0' jid='pubsub.localhost' node='pushnode1234'><x xmlns='jabber:x:data' type='form'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>firebase888899</value></field></x></enable></iq>
18:00:46 RECV (0): <a h='15' xmlns='urn:xmpp:sm:3'/>
18:00:46 RECV (0): <message xml:lang='en' to='user1@localhost/55656436748124944541890' from='user2@localhost/132249531708521665841826' type='chat' id='v8mgB-42'><request xmlns='urn:xmpp:receipts'/><delay from='localhost' stamp='2017-10-12T15:59:54.205754Z' xmlns='urn:xmpp:delay'>Offline storage</delay><body>connction36661122221</body></message><r xmlns='urn:xmpp:sm:3'/><presence xml:lang='en' to='user1@localhost/55656436748124944541890' from='user1@localhost/55656436748124944541890' id='4nzjI-34'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.igniterealtime.org/projects/smack' ver='os2Kusj3WEOivn5n4iFr/ZEO8ls='/><x xmlns='vcard-temp:x:update'/></presence>
18:00:46 SENT (0): <a xmlns='urn:xmpp:sm:3' h='15'/>
18:00:46 RECV (0): <presence xml:lang='en' to='user1@localhost/55656436748124944541890' from='user1@localhost/55656436748124944541890' id='4nzjI-35'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.igniterealtime.org/projects/smack' ver='os2Kusj3WEOivn5n4iFr/ZEO8ls='/><x xmlns='vcard-temp:x:update'/></presence><iq xml:lang='en' to='user1@localhost/55656436748124944541890' from='user1@localhost' type='result' id='4nzjI-37'/>
Delivery Receipt ID for this message is: 4nzjI-42
Pubsubnode is null
18:00:46 SENT (0): <message to='user2@localhost' id='4nzjI-42' type='chat'><body>connction36661122221</body><request xmlns='urn:xmpp:receipts'/></message><r xmlns='urn:xmpp:sm:3'/><presence id='4nzjI-43' type='unavailable'></presence><a xmlns='urn:xmpp:sm:3' h='18'/>
18:00:46 SENT (0): </stream:stream>
18:00:46 RECV (0): <r xmlns='urn:xmpp:sm:3'/>
18:00:46 RECV (0): <a h='18' xmlns='urn:xmpp:sm:3'/>
18:00:46 RECV (0): </stream:stream>
Connection closed
18:00:46 XMPPConnection closed (XMPPTCPConnection[user1@localhost/55656436748124944541890] (0)) `

**Comment by saribe0** [comment]
I think I'm experiencing the same issue; mod_pubsub seems to get get the secret option and parse it fine. Instead of the resource constraint error like before, it sends out the published message but it does so without the secret field. The debug logs showing this look like:

```
2017-10-12 19:15:49.029 [debug] <0.1082.0>@ejabberd_sm:do_route:667 processing IQ to bare JID:
#iq{id = <<"3410215823721087545">>,type = set,lang = <<>>,
    from =
        {jid,<<>>,<<"my.server.com">>,<<>>,<<>>,
            <<"my.server.com">>,<<>>},
    to =
        {jid,<<"push">>,<<"my.server.com">>,
            <<>>,<<"push">>,<<"my.server.com">>,
            <<>>},
    sub_els =
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,
                 <<"push@my.server.com">>,
                 [{ps_item,<<>>,<<>>,
                      [{xmlel,<<"notification">>,
                           [{<<"xmlns">>,<<"urn:xmpp:push:0">>}],
                           []}],
                      <<>>,<<>>}]},
             {xdata,submit,[],undefined,undefined,[],
                 [{xdata_field,<<>>,hidden,<<"FORM_TYPE">>,false,<<>>,
                      [<<"http://jabber.org/protocol/pubsub#publish-options">>],
                      [],[]},
                  {xdata_field,<<>>,'text-single',<<"secret">>,false,<<>>,
                      [<<"my_secret_token">>],
                      [],[]}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined}],
    meta = #{}}
2017-10-12 19:15:49.029 [debug] <0.1082.0>@mod_pubsub:tree_call:3490 tree_call apply(nodetree_tree, get_node, [{<<"push">>,<<"my.server.com">>,<<>>},<<"push@my.server.com">>]) @ my.server.com
2017-10-12 19:15:49.029 [debug] <0.1082.0>@mod_pubsub:node_call:3522 node_call <<"pep">> publish_item [3,{jid,<<>>,<<"my.server.com">>,<<>>,<<>>,<<"my.server.com">>,<<>>},open,1,<<"5E3CC0A5730D">>,[{xmlel,<<"notification">>,[{<<"xmlns">>,<<"urn:xmpp:push:0">>}],[]}],[{secret,<<"my_secret_token">>}]]
2017-10-12 19:15:49.044 [debug] <0.1082.0>@mod_pubsub:tree_call:3490 tree_call apply(nodetree_tree, get_parentnodes_tree, [{<<"push">>,<<"my.server.com">>,<<>>},<<"my.server.com">>,{jid,<<"push">>,<<"my.server.com">>,<<>>,<<"push">>,<<"my.server.com">>,<<>>}]) @ my.server.com
2017-10-12 19:15:49.044 [debug] <0.1082.0>@mod_pubsub:node_call:3522 node_call <<"pep">> get_node_subscriptions [3]
2017-10-12 19:15:49.044 [debug] <0.1082.0>@ejabberd_router:do_route:337 route:
#message{
    id = <<>>,type = headline,lang = <<>>,
    from =
        {jid,<<"push">>,<<"my.server.com">>,
            <<>>,<<"push">>,<<"my.server.com">>,
            <<>>},
    to =
        {jid,<<"push">>,<<"my.server.com">>,
            <<"142439354843634512942530">>,<<"push">>,
            <<"my.server.com">>,
            <<"142439354843634512942530">>},
    subject = [],body = [],thread = undefined,
    sub_els =
        [{ps_event,
             {ps_items,<<>>,
                 <<"push@my.server.com">>,
                 [{ps_item,<<>>,<<"5E3CC0A5730D">>,
                      [{xmlel,<<"notification">>,
                           [{<<"xmlns">>,<<"urn:xmpp:push:0">>}],
                           []}],
                      <<>>,<<>>}],
                 undefined,<<>>,undefined},
             undefined,undefined,undefined,undefined,undefined}],
    meta = #{}}
2017-10-12 19:15:49.045 [debug] <0.1082.0>@ejabberd_local:do_route:256 local route:
```

Thinking that maybe this should be a mod_pubsub specific issue to handle the secret field? Might be related to what @weiss explained earlier in this thread?:

> But the real problem is that XEP-0357 says that arbitray custom publish options may be included while XEP-0060 tells the server to reject unknown options. So basically you can't use a standard PubSub service for implementing an app server.

**Comment by weiss** [comment]
Yes `<publish-options/>` are meant to be handled by the PubSub service itself.  They're aren't included with the items sent out to the node subscribers.  You can't build an app server on top of `mod_pubsub` without modifying it.

**Comment by saribe0** [comment]
Alright, so in that case, what is the point of mod_push and XEP-0357?  Especially in the case of ejabberd, the node pushes out the notification but the node subscribers don't get any information about the notification (no message body, no message sender, no message count, no user specific secret value) so they can't do anything with that notification. This seems to defeat the purpose of XEP-0357.

Is there some way to intercept the intermediate pubsub iq message (the iq message in the log output from my above comment) that mod_pubsub uses or do we have to modify mod_pubsub itself in some way?

**Comment by weiss** [comment]
I can't tell you why PubSub syntax was chosen for the notifications.

If I had to write an app server, I'd probably implement it as a [server component][1].  But the details of building an app server are really outside the scope of ejabberd, sorry.

[1]: https://xmpp.org/extensions/xep-0114.html

**Comment by zinid** [comment]
@saribe0 we actually raised a discussion in the [XSF chatroom](http://logs.xmpp.org/xsf/2017-10-12/#10:08:28) but it seems like with no agreement.

**Comment by saribe0** [comment]
Hmmm well, thank you both for all your help... any good erlang and ejabberd programming references that you'd recommend? 

I've tried both prosody and openfire as well and neither seem to have anything either. Looks like its going to be a long road to getting these notifications to work :(

**Comment by weiss** [comment]
> any good erlang and ejabberd programming references that you'd recommend?

I was suggesting a server component because you're then free to choose whatever programming language (and XMPP library) you like.  But yes, an ejabberd module would be another option of course.  Most docs and books mentioned on <http://www.erlang.org/docs/> are quite good actually, and for ejabberd there's <https://docs.ejabberd.im/developer/>.

> Looks like its going to be a long road to getting these notifications to work :(

Sorry about that.  The inclusion of `mod_push` into the Community Edition was mostly aimed at supporting third-party apps with existing push services (such as [Conversations][1]).  For custom chat solutions (where you control both the server and clients) you wouldn't really need XEP-0357 at all, but could just implement APNS/GCM support directly (as in the ejabberd Business Edition).

[1]: https://conversations.im/

**Comment by Ghostw4lk** [comment]
I did some research in the mod_push.erl file and saw, how the push notification gets created (Line 431 - 437). Above we get the "XData" object which will saved in the "publish_options" (Line 430). 

So I have an idea and want to know if it is a workaround to get the "XData" on the app server.

Is it possible to put the XData object into the IQ object? If that wont work, another idea is to put the XData into the item which gets published (Line 429). 

I know these ideas does not follow the XEP-0357 protocol, but people who wants to make an own app server and need the additional fields like "secret" it could be a workaround. 

Thank you all for the help to these questions.
