### ISSUE TITLE
Ejabberd crashes trying to access web admin

### ISSUE THREAD

**Issue by spippari** [processone/ejabberd#2050]
Hi
All
I am trying to access ejabberd web admin by visiting http://mydomain:5280/admin and i get a blank page. After checking the log file, i found that ejabberd crashes. The crash is immediate after visiting the web admin URL.

The error log->
```
2017-10-12 20:47:01.910 [error] <0.37.0> CRASH REPORT Process <0.37.0>
 with 0 neighbours exited with reason: {undefined_macro,''}
 in application_master:init/4 line 133
```
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/1381044/ejabberd.yml.txt)

The ejobberd log-->
```
2017-10-12 20:47:01.910 [error] <0.37.0> CRASH REPORT Process <0.37.0>
 with 0 neighbours exited with reason: {undefined_macro,''}
 in application_master:init/4 line 133
2017-10-12 20:47:01.910 [info] <0.7.0> Application ejabberd exited with reason:
 {undefined_macro,''}
```

The crash log-->
```
2017-10-12 20:40:16 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.37.0>
    registered_name: []
    exception exit: {{bad_return,{{ejabberd_app,start,[normal,[]]},
{'EXIT',{undefined_macro,''}}}},
[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [<0.36.0>]
    messages: []
    links: [<0.36.0>,<0.38.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 147
  neighbours:
2017-10-12 20:47:01 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.37.0>
    registered_name: []
    exception exit: {{bad_return,{{ejabberd_app,start,[normal,[]]},
{'EXIT',{undefined_macro,''}}}},
[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [<0.36.0>]
    messages: []
    links: [<0.36.0>,<0.38.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 147
  neighbours:
```

**Comment by badlop** [comment]
I tried your config file (which is almost the default one with just some modules disabled, right?), and it fails to start. Some questions:
* What ejabberd version?
* In what operating system?
* Did Web Admin work correctly anytime before, or it failed even the first tiime you tried?
* If you install ejabberd from scratch, the first time you start it, does Web Admin work?

**Comment by spippari** [comment]
Please find below answers

What ejabberd version?
--14.07
In what operating system?
--Centos7
Did Web Admin work correctly anytime before, or it failed even the first time you tried?
--It was failed for the first time
If you install ejabberd from scratch, the first time you start it, does Web Admin work?
--I installed it from scratch,No ,it was not worked for the first time.

**Comment by spippari** [comment]
Please find below answers
What ejabberd version?
--14.07
In what operating system?
--Centos7
Did Web Admin work correctly anytime before, or it failed even the first time you tried?
--It was failed for the first time
If you install ejabberd from scratch, the first time you start it, does Web Admin work?
--I installed it from scratch,No ,it was not worked for the first time.


Thanks & Regards
----------------------------------------------------------
Srikanth Pippari  | V3OPS team.
Email ID : spippari@vitechinc.com
-----------------------------------------------------------

**Comment by badlop** [comment]
Ahh, it's a version three years old. See this ticket, it may give you some idea: https://github.com/processone/ejabberd/issues/447

**Comment by spippari** [comment]
Thanks for the support,I can able to access the admin console url for ejabberd now. 

But my requirement is to access the admin console url without authentication.I have added below lines in ejabberd.yml file for anonymous access but still it is asking for credentials when i access the url..Can you please help me on this ..I am also attaching the ejabberd.yml file to this.


Added below lines in ejabberd.yml file

Anonymous login support:
    auth_method: anonymous
    anonymous_protocol:  login_anon
    allow_multiple_connections: true
host_config:
    "chatbot.vitechinc.com":
        auth_method: anonymous
        allow_multiple_connections: false
        anonymous_protocol: sasl_anon
host_config:
    "chatbot.vitechinc.com":
       auth_method:
         - internal
         - anonymous

**Comment by spippari** [comment]
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/1413702/ejabberd.yml.txt)

**Comment by badlop** [comment]
> But my requirement is to access the admin console url without authentication

Not possible. But you can specify the account and password in the URL, for example:
> http://user1@localhost:mypass11@localhost:5280/admin/acls/
