### ISSUE TITLE
Ejabberd with S4B

### ISSUE THREAD

**Issue by Langlife2** [processone/ejabberd#2053]
Hello, I've a question for y'all interested ejabberd developers and users!

How to integrate ejabberd chat service with Skype for Business? :smiley: 

I'm currently using the following software versions:

- ejabberd v.14.07 bpo wheezy.
- Erlang v.17.3.
- Linux Ubuntu 16.04 LTS.
- I used a source to install ejabberd.

thanks in advance

**Comment by mremond** [comment]
To my knowledge you cannot integrate ejabberd with Skype for Business.

**Comment by Langlife2** [comment]
I'm sorry, maybe I've used the wrong word to explain myself. 

The point is to enable some connection between ejabberd contacts and Skype contacts, and I would like to know if you are aware of some protocol or some connection that can be made to do that. 
Maybe using a webservice or something..
I will research more about it but I would appreciate some advice if you have it.

Thank you

**Comment by Langlife2** [comment]
I'm sorry, maybe I've used the wrong word to explain myself.

The point is to enable some connection between ejabberd contacts and Skype contacts, and I would like to know if you are aware of some protocol or some connection that can be made to do that.
Maybe using a webservice or something..
I will research more about it but I would appreciate some piece of advice if you have it.

Thank you

________________________________
De: Mickaël Rémond <notifications@github.com>
Enviado: 16 de outubro de 2017 14:30
Para: processone/ejabberd
Cc: Langlife2; Author
Assunto: Re: [processone/ejabberd] Ejabberd with S4B (#2053)


Closed #2053<https://github.com/processone/ejabberd/issues/2053>.

**Comment by mremond** [comment]
Sorry, I am aware of any way to do this.
