### ISSUE TITLE
AWS RDS Endpoint

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#2054]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Linux binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

Just need to ask a question in regards to whether does Ejabberd 17.08 supports endpoint for aws rds.

The current SQL documentation points out the setup for localhost MySQL will be as follow.

sql_type: mysql
sql_server: "server.company.com"
sql_port: 3306 # the default
sql_database: "mydb"
sql_username: "user1"
sql_password: "**********"
sql_pool_size: 5

Supposely for the parameter above, for "sql_server: ", can i specify here to include the aws rds endpoint which will point the DB to the aws rds mysql?  Does current ejabberd version supports this?

Thanks.

**Comment by molochmike** [comment]
Just re-look into the ejabberd docs for support on MySQL.  Looks like i miss out the section for AWS RDS compliance as stated.  So i will assume it will just works as normal by setting the RDS endpoint at the "sql_server" section?   Just need a good confirmation as I could not find any examples over the net.

**Comment by prefiks** [comment]
Yes it should work that way.
