### ISSUE TITLE
Time warp mode

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [processone/ejabberd#2055]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?  
GNU/Linux Debian  

> How did you install ejabberd (source, package, distribution)?  
Distribution  

Why you did not use `multi_time_warp` for starting Erlang?
According to the [Erlang documentation](http://erlang.org/doc/apps/erts/time_correction.html) using `erlang:now()` is deprecated and having monotonic time using `multi_time_warp` is good.  
 Why ejabberd used `erlang:now()`(in `mod_last` it calls `p1_time_compat:system_time/1` which uses `erlang:noew()`) and why it does not use new time API and `multi_warp_mode`?

```erlang
(ejabberd@localhost)1> erlang:system_info(time_warp_mode).
no_time_warp
```

**Comment by zinid** [comment]
You can use whatever mode you like in your setup.
`ejabberd` doesn't assume time wrap safety.

**Comment by prefiks** [comment]
p1_time_compat:system_time uses system_time() when your erlang do have it and now() only when your erlang version is too old.
