### ISSUE TITLE
PubSub: #purge_offline does not work successfully

### ISSUE THREAD

**Issue by ejbravo** [processone/ejabberd#2057]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

Recently, I have updated ejabberd version from 17.01 to 17.09 and I have found an unexpected error working with pubsub module:

I have created one pubsub node with some changes over default configuration:

`<field var='pubsub#access_model'><value>open</value></field>`
`<field var='pubsub#publish_model'><value>open</value></field>`
`<field var='pubsub#purge_offline'><value>1</value></field>`

I would like to focus on the last field: "purge_offline", described on the [XEP-0060](https://xmpp.org/extensions/xep-0060.html#owner-configure) as:

        <field var='pubsub#purge_offline' type='boolean'
               label='Purge all items when the relevant publisher goes offline?'>
          <value>0</value>
        </field>

Before updating to the last ejabberd version, the behaviour was that I expected: When the publisher had gone offline the system purged all items which were published by that user
However, now, no item is removed from pubsub when publisher goes offline. 

I guess that this new behaviour is caused by something new on pubsub_module. Have you any idea about this change?

**Comment by cromain** [comment]
confirmed and fixed
