### ISSUE TITLE
Registration issue with REST API

### ISSUE THREAD

**Issue by faysal515** [processone/ejabberd#2058]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?
MacOS 10.12.6(Sierra)

> How did you install ejabberd (source, package, distribution)?
Mac installer

> What did not work as expected? Are there error messages in the log?
wiling to try out ejabberd rest api from localhost without authentication. this is the api_permisssion config
```
api_permissions:
  "parse server":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "*"
      - "!stop"
      - "!start"
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - ip: "127.0.0.1/8"
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - ip: "127.0.0.1/8"
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
```

> was the unexpected behavior? What was the expected result?
sending a POST request to this address `http://localhost:5280/api/register`
getting the following error
```
{
    "status": "error",
    "code": 32,
    "message": "AccessRules: Account does not have the right to perform the operation."
}
```

> ejabber.log
```
2017-10-20 10:37:32.183 [info] <0.444.0>@mod_http_api:log:541 API call register [{<<"username">>,<<"random">>},{<<"password">>,<<"qweqwe">>},{<<"host">>,<<"sendjob">>}] from ::1:50100

```

**Comment by prefiks** [comment]
Looks like your system uses ipv6 address for localhost, so having rule just for ipv4 address is not enough in your case, if you copy loopback acl from default config (https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example) and use it here i think it will work for you.

**Comment by faysal515** [comment]
Thank you for the reply. I resolved the issue by commenting out ip from the configuration. 

though my loopback acl is like this

```
loopback:
    ip:
      - "127.0.0.0/8"
```
