### ISSUE TITLE
Bad value of attribute 'from' in tag <stream:stream/> qualified by namespace 'jabber:client'

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#2059]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Source code

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Same Android client (Java code) that works correctly with the version 16.03.92 does not work with the version 17.09. 

The XML send from my client is the following:

```
<<"<stream:stream xmlns='jabber:client' to='ejabberd.domain.com' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='username@ejabberd.domain.com@ejabberd.domain.com' xml:lang='en'>">>
```

This works properly in the version mentioned above. However, in the last version it returns an XML with the following error message:

```
Bad value of attribute 'from' in tag <stream:stream/> qualified by namespace 'jabber:client'
```

Do you know why it's happening? What is wrong?

IMHO, the ```from``` attribute has a quite strange value, but it works with the old version, and, in addition, if I modify the ```from``` value, it does not connect neither with the older version.

Any suggestion?

Thanks a lot!

**Comment by zinid** [comment]
> `username@ejabberd.domain.com@ejabberd.domain.com`

This is not a valid JID obviously (there are duplicated `@`).
It worked in previous versions because ejabberd didn't check `from` attribute for client streams. Now it does.

> if I modify the from value, it does not connect neither with the older version

What error do you get in this case?

**Comment by joanlopez** [comment]
Hi @zinid,

Your answer is what I expected.

The problem is that I'm using one of the most common XMPP Java libraries (Smack) and it produces this packet.

Is it possible to disable this verification in the side of the server (Ejabberd)?

Otherwise I will try to intercept and modify this packet, but I've tried it and I'm not being able...

Thanks a lot!

**Comment by zinid** [comment]
> The problem is that I'm using one of the most common XMPP Java libraries (Smack) and it produces this packet

That's right, this library is used by a lot of projects which don't have problems with recent versions of ejabberd. Don't you find this suspicious that only you have problems? :)

I suggest just not to set this `from` attribute, it's not mandatory for client streams.

**Comment by zinid** [comment]
I also suggest reporting this bug to the Smack devs.

**Comment by zinid** [comment]
I close due to inactivity.
