### ISSUE TITLE
how to enable ping _mod..

### ISSUE THREAD

**Issue by sambeiber** [processone/ejabberd#2060]
> What version of ejabberd are you using?

version 17.09

> What operating system (version) are you using?

Ubuntu 16

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

hi..i am beginner  using ejabberd with android application it is working with one node now  i am doing clustering  while i add cluster using 
 cluster add command ejabberdctl join_cluster 'ejabberd@node1' it give me error 
no_ping,ejabberd@node1
4369 port enable 
both nodes are on same network
due to this i am going  to add ping_mod so i am bit confuse  where to add this ping_mod in configuration file .yml etc or  in ejabbberd panel and how ?

kindly help me to resolve this issue.

**Comment by cromain** [comment]
no_ping means your host in not able to ping host node1. There is no relation with mod_ping which is about XMPP ping.
To solve this, best and simplest option is to add IP of node1 in node2's ejabberd conf/inetrc, and also add node IP of node2 in node1's ejabberd conf/inetrc and restart.

**Comment by sambeiber** [comment]
while adding IP of node 1 to node 2 and IP of Node2 to node 1 in
conf/intetrc ejabberd crash at this point ..
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_9211228727817109050_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, Oct 23, 2017 at 6:35 AM, Christophe Romain <notifications@github.com
