### ISSUE TITLE
Offline message: Delay field is missing

### ISSUE THREAD

**Issue by Ghostw4lk** [processone/ejabberd#2061]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04.3 LTS

> How did you install ejabberd (source, package, distribution)?

Cloned from the github repo

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Expected:
If a user sends a message to another user, which is offline, the message should includes the delay field when the message is stored.

Outcome:
Delay field is not existing.

```xml 
<message xml:lang='en'
         to='testuser@localhost'
         from='testuser2@localhost/test'
         id='LrRDN-39'
         xmlns='jabber:client'>
  <body>Delay test</body>
</message>
```
The mod_offline is enabled (default config).
I enabled mod_mam manually, to only store MUC messages to the MAM storage.

Here is the config:
```xml 
  mod_mam: 
    default: never
    assume_mam_usage: true
  mod_muc: 
    ## host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
       mam: true
       moderated: true
       persistent: true
       max_users: 256
       members_by_default: true
  mod_muc_admin: {}
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
```
Maybe is it related, that I´ve enabled mam?

**EDIT:** I set up a fresh server and only enabled mod_offline, but the message object has still no delay field.

**Comment by badlop** [comment]
> If a user sends a message to another user, which is offline, the message should includes the delay field when the message is stored.

Why when the message is *stored*, and not when it is finally *delivered*? The XEP only refers to the final message delivered to the destination. ejabberd stores the original packet untouched, and the timestamp, and other information. Later, when the destination user logins, mod_offline prepares the packet with the Delay element

**Comment by Ghostw4lk** [comment]
Before, all messages which are stored to the server includes a delay field, which was added by the server.
I have also a problem to fetch these mesages from the storage, because I get a correct count of messages, but I can´t get these.

**Comment by zinid** [comment]
I would just suggest you disabling offline (by issuing any flex-offline request before you send initial presence, as described in the XEP-0013) and then directly work with MAM archives only.

**Comment by Ghostw4lk** [comment]
Okay, thank you for helping, with MAM I have no issues to store One-to-One and MUC messages.
