### ISSUE TITLE
Memory consumption is high when online 2M users and TLS is enabled

### ISSUE THREAD

**Issue by malir** [processone/ejabberd#2062]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

debian 8.4

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When online  2 million users by tsung with tls, memory consume 90 GB of physical and swap.
It seems the SSL_MODE_RELEASE_BUFFERS flag is not enable and every connection has a 50KB tls footprint.

**Comment by zinid** [comment]
It's set, see https://github.com/processone/fast_tls/blob/master/c_src/fast_tls.c#L613
Also, you're lucky it consumes only 50kb, I saw values around 100kb in practice.

**Comment by zinid** [comment]
Since we are not aware of any methods to reduce openssl memory consumption (beyond already approached), I close the ticket.
