### ISSUE TITLE
Enable mod_mam in transport's MUC

### ISSUE THREAD

**Issue by p5n** [processone/ejabberd#2063]
> What version of ejabberd are you using?

ejabberd 17.09-2

> What operating system (version) are you using?

ArchLinux

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

May be it is support request. mod_mam does not store room history from transports. For example I have spectrum2/skype transport connected and all direct messages go into mod_mam database well however groupchat messages do not. Is there any way to enable mod_mam for transport's MUCs? Can it be spectrum2 problem?

**Comment by zinid** [comment]
We do not add workarounds for transports.
