### ISSUE TITLE
Commandline no groups are returned for some users

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#2064]
> What version of ejabberd are you using?
17.07

When commandline I run
./get_user_rooms patrick host

For some users i see all groups, and for some users i see nothing?
The users seem te be identical and in the messenger it works fine.

**Comment by badlop** [comment]
```
$ ejabberdctl get_user_rooms User1 localhost
$ ejabberdctl get_user_rooms user1 localhost
room1@conference.localhost
room2@conference.localhost
```

**Comment by cromain** [comment]
maybe get_user_rooms should nodeprep passed usedname ?
