### ISSUE TITLE
PubSub: Delete an Item from a Node published by an old (unregistered) user

### ISSUE THREAD

**Issue by ejbravo** [processone/ejabberd#2067]
> What version of Ejabberd are you using?

17.09

> What operating system (version) are you using?

CentOS 7

> How did you install Ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

I have found another unexpected behaviour on PUBSUB module after updating Ejabberd from v.17.01 to v.17.09

One of my pubsub nodes has the next configuration:

`<field var='pubsub#persist_items'><value>1</value></field>`
`<field var='pubsub#access_model'><value>open</value></field>`
`<field var='pubsub#publish_model'><value>open</value></field>`

As you can see, I am working with persist storage and public access. 

Previously, working with v.17.01, when an XMPP user had published an item (e.g. User 'A' published an item 'X'), no user was allowed to delete this item (e.g. User 'B' could not delete the item 'X'), the result was an 'forbidden' (403) stanza. Moreover, if user 'A' was removed from the system (unregistered) and user 'B' tried to delete the item X, result stanza said: 'item-not-found' (404). As it is described in [XEP-0060](https://xmpp.org/extensions/xep-0060.html#publisher-publish) documentation. Therefore, removing the item 'X' was not possible unless another user with privileges published a new item with the same key overwriting the previous value and then, yes, it was possible to remove definitely the item 'X'.

I am not sure if this is the best option for solving this issue, but that is what it was.

Now, v.17.09, when a user who published the item 'X' (A) is removed from the system (unregistered) and another user attempts to delete 'X', the behaviour is the same as before. However, even when another user with more privileges (e.g the admin) tries to publish an item with the same key, it is not possible to overwrite that item. So, it is technically impossible removing an item which was published on PUBSUB by a user who has been removed (unregistered).

How could I solve this issue caused by this behaviour introduced in this new version?
Thank you in advance.

**Comment by cromain** [comment]
This is a good point. We should let node owner be able to remove that item always.
Right now it gets item-not-found because associated #pubsub_state for that item has been removed, as publisher is unregistered. In this case we should just force item removal.
