### ISSUE TITLE
crashing during presence query

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#2070]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

through source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

when hooking to user_receive_packet and calling mod_admin_extra.get_presence in the callback function the process crashes to timeout. i think there is some kind of race condition between presence call and ongoing packet call.

The thing I want to achieve is that i can send push messages through FCM or APNS when users presence is unavailable. unfortunately offline hook is not enough, as user is not considered offline until ping timeout or stream mgmt timeout. but users presence could still be set to unavailable.

11:08:41.170 [error] Hook user_send_packet crashed when running 'Elixir.MoimoiModules.PushNotification':send_packet/1:
** Reason = {exit,{timeout,{p1_server,call,[<0.674.0>,get_presence,1000]}},[{p1_server,call,[{file,"/opt/app/deps/p1_utils/src/p1_server.erl"},{line,210}],3},{mod_admin_extra,get_presence,[{file,"src/mod_admin_extra.erl"},{line,1085}],1},{mod_admin_extra,get_presence,[{file,"src/mod_admin_extra.erl"},{line,1102}],2},{'Elixir.MoimoiModules.PushNotification',check_status,[{file,"lib/moimoi_modules/push_notification.ex"},{line,90}],1},{'Elixir.MoimoiModules.PushNotification',send_packet,[{file,"lib/moimoi_modules/push_notification.ex"},{line,19}],1},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_c2s,handle_authenticated_packet,[{file,"src/ejabberd_c2s.erl"},{line,469}],2}]}
** Arguments = [{{message,<<>>,normal,<<"en">>,{jid,<<"seppot">>,<<"localhost">>,<<"farady">>,<<"seppot">>,<<"localhost">>,<<"farady">>},{jid,<<"seppot">>,<<"localhost">>,<<>>,<<"seppot">>,<<"localhost">>,<<>>},[],[],undefined,[],#{ip => {172,20,0,1}}},#{mgmt_stanzas_out => 0,mgmt_max_timeout => 300,lserver => <<"localhost">>,mgmt_resend => false,tls_verify => false,zlib => true,conn => c2s_tls,server => <<"localhost">>,mgmt_timeout => 300,lang => <<"en">>,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"seppot">>,<<"localhost">>,<<"farady">>,<<"seppot">>,<<"localhost">>,<<"farady">>},{jid,<<"seppot">>,<<"localhost">>,<<>>,<<"seppot">>,<<"localhost">>,<<>>},undefined,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"VUFD6HcFmUT2NxJkBGCiKlZnS3M=">>}],[]},{xmlel,<<"x">>,[{<<"xmlns">>,<<"vcard-temp:x:update">>}],[{xmlel,<<"photo">>,[],[{xmlcdata,<<"699932f3c553963d307c092ce625a079cfd187d6">>}]}]}],#{ip => {172,20,0,1}}},socket => {socket_state,fast_tls,{tlssock,#Port<0.18625>,#Ref<0.1761268672.3280076801.110688>},<0.673.0>},xmlns => <<"jabber:client">>,csi_queue => {0,#{}},tls_required => false,mgmt_queue_type => ram,mgmt_state => inactive,shaper => c2s_shaper,mod => ejabberd_c2s,stream_restarted => true,ip => {{172,20,0,1},43498},stream_direction => in,resource => <<"farady">>,pres_timestamp => {1509,102497,380127},auth_module => ejabberd_auth_sql,sockmod => ejabberd_socket,owner => <0.674.0>,mgmt_ack_timeout => 60000,jid => {jid,<<"seppot">>,<<"localhost">>,<<"farady">>,<<"seppot">>,<<"localhost">>,<<"farady">>},stream_encrypted => true,socket_monitor => #Ref<0.1761268672.3279945729.110682>,sid => {{1509,102497,82},<0.674.0>},pres_a => {0,nil},stream_version => {1,0},stream_state => established,stream_timeout => infinity,mgmt_stanzas_req => 0,tls_enabled => true,access => c2s,mgmt_max_queue => 1000,stream_id => <<"10975092049720961375">>,stream_authenticated => true,user => <<"seppot">>,stream_header_sent => true,stream_compressed => false,tls_options => [compression_none,{ciphers,<<"HIGH">>},{certfile,<<"/opt/app/config/priv/xmpp.net-full-cert.pem">>}],csi_state => active,mgmt_stanzas_in => 0}}]

11:08:41.170 [warn]  got unexpected info: {#Ref<0.1761268672.3279945731.109094>,{presence,<<>>,available,<<"en">>,{jid,<<"seppot">>,<<"localhost">>,<<"farady">>,<<"seppot">>,<<"localhost">>,<<"farady">>},{jid,<<"seppot">>,<<"localhost">>,<<>>,<<"seppot">>,<<"localhost">>,<<>>},undefined,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"VUFD6HcFmUT2NxJkBGCiKlZnS3M=">>}],[]},{xmlel,<<"x">>,[{<<"xmlns">>,<<"vcard-temp:x:update">>}],[{xmlel,<<"photo">>,[],[{xmlcdata,<<"699932f3c553963d307c092ce625a079cfd187d6">>}]}]}],#{ip => {172,20,0,1}}}}

**Comment by zinid** [comment]
You're calling the same process from where you're calling :) This is clearly seen from your log:
`p1_server,call,[<0.674.0>, ...` and `owner => <0.674.0>`.
You need to do it another way: `user_send_packet` provides a c2s state map as part of its arguments. You can fetch `pres_last` field form this map, for example, just like it's done [here](https://github.com/processone/ejabberd/blob/17.09/src/ejabberd_c2s.erl#L533).

**Comment by jonni-larjomaa** [comment]
Thanks for the pointers :) parsing pres_last solved the problem :) still bit of a newbie with elixir/erlang so do not always what all the errors are based on stacktraces.
