### ISSUE TITLE
Pubsub last item cached not cleared when node is deleted

### ISSUE THREAD

**Issue by sailerinteractive** [processone/ejabberd#2071]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm investigating #2026 and came across this issue. I'm not 100% sure yet if they are related.

I'm running mod_pubsub with MySQL backend and last item cache enabled. When i delete a node i can see that the node and related items are deleted from the MySQL DB. However, it seems that the cached items are not removed from the Mnesia pubsub_last_item table since the number of records remains the same after node deletion (checked with ejabberdctl mnesia info)

In my application a lot of nodes are created and removed after a certain amount of time which leads to an ever growing pubsub_last_item table and related resource usage.

**Comment by cromain** [comment]
I confirm this is a mistake, will be fixed by next release.
