### ISSUE TITLE
bad_server

### ISSUE THREAD

**Issue by TaganRock1** [processone/ejabberd#2073]
How to block a server (bad_server) for a specific user(ej 16.03).
eg:
user:
- myname@myserver.ru
  bad_servers:
     server:
      - "6irc.net"
      - "42cc.co"
      - "jabber3star.com"
      - "rows.io"

**Comment by TaganRock1** [comment]
mmm?
`host_config:
   "myserver.ru":
     acl:
       admin:
         user:
           - "myname": "myserver.ru"
           access:
             s2s: 
               bad_servers: deny
               all: allow`

**Comment by TaganRock1** [comment]
`host_config:
   "myserv.ru":
     acl:
       user:
         - "myname": "myserv.ru"
           bad_servers:
             server:
               - "tigase.im"`

**Comment by TaganRock1** [comment]
host_config:
   "myserv.ru":
     acl:
       user:
         - "myname": "myserv.ru"
           bad_servers:
             server:
               - "tigase.im"

**Comment by cromain** [comment]
you miss the access rule, please read the documentation
access rule cal look like this
    access_rules:
      s2s:
        - deny: bad_servers
