### ISSUE TITLE
urn:xmpp:mam:2 and ejabberd

### ISSUE THREAD

**Issue by rheman** [processone/ejabberd#2077]
Hi everyone.
I am using converjs with ejabberd 16.09.
I want to know which version of ejabberd support urn:xmpp:mam:2
Best regard.

**Comment by cromain** [comment]
Hi
a simple search would have pointed https://github.com/processone/ejabberd/issues/1762 which is about urn:xmpp:mam:2

**Comment by rheman** [comment]
Thanks a  lot ... Which lastest release XEP-0313 is supported (0.2 , 0.3 , 0.6 ) by ejabberd ?

**Comment by badlop** [comment]
According to the source code, 0.5.1.
