### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by shashwatbishwen** [processone/ejabberd#2082]
> What version of ejabberd are you using?

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

/home/ubuntu/ejabberd/deps/xmpp/xmpp_codec: function get_mod/2+2689:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,862},[{x,5},0]}
  Error:       {no_bsm_context,{x,5}}:

Compiling /home/ubuntu/ejabberd/deps/xmpp/src/xmpp_codec.erl failed:
ERROR: compile failed while processing /home/ubuntu/ejabberd/deps/xmpp: rebar_abort
Makefile:100: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1

**Comment by Ghostw4lk** [comment]
This issue is a duplicate, see here: https://github.com/processone/ejabberd/issues/2032

**Comment by zinid** [comment]
Duplicates #2032
