### ISSUE TITLE
mod_admin_extra falls off, if delete one of several vhosts from config

### ISSUE THREAD

**Issue by oxoWrk** [processone/ejabberd#2083]
ejabberd 17.08
Debian 8.6
with Binary Installer

mudule admin_extra falls off, if delete host (one of several ) from config and  do reload_config . Logs are clean. Fix only ejabberd restart

**Comment by zinid** [comment]
> mudule admin_extra falls off

What does it mean? I see nothing when I remove a host and reload.

**Comment by oxoWrk** [comment]
After removing the host and rebooting the config,  module admin_extra commands  are not available on the command line and through api 

> ./ejabberdctl user_sessions_info
> {error,unknown_command}

**Comment by badlop** [comment]
Problem confirmed. When a host is removed, its modules get stopped, so mod_admin_extra is stopped for that host, and it removes all its commands regardless if other hosts still have this module enabled.
