### ISSUE TITLE
How to configure XMPP  in ejabberd?

### ISSUE THREAD

**Issue by spippari** [processone/ejabberd#2084]
> What version of ejabberd are you using?

14.07

> What operating system (version) are you using?

Centos7

> How did you install ejabberd (source, package, distribution)?

i have installed it from source package(using yum command)

I have installed ejabberd .Can you please help to enable Xmpp on the ejabberd server?
How do we test with an xmpp/jabber after the installation?

**Comment by cromain** [comment]
Please read the documentation about how to configure ejabberd
https://docs.ejabberd.im/admin/

**Comment by spippari** [comment]
![pidgin-error-screenshot](https://user-images.githubusercontent.com/25244961/32558529-f6ce8ab2-c472-11e7-9f3e-a3b1050f151e.png)
I have configured ejabberd chat server and enabled anonymous access to login console with any username and password.I want to test ejabberd integrating with pidgin.When i am trying to create a user from pidgin client i am getting Registration failed with 405:Not allowed error.Do we need to modify anything in ejabberd.yml file to fix this issue
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/1454499/ejabberd.yml.txt)
.I am attaching error screenshot and my ejabberd.yml file.Can you please help me to resolve the issue.

**Comment by spippari** [comment]
I tried by commenting out below lines in the ejabberd.yml file but still have same issue
trusted_network:
    loopback: allow
 ip_access: trusted_network

**Comment by spippari** [comment]
Thanks Weiss,It's working as expected after few changes in ejabberd.yml file..

**Comment by spippari** [comment]
Thanks Weiss,It's working as expected after few changes in ejabberd.yml file..

**Comment by spippari** [comment]
Thanks @weiss ,It's working as expected after few changes in ejabberd.yml file..

**Comment by spippari** [comment]
Thanks @weiss ,It's working as expected after few changes in ejabberd.yml file..
