### ISSUE TITLE
How to add pending roster using ejabberdctl

### ISSUE THREAD

**Issue by rheman** [processone/ejabberd#2085]
Hi everyone.

I am using converjs with ejabberd 16.09 under Debian 9. I am using distribution package.
I want to know how to add a pending roster using ejabberdctl. I have tried ejabberdctl add_rosteritem but add_rosteritem does not support pending parameter.
Which command should I use .

Best regard.

**Comment by badlop** [comment]
Right, add_rosteritem doesn't allow to set the "ask" element. You can try sending a stanza with send_stanza or send_stanza_c2s command.
