### ISSUE TITLE
Support: XEP-0256: Last Activity in Presence

### ISSUE THREAD

**Issue by Ghostw4lk** [processone/ejabberd#2087]
Hey,

I saw that this XEP protocol is supported in the business version of the ejabberd server. 
Is it also possible to implement this module in the community edition or is it only allowed in the business version?

Thanks in advance.

**Comment by badlop** [comment]
Looking at https://xmpp.org/extensions/xep-0256.html I see nothing that needs implementation in the server, it's a client protocol, right? Where did you read that ejabberd supports it?

**Comment by Ghostw4lk** [comment]
I saw it here: https://www.process-one.net/en/ejabberd/protocols/

**Comment by badlop** [comment]
Ah, yes, looking at the source code of Business Edition, it has additional code to add a Delay element in some cases, if not already included by the sender client.

> Is it also possible to implement this module in the community edition or is it only allowed in the business version?

The response is already in that table: not included. But of course you can implement the feature.
