### ISSUE TITLE
mod_push configuration

### ISSUE THREAD

**Issue by skyfox675** [processone/ejabberd#2089]
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
Server 2016

> How did you install ejabberd (source, package, distribution)?
Windows 64bit Installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Unable to locate documentation on configuring mod_push for FCM and APNS.

**Comment by weiss** [comment]
`mod_push` doesn't support FCM/APNS.  It's meant to be used with third-party clients such as [Conversations][1] or [ChatSecure][2], where the actual FCM/APNS notifications are generated by a service provided by the respective app vendor.  `mod_push` merely notifies such services (see [XEP-0357][3] if you're interested in the details).

Closed/commercial chat solutions who control the mobile apps themselves don't need XEP-0357 support, but could indeed let ejabberd generate FCM/APNS notifications directly.  This is supported by the Business Edition.

[1]: https://conversations.im/
[2]: https://chatsecure.org/
[3]: https://xmpp.org/extensions/xep-0357.html
