### ISSUE TITLE
delte_old_mam_messages crashes ejabberd

### ISSUE THREAD

**Issue by nekoswag** [processone/ejabberd#2090]
> What version of ejabberd are you using?

17.07 and 17.09 (happens on both)

> What operating system (version) are you using?

openSUSE Leap 42.3

> How did you install ejabberd (source, package, distribution)?

distribution
https://build.opensuse.org/project/show/devel:languages:erlang

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When running
>sudo -u ejabberd ejabberdctl delete_old_mam_messages all 90

the CPU load shoots up, leading to timeouts, then RAM explodes as well and ejabberd will allocate more and more until it crashes.
I ran this command every day before, but only recently it started causing ejabberd to crash.
Attached are the latest two crash logs from /var/log/ejabberd/erl_crash_XXXXX.dump (I only replaced my real vhost name with mydomain.com)
[erl_crash_dumps.tar.gz](https://github.com/processone/ejabberd/files/1449633/erl_crash_dumps.tar.gz)

It's possibly related to
#2069

**Comment by weiss** [comment]
My guess is that you're using Mnesia and the table was corrupted.  In that case you probably can't do much other than throwing it away:

    ejabberdctl stop
    cd $SPOOL_DIR ;# To find the $SPOOL_DIR: grep SPOOL_DIR=/ `which ejabberdctl`
    mv archive_msg* /tmp/
    ejabberdctl start

As I don't know how to protect against such table corruption, I'd strongly recommend switching to SQL, at least for MAM.

If you're *not* using Mnesia, please post the trace(s) from your crash.log file.  We'll then reopen the issue.
