### ISSUE TITLE
Idle kick in MUC

### ISSUE THREAD

**Issue by axcl** [processone/ejabberd#2091]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?
Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
Binary installer .run file

> What did not work as expected? Are there error messages in the log? What
Everything working fine
> was the unexpected behavior? What was the expected result?
Nothing

Hello Team,

I am wondering is there any option for setting a idle time for users in a muc room after which they will be kicked out of tje room automatically.

Currently once a id enters it remains unless it get disconnected.

**Comment by zinid** [comment]
> I am wondering is there any option for setting a idle time for users in a muc room after which they will be kicked out of tje room automatically.

There are no such options. An occupant will only be kicked if an error stanza is received from it.

> Currently once a id enters

Who enters?

**Comment by axcl** [comment]
Any user. Can you guide me how can i achieve this by editing module

**Comment by zinid** [comment]
You need to mess with timers, this is not very trivial since the module is complex.

**Comment by axcl** [comment]
Can it be done creating hook cause what happens now if a device disconnected unexpectedly it remains in muc for unlimited time unless anyone kick the id

**Comment by zinid** [comment]
Short answer: no
