### ISSUE TITLE
Sessions not cleared after stream management timeout

### ISSUE THREAD

**Issue by sailerinteractive** [processone/ejabberd#2092]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Clients connect through web sockets, stream management is enabled. When a connection of a client fails, offline presence is sent to other clients as expected after the configured "resume_timeout" but the session count in the mnesia session table remains the same. I'm not sure if there are other resources which are not properly freed as well.

With stream management disabled the number in the session table always reflects the number of online users and drops when a resource goes offline.

**Comment by weiss** [comment]
Yes, currently the record is kept until a client with the same resource string re-logs in (or the `max_user_sessions` limit is reached).  The record is used to look up the `h` value for the `<failed/>` response in case the client tries to [resume][1] the session later.

[1]: https://xmpp.org/extensions/xep-0198.html#resumption
