### ISSUE TITLE
send_direct_invitation not working on MUC [ejabberd mod muc admin]

### ISSUE THREAD

**Issue by a-pool** [processone/ejabberd#2094]
> What version of ejabberd are you using?
    Ejabberd 16.01

> What operating system (version) are you using?
    Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
   distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i have no problem to create MUC room. But when i want to add participant for the room and use below command :

> ejabberdctl send_direct_invitation testRoom@localhost localhost "" "hi" msg_test1@localhost

it return error like this 

> Problem 'error function_clause' occurred executing the command.
Stacktrace: [{jid,to_string,[error],[{file,"src/jid.erl"},{line,134}]},
             {mod_muc_admin,send_direct_invitation,5,
                            [{file,"src/mod_muc_admin.erl"},{line,695}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,407}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,295}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,220}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,205}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]

May i know the right way to execute the command?

**Comment by cromain** [comment]
If you read the doc https://docs.ejabberd.im/developer/ejabberd-api/admin-api/
you will see what you're doing wrong.
args should be send_direct_invitation testRoom conference.localhost "" "hi" msg_test1@localhost
