### ISSUE TITLE
ejabberdctl's SPOOL_DIR value no longer based on ERLANG_NODE set in ejabberdctl.cfg

### ISSUE THREAD

**Issue by clamjamfrie** [processone/ejabberd#2097]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

x64 Debian Package from www.process-one.net

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

After upgrading from 17.04 to 17.09 I noticed that ejabberctl does not set SPOOL_DIR based on the value of ERLANG_NODE set in ejabberctl.cfg. In 17.04 it did.

SPOOL_DIR is now set to its value before ejabberctl.cfg is loaded and thus it is set using the default ERLANG_NODE value of ejabbed@localhost and not the one in ejabberdctl.cfg

Obviously I can run ejabberdctl with the --spool option to set where I want it to be, but this was not required in 17.04 before the big ejabberdctl refactor in commit cbe6553.

Regards.

Ian Gordon.

**Comment by cromain** [comment]
good catch ! we'll fix that by next release.

**Comment by cromain** [comment]
note: this only affects binary installer

**Comment by cromain** [comment]
will be fixed by 17.11 installer
