### ISSUE TITLE
ldap authentication code no longer has any supported ciphers on ldap server after upgrade of ejabberd

### ISSUE THREAD

**Issue by clamjamfrie** [processone/ejabberd#2098]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

x64 Debian Package from www.process-one.net

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We are using 'auth_method: ldap" and it was all working fine with ejabberd 17.04.
After an upgrade to 17.09 we now get

```
2017-11-09 20:10:40.937 [error] <0.481.0>@eldap:connect_bind:1083 LDAP connection failed:
** Server: ldaphost0.cis.strath.ac.uk:636
** Reason: closed
** Socket options: [{packet,asn1},{active,true},{keepalive,true},binary]
```

errors in the ejabberd.log file.

I have debugged this down to ejabberd as an ldap client not having any ciphers that our LDAP server supports. Our LDAP server currently only allow SECURE128 and SECURE 192 ciphers as defined in gnutls. If I also allow NORMAL ciphers on the LDAP server then the secure LDAP connection succeeds.

We are using openssl 1.0.2g on the server (although ejabberd seems to be using its own version).

I know that openssl 1.0.2g does have ciphers in common with our LDAP server because running

`openssl s_client -host <hostname> -port 636`

connects using cipher ECDHE-RSA-AES256-GCM-SHA384

Is there any way to make the ldap connection us a better set of ciphers?

Thanks,

Ian Gordon.

**Comment by badlop** [comment]
I close this ticket due to inactivity. If somebody sees the problem with a recent ejabberd version, please reopen.

**Comment by cmfrtl** [comment]
Some problem. How resolve it?

**Comment by licaon-kter** [comment]
@cmfrtl ejabberd version? OTP version? OS version? link to [gist](https://gist.github.com) with config?

**Comment by Neustradamus** [comment]
@clamjamfrie: Any news since this ticket? Have you updated? Have you solved?
@cmfrtl: Have you seen reply from @licaon-kter? What are your infos?
