### ISSUE TITLE
<subject xml:lang="en">...</subject> and PSI client do not work...

### ISSUE THREAD

**Issue by wkg** [processone/ejabberd#2099]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
Gentoo

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Psi do not view subject in MUC.

if subject change when psi in muc - all OK! in XML `<subject>....</subject>`
BUT when PSI join in muc - subject empty and in XML - `<subject xml:lang="en">...</subject>`

for what is there xml:lang ?? AND always "en"! in settings ejabberd - language: "ru"

in ejabberd 16.09 all is OK. problem with 17.xx

**Comment by zinid** [comment]
> for what is there xml:lang ?? AND always "en"! in settings ejabbed - language="ru"

Although there is indeed a minor problem with languages (which I will fix), psi MUST accept subject elements with `xml:lang` attribute set, see [Section 5.2.4](https://tools.ietf.org/html/rfc6121#section-5.2.4) or RFC6121

**Comment by wkg** [comment]
when first time set subject: 
`<message to="....." id="aceaa**" xml:lang="ru"** type="groupchat" from="....">
<archived xmlns="urn:xmpp:mam:tmp" id="1510497544047206" by="...."/>
<stanza-id xmlns="urn:xmpp:sid:0" id="1510497544047206" by="...."/>
<subject>test</subject>`
</message>`

when join in muc:
`<message to="...." type="groupchat" from="...">
<subject xml:lang="en">test</subject>
</message>`

maybe need this:
`<message to="...." xml:lang="en"  type="groupchat" from="...">
<subject>test</subject>
</message>`
?
in RFC subject without xml:lang...
may be you can say how this fix in code ejabberd 17?

**Comment by wkg** [comment]
in psi i write issue https://github.com/psi-im/psi/issues/331

**Comment by zinid** [comment]
> in RFC subject without xml:lang...

Are you blind or what?

**Comment by wkg** [comment]
Did not notice, sorry

**Comment by zinid** [comment]
I'm preparing a fix where exact copy of all `<subject/>` elements is saved by ejabberd (and thus returned untouched to clients).

**Comment by wkg** [comment]
А можно по русски написать? у вас вроде имя то наше)
Наверное это правильноее решение - сохранять... 
Но пока что сложно дать небольшой патчик чтоб в версии 17.04 просто был subject всегда без xml:lang? я пытался сам найти, но не получилось, erlang не знаю совсем... Если это не сложно, пожалуйста...

**Comment by zinid** [comment]
Патч можно будет выдернуть из коммита, он должен будет накатиться без проблем на 17.04.

**Comment by wkg** [comment]
Сообщите какой именно коммит на эту тему будет?

**Comment by zinid** [comment]
Да

**Comment by zinid** [comment]
@wkg so you need https://github.com/processone/ejabberd/commit/11829906ac5a3145b862bd1bc55a088c1ad4fafb and https://github.com/processone/ejabberd/commit/1413f5dd23c680c3d3f69ddca0bebe7e95183c81

**Comment by wkg** [comment]
Работает, спасибо!
