### ISSUE TITLE
Node name ejabberd 17.08

### ISSUE THREAD

**Issue by TaganRock1** [processone/ejabberd#2101]
I plan to install the latest ejabberd on a separate server. Prompt please how to change before installation localhost on other name, what and the name of a node was another right after installation.

Планирую устанавливать последний ежабберд на отдельный сервер. Подскажите пожалуйста, как изменить до установки локалхост на другое имя, что бы и имя ноды было другое сразу после установки.

**Comment by zinid** [comment]
Frankly the question is cumbersome: what exactly do you need to achieve? You can set any FQDN for your machine and then just set
```
ERLANG_NODE=ejabberd@your-fqdn-here
```
in ejabberdctl.cfg

**Comment by zinid** [comment]
This is if we talk about initial installation (not a part of a cluster or relocation).
