### ISSUE TITLE
17.08 | Failed to secure inbound s2s connection: TLS failed: SSL_CTX_new failed

### ISSUE THREAD

**Issue by TaganRock1** [processone/ejabberd#2102]
**Users do not see my jabber, as I do not see the other jabber. The error is:**
Remote server not found.
A remote server or service specified as part or all of the JID of the intended recipient does not exist.

**Ejabberd.yml:**
https://pastebin.com/EjWhHsra

**Error:**
```
2017-11-14 01:14:05.974 [error] <0.1645.5>@ejabberd_s2s_in:terminate:292 (tcp|<0.1644.5>) Failed to secure inbound s2s connection: TLS failed: SSL_CTX_new failed
2017-11-14 01:21:42.482 [error] <0.1658.5>@ejabberd_http:init:114 CRASH REPORT Process <0.1658.5> with 0 neighbours crashed with reason: no match of right hand value {error,<<"SSL_CTX_new failed">>} in ejabberd_http:init/2 line 114
```

**Crash:**
```
2017-11-14 01:21:42 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.1658.5>
    registered_name: []
    exception error: {{badmatch,{error,<<"SSL_CTX_new failed">>}},[{ejabberd_http,init,2,[{file,"src/ejabberd_http.erl"},{line,114}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.26152.3>,ejabberd_listener,ejabberd_sup,<0.25897.3>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.37697>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 293
  neighbours:
```

**Ejabberd version:** 17.08
Debian x86_64

**Comment by zinid** [comment]
This line is failing: https://github.com/processone/fast_tls/blob/master/c_src/fast_tls.c#L565
Lord knows why it fails, maybe because of a deprecation of `SSLv23_method()` API function?
What version of openssl ejabberd is compiled against (use `$ ldd fast_tls.so`)?

**Comment by TaganRock1** [comment]
**openssl version**
OpenSSL 1.1.0g  2 Nov 2017

**ldd fast_tls.so**
ldd: ./fast_tls.so: No such file or directory

**Comment by zinid** [comment]
Sigh...

**Comment by TaganRock1** [comment]
Not relevant. Fixed thanks to the settings.
