### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by rvman** [processone/ejabberd#2104]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Debian 8.7

> How did you install ejabberd (source, package, distribution)?

deb package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have 2 ejabberd instances in a cluster and they both crash on a regular basis every few days.

This has been happening since 17.04.  We upgraded to 17.09 in the hopes that it would fix the issue, but if anything, it's gotten worse now.

We have a mostly stock install, save for a custom authentication script.

Postgresql is used as the backing database for everything.

Instances are fronted by an Amazon ELB to distribute requests.  Servers have 4CPU/16GB ram.

Total number of simultaneous/online users is not very high - under 3k.

Here is the most recent crash log entry.  Hopefully something can be gleaned from it.

2017-11-15 03:13:34 =ERROR REPORT====
** Generic server <0.26488.104> terminating 
** Last message in was {'$gen_event',{xmlstreamelement,{xmlel,<<"presence">>,[{<<"id">>,<<"ur897-2401">>},{<<"type">>,<<"unavailable">>}],[]}}}
** When Server state == #{mod => ejabberd_c2s,socket => {socket_state,gen_tcp,#Port<0.684968>,<0.11892.104>},mgmt_timeout => 300,mgmt_max_queue => 1000,xmlns => <<"jabber:client">>,stream_version => {1,0},csi_queue => {0,#{}},mgmt_resend => false,stream_restarted => true,shaper => c2s_shaper,stream_timeout => {30000,-576356261907},mgmt_state => inactive,access => c2s,tls_options => [compression_none,{protocol_options,<<"no_sslv3">>},{certfile,<<"/opt/ejabberd-17.09/conf/server.pem">>}],mgmt_stanzas_in => 0,mgmt_stanzas_out => 0,tls_verify => false,auth_module => ejabberd_auth_external,user => <<"20003717814">>,stream_direction => in,sockmod => ejabberd_socket,mgmt_queue_type => ram,mgmt_ack_timeout => 60000,mgmt_stanzas_req => 0,lang => <<"en">>,ip => {{0,0,0,0,0,65535,2760,24},61879},stream_id => <<"9600649169375258625">>,socket_monitor => #Ref<0.0.25427970.36364>,resource => <<>>,mgmt_max_timeout => 300,stream_encrypted => false,lserver => <<"chat.foo.com">>,server => <<"chat.foo.com">>,stream_header_sent => false,csi_state => active,pres_a => {0,nil},owner => <0.26488.104>,stream_compressed => false,stream_authenticated => true,tls_required => false,zlib => false,stream_state => wait_for_stream,tls_enabled => true}
** Reason for termination == 
** {{case_clause,{presence,<<"ur897-2401">>,unavailable,<<>>,undefined,undefined,undefined,[],undefined,[],#{}}},[{xmpp_stream_in,process_element,2,[{file,"src/xmpp_stream_in.erl"},{line,528}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-11-15 03:13:34 =CRASH REPORT====
  crasher:
    initial call: xmpp_stream_in:init/1
    pid: <0.26488.104>
    registered_name: []
    exception exit: {{{case_clause,{presence,<<"ur897-2401">>,unavailable,<<>>,undefined,undefined,undefined,[],undefined,[],#{}}},[{xmpp_stream_in,process_element,2,[{file,"src/xmpp_stream_in.erl"},{line,528}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{p1_server,terminate,7,[{file,"src/p1_server.erl"},{line,878}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.63.0>]
    messages: []
    links: [<0.471.0>]
    dictionary: [{'$internal_queue_len',0},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[111525840439279916|38484302832208507]}},{already_terminated,true}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 3252
  neighbours:
2017-11-15 03:13:34 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_c2s_sup}
     Context:    child_terminated
     Reason:     {{case_clause,{presence,<<"ur897-2401">>,unavailable,<<>>,undefined,undefined,undefined,[],undefined,[],#{}}},[{xmpp_stream_in,process_element,2,[{file,"src/xmpp_stream_in.erl"},{line,528}]},{xmpp_stream_in,handle_info,2,[{file,"src/xmpp_stream_in.erl"},{line,341}]},{p1_server,handle_msg,8,[{file,"src/p1_server.erl"},{line,696}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.26488.104>},{id,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

**Comment by zinid** [comment]
What crashes are you talking about? erl_crash.dump? core dump? Or the stuff you see in the config?
Also, are you using BOSH?

**Comment by rvman** [comment]
By crashing, I mean the ejabber process dies/exits and clients can no longer connect (socket isn't listening).

We don't get any core dump files, but we have lots of entries in the crash.log.  The above is the most recent one of many.

**Comment by zinid** [comment]
The crashes you have shown are irrelevant, they cannot block ejabberd from listening the sockets.

**Comment by zinid** [comment]
I also asked you: are you using BOSH?

**Comment by rvman** [comment]
I'm not sure on the BOSH thing - I'll have to confirm with our mobile app devs what sdk/protocol they're using.  Is there a way I can easily tell from looking at the logs?

**Comment by zinid** [comment]
> Is there a way I can easily tell from looking at the logs?

Hum, no, I don't think so.
You also need to find other errors in the crash.log/error.log and show them here.

**Comment by rvman** [comment]
[crash2.log](https://github.com/processone/ejabberd/files/1474479/crash2.log)
Here's another nasty looking entry in the crash log we're also seeing now and then, if it helps

**Comment by zinid** [comment]
This means your SQL is overloaded: 11 thousands of unprocessed requests in the queue.
And you are using `mod_shared_roster`, hehe. That's bad, its code really scales bad. Actually it is overloading your SQL connections.

**Comment by rvman** [comment]
Here's one of the last error.log entries before the last restart.  Looks like a database error of some sort:

`
2017-11-15 07:54:31.463 [error] <0.29834.43>@ejabberd_sql:sql_query_internal:570 Internal error while processing SQL query: {exit,{timeout,{gen_server,call,[<0.29767.43>,{execute,{<<"Q84489452">>,[<<"20001203908">>,<<"Blocked contacts">>]}}]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,204}]},{ejabberd_sql,pgsql_execute_sql_query,2,[{file,"src/ejabberd_sql.erl"},{line,700}]},{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,558}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,427}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-11-15 07:54:31.463 [error] <0.12563.127>@ejabberd_sql:check_error:1078 SQL query 'Q84489452' at {mod_privacy_sql,341} failed: <<"internal error">>
`

**Comment by zinid** [comment]
@rvman yes, this is a consequence of what I said above.

**Comment by rvman** [comment]
Ah... well that would explain it.  Thanks!

Well at least I can easily scale up the DB side if that's the root cause of everything.  If I can disable mod_shared_roster, I'll do that first!

**Comment by zinid** [comment]
But this still doesn't explain why ejabberd stops accepting connections. If the listeners have failed, you should detect that in error.log/crash.log.

**Comment by zinid** [comment]
@rvman also consider using [cache](https://docs.ejabberd.im/admin/configuration/#caching) wherever possible.
Well, would be great to look into ejabberd.yml anyway.

**Comment by rvman** [comment]
Ok - I see what's really happened now....

At some point during all this, there must be a memory leak or a queue is getting too big or something.

The kernel's OOM killer is kicking in and killing ejabberd... thus no listening socket :-)

**Comment by zinid** [comment]
Yes, this could happen when your SQL is constantly overloaded.

**Comment by rvman** [comment]
There are also errors like this in the error.log - probably also sql related?

`
2017-11-14 21:04:59.263 [error] <0.8733.64>@ejabberd_hooks:safe_apply:383 Hook roster_get crashed when running mod_shared_roster:get_user_roster/2:
** Reason = {exit,{{process_limit,{max_queue,11605}},{p1_fsm,sync_send_event,[<0.23829.22>,{sql_cmd,{sql_query,{sql_query,<<"Q77520278">>,#Fun<mod_shared_roster_sql.0.47411181>,#Fun<mod_shared_roster_sql.1.47411181>,#Fun<mod_shared_roster_sql.2.47411181>,{mod_shared_roster_sql,53}}},-576378372392},60000]}},[{p1_fsm,sync_send_event,[{file,"src/p1_fsm.erl"},{line,238}],3},{ejabberd_sql,sql_query,[{file,"src/ejabberd_sql.erl"},{line,133}],2},{mod_shared_roster_sql,list_groups,[{file,"src/mod_shared_roster_sql.erl"},{line,51}],1},{mod_shared_roster,get_special_users_groups,[{file,"src/mod_shared_roster.erl"},{line,467}],1},{mod_shared_roster,get_user_groups,[{file,"src/mod_shared_roster.erl"},{line,403}],1},{mod_shared_roster,get_user_displayed_groups,[{file,"src/mod_shared_roster.erl"},{line,532}],1},{mod_shared_roster,get_user_roster,[{file,"src/mod_shared_roster.erl"},{line,141}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4}]}
** Arguments = [[],{<<"20006743098">>,<<"chat.foo.com">>}]
2017-11-14 21:04:59.263 [error] <0.3361.64>@ejabberd_hooks:safe_apply:383 Hook unset_presence_hook crashed when running mod_last:on_presence_update/4:
** Reason = {exit,{{process_limit,{max_queue,11605}},{p1_fsm,sync_send_event,[<0.23829.22>,{sql_cmd,{sql_query,#Fun<mod_last_sql.5.50928161>},-576378415744},60000]}},[{p1_fsm,sync_send_event,[{file,"src/p1_fsm.erl"},{line,238}],3},{ejabberd_sql,sql_query,[{file,"src/ejabberd_sql.erl"},{line,133}],2},{mod_last_sql,store_last_info,[{file,"src/mod_last_sql.erl"},{line,61}],4},{ets_cache,update,[{file,"src/ets_cache.erl"},{line,189}],5},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run1,[{file,"src/ejabberd_hooks.erl"},{line,329}],3},{ejabberd_c2s,process_terminated,[{file,"src/ejabberd_c2s.erl"},{line,280}],2},{mod_stream_mgmt,c2s_terminated,[{file,"src/mod_stream_mgmt.erl"},{line,282}],2}]}
** Arguments = [<<"20001792173">>,<<"chat.foo.com">>,<<"Android">>,<<"Connection failed: connection closed">>]
2017-11-14 21:04:59.263 [error] <0.30920.63>@mod_pubsub:transaction_retry:3603 transaction return internal error: {'EXIT',{{process_limit,{max_queue,11605}},{p1_fsm,sync_send_event,[<0.23829.22>,{sql_cmd,{sql_bloc,#Fun<mod_pubsub.94.90127600>},-576378417619},60000]}}}
2017-11-14 21:04:59.263 [error] <0.8779.64>@mod_pubsub:transaction_retry:3603 transaction return internal error: {'EXIT',{{process_limit,{max_queue,11605}},{p1_fsm,sync_send_event,[<0.23829.22>,{sql_cmd,{sql_bloc,#Fun<mod_pubsub.94.90127600>},-576378389706},60000]}}}
`

**Comment by zinid** [comment]
Yes
