### ISSUE TITLE
Want to get all registered user from jabber server. used smack 4.1lib

### ISSUE THREAD

**Issue by gpandroid90** [processone/ejabberd#2106]
I have used bellow code to get list of all user but geting error like "policy-violation - modify".
  ProviderManager.addIQProvider("query","jabber:iq:search", new UserSearch.Provider());

        List<String> l = new ArrayList<String>();

        UserSearchManager search = new UserSearchManager(connection);
        try {
            Log.e("Iteartor values......"," "+connection.getServiceName());
            Form searchForm = search.getSearchForm("search." + connection.getServiceName());
            Form answerForm = searchForm.createAnswerForm();

            answerForm.setAnswer("Username", true);
            answerForm.setAnswer("search", "t");

            System.out.println("search form");
            ReportedData data = search.getSearchResults(answerForm, "search."+connection.getHost());

            if(data.getRows() != null)
            {
                System.out.println("not null");
                Iterator<ReportedData.Row> it = (Iterator<ReportedData.Row>) data.getRows();
                while(it.hasNext())
                {
                    System.out.println("row");
                    ReportedData.Row row = it.next();
                    Iterator iterator = (Iterator) row.getValues("jid");
                    if(iterator.hasNext())
                    {
                        String value = iterator.next().toString();
                        l.add(value);
                         Log.e("Iteartor values......"," "+value);
                    }
                 //   Log.i("Iteartor values......"," "+value);
                }

            }else{
                System.out.println("its null");
            }

        } catch (XMPPException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("not search form");
        } catch (SmackException.NotConnectedException e) {
            e.printStackTrace();
        } catch (SmackException.NoResponseException e) {
            e.printStackTrace();
        }
        return l;
=================================================================
bellow my logcat
11-15 18:20:54.310 22051-30033/com.xmppdemo D/SMACK: SENT (1): <iq to='search.3rddigital-001s-imac.local' id='0iySu-71' type='get'><query xmlns='jabber:iq:search'/></iq>
11-15 18:20:54.312 22051-30034/com.xmppdemo D/SMACK: RECV (1): <iq xml:lang='en' to='gaurav@3rddigital-001s-imac.local/xmppdemo' from='search.3rddigital-001s-imac.local' type='error' id='0iySu-71'><query xmlns='jabber:iq:search'/><error code='403' type='modify'><policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Server connections to local subdomains are forbidden</text></error></iq><r xmlns='urn:xmpp:sm:3'/>
11-15 18:20:54.314 22051-30033/com.xmppdemo D/SMACK: SENT (1): <a xmlns='urn:xmpp:sm:3' h='7'/>
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPPError: policy-violation - modify
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(PacketCollector.java:232)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(PacketCollector.java:213)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at org.jivesoftware.smackx.search.UserSearch.getSearchForm(UserSearch.java:73)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at org.jivesoftware.smackx.search.UserSearchManager.getSearchForm(UserSearchManager.java:71)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at com.xmppdemo.xmpp.XMPPHandler.getAllUser(XMPPHandler.java:343)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at com.xmppdemo.AddUserActivity$GetUserAcync.doInBackground(AddUserActivity.java:114)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at com.xmppdemo.AddUserActivity$GetUserAcync.doInBackground(AddUserActivity.java:103)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-15 18:20:54.315 22051-30032/com.xmppdemo W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-15 18:20:54.316 22051-30032/com.xmppdemo I/System.out: not search form
11-15 18:20:54.409 22051-22051/com.xmppdemo E/LIST: []

**Comment by zinid** [comment]
Or maybe you have it, but the service name is different.

**Comment by gpandroid90** [comment]
@zinid I was have value of mod_vcard set as [{search, true}]  there but still getting issue... can you halp me for fix issue like <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/> which getting in logcat.

also if we have using wrong server name then it will stop working other function.
but i am sure that server name is right. used search.3rddigital-001s-imac.local

**Comment by zinid** [comment]
Are you sure? Can you use some jabber client (Gajim or Psi) to connect to the server and open it's "Service Discovery" browser? You will see all routes registered by ejabberd.

**Comment by gpandroid90** [comment]
yes i use gajjim for cross verification Both my app and Gajim is working fine..chat is working but i found that Gajim also not have list of registered user..

also thank you sir @zinid for your reply And hope you have any code then can you share with me.

**Comment by zinid** [comment]
@gpandroid90 as I said above you're sending your requests to non-registered route, because this error is generated inside `ejabberd_s2s`: ejabberd sees it doesn't serve the domain and route it to s2s manager.
