### ISSUE TITLE
XEP-0163 - owner did not receive any PEP notifications

### ISSUE THREAD

**Issue by Torxen** [processone/ejabberd#2108]
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
CentOS Linux 7 (Core)

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

As described in [XEP-0163: Personal Eventing Protocol](https://xmpp.org/extensions/xep-0163.html) after publishing an event the owner should receive his own notifications on every resource even if the resource was offline.  The issue is that the owner did not receive any notifications, it doesn’t matter if the client is online or after sending the initial presence stanza.

The feature works with people in my roster.

`Because PEP services must send notifications to the account owner, you too receive the notification at each of your resources (here "balcony" and "chamber")`

Also described in XEP-163 Step 2.3 - Use Presence [XEP-0163: Personal Eventing Protocol](https://xmpp.org/extensions/xep-0163.html#approach-presence)

Any idea what went wrong?

Thanks

**Comment by cromain** [comment]
Indeed... fixed now

**Comment by cromain** [comment]
Thanks for reporting this !

**Comment by Torxen** [comment]
Thanks
