### ISSUE TITLE
Documentation for mod_push

### ISSUE THREAD

**Issue by spacebat** [processone/ejabberd#2109]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu Linux 16,04

> How did you install ejabberd (source, package, distribution)?

Deb package from the processone website

> What did not work as expected? What was the expected result?

Example config for mod_push amounts to: mod_push: {}

There seems to be no documentation for it on the website. It is difficult to piece together how to use it, just going on the documentation of the deprecated 3rd party module of the same name, the XEP-0357 document, and the source code (I'm an erlang beginner).

Some documentation on its configuration on the website, and perhaps a blog post with contrived examples would be very helpful.

**Comment by Ghostw4lk** [comment]
Please see here, how to work with: https://github.com/processone/ejabberd/issues/2089

In my case I modified the mod_push.erl file to support the Firebase Push Service or APNS.

**Comment by spacebat** [comment]
I've had a good chat on freenode #jabberd about this and think I understand a fair bit more about the module. Perhaps the documentation for mod_push would just mention what role it plays in getting notifications to the app server. I had read XEP-0357 but I guess it did not sink in that this would be a server to server iq message stream.

**Comment by anujmiddha** [comment]
@spacebat As the documentation is still missing, can you please add an example here?

**Comment by weiss** [comment]
@anujmiddha, `mod_push` was written to support the push interfaces offered by third-party apps such as [Conversations][1] or [ChatSecure][2].  All you need to do to enable it is adding `mod_push: {}` to the list of modules (as [in the sample configuration file][3]), so there's not much to document.

The ejabberd Community Edition does *not* include support for generating FCM/APNS notifications directly.

[1]: https://conversations.im/
[2]: https://conversations.im/
[3]: https://github.com/processone/ejabberd/blob/18.03/ejabberd.yml.example#L792

**Comment by anujmiddha** [comment]
@weiss Thanks for your response. In my case however, I want to create a third party app similar to Conversations. I have a backend that is configured to send push notifications to my app. How would the ejabberd server notify my backend that it needs to send a push?

**Comment by zinid** [comment]
@anujmiddha as an option you can connect your app backend to ejabberd as a component (see XEP-0114). Then you should process "publish" events as described in XEP-0357.
This approach is actually server independent, you can use your push backend with any server software.

**Comment by weiss** [comment]
> There seems to be no documentation for it on the website.

`mod_push` and `mod_push_keepalive` are [documented][1] now.

[1]: https://docs.ejabberd.im/admin/configuration/#mod-push

**Comment by jithin-pits** [comment]
@anujmiddha  did you configured ejabberd server to notify your back end server.
