### ISSUE TITLE
Ejabberd 17.09 didnt work with Let's Encrypt 

### ISSUE THREAD

**Issue by skawz** [processone/ejabberd#2110]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

centOS 7 linux  3.10.0-693.2.2.el7.x86_64

> How did you install ejabberd (source, package, distribution)?

yum install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Certificate Let's Encrypt didn't work.
For getting certificate i use acme.sh v2.7.3
For installing i use instructions:
1 https://www.ejabberd.im/forum/28648/ejabberd-letsencrypt-ssl-certificate
2 https://blog.process-one.net/securing-ejabberd-with-tls-encryption/

Log message:
[warning] <0.1342.0>@ejabberd_pkix:mk_cert_state:240 certificate from /opt/ejabberd-17.09/conf/ssl/my.domain.com.pem is invalid: certificate is signed by unknown CA

Log message 2:
<0.7432.0>@ejabberd_s2s_in:handle_auth_failure:206 (tls|<0.7431.0>) Failed inbound s2s EXTERNAL authentication otherdomain.com -> my.domain.com (::FFFF:my IP): unable to get local issuer certificate

With 10 servers the same in logs. Messages not deliver from other domains to my.domain.com.

**Comment by zinid** [comment]
Did you put the whole certificate chain in your PEM file?
Also in centos you need to set 's2s_cafile' to point to your system CA bundle, something like:
```yaml
s2s_cafile: "/etc/ssl/certs/ca-bundle.pem"
```
You will still get the warning in this case, but at least s2s authentication will work

**Comment by skawz** [comment]
I try put to my.domain.com.pem:
1. Main Certificate + Intermediate certificate, chain certs + Private Key = Didn't work
2. Private Key + Fullchain = Didn't work

After your message i try define in ejabberd.yml in S2S GLOBAL OPTIONS
`s2s_cafile: "/opt/ejabberd-17.09/conf/ssl/my.domain.com.bundle.pem"`

But inbound s2s authentication didn't work.
Can you give me link to instruction to install Let's Encrypt on ejabberd on CentOS ?

**Comment by zinid** [comment]
@skawz installing Let's Encrypt certificate is not ejabberd specific. You should use `certbot` provided by the Let's Encrypt community.
