### ISSUE TITLE
XEP-0163 - owner did not receive any PEP notifications after initial presence stanza

### ISSUE THREAD

**Issue by Torxen** [processone/ejabberd#2112]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

CentOS Linux 7 (Core)

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

As described in [XEP-0163: Personal Eventing Protocol](https://xmpp.org/extensions/xep-0163.html) after publishing an event the owner should receive his own notifications on every resource even if the resource was offline. After the fix from yesterday [XEP-0163 - owner did not receive any PEP notifications](https://github.com/processone/ejabberd/issues/2108) (thanks for the quick turnaround) the owner only receives his notification if he is online. As described in in [XEP-163 - Notify Last](https://xmpp.org/extensions/xep-0163.html#notify-last) every new ressource of the owner should also get the notification, which is not working until now.

`As mentioned, a PEP service MUST send the last published item to all new subscribers and to all newly-available resources for each subscriber, including the account owner itself. `

Thanks

**Comment by cromain** [comment]
for PEP, we first need the client's CAPS. As we don't trigger pubsub last items on presence_probe, we may need an extra hook to be able to handle the PEP (with caps) case. Maybe caps_add hook will be needed to cover this case.
