### ISSUE TITLE
Can't connect through AWS Classic Load Balancer

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#2113]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I can't get clients to connect through elb. The http 5280 works fine with https termination with elb  but port 5222 (tcp) ssl terminated and then passed to the ec2 ejabberd instance with the same 5222 port.

There are no error logs too.

**Comment by zinid** [comment]
The info provided is cumbersome. Could you please elaborate?

**Comment by jjdp** [comment]
This is all I'm getting in gajim console

```
<!-- Out 11/17/2017 10:44:56 PM -->
<?xml version='1.0'?>
<stream:stream xmlns="jabber:client" to="mydomain.com" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xml:lang="en" >
```

Do note that i tried connecting directly to the instance and it works fine. I don't even know even know if logging supported in elb

**Comment by zinid** [comment]
Isn't this a problem of elb itself? I don't know what it is, but do you see traffic coming to ejabberd at all? If you don't, then elb is configured incorrectly.

**Comment by jjdp** [comment]
I can see traffic only through 5280. I don't know why ssl 5280 to (tcp 5280 or ssl 5280) ejabberd does not work.

**Comment by cromain** [comment]
not an ejabberd issue
