### ISSUE TITLE
TLS Connections per second

### ISSUE THREAD

**Issue by ghrst** [processone/ejabberd#2115]
> What version of ejabberd are you using?
17.0.1

> What operating system (version) are you using?
Debian Jessie

> How did you install ejabberd (source, package, distribution)?
Binary installer (package)

The problem that I have is that Ejabberd only accepts about **100 TLS connections per second**. I can not make it to accept more. Is it normal? Is there any configuration that can change this behavior? Or this is due to OS problems. The server that I am testing is a bare metal server with 20 CPUs (2 threads per core) and 64 GB of RAM.

**Comment by zinid** [comment]
Might be SYN-flood protection by the OS.

**Comment by ghrst** [comment]
I have set net.ipv4.tcp_max_syn_backlog to 1000000, so this problem should not happen.

**Comment by ghrst** [comment]
I found the problem. It was due to default backlog size of Ejabberd.

**Comment by zinid** [comment]
Good to know :smile:
