### ISSUE TITLE
mod_avatar fails to compile and crash the compilation.

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#2116]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

ubuntu

> How did you install ejabberd (source, package, distribution)?

from github tag 17.09

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

src/mod_avatar.erl:72: undefined macro 'NS_AVATAR_METADATA'
src/mod_avatar.erl:192: undefined macro 'NS_AVATAR_DATA'
src/mod_avatar.erl:225: undefined macro 'NS_AVATAR_METADATA'
src/mod_avatar.erl:255: undefined macro 'NS_AVATAR_METADATA'
src/mod_avatar.erl:29: function pubsub_publish_item/6 undefined
src/mod_avatar.erl:128: function publish_avatar/5 undefined
src/mod_avatar.erl:128: record avatar_meta undefined
src/mod_avatar.erl:135: function get_avatar_meta/1 undefined
src/mod_avatar.erl:139: record avatar_meta undefined
src/mod_avatar.erl:140: variable 'Info' is unbound
src/mod_avatar.erl:140: record avatar_info undefined
src/mod_avatar.erl:141: record avatar_info undefined
src/mod_avatar.erl:145: variable 'URL' is unbound
src/mod_avatar.erl:145: record avatar_info undefined
src/mod_avatar.erl:147: record avatar_meta undefined
src/mod_avatar.erl:148: function publish_avatar/5 undefined
src/mod_avatar.erl:151: function publish_avatar/5 undefined
src/mod_avatar.erl:151: record avatar_meta undefined
src/mod_avatar.erl:159: type avatar_info() undefined
src/mod_avatar.erl:162: record avatar_info undefined
src/mod_avatar.erl:164: variable 'URL' is unbound
src/mod_avatar.erl:164: record avatar_info undefined
src/mod_avatar.erl:166: record avatar_info undefined
src/mod_avatar.erl:168: record avatar_info undefined
src/mod_avatar.erl:169: variable 'MimeType' is unbound
src/mod_avatar.erl:182: record avatar_info undefined
src/mod_avatar.erl:187: spec for undefined function get_avatar_data/2
src/mod_avatar.erl:218: spec for undefined function get_avatar_meta/1
src/mod_avatar.erl:250: spec for undefined function publish_avatar/5
src/mod_avatar.erl:250: type avatar_meta() undefined
src/mod_avatar.erl:144: Warning: variable 'Info1' is unused
src/mod_avatar.erl:160: Warning: function get_meta_info/2 is unused
src/mod_avatar.erl:341: Warning: function set_vcard_avatar/3 is unused
src/mod_avatar.erl:357: Warning: function delete_vcard_avatar/1 is unused
src/mod_avatar.erl:361: Warning: function get_vcard/1 is unused
src/mod_avatar.erl:406: Warning: function decode_mime_type/1 is unused
could not compile dependency :ejabberd, "mix compile" failed. You can recompile this dependency with "mix deps.compile ejabberd", update it with "mix deps.update ejabberd" or clean it with "mix deps.clean ejabb

I get lots of warnings and undefs when compiling from mod_avatar and in the end the ejabberd fails to compile. Do I miss some dependency needed for mod_avatar ?

I use erlang/OTP 20.0 and elixir 1.5.0

**Comment by zinid** [comment]
`make distclean`
