### ISSUE TITLE
Use MongoDB with eJabberd

### ISSUE THREAD

**Issue by waqadeer** [processone/ejabberd#2119]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

CentOS 7 64-bit

> How did you install ejabberd (source, package, distribution)?

source

eJabberD works so cool! I want additionally connect MongoDB to put my user's information there using hooks, and that will be used by PHP as in Admin Panel.

Now, I need to connect MongoDB and tried https://github.com/comtihon/mongodb-erlang but no luck, as it is not building while eJabberD compilation.

I request to share any other possible solution OR any other suggestion for my problem?

Thanks for your time...

**Comment by waqadeer** [comment]
Can anybody update this issue? Thanks

**Comment by zinid** [comment]
The question is too broad. Adding mongodb support is a non-trivial task which cannot be described easily.

**Comment by cromain** [comment]
MongoDB backend is not implemented and we have no plans for this in short terms.
We're open to pull request for this.

**Comment by Neustradamus** [comment]
@waqadeer Have you found a solution for MongoDB?
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang

Linked to:
- https://github.com/processone/ejabberd/issues/419
- https://github.com/processone/ejabberd/issues/305
