### ISSUE TITLE
Best way to automatically set up a cluster

### ISSUE THREAD

**Issue by Root-man** [processone/ejabberd#2120]
> What version of ejabberd are you using?
16.08 CS

> What operating system (version) are you using?
Ubuntu Server 14.04

> How did you install ejabberd (source, package, distribution)?
Source

Hi,
More like a question, not an issue.
I'am trying to find the best way to automatically set up a ejabberd cluster and manage nodes going down.
So basically on each node I have a env. variable containing list of all nodes that should join the cluster, e.g. [ejabberd1@host1, ejabberd2@host2, ejabberd3@host3].
Since ejabberd_cluster.erl code doesn't prevent any failures rising from nodes trying to simultaneously join to each other, I assume I need to pick 1 node which will coordinate the cluster assembly - like ejabberd1@host1 performs join_cluster ejabberd2@host2, then join_cluster ejabberd3@host3, and so on, if there are more than 3 nodes. Is it possible to perform join_cluster from a node which is already in a cluster?

**Comment by cromain** [comment]
best it to make a new joining node call join_cluster itself only once, picking one of the running cluster node randomly as join_cluster parameter.
