### ISSUE TITLE
MUC error in ejabberd 17.11

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#2121]
When you update ejabberd 17.11 everything works fine, but if you change the theme of a room and restart ejabberd gives the following errors:

crash.log:

> 2017-11-23 23:06:07 =CRASH REPORT====
>   crasher:
>     initial call: mod_muc:init/1
>     pid: <0.4768.0>
>     registered_name: []
>     exception error: bad argument: [{erlang,iolist_to_binary,[[{text,<<>>,<<"Sala de temÃ¡tica libre. Os hallÃ¡is en el Reino de la Luz.">>}]],[]},{mod_muc,'-opts_to_binary/1-fun-2-',1,[{file,"src/mod_muc.erl"},{line,826}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{mod_muc_sql,'-get_rooms/2-fun-7-',4,[{file,"src/mod_muc_sql.erl"},{line,188}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{mod_muc,load_permanent_rooms,6,[{file,"src/mod_muc.erl"},{line,633}]}]
>     ancestors: [ejabberd_gen_mod_sup,ejabberd_sup,<0.66.0>]
>     message_queue_len: 0
>     messages: []
>     links: [<0.484.0>]
>     dictionary: []
>     trap_exit: true
>     status: running
>     heap_size: 75113
>     stack_size: 27
>     reductions: 1286243
>   neighbours:

error.log:  
> 2017-11-23 23:06:07.476 [error] <0.4768.0>@mod_muc:-opts_to_binary/1-fun-2-:826 CRASH REPORT Process <0.4768.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary([{text,<<>>,<<"Sala de temÃ¡tica libre. Os hallÃ¡is en el Reino de la Luz.">>}]) in mod_muc:'-opts_to_binary/1-fun-2-'/1 line 826
> 2017-11-23 23:06:07.477 [critical] <0.4675.0>@gen_mod:start_module:212 Problem starting the module mod_muc for host suchat.org 
>  options: [{host,<<"salas.suchat.org">>},
>            {access,[{allow,[all]}]},
>            {access_admin,[{allow,[{acl,admin}]}]},
>            {access_create,muc_create},
>            {access_persistent,muc_create},
>            {max_user_conferences,15}]
>  error: {error,
>             {{badarg,
>                  [{erlang,iolist_to_binary,
>                       [[{text,<<>>,
>                             <<"Sala de temÃ¡tica libre. Os hallÃ¡is en el Reino de la Luz.">>}]],
>                       []},
>                   {mod_muc,'-opts_to_binary/1-fun-2-',1,
>                       [{file,"src/mod_muc.erl"},{line,826}]},
>                   {lists,map,2,[{file,"lists.erl"},{line,1239}]},
>                   {lists,map,2,[{file,"lists.erl"},{line,1239}]},
>                   {mod_muc_sql,'-get_rooms/2-fun-7-',4,
>                       [{file,"src/mod_muc_sql.erl"},{line,188}]},
>                   {lists,map,2,[{file,"lists.erl"},{line,1239}]},
>                   {lists,map,2,[{file,"lists.erl"},{line,1239}]},
>                   {mod_muc,load_permanent_rooms,6,
>                       [{file,"src/mod_muc.erl"},{line,633}]}]},
>              {child,undefined,'mod_muc_suchat.org',
>                  {gen_server,start_link,
>                      [{local,'mod_muc_suchat.org'},
>                       mod_muc,
>                       [<<"suchat.org">>,
>                        [{host,<<"salas.suchat.org">>},
>                         {access,[{allow,[all]}]},
>                         {access_admin,[{allow,[{acl,admin}]}]},
>                         {access_create,muc_create},
>                         {access_persistent,muc_create},
>                         {max_user_conferences,15}]],
>                       []]},
>                  transient,60000,worker,
>                  [mod_muc]}}}
> [{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,203}]},
>  {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
>  {gen_mod,reload_modules,1,[{file,"src/gen_mod.erl"},{line,235}]},
>  {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
>  {ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,380}]},
>  {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
>  {ejabberd_ctl,call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,352}]},
>  {ejabberd_ctl,try_call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,321}]}]

**Comment by zinid** [comment]
Argh, the regression is introduced in #2099 via 11829906ac5a3145b862bd1bc55a088c1ad4fafb
