### ISSUE TITLE
pubsub#num_subscribers is always 0 in Pubsub node metadata 

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2122]
> What version of ejabberd are you using?
17.11

> What operating system (version) are you using?
Debian stable

> How did you install ejabberd (source, package, distribution)?
ProcessOne Debian packages

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

pubsub#num_subscribers is always equal to 0, it should return the numbers of actual subscribers to the node.
```xml
<field var='pubsub#num_subscribers' type='text-single' label='The number of subscribers to the node'><value>0</value></field>
```

**Comment by zinid** [comment]
Hehe :smile:

**Comment by cromain** [comment]
indeed i confirm, the test is not good... will fix this ASAP
