### ISSUE TITLE
mod_register_web: Include an external css file

### ISSUE THREAD

**Issue by zuglufttier** [processone/ejabberd#2124]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

FreeBSD 11

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The styling of the module is not possible without editing the source code. It would be nice if you could add support in the config for an external style sheet with an import rule: https://www.w3.org/TR/CSS21/cascade.html#at-import

**Comment by zinid** [comment]
This is now fixed in 17.11
