### ISSUE TITLE
Ban user with their IP in MUC.

### ISSUE THREAD

**Issue by kabirhaxor** [processone/ejabberd#2125]
> What version of ejabberd are you using?
Ejabberd 17.11

> What operating system (version) are you using?
Ubuntu 17.0

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Everything is fine. I just want to ask few questions only.

1. Is there any module to ban user and their IP in MUC
Like this: https://modules.prosody.im/mod_muc_ban_ip.html

2. Can i use reCaptcha in registeration page.?

3. How can i upload user's avatar to another image uploading website and get their user's avatar by using link.
Like this: http://avatar.nimbuzz.com/getAvatar?jid=killer@nimbuzz.com

And the uploading avatar url is: http://avatar.nimbuzz.com/setAvatar

Thank you.

**Comment by zinid** [comment]
1. No
2. No, you have to write your own registration page for this
3. I think server is irrelevant here, this is purely client feature: you just put your URL into `<URL/>` vCard element or inside avatar metadata PEP node. Note however that clients usually ignore URL avatars.

**Comment by kabirhaxor** [comment]
Thank you @zinid
