### ISSUE TITLE
Ejabberd source cide installation error

### ISSUE THREAD

**Issue by shubham1164** [processone/ejabberd#2126]
> What version of ejabberd are you using?

Ejabberd {vsn, "17.11.9"}
I have git clone the ejabberd source code from https://github.com/processone/ejabberd.git on 26 Nov. 2017. 

> What operating system (version) are you using?

Linux Mint 18.2 Cinnamon 64 bit (running in VMware 12)

> How did you install ejabberd (source, package, distribution)?

I am installing ejabberd from source code from https://github.com/processone/ejabberd.git

> What did not work as expected? Are there error messages in the log? What

I have installed erlang from "sudo apt-get install erlang". Erlang/OTP 18 is installed. After that
$ ./autoshen 
$ /configure --enable-user=ejabberd --enable-mysql
$ sudo make install
//here I am getting the following logs
////////////////////////////////////////////////////////////////////
ricky@ricky-vm ~/Desktop/ejabberd $ sudo make install
/usr/lib/erlang/bin/escript rebar compile && :> deps/.built
==> goldrush (compile)
==> lager (compile)
==> p1_utils (compile)
==> cache_tab (compile)
Compiling /home/ricky/Desktop/ejabberd/deps/cache_tab/c_src/ets_cache.c
In file included from /home/ricky/Desktop/ejabberd/deps/cache_tab/c_src/ets_cache.c:22:0:
/usr/lib/erlang/erts-7.3/include/erl_nif.h:69:20: fatal error: stdlib.h: No such file or directory
compilation terminated.
ERROR: compile failed while processing /home/ricky/Desktop/ejabberd/deps/cache_tab: rebar_abort
Makefile:100: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1
////////////////////////////////////////////////////////////////////

> was the unexpected behavior? What was the expected result?

ERROR: compile failed while processing /home/ricky/Desktop/ejabberd/deps/cache_tab: rebar_abort
Makefile:100: recipe for target 'deps/.built' failed
Error should not come

**Comment by shubham1164** [comment]
I have found th version of Ejabberd {vsn, "17.11.9"}

**Comment by zinid** [comment]
You don't have glibc headers installed in your system.

**Comment by shubham1164** [comment]
Thanks you made my day. Awesome bro keep helping.
