### ISSUE TITLE
export2sql result output

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#2134]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Debian 9

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I use Postgre and the last part to be moved from Mnesia is users' rosters. Is it possible to export them to SQL format?

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Well, the body of the issue got cleared and I can't edit it. Anyway, here is the question. 

I use Postgre and the last part to be moved from Mnesia is users' rosters. Is it possible to export them to SQL format?

**Comment by badlop** [comment]
Yes, simply run this command:
```
$ ejabberdctl export2sql localhost /tmp/aa.
```

And you will get a sql file with many tables, including:
```
--
-- Mnesia table: roster
--
delete from rosterusers where username='user1' and 0=0 and jid='user3@localhost';
INSERT INTO rosterusers(username, jid, nick, subscription, ask, askmessage, server, subscribe, type) VALUES ('user1', 'user3@localhost', 'user3', 'B', 'N', '', 'N', '', 'item');
delete from rostergroups where username='user1' and 0=0 and jid='user3@localhost';
--
```

I think, in your 17.09 version and older ones, you need to configure in mod_roster the option db_type: mnesia... or was it sql? Try both, one will work.

**Comment by zinid** [comment]
In recent ejabberd version no need to set preliminary `db_type: sql`: convert first, load the file into SQL, then change the `db_type` to `sql` and restart.

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Well, guys, I am aware of the `export2sql`, but I thought it didn't work for me. I called it like this: `sudo ejabberdctl export2sql mydomain.tld exported.sql`. The command didn't provide any output. I checked my current directory and haven't found `exported.sql` file. And today I realized the this file was actually created, but given the relative path, it for some reason was created in the `/var/lib/ejabberd` directory!

I have accidentally discovered it (and some huge Mnesia dump files, too) investigating why my `/var` got so big.

You guys probably should explicitly output some meaningful message after `export2sql`, `dump`, `dump_table` etc. commands have successfully exported the data.

**Comment by cromain** [comment]
you should not use sudo to run ejabberdctl. ejabberdctl is supposed to be run as low privilege user, likely 'ejabberd' user.
until you set absolute path, output file is relative to ejabberd's working directoty, which is set to /var/lib/ejabberd usually, so you get expected result.

@badlop maybe can we let export2sql output a result string on terminal, with absolute path of result and success/error ?

**Comment by badlop** [comment]
> Well, guys, I am aware of the export2sql, but I thought it didn't work for me. I called it like this: sudo ejabberdctl export2sql mydomain.tld exported.sql. The command didn't provide any output.

It returned no explicit error message, which is a first symptom of success.

>  I checked my current directory and haven't found exported.sql file. 

Consider that this command can be called using ejabberdctl, but also XML-RPC, ReST, from the WebAdmin.... Obviously, "my current directory" is not an acceptable path for that or any other command. Better you provide full path to ejabberdctl, to ensure it uses what you want it to use.

> And today I realized the this file was actually created, but given the relative path, it for some reason was created in the /var/lib/ejabberd directory!

Right, it was created in the spool dir, where database files, and mnesia crash dumps, and other DB files are created. Its location is not arbitrary, it is set:
```
$ ejabberdctl help
...
Optional parameters when starting an ejabberd node:
  --config-dir dir   Config ejabberd:    /etc/ejabberd
  --config file      Config ejabberd:    /etc/ejabberd/ejabberd.yml
  --ctl-config file  Config ejabberdctl: /etc/ejabberd/ejabberdctl.cfg
  --logs dir         Directory for logs: /usr/local/var/log/ejabberd
  --spool dir        Database spool dir: /usr/local/var/lib/ejabberd
  --node nodename    ejabberd node name: ejabberd@localhost
```

> @badlop maybe can we let export2sql output a result string on terminal, with absolute path of result and success/error ?

Commands that return no explicit message, do at least leave the success state:
```
$ ejabberdctl export2sql localhost aaa.sql
$ echo $?
0
```
