### ISSUE TITLE
filter_packet hook

### ISSUE THREAD

**Issue by skhaz** [processone/ejabberd#2135]
> What version of ejabberd are you using?

lastest (from the master branch)

> What operating system (version) are you using?

macOS 10.12.6

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am wondering if the filter_packet hook signature was changed, I was following this [article](https://blog.process-one.net/ejabberd-with-elixir-packet-filters/) to create a simple hook in Elixir, but the code seems that doesn't work anymore.

```elixir
defmodule PacketFilter do
  import Ejabberd.Logger
  @behaviour :gen_mod
  def start(_host, _opts) do
    info('Starting ejabberd module Filter Packet Demo')
    Ejabberd.Hooks.add(:filter_packet, :global, __ENV__.module, :on_filter_packet, 50)
    :ok
  end

  def stop(_host) do
    info('Stopping ejabberd module Filter Packet Demo')
    Ejabberd.Hooks.delete(:filter_packet, :global, __ENV__.module, :on_filter_packet, 50)
    :ok
  end

  def on_filter_packet({from, to, xml={:xmlel, "message", attributes, children}} = packet) do
     # This hook is never called.
    # What I want only packets of type `message` here.

    info("on_filter_packet [1] #{inspect packet}")
    packet
  end

  def on_filter_packet(packet) do
    # Always called, without this hook, the ejabberd throws a lot of erros.
    info("on_filter_packet [2] #{inspect packet}")
    packet
  end

end
```

**Comment by zinid** [comment]
Well, yes, and the change is almost one year old.

**Comment by badlop** [comment]
Right. Instead of: {From, To, Packet}, now the argument is simply: Packet

This change was introduced around ejabberd 17.03: https://github.com/processone/ejabberd/commit/8b2d3084986defd6045a0c02706415e0e7ae4b3f#diff-b81e1bd5c308d13a2065da751c70b882L258

**Comment by skhaz** [comment]
Thanks!
