### ISSUE TITLE
mod_muc with millions of persistent rooms created daily

### ISSUE THREAD

**Issue by dlameri** [processone/ejabberd#2136]
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
As a dependency

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Perhaps I'm using ejabberd wrongly, but my use case is: Two users can have many chats with one another, it's one chat by every two users and a product that is being sold.

The problem is, we have 1 million of this chats created daily and we need this chat history for a very long time (maybe a year). This makes table muc_room increase indefinitely.

Every time I create a new instance, mod_muc executes the function load_permanent_room that executes a "select *" on muc_room, to store it on mnesia or on SQL DB. If I store it all in memory, the server dies out of memory, if I set it to SQL DB it takes hours to run.

Even if load_permanent_room was optional, it wouldn't solve the problem, since every single aspect of MUC interaction needs the room to be considered online.

Is there a way to solve this problem or am I trying to use ejabberd for something that it was not meant to do?

**Comment by zinid** [comment]
Not currently, alas.
`mod_muc` is gonna be refactored, there is even related Github issue.

**Comment by dlameri** [comment]
This refactoring will probably take a while, right?

Maybe I'll need another open source or make my own chat server =/

**Comment by dlameri** [comment]
I haven't found the related issue. Which one is it?

Can I help in any way?

**Comment by badlop** [comment]
I can't find such issue either, maybe that refactoring was mentioned as a comment in another issue, and the github search doesn't find it.

Regarding the original question: chatrooms are expected to be used. Once a conversation between three accounts can be _considered_ finished, that room can be destroyed, right? The only that should remain days, months and years after that is the room log (toallow checking it later in case of necessity).

And, in the rare case of requiring to continue that same conversation between those three exact users many time after it was considered finished... the room can be created again, maybe with a link to the old logs.

If you keep logs for one year, and destroy rooms that are inactive after 7 days, maybe mod_muc could handle the amount of rooms: that would be 7 millions + the ones that remain active more than a day.

**Comment by dlameri** [comment]
Thanks for the suggestion, but when i call :mod_muc_admin.destroy_room("roomName", "conference.host") it deletes all messages from that room.

Is there a different way to destroy a room without losing the content of "archive" table related to it?

**Comment by dlameri** [comment]
I tested creating room with option "persistent:false" and when i call destroy it keeps everything on my database, as you mentioned
