### ISSUE TITLE
Parent element from one namespace child namespace from another

### ISSUE THREAD

**Issue by mkearn** [processone/ejabberd#2137]
> What version of ejabberd are you using?

15.07.40

> What operating system (version) are you using?

Windows Server 2012

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? 

Unmarshalling of XML on switchover
> Are there error messages in the log?

No
 
> What was the unexpected behavior?

Expected to be able to use Java to simply unmarshall the data received but this is not the case due to XML namespace.
The parent element namespace is QUALIFIED but the child element namespace is UNQUALIFIED
Java unmarshaller ignores the child elements is not namespace-qualified.

fin xmlns='urn:xmpp:mam:0' queryid='f27' complete='true'>
set xmlns='http://jabber.org/protocol/rsm'>

> What was the expected result?

To have the namespace QUALIFIED.

**Comment by zinid** [comment]
Shitty parser detected.
Using namespace prefixes is not recommended by the XMPP community, for the record.

**Comment by mkearn** [comment]
Thank you for your quick response!
In response to your close reason why are the namespaces different? We are receiving this from ejabberd.
1) Can these namespaces be configured to the same namespace?
2) As you state "namespace prefixes is not recommended by the XMPP community", how can this be configured to have no namespaces?

**Comment by zinid** [comment]
I don't understand the question. You cannot configure namespaces in XMPP, they are predefined by the standards. Or what do you mean? Configure what exactly?

**Comment by mkearn** [comment]
In ejabberd how can these namespaces be configured?
You have said that namespace prefix are not recommended, is it possible to configure ejabberd so namespace prefix are the same or can ejabberd be configured to send no namespace prefix?
