### ISSUE TITLE
mod_avatar disabled in binary installers

### ISSUE THREAD

**Issue by ChaosKid42** [processone/ejabberd#2140]
> What version of ejabberd are you using?

ejabberd Community Server 17.11

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Linux x86 64-bits RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Cannot activate mod_avatar.

Log file shows:

2017-12-02 16:54:03.792 [critical] <0.316.0>@mod_avatar:start:50 ejabberd is built without graphics support: reconfigure it with --enable-graphics or disable 'mod_avatar'

This worked in 17.09

**Comment by badlop** [comment]
I get that same error with 17.11 Linux x86 64-bits Package, in Debian.

**Comment by zinid** [comment]
Because ejabberd is not built with `mod_avatar` support, because there was a lot of pain. We shall improve it.

**Comment by cromain** [comment]
our installers won't include graphics support until it's improved, depending on less libraries and let ejabberd start without libX11 installed. Until then if you need mod_avatar, you have to compile from sources.

**Comment by cromain** [comment]
For the record, this is now enabled in our latest container: https://hub.docker.com/r/ejabberd/ecs/

**Comment by cromain** [comment]
installer now configured with mod_avatar
