### ISSUE TITLE
could not start inotifywait.exe on Windows installer

### ISSUE THREAD

**Issue by shyamsshingare** [processone/ejabberd#2142]
inotifywait.exe - this application could not be started

**Comment by cromain** [comment]
you likely miss csc.exe compiler from Microsoft.NET framework, which is used in dependency 'fs' to build inotifywait.exe

**Comment by cromain** [comment]
do you build from sources, or use our windows installer ?

**Comment by shyamsshingare** [comment]
using Windows installer.
and csc.exe exist in .net framework.
please help

**Comment by cromain** [comment]
the executable is included in lib/fs-2.12.0/priv/inotifywait.exe

**Comment by Subnum12** [comment]
check here: there is a workaround:
https://www.ejabberd.im/forum/29719/windows-2012-and-1711-problems

**Comment by cromain** [comment]
yep this confirms what i suspected, we'll have to re-compile the .exe

**Comment by shyamsshingare** [comment]
i can't understand anything please tell in easy way...

**Comment by Subnum12** [comment]
replace inotifywait.exe by this: [http://www95.zippyshare.com/d/AWMvbo3B/39829/inotifywait.exe](url)

**Comment by shyamsshingare** [comment]
after replacing inotifywait.exe, inotifywait.exe problem solved. but after starting ejjaberd it says error occurred....
please check your configuration and your installation

**Comment by RahulRawat95** [comment]
Same here after compiling the source code into inotifywait.exe and replacing it says....
please check your configuration and your installation

**Comment by cromain** [comment]
do you have something in ejabberd.log ?

**Comment by cromain** [comment]
Fixed inotifywait.exe is now part of our packaging and will be included in 17.12.
With new exe, ejabberd starts and run as expected.
