### ISSUE TITLE
Result Set Management (XEP-0059) - Use Case: PubSub - Returning All Items

### ISSUE THREAD

**Issue by ejbravo** [processone/ejabberd#2143]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

I have noticed in the last version that requesting all items from a Pubsub node has been modified. Whereas in the previous versions the service returned all available items at the same request, now the items are returned truncated including an RSM notation as described in the [XEP-0060](https://xmpp.org/extensions/xep-0060.html#subscriber-retrieve-requestall)

Incorporating **Result Set Management** protocol ([XEP-0059](https://xmpp.org/extensions/xep-0059.html)) is a good advance (thank you). However, I am having some problems in order to implement it successfully and I am still not able to get any result. The only message I receive is 

> No module is handling this query

- [ ] What is necessary to implement this new feature? Do I have to amend Ejabberd configuration?
 _ejabberd.yml_ file? I have not found anything about this issue on [ejabbberd documentation](https://docs.ejabberd.im/admin/configuration). 

- [ ] I have checked support as [it is described in the XEP](https://xmpp.org/extensions/xep-0059.html#support) receiving the next results:

```
<feature var='http://jabber.org/protocol/commands'/>
<feature var='http://jabber.org/protocol/disco#info'/>
<feature var='http://jabber.org/protocol/disco#items'/>
<feature var='http://jabber.org/protocol/offline'/>
<feature var='http://jabber.org/protocol/pubsub'/>
<feature var='http://jabber.org/protocol/pubsub#access-authorize'/>
<feature var='http://jabber.org/protocol/pubsub#access-open'/>
<feature var='http://jabber.org/protocol/pubsub#access-presence'/>
<feature var='http://jabber.org/protocol/pubsub#access-whitelist'/>
<feature var='http://jabber.org/protocol/pubsub#auto-create'/>
<feature var='http://jabber.org/protocol/pubsub#auto-subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#collections'/>
<feature var='http://jabber.org/protocol/pubsub#config-node'/>
<feature var='http://jabber.org/protocol/pubsub#create-and-configure'/>
<feature var='http://jabber.org/protocol/pubsub#create-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#delete-items'/>
<feature var='http://jabber.org/protocol/pubsub#delete-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#filtered-notifications'/>
<feature var='http://jabber.org/protocol/pubsub#get-pending'/>
<feature var='http://jabber.org/protocol/pubsub#instant-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#item-ids'/>
<feature var='http://jabber.org/protocol/pubsub#last-published'/>
<feature var='http://jabber.org/protocol/pubsub#manage-subscriptions'/>
<feature var='http://jabber.org/protocol/pubsub#member-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#modify-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#outcast-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#persistent-items'/>
<feature var='http://jabber.org/protocol/pubsub#presence-notifications'/>
<feature var='http://jabber.org/protocol/pubsub#presence-subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#publish'/>
<feature var='http://jabber.org/protocol/pubsub#publish-only-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#publisher-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#purge-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#retract-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-default'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-subscriptions'/>
<feature var='http://jabber.org/protocol/pubsub#shim'/>
<feature var='http://jabber.org/protocol/pubsub#subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#subscription-notifications'/>
<feature var='iq'/>
<feature var='jabber:iq:last'/>
<feature var='jabber:iq:privacy'/>
<feature var='jabber:iq:register'/>
<feature var='jabber:iq:version'/>
<feature var='msgoffline'/>
<feature var='presence'/>
<feature var='urn:xmpp:blocking'/>
<feature var='urn:xmpp:carbons:2'/>
<feature var='urn:xmpp:ping'/>
<feature var='vcard-temp'/>
```

As you can see, I do not have the expected 
`<feature var='http://jabber.org/protocol/rsm'/>`
It makes no sense to me because I receive truncated items now. How is that possible?

I appreciate your help. Thank you in advance.

**Comment by cromain** [comment]
rsm is returned when quering disco info on pubsub service, as long as you are using an sql backend. (pubsub does not use rsm with mnesia)
```
...
<feature var="http://jabber.org/protocol/pubsub#retrieve-items"/>
<feature var="http://jabber.org/protocol/pubsub#retrieve-subscriptions"/>
<feature var="http://jabber.org/protocol/rsm"/>
<feature var="http://jabber.org/protocol/pubsub#shim"/>
<feature var="http://jabber.org/protocol/pubsub#subscribe"/>
...
```

requesting a page of items is just about adding rsm elements to your pubsub iq.

**Comment by ejbravo** [comment]
Thanks for your response. However, I am not sure if I understood it, I am still confused about this issue.

I do not use SQL backend. Actually, I have worked with Mnesia since I knew Ejabberd and it was only after updating to 17.11 from 17.01 when PubSub service begun to retrieve a paged result when the items were more than 10.
I can show you an example of my results.

- Result Stanza when there is an only one item:

`Element {
  name: "pubsub",
  parent:
   Stanza {
     name: "iq",
     parent: null,
     children: [ [Circular] ],
     attrs:
      { "xml:lang": "en",
        to: "alice@wonderland/A",
        from: "pubsub.wonderland",
        type: "result",
        id: "get.node.items",
        "xmlns:stream": "http://etherx.jabber.org/streams" } },
  children:
   [ Element {
       name: "items",
       parent: [Circular],
       children: [Object],
       attrs: [Object] } ],
  attrs: { xmlns: "http://jabber.org/protocol/pubsub" } }`


- Result Stanza when there are more than 10 items:

 `Element {
  name: "pubsub",
  parent:
   Stanza {
     name: "iq",
     parent: null,
     children: [ [Circular] ],
     attrs:
      { "xml:lang": "en",
        to: "alice@wonderland/A",
        from: "pubsub.wonderland",
        type: "result",
        id: "get.node.items",
        "xmlns:stream": "http://etherx.jabber.org/streams" } },
  children:
   [ Element {
       name: "set",
       parent: [Circular],
       children: [Object],
       attrs: [Object] },
     Element {
       name: "items",
       parent: [Circular],
       children: [Object],
       attrs: [Object] } ],
  attrs: { xmlns: "http://jabber.org/protocol/pubsub" } }`

As you can see in the second stanza, there is a 'SET' element (described in rsm protocol) and just ten result within 'items' element
`    set:
   { index: "0",
     count: "11",
     first: "2017-12-22T09:57:20.997759Z",
     last: "2017-12-22T09:57:21.741937Z" }`


Moreover, about your affirmation 
> pubsub does not use rsm with mnesia 

I read on your blog ([post about ejabberd 17.09](https://blog.process-one.net/ejabberd-17-09/)) the opposite information:

PubSub
> Add RSM support on mnesia

So, could you clarify how this new feature works? What do I have to change on Ejabberd configuration in order to get rsm feature?

Thanks in advance.
