### ISSUE TITLE
How to build from source for Windows

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#2144]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
Deb

> How did you install ejabberd (source, package, distribution)?
Source

How to build from source for Windows OS ?

**Comment by mremond** [comment]
You have two options: Crosscompile from Linux or try modifying ejabberd build chain to compile on Visual Studio. However, I think you are on your own. If you want to contribute documentation, you are welcome to open a PR on the doc.

Thanks !

**Comment by nOmi7** [comment]
So how is the existing Windows installer binary created ?

**Comment by mremond** [comment]
Windows installer is created by cross compilation.
