### ISSUE TITLE
PuSH breaks with mobile clients after sometime

### ISSUE THREAD

**Issue by mitchellurgero** [processone/ejabberd#2146]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Package(deb download from site)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Push works while the client app runs in the background but after it sits for sometime push breaks. This happens on Android and iOS clients.

The reason I am posting here and not on the app(s) github(s) is because it happens to all apps I use.
After quick research it seems that this is caused because client/server bits in SSL certificate??

Can someone help me debug this problem?

**Comment by weiss** [comment]
Enable debug output (`ejabberdctl set-loglevel 5`), wait until you failed to receive a notification, then `grep mod_push ejabberd.log`.

> SSL certificate

You can check this on https://check.messaging.org/ (select `s2s` from the drop-down on the right).

**Comment by mitchellurgero** [comment]
@weiss 
check.messaging.org is not reachable for me.

Any how, I checked logs and there are no errors for mod_push. Can you please show me an example configuration on using mod_push?

Right now I have a pubsub node for it and ```mod_push: []``` in the config hoping default values would work, but maybe it needs more...?

**Comment by weiss** [comment]
> check.messaging.org is not reachable for me.

I'm sorry, https://check.messaging.one/ ...

> Any how, I checked logs and there are no errors for mod_push.

I told you how to enable debug output.

> Right now I have a pubsub node for it

What?  See https://github.com/processone/ejabberd/issues/2089#issuecomment-342263378 if your goal is to generate APNS/FCM notifications.  `mod_push` won't do that.

**Comment by mitchellurgero** [comment]
So this is an issue with the mobile app I am using??

**Comment by weiss** [comment]
> So this is an issue with the mobile app I am using??

"My car is broken, what's the problem?"

**Comment by mitchellurgero** [comment]
I mean no reason to be rude.. it’s a simple question. Thanks for the help.
