### ISSUE TITLE
Crash when start ejabberd 17.11

### ISSUE THREAD

**Issue by jefryjacky** [processone/ejabberd#2148]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

MacOS High Sierra 10.13.1 (17B1003)

> How did you install ejabberd (source, package, distribution)?

I install from https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.11/ejabberd-17.11-osx-installer.app.zip

> What did not work as expected? Are there error messages in the log? What

not able to start ejabberd,
here is the crash log, 
[crash.log](https://github.com/processone/ejabberd/files/1538264/crash.log)

> was the unexpected behavior? What was the expected result?

unexpected behaviour: not able to start ejabberd
expected result: able to start ejabberd

**Comment by cromain** [comment]
see #2025
binary installer will be fixed once Erlang 20.2 is released.

**Comment by cromain** [comment]
17.12 installer will use OTP 20.2

**Comment by jefryjacky** [comment]
Hi @cromain , I am using ejabberd 18.03 now, but still crashing. below is the crash.log

[crash.log](https://github.com/processone/ejabberd/files/1928802/crash.log)
