### ISSUE TITLE
Handling stopped return value in running hooks

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [processone/ejabberd#2149]
Why you did not handle `'stopped'` return value for running hooks?  
For example instead of [**This**](https://github.com/processone/ejabberd/blob/master/src/ejabberd_c2s.erl#L427), Can we have following?
```erlang

handle_stream_end(Reason, #{lserver := LServer} = State) ->
    State1 = State#{stop_reason => Reason},
    case ejabberd_hooks:run_fold(c2s_closed, LServer, State1, [Reason]) of
        stopped ->
            State1;
        State2 ->
            State2
    end.
```

**Comment by zinid** [comment]
What's the point in this code? What is the goal?

**Comment by zinid** [comment]
If you want to terminate c2s process brutally (without losing current state), you can call `ejabberd_c2s:stop(State)`.

**Comment by prefiks** [comment]
You can also return {stop, NewValue} from hook to stop processing with NewValue as a result

**Comment by zinid** [comment]
@prefiks indeed

**Comment by Pouriya-Jahanbakhsh** [comment]
According to the documentation of `ejabberd_hooks`, hook callback can return `stop` and `run_fold` function will return `stopped` after seeing `stop`.  
for example if i use `c2s_filter_send` hook and define callback like bellow:
```erlang

c2s_filter_send(Args) ->
    case SomeThing of
        Val1 ->
            stop;
        _ ->
            {Pkt, State}
    end.

```
in (**Here**)[https://github.com/processone/ejabberd/blob/master/src/ejabberd_c2s.erl#L139] we have case_clause error!  We don't have these errors if we handle this possible return value of `run_fold`.

**Comment by Pouriya-Jahanbakhsh** [comment]
And i'm asking why you did not handle this return value? Because of you know you don't want to use `'stop'` in other codes for this hook?

**Comment by zinid** [comment]
Just register the hook with lower sequence number and return `{stop, State}` from it.

**Comment by prefiks** [comment]
Accepted data is set is defined in a per hook basis, this one accept only c2s state records, if you really want to stop with value use {stop, Soemthing}. In general we expect hooks to return something sane, if it returns something unexpect that causes problems we will blame hook authror ;)
