### ISSUE TITLE
Optimizing ejabberd 17.09 and linux kernel

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#2153]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Installer

Currently the box is not yet benchmarked but I just wanted to know what are the recommened flags I can set. Currently I have these in my aws m4.large box:

```
/etc/security/limits.d/custom.conf:

root soft nofile 200000
* soft nofile 200000
```

```
/etc/sysctl.conf
net.ipv4.netfilter.ip_conntrack_max = 200000
net.nf_conntrack_max = 200000
```

The hard limits I checked and its way above I wanted and I didn't set them. Same for fs.file-max and fs.nr_open.

Also on the systemd ejabberd.service I have set LimitNOFILE=200000 and in ejabberdctl.cfg i set 
ERL_MAX_PORTS=100000 since It's two to three times per port?

I'm not sure about ERL_PROCESSES

Do I also need to edit something in ejabberd.yml?

**Comment by cromain** [comment]
default settings are good for most cases and are the recommended flags. until to handle more than 100k online users, you don't need to tune anything.
