### ISSUE TITLE
WSL - /opt/bitrock/ejabberd-17.11-0/helperBinary unterminated quoted string

### ISSUE THREAD

**Issue by fenchu** [processone/ejabberd#2154]
> What version of ejabberd are you using?

`wget "https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.11/ejabberd_17.11-0_amd64.deb" -O ejabberd_17.11-0_amd64.deb`

[WSL bug](https://github.com/Microsoft/WSL/issues/2736)

> What operating system (version) are you using?

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
Linux MB-PC 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Works fine on a regular ubuntu 16.04LTS, so this is probably WSL 

> How did you install ejabberd (source, package, distribution)?

```
# dpkg -i ejabberd_17.11-0_amd64.deb
Velger den tidligere bortvalgte pakka «ejabberd».
(Leser database ... 43697 filer og kataloger er for øyeblikket installerte.)
Preparing to unpack ejabberd_17.11-0_amd64.deb ...
Unpacking ejabberd (17.11-0) ...
dpkg: advarsel: klarte ikke slette den gamle mappa «/var/log/ejabberd»: Mappa er ikke tom
dpkg: advarsel: klarte ikke slette den gamle mappa «/var/lib/ejabberd»: Mappa er ikke tom
dpkg: advarsel: klarte ikke slette den gamle mappa «/etc/ejabberd/modules.d»: Mappa er ikke tom
dpkg: advarsel: klarte ikke slette den gamle mappa «/etc/ejabberd»: Mappa er ikke tom
Setter opp ejabberd (17.11-0) ...
/opt/bitrock/ejabberd-17.11-0/helperBinary: 2: /opt/bitrock/ejabberd-17.11-0/helperBinary: Syntax error: Unterminated quoted string
```
ls -l /opt/bitrock/ejabberd-17.11-0/helperBinary
-rwxr-xr-x 1 1003 1003 5417575 jan.  20  2017 /opt/bitrock/ejabberd-17.11-0/helperBinary
sudo /opt/bitrock/ejabberd-17.11-0/helperBinary
-su: /opt/bitrock/ejabberd-17.11-0/helperBinary: klarte ikke å kjøre binærfil: Ugyldig format på eksekverbar fil (Translated illegal format on executable)

**Comment by cromain** [comment]
The .deb we provide are to be used under Linux. Never tested on WSL which is not a supported target.
Is any linux package supposed to run without recompilation here ?

**Comment by cromain** [comment]
issue identified on WSL side: https://github.com/Microsoft/WSL/issues/1884
fix is being worked on.
