### ISSUE TITLE
Problem starting the module mod_log_chat for host localhost 

### ISSUE THREAD

**Issue by pratikshivlab** [processone/ejabberd#2155]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Ubuntu 16.04

after install mod_log_chat using module_install ejabberd is not started.

**Comment by badlop** [comment]
mod_log_chat was updated some months ago: "Update to work with ejabberd 17.06". Did you run "ejabberdctl modules_update_specs?

It starts for me correctly using ejabberd 17.11. There were some fixes in ext_mod.erl since 17.04, maybe some of them fixes your problem.

**Comment by pratikshivlab** [comment]
thank you badlop now we will start to work with 17.11 latest version.
