### ISSUE TITLE
How to make voice call in ejabberd. Which module is needed.

### ISSUE THREAD

**Issue by kabirhaxor** [processone/ejabberd#2156]
> What version of ejabberd are you using?

Ejabberd 17.11

> What operating system (version) are you using?

Ubuntu 17

> How did you install ejabberd (source, package, distribution)?

Run Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hello,
I want to know how to make client to client voice call through client in ejabberd.
Which module is needed and from where i get that module. And one more question is how to use Rest API through OAuth token. OAuth need jid and password to generate token but when im using register new account API with OAuth token then how can a i use jid and password. IF a user run register commands it means that user don't have an account then how can he/she generate token by using credentials. Any simple way to generate token without jid and password and use that token in API.

Thank you very much.

**Comment by kabirhaxor** [comment]
No one here to answer this question?

**Comment by zinid** [comment]
VoIP in XMPP (aka "Jingle") is a client specific feature. The only exception is that STUN/TURN server is needed sometimes, and ejabberd provides one. Refer to the documentation on how to configure this STUN/TURN thingy. Another way to utilize VoIP with ejabberd is to use SIP (there is `mod_sip` in ejabberd, see the docs).

Regarding your question about OAuth: dunno, you're better off creating a separate issue, maybe somebody will answer.
