### ISSUE TITLE
Offline pictures and word/pdf files in ejabberd server 

### ISSUE THREAD

**Issue by hibazubair162** [processone/ejabberd#2161]
> What version of Ejabberd are you using?

ejabberd 17

> What operating system (version) are you using?

Ubuntu 

> How did you install ejabberd (source, package, distribution)?
Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am testing ejabbered server. I am having issue regarding that i cannot see offline picture and word/pdf file messages saved inside ejabbered server while other chats are visible. Why is it so?

**Comment by zinid** [comment]
How are we supposed to help when the question is "stuff doesn't work"? Config, errors from logs (if any), what clients are used, etc.

**Comment by thundergreen** [comment]
Because your client doesn't support this?

**Comment by hibazubair162** [comment]
client? can u explain plz? or u can share any link so that i got
understanding for this please

**Comment by hibazubair162** [comment]
client is xmpp. Can u tell in this scenerio where i have xmpp
server/ejabbered and xmpp client.
How voice and file transfer would work? is xmpp server involved in this
condition?or there is a direct transfer?
