### ISSUE TITLE
mod_register_web customizable create/delete/change password pages.

### ISSUE THREAD

**Issue by andrew-vant** [processone/ejabberd#2163]
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I would like to replace the create/delete/change password pages with my own versions, and can't figure out how to tell mod_register_web to do that, or if it's possible.

**Comment by badlop** [comment]
Your possibilities are:
* edit mod_register_web.erl,
* modify register.css,
* write your own page that uses XML-RPC or ReST to run ejabberd commands
* write your own webpage that uses XMPP to perform registrations
