### ISSUE TITLE
how to store chat history in xml format ?

### ISSUE THREAD

**Issue by pratikshivlab** [processone/ejabberd#2165]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Ubuntu 16.04

i want to store chat in log file in XML format.
i have already store history using mod_log_chat but it stored in html or text format.

**Comment by badlop** [comment]
Try mod_logxml. Other than that, I am not aware of anything else.

**Comment by pratikshivlab** [comment]
That i have installed but it gives logs about ejabberd setting like stanza etc, not gives chat history.

**Comment by badlop** [comment]
Then it isn't possible, unless you edit mod_log_chat to produce XML instead of HTML.
