### ISSUE TITLE
call to undefined function oauth2:authorize_password

### ISSUE THREAD

**Issue by Kulkow** [processone/ejabberd#2166]
> What version of ejabberd are you using?

16.09-4

> What operating system (version) are you using?
 debian stretch

> How did you install ejabberd (source, package, distribution)?
  apt-get install ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
      "/register": mod_register_web
      "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: true
    captcha: true
    tls: true
    certfile: "/etc/ejabberd/ejabberd.pem"

https://127.0.0.1:5280/oauth/authorization_token enter login and password, and submit. (500 Error)
[error] <0.506.0> CRASH REPORT Process <0.506.0> with 0 neighbours crashed with reason: call to undefined function oauth2:authorize_password({<<"admin">>,<<"localhost">>}, <<>>, <<>>, [], {

**Comment by cromain** [comment]
there is something wrong with your installation. oauth2:authorize_password is provided by dependency p1_oauth2, which is part of the distribution.

**Comment by cromain** [comment]
you should contact the debian packager. p1_oauth2 must be included in the package, or defined as a dependency.

**Comment by zinid** [comment]
Try to install ejabberd from sid, some guys are using it and don't face the problem you see.

**Comment by zinid** [comment]
OK, the maintainer said you need to install `p1-oauth` explicitly.

**Comment by Kulkow** [comment]
Thank you 
apt-get install erlang-p1-oauth2
