### ISSUE TITLE
lager_file_backend dropped XX messages

### ISSUE THREAD

**Issue by jjdp** [processone/ejabberd#2168]
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Benchmarking our pre production servers with about 5000 chats/s with tsung, I'm getting a` [warning]  lager_file_backend dropped 49 messages in the last second that exceeded the limit of 100 messages/sec`.

What does this mean? Is the instance or the RDS (mysql) at fault? How do you remedy this?

**Comment by prefiks** [comment]
No it's perfectly normal, we made logging library limit number of processed messages to 100 per second, your test just made it generate more messages than that so you get this warning message.

**Comment by zinid** [comment]
See also `log_rate_limit` option from [the doc](https://docs.ejabberd.im/admin/configuration/#logging)
