### ISSUE TITLE
Some MUC subscription nodes are ignored in 17.11

### ISSUE THREAD

**Issue by spacebat** [processone/ejabberd#2169]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Linux Mint 18

> How did you install ejabberd (source, package, distribution)?

DEB package from processone website

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Subscribing to a MUC room fails for some of the nodes that were returned as successfully subscribed, in particular it only works for the first node or two. I have not seen anything unusual in the log, except the absence of expected mucsub stanzas being sent.

I have tracked it down somewhat by observing the values written to the nodes field of the sql table muc_room_subscribers. We use postgresql 9.6.

If I subscribe a user to a room like so, with the node order being messages, presence, affiliations, subscribers:

```
/opt/ejabberd-17.11/bin/ejabberdctl subscribe_room devchat conference.localhost meep@localhost urn:xmpp:mucsub:nodes:messages:urn:xmpp:mucsub:nodes:presence,urn:xmpp:mucsub:nodes:affiliations,urn:xmpp:mucsub:nodes:subscribers
```
The nodes field for that user's subscription in the database looks like the following. Note the newlines after presence and affiliations. In this case, we get mucsub notifications for messages and presence but not affiliations or subscribers.

```
[<<"urn:xmpp:mucsub:nodes:messages">>,<<"urn:xmpp:mucsub:nodes:presence">>,
 <<"urn:xmpp:mucsub:nodes:affiliations">>,                                 
 <<"urn:xmpp:mucsub:nodes:subscribers">>]
```

If I change the order so that affiliations comes first, the word wrapping in the serialized value changes, and we can then get affiliation mucsub notifications, but don't get them for the other nodes.

```
/opt/ejabberd-17.11/bin/ejabberdctl subscribe_room devchat conference.localhost meep@localhost urn:xmpp:mucsub:nodes:affiliations,urn:xmpp:mucsub:nodes:messages:urn:xmpp:mucsub:nodes:presence,urn:xmpp:mucsub:nodes:subscribers
```
```
[<<"urn:xmpp:mucsub:nodes:affiliations">>,
 <<"urn:xmpp:mucsub:nodes:messages">>,<<"urn:xmpp:mucsub:nodes:presence">>,
 <<"urn:xmpp:mucsub:nodes:subscribers">>]
```

It appears that the newlines in the serialized node list are causing a problem, preventing subscriptions to nodes appearing after the newlines from taking effect.

**Comment by badlop** [comment]
First, you must separate the nodes with commas like , but I see in your commands that you used : between two nodes, maybe it's a typo?

Second, the order of your command arguments do not work for me, I must use this one:
> $ ejabberdctl subscribe_room meep@localhost/tka1 Meep devchat@conference.localhost urn:xmpp:mucsub:nodes:affiliations,urn....

Third, it works correctly for me using Mnesia storage. 

Can you check points First and Second? If it still fails, try to use Mnesia storage. Also try to send the subscription quers using a Jabber client. And comment here what you find after trying all this.

**Comment by spacebat** [comment]
Sorry for the confusion and yes the first two points are my bad in composing the bug report. I'm definitely separating the nodes with commas and using the order of arguments you suggest.

Is there a way to use mnesia storage just for the muc subscribers data?

**Comment by spacebat** [comment]
I can't reproduce the problem locally with a freshly built 17.11 and newly cr, eated mnesia+postgres databases. Perhaps there's some state hangover in the migration that caused what I was seeing, I'm afraid the word wrapping was a red herring.

Sorry for wasting your time, but there's another bug that I'm more certain of that I'll report soon.
