### ISSUE TITLE
How to create module in ejabberd 17.11 ?

### ISSUE THREAD

**Issue by pratikshivlab** [processone/ejabberd#2173]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

distribution

Hello please help me to create user define custom module for store and fetch history in xml format for one to one chat.

**Comment by badlop** [comment]
The  easiest way is to copy an existing module like mod_log_chat.erl and change its name, then edit its content slowly.
