### ISSUE TITLE
ignoring invalid value 'sql' for option 'db_type' 

### ISSUE THREAD

**Issue by oxoWrk** [processone/ejabberd#2174]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?
Ubuntu/Debian

I'm developing a module for ejabberd . 
On dev machine (Ubuntu 16.04, ejabberd is installed from source) my module works great.
On production server (Debian, ejabberd is installed with Binary Installer) I have error:

`[error] ignoring invalid value 'sql' for option 'db_type' of module 'my_e_module'`

**Comment by badlop** [comment]
See mod_announce.erl for example. It has those lines:
```erlang
mod_opt_type(db_type) -> fun(T) -> ejabberd_config:v_db(?MODULE, T) end;
```

And later it accepts what that function accepts, but rejects other values, for example:
```
12:09:51.015 [error] ignoring invalid value 'sqllll'
 for option 'db_type' of module 'mod_announce'
```

Maybe you lack such a function.

**Comment by zinid** [comment]
I tend to think erlang just didn't see his module because it's not a part of ejabberd application (not defined in `ejabberd.app`)

**Comment by oxoWrk** [comment]
@badlop that's exactly what I did

**Comment by cromain** [comment]
since 17.11, it's possible to add "external_beams /path/to/my/beams" to EJABBERD_OPTS in ejabberdctl script, you you can store your own beams (likely $HOME/.ejabberd-module/my_own_mod/ebin) and option validator will take your module into account.

**Comment by oxoWrk** [comment]
@cromain your method has helped. Thanks to all
