### ISSUE TITLE
Malformed iq destroys rooms in 17.11

### ISSUE THREAD

**Issue by spacebat** [processone/ejabberd#2175]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

Linux Mint 18

> How did you install ejabberd (source, package, distribution)?

Deb package on processone website

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I was hoping to query all the affiliations of a room in one go by supplying a wildcard affiliation (I know, wishful thinking) like so:

```
  <iq from='meep@localhost/view-rooms.rb'
      id='iq-599318'
      to='devchat@conference.localhost'
      type='get'>
    <query xmlns='http://jabber.org/protocol/muc#admin'>
      <item affiliation='*'/>
    </query>
  </iq>
```

Because the affiliation is not a legal value, an error is returned:

```
  <iq type="error" id="iq-599318" lang="en" to="meep@localhost/view-rooms.rb" from="devchat@conference.localhost">
    <query xmlns="http://jabber.org/protocol/muc#admin">
      <item affiliation="*"/>
    </query>
    <error code="400" type="modify">
      <bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
      <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Bad value of attribute 'affiliation' in tag &lt;item/&gt; qualified by namespace 'http://jabber.org/protocol/muc#admin'</text>
    </error>
  </iq>
```

This gets logged:
```
  [info] Stopping MUC room devchat@conference.localhost
  [error] gen_fsm <0.549.0> in state normal_state terminated with reason: bad return value: ok
  [error] CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: bad return value: ok in p1_fsm:terminate/8 line 760
```

And although the room still appears in the postgresql backend table muc_room, it is not visible from ejabberd's admin interface using muc_online_rooms. Restarting ejabberd restores the room.

I think this is a bug because it seems any client submitting an innocently malformed query can destroy a room.

BTW, on closer inspection I don't think there is a way to get all the affiliations for a room in one query (other than via the admin API get_room_affiliations). Am I right?

**Comment by zinid** [comment]
Ha, what a silly bug.
