### ISSUE TITLE
A better way to know if MUC is created or destroyed?

### ISSUE THREAD

**Issue by melvinkcx** [processone/ejabberd#2176]
I would like to broadcast notification to a shared roster group whenever a MUC room is created or destroyed. Is there any event or hook related to this?

I could filter_packet to check if server sent a stanza as shown in Example 154 
[XEP-0045](https://xmpp.org/extensions/xep-0045.html#createroom)

But how do I know if a room is destroyed? 

Thanks in advance.

**Comment by melvinkcx** [comment]
I have found the stanza that server response to successful destruction of a MUC room in Example 203 
[XEP-0045](https://xmpp.org/extensions/xep-0045.html#createroom).

However, I would still like to know if there is a built-in event triggered whenever these happen? Or could you suggest a better way?

**Comment by zinid** [comment]
You cannot know it, there are no hooks for this :/

**Comment by badlop** [comment]
Looking in mod_muc.erl, I see those events:
>   ejabberd_hooks:run(remove_room, LServer, [LServer, Name, Host]),
>   ejabberd_hooks:run(create_room, ServerHost, [ServerHost, Room, Host]),

**Comment by cromain** [comment]
that's it, remove_room and create_room are the hooks you can use.
