### ISSUE TITLE
Get archived messages using StropheJs

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#2177]
> What version of ejabberd are you using?

   Source code Release 16.02

> What operating system (version) are you using?

   CentOs7

> How did you install ejabberd (source, package, distribution)?

   source

I am trying to show the conversation between the two users even after the users logout and login. I mean when user1 logged out and again logged in, he should see the conversations made with the user2. I am using Ejabberd XMPP server and Strophe Js to retrive the messages.

Can anyone help me

**Comment by badlop** [comment]
Enable mod_mam, and use https://xmpp.org/extensions/xep-0313.html
