### ISSUE TITLE
Deployment from source;

### ISSUE THREAD

**Issue by anghiloglu-dmitrii** [processone/ejabberd#2179]
> What version of ejabberd are you using?
17.11
> What operating system (version) are you using?
ubuntu 16.04
> How did you install ejabberd (source, package, distribution)?
source
> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I try to install a customised compiled version of ejabberd into production.
Steps:
 - run ./configure && make
 - make rel. 
 - found in rel/ejabberd directory with ejabberd and all dependencies, including the required parts of Erlang/OTP.
- make install & it works from prefix directory
- run it dev on the server from rel folder, it works;
- tar rel/ejabberd/* copy archive to production, try run on production 
got error 
```
15:39:58.350 [error] CRASH REPORT Process <0.111.0> with 0 neighbours exited with reason: {{load_failed,“Failed to load NIF library /home/ejabberd/lib/fast_yaml-1.0.12/priv/lib/fast_yaml: ‘libyaml-0.so.2: cannot open shared object file: No such file or directory’“},{fast_yaml_app,start,[normal,[]]}} in application_master:init/4 line 134
15:39:58.350 [critical] failed to start application ‘fast_yaml’: {error,
                                         {{load_failed,
                                           “Failed to load NIF library /home/ejabberd/lib/fast_yaml-1.0.12/priv/lib/fast_yaml: ‘libyaml-0.so.2: cannot open shared object file: No such file or directory’“},
                                          {fast_yaml_app,start,[normal,[]]}}}
15:39:58.350 [info] Application fast_yaml exited with reason: {{load_failed,“Failed to load NIF library /home/ejabberd/lib/fast_yaml-1.0.12/priv/lib/fast_yaml: ‘libyaml-0.so.2: cannot open shared object file: No such file or directory’“},{fast_yaml_app,start,[normal,[]]}}
```
- run command lld
```
ldd /../rel/ejabberd/lib/fast_yaml-1.0.12/priv/lib/fast_yaml.so
	linux-vdso.so.1 =>  (0x00007ffe76df2000)
	libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 (0x00007f0f48174000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0f47daa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0f48596000)
```
it seems ejabberd has dependency to system files. 
if ejabberd is installed from binary we can find in lib directory(inside ejabberd) additional folder linux-x86-64 with
libcrypto.so.1.0.0
libssl.so.1.0.0
libexpat.so.1.6.0
libtinfo.so.5
libncurses.so.5
libyaml-0.so.2 files.

My question: is there an option to compile ejabberd with all included decencies.

 Thank you.

**Comment by cromain** [comment]
no, you build ejabberd on your build host, which links generated .so to your host libraries. If you want to distribute binaries to other hosts, either the target hosts must have compatible versions of those dependencies, either you have to package them yourself. You noticed that's what we do in our binary installer. It's up to you to cope with your packaging and deployment process.
