### ISSUE TITLE
Voucher-safe system support?

### ISSUE THREAD

**Issue by poVoq** [processone/ejabberd#2181]
There is this interesting voucher system that is implemented on top of XMPP and supported by OpenFire:

https://www.voucher-safe.org/

It's basically an easy way to safely exchange tokens with a certain asset backed value, and could be an interesting starting point for a community "currency", gift exchange etc. It's not a crypto-currency, but just a way to share a sort of arbitrary value in a decentralized way.

Would be nice if ejabberd would also implement this XMPP extension, but I am not sure if it is an official one.

**Comment by cromain** [comment]
We're open to PR. Best is to use https://github.com/processone/ejabberd-contrib project for this Feel free to suggest a PR there.
