### ISSUE TITLE
Missing schema of pubsub_node and null value in column server_host

### ISSUE THREAD

**Issue by kevin71020** [processone/ejabberd#2182]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Docker on macOS Sierra 10.13.2

> How did you install ejabberd (source, package, distribution)?

Docker image: rroemhild/ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am configuring Ejabberd to use Postgres as backend. 
1. It connected to Postgres but database schema of “pubsub_node” miss column “type”.
error.log:

> pgmaster_1  | ERROR:  column "type" of relation "pubsub_node" does not exist at character 45
> pgmaster_1  | STATEMENT:  insert into pubsub_node(host, node, parent, type) values($1, $2, $3, $4)
> pgmaster_1  | ERROR:  current transaction is aborted, commands ignored until end of transaction block
> pgmaster_1  | STATEMENT:  insert into pubsub_node(host, node, parent, type) values('pubsub.mac.example.com', '/home', '', 'flat')
> 
> 

Table schema of pubsub_node in [**pg.new.sql**](https://github.com/processone/ejabberd/tree/master/sql)
> CREATE TABLE pubsub_node (
>   host text NOT NULL,
>   node text NOT NULL,
>   parent text NOT NULL DEFAULT '',
>   plugin text NOT NULL,
>   nodeid SERIAL UNIQUE
> );
> 

2. It has null value in colume “server_host”.
error.log

> 
> pgmaster_1  | ERROR:  null value in column "server_host" violates not-null constraint
> pgmaster_1  | DETAIL:  Failing row contains (userName, null, D0dOa/J5a2Mq9apTtrfppuHfCus=, QYGUFLWjp0AspAYaRcwjR41AUtI=, 9PWDsMGPZI1WXbNG4tB1tw==, 4096, 2017-12-21 12:14:15.257686).
> pgmaster_1  | STATEMENT:  insert into users(username, password, serverkey, salt, iterationcount) values ($1, $2, $3, $4, $5)
> 
> 

Table schema of users in pg.new.sql .

> 
> CREATE TABLE users (
>     username text NOT NULL,
>     server_host text NOT NULL,
>     "password" text NOT NULL,
>     serverkey text NOT NULL DEFAULT '',
>     salt text NOT NULL DEFAULT '',
>     iterationcount integer NOT NULL DEFAULT 0,
>     created_at TIMESTAMP NOT NULL DEFAULT now(),
>     PRIMARY KEY (server_host, username)
> );
> 

docker-compose.ml

> 
> version: "3"
>   ejabberd:
>     image: rroemhild/ejabberd
>     ports:
>       - 5222:5222
>       - 5269:5269
>       - 5280:5280
>     environment:
>       - ERLANG_NODE=ejabberd
>       - XMPP_DOMAIN=mac.exmaple.com
>       - EJABBERD_ADMINS=admin@ mac.exmaple.com
>       - EJABBERD_USERS=admin@ mac.exmaple.com:a1234 kt@ mac.exmaple.com:a1234
>       - TZ=Asia/Taipei
>       # Modules
>       - EJABBERD_SKIP_MODULES_UPDATE=true
>       # Logging
>       - EJABBERD_LOGLEVEL=5
>       # PostgreSQL Everything 
>       - EJABBERD_AUTH_METHOD=sql
>       - EJABBERD_CONFIGURE_ODBC=true
>       - EJABBERD_ODBC_TYPE=pgsql
>       - EJABBERD_ODBC_SERVER= mac.exmaple.com
>       - EJABBERD_ODBC_DATABASE=ejabberd
>       - EJABBERD_ODBC_USERNAME=ejabberd
>       - EJABBERD_ODBC_PASSWORD=a12345
>     volumes:
>         - ~/Certificates/ejabberd/ssl:/opt/ejabberd/ssl
>         - ~/docker/ejabberd/log:/usr/local/var/log/ejabberd/
>         - ~/docker/ejabberd/backup:/opt/ejabberd/backup 
> 
> 
>

**Comment by cromain** [comment]
1. you reference pg.new.sql, so I assume ejabberd is configured and compiled with --enable-new-sql-schema. This option was introduced in 17.11.

2. in pubsub_node, column 'type' was renamed to 'plugin' in 17.11.
=> You are using 17.09 code. with schema for 17.11. That's why it fails.

**Comment by kevin71020** [comment]
Thanks for your reply. The schema problem is fixed !

Another problem, null value in column **server_host** when register new user is still happen.

error log:
> ejabberd_1  | 18:43:29.835 [error] SQL query 'Q73531467' at {ejabberd_auth_sql,179} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"23502">>},{message,<<"null value in column \"server_host\" violates not-null constraint">>},{detail,<<"Failing row contains (userName, null, a1234, , , 0, 2017-12-22 10:43:29.830922).">>},{115,<<"public">>},{116,<<"users">>},{99,<<"server_host">>},{file,<<"execMain.c">>},{line,1731},{routine,<<"ExecConstraints">>}]
