### ISSUE TITLE
Auto approve presence request to someone contact by Ejabberd server instead of taking permission from that contact

### ISSUE THREAD

**Issue by shubham1164** [processone/ejabberd#2184]
> What version of ejabberd are you using?

Ejabberd 17.11

> What operating system (version) are you using?

Linux Mint 18.2

> How did you install ejabberd (source, package, distribution)?

Source code

> What did not work as expected? Are there error messages in the log? What

There is no error instead I need some help in implementing the below features -

1. I need  some mechanism (hooks/IQ/custom code changes) by which the presence request of some user auto-approves by the server instantly instead of taking permission from the second user whose presence info is required.

2. I need the above because I need presence of 1 contact at a  time so there is no need to add multiple users in roster instead I will add someone in the roster, see the last seen or Presence then unsubscribe from the presence(Like the Whatsapp Last seen/Online status).

This way I can reduce the burden on the server. Please guide the most easy solution.

**Comment by badlop** [comment]
1. I am not aware of any customization to enable such thing in ejabberd. Some Jabber clients have a similar option, but probably you want to do it in the server.

2. Well, there's mod_shared_roster, with the @online@ keyword (see the ejabberd documentation. But maybe you alredy read that, and it doesn't help you.
