### ISSUE TITLE
Retrieve more than 10 items from a PubSub Node (retrieve all the items)

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2189]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I need to retrieve all the items from a pubsub node, but with v17.11 I'm not able to retrieve more than 10. My code hasn't changed.

In older versions it worked fine and I could retrieve all the items with this kind of stanza:
_- stanza
-- pubsub
---- items (array)
------ item_

but now I'm receiving a new kind of stanza when there are more than 10 items:
_- stanza
-- pubsub
---- set
------- index
------- count
------- first
------- last
---- items (array)
------ item_

How can I do to retrieve all the items from a pubsub node?

Thanks in advance.

**Comment by cromain** [comment]
from 17.11, if using sql backend for pusbub and node store more than 10 items, RSM is used.
maybe we can relax this a bit, assuming user know what he's doing if max_items is not provided.

**Comment by Emilio-Gonzalez** [comment]
I'm using the default database Mnesia and I'm not using RSM notation.

Makes sense to retrieve al the items if max_items is not provided.

I retrieve all the items from a node like this:
_<iq type='get'
   from='francisco@denmark.lit/barracks'
   to='pubsub.shakespeare.lit'
   id='items1'>
 <pubsub xmlns='http://jabber.org/protocol/pubsub'>
   <items node='princely_musings'/>
 </pubsub>
</iq>_

**Comment by cromain** [comment]
I confirm current test to trigger rsm is not good enough.
need fix for 07a193d4d and 216a0c97b. I'll add this for 17.12

**Comment by ejbravo** [comment]
I have followed this thread with interest and it seems that Pubsub does use RSM with Mnesia according to [216a0c9](https://github.com/processone/ejabberd/commit/216a0c97b962d101311dc4d44875685f4c7cb008) (PubSub: add RSM support for Mnesia backend). Therefore this ticket has relationship with [this closed one](https://github.com/processone/ejabberd/issues/2143)

I hope you come up with a solution in the near future. Thanks

**Comment by cromain** [comment]
Yes i forgot that one, and indeed mnesia now is able to handle rsm.
i've just pushed the fix.
