### ISSUE TITLE
Avoid archiving of some messages 

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#2191]
> What version of ejabberd are you using?
ejabberd community 

> What operating system (version) are you using?
CenOs7

> How did you install ejabberd (source, package, distribution)?
package

Can we skip archiving of some messages like based on namespace or with some other param?

**Comment by zinid** [comment]
https://xmpp.org/extensions/xep-0334.html#no-store

**Comment by Veerbhadra277** [comment]
Ok Thank you @zinid
