### ISSUE TITLE
How to install mod_http_upload

### ISSUE THREAD

**Issue by Javixu69** [processone/ejabberd#2195]
Hi, today I've installed an ejabbered server but I can't send pictures.

Anyone could explain me how to install mod_http_upload for doing so?
 
Im using Ubuntu 14.04 and I've installed it by this command apt-get install ejabberd

**Comment by badlop** [comment]
I think Ubuntu 14 includes ejabberd 2.1.11, but mod_http_upload was included in a newer version.

**Comment by cromain** [comment]
you need ejabberd 15.11 or newer.
