### ISSUE TITLE
Issue while starting ejabberd 16.02

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#2196]
> What version of ejabberd are you using?

16.02

> What operating system (version) are you using?

CentOs7

> How did you install ejabberd (source, package, distribution)?

Package

Getting following error on trying to start ejabberd 
```
[root@ip-172-31-28-121 ejabberd-16.02]# ./bin/ejabberdctl start
This account is currently not available.
./bin/ejabberdctl: line 141: cd: /opt/ejabberd-16.02/database/ejabberd@localhost: No such file or directory
This account is currently not available.
```
Can anyone help me in this?

**Comment by Veerbhadra277** [comment]
@zinid  @badlop, can you help me in this.

**Comment by BhattiMarry** [comment]
Try building it from sources. I dont know the installation from package does not run at several times. I did it to but then i installed it from sources.

Give it a try and post the results here. Make sure to install erlang 17+ before the installation. You should also install the erlang from sources.

**Comment by cromain** [comment]
what package ?
official centos ? -> ask package maintainer
process-one rpm ? -> read ejabberdctl script and see what it does, you need ejabberd user on your host
process-one binary installer ? -> it's not supposed to be installed as root. You must run ejabberdctl with same user who installed ejabberd on your system.

**Comment by Veerbhadra277** [comment]
@cromain I am using same user i.e. root (not created any other user), I have installed same package on another same aws centos7 ec2 instance, and its up and running. 
But when I removed/uninstalled ejabberd 16.02 package and trying to install same again, its throwing error mentioned in error.

**Comment by Veerbhadra277** [comment]
Please find install.log

```
Log started 01/03/2018 at 16:24:12
Preferred installation mode : unattended
Trying to init installer in mode unattended
Mode unattended successfully initialized
Preparing to Install
Preparing to Install
Executing final installation script
Error executing post installation script
/opt/ejabberd-16.02/bin/postinstall.sh
\./ejabberdctl: line 141: cd: /opt/ejabberd-16.02/database/ejabberd@localhost: No such file or directory
./ejabberdctl: line 141: cd: /opt/ejabberd-16.02/database/ejabberd@localhost: No such file or directory
Error running Post Install Script.
The installation may have not completed correctly
Creating Uninstaller
Creating uninstaller 25%
Creating uninstaller 50%
Creating uninstaller 75%
Creating uninstaller 100%
Installation completed
Log finished 01/03/2018 at 16:25:16
```

**Comment by Veerbhadra277** [comment]
Issue resolved, actually `su ejabberd` was failing, referred following link for this issue 
https://geekpeek.net/this-account-is-currently-not-available-login-problems/ 

`# chsh -s /bin/bash ejabberd` solved my problem.
