### ISSUE TITLE
Monitoring Ejabberd Server.

### ISSUE THREAD

**Issue by BhattiMarry** [processone/ejabberd#2198]
> What version of ejabberd are you using?

17.12

> What operating system (version) are you using?

Centos 7.4

> How did you install ejabberd (source, package, distribution)?

sources

> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

Whenever i enable any module the server does not run neither show any error in log.

Actually i am looking for Ejabberd monitoring tool. I found Grapherl but could not integrate it with ejabberd to run. Also the official Ejabberd's site says that the server is configurable with nagios monitoring, i also could not find any nagios plugin for ejabberd monitoring. Have anyone done this, please share.

**Comment by badlop** [comment]
> Whenever i enable any module the server does not run neither show any error in log.

How do you enable that module? Which one? If you disable an existing module, instead of adding a new one, does it also hang on start?

**Comment by BhattiMarry** [comment]
Well i tried mod_grafite and that gave me the following error in log. 
**2018-01-03 07:43:52.358 [critical] <0.696.0>@gen_mod:start_module:212 Problem starting the module mod_grafite for host 192.168.122.200 
 options: [{statsdhost,<<"carbonr.xmpp.com.br">>},{statsdport,8125}]
 error: {badmatch,{error,nxdomain}}
[{mod_grafite,start,2,
              [{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_grafite/src/mod_grafite.erl"},
               {line,55}]},
 {gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,200}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,reload_modules,1,[{file,"src/gen_mod.erl"},{line,235}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,380}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,220}]}]
2018-01-03 07:43:52.358 [error] <0.696.0>@ejabberd_hooks:safe_apply:383 Hook config_reloaded crashed when running gen_mod:config_reloaded/0:
** Reason = {error,{badmatch,{error,nxdomain}},[{mod_grafite,start,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_grafite/src/mod_grafite.erl"},{line,55}],2},{gen_mod,start_module,[{file,"src/gen_mod.erl"},{line,200}],4},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{gen_mod,reload_modules,[{file,"src/gen_mod.erl"},{line,235}],1},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run1,[{file,"src/ejabberd_hooks.erl"},{line,329}],3},{ext_mod,install,[{file,"src/ext_mod.erl"},{line,220}],1}]}
** Arguments = []**

I installed it with `ejabberdctl module_install mod_grafite`

Here is how i install a separate module.
- compile the source (.erl) code file to generate a .beam file.
- mv the .beam file to /PATH-TO-EJABBERD/ebin/
- edit the ejabberd yaml file to enable the desired module.
- restart the ejabberd

There is no error in log but the server does not run.

**Comment by cromain** [comment]
this is not an ejabberd issue.
please create issue on the right project: https://github.com/processone/ejabberd-contrib
and ask mod_grafite creator for assistance.
