### ISSUE TITLE
error, crash reports, when run tsung loadtest on ejabberd server

### ISSUE THREAD

**Issue by edukondalugorla** [processone/ejabberd#2200]
When i do tsung loadtest , send messages with 1000/sec simultaneous users on ejabberd, Below error, crash reports generated. please help me.

error.log:
----------
2018-01-03 10:26:50.930 [error] <0.27778.1>@ejabberd_hooks:run_fold1:368 {timeout,{gen_server,call,[cache_tab_archive_prefs_1,{lookup,{<<"tsung35558">>,<<"chat.mydomain.com">>},#Fun<mod_mam.14.74615511>},60000]}}
running hook: {user_send_packet,[{state,{socket_state,gen_tcp,#Port<0.42525>,<0.27777.1>},ejabberd_socket,#Ref<0.0.1310721.185539>,false,<<"13074739368386076477">>,undefined,c2s,c2s_shaper,false,false,false,false,[verify_none,compression_none],true,{jid,<<"tsung35558">>,<<"chat.mydomain.com">>,<<"tsung">>,<<"tsung35558">>,<<"chat.mydomain.com">>,<<"tsung">>},<<"tsung35558">>,<<"chat.mydomain.com">>,<<"tsung">>,{{1514,955203,31188},<0.27778.1>},{1,{{<<"tsung35558">>,<<"chat.mydomain.com">>,<<>>},nil,nil}},{1,{{<<"tsung35558">>,<<"chat.mydomain.com">>,<<>>},nil,nil}},{1,{{<<"tsung35558">>,<<"chat.mydomain.com">>,<<>>},nil,nil}},{xmlel,<<"presence">>,[{<<"id">>,<<"210428">>}],[]},{1514,955236,206329},{userlist,none,[],false},c2s,ejabberd_auth_sql,{{13,228,212,232},48415},[],active,inactive,undefined,undefined,1000,undefined,300,300,60000,undefined,false,0,0,0,true,<<>>},{jid,<<"tsung35558">>,<<"chat.mydomain.com">>,<<"tsung">>,<<"tsung35558">>,<<"chat.mydomain.com">>,<<"tsung">>},{jid,<<"tsung3038">>,<<"chat.mydomain.com">>,<<>>,<<"tsung3038">>,<<"chat.mydomain.com">>,<<>>}]}

crash.log
==========

2018-01-03 10:24:56 =ERROR REPORT====
callback failed:
** Tab: archive_prefs
** Owner: <0.38.0>
** Operation: lookup
** Args: [{<<"tsung20948">>,<<"chat.mydomain.com">>}]
** Reason: {timeout,{p1_fsm,sync_send_event,[<0.327.0>,{sql_cmd,{sql_query,{sql_query,<<"Q125746177">>,#Fun<mod_mam_sql.10.73335102>,#Fun<mod_mam_sql.11.73335102>,#Fun<mod_mam_sql.12.73335102>,{mod_mam_sql,114}}},-576460467749},60000]}}

**Comment by cromain** [comment]
you connect 1000/sec users, really ? please, make sure you understand what you are doing. writing valid tsung scenario requires experience.
your logs just tell ejabberd is overloaded, your scenario is likely broken, or the architecture you designed does not support your load.

**Comment by edukondalugorla** [comment]
I run tsung with  below arrival rate..

 <arrivalphase phase="1" duration="50" unit="minute">
          <users arrivalrate="1000" unit="second"></users>
  </arrivalphase>

**Comment by zinid** [comment]
The error tells that you're using too old ejabberd version (with really slow caching implementation). You're better off switching to 17.11 or 17.12 (with TLS disabled). Also, in 17.12 a new system monitor is implemented, which will tell you what part of ejabberd is overloaded exactly.
