### ISSUE TITLE
Server crashed after reaching 30000 connected users  

### ISSUE THREAD

**Issue by edukondalugorla** [processone/ejabberd#2207]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

github source

When i run ejabberd loadtest using Tsung, after reaching 30000 connected_users_number.  Server was shoutdown with below crash report,  Please help me

CRASH REPORT:
-----------------

2018-01-04 16:48:35 =SUPERVISOR REPORT====
     Supervisor: {local,mnesia_kernel_sup}
     Context:    child_terminated
     Reason:     killed
     Offender:   [{pid,<0.3357.0>},{id,mnesia_locker},{mfargs,{mnesia_locker,start,[]}},{restart_type,permanent},{shutdown,3000},{child_type,worker}]

2018-01-04 16:48:35 =SUPERVISOR REPORT====
     Supervisor: {local,mnesia_kernel_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.3357.0>},{id,mnesia_locker},{mfargs,{mnesia_locker,start,[]}},{restart_type,permanent},{shutdown,3000},{child_type,worker}]

2018-01-04 16:48:35 =ERROR REPORT====
Mnesia(ejabberd@localhost): ** ERROR ** (could not write core file: system_limit)
 ** FATAL ** Cannot open log file "/var/lib/ejabberd/PREVIOUS.LOG": {file_error,"/var/lib/ejabberd/PREVIOUS.LOG",system_limit}
2018-01-04 16:48:38 =SUPERVISOR REPORT====
     Supervisor: {local,mnesia_sup}
     Context:    child_terminated
     Reason:     shutdown
     Offender:   [{pid,<0.3354.0>},{id,mnesia_kernel_sup},{mfargs,{mnesia_kernel_sup,start,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]

**Comment by prefiks** [comment]
You probably need to increase limit of open files with "ulimit -n <BIGGER_NUMBER>". I don't know how you start ejabberd, but probably you should add "ulimit -n 200000" line before it starts ejabberd.

**Comment by zinid** [comment]
Don't use Mnesia backend anywere if you need to handle that much connections.
Also, 16.09 is too old: with 17.x branch you will see very different results.
