### ISSUE TITLE
Version 17.12 server_host value is null from ejabberd 

### ISSUE THREAD

**Issue by mskocabay** [processone/ejabberd#2210]
I am using ejabberd 17.12 on Linux Ubuntu.

i upgraded  database tables, when ejabberd insert database **server_host** value return null, so not saved the db .Is there any way to resolve this problem ? In my ejabberd.yml  conf about host info .
Thanks

`###'  SERVED HOSTNAMES

##
##
hosts:
  **- "server1.myhost.com"**

##
##
## route_subdomains: s2s

###.  ===============
###'  LISTENING PORTS
`

**Comment by cromain** [comment]
Our binary installers and .deb/.rpm are build without that feature for now. If you want that feature you MUST build from sources with option --enable-new-sql-schema.
Did you compiled from sources ?

**Comment by mskocabay** [comment]
Installed ejabberd from rpm ,  I upgraded db  from https://github.com/processone/ejabberd/blob/master/sql/pg.new.sql, added new column server_host. This column in table not_null. But ejabberd send null value for server_host.  How can i enable -new-sql-schema  with option ? I didint try before.

**Comment by mskocabay** [comment]
thank you i turned  back old schema .
