### ISSUE TITLE
Bare JID messages not routed to websocket connections

### ISSUE THREAD

**Issue by spacebat** [processone/ejabberd#2212]
> What version of ejabberd are you using?

17.09, 17.11

> What operating system (version) are you using?

Linux Mint 18.2

> How did you install ejabberd (source, package, distribution)?

DEB packages from processone website

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Using the admin api command send_stanza, a message sent to a user's bare JID will be routed to each of their active connections, however it appears that websocket connections are not included. Messages sent to bare JIDs are only received on c2s connections.

Messages sent to the full JID of a websocket connection are received as normal.

If the user has a websocket connection and no c2s connections, a message sent to their bare JID occasionally results in a error stanza in the log, containing the message to be sent along with:
```
         #stanza_error{
               type = cancel,code = 503,by = <<>>,
               reason = 'service-unavailable',
               text = #text{lang = <<>>,data = <<"User session not found">>},
               sub_els = []}
```
Perhaps at those times the websocket had disconnected - I haven't been able to reproduce that today while the websocket was definitely connected.

When there is no such error and the user only has a websocket connection, the last thing logged in debug mode is the message prepended by "processing message to bare JID:"

**Comment by prefiks** [comment]
This is working fine here, do your websocket client send presence at startup, this is required per xmpp spec to route messages to bare jid, eventually do you have another client for that jid that uses higher priority in presence?

**Comment by spacebat** [comment]
The websocket client is using strophe.js, and it does send presence to the MUC room.
We're using mod_carbon_copy which I assumed means presence priority does not come into it.
