### ISSUE TITLE
Route selection/balancing algorithm

### ISSUE THREAD

**Issue by pdorofiejczyk** [processone/ejabberd#2215]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hello,

We have cluster of ejabberd behind load balancer and a few nodes of custom transport components (handling legacy solution sync). We have set domain balancing to bare_source so each stanza from given user should be balanced to the same transport component which is critical to us because we multiplicate one session in legacy solution to multiple in ejabberd. This is true when new user session is balanced to the same ejabberd node but from other nodes ejabberd selects other transport component.

As I see in ```ejabberd_router.erl``` there are two route selection algorithms. Algorithms can be switched by setting ```domain_balancing_component_number``` in config. When ```domain_balancing_component_number``` is set, only given number of nodes can be registered and routes are selected from all routes available (local and remote) but in case of transport component crash, users are not rebalanced to other nodes. In the other case  the algorithm selects routes by phash of selected domain balancing but with priority of local routes so if any local routes are available one of them would be selected.

I am thinking of making PR with implementation of consistent hasing algorithm to solve my problem and improve reliability of ejabberd routing. The question is why this kind of algorithm is not implemented yet? Do yo see any downsides of this?

**Comment by zinid** [comment]
The problem with consistent hashing is that you need to do rebalancing/data migration in the case when a new node (component) arrives. E.g., when a new component connects, it's injected into hashing ring instantly and 1/N part of users will be routed to this new instance. If a client session maintains "connection state" with a particular component, this may lead to stale sessions on the component or something like that.

**Comment by pdorofiejczyk** [comment]
I agree with your arguments but each algorithm has pros and cons. Let's see:

**"Static" algorithm (```domain_balancing_component_number```)**

pros:
- users are balanced always to the same component independently of ejabberd node in cluster
cons:
- in case of one component fail/disconnect, 1/N users will be not rebalanced and don't have access to component's functionality
- components can't be added dynamically to handle bigger load

**"Dynamic" algorithm with local routes priority**

pros:
- users will be rebalanced if one component fail/disconnect
- components can be dynamically added
cons:
- there is no guarantee to user will be balanced to the same component independently of ejabberd node in cluster
- nearly all users will be rebalanced if one component is added/removed

**Consistent hashing**
pros:
- users will be rebalanced if one component fail/disconnect
- components can be dynamically added
- users are balanced always to the same component independently of ejabberd node in cluster
cons:
- 1/N users will be rebalanced if one component is added/removed

As you see consistent hashing algorithm seems to have the least cons. I understand that selection of algotithm can depend of use case (ex. component impelmentation) but I think it will be nice to have one more option.

**Comment by zinid** [comment]
I you're ok with the cons you mentioned, then of course we could implement something like this. However, ejabberd is lacking functions notifying other nodes about routes registration (and rebuilding hashing ring on every route request might be very expensive). So it should be implemented first somehow in order to populate the hashing ring.

**Comment by pdorofiejczyk** [comment]
What do you mean by "rebuilding hashing ring"? As I know consistent hashing is just matematic algorithm which splits keys into given number of buckets. I don't see any needs to populate "hashing ring" between nodes. One thing which should be populated is routing table but it works now by mnesia replication (or sth else in other implementations).

**Comment by zinid** [comment]
That's what I mean:
![](http://paperplanes-assets.s3.amazonaws.com/consistent-hashing.png)
You need to have next() property on the table where you keep your IDs. Maybe there are other possiblities, but I don't see how existing SQL/Redis/Mnesia routing table can be used to map IDs to routes.

**Comment by pdorofiejczyk** [comment]
I was thinking about google's "jumping consistent hash" algorithm (https://arxiv.org/pdf/1406.2294.pdf) which requires no storage and is very fast. Here is c implementation of this algorithm with erlang wrapper https://github.com/darach/jch-erl. The main limitation is that the buckets must be numbered sequentially but it's not the problem because routes are numered sequentially now during registration and this numbers are saved in ```local_hint``` column in all router implementations (mnesia, sql, redis).

**Comment by zinid** [comment]
I close the issue because of inactivity.
