### ISSUE TITLE
Error when creating Mutual Subscription using send_stanza

### ISSUE THREAD

**Issue by rheman** [processone/ejabberd#2222]
I am using ejabberd 16.01under ubunu 16.04 TLS (distribution packge).
I can add a roster using send_stanza by using the following command.

`ejabberdctl --auth admin esfamchat.auf.org pessek12 send_stanza irene@esfamchat.auf.org durand@esfamchat.auf.org "<iq from='irene@esfamchat.auf.org/balcony' type='set' id='roster_2'><query xmlns='jabber:iq:roster'><item jid='durand@esfamchat.auf.org' subscription='none' ask='subscribe' name='Durand Puewe'><group>Friends</group></item></query></iq>"`

But when I try to create mutual  subscription using the following command I have an error

`ejabberdctl --auth admin esfamchat.auf.org pessek12 send_stanza irene@esfamchat.auf.org durand@esfamchat.auf.org "<iq  type='set' id='roster_2'><query xmlns='jabber:iq:roster'><item jid='durand@esfamchat.auf.org' subscription='from' ask='subscribe' name='Durand Puewe'><group>Friends</group></item></query></iq><presence from='irene@esfamchat.auf.org' to='durand@esfamchat.auf.org' type='subscribe'/>"`

I have just added 
`<presence from='irene@esfamchat.auf.org' to='durand@esfamchat.auf.org' type='subscribe'/> `
in the query for creating roster.

My error looks as followed

```
problem 'error {badmatch,{error,{9,<<"junk after document element">>}}}' occurred executing the command.
Stacktrace: [{mod_admin_extra,send_stanza,3,
                              [{file,"src/mod_admin_extra.erl"},{line,1336}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,407}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,295}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,220}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,205}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,206}]}]
```

Could someone help me ?

Best regard

**Comment by prefiks** [comment]
You can only send single stanza using this command, you would have to split those two to separate calls to ejabberdctl
