### ISSUE TITLE
default access rule for ejabberd_http_ws

### ISSUE THREAD

**Issue by varmando** [processone/ejabberd#2223]
> What version of ejabberd are you using?
18.01

> What operating system (version) are you using?
Debian 9

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Is there a way to explicitly set access rule for websocket connections? Now the ejabberd_http_ws seems to inherit access rule from ejabber_c2s listener with lowest port number.

**Comment by prefiks** [comment]
This was added in commit c3b4b4ce4f269d98960d51a6bac9f4d6ee2d6086
