### ISSUE TITLE
mod_pubsub column rename in new SQL schema missing

### ISSUE THREAD

**Issue by Natureshadow** [processone/ejabberd#2226]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian 9

> How did you install ejabberd (source, package, distribution)?

jabber.at package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I migrated the SQL schema using the pg.neq.sql file for PostgreSQL. After that, mod_pubsub stopped working because the `type` column was apparently renamed to `plugin`. This change is nowhere to be found in the shipped SQL schemas.

**Comment by cromain** [comment]
This should be a packaging issue. I don't know what means "jabberd.at package".
Sources includes schema with type column renamed to plugin.
Note: using new schema can only works if ejabberd is explicitely compiled with --enable-new-sql-schema option. This is not the case for the binary/packages we provide.

**Comment by Natureshadow** [comment]
jabber.at are the people providing the official Debian package.

I am pretty certain they did not remove that one change from the schema ;). I also cannot find any ALTER TABLE for that in this repository…

Maybe it is because I missed one of the updates between 17.08 and 18.01?

**Comment by cromain** [comment]
Please check upgrade note
https://docs.ejabberd.im/admin/upgrade/from_17.09_to_17.11/

**Comment by cromain** [comment]
BTW quickly looking at debian's package rule, i don't think they are configuring with --enable-new-sql-schema also.

**Comment by Natureshadow** [comment]
Yep, I missed that step.

Apart from these two issues, the server seems to run flawlessly with the new schema, though…
