### ISSUE TITLE
mod_offline writes NULL to NOT NULL column

### ISSUE THREAD

**Issue by Natureshadow** [processone/ejabberd#2227]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian 9

> How did you install ejabberd (source, package, distribution)?

jabber.at package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The new SQL schema dictates a `server_host` column contaiing the virtual host name. `mod_offline` does not seem to know this and tries writing entries without a value in `server_host`, leading to the module failing.

I temporaily removed the `NOT NULL` constraint from the column to circumvent this.

**Comment by cromain** [comment]
It seems you're running binary compiled without experimental --enable-new-sql-schema

**Comment by Natureshadow** [comment]
Not as far as other modules are concerned.

**Comment by Natureshadow** [comment]
Ah, nope… That was another side effect, apparently.

For now, I added the DEFAULT to the columns. From all I see, this should make it backwards compatible for now.

Sorry for the noise - I somehow failed to find the information about when to apply the new schema and when not…
