### ISSUE TITLE
PubSub: the service can include the publisher of the item when it generates event notifications

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2229]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is it possible to include the publisher in the item attributes when that item is retrieved from a pubsub node?

https://xmpp.org/extensions/xep-0060.html#publisher-publish-success-publisher
_If configured to do so, the service can include the publisher of the item when it generates event notifications._

**Comment by cromain** [comment]
you need to configure node option itemreply.
see details here: https://xmpp.org/extensions/xep-0060.html#impl-association
