### ISSUE TITLE
Can I use Different DB for each module?

### ISSUE THREAD

**Issue by gylraj** [processone/ejabberd#2233]
Can I use Different DB for each module?

Example:

auth_method: mysql

modules:
  mod_mam:
     db_type: mysql2
     default: always

  mod_muc:
    host: "room.@HOST@"
    access: all
    access_admin: all
    access_create: all
    access_persistent: all
    db_type: mysql3

**Comment by zinid** [comment]
Different SQL databases can only be set for different virtual hosts.
You cannot use different SQL databases on the same virtual host.
