### ISSUE TITLE
Setting up ejabberd server and using it with mobile and web clients.

### ISSUE THREAD

**Issue by udayofficial** [processone/ejabberd#2234]
> What version of ejabberd are you using?
18.x

> What operating system (version) are you using?

Mac high Siera v10.12.1

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log?
I am confused where to start from?
 
>What was the unexpected behavior? What was the expected result?

I do not have any previous experiance in backend/ server technologies. I have a web and mobile app for iOS and Android. I want to provide messaging feature within these apps. I do not want to use services of any third party SDk etc. I want my own ejabberd based server and setup everything myself. I know it is quite difficult but i can do it. I do not if mind if anybody is interested to work for me part-time/full-time. 

I am looking for a step-by-step guide which guides me from 0 to complete messaging :). 
I have already been through the ejabberd.im tutorials but with no luck.

Thanks in advance.
Uday

**Comment by cromain** [comment]
Hello
This is not a bug report, nor a detailed issue.
Read ejabberd documentation and make sure you understand basis concepts: https://docs.ejabberd.im
You can post such question on community forum, but not on github.

**Comment by mremond** [comment]
Stackoverflow / Serverfault are also typically good places to ask technical questions, as long as you have already worked on the topic and are able to ask a precise enough questions with example code.
