### ISSUE TITLE
Configure node option itemreply to retrieve node owner

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2235]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentoOS 7

> How did you install ejabberd (source, package, distribution)?

RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

As @cromain described at #2229, I do receive the item publisher configuring node option itemreply.

Now I'm trying to retrieve the node owner instead of the publisher, but I can't.

Any advice?

**Comment by cromain** [comment]
well, i don't see how can i help with your description.
I assume you configured owner as itemreply, instead of publisher.
i'd need at least the sent/received payload, any errors in logs, etc...
