### ISSUE TITLE
For what purpose ?SQL macros used for?

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2240]
> What version of ejabberd are you using?

17

> What operating system (version) are you using?

centOS

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by cromain** [comment]
it's used for cleaner code and transient type conversion. example:

before:
```
    Count = case ejabberd_sql:sql_query_t(
                   [<<"select count(id) from table where id='">>, integer_to_binary(Id), <<"';">>]) of
                {selected, [_], [[C]]} -> binary_to_integer(C);
                _ -> 0
            end,
```

after:
```
    Count = case catch ejabberd_sql:sql_query_t(
                    ?SQL("select @(count(id))d from table where id=%(Id)d")) of
                {selected, [{C}]} -> C;
                _ -> 0
            end,
```
