### ISSUE TITLE
Missing plugins: [rebar3_hex]

### ISSUE THREAD

**Issue by RabbitDuck** [processone/ejabberd#2243]
> What version of ejabberd are you using?
ejabberd-18.01
ejabberd-18.1.0

> What operating system (version) are you using?
Slackware64 14.2

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What

> was the unexpected behavior? What was the expected result?

Compile with the following configure:
./configure --enable-mysql --enable-sqlite --enable-zlib --enable-redis --enable-iconv --enable-stun --enable-sip --enable-graphics --enable-user=ejabberd

A warning is issued:
/usr/lib64/erlang/bin/escript rebar skip_deps=true compile
WARN:  Missing plugins: [rebar3_hex]
==> rel (compile)
==> ejabberd-18.1.0 (compile)

ignore the warning?
or how to install the missing plugins?

Thanks

**Comment by zinid** [comment]
Ignore it. I personally don't have this plugin neither.
