### ISSUE TITLE
Listener exception in 18.01

### ISSUE THREAD

**Issue by gardenia** [processone/ejabberd#2244]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Ubuntu 16.04, amd64

> How did you install ejabberd (source, package, distribution)?

binary file

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm seeing this fairly regularly in the logs.  I'm not sure if I can say it is resulting in any negative user experience (doesn't seem to be) but that is not yet clear.  Should I be concerned about this?

2018-01-24 13:46:57 =CRASH REPORT====
  crasher:
    initial call: ejabberd_listener:init/3
    pid: <0.566.0>
    registered_name: []
    exception error: {{badmatch,ignore},[{xmpp_socket,start,4,[{file,"src/xmpp_socket.erl"},{line,108}]},{ejabberd_listener,accept,4,[{file,"src/ejabberd_listener.erl"},{line,297}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_listener,ejabberd_sup,<0.65.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.22263>,<0.341.0>,#Port<0.22233>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 29132
  neighbours:
2018-01-24 13:46:57 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_listener}
     Context:    child_terminated
     Reason:     {{badmatch,ignore},[{xmpp_socket,start,4,[{file,"src/xmpp_socket.erl"},{line,108}]},{ejabberd_listener,accept,4,[{file,"src/ejabberd_listener.erl"},{line,297}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.566.0>},{id,{5222,{0,0,0,0,0,0,0,0},tcp}},{mfargs,{ejabberd_listener,start,[{5222,{0,0,0,0,0,0,0,0},tcp},ejabberd_c2s,[{access,c2s},{shaper,c2s_shaper},{max_stanza_size,500000},{starttls,true}]]}},{restart_type,transient},{shutdown,brutal_kill},{child_type,worker}]

**Comment by gardenia** [comment]
update: I discovered this was a haproxy TCP load balancer health check.  so it isn't a problem but if I was being picky I would say the logging could be more clear somehow.  what do you think?

**Comment by prefiks** [comment]
Should be fixed by 56d4224e083d6160dfd60338278c6cee6c6fe642
