### ISSUE TITLE
Errors in mod_privilege's process_presence_in when handling presences from transport

### ISSUE THREAD

**Issue by himselfv** [processone/ejabberd#2248]
Using ejabberd 18.01 on Amazon AMI, installed from official RPM. In conjunction with spectrum2, hosting purple-skypeweb.

Once the transport connects and starts sending presences it works fine, like before, but there's a lot of error messages in error log:
```
[error] <0.513.0>@ejabberd_hooks:safe_apply:383 Hook user_receive_packet crashed when running mod_privilege:process_presence_in/1:
** Reason = {error,{case_clause,none},[{mod_privilege,'-process_presence_in/1-fun-0-',[{file,"src/mod_privilege.erl"},{line,163}],3},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{mod_privilege,process_presence_in,[{file,"src/mod_privilege.erl"},{line,161}],1},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4}, [...]
** Arguments = [{{presence,<<>>,unavailable,<<>>, [...]]
```

I think this haven't been happening in 17.12 which I had before (I'd notice error log quickly growing).

I have only one rule for mod_privilege: ```message: outgoing: allow: "transport.example.org"``` (syntax simplified here).

This is the code where it says {case_clause, none}:
```
    lists:foreach(
      fun({Host, Access}) ->
	      case proplists:get_value(presence, Access, none) of
		  roster ->
		        //...
		      end;
		 true ->
		      ok
	      end
end, dict:to_list(Permissions)),
```

**Comment by himselfv** [comment]
I've not much experience with erlang, but from the docs it looks like ```proplist:get_value``` returns the last argument if the value is not in the list. In this case, ```none```.

And it looks like ```true ->``` is used as the ```else``` clause with ```if```, but maybe not with the ```case``` statement? It looks like with the ```case``` statement ```_``` can be used as a catch-all instead.

So maybe ```true``` should be changed to ```_```?

**Comment by prefiks** [comment]
Hello,

Looks like someone did forgot to change something when switching from `if` to `case` block, this should be fixed by commit 53870c854e4a3d5deb57d77862ee59f25620cb0c.

**Comment by himselfv** [comment]
I think that's not enough, ```roster``` and ```none``` are not the only possible values, you can also get ```managed_entity```. It might be better to just use ```_```.

**Comment by prefiks** [comment]
Ah, you are completly right, followup commit in a bit

**Comment by prefiks** [comment]
And that would be commit bb583071901e598956f59de7323660ab7b83cc10

**Comment by himselfv** [comment]
Thanks!
