### ISSUE TITLE
Updating Ejabberd 17.07.30

### ISSUE THREAD

**Issue by OmPrakash95** [processone/ejabberd#2250]
> What version of ejabberd are you using?

ejabberd 17.07.30 is running in that node

> What operating system (version) are you using?

Ubuntu 14.04 LTS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What

I wanted to add mod_push to my existing ejabberd Edition. But I felt upgrading it would be a better option and there's no documentation related to updating Ejabberd from version 17.07.30 to 17.08/17.09
The documentation here is empty https://docs.ejabberd.im/admin/upgrade/from_17.06_to_17.09/

**Comment by badlop** [comment]
In the link you provide, I can read:

> Upgrade to ejabberd 17.09
> 
> Ejabberd upgrade process
> You should follow this procedure if you are upgrading from ejabberd 17.06, 17.07 or 17.08.
> 
> ejabberdctl script
> Due to a major refactor of the ejabberdctl script, you should check your packaging and your system's version of ejabberdctl script. While old script still works, you are encouraged to use the new one. This may depends on media you install ejabberd from.

**Comment by OmPrakash95** [comment]
I Installed ejabberd from Source and what does the version of ejabberdctl script has to do with updating ejabberd ?

**Comment by cromain** [comment]
if you install fro sources, i assume you know what you are doing. if you don't want to update your ejabberdctl script, it's a mater of choice, completely up to you.
the the upgrade note state, there is nothing else needed for the upgrade.
