### ISSUE TITLE
GetMessagesBySenderJBID

### ISSUE THREAD

**Issue by gylraj** [processone/ejabberd#2251]
> What version of ejabberd are you using?

ejabberd-17.01

> What operating system (version) are you using?

Ubuntu 16

> How did you install ejabberd (source, package, distribution)?

ejabberd_17.01-0_amd64.deb

>HowTo

how to get messages by to jbid using Rest API?
or
how to create specific API for getting Messages with params(ToJBID, FromJBID, etc)?

thanks

**Comment by badlop** [comment]
If you refer to messages stored by mod_mam: it does not provide any command access its database.

**Comment by gylraj** [comment]
What is the best practice to implement for retrieving past messages of a muc? how can i get the previous messages from a room?

**Comment by badlop** [comment]
If mod_mam is enabled, and the room has "Archiving" enabled, then you can use https://xmpp.org/extensions/xep-0313.html to retrieve room messages

**Comment by gylraj** [comment]
Thanks,
can i ask u another question?
i want to send stanza via api
but it keeps saying "no session"

http://localhost:5285/api/send_stanza_c2s
{
  "name": "admin@localhost",
  "host": "localhost",
  "stanza":"<iq id='123' to='test@localhost' type='get'><query xmlns='jabber:iq:roster'/></iq>"
}

status: 400
"no_session"

**Comment by cromain** [comment]
badlop answered your question.
your last question is unrelated to the initial topic, not a bug, not even an issue.
please read documentation before asking and don't mix unrelated issue on the same thread.
this is an issue tracking system. not a free support platform.
if you have question, please ask on forums or other community platforms.
