### ISSUE TITLE
Suggestion: Do not produce carbons of carbons

### ISSUE THREAD

**Issue by himselfv** [processone/ejabberd#2252]
A transport I'm working with wants to inform XMPP clients about any messages sent via different legacy clients from same account in the legacy network.

For example, if the transport associates a certain Skype account (example@skype.com) with a certain XMPP JID (example@xmpp.org), it wants to inform that JID of any Skype messages sent by example@skype.com via Skype for PC.

Since ejabberd never saw the original message, the transport has no choice but to produce [XEP-0280 carbons](https://xmpp.org/extensions/xep-0280.html) manually. It wraps the original message in a ```<message><sent><forwarded>``` and delivers this to the server (additionally wrapping it in <privilege> forwarder per [XEP-0356](https://xmpp.org/extensions/xep-0356.html), which works fine).

ejabberd unwraps the privileged packet and delivers the carbon fine, everything works.

But then ejabberd produces its own carbons of this carbon, for every carbon-subscribed client. Additionally, those are ```<received>``` carbons. So the following chain of nested tags is produced: ```<message><received><forwarded><message><sent><forwarded><message />```.

ejabberd actually checks for whether the message is already a carbon before producing carbons of it, but it is checking for this via its internal meta fields which are only present in in-memory representation and are unavailable to external XML.

Maybe ejabberd could skip producing carbons for messages that already include ```<received xmlns="urn:xmpp:carbons:2">``` or ```<sent xmlns=..>``` ?

As a workaround, if you add ```<no-copy [..] />```, no carbons are produced.

**Comment by weiss** [comment]
> But then ejabberd produces its own carbons of this carbon, for every carbon-subscribed client.

As per the [XEP-0280 rules][1], yes.

> As a workaround, if you add `<no-copy [..] />`, no carbons are produced.

Why do you consider this a workaround?  I think those hints are a good solution for such special use cases.

[1]: https://xmpp.org/extensions/xep-0280.html#which-messages

**Comment by himselfv** [comment]
Should it really? XEP-0280 says "rules a server MAY use, or it MAY use its own" and "SHOULD follow the general intent of these rules".

I mean, I don't mind setting ```<no-copy />```, but are carbons of carbons really an intended result? What purpose could they serve?

I can code this if this helps.

**Comment by zinid** [comment]
Please ask this in the XSF mailing list or conference. We're not going to change rules of the XEP.

**Comment by himselfv** [comment]
Alright, I've asked: https://mail.jabber.org/pipermail/standards/2018-January/034224.html

**Comment by weiss** [comment]
> are carbons of carbons really an intended result? What purpose could they serve?

Just like I haven't thought of your special use case before, I can imagine there's other special use cases neither you nor me currently have in mind.

**Comment by himselfv** [comment]
Maybe ¯\_(´°_°` )_/¯ Let's see where it leads us. What's your opinions on the "negotiate + send to the bare JID" proposal from the thread, btw? If it were formalized as a XEP.

**Comment by zinid** [comment]
As I understand, the issue doesn't relate to ejabberd, but to the standard itself. I close it.
