### ISSUE TITLE
Maybe mod_mam should archive carbon contents when no original message is available?

### ISSUE THREAD

**Issue by himselfv** [processone/ejabberd#2253]
A transport I'm involved with uses [XEP-0280 carbons](https://xmpp.org/extensions/xep-0280.html) to inform XMPP clients of any messages sent from the same legacy network account via different legacy clients.

For example, if the transport associates a certain Skype account (example@skype.com) with a certain XMPP JID (example@xmpp.org), it copies any Skype messages sent by example@skype.com via Skype for PC to XMPP clients via carbons.

I'm using mod_mam to keep a history of all conversations. Messages sent to our legacy network identity elsewhere are delivered as normal incoming messages and archived fine. But these carbons of our own messages are not archived. So only half of each conversation is archived.

What's the correct way of dealing with this? (Looking from the transport side)

I can produce a fake "original message" (```from=example@xmpp.org to=example_contact@skype.net```) but if the transport gives this to ejabberd, it just routes this back to transport for delivery. (And it doesn't even archive it, because archival sits on c2s connection hooks and this is s2s) And I don't think this is ideologically correct anyway.

Maybe mod_mam could archive carbon contents when no original message is available? Or, more broadly, just archive carbon contents always, unless that message is already archived, for example, because it's original copy had been archived.

**Comment by weiss** [comment]
> Maybe mod_mam could archive carbon contents when no original message is available?

I think `mod_mam` should stick to the [standard business rules][1] rather than adding complicated rules to cope with such special use cases.  Can't the transport just add a [`<store/>` hint][2]?

[1]: https://xmpp.org/extensions/xep-0313.html#sect-idm139640281572528
[2]: https://xmpp.org/extensions/xep-0334.html#sect-idm139626442489328

**Comment by himselfv** [comment]
```<store>``` works but it stores the wrapper stanza (```<message to=example@xmpp.org><sent><forwarded><message to=example@skype.com>...```), not the internal stanza. Furthermore, it is stored not for the original recipient (since it's not in the topmost ```to=```) and multiple carbons are stored multiple times.

Is there anything in those rules that says carbons _shouldn't_ be studied like that? The only mention I could find is:
```
If a server supports mechanisms that multiply copies of a stanza (e.g. Carbons, or forking a stanza to a bare JID), it MUST store such a stanza within a given archive only once
```

Which I think suggests the server _might_ inspect carbon contents (otherwise why would they need to mention that it shouldn't produce duplicates based on this contents?) Of course "might" is not "should"...

**Comment by zinid** [comment]
As I understand, the issue doesn't relate to ejabberd, but to the standard itself. I close it.
