### ISSUE TITLE
retrieve the chat messages I have received

### ISSUE THREAD

**Issue by ganeshnegi** [processone/ejabberd#2254]
> ejabberd version 17.04

> ubuntu 17.04

I want to retrieve the message that a particular user has received and sent. I want to display these messages as the inbox and sent box of email [I am trying to implement an email like service where I can display the received chat messages in inbox and sent messages in sent box]. 

I want to get all these messages using python. I am unable to find any method for client with which I can retrieve chat history.

In ejabberd.yml, I have enabled mod_mam as :

```
> mod_mam:
>     db_type: sql
>     default: always
```
Please help.

**Comment by badlop** [comment]
And did you try https://xmpp.org/extensions/xep-0313.html#query ?
