### ISSUE TITLE
what is different between connection to 5222 port or 5280?

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2256]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

centOS 7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by cromain** [comment]
this is not an issue.
please read documentation before asking question: https://docs.ejabberd.im/admin/configuration/#listening-ports
