### ISSUE TITLE
[ejabberd version 16.01] ejabberdctl permission denied on Ubuntu 16.04.03

### ISSUE THREAD

**Issue by digz6666** [processone/ejabberd#2257]
I've installed ejabberd with apt-get on my Ubuntu 16.04.03.
But when I try to use ejabberdctl it says:
```
The command can only be run by root or the user ejabberd.
```

So I've used with sudo ejabberd but this time it says permission denied:
```
/usr/sbin/ejabberdctl: line 447: /bin/ps: Permission denied
/usr/sbin/ejabberdctl: line 451: /bin/ps: Permission denied
```

I opened up /usr/sbin/ejabberdctl with vim and checked those lines:
```
ps ux | grep -v grep | grep -q "ERLANG_NODE" && {                                              # line 447
    echo "ERROR: The ejabberd node '$ERLANG_NODE' is already running."
    exit 4
} || {
    ps ux | grep -v grep | grep -q beam && {                                                             # line 451
        echo "ERROR: The ejabberd node '$ERLANG_NODE' is registered.
        .....
}
```

I've logged in as user ejabberd with su command and tried to run ejabberdctl start it the issue is exact same.
So I've followed this comment https://github.com/processone/ejabberd/issues/1504#issuecomment-280474103 and copied /usr/sbin/ejabberdctl to /usr/sbin/ejctl and used ejctl command it works without any problems.

Ejabberd version: 16.01
OS: Ubuntu 16.04.03
Install type: package (apt-get)

**Comment by cromain** [comment]
so what ?
you're using a very old ejabberd version and get an issue which was solved long time ago.
of course using recent/fixed ejabberdctl script solve your problem.

**Comment by digz6666** [comment]
@cromain Ah my bad, I didn't notice 18.01 version is released. The ejabberd on ubuntu apt repository is outdated.
