### ISSUE TITLE
Ejjaberd canot access to admin page

### ISSUE THREAD

**Issue by abdelhafiddahhani** [processone/ejabberd#2260]
> What version of ejabberd are you using?

> What operating system (version) are you using?

ubuntu 17

> How did you install ejabberd (source, package, distribution)?

package using apt-get

> What did not work as expected? Are there error messages in the log? What

i installed ejabberd in ubuntu and when i try to access to this link : 127.0.0.1:5222 i got this error

""<stream:stream id='12847806584895138227' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'>stream:errorsyntax error</stream:error></stream:stream>""

> was the unexpected behavior? What was the expected result?

""<stream:stream id='12847806584895138227' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'>stream:errorsyntax error</stream:error></stream:stream>""

Best regards,

**Comment by licaon-kter** [comment]
You need a proper XMPP client to access the server, not a browser.

Eg. Gajim

/Close as invalid

**Comment by abdelhafiddahhani** [comment]
Thank you Mr licaon-kter how can i get it plz

**Comment by abdelhafiddahhani** [comment]
and why it works for him !!!

https://www.youtube.com/watch?v=usFTiqHR0K8 lok at this

**Comment by cromain** [comment]
admin page is usually served on port 5280.
port 5222 is XMPP stream

**Comment by licaon-kter** [comment]
@abdelhafiddahhani `apt install gajim` I guess

**Comment by abdelhafiddahhani** [comment]
Thank you Mr. cromain .. it doesn't work

**Comment by abdelhafiddahhani** [comment]
licaon-kter but firstly i want to access to the admin page .. how i can do that becaus in the video its work for him .. me noo and i folowed the same step !!

**Comment by licaon-kter** [comment]
@abdelhafiddahhani No idea, maybe the docs help: https://docs.ejabberd.im/admin/configuration/
