### ISSUE TITLE
ejabberdctl status Failed RPC connection to the node ejabberd@ubuntu: nodedown

### ISSUE THREAD

**Issue by abdelhafiddahhani** [processone/ejabberd#2263]
> What version of ejabberd are you using?
Ejabberd 18.01

> What operating system (version) are you using?

ubuntu 17

> How did you install ejabberd (source, package, distribution)?

apt-get ..

> What did not work as expected? Are there error messages in the log? What
when i add connexion with mysql database in ejabberd.yml i  execute this command ejabberdctl status i got this error
{{{ ejabberdctl status Failed RPC connection to the node ejabberd@ubuntu: nodedown }}}
> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
Read the logs please.

**Comment by abdelhafiddahhani** [comment]
thank you 
Logs:

2018-02-02 04:29:21.324 [error] <0.65.0>@misc:try_read_file:210 Failed to read /etc/ejabberd/example_com.pem: no such file or directory
2018-02-02 04:29:21.324 [error] <0.65.0>@ejabberd_config:validate_opts:1016 ignoring option 'domain_certfile' with invalid value: <<"/etc/ejabberd/example_com.pem">>
2018-02-02 04:29:21.498 [error] <0.325.0>@ejabberd_pkix:mk_cert_state:244 failed to read certificate from /etc/ejabberd/server.pem: no PEM encoded certificates found
2018-02-02 04:29:21.543 [error] <0.325.0>@ejabberd_pkix:mk_cert_state:244 failed to read certificate from /etc/ejabberd/server.pem: no PEM encoded certificates found
2018-02-02 04:29:21.549 [critical] <0.363.0>@ejabberd:exit_or_halt:131 failed to start application 'p1_mysql': {error,
                                         {"no such file or directory",
                                          "p1_mysql.app"}}

**Comment by zinid** [comment]
The error means ejabberd is not compiled with mysql support.

**Comment by abdelhafiddahhani** [comment]
and what i will do to fixe it plz

**Comment by abdelhafiddahhani** [comment]
08:40:46.172 [info] Application crypto started on node ejabberd@ubuntu
08:40:46.176 [info] Application sasl started on node ejabberd@ubuntu
08:40:46.179 [info] Application asn1 started on node ejabberd@ubuntu
08:40:46.179 [info] Application public_key started on node ejabberd@ubuntu
08:40:46.197 [info] Application ssl started on node ejabberd@ubuntu
08:40:46.199 [info] Application p1_utils started on node ejabberd@ubuntu
08:40:46.208 [info] Application fast_yaml started on node ejabberd@ubuntu
08:40:46.218 [info] Application fast_tls started on node ejabberd@ubuntu
08:40:46.228 [info] Application fast_xml started on node ejabberd@ubuntu
08:40:46.239 [info] Application stringprep started on node ejabberd@ubuntu
08:40:46.241 [info] Application xmpp started on node ejabberd@ubuntu
08:40:46.250 [info] Application cache_tab started on node ejabberd@ubuntu
08:40:46.250 [info] Loading configuration from /etc/ejabberd/ejabberd.yml
08:40:46.261 [warning] value '10000' of option 'outgoing_s2s_timeout' is too big, are you sure you have set seconds?
08:40:46.738 [info] Application mnesia started on node ejabberd@ubuntu
08:40:46.760 [info] FQDN used to check DIGEST-MD5 SASL authentication: ubuntu
08:40:46.804 [error] failed to read certificate from /etc/ejabberd/server.pem: no PEM encoded certificates found
08:40:46.805 [warning] listening option 'resend_on_timeout' is deprecated: use 'resend_on_timeout' option from mod_stream_mgmt module
08:40:46.829 [warning] certificate from /etc/ejabberd/ejabberd.pem is invalid: self-signed certificate in the chain
08:40:46.831 [error] failed to read certificate from /etc/ejabberd/server.pem: no PEM encoded certificates found
08:40:46.841 [critical] failed to start application 'p1_mysql': {error,
                                         {"no such file or directory",
                                          "p1_mysql.app"}}
failed to start application 'p1_mysql': {error,
                                         {"no such file or directory",
                                          "p1_mysql.app"}}

Crash dump is being written to: /var/log/ejabberd/erl_crash_20180202-084041.dump...done

**Comment by zinid** [comment]
> and what i will do to fixe it plz

Read the documentation? Join ejabberd chatroom, ask on forum? Issue tracker is not a helpdesk.

**Comment by debalance** [comment]
FWIW: apt install erlang-p1-mysql (which is to say: RTFM!)
