### ISSUE TITLE
Last Activity returns 0 seconds for unavailable sessions

### ISSUE THREAD

**Issue by hhravn** [processone/ejabberd#2265]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian GNU/Linux 8 (jessie)

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

I recently upgraded from 16.09 to 18.01, and now XEP-0012 returns 0 seconds even for a session that has been set to `unavailable`, e.g.

```
$ejabberdctl user_sessions_info 5a701b0e952602000f9fb3d2 domain.com
websocket	172.21.0.1	46758	undefined	ejabberd@localhost	8	unavailable	react-native-xmpp-client
```

The moment i kick the user, XEP-0012 will start correctly returning the last time any activity was seen from the user.

**Comment by hhravn** [comment]
Ok, as far as i can figure out, i end up about here;

https://github.com/processone/ejabberd/blob/4b012a99d2bdd6d22f05676e9a7989409e314fca/src/mod_last.erl#L226

Which means that the user has resources that are not offline. What exactly does it take for a session to be offline? I noticed that setting priority < 0 results in get_presence returning `nil` for priority after we upgraded.

**Comment by badlop** [comment]
> a session that has been set to unavailable

And how are you able to set presence to Unavailable, but still keep the XMPP session alive?

When I set presence to unavailable, ejabberd immedtialely closes the XMPP session:
```xml
<presence type='unavailable'>
  <priority>8</priority>
  <status>testing the disconnection reason22</status>
</presence>
```

**Comment by hhravn** [comment]
We're connecting from an app, and leave our websocket open when the app goes to the background, indicating that we're offline by setting `presence=unavailable, priority=-1`. By not disconnecting the session entirely, we reuse it by setting `presence=available, priority=1`  if the socket is still intact when we come back from the background. This worked fine on 16.09. 

Do you have a suggestion for a better strategy? Should we simply disconnect entirely when going to the background?

**Comment by badlop** [comment]
Sending a "presence=unavailable" is a graceful presence broadcasted to the contacts [1], but ejabberd does not unbind the resource from the stream, so it doesn't close the session, nor closes the stream. That's why, in the code you referenced, if there's any resource, whatever its kind, the user is considered to be online.

Is that the expected behavor according to the protocols, or is a bug in ejabberd? Sorry, I don't know. Also I don't know if there's a more recomended way for you to achieve what you want.

Let's see if somebody else can help here. 
[1] https://tools.ietf.org/html/rfc6121#section-4.5.1
[2] https://tools.ietf.org/html/rfc6120#section-7

**Comment by hhravn** [comment]
I guess i always just assumed that the semantics were the same as in mod_offline, in that `priority <= 0` would mean that the session is offline ;)

The [XEP](https://xmpp.org/extensions/xep-0012.html#offline) was not entirely clear to me in its wording before;

> If the user has at least one connected or available resource when the server receives the request, the response MUST (subject to local security policies) contain an empty <query/> element whose 'seconds' attribute is set to a value of '0'.

but reading it again, i think it means that if session (socket in this case) is alive the server _must_ return `seconds=0`, even if `type=unavailable`.

Anyways, thanks for having a look at it. I guess i'll see if someone has anything to add in the next few days and, if not, apply the workaround of disconnecting the session entirely, even when the app is only left momentarily.
