### ISSUE TITLE
Unable to publish PubSub event

### ISSUE THREAD

**Issue by jovanpn** [processone/ejabberd#2267]
> What version of ejabberd are you using?
1711 (tried on 1701 also on other machine with the same problem)

> What operating system (version) are you using?
Linux Debian Jessie 3.16.39-1 (2016-12-30)

> How did you install ejabberd (source, package, distribution)?
generic installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I’m having problems to publish an event to a PubSub service. I'm using Smack Java library on application side and eJabberd 1711 on the server side (I also tried eJabberd server 1701 on an other machine).
I successfully create node on eJabberd server with deliver_payloads and persist_items set to false, as it is required configuration by XEP-0060 specification and everything about the node is ok which I can confirm by reading node configuration:

> [(FORM_TYPE:http://jabber.org/protocol/pubsub#node_config)
(pubsub#deliver_payloads:0)
(pubsub#notify_config:0)
(pubsub#notify_delete:0)
(pubsub#notify_retract:1)
(pubsub#purge_offline:0)
(pubsub#persist_items:0)
(pubsub#max_items:10)
(pubsub#subscribe:1)
(pubsub#access_model:open)
(pubsub#roster_groups_allowed:NOT SET)
(pubsub#publish_model:publishers)
(pubsub#notification_type:headline)
(pubsub#max_payload_size:60000)
(pubsub#send_last_published_item:on_sub_and_presence)
(pubsub#deliver_notifications:1)
(pubsub#presence_based_delivery:0)
(pubsub#itemreply:none)]

Then when I try to publish an event with next iq:
> <iq to='pubsub.fm.ch' id='Z3Hsq-23' type='set'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'/>
    </pubsub>
</iq>

I get bad-request error from the server with pubsub-specific condition error of item-required:

> <iq xml:lang='en' to='***@fm.ch/***' from='pubsub.fm.ch' type='error' id='Z3Hsq-23'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'/>
    </pubsub>
    <error code='400' type='modify'>
        <item-required xmlns='http://jabber.org/protocol/pubsub#errors'/>
        <bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    </error>
</iq>

which is strange because by specification definition:

> 7.1.3.6 Request Does Not Match Configuration
...
> - If the event type is persistent (either event notification or payload) and the publisher does not include an item, the service MUST bounce the publication request with a `<bad-request/>` error and a pubsub-specific error condition of `<item-required/>`.

item-required error should be sent back to the publisher in case that event type is persistent, which is not the case here as seen from node configuration.

I then tried to publish an event with empty item like:
> <iq to='pubsub.fm.ch' id='gG7r4-23' type='set'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'>
            <item/>
        </publish>
    </pubsub>
</iq>

and then I get wrong answer from the server again:
> <iq xml:lang='en' to='***@fm.ch/***' from='pubsub.fm.ch' type='error' id='gG7r4-23'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'>
            <item/>
        </publish>
    </pubsub>
    <error code='400' type='modify'>
        <payload-required xmlns='http://jabber.org/protocol/pubsub#errors'/>
        <bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    </error>
</iq>

Again, by specification:
> 7.1.3.6 Request Does Not Match Configuration
...
> - If the event type is payload (either persistent or transient) and the publisher does not include a payload, the service SHOULD bounce the publication request with a `<bad-request/>` error and a pubsub-specific error condition of `<payload-required/>`.

it means that my event is now considered as payload event, which is again wrong by node configuration set.

At the end, if I then publish full payload event like:
> <iq to='pubsub.fm.ch' id='RCmTX-23' type='set'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'>
            <item id='testItem'>
                <payload>test</payload>
            </item>
        </publish>
    </pubsub>
</iq>

then I get answer from the server:
> <iq xml:lang='en' to='***@fm.ch/***' from='pubsub.fm.ch' type='error' id='RCmTX-23'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
        <publish node='testNode'>
            <item id='testItem'>
                <payload>test</payload>
            </item>
        </publish>
    </pubsub>
    <error code='400' type='modify'>
        <item-forbidden xmlns='http://jabber.org/protocol/pubsub#errors'/>
        <bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    </error>
</iq>

which is finally correct answer by specification:

> 7.1.3.6 Request Does Not Match Configuration
...
> - If the event type is notification + transient and the publisher provides an item, the service MUST bounce the publication request with a `<bad-request/>` error and a pubsub-specific error condition of `<item-forbidden/>`.

Can anyone tell me if I have set something wrong, am I doing something wrong or there is some problem with my server?

I also posted this problem on: [https://www.ejabberd.im/forum/29776/unable-publish-pubsub-event](url)

**Comment by cromain** [comment]
Publish an event (no item, and no persistence) is an edge case of pubsub, i think tests does not cover this particular case (wonder what it's used for by the way...). This looks a bug anyway. After a quick check here is what can i say:

- Corresponding switch raises only if persist_items or deliver_payloads is true. This is clearly unexpected reply but test looks good. (i need to investigate)
- second case is due to a wrong test, which lacks test on deliver_payloads (i'll fix this)
- third case is correct answer indeed.

**Comment by jovanpn** [comment]
Thanks for answering Christophe!
I'm not Erlang developer but I've followed the functions call path from the Java Smack library and for the second case I think that the bug is in mod_pubsub.erl file, function publish_item, then in the Action subfunction (starting at line 1771) and finally in the `if` statement section

> (PayloadCount == 0) and (Payload == []) ->
		    {error, extended_error(xmpp:err_bad_request(),
					   err_payload_required())};

I think there should be added `DeliverPayloads == true` as requirement in order to count this case as an error.
For the first case, it looks to me that in the same section everything is ok, so the `item_required` error might come from some other place in the code, like iq_pubsub function.
One other thing though is that maybe it would be enough just to rearrange some condition tests in `if` statement.
As I've said, I'm not Erlang developer so I don't know if my suggestions are good enough, but I'm just trying to be helpful.
