### ISSUE TITLE
offline_message_hook crashed when running my custom module

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2269]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 6

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have recently updated ejabberd from 16.09 to 18.01. In my custom module practically nothing is working. offline_message_hook crashed when running, because in every hook or function is using xmpp library which don't have clear solution about making custom namespace stanzas (i tried yesterday making my own xmpp spec but ended up with erlang critical error when started ejabberd).

I moved to old jlib library but it is not fully supported, for example in offline_message_hook expects tupple {_Action, Packet} packet may be one of already defined record(iq, presence, message). this records is not included in my module. if i include jlib and xmpp .hrl files together it throws error.

i don't know what to do. i'm thinking of downgrade ejabberd to older 16.09 version, i know it's bad idea, but i have no other choice. if anyone could help me to solve my problem , i would be very glad

**Comment by zinid** [comment]
It seems like you have a lot of questsion, it's probably better to join ejabberd@conference.process-one.net in order to get all the answers. Because it's very hard to consult on github.

**Comment by ltAldoRaine** [comment]
if someone has same problem, how thay could find solution, i think these is problem for everyone who is developing custom modules. how to join?

**Comment by zinid** [comment]
> i think these is problem for everyone

What problem? All I see in your "report" is the cry that "nothing works".

**Comment by ltAldoRaine** [comment]
> offline_message_hook crashed when running, because in every hook or function is using xmpp library which don't have clear solution about making custom namespace stanzas

this is offline message hook function parameters {_Action, #message{from = From, to = To} = Packet} i don't have this message record , because xmpp.hrl is not included in my module.

i had to used jlib.hrl, because xmpp library doesn't have clear solution how to make custom nms stanzas as i sad :) :) 

it's not cry it's a problem :)

**Comment by ltAldoRaine** [comment]
ejabberd is using xmpp.hrl records #message, #Iq, #presence which i don't have defined so i think these is the reason why everything is messed up

**Comment by zinid** [comment]
So, did you read [README](https://github.com/processone/xmpp/blob/master/README.md)?

**Comment by ltAldoRaine** [comment]
Yes, of course :)

i commented on this issue about xmpp codec registering

https://github.com/processone/xmpp/issues/9#issuecomment-363206732

**Comment by zinid** [comment]
Commented there.
