### ISSUE TITLE
Querying Subscribed MUC SUB Events

### ISSUE THREAD

**Issue by melvinkcx** [processone/ejabberd#2272]
In the [muc sub documentation](https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#list-of-subscriptions), it does not mention how can we get the event types of a MUC that we have subscribed to.

How can we query about the event types about a particular MUC a user subscribed to?

Thanks in advance.

**Comment by badlop** [comment]
You are right, it is possible for a user to get the list of rooms where he has some subscription... but that doesn't return the events he's subscribed to, and there's no way to query a specific room to get the subscribed events.
