### ISSUE TITLE
PubSub Multicast support

### ISSUE THREAD

**Issue by Raja021084** [processone/ejabberd#2273]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

RHEL 6

> How did you install ejabberd (source, package, distribution)?
RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is it possible to multicast message to different nodes? Lets say I have node1 and node2. Can I publish a message to both node1 and node2 in single command?

**Comment by cromain** [comment]
no you can not, as recipient of your publication is the pubsub service (not the pubsub node directly)
