### ISSUE TITLE
os_mon seems to be a dependency, but it is not listed in rebar.config

### ISSUE THREAD

**Issue by bowlofeggs** [processone/ejabberd#2279]
Hello!

I maintain the ejabberd package in Fedora, and a user [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1542927) that os_mon is a required dependency and that the RPM didn't require it. I was able to reproduce it by removing os_mon from my system:

```
2018-02-13 11:38:01.524 [critical] <0.62.0>@ejabberd:exit_or_halt:131 failed to start application 'os_mon': {error,
                                       {"no such file or directory",
                                        "os_mon.app"}}
```

Should os_mon be listed as a dependency in rebar.config?

**Comment by zinid** [comment]
This application is included in Erlang/OTP: http://erlang.org/doc/apps/os_mon/index.html
Seems like you have Erlang built without `os_mon` support or something like that.

**Comment by bowlofeggs** [comment]
On 02/13/2018 12:08 PM, Evgeny Khramtsov wrote:
> This application is included in Erlang/OTP:
> http://erlang.org/doc/apps/os_mon/index.html
> Seems like you have Erlang built without |os_mon| support or something
> like that.

As far as I can tell, it is an optional component of Erlang since I was
able to start ejabberd without it. Perhaps the way it is split up is
somewhat Fedora specific? I'm not particularly familiar with Erlang so
my knowledge isn't very strong. If you think we should not worry about
it, feel free to close this issue. Thanks!

**Comment by zinid** [comment]
I cannot tell about Fedora, but in Debian erlang-os-mon is a separate package and new ejabberd versions depend on it.

**Comment by zinid** [comment]
I close the ticket since we really cannot do anything with it, this is specific to local Erlang installation.
