### ISSUE TITLE
user last activity doesn't work correctly

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2282]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 6

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

after disconnecting from ejabberd user last activity row is still exists in last table.

and value in seconds column is not 0

**Comment by zinid** [comment]
And the database is?

**Comment by ltAldoRaine** [comment]
sorry.. mysql

**Comment by ltAldoRaine** [comment]
any ideas ?

**Comment by cromain** [comment]
i don't understand what's the problem.
- mod_last is enabled to use mysql backend
- user connects, then disconnect
- last table has entry with non 0 value

this all sounds good. what's the problem ?

**Comment by ltAldoRaine** [comment]
last activity is when user last time goes to offline yes? in ejabberd 16.09 when user comes to online record for that user in last table had been removed.. but as  i figured out last activity info stays permananltly in newer ejabberd
