### ISSUE TITLE
User are online but unable to deliver message 

### ISSUE THREAD

**Issue by zaidshaikh112** [processone/ejabberd#2283]
Ejabber15.11 on Ubuntu and install from official site of ejabberd my message are deliver all time to 1 to 1 users but some time when users are online their messages are not delivering on same time like previous messages delivered and there were no errors in error log shows to trace the issue please help me out with this 

advance thanks

**Comment by zinid** [comment]
The version you use is severely outdated, it's hard to say which of already fixed bugs you're facing.
