### ISSUE TITLE
Node name in random ID.

### ISSUE THREAD

**Issue by kabirhaxor** [processone/ejabberd#2284]
> What version of ejabberd are you using?
Ejabberd 18.0.1

> What operating system (version) are you using?
Ubuntu

> How did you install ejabberd (source, package, distribution)?
Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
<iq to="admin@localhost/Miranda" from="admin@localhost" type="get" id="rr-1518825844956-5680070232441450020-1cJLHxJbeM+DD6izWcMAEjhhlZw=-ejabberd@localhost">
<ping xmlns="urn:xmpp:ping" />
</iq>
```

Ping request xml contains ejabberd@localhost (my ejabberd node name). Anyone know how to change/modify this random generated ID text.

**Comment by zinid** [comment]
You cannot hide it.

**Comment by kabirhaxor** [comment]
I don't wana hide. I just want to change the text. Is this possible? Sir.

**Comment by zinid** [comment]
I just fixed it, ejabberd will no longer be putting node names inside "id" attributes.
