### ISSUE TITLE
MySQL schema incompatibility: server_host nullable

### ISSUE THREAD

**Issue by mieciu** [processone/ejabberd#2289]
> What version of ejabberd are you using?

`18.1.0`

> How did you install ejabberd (source, package, distribution)?

It's installed as dependency in Elixir project 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm shooting an API request to create a chatroom:
```
curl -XPOST http://localhost:5280/api/create_room -d '{ "name": "room_a", "service": "xmpp.com", "host": "xmpp.com" }'
```
When switching log level to debug, I can clearly see that there's a query to DB
```
17:32:40.426 [debug] Executing command mod_muc_admin:create_room with Args=[<<"room_a">>,<<"xmpp.com">>,<<"xmpp.com">>]
17:32:40.426 [debug] SQL: "begin;"
17:32:40.427 [debug] SQL: "UPDATE muc_room SET opts='[]' WHERE name='room_a' AND host='xmpp.com'"
17:32:40.427 [debug] SQL: "INSERT INTO muc_room(name, host, opts) VALUES ('room_a', 'xmpp.com', '[]');"
17:32:40.428 [debug] SQL: "delete from muc_room_subscribers where room='room_a' and host='xmpp.com'"
17:32:40.428 [debug] SQL: "commit;"
```
However, the room is not created in MySQL:
```
mysql> select * from muc_room;
Empty set (0.00 sec)
```

I've tried replicating that query manually and it turned out that there's a schema incompatibility 
```
iex(7)> :p1_mysql.fetch(:myid, 'INSERT INTO muc_room(name, host, opts) VALUES (\'room_a\', \'xmpp.com\', \'[]\')')
p1_mysql: fetch "INSERT INTO muc_room(name, host, opts) VALUES ('room_a', 'xmpp.com', '[]')" (id myid)
{:error,
 {:p1_mysql_result, [], [], 0,
  '#HY000Field \'server_host\' doesn\'t have a default value'}}
```

So the only way to solve this issue is to allow `server_host` be nullable:
```
mysql> ALTER TABLE muc_room MODIFY server_host text;
Query OK, 0 rows affected (0.08 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> describe muc_room
    -> ;
+-------------+------------+------+-----+-------------------+-------+
| Field       | Type       | Null | Key | Default           | Extra |
+-------------+------------+------+-----+-------------------+-------+
| name        | text       | NO   | MUL | NULL              |       |
| host        | text       | NO   |     | NULL              |       |
| server_host | text       | YES  |     | NULL              |       |
| opts        | mediumtext | NO   |     | NULL              |       |
| created_at  | timestamp  | NO   |     | CURRENT_TIMESTAMP |       |
+-------------+------------+------+-----+-------------------+-------+
5 rows in set (0.01 sec)
```

This can be of course easily solved, but the biggest pain is that:
* API has not responded with an error message -> at the end, room creation *failed*
* There's no error message in logs -> I can only see query itself ( which was wrong and resulted in error).

**Comment by alexeyshch** [comment]
You probably used `mysql.new.sql` schema to create muc_room table, but ejabberd was compiled without `--enable-new-sql-schema` configure option.  The next ejabberd version will include an option to enable new schema, so you'll be able to add this line to `ejabberd.yml` to use `mysq.new.sql` without recompilation:
```YML
new_sql_schema: true
```
