### ISSUE TITLE
Problem with Persistent MUC

### ISSUE THREAD

**Issue by nandinibhaduri** [processone/ejabberd#2291]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Windows 7 Professional

> How did you install ejabberd (source, package, distribution)?

Installer

> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

1. Creating Persistent Room using REST API: Doesn't persist. I have tried both db_type: sql and db_type: mnesia. With db_type: sql I see that no data is getting saved in the muc_room table.

2. Creating Persistent Room using converse.js client: All is well when db_type: mnesia, but when I am trying the same with db_type: sql, I am getting the following error when restarting ejabberd (Note: I am using SQL Server database) :

```
2018-02-20 15:00:55 =CRASH REPORT====
  crasher:
    initial call: mod_muc:init/1
    pid: <0.5069.0>
    registered_name: []
    exception exit: {{{badmatch,{error,{1,erl_scan,{string,34,"admin\">>},\n {all"}},1}},[{ejabberd_sql,decode_term,1,[{file,"src/ejabberd_sql.erl"},{line,250}]},{mod_muc_sql,'-get_rooms/2-fun-3-',2,[{file,"src/mod_muc_sql.erl"},{line,110}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{mod_muc,load_permanent_rooms,6,[{file,"src/mod_muc.erl"},{line,626}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_muc,init,1,[{file,"src/mod_muc.erl"},{line,236}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_gen_mod_sup,ejabberd_sup,<0.4654.0>]
    messages: []
    links: [<0.5059.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 2824
  neighbours:
```
 This is the data in the opts column:
[{title,<<>>},\n {description,<<\"admin\">>},\n {allow_change_subj,true},\n {allow_query_users,true},\n {allow_private_messages,true},\n {allow_private_messages_from_visitors,anyone},\n {allow_visitor_status,true},\n {allow_visitor_nickchange,true},\n {public,true},\n {public_list,true},\n {persistent,true},\n {moderated,true},\n {members_by_default,true},\n {members_only,false},\n {allow_user_invites,false},\n {password_protected,false},\n {captcha_protected,false},\n {password,<<\"admin\">>},\n {anonymous,true},\n {logging,false},\n {max_users,200},\n {allow_voice_requests,true},\n {allow_subscription,false},\n {mam,false},\n {presence_broadcast,[moderator]},\n {voice_request_min_interval,1800},\n {vcard,<<>>},\n {captcha_whitelist,[]},\n {affiliations,[{{<<\"admin\">>,<<\"example\">>,<<>>},{owner,<<>>}}]},\n {subject,<<>>},\n {subject_author,<<>>},\n {subscribers,[]}]

**Comment by nandinibhaduri** [comment]
From a different issue https://github.com/processone/ejabberd/issues/1748 I got some information and tried changing the configuration to -

```
modules:
  mod_mam:
    db_type: sql
    default: always
  mod_muc:
    db_type: sql
    default_room_options:
      persistent: true
      mam: true
```
(I don't need muc default option to be persistent though) and tried creating a room using the rest api and the ejabberdctl, but in both cases the groups created were not persistent (I checked from the admin web console) and of course it wasn't getting saved in the database.

But when I create room using REST API with options like so - 

```
{
  "name": "testapi",
  "service": "conference.eteam",
  "host" : "localhost",
  "options": [
    {
      "name": "persistent",
      "value": "true"
    },
    {
      "name": "mam",
      "value": "true"
    },
    {
      "name": "title",
      "value": "test"
    },
    {
      "name": "description",
      "value": "Testing for Notification Group"
    }
  ]
}
```
I see from the web admin panel that the group created is persistent, but it doesn't get saved to the database and disappears when I restart the server.

I am kind of stuck here. It would be great if you can suggest me a solution.

**Comment by badlop** [comment]
I've compiled ejabberd 17.08 from git, installed and configured:
```yaml
modules:
  mod_muc:
    host: "muc.@HOST@"
    default_room_options:
      allow_subscription: true
      persistent: true
```
Then I run:
```
$ ejabberdctl create_room room1 muc.localhost localhost
```
Using the debug console, I confirm the room is stored:
```
> ets:tab2list(muc_room).
[{muc_room,{<<"room1">>,<<"muc.localhost">>},
           [{allow_subscription,true},{persistent,true}]}]
```
After restaring ejabberd, I check again that table, the room is there. I login with a client, and the room is listed in the Service Discovery.
