### ISSUE TITLE
Need help with process_rosteritems

### ISSUE THREAD

**Issue by tmany** [processone/ejabberd#2293]
Hello, guys!
I need help with ejabberdctl process_rosteritems.
I'm under spam, as all xmpp servers now. And for years, there are a lot of spam xmpp domains in my DB. I want to delete all this sh**t domains from all users rosters, but can't launch ejabberdctl process_rosteritems correctly.

My ejabberd is 14.07, Debian 9, 64. Mnesia.
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false], Eshell V6.2

Help me, please, to launch process_rosteritems.

I need to:
1. delete roster items with domain @df.ru from all user roster's 
**for example,** to delete all jd854h@df.ru, la93@df.ru, mznr59@df.ru, zbjw7@df.ru and so on from my users rosters
2. my node name is ejabberd@s123456
3. subs - any

thanks for help!

**Comment by tmany** [comment]
Tried
ejabberdctl process_rosteritems list any any admin@localhost any

Receive error:
Problem 'error badarg' occurred executing the command.
Stacktrace: [{erlang,binary_to_list,["admin@localhost"],[]},
 {jlib,string_to_jid,1,[{file,"src/jlib.erl"},{line,217}]},
{mod_admin_extra,'-decide_rip_jid/2-fun-0-',3,
[{file,"src/mod_admin_extra.erl"},{line,1558}]},
{lists,any,2,[{file,"lists.erl"},{line,1223}]},
{mod_admin_extra,decide_rip,2,
[{file,"src/mod_admin_extra.erl"},{line,1546}]},

**Comment by tmany** [comment]
I have found some info here https://support.process-one.net/browse/EJAB-1716
But I don't unserdtand, what I should I do.

**Comment by tmany** [comment]
Do somebody slve this task? Or can you help me, pls?

**Comment by cromain** [comment]
@badlop can you check this

**Comment by badlop** [comment]
In my test server, with host "example.org", I have only one user called "user1", and it has as contact "user2@other.com". I can list it this way:
```
$ ejabberdctl process_rosteritems list any any *@example.org *@other.com
There are 1 roster items in total.
Matches: user1@example.org user2@other.com
Progress 100% - visited 1 - deleted 1
user1@example.org user2@other.com
```

**Comment by tmany** [comment]
But why I receive such error

# ejabberdctl process_rosteritems list any any any any
There are 3095925 roster items in total.
Problem 'error badarg' occurred executing the command.
Stacktrace: [{erlang,binary_to_list,["*"],[]},
             {jlib,string_to_jid,1,[{file,"src/jlib.erl"},{line,217}]},
             {mod_admin_extra,'-decide_rip_jid/2-fun-0-',3,
                              [{file,"src/mod_admin_extra.erl"},{line,1558}]},
             {lists,any,2,[{file,"lists.erl"},{line,1223}]},
             {mod_admin_extra,decide_rip,2,
                              [{file,"src/mod_admin_extra.erl"},{line,1546}]},
             {mod_admin_extra,rip,4,
                              [{file,"src/mod_admin_extra.erl"},{line,1508}]},
             {mod_admin_extra,rosteritem_purge,1,
                              [{file,"src/mod_admin_extra.erl"},{line,1499}]},
             {mod_admin_extra,process_rosteritems,5,
                              [{file,"src/mod_admin_extra.erl"},{line,1483}]}]

The same result of 
# ejabberdctl process_rosteritems list any any *@example.org *@@example.org

@badlop How can I solve this? Help me please.

**Comment by prefiks** [comment]
This was fixed in never version that you have.

**Comment by tmany** [comment]
Guys, advice me, how can I update process_rosteritems / mod_admin without updating ejabberd?

**Comment by zinid** [comment]
@tmany you cannot, we don't provide fixes for previous versions.
