### ISSUE TITLE
ejabberd is not compiled with SIP support ...

### ISSUE THREAD

**Issue by Talisker69** [processone/ejabberd#2294]
Hi Every Body
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Ubuntu server 16.04 (32 Bits)

> How did you install ejabberd (source, package, distribution)?

Source from GIT

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I can't add ejabberd_sip, i've got the following log message :  
@ejabberd_sip:log_error:32 ejabberd is not compiled with SIP support ...

What I need to add (options) when I compile the source ? Do I need to reinstall everything ?
Option like "--enable-all" during the build configuration ?

Thanks

**Comment by zinid** [comment]
You need reconfigure with `--enable-sip` and recompile, yes.

**Comment by Talisker69** [comment]
Thanks a lot
