### ISSUE TITLE
my friend from 2 days configured ejabberd. in final turn server don't exist.  failed to process callback function ejabberd_stun:udp_init(

### ISSUE THREAD

**Issue by gurussia** [processone/ejabberd#2303]
HI guys.

Shit real shit. How is that possible that my friend didn't go to play football and stay try configure ejabberd 18.0.-2 ubuntu development version and today he find it comment. He call me and comment: 

18:26:24.795 [info] Start accepting UDP connections at 0.0.0.0:8443 for ejabberd_stun

18:26:24.809 [critical] failed to start application 'stun': {error,
                                     {"no such file or directory","stun.app"}}
18:26:24.809 [error] failed to process callback function ejabberd_stun:udp_init(#Port<0.10150>, [inet,{auth_type,user},{dhfile,<<"/etc/ejabberd/dh2048.pem">>},{turn_max_port,40000},{turn_min_port,30000},{turn_max_allocations,10},{turn_ip,{5,23,56,333}},{use_turn,true},{certfile,<<"/etc/ejabberd/ejabberd.pem">>},{tls,true},{ip,{0,0,0,0}}]): {'EXIT',{application_start_failed,[{ejabberd,exit_or_halt,2,[{file,"src/ejabberd.erl"},{line,137}]},{ejabberd_stun,udp_init,2,[{file,"src/ejabberd_stun.erl"},{line,60}]},{ejabberd_listener,init_udp,6,[{file,"src/ejabberd_listener.erl"},{line,120}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}

So what it comment: turn is not compiled and stun is not compiled in ubuntu repository.

apt-get install ejabberd

How is that possible

**Comment by weiss** [comment]
> turn is not compiled and stun is not compiled in ubuntu repository.

This is not the right issue tracker for Ubuntu packaging questions, but you're probably missing this package:

https://packages.ubuntu.com/artful/erlang-p1-stun
