### ISSUE TITLE
CRASH REPORT: no function clause matching lists:map <<"/etc/ejabberd/upload">>)

### ISSUE THREAD

**Issue by gurussia** [processone/ejabberd#2305]
why when it someone apt-get install ejabberd it not install the dependency who person will know why it don't work
01:46:42.899 [error] CRASH REPORT Process <0.66.0> with 0 neighbours exited with reason: no function clause matching lists:map(#Fun<gen_iq_handler.4.31734626>, <<"/etc/ejabberd/upload">>) line 1238 in application_master:init/4 line 134
01:46:42.900 [info] Application ejabberd exited with reason: no function clause matching lists:map(#Fun<gen_iq_handler.4.31734626>, <<"/etc/ejabberd/upload">>) line 1238

**Comment by zinid** [comment]
Please stop creating such silly issues
1) we don't produce ejabberd packages for apt repositories
2) we don't know what ejabberd version you're using
3) you didn't provide errors from crash.log
4) you didn't describe the problem and it seems like you have two unrelated problems, but it's hard to say from the info you provided

**Comment by gurussia** [comment]
Please stop creating such silly issues
