### ISSUE TITLE
how to send message from one user to another inside ejabberd module

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2306]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to send message from one user to another. I don't want to send message from client and for that i am using mod_rest for catching HTTP requests, but i can't properly route message stanza from one user to another.

I tried to call mod_mam:user_send_packet, but message haven't saved in archive for reciever.

Is there any clean way to solve these problem?

**Comment by cromain** [comment]
hello

this is not a bug nor an issue. you should use forums, mailing lists of chatrooms for this.
read the code, check how modules are routing messages...

**Comment by ltAldoRaine** [comment]
i tried to use route function, but it didn’t save message in archive for sender

**Comment by ltAldoRaine** [comment]
[https://github.com/processone/ejabberd/issues/2307](url)
