### ISSUE TITLE
 ejabberd_router:route/1 doesn't initiate mod_mam:user_send_packet

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2307]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

centos 6

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```erl
  Pkt = #message{
        id = <<"asda4545w3e4563e456asdasd56asd">>,
        type = chat,
        lang = <<"en">>,
        from = From,
        to = To,
        body = [
          #text{
            data = <<"hello">>
          }
        ],
        sub_els = [
          #chatstate{type = active},
          #receipt_request{}
        ]},
  ejabberd_router:route(Pkt),
```

**Comment by ltAldoRaine** [comment]
https://stackoverflow.com/questions/48986462/how-to-send-message-from-one-user-to-another-inside-ejabberd-module

**Comment by zinid** [comment]
Three unrelated errors in just `Pkt` structure:
1) avoid setting `lang` attribute
2) use randoms:get_string() for generating `id` attribute
3) use `xmpp:mk_text/1` instead of setting `body` explicitly via `#text{}` structure

Example:
```erl
Pkt = #message{type = chat, from = From, to = To,
               id = randoms:get_string(),
               body = xmpp:mk_text(<<"hello">>),
               sub_els = [#chatstate{type = active}, #receipt_request{}]}
```

**Comment by zinid** [comment]
Regarding your question: you message doesn't get stored in neither `From` nor `To` archive?

**Comment by ltAldoRaine** [comment]
my problem was that message doesn't get stored for sender.. but with this 
part of code 

`ejabberd_hooks:run_fold(user_send_packet, LServer, {Pkt, C2SState}, []),
 ejabberd_router:route(Pkt)`

i archived for both sides.. also carboncopy is working perfectly and mod_mam user_send_packet archives message for sender

**Comment by ltAldoRaine** [comment]
but i though ejabberd_router:route/1 initiate not only user_recieve_packet also user_send_packet...gess i was wrong..maybe it's not a issue
