### ISSUE TITLE
Vcard not showing when request it

### ISSUE THREAD

**Issue by deounix** [processone/ejabberd#2308]
> What version of ejabberd are you using?
2.1.13

> What operating system (version) are you using?
Centos 7

> How did you install ejabberd (source, package, distribution)?
Source

There's an error in Vcard when I'm deleting all vcard files in var/lib/ejabberd and restart ejabberd it's working 100% after that it's not responding again.

```
<iq type="get" to="test@conference.example.com/iSiDa" id="aacea">
	<query xmlns="jabber:iq:version"/>
</iq>

<iq type="get" to="test@conference.example.com/iSiDa" id="aacfa">
	<time xmlns="urn:xmpp:time"/>
</iq>

<iq type="get" to="test@conference.example.com/iSiDa" id="aad0a">
	<vCard xmlns="vcard-temp"/>
</iq>

<iq from="test@conference.example.com/iSiDa" type="result" to="deounix@example.com/zeroTechnology" id="aacea">
	<query xmlns="jabber:iq:version">
	<name>iSida</name>
	<os>Python V2.7.14 [Dec 18 2017]</os>
	</query>
</iq>

<iq from="test@conference.example.com/iSiDa" type="result" to="deounix@example.com/zeroTechnology" id="aacfa">
	<time xmlns="urn:xmpp:time">
	<tzo>-0-5:00</tzo>
	<utc>2018-02-28T00:14:04Z</utc>
	</time>
</iq>

```

**NOT RESPONDING**

I can't move to the new ejabberd cuz I've alot of modules I've built with 2.1.13

**Comment by zinid** [comment]
> I can't move to the new ejabberd cuz I've alot of modules I've built with 2.1.13

But nobody will fix the old version for you. We already don't even remember how it was working.
Not to mention that your bug report is completely moot: all I got is that something is not responding.
