### ISSUE TITLE
Ejabberd can't pickup 'my' custom module from ejabberdctl module_install command.

### ISSUE THREAD

**Issue by ajm113** [processone/ejabberd#2309]
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Linux ubuntu-xenial 4.4.0-116-generic (Vagrant Box)

> How did you install ejabberd (source, package, distribution)?

Source:

```
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
sudo dpkg -i erlang-solutions_1.0_all.deb && rm -f erlang-solutions_1.0_all.deb
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y build-essential automake autogen erlang \
	libssl-dev libexpat1-dev libyaml-dev zlib1g-dev libgd2-noxpm-dev libwebp-dev

git clone https://github.com/processone/ejabberd.git \
	&& cd ejabberd \
	&& git checkout tags/17.09 \
	&& ./autogen.sh \
	&& ./configure --enable-user=vagrant --enable-mysql --enable-tools \
	&& make \
	&& sudo make install
```

> What did not work as expected? Are there error messages in the log? What

Running: `ejaberdctl module_install mod_hello_world` outputs: `Error: not_available`

**Server Log:**
```
09:27:29.124 [debug] Command 'module_install' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
09:27:29.124 [debug] Executing command ext_mod:install with Args=[<<"mod_hello_world">>]
```

> was the unexpected behavior? What was the expected result?

I was expecting a `ok` from the command, since I heard this should compile the module, but for some reason it's not. I checked my file paths and environment variables. $HOME outputs /home/vagrant and my `.ejabberd-modules/sources` lives inside $HOME folder.

I've also attempted to create a mod_hello_world and place the mod_hello_world.erl inside of it, and moved the erl file outside the /mod_hello_world folder, but I can't seem to get different results. I've also attempted to diggest the `ext_mod.erl`, with no luck. I'm beginnerish/moderate w/ Erlang, but can't see what I'm doing wrong. The contrib mods seem to work fine, but for whatever reason Ejabberd can't pickup my test module.

-- I have a good feeling I'm missing something stupid, but I've read all the docs, and Googled around with no luck.

Appreciate any help, 

Thanks!

**Comment by cromain** [comment]
please confirm you have $HOME/.ejabberd-modules/sources/mod_hello_world/src/mod_hello_world.erl
this is where your source module should be stored.

**Comment by ajm113** [comment]
Can confirm I've attempted that combination.

```
-module(mod_hello_world).

-behaviour(gen_mod).

%% Required by ?INFO_MSG macros
-include("logger.hrl").

%% gen_mod API callbacks
-export([start/2, stop/1]).

start(_Host, _Opts) ->
    ?INFO_MSG("Hello, ejabberd world!", []),
    ok.

stop(_Host) ->
    ?INFO_MSG("Bye bye, ejabberd world!", []),
    ok.
```

**Comment by ajm113** [comment]
I don't know if the spec file would have anything to do with it, but I'll provide it too...
```
author: "Me <ajm113@github>"
category: "roster"
summary: "Just say's hello at the moment."
home: ""
url: ""
```

**Comment by cromain** [comment]
I confirm the .spec is mandatory. it must be in file $HOME/.ejabberd-modules/sources/mod_hello_world/mod_hello_world.spec
once you have this, it works as expected
```
ejabberdctl module_install mod_hello_world
ejabberdctl modules_installed
mod_hello_world Just say's hello at the moment.
```
