### ISSUE TITLE
Problem starting the module mod_hello_world

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#2316]
> What version of ejabberd are you using?

16.03.92

> What operating system (version) are you using?

Debian Jessie

I'm trying to develop my own module but I'm not being able to do it.
In order to find what I'm doing wrong, I've tried to implement my own ```mod_hello_world```.
But it's also not working...

The logs are:
```
2018-03-02 19:20:05.585 [critical] <0.37.0>@gen_mod:start_module:122 Problem starting the module mod_hello_world for host <<"ejabberd.nepcom.es">>
 options: []
 error: undef
[{mod_hello_world,start,[<<"ejabberd.nepcom.es">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,114}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,74}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2018-03-02 19:20:05.585 [critical] <0.37.0>@gen_mod:start_module:127 ejabberd initialization was aborted because a module start failed.
```

What I've done:

1. Added a new file ```mod_hello_world.erl``` in the ```/var/opt/ejabberd/src``` directory.
2. Pasted the contents of the ejabberd Modules Development guide into the file.
3. Run ```make clean``` and ```make``` from ```/var/opt/ejabberd```.
4. Added ```mod_hello_world: {}``` into my ```modules``` list in the ```/var/etc/ejabberd/ejabberd.yml```.
5. Run ```ejabberdctl stop``` and ```ejabberdctl start```

Then it does not start and outputs the previously pasted logs.

-Any idea about what I'm doing wrong?
-How can I get more info about the error? 
With the pasted stack trace I can't understand what's happening...

Thanks a lot!!!

**Comment by zinid** [comment]
When you compile ejabberd it produces `mod_hello_world.beam`, find it, check if it's placed with all other ejabberd BEAM files.

**Comment by joanlopez** [comment]
Thanks for your suggestion @zinid, everything is OK now.

I proced to explain my case just as an example for those who have a similar problem:

I have my Ejabberd in the path ```/opt/ejabberd```, so, when I compile it, then it puts the compiled files into the path ```/opt/ejabberd/ebin```.

So, the solution was to copy the file ``` mod_xxx.beam``` from this directory to ```/lib/ejabberd-16.03.92/ebin```.

I suppose that the compiled files are being taken from this path.

**Comment by joanlopez** [comment]
To conclude and understand it,

If I'm using a third-party library as a dependency.

What should I do appart from adding it to ```rebar.config``` file?

I've tried tot just add it to ```rebar.config```, compile and run, but I'm still having an ```undef``` error.
I should also copy some files from this dependency to ```/lib/ejabberd-16.03.92/```?

Thank you so much @zinid!

**Comment by zinid** [comment]
For the record, you will rewrite your module for the new ejabberd version.
So I advise you to upgrade and use `CONTRIB_MODULES_PATH` variable from `ejabberdctl.cfg`.

**Comment by joanlopez** [comment]
Thanks @zinid!

Is there any guide about how to plan this rewriting?

**Comment by zinid** [comment]
Even if there was the plan, why on earth you want to write and then rewrite it instead of just installing the latest version?

**Comment by joanlopez** [comment]
I think I explained myself wrong.

I was asking about a guide where I can find the changes needed to port an old module to be compatible with the latest version of Ejabberd.

Are you suggesting to write it again from scratch?

Thanks!

**Comment by zinid** [comment]
There is no such guide.
Since 16.12 ejabberd was switched to the new [XMPP library](https://github.com/processone/xmpp). Also, many hooks and internal API functions have been changed since then. So, likely, yes - you will have to rewrite most of your code.
