### ISSUE TITLE
Blah blah blah

### ISSUE THREAD

**Issue by gurussia** [processone/ejabberd#2318]
Guys ask yourself why programs don't work. So here is why it programs don't work:

Latest ubuntu version 18.0.2:

21:03:55.985 [warning] Listening option 'certfile' for ejabberd_c2s is deprecated, use 'certfiles' global option instead
21:03:56.348 [info] Application inets started on node ejabberd@localhost
21:03:56.348 [warning] module 'mod_mam' is recommended for module 'mod_muc' but is not found in the config

Now when it change to certfiles it comment this:

in ejabbled.ym:

    certfiles: "/etc/ejabberd/ejabberd.pem"

it comment:

21:07:15.149 [info] Application fs started on node ejabberd@localhost
21:07:15.246 [error] unknown listen option 'certfiles' for 'ejabberd_c2s' will be likely ignored, available options are: access, shaper, certfile, ciphers, dhfile, cafile, protocol_options, tls, tls_compression, starttls, starttls_required, tls_verify, zlib, max_fsm_queue

So INHUMAN. it comment change to certfiles and when you change to certfile it comment change to certfile. SO NOW YOU HAVE THE ANSWERS WHY programs don't 100 % work and the fault is in the women developer.

**Comment by zinid** [comment]
Dude, you should visit a doctor or take pills or something like that
