### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2323]
On the XEPs support page, it is possible to add version of XEPs?
https://www.process-one.net/en/ejabberd/protocols/

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by zinid** [comment]
You can do:
```
$ grep '\-protocol(' src/*.erl
```

**Comment by Neustradamus** [comment]
Version?
