### ISSUE TITLE
No publisher JID in pubsub items retrieved from server

### ISSUE THREAD

**Issue by pubtub** [processone/ejabberd#2325]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian GNU/Linux 9.1 (stretch)

> How did you install ejabberd (source, package, distribution)?

.DEB package from process-one website

> What did not work as expected? Are there error messages in the log? What

We currently use mysql as the DB. The relevant modules that are active on the server are:
  mod_bosh:
  mod_mam:
  mod_muc:
  mod_offline:
  mod_pubsub:
  mod_stream_mgmt : 

While using pubsub, the messages that arrive on the client side in real-time get delivered with the appropriate publisher jid so that the client knows who published it. This is the case even for messages that arrive on the client side after the message was originally missed due to user being offline, ie from the spool table in the DB.

However, when we explicitly fetch the items published to a particular node, the set of items returned do not have a corresponding publisher jid. In this case, if the end user loses the device and wants to fetch all the messages from the server using a new device, there is no way of telling which users have published the items received.

Any attempt to put publisher information as a tag within the item itself would result in leaving the app open to phishing. Is there a fix or a workaround or is this expected behaviour?

**Comment by pubtub** [comment]
Some additional info:
There was a feature request EJAB-1347 in 2012 which highlighted "7.1.2.3 Item Publisher" of XEP-0060. Which states "If configured to do so, the service can include the publisher of the item when it generates event notifications.". Subsequently a patch was released and the feature was implemented in ejabberd version 16.02.
However, 7.1.2.3 of XEP-0060 also states that "...the service MUST also include the publisher with every other form of item retrieval". I believe this is the part which is not working as expected for us.

**Comment by cromain** [comment]
thanks for reporting ! everything is clear and the "bug" identified.
EJAB-1347 patch was indeed partial and did not covered item retrieval. The improvement is quite simple but i won't be able to work on it by 18.03. So it will be in 18.04.

**Comment by pubtub** [comment]
Thanks for looking into this. 
I did have a look at the source code for mod_pubsub.erl and think about changing get_items and re-compiling to see what happens, but I have no knowledge of erlang.
I guess I will wait for 18.04 :)

**Comment by cromain** [comment]
should be ok now, simple tests looks good.
