### ISSUE TITLE
Unable to import from Prosody

### ISSUE THREAD

**Issue by SkewedZeppelin** [processone/ejabberd#2328]
Using 18.01 from repos on Ubuntu 18.04

I've been trying to switch from prosody to ejabberd and no matter what I try it always fails.

The errors are as follows
```
Problem 'error undef' occurred executing the command.
Stacktrace: [{luerl,init,[],[]},
             {prosody2ejabberd,eval_file,1,
                               [{file,"src/prosody2ejabberd.erl"},{line,101}]},
             {prosody2ejabberd,'-convert_dir/3-fun-0-',4,
                               [{file,"src/prosody2ejabberd.erl"},{line,80}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,352}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,321}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,249}]}]
```

My process is as follows
```
$ cd /var/lib/ejabberd
$ cp /var/lib/prosody . -r
$ chown ejabberd:ejabberd prosody -R
$ ejabberdctl import_prosody /var/lib/ejabberd/prosody #errors out with error above
$ ejabberdctl registered_users $host #no accounts
```
I've tried removing various unneeded directories from the prosody copy, but it still won't import.
I've also tried removing the offline files like mentioned in #2312, but that didn't help, and the error does seem different.

On the ejabberd side, I'm using scram and the internal db (mnesia?)
On the prosody side, I'm using internal_hashed and the internal db + xmlarchive

**Comment by zinid** [comment]
That means ejabberd is compiled without Lua support.

**Comment by zinid** [comment]
Or maybe you need to install `luerl` package or something, dunno if it's present in Ubuntu.

**Comment by SkewedZeppelin** [comment]
Ah!
Thanks @zinid 

I installed erlang-luerl, ran the commands above, encountered #2312, removed offline, ran import again and it worked!
