### ISSUE TITLE
mod_shared_roster not working

### ISSUE THREAD

**Issue by SkewedZeppelin** [processone/ejabberd#2329]
Using 18.01 from repos on Ubuntu 18.04

Switching from prosody I have manually recreated many shared roster groups using the web interface. However no groups ever appear in any client's roster.

My process is as follows
- Create account A
- Create account B
- Open web interface
- Create a shared roster group with both A and B
- Check roster of both A and B, no groups
- Force restart A and B client, no groups

But no groups are ever to be seen and no errors are logged

I know this feature worked back around 17.06 (or so), as I was testing back then.

In the ejabberd config I have both mod_roster and mod_shared_roster enabled.

Suggestions?

**Comment by zinid** [comment]
You're probably facing #1846
