### ISSUE TITLE
Captcha script generates invalid image

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#2331]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian 9.4 with latest imagemagick package.

> How did you install ejabberd (source, package, distribution)?

From package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Captcha script generates invalid image:

<img width="184" alt="2018-03-19_190700" src="https://user-images.githubusercontent.com/5073817/37613737-129c3896-2ba9-11e8-85b0-1c85c932c2a5.png">

**Comment by zinid** [comment]
Fonts problem maybe? What if you call it from the command line:
```
$ /path/to/captcha.sh 123456 | display -
```

**Comment by beherit** [comment]
I see an error:
```
display-im6.q16: unable to open X server @ error/display.c/DisplayImageCommand/432.
```

**Comment by SkewedZeppelin** [comment]
@beherit I think you need to install gsfonts

**Comment by zinid** [comment]
> I see an error

You can only run `display` with X server loaded. Another way is to dump the output somewhere and the open the image on any machine with GUI.

**Comment by beherit** [comment]
@zinid @SkewedZeppelin thank You, gsfonts was missing on my system :)

**Comment by zinid** [comment]
Ah, @SkewedZeppelin good catch then!
