### ISSUE TITLE
Error registering users in Ejabberd-18.01 with database as postgresql and structure pg.new.sql

### ISSUE THREAD

**Issue by prasanna-patil** [processone/ejabberd#2332]
> What version of ejabberd are you using?

Ejabberd-18.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Installation was done by package. Source https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/18.01/ejabberd_18.01-0_amd64.deb

> What did not work as expected? Are there error messages in the log?
>What was the unexpected behavior? What was the expected result?

User registration failed. I tried to register user "admin" with the command
> ejabberdctl register admin < domainname > password

and getting error as:
> Error: conflict

Prior to that I have installed otp 20.03. The database we are using is postgresql and have restore the database structure which is in pg.new.sql.

the debug show the following:

17:19:46.304 [debug] (#Port<0.21896>) http query: 'GET' <<"/admin/server/mydomain.com/">>
17:19:46.306 [debug] [<<"admin">>,<<"server">>,<<"mydomain.com">>] matches [<<"admin">>]
17:19:53.940 [info] Memory consumption is back to normal, stopping OOM watchdog
08:15:02.746 [debug] Command 'register' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
08:15:02.746 [debug] Executing command ejabberd_admin:register with Args=[<<"admin">>,<<"mydomain.com">>,<<"admin@123">>]
08:15:06.292 [error] SQL query 'Q73531467' at {ejabberd_auth_sql,174} failed: [{severity,'ERROR'},{code,<<"23502">>},{message,<<"null value in column \"server_host\" violates not-null constraint">>},{detail,<<"Failing row contains (admin, null, admin@123, , , 0, 2018-03-20 08:15:06.275556).">>},{115,<<"public">>},{116,<<"users">>},{99,<<"server_host">>},{file,<<"execMain.c">>},{line,1699},{routine,<<"ExecConstraints">>}]

I created a new database and restored the pg.sql file (which doesnt have server_host column in USERS table) and connected ejabberd to the new database. Registration was successful.

**Comment by cromain** [comment]
The 18.01 package do not support the new schema. You should use 18.03 and see ejabberd.yml for new_sql_schema option.
