### ISSUE TITLE
@mod_muc_mnesia:handle_info:343 unexpected info: {mnesia_system_event,{mnesia_overload,{dump_log,write_threshold}}}

### ISSUE THREAD

**Issue by kishoreacesurf** [processone/ejabberd#2333]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Centos 7.4

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log? What
@mod_muc_mnesia:handle_info:343 unexpected info: {mnesia_system_event,{mnesia_overload,{dump_log,write_threshold}}}

> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
So? Your Mnesia database is overloaded. That's all I can say about your report.

**Comment by kishoreacesurf** [comment]
I am using mysql as my database and 3 node cluster. Please let me know how to resolve the above error.

**Comment by zinid** [comment]
What error? This message is just a warning. You should only fix this when you have real problems.

**Comment by zinid** [comment]
The error you have shown is not related to MUC or Mnesia. That's mod_bosh's bug.

**Comment by kishoreacesurf** [comment]
Any insights to get a work around for this?

**Comment by cromain** [comment]
zinid explained the main problem: you are overloading mnesia.  this can have several causes, likely design or sizing problem. your workaround may have side effects which are not effective bugs.
You should focus on root causes of overload, there is something wrong with use, and we can not help on that.
