### ISSUE TITLE
mod_register_web: registration_watchers option doesn't work

### ISSUE THREAD

**Issue by Elizafox** [processone/ejabberd#2337]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian Buster

> How did you install ejabberd (source, package, distribution)?

Distribution

> What did not work as expected? Are there error messages in the log? What
The registration_watchers option for mod_register_web does not send messages correctly.

When loading:

```
2018-03-22 21:12:20.180 [error] <0.713.0>@gen_mod:validate_opts:531 unknown option 'registration_watchers' for module 'mod_register_web' will be likely ignored because the module doesn't have any options
```

(although the below does not appear in the log when it is not set, and this is contrary to the documentation)

Error message when it attempts to send:

```
2018-03-22 21:37:51.665 [error] <0.830.0>@ejabberd_router:route:95 failed to route packet:
#message{id = <<>>,type = chat,lang = <<>>,
         from = #jid{user = <<>>,server = <<"interlinked.me">>,
                     resource = <<>>,luser = <<>>,
                     lserver = <<"interlinked.me">>,lresource = <<>>},
         to = [{<<"user">>,<<"elizacat">>},
               {<<"server">>,<<"interlinked.me">>}],
         subject = [],
         body = [#text{lang = <<"en">>,
                       data = <<"[2018-03-22 21:37:51] The account test@interlinked.me was registered from IP address [redacted] on node ejabberd@localhost using mod_register_web.">>}],
         thread = undefined,sub_els = [],meta = #{}}
Reason = {error,{{badrecord,jid},[{ejabberd_router,do_route,1,[{file,"src/ejabberd_router.erl"},{line,367}]},{ejabberd_router,route,1,[{file,"src/ejabberd_router.erl"},{line,93}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_register_web,process,2,[{file,"src/mod_register_web.erl"},{line,110}]},{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,374}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,472}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,206}]}]}}
```

> was the unexpected behavior? What was the expected result?

For the message to be properly sent.

**Comment by zinid** [comment]
> unknown option 'registration_watchers' for module 'mod_register_web'

There is no such option in `mod_register_web`. This option only presents in `mod_register`.
I also cannot reproduce the issue, and I fail to see in the code how it's possible to have the type error you have shown.

**Comment by zinid** [comment]
I now understand how you got this crash, you put something like this in the config:
```yaml
mod_register_web:
  registration_watchers:
    "user": "elizacat"
    "server": "interlinked.me"
```
And due to the bug in `mod_register.erl` the option was accepted by ejabberd. This is now fixed. Please set the following after version upgrade:
```yaml
mod_register:
  registration_watchers:
    - "elizacat@interlinked.me"
```

**Comment by Elizafox** [comment]
That is what I put in the config.
