### ISSUE TITLE
Invalid Username and Password with auth_use_cache: true;  

### ISSUE THREAD

**Issue by claudiocleberson** [processone/ejabberd#2339]
> What version of ejabberd are you using?

ejabberd 18.1.0

> What operating system (version) are you using?

Digital ocean Ubuntu 16.04.3 Lts
with Postesgres DB.

> How did you install ejabberd (source, package, distribution)?

I installed the ejabberd using a  Dockerfile for Ejabberd server  by rroemhild/docker-ejabberd.

> What did not work as expected? Are there error messages in the log? What

I'm authenticating all users against my backend, using a External authentication script written in python. 

I set the: 
auth_use_cache = true;  

the problem is that when the user changes the password on the backend, when try again to sing-in the ejabberd  refused the new connection with the log:

 179.213.212.97: Invalid username or password

and it keeps repeating that log. 

> was the unexpected behavior? What was the expected result?

I would expected, that after a failed attempt, the authentication  cached could be invalidated. and the new user's password accepted. 

Is there any settings that I am missing?

**Comment by zinid** [comment]
> the problem is that when the user changes the password on the backend

What does that mean? If you change a password via external mechanisms, ejabberd obviously doesn't know about the change. You need to clear cache via `clear-cache` ejabberd command explicitly.

**Comment by claudiocleberson** [comment]
Thanks for your reply, I thought that would have an out of box solution when an user tries another signup with other password. For now I'm setting the auth_use_cache = false and later I will try to handle that using clear-cache as suggested!

cheers,
