### ISSUE TITLE
18.1 does not compile as embedded mix project

### ISSUE THREAD

**Issue by chartera** [processone/ejabberd#2340]
> What version of ejabberd are you using?

18.1

> What operating system (version) are you using?

OSX 10.11.6

> How did you install ejabberd (source, package, distribution)?

{:ejabberd, "~> 18.1"}

> What did not work as expected? Are there error messages in the log? What

could not compile dependency :ejabberd, "mix compile" failed. You can recompile this dependency with "mix deps.compile ejabberd", update it with "mix deps.update ejabberd" or clean it with "mix deps.clean ejabberd"

> was the unexpected behavior? What was the expected result?

runnin mix deps.get and then mix compile fails

using Erlang/OTP 20.2 and elixir 1.6.4

**Comment by apcxiii** [comment]
Same problem in freebsd server and OSX

**Comment by apcxiii** [comment]
try to set these dependencies

```
{:ejabberd, git: "https://github.com/processone/ejabberd", tag: "18.1.0"},
     {:iconv, "1.0.6", manager: :rebar3, override: true},
     {:xmpp, "1.1.19", override: true},
     {:fast_xml, "1.1.28", override: true},
     {:p1_utils, "1.0.10", override: true}]     
```

**Comment by chartera** [comment]
thanks

**Comment by Freyskeyd** [comment]
still not working for me :(
