### ISSUE TITLE
p1_mysql_conn: Received close signal, exiting

### ISSUE THREAD

**Issue by rheman** [processone/ejabberd#2341]
Hi everyone .
I am using ejabberd 18.01 (ejabberd_18.01-0_amd64.deb) under ubuntu 16.04. with mysql backend.
Everything works perfectly. 
-When I create user
-store vcard
-send roster 
Everything is store in my database. But I have the following message in my ejabberd error.log
0.473.0>@ejabberd_sql:log:940 p1_mysql_conn: Received close signal, exiting.
<0.472.0>@ejabberd_sql:log:940 p1_mysql_conn: Received close signal, exiting.
<0.363.0> backend port not found: inotifywait

My mysql server setting in ejabberd.yml looks as followed.

##
## 
host_config:
  "esfamchat.auf.org":
    sql_type: mysql
    sql_server: "localhost"
    sql_database: "esfamaufchatlast"
    sql_username: "esfamaufchatlast"
    sql_password: "esfamaufchatlast"
    sql_port: 3306
    sql_keepalive_interval: 28800
    sql_pool_size: 20

I dont know what's wrong with my settings.

Best regard.

**Comment by zinid** [comment]
> Everything works perfectly

So what problems do you have? Errors in the log are not always lead to any problems. In your case this most likely means your MySQL server is dropping inactive connections.

**Comment by cromain** [comment]
closing this thread. this is harmless.
MySQL server is dropping inactive connections and ejabberd will reopen connection when needed.

**Comment by JonnyDevid** [comment]
hi, how i cant install Step-by-step  FreeTDS and unixODBC installed on windows?.

Also, you need to add machine name to sql_username, especially when you have sql_server defined as an IP address, e.g.: SQL Server Management studio(MSSQL)

sql_type: mssql
sql_server: "1.2.3.4"
...
sql_username: "user1@host"
SQL Authentication

SQL Storage
db_type: sql or odbc ?
