### ISSUE TITLE
non latin characters in mod_http_upload

### ISSUE THREAD

**Issue by Yures** [processone/ejabberd#2346]
Maybe [it's](https://github.com/processone/ejabberd/blob/d71bc732717ca637c42edf3a75aef71ac6c67ef8/src/mod_http_upload.erl#L687) in the module settings, because not all use Latin characters in file names.

**Comment by weiss** [comment]
What actual problem are you running into?  The assumption was that the file name usually won't be exposed to the end user anyway.

**Comment by Yures** [comment]
for images it may not make sense, but if, for example, you load a document with non-Latin characters in the file name, then another user will receive a file named __________. odf.
