### ISSUE TITLE
Failed to validate certificate self-signed certificate

### ISSUE THREAD

**Issue by Hassnain-Alvi** [processone/ejabberd#2348]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

installer run file

> What did not work as expected? Are there error messages in the log?

2018-03-28 06:48:03.996 [warning] <0.609.0>@ejabberd_pkix:build_chain_and_check:426 Failed to validate certificate from /opt/ejabberd-18.01/conf/server.pem: self-signed certificate
2018-03-28 06:48:04.019 [warning] <0.609.0>@ejabberd_pkix:handle_call:255 No certificate found matching 'xxxx-portal': strictly configured clients or server

> was the unexpected behavior? What was the expected result?

On ejabberd server bootup or restart we see a warning for server.pem file that its self signed. We were using the same self signed server.pem bundled with the distribution (in conf dir) but it was not raising this warning before. Did you guys explicitly added warning in new version? 

Secondly i am facing delay while starting ejabberd in my CentOS instance?  Is this delay normal for graceful start and shutdown?

**Comment by zinid** [comment]
> Did you guys explicitly added warning in new version?

Yes.

> Secondly i am facing delay while starting ejabberd in my CentOS instance?

Completely irrelevant question, but ejabberd reports startup time. What time is it reporting?

**Comment by Hassnain-Alvi** [comment]
I see following log in ejabberd:
2018-03-29 07:22:06.418 [info] <0.66.0>@ejabberd_app:start:59 ejabberd 18.01 is started in the node 'ejabberd@ip-10-0-4-149.us-west-2.compute.internal' in 152.87s

It took around 2.5 minutes. Is it normal?

**Comment by zinid** [comment]
> It took around 2.5 minutes. Is it normal?

Of course not, please enable debug (`loglevel: 5`) and check line by line what consumed the most time.

**Comment by Hassnain-Alvi** [comment]
Here are the logs i got from debug 

> 2018-03-30 03:38:34.450 [info] <0.3873.3> Application elixir started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-30 03:38:34.470 [info] <0.3906.3>@ejabberd_config:start:73 Loading configuration from /opt/ejabberd/conf/ejabberd.yml
> 2018-03-30 03:40:10.836 [info] <0.3873.3> Application mnesia started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-30 03:40:10.997 [info] <0.3873.3> Application os_mon started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-30 03:40:10.998 [info] <0.4327.3>@cyrsasl_digest:start:62 FQDN used to check DIGEST-MD5 SASL authentication: ip-10-0-5-113.localdomain
> 2018-03-30 03:41:39.108 [info] <0.3873.3> Application fs started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-30 03:41:39.211 [warning] <0.4379.3>@ejabberd_pkix:build_chain_and_check:426 Failed to validate certificate from /opt/ejabberd-18.01/conf/server.pem: self-signed certificate

According to these logs it took around 2 minutes loading configuration and 1 minute on FQDN configuration. Why its taking too much time on these steps and its not raising any error or warning

**Comment by zinid** [comment]
This is not debug

**Comment by Hassnain-Alvi** [comment]
Oh Sorry here it is

> 2018-03-31 06:09:34.862 [notice] <0.83.0>@lager_file_backend:146 Changed loghwm of /opt/ejabberd/logs/error.log to 20000
> 2018-03-31 06:09:34.862 [notice] <0.83.0>@lager_file_backend:146 Changed loghwm of /opt/ejabberd/logs/ejabberd.log to 20000
> 2018-03-31 06:09:34.863 [info] <0.33.0> Application lager started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.869 [info] <0.33.0> Application crypto started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.875 [info] <0.33.0> Application sasl started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.882 [info] <0.33.0> Application asn1 started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.882 [info] <0.33.0> Application public_key started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.892 [info] <0.33.0> Application ssl started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.896 [info] <0.33.0> Application p1_utils started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.905 [info] <0.33.0> Application fast_yaml started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.918 [info] <0.33.0> Application fast_tls started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.932 [info] <0.33.0> Application fast_xml started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.936 [info] <0.33.0> Application stringprep started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.944 [info] <0.33.0> Application xmpp started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.956 [info] <0.33.0> Application cache_tab started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:34.988 [info] <0.33.0> Application elixir started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:09:35.007 [info] <0.66.0>@ejabberd_config:start:73 Loading configuration from /opt/ejabberd/conf/ejabberd.yml
> 2018-03-31 06:09:35.799 [notice] <0.83.0>@lager_file_backend:135 Changed loglevel of /opt/ejabberd/logs/ejabberd.log to debug
> 2018-03-31 06:09:35.832 [debug] <0.60.0> Supervisor kernel_safe_sup started dets_sup:start_link() at pid <0.182.0>
> 2018-03-31 06:09:35.832 [debug] <0.60.0> Supervisor kernel_safe_sup started dets_server:start_link() at pid <0.183.0>
> 2018-03-31 06:09:35.850 [debug] <0.193.0> Supervisor mnesia_sup started mnesia_sup:start_event() at pid <0.194.0>
> 2018-03-31 06:09:35.851 [debug] <0.193.0> Supervisor mnesia_sup started mnesia_ext_sup:start() at pid <0.195.0>
> 2018-03-31 06:09:35.852 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_monitor:start() at pid <0.197.0>
> 2018-03-31 06:09:35.854 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_subscr:start() at pid <0.198.0>
> 2018-03-31 06:09:35.859 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_locker:start() at pid <0.199.0>
> 2018-03-31 06:09:35.862 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_recover:start() at pid <0.200.0>
> 2018-03-31 06:09:35.888 [debug] <0.60.0> Supervisor kernel_safe_sup started disk_log_sup:start_link() at pid <0.205.0>
> 2018-03-31 06:09:35.888 [debug] <0.60.0> Supervisor kernel_safe_sup started disk_log_server:start_link() at pid <0.206.0>
> 2018-03-31 06:09:35.900 [debug] <0.212.0> Supervisor inet_gethost_native_sup started undefined at pid <0.213.0>
> 2018-03-31 06:09:35.900 [debug] <0.60.0> Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.212.0>
> 2018-03-31 06:11:31.003 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_tm:start() at pid <0.201.0>
> 2018-03-31 06:11:31.005 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_checkpoint_sup:start() at pid <0.377.0>
> 2018-03-31 06:11:31.005 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_controller:start() at pid <0.378.0>
> 2018-03-31 06:11:31.020 [debug] <0.196.0> Supervisor mnesia_kernel_sup started mnesia_late_loader:start() at pid <0.379.0>
> 2018-03-31 06:11:31.020 [debug] <0.193.0> Supervisor mnesia_sup started mnesia_kernel_sup:start() at pid <0.196.0>
> 2018-03-31 06:11:31.020 [info] <0.33.0> Application mnesia started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:11:31.020 [debug] <0.181.0>@ejabberd_mnesia:init:71 Waiting for Mnesia tables synchronization...
> 2018-03-31 06:11:31.163 [debug] <0.181.0>@ejabberd_mnesia:read_schema_file:226 No custom Mnesia schema file found
> 2018-03-31 06:11:31.168 [debug] <0.136.0> Supervisor p1_utils_sup started p1_file_queue:start_link("/opt/ejabberd/database/ejabberd@ip-10-0-5-113.us-west-2.compute.internal/queue") at pid <0.571.0>
> 2018-03-31 06:11:31.174 [debug] <0.575.0> Supervisor os_mon_sup started disksup:start_link() at pid <0.576.0>
> 2018-03-31 06:11:31.178 [debug] <0.575.0> Supervisor os_mon_sup started memsup:start_link() at pid <0.577.0>
> 2018-03-31 06:11:31.178 [info] <0.33.0> Application os_mon started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:11:31.178 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_hooks:start_link() at pid <0.581.0>
> 2018-03-31 06:11:31.178 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_cluster:start_link() at pid <0.582.0>
> 2018-03-31 06:11:31.179 [info] <0.583.0>@cyrsasl_digest:start:62 FQDN used to check DIGEST-MD5 SASL authentication: ip-10-0-5-113.localdomain
> 2018-03-31 06:11:31.179 [debug] <0.580.0> Supervisor ejabberd_sup started cyrsasl:start_link() at pid <0.583.0>
> 2018-03-31 06:11:31.181 [debug] <0.60.0> Supervisor kernel_safe_sup started timer:start_link() at pid <0.585.0>
> 2018-03-31 06:11:31.196 [debug] <0.580.0> Supervisor ejabberd_sup started translate:start_link() at pid <0.584.0>
> 2018-03-31 06:11:31.196 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_access_permissions:start_link() at pid <0.589.0>
> 2018-03-31 06:11:31.196 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_ctl:start_link() at pid <0.590.0>
> 2018-03-31 06:13:19.278 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'ejabberd_commands' found
> 2018-03-31 06:13:19.278 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_commands:start_link() at pid <0.591.0>
> 2018-03-31 06:13:19.278 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_admin:start_link() at pid <0.642.0>
> 2018-03-31 06:13:19.284 [info] <0.33.0> Application fs started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:13:19.303 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(ca_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.648.0>
> 2018-03-31 06:13:19.303 [debug] <0.643.0>@ejabberd_pkix:clean_dir:618 Cleaning directory /opt/ejabberd/database/ejabberd@ip-10-0-5-113.us-west-2.compute.internal/certs
> 2018-03-31 06:13:19.303 [debug] <0.643.0>@ejabberd_pkix:add_certfiles:349 Reading certificates
> 2018-03-31 06:13:19.331 [debug] <0.643.0>@ejabberd_pkix:build_chain_and_check:406 Building certificates graph
> 2018-03-31 06:13:19.334 [debug] <0.643.0>@ejabberd_pkix:build_chain_and_check:408 Finding matched certificate keys
> 2018-03-31 06:13:19.334 [debug] <0.643.0>@ejabberd_pkix:build_chain_and_check:411 Storing certificate chains
> 2018-03-31 06:13:19.335 [debug] <0.643.0>@ejabberd_pkix:build_chain_and_check:419 Validating certificates
> 2018-03-31 06:13:19.414 [debug] <0.643.0>@ejabberd_pkix:build_chain_and_check:421 Subscribing to file events
> 2018-03-31 06:13:19.424 [debug] <0.651.0> Supervisor '20935603sup' started fs_server:start_link('20935603file', '20935603', inotifywait, <<"/opt/ejabberd-18.01/conf">>, <<"/opt/ejabberd-18.01/conf">>) at pid <0.652.0>
> 2018-03-31 06:13:19.424 [debug] <0.651.0> Supervisor '20935603sup' started gen_event:start_link({local,'20935603'}) at pid <0.653.0>
> 2018-03-31 06:13:19.424 [debug] <0.643.0>@ejabberd_pkix:subscribe:865 Subscribed to FS events from /opt/ejabberd-18.01/conf
> 2018-03-31 06:13:19.427 [warning] <0.643.0>@ejabberd_pkix:build_chain_and_check:426 Failed to validate certificate from /opt/ejabberd-18.01/conf/server.pem: self-signed certificate
> 2018-03-31 06:13:19.427 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_pkix:start_link() at pid <0.643.0>
> 2018-03-31 06:13:19.427 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_acme:start_link() at pid <0.654.0>
> 2018-03-31 06:13:19.429 [debug] <0.655.0> Supervisor ejabberd_listener started ejabberd_listener:start({5222,{0,0,0,0,0,0,0,0},tcp}, ejabberd_c2s, [{access,c2s},{shaper,c2s_shaper},{max_stanza_size,262144},{zlib,true},{protocol_options,[<<"no_s...">>]},...]) at pid <0.656.0>
> 2018-03-31 06:13:19.429 [debug] <0.655.0> Supervisor ejabberd_listener started ejabberd_listener:start({5269,{0,0,0,0,0,0,0,0},tcp}, ejabberd_s2s_in, [{shaper,s2s_shaper},{max_stanza_size,131072}]) at pid <0.657.0>
> 2018-03-31 06:13:19.429 [debug] <0.655.0> Supervisor ejabberd_listener started ejabberd_listener:start({5280,{0,0,0,0,0,0,0,0},tcp}, ejabberd_http, [{captcha,false},{http_bind,true},{web_admin,true},{request_handlers,[{<<"/websocket">>,ejabberd_http_ws},...]}]) at pid <0.658.0>
> 2018-03-31 06:13:19.430 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_listener:start_link() at pid <0.655.0>
> 2018-03-31 06:13:19.430 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 's2s' found
> 2018-03-31 06:13:19.430 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'temporarily_blocked' found
> 2018-03-31 06:13:19.430 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_s2s:start_link() at pid <0.659.0>
> 2018-03-31 06:13:19.431 [debug] <0.660.0>@ejabberd_captcha:get_prog_name:355 The option captcha_cmd is not configured, but some module wants to use the CAPTCHA feature.
> 2018-03-31 06:13:19.433 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'acl' found
> 2018-03-31 06:13:19.433 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'access' found
> 2018-03-31 06:13:19.433 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_captcha:start_link() at pid <0.660.0>
> 2018-03-31 06:13:19.433 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_tmp_sup:start_link(ejabberd_s2s_in_sup, ejabberd_s2s_in) at pid <0.662.0>
> 2018-03-31 06:13:19.434 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_tmp_sup:start_link(ejabberd_s2s_out_sup, ejabberd_s2s_out) at pid <0.663.0>
> 2018-03-31 06:13:19.434 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_tmp_sup:start_link(ejabberd_service_sup, ejabberd_service) at pid <0.664.0>
> 2018-03-31 06:13:19.434 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_tmp_sup:start_link(ejabberd_iq_sup, gen_iq_handler) at pid <0.665.0>
> 2018-03-31 06:13:19.445 [debug] <0.580.0> Supervisor ejabberd_sup started acl:start_link() at pid <0.666.0>
> 2018-03-31 06:13:19.445 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'shaper' found
> 2018-03-31 06:13:19.446 [debug] <0.580.0> Supervisor ejabberd_sup started shaper:start_link() at pid <0.691.0>
> 2018-03-31 06:13:19.446 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_backend_sup:start_link() at pid <0.692.0>
> 2018-03-31 06:13:19.446 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_rdbms:start_link() at pid <0.693.0>
> 2018-03-31 06:13:19.446 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_riak_sup:start_link() at pid <0.694.0>
> 2018-03-31 06:13:19.447 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_redis_sup:start_link() at pid <0.695.0>
> 2018-03-31 06:13:19.447 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_iq:start_link() at pid <0.696.0>
> 2018-03-31 06:13:19.449 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'route' found
> 2018-03-31 06:13:19.450 [debug] <0.692.0> Supervisor ejabberd_backend_sup started ejabberd_router_mnesia:start_link() at pid <0.698.0>
> 2018-03-31 06:13:19.450 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_router:start_link() at pid <0.697.0>
> 2018-03-31 06:13:19.450 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'route_multicast' found
> 2018-03-31 06:13:19.450 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_router_multicast:start_link() at pid <0.701.0>
> 2018-03-31 06:13:19.452 [debug] <0.702.0>@ejabberd_router:register_route:179 Route registered: abode-home-portal
> 2018-03-31 06:13:19.452 [warning] <0.643.0>@ejabberd_pkix:handle_call:255 No certificate found matching 'abode-home-portal': strictly configured clients or servers will reject connections with this host; obtain a certificate for this (sub)domain from any trusted CA such as Let's Encrypt (www.letsencrypt.org)
> 2018-03-31 06:13:19.455 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_local:start_link() at pid <0.702.0>
> 2018-03-31 06:13:19.455 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'session' found
> 2018-03-31 06:13:19.455 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'session_counter' found
> 2018-03-31 06:13:19.455 [debug] <0.692.0> Supervisor ejabberd_backend_sup started ejabberd_sm_mnesia:start_link() at pid <0.705.0>
> 2018-03-31 06:13:19.455 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_sm:start_link() at pid <0.704.0>
> 2018-03-31 06:13:19.466 [debug] <0.711.0> Supervisor inets_sup started ftp_sup:start_link() at pid <0.712.0>
> 2018-03-31 06:13:19.481 [debug] <0.714.0> Supervisor httpc_profile_sup started httpc_manager:start_link(default, only_session_cookies, inets) at pid <0.715.0>
> 2018-03-31 06:13:19.481 [debug] <0.713.0> Supervisor httpc_sup started httpc_profile_sup:start_link([{httpc,{default,only_session_cookies}}]) at pid <0.714.0>
> 2018-03-31 06:13:19.483 [debug] <0.713.0> Supervisor httpc_sup started httpc_handler_sup:start_link() at pid <0.716.0>
> 2018-03-31 06:13:19.483 [debug] <0.711.0> Supervisor inets_sup started httpc_sup:start_link([{httpc,{default,only_session_cookies}}]) at pid <0.713.0>
> 2018-03-31 06:13:19.485 [debug] <0.711.0> Supervisor inets_sup started httpd_sup:start_link([]) at pid <0.717.0>
> 2018-03-31 06:13:19.487 [debug] <0.711.0> Supervisor inets_sup started tftp_sup:start_link([]) at pid <0.718.0>
> 2018-03-31 06:13:19.487 [info] <0.33.0> Application inets started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:13:19.487 [debug] <0.580.0> Supervisor ejabberd_sup started ext_mod:start_link() at pid <0.707.0>
> 2018-03-31 06:13:19.489 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_shared_roster at abode-home-portal
> 2018-03-31 06:13:19.489 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'sr_group' found
> 2018-03-31 06:13:19.489 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'sr_user' found
> 2018-03-31 06:13:19.489 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_adhoc at abode-home-portal
> 2018-03-31 06:13:19.490 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_private at abode-home-portal
> 2018-03-31 06:13:19.490 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'private_storage' found
> 2018-03-31 06:13:19.497 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(private_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.720.0>
> 2018-03-31 06:13:19.497 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_ping at abode-home-portal
> 2018-03-31 06:13:19.497 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_privacy at abode-home-portal
> 2018-03-31 06:13:19.497 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'privacy' found
> 2018-03-31 06:13:19.497 [debug] <0.719.0> Supervisor ejabberd_gen_mod_sup started gen_server:start_link({local,'mod_ping_abode-home-portal'}, mod_ping, [<<"abode-home-portal">>,[{send_pings,true},{ping_interval,45},{ping_ack_timeout,30000},{timeout_action,...}]], []) at pid <0.722.0>
> 2018-03-31 06:13:19.505 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(privacy_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.723.0>
> 2018-03-31 06:13:19.511 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(privacy_list_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.725.0>
> 2018-03-31 06:13:19.511 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_disco at abode-home-portal
> 2018-03-31 06:13:19.512 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_announce at abode-home-portal
> 2018-03-31 06:13:19.512 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'motd' found
> 2018-03-31 06:13:19.516 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'motd_users' found
> 2018-03-31 06:13:19.525 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(motd_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.728.0>
> 2018-03-31 06:13:19.525 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_blocking at abode-home-portal
> 2018-03-31 06:13:19.525 [debug] <0.719.0> Supervisor ejabberd_gen_mod_sup started gen_server:start_link({local,'mod_announce_abode-home-portal'}, mod_announce, [<<"abode-home-portal">>,[{access,announce}]], []) at pid <0.727.0>
> 2018-03-31 06:13:19.525 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_http_api at abode-home-portal
> 2018-03-31 06:13:19.525 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_s2s_dialback at abode-home-portal
> 2018-03-31 06:13:19.526 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_roster at abode-home-portal
> 2018-03-31 06:13:19.526 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'roster' found
> 2018-03-31 06:13:19.527 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'roster_version' found
> 2018-03-31 06:13:19.535 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(roster_version_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.730.0>
> 2018-03-31 06:13:19.541 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(roster_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.732.0>
> 2018-03-31 06:13:19.548 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(roster_item_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.734.0>
> 2018-03-31 06:13:19.549 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_stream_mgmt at abode-home-portal
> 2018-03-31 06:13:19.549 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_last at abode-home-portal
> 2018-03-31 06:13:19.549 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'last_activity' found
> 2018-03-31 06:13:19.555 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(last_activity_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.736.0>
> 2018-03-31 06:13:19.556 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_admin_extra at abode-home-portal
> 2018-03-31 06:13:19.557 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_caps at abode-home-portal
> 2018-03-31 06:13:19.562 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(caps_features_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.739.0>
> 2018-03-31 06:13:19.568 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(caps_requests_cache, [{max_size,1000},{life_time,600000}]) at pid <0.741.0>
> 2018-03-31 06:13:19.568 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'caps_features' found
> 2018-03-31 06:13:19.573 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_configure at abode-home-portal
> 2018-03-31 06:13:19.573 [debug] <0.580.0>@gen_mod:start_module:193 loading mod_version at abode-home-portal
> 2018-03-31 06:13:19.573 [debug] <0.719.0> Supervisor ejabberd_gen_mod_sup started gen_server:start_link({local,'mod_caps_abode-home-portal'}, mod_caps, [<<"abode-home-portal">>,[]], []) at pid <0.738.0>
> 2018-03-31 06:13:19.573 [debug] <0.580.0> Supervisor ejabberd_sup started gen_mod:start_link() at pid <0.719.0>
> 2018-03-31 06:13:19.580 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(auth_cache, [{max_size,1000},{cache_missed,true},{life_time,3600000}]) at pid <0.747.0>
> 2018-03-31 06:13:19.580 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_auth:start_link() at pid <0.743.0>
> 2018-03-31 06:13:19.582 [debug] <0.181.0>@ejabberd_mnesia:schema:203 No custom Mnesia schema for table 'oauth_token' found
> 2018-03-31 06:13:19.609 [debug] <0.164.0> Supervisor cache_tab_sup started ets_cache:start_link(oauth_cache, [{max_size,1000},{life_time,3600000},{cache_missed,true}]) at pid <0.750.0>
> 2018-03-31 06:13:19.620 [debug] <0.580.0> Supervisor ejabberd_sup started ejabberd_oauth:start_link() at pid <0.749.0>
> 2018-03-31 06:13:19.620 [info] <0.66.0>@ejabberd_cluster_mnesia:wait_for_sync:124 Waiting for Mnesia synchronization to complete
> 2018-03-31 06:13:19.620 [info] <0.66.0>@ejabberd_app:start:59 ejabberd 18.01 is started in the node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal' in 224.97s
> 2018-03-31 06:13:19.622 [info] <0.33.0> Application ejabberd started on node 'ejabberd@ip-10-0-5-113.us-west-2.compute.internal'
> 2018-03-31 06:13:19.622 [info] <0.656.0>@ejabberd_listener:init_tcp:140 Start accepting TCP connections at [::]:5222 for ejabberd_c2s

**Comment by Hassnain-Alvi** [comment]
@zinid Any update on this?

**Comment by zinid** [comment]
Initializing Mnesia tables consumes several minutes. Something is wrong with Mnesia (corrupted?) or problems with disk I/O. Try to start ejabberd with empty Mnesia directory to check.

**Comment by Hassnain-Alvi** [comment]
@zinid I am joining a cluster and its the fresh installation 
Does deleting Mnesia directory delete all cluster related information and break the cluster?

**Comment by badlop** [comment]
> Does deleting Mnesia directory delete all cluster related information

I think yes. If you stop a node, delete its mnesia spool dir (where clustering information is stored), and start that node, then a new empty Mnesia database is created. This means that node is independent, out of the old cluster. You can add it again using the command "join_cluster", as you did before, right?
