### ISSUE TITLE
ejabberd relays the presence subscription request only after the contact is logout and login again 

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#2352]
> What version of ejabberd are you using?

version 17.08

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source build on ubuntu

> What did not work as expected? Are there error messages in the log? What

1. User A (swordfish) and contact B (aaa123) hosted on the same ejabberd server;  and are both online but no presence subscription of each other 

2. User A sends a presence subscription request to contact B.
`<presence to='aaa123@atalk.org' id='CQmXi-409' type='subscribe'><nick xmlns="http://jabber.org/protocol/nick">swordfish@atalk.org</nick></presence>`

3. ejabberd server receives the request and response with roster status update to user A. 
`<iq to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='set' id='push7413189444113067499'><query ver='a18ca19f2b9132051844e7d2a1c273cc5e945bc7' xmlns='jabber:iq:roster'><item ask='subscribe' name='aaa123@atalk.org' jid='aaa123@atalk.org'><group>friends</group></item></query></iq>`

4. ejabberd server however does not relay this request to contact B upon receiving the request from A. It sends the authorization request to contact B, only after contact B has logoff and login again.
`<presence to='aaa123@atalk.org/atalk' from='swordfish@atalk.org' type='subscribe'/>`

> was the unexpected behavior? What was the expected result?

ejabberd server should relay the Presence Subscription Request to contact B if already online and has not previously ignored the request since last login; ejabberd should not wait until contact B logoff and login again.
see https://xmpp.org/rfcs/rfc6121.html#sub-request-inbound
3.1.3.  Server Processing of Inbound Subscription Request

**Comment by zinid** [comment]
> ejabberd server however does not relay this request to contact B upon receiving the request from A. It sends the authorization request to contact B, only after contact B has logoff and login again

Which means basic functionality is broken? Which is checked in the test suite. Are you sure about that?

**Comment by cmeng-git** [comment]
So far this is my observations after many rounds of testing. Contact B only
see the Authorization request prompt after logoff and login.  I will carry
out more testing to re-confirm this.

**Comment by zinid** [comment]
You're better of enabling debug and see if ejabberd relays the subscription request.

**Comment by cmeng-git** [comment]
Thanks for the advice, Actually I have ejabberd debug on at all the time. When the problem happened, I checked the ejabberd.log and found that ejabberd did received the request, but there is no trace of it relays the request to contact B. But I am not very sure now whether the test environment was setup correctly then.

All the testings are performed on my two android devices Note8 as user A and Note3 as contact B. I traced the devices log, and was not able to see the requests being relayed to contact B in all my previous tests. 

However just half hour ago, I saw ejabberd did relayed the request to contact B, however smack immediately throws ConnectionListenerError Exception, and terminated the stream. Upon smack re-connection, ejabberd did again relayed the request, but there is no authorization prompt being displayed on the contact device. But I believe this is aTalk.apk problem.

I need to spent some time to clear all these noises, before I can perform more tests to ascertain if the problem happens intermittently. Will come back to you once I have the answers.

**Comment by cmeng-git** [comment]
Following is the whole test environment setup for testing Presence Subscription Request.
a. ejabberd server 17.08 on ubuntu 16.04 - home server
b. Note 8 - installed with aTalk xmpp client (user - swordfish@atalk.org)
c. Note 3 - installed with aTalk xmpp client (contact/buddy - aaa123@atalk.org)
d. Both devices are set to have accept-all enabled on receiving presence subscription request

As I am using the same two devices for repeating tests, I removed the subscribed contact from both the devices after each test. Then restart aTalk app on both devices before the next test as much as possible. 
In all my observation, I will only list the smack debug log captured on both the devices for clarity. I have checked and confirmed that all log reported by devices are correctly reflected in timing and stanza sending and receiving in ejabberd log.

The process of presence subscription involves two distinct steps as performed by Roster class in Smack 4.2.3 i.e. createEntry()
        rosterPacket.addRosterItem(item);
        connection.createStanzaCollectorAndSend(rosterPacket).nextResultOrThrow();
        sendSubscriptionRequest(user);
 
- a roster entry is created, if successful then proceed to presence subscribe.

**Observations: # 1**
1.a On removing subscribed on Note 8; correct response as captured in log. Contact removed from aTalk Contact List window.
```
04-03 08:52:30.340 23475-29303/org.atalk.android D/SMACK: SENT (0): <iq id='KsB51-136' type='set'><query xmlns='jabber:iq:roster'><item jid='aaa123@atalk.org' name='aaa123@atalk.org' subscription='remove'></item></query></iq>
04-03 08:52:30.832 23475-29304/org.atalk.android D/SMACK: RECV (0): <iq to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='set' id='push16775580132441171636'><query ver='0ec6508444796c502c41aea673ee00198b56b441' xmlns='jabber:iq:roster'><item subscription='remove' jid='aaa123@atalk.org'/></query></iq>
04-03 08:52:30.833 23475-29304/org.atalk.android D/SMACK: RECV (0): <presence to='swordfish@atalk.org/atalk' from='aaa123@atalk.org/atalk' type='unavailable'/>
04-03 08:52:30.834 23475-29304/org.atalk.android D/SMACK: RECV (0): <iq xml:lang='en' to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='result' id='KsB51-136'/>
04-03 08:52:30.857 23475-29303/org.atalk.android D/SMACK: SENT (0): <iq to='swordfish@atalk.org' id='push16775580132441171636' type='result'></iq><r xmlns='urn:xmpp:sm:3'/>
```
1.b On removing subscribed on Note 3: No reply from ejabberd, so smack throws NoResponseException after timeout. Because of error, the contact still being displayed in aTalk contact list until exit and login again.
```
04-03 08:52:16.821 18755-19282/org.atalk.android D/SMACK: SENT (0): <iq id='rCzZQ-100' type='set'><query xmlns='jabber:iq:roster'><item jid='swordfish@atalk.org' subscription='remove'></item></query></iq>
04-03 08:52:26.831 18755-19980/org.atalk.android W/System.err: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 10000ms (~10s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=rCzZQ-100)), : fromFilter (OrFilter: (FromMatchesFilter (full): null, FromMatchesFilter (ignoreResourcepart): aaa123@atalk.org, FromMatchesFilter (full): atalk.org)).
```
**Observations: # 2**
Exit aTalk and relogin on both devices.
2.a Add contact (aaa123) in Note-8: 
Upon receipt the presence subscription on Note-3, in return it also sends presence subscription to swordfish as depicted in the following log. 
By right, smack should trigger the aTalk upper app level to auto approve the request, but seems this is not happening - need to investigate.
```
04-03 09:39:32.688 21712-21834/org.atalk.android D/SMACK: SENT (0): <presence to='aaa123@atalk.org' id='771tF-120' type='subscribe'><x xmlns='vcard-temp:x:update'><photo>2644872feed4850eb50d8562f17e2bc84932164c</photo></x></presence>
04-03 09:39:32.886 21712-21835/org.atalk.android D/SMACK: RECV (0): <iq to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='set' id='push12287248691357614277'><query ver='72e66ad9287b34f65dcb5d1eccc830ee6d1e01d0' xmlns='jabber:iq:roster'><item ask='subscribe' name='aaa123@atalk.org' jid='aaa123@atalk.org'/></query></iq>
04-03 09:40:20.908 21712-21835/org.atalk.android D/SMACK: RECV (0): <iq to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='set' id='push3762097389260607737'><query ver='466abacd4c677bbe66886fb7611225215816efc0' xmlns='jabber:iq:roster'><item ask='subscribe' name='aaa123@atalk.org' jid='aaa123@atalk.org'/></query></iq>
04-03 09:40:20.910 21712-21835/org.atalk.android D/SMACK: RECV (0): <presence xml:lang='en' to='swordfish@atalk.org/atalk' from='aaa123@atalk.org' type='subscribe' id='xWPf7-89'><x xmlns='vcard-temp:x:update'/></presence>
04-03 09:40:20.914 21712-21834/org.atalk.android D/SMACK: SENT (0): <a xmlns='urn:xmpp:sm:3' h='36'/><iq to='swordfish@atalk.org' id='push3762097389260607737' type='result'></iq>
04-03 09:40:20.979 21712-21835/org.atalk.android D/SMACK: RECV (0): <iq to='swordfish@atalk.org/atalk' from='swordfish@atalk.org' type='set' id='push14590491973729192275'><query ver='b58f40f40fbf2fe0fba713f88617f881a5f01a75' xmlns='jabber:iq:roster'><item subscription='to' name='aaa123@atalk.org' jid='aaa123@atalk.org'/></query></iq>
04-03 09:40:20.986 21712-21835/org.atalk.android D/SMACK: RECV (0): <presence xml:lang='en' to='swordfish@atalk.org/atalk' from='aaa123@atalk.org' type='subscribed' id='xWPf7-90'><x xmlns='vcard-temp:x:update'/></presence>
```
2.b Note-3 upon receipt presence subscribe:
Do not know why smack throws callConnectionClosedOnErrorListener. Not sure who is causing this.
```
04-03 09:39:33.821 28008-28177/org.atalk.android D/SMACK: RECV (0): <presence xml:lang='en' to='aaa123@atalk.org/atalk' from='swordfish@atalk.org' type='subscribe' id='771tF-120'><x xmlns='vcard-temp:x:update'><photo>2644872feed4850eb50d8562f17e2bc84932164c</photo></x></presence>
04-03 09:40:11.211 28008-28177/org.atalk.android W/aTalk: [9] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[aaa123@atalk.org/atalk] (0) closed with error
    org.jivesoftware.smack.SmackException: Parser got END_DOCUMENT event. This could happen e.g. if the server closed the connection without sending a closing stream element
```
2.c After auto re-connection; smack is configured to reconnect upon closed on error. ejabberd will relay the subscribe stanza (\</delay\>).

```
04-03 09:40:19.251 28008-28297/org.atalk.android D/SMACK: XMPPConnection (XMPPTCPConnection[aaa123@atalk.org/atalk] (0)) will reconnect in 1
04-03 09:40:20.261 28008-28297/org.atalk.android D/SMACK: XMPPConnection (XMPPTCPConnection[aaa123@atalk.org/atalk] (0)) will reconnect in 0
04-03 09:40:21.001 28008-28297/org.atalk.android D/SMACK: XMPPConnection connected (XMPPTCPConnection[aaa123@atalk.org/atalk] (0))
04-03 09:40:21.261 28008-28297/org.atalk.android D/SMACK: User logged (0): aaa123@atalk.org:5222/atalk
04-03 09:40:21.281 28008-28301/org.atalk.android D/SMACK: RECV (0): <presence xml:lang='en' to='aaa123@atalk.org/atalk' from='swordfish@atalk.org' type='subscribe' id='771tF-120'><x xmlns='vcard-temp:x:update'><photo>2644872feed4850eb50d8562f17e2bc84932164c</photo></x><delay from='atalk.org' stamp='2018-04-03T01:39:33.869835Z' xmlns='urn:xmpp:delay'>Resent</delay></presence>
04-03 09:40:21.291 28008-28300/org.atalk.android D/SMACK: SENT (0): <iq id='xWPf7-88' type='set'><enable xmlns='urn:xmpp:carbons:2'/></iq>
04-03 09:40:21.311 28008-28213/org.atalk.android I/aTalk: [11] impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.processSubscribe().1499 Approve and return request if required for contact: swordfish@atalk.org
04-03 09:40:21.311 28008-28300/org.atalk.android D/SMACK: SENT (0): <presence to='swordfish@atalk.org' id='xWPf7-89' type='subscribe'><x xmlns='vcard-temp:x:update'></x></presence>
    SENT (0): <presence to='swordfish@atalk.org' id='xWPf7-90' type='subscribed'><x xmlns='vcard-temp:x:update'></x></presence>
```
2.d Note-8 sends ping to server at standby, but received connection error. Actually this also happens on Note-3 during ping.
```
04-03 10:10:21.097 21712-21834/org.atalk.android D/SMACK: SENT (0): <iq to='atalk.org' id='771tF-133' type='get'><ping xmlns='urn:xmpp:ping'/></iq><r xmlns='urn:xmpp:sm:3'/>
04-03 10:10:21.098 21712-21835/org.atalk.android W/aTalk: [19533] org.jivesoftware.smack.util.PacketParserUtils.parsePresence() Failed to parse extension element in Presence stanza: "java.net.SocketException: socket is closed" from: 'aaa123@atalk.org id: 'xWPf7-89'
04-03 10:10:21.102 21712-21834/org.atalk.android W/aTalk: [19532] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[swordfish@atalk.org/atalk] (0) closed with error
```
2.e After Note-8 reconnected and authenticated: aTalk resends the subscribe request again as it was not informed of the earlier subscribed status. This time every executed correctly.
```
04-03 10:10:28.025 21712-10223/org.atalk.android D/SMACK: SENT (0): <enable xmlns='urn:xmpp:sm:3' resume='true'/>
04-03 10:10:28.031 21712-10224/org.atalk.android D/SMACK: RECV (0): <enabled resume='true' max='300' id='g2gCbQAAAAVhdGFsa2gDYgAABfJiAAsCFGIAAOkd' xmlns='urn:xmpp:sm:3'/>
04-03 10:10:28.033 21712-10173/org.atalk.android D/SMACK: User logged (0): swordfish@atalk.org:5222/atalk
04-03 10:10:28.037 21712-10223/org.atalk.android D/SMACK: SENT (0): <presence to='aaa123@atalk.org' id='771tF-120' type='subscribe'><x xmlns='vcard-temp:x:update'><photo>2644872feed4850eb50d8562f17e2bc84932164c</photo></x></presence><iq to='swordfish@atalk.org' id='push12287248691357614277' type='result'></iq><iq to='aaa123@atalk.org' id='771tF-128' type='get'><vCard xmlns='vcard-temp'/></iq><iq to='swordfish@atalk.org' id='push3762097389260607737' type='result'></iq><iq to='atalk.org' id='771tF-133' type='get'>
04-03 10:10:32.993 21712-10224/org.atalk.android D/SMACK: RECV (0): <presence to='swordfish@atalk.org/atalk' from='aaa123@atalk.org' type='subscribe'/>
04-03 10:10:32.996 21712-10242/org.atalk.android I/aTalk: [19573] impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.processSubscribe().1499 Approve and return request if required for contact: aaa123@atalk.org
04-03 10:10:33.001 21712-10223/org.atalk.android D/SMACK: SENT (0): <iq to='swordfish@atalk.org' id='771tF-151' type='get'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist'/></pubsub></iq><presence to='aaa123@atalk.org' id='771tF-152' type='subscribed'><x xmlns='vcard-temp:x:update'><photo>2644872feed4850eb50d8562f17e2bc84932164c</photo></x></presence>
```
**Observations: # 3**
Repeat the whole test:
2.b happen on Note3
2.c happen but smack does not trigger upper level to take action and the whole subscription failed.

This is the current situation, observation may not necessary be repeated, and at time note-3 does not receive the subscription request etc.

**Comment by cmeng-git** [comment]
In all my test cases,  ejabberd usually failed to response to closing stream stanza sent from entity on exit as indicated in the following log.

Does this mean ejabberd did not detect hence to update its recorded state that the contact has log off?
If so, this may be the reason why ejabberd  fails to relay the \<presence type='subscribe'/\> stanza received from the user swordfish to its contact aaa123. 

I also observed that ejabberd does not always send the delayed \<presence type='available'/\> to contact aaa123 when he exits and login. This again may due to the same reason.

```
04-05 08:37:56.254 26941-30734/org.atalk.android D/SMACK: SENT (1): <presence id='wZ2uZ-181' type='unavailable'></presence>
    SENT (1): </stream:stream>
04-05 08:38:06.264 26941-31071/org.atalk.android I/aTalk: [21] org.jivesoftware.smack.tcp.XMPPTCPConnection.shutdown() Exception while waiting for closing stream element from the server XMPPTCPConnection[aaa123@atalk.org/atalk] (1)
    org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 10000ms (~10s). While waiting for stream closing element received
```

**Comment by zinid** [comment]
This issue becomes a complete mess.

**Comment by cmeng-git** [comment]
Sorry if my detailed description has confused you so much. My simple conclusion is I feel ejabberd has intermittent in relaying the subscribe to the contact.  You may proceed to close the issue if you believe your test
