### ISSUE TITLE
Ejabberd Connection lost in Cluster

### ISSUE THREAD

**Issue by MuddassirFarooq** [processone/ejabberd#2356]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?

CentOs

> How did you install ejabberd (source, package, distribution)?

Installer.

> What did not work as expected? Are there error messages in the log? What
no error or logs
> was the unexpected behavior? What was the expected result?

We are using 7 Ejabberd in a cluster. This setup is on aws ec2 instances and behind an application Loadbalancer. Sometimes It happens xmpp clients got disconnected and we found nothing in the logs. In our monitoring setup we found dip of low cpu on all 7 servers in cluster at time of the issue. We are unable to troubleshoot this in our setup. We don't know the reason why it happens and why there is dip in all 7 server on the cluster. Please provide the solution or some steps so that we can troubleshoot our infrastructure. There is no proof of cluster breakage in logs or in monitoring.

**Comment by mremond** [comment]
This would require deep analysis of the platform behaviour. I feel this is a real task / job and not something that can be handle on a Github issue. Sorry about that.

**Comment by MuddassirFarooq** [comment]
Any troubleshooting steps we can perform. At now we have no understanding why this happens
