### ISSUE TITLE
Stanza Forwarding

### ISSUE THREAD

**Issue by rheman** [processone/ejabberd#2359]
Hi everyone .
I am using ejabberd 18.01 (ejabberd_18.01-0_amd64.deb) under ubuntu 16.04. with mysql backend.

I just want to know if the ejabberd lastest release support Stanza Forwarding (`https://xmpp.org/extensions/xep-0297.html`)

Best regard

**Comment by zinid** [comment]
This XEP is not used standalone, but in pair with another one, such as Message Carbons (XEP-0280) or MAM (XEP-0313). So the question is quite irrelevant.
