### ISSUE TITLE
MUC/Sub events are stored in offline storage

### ISSUE THREAD

**Issue by anghiloglu-dmitrii** [processone/ejabberd#2363]
> What version of ejabberd are you using?
17.11

> What operating system (version) are you using?
ubuntu 16.10

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
There is a difference between a regular groupchat protocol and muc/sub events.
In the regular groupchat protocol messages aren't stored in offline storage.

But if user subscribe to a room all events user subscribed to are stored in offline storage: 
I've tested this events from this nodes
```xml 
urn:xmpp:mucsub:nodes:presence
urn:xmpp:mucsub:nodes:messages
urn:xmpp:mucsub:nodes:affiliations
urn:xmpp:mucsub:nodes:config
```
Each event are per user. So if have got 10 affiliation offline in room then each presence/message/room config event will generate 10 offline messages.

My config for mod_offline
```yaml 
 mod_offline:
    db_type: sql
    store_empty_body: unless_chat_state
    access_max_user_messages: 100
```
I am going to fix it modifying this method wrap from **mod_muc_room.erl** by adding **no-store** extension into the wrap message.
```erlang
-spec wrap(jid(), jid(), stanza(), binary()) -> message().
wrap(From, To, Packet, Node) ->
    El = xmpp:encode(xmpp:set_from_to(Packet, From, To)),
    #message{
       sub_els = [#ps_event{
		     items = #ps_items{
				node = Node,
				items = [#ps_item{
					    id = randoms:get_string(),
					    xml_els = [El]}]}}]}. 
```

**Comment by weiss** [comment]
> There is a difference between a regular groupchat protocol and muc/sub events.

Yes, otherwise MUC/Sub wouldn't be needed :smile:

> In the regular groupchat protocol messages aren't stored in offline storage.

Right, so they don't trigger push notifications, for example.

Why are you using MUC/Sub?

**Comment by anghiloglu-dmitrii** [comment]
I use MUC/Sub because an user can receive messages without having to send presence to the room. 
I followed documentation https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub

> Add the ability to re sync the client for missed messages on reconnect. We will leverage Message Archive Management service for MUC

Storing events in the offline storage doesn't resolve use case when user has got 2 resources. If one of the resources is online another will receive nothing. I don't know how to synchronise between state between 2 resources using offline store. Please advise if there is a way to do it.

Also storing each event in the offline storage may cause flood of messages in the offline storage because each message/event is multiplied to offline affiliations number. And I thought that is why offline storage is disabled for regular group chat protocol and should be disabled for MUC/Sub protocol.

So if it by design and all muc/sub events should be stored into offline storage -> ok.
So I have 2 option:
1. don't use MUC/Sub and join every reconnect.
2. disable storing muc for MUC/Sub events and sync resources using mam.
Please advise.
Thank you.

**Comment by anghiloglu-dmitrii** [comment]
> What's the problem with sending presence?
No problem, but I tried to reduce number of packet send from mobile device, avoid freezes and save battery life.

> Ah, indeed, without a <store/> hint, the events won't go into the user's MAM archive 
MUC/Sub events don't go to MAM at all. There are stored only messages for group chat in the archive. So I have message wrapped into MUC/Sub events(+ all subscribed events) in offline storage and messages  in the MAM. Messages are duplicated in MAM and offline storage. My idea don't store events in offline. I add no-store hint to message event not the message sent by user. So I have only message stored in MAM.

> and therefore not trigger push notifications in this situation.
Yes it's a problem, now I send push on every message in group chat, no matter if user online or offline. Bad but I try to reduce load to database. The best solution for me, I think, working around store_offline_message hook which will trigger push, and return drop denying store in the offline storage(if it will work, I have to test it.).

Thank you, more thing became more clear for me now.

**Comment by cromain** [comment]
I suggest to close this thread, as @weiss gave some explanations, and title just describes what muc/sub are designed for. this is an expected behavior.
