### ISSUE TITLE
config rules do not work consistently when given access or allow clauses

### ISSUE THREAD

**Issue by kooshywoosh** [processone/ejabberd#2364]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Ubuntu 16.04.4

> How did you install ejabberd (source, package, distribution)?

binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The `who` rules do not work consistently when given `access` / `allow` clauses.

It's unclear that these won't work:
```
  "admin access":
    who:
      - access:
          - allow:
            - ip: "::ffff:47.32.132.221"
      - access:
          - allow:
            - acl: loopback
```
```
  "admin access":
    who:
      - access:
          - allow:
            - ip: "::ffff:47.32.132.221"
          - allow:
            - acl: loopback
```
```
  "admin access":
    who:
      - access:
          - allow:
            - ip: "::ffff:47.32.132.221" 
```

Whereas the following do:
```
  "admin access":
    who:
       - acl: loopback
       - ip: "::ffff:47.32.132.221" 
```
```
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
```

In the first two cases, access is denied from both the ip and loopback.
In the third case access from the ip is denied.
In the fourth case access for both work fine.
In the fifth case, access for the loopback works fine.

I've tested this with the same curl request from the server running ejabber itself and a postman request from the specified IP address. It seems like if the `who` is given multiple `access` or `allow` items, they all are ignored. If just `access` and `allow` are present with one child, ip addresses do not work but acls do.

Also, per the current layout of the online documentation, it's really confusing to know that the description, for a rule e.g. `This will accept user admin@server.com or commands originating from localhost` applies to the block ABOVE not BELOW since it's closer to the below block. Sadly, this threw me for a couple hours while I was trying to configure api access... I'm not the first and likely not the last.

Screenshot:
![screen shot 2018-04-04 at 3 52 57 pm](https://user-images.githubusercontent.com/5790010/38338876-4cf84632-3820-11e8-8204-547ba8c2b2cf.png)

**Comment by prefiks** [comment]
All of those should work, and in my tests with my local server they do work (i checked with pretty recent version, but i don't think there was any change since your version that should affect this).

If you have loglevel set to 5 api calls should generate log message with "Command '...' execution denied ...', would you be able to try to see if you have that in your logs and copy/paste it here? Also what acl loopback looks like in your config?
