### ISSUE TITLE
MUC/Sub with temporary rooms.

### ISSUE THREAD

**Issue by mpope9** [processone/ejabberd#2365]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Ubuntu 16.10

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Right now we have 25K MUC rooms open.  When sending a MUC presence request to a room we're seeing quite a large response time from ejabberd.  We've confirmed the cause is the large amount of muc rooms by incrementally making more MUC rooms and witnessing the response time for the presence request increase at the same rate.  Looking at [this](https://github.com/processone/ejabberd/issues/1385) issue I see that we can save our rooms and mam history, but it indicates nothing about destroying the room.  We're seeing that a room has no occupants and has active subscribers and its not being destroyed.  

Here is a stanza we're using to create a room
```xml
<iq 
  xmlns="jabber:client" to="room_name@our.service" type="set" id="xyz">
  <query 
    xmlns="http://jabber.org/protocol/muc#owner">
    <x 
      xmlns="jabber:x:data" type="submit">
      <field var="FORM_TYPE">
        <value>http://jabber.org/protocol/muc#roomconfig</value>
      </field>
      <field var="muc#roomconfig_persistentroom">
        <value>1</value>
      </field>
    </x>
  </query>
</iq>
```

Here is an example of how long it takes presence
```xml
Timestamp: 16:34:46.132
<presence 
  xmlns="jabber:client" to="room1@exmaple.com/res" id="fff">
  <x 
    xmlns="http://jabber.org/protocol/muc">
    <history maxstanzas="50"/>
  </x>
  <c 
    xmlns="http://jabber.org/protocol/caps" node="node" hash="sha-1" ver="x/>
  </presence>

Timestamp: 16:35:05.858
<presence 
  xmlns='jabber:client' xml:lang='en' to='person@example.com/personRes' from='room1@example.com/room1Res id='fff'>
  <c 
    xmlns='http://jabber.org/protocol/caps' node='node' hash='sha-1' ver='x'/>
    <x 
      xmlns='http://jabber.org/protocol/muc#user'>
      <item jid='person@chat.staging.skillz.com/personRes' role='participant' affiliation='none'/>
      <status code='170'/>
      <status code='110'/>
    </x>
  </presence>
```

What do you suggest we do to speed up MUC presence.

**Comment by mpope9** [comment]
I put some thought into this.  Is there a way to make muc rooms offline, and still keep their subscribers?  Would this speed them up at all?

**Comment by badlop** [comment]
You can try to configure the muc service like this:
```yaml
modules:
  mod_muc:
    default_room_options:
      persistent: true
      allow_subscription: true
      mam: true
```
Then create rooms in any way, in my case I execute:
> ejabberdctl create_room room1 conference.localhost localhost

Then, following [the MUC/Sub document](https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/#sending-a-message), users subscribe to the room, can send messages to the room, and receive notifications, all that without taking care to send presence to the room to join it.
