### ISSUE TITLE
Push notification not working when sent a SMS

### ISSUE THREAD

**Issue by maverick2911** [processone/ejabberd#2366]
Version of ejabberd :
ejabberd 16.04.185

operating system :
Linux dummy-host 3.10.0-514.21.2.el7.x86_64

Installation method
distribution

Issue :
I made a custom module for sending push notification for offline users when they get a SMS.
I use the same module when they receive IM (instant message), though it is working fine for IM but it is not for SMS.

Module i made : 

> should_send_notification(#xmlel{name = <<"message">>} = Pkt, LServer) ->
  case fxml:get_attr_s(<<"type">>, Pkt#xmlel.attrs) of
    <<"chat">> ->
      case fxml:get_subtag_cdata(Pkt, <<"body">>) of
        <<>> ->
          %% Empty body
          false;
        <<" ">> ->
          %% space body
          false;
        <<"%20">> ->
          %% encoded space body
          false;
        _ ->
          true
      end;
    _ ->
      false
  end;
should_send_notification(_, _LServer) ->
  false.

when i send IM, user gets the push notification and the logs are : 

> 2018-04-05 14:39:31.033 [info] <0.662.0>@mod_notification:send_to_offline_resources:164 Checking offlien resources for user user1
2018-04-05 14:39:31.034 [info] <0.662.0>@mod_notification:send:77 Generated body: {"push":"some_long_string","message":{"msg":"IM test4","from":"user1","type":"chat","format":"text/plain"},"username":"user1","title":"ABC Message","badge":"1","category":"IM_ACTION","body":"user1: IM test_message"}
2018-04-05 14:39:31.494 [info] <0.662.0>@mod_notification:send:81 Sending notification from username="user1", to="user2", token="some_long_string"

While for SMS i don't get the push, but when i open app user can see the message and the logs are : 

> 2018-04-05 14:39:45.332 [info] <0.662.0>@mod_notification:send_to_offline_resources:164 Checking offlien resources for user user1
2018-04-05 14:39:45.335 [info] <0.662.0>@ejabberd_c2s:process_chat_message:1889 Send message username="user1", resource="xxxxxxx", send_to="user1", message_type=<<"sms">>, message_length="13" 

i cannot see any push here, but can see message when i open app.
When the user is offline and he gets a message  the only log is this : 

> 2018-04-05 15:15:11.071 [info] <0.1014.0>@mod_http_api:log:501 API call send_stanza [{<<"stanza">>,<<"<message><body>hello</body><message_format>\n               <fromDid>xxxxxxx</fromDid>\n               <from>xxxxxxx</from>\n               <format>sms</format>\n               <messageTime>1522966511000</messageTime>\n               <messageId>1522966511</messageId>\n               </message_format></message>">>},{<<"from">>,<<"xxxxxx">>},{<<"to">>,<<"user2@dummy-host.com">>}] from xx.xx.xx.xx:xx

But when user comes online the log i see  is  this : 

> 2018-04-05 15:18:57.946 [info] <0.1465.0>@ejabberd_c2s:process_chat_message:1889 Send message username="", resource="", send_to="user2", message_type=<<"sms">>, message_length="1" 

Any help would be highly appreciated.
Thanks in advance.

**Comment by cromain** [comment]
Are you seriously asking for free help on your custom development ?
This is not an ejabberd bug: your question is out of scope of ejabberd bug tracker. I'm closing this issue.
