### ISSUE TITLE
ejabberd - delete a roster and load a fresh one

### ISSUE THREAD

**Issue by sunstar20** [processone/ejabberd#2368]
> What version of ejabberd are you using?

ejabberd 17.09

> What operating system (version) are you using? 

Linux

> How did you install ejabberd (source, package, distribution)? 

from processone

How to delete the roster and load a fresh one?

Thanks in advance

**Comment by sunstar20** [comment]
Could you please mention the command and path to be used in ejabberd for deleting the roster and loading a fresh one.

**Comment by karbovskibg** [comment]
DANGER: DON'T USE Latest ejabberd 18.03.1 for linux 

sunstar20 don't update ejabberd to 18.03.1 it automatically convert your database to cram: https://github.com/processone/ejabberd/issues/2370

**Comment by badlop** [comment]
This command deletes all the items stored in the roster of user1@localhost. This command works only if the default Mnesia database is used for mod_roster:
> $ ejabberdctl process_rosteritems delete any any user1@localhost *@localhost
There are 4 roster items in total.
Progress 25% - visited 1 - deleted 0
Matches: user1@localhost user3@localhost
Progress 50% - visited 2 - deleted 1
Matches: user1@localhost user2@localhost
Progress 75% - visited 3 - deleted 2
Progress 100% - visited 4 - deleted 2
user1@localhost user2@localhost
user1@localhost user3@localhost

**Comment by sunstar20** [comment]
Thanks a lot

**Comment by sunstar20** [comment]
I am able to delete the roster.
![image](https://user-images.githubusercontent.com/12511931/38497062-6326e318-3c1d-11e8-8fef-da177723001b.png)

But on executing the same command again, the below data is shown. 
Could you please help.

There are 15 roster items in total.
Progress 6% - visited 1 - deleted 0
Progress 13% - visited 2 - deleted 0
Progress 20% - visited 3 - deleted 0
Progress 26% - visited 4 - deleted 0
Progress 33% - visited 5 - deleted 0
Progress 40% - visited 6 - deleted 0
Progress 46% - visited 7 - deleted 0
Progress 53% - visited 8 - deleted 0
Progress 60% - visited 9 - deleted 0
Progress 66% - visited 10 - deleted 0
Progress 73% - visited 11 - deleted 0
Progress 80% - visited 12 - deleted 0
Progress 86% - visited 13 - deleted 0
Progress 93% - visited 14 - deleted 0
Progress 100% - visited 15 - deleted 0

Is there a way to list the roster items?

**Comment by badlop** [comment]
> Is there a way to list the roster items?

Yes. For example, this will list all the roster items in accounts of your localhostst host with contacts also in that vhost:
`` 
$ ejabberdctl process_rosteritems list any any *@localhost *@localhost
There are 2 roster items in total.
Matches: user2@localhost user1@localhost
Progress 50% - visited 1 - deleted 1
Matches: user3@localhost user1@localhost
Progress 100% - visited 2 - deleted 2
user3@localhost user1@localhost
user2@localhost user1@localhost
```

**Comment by sunstar20** [comment]
**Thank** **you for the quick response. Sorry for the delayed response.**

On executing the below query after deleting/emptying the roster, the below data is shown:

**Query** **:** **./ejabberdctl** **process_rosteritems** **list** **any** **any** *@localhost *@localhost

**Data**:
There are **14** **roster** **items** in total.
Progress 7% - visited 1 - deleted 0
Progress 14% - visited 2 - deleted 0
Matches: 9@localhost ksce@localhost
Progress 21% - visited 3 - deleted 1
Matches: 74@localhost ksce@localhost
Progress 28% - visited 4 - deleted 2
Matches: 51@localhost ksce@localhost
Progress 35% - visited 5 - deleted 3
Matches: 22@localhost ksce@localhost
Progress 42% - visited 6 - deleted 4
Progress 50% - visited 7 - deleted 4
Matches: 7@localhost ksce@localhost
Progress 57% - visited 8 - deleted 5
Matches: test5@localhost ksce@localhost
Progress 64% - visited 9 - deleted 6
Matches: 25@localhost ksce@localhost
Progress 71% - visited 10 - deleted 7
Progress 78% - visited 11 - deleted 7
Matches: 56@localhost ksce@localhost
Progress 85% - visited 12 - deleted 8
Matches: 12@localhost ksce@localhost
Progress 92% - visited 13 - deleted 9
Progress 100% - visited 14 - deleted 9
12@localhost    ksce@localhost
56@localhost    ksce@localhost
25@localhost    ksce@localhost
test5@localhost ksce@localhost
7@localhost     ksce@localhost
22@localhost    ksce@localhost
51@localhost    ksce@localhost
74@localhost    ksce@localhost
9@localhost     ksce@localhost

**Could** **you** **please** **tell** **me** **if** **the** **above** **command** **lists** **the** **deleted** **roster** **items.**

**Also** **how** **the** **14** **roster** **items** **are** **retrieved** **when** **there** **are** **9+1** **(admin)** **roster** **items.**

**Thanks in advance**

**Comment by badlop** [comment]
> Could you please tell me if the above command lists the deleted roster items.

That command only provides a "list". Later you can run again, but with the argument "delete" to really delete them.

> Also how the 14 roster items are retrieved when there are 9+1 (admin) roster items.

Because there are 14 items in *total* in the database. This includes rosters of users in localhost, and also in other vhosts that you may have configured in ejabberd. Later it lists only roster items in *@localhost...

**Comment by sunstar20** [comment]
tried deleting the roster using the below command:
./ejabberdctl process_rosteritems delete any any *@localhost *@localhost but its not deleting the roster and also getting the below message

There are 32 roster items in total.
Progress 3% - visited 1 - deleted 0
Progress 6% - visited 2 - deleted 0
Progress 9% - visited 3 - deleted 0
Progress 12% - visited 4 - deleted 0
Progress 15% - visited 5 - deleted 0
Progress 18% - visited 6 - deleted 0
Progress 21% - visited 7 - deleted 0
Progress 25% - visited 8 - deleted 0
Progress 28% - visited 9 - deleted 0
Progress 31% - visited 10 - deleted 0
Progress 34% - visited 11 - deleted 0
Progress 37% - visited 12 - deleted 0
Progress 40% - visited 13 - deleted 0
Progress 43% - visited 14 - deleted 0
Progress 46% - visited 15 - deleted 0
Progress 50% - visited 16 - deleted 0
Progress 53% - visited 17 - deleted 0
Progress 56% - visited 18 - deleted 0
Progress 59% - visited 19 - deleted 0
Progress 62% - visited 20 - deleted 0
Progress 65% - visited 21 - deleted 0
Progress 68% - visited 22 - deleted 0
Progress 71% - visited 23 - deleted 0
Progress 75% - visited 24 - deleted 0
Progress 78% - visited 25 - deleted 0
Progress 81% - visited 26 - deleted 0
Progress 84% - visited 27 - deleted 0
Progress 87% - visited 28 - deleted 0
Progress 90% - visited 29 - deleted 0
Progress 93% - visited 30 - deleted 0
Progress 96% - visited 31 - deleted 0
Progress 100% - visited 32 - deleted 0

Kindly help
