### ISSUE TITLE
DANGER: DON'T USE Latest ejabberd 18.03.1 for linux

### ISSUE THREAD

**Issue by karbovskibg** [processone/ejabberd#2370]
Guys.

Don't use latest ejabberd 18.03.1 for ubuntu by default it will use scram shit password and all your plain password will automatically be converted in scram the problem come that when you use SIP AND TURN it will denied your passwords. It is inhuman WHY ejabberd make this SHIT. In version 18.01 all was working. ejabberd indirectly is INSULTING you peoples. Do someone know beter xmpp server like ejabberd i'm tired of this SHIT, it use sip but it don't work 100 %, and there is much more issues that right now i can't remember but there was days that i seek how to resolve ejabberd. And when it works with new version 18.03.1 again ejabberd INDIRECTING INSULT humankind. ejabberd has manual how to convert from plain text to scram, but there is no manual how to convert from scram to plain. If there is no manual in the moment you have two options. Delete the FUCKING SHIT database, this mean all your password will be deleted and if you have 300 users more problems. Someone comment much better xmpp server.

**Comment by karbovskibg** [comment]
Unnoficial giude how to reset FUCKING database:
https://github.com/ArchipelProject/Archipel/wiki/Developer:-Reset-ejabberd-database

From upper manual they comment all will be erased. very bad for ejabberd it just lose peoples from using it.

**Comment by weiss** [comment]
> ejabberd indirectly is INSULTING you peoples.

I'm not sure what you're smoking, but please stop spamming the ejabberd bug tracker.  If you're unhappy with some distribution package, please complain to your distribution.  Upstream ejabberd doesn't enable scram hashing of stored passwords by default.
