### ISSUE TITLE
Need some pointers for making HTTP Rest API calls to XMPP (ejabberd) service from the Cloud web app

### ISSUE THREAD

**Issue by cpremkumar** [processone/ejabberd#2373]
> What version of ejabberd are you using?

ejabberd v18.01

> What operating system (version) are you using?

Ubuntu Linux, running as Virtual Machine instance inside OpenStack cloud environment

> How did you install ejabberd (source, package, distribution)?

By downloading and installing a DEB package (.deb)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

How do I make Rest API calls from the cloud web app to ejabberd service? Any example link would help me in a big way.

The web app already uses MySql DB for user management and to manage loads of other functionalities. We'd like to extend the login session of the web app to use the ejabberd service for chat functionality. How do I go about it?

I'm thinking of a solution something like this, when a user signs up in the web app, I create a corresponding Jabber ID for the same user in ejabberd and just have an user level mapping in web app's MySql DB and ejabberd DB. Basically, I need to do all administration related functionalities like adding user, authenticating user, setting password, removing user, etc.. in ejabberd from web app via HTTP Rest API. Is this possible, and if yes, please give me some pointers.

Does external authentication script/program strictly need to receive the input parameters as mentioned in the link "https://www.ejabberd.im/files/doc/dev.html#htoc8"?

**Comment by cromain** [comment]
Yes this is possible, all is documented here: https://docs.ejabberd.im/developer/ejabberd-api/
you need to setup API permissions, and configure mod_http_api. There is config example in default ejabberd.yml config file.

**Comment by badlop** [comment]
> I need to do all administration related functionalities like adding user, authenticating user, setting password, removing user, etc.. in ejabberd from web app via HTTP Rest API.

ejabberd provides commands for all this, see them at https://docs.ejabberd.im/developer/ejabberd-api/admin-api/

There are several ways to execute them. For playing, you can use ejabberdctl in the shell. Later you can use XML-RPC queries to ejabberd (if you enable ejabberd_xmlrpc), ReST queries (if you enable mod_http_api, see https://docs.ejabberd.im/developer/ejabberd-api/simple-configuration/ )...
