### ISSUE TITLE
Parent attribute missing on thread element

### ISSUE THREAD

**Issue by stevenlivz** [processone/ejabberd#2375]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Mac but this is on debian:jessie docker image at https://hub.docker.com/r/rroemhild/ejabberd/

> How did you install ejabberd (source, package, distribution)?

From https://hub.docker.com/r/rroemhild/ejabberd/

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

If I send in the following message to ejabberd as per [XEP-0201 "Child Threads"](https://xmpp.org/extensions/xep-0201.html#child):

```
<message to="steven@localhost" from="admin@localhost" type="chat">
<thread parent="1111111111">2222222</thread>
<body>hello</body>
</message>
```

... the parent attribute seems to be dropped. I looked at the definition of "thread" in the message record for [your XMPP parser](https://github.com/processone/xmpp/blob/master/include/xmpp_codec.hrl#L30) and i'm not sure where parent is/should be set. 

```
14:58:54.569 [debug] route:
#message{id = <<>>,type = chat,lang = <<"en">>,
         from = #jid{user = <<"admin">>,server = <<"localhost">>,
                     resource = <<"alchemy">>,luser = <<"admin">>,
                     lserver = <<"localhost">>,lresource = <<"alchemy">>},
         to = #jid{user = <<"steven">>,server = <<"localhost">>,
                   resource = <<>>,luser = <<"steven">>,
                   lserver = <<"localhost">>,lresource = <<>>},
         subject = [],
         body = [#text{lang = <<>>,data = <<"hello">>}],
         thread = <<"2222222">>,sub_els = [],
         meta = #{ip => {172,17,0,1},mam_archived => true,stanza_id => 1523372334554224}}
```

Maybe I am missing something?

regards,
steven

**Comment by zinid** [comment]
Fixed.
The `thread` field will now contain `#message_thread{}` record, see the description [here](https://github.com/processone/xmpp/blob/master/include/xmpp_codec.hrl#L225)
