### ISSUE TITLE
Cannot set nick on HTTP/REST API set_room_affiliation

### ISSUE THREAD

**Issue by Jack12816** [processone/ejabberd#2378]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

ubuntu:18.04

> How did you install ejabberd (source, package, distribution)?

distribution package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm a bit confused about the HTTP/REST API. [POST /api/set_room_affiliation](https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#set-room-affiliation).

With this call, I am able to grant access as an administrator to a regular user for a members-only room. But I cannot set the nickname of the user at this point which should be possible due to the [XEP-0045](https://xmpp.org/extensions/xep-0045.html#grantmember) specs.

```xml
<iq from='crone1@shakespeare.lit/desktop'
    id='member1'
    to='coven@chat.shakespeare.lit'
    type='set'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item affiliation='member'
          jid='hag66@shakespeare.lit'
          nick='thirdwitch'/>
  </query>
</iq>
```

Is there something I'm missing? Or is this a missing feature?

Thanks for the great software anyway!

**Comment by badlop** [comment]
> (if a nick is provided, that nick becomes the user's default nick in the room if that functionality is supported by the implementation)

From what I see in the source code, that feature is not supported. In this sense, that command does not provide any way to provide a default-nick. 

And also, I use Tkabber as test client, which allows to provide a default-nick when granting membership... and ejabberd does not store that nick.

**Comment by badlop** [comment]
ejabberd's MUC implementation does not support the optional feature of "default reserved nick in a room", as defined in https://xmpp.org/extensions/xep-0045.html#reservednick so that command does not need a nick argument.

On the other hand, ejabberd supports a nick registration for the whole MUC service .
