### ISSUE TITLE
ejabberd 0.0 is running in that node

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#2379]
> What version of ejabberd are you using?
17.12 

> What operating system (version) are you using?
CentOS7

> How did you install ejabberd (source, package, distribution)?
source

I have downloaded code of ejabberd 17.12 and built its started but something looks weird is 

```
The node ejabberd@localhost is started with status: started
ejabberd 0.0 is running in that node

```
Doest it make any problem if it ejabberd running on 0.0 node? why does it choose 0.0 node?

@badlop 

Thanks in advance !!!

**Comment by prefiks** [comment]
It should doesn't matter, version is generated from git tag/commits so if you built ejabberd outside git worktree you just get bogus version, but it's not really used for anything substantial.
