### ISSUE TITLE
[question] Module: sending its own presence

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#2380]
> What version of ejabberd are you using?

17

> What operating system (version) are you using?

Linux AMD64

> How did you install ejabberd (source, package, distribution)?

your builtin package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have built a module of mine, it's acting like some sort of echo server, It's registered and works as a service subdomain (`echo.<XMPP Domain>`). I'd like to add it's own presence (not on behalf of someone else) so my external clients will have its status and presence, it's obviously always online but it's enough for me. Is there a way to send <presence> packets from it ? Is there some sort of hook or function to call in order to send <presence> packets during module startup ? Any hints ?
 

Thanks in advance for your reply
Ben

**Comment by cromain** [comment]
you're module have its own route, there is no need/reason to set presence. you should read code of other modules to understand how internal stuff works, and how to route packets. it seems everything you need is done in mod_echo.
