### ISSUE TITLE
eimp requires outdated versions of libraries

### ISSUE THREAD

**Issue by oxoWrk** [processone/ejabberd#2383]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

Debian 9.4

> How did you install ejabberd (source, package, distribution)?
Linux Installer

eimp requires outdated versions of libraries: libjpeg8(Debian 7 !!!!!), libpng12, libwebp2

**Comment by cromain** [comment]
This is a known problem which is solved in 18.04 in our installer
