### ISSUE TITLE
How can i call my custom module by adding hook to mod_http_api

### ISSUE THREAD

**Issue by maverick2911** [processone/ejabberd#2384]
> Ejabberd version : 16.04

> Linux myhost 3.10.0-514.21.2.el7.x86_64

> Installation method : distribution

there is a need to send some stanzas to ejabberd via rest api (mod_http_api)
I want to call my custom module which i made for sending push notifications by adding a hook to it.
Is it a good way, if not how can i achieve it otherwise. (call my custom module without altering core module).

Also the hook ```offline_message_hook``` in 16.04 only have three params : 
```_From, _To, Packet```
How can i access following using the same hook : 
LServer, Peer.

thanks in advance.

**Comment by zinid** [comment]
We don't have support for legacy versions due to limited resources. Please update ejabberd and use `mod_push` instead.
I close the ticket.

**Comment by maverick2911** [comment]
Thanks for the update.
fact is i cannot update it due to heavy-lifting of GDPR this month, so if you can point me towards a work-around (if there is one and i hope there would be), that would be helpful.

thanks
