### ISSUE TITLE
External eimp process has terminated unexpectedly

### ISSUE THREAD

**Issue by HGehrmann** [processone/ejabberd#2385]
> What version of ejabberd are you using?

18.03, updated from 18.01

> What operating system (version) are you using?

CentOS 7.4.1708

> How did you install ejabberd (source, package, distribution)?

RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Every second the following log entry is created in crash.log, ejabberd.log, error.log:
```
[error] <0.172.0> External eimp process (pid=13609) has terminated unexpectedly, restarting in a few seconds
```
The number in <> changes and the pid counts ascending.

**Comment by cromain** [comment]
your system miss eimp dependencies: libgd and libwebp
see https://github.com/processone/ejabberd/issues/2362
this will be fixed in 18.04 (bundled eimp will be build without img support, see https://github.com/processone/ejabberd/issues/2383)
