### ISSUE TITLE
Ejabberd compilation error  in xmpp_stream.in.erl

### ISSUE THREAD

**Issue by edukondalugorla** [processone/ejabberd#2386]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

ubuntu 15

> How did you install ejabberd (source, package, distribution)?

source

> While compiling the ejabberd, i am getting below error

src/xmpp_stream_in.erl:633: field resource undefined in record bind
src/xmpp_stream_in.erl:634: variable 'R' is unbound
Compiling src/xmpp_stream_in.erl failed:

**Comment by zinid** [comment]
Seems like deps is outdated, try `make distclean` and repeat the compile process.
