### ISSUE TITLE
How can I‌ disallow links being posted in MUC?

### ISSUE THREAD

**Issue by k0fi** [processone/ejabberd#2388]
I'm struggling with link spammers in my ejabberd chatroom. I'm wondering what is the best solution to disalow certain urls (or certain strings) to be posted into a MUC?

**Comment by badlop** [comment]
There isn't what you mention.

mod_muc has some useful options:
* access: allow only accounts from your vhosts to join your rooms
* public: only people that know the room name will be able to join it, so spammers can't find it
* captcha_protected: to join the room, the user has to solve a captcha

You can also look at mod_pottymouth.
