### ISSUE TITLE
ns.hrl and fxml.hrl not found when building modules, error in jlib.hrl again

### ISSUE THREAD

**Issue by asevans48** [processone/ejabberd#2389]
> What version of ejabberd are you using? 
18.03

> What operating system (version) are you using?
Ubuntu latest

> How did you install ejabberd (source, package, distribution)?
Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I installed the package from the website. The program works well. When I try to install modules, as some in previous issues noticed, I received the following error:

********/lib/ejabberd-18.03/include/jlib.hrl:21: can't find include file "ns.hrl"
*******/lib/ejabberd-18.03/include/jlib.hrl:22: can't find include file "fxml.hrl"

The module I am trying to compile specifically is mod_webpresence. I am following the instructions at erlang-contrib and opened a ticket there as well. The error was presented here in the past. Thanks

**Comment by zinid** [comment]
`jlib.hrl` is a deprecated header and should not be used with ejabberd 17.x-18.x. Seems like the module is outdated.

**Comment by badlop** [comment]
Problem tracked here: https://github.com/processone/ejabberd-contrib/issues/241
