### ISSUE TITLE
Hidden Service (feature request)

### ISSUE THREAD

**Issue by gongzisun** [processone/ejabberd#2390]
Will openfire consider implementing a proxy option for s2s?

I am in a country full of surveillance and censorship.

We can just use hidden service like onion/i2p for anti-censorship, if hidden xmpp server can connect each other, we can build countless server.

**Comment by zinid** [comment]
> Will openfire consider implementing a proxy option for s2s?

Ask openfire guys. This is ejabberd bugtracker.

**Comment by gongzisun** [comment]
Sorry for that, i thought i am in that repo, but i want know that in the ejabberd too, sorry again for my impolite behaviour。

**Comment by zinid** [comment]
No, we have no such plans.

**Comment by gongzisun** [comment]
Thank you, and sorry again.

best wish.
