### ISSUE TITLE
Compilation: Failed to extract name

### ISSUE THREAD

**Issue by vanitasvitae** [processone/ejabberd#2391]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

```
uname -a
Linux raspian01 4.14.30+ #1102 Mon Mar 26 16:20:05 BST 2018 armv6l GNU/Linux
```

> How did you install ejabberd (source, package, distribution)?

Compilation from source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I try to compile ejabberd using `./configure --enable-mysql --enable-user=ejabberd && make update && make && sudo make install`, I get the following error in the `make update` step.

```
/usr/lib/erlang/bin/escript rebar update-deps && :> deps/.got
ERROR: Failed to extract name from /tmp/ejabberd/src/ejabberd.app.src: {error,
                                                                                     {error,
                                                                                      {9,
                                                                                       erl_parse,
                                                                                       ["syntax error before: ",
                                                                                        "'@'"]}}}
Makefile:112: die Regel für Ziel „update“ scheiterte

```
If I try to compile 18.01 however, it works. I assume some dependency is out of date?

**Comment by vanitasvitae** [comment]
It looks like the issue disappeared after I ran `./autogen.sh`. I had not tried that because this was an attempt to update an existing installation.

**Comment by zinid** [comment]
Yeah, you have to run `autogen.sh` in order to compile from git.
