### ISSUE TITLE
Ejabberd v18.01 clustering with v17.04

### ISSUE THREAD

**Issue by Hassnain-Alvi** [processone/ejabberd#2392]
> What version of ejabberd are you using?

Ejabberd v18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

installer Package (.run)

This issue is generated for informational purposes. 
We are using ejabberd 17.04 cluster in our production environment and want to upgrade our infrastructure gradually to v18.01. 
We want to know if there is any known issues that may occur when an ejabberd node running v18.01  join a cluster with a node running v17.04? Does it break something? or its completely backward compatible with v17.04 cluster?

**Comment by zinid** [comment]
It's hard to say because we don't test such compatibility, but the general advise is to avoid such setups, because Erlang relies on message passing and the format of some messages being passed might differ between ejabberd versions. So it might work, or might not.

**Comment by Hassnain-Alvi** [comment]
@zinid Thanks for clarification but if we use the same Erlang version. but create a cluster between v17.04 and v18.01, will it work? or will it break something?

**Comment by badlop** [comment]
Additionally, ejabberd may use different message formats between those two versions. So, maybe roster breaks, or rooms, or presence. Or nothing breaks. Or all breaks. To be sure, it would require checking the changes in the internal structures shared between nodes in those two versions. I guess you don't expect anybody to spend time checking that, just to solve that question... You have two paths:
A) Try yourself
B) ot Install the same ejabberd version in both nodes.

**Comment by Hassnain-Alvi** [comment]
@badlop Thanks for the clarification
