### ISSUE TITLE
Ejabberd 18.01 - "Error running post install script.

### ISSUE THREAD

**Issue by bobbybongarala** [processone/ejabberd#2394]
> What version of ejabberd are you using?
18.01

> What operating system (version) are you using?
Win 7 x64

> How did you install ejabberd (source, package, distribution)?
Windows installer  - ejabberd-18.01-windows-installer.exe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
- Installation Error while Executing final installation script.
![image](https://user-images.githubusercontent.com/38499422/38936205-4beadb1e-42ee-11e8-872f-c334760afac8.png)
message "Error running Post Install Script.  The installation may have not completed correctly."
- no Errors in the log file,

[install.log](https://github.com/processone/ejabberd/files/1924502/install.log)
[ejabberd.log](https://github.com/processone/ejabberd/files/1924509/ejabberd.log)

- cannot log on to web Admin as the Service(s) does not start,

**Comment by cromain** [comment]
it seems ejabberd started, but maybe it took time to perform some data migration if you're upgrading, so ejabberdctl started failed.
does 'ejabebrdctl started' always return error code ?

**Comment by bobbybongarala** [comment]
it is not an upgrade, its a new install and always the errorlevel is 1

**Comment by bobbybongarala** [comment]
Windows registerd application error log
========================\
Log Name:      Application
Source:        Application Error
Date:          4/20/2018 09:59:23
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DNCADDEMO-1
Description:
Faulting application name: erl.exe, version: 0.0.0.0, time stamp: 0x5a2efb31
Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f83ff
Exception code: 0xc0000005
Fault offset: 0x000000000003c798
Faulting process id: 0x1c20
Faulting application start time: 0x01d3d8afc883f7e8
Faulting application path: C:\Program Files\ejabberd-18.01\bin\erl.exe
Faulting module path: C:\Program Files\ejabberd-18.01\bin\MSVCR120.dll
Report Id: 07324ec7-44a3-11e8-b06e-005056c00008
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-20T13:59:23.000000000Z" />
    <EventRecordID>26658512</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DNCADDEMO-1</Computer>
    <Security />
  </System>
  <EventData>
    <Data>erl.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5a2efb31</Data>
    <Data>MSVCR120.dll</Data>
    <Data>12.0.21005.1</Data>
    <Data>524f83ff</Data>
    <Data>c0000005</Data>
    <Data>000000000003c798</Data>
    <Data>1c20</Data>
    <Data>01d3d8afc883f7e8</Data>
    <Data>C:\Program Files\ejabberd-18.01\bin\erl.exe</Data>
    <Data>C:\Program Files\ejabberd-18.01\bin\MSVCR120.dll</Data>
    <Data>07324ec7-44a3-11e8-b06e-005056c00008</Data>
  </EventData>
</Event>

**Comment by cromain** [comment]
what if you remove C:\Program Files\ejabberd-18.01\bin\MSVCR120.dll then ?

**Comment by bobbybongarala** [comment]
just reinstalled VCredist 2013x64 again and I am able to launch the service, but it doest let me log on to web admin@localhost and the correct password.
