### ISSUE TITLE
Ejabberd SQL result error

### ISSUE THREAD

**Issue by edukondalugorla** [processone/ejabberd#2395]
> What version of ejabberd are you using?

18.02

> What operating system (version) are you using?

Ubuntu 15

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What

Error message while executng stored procedure

> was the unexpected behavior? What was the expected result?

Hi I am getting below error while executing sql query, The Error is in ejabberd_sql line number 734 error message

```

`Error while processing SQL query result: {error,function_clause,[{mod_mychat,'-process_get_agent/1-fun-1-',...........
`

```

**Comment by cromain** [comment]
error is explicit, and not into ejabberd_sql.
you have a function clause error in your module mod_mychat:process_get_agent/1 un a lambda fun.
