### ISSUE TITLE
MSSQL Schema column types

### ISSUE THREAD

**Issue by brobaniuc** [processone/ejabberd#2397]
> What version of ejabberd are you using?
ejabberd 18.03

> What operating system (version) are you using?
RHEL7

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
While there is not current MSSQL schema for MSSQL server I did the corresponding changes based on the postgre SQL schema. 
I also found some unsupported MSSQL design like:
- In MSSQL we can only have one clustered index the others must be nonclustered
- the field type text is not fully supported by MSSQL in the sense of ordering by it or maybe use it in triggers. For example on pubsub_item table we have the column "creation" which I saw is storing a time stamp but is declared of type text. Next in the queries it is used for sorting, which throws an error. Also there is the column 'modification' on the same table that is of type varchar(255). I think that both can be changed to a shorter varchar. I did changed the creation to varchar(255) and seems to work.

A request if possible could we have the system not delete the archive records in case the muc room is removed. 

Thanks you.

**Comment by cromain** [comment]
Yep, the schema is far from perfect, and mssql support is not at best. If you suggest a patch i'll review it for inclusion.
The issue with pubsub creation/modification is about using same code for many different backends, not necessary all being SQL. Using timestamp is best of course but would likely need different encoding per sql database (not sure mssql format is same as pgsql or mysql, but i'm not an sql expert anyway). varchar(24) will even be enough for the encoding we're using on timestamps, and is for now the most generic we can use.

Please one item per issue: create a new issue for archive records.

**Comment by cromain** [comment]
i'll change type of creation and modification from text to varchar(32)

**Comment by cromain** [comment]
use of varchar(32) will speedup get_items requests, and enough room is left on the record if we change encoding later.

**Comment by brobaniuc** [comment]
Thank you. I will let you know about other stuff i find. When I will have final version of the MSSQL schema I will send it to you for review.

**Comment by cromain** [comment]
it's available here
https://raw.githubusercontent.com/processone/ejabberd/master/sql/mssql.sql
