### ISSUE TITLE
publish_item and retract_item should be transactions

### ISSUE THREAD

**Issue by ejbravo** [processone/ejabberd#2398]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Regarding the issue #2231 
I am wondering if other PubSub operations like 'publish_item' and 'retract_item' should be 'pure' transactions in order to avoid errors like this one which was described in mentioned issue

> When a user, who has been registered in host_A of cluster, publishes one item (X) in node 'test' and time after, the same user (this time being logged in host_B of cluster) tries to update that item (X), the system responses an error message which says 'forbidden'. However, if that user is logged in host_A, will be able to update the item (X) without any problem. Moreover, if the publisher tries to remove that item logged in host_B, the result will be another error, 'item-not-found', but the item is still in node 'test' of pubsub.

**Comment by cromain** [comment]
publish_item and retract_item are "almost" atomic. This was a design choice to keep it sync_dirty for performance reason. only possible race with publish_item on cluster occurs when two user from different cluster node publish an item with same itemid on same node exactly at same time, the creation/modification publisher will be set to one of two users.
performance improvement here has more benefits than the very low probability this occurs.

if you use a big cluster, with lots of pubsub usage and need pure transaction, mnesia backend is not the good choice. you'd better use an sql backend in this case.
