### ISSUE TITLE
Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.2102.0> exit with reason killed in context child_terminated

### ISSUE THREAD

**Issue by Hassnain-Alvi** [processone/ejabberd#2403]
> What version of ejabberd are you using?

Ejabberd 18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Installer (.run)

> What did not work as expected? Are there error messages in the log? 

I am connecting simultaneous users with my ejabberd 18.01 server. i am using an extauth PHP script for authentication. When i launch a tsung script to connect users, everything goes well but as soon as 13K connections are established the extauth module start breaking.
I see following error over and over again in ejabberd logs

> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.2102.0> exit with reason killed in context child_terminated

The crash logs shows following message

> 2018-04-30 09:55:08 =ERROR REPORT====
> ** Generic server <0.9337.2> terminating
> ** Last message in was {'$gen_event',{xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"AGZmMDBmZjAwMWU2YgAxMjM0NTY=">>}]}}}
> ** When Server state == #{shaper => c2s_shaper,mgmt_max_queue => 5000,mod => ejabberd_c2s,access => c2s,tls_options => [compression_none,{protocol_options,<<"no_sslv3">>}],stream_direction => in,socket => {socket_state,gen_tcp,#Port<0.94499>,262144,#Ref<0.737633104.302907393.1470>,{maxrate,50000,33158.24031516743,1525096508696643},undefined},tls_required => false,stream_header_sent => true,stream_compressed => false,stream_id => <<"8024247744200027817">>,stream_authenticated => false,mgmt_ack_timeout => 60000,tls_verify => false,stream_state => wait_for_sasl_request,mgmt_timeout => 300,lang => <<"en">>,zlib => true,mgmt_resend => false,mgmt_stanzas_in => 0,lserver => <<"abode-home-portal">>,socket_monitor => #Ref<0.737633104.302514178.225733>,resource => <<>>,ip => {{0,0,0,0,0,65535,8921,3434},47093},mgmt_state => inactive,owner => <0.9337.2>,stream_encrypted => false,user => <<>>,tls_enabled => true,mgmt_stanzas_req => 0,mgmt_queue_type => ram,xmlns => <<"jabber:client">>,stream_version => {1,0},mgmt_max_timeout => 300,server => <<"abode-home-portal">>,pres_a => {0,nil},stream_restarted => false,mgmt_stanzas_out => 0,stream_timeout => {30000,-576460370282}}
> ** Reason for termination ==
> ** {badarg,[{extauth,call_port,2,[{file,"src/extauth.erl"},{line,101}]},{ejabberd_auth_external,check_password_extauth,4,[{file,"src/ejabberd_auth_external.erl"},{line,88}]},{ejabberd_auth,'-db_check_password/7-fun-0-',5,[{file,"src/ejabberd_auth.erl"},{line,564}]},{ets_cache,update,5,[{file,"src/ets_cache.erl"},{line,190}]},{ejabberd_auth,db_check_password,7,[{file,"src/ejabberd_auth.erl"},{line,561}]},{ejabberd_auth,'-check_password_with_authmodule/6-fun-0-',8,[{file,"src/ejabberd_auth.erl"},{line,222}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,55}]}]}
> 2018-04-30 09:55:08 =CRASH REPORT====
>   crasher:
>     initial call: xmpp_stream_in:init/1
>     pid: <0.9337.2>
>     registered_name: []
>     exception exit: {{badarg,[{extauth,call_port,2,[{file,"src/extauth.erl"},{line,101}]},{ejabberd_auth_external,check_password_extauth,4,[{file,"src/ejabberd_auth_external.erl"},{line,88}]},{ejabberd_auth,'-db_check_password/7-fun-0-',5,[{file,"src/ejabberd_auth.erl"},{line,564}]},{ets_cache,update,5,[{file,"src/ets_cache.erl"},{line,190}]},{ejabberd_auth,db_check_password,7,[{file,"src/ejabberd_auth.erl"},{line,561}]},{ejabberd_auth,'-check_password_with_authmodule/6-fun-0-',8,[{file,"src/ejabberd_auth.erl"},{line,222}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,55}]}]},[{p1_server,terminate,7,[{file,"src/p1_server.erl"},{line,878}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
>     ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.66.0>]
>     message_queue_len: 0
>     messages: []
>     links: [<0.421.0>]
>     dictionary: [{'$internal_queue_len',0},{rand_seed,{#{bits => 58,jump => #Fun<rand.8.15449617>,next => #Fun<rand.5.15449617>,type => exrop,uniform => #Fun<rand.6.15449617>,uniform_n => #Fun<rand.7.15449617>,weak_low_bits => 1},[215476747292979747|271022715590356102]}},{already_terminated,true}]
>     trap_exit: false
>     status: running
>     heap_size: 2586
>     stack_size: 27
>     reductions: 2642
>   neighbours:
> 2018-04-30 09:55:08 =SUPERVISOR REPORT====
>      Supervisor: {local,ejabberd_c2s_sup}
>      Context:    child_terminated
>      Reason:     {badarg,[{extauth,call_port,2,[{file,"src/extauth.erl"},{line,101}]},{ejabberd_auth_external,check_password_extauth,4,[{file,"src/ejabberd_auth_external.erl"},{line,88}]},{ejabberd_auth,'-db_check_password/7-fun-0-',5,[{file,"src/ejabberd_auth.erl"},{line,564}]},{ets_cache,update,5,[{file,"src/ets_cache.erl"},{line,190}]},{ejabberd_auth,db_check_password,7,[{file,"src/ejabberd_auth.erl"},{line,561}]},{ejabberd_auth,'-check_password_with_authmodule/6-fun-0-',8,[{file,"src/ejabberd_auth.erl"},{line,222}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,55}]}]}
>      Offender:   [{pid,<0.9337.2>},{id,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

It does not make sense whats actually causing the problem because i did not see any issue or restart in extauth script. Can you guys help me out in this?

**Comment by Hassnain-Alvi** [comment]
I did not see any error or restart logs in extauth script
Can you tell me what this error means, i mean what goes wrong here?

**Comment by Hassnain-Alvi** [comment]
Yes. Agree with @nosnilmot 
I was tailing extauth logs and i did not see any requested routed to external auth. Only ejabberd is raising error.
@badlop Can you give us an insight on this?

**Comment by zinid** [comment]
@Hassnain-Alvi when you start receiving these errors, do you see the authentication as completely halted? Or some clients are still able to authenticate?

**Comment by Hassnain-Alvi** [comment]
@zinid I have put authentication logs inside my extauth script but when this error occurs there are no logs printed so it means that requests are not routing to extauth script 
ejabberd.log shows that the same error over and over again:

> 2018-05-02 05:55:00.832 [error] <0.25443.2>@extauth:call_port:101 gen_server <0.25443.2> terminated with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25445.2>@extauth:call_port:101 gen_server <0.25445.2> terminated with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25443.2>@extauth:call_port:101 CRASH REPORT Process <0.25443.2> with 0 neighbours exited with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25445.2>@extauth:call_port:101 CRASH REPORT Process <0.25445.2> with 0 neighbours exited with reason: bad argument in extauth:call_port/2 line 101

**Comment by zinid** [comment]
Do you see any other errors except those you have already shown?

**Comment by zinid** [comment]
Something like [this](https://github.com/processone/ejabberd/blob/master/src/extauth.erl#L137) error maybe?

**Comment by Hassnain-Alvi** [comment]
No nothing like that
Ejabberd logs show this

> 2018-05-02 05:55:00.832 [error] <0.25443.2>@extauth:call_port:101 gen_server <0.25443.2> terminated with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25445.2>@extauth:call_port:101 gen_server <0.25445.2> terminated with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25443.2>@extauth:call_port:101 CRASH REPORT Process <0.25443.2> with 0 neighbours exited with reason: bad argument in extauth:call_port/2 line 101
> 2018-05-02 05:55:00.832 [error] <0.25445.2>@extauth:call_port:101 CRASH REPORT Process <0.25445.2> with 0 neighbours exited with reason: bad argument in extauth:call_port/2 line 101

while extauth print no logs like no authentication requests ever arrived. No restarts as well

**Comment by zinid** [comment]
OK, guys, I see the code has some drawbacks, I will try to make it more robust, please be patient, I think I will do that by 18.05 (or what will be the next release).

**Comment by nosnilmot** [comment]
@zinid thanks. Can you provide any insight into what conditions you think might cause these errors to happen? I don't see them in all environments or at all times, so wonder if there are factors that we might be able to adjust to reduce the frequency of errors until you are able to provide a complete fix.

**Comment by Hassnain-Alvi** [comment]
@zinid Yes agreed with @nosnilmot Please give us some feedback on this atleast a temporary fix because v18.05 is released in few months time.

**Comment by Hassnain-Alvi** [comment]
@zinid Is it fixed in latest release or its coming up in v18.05

**Comment by zinid** [comment]
It's not fixed in the latest release and seems like there won't be 18.05, so 18.06 most likely.

**Comment by Hassnain-Alvi** [comment]
@zinid Okay sure when will v18.06 release?
