### ISSUE TITLE
UTF-8 Characters in MSSQL gets corrupted. 

### ISSUE THREAD

**Issue by UgniusD** [processone/ejabberd#2404]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Rhel 7

> How did you install ejabberd (source, package, distribution)?

From source also tried rpm and got same result.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When using MSSQL all messages that contain utf-8 characters gets corrupted in database.
For example ąčę becomes: "Ä?ÄÄ?" I think I'm missing something with MSSQL (2016) setup and I'm out of ideas what I could change. Maybe collation?
If i try to insert via isql or tsql everything works fine. Even posting from ejabberd via custom mod works.

Looks like issue is somewhere here:
(ejabberd@Server.com)3> X = unicode:characters_to_binary("ąčęėįšųū90- test").
io:format("~s",[X]). 
Ä�Ä�Ä�Ä�Ä¯Å¡Å³Å«90- testok
io:format("~ts",[X]).
ąčęėįšųū90- testok
This was client encoding issue.
But after this we found out that sql insert/update in all modules of Ejabberd is wrong. MsSQL needs different syntax for inserts and updates if you are using utf characters. N before quotes that specifies that this will be utf. if its not there utf characters gets striped. 

Any help would be greatly appreciated.

**Comment by dmitryDemchenko** [comment]
Having the same issue. Version 18.04.
Connection to MS SQL is made via freedts, ejabberd generates freedts config as 
```
[example.com]
        host = mssql.example.com
        port = 1433
        tds version = 7.1
```
There is config param "client charset" in FreeTDS. Setting it to UTF-8 resolves the issue. Finally, generated freetds config
```
[example.com]
        host = mssql.example.com
        port = 1433
        client charset = UTF-8
        tds version = 7.1
```
Corresponding changes to ejabberd source code
```
diff --git a/src/ejabberd_sql.erl b/src/ejabberd_sql.erl
index 675941a..9bdebb3 100644
--- a/src/ejabberd_sql.erl
+++ b/src/ejabberd_sql.erl
@@ -1030,6 +1030,7 @@ init_mssql(Host) ->
     FreeTDS = io_lib:fwrite("[~s]~n"
                            "\thost = ~s~n"
                            "\tport = ~p~n"
+                           "\tclient charset = UTF-8~n"
                            "\ttds version = 7.1~n",
                            [Host, Server, Port]),
     ODBCINST = io_lib:fwrite("[freetds]~n"
```
This works for UTF-8 only. Some more coding needed to parametrize charset, sql_ option group suggested.

**Comment by zinid** [comment]
> This works for UTF-8 only. Some more coding needed to parametrize charset

No need since ejabberd only speaks UTF-8 because XMPP doesn't allow other charsets.
Please create a PR if you want your patch to be merged ASAP.

**Comment by dmitryDemchenko** [comment]
done.
b545301f635cf682004f30f50a80fbf055eae0aa

**Comment by dmitryDemchenko** [comment]
Travis build failed with message
```
SQL query 'Q5299802' at {ejabberd_sm_sql,53} failed: "#42S02Table 'ejabberd_test.sm' doesn't exist"
```
Seems this has nothing to do with changes in fix.

**Comment by zinid** [comment]
Yeah, it's unrelated
