### ISSUE TITLE
ejabberd set incomplete host name

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd#2406]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Alpine Linux (docker container)

> How did you install ejabberd (source, package, distribution)?
using below ejabberd official docker repository  image 
https://hub.docker.com/r/ejabberd/ecs/

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I am just getting a 2nd level domain in the ejabberd web console which creating an issue while joining the cluster.
For example this the staging-new-1999013124.us-west-2.elb.amazonaws.com
this is the actual host of the container while ejabberd console show only ejabberd@staging-new-1999013124

Expected value at host should be staging-new-1999013124.us-west-2.elb.amazonaws.com

**Comment by cromain** [comment]
you're mixing concept of ejabberd node name, and host domain name. those are not the same.
if you want ejabberd node name to use dns name, you must add ejabberdctl.cfg in config directory, and set ERLANG_NODE accordingly.
