### ISSUE TITLE
mod_http_upload save files to S3

### ISSUE THREAD

**Issue by ismailmohammed** [processone/ejabberd#2407]
Hi,

I am using JSXC and its working wonderful as expected but I have a requirement where i have to save the files which are shared in the chat to S3 server.
Now I am able to save them in the server where ejabbered installed.

please help me on this.

Thank you.

**Comment by zinid** [comment]
This is not a bug, I close the ticket.
[Ask administration questions on Sever Fault](https://serverfault.com/questions/tagged/ejabberd?sort=newest)
Join ejabberd room to ask questions: xmpp:ejabberd@conference.process-one.net?join
