### ISSUE TITLE
Disabling mod_ping and instead using stream management and TCP keepalive

### ISSUE THREAD

**Issue by ghrst** [processone/ejabberd#2408]
I was wondering what happens if we totally disable mod_ping and instead use XMPP Stream Management and TCP Keep-Alive to detect whether a client is still connected or not. Is it possible at all or it can cause unexpected issues in large-scale?

**Comment by zinid** [comment]
This is not a bug, I close the ticket.
[Ask administration questions on Sever Fault](https://serverfault.com/questions/tagged/ejabberd?sort=newest)
Join ejabberd room to ask questions: xmpp:ejabberd@conference.process-one.net?join
