### ISSUE TITLE
Is it necessary to open the global default database in the cluster？

### ISSUE THREAD

**Issue by lemon2015** [processone/ejabberd#2409]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?
cenOS 7.4

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am configuring a ejabberd cluster, Is it necessary to open the `default_db: sql` in the cluster？What I mean is whether this can reduce data replication between individual nodes and reduce the  network bandwidth resources? 

Hope someone can answer my confusion，thanks a lot.

**Comment by zinid** [comment]
This is not a bug, I close the ticket.
[Ask administration questions on Sever Fault](https://serverfault.com/questions/tagged/ejabberd?sort=newest)
Join ejabberd room to ask questions: xmpp:ejabberd@conference.process-one.net?join
