### ISSUE TITLE
ejabberd cannot use IPv6 for LDAP- and SQL-connections

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#2411]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Debian Stretch

> How did you install ejabberd (source, package, distribution)?

Debian Stretch Backports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

It seems ejabberd does not support connecting to LDAP- and SQL-Backends via IPv6.
Details at https://bugs.debian.org/895692

**Comment by zinid** [comment]
I will check, thanks.
