### ISSUE TITLE
XEP-0227 import of privacy lists fail

### ISSUE THREAD

**Issue by crosser** [processone/ejabberd#2412]
When importing privacy lists from a XEP-0227 dump, one `<query xmlns="jabber:iq:privacy"/>` element from the dump file is converted into one `iq` (ejabberd_piefxis.erl:481). XEP-0227 assumes that multiple `<list/>` elements and `<default/>` element are present in the same `<query xmlns="jabber:iq:privacy"/>` element (see https://xmpp.org/extensions/xep-0227.html). But `iq` with multiple elements is rejected by `process_iq_set` (mod_privacy.erl:280).

It is my understanding that either mod_privacy should accept stanzas with multiple `<list/>` and `<default/>` elements, or ejabberd_piefxis should break the `<query/>` element from the dump and submit it as multiple `iq`-s.

**Comment by badlop** [comment]
Thanks! I've committed a slightly modified version of your patch.
