### ISSUE TITLE
redis support in docker image

### ISSUE THREAD

**Issue by zh99998** [processone/ejabberd#2414]
> What version of ejabberd are you using?

18.3

> What operating system (version) are you using?

debian 9

> How did you install ejabberd (source, package, distribution)?

docker ejabberd/ecs

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
failed to start application 'eredis': {error,
                                        {"no such file or directory",
                                         "eredis.app"}}
```

**Comment by doomsower** [comment]
@zh99998 , have you found a way to enable redis in this docker image?

**Comment by cromain** [comment]
This will be added in next version, I move that issue to docker-ejabberd repository instead
https://github.com/processone/docker-ejabberd/issues/16
