### ISSUE TITLE
[error] <0.988.0>@ejabberd_iq:callback:176 gen_server ejabberd_iq terminated with reason: bad argument in ejabberd_iq:callback/3 line 176

### ISSUE THREAD

**Issue by Hassnain-Alvi** [processone/ejabberd#2417]
> What version of ejabberd are you using?

v18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

installer (.run)

> What did not work as expected? Are there error messages in the log? 

Yes we see following crash logs 

> exception error: bad argument: [{ejabberd_iq,callback,3,[{file,"src/ejabberd_iq.erl"},{line,176}]},{ejabberd_iq,clean,1,[{file,"src/ejabberd_iq.erl"},{line,122}]},{ejabberd_iq,handle_info,2,[{file,"src/ejabberd_iq.erl"},{line,96}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

Can someone look into this issue?

**Comment by zinid** [comment]
Are you running third-party code?

**Comment by zinid** [comment]
Closed as inactive.
