### ISSUE TITLE
IP in a extauth_program

### ISSUE THREAD

**Issue by hlop** [processone/ejabberd#242]
There is no way to get the IP from the User in a extauth_program.
This would be very useful to make an ip range barrier.
The best way would be to set the server var REMOTE_ADDR

**Comment by cromain** [comment]
best to use acl on ejabberd config. see https://github.com/processone/ejabberd/issues/1731

**Comment by cromain** [comment]
@weiss if you think it's worth adding it, please create a PR with your patch https://gist.github.com/weiss/8f64dc5cb98f08487563
it may be applied later this year
