### ISSUE TITLE
mod_http_upload 'thumbnail'  error in error.log

### ISSUE THREAD

**Issue by antonyablonsky** [processone/ejabberd#2420]
> What version of ejabberd are you using?

18.04 Community edition

> What operating system (version) are you using?

Windows 10 Pro 1709 16299.431

> How did you install ejabberd (source, package, distribution)?

Official installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

It's not a big deal, but I constantly see message

>"gen_mod:validate_opt:620 Ignoring invalid value 'true' for option 'thumbnail' of module 'mod_http_upload'" 

in error.log after every ejabberd start. Even if I set this option false, even true (which should cause this error), even if I'm commenting this option in ejabberd.yml. 

Here's the config of module:

> mod_http_upload:
>     docroot: "path"
>     put_url: "url"
>     thumbnail: false

**Comment by zinid** [comment]
This is already fixed in c30715e67bd8411202c776f417a40387fa04d39e
