### ISSUE TITLE
delete_old_users very slow with high cpu usage

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#2421]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

Debian Stretch

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am trying to delete inactive users using the **delete_old_users** ejabberd command. However, on the latest 18.03 release, it takes really long time to delete users and the CPU usage is very high during the delete process. The command returns the following error, however the delete eventually happens but isn't as fast as it used to be before. 

`Failed RPC connection to the node ejabberd@localhost: timeout`

I have a relatively small number of registered users (~1000) and this command used to take just under 2 seconds in the previous ejabberd versions, but on 18.03 it takes nearly 6 minutes with very high cpu usage. I run this command weekly and on an average it deletes about 300 users.

![image](https://user-images.githubusercontent.com/1326273/40217998-efeef078-5a8c-11e8-9f66-d62679d19509.png)

**Comment by zinid** [comment]
What database backend are you using?

**Comment by dhiru1602** [comment]
Mnesia backend. 

```
---> Processes holding locks <---
---> Processes waiting for locks <---
---> Participant transactions <---
---> Coordinator transactions <---
---> Uncertain transactions <---
---> Active tables <---
route          : with 5        records occupying 406      words of mem
ejabberd_commands: with 142      records occupying 51962    words of mem
sql_pool       : with 10       records occupying 438      words of mem
caps_features  : with 8        records occupying 17899    bytes on disc
bosh           : with 0        records occupying 298      words of mem
acl            : with 10       records occupying 574      words of mem
access         : with 24       records occupying 898      words of mem
shaper         : with 2        records occupying 320      words of mem
push_session   : with 0        records occupying 5464     bytes on disc
carboncopy     : with 3        records occupying 400      words of mem
last_activity  : with 408      records occupying 140871   bytes on disc
pubsub_index   : with 1        records occupying 437      words of mem
vcard_search   : with 405      records occupying 45832    words of mem
motd_users     : with 0        records occupying 5464     bytes on disc
reg_users_counter: with 1        records occupying 312      words of mem
sr_user        : with 0        records occupying 298      words of mem
schema         : with 41       records occupying 5433     words of mem
roster_version : with 0        records occupying 5464     bytes on disc
pubsub_orphan  : with 0        records occupying 298      words of mem
session        : with 15       records occupying 1448     words of mem
pubsub_last_item: with 0        records occupying 298      words of mem
offline_msg    : with 0        records occupying 5464     bytes on disc
private_storage: with 1        records occupying 5986     bytes on disc
motd           : with 0        records occupying 5464     bytes on disc
sr_group       : with 1        records occupying 351      words of mem
oauth_token    : with 0        records occupying 5464     bytes on disc
pubsub_item    : with 417      records occupying 383309   bytes on disc
muc_room       : with 0        records occupying 298      words of mem
privacy        : with 0        records occupying 5464     bytes on disc
pubsub_state   : with 421      records occupying 15184    words of mem
passwd         : with 406      records occupying 246516   bytes on disc
temporarily_blocked: with 0        records occupying 298      words of mem
muc_registered : with 0        records occupying 298      words of mem
s2s            : with 0        records occupying 298      words of mem
session_counter: with 0        records occupying 298      words of mem
irc_custom     : with 0        records occupying 298      words of mem
muc_online_room: with 0        records occupying 88       words of mem
pubsub_node    : with 421      records occupying 59170    words of mem
vcard          : with 405      records occupying 243848   bytes on disc
route_multicast: with 0        records occupying 298      words of mem
roster         : with 0        records occupying 5464     bytes on disc
===> System info in version "4.14.2", debug level = none <===
opt_disc. Directory "/var/lib/ejabberd" is used.
use fallback at restart = false
running db nodes   = [ejabberd@localhost]
stopped db nodes   = []
master node tables = []
remote             = []
ram_copies         = [access,acl,bosh,carboncopy,ejabberd_commands,
                      muc_online_room,pubsub_last_item,reg_users_counter,
                      route,route_multicast,s2s,session,session_counter,
                      shaper,sql_pool,temporarily_blocked]
disc_copies        = [irc_custom,muc_registered,muc_room,pubsub_index,
                      pubsub_node,pubsub_orphan,pubsub_state,schema,sr_group,
                      sr_user,vcard_search]
disc_only_copies   = [caps_features,last_activity,motd,motd_users,oauth_token,
                      offline_msg,passwd,privacy,private_storage,pubsub_item,
                      push_session,roster,roster_version,vcard]
[{ejabberd@localhost,disc_copies}] = [pubsub_node,irc_custom,muc_registered,
                                      pubsub_state,muc_room,sr_group,
                                      pubsub_orphan,schema,sr_user,
                                      vcard_search,pubsub_index]
[{ejabberd@localhost,disc_only_copies}] = [roster,vcard,passwd,privacy,
                                           pubsub_item,oauth_token,
                                           caps_features,motd,private_storage,
                                           offline_msg,roster_version,
                                           motd_users,last_activity,
                                           push_session]
[{ejabberd@localhost,ram_copies}] = [shaper,route_multicast,muc_online_room,
                                     session_counter,s2s,temporarily_blocked,
                                     bosh,acl,access,pubsub_last_item,session,
                                     reg_users_counter,carboncopy,sql_pool,
                                     ejabberd_commands,route]
8219 transactions committed, 2 aborted, 0 restarted, 37802 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []

```

**Comment by dhiru1602** [comment]
I guess it was before https://github.com/processone/ejabberd/issues/1846 was merged.

**Comment by dhiru1602** [comment]
I was able to grab more logging when I am trying to delete users.

`[error] <0.14229.5>@ejabberd_hooks:safe_apply:383 Hook remove_user crashed when running mod_shared_roster:remove_user/2:
** Reason = {error,badarg,[{ets,lookup,[],[ejabberd_modules,{mod_shared_roster,<<"example.com">>}]},{gen_mod,get_module_opt,[{file,"src/gen_mod.erl"},{line,449}],4},{gen_mod,db_type,[{file,"src/gen_mod.erl"},{line,730}],2},{gen_mod,db_mod,[{file,"src/gen_mod.erl"},{line,752}],2},{mod_shared_roster,get_group_opts,[{file,"src/mod_shared_roster.erl"},{line,385}],2},{mod_shared_roster,get_group_opt,[{file,"src/mod_shared_roster.erl"},{line,406}],4},{mod_shared_roster,get_group_users,[{file,"src/mod_shared_roster.erl"},{line,426}],2},{mod_shared_roster,push_user_to_group,[{file,"src/mod_shared_roster.erl"},{line,663}],6}]}
`

And there is this spam.
` [warning] <0.500.0> Shrinking cache 'vcard_cache' (current size = 1001, max size = 1000, life time = 3600000, memory = 495880 bytes); you should increase maximum cache size if this message repeats too often`

**Comment by badlop** [comment]
I don't get any error or warning messages. By the way, disabling mod_shared_roster before running the command reduces the time again to 4 seconds in my test.

**Comment by dhiru1602** [comment]
Yes. Disabling the mod_shared_roster does speed up the delete operation. However, I am currently having a setup that relies on having a shared roster. If the number of users grows, the increasing roster size causes performance issues in clients, especially mobile ones. Hence it's important for me to constantly keep deleting new users and with the recent updates, the delete operation is slow and maxes out the CPU. Since I am running ejabberd on a 2 core virtual machine, the delete operation tends to freeze the virtual machine until it's complete. It wasn't the case earlier.
