### ISSUE TITLE
Introducing new hooking library

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [processone/ejabberd#2422]
Hi. I just wrote new hooking library [**posthaste**](https://github.com/pouriya-jahanbakhsh/posthaste). It's API is more like `ejabberd_hooks` API and functionality. But in lookup operation (for large number of processes at the same time) it's about 3-5 times faster than ETS. Do you want to look at that or use that ? If yes, i can open a pr.
thanks.

**Comment by zinid** [comment]
If it uses code generation and auto-compilation then no.

**Comment by zinid** [comment]
It will degrade performance for loading thousands of virtual hosts. Also, doesn't work with HIPE.

**Comment by zinid** [comment]
I also want to add, that, despite you see significant speed-up when comparing the calls by themselves, in real ejabberd benchmark I didn't notice significant improvements, something around 1-2% only, not a worth given the drawbacks I described.
We also used to have this for configuration, but then we reverted back to ETS for the reasons described.

**Comment by Pouriya-Jahanbakhsh** [comment]
I think that we don't need HiPE for ETS lookup. because It's a NIF call (am i right?). In posthaste i will create a function for each hook. Every hook can has one or more keys. Key is argument of function and every key has its own callbacks. Then Thousands VHs means thousands function clauses !
We are using Ejabberd and we have 10 milion users registered and about 1-2 million online users. but we have just one VH😁. I'm interested apps that use thousands VHs ! ok, are you agree with using it with one VH? I will test it in our app and will share details to you. thanks.

**Comment by zinid** [comment]
> I think that we don't need HiPE for ETS lookup

I'm not talking about HiPE for ETS.

**Comment by zinid** [comment]
> Then Thousands VHs means thousands function clauses !

Erlang compiler will use binary search for this, hard to say how it will compare to ETS lookups.
For me, the advantage is moot.

**Comment by Pouriya-Jahanbakhsh** [comment]
In benchmark (that exists in test codes) i added 100 hooks, and 3 keys (means 3 VHs) for each hook and 3 callbacks for each key. In lookup test 10K processes will lookup callbacks of each key 3 times for all hooks. In my laptop with 4 cores CPU (2 threads per core) posthaste lookup is about 4 times faster than ETS.

**Comment by zinid** [comment]
> lookup is about 4 times faster than ETS

So what? ETS hook lookups take 5% maximum in ejabberd if you run the benchmark, what will we get from this? What's the goal to optimize 5%? In order to get overall optimization in 2%?

**Comment by zinid** [comment]
I will make it clear: I'm not against your library, you can use it, but I don't see the reason to rewrite all hooking code and to say good bye to HiPE just to get 2% overall performance improvement.
