### ISSUE TITLE
Make it possible to add custom external sources for external modules

### ISSUE THREAD

**Issue by yokomizor** [processone/ejabberd#2427]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

alpine:3.7.0

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

`ext_mod` is very handful. However I feel like a standard way to add external sources is missing.  According to ejabberd-contrib README.md, all we have to do is to add custom sources on `$CONTRIB_MODULES_PATH/sources/`, but it is not clear if new module sources will be updated by `ejabberdctl modules_update_spec` command. If yes, it is also not clear how. Users must know about $CONTRIB_MODULES_PATH and also manage updates by themselves.

I would like to suggest 2 little improvements:

**1) Expose ext_mod:add_source/2 as ejabberd command**

```
#ejabberd_commands{name = module_add_sources,
                        tags = [admin,modules],
                        desc = "Add module source code from Git",
                        module = ?MODULE, function = add_sources,
                        args_desc = ["Module name", "Module source path"],
                        args_example = ["ejabberd_auth_jwt", <<"https://github.com/yokomizor/ejabberd-auth-jwt">>],
                        args = [{module, binary}, {path, string}],
                        result = {res, rescode}},
```

This would allow us to add new modules on running ejabberd hosts.

**2) Load `?REPO` from config**

The default contrib repository is hardcoded on `ext_mod`:
https://github.com/processone/ejabberd/blob/d2114be6f333a47cc2024d2fff7d9ccedc2968d6/src/ext_mod.erl#L48

Is there a way to override this macro? It would be nice to control this value through ejabberd.yml.

-------

I am very interested into building custom modules. It is true that the current state exposes enough apis to add custom code. Nevertheless the motivation behind my request is to make it easier for users to use 3rd party modules with minimal ejabberd/erlang knowledge.

What do you think?

**Comment by cromain** [comment]
For now, you add any sources you want into $CONTRIB_MODULES_PATH/sources/
it's up to you to update the code out of ejabberd-contrib before calling modules_update_spec, because your own sources may not be versioned, or versioned with any manager, cvs/svn/bzr/hg/git/.... and ejabberd will not cope with this. It's very easy to write a shell script which first update your sources, then make ejabberd build&load them.

1. expose add_sources may be interesting, but your repo will be out of sync anyway until we make this configurable with a list of git urls into ejabberd config.
2. add list of git urls into ejabberd config looks a nice to have feature.

**Comment by yokomizor** [comment]
Hey @cromain, thanks for replying (: 

It is reasonable that ejabberd maintainers don't want to cope to a specific version manager. It is also true that creating scripts to keep modules up to date is an easy task. However, to create a script like this, maintainers must have some knowledge on ejabberd file structure.

The motivation behind my suggestions is to enable users to plug modules with zero experience with ejabberd or even erlang.

**Comment by cromain** [comment]
It's not a good idea to allow user without any experience in ejabberd and erlang messing ejabberd with such approach. When user knows a bit about ejabberd and module development, it's very straightforward to write such script so it performs the glue with whatever user needs.

We won't add such feature to ext_mod as it's very easy to copy with current defined process using a simple custom script.

**Comment by yokomizor** [comment]
😢
