### ISSUE TITLE
Use MySQL from Travis

### ISSUE THREAD

**Issue by yokomizor** [processone/ejabberd#2429]
> What version of ejabberd are you using?

18.03

> What operating system (version) are you using?

alpine:3.7

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**From ejabberd .travis.yml:**
https://github.com/processone/ejabberd/blob/d2114be6f333a47cc2024d2fff7d9ccedc2968d6/.travis.yml#L13
```
  # We need MySQL 5.6 or newer in order to get support for FULLTEXT indexes
  # with InnoDB. As soon as Travis ships that version, the following lines
  # (except for the "apt-get update" call) can go away.
```

**Travis supports MySQL 5.6 on trusty builds:**
https://docs.travis-ci.com/user/database-setup/#MySQL
```
                  | Ubuntu Precise | Ubuntu Trusty
Sudo-enabled      | 5.5.x          | 5.6.x
Container-based   | -              | 5.6.x
```

**From ejabberd build log (https://travis-ci.org/processone/ejabberd/jobs/381096878):**
```
...
Build dist: trusty 
...
```

Not sure if this will make the build faster but it is a nice clean up.

**Comment by badlop** [comment]
Right. I noticed that too, and updated it in https://github.com/processone/ejabberd/commit/1c3a7b7c968795ee36137e1da06c76a63a1c8cde

Anyway, thanks for reporting!
