### ISSUE TITLE
Offline users using Redis as database backend for Session Management

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2439]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I changed the database backend for Session Management, from Mnesia to REDIS.
I configured the .yml file as follows:
```
sm_db_type: redis
redis_server: "AAA.BBB.CCC.DDD"
redis_port: 6379
redis_password: "mypwd"
redis_db: 0
redis_connect_timeout: 5
```
I registered several users and I can see their sessions stored in REDIS. E.g.:
`ejabberd:sm:testuser1@mydomain.com`

But when I try to set them offline, it doesn't work:
`event: end.session#testuser1@mydomain.com/testres1, attrs: {code: 400, type: modify}, message: bad-request`

Using Mnesia it works perfectly (the same code).
I'm using _https://xmpp.org/extensions/xep-0133.html#end-user-session_

It does work via ejabberdctl:
`ejabberdctl kick_user testuser1 mydomain.com`
Returns 1 and I can see the user offline and the key is gone from REDIS.

Could you give me some advice?

**Comment by Emilio-Gonzalez** [comment]
When I use Redis as Session Management backend, all the functionality works except the offline.

If I try to set a user offline, Ejabberd returns _**attrs: {code: 400, type: modify}, message: bad-request**_ and the user remains online in the system.
The same code executed using Mnesia as SM backend returns a _**result**_ stanza and the user is setted offline.

Ejabberdctl command _**kick_user**_ also works ok using either Mnesia or Redis as SM backend and sets the user offline.

The problem is that a working stanza with Mnesia becomes a a bad-request with Redis.

**Comment by zinid** [comment]
> The problem is that a working stanza with Mnesia becomes a bad-request with Redis.
Enable debug, find and show the stanza then.

**Comment by Emilio-Gonzalez** [comment]
REDIS stanzas

`2018-05-30 07:51:47.477 [debug] <0.606.0>@xmpp_socket:parse:371 (tls|<0.606.0>) Received XML on stream = <<"<iq type=\"set\" id=\"admin.command.end.session#testuser1@mydomain.com/testres1\" to=\"mydomain.com\"><command xmlns=\"http://jabber.org/protocol/commands\" action=\"execute\" node=\"http://jabber.org/protocol/admin#end-user-session\"/></iq>">>`

`2018-05-30 07:51:47.487 [debug] <0.606.0>@xmpp_socket:send:221 (tls|<0.606.0>) Send XML on stream = <<"<iq xml:lang='en' to='myadmin@mydomain.com/myxmpp:AAA.BBB.CCC.DDD' from='mydomain.com' type='result' id='admin.command.end.session#testuser1@mydomain.com/testres1'><command status='executing' sessionid='2018-05-30T07:51:47.481430Z' node='http://jabber.org/protocol/admin#end-user-session' xmlns='http://jabber.org/protocol/commands'><actions execute='complete'><complete/></actions><x type='form' xmlns='jabber:x:data'><title>End User Session</title><field var='FORM_TYPE' type='hidden'><value>http://jabber.org/protocol/admin</value></field><field var='accountjid' type='jid-single' label='Jabber ID'><required/></field></x></command></iq>">>
`

`2018-05-30 07:51:47.488 [debug] <0.606.0>@xmpp_socket:parse:371 (tls|<0.606.0>) Received XML on stream = <<"<iq type=\"set\" id=\"end.session#testuser1@mydomain.com/testres1\" to=\"mydomain.com\"><command xmlns=\"http://jabber.org/protocol/commands\" node=\"http://jabber.org/protocol/admin#end-user-session\" sessionid=\"2018-05-30T07:51:47.481430Z\"><x xmlns=\"jabber:x:data\" type=\"submit\"><field type=\"hidden\" var=\"FORM_TYPE\"><value>http://jabber.org/protocol/admin</value></field><field var=\"accountjid\"><value>testuser1@mydomain.com/testres1</value></field></x></command></iq>">>`

`2018-05-30 07:51:47.492 [debug] <0.606.0>@xmpp_socket:send:221 (tls|<0.606.0>) Send XML on stream = <<"<iq xml:lang='en' to='myadmin@mydomain.com/myxmpp:AAA.BBB.CCC.DDD' from='mydomain.com' type='error' id='end.session#testuser1@mydomain.com/testres1'><command sessionid='2018-05-30T07:51:47.481430Z' node='http://jabber.org/protocol/admin#end-user-session' xmlns='http://jabber.org/protocol/commands'><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE' type='hidden'><value>http://jabber.org/protocol/admin</value></field><field var='accountjid'><value>testuser1@mydomain.com/testres1</value></field></x></command><error code='400' type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>">>`
