### ISSUE TITLE
Add support for XEP-0312: PubSub Since

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2440]
Would it be possible to add support for XEP-0312: PubSub Since in ejabberd.

When connecting with "big" accounts on Movim a lot of PEP and Pubsub notifications are simply discarded because they were already received before, it would be nice to filter them to speed up this part.

I'm willing to help with the implementation client side in Movim :)

**Comment by cromain** [comment]
this duplicates #2002. let's follow this on initial thread #2002
