### ISSUE TITLE
Auto refresh f5 keypress

### ISSUE THREAD

**Issue by burhanahmed** [processone/ejabberd#2443]
> What operating system (version) are you using?

Windows 10

Hi,

i want to Autorefresh F5 key press for specific program Eg: Browser or MS Excel.
How i can do this. this the script what changes i have to make in this.

#Persistent
SetTimer, PressTheKey, 25000
Return

PressTheKey:
Send, {F5}
Return

Thanks

**Comment by prefiks** [comment]
I think you wanted to ask that question somewhere else, this project is for xmpp server software

**Comment by burhanahmed** [comment]
Oh sorry can u guide me to right Project
