### ISSUE TITLE
mucsub issue when user is banned from muc room

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd#2451]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

CentOS 6

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

If user is banned from the muc (via xep-0045) and has subscription (via mucsub), pubsub events is still available from that muc room

**Comment by ltAldoRaine** [comment]
@badlop @zinid

**Comment by ltAldoRaine** [comment]
and if user which has subscription to muc room is banned from that muc room and after some time user unsubscribes that room, meanwhile owner decides to  set affiliation from outcast to none (removes ban) server replies Nickname x does not exist in the room. It's because user unsubscribed room.

**Comment by ltAldoRaine** [comment]
also when i remove membership these issue appears

**Comment by badlop** [comment]
> If user is banned from the muc (via xep-0045) and has subscription (via mucsub), pubsub events is still available from that muc room

I can reproduce that behaviour. I've writteng a small patch that, a subscriber that is banned doesn't receive messages, and cannot send messages to the room. I've tested the patch, and I think it works correctly. Please try that patch whe nyou can, and report here if you find andy problem in it.

> and if user which has subscription to muc room is banned from that muc room and after some time user unsubscribes that room, meanwhile owner decides to set affiliation from outcast to none (removes ban) server replies Nickname x does not exist in the room. It's because user unsubscribed room.

I haven't send that behaviour. In my test, a user subscribes, then he is banned, then he unsubscribes... and later the room owner can change the user affiliation to none, or to member... No error reported, and I see in the Mnesia database that the changes are applied correctly. Notice: when a user unsubscribes, his outcast affiliation is not removed.

The patch I mentioned:
```
From dacf8f25fcef8dbd50bccde032fc47b4ecbc57a2 Mon Sep 17 00:00:00 2001
From: Badlop <badlop@process-one.net>
Date: Thu, 14 Jun 2018 11:40:11 +0200
Subject: [PATCH] A banned subscriber cannot send or receive messages (#2451)

---
 src/mod_muc_room.erl | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)

diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 7779cd5..805250c 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -727,8 +727,9 @@ route(Pid, Packet) ->
 -spec process_groupchat_message(message(), state()) -> fsm_next().
 process_groupchat_message(#message{from = From, lang = Lang} = Packet, StateData) ->
     IsSubscriber = is_subscriber(From, StateData),
-    case is_user_online(From, StateData) orelse IsSubscriber orelse
-	   is_user_allowed_message_nonparticipant(From, StateData)
+    case is_user_online(From, StateData)
+	orelse (IsSubscriber andalso not is_banned(From, StateData))
+	orelse is_user_allowed_message_nonparticipant(From, StateData)
 	of
       true ->
 	  {FromNick, Role} = get_participant_data(From, StateData),
@@ -1121,7 +1122,8 @@ get_users_and_subscribers(StateData) ->
 			   end, ?SETS:new(), StateData#state.users),
     ?DICT:fold(
        fun(LBareJID, #subscriber{nick = Nick}, Acc) ->
-	       case ?SETS:is_element(LBareJID, OnlineSubscribers) of
+	       case ?SETS:is_element(LBareJID, OnlineSubscribers) orelse
+				    is_banned(LBareJID, StateData) of
 		   false ->
 		       ?DICT:store(LBareJID,
 				   #user{jid = jid:make(LBareJID),
@@ -1144,6 +1146,9 @@ is_subscriber(JID, StateData) ->
     LJID = jid:tolower(jid:remove_resource(JID)),
     (?DICT):is_key(LJID, StateData#state.subscribers).
 
+is_banned(JID, StateData) ->
+    outcast == get_affiliation(JID, StateData).
+
 %% Check if the user is occupant of the room, or at least is an admin or owner.
 -spec is_occupant_or_admin(jid(), state()) -> boolean().
 is_occupant_or_admin(JID, StateData) ->
-- 
2.7.4
```

**Comment by ltAldoRaine** [comment]
Thanks for your response.

Yes you are right about these. I was making incorrect request, when removing ban

> I haven't seen that behaviour. In my test, a user subscribes, then he is banned, then he unsubscribes... and later the room owner can change the user affiliation to none, or to member... No error reported, and I see in the Mnesia database that the changes are applied correctly. Notice: when a user unsubscribes, his outcast affiliation is not removed.

I will definitely test these patch.

by the way i reproduce my own solution which means that when user is banned from muc i force user to unsubscribe that muc.

**Comment by ltAldoRaine** [comment]
That way i'm 100% sure no presence, subject, config or any other node changes available for that user

**Comment by badlop** [comment]
Ah, I see the alternative patch: https://stackoverflow.com/questions/50683075/mucsub-issue-when-user-is-banned-from-muc-room

**Comment by cromain** [comment]
@badlop what's status on this ? should that patch be scheduled for injection ?
