### ISSUE TITLE
Http File Format issue

### ISSUE THREAD

**Issue by vasurajput** [processone/ejabberd#2453]
> What version of ejabberd are you using?
ejabberd-18.04

> What operating system (version) are you using?
Cent-Os

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
Format Not Support

> was the unexpected behavior? What was the expected result?
i am using mod_http_upload i will get succesfully get link in my docroot folder and receiver also get link but when i am open that link it will not supported says not supported format

**Comment by weiss** [comment]
>  receiver also get link but when i am open that link it will not supported says not supported format

This is a client-side issue.
