### ISSUE TITLE
Last Activity

### ISSUE THREAD

**Issue by vasurajput** [processone/ejabberd#2456]
> What version of ejabberd are you using?
ejabberd-18.04

> What operating system (version) are you using?
Cent_os

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
last activity time of user

> was the unexpected behavior? What was the expected result?

hi, i want to get user last activity means the last time of user online status like in whatsapp for this o have configure

    mod_last: 
    db_type: sql
    use_cache: true

and in mysql DB i query select * from user then i get last time in seconds how will i convert it into timestamp and if i hit the rest api  "get_last" then i will get 

{
    "timestamp": "2018-06-05T09:09:42Z",
    "status": ""
}

how 'll i get correct timestamp tell me

Thank You

**Comment by zinid** [comment]
Closed due to author inactivity
