### ISSUE TITLE
mod_muc

### ISSUE THREAD

**Issue by vasurajput** [processone/ejabberd#2457]
> What version of ejabberd are you using?
ejabberd-18.04

> What operating system (version) are you using?
Cent-Os

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
Not Get Entr inside database tables

> was the unexpected behavior? What was the expected result?
hi, i have just configured mod_muc in ejabberd.yml and i have done following config

mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
    db_type: sql
    max_users: 20

but the issue is i am not getting entry inside any below table;

| muc_online_room         |
| muc_online_users        |
| muc_registered          |
| muc_room                |
| muc_room_subscribers

**Comment by licaon-kter** [comment]
So you've created some MUCs, join them, but those stats show 0?

**Comment by zinid** [comment]
Closed due to author inactivity
