### ISSUE TITLE
Big Pubsub_item payload not fetched from MSSQL

### ISSUE THREAD

**Issue by brobaniuc** [processone/ejabberd#2459]
> What version of ejabberd are you using?
18.04

> What operating system (version) are you using?

RHEL 7

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
When using Mnesia backend I can get all payloads of all Items but once we use MSSQL backend database the item that has a large payload xml content contains only the id of the pubsub_item with no content.
In MSSQL database the  item has all fields populated correspondingly and a valid XML value in payload field.
If I reduce considerable the a size of the payload field value manually in MSSQL database than the everything works as expected.

**Comment by brobaniuc** [comment]
Hi,
I have modified the column type to Varchar(MAX)  with sam result and did a select directly with tsql from RHEL machine in order to exclude any UnixODBC or FreeTDS limitations, and the data was returned accordingly.
But when requesting the data from ejabberd instance i get all items populated right except this one with a large payload. 
I am wondering if there is no specific MSSQL logic in ejabberd implementation that will trigger this behavior. 
It is also strange that if i reduce the amount of data on that field than it works ok.

Also it would help a lot to allow configuring ejabberd to load the MSSQL configuration from default system location of odbc.ini, freetds.conf and odbcinst.ini like "/etc/..." files than generating temporary files with the configuration that ejabberd builds and which will be rebuild each time ejabberd is started. I would like to set the timeouts for freetds configuration which currently i can't.

Thanks, Bogdan R.

**Comment by brobaniuc** [comment]
Hi, 
Are there any chances that this would get fixed on 18.05 version?
Thanks, Bogdan R.

**Comment by cromain** [comment]
1. there is no special logic ejabberd side for mssql
2. config will not be written in /etc, ejabberd does not run as root
3. this will not be fixed in 18.06 because we don't have idea what cause this yet

**Comment by brobaniuc** [comment]
Hi,
We depend on this feature in order to migrate from Mnesia to MSSQL so I am curios if was anything discovered for this issue?

**Comment by zinid** [comment]
> in order to migrate from Mnesia to MSSQL

Doesn't sound like a great idea. I would suggest migrating to PostgreSQL or MySQL instead.

**Comment by brobaniuc** [comment]
Hi,
So there is no solution on this issue yet?
