### ISSUE TITLE
Unable to use MySql ejabberd 18.04

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#2468]
> What version of ejabberd are you using?
ejabberd-18-04

> What operating system (version) are you using?
Debian

> How did you install ejabberd (source, package, distribution)?
deb.package (from https://www.process-one.net/en/ejabberd/downloads)

> ---
When I enable MySql in the yml file i get an error when starting ejabberd

```
##
## MySQL server:
##
 sql_type: mysql 
 sql_server: "localhost"
 sql_database: "ejabberd"
 sql_username: "ejabberd"
 sql_password: "ejabberd"
```

**Error**
```2018-06-12 10:55:59.404 [error] <0.66.0>@ejabberd_config:get_plain_terms_file:300 Cannot load /opt/ejabberd/conf/ejabberd.yml: Syntax error on line 398 at position 2: did not find expected key```

Line:398 =  sql_type: mysql 

Do  need to install an additional package?
Thanks you in advance.

**Comment by prefiks** [comment]
Make sure there is no space before any of that options (they should start in first column)

**Comment by zinid** [comment]
This is clearly an indentation issue. I close it.
