### ISSUE TITLE
Debug and Run ejabberd code using Eclipse in windows

### ISSUE THREAD

**Issue by vasurajput** [processone/ejabberd#2469]
> What version of ejabberd are you using?
ejabberd-18.04

> What operating system (version) are you using?
Cent-Os

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
Don't know and not get details how to debug and run ejabberd code in eclipse
> was the unexpected behavior? What was the expected result?

Hi,
    i am using Eclipse on windows 10 and i have successfully clone ejabberd Source Code Into My Eclipse but i dont't know how to run this code and how to debug this, but i know how to run ErLang Programes i have Tried This But it do not work , and i aso go through 
https://docs.ejabberd.im/admin/installation/#installing-ejabberd-from-source-code
the above link but i didn't get any solution please tell me the steps to Debug and run This source Code in Eclipse
i have already installed erlang

**Comment by zinid** [comment]
Not a bug report. I close the issue.
