### ISSUE TITLE
iqdisc was removed, but nothing about it in configuration documents

### ISSUE THREAD

**Issue by Cheburum** [processone/ejabberd#2473]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu 16.04 LTS

> How did you install ejabberd (source, package, distribution)?

.deb package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

`iqdisc` feature removal not listed in configuration docs.
[https://docs.ejabberd.im/admin/configuration](url)

**Comment by badlop** [comment]
Fixed in the documentation source. It will be published sometime later.

**Comment by jjcorrea** [comment]
Hi guys,

Is there any alternative to iqdisc, given its been deprecated in iq handlers? We're using ejabberd 18.12 here, and found it might be useful for a custom module we've built.
