### ISSUE TITLE
how to run custom module in ejabberd server

### ISSUE THREAD

**Issue by vasurajput** [processone/ejabberd#2474]
> What version of ejabberd are you using?
ejabberd 18

> What operating system (version) are you using?
Cent-Os

> How did you install ejabberd (source, package, distribution)?
rpm package

> What did not work as expected? Are there error messages in the log? What
how to add custom module
> was the unexpected behavior? What was the expected result?

Hi, 
   i want to add my custom module in ejabberd i have already compile it with erl and it succesfully work, now i have to use this module inside my ejabberd server and i have installed ejabberd using rpm package so please tell me the steps to add this custom module in ejabberd server

Thank you

**Comment by cromain** [comment]
1. make sure ejabberd.yml have this line
`allow_contrib_modules: true`

2. copy your module code repository in $HOME/.ejabberd-modules/sources/mod_mymodule

3. check https://docs.ejabberd.im/developer/extending-ejabberd/modules/
```
$ ejabberdctl module_check mod_mymodule
ok
$ ejabberdctl module_install mod_mymodule
ok
```
