### ISSUE TITLE
Ejabberd: ODBC connection with remote Oracle DB

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2481]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Linux - Ubuntu

> How did you install ejabberd (source, package, distribution)?

.deb package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I tried to connect my ejabberd instance with an oracle database.
I've created a database called ejabberd, and I've imported the schema through this script:
[https://github.com/softctrl/ejabberd-oracle-odbc/blob/master/sql/oracle.sql](url)

Then I changed the .yml file like this:

```
sql_type: odbc
sql_server: "DSN=EJABBERD://IP-HOST:1521/EJABBERDORACLE;UID=EJABBERD;PWD=EJABBERD"
```
where sql_server has this structure:

```
DNS=DB-NAME://IP-MACHINE:PORT/SID
UID=username
PWD=password
```

The log:

```
[info] <0.402.0>@ejabberd_sql:connecting:339 odbc connection failed:
** Reason: "[unixODBC][Driver Manager]Data source name not found, and no default driver specified SQLSTATE IS: IM002 Connection to database failed."
```
Anyone can help me?

**Comment by bp91** [comment]
After some tests, I've reached this situation:

I've installed unixOdbc driver and Oracle Instant client, in order to define **odbc.ini** and **odbcinst.ini**. 
**odbcinst.ini**:

```
[Oracle]
Description = ODBC for Oracle
Driver = /usr/lib/oracle/11.2/client64/lib/libsqora.so.11.1
UsageCount = 1
FileUsage = 1
```
**odbc.ini**:

```
[ejabberd]
Driver = Oracle
DSN = Oracle
ServerName = //x.x.x.x:1521/DB_SID
UserID = EJABBERD
Password = EJABBERD
```

Then, I've exported
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/oracle/11.2/client64/lib`
and tested the connection with
`isql -v ejabberd`
The result is:

```
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL>
```

But with ejabberd, I've this error:
```
<0.400.0>@ejabberd_sql:connecting:339 odbc connection failed:
** Reason: "[unixODBC][Driver Manager]Can't open lib '/usr/lib/oracle/11.2/client64/lib/libsqora.so.11.1' : file not found SQLSTATE IS: 01000 Connection to database failed."
** Retry after: 30 seconds
```

**Comment by cromain** [comment]
because ejabberd overrides LD_LIBRARY_PATH/LD_FALLBACK_LIBRARY_PATH
can you try edit ejabberctl, and add your export line right after LD_LIBRARY_PATH ?

**Comment by cromain** [comment]
I assume your export with correct path for LD_LIBRARY_PATH does fix the glitch

**Comment by Neustradamus** [comment]
@cromain @bp91 All works with OracleDB and last ejabberd?
It will be nice to have a module in ejabberd-contrib if not in ejabberd directly ^^
