### ISSUE TITLE
[BUG] [INFO] MSSQL Connection with Ejabberd

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2486]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

distribution

This is not a bug but a **request info**. In order to connect ejabberd with a remote MSSQL database, the documentation says:

```
sql_type: mysql | pgsql | odbc | **mssql** | sqlite

Microsoft SQL Notes
For now, MS SQL is only supported in Unix-like OS'es. You need to have FreeTDS and unixODBC installed on your machine. Also, in some cases you need to add machine name to sql_username, especially when you have sql_server defined as an IP address, e.g.:

sql_type: mssql
sql_server: "1.2.3.4"
...
sql_username: "user1@host"

```

I really don't understand how I can use a mssql connection.
Why I have to install **FreeTDS** and **unixODBC** if I don't have to use an odbc connetion?

I followed the documentation with and I wrote this configuration:

```
sql_type: mssql
sql_server: "172.31.80.82"
sql_database: "EjabberdTest"
sql_username: "admin"
sql_password: "admin"

##If you want to specify the port:
sql_port: 1433
```

And when I run the ejabberd service, I have the following exception:
```
2018-06-25 10:03:48.990 [info] <0.405.0>@ejabberd_sql:connecting:339 mssql connection failed:
** Reason: "[unixODBC][Driver Manager]Can't open lib 'libtdsodbc.so' : file not found SQLSTATE IS: 01000 Connection to database failed."
** Retry after: 30 seconds
```

Can someone help me?

**Comment by haegar** [comment]
The mssql connector is using odbc internally, this is why it needs those two supports installed as documented.

**Comment by bp91** [comment]
@haegar @zinid I have another question before close this request: Now i can connect to a mssql database, but I want to use this database as default. So I've inserted:

`default_db: mssql` but I have this log:

```
2018-06-25 11:09:27.573 [warning] <0.509.0>@ejabberd_config:default_db:977 Module 'ejabberd_auth' doesn't support database 'mssql' defined in option 'default_db', using 'mnesia' as fallback```.

Any help?

**Comment by zinid** [comment]
`default_db: sql`

**Comment by bp91** [comment]
@zinid thanks. I've updated

```
hosts:
  - "custom.host"
...
sql_type: mssql
sql_server: "172.31.80.82"
sql_database: "EjabberdTest"
sql_username: "admin"
sql_password: "admin"
sql_port: 1433
...
default_db: sql
auth_method: sql
```

It works correctly except when I stop ejabberd. When I run it again, seems that it loses somethig.

Steps:
```
systemctl start ejabberd

ejabberdctl register "admin" "custom.host" "admin"
```
login into localhost:5280/admin OK

```
systemctl stop ejabberd
systemctl start ejabberd
```

login into localhost:5280/admin KO.

logs:
```
2018-06-25 11:54:45.293 [debug] <0.519.0>@ejabberd_http:process_header:277 (#Port<0.22177>) http query: 'GET' <<"/admin/server/custom.host/access/">>
2018-06-25 11:54:45.294 [debug] <0.519.0>@ejabberd_http:process:364 [<<"admin">>,<<"server">>,<<"custom.host">>,<<"access">>] matches [<<"admin">>]
2018-06-25 11:54:45.294 [warning] <0.519.0>@ejabberd_web_admin:process:202 Access of <<"admin@custom.host">> from <<"::1">> failed with error: <<"inexistent-account">>
```

But into the database mssql that user was inserted before (and it's into the table users).
Is it a bug or I lost something else?

**Comment by zinid** [comment]
Don't you see SQL queries logging in debug mode?

**Comment by zinid** [comment]
> [FreeTDS][SQL Server]Invalid column name 'serverkey'.
> [FreeTDS][SQL Server]Invalid column name 'salt'.
> [FreeTDS][SQL Server]Invalid column name 'iterationcount'.

Something is wrong with the schema. Those keys clearly present in the schema, see: https://github.com/processone/ejabberd/blob/master/sql/mssql.sql#L391
What schema did you load?

**Comment by bp91** [comment]
I used that file. I saw that these columns were not created, but I saw also that If I try to create a new user without that columns, It works. Anyway, I've created the columns, so now seems that everything it's ok. Thanks for your support

**Comment by vkelman** [comment]
Is it correct that if I install ejabberd on Windows machine I cannot use MS SQL instead of Mnesia?
This sounds strange, because
1) ejabberd works fine on Windows;
2) Windows is the native environment for SQL Server.
