### ISSUE TITLE
pubsub nodes are not persistent without the hometree plugin.

### ISSUE THREAD

**Issue by sezuan** [processone/ejabberd#249]
Setup: 
- latest master
- pubsub_node is configured as disc_copy (default)
- only flat and pep are enabled.

Steps to reproduce:
1. Create a node.
2. Verify node is there.
3. Restart server.
4. Node is gone.

PS: clean database, no virtual plugin for pubsub.

**Comment by cromain** [comment]
could not reproduce after pubsub refactor
