### ISSUE TITLE
Hook remove_user crashed when running mod_roster

### ISSUE THREAD

**Issue by kishoreacesurf** [processone/ejabberd#2492]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Centos

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by licaon-kter** [comment]
Logs?

**Comment by zinid** [comment]
I close it due to author's inactivity.
