### ISSUE TITLE
External eimp process has terminated unexpectedly,

### ISSUE THREAD

**Issue by tbeitter** [processone/ejabberd#2497]
> What version of ejabberd are you using?

ejabberd 18.04-2~bpo9+1

> What operating system (version) are you using?

Debian GNU/Linux 9.4 (stretch)

> How did you install ejabberd (source, package, distribution)?

Debian strecht backports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Every second I get two of those lines:
```
External eimp process (pid=24973) has terminated unexpectedly, restarting in a few seconds2018-07-01 14:44:12 =ERROR REPORT====
External eimp process (pid=24974) has terminated unexpectedly, restarting in a few seconds2018-07-01 14:44:12 =ERROR REPORT====
```

#2362 seems to be related.

libgd and libwebp are installed, but maybe too new:
```
libgd3:amd64                            2.2.4-2+deb9u2
libwebp6:amd64                          0.5.2-1
```

**Comment by zinid** [comment]
Just run `eimp` from the shell directly, it's a regular binary. See what error it returns.

**Comment by tbeitter** [comment]
it's not in the PATH but it exists at 
`/usr/lib/erlang/lib/p1_eimp-1.0.5/priv/bin/eimp`

There is no error, it locks the console when started and I can stop it with ctrl-c.

**Comment by zinid** [comment]
So is it resolved now?
We cannot do anything with AppArmor for you.

**Comment by tbeitter** [comment]
It is for now, although I yet don't know why :-)

Thanks and sorry for bothering, #2362 made me think it could be related.
