### ISSUE TITLE
ejabberd.hrl is missing from 18.06

### ISSUE THREAD

**Issue by moneytoo** [processone/ejabberd#2503]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Community version of RPM from ProcessOne

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm unable to install contrib module to ejabberd 18.06. It worked fine in 18.04. ejabberd.hrl is missing from both RPM/DEB, I didn't try other installers.

```
$ ./ejabberdctl modules_update_specs
$ ./ejabberdctl module_install mod_rest
/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_rest/src/mod_rest.erl:36: can't find include file "ejabberd.hrl"
Error: {compilation_failed,"/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_rest/src/mod_rest.erl"}
```

**Comment by prefiks** [comment]
ejabberd.hrl was removed in that release but contrib modules were not updated with that change. I commited change that should fix that problem, updating spec i think should fix your problem.
