### ISSUE TITLE
[INFO] Retrieve all registered users information from REST API Service

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2504]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Centos

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi everyone, I need to retrieve all the information related to a user, (username, password), stored into the internal DB, from a Java backend using the REST API.
Into the documentation ([](https://docs.ejabberd.im/developer/ejabberd-api/admin-api/)) I did't find any service that gave me the possibility to obtain the password using the username. How can I do this? thanks for your support

**Comment by cromain** [comment]
Doing so is really not a good idea. That's why there is no such API.
If you need to have hands on registered users, you'd better use an external sql database.

**Comment by bp91** [comment]
@cromain thanks for the answer. Why It's not a good idea? If I have to integrate for example into an external application that uses ejabberd for its rest api, and I want for example to do a complete export of registered agents without using an external db, I can't. I think that this is a missed feature. I don't have to integrate ejabberd with an external db and querying directly this db!!!!
