### ISSUE TITLE
Log off user from web admin console

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2505]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu

> How did you install ejabberd (source, package, distribution)?

.deb

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm logged in into the web admin console of ejabberd (http://localhost:5280/admin) and I would like to force the logoff of an online user. Is it possible? I have to configure something into the ejabberd.yml conf file? Thanks

**Comment by zinid** [comment]
No, this is currently not possible.

**Comment by bp91** [comment]
@zinid thanks for your answer and for your support
