### ISSUE TITLE
ejabberdctl register with MySQL

### ISSUE THREAD

**Issue by handsonin** [processone/ejabberd#2506]
> What version of ejabberd are you using?
18.06

> What operating system (version) are you using?
CentOS 6.8

> How did you install ejabberd (source, package, distribution)?
.run

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Run the following command：
./ejabberdctl register user host password 

ejabberd.log displayed as follows:
@ejabberd_sql:check_error:1099 SQL query 'Q14145189' at {ejabberd_auth_sql,174} failed: "#HY000Field 'server_host' doesn't have a default value"

I hope I can get help, thank you very much.

**Comment by licaon-kter** [comment]
Did you setup SQL? Mysql? Postgresql?

**Comment by prefiks** [comment]
You probably need to set option new_sql_schema to true in your config file, this is top level option, there should be no space before it just make sure it looks like:
```
new_sql_schema: true
```

**Comment by handsonin** [comment]
@prefiks You are right, and after upgrading from v18.04 to v18.06 yesterday, this problem has arisen and is now resolved, thank you very much.
