### ISSUE TITLE
Custom IQ Handler not working

### ISSUE THREAD

**Issue by dlameri** [processone/ejabberd#2508]
> What version of ejabberd are you using?
18.06

> How did you install ejabberd (source, package, distribution)?
As a dependency

> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

On 18.04 i had a custom iq, that was something like this
`
<iq type='get' id='e95d03bd-3ed2-4577-96b6-0b3fa0984505' xmlns='jabber:client'><query xmlns='urn:xmpp:create_room'><list_id>489249229</list_id></query></iq>
`
I registered my module to handle this query with : 
`
:gen_iq_handler.add_iq_handler(
      :ejabberd_sm,
      host,
      @muc_create_room_namespace,
      __MODULE__,
      :process_create_room,
      50
    )
`
After updating, i'm receiving this error:

`Unknown tag <query/> qualified by namespace 'urn:xmpp:create_room';`

After some investigation i saw that the error was on this method of xmpp_codec:

`
decode({xmlel, Name, Attrs, _} = El, TopXMLNS, Opts) ->
    XMLNS = get_attr(<<"xmlns">>, Attrs, TopXMLNS),
    case get_mod(Name, XMLNS) of
      undefined when XMLNS == <<>> ->
	  erlang:error({xmpp_codec, {missing_tag_xmlns, Name}});
      undefined ->
	  erlang:error({xmpp_codec, {unknown_tag, Name, XMLNS}});
      Mod -> Mod:do_decode(Name, XMLNS, El, Opts)
    end.
`

It seems that he isn't finding my module on the xmpp_codec_external:lookup. I noticied that there was some changes on iq handling, but nothing concerning this.

Is this a bug or is some configuration missing on my part?

**Comment by dlameri** [comment]
Actually, this commit that made it stop working: 

https://github.com/processone/ejabberd/commit/17b05ff4b733089f0118768b941497fc5a92d8bf#diff-871a58572ad146ae3f93f99560f3c811

And there is nothing on the docs about that.

**Comment by zinid** [comment]
> And there is nothing on the docs about that

That was an undocumented hack, it was removed, so there was nothing to document.

> So, how should i proceed?

https://github.com/processone/xmpp/issues/9
