### ISSUE TITLE
Document data structure for session stored in Redis backend

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#2509]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is possible to obtain this info? I can't find it anywhere.

Using redis-cli console I can list the session management stored keys and the content inside them using HGETALL Key command, for example.

But the content is quite unreadable and it would be very useful to be able to read and use it.

**Comment by zinid** [comment]
> But the content is quite unreadable and it would be very useful to be able to read and use it

Because ejabberd stores serialized Erlang structures there. You need to use Erlang to deserialize them.
