### ISSUE TITLE
[Feature] Allow logging directly to syslog w/ lager_syslog

### ISSUE THREAD

**Issue by michalrus** [processone/ejabberd#2510]
> What version of ejabberd are you using?

17.07.

> What operating system (version) are you using?

NixOS 17.09.

> How did you install ejabberd (source, package, distribution)?

Package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

This sub-library for Lager seems to allow syslog as a sink: https://github.com/erlang-lager/lager_syslog

Currently it can be kind-of simulated by:
* running `ejabberdctl foreground`,
* and setting logs directory to `tmpfs` in `/run/log/ejabberd`,
* and:
    ```yaml
        log_rotate_size: 1
        log_rotate_date: ""
        log_rotate_count: 0
    ```
    … to keep the `tmpfs` stuff minimal.

But then still, the logs look kind of silly, with double timestamps and `[info]`, `[warning]`, `[error]` markers instead of correct syslog severities, e.g.:

```
Jul 06 00:44:12.253325 ejabberdctl[683]: 00:44:12.252 [info] Loading configuration from /nix/store/b1i9g0dq6awwhjm2j11in8armx9v9a17-ejabberd.yml
Jul 06 00:44:19.224464 ejabberdctl[683]: 00:44:19.223 [info] Application mnesia started on node ejabberd@localhost
```

**Comment by cromain** [comment]
problem is lager_syslog is not maintained. one would need to test if it works with lager 3.4.x

**Comment by zinid** [comment]
I close the issue because:
- lager_syslog is abandoned and we don't have enough resources to maintain it
- syslog is not a cross-platform tool for the logging and thus has very little priority for us
