### ISSUE TITLE
change of mod_muc option "history_size" not honoured by reload_config

### ISSUE THREAD

**Issue by ChaosKid42** [processone/ejabberd#2513]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Arch Linux version 4.14.52-1-ARCH on raspberry pi 2

> How did you install ejabberd (source, package, distribution)?

Compiled it myself using the arch PKGBUILD:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ejabberd

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Steps to reproduce:

1. configure mod_muc without option `history_size`

2. entered a MUC room and send some messages

3. after re-entering the room, at most 20 messages (default history size) are pushed to the client (checked on gajim's XML-console)

4. change ejabberd.yml and add option `history_size=0` to mod_muc config

5.  `sudo -u jabber HOME=/var/lib/ejabberd /usr/bin/ejabberdctl reload_config`

6. after re-entering the room, again up to 20 messages from the history are pushed (again checked on gajim's XML-console)

Expected result:

After step 5 entering a room will not yield any messages from the history (except subject message).

It needed restarting ejabberd with `systemctl restart ejabberd` to reach the expected result.

I believe this is not the intended behaviour.

**Comment by badlop** [comment]
The reload_config command documentation says:
> Reload config file in memory

This means that each option will be applied in practice depending on how the option is used, maybe immediately, or maybe after some other event.

In the case of mod_muc's history_size option, the configured value is read from memory when a room is created. So, newly created rooms will have the new value, and old rooms will continue with the old value. In order for old rooms to also use the new value, you must restart the mod_muc module. That will stop all the modules, and start all the persistent ones again, but now with the new value.  To restart mod_muc you can use the WebAdmin.

**Comment by zinid** [comment]
I reopened the issue because it's a bug: the configuration should be reloaded immediately in this case: there is nothing technically preventing us from doing so.
