### ISSUE TITLE
Error Occured while starting ejabbered

### ISSUE THREAD

**Issue by VickyQAS** [processone/ejabberd#2523]
> What version of ejabberd are you using?
Ejabbered-18.06-Windows

> What operating system (version) are you using?
Window 7

> How did you install ejabberd (source, package, distribution)?
Installer (https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/18.06/ejabberd-18.06-windows-installer.exe)

> What did not work as expected? Are there error messages in the log? What

When Starting server as mentioned here : https://docs.ejabberd.im/admin/installation/#install-on-windows. Getting error message in ejabbered log file. Rest all log files are empty. 

Error: https://gist.github.com/VickyQAS/412721094373b81686d081529c5414ab

> was the unexpected behavior? What was the expected result?
Must start server without any error.

**Comment by cromain** [comment]
the log shows ejabberd correctly started, then correctly stopped. all looks good.
2018-07-10 15:37:28.424 [info] <0.64.0>@ejabberd_app:start:59 ejabberd 18.06 is started in the node ejabberd@localhost in 21.92s
2018-07-10 15:37:36.327 [info] <0.64.0>@ejabberd_app:stop:86 ejabberd 18.06 is stopped in the node ejabberd@localhost

this means some script/action triggered call to 'ejabberdctl stop'
