### ISSUE TITLE
Failed to start ejabberd.service: Unit epmd.service not found

### ISSUE THREAD

**Issue by kapilsingh421** [processone/ejabberd#2531]
> What version of ejabberd are you using?

> What operating system (version) are you using?
Ejabbered-18.06-ubuntu(16.04)(ec2)

> How did you install ejabberd (source, package, distribution)?
![screen shot 2018-07-15 at 8 57 17 pm](https://user-images.githubusercontent.com/37150928/42735454-bb173d66-8871-11e8-95f6-fa63e5e44ff9.png)
wget https://www.process-one.net/downloads/ejabberd/18.06/ejabberd-18.06.tgz

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

**Comment by weiss** [comment]
You said you downloaded the source tarball, but you're using an `ejabberd.service` unit file which depends on an `epmd.service` unit.  [The one provided with the source tarball][1] does not.

[1]: https://github.com/processone/ejabberd/blob/18.06/ejabberd.service.template
