### ISSUE TITLE
Invalid value 'sql' for option 'db_type' of module

### ISSUE THREAD

**Issue by ForGuru** [processone/ejabberd#2532]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?
Distribution 

> What did not work as expected? Are there error messages in the log? What
Developed module to save Delivery Receipt in MySQL table. Compiled . Giving following error 

2018-07-15 18:08:57.168 [error] <0.319.0>@gen_mod:module_error:571 Invalid value 'sql' for option 'db_type' of module 'mod_ims_event_msg'

```
following is .yml setting 
  mod_ims_event_msg:
    db_type: sql
```

This is how I am handling db_type

```
depends(_Host, _Opts) ->
    [].
reload(_Host, _NewOpts, _OldOpts) ->
	ok.
mod_opt_type(db_type) -> fun(T) -> ejabberd_config:v_db(?MODULE, T) end.


mod_options(Host) ->
    [{db_type, ejabberd_config:default_db(Host, ?MODULE)}].
```

I have these three modules compiled and deployed 
mod_ims_event_msg_sql.beam
mod_ims_event_msg_mnesia.erl
mod_ims_event_msg.erl

> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment]
Did you set `CONTRIB_MODULES_PATH` of ejabberdctl.cfg? ejabberd needs to know where to look for the modules.

**Comment by zinid** [comment]
Another way is to set `-pa directory_with_your_beams` in `ERL_OPTIONS` of ejabberdctl.cfg.

**Comment by ForGuru** [comment]
@zinid  when I put my other modules .beam file in 

> /opt/ejabberd-18.06/lib/ejabberd-18.06/ebin/ 

that works fine this is the module which has some issues.

**Comment by ForGuru** [comment]
I am facing this issue when I compile module on server which has installation through Installer 
https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/18.06/ejabberd-18.06-linux-x86_64-installer.run

And issue is not appearing the server which has installation though sources.

I think some issue in Linking Library .
