### ISSUE TITLE
MS SQL setup script is invalid

### ISSUE THREAD

**Issue by rouen-sk** [processone/ejabberd#2535]
Hello, I am just trying to setup ejabberd with Azure SQL database, and there are several errors in your mssql setup script:
1. bad semicolon on https://github.com/processone/ejabberd/blob/68c9328a9c9c74df79e66d008a1d25ff64cfd33f/sql/mssql.sql#L139
2. two clustered indexes (this is not allowed) on tables `muc_online_users` (I have kept `muc_online_users_us` as clustered) and `push_session` (I have kept `i_push_usn` as clustered)
3. TEXTIMAGE ON PRIMARY is not usable on Azure SQL (this is not bug, just hint) https://github.com/processone/ejabberd/blob/68c9328a9c9c74df79e66d008a1d25ff64cfd33f/sql/mssql.sql#L532

**Comment by zinid** [comment]
We kinda don't accept bug reports about MSSQL. You're better off creating a PR.
We just don't have a way to test this because keeping mssql/azure running costs money (last time I checked) for almost zero benefit.
