### ISSUE TITLE
ejabberd 18.04 version --> consuming more cpu memory 

### ISSUE THREAD

**Issue by mallik3230** [processone/ejabberd#2539]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Ubuntu (ngix server )

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
consuming more cpu memory 
> was the unexpected behavior? What was the expected result?

**Comment by licaon-kter** [comment]
More CPU or more Memory? Compared to what? Started when? 

Do attach logs, rrd files, something.

**Comment by mallik3230** [comment]
More CPU
