### ISSUE TITLE
Crashed ejabberd restart

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#2542]
> What version of ejabberd are you using?
16.04

> What operating system (version) are you using?

 ubuntu 14.04 lts 

> How did you install ejabberd (source, package, distribution)?

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I have a problema but the vps not restart ejabberd!!
I hope you can help me!!!!!

Log:

2018-07-22 15:13:30 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.37.0>
    registered_name: []
    exception exit: {{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{noproc,{gen_server,call,[ejabberd_sup,{start_child,{ejabberd_sm,{ejabberd_sm,start_link,[]},transient,1000,worker,[ejabberd_sm]}},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.36.0>]
    messages: []
    links: [<0.36.0>,<0.38.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 116
  neighbours:

**Comment by zinid** [comment]
Sorry, we don't provide support for outdated versions. Please update to 18.x
