### ISSUE TITLE
Windows service wont start automatically after boot

### ISSUE THREAD

**Issue by rouen-sk** [processone/ejabberd#2544]
ejabberd 18.06 on Windows Server 2016, installed from installer package. 
Windows service has startup type Automatic, but wont start after server boot. Event log provides these error messages:
`ejabberd01d41e9505ff3a00: Could not get registry keys for erlang service.`
and
`The ejabberd01d41e9505ff3a00 service terminated with the following error: 
The configuration registry key could not be read.`

From quick google search it seems that various erlang-based project have this issue, and it can be "resolved" by changing service startup mode to Automatic-delayed. But this effectively prolong offline time of service by 2 more minutes. 
Is it possible that ejabberd service is starting "too soon" and should have some other service (registry-related) as dependency?

**Comment by cromain** [comment]
i fixed several bugs on windows, if someone can provide some guidance about this i'll include fix for 19.02.

**Comment by badlop** [comment]
No Windows installer is produced since a year ago. Nowadays the preferable method to install ejabberd on Windows machines is using the Docker image. So, this ticket can be closed.
