### ISSUE TITLE
got unexpected info: gen_event

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2549]
> What version of ejabberd are you using?

18.06.82 ([I guess this is the version]( https://github.com/processone/ejabberd/issues/2548 ))

> What operating system (version) are you using?

Raspbian

> How did you install ejabberd (source, package, distribution)?

git

> What did not work as expected? Are there error messages in the log? What

`loglevel: 3` so I don't have much info for now, basically my log is filled with:

`[warning] <0.XXXX.0>@ejabberd_c2s:process_info:252 got unexpected info: {'$gen_event',{socket,closed}}`

I'll switch to 4 to get more info.

/LE: seeing this on .88 too, level 4 does not show addition information unfortunately.
Any ideas (besides level 5) ? :-|

**Comment by licaon-kter** [comment]
Log is full of these, also #2547 happens now continously, they don't seem related exactly but 🤷

**Comment by zinid** [comment]
@prefiks this is related to your [commit](https://github.com/processone/xmpp/commit/8bf26b9e208bd0059cd8fd4e6593d88548c136cf) in xmpp. Any thoughts?

**Comment by prefiks** [comment]
This should be fixed by commit 43aca4c1e6b868444ad1669cd8bf8407bc74819f in xmpp

**Comment by licaon-kter** [comment]
@zinid so I'll wait for ejabberd to update its dependencies on that xmpp hash, right?

**Comment by prefiks** [comment]
Ups, forgot to push change that updated this dep, if you update to master you should get it.
