### ISSUE TITLE
Ejabberd Clustor file sharing not working

### ISSUE THREAD

**Issue by jigsp269** [processone/ejabberd#2550]
> What version of ejabberd are you using?

ejabberd-18.04

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Using RPM Package 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have setup a cluster in two different system. Cluster is completely setup, Chat between two user of different system is working properly but I am not be able to share files between those users.

For file_sharing, I am using mod_http_upload. And file sharing is working properly when I use this functionality without implementing cluster.
Please provide solution for the same

**Comment by licaon-kter** [comment]
How did you setup http_upload exactly? Eg. Share your config .yml

**Comment by jigsp269** [comment]
In Ejabberd.yml :-

ip: "::"
    port: 5443
    tls : true
    module: ejabberd_http
    request_handlers:
         "upload": mod_http_upload
    web_admin: true
    http_bind: true
    register: true
    captcha: true
    certfile: "/usr/local/etc/ejabberd/ejabberd.pem"

 mod_http_upload:
       docroot: "/home/ravi/upload"    //My UPLOAD File Path
       put_url: "https://@HOST@:5443/upload"

**Comment by licaon-kter** [comment]
And all clusters can access the upload server?

What does the ejabberd. log say?

**Comment by jigsp269** [comment]
Yes, I use two system for clustor.
And for the upload I use one system of them.

And log are like 
2018-07-30 14:14:54.579 [debug] <0.1238.0>@ejabberd_http:process:364 [<<"upload">>,<<"96ff88d459a2946d98fa1320fe81e88ff699bc98">>,<<"aUVT8H96CN5CONjmHifyo1jnpJ37XMeugQPp0e5j">>,<<"ER4JZP
SZQsWGi8izd4nk-w.jpg">>] matches [<<"upload">>]

**Comment by jigsp269** [comment]
Please provide solution for this.

**Comment by zinid** [comment]
This is a bug tracker, dude.
