### ISSUE TITLE
cacert.pem uses deprecated sha1?

### ISSUE THREAD

**Issue by Undigon** [processone/ejabberd#2554]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Debian Stretch (9.5)

> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/18.06/ejabberd-18.06-linux-x86_64-installer.run

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

While trying to use a certificate signed with my own certificate authority I ran into many troubles (```~/ejabberd-18.06/conf/localhost.pem: failed to decode from DER format```). In order to try and gain a better understanding of what could be wrong I started running
```openssl x509 -text -noout -inform PEM -in *.pem```
on _cacert.pem_, server.pem and my unlucky localhost.pem.

Reading the output I've noticed that _cacert.pem_ uses **sha1**. Because of security concerns over sha1 (deprecated since 2016?) I was expecting _cacert.pem_ to use **sha256**.

**Comment by zinid** [comment]
> I was expecting cacert.pem to use sha256

So go tell Mozilla to pack only sha256 CA certs in their bundle. Because this is the bundle we use in the ejabberd installer.
