### ISSUE TITLE
max_user_conferences is compared to user’s # of joined MUCs across all vhosts

### ISSUE THREAD

**Issue by michalrus** [processone/ejabberd#2556]
> What version of ejabberd are you using?

17.07.

> What operating system (version) are you using?

NixOS.

> How did you install ejabberd (source, package, distribution)?

Package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

* If I define two independent vhosts, each hosting a MUC service,

* and define `max_user_conferences` for the second MUC service:

    ```yaml
            modules:
              mod_muc:
                max_user_conferences: 1
    ```

* and join a few rooms on the first MUC service,

* then I cannot join any rooms on the second MUC service.

The vhosts manual says that vhosts are truly independent, so the number of joined MUCs should not be global here. E.g. magine if those MUC services were running on different machines, not as different vhosts.

I.e. as an admin, I would like to limit `max_user_conferences` across a single MUC service I’m defining.

How can this be achieved?

**Comment by licaon-kter** [comment]
Do attach (in a https://gist.github.com link) the whole config, you can add [per host settings](https://docs.ejabberd.im/admin/configuration/#virtual-hosting) with `append_host_config`

**Comment by michalrus** [comment]
These are the offending lines:

https://github.com/processone/ejabberd/blob/c9ba0e83d28866f3b2cd47291b3e403e3ad2eadc/src/mod_muc_room.erl#L1875-L1885

So `NConferences` seems to be taken from across all vhosts…

**Comment by michalrus** [comment]
On the other hand this seems to be taking `ServerHost` into consideration…

https://github.com/processone/ejabberd/blob/c9ba0e83d28866f3b2cd47291b3e403e3ad2eadc/src/mod_muc_room.erl#L4335-L4339

So I really don’t know. Perhaps it’s because the servers are named `chat` and `sub.chat`, one being a subdomain of the other?

**Comment by michalrus** [comment]
> Perhaps it’s because the servers are named chat and sub.chat, one being a subdomain of the other?

OMG, it seems so… This feels rather wrong…

**Comment by licaon-kter** [comment]
Do you really need `fqdn: "chat"` ?

**Comment by michalrus** [comment]
(I think I hoped `fqdn:` would remove some warning from logs, but that failed, IIRC.)

**Comment by michalrus** [comment]
Actually it’s this one. `_ServerHost` is simply ignored. :confused: 

https://github.com/processone/ejabberd/blob/5b055d7eecdfd901054ddda2490c3359c2bc6ccf/src/mod_muc_mnesia.erl#L266-L272

**Comment by michalrus** [comment]
What’s the reasoning here?

**Comment by michalrus** [comment]
Mhhhh, I see:
* `count_online_rooms_by_user` gets server host (e.g. `example.com`)
* but the `muc_online_users` Mnesia table holds full MUC hosts, e.g. `conference.example.com`):

```
(ejabberd@localhost)5> ets:tab2list(muc_online_users).
[{muc_online_users,{<<"42af094b-d6f7-4673-ae0e-d6624d24459a">>,
                    <<"chat">>},
                   <<"converse.js-30400625">>,<<"announcements">>,
                   <<"muc.public.chat">>},
 {muc_online_users,{<<"42af094b-d6f7-4673-ae0e-d6624d24459a">>,
                    <<"chat">>},
                   <<"converse.js-30400625">>,<<"discussions">>,
                   <<"muc.public.chat">>}]
```

**Comment by michalrus** [comment]
So a rather silly patch that makes Ejabberd behave according to docs (i.e. completely separate vhosts), if you configure

```yaml
              mod_muc:
                host: "muc.@HOST@"
```

is:

```diff
diff --git a/src/mod_muc_mnesia.erl b/src/mod_muc_mnesia.erl
index 53f31cb9..ebf0deec 100644
--- a/src/mod_muc_mnesia.erl
+++ b/src/mod_muc_mnesia.erl
@@ -262,12 +262,13 @@ unregister_online_user(_ServerHost, {U, S, R}, Room, Host) ->
                      #muc_online_users{us = {U, S}, resource = R,
                                        room = Room, host = Host}).
 
-count_online_rooms_by_user(_ServerHost, U, S) ->
+count_online_rooms_by_user(ServerHost, U, S) ->
+    H = << <<"muc.">>/binary, ServerHost/binary >>,
     ets:select_count(
       muc_online_users,
       ets:fun2ms(
-       fun(#muc_online_users{us = {U1, S1}}) ->
-               U == U1 andalso S == S1
+       fun(#muc_online_users{us = {U1, S1}, host = H1}) ->
+               U == U1 andalso S == S1 andalso H == H1
        end)).
 
 get_online_rooms_by_user(ServerHost, U, S) ->
```

**Comment by badlop** [comment]
In SQL backends, only the current MUC service is used, not all the other vhosts, so I guess this behaviour in Mnesia is not expected nor desired. I've fixed it for mnesia. Thanks for reporting!

**Comment by michalrus** [comment]
@badlop No prob!

BTW, I’m using:

```yaml
        default_db: sql
```

… and still the Mnesia backend is used for that info, not SQL. That SQL table stays empty, hmm.

**Comment by badlop** [comment]
Right, I noticed that. Looking at the source code, I found an undocumented option:
```yaml
  mod_muc:
    db_type: sql
    ram_db_type: sql
```
I wonder why ram_db_type is not documented: forgotten? not recommented? experimental feature?

**Comment by licaon-kter** [comment]
IIRC saw that in the webadmin.

**Comment by badlop** [comment]
That's the default value, in case the admin didn't configure the 'host' option in the module.

**Comment by michalrus** [comment]
But then that default value is hardcoded in at least two places. Unlikely to change, tho, however this feels slightly wrong. =]
