### ISSUE TITLE
mod_offline not dispatching message properly

### ISSUE THREAD

**Issue by faysal515** [processone/ejabberd#2558]
> What version of ejabberd are you using?
17.01

> What operating system (version) are you using?
Ubuntu 14.04 LTS

> How did you install ejabberd (source, package, distribution)?
distribution

> What did not work as expected? Are there error messages in the log?

mod_offline is not dispatching offline message

> What was the unexpected behavior? What was the expected result?

I'm using ejabberd for one of my hybrid(react native) app. When I'm in the app foreground, I login/authorize my user and start the stream. When I'm going background or killing the app, I'm disconnecting the stream and logging again when the app comes in the foreground.My offline messages are not being dispatched to the user when the app comes in the foreground. I've observerd that If I logout and login back only then its dispatching those offline messages

N.B. after the transition of background -> foreground, everything works(sending/receiving msg) except this problem. this is why I believe my problem can be on the server rather than the client-side connection issue. This weird problem is occurring when I'm exiting the app using Android hardware back button. If I press the home button to go background and the comeback, it seems to work fine

**Comment by badlop** [comment]
You can sniff the XMPP traffic that the client is sending to the server, to determine what are the differences in the traffic between the cases where all works correctly and the one when it fails. I use tcpflow, but there many tools, also graphical network sniffers Wireshark, Ethereal...
