### ISSUE TITLE
can't update profile picture.

### ISSUE THREAD

**Issue by jigsp269** [processone/ejabberd#2559]
> What version of ejabberd are you using?
ejabberd-18.04

> What operating system (version) are you using?
CentOS 7

> How did you install ejabberd (source, package, distribution)?
Using RPM Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have setup ejabbered with file sharing. It's working fine but i can't update profile picture.
It gives error like **"The server rejected your publication"**

**Comment by licaon-kter** [comment]
What client? Did you load `muc_vcard` ?

**Comment by jigsp269** [comment]
Yes, I implement this, but that is not work for me. So please provide me how to add this.
Thanks in advance.

**Comment by licaon-kter** [comment]
What client do you use to setup an avatar?

**Comment by jigsp269** [comment]
My client as a conversation app user

**Comment by licaon-kter** [comment]
What does "ejabberd.log" show when you try to publish?

**Comment by jigsp269** [comment]
Please find the attachment for log.
[ejabberd.log](https://github.com/processone/ejabberd/files/2265897/ejabberd.log)

**Comment by jigsp269** [comment]
mod_pubsub:
**db_type: sql this line must be commented**
access_createnode: pubsub_createnode
ignore_pep_from_offline: true
last_item_cache: false
plugins:

"flat"
"hometree"
"pep"

mod_vcard:
search: true
**db_type: sql this line must be commented**
mod_vcard_xupdate:
use_cache: false

Using this i resolved this.
