### ISSUE TITLE
your server does not support the publication of avatars

### ISSUE THREAD

**Issue by jigsp269** [processone/ejabberd#2560]
> What version of ejabberd are you using?

ejabberd 18.04

> What operating system (version) are you using?

centos 7

> How did you install ejabberd (source, package, distribution)?

using RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Please provide the solution for this

I am configure ejabberd 18.04 and configure **mod_pubsub** as above
**mod_pubsub:
db_type: sql
access_createnode: pubsub_createnode
ignore_pep_from_offline: true
last_item_cache: false
plugins:
- "flat"
- "hometree"
- "pep"**

and also add
**mod_vcard_xupdate:
use_cache: false**

I want to add or update profile picture to client
I use client as a conversation app.
On app side i get error **"your server does not support the publication of avatars"**

**Comment by jigsp269** [comment]
Yes but it's with more details of issue

**Comment by licaon-kter** [comment]
Close this and add the info there

**Comment by jigsp269** [comment]
mod_pubsub:
**db_type: sql** this line must be commented
access_createnode: pubsub_createnode
ignore_pep_from_offline: true
last_item_cache: false
plugins:

"flat"
"hometree"
"pep"

 


mod_vcard:
    search: true
    **db_type: sql**  this line must be commented
  mod_vcard_xupdate:
    use_cache: false


Using this i resolved this.
