### ISSUE TITLE
Call to undefined function ejabberd_auth_http:get_vh_registered_users

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd#2561]
> What version of ejabberd are you using?

Ejabberd 17.04

> What operating system (version) are you using?

Centos

> How did you install ejabberd (source, package, distribution)?

distribution

> What did not work as expected? Are there error messages in the log? What
was the unexpected behavior? What was the expected result?

I am using http_auth for authentication its working fine both gateway and admin panel work but when I tried to check admin panel `mydomain:5280/admin/vhosts/` page shows some thing like

This page isn’t working
34.210.89.126 didn’t send any data.
ERR_EMPTY_RESPONSE

And Through Error 

2018-08-08 03:56:20.635 [error] <0.28165.15> CRASH REPORT Process <0.28165.15> with 0 neighbours crashed with reason: call to undefined function ejabberd_auth_http:get_vh_registered_users(<<"my-home-portal">>)

Thanks.

**Comment by badlop** [comment]
I think was solved in 633b68db1130c81551b063f3aa15d599b0d355e5, included ince ejabberd 17.06. Can you update, test and confirm it?

**Comment by Adiii717** [comment]
@badlop Thanks for the suggestion but we are using this in production in a cluster and we do not want downtime is there patch if we can run, please

**Comment by badlop** [comment]
It is a very big commit that affects many files with many changes, so better not to apply it alone. Also, it isn't a good idea to mix nodes that run different ejabberd versions.

But, in your case, if you don't mind getting wrong values in that webpage about the number of registered accounts, you can apply a small patch like this to avoid crashes:
```diff
diff --git a/ejabberd_auth_http/src/ejabberd_auth_http.erl b/ejabberd_auth_http/src/ejabberd_auth_http.erl
index 8bd213d..407c3ce 100644
--- a/ejabberd_auth_http/src/ejabberd_auth_http.erl
+++ b/ejabberd_auth_http/src/ejabberd_auth_http.erl
@@ -30,6 +30,8 @@
          opt_type/1,
          stop/1]).
 
+-export([get_vh_registered_users/1]).
+
 -include("scram.hrl").
 -include("logger.hrl").
 
@@ -37,6 +39,9 @@
 %%% API
 %%%----------------------------------------------------------------------
 
+get_vh_registered_users(_) ->
+    [].
+
 opt_type(auth_opts) -> fun (V) -> V end;
 opt_type(_) -> [auth_opts].
 
```

**Comment by Adiii717** [comment]
@badlop Thanks
