### ISSUE TITLE
If more that 90 ldap (Active Directory) users have status online, messages not deliver

### ISSUE THREAD

**Issue by sfalkon** [processone/ejabberd#2565]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

CentOS Linux release 7.5.1804 (Core)

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have a problem similar to [this one](https://github.com/processone/ejabberd/issues/1784)

There is domain with ldap auth method. If users in state online > ~90 that messages did not deliver to them. But all are not delivered message content into archive (mod_mam)

**Comment by mremond** [comment]
You should at the log, possibly in debug mode to search for errors.

**Comment by Neustradamus** [comment]
@sfalkon Any news?
