### ISSUE TITLE
Ejabberd - getting “Failed c2s PLAIN authentication” error message

### ISSUE THREAD

**Issue by saranraj07** [processone/ejabberd#2566]
@zinid 
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

Package (https://www.process-one.net/downloads/ejabberd/17.11/ejabberd-17.11-linux-x86_64-installer.run)

> What did not work as expected? Are there error messages in the log? 

I have installed the Ejabberd version 17.11 in our server. After the intallation, the user is able to connect with the Ejabberd service 1st time successfully. But once the session ended by that user and if the same user tries to connect again then we are getting the below error message.

`(websocket Failed c2s PLAIN authentication for 776145@domainname.com: Invalid username or password
`
> What was the unexpected behavior? What was the expected result?

Getting same issue with the version 18.06 as well. 1st time its opening session with the message. 
`(websocket| Accepted c2s PLAIN authentication for 776145@domainname.com by anonymous backend (websocket| Opened c2s session for 776145@domainname.com/reg_agent `

Once the user disconnected the session then getting message. 
`(websocket| Closing c2s session for 776145@domainname.com/reg_agent: Connection failed: connection closed `

Now user trying to rejoin with the same session and getting error. 
`(websocket Failed c2s PLAIN authentication for 776145@domainname.com: Invalid username or password.`

**Comment by dramancompany** [comment]
me too! i got an error
@ejabberd_c2s:handle_auth_failure:442 (http_bind|<0.632.0>) Failed c2s PLAIN authentication for 51770@xmpp.rememberapp.co.kr from 218.55.119.137: Invalid username or password

**Comment by dramancompany** [comment]
me too! i got an error
@ejabberd_c2s:handle_auth_failure:442 (http_bind|<0.632.0>) Failed c2s PLAIN authentication for id@host from x.x.x.x: Invalid username or password

**Comment by zinid** [comment]
Config please. With comments and newlines stripped.

**Comment by saranraj07** [comment]
[Ejabberd-17.11-Config.txt](https://github.com/processone/ejabberd/files/2285713/Ejabberd-17.11-Config.txt)

Uploaded my config file.

**Comment by zinid** [comment]
The problem is that you combine two auth methods: internal and anonymous. So it's hard to say: maybe the behaviour is expected, or maybe you are facing #2322 
If the latter, you can try to disable authentication cache:
```yaml
auth_use_cache: false
```

**Comment by saranraj07** [comment]
After added the below line its working fine now.
auth_use_cache: false

Also, one more thing - Can we use bosh method instead of http_bind method which was used in lower versions. We used this http_bind method for lower version browsers and iPad app which are all not supporting the WebSocket feature.

Thanks for your great help.

**Comment by dramancompany** [comment]
"auth_use_cache: false" is solved the problem. Thankyou for your help!

**Comment by zinid** [comment]
> Also, one more thing - Can we use bosh method instead of http_bind method which was used in lower versions. We used this http_bind method for lower version browsers and iPad app which are all not supporting the WebSocket feature.

Please don't mix different/unrelated topics in the same issue if you really want to get answers. If you think you see the bug report it separately.
