### ISSUE TITLE
Database Macros Help required

### ISSUE THREAD

**Issue by ForGuru** [processone/ejabberd#2572]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I need help regarding DB Macros like ?SQL_UPSERT_MARK , ?SQL_INSERT, ?SQL_UPSERT

Can you share me a link of some blog ? 

in my custom mule I have to update if id already exist or I have to Insert if does not exist.

**Comment by zinid** [comment]
Use `?SQL_UPSERT` macro: grep sources, there are plenty of examples.

**Comment by ForGuru** [comment]
@zinid Thanks for quick reply .. just a small help will play a big role  

In following example I am assuming **!username** and **!server_hos** fieds to be matched ?? and **xml** to be inserted or updated ??


```
?SQL_UPSERT_T(
                             "motd",
                             ["!username=%(U)s",
                              "!server_host=%(LServer)s",
                              "xml=''"])
```

**Comment by zinid** [comment]
`username` and `server_host` are used inside `where` clause, while `xml` is updated, yes. If the row doesn't exist, all columns are inserted.
