### ISSUE TITLE
configure accept_interval on the c2s listener

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd#2573]
> What version of ejabberd are you using?

Ejabberd 17.04

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I want to configure **accept_interval on c2s listener** but I did not find in the documentation. As `accept_interval` specifies a minimal interval between accepting connections.I want to
 ```
set  number I1 sets the initial interval in milliseconds after ejabberd startup, which will last
for T1 seconds, and then during `T2` seconds it will change linearly to `I2` milliseconds.
```
```

**Comment by badlop** [comment]
Right, accept_interval was implemented years ago in c6798fc51, but never documented. You can simply configure it like this, for an internal of 1 second, right?
```yaml
listen:
  -
    port: 5222
    module: ejabberd_c2s
    accept_interval: 1000
```
