### ISSUE TITLE
Muc private messages are not stored in message archives

### ISSUE THREAD

**Issue by pruthwirajs** [processone/ejabberd#2574]
> What version of ejabberd are you using?

Ejabberd-18.06

> What operating system (version) are you using?

ubuntu-16.04

> How did you install ejabberd (source, package, distribution)?

source installation

Muc private messages are not stored in message archives...I am not able to retrive muc private messages

**Comment by licaon-kter** [comment]
Yes, anyone can join as everyone, you can be sure that's the right person.

**Comment by badlop** [comment]
I configured the module with this:
```yaml
  mod_mam:
    default: always
```
Next user1 created a room and enabled archiving in it. Later user2 joins the room also. And user1 sent a private message in the room to user2. Finally, user2 requested the archive:
```xml
<iq type='set' id='juliet1'>
  <query xmlns='urn:xmpp:mam:2' queryid='f27' />
</iq>

<message to='user2@localhost/tka22'
	from='user2@localhost'>
  <result id='1534499261154492'
	queryid='f27'
	xmlns='urn:xmpp:mam:2'>
    <forwarded xmlns='urn:xmpp:forward:0'>
      <message xml:lang='es'
	to='user2@localhost/tka22'
	from='sala1@conference.localhost/user1'
	type='chat'
	id='221:478790'
	xmlns='jabber:client'>
        <archived by='user2@localhost'
	id='1534499261154492'
	xmlns='urn:xmpp:mam:tmp'/>
        <stanza-id by='user2@localhost'
	id='1534499261154492'
	xmlns='urn:xmpp:sid:0'/>
        <active xmlns='http://jabber.org/protocol/chatstates'/>
        <x xmlns='jabber:x:event'>
          <offline/>
          <delivered/>
          <displayed/>
          <composing/>
        </x>
        <x xmlns='http://jabber.org/protocol/muc#user'/>
        <body>private message in the room</body>
      </message>
      <delay from='localhost'
	stamp='2018-08-17T09:47:41.154492Z'
	xmlns='urn:xmpp:delay'/>
    </forwarded>
  </result>
</message>
```

**Comment by pruthwirajs** [comment]
When you request messages from MAM...muc private messages are not coming ...but the normal conversation restore..@badlop

**Comment by licaon-kter** [comment]
@pruthwirajs what type of MUC? Private? Anonymous? ? ?

**Comment by pruthwirajs** [comment]
@licaon-kter  its a private muc..

**Comment by pruthwirajs** [comment]
@badlop 


  mod_mam:
    default: always
    request_activates_archiving: true       ##true|false
    ## assume_mam_usage: on_request                ##if_enabled|on_request|never
    cache_size: 1000
 mod_muc:
    ## host: "conference.@HOST@"
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    max_user_conferences: 50
    max_users: 3
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}

**Comment by weiss** [comment]
> Muc private messages are not stored in message archives

How *exactly* did you check that the messages aren't in the user's archive?

**Comment by pruthwirajs** [comment]
Actually I clear the messages..and try to fetch the message using MAM..All the normal message getting stored except the private message in muc ..  @weiss

**Comment by jovanpreet** [comment]
Hi actually I had a similar kind of issue. When User A sends message to `test` room the only entry that goes to `archive` table is this.

```
  username: test@conference.localhost
 timestamp: 1546447139557452
      peer: 30957@localhost/2ddfc688-214f-4d75-ac57-9a0bfba9eb3f
 bare_peer: 30957@localhost
       xml: <message xml:lang='en' to='test@conference.localhost' from='30957@localhost/2ddfc688-214f-4d75-ac57-9a0bfba9eb3f' type='groupchat' id='test-id-123' xmlns='jabber:client'><markable xmlns='urn:xmpp:chat-markers:0'/><body>SGVsbG8=</body><subject>chat_text</subject></message>
       txt: SGVsbG8=
        id: 58160569
      kind: groupchat
      nick: 30957
created_at: 2019-01-02 16:38:59
    msg_id: NULL
```

User B receive message from `mod_offline` but can't fetch from `mod_mam`.
Am I doing something wrong?

**Comment by jovanpreet** [comment]
Here you go https://gist.github.com/jovanpreet/8b1e7d3ff058fcfe3667c6aedbaf7500

**Comment by jovanpreet** [comment]
Its a bug in version 18.06. Updating to 18.12.1 solve the issue.
