### ISSUE TITLE
18.06 fails to build with `field sub_els undefined in record ps_item`

### ISSUE THREAD

**Issue by michalrus** [processone/ejabberd#2577]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

NixOS

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When trying to compile 18.06, this happens:

```
==> ejabberd-18.06 (compile)
Compiled asn1/XmppAddr.asn1
Compiled src/eldap_filter_yecc.yrl
Compiled src/ejabberd_sql_pt.erl
Compiled src/ejabberd_config.erl
Compiled src/gen_mod.erl
src/mod_muc_room.erl:4328: field sub_els undefined in record ps_item
src/mod_muc_room.erl:4393: field sub_els undefined in record ps_item
src/mod_muc_room.erl:4312: Warning: variable 'Payload' is unused
src/mod_muc_room.erl:4386: Warning: variable 'El' is unused
Compiling src/mod_muc_room.erl failed:
ERROR: compile failed while processing /build/ejabberd-18.06: rebar_abort
make: *** [Makefile:106: deps/.built] Error 1
```

The latest release which is not affected is 18.01…

**Comment by michalrus** [comment]
Possibly related: https://elixirforum.com/t/ejabberd-as-a-mix-dependency-in-a-phoenix-project-anyone-been-able-to-compile-it-with-mix/12734

**Comment by zinid** [comment]
`make distclean`

**Comment by michalrus** [comment]
It most certainly is a clean build with a sandbox, because it’s being built by Nix ( https://nixos.org/nix/ ), with the same exact recipe that works for 18.01.

**Comment by michalrus** [comment]
Yes, that’s what Nix’ standard builder calls. Hmm. Perhaps this issue should be posted in Nixpkgs, then, if you’re not sure what causes this.
