### ISSUE TITLE
Invalid sql query for text search in mod_mam_sql.erl

### ISSUE THREAD

**Issue by oxoWrk** [processone/ejabberd#2580]
> What version of ejabberd are you using?
last
> What operating system (version) are you using?
no matter
> How did you install ejabberd (source, package, distribution)?
no matter

To search for messages in the archive by text, you use the "MATCH AGAINST" that is not supported by Postgres

**Comment by zinid** [comment]
This feature is not documented, it's non-standard and, thus, should not be used.
