### ISSUE TITLE
OMEMO nonfunctional even after commenting out config lines

### ISSUE THREAD

**Issue by ThatGuy435** [processone/ejabberd#2581]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

DEB package from process-one.net

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Default configuration with the eu.siacs.conversations.axolotl.* and "access_model: whitelist" lines commented out does not work for OMEMO with Gajim 1.03 or Conversations on Android. Also attempted with lines completely deleted.  Server Info on Conversations shows PEP as Available, but throws an error about not being able to find devices. Gajim will not send OMEMO because there are no published device keys.

There does not seem to be anything relevant in /opt/ejabberd/logs/ejabberd.log

Expected result should be functioning OMEMO keys published to the server, as described in the only OMEMO documentation I could find (the comment in the configuration).

**Comment by licaon-kter** [comment]
Delete private data and upload full config on https://gist.github.com

**Comment by ThatGuy435** [comment]
Only changes from default are the hostname (replaced with host_name) and the FQDN, replaced with fq.dn.com, and the removal of the OMEMO lines indicated in the comment.

https://gist.github.com/ThatGuy435/fd4635834dea3400716f8381276db92c

**Comment by ThatGuy435** [comment]
I was just able to get it working by changing the original configuration line from the default of whitelist to blacklist. That section of the config now reads:
`    force_node_config:
      ## Avoid using OMEMO by default because it
      ## introduces a lot of hard-to-track problems
      "eu.siacs.conversations.axolotl.*":
        access_model: blacklist`
