### ISSUE TITLE
HttpFileUploadManager getting SMACK java.io.EOFException: \n not found: size=0 content=

### ISSUE THREAD

**Issue by onlyauvy** [processone/ejabberd#2582]
I am facing the problem in the below:
[https://stackoverflow.com/questions/51885265/httpfileuploadmanager-getting-smack-java-io-eofexception-n-not-found-size-0-c](https://stackoverflow.com/questions/51885265/httpfileuploadmanager-getting-smack-java-io-eofexception-n-not-found-size-0-c)

Here the eJabberd log:
```erl
#iq{id = <<"Om1Ft-22">>,type = result,lang = <<"en">>,
    from = #jid{user = <<>>,server = <<"upload.localhost">>,resource = <<>>,
                luser = <<>>,lserver = <<"upload.localhost">>,
                lresource = <<>>},
    to = #jid{user = <<"mamun">>,server = <<"localhost">>,
              resource = <<"89208986776193817881827">>,luser = <<"mamun">>,
              lserver = <<"localhost">>,
              lresource = <<"89208986776193817881827">>},
    sub_els = [#upload_slot_0{get = <<"http://192.168.43.12:5444/dd2991e77a50488236a27332fad4767668dabd4e/tw3wQPX3h4qXvO5fM1YZKLisMFgUE7PQywnuUMOf/img.jpg">>,
                              put = <<"http://192.168.43.12:5444/dd2991e77a50488236a27332fad4767668dabd4e/tw3wQPX3h4qXvO5fM1YZKLisMFgUE7PQywnuUMOf/img.jpg">>,
                              xmlns = <<"urn:xmpp:http:upload:0">>}],
    meta = #{ip => {192,168,43,1}}}
```

**Comment by weiss** [comment]
The ejabberd log snippet doesn't explain your issue, and from the stack trace, the problem isn't obvious to me; it would have to be tracked down further.  If you still believe this is an ejabberd bug after figuring out the details, please open a new issue and describe how exactly ejabberd's behavior is incorrect.
