### ISSUE TITLE
Mixed Content Error in ejabberd/XMPP chat server

### ISSUE THREAD

**Issue by shazvan275** [processone/ejabberd#2586]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

windows

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My site is protected With SSL when i try to call XMPP Chat server is showing this error.

Mixed Content: The page at 'https://localhost:44300/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.30.1:5280/http-bind/'. This request has been blocked; the content must be served over HTTPS.

how to add ssl to ejabberd/XMPP chat server

pls Help Me am new to this

**Comment by badlop** [comment]
Same question here: https://stackoverflow.com/questions/52027236/mixed-content-error-in-ejabberd-xmpp-chat-server
