### ISSUE TITLE
[Ubuntu Upgrade 16.04 -> 18.04] Log spammed with `got unexpected info`

### ISSUE THREAD

**Issue by wolkenschieber** [processone/ejabberd#2587]
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Ubuntu 18.04.1

> How did you install ejabberd (source, package, distribution)?

Ubuntu bionic universe

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We upgraded the server from Ubuntu 16.04 to Ubuntu 18.04. As part of the upgrade also ejabberd got upgraded from 16.01 to 18.01. We are using `mod_roster` and `mod_shared_roster`.

Everytime a user connects, the `ejabberd.log` is spammed with following messages:
```
[warning] <0.612.0>@ejabberd_c2s:process_info:253 got unexpected info: {item,{<<"user1">>,<<"example.net">>,<<>>},both}
[warning] <0.612.0>@ejabberd_c2s:process_info:253 got unexpected info: {item,{<<"user2">>,<<"example.net">>,<<>>},both}
[warning] <0.612.0>@ejabberd_c2s:process_info:253 got unexpected info: {item,{<<"user3">>,<<"example.net">>,<<>>},both}
[warning] <0.612.0>@ejabberd_c2s:process_info:253 got unexpected info: {item,{<<"user4">>,<<"example.net">>,<<>>},both}
```
The issue is addressed in [#1846](https://github.com/processone/ejabberd/issues/1846) and fixed for (open?) [milestone 18.03](https://github.com/processone/ejabberd/milestone/30).

Since the package is provided through Ubuntu's repository, which is not kind to new versions, is there a way to work around or patch this issue?

**Comment by badlop** [comment]
I've compiled and installed ejabberd 18.01 from the git repository, then tested shared rosters, and it showed the log messages you mention. Then I applied to 18.01 the patch I extracted from git for the https://github.com/processone/ejabberd/commit/bb20e5f3fae35b4952ff23153dba3f306ca552f0 commit. Recompiled, tested, and the log messages didn't appear.

So, you can get the sources of your ejabberd package in ubuntu, then obtain the patch of that commit and apply it, compile, reinstall, and restart. Ask me if you can't obtain the patch yourself.

**Comment by wolkenschieber** [comment]
Thanks a lot for taking your time, reproducing the issue and suggesting a solution!

I've seen bb20e5f, but thought it wasn't applicable to 18.01. This [#1846 comment](https://github.com/processone/ejabberd/issues/1846#issuecomment-374258462) said that a patched ejabberd won't start.

To be honest I was hoping for a patched upstream version. As custom build version tend to cause problems in a production environment. They might conflict with updates.

However I've built a patched deb package, but wasn't able to test this yet. Below are step taken, maybe they provide some help:

# Patch mod_shared_roster in ejabberd 18.04 in 18.04

## Add source repositories

Add to `/etc/apt/sources.list`:
```
deb http://archive.ubuntu.com/ubuntu bionic main universe
deb-src http://archive.ubuntu.com/ubuntu bionic main universe
```

```
~$ sudo apt update
```

## Install ejabberd build dependencies

```
~$ sudo apt build-dep ejabberd
```

## Get source code

```
ejabberd$ apt source ejabberd
```


## Extract patch

```
           ~$ git clone git@github.com:processone/ejabberd.git ejabberd-git
ejabberd-git$ git format-patch -1 bb20e5f3fae35b4952ff23153dba3f306ca552f0
```

## Apply patch

```
           ejabberd-git$ mv 0001-Apply-some-dirty-hacks-for-mod_shared_roster.patch ../ejabberd/ejabberd-18.01
ejabberd/ejabberd-18.01$ patch -p1 < 0001-Apply-some-dirty-hacks-for-mod_shared_roster.patch
```

## Build patched deb package

```
ejabberd/ejabberd-18.01$ pkg-buildpackage -b -uc -us
```

Generated deb package `ejabberd_18.01-2_amd64.deb` to placed in `ejabberd` directory.

## Install patch deb package

```
ejabberd$ dpkg -i ejabberd_18.01-2_amd64.deb
ejabberd$ apt -f install

```

**Comment by zinid** [comment]
I close the issue as it's already fixed.
