### ISSUE TITLE
Error Code 503 - service-unavailable -The feature requested is not supported by the conference

### ISSUE THREAD

**Issue by GondaSridhar007** [processone/ejabberd#2589]
In Android MultiUserChatLight getting error at room chat
Error :- 
<iq xml:lang='en' to='JID' from='RoomId' type='error' id='6oeig-41'><query xmlns='urn:xmpp:muclight:0#configuration'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>The feature requested is not supported by the conference</text></error></iq>

**Comment by zinid** [comment]
Close as badly formed and non informative.
