### ISSUE TITLE
Improvement: Allow a callback for acme proxying when using the renew_certificates command

### ISSUE THREAD

**Issue by malt3** [processone/ejabberd#2590]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Debian GNU/Linux 9.5 (stretch)

> How did you install ejabberd (source, package, distribution)?

Official installer (https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/18.06/ejabberd-18.06-linux-x86_64-installer.run)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My ejabberd installation is running on a subdomain of the SID domain.
So my users have usernames like user@example.com while ejabberd is listening on xmpp.example.com
This creates an interesting problem, because I need a letsencrypt certificate for example.com on xmpp.example.com.
I wrote a small proxy that I want to run on the webserver of example.com that can proxy acme http01 requests to another host. In order for this to work, I would like to have a hook that calls a shellscript so that my proxy knows the request token (e.g. `/.well-known/acme/<token>`).
I think that this problem is quite common for ejabberd installations.

A proposed solution would be a new configuration option inside ejabberd.yml with a path to a script that will be called prior to the authentication. This is similar to the way certbot does it ([https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks](https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks)).

**Comment by paulmenzel** [comment]
I am having the same problem. Is your proxy is publicly available, so others can use it too?

**Comment by malt3** [comment]
It is actually. See 
https://github.com/malt3/acme_proxy
It is just a collection of scripts to work with an nginx proxy.

**Comment by zinid** [comment]
I added a hook `acme_challenge`. One can write a simple ejabberd module to run any script on that hook.
