### ISSUE TITLE
apparmor profile affects /usr/sbin/ejabberdctl even when ejabberdctl is installed in /opt/ejabberd-xx.xx/bin

### ISSUE THREAD

**Issue by MarcelWaldvogel** [processone/ejabberd#2591]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

deb package from ejabberd.im

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The dep package installs the executables etc. below `/opt/ejabberd-18.06`. However, the *apparmor* profile in `/etc/apparmor.d/usr.sbin.ejabberdctl` restricts (as the name suggests) the execution of `/usr/sbin/ejabberdctl`.

1. This does not protect the real `ejabberdctl`
1. This prevents the user from installing a compatibility `ejabberdctl` wrapper in `/usr/sbin/ejabberctl` (a miniature shell script is necessary, as symlinks to the real ejabberdctl not work due to the way `ROOT_DIR` is extracted in `ejabberdctl`)

Could you please rename and modify the apparmor profile to affect `/opt/ejabberd-xx.xx/bin/ejabberdctl`?

**Comment by debalance** [comment]
The deb package from ejabberd.im does not contain an AppArmor profile **at all**, the one from Ubuntu does, you must be mixing things up.
Also, to get Ubuntu's AppArmor profile for ejabberd(ctl) working, you need to change a lot more than just the path to ejabberdctl.

Long story short: there is no bug, at most this could be a feature request to add an AppArmor profile.
Not sure if upstream is interested in that. Maybe you want to provide one (with asterisks for the version in the path).

**Comment by MarcelWaldvogel** [comment]
`dpkg-query -L ejabberd` says:

```
/.
/opt
/opt/bitrock
/opt/bitrock/ejabberd-18.06-0
/opt/bitrock/ejabberd-18.06-0/helperBinary
[2630 files and directories under /opt/ejabberd-18.06]
/etc/ufw/applications.d/ejabberd
/etc/default/ejabberd
/etc/security/limits.d/ejabberd.conf
/etc/logrotate.d/ejabberd
/etc/apparmor.d/usr.sbin.ejabberdctl
/etc/ejabberd/inetrc
/etc/ejabberd/modules.d/README.modules
```

But the `.deb` package definitely does not contain anything under `/etc`. So it must be a remnant of an earlier Ubuntu *ejabberd* installation. Weird that it is reported as belonging to the files that came with your `.deb`.

BTW: The `Description:` in the `control` file is not being substituted. (I can open a separate ticket, if desired)
```
Description: ${msg(ejabberd.desc)}
```
