### ISSUE TITLE
Moduls could not be installed

### ISSUE THREAD

**Issue by Thomas301263** [processone/ejabberd#2594]
> What version of ejabberd are you using?
18.06

> What operating system (version) are you using?
Ubuntu 18.04   kernel 4.15.0-33-generic

> How did you install ejabberd (source, package, distribution)?
First I installed from the source package and then I made upgrades to 18.04.
Three days ago I updated Ubuntu and the ejabberd 18.06-1 packege was included.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The upgrade should work without problems but there were messages that some modules could not be upgraded.
Now ejabberd 18.06-1 is running but if there are programs of Ubuntu which should be updated then I get the message that there are packages which should be updated but couldn't caus of errors.
I tried to update manually but that wont work.
I have done the following steps and got the following error massages:

apt update
OK:1 http://archive.ubuntu.com/ubuntu bionic InRelease
OK:2 http://security.ubuntu.com/ubuntu bionic-security InRelease         
Holen:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]                       
OK:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                           
OK:5 https://apt.jabber.at bionic InRelease                               
Holen:6 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [161 kB]
Holen:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [308 kB]
Holen:8 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [116 kB]
Holen:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [173 kB] 
Holen:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [80,5 kB]
Es wurden 927 kB in 3 s geholt (267 kB/s).                   
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Aktualisierung für 16 Pakete verfügbar. Führen Sie »apt list --upgradable« aus, um sie anzuzeigen

apt dist-upgrade 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete werden aktualisiert (Upgrade):
  console-setup console-setup-linux keyboard-configuration libgpgme11
4 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Es müssen 1.569 kB an Archiven heruntergeladen werden.

apt list --upgradable
Auflistung... Fertig
console-setup/bionic-updates 1.178ubuntu2.7 all [aktualisierbar von: 1.178ubuntu2.6]
console-setup-linux/bionic-updates 1.178ubuntu2.7 all [aktualisierbar von: 1.178ubuntu2.6]
ejabberd-mod-cron/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-log-chat/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-logxml/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-message-log/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-muc-log-http/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-post-log/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-pottymouth/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-rest/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-s2s-log/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-shcommands/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-statsdx/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
ejabberd-mod-webpresence/bionic-fsinf 1:20180821-0.1~ubuntu18.04 amd64 [aktualisierbar von: 1:20180428-0.1~ubuntu18.04]
keyboard-configuration/bionic-updates 1.178ubuntu2.7 all [aktualisierbar von: 1.178ubuntu2.6]
libgpgme11/bionic-updates 1.10.0-1ubuntu2 amd64 [aktualisierbar von: 1.10.0-1ubuntu1]

apt install -f
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 12 nicht aktualisiert.

If I try to install the packages manually I get those messages and don't know now what I can do to install those packages.

 apt install -f ejabberd-mod-cron
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 ejabberd-mod-cron : Hängt ab von: ejabberd (= 1:18.06-1~) aber 1:18.06-1~ubuntu18.04 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by weiss** [comment]
It seems you're using the [jabber.at's APT repository][1] and are now seeing some sort of packaging conflict. You might want to ask in the `chat@conference.jabber.at` room. This tracker is meant for actual ejabberd bugs.

[1]: https://jabber.at/p/apt-repository/

**Comment by mathiasertl** [comment]
@Thomas301263 https://github.com/jabber-at/ejabberd/issues ;-)
