### ISSUE TITLE
Is there any official/contributed extensions available to connect Ejabberd 18 to App Sever to enable push notifications with mod_push

### ISSUE THREAD

**Issue by jithin-pits** [processone/ejabberd#2596]
> What version of ejabberd are you using?

**Ejabberd 18.04**

> What operating system (version) are you using?

**Ubuntu 16**

> How did you install ejabberd (source, package, distribution)?

**Package**

Tired of Installing plugins with different versions, getting lot of issues, Please help.

**Comment by weiss** [comment]
If your question is whether the ejabberd Community Edition includes a module that generates Google or APNS notifications directly then the answer is "no".  The Business Edition does.

**Comment by jithin-pits** [comment]
@weiss thank you so much, my question was actually not about "direct push notification", Its more like

I have a chat App client, a chat **App Back end server**, firebase, and xmpp server **Ejabberd 18**
App back end server and firebase sends push notification and its ok.

I was asking about the connection between **App Back end server**  and **Ejabberd 18** (community edition)

just like the royneary (https://github.com/royneary/mod_push) extension (which is not maintained now )

Thanks in advance

**Comment by weiss** [comment]
> I was asking about the connection between App Back end server and Ejabberd 18

This is described in [XEP-0357][1], though the spec's language makes it sound more complicated than it is.  Ignore all the blah blah about PubSub.  Basically, your app requests a node name and a secret token (think: a user name and password for that app instance) from your back-end server (using XMPP or HTTP or whatever) and hands it over to ejabberd in the `<enable/>` request, together with the back-end's address.  Then `mod_push` will send notification `<iq/>`s as shown in example 13.  You could set up an XMPP server such as ejabberd or [Metre][2] to receive them, and connect to that server instance using the [component protocol][3].

[1]: https://xmpp.org/extensions/xep-0357.html
[2]: https://github.com/surevine/Metre
[3]: https://xmpp.org/extensions/xep-0114.html
