### ISSUE TITLE
help in direct upgradation from ejabberd 16.09 to 18.06

### ISSUE THREAD

**Issue by sumesh048** [processone/ejabberd#2600]
> What version of ejabberd are you using?

ejabberd 16.09

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
![ejjaberd1806](https://user-images.githubusercontent.com/36732187/45283362-44de2400-b4fb-11e8-9492-e94a489c2ffb.png)

> was the unexpected behavior? What was the expected result?

Team,
We have configured ejabberd 16.09 version. but we required to upgrade to ejabberd 18.06.
Please help me to do the steps or can we do the upgradation from 16.09 to 18.06 directly and let me know the consequence of this procedure on directly.

**Comment by zinid** [comment]
This is a bug tracker. What bugs do you have?

**Comment by sumesh048** [comment]
Please help me below issue of new version ejabberd 18.06.
we have configured in ejabberd 18.06 with old xmpphp framework. But presence function has not working while registering user from xmpphp framework.

**Comment by zinid** [comment]
So this is a bug in ejabberd? What should we fix? We don't fix xmpphp.

**Comment by zinid** [comment]
If you have a ejabberd related question please consider links listed at ejabberd.im
If you want upgraded ejabberd version, refer to [Upgrade Notes](https://docs.ejabberd.im/admin/upgrade/#note-on-database-schema-upgrade)
I close the issue.

**Comment by sumesh048** [comment]
but it will register the user from xmpphp with using the presence function. please help any issue with while disabling presence module from ejabberd 18.06.

And one help: Now we resolved the issue while disabling presence function.
But we need to migrate the old version mnesia backup and restore to new version 18.06. And old version we are using presence function. is there any issue while restoring db backup?
