### ISSUE TITLE
Stream closed by us: Replaced by new connection (conflict)

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2601]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

CentOS

> How did you install ejabberd (source, package, distribution)?

rpm file

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have ejabberd running on a CentOS machine. I have enabled the **mod_ping** module in the following way:
```
mod_ping:
    send_pings: true
    ping_interval: 30
    ping_ack_timeout: 900
    timeout_action: none
```
In order to ping the client every 30 seconds and wait for 900 seconds the response. The default action is none (I really don't want to kill the connection if I don't receive any response).

But I receive, **every 10 minutes**, the following action from ejabberd:

```
018-09-11 08:32:23.464 [info] <0.7225.0>@ejabberd_c2s:bind:403 (http_bind|<0.7224.0>) Opened c2s session for agent3@my_centos.net/euphonia
2018-09-11 08:32:23.465 [debug] <0.5845.0>@mod_pubsub:node_action:3580 node_action <<"pubsub.my_centos.net">> <<"flat">> get_entity_affiliations [<<"pubsub.my_centos.net">>,{<<"my_centos">>,<<"my_centos.net">>,<<"euphonia">>}]
2018-09-11 08:32:23.465 [debug] <0.5845.0>@mod_pubsub:node_call:3561 node_call <<"flat">> get_entity_affiliations [<<"pubsub.my_centos.net">>,{<<"my_centos">>,<<"my_centos.net">>,<<"euphonia">>}]
2018-09-11 08:32:23.465 [debug] <0.5845.0>@mod_pubsub:node_action:3580 node_action <<"pubsub.my_centos.net">> <<"pep">> get_entity_affiliations [<<"pubsub.my_centos.net">>,{<<"my_centos">>,<<"my_centos.net">>,<<"euphonia">>}]
2018-09-11 08:32:23.467 [debug] <0.5845.0>@mod_pubsub:node_call:3561 node_call <<"pep">> get_entity_affiliations [<<"pubsub.my_centos.net">>,{<<"my_centos">>,<<"my_centos.net">>,<<"euphonia">>}]
2018-09-11 08:32:23.467 [info] <0.5845.0>@ejabberd_c2s:process_terminated:271 (http_bind|<0.5844.0>) Closing c2s session for my_centos@my_centos.net/euphonia: Stream closed by us: Replaced by new connection (conflict)
2018-09-11 08:32:23.467 [debug] <0.5845.0>@mod_carboncopy:disable:263 disabling for <<"my_centos">>
```

the client connection is in a bosh connection:

```
port: 9090
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
    shaper: s2s_shaper
    web_admin: true
    http_bind: true
    captcha: false
```

and shaper s2s_shaper has a fast configuration like this:

```
shaper:

  normal: 1000

  fast: 50000
```

other configured modules:

```
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_blocking: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_configure: {}
  mod_bosh: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 30
    ping_ack_timeout: 900
    timeout_action: none
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
  mod_roster: {}
  mod_shared_roster: {}
  ## mod_stats: {}
  ## mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 1
    c2s_max_auth_failures: 1000
  mod_last: {}
```

Is a bug or there is something wrong in my configuration? Thanks for the help

**Comment by prefiks** [comment]
"Stream closed by us: Replaced by new connection (conflict)" is generated if another clients starts new session with same resource as existing client (since each client must have unique resource if new clients connects with resource that existing session already used, that old session will be terminated). There is no problem with your config or actions that server does, it works as expected.

**Comment by bp91** [comment]
@prefiks hi and thanks for the answer. I've understood the problem, but seems that the client (using Strophe library) couldn't keep the bosh connection (I don't know if it's for a network problem). And really this problem happens every 10 minutes

**Comment by prefiks** [comment]
Without client traffic log it's hard to tell what's happening here, as you see per server session is still alive (that why you get conflict, if session was terminated there would be no such message) so there must be some reason in client why it start new session instead of keeping using old one.
