### ISSUE TITLE
How to login a user using mod_http_api

### ISSUE THREAD

**Issue by CreativeWolf** [processone/ejabberd#2609]
> What version of ejabberd are you using?

ejabberd 18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to understand how to log in a user using mod_http_api

Appreciate any help please.

Thanks!

**Comment by badlop** [comment]
mod_http_api allows to execute commands. You can see the list of commands running this in a shell:
```
ejabberdctl help --tags
```
You can register new accounts, see statistics, perform administrative tasks... using ejabberdctl, or using mod_http_api, or using ejabberd_xmlrpc... Those modules are not used to login to a XMPP account.

**Comment by CreativeWolf** [comment]
@badlop Thanks for that!

What'd you recommend for logging in a user? (I'm trying to do this from a web application).

Appreciate any pointers towards achieving this please.

Thanks!

**Comment by badlop** [comment]
Use a library for writting a simple xmpp client in the language of your web application. See in https://xmpp.org/software/libraries.html or search for it.

**Comment by CreativeWolf** [comment]
@badlop Thanks, couldn't find any library for PHP in that list.

However, found a XMPP Protocol Connection wrapper for PHP which is connecting to the server using TCP `tcp://myejabberdserver.test:5222`

Is that the proper way to connect to ejabberd or would you recommend some other way?

Appreciate your inputs.

Thanks!

**Comment by badlop** [comment]
Looks good.
