### ISSUE TITLE
ejabberd crash: stun.app

### ISSUE THREAD

**Issue by blinux45** [processone/ejabberd#2610]
> What version of ejabberd are you using?
v16.09-4

> What operating system (version) are you using?

Debian 9 Stretch

> How did you install ejabberd (source, package, distribution)?

Distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I installed ejabberd v16.09-4 on Debian Stretch from the repository
# apt-get install ejabberd

I enabled stun by uncommenting the following
-
port: 4478
transport: udp
module: ejabberd_stun

Now ejabberd crashes.
When looking at the logs, I get:
failed to start application 'stun': {error;
{"no such file or directory","stun.app"}}

What is wrong?

**Comment by zinid** [comment]
1) Too old ejabberd version
2) The package was not compiled with STUN support

I close the issue.
