### ISSUE TITLE
mod_block_strangers drops messages coming from transports regardless of "allow_transports" setting

### ISSUE THREAD

**Issue by sicherha** [processone/ejabberd#2613]
> What version of ejabberd are you using?

18.06

> What operating system (version) are you using?

Debian Stretch

> How did you install ejabberd (source, package, distribution)?

Debian Backports package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Incoming queries from IRC users arriving from my Biboumi transport are dropped even though messages originating from transports are supposed to pass. The log indicates that mod_block_strangers is to blame.

The relevant line in my ejabberd.yml:
`mod_block_strangers: {}`
According to the documentation, the `allow_transports` option is enabled by default. The behaviour does not change if I explicitly set `allow_transports: true`.

As a workaround, disabling mod_block_strangers fixes the issue for me.

**Comment by zinid** [comment]
You should have a transport JID in the roster, do you have it?

**Comment by sicherha** [comment]
I have a JID `irc.fau.de@biboumi.example.org` in my roster and the incoming messages are from `ircuser%irc.fau.de@biboumi.example.org`. Nominally that should be sufficient, shouldn't it?

**Comment by zinid** [comment]
No, it's not. Add `biboumi.example.org` to your roster if it's possible.

**Comment by sicherha** [comment]
Thanks! That did the trick.
