### ISSUE TITLE
Feature Request: Convert between PEP and private XML bookmarks

### ISSUE THREAD

**Issue by Natureshadow** [processone/ejabberd#2619]
Although the XEP is only a draft, I would like to ask for the implementation of bookmark conversion:

https://github.com/xsf/xeps/blob/master/inbox/bookmarks-conversion.xml

This way, clients implementing the different storage protocols can all use the same bookmarks.

**Comment by zinid** [comment]
Fixed in 1cdca1ab99c8a0dfd7cab8a760a65840067bea16
