### ISSUE TITLE
There is no easy way to unban IPs banned by mod_fail2ban

### ISSUE THREAD

**Issue by madmalkav** [processone/ejabberd#2620]
Environment
-----------
- ejabberd version: 18.06
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 9.3.1
- OS: Linux (SLES 12)
- Installed from: source

Bug description
---------------
Currently there is no easy way to unban an IP  banned by mod_fail2ban list.

**Comment by zinid** [comment]
For anyone who takes this: the supposed ejabberd command should accept an IP address (possibly with network mask, optionally), parse it and remove from `failed_auth` ETS table. The table is just a simple mapping `IP => foo` where `foo` doesn't matter for the command.
