### ISSUE TITLE
Unknown listening option websocket_timeout use_turn turn_ip

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#2621]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: OTP 21
- OS: Debian GNU/Linux 9 (stretch)
- Installed from: source
----------------------------------------------------------------------------

> Unknown listening option 'turn_ip' of module ejabberd_stun; available options are: ip, supervisor, shaper, tls, turn_max_allocations, turn_max_permissions, port, transport, inet, turn_min_port, turn_max_port, module, auth_type, certfile, server_name, inet6, backlog, accept_interval, auth_realm
> 2018-09-28 23:20:27.914 [error] <0.81.0>@ejabberd_config:validate_opts:1087 Invalid value for option 'listen'
> Unknown listening option 'use_turn' of module ejabberd_stun; available options are: ip, supervisor, shaper, tls, turn_max_allocations, turn_max_permissions, port, transport, inet, turn_min_port, turn_max_port, module, auth_type, certfile, server_name, inet6, backlog, accept_interval, auth_realm
> 2018-09-28 23:18:44.532 [error] <0.81.0>@ejabberd_config:validate_opts:1087 Invalid value for option 'listen'
> Unknown listening option 'websocket_timeout' of module ejabberd_http; available options are: ip, captcha, supervisor, register, ciphers, protocol_options, tls, xmlrpc, request_handlers, custom_headers, port, transport, inet, http_bind, default_host, module, certfile, dhfile, cafile, inet6, backlog, accept_interval, tls_compression, web_admin
> 2018-09-28 23:14:14.317 [error] <0.81.0>@ejabberd_config:validate_opts:1087 Invalid value for option 'listen'

---------------
Nothing works, plz halp :(

**Comment by zinid** [comment]
Damn, that's my fault

**Comment by suchatorg** [comment]
websocket_timeout

**Comment by zinid** [comment]
`websocket_timeout` is a top-level option, that was actually a bug in the documentation or maybe in the implementation, whatever.

**Comment by zinid** [comment]
Here it is: https://github.com/processone/ejabberd/blob/master/src/ejabberd_http_ws.erl#L140

**Comment by suchatorg** [comment]
Thank you very much for the clarification
