### ISSUE TITLE
crash / websocket closed unexpectedly

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#2624]
Environment
-----------
- ejabberd version: 17.07
- OS: Linux (Debian)
- Installed from: official deb/rpm
- Database: mysql

Bug description
---------------
We store all massages in the archive table (mysql) so the messenger can be used cross platform.
We have a user with a lot of chatrooms  89 (29 1-on-1 / 60 group-chats)

And very often fetching the chatrooms crashes. Users of our medical application start to complain so solving this is high priority for us!

The errorlog shows
```
2018-10-04 09:52:19.247 [error] <0.3392.0> CRASH REPORT Process <0.3392.0> with 0 neighbours exited with reason: {process_limit,{max_queue,1025}} in p1_server:terminate/7 line 864
2018-10-04 09:52:19.247 [error] <0.1397.0> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.3392.0> exit with reason {process_limit,{max_queue,1025}} in context child_terminated
```

And the crashlog
```
2018-10-04 09:52:19 =CRASH REPORT====
  crasher:
    initial call: xmpp_stream_in:init/1
    pid: <0.3392.0>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1025}},[{p1_server,terminate,7,[{file,"src/p1_server.erl"},{line,864}]},{p1_server,loop,9,[{file,"src/p1_server.erl"},{line,412}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.66.0>]
    messages: []
    links: [<0.1397.0>]
    dictionary: [{'$internal_queue_len',974},{already_terminated,true}]
    trap_exit: false
    status: running
    heap_size: 833026
    stack_size: 27
    reductions: 701926
  neighbours:
2018-10-04 09:52:19 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_c2s_sup}
     Context:    child_terminated
     Reason:     {process_limit,{max_queue,1025}}
     Offender:   [{pid,<0.3392.0>},{id,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

I really hope you can help me out

**Comment by licaon-kter** [comment]
How big is your [max_fsm_queue](https://docs.ejabberd.im/admin/configuration/#options) ? Try to make it bigger...

> We store all massages in the archive table (mysql) so the messenger can be used cross platform.

I don't understand what the database provider has to do with cross platform clients.

**Comment by PH-F** [comment]
It was on 1000 (default i guess) I increased it to 2500
I hope this will fix the problem.

**Comment by zinid** [comment]
In recent ejabberd versions the default value is 5000.

**Comment by PH-F** [comment]
Then i'll increase it to 5000 !

**Comment by PH-F** [comment]
Thx for your help it looks like the problem is fixed.
