### ISSUE TITLE
mod_offline not working with mod_mam active and ldap authentication

### ISSUE THREAD

**Issue by vcarro** [processone/ejabberd#2625]
Environment
-----------
- ejabberd version: 18.06
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1
- OS: Linux Debian 9.5
- Installed from: source

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
---------------
When a user sends a message to another user not connected (offline) and mod_mam es active with ldap authentication configured, the messages are not save to offline_msg.dat table. If run:

    ejabberdctl dump_table offline_msg.txt offline_msg

The result is:

    {tables,[{offline_msg,[{record_name,offline_msg},
                           {attributes,[us,timestamp,expire,from,to,packet]}]}]}.

Without any messages.

If I delete the **mod_mam** configuration in **ejabberd.yml** file, messages are saved in offline_msg.dat.
If I change

    case ejabberd_auth:user_exists(LUser, LServer) andalso

for

    case ejabberd_auth_ldap:user_exists(LUser, LServer) andalso

inside of

    route_message(#message{to = To, type = Type} = Packet) ->

function at **ejabberd_sm.erl** file, is working too.

**Comment by prefiks** [comment]
Hello,

Could you tell me more about usernames that you are using?

Normally ejabberd_auth:user_exists will call ejabberd_auth_ldap:user_exists if you defined ldap as auth scheme to use, only difference that this code change introduces that i can think of, is that it skip username normalization step (it will convert all uppercase letters to lower case, and do combine some unicode codepoints together). Do username that you use have uppercase letters in them or use letters outside latin? Possibly ldap is not able to recognize them after that normalization.

**Comment by cultcom** [comment]
We have a similar issue, mod_offline is enabled but when I try to send to offline contacts I always receive a "code 503" error from pidgin.
We authenticate against ldap as well but I do not really know how to debug this further.

**Comment by zinid** [comment]
Just don't use Pidgin, please.

**Comment by cultcom** [comment]
wow that's helping a lot. And that's what I tell the other users as well I guess ...

**Comment by zinid** [comment]
And what did you expect? That's a Pidgin UI bug. And since XMPP support in Pidgin is abandoned it will never be fixed.
Here is a recent discussion: https://mail.jabber.org/pipermail/standards/2019-June/036141.html (this time Poezio).

**Comment by cultcom** [comment]
That was an answer I would have expected. Sorry I was not aware that pidgin abandoned xmpp support. I will try another client and see what happens. Thank you.

**Comment by badlop** [comment]
No news in this ticket for two months, I guess it's either solved or isn't relevant anymore.
