### ISSUE TITLE
Stream management protocol responds to the first acknowledgement request only

### ISSUE THREAD

**Issue by ralzohairi** [processone/ejabberd#2628]
Environment
-----------
- ejabberd version: 18.06 & 18.09.
- OS: MacOS Sierra (10.12.3)
- Installed from: installer package

Configuration:  ejabberd.yml
---------------------------------------------------------------------------
```yaml
...
mod_stream_mgmt: {}
...
```

Errors from error.log/crash.log
-------------------------------
I don't see any errors regarding this issue.

Bug description
---------------

I’m working with the stream management protocol (mod_stream_mgmt in jabbered).

I managed to enable the stream management successfully after user connects to the server.

When I make my first request for an acknowledgment (using r element), I receive an acknowledgment back successfully.

However, after the first request, if I make any other request for an acknowledgment, I don’t get anything back from the server.

So, it only responds to the first acknowledgement request.

There is also a weird behavior of it disconnecting after a while for the reason of enabling the stream management.

I'm not sure what the problem is to be honest, especially that I made sure stream management is enabled and I do in fact receive a single acknowledgment only one time.

**Comment by weiss** [comment]
As it works with all popular standard clients I'm aware of, I would assume some client-side error, but without seeing the stream, we can't tell of course.

If I connect to an 18.09 instance using Gajim and open the XML console, I can send `<r xmlns='urn:xmpp:sm:3'/>` as much as I want and always get responses.
