### ISSUE TITLE
Feature request: implement XEP-0410: MUC Self-Ping optimization

### ISSUE THREAD

**Issue by ge0rg** [processone/ejabberd#2630]
It would be great to have a server-side implementation of the round-trip optimization outlined in https://xmpp.org/extensions/xep-0410.html#serveroptimization :

> The normal routing rules of the self-ping impose two round-trips: first the initial ping from the client to the MUC, then the reflection of the ping and its response (possibly to another client), and finally the response to the initial IQ. If the other client is experiencing network connectivity issues, which is often the case with mobile devices, the ping request might never be responded to.

> Therefore, a MUC service supporting this protocol may directly respond to a participant's Ping request to the participant's own nickname, as opposed to routing it to any of the participant's clients.

This should be a rather straight-forward thing to add to the MUC code. Example implementation from prosody is at https://issues.prosody.im/1220#comment-2

**Comment by zinid** [comment]
> Example implementation from prosody

Nice trolling.
