### ISSUE TITLE
Cannot access API with browser show not found

### ISSUE THREAD

**Issue by ilhammalik** [processone/ejabberd#2633]
i'm access 5280/api/register not found but i have configuration 

Configure http_mod_api : 

cd /opt/ejabberd-16.09/conf
sudo vi ejabberd.yml

Locate Port: 5280 and update following

 request_handler:
   "/websocket": ejabberd_http_ws
   "/api": mod_http_api

modules:
  mod_http_api:
    admin_ip_access: admin_ip_access_rule

access:
  admin_ip_access_rule:
   admin_ip_acl:
    - change password
    - add_rosteritem
    - register
    - delete_rosteritem
    - send_message

acl:
  admin_ip_acl:
    ip:
     - "x.x.x.x/8"

**Comment by prefiks** [comment]
What error are you getting exactly? JSON payload with Endpoint not found or something else? Also you can simplify your configuration by tweaking api_permissions:
```
api_permisions:
  "ip access":
    who:
      - access:
        - allow:
          - ip: "1.1.1.1/8"
    what:
      - register
     ....
```
