### ISSUE TITLE
Log in JSON format

### ISSUE THREAD

**Issue by yhaskell** [processone/ejabberd#2637]
Environment
-----------
- ejabberd version: 18.04
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 9.1.5`
- OS: Linux (Kubernetes)
- Installed from: `ejabberd/ecs` docker image

Hello.

Is there a way to somehow make ejabberd log in JSON?
Something like `{ "timestamp": "timestamp", "level": "info", message: "message" }` is what I would like to somehow get.

Thanks!

**Comment by cromain** [comment]
there are no plans for structured logging for now

**Comment by yhaskell** [comment]
Would you maybe accept PRs for that?)

**Comment by zinid** [comment]
@yhaskell I personally have objections. I don't find JSON a good format for storing data. For example, journald is a much better fit.

**Comment by yhaskell** [comment]
@zinid It is very good format if you for example want to export your logs to elasticsearch :) 

I think cleaner solution would be to add a possibility to set lager formatter from config. 
Default config would be to use lager_default_formatter, and if someone wants different formatter, he could just change formatter to whatever he prefers.

**Comment by zinid** [comment]
> It is very good format if you for example want to export your logs to elasticsearch :)

No, this only reflects modern IT degradation.

> Default config would be to use lager_default_formatter, and if someone wants different formatter, he could just change formatter to whatever he prefers.

Sounds okay to me.
