### ISSUE TITLE
Need help on Push Notifications

### ISSUE THREAD

**Issue by ismailmohammed** [processone/ejabberd#2641]
Environment
-----------
- ejabberd version: 18.01
- OS: Windows
- Installed from: https://www.process-one.net/en/ejabberd/downloads/

Need help on Push Notifications.
I am able to get online messages to 1-1 and Group Chat but when a user is offline from a group or for 1-1 then I user should get the offline notifications.

I have added one module for a workaround but I am able to get only 1-1 notifications. which will call a web API which I have written from that Web API using FCM notification will be pushed to users. 
From some sources, I read that with 18.09 we can get push notifications to Mobile without any modules. Please help me on this where we need to configure this.

Thanks in advance.
Regards,
Md.Ismail.

**Comment by licaon-kter** [comment]
The config template offers a complete setup covering push too: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

Try it with 18.09 ;)

**Comment by weiss** [comment]
As I told you [before][1], you have two options (besides modifying ejabberd, e.g. to let groups generate notifications directly):

1. If you're developing a custom client, you can use the non-standard [MUC/Sub][2] extension.
2. For standard clients, the [`mod_push_keepalive`][3] module tries to work around the issue by keeping the [stream management][4] session online.  This will only work if the client does _not_ close the XMPP stream before closing the TCP connection.

[1]: https://github.com/processone/ejabberd/issues/697#issuecomment-426950083
[2]: https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/
[3]: https://docs.ejabberd.im/admin/configuration/#mod-push-keepalive
[4]: https://xmpp.org/extensions/xep-0198.html

**Comment by ismailmohammed** [comment]
Thanks for your quick replay,

I have enabled Mod_push_keepalive below is my config file code for this.

> mod_push:
>     include_sender: true
>     include_body: true
>   mod_push_keepalive:
>     resume_timeout: 259200
>     wake_on_start: false
>     wake_on_timeout: true

I am using JSXC for my Web application when I sent offline message to apple user in response I received below stanza.

<body xmlns="http://jabber.org/protocol/httpbind"><message xmlns="jabber:client" xml:lang="en" to="ismail@konnectz.com/20344326581792388601186" from="pavan@konnectz.com" type="error"><paused xmlns="http://jabber.org/protocol/chatstates"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">User session not found</text></error></message></body>

Thanks in advance,
Regards,
Md.Ismail.

**Comment by weiss** [comment]
Seems the iOS client added this element to the `<enable/>` IQ:

```
<delay xmlns=“urn:xmpp:delay” stamp=“2018-10-24T06:34:54Z”>Retransmission</delay>
```

As [per the RFC][1], this is not permitted for IQ stanzas:

> An IQ stanza of type "get" or "set" MUST contain exactly one child element [...].

So ejabberd returns the "Too many child elements" error and doesn't enable push notifications.

[1]: https://tools.ietf.org/html/rfc6120#section-8.2.3

**Comment by ismailmohammed** [comment]
Hi,

They didn't add this `<delay xmlns=“urn:xmpp:delay” stamp=“2018-10-24T06:34:54Z”>Retransmission</delay> `to <enable/> IQ but in response, we are getting this.
below is the request IQ which they are sending.

`<enable xmlns="urn:xmpp:push:0" jid="admin@konnectz.com" node="40AFC2A6-DD77-47C9-A38D-7417BAEC16DA"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="device_id"><value>a8dd51cff0f861da1c106a9e81f253951d06b100a4833396f5e274e0fde01082</value></field><field var="topic"><value>com.audlink.KConnect</value></field><field var="service"><value>apns</value></field><field var="mode"><value>prod</value></field></x></enable>`

Thanks,
Md.Ismail.

**Comment by weiss** [comment]
> They didn't add this `<delay xmlns=“urn:xmpp:delay” stamp=“2018-10-24T06:34:54Z”>Retransmission</delay>` to IQ

Maybe their library did, I don't know.  Either way, it's what ejabberd received and the reason it rejected the IQ.

**Comment by ismailmohammed** [comment]
Hi,
If you don't please let me know the steps which should follow for push notifications server side and client side. as I am new to it please help me.

1. I have installed ejabbered 18.09
2. Ejabbered Yml file changed as per this `https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example`
 
what else we need to do from the server side? and what from the client side?

please don't be angry with my questions :)

Regards,
Md.Ismail
