### ISSUE TITLE
Ejabberd crashes after a while with too many open files error

### ISSUE THREAD

**Issue by pooyarm** [processone/ejabberd#2643]
Environment
-----------
- ejabberd version: 17.04
- Erlang version: 5.8.5
- OS: CentOS 6.7
- Installed from: don't know exactly

Bug description
---------------
We are using Ejabbered (v17.0.4) as a chat server. Recently, we have moved our data center physically and consequently turned the servers off. After migration and running the servers we encountered the following error:

> <0.322.0>@ejabberd_listener: accept :320 (#Port<0.20269>) Failed TCP accept: too many open files

When we try to check the list of open files on the server, it shows that the number of open files are increasing quickly. for example:

```sh
lsof | wc -l
250
```
after 5 minutes it increases to:

```sh
lsof | wc -l
1100
```
The server is stopped when the number of open files reaches at ~32000 and Ejabbered cannot be started again unless the server is rebooted. However, the server config has not been changed and everything are the same as before migration.

Also we got the following error from logs/error.log:

> 2018-10-24 09:42:23.197 [error] <0.2317.1> CRASH REPORT Process <0.2317.1> with 0 neighbours exited with reason: {process_limit,{max_queue,1002}} in p1_server:terminate/7 line 864
> 2018-10-24 09:42:23.197 [error] <0.493.0> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.2317.1> exit with reason {process_limit,{max_queue,1002}} in context child_terminated

Any idea how to resolve this issue?

**Comment by licaon-kter** [comment]
/duplicate https://github.com/processone/ejabberd/issues/2624 ?

**Comment by zinid** [comment]
@licaon-kter no, but this bug has been fixed in 17.06 or so. That's why we insist on reporting bugs of recent version only.

**Comment by pooyarm** [comment]
@zinid thanks for your reply, I'm just wondering why this was working correctly before, it was ok for about 2 years before we moved the machine to a new datacenter. I'm also trying to upgrade to 17.06.

**Comment by licaon-kter** [comment]
@pooyarm if you upgrade why not 18.09?

**Comment by licaon-kter** [comment]
@pooyarm that is why you use test machines first...right?

**Comment by pooyarm** [comment]
@licaon-kter actually this was our production machine for more than 2 years and worked perfectly, but recently dev ops guys moved the machine to a new datacenter, nothing has changed on the machine but we have this problem on our new environment.
also wanted to mention that when I run lsof command I see lot's of sockets regarding ejabberd with status "can't identify protocols"

**Comment by weiss** [comment]
> since this is the production server I want to fix this problem with least changes so we can plan on big upgrade to latest version in future.

That strategy might make sense for you, but if you run into problems with that, this bug tracker is not the right place to get help.

**Comment by pooyarm** [comment]
> > since this is the production server I want to fix this problem with least changes so we can plan on big upgrade to latest version in future.
> 
> That strategy might make sense for you, but if you run into problems with that, this bug tracker is not the right place to get help.

I just realized that there is not any support for old versions when zinid said that and I just said "ok thank you" and left the thread, after that licaon-kter asked question and I answered that, and as you see this issue has already closed so I need to say "Yes Sir, sorry for this post"

**Comment by hamidgh83** [comment]
Is there any update on Ejabberd Rest API If we want to switch from version 17.04 to the latest version (18.09)? We have used [this library](https://github.com/fabiang/xmpp) to connect to ejabberd server. I want to know if there might be any changes in our code after migrating to the latest ejabberd version!?
