### ISSUE TITLE
tried deleting the roster using the below command:

### ISSUE THREAD

**Issue by sunstar20** [processone/ejabberd#2646]
./ejabberdctl process_rosteritems delete any any *@localhost *@localhost but its not deleting the roster and also getting the below message

There are 32 roster items in total.
Progress 3% - visited 1 - deleted 0
Progress 6% - visited 2 - deleted 0
Progress 9% - visited 3 - deleted 0
Progress 12% - visited 4 - deleted 0
Progress 15% - visited 5 - deleted 0
Progress 18% - visited 6 - deleted 0
Progress 21% - visited 7 - deleted 0
Progress 25% - visited 8 - deleted 0
Progress 28% - visited 9 - deleted 0
Progress 31% - visited 10 - deleted 0
Progress 34% - visited 11 - deleted 0
Progress 37% - visited 12 - deleted 0
Progress 40% - visited 13 - deleted 0
Progress 43% - visited 14 - deleted 0
Progress 46% - visited 15 - deleted 0
Progress 50% - visited 16 - deleted 0
Progress 53% - visited 17 - deleted 0
Progress 56% - visited 18 - deleted 0
Progress 59% - visited 19 - deleted 0
Progress 62% - visited 20 - deleted 0
Progress 65% - visited 21 - deleted 0
Progress 68% - visited 22 - deleted 0
Progress 71% - visited 23 - deleted 0
Progress 75% - visited 24 - deleted 0
Progress 78% - visited 25 - deleted 0
Progress 81% - visited 26 - deleted 0
Progress 84% - visited 27 - deleted 0
Progress 87% - visited 28 - deleted 0
Progress 90% - visited 29 - deleted 0
Progress 93% - visited 30 - deleted 0
Progress 96% - visited 31 - deleted 0
Progress 100% - visited 32 - deleted 0

Kindly help

Related question posted earlier: https://github.com/processone/ejabberd/issues/2368

_Originally posted by @sunstar20 in https://github.com/processone/ejabberd/issue_comments#issuecomment-432930898_

**Comment by badlop** [comment]
And what roster items do you expect it should delete?

I ask for this reason: In my test server I have two vhosts: localhost and example1.org, with rosteritems only in example1.org. I get a response similar to you when I ask for localhost, because the rosteritems are in the other vhost, see:

```
$ ejabberdctl process_rosteritems list any any *@localhost *@*
There are 2 roster items in total.
Progress 50% - visited 1 - deleted 0
Progress 100% - visited 2 - deleted 0

$ ejabberdctl process_rosteritems list any any *@example1.org *@*
There are 2 roster items in total.
Matches: user2@example1.org user1@example1.org
Progress 50% - visited 1 - deleted 1
Matches: user1@example1.org user2@example1.org
Progress 100% - visited 2 - deleted 2
user1@example1.org      user2@example1.org
user2@example1.org      user1@example1.org
```

**Comment by sunstar20** [comment]
I just have a single vhost.

![image](https://user-images.githubusercontent.com/12511931/47696506-13e1bc00-dc2d-11e8-9397-3c9829ecfa11.png)

**Comment by badlop** [comment]
Well, then think what kind of roster items you have, and what filter will catch them... I am not the admin of your server. Maybe this is your case?

```
$ ejabberdctl process_rosteritems list any any *@localhost *@localhost
There are 1 roster items in total.
Progress 100% - visited 1 - deleted 0
```

Try to list all the roster items:
```
$ ejabberdctl process_rosteritems list any any *@* *@*
There are 1 roster items in total.
Matches: user1@localhost user4@example1.org
Progress 100% - visited 1 - deleted 1
user1@localhost user4@example1.org
```
