### ISSUE TITLE
erlc is giving the following error "init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})"

### ISSUE THREAD

**Issue by jayakishorereddy** [processone/ejabberd#2648]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
loglevel: 4
...
```

/opt/ejabberd-18.09/bin/erlc -I /opt/ejabberd-18.09/lib/ejabberd-18.09/include/ -I /opt/ejabberd-18.09/lib/xmpp-1.2.5/include/ -I /opt/ejabberd-18.09/lib/fast_xml-1.1.34/include/  mod_yellow_log.erl

{"init terminating in do_boot",{'cannot get bootfile','no_dot_erlang.boot'}}
init terminating in do_boot ({cannot get bootfile,no_dot_erlang.boot})

Crash dump is being written to: erl_crash.dump...done

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
---------------
Nothing works, plz halp :(

**Comment by deniswisedeniswise** [comment]
Same bug. Happens when you attempt to compile a module using erlc directly

**Comment by prefiks** [comment]
Is that erlc returning that error or that happens when you use module compiled that way?

If it's problem with executing erlc, you probably could try to start .../bin/erl with those flags and executing c(mod_yellow_log) and see if that compiles that file

**Comment by deniswisedeniswise** [comment]
@prefiks , thanks.
@jayakishorereddy 
go to ejabberd bin folder and start erl.exe

1. change directory to your module directory by typing this into the erlang shell. Note that the path must use forward slashes.
`cd("c:/erlang/myspecialmoduledirectory").`
2. compile using the erlang shell command c, but specify include directory ie 
`c(mod_yellow_log,[{ i, "c:/program files/ejabberd-18.09/lib/ejabberd-18.09/include"}]).`

**Comment by cromain** [comment]
erlc should work out of the box, i'll double check this

**Comment by cromain** [comment]
adding no_dot_erlang.boot in bin directory fixes use of erlc. it will be included in next installer.
