### ISSUE TITLE
mod_privacy race condition

### ISSUE THREAD

**Issue by nbruning** [processone/ejabberd#2652]
Environment
-----------
- ejabberd version: 18.06
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 9.3.3
- OS: Linux (Ubuntu)
- Installed from: official binary installer

Bug description
---------------

When changing the active privacy list using XEP-0016, the change is not affected immediately. Any queued packets are processed using the old (or without any) privacy list.

Details: https://github.com/processone/ejabberd/pull/2651

**Comment by cromain** [comment]
I scheduled the PR so we can close this issue to avoid duplicate. Thanks for the report.
