### ISSUE TITLE
remove msg history failed?

### ISSUE THREAD

**Issue by lemon2015** [processone/ejabberd#2654]
Environment
-----------
- ejabberd version: 18.01
- Erlang version: `erl +V`
- OS: Linux (CentOS 7)
- Installed from: source | distro package | official deb/rpm | official binary installer | other
official binary installer
Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
```yaml
loglevel: 4
...
```

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
Hi, I want delete one of the room message ,so the members will not see it again. 
But ,when I delete the message data from  mysql archive table directly,  next time,
the members could still see it. I disabled the muc room cache ,it still not worked. is it just copy to 
database or somewhere?
What should I do to keep the message rsync with database ? 
---------------
Nothing works, plz halp :(

**Comment by licaon-kter** [comment]
So a new user joining the room sees all the old messages?

**Comment by lemon2015** [comment]
> So a new user joining t

No,the new user can't see the old message,but anyone who has joined the room can still see the deleted message. That's where I am confused,I don't want anyone to see the deleted message.Can it be implemented by modifying the configuration?

Here is my config:

` ## XEP-0313: Message Archive Management
  ## You might want to setup a SQL backend for MAM because the mnesia database is
  ## limited to 2GB which might be exceeded on large servers
  ## mod_mam: {} # for xep0313, mnesia is limited to 2GB, better use an SQL backend
  mod_mam:
    iqdisc: one_queue
    db_type: sql
    default: always
    request_activates_archiving: false
    assume_mam_usage: false
    use_cache: false
    ## cache_size: 1000
    ## cache_life_time: 3600
  mod_muc:
    db_type: sql
    host: "conference.@HOST@"
    history_size: 20
    default_room_options:
      mam: true
      logging: true
      persistent: false
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create`

**Comment by licaon-kter** [comment]
The old users already downloaded the old messages, there's no way to "delete messages from THEIR devices".

Try to flush MAM history too, but the above statement still stands.

/close an invalid

**Comment by lemon2015** [comment]
> The old users already downloaded the old messages, there's no way to "delete messages from THEIR devices".
> 
> Try to flush MAM history too, but the above statement still stands.
> 
> /close an invalid

thinks
