### ISSUE TITLE
When registering a new user other users will not get their PEP information on subscribing to other users.

### ISSUE THREAD

**Issue by egoodwinx** [processone/ejabberd#2660]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.3`
- OS: Windows 10
- Installed from: official binary installer 

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
---------------
1. Register a new user
2. Send my presence out, no one is subscribed 
3. Subscribe to other users, my presence is not sent therefore my caps are not sent out
4. I am not subscribed to others PEP events until I log off/on again since my presence is sent out again.

**Comment by licaon-kter** [comment]
Client? Logs?

**Comment by egoodwinx** [comment]
Sorry. I have a bunch of comments in mine so I regex removed comments/empty lines.
https://gist.github.com/egoodwinx/f88fa7a47a85036fa9ff90e3ca266a97

**Comment by licaon-kter** [comment]
Can you repro with another client? Conversations? Dino? Gajim?

**Comment by egoodwinx** [comment]
I have no idea. I have been trying to make Gajim work but am unsure how to connect to my server.

**Comment by badlop** [comment]
Without more information to reproduce the problem, it cannot be solved.
