### ISSUE TITLE
Include the disco#info feature in a MUC’s disco#info result

### ISSUE THREAD

**Issue by linkmauve** [processone/ejabberd#2661]
Environment
-----------
- ejabberd version: probably 18.09
- Erlang version: probably not important
- OS: probably not important
- Installed from: probably not important

Bug description
---------------
When I send a disco#info query to a MUC hosted on Ejabberd, it doesn’t include the `http://jabber.org/protocol/disco#info` feature, despite XEP-0030 section 3.1 saying:
> Note: Every entity MUST […] support at least the 'http://jabber.org/protocol/disco#info' feature

This isn’t an issue on Ejabberd’s user domain or MUC domain, but you should check that you include this feature on every single JID from which you support disco#info.

**Comment by badlop** [comment]
The implementation follows https://xmpp.org/extensions/xep-0045.html#disco-roominfo which apparently contradicts that XEP-0030 sentence and its example. Until this is clarified, I think it's better not to touch the code.

**Comment by Flowdalic** [comment]
I don't see a contradiction, only a faulty example in XEP-0045.  And examples are considered non-normative. I can't find any normative text in XEP-0045 which forbids the inclusion of the `disco#info` feature. I've created https://github.com/xsf/xeps/pull/715 to fix the faulty example.

**Comment by horazont** [comment]
IMO, the example in XEP-0045 is faulty. XEP-0030 is rather clear in that the feature must be announced. Thanks @Flowdalic for the PR against XEP-0045.
