### ISSUE TITLE
offline messages not working with mod_mam enabled for some users

### ISSUE THREAD

**Issue by froghorn82** [processone/ejabberd#2662]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.1.1
- OS: Linux (Debian)
- Installed from: official binary installer

Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
---------------------------------------------------------------------------
loglevel: 1
log_rotate_size: 0
log_rotate_date: ""
log_rate_limit: 100
hosts:
  - "domain.im"
certfiles:
  - "/opt/ejabberd-18.09/conf/ejabberd.pem"
ca_file: "/opt/ejabberd-18.09/conf/cacert.pem"
define_macro:
    'TLS_OPTIONS':
      - "no_sslv2"
      - "no_sslv3"
    'TLS_CIPHERS': "ECDH:!DH:!CAMELLIA128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM"
    'DH_FILE': "/opt/ejabberd-18.09/conf/dhparams.pem" # generated with: openssl dhparam -out dhparams.pem 2048
c2s_dhfile: 'DH_FILE'
s2s_dhfile: 'DH_FILE'
c2s_ciphers: 'TLS_CIPHERS'
s2s_ciphers: 'TLS_CIPHERS'
c2s_protocol_options: 'TLS_OPTIONS'
s2s_protocol_options: 'TLS_OPTIONS'
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    protocol_options: 'TLS_OPTIONS'
    dhfile: 'DH_FILE'
    ciphers: 'TLS_CIPHERS'
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
      "/api": mod_http_api
    web_admin: true
    captcha: true
    tls: true
  -
    port: 5223
    ip: "::"
    module: ejabberd_c2s
    tls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5444
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "": mod_http_upload
    tls: true
    protocol_options: 'TLS_OPTIONS'
    dhfile: 'DH_FILE'
    ciphers: 'TLS_CIPHERS'
s2s_use_starttls: optional
auth_method: internal
auth_password_format: scram
shaper:
  normal: 20000
  fast: 500000
max_fsm_queue: 10000
acl:
  admin:
    user:
      - "admin@domain.im"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: all
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
registration_timeout: infinity
  
language: "en"
captcha_cmd: "/opt/ejabberd-18.09/lib/ejabberd-18.09/priv/bin/captcha.sh"
captcha_host: "domain.im:5280"
captcha_limit: 5
acme:
   contact: "mailto:admin@domain.im"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco:
    server_info:
      -
        modules: all
        name: "abuse-addresses"
        urls: ["mailto:abuse@domain.im"]
  mod_bosh: {}
  mod_http_upload:
    docroot: "@HOME@/upload"
    put_url: "https://@HOST@:5444"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS, DELETE"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
  mod_http_upload_quota:
    max_days: 30
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    default_room_options:
      allow_subscription: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping:
    send_pings: true
    ping_interval: 30
    ping_ack_timeout: 5
    timeout_action: kill
  mod_privacy: {}
  mod_private: {}
  mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep" # pep requires mod_caps
    force_node_config:
      "storage:bookmarks":
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    captcha_protected: true
    welcome_message:
      subject: "Welcome!"
      body: |-
        Hello there!
        Welcome to omemo.im. Your open source, secure & free community XMPP chat server.
        Please respect our service policy and enjoy chatting!
        omemo.im
    registration_watchers:
        - "watch@domain.im"
    ip_access: trusted_network
    access: register
  mod_roster:
    versioning: true
    use_cache: true
    store_current_id: true
  mod_shared_roster: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 10
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
allow_contrib_modules: true

Errors from error.log/crash.log
-------------------------------
No errors

Bug description
---------------
When mod_mam is enabled and ejabberdctl restarted, users that disconnected and have been sent messages during their offline period do not receive them when they reconnect, those messages are lost.

Stream management is enabled and neither do those messages that are sent to the user during the period resend_on_timeout: true (10 sec) arrive nor do the ones after this period (if user didn't reconnect after 10sec) that are supposedly archived into offline messages arrive. This appears to happen to older user accounts whereas newly registered users seem to work for some reason.

similar to post: https://github.com/processone/ejabberd/issues/2625

What could be the cause?

**Comment by licaon-kter** [comment]
See the docs, but don't use `store_current_id: true` with `mod_shared_roster: {}`.

Your config doesn't mention `mod_mam` at all?

You'll need at least:
```
mod_mam:
    assume_mam_usage: true
    default: always
```

Also, regarding MUCs:
```
  mod_muc:
...
    default_room_options:
      mam: true
```

Keep in mind that users can opt-in or opt-out of MAM as they wish, ask them to check it in their clients.

**Comment by froghorn82** [comment]
@licaon-kter a strange coincidence that I can no longer test omemo.im on https://compliance.conversations.im. ???

Running tests for omemo.im
ParseError at [row,col]:[1,1] Message: Premature end of file.

**Comment by licaon-kter** [comment]
@froghorn82 Ask https://github.com/iNPUTmice/caas/issues
