### ISSUE TITLE
Update documentation to be more synchronized

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2665]
It is possible to update: https://docs.ejabberd.im/admin/configuration/ ?

  * protocol_options: ProtocolOpts: List of general options relating to SSL/TLS. These map to OpenSSL’s set_options(). For a full list of options available in ejabberd, see the source. The default entry is: "no_sslv2"

  * s2s_protocol_options: ProtocolOpts: List of general options relating to SSL/TLS. These map to OpenSSL’s set_options(). For a full list of options available in ejabberd, see the source. The default entry is: "no_sslv2"

  * s2s_use_starttls: optional

Linked to: https://blog.process-one.net/securing-ejabberd-with-tls-encryption/ + https://github.com/processone/ejabberd/issues/2004

    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"

    s2s_use_starttls: required

**Comment by Neustradamus** [comment]
Differences:
* https://github.com/processone/ejabberd/blob/master/config/ejabberd.yml
* https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

-> certfiles etc

**Comment by Neustradamus** [comment]
1/ I have commented about "mod_vcard_ldap" on https://github.com/processone/ejabberd/issues/1410
> [warning] <0.65.0>@ejabberd_config:emit_deprecation_warning:1365 Module mod_vcard_ldap is deprecated, use mod_vcard with 'db_type: ldap' instead

2/ certfile old part
> [warning] <0.368.0>@ejabberd_c2s:listen_opt_type:1005 Listening option 'certfile' for ejabberd_c2s is deprecated, use 'certfiles' global option instead

**Comment by cromain** [comment]
I committed few documentation changes to list default tls options: no_sslv3|cipher_server_preference|no_compression
and removed useless config file, which was adding confusion.
documentation will need more update to match all recent changes, but i'm closing this for now as most important fixes has been pushed

**Comment by Neustradamus** [comment]
Thanks but:
  - "no_sslv2" ?
  - "no_tlsv1" ?
  - "no_tlsv1_1" ?

certificates part?
mod_vcard_ldap part?

**Comment by Neustradamus** [comment]
In more: https://github.com/processone/ejabberd/issues/2707

**Comment by Neustradamus** [comment]
Some improvements (but not all) done in: https://github.com/processone/ejabberd/commit/7713edc6bbef064c6be99a348ddb258da15ef72f
