### ISSUE TITLE
Crashing when attempting to make a connection

### ISSUE THREAD

**Issue by justindunn** [processone/ejabberd#2671]
Environment
-----------
- ejabberd version: 16.06
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.1.1`
- OS: OS High Sierra
- Installed from: official binary installer 

Errors from error.log/crash.log
-------------------------------
No errors in log

this occurs when running in live mode:
beam.smp(77809,0xb04b6000) malloc: *** error for object 0x1e6c0638: pointer being freed was not allocated
                                                                                                         *** set a breakpoint in malloc_error_break to debug
                                                                                                                                                            ./ejabberdctl: line 215: 77809 Abort trap: 6           $EXEC_CMD "$CMD"

Bug description
---------------
When i start to create a connection, it crashes :(

**Comment by licaon-kter** [comment]
You're stuck on an old OS and you can only run that 2-3 years old ejabberd version?

**Comment by cromain** [comment]
16.06 is not supported on High Sierra. Please just use 18.09 which includes environment and libraries fixes to work on High Sierra.
