### ISSUE TITLE
IBR Register form improvements

### ISSUE THREAD

**Issue by lovetox** [processone/ejabberd#2672]
Environment
-----------
- ejabberd version: 18.09 and previous versions

Enhancement description
---------------

This is the current form that ejabberd sends out (i translated the strings because i get it only in german, so its not accurate there)
```xml
<x type='form' xmlns='jabber:x:data'>
      <instructions>Put a Username and Passwort to register</instructions>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:captcha</value>
      </field>
      <field var='username' type='text-single' label='User'>
        <required/>
      </field>
      <field var='password' type='text-private' label='Password'>
        <required/>
      </field>
      <field type='fixed'>
        <value>If you dont see the CAPTCHA go to the website</value>
      </field>
      <field var='captchahidden' type='hidden'>
        <value>workaround-for-psi</value>
      </field>
      <field var='url' type='text-single' label='CAPTCHA Website'>
        <value>https://url/captcha/3427314124937706175/image</value>
      </field>
      <field var='from' type='hidden'>
        <value>conversations.im</value>
      </field>
      <field var='challenge' type='hidden'>
        <value>3427314124937706175</value>
      </field>
      <field var='sid' type='hidden'>
        <value>c1bca9ec-b354-4c6d-b971-cd75229e4e9a</value>
      </field>
      <field var='ocr' type='text-single' label='Put in the text that you see'>
        <media xmlns='urn:xmpp:media-element'>
          <uri type='image/png'>cid</uri>
        </media>
        <required/>
      </field>
    </x>
```

There are 2 fallback fields that should only be shown if the client doesnt support catchas. The Problem im having with this is, i can not apply a generic way to hide these fallback fields. Hence all users see these fields.

My request would be to name the `var` attr in a way that a client developer can apply a semi-generic approach (would have to convince other server developers also) to hide these fields.

for exacmple `captcha-fallback-url` and `captcha-fallback-text`

while i could apply code that only in IBR and MUC challenges hides all `var = url` attr (very ugly), i just dont think its viable to hide all `fixed` fields (the field right now has no var attr defined)

I think this is a change that is both in line with the XEPs, doesnt hurt anyone and lets clients devs hide these fields if they are supporting Captchas. This would increase the user experience with ejabberd IBR.

**Comment by badlop** [comment]
In case you want to test your idea, here are the required changes in ejabberd:
```diff
@@ -128,10 +128,10 @@ create_captcha_x(SID, To, Lang, Limiter, #xdata{fields = Fs} = X) ->
 					  "visit the web page.">>),
 	  Imageurl = get_url(<<Id/binary, "/image">>),
 	  NewFs = [mk_field(hidden, <<"FORM_TYPE">>, ?NS_CAPTCHA)|Fs] ++
-		[#xdata_field{type = fixed, values = [HelpTxt]},
+		[#xdata_field{type = fixed, var = <<"captcha-fallback-text">>, values = [HelpTxt]},
 		 #xdata_field{type = hidden, var = <<"captchahidden">>,
 			      values = [<<"workaround-for-psi">>]},
-		 #xdata_field{type = 'text-single', var = <<"url">>,
+		 #xdata_field{type = 'text-single', var = <<"captcha-fallback-url">>,
 			      label = translate:translate(
 					Lang, <<"CAPTCHA web page">>),
 			      values = [Imageurl]},
```

**Comment by lovetox** [comment]
Thanks for considering my idea.

This works for me.
