### ISSUE TITLE
file transfer

### ISSUE THREAD

**Issue by nico73615** [processone/ejabberd#2674]
Hello,

what is the best way to transfer files with ejabberd ?

Environment
ejabberd version: 18.09
OS: Linux (centos 7)
Installed from: official deb/rpm

**Comment by licaon-kter** [comment]
Use the included ejabberd.yml.example to setup HTTP upload

**Comment by nico73615** [comment]
there is no other way because with http upload was not practical to see an image ?

for example

![image](https://user-images.githubusercontent.com/44775505/48126720-2c338580-e282-11e8-981e-c6f281e5e602.png)

**Comment by licaon-kter** [comment]
Seeing images in the chat view is a client feature, Gajim, Dino, Conversations, ChatSecure, etc all show them just fine.

/close this as invalid

**Comment by nico73615** [comment]
ok thank you for this info and ejabberd can use jingle ?

**Comment by mremond** [comment]
ejabberd supports jingle indeed, but Jingle file transfer is mostly a client-side feature.
HTTP file transfer is easier to implement and proper image display is purely client-side.
