### ISSUE TITLE
Hooks crash on pubsub

### ISSUE THREAD

**Issue by yajo10** [processone/ejabberd#2676]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: `8.2.1`
- OS: Raspbian
- Installed from: source

Bug description
`Hook presence_probe_hook crashed when running mod_pubsub:presence_probe/3: `

`** Reason = {error,{case_clause,blacklist},[{mod_pubsub,'-send_last_pep/2-fun-0-',[{file,"src/mod_pubsub.erl"},{line,2998}],4},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run1,[{file,"src/ejabberd_hooks.erl"},{line,329}],3},{mod_caps,c2s_presence_in,[{file,"src/mod_caps.erl"},{line,233}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{ejabberd_c2s,process_presence_in,[{file,"src/ejabberd_c2s.erl"},{line,607}],2}]}`

`** Arguments = [{jid,<<"xxxxx">>,<<"xxxxxx">>,<<"phone">>,<<"xxxxx">>,<<"xxxxx">>,<<"phone">>},{jid,<<"xxxxxxxxx">>,<<"xxxxxxxxx">>,<<"phone">>,<<"xxxxxxx">>,<<"xxxxxxx">>,<<"phone">>},[<<"eu.siacs.conversations.axolotl.devicelist+notify">>,<<"http://jabber.org/protocol/caps">>,<<"http://jabber.org/protocol/chatstates">>,<<"http://jabber.org/protocol/disco#info">>,<<"http://jabber.org/protocol/muc">>,<<"http://jabber.org/protocol/nick+notify">>,<<"jabber:iq:version">>,<<"jabber:x:conference">>,<<"jabber:x:oob">>,<<"urn:xmpp:avatar:metadata+notify">>,<<"urn:xmpp:chat-markers:0">>,<<"urn:xmpp:idle:1">>,<<"urn:xmpp:jingle:1">>,<<"urn:xmpp:jingle:apps:file-transfer:3">>,<<"urn:xmpp:jingle:apps:file-transfer:4">>,<<"urn:xmpp:jingle:apps:file-transfer:5">>,<<"urn:xmpp:jingle:transports:ibb:1">>,<<"urn:xmpp:jingle:transports:s5b:1">>,<<"urn:xmpp:message-correct:0">>,<<"urn:xmpp:otr:0">>,<<"urn:xmpp:ping">>,<<"urn:xmpp:receipts">>,<<"urn:xmpp:time">>]]`

This part of my configuration may be related to that:
```yaml
mod_pubsub:
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    plugins:
      - "flat"
      - "pep"
    force_node_config:
      "storage:bookmarks":
        access_model: whitelist
```

There are also some other things not working...
` Hook caps_add crashed when running mod_pubsub:caps_add/3:`
`Hook presence_probe_hook crashed when running mod_pubsub:presence_probe/3:`

Could anybody be so kind and explain me if this is a problem and may also how to solve it?
Thanks in advance
yajo

**Comment by cromain** [comment]
where does this 'blacklist' comes from ?
it seems node is configured with access_model=blacklist, but it's not a supported item.

**Comment by cromain** [comment]
also notice access model whitelist is not supported yet for PEP https://github.com/processone/ejabberd/issues/1574

**Comment by yajo10** [comment]
'blacklist' comes from the commented option of the default file. I needed some tries to figure out how it exactly work with Conversations. Therefore I commented the lines out to check out if it would work better.
 In the default configuration file the content looks like this:
`    force_node_config:
      ## Comment out the following lines to enable OMEMO support
      ## See https://github.com/processone/ejabberd/issues/2425
      ##"eu.siacs.conversations.axolotl.*":
      ##  access_model: blacklist
      ## Avoid buggy clients to make their bookmarks public
      "storage:bookmarks":
        access_model: whitelist`

**Comment by weiss** [comment]
'blacklist' comes from the commented option of the default file.

I don't see such a comment in the [sample configuration file][1].

[1]: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

**Comment by cromain** [comment]
as said, blacklist is not a supported option, and not commented in sample config. it's also not documented.
your bad configuration triggered expected behavior on pubsub: a case_clause crash which explicitly state you're using a wrong value.

**Comment by zinid** [comment]
@cromain in this case the validation of the option should be improved. Just saying.

**Comment by yajo10** [comment]
I'm sorry. It seems that I have mixed them up. But is this failure decreasing the function of the server and the description? Or is it just annoying and not causing any problems?
Thank's a lot for your help!
