### ISSUE TITLE
ejabberd and backend integration

### ISSUE THREAD

**Issue by damirci** [processone/ejabberd#2679]
Environment
-----------
- ejabberd version: 18.09
- OS: windows server 2016
- Installed from: official binary installer

I know this is not an issue, but I don't know where can I find answers also I posted this questions on [Stackoverflow](https://stackoverflow.com/questions/53237815/ejabberd-and-backend-integration).

I have a social network that written in Microsoft tech stack and when users register on that I create an Ejabberd user using rest API until now everything works perfectly.

But for chat clients authentication with Ejabberd, I don't want to send Ejabberd username and password to clients. I want to send a token to clients to authenticate.

Questions: Did I chose write approach to integration? If yes, how can I clients authentication token from Ejabberd? If no, in scenarios like this what is the right approach?

**Comment by cromain** [comment]
this question has been answered on stackoverflow
