### ISSUE TITLE
Privacy list between resources

### ISSUE THREAD

**Issue by nbruning** [processone/ejabberd#2681]
When a user is online using 2 resources, the privacy lists are not respected for presence between them.

For example, if resource 2 has an active privacy list (deny outgoing presence), it'll still publish presence to resource 1. By looking at the sources, I would say this was not the case in ejabberd 16 and before.

Do you agree this is a bug ? In that case I'll prepare a pull request.

**Comment by zinid** [comment]
Yes, but it's somewhat ignored due to the two facts:
1) The idea of active lists is retarded and almost never used in practice
2) The privacy lists are deprecated and new client implementation don't even support it (in favor of XEP-0191).

However, if the PR is trivial, you can submit it of course.
