### ISSUE TITLE
mod_push notification when receipient offline

### ISSUE THREAD

**Issue by sunishkumar** [processone/ejabberd#2682]
Environment
-----------
- ejabberd community edition
- ejabberd version: 18.06
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

Please clarify some doubts on mod_push.

I was hopping that mod_push will publish pubsub stanza when the receiver is offline. 
In my test environment ejabberd is publishing a pubsub stanza even when user is online.
Is there any configuration for it to publish only if user is offline?

Thanks 

Sunish Kumar

**Comment by weiss** [comment]
> In my test environment ejabberd is publishing a pubsub stanza even when user is online.

`mod_push` won't do this if the client re-`<enable/>`s push notifications whenever going online.
