### ISSUE TITLE
Thumbnail not working

### ISSUE THREAD

**Issue by jigsp26** [processone/ejabberd#2684]
Environment
-----------
- ejabberd version: 18.04
- OS: Linux (Debian)
- Installed from: source 
Configuration (only if needed):  ejabberd.yml
log-level: 5

    ip: "::"
    port: 5443
    tls : true
    module: ejabberd_http
    request_handlers:
            "upload": mod_http_upload
    web_admin: true
    http_bind: true
    **thumbnail: false**
    register: true
    captcha: true
    certfile: "/usr/local/etc/ejabberd/ejabberd.pem"

I can get and send image and video properly, But i can't get thumbnail of video.
I use conversation app for send and receive video
So, how to fix that?

I fix this also,
https://github.com/processone/ejabberd/commit/c30715e67bd8411202c776f417a40387fa04d39e

So, please give me solution for that.

**Comment by licaon-kter** [comment]
Works fine here, it's not a server thing, ignore that thumbnail option.

**Comment by jigsp26** [comment]
Is there any protocol by which we can send and retrieve thumbnail in message packet?

**Comment by weiss** [comment]
You're building your own client or what?  If so, you could set `thumbnail: true`, the server will then return a thumbnail with the HTTP PUT response.

**Comment by weiss** [comment]
> Can i add thumbnail attribute in XEP-0363 as a solution?

Makes no sense to me, only the server sees the XEP-0363 request, not the remote client.

So you want to generate the thumbnail client-side.  Maybe just perform a separate HTTP upload for the thumbnail?

**Comment by weiss** [comment]
Anyway, this tracker is for tracking ejabberd bugs, it's the wrong place for discussing custom solutions.
