### ISSUE TITLE
upgrade from 17.04 to 17.11

### ISSUE THREAD

**Issue by abdullah-aghayan** [processone/ejabberd#2685]
Environment
-----------
- ejabberd version: 17.11
- OS: Linux (Debian)
- Installed from: official deb/rpm

Hi, I want to upgrade my ejabberd from 17.04 to 17.11, so I read the tutorial in the website. But I want to change my host at the same time (from chat1.xyz.com to new host chat2.xyz.com). Is it possible?

**Comment by licaon-kter** [comment]
Why not 18.09? Why using years old versions?

**Comment by abdullah-aghayan** [comment]
If we upgrade to 18.09, can we be able to change host?

> Why not 18.09? Why using years old versions?

**Comment by cromain** [comment]
just follow upgrade procedures: https://docs.ejabberd.im/admin/upgrade/
changing domain has no relation with upgrade. just change hosts config in ejabberd.yml. If you have database and want to "port" old data to new domain, this can be tricky, you may have to perform some manual queries to changes the domain name (for example starting by the users table....) depending on config and there can be a lot of data to change in the backend.

**Comment by abdullah-aghayan** [comment]
So we decided to upgrade to 18.09, Do you know how we can migrate old data to the new one?

**Comment by badlop** [comment]
> So we decided to upgrade to 18.09, Do you know how we can migrate old data to the new one?

Make a backup of the old database, or at least copy the mnesia spool directory. Then install the new ejabberd version. If it's installed in a different place, copy the mnesia spool directory to that new place. When ejabberd starts, it will automatically update the mnesia tables. If you use SQL, then read the release notes of the intermedia versions, in case you need to make some manual changes in your SQL tables.
