### ISSUE TITLE
disable client IP logging

### ISSUE THREAD

**Issue by 984nz** [processone/ejabberd#2688]
how to configure Ejabberd  to disable logging client IP address  and replace her to 127.0.0.1?

**Comment by zinid** [comment]
Read the doc. This is the bugtracker.

**Comment by 984nz** [comment]
> Read the doc. This is the bugtracker.

вы как разработчик, укажите участок кода который отвечает за  логгирование ИП адреса клиента.

вы думаете я не изучал документацию
