### ISSUE TITLE
problems with mod_shared_roster

### ISSUE THREAD

**Issue by JDVU** [processone/ejabberd#2692]
when adding a user to a group of shared contacts such an error
```
@ejabberd_hooks:safe_apply:384 Hook webadmin_page_host crashed when running mod_shared_roster:webadmin_page/3:
** Reason = {error,{case_clause,undefined},[{mod_roster,push_item,[{file,"src/mod_roster.erl"},{line,482}],3},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{mod_shared_roster,'-push_user_to_displayed/6-lc$^0/1-0-',[{file,"src/mod_shared_roster.erl"},{line,649}],6},{mod
_shared_roster,'-push_user_to_displayed/6-lc$^0/1-0-',[{file,"src/mod_shared_roster.erl"},{line,651}],6},{mod_shared_roster,add_user_to_group,[{file,"src/mod_shared_roster.erl"},{line,553}],3},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{mod_shared_roster,shared_rost
er_group_parse_query,[{file,"src/mod_shared_roster.erl"},{line,941}],3},{mod_shared_roster,shared_roster_group,[{file,"src/mod_shared_roster.erl"},{line,805}],4}]}

```
also in the client does not show the group
maybe some table in the database is missing?
made a comparison with /ejabberd/sql/pg.sql
identically

**Comment by licaon-kter** [comment]
Do add the info the template you've deleted wanted you to...

Also, you need `pg.new.sql` and `use_new_schema: true` in the config for ejabberd 18.03 or newer

**Comment by badlop** [comment]
The crash appears when the group has a member which vhost is not hosted by ejabberd (that is, a remote user). The problem was introduced in https://github.com/processone/ejabberd/commit/ba2b650464bd3aae2b6b0f3a3177476360cb6d08
