### ISSUE TITLE
Shared_roster related errors while delete_old

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2695]
ejabberd HEAD (18.09.49), 1 shared roster, RPi1 w/ 256Mb Raspbian up to date.

Running:
`ejabberdctl --no-timeout delete_old_mam_messages all 30`

then
`ejabberdctl delete_old_messages 30`

then
`ejabberdctl delete_expired_messages`

It worked, (the database got smaller) but the log says this too: https://gist.github.com/licaon-kter/eff6712b1a1f0e986390ddfc52f0360b  (can't pinpoint exactly where each command was run, but they were in that order)

/PS: @mremond there was no issue template BTW

**Comment by badlop** [comment]
> [error] <0.539.0>@mod_offline_sql:remove_old_messages:98
 Cannot delete message in offline spool:
 {error,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},
 {message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},
 {routine,<<"scanner_yyerror">>}]}

That was triggered by the query
> $ ejabberdctl delete_old_messages 30

Looking at the source code, it just says:
```erl
remove_old_messages(Days, LServer) ->
    case ejabberd_sql:sql_query(
	   LServer,
	   ?SQL("DELETE FROM spool"
                " WHERE created_at < NOW() - INTERVAL %(Days)d DAY")) of
	{updated, N} ->
	    ?INFO_MSG("~p message(s) deleted from offline spool", [N]);
	_Error ->
	    ?ERROR_MSG("Cannot delete message in offline spool: ~p", [_Error])
    end,
    {atomic, ok}.
```
So, the query is quite simple, how can fail its parsing? I tried myself, and it's parsed and that code runs as expected without error, and just logs:
```
13:37:12.190 [info] 2 message(s) deleted from offline spool
13:37:23.013 [info] 0 message(s) deleted from offline spool
```


Are you able to reproduce the problem, or it just failed that time?

**Comment by licaon-kter** [comment]
Kinda repro, here's the output of the commanda 2 days ago:

`ejabberdctl --no-timeout delete_old_mam_messages all 30` said:
```
[error] <0.322.0>@ejabberd_sql:check_error:1138 SQL query 'Q16190015' at {mod_mam_sql,79} failed: <<"timed out">>

[warning] <0.322.0>@ejabberd_sql:handle_info:421 unexpected info in session_established: {#Ref<0.1115643817.4083679233.56285>,{ok,{'DELETE',11970}}}
```
`ejabberdctl delete_old_messages 30` said:
```
[error] <0.322.0>@ejabberd_sql:sql_query_internal:572 PREPARE failed for SQL query at {mod_offline_sql,93}: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"$1\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.322.0>@ejabberd_sql:check_error:1145 SQL query 'DELETE FROM spool WHERE created_at < NOW() - INTERVAL 30 DAY' failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.322.0>@ejabberd_sql:check_error:1138 SQL query 'Q51055759' at {mod_offline_sql,93} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.1095.0>@mod_offline_sql:remove_old_messages:98 Cannot delete message in offline spool: {error,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]}
```

While `ejabberdctl delete_expired_messages` didn't complain about anything.

Today only `ejabberdctl delete_old_messages 30` errors out with:
```
[error] <0.322.0>@ejabberd_sql:sql_query_internal:572 PREPARE failed for SQL query at {mod_offline_sql,93}: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"$1\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.322.0>@ejabberd_sql:check_error:1145 SQL query 'DELETE FROM spool WHERE created_at < NOW() - INTERVAL 30 DAY' failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.322.0>@ejabberd_sql:check_error:1138 SQL query 'Q51055759' at {mod_offline_sql,93} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]

[error] <0.1584.0>@mod_offline_sql:remove_old_messages:98 Cannot delete message in offline spool: {error,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42601">>},{message,<<"syntax error at or near \"30\"">>},{position,55},{file,<<"scan.l">>},{line,1087},{routine,<<"scanner_yyerror">>}]}
```

**Comment by licaon-kter** [comment]
Ok, updated to HEAD.

`ejabberdctl --no-timeout delete_old_mam_messages all 30` -> no error, ok

`ejabberdctl delete_old_messages 30`:
```
[error] <0.322.0>@ejabberd_sql:check_error:1143 SQL query 'Q42356763' at {mod_offline_sql,95} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q42356763\" requires 0">>},{file,<<"postgres.c">>},{line,1536},{routine,<<"exec_bind_message">>}]
[error] <0.557.0>@mod_offline_sql:remove_old_messages:107 Cannot delete message in offline spool: {aborted,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q42356763\" requires 0">>},{file,<<"postgres.c">>},{line,1536},{routine,<<"exec_bind_message">>}]}
```

`ejabberdctl delete_expired_messages` -> no error, ok

Will try a `make distclean` next just in case something was mixed up on update.

**Comment by licaon-kter** [comment]
19.02.143 aka HEAD

`ejabberdctl delete_old_messages 200`
> 2019-05-18 08:09:33.332 [error] <0.355.0>@ejabberd_sql:check_error:1161 SQL query 'Q118282789' at {mod_offline_sql,95} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q118282789\" requires 0">>},{file,<<"postgres.c">>},{line,1601},{routine,<<"exec_bind_message">>}]
> 2019-05-18 08:09:33.333 [error] <0.1452.0>@mod_offline_sql:remove_old_messages:107 Cannot delete message in offline spool: {error,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q118282789\" requires 0">>},{file,<<"postgres.c">>},{line,1601},{routine,<<"exec_bind_message">>}]}
> 2019-05-18 08:09:33.383 [error] <0.359.0>@ejabberd_sql:check_error:1161 SQL query 'Q118282789' at {mod_offline_sql,95} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q118282789\" requires 0">>},{file,<<"postgres.c">>},{line,1601},{routine,<<"exec_bind_message">>}]
> 2019-05-18 08:09:33.383 [error] <0.1452.0>@mod_offline_sql:remove_old_messages:107 Cannot delete message in offline spool: {error,[{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"08P01">>},{message,<<"bind message supplies 1 parameters, but prepared statement \"Q118282789\" requires 0">>},{file,<<"postgres.c">>},{line,1601},{routine,<<"exec_bind_message">>}]}

**Comment by alexeyshch** [comment]
Sorry, should be fixed now.

**Comment by licaon-kter** [comment]
Confirmed fixed, thanks.
