### ISSUE TITLE
Use SCRAM by default on example config

### ISSUE THREAD

**Issue by aveao** [processone/ejabberd#2699]
**Is your feature request related to a problem? Please describe.**
By default, if you use example config, ejabberd keeps passwords in plaintext, which is an unacceptable security practice in 2018.

Due to the sheer size of the documentation and the config file, it's easy for people to miss this fact and run ejabberd in a rather insecure way.

**Describe the solution you'd like**
`auth_password_format: scram` should be set by default on [config/ejabberd.yml](https://github.com/processone/ejabberd/blob/master/config/ejabberd.yml).

**Describe alternatives you've considered**
An alternative would be to make it very clear that default is plaintext and that user can enable SCRAM by setting `auth_password_format: scram`.

**Additional context**
SIP requires plaintext passwords, so this breaks support for that on example config.

I doubt that anyone who needs SIP will just deploy example config though. At the very least they'll be required to read config, and config clearly mentions that SIP requires plaintext.

**Comment by weiss** [comment]
> I doubt that anyone who needs SIP will just deploy example config though. At the very least they'll be required to read config, and config clearly mentions that SIP requires plaintext.

I've seen several occasions of people asking how to revert the SCRAM hashes to plain-text passwords after deciding to enable STUN/TURN or SIP authentication at some later point in time.  The only reason this isn't asked even more frequently is that the audio/video support in today's XMPP clients is currently very poor.

**Comment by zinid** [comment]
As @weiss explained, the problem is that there is no way to put scrammed passwords back to plain, so we cannot set `auth_password_format: scram` by default.
We also avoid adding comments to the default config. If the documentation is hard to read/understand, than it should be fixed accordingly. Feel free to open an issue regarding the documentation.

**Comment by zinid** [comment]
> Is there a way to somehow drop plaintext requirement for SIP or STUN/TURN, maybe?

Only by using client certificate authentication which is unique and can be performed by any type of server: sip, stun, xmpp, https, email, no matter. I don't want to apply any kind of hacks for SCRAM which I don't even find a good authentication method.

**Comment by Neustradamus** [comment]
For people, a beautiful page: https://infosec-handbook.eu/blog/xmpp-aitm/
