### ISSUE TITLE
djabberd, jabberd14, jabberd2, metronome, openfire, prosody, tigase, wpjabber import to actual ejabberd

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2701]
How it is possible to migrate from djabberd, jabberd14, jabberd2, metronome, openfire, prosody, tigase, wpjabber to actual ejabberd?

Nothing on https://docs.ejabberd.im/.

**Comment by weiss** [comment]
The most popular of those servers is probably Prosody, there's an `ejabberdctl import-prosody` call documented [here][1] (and [here][2]).  Apart from that, there's an `ejabberdctl import-piefxis` command (documented at the same places),  so the question would be whether those servers support [PIEFXIS export][3].

[1]: https://docs.ejabberd.im/admin/guide/managing/#list-of-ejabberd-commands
[2]: https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#import-prosody
[3]: https://xmpp.org/extensions/xep-0227.html
