### ISSUE TITLE
"Error executing post installation script" on ejabberd 18.09 and windows 10

### ISSUE THREAD

**Issue by damirci** [processone/ejabberd#2702]
I have the below error on ejabberd 18.09 installation on windows 10.

> 
> Executing final installation script
> Error executing post installation script
> C:\Program Files\ejabberd-18.09\bin\postinstall.cmd
> \Program ended with an error exit code

I tried solutions for previous versions but I can't solve it.

**Comment by cromain** [comment]
is that same as #2686 ?

**Comment by cromain** [comment]
ok, in this case there should be logs produced by ejabberd. do you have error.log ?

**Comment by damirci** [comment]
I checked crash.log, ejabberd.log, error.log is there anywhere else to check logs?!

**Comment by cromain** [comment]
ProgramData/ejabberd/logs is the only place
maybe ProgramFiles/ejabberd-18.09/logs as postinstall failed
