### ISSUE TITLE
Pin xmpp version for 18.09 release in mix.exs

### ISSUE THREAD

**Issue by aquarhead** [processone/ejabberd#2705]
Here's a `.patch` file with my change, was about to open a PR but there seems isn't a branch for 18.09 maintenance.

```
From f54bc0aa0d922ee373c74606e550a306092a60b7 Mon Sep 17 00:00:00 2001
From: LOU Xun <aquarhead@ela.build>
Date: Wed, 5 Dec 2018 15:55:18 +0000
Subject: [PATCH] Pin xmpp version to <= 1.2.5

After 1.2.5 some public functions are removed from xmpp:
https://github.com/processone/xmpp/commit/0ca8fc95d2ea69d39dda0b8deb5adc96ea1414d9

Yet `mod_muc_room.erl` still uses `xmpp_util:add_delay_info` for example.
---
 mix.exs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/mix.exs b/mix.exs
index f96f8c25..7d8baeda 100644
--- a/mix.exs
+++ b/mix.exs
@@ -61,7 +61,7 @@ defmodule Ejabberd.Mixfile do
     [{:lager, "~> 3.4.0"},
      {:p1_utils, "~> 1.0"},
      {:fast_xml, "~> 1.1"},
-     {:xmpp, "~> 1.2"},
+     {:xmpp, ">= 1.2.0 and <= 1.2.5"},
      {:cache_tab, "~> 1.0"},
      {:stringprep, "~> 1.0"},
      {:fast_yaml, "~> 1.0"},
--
2.19.2

```

Currently the 18.09 release causes issue for Elixir projects that wraps `ejabberd` (having it as a dep) because it tries to pull version 1.2.7 of `xmpp` (by default) and will crash `mod_muc_room` processes at runtime:

```
** Reason for termination =
** {:undef, [{:xmpp_util, :add_delay_info,
```

Of course one can override the dep resolution with `{:xmpp, "== 1.2.5", override: true}`, but it's not very obvious and I think it should be fixed anyway.

**Comment by prefiks** [comment]
I don't we will release 18.09.01 (we will release 18.12 today), so i will probably not merge this, but i am getting point of that patch, and in future i will be more vigilant when releasing new version of xmpp and make sure that breaking changes will use version that aren't compatible with older version of ejabberd.

**Comment by aquarhead** [comment]
all good 👍
