### ISSUE TITLE
How official is mod_legacy_auth?

### ISSUE THREAD

**Issue by tallesl** [processone/ejabberd#2706]
While testing XMPP (no client, opening a socket and sending XML myself), mod_legacy_auth became really useful.

I read about mod_legacy_auth on old forum posts and bug reports, there's no mention on official docs.
And if I'm not mistaken, it's enabling [XEP-0078](https://xmpp.org/extensions/xep-0078.html) which is [listed as supported](https://www.process-one.net/en/ejabberd/protocols/).

Can I count on mod_legacy_auth to still work on newer releases (even though is not documented)?

**Comment by zinid** [comment]
The feature is [tested](https://github.com/processone/ejabberd/blob/master/test/ejabberd_SUITE.erl#L334) by the test suite, so it should be working.

**Comment by tallesl** [comment]
@zinid Shouldn't be documented somewhere?
