### ISSUE TITLE
Schema description for PubSub and MUC

### ISSUE THREAD

**Issue by woj-tek** [processone/ejabberd#2707]
It would be nice if schema documentation (https://docs.ejabberd.im/developer/sql-schema/) would be completed with description of schema for PubSub and MUC. Is it planned?

**Comment by jsautret** [comment]
muc_online_room, muc_online_users & muc_room_subscribers have been in the documentation.

**Comment by woj-tek** [comment]
Where? I don't see it in the linked documentation.

**Comment by jsautret** [comment]
Online documentation needs a delay to be updated. It is now.

**Comment by woj-tek** [comment]
Thank you!
