### ISSUE TITLE
The Files Uploaded using mod http_upload gets deleted randomly

### ISSUE THREAD

**Issue by nischalgowdav** [processone/ejabberd#2708]
Ejabberd Version - 18.04
We are using mod http_upload to upload files and the files are being uploaded successfully and we are able to retrieve them as well.
However the uploaded files are being deleted randomly after uploading.
Below is the Mod upload configuration .

  mod_http_upload:
    docroot: "@HOME@/upload"
    put_url: "https://@HOST@:5444"
    thumbnail: false # otherwise needs ejabberd to be compiled with libgd support
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS, DELETE"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
##     max_days: 30
 
[ejabberd_yml.zip](https://github.com/processone/ejabberd/files/2655994/ejabberd_yml.zip)

**Comment by nischalgowdav** [comment]
This was random ,
I saw that file was deleted next day some time , and i saw that there was a was which was deleted 4 days later

**Comment by licaon-kter** [comment]
By saw you mean in ejabberd.log?

**Comment by nischalgowdav** [comment]
No In the Logs i dint see anything related to deleting the file . I just logged in as a user to check my chat history and the File URL gave me a 404

**Comment by licaon-kter** [comment]
@zinid it's commented, see zip

Github markup ## header

**Comment by zinid** [comment]
> No In the Logs i dint see anything related to deleting the file . I just logged in as a user to check my chat history and the File URL gave me a 404

Well, this is not a bug report at all.

**Comment by nischalgowdav** [comment]
@zinid  yes the mod_upload_quota is commented in the yaml .. how ever the files get deleted

**Comment by licaon-kter** [comment]
When the files get deleted there's a line written in the log, hence maybe the file got deleted by other process.  Maybe you have a cron task to clean up.

By deleted you mean you've got the hash and searched for it in the upload folder?

**Comment by zinid** [comment]
Closed due to the author's inactivity.

**Comment by nischalgowdav** [comment]
Hello ,
Sorry for the late reply .
Here are some further analysis details .
I have 2 shared rooster , Visitors & operators 
Lets say a chat conversation happened between a visitor an operator 10 days ago . in this conversation both visitor and operator have uploaded documents. and the chat ended there .

if there is no conversation by the visitor for more than 2 days again , I delete the visitor and remove him from the shared rooster group. and the visitor comes back later , now i register the same user and connect to same operator.
I observed that the file uploaded by operator was found , but the file uploaded by the visitor was not found.
Is there a configuration  which deletes the uploaded files by the user , if the user jid is removed from the 
ejabberd? (How ever i can see that in the Archive the chat history exits , even if the user is removed from ejabberd).

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/admin/configuration/#mod-http-upload
`rm_on_unregister: true|false: This option specifies whether files uploaded by a user should be removed when that user is unregistered. Default: true.`

Right?

**Comment by licaon-kter** [comment]
Always state the whole setup, steps and what you want. You've omitted the most important detail: "remove user".
