### ISSUE TITLE
mod_roster: push roster update error

### ISSUE THREAD

**Issue by anghiloglu-dmitrii** [processone/ejabberd#2709]
Environment
ejabberd version: 17.11
OS: Ubuntu 16.10
Installed from: sources

I can find many logs like this in my current ejabberd cluster.

Errors from error.log/crash.log
> ** Reason = {error,badarg,[{fxml,element_to_binary,[],[{xmlel,<<"iq">>,[{<<"to">>,<<"45731@myhost/96a8dcd1-17c4-4dc3-b58b-985f7e56cc93">>},{<<"from">>,<<"45731@myhost">>},{<<"type">>,<<"set">>},{<<"id">>,<<"push14127011705642741761">>}],[{xmlel,<<"query">>,[{<<"ver">>,not_found},{<<"xmlns">>,<<"jabber:iq:roster">>}],[{xmlel,<<"item">>,[{<<"ask">>,<<"subscribe">>},{<<"jid">>,<<"743703@myhost">>}],[]}]}]}]},{ejabberd_socket,send_element,[{file,"src/ejabberd_socket.erl"},{line,200}],2},{xmpp_stream_in,send_pkt,[{file,"src/xmpp_stream_in.erl"},{line,1040}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run_fold1,[{file,"src/ejabberd_hooks.erl"},{line,364}],4},{xmpp_stream_in,handle_info,[{file,"src/xmpp_stream_in.erl"},{line,373}],2},{p1_server,handle_msg,[{file,"src/p1_server.erl"},{line,696}],8},{proc_lib,init_p_do_apply,[{file,"proc_lib.erl"},{line,240}],3}]}

Bug description: 
fxml element can't be converted to binary because of **not_found** value of **<<"ver">>** element.
**mod_roster line:237**
```
roster_version(LServer, LUser) ->
    US = {LUser, LServer},
    case roster_version_on_db(LServer) of
      true ->
	  case read_roster_version(LUser, LServer) of
	    error -> not_found;
	    {ok, V} -> V
	  end;
      false ->
	  roster_hash(ejabberd_hooks:run_fold(roster_get, LServer,
					      [], [US]))
    end.
```
Wrong xml el
```
El = #xmlel{name = <<"iq">>,
       attrs = [{<<"to">>,
                 <<"45731@youchat/96a8dcd1-17c4-4dc3-b58b-985f7e56cc93">>},
                {<<"from">>,<<"45731@myhost">>},
                {<<"type">>,<<"set">>},
                {<<"id">>,<<"push14127011705642741761">>}],
       children = [#xmlel{name = <<"query">>,
                          attrs = [{<<"ver">>,not_found},
                                   {<<"xmlns">>,<<"jabber:iq:roster">>}],
                          children = [#xmlel{name = <<"item">>,
                                             attrs = [{<<"ask">>,<<"subscribe">>},
                                                      {<<"jid">>,<<"743703@myhost">>}],
                                             children = []}]}]}

fxml:to_xmlel(El).

** exception error: bad argument
     in function  iolist_to_binary/1
        called as iolist_to_binary(not_found)
     in call from fxml:'-to_xmlel/1-lc$^1/1-0-'/1 (src/fxml.erl, line 305)
     in call from fxml:to_xmlel/1 (src/fxml.erl, line 305)
     in call from fxml:'-to_xmlel/1-lc$^0/1-1-'/1 (src/fxml.erl, line 307)
     in call from fxml:to_xmlel/1 (src/fxml.erl, line 307)
```
change not_found -> <<"not_found">> fixes the issue.

I unable to find the repro steps but, I guess this is because of migration from unversioned roster to versioned.

**Comment by zinid** [comment]
Yeah, the whole stuff is broken.

**Comment by zinid** [comment]
It's actually trivial to reproduce: it doesn't work at all when roster versioning on DB is enabled. Seems like just nobody is using that.
