### ISSUE TITLE
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo=0x15bc38d0 {NSLocalizedDescription=Socket closed by remote peer}

### ISSUE THREAD

**Issue by praveenoms** [processone/ejabberd#271]
Hi,
  we have ejabberd server configured by third party vendors and we are getting "Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" , they are saying its not their fault and the server is configured correctly on their part :( there is something wrong with our client..

i am not agreed with their statement as we are running the same application on DEV server since last 8 months configured by us and never face this issue,the only difference is we used menesia on DEV server and Mongo on the production which is configured by third party vendors.

could anyone please let me know why and when this error occurred as our clients has all implementation related to connection like XMPP Ping & XMPP Reconnect

appreciate quick response as we need to make our app live on production

**Comment by Nitin3589** [comment]
is there any update on this error  ?

**Comment by weiss** [comment]
> is there any update on this error ?

As far as I can see, this was about some issue with some MongoDB code which is not shipped with ejabberd?  So I don't see how anyone would be able to provide any updates.

**Comment by rraptorr** [comment]
No, I have never ever used mongo and I do not plan to. Please, do not resurrect ancient closed tickets, it is very annoying.
