### ISSUE TITLE
Muc Group chat + ejabberd + conversations

### ISSUE THREAD

**Issue by jarvisv4** [processone/ejabberd#2711]
**Ejabberd version:-** 18.04

configuration of **ejabberd.yml**

mod_muc:
access: muc
access_create: muc
access_persistent: muc
access_admin: muc_admin
default_room_options:
allow_change_subj: true
allow_private_messages: true
allow_user_invites: true
allow_subscription: true
logging: true
members_by_default: true
persistent: true
public: true
public_list: false
mod_muc_log:
access_log: muc
dirtype: plain
dirname: room_jid
outdir: "/var/www/muclogs"
timezone: universal
spam_prevention: true
mod_muc_admin: {}

In muc group chat I get following issues:-

->When an admin/owner tries to leave a muc group by changing it's role gets changed to none ,  still it is present in members list in muc_room ,due to which even though it has left group chat other users are not able to get updated users list. This situation is not faced when a member is removed from a group or a member leaves a group.

-> Also what should we do so that a admin can grant / revoke admin privileges to other user as well as revoke from owner. Are there any possible configurations?

->Is there any way to not auto-join a left group except archiving the conversation.Since in this way user is not able to see it's previous group chat when user was present in group.

**Comment by badlop** [comment]
> ->When an admin/owner tries to leave a muc group by changing it's role gets changed to none , still it is present in members list in muc_room ,due to which even though it has left group chat other users are not able to get updated users list. This situation is not faced when a member is removed from a group or a member leaves a group.

Any room occupant (member, owner, whatever) leaves the room by following this:
https://xmpp.org/extensions/xep-0045.html#exit

which means, sending this stanza (user1 is a room owner):
```xml
<presence id='25:663994'
	xml:lang='es'
	type='unavailable'
	to='room1@muc.localhost/user1'/>
```

and the other room occupants receive this:
```xml
<presence to='user2@localhost/tka1'
	from='room1@muc.localhost/user1'
	type='unavailable'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item role='none'
	affiliation='owner'/>
  </x>
</presence>
```

> -> Also what should we do so that a admin can grant / revoke admin privileges to other user as well as revoke from owner. Are there any possible configurations?

I think that is not allowed in the XEP, and consequently it is not allowed in the ejabberd source code:
https://xmpp.org/extensions/xep-0045.html#affil-change

Of course, you can modify the source code to suit your needs, recompile and install.

> ->Is there any way to not auto-join a left group except archiving the conversation.Since in this way user is not able to see it's previous group chat when user was present in group.

I didn't understand this, but maybe it is a client question, not server question?
