### ISSUE TITLE
User session not removed

### ISSUE THREAD

**Issue by thatorangebox** [processone/ejabberd#2712]
- ejabberd version: 18.09
- OS: Ubuntu 18.04
- Installed from: source

Hi, i've recently noticed that user's sessions are not removed when the user disconnect and new session is added when user reconnects. The connected resources from ejabberd web admin shows that the user is connected to more than 1 resources even though the config settings only allows 1 user to be connected to 1 session.
The ejabberd set up is running in cluster of 4 nodes. 

Thanks.

**Comment by licaon-kter** [comment]
Config? Logs?

**Comment by zinid** [comment]
So this is a bug report or what?
