### ISSUE TITLE
ejabberd15.07 stream management is enabled but message are getting dropped

### ISSUE THREAD

**Issue by xabberd** [processone/ejabberd#2713]
I am using ejabberd 15.07 on Centos. I have enabled stream management on the server and on the client (Android and iOS) as well.
But still some messages are getting dropped when sent within stream resumption period. mod_mam is enabled and mod_offline too. From mysql database it can be seen that the message has reached the server but not to the recipient. After some time if the stream does not resume, the message entry is stored in spool table. When the recipient comes online again, some messages are sent to him and some are not. There is no error for that message in the logs on server. Please suggest what is wrong. Below is my yml file snippet for stream management.
   
    stream_management: true
    resend_on_timeout: true
    resume_timeout: 30
    max_ack_queue: 1000

**Comment by licaon-kter** [comment]
15.07? No way to update?

**Comment by xabberd** [comment]
> 15.07? No way to update?

Is there any way to solve the issue with this version?

**Comment by zinid** [comment]
@xabberd no. We don't provide support for previous versions.
