### ISSUE TITLE
prosody2ejabberd crashes with some roster files

### ISSUE THREAD

**Issue by Lykos153** [processone/ejabberd#2722]
Version 18.12-1 on Arch Linux.

This is the stacktrace:
```
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{prosody2ejabberd,'-convert_roster_item/4-fun-1-',
                 [{<<"persist">>,false},
                  {roster,
                      {<<"a">>,<<"y">>,
                       {<<"b">>,<<"y">>,<<>>}},
                      {<<"a">>,<<"y">>},
                      {<<"b">>,<<"y">>,<<>>},
                      <<"B">>,none,none,
                      [<<"Alle">>],
                      <<>>,[]}],
                 [{file,"src/prosody2ejabberd.erl"},{line,308}]},
             {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
             {prosody2ejabberd,convert_roster_item,4,
                 [{file,"src/prosody2ejabberd.erl"},{line,307}]},
             {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
             {prosody2ejabberd,convert_data,4,
                 [{file,"src/prosody2ejabberd.erl"},{line,162}]},
             {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
             {ejabberd_ctl,call_command,4,
                 [{file,"src/ejabberd_ctl.erl"},{line,351}]},
             {ejabberd_ctl,try_call_command,4,
                 [{file,"src/ejabberd_ctl.erl"},{line,320}]}]

```
Maybe this is sufficient to spot the error for someone who is familiar with the code. If not, I could provide an anonymized roster file.

**Comment by badlop** [comment]
Please provide some example files, one good and one bad, so I can reproduce, as I don't know prosody format.

**Comment by Lykos153** [comment]
Here you go! (Had to add .txt to the filename so github would accept it)

[member_good.dat.txt](https://github.com/processone/ejabberd/files/2696962/member_good.dat.txt)
[member_bad.dat.txt](https://github.com/processone/ejabberd/files/2696963/member_bad.dat.txt)

**Comment by badlop** [comment]
The problem is in those roster items with persist=false, that ejabberd doesn't know how to handle. Looking at Prosody source code, it seems those roster items are produced by mod_groups (similar to ejabberd's  mod_shared_roster), so they shouldn't be imported into ejabberd, right?

**Comment by Lykos153** [comment]
You're right. In this case they should probably just be skipped.
