### ISSUE TITLE
ejabberd_http decode data

### ISSUE THREAD

**Issue by longlene** [processone/ejabberd#2738]
**ejabberd_http:extract_path_query** try to decode HTTP body and add to the decoded body with nokey as the LQuery, it may mislead developer, is it better just put raw body as #request.data, don't add {nokey, decoded body} to LQuery?

If so, request handler can get Headers from #request.headers, get Body from #request.data, get query-string from #request.q

**Comment by badlop** [comment]
Hi! Sorry, I don't completely understand your explanation. If you can convert your paragraph into a working source code patch, that could be compiled, tested, and verified... that could lead to a productive solution. Until then, I propose to close this issue. Thanks!
