### ISSUE TITLE
ejabberd web admin didn't work

### ISSUE THREAD

**Issue by stoneLee81** [processone/ejabberd#2746]
I run sudo apt-get install ejabberd command to install ejabberd on Ubuntu system, and then run 
ejabberdctl start to start it. 
When accessing web admin through web browser, it didn't work.
1 The remote service port is open
![snip20190102_29](https://user-images.githubusercontent.com/18001708/50582636-ed473800-0e9e-11e9-8ec3-1752aa079464.png)
2 access web admin, didn't work
![snip20190102_28](https://user-images.githubusercontent.com/18001708/50582643-f3d5af80-0e9e-11e9-9537-7a417cb85dcc.png)

**Comment by licaon-kter** [comment]
Did you make sure that **ejabberd.yml** config has the port open? Maybe it's 5443 or something.

**Comment by stoneLee81** [comment]
yes, I run telnet to that ip and port, conneted.

**Comment by stoneLee81** [comment]
and I use imessage client to test 5222 port, it's ok.
