### ISSUE TITLE
ejabberd use mysql instead of defaut mnesia db

### ISSUE THREAD

**Issue by stoneLee81** [processone/ejabberd#2747]
Use mysql instead of default mnesia db:
1 Modify ejabberd.yml file
![image](https://user-images.githubusercontent.com/18001708/50585678-25f00d00-0eb1-11e9-95fa-9c4c32c42dc2.png)
![image](https://user-images.githubusercontent.com/18001708/50585663-1bce0e80-0eb1-11e9-877d-8bc45bd73f8e.png)
and restart ejabberd, then run command to add user
ejabberdctl register testuser2 localhost 123456
it showed conflict, and the error log is:
2019-01-02 17:03:09.627 [error] <0.605.0>@ejabberd_auth:is_user_exists:316 The authentication module ejabberd_auth_sql returned an error
when checking user <<"testuser2">> in server <<"172.16.16.2">>
Error message: {aborted,{no_exists,[sql_pool,<<"172.16.16.2">>]}}

==> /var/log/ejabberd/ejabberd.log <==
2019-01-02 17:03:09.627 [error] <0.605.0>@ejabberd_auth:is_user_exists:316 The authentication module ejabberd_auth_sql returned an error
when checking user <<"testuser2">> in server <<"172.16.16.2">>
Error message: {aborted,{no_exists,[sql_pool,<<"172.16.16.2">>]}}

**Comment by licaon-kter** [comment]
Did you make the database first? Just modifying the config is not enough

**Comment by stoneLee81** [comment]
[ejabberd.txt](https://github.com/processone/ejabberd/files/2720321/ejabberd.txt)
this is the ejabberd.yml file

**Comment by licaon-kter** [comment]
Two thoughts:
* use the newer config template if you're just setting up a new server: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example
* how did you create the database, did you import
