### ISSUE TITLE
Mod HTTP web admin

### ISSUE THREAD

**Issue by panpansh** [processone/ejabberd#2750]
Hello I have trouble to get web admin working on port 5443.
I can access web admin via 5280 but nothing via 5443.

![ejabberd conf](https://user-images.githubusercontent.com/790586/50675265-576df300-0fed-11e9-89b2-9580bf695bea.PNG)
![ejabberd iptables](https://user-images.githubusercontent.com/790586/50675279-6fde0d80-0fed-11e9-98f6-812b5aee2251.PNG)
![ejabberd netstat](https://user-images.githubusercontent.com/790586/50675283-72d8fe00-0fed-11e9-8b29-2913e3dfc4c5.PNG)

when I hit the refresh page button for port 5443 I can see in live log  : 5280 🐙 
![ejabberd hitrefresh](https://user-images.githubusercontent.com/790586/50675330-baf82080-0fed-11e9-913c-917a6be0ea37.PNG)

tried to set web_admin to false on 5280, did the same but yes it disable access from 5280
access from 5443 stay impossible and log looks like last print screen.

ejabberd 18.12.42 master

**Comment by panpansh** [comment]
oh god when I post I see my problem xD
netstat is saying 5433 not 5443 lol
sorry it's work :/

**Comment by panpansh** [comment]
But why they "accept connection" (in log) of a non listening port saying ok 5280

**Comment by licaon-kter** [comment]
You he web_admin on both ports (5433 and 5280), in your pictures, what is the problem?

**Comment by panpansh** [comment]
call http 5444 without ejabberd listening on it. can you see in log "accept connection" 5280 ?

**Comment by licaon-kter** [comment]
Upload the full config on https://gist.github.com
