### ISSUE TITLE
Permanent MUC subscription

### ISSUE THREAD

**Issue by jithin-pits** [processone/ejabberd#2755]
Is subscribing to a group using subscribe_room api permanent ?

here https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/
in the drawbacks section, it says the muc subscription is not permanent,

would the subscription be permanent if we use the api ie https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#unsubscribe-room ?

how to subscribe to a room, from client side using stanza or from server side using api ?

**Comment by badlop** [comment]
> in the drawbacks section, it says the muc subscription is not permanent,

It doesn't say that. It says that the common way to be involved in a room (by sending a presence to join it) is not permanent. And after those drawbacks, it says _This specification tries to solve those issues_ 

> Is subscribing to a group using subscribe_room api permanent ?

Yes.

> would the subscription be permanent if we use the api ie https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#unsubscribe-room ?

Yes.

> how to subscribe to a room, from client side using stanza or from server side using api ?

Both ways have the same effect.

Please try it, and comment here if you see the subscription is not permanent... that would be a bug.

**Comment by jithin-pits** [comment]
Dear @badlop 

Thank you so much, no issues so far.

**Comment by jithin-pits** [comment]
Dear @badlop,

We are not getting messages if the client app is closed, we only get the messages when the client app is open or minimised, we are using ejabberd saas edition, are we missing anything.

thanks in advance.

**Comment by licaon-kter** [comment]
@jithin-pits Conversations from Google Play store does this? ChatSecure from iTunes does this?

You did enable push right?

**Comment by jithin-pits** [comment]
Dear @licaon-kter ,

We are using saas version and we asked official ejabberd support executives to enable push, they said they have enabled push notification, but we are not receiving any notification, are we missing something, is there anything we have to do from client side (client app)

thanks in advance.

**Comment by mremond** [comment]
Hello @jithin-pits,
The best is to discuss with the support. That's the best way to gather info and troubleshot your issue.

**Comment by jithin-pits** [comment]
Dear @licaon-kter ,

We have set up firebase and we have manage to send push notification from a backend php server (not xmpp server) the problem is with xmpp.

Is there anything we have to implement in the client app.

**Comment by jithin-pits** [comment]
Dear @mremond ,

emails takes time :( , here we could get immediate response, we are running out of time. :(

thanks for your concern, please help.

**Comment by jithin-pits** [comment]
Dear @licaon-kter , @mremond , @badlop ,

While creating group we call the subscribe_room api to get realtime chat (when app is minimised (foreground and background))

would this prevent push notification when the app is closed ?

thanks in advance.

**Comment by licaon-kter** [comment]
@jithin-pits You realise they're the same people (more or less) responding to e-mail and here, right?

**Comment by jithin-pits** [comment]
Dear @licaon-kter ,

mail is one to one and here its one to many :+1:  :)
