### ISSUE TITLE
Delay in sending OMEMO encrypted messages

### ISSUE THREAD

**Issue by skumarm** [processone/ejabberd#2758]
I am using **ejabberd-18.09** server for implementing chat using Conversations ( Android ) and ChatSecure-iOS ( iOS ). 
Normal ( unencrypted ) conversations working without any problem. But I am facing a delay in sending OMEMO encrypted messages. Need help on this. Please...

Please find my ejabberd configuration file [here](https://gist.github.com/skumarm/e6308006c388b7cc9983acdbdbe98a57)

**Comment by licaon-kter** [comment]
Loglevel 4 or 5, capture sending anunencrypted one, then one encrypted, put it on gist.

Take notes on each step, time info, etc

**Comment by mremond** [comment]
I would suggest you put the server in debug mode to check if you are not hitting a trafic shaper limit.
