### ISSUE TITLE
Consider un-deprecating c2s_certfile and s2s_certfile

### ISSUE THREAD

**Issue by rhn** [processone/ejabberd#2760]
I'd like to use my own CA for client communication, while I would like to retain the ability to federate. Having the clients trust exclusively my custom CA defends me from having a fake certificate [like this](https://arstechnica.com/information-technology/2019/01/a-dns-hijacking-wave-is-targeting-companies-at-an-almost-unprecedented-scale/) taking over client traffic. My s2s traffic may still be affected, but at least within the domain of my server, communication stays secure.

This is no longer possible if separate `c2s_certfile` and `s2s_certfile` are replaced with a unified `certfiles` option.

**Describe the solution you'd like**
Keeping c2s and s2s certificates separate lets me specify separate CAs already.

**Describe alternatives you've considered**
New `c2s_certfiles` and `s2s_certfiles` (note the "s") options following the same structure as `certfiles`, but applying to different connection types would also solve the issue.

Another alternative would be running some sort of a TLS proxy replacing the cetrtificate between my server and the federated network, but that would only affect the server-side (inbound) certificate and not the client (outbound) one. That sounds unnecessarily complicated though, compared to the proposed split.

I'm happy to help implementing this if it is not thrown away out of hand :)

**Comment by licaon-kter** [comment]
> my custom CA defends me from having a fake certificate like this taking over client traffic

You're joking right? That "attack" is based on _"improperly secured or compromised DNS configuration controls"_, which could happen on your systems too, making the whole `c2s_certfile and s2s_certfile` issue a moot point.

**Comment by zinid** [comment]
I disagree with having such a complicated system. I understand that some people want that (for the reason I don't understand), but we want to make the code managing certificates to be as simple as possible, especially given that incorrect configuration may lead to security threats.

**Comment by rhn** [comment]
> You're joking right?

That's a strange comment, why would I waste my time making jokes?

This particulat attack is completely mitigated by having a client that's configured to use only a single CA. Consider that s2s is secured with Let's Encrypt (CA1), c2s is secured with CA2, and clients accept only CA2. In the following scenario:

- the attacker changes DNS configuration for xmpp.example.com to use the attacker-controlled host A and obtains a certificate C1 signed by CA1
- the client connects to A after resolving xmpp.example.com
- the client rejects A's certificate C1 based on the fact that it's not signed by CA2

This obviously mitigates the error, so I don't see how the issue becomes moot.

Sure, every system can be misconfigured, but choosing separate roots of trust for the domains of internal and federated communication means choosing the sources of errors that can affect either.

**Comment by zinid** [comment]
> Sure, every system can be misconfigured

I'm mainly concerned about code complexity, for instance we used to have several bugs already in the past where the server provided incorrect certificate (i.e. for another configured domain). I'd like to stress also that certificate management subsystem in ejabberd is one of the most complicated component. So for me this is a question of pros vs cons.

**Comment by rhn** [comment]
> I'm mainly concerned about code complexity

I completely understand and respect that.

If I'm reading `ejabberd_pkix` right, it's a matter of having one `state` instance for c2s and another for `c2s`, and adjusting `add_certificate` and `get_certificate` signatures to use the correct one. I can envision bugs where certificates get mixed up between c2s and s2s, but given the change would be rather contained, I don't think they would be common.
