### ISSUE TITLE
Not-authorized when try to login using a registered user

### ISSUE THREAD

**Issue by VitorCioletti** [processone/ejabberd#2762]
> What version of ejabberd are you using?

18.12.44 (according to my `ejabberd.app`, but it does not match to released versions at GitHub '-')

> What operating system (version) are you using?

Ubuntu 18.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? 

Trying to login using a registered user and I get the following message log.

`2019-01-12 16:24:00.952 [warning] <0.17527.4>@ejabberd_c2s:handle_auth_failure:452 (tcp|<0.17527.4>) Failed c2s legacy authentication for myuser@mydomain from 192.168.0.0: not-authorized`

I'm positively sure I'm sending the correct user and password.

> What was the unexpected behavior? What was the expected result?

Unexpected behavior: not-authorized

Expected result: Normal connection.

> Description of the problem.

When that happens, I can solve the problem by logging into ejabberd admin interface using `admin@mydomain` and changing the user password to the **same one** it was registered before. However, after some time (was not able to detect some kind of pattern to this) the problem happens again...

I've taken a mnesia dump to see if user's password changes automatically due to some password expiration module, but I've found nothing.

This issue #838 is facing the same problem.

> [Current ejabberd.yml](https://gist.github.com/VitorCioletti/98d378e2e9d2d02be8ebfbc813f243ee)

Thanks in advance.

**Comment by zinid** [comment]
I'm not even sure legacy authentication works with SCRAM. Also, try to set `auth_use_cache: false`.

**Comment by VitorCioletti** [comment]
Well, the problem seems to be solved by taking off `auth_password_format: scram` from my yaml. As you said, it seems it does not work well with legacy auth.

`auth_use_cache: false` had no effect.

Thanks, @zinid.
