### ISSUE TITLE
Unable to set thumbnail configuration to true for Ejabberd mod_http_upload

### ISSUE THREAD

**Issue by DhruvKapur** [processone/ejabberd#2767]
I am using latest Ejabberd version 18.12.1 (and have tried some old versions as well) on AWS EC2 Linux Machine. I have switched on mod_http_upload to upload the files with the default configuration for thumbnail as false. However when I try to turn it to true, the server fails to start and gives an error -

[error] <0.408.0>@gen_mod:module_error:574 Invalid value for option 'thumbnail' of module mod_http_upload: true

Based upon various documents and support material, I understand that we need to compile ejabberd with libgd option, to enable this feature. However I am not sure how to enable / compile with libgd. Which command do will do this.

I have installed all the required libraries including gd and gd-devel before compiling Ejabberd. I have also tried various options while compiling including --enable-graphics but that also didn't help.

Any help to understand how thumbnails can be enabled will be really appreciated.

**Comment by badlop** [comment]
Replied here with the probable solution: https://serverfault.com/questions/949482/unable-to-set-thumbnail-configuration-to-true-for-ejabberd-mod-http-upload

Maybe the specific libraries should be mentioned in the error log message?

**Comment by DhruvKapur** [comment]
Thanks for the response Badlop.

Actually I was trying this on Centos and even after resolving libgd dependency as you mentioned above, it was giving issues with the eimp module. So finally I have switched to ubuntu (Debian) and after installing ejabberd again with all the dependencies that error is gone.

Now I am able to start the server without any error with "thumbnail: true" and able to send files as well. However its still not generating thumbnail and there is no error in logs. Not sure what I am missing now. Is there any limitation on types of files for which thumbnail is generated? We have uploaded PNG files so far. There is no error and hence I am clue less here. Any help to debug this further would really help.

**Comment by vinothabc** [comment]
Hi DhruvKapur

I am also facing the same problem on my AWS Linux instance,  Iam using Ejabberd-18.06 version. Is there any other option to solve this issue, Because Iam not ready to change my server OS for this one single reason. If you provide any solution to solve this issue, It will be really helpful to me.

**Comment by DhruvKapur** [comment]
Hi

Based upon our usage and integration with the app I am working on, and also considering the security of uploaded files, we have decided to use our own service to support attachments and thumbnails. Hence I didn't really spent much time on this approach. Apologies but don't have much to help you out.
