### ISSUE TITLE
Letsencrypt Ejabberd certificate config and renew

### ISSUE THREAD

**Issue by danjde** [processone/ejabberd#2768]
Hi Friends!
I’m enabling the ejabberd service.
My question is: using a LE cumulative certificate (multiple domains in the same) is it possible to link directly on eJabberd config file the “pem” certs?
And eventually, if not possible, how automate the creation and renewal of the “ejabberd.pem”?

##
##
s2s_certfile: "/etc/ejabberd/ejabberd.pem"

Many many thanks!

Davide

**Comment by zinid** [comment]
Not a bug report.
