### ISSUE TITLE
cache_size not applied to mod_roster on reload_config

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2769]
18.12.72 from Git, arm64

See in the log
`[warning] <0.403.0> Shrinking cache 'roster_item_cache' (current size = 1001, max size = 1000, life time = 3600000, memory = 331480 bytes); you should increase maximum cache size if this message repeats too often`
...edit config `cache_size: 20000`, do `ejabberdctl reload_config`, log filled with the same message.

**Comment by badlop** [comment]
Caching was first implemented in mod_roster and mod_privacy in f782955c069f1091cd56cc9d139ec0b0e2d62780. Later it was improved in 35d19b32f40a4f6aedecca36c3145ab3013ecf87, in mod_privacy it got an improvement to reinitialize the cache when reloading the configuration... but that improvement was not applied to mod_roster.
