### ISSUE TITLE
Can't connect to ejabberd using Psi

### ISSUE THREAD

**Issue by OmarElmekaalel** [processone/ejabberd#2771]
I have installed ejabberd and psi also to test it, it seems like I can't connect to ejabberd; I have this message:
"There was a problem communicating with the server"
"Details: Disconnected"
This is my [ejabberd.yml](https://gist.github.com/OmarElmekaalel/fece6f11dff216b6c33fb896681bbd01)
I run theme both on the same machine!

**Comment by OmarElmekaalel** [comment]
>           What ejabberd version? Try 18.12.1 too...
> Any errors in ejabberd.log?

 I installed the 18.09
[Ejabberd.log](https://gist.github.com/OmarElmekaalel/24ac64fb7de453aeb48c37a1578c231a)

**Comment by OmarElmekaalel** [comment]
Oh, yeah, I have readed it now, I'm pretty new to ejabberd, so I didn't pay attention to it.
in "www.letsencrypt.org" they are talking about "With shell access" and "Without shell access", and I didn't get that, is there any stepByStep tuto to do so?

**Comment by licaon-kter** [comment]
@OmarElmekaalel plenty on the internet yes, it depends on what type of access you have, via CPanel WHM web type or via shell console. Use your favourite search engine.

I like https://zerossl.com/free-ssl/#crt via DNS

**Comment by OmarElmekaalel** [comment]
Ok,this is turning me crazy, I got stocked at the second step (Verification), Now I got the csr file and key file.
What should I do next?

**Comment by OmarElmekaalel** [comment]
Ok, It works now, I have changed the certfile to another one(self signed using OpenSSL) and It connected to Psi manually.
