### ISSUE TITLE
ejabberd does not support http file upload for virtual host

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#2772]
ejabberd v18.09 its mod_http_upload requires that the put_url setting must use @HOST@; i.e. from online doc https://docs.ejabberd.im/admin/configuration/#mod-http-upload

> put_url: URL: This option specifies the initial part of the PUT URLs used for file uploads. The keyword @HOST@ is replaced with the virtual host name.

However not all the virtual hosts contain physical IP addresses for direct network access, hence virtual host without IP will fail http file upload.

**Comment by badlop** [comment]
You can use host_config to configure the module in specific hosts with specific options https://docs.ejabberd.im/admin/configuration/#virtual-hosting

What alternative do you propose?

**Comment by zinid** [comment]
> However not all the virtual hosts contain physical IP addresses for direct network access, hence virtual host without IP will fail http file upload

I fail to see how this is ejabberd problem. If you cannot add yet another DNS record of your virtual host pointing to some IP then how we can help? You still can use IP addresses in put_url of course, which is very stupid, but still possible.

**Comment by cmeng-git** [comment]
> You can use host_config to configure the module in specific hosts with specific options

Thanks for the proposal, but not sure which parameter of host_config to override the put_url.

Is there any reason the @host@ has to be uploading server?
If the configuration below is possible, then the virtual host upload support is possible  i.e.
put_url: "https://example.com:5443/@HOST@/upload"
Where example.com is the physical server with reachable IP

Actually I am using smack HttpFileUploadManager to implement file sharing. any change to the put_url IP mean I have to rewrite the class. I have thought of it, but does not like the idea.

**Comment by zinid** [comment]
> If the configuration below is possible, then the virtual host upload support is possible i.e.
> put_url: "https://example.com:5443/@HOST@/upload"

Yes, it should be possible.

**Comment by cmeng-git** [comment]
I tried but the server responses with error 404:

Error response 404 from server during file upload: Not Found, file size: 72588, put URL: http://atalk.sytes.net:5280/atalk.org/upload/bbe1d68b2217ca2b1bdb770463f50a9ac5015477/3cAAcg6skhfy4rggr3O11owFogOntS4pWfrE6ZiN/IMG-20180216-WA0012-1.jpg

**Comment by weiss** [comment]
My guess is that you're using something like this in your `ejabberd_http` listener configuration:

    request_handlers:
        "upload": mod_http_upload

If that's true, just change the `put_url` to `"https://example.com:5443/upload/@HOST@"` (i.e., swap the `upload` and `@HOST@` components of the URL).

**Comment by cmeng-git** [comment]
> If that's true, just change the put_url to "https://example.com:5443/upload/@HOST@" (i.e., swap the upload and @HOST@ components of the URL).

Yes, the http File Upload works for the virtual hosts with your proposed changes. Many thanks.

**Comment by ismailmohammed** [comment]
Hi,

I want put url should be virtual as below but i am getting error as Error requesting upload slot.

mod_http_upload:
    ##docroot: "/opt/ejabberd/upload/"
    ##docroot: "C:\\ProgramData\\ejabberd\\upload"
    ##put_url: "https://@HOST@:5443/upload"
    max_size: infinity
    service_url: "https://@HOST@/api/UserProfile/JabberUpload"  
i want @HOST@ to be replaced with requesting users host . 
please help.
Thanks in advance.

**Comment by weiss** [comment]
> i want `@HOST@` to be replaced with requesting users host .

This is not supported for the `service_url` option.  Apart from that, the `service_url` feature is deprecated, with recent ejabberd versions a `[warning]` will be logged on service startup.  Consider using the [external][1] interface instead.

[1]: https://github.com/processone/ejabberd/commit/fface33d54f24c777dbec96fda6bd00e665327fe

**Comment by ismailmohammed** [comment]
I already have external API enabled and it is working fine for one domain/ virtual host. Now i would like to use same ejabbered instance for another virtual host. Is there any better solution?

**Comment by ismailmohammed** [comment]
FYI.. some of the lines from my config.

hosts:
  - "AUD.com"
  - "AUD.net"
  - "Govtax.biz"

mod_http_upload:
    max_size: infinity
    service_url: "https://api.Aud.net/api/UserProfiles/JabberUpload"
    thumbnail: false # otherwise needs the identify command from ImageMagick installed
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
      "Access-Control-Allow-Headers": "Authorization"
      "Access-Control-Allow-Credentials": "true"
      ##"Access-Control-Allow-Headers": "Content-Type"

here I want to make Aud.net dynamic in service_url. 
Please give me some alternative solution to handle with diffrent hosts.

Thanks in advance.

**Comment by weiss** [comment]
You could search [the docs][1] for `append_host_config`.  But as I said [above][2], the `service_url` feature is depracated and will be removed from a future ejabberd release.

> I already have external API enabled 

Please read my comments properly.

[1]: https://docs.ejabberd.im/admin/configuration/
[2]: https://github.com/processone/ejabberd/issues/2772#issuecomment-489602281

**Comment by ismailmohammed** [comment]
Thanks for quick replay.
I understood your above comment but I am unable to get where and how we need to start changes.
I have changed my config put_url as below, 
  put_url: "https://api.@HOST@/api/UserProfiles/NewPutJabberFile"

and its hitting to my web Api as below
https://api.Govtax.biz/api/UserProfile/PutJabberFile/7c5b36797cdff5e62b9cb7b5c344f34f08f84c2f/YUnJBQApGn1pYxvck8xXCSExzqed1dohLvxLXBEa/12.jpg

here my question is how to get the image stream or content in API?

my web API looks as below,

[HttpPut]
        [Route("NewPutJabberFile/{jid}/{otherId}/{filename}")]
        [ProducesResponseType(typeof(int), 204)]
        public async Task<IActionResult> NewPutJabberFile(string jid,string otherId, string filename)
        {
            _logger.LogError("jid " + jid, ModelStateErrors.GetErrorList(ModelState));
            _logger.LogError("otherId " + otherId, ModelStateErrors.GetErrorList(ModelState));
            _logger.LogError("filename " + filename, ModelStateErrors.GetErrorList(ModelState));

            //_logger.LogError("Request " + Request, ModelStateErrors.GetErrorList(ModelState));
            //_logger.LogError("Request From " + Request.Form, ModelStateErrors.GetErrorList(ModelState));
            //_logger.LogError("Request Body " + Request.Body, ModelStateErrors.GetErrorList(ModelState));
            //_logger.LogError("Request headers " + Request.Headers, ModelStateErrors.GetErrorList(ModelState));
            using (var ms = new MemoryStream(2048))
            {
                await Request.Body.CopyToAsync(ms);
                 var filestream = ms.ToArray();  
                _logger.LogError("filestream " + filestream, ModelStateErrors.GetErrorList(ModelState));
 
            }

            return StatusCode((int)System.Net.HttpStatusCode.OK);

        }

Please help.

**Comment by ismailmohammed** [comment]
> You could search [the docs](https://docs.ejabberd.im/admin/configuration/) for `append_host_config`. But as I said [above](https://github.com/processone/ejabberd/issues/2772#issuecomment-489602281), the `service_url` feature is deprecated and will be removed from a future ejabberd release.

i have followed above configuration for append_host_config for individual hosts but i am getting below error.

 Problem starting the module append_host_config for host abc.com 
 options: [{<<"govtax.biz">>,
            [{modules,
                 [{mod_http_upload,
                      [{max_size,infinity},
                       {service_url,
                           <<"https://api.govtax.biz/api/UserProfile/JabberUpload">>},
                       {thumbnail,false},
                       {custom_headers,
                           [{<<"Access-Control-Allow-Origin">>,<<"*">>},
                            {<<"Access-Control-Allow-Methods">>,
                             <<"GET, POST, PUT, OPTIONS">>},
                            {<<"Access-Control-Allow-Headers">>,
                             <<"Authorization">>},
                            {<<"Access-Control-Allow-Credentials">>,
                             <<"true">>}]}]},
                  {mod_http_upload_quota,[{max_days,30}]}]}]}]
 error: undef
[{append_host_config,start,
     [<<"abc.com">>,
      [{<<"govtax.biz">>,
        [{modules,
             [{mod_http_upload,
                  [{max_size,infinity},
                   {service_url,
                       <<"https://api.govtax.biz/api/UserProfile/JabberUpload">>},
                   {thumbnail,false},
                   {custom_headers,
                       [{<<"Access-Control-Allow-Origin">>,<<"*">>},
                        {<<"Access-Control-Allow-Methods">>,
                         <<"GET, POST, PUT, OPTIONS">>},
                        {<<"Access-Control-Allow-Headers">>,
                         <<"Authorization">>},
                        {<<"Access-Control-Allow-Credentials">>,
                         <<"true">>}]}]},
              {mod_http_upload_quota,[{max_days,30}]}]}]}]],
     []},

below is my yml file configration.

append_host_config:
   "abc.com":
     modules:
       mod_http_upload:
         max_size: infinity
         service_url: "https://api.abc.net/api/UserProfiles/JabberUpload"
         thumbnail: false # otherwise needs the identify command from ImageMagick installed
         custom_headers:
           "Access-Control-Allow-Origin": "*"
           "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
           "Access-Control-Allow-Headers": "Authorization"
           "Access-Control-Allow-Credentials": "true"
           ##"Access-Control-Allow-Headers": "Content-Type"
       mod_http_upload_quota:
          max_days: 30
  append_host_config:
   "abc.net":
     modules:
       mod_http_upload:
         max_size: infinity
         service_url: "https://api.abc.net/api/UserProfiles/JabberUpload"
         thumbnail: false # otherwise needs the identify command from ImageMagick installed
         custom_headers:
           "Access-Control-Allow-Origin": "*"
           "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
           "Access-Control-Allow-Headers": "Authorization"
           "Access-Control-Allow-Credentials": "true"
           ##"Access-Control-Allow-Headers": "Content-Type"
       mod_http_upload_quota:
          max_days: 30
  append_host_config:
   "western.com":
     modules:
       mod_http_upload:
         max_size: infinity
         service_url: "https://api.western.com/api/UserProfiles/JabberUpload"
         thumbnail: false # otherwise needs the identify command from ImageMagick installed
         custom_headers:
           "Access-Control-Allow-Origin": "*"
           "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
           "Access-Control-Allow-Headers": "Authorization"
           "Access-Control-Allow-Credentials": "true"
           ##"Access-Control-Allow-Headers": "Content-Type"
       mod_http_upload_quota:
          max_days: 30
  append_host_config:
   "govtax.biz":
     modules:
       mod_http_upload:
         max_size: infinity
         service_url: "https://api.govtax.biz/api/UserProfile/JabberUpload"    		   
         thumbnail: false # otherwise needs the identify command from ImageMagick installed
         custom_headers:
           "Access-Control-Allow-Origin": "*"
           "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS"
           "Access-Control-Allow-Headers": "Authorization"
           "Access-Control-Allow-Credentials": "true"
           ##"Access-Control-Allow-Headers": "Content-Type"
       mod_http_upload_quota:
          max_days: 30

please help.
Thank you.

**Comment by weiss** [comment]
> `Problem starting the module append_host_config for host abc.com`

Remove all but the first occurrence of `append_host_config` from your configuration snippet above.

Anyway, this bug tracker is not an appropriate place to ask for support.
