### ISSUE TITLE
Query: Is there any way to support encrypted password while using MySQL as DB in ejabberd.

### ISSUE THREAD

**Issue by sinsharat** [processone/ejabberd#2777]
**Is your feature request related to a problem? Please describe.**
I am plannig to use MySQL as data store for ejabberd. But currently its storing passwords in plain text which most customers will have issue with.
**Describe the solution you'd like**
Just wanted to know is there anyway ejabberd provides in-built feature to store passwords in encrypted format.

**Describe alternatives you've considered**
I am still at exploring phase.

**Additional context**

**Comment by sinsharat** [comment]
Got the solution using SCRAM hence closing the same.

**Comment by Neustradamus** [comment]
@sinsharat: For have a better SCRAM ^^
-> https://github.com/processone/ejabberd/issues/2742
