### ISSUE TITLE
Query: Is it possible to login and get ejabberd XMPP connection by using external authentication

### ISSUE THREAD

**Issue by sinsharat** [processone/ejabberd#2782]
**Is your feature request related to a problem? Please describe.**
Need to perform authentication from main application for ejabberd login.

**Describe the solution you'd like**
I want to use ejabberd for chat as a part of my main application. The resgistration of user happens through main application.
Username and password are stored in the main application itself.
I need to simultaneously login to ejabberd as well when main app login is successful.
Is there any solution to use an external account for getting the XMPP connection?

**Describe alternatives you've considered**

**Additional context**

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/admin/configuration/#external-script

/close as invalid
