### ISSUE TITLE
rooms_unused_destroy destroys all rooms without history if uptime > given no of days

### ISSUE THREAD

**Issue by ChaosKid42** [processone/ejabberd#2787]
I believe I found a bug in `ejabberdctl rooms_unused`:

If a room has no history, then the system uptime seems to be used as a reference:

https://github.com/processone/ejabberd/blob/master/src/mod_muc_admin.erl#L789

This essentially means that all persistent rooms, without any history are destroyed if the number of days given on the command line is smaller than the uptime.

This seems to make sense on first sight (an empty history could mean that the last message is at least uptime days old.).

However there might be other reasons for an empty history:

- muc history could have been turned off altogether by config

- the room service could have been restarted without the whole server beeing restarted

I believe the only thing you can do is to *not* destroy rooms if there's no history.

**Comment by badlop** [comment]
> * muc history could have been turned off altogether by config

Ah, right! that case should be handled by the code, and rooms not removed due to lacking history, when history isn't stored at all.

> * the room service could have been restarted without the whole server beeing restarted

Well, it is a task of the admin to wait a few days/weeks after a _service_ restart before running that command, to allow potential users join the rooms and leave messages there. That is true regardless if _service_ means mod_muc, or all ejabberd. And it is also a task of giving an appropiate number of Days.

**Comment by ChaosKid42** [comment]
> > * the room service could have been restarted without the whole server beeing restarted
> 
> Well, it is a task of the admin to wait a few days/weeks after a _service_ restart before running that command, to allow potential users join the rooms and leave messages there. That is true regardless if _service_ means mod_muc, or all ejabberd. And it is also a task of giving an appropiate number of Days.

OK. Thema I suggest that this is pointed out explicitly in the documentatio.

Are there any other cases to consider? E.g. if a cluster node goes down the room might be restarted on another node. I'm not sure: Is the the history also cleared but the new node's uptime being considered for room destroy?

**Comment by badlop** [comment]
> Are there any other cases to consider? E.g. if a cluster node goes down the room might be restarted on another node. I'm not sure: Is then the history also cleared but the new node's uptime being considered for room destroy?

From what I know, room processes are not "migrated", they are simply recreated, which means a new room state, which means a new room history... but using the erlang node uptime, which is old. So, yes, a node going down is another case in which "purging rooms older than X" should wait X time after node closeup, because rooms will be recreated.

**Comment by mremond** [comment]
@badlop Wouldn't it be better to use "now" as timestamp in case the room is recreated ? 
In that case we would be on the safe side for the purge process.

**Comment by badlop** [comment]
Maybe I didn't understand that question. There is no information stored about room creation time or last activity (neither in the room #state or in the room erlang process). It would be possible to store the timestamp of room process creation/recreation somewhere (in the erlang process dictionary, or in room#state.just_created, or with a specific message in the room history...)

**Comment by mremond** [comment]
Yes, my point is that there is probably a way to avoid cleaning up those rooms. I am not sure what we are comparing to uptime, but then storing a timestamp may be helpful.

**Comment by badlop** [comment]
I've committed a feature that stores the room process creation in #state.just_create once it becomes false, and updated the code and the filtering accordingly.
