### ISSUE TITLE
Return the access_model and publish_model in Node Metadata

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2792]
As a client developer I'd like to know what are the access and publish models of the node I'm requesting metadata from. This allows me to adapt the UI of my client in consequences.

Return `pubsub#access_model` and `pubsub#publish_model` when requesting disco#info in the node (https://xmpp.org/extensions/xep-0060.html#entity-metadata)

The information are already in the ejabberd database.

I'll submit a patch to the XEP-0060 to add those information as well.

**Comment by cromain** [comment]
provided by 8a2b2668

**Comment by cromain** [comment]
duplicated by #2931
