### ISSUE TITLE
Feature Request: add to mod_shared_roster prefix or suffix users filter

### ISSUE THREAD

**Issue by tonal** [processone/ejabberd#2796]
**Is your feature request related to a problem? Please describe.**
We automatically create users for communication with site visitors.
Now such users are created with different prefixes depending on the site.
There are also groups of managers serving a specific site.
Now all managers see all created users.
I would like to be able to limit the visibility of users by managers.

**Describe the solution you'd like**
Group "all_user" with ```@all@``` visible for all manager groups

**Describe alternatives you've considered**
Add special values ```@prefix@SOME_PREFIX@``` for filter users for SOME_PREFIX,
Ок special values ```@regexp@SOME_REGEX@``` for filter users for SOME_REGEX.

**Comment by badlop** [comment]
I think you can already accomplish that:

1. You can define a vhost in ejabberd to match each site.
2. Create the users of each site in the corresponding vhost.
3. In each vhost, define a shared roster group called "all_users" with members @all@
4. Then in your core vhost (the one with the manager accounts), create a shared roster group for each vhost, called "managers_of_vhostX", with members the managers you want, and with display: all_users@vhostX
