### ISSUE TITLE
MUC offline messages with mod_offline_http_post

### ISSUE THREAD

**Issue by lakmalniranga** [processone/ejabberd#2797]
I'm using **mod_offline_http_post** to trigger HTTP request to my push service. It's working perfectly fine with one:one chats. But when it comes to MUC, offline messages are saving on spool. But mod_offline_http_post doesn't trigger a HTTP request. 

Is there any workaround to get this work.

I'm using ejabberd 18.09 on ubuntu 18.04.
mod_offline_http_post: https://github.com/PH-F/mod_offline_http_post

**Comment by mremond** [comment]
Hello @lakmalniranga 

This module is not part of ejabberd but is a custom module. It seems it makes more sense to ask that question to the developer of that module.
