### ISSUE TITLE
Add uniqueness to rostergroups MySQL schema.

### ISSUE THREAD

**Issue by mtdcr** [processone/ejabberd#2798]
Dear developers,

I'd like to propose the following modifications to rostergroups:

```
ALTER TABLE rostergroups
    MODIFY server_host VARCHAR(191),
    MODIFY grp VARCHAR(191),
    ADD UNIQUE (username, server_host, jid, grp);
```

This helps to reduce the number of queries needed when managing rostergroups of an organization externally with SQL, if you want to avoid duplicate entries.

**Comment by zinid** [comment]
Can you please post the resulting version of the table schema?

**Comment by mtdcr** [comment]
Here's the output of mysqldump:
<pre>CREATE TABLE `rostergroups` (
  `username` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `jid` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `grp` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  UNIQUE KEY `username` (`username`,`jid`,`grp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
</pre>

**Comment by zinid** [comment]
I don't think this change is possible, because a user may be a member of different groups.

**Comment by mtdcr** [comment]
The column `grp` is included in the unique key, so that's no problem.

By the way, I noticed that in the first post I used the new SQL schema, while the output of mysqldump shows the old SQL schema without `server_host`.

**Comment by zinid** [comment]
Sorry for the delay.
So, basically, you suggest to add an unique index, right?

**Comment by zinid** [comment]
We indeed need to add a unique index for performance.

**Comment by mtdcr** [comment]
Yes.
