### ISSUE TITLE
Regression: ejabberd 18.12.1 returns error response to node create if node is configured persistent and to not deliver payloads

### ISSUE THREAD

**Issue by Flowdalic** [processone/ejabberd#2799]
I finally found the time to update the ejabberd instance which is used as server counterpart for Smack's integration tests from 17.(04?) to 18.12.1. Now a PubSub integration tests fails: ejabberd 18.12.1 returns an  error response to an item publish request if the node is configured persistent and to not deliver payloads. This was not the case in the previous version I used, and hence is a regression.

@weiss kindly pointed to
 - https://github.com/processone/ejabberd/commit/a84dd0f627
 - https://github.com/processone/ejabberd/issues/2267
as potential related commit and issue.

While the spec is possibly not perfectly clear about that, I also believe that returning an error in this case is not specification compliant. Besides that aspect, I also see a use case for `pubsub#deliver_payloads=false` and `pubsub#persist_items=true` PubSub nodes.

The publish request - error response sequence:
```
13:14:56 SENT (1): 
<iq to='pubsub.salem.geekplace.eu' id='cwRAd-130' type='set'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <publish node='sinttest-simple-nodename-uhhr0'>
      <item xmlns='http://jabber.org/protocol/pubsub' id='sintest-simple-itemid-uhhr0'/>
    </publish>
  </pubsub>
</iq>
13:14:56 RECV (1): 
<iq xml:lang='en' to='smack-inttest-one-uhhr0@salem.geekplace.eu/one-uhhr0' from='pubsub.salem.geekplace.eu' type='error' id='cwRAd-130'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <publish node='sinttest-simple-nodename-uhhr0'>
      <item id='sintest-simple-itemid-uhhr0'/>
    </publish>
  </pubsub>
  <error code='400' type='modify'>
    <item-required xmlns='http://jabber.org/protocol/pubsub#errors'/>
    <bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
  </error>
</iq>
```

The node is configured as follows:
```
13:14:56 SENT (1): 
<iq to='pubsub.salem.geekplace.eu' id='cwRAd-128' type='set'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <create node='sinttest-simple-nodename-uhhr0'/>
    <configure>
      <x xmlns='jabber:x:data' type='submit'>
        <field var='FORM_TYPE' type='hidden'>
          <value>
            http://jabber.org/protocol/pubsub#node_config
          </value>
        </field>
        <field var='pubsub#deliver_payloads' type='boolean'>
          <value>
            false
          </value>
        </field>
        <field var='pubsub#persist_items' type='boolean'>
          <value>
            true
          </value>
        </field>
      </x>
    </configure>
  </pubsub>
</iq>
13:14:56 RECV (1): 
<iq xml:lang='en' to='smack-inttest-one-uhhr0@salem.geekplace.eu/one-uhhr0' from='pubsub.salem.geekplace.eu' type='result' id='cwRAd-128'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <create node='sinttest-simple-nodename-uhhr0'/>
  </pubsub>
</iq>
```

The relevant part of the (simple) test: https://github.com/igniterealtime/Smack/blob/ae208d6a2f608a69c54aae7cb2b22dc52524e9ff/smack-integration-test/src/main/java/org/jivesoftware/smackx/pubsub/PubSubIntegrationTest.java#L55-L65

**Comment by cromain** [comment]
The current behavior is compatible with this spec which is clear, if persist_items=true then event must include a payload:

> If the event type is persistent (either event notification or payload) and the publisher does not include an item, the service MUST bounce the publication request with a <bad-request/> error and a pubsub-specific error condition of <item-required/>.

This is the clause matching in your case, not related to change done for #2267.
What you ask is to relax this clause to allow publication without payload when deliver_payload is set to false. This could be seen as an edge case not defined in XEP-0060.

**Comment by Flowdalic** [comment]
> What you ask is to relax this clause to allow publication without item when deliver_payload is set to false if persist is true.

Actually no, after you pointed out that `persist_items=true` requires items with payload the current ejabberd behavior appears sensible (see also XEP-0060 Example 112).  Clients show not be allowed to publish itemless events on persisten items, even if `deliver_payload` is set to true.

Thanks for pointing this out. I am closing this issue.
