### ISSUE TITLE
Push token from push_session table cleared while recipient's network disconnected

### ISSUE THREAD

**Issue by skumarm** [processone/ejabberd#2802]
Hai..
I need a help on mod_push module.

We enabled mod_push on ejabberd server and setup push server based on the "Conversation Push Proxy" found on GitHub.

Push notification enable is working and push token is saved in push_session table. While disconnecting network, after 2-3 minutes the push token entry is cleared from the same table. Due to this offline messages are received on the recipient whose network disconnected. How could resolve this issue. ?

**Comment by weiss** [comment]
My guess would be that the "push proxy" is returning an error and `mod_push` therefore removing the token.  You could apply [a patch][1] to get a proper log message in this case, or enable debug logging (`ejabberdctl set-loglevel 5`) and search for an IQ error returned from the push proxy.

[1]: https://github.com/processone/ejabberd/commit/abdbc5df13230.patch

**Comment by skumarm** [comment]
> My guess would be that the "push proxy" is returning an error and `mod_push` therefore removing the token. You could apply [a patch](https://github.com/processone/ejabberd/commit/abdbc5df13230.patch) to get a proper log message in this case, or enable debug logging (`ejabberdctl set-loglevel 5`) and search for an IQ error returned from the push proxy.

Yes. I set loglevel as 5. But couldn't find any errors here.

**Comment by weiss** [comment]
It's not flagged as an `[error]`, it's an `<iq type='error' .../>` stanza.
