### ISSUE TITLE
ejabberd 18.09 external auth using php and mysql , add user to mnesia db also.

### ISSUE THREAD

**Issue by xabberd** [processone/ejabberd#2807]
Currently when using external auth all the operations related to use authentication are done from mysql db. But when server is restarted , the ejabberd registered_users command returns 0 users registered. This is probably because the ejabberd is configured to read user list from mnesia db. But when using external auth user is not added to mnesia. Please help.

This problem is resolved in ejabberd 15.07 by using extauth_cache parameter. But the same is not working in ejabberd 18.09. The new caching parameters are also not working as expected.

**Comment by badlop** [comment]
> But when server is restarted , the ejabberd registered_users command returns 0 users registered.

Right, when you configure
```yaml
auth_method: external
auth_use_cache: true
```
it will start caching authentications, so it's possible to get the list of accounts that have logged in since the last ejabberd start:
```
$ ejabberdctl registered_users localhost
user1
user2
```
That cache is kept in memory, not stored in database. So, as you noticed, the cache is empty after a server start. This is not a bug.

> The new caching parameters are also not working as expected.

Can you explain what parameter, how did you configure it, how did it behave in your case, and what did you expect it to do?

**Comment by xabberd** [comment]
Yes when auth_cache is used, the cache is in memory. I expected the parameters to cache the accounts in mnesia database also as it did in the ejabberd 15 version with external_cache parameter.

Is there any way to store auth data in mnesia?

And if not is there any way to change the database for admin rest API, and the command to return the correct number of users registered even after server restart?

**Comment by mremond** [comment]
Hi, I am not sure I understand the need. If you are managing your users outside of ejabberd, why are you asking ejabberd to give you the count of users ? Why don't you query your users service for that info ?

**Comment by xabberd** [comment]
yes i can definitely do that but problem comes when i am using rest apis to get the users list after server restart. Also web admin does not show up the users. Is there any way i can get the actual list in web admin and rest API's.?

**Comment by mremond** [comment]
No, at the moment, there is no way to have the list of users in admin when you are storing the users externally
