### ISSUE TITLE
Debian package systemd service files

### ISSUE THREAD

**Issue by nbruning** [processone/ejabberd#2809]
The debian package for ejabberd 19.02 seems to have an out-of-date service file.

In `/opt/ejabberd-19.02/bin/ejabberd.service`, there are no entries `ExecReload` or `TimeoutSec`, which have been added to the template a long time ago (https://github.com/processone/ejabberd/blob/master/ejabberd.service.template).

In general, is there any place we can find the scripts that generate the provided debian packages?

**Comment by mremond** [comment]
You can find the info here (including link to source package): https://packages.debian.org/stretch/ejabberd

**Comment by nbruning** [comment]
Hi @mremond,

I didn't mention it, but I was referring to the "official ejabberd packages", that can be downloaded from here: https://www.process-one.net/en/ejabberd/downloads

**Comment by mremond** [comment]
They are not generated with Debian tools but the tool also generating the installer, etc.
So, this is part of our internal toolchain. However, I will reopen the ticket so that we update the service file based on new templates.

**Comment by cromain** [comment]
This is indeed something I forgot to include in our packaging.

**Comment by cromain** [comment]
change included in packaging chain.
