### ISSUE TITLE
Raspbian: Binary Install Terminates

### ISSUE THREAD

**Issue by geraldhuba** [processone/ejabberd#2812]
**Ejabberd:**
ejabberd version: 19.02 (or lower revisions)
Installed from: official binary installer
   ./ejabberd-19.02-linux-aarch64.run (for RPi 3)
   ./ejabberd-19.02-linux-armhf.run  (for RPi 2)
**Hardware:** Raspberry Pi 3 or 2
**OS:** Raspbian GNU/Linux 9 (stretch) (9.8)

**Problem:** Official binary installer terminates before completion

**Example:**  pi@raspberrypi:~ $ ./ejabberd-19.02-linux-aarch64.run
  / installing ejabberd-19.02...
  / * Configure ejabberd installation
  / * Set default config in conf/ejabberd.yml
  / * Terminate ejabberd installation

**Logs:**  No logs

**Version Information:**
dpkg -l | grep libc6   ---> 2.24-11+deb9u4 
dpkg -l | grep erlang  ---> 1:19.2.1+dfsg-2+deb9u2

**Packages installed** in unsuccessful attempts to resolve problem:
sudo apt-get install make make gcc erlang-nox libexpat1 libyaml-0-2 erlang libssl-dev zlib1g-dev imagemagick libexpat1-dev autoconf libghc-yaml-dev

**Compiling from Source** , ejabberdctl status command (after ejabberdctl start) results in:
"Failed RPC connection to the node ejabberd@localhost: nodedown"   I assume this is a separate issue but reporting as observation.

Thanks in advance
geraldhuba

**Comment by licaon-kter** [comment]
`Raspbian` is not arm64 since they want it to be compatible with RPi1&2 too and those are armv6 so 32bit only.

/close as invalid

FYI, you can build from source or install 18.12.1 from the `testing` repo.

**Comment by geraldhuba** [comment]
Ah, so the Linux ARM64 Installer is for the RPi3, but not for Raspbian(yet)!  Thanks for pointing that out.  I will try SUSE 64bit OS for the RPi3.

**Comment by licaon-kter** [comment]
Also Debian has one: https://wiki.debian.org/RaspberryPi3

But, you'll need to build the arm64 Raspbian kernel in order to get stuff fixed (cpu freq at least): https://github.com/Debian/raspi3-image-spec/issues/12

**Comment by geraldhuba** [comment]
I am closing this issue as invalid due to 64bit binary install testing done on RPi3(64bit hardware) with Raspbian (32bit) OS and 32bit binary install testing was unintentionally done on Rpi 1 (B+)  instead of RPi 2.
Thanks for comments.
