### ISSUE TITLE
Windows - erl.exe crashing while installation or execution - Visual Studio DLL Issue

### ISSUE THREAD

**Issue by GuestNo1** [processone/ejabberd#2817]
Hello,

setted up some Windows Server 2016 1605 with ejabberd 19.02.
Setup was flawlessly, Logs without issues.

After upgrading Visual Studio 2017 14.16.27027 I encountered the issue that the erl.exe keeps stopping while execution.
Updating to different Visual Studio versions did not helped me out at the moment.
Deinstallation of Visual Studio did not helped aswell - the reasonable file is not getting replaced!
Deinstallation of ejabberd, and installation of 19.02 again only showed up that the erl.exe crashes again while executing the postinstallation script.
Only solution for the moment is to load a previous backup (maybe to manually replace the DLLs mentioned next can do the trick if you got the working DLLs).

My research showed that with 16.11 and Visual Studio back than there is already an issue posted here on GitHub [https://github.com/processone/ejabberd/issues/1373](#1373), explaining ejabberd needs the msvcr120.dll and mscvr100.dll.
The issue was marked as solved and ejabberd was supposed to have both build-in in future releases(?).

Anyways:
This needs to get fixed ASAP,
because some Server need VC ... I can not let of VC nor ejabberd...

Thanks

**Comment by cromain** [comment]
The installer includes msvcr120.dll, which should be located in ProgramFiles\ejabberd-19.02\bin
I'm not a windows user so I just wonder if installing VC can alter some environement to force load of it's own (more recent) DLL always.
- Does Windows allow installation of several versions of that DLL ?
- Why after installing/upgrading VC ejabberd does not load included msvcr120.dll ?
I guess that all depends on how binary ask OS about loading a DLL. If included bash.exe behaves correctly, I think you can try add this line in ejabberdctl around line 80
{code}
export LD_LIBRARY_PATH="$ROOT_DIR/bin"
{code}
