### ISSUE TITLE
Custom Module is not working with 19.02

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#2818]
Environment
-----------
- ejabberd version: 19.02
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 8.1
- OS: Linux (Ubuntu 16.04.5 LTS)
- Installed from: source 

Configuration (new module): 
---------------------------------------------------------------------------
```yaml
mod_hello: {}
...
```

Errors from ejabberd live:
-------------------------------
[error] Invalid value for option 'db_type' of module mod_hello: mnesia
[critical] ejabberd initialization was aborted because a module start failed.

The module callback function like this:
-------------------------------
```erlang
mod_opt_type(db_type) -> fun(T) -> ejabberd_config:v_db(?MODULE, T) end.

mod_options(Host) ->
    [{db_type, ejabberd_config:default_db(Host, ?MODULE)}].
```

My custom module worked fine on ejabberd 17.01, i just want to migrate them  from ejabberd 17.01 to 19.02, i compiled them on the new environment, but start the ejabberd, it's not working.

**Comment by cisiqo** [comment]
I saw the [#2174](https://github.com/processone/ejabberd/issues/2174), it's work now, but it not convenient.

**Comment by cisiqo** [comment]
Ohhhhh...... I think the problem solved, but when i custom a param on the module like this:
```
mod_opt_type(auth_token) ->
    fun (T) when is_binary(T)  -> T end.

mod_options(_Host) ->
    [{auth_token, "User_post_auth_token"}].
```

I compiled and ejabberd live, the error comeback

```
[error] Invalid value for option 'auth_token' of module mod_XXX: User_post_auth_token
[critical] ejabberd initialization was aborted because a module start failed.
```

**Comment by zinid** [comment]
That's because a string is not a binary. Read Erlang manual or something.
