### ISSUE TITLE
mod_ping send_pings behaviour changed between 18.12.1 and 19.02

### ISSUE THREAD

**Issue by varmando** [processone/ejabberd#2820]
When mod_ping set with send_pings: true, ejabberd version 18.12.1 sends pings every minute by default even when ping target doesn't respond (expected), but with version 19.02 it sends only one ping when ping target doesn't respond to pings and no more pings after that.

**Comment by cromain** [comment]
@badlop can you check why this changed ? is it a regression or a feature ?

**Comment by badlop** [comment]
It was introduced in mod_ping's latest change: https://github.com/processone/ejabberd/commit/dd57950103f960da32fc8988835af5209f47c78a

**Comment by mremond** [comment]
ah, it seems that change is not correct then.
