### ISSUE TITLE
Is there any way to encrypt the code of erlang part ?

### ISSUE THREAD

**Issue by dingdongnigetou** [processone/ejabberd#2825]
All i know is to remove the debugs info from beam file, but is it possible to recover raw code from beam with op code ?

**Comment by mremond** [comment]
It is not related to ejabberd, right ?

**Comment by dingdongnigetou** [comment]
> It is not related to ejabberd, right ?

Actually i need to do some obscure on ejabberd, to prevent some one crack the code.

**Comment by zinid** [comment]
But the answer can be found in Erlang documentation.

**Comment by dingdongnigetou** [comment]
ok, thanks
