### ISSUE TITLE
mod_http_upload is not case-insensitive for put_url option

### ISSUE THREAD

**Issue by joudinet** [processone/ejabberd#2827]
Hi,
After renaming my host to a name with uppercase letters, I notice mod_http_upload was not working anymore. Here the error message:
```
2019-03-14 11:20:16.066 [error] <0.6451.0>@mod_http_upload:process:418 Cannot handle PUT request from ::ffff:127.0.0.1 for yoi-2.gnyoi.com: {'EXIT',{noproc,{gen_server,call,['mod_http_upload_yoi-2.gnyoi.com/upload',{use_slot,[<<"d885aee31889259f8874fdd6ebfa263b2d4bf7b5">>,<<"uNgeVzDbfvTcUnKFguuoSEdMhMwpixa5W29r7okg">>,<<"588C9E94-253B-4429-873B-2115DEB82262.jpeg">>],1246068},60000]}}}
```
`put_url` is set to "https://YOI-2.gnyoi.com/upload"

I'm going to change my script to make sure I set put_url to only lowercase letters but I think this should be at least mention in the documentation of `put_url` or handle in the code. Quoting rfc 4343:
> According to the original DNS design decision, comparisons on name lookup for DNS queries should be case insensitive. That is to say, a lookup string octet with a value in the inclusive range from 0x41 to 0x5A, the uppercase ASCII letters, MUST match the identical value and also match the corresponding value in the inclusive range from 0x61 to 0x7A, the lowercase ASCII letters.  A lookup string octet with a lowercase ASCII letter value MUST similarly match the identical value and also match the corresponding value in the uppercase ASCII letter range.

**Comment by zinid** [comment]
Well, you're citing a wrong RFC, the "registered name" of an URI component is described in RFC 3986:
> Although host is case-insensitive, producers and normalizers should use lowercase for registered names and hexadecimal addresses for the sake of uniformity, while only using uppercase letters for percent-encodings.

But yeah, this should be fixed.
