### ISSUE TITLE
MucSub sending and receiving too much latency and some crashes

### ISSUE THREAD

**Issue by gylraj** [processone/ejabberd#2829]
Environment
-----------
- ejabberd version: 18.12.1
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2`
- OS: Linux (Ubuntu)
- Installed from:  official deb/rpm

sample of error
exception exit: {{process_limit,{max_queue,14673}},[{p1_server,terminate,7,[{file,"src/p1_server.erl"},{line,864}]},{p1_server,loop,9,[{file,"src/p1_server.erl"},{line,412}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    
can you give me some idea to fix this error?

crash.log, ejabberdctl.cfg, ejabberd.yml and MySQL Server Info
https://gist.github.com/gylraj/c7a965412a61531d78032c2b15267474

**Comment by zinid** [comment]
I think #2824 is related.

**Comment by zinid** [comment]
The author of the previous issue didn't reply, please try:
```
$ grep 'transaction called at' /path/to/ejabberd.log
```

**Comment by zinid** [comment]
Okay, no additional info is required, see my comment: https://github.com/processone/ejabberd/issues/2824#issuecomment-473362358
