### ISSUE TITLE
Hook webadmin_page_main crashed when running mod_muc_admin:web_page_main/2

### ISSUE THREAD

**Issue by th3g0dfa1h3r** [processone/ejabberd#2830]
Ejabberd version: 19.02

Installed by dpkg.

Error like in here, 
https://github.com/processone/ejabberd/issues/1753 
I made everything exactly like him, getting this error:

```

Reason = {error,badarg,[{erlang,atom_to_binary,[1552729524057720,utf8],[]},
{misc,atom_to_binary,1,[{file,"src/misc.erl"},{line,198}]},{mod_muc_admin,prepare_room_info,1,
[{file,"src/mod_muc_admin.erl"},{line,593}]},{mod_muc_admin,'-prepare_rooms_infos/1-lc$^0/1-0-',1,
[{file,"src/mod_muc_admin.erl"},{line,577}]},{mod_muc_admin,make_rooms_page,3,
[{file,"src/mod_muc_admin.erl"},{line,494}]},{mod_muc_admin,web_page_main,2,
[{file,"src/mod_muc_admin.erl"},{line,460}]},{ejabberd_hooks,safe_apply,4,
[{file,"src/ejabberd_hooks.erl"},{line,381}]},{ejabberd_hooks,run_fold1,4,
[{file,"src/ejabberd_hooks.erl"},{line,365}]}]}

```

**Comment by th3g0dfa1h3r** [comment]
Plus, when I am changing default host, to "hosts" with two value (i.e "public_group", "private_group"), I am  getting "Not found" when pressing at Multi user chat

**Comment by badlop** [comment]
Oh, this is provoked by this commit: https://github.com/processone/ejabberd/commit/e18522f74ceaae87885d2265a6fea6e063e23aa3 I've fixed it now in mod_muc_admin.
