### ISSUE TITLE
Cannot start ejabberd using ejabberd_app:start(normal,[]).

### ISSUE THREAD

**Issue by gilons** [processone/ejabberd#2831]
when trying to start ejabberd i  have this error  

`CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls...."}) in erl_ddll:format_error/1 line 239
00:11:47.683 [error] Supervisor fast_tls_sup had child fast_tls started with fast_tls:start_link() at undefined exit with reason bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls...."}) in erl_ddll:format_error/1 line 239 in context start_error
00:11:47.683 [error] CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen..."},...]},...]}}},...} in application_master:init/4 line 134
00:11:47.683 [info] Application fast_tls exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen..."},...]},...]}}},...}
00:11:48.002 [info] Application asn1 started on node nonode@nohost
00:11:48.003 [info] Application public_key started on node nonode@nohost
00:11:48.015 [info] Application pkix started on node nonode@nohost
00:11:48.035 [info] Application fast_xml started on node nonode@nohost
00:11:48.042 [info] Application stringprep started on node nonode@nohost
00:11:48.043 [error] CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls...."}) in erl_ddll:format_error/1 line 239
00:11:48.043 [error] Supervisor fast_tls_sup had child fast_tls started with fast_tls:start_link() at undefined exit with reason bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls...."}) in erl_ddll:format_error/1 line 239 in context start_error
00:11:48.044 [error] CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen..."},...]},...]}}},...} in application_master:init/4 line 134
00:11:48.044 [info] Application fast_tls exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen..."},...]},...]}}},...}
00:11:48.044 [error] CRASH REPORT Process <0.288.0> with 0 neighbours exited with reason: {{fast_tls,{{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,...},...]}}},...}},...} in application_master:init/4 line 134
`

please can someone help me to figure out what is happening here ?

**Comment by zinid** [comment]
Since you ignored the pattern and didn't report what OS you're using, ejabberd version and the installation source we cannot help you much.
