### ISSUE TITLE
Suggestion or help needed for fully integrating XMPP on an app with registered users

### ISSUE THREAD

**Issue by gujjubola** [processone/ejabberd#2832]
We have a social networking application where people have contacts and we want to integrate a real-time application. As I am new to XMPP there are some question I need help with. Till now I have installed ejabberd server and also calling registering user from REST API and terminal. But the user gets stored in the ejabberd database. Attaching the yml configuration file for your information
[ejabberd.yml.zip](https://github.com/processone/ejabberd/files/2976832/ejabberd.yml.zip)

Technologies used are:
 1. Node.JS
 2. Ejabberd as XMPP server
 3. MySQL Database
 4. React-Native (Front-End)
 5. OS - Ubuntu 18.04

Here are my questions:

 1. Create user account. I want to implement that, while registering the account there will be an authentication key will be generated and will be stored in my database. Example: When a user login an authentication will be generated and stored in the users schema of database and user can be connected with the authentication key. Also I don't need to create any database where ejabberd server is running. 

 2. How to implement ejabberd server with my existing database. I guess by sql auth configuration I need to create tables in my database server. But is there any way where I can't select both database, schema and fields to authenticate?  

Any help regarding this topic will be appreciated. Thanks in advance.

**Comment by licaon-kter** [comment]
Configuring ejabberd | ejabberd Docs - https://docs.ejabberd.im/admin/configuration/#external-script ?

**Comment by gujjubola** [comment]
@licaon-kter Thanks a lot for the reply. Just one more question. Do I need to make new tables in that database for contacts and message to store data or will be able to point to exisiting database with different name?
