### ISSUE TITLE
unable to start ejabberd with  ejabberd_app:start(normal,[]). 

### ISSUE THREAD

**Issue by gilons** [processone/ejabberd#2833]
hello . 
when trying to start ejabberd in the shell with ejabberd_app:start(normal,[])  i'm getting the error

 `10:31:32.554 [error] CRASH REPORT Process <0.276.0> with 0 neighbours crashed with reason: bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd-18.06/deps/fast_tls/priv/lib/fas..."}) in erl_ddll:format_error/1 line 239
10:31:32.554 [error] Supervisor fast_tls_sup had child fast_tls started with fast_tls:start_link() at undefined exit with reason bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library: '/home/fokam/ejabberd-18.06/deps/fast_tls/priv/lib/fas..."}) in erl_ddll:format_error/1 line 239 in context start_error
10:31:32.554 [error] CRASH REPORT Process <0.273.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd-18.06/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,490}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,91}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,...},...]},...]}}},...} in application_master:init/4 line 134
10:31:32.555 [info] Application fast_tls exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library: '/home/fokam/ejabberd-18.06/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,490}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,91}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,...},...]},...]}}},...}
10:31:32.555 [critical] failed to start application 'fast_tls': {error,
                                         {{shutdown,
                                           {failed_to_start_child,fast_tls,
                                            {badarg,
                                             [{erl_ddll,format_error_int,
                                               [{load_failed,
                                                 "Failed to load NIF library: '/home/fokam/ejabberd-18.06/deps/fast_tls/priv/lib/fast_tls.so: undefined symbol: OPENSSL_init_ssl'"}],
                                               []},
                                              {erl_ddll,format_error,1,
                                               [{file,"erl_ddll.erl"},
                                                {line,239}]},
                                              {fast_tls,load_nif,1,
                                               [{file,"src/fast_tls.erl"},
                                                {line,490}]},
                                              {fast_tls,init,1,
                                               [{file,"src/fast_tls.erl"},
                                                {line,91}]},
                                              {gen_server,init_it,2,
                                               [{file,"gen_server.erl"},
                                                {line,365}]},
                                              {gen_server,init_it,6,
                                               [{file,"gen_server.erl"},
                                                {line,333}]},
                                              {proc_lib,init_p_do_apply,3,
                                               [{file,"proc_lib.erl"},
                                                {line,247}]}]}}},
                                          {fast_tls_app,start,[normal,[]]}}}
`
i'm using ubuntu 18..04 
the the version of ejabberd is ejabberd-18.06
please can some one help me?

**Comment by gilons** [comment]
i'm using otp 20

**Comment by gilons** [comment]
Erlang/OTP 20

**Comment by zinid** [comment]
Well, this is an installation problem. Please consider to install recent ejabberd version instead of build it. You have a problem with openssl version or some such.

**Comment by gilons** [comment]
i will like to use it as part of a project 
so i have to make some links from it to my application

**Comment by gilons** [comment]
please which version of open ssl was used let me install it

**Comment by gilons** [comment]
and add as my dependency.

**Comment by gilons** [comment]
i installed the latest version of openssl but still not working.

**Comment by badlop** [comment]
Hi! Is your problem solved? Have you tried with the recent ejabberd 19.02?
