### ISSUE TITLE
ejabberd_auth_external:failure:103 External authentication program failed when calling 'check_password'

### ISSUE THREAD

**Issue by gujjubola** [processone/ejabberd#2835]
I already have a schema of users with authentication-key and wanted to do authentication via that. I tried implementing authentication via sql but due to different structure of my schema I was getting error and so I implemented external-authentication method. The technologies and OS used in my application are : 

- Node.JS
- Ejabberd as XMPP server
- MySQL Database
- React-Native (Front-End)
- OS - Ubuntu 18.04

I implemented the external authentication configuration as mentioned in https://docs.ejabberd.im/admin/configuration/#external-script and took php script https://www.ejabberd.im/files/efiles/check_mysql.php.txt as an example. But I am getting the below mentioned error in error.log. Also is there any external auth javascript script ?

> 2019-03-19 07:19:16.814 [error] <0.524.0>@ejabberd_auth_external:failure:103 External authentication program failed when calling 'check_password' for admin@example.org.co: disconnected 

Any help regarding this topic will be appreciated. Attaching the yml, ejabberd.log file, error.log and php file for refrence
[ejabberd.log](https://github.com/processone/ejabberd/files/2982127/ejabberd.log)
[error.log](https://github.com/processone/ejabberd/files/2982128/error.log)
[ejabberd.yml.zip](https://github.com/processone/ejabberd/files/2982141/ejabberd.yml.zip)
[JabberAuth.class.php.zip](https://github.com/processone/ejabberd/files/2982142/JabberAuth.class.php.zip)

**Comment by zinid** [comment]
Disconnected means your external script has terminated unexpectedly.
Since the functionality is covered in TravisCI and I don't see any regressions, I close the ticket until a proof is provided that demonstrates the bug.
