### ISSUE TITLE
Administration API simplest case, doesn't work for me

### ISSUE THREAD

**Issue by malachib** [processone/ejabberd#2840]
I'm attempting more or less a boilerplate invocation of the Administration API, following guidelines set here: https://docs.ejabberd.im/developer/ejabberd-api/simple-configuration/

I attempt to issue a `check_account` command, and get an error code:

`Command need to be run with admin priviledge`

I was expecting "With that setup you can call ejabberd commands through API" to be true as described in the section.  Running my `curl` test on same localhost as `ejabberd` itself.  

Additionally, when attempting to connect from my .NET Core client, it actually aborts the connection.  This confuses me, and seems like a .NET Core issue not ejabberd, but maybe someone can give me some guidance on that as well

Please advise.  Thank you

ENVIRONMENT:

debian, running ejabberd v16.09-4 as supplied by apt-get

**Comment by licaon-kter** [comment]
Use `stretch-backports` repo, get 18.12.1 and retry, as your version is no longer supported.

**Comment by malachib** [comment]
That did it.  Thank you <3
