### ISSUE TITLE
MQTT - interoperable?

### ISSUE THREAD

**Issue by malachib** [processone/ejabberd#2841]
I was getting the impression MQTT and XMPP messages could interoperate with one another (i.e. send an XMPP and get an MQTT notification). As nearly as I can tell though they are parallel universes.  Did I misunderstand?

**Comment by licaon-kter** [comment]
If you set up something like that....maybe...but not by default afaik.

**Comment by malachib** [comment]
I'm a newcomer to XMPP and `ejabberd` world.  How involved is setting something like that up?

**Comment by zinid** [comment]
You cannot interoperate so far, the only common stuff at the moment is a single authentication backend.

**Comment by malachib** [comment]
Alright, thank you.  How about SIP?  I am trying to get a .NET Core backend to talk to `ejabberd` as a client, and the state of XMPP libs is .NET is ... well ... a mess

**Comment by licaon-kter** [comment]
Same for SIP (remember you need credentials NOT setup as SCRAM).

**Comment by zinid** [comment]
Same thing. SIP was introduced in ejabberd in context of [CUSAX](https://tools.ietf.org/html/rfc7081), i.e. using XMPP for chat and SIP for A/V calls. The current state of the standards doesn't allow you to use a single protocol for both chat and A/V.

**Comment by malachib** [comment]
Damn.  Last I checked, SIP did have a standard text-message style facility, and I think some presence stuff too.  I was hopeful.  Thanks for the answers

**Comment by zinid** [comment]
@malachib well formally speaking your statement is correct. However, when you start doing this in **practice** you will quickly face a lot of problems.

**Comment by malachib** [comment]
> @malachib well formally speaking your statement is correct. However, when you start doing this in **practice** you will quickly face a lot of problems.

No argument.  I worked at a company doing NG911/SIP and it is not for the faint of heart.  Still, `ejabberd` is so badass, I thought maybe....

**Comment by mremond** [comment]
@malachib Further integration will come over time. We introduce new protocol in ejabberd to make them play nice together. That's a lot of work and requires a lot of coordination, but that's the plan.
