### ISSUE TITLE
"failed to process iq" on login

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2844]
HEAD: https://github.com/processone/ejabberd/commit/9b040f65a307a438d9e8574f1f6d4fac838277f5 (19.02.36)

Debian Buster, arm64

Log: https://gist.github.com/licaon-kter/a616ee55c5bfc3ee0b7ab692bff29f21

`Hook muc_process_iq crashed when running mod_mam:muc_process_iq/2:` is repeated for each MUC the user is joined.

**Comment by licaon-kter** [comment]
Went back to 19.02.29 just in case the error messes up something else too.

**Comment by prefiks** [comment]
This should be fixed by7eef966a04456600e1c77f6e97bc2e9772aa128b, i didn't test my changes with new schema option...
