### ISSUE TITLE
XEP-0198: Stream Management

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2845]
Any news about this XEP-0198 support?
-> https://xmpp.org/extensions/xep-0198.html

This XEP-0198 is listed in XEP-0412: XMPP Compliance Suites 2019
-> https://xmpp.org/extensions/xep-0412.html

**Comment by licaon-kter** [comment]
What's missing ( https://github.com/processone/ejabberd/blob/master/src/mod_stream_mgmt.erl ), the error conditions or what?

**Comment by mremond** [comment]
Stream management is already supported and has been for many years.

**Comment by Neustradamus** [comment]
-> https://github.com/processone/ejabberd/pull/1969

**Comment by Neustradamus** [comment]
Any news?
