### ISSUE TITLE
Losing messages when send messages XMPP

### ISSUE THREAD

**Issue by mohammadtrigger** [processone/ejabberd#2848]
When sending messages from client A to a client B who still has an online presence and at the same time shut down the XMPP connection on Client B the message lost and never delivered to the Client B and I'm sure that the message came out of server-side and goes to client B but shutting down the connection in parallel with sending a message cause to losing this message ... how to solve this issue or avoid losing the message ?! Any suggestion, please !!

Stream management not work on this case because client B still has an online presence when the client A sent the message

**Comment by badlop** [comment]
For reference: also asked here: https://stackoverflow.com/questions/55471233/losing-messages-when-send-messages-using-smack

**Comment by zinid** [comment]
Since the author didn't fill out the issue as appropriate (what version? what config? lord knows), I close it because it won't attract a lot of attention.
