### ISSUE TITLE
Could not load module C:Program Filesejabberd-19.02/bin\erlexec.dll.

### ISSUE THREAD

**Issue by a-jahanshahlo** [processone/ejabberd#2849]
Why this error occur on windows server 2008?
look at to this line of error :
Could not load module C:Program Filesejabberd-19.02/bin\erlexec.dll.

the path on here `Filesejabbered`  concatenate!
why show me above error on installation?

**Comment by licaon-kter** [comment]
Ejabberd.log?

**Comment by badlop** [comment]
I close thsi ticket because a month has passed without more details about the problem.
