### ISSUE TITLE
PEM decoder doesn't support CRLF line termination (was: GoDaddy SSL Certificate)

### ISSUE THREAD

**Issue by cimframe** [processone/ejabberd#2850]
I have a new SSL certificate from GoDaddy.  I followed the instructions to create the .pem file, but the response I get when I start ejabberd is "no matching private key found for this certificate".  I took the private key that was generated when I created the CSR.  GoDaddy gave me the ssl certificate and a chain file.  I have concatenated these files per the instructions and it doesn't want to load.

cat privatekey.key >> ejabberd.pem
cat ssl.crt >> ejabberd.pem
??? cat bundle.crt >> ejabberd.pem ???

I have tried it with and without the bundle file.

Any suggestions?

**Comment by zinid** [comment]
Try without concatenation:
```yaml
certfiles:
  - "/path/to/bundle.crt"
  - "/path/to/ssl.crt"
  - "/path/to/privatekey.key"
```
And check ejabberd.log for warnings.

**Comment by cimframe** [comment]
Thanks for such a quick response!!!!

I have a self-signed cert that works fine.  But, I want to use the GoDaddy cert because I don't want the red https:// of death to show.  I did as you suggested, but it complained about the private key not being in PEM format, which it is.  I changed the order and no matter what file is at the top of the list, it complains about PEM format.  All three files are definitely in PEM format...

**Comment by cimframe** [comment]
I ran a check and the private key (a PEM file!!!) matches the certificate generated from the CSR.  Everything is in PEM format.  What else can be done?

I still get "Failed to read PEM file /opt/ejabberd/cert/ejabberd.pem: at line 29: no matching private key found for this certificate"

**Comment by licaon-kter** [comment]
@cimframe Are the permissions ok?

What do `sudo -u ejabberd stat <pemfile>` say? (If you run it as user `ejabberd` that is)

**Comment by zinid** [comment]
1. What ejabberd version?
2. What **EXACT** error/warning does ejabberd produce?

**Comment by cimframe** [comment]
I am running version 18.12.1 on Ubuntu 18.10


This is the main cert file:

root@jabber:/opt/ejabberd/cert# sudo -u ejabberd stat 559a9701480def34.crt 
  File: 559a9701480def34.crt
  Size: 2216      	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 6949600     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-03 11:50:24.964794665 -0700
Modify: 2019-04-03 11:46:21.028751690 -0700
Change: 2019-04-03 11:46:21.028751690 -0700
 Birth: -

This is the GoDaddy chain file:

root@jabber:/opt/ejabberd/cert# sudo -u ejabberd stat gd_bundle-g2-g1.crt 
  File: gd_bundle-g2-g1.crt
  Size: 4795      	Blocks: 16         IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 6949602     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-03 11:50:31.396902867 -0700
Modify: 2019-04-03 11:46:21.028751690 -0700
Change: 2019-04-03 11:46:21.028751690 -0700
 Birth: -

This is the private key file:
root@jabber:/opt/ejabberd/cert# sudo -u ejabberd stat privatekey.key 
  File: privatekey.key
  Size: 1707      	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 6949604     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-03 11:49:33.607933263 -0700
Modify: 2019-04-03 11:46:25.700827823 -0700
Change: 2019-04-03 11:46:25.700827823 -0700
 Birth: -

This is a version of the concatenated files:
root@jabber:/opt/ejabberd/cert# sudo -u ejabberd stat ejabberd.pem 
  File: ejabberd.pem
  Size: 3932      	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 6949603     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-03 15:35:23.548041527 -0700
Modify: 2019-04-03 15:35:05.903596306 -0700
Change: 2019-04-03 15:35:15.407836250 -0700
 Birth: -

Here is ejabberdctl live's output:

root@jabber:/opt/ejabberd/conf# ejabberdctl live
Eshell V10.1  (abort with ^G)
(ejabberd@localhost)1> 07:51:40.876 [notice] Changed loghwm of /opt/ejabberd/logs/error.log to 100
(ejabberd@localhost)1> 07:51:40.876 [notice] Changed loghwm of /opt/ejabberd/logs/ejabberd.log to 100
(ejabberd@localhost)1> (ejabberd@localhost)1> 07:51:41.028 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
**(ejabberd@localhost)1> 07:51:41.941 [error] Failed to read PEM file /opt/ejabberd/cert/privatekey.key: no PEM encoded certificate or private key found
(ejabberd@localhost)1> 07:51:41.941 [critical] ejabberd initialization was aborted due to invalid certificates configuration**
(ejabberd@localhost)1> =INFO REPORT==== 4-Apr-2019::07:51:41.943760 ===
    application: lager
    exited: stopped
    type: temporary

**Comment by zinid** [comment]
> [error] Failed to read PEM file /opt/ejabberd/cert/privatekey.key: no PEM encoded certificate or private key found

Could you show the first and the last line of that file? It's pretty safe. Does it have Unix terminated (LF) lines? Try `$ dos2unix /opt/ejabberd/cert/privatekey.key`

**Comment by cimframe** [comment]
Well, converting the files had a tremendous effect!  It reads the cert and key files now!!  Thanks!

**Comment by zinid** [comment]
I think this is a bug worth fixing.

**Comment by zinid** [comment]
According to [RFC7468](https://tools.ietf.org/html/rfc7468):
> Furthermore, parsers ... MUST handle different newline conventions.
> ... lines are divided with CRLF, CR, or LF;
