### ISSUE TITLE
ejabberd.yml installer is not synchronized with ejabberd.yml.example

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2854]
ejabberd.yml installer is not synchronized with ejabberd.yml.example, for each release, the installer must be synchronized with the actual ejabberd.yml.example file, for be up-to-date :)

**Comment by cromain** [comment]
Installer's ejabberd.yml must not be synchronized at every release. While example file can include some new feature changes or default changes, we don't always want them in standard configuration we include in the installer. Installer includes good default production configuration, while config example is... an example which can be ahead of good production config.
