### ISSUE TITLE
Mod_shared_roster - missing roster update on contact removal via server

### ISSUE THREAD

**Issue by gallinodeluxe** [processone/ejabberd#2857]
Using ejabberd 18.01 with Converse.js. 

If I add a contact (server-side) in a shared roster group and refresh the contact list, it's all ok.

If I remove a contact (server-side) in a shared roster group and refresh the contact list, the removed contact is still there.

It seems that ejabberd doesn't send a "remove" item to the client. It sends only the remaining contacts. This way Converse (compliant to XEP-0144) never remove the removed contact.

RFC 6121 says the server should send a "roster push" to a client when an item of its roster is created, updated or deleted, so I think this could be a bug.

**Comment by badlop** [comment]
I've downloaded ejabberd 18.01 source code, compiled, installed, created an account **user1**, granted admin rights, logged in with Tkabber client and also in webadmin, created a shared roster group called **tech** with display: **tech**, and added as members that account and several other accounts that do not exist yet (**user2, user3, user4**).

When I add another account to the group using WebAdmin, the roster item is pushed to the client properly, as you noticed.

When I remove an account **user4** of the group using WebAdmin, and click "Send" in the WebAdmin, then the client gets immediately this:
```xml
<iq to='user1@localhost/tka1'
	from='user1@localhost'
	type='set'
	id='push9398182056108140795'>
  <query xmlns='jabber:iq:roster'>
    <item subscription='remove'
	jid='user4@localhost'>
      <group>tech</group>
    </item>
  </query>
</iq>
```

**Comment by badlop** [comment]
I close this ticket because almost a month has passed without feedback.
