### ISSUE TITLE
sessions in sql database not erased after p1_time_compat:unique_timestamp() count reaches 1 million

### ISSUE THREAD

**Issue by FanskiY** [processone/ejabberd#2860]
### Affected ejabberd versions at least from 17.07 to 19.02 when sm_db_type: sql

Before session is written into sql database now_to_timestamp(X) operation is called,
when user session is to be closed reverse operation is done timestamp_to_now(X).

At the new connection when ejabberd_sm:make_sid() is called, if p1_time_compat:unique_timestamp() returns > 1 000 000 then timestamp_to_now(X) returns different time, comparison before closing session by SID fails and session record will not be erased in sql database.

Example:
now_to_timestamp({1555,397983,1000005}) result is 1555397984000005
timestamp_to_now(1555397984000005) result is {1555,397984,5}
{1555,397983,1000005} != {1555,397984,5} and logic below in ejabberd_sm.erl will fail

Info = case lists:keyfind(SID, #session.sid, Sessions) of
	       #session{info = I} = Session ->
		   delete_session(Mod, Session),
		   I;
	       _ ->
		   []
	   end

To test this open ./bin/ejabberdctl debug and call p1_time_compat:unique_timestamp() 1kk times as below:

```
F = fun() -> p1_time_compat:unique_timestamp() end.
TCN2 = fun(T,F,0) -> ok; (T,F,N) -> F(), T(T,F,N-1) end.
TCN = fun(F,N) -> B=now(), TCN2(TCN2,F,N), A=now(), "time to execute: "++integer_to_list(timer:now_diff(A,B)) end.
TCN(F, 1000000).
```

Define converting functions in console, because ejabberd_sm does not exports them
```
Now_to_timestamp = fun ({MSec, Sec, USec}) ->
  (MSec * 1000000 + Sec) * 1000000 + USec end.

Timestamp_to_now = fun (I) ->
  Head = I div 1000000,
  USec = I rem 1000000,
  MSec = Head div 1000000,
  Sec = Head rem 1000000,
  {MSec, Sec, USec} end.

```
and finally test 

```
(ejabberd@localhost)11> {Usec, Pid} = ejabberd_sm:make_sid().
{{1555,397983,1000005},<0.670.0>}
(ejabberd@localhost)12> Timestamp = Now_to_timestamp(Usec).
1555397984000005
(ejabberd@localhost)13> CheckUsec = Timestamp_to_now(Timestamp).
{1555,397984,5}
(ejabberd@localhost)14> Usec == CheckUsec.
false


but if you do
(ejabberd@localhost)15> Now_to_timestamp(CheckUsec).
1555397984000005
you will get same timestamp as in Now_to_timestamp(Usec)
```

**Comment by prefiks** [comment]
Hello,

Good catch, i commited 3706e35b863eccc9e86ec3db9ea1ad328f8006f6 that should fix this issue.
