### ISSUE TITLE
Self-signed certificate generated for localhost

### ISSUE THREAD

**Issue by wrooot** [processone/ejabberd#2863]
I have tried installing ejabberd on Windows. During the setup it asked for a domain. It automatically prefilled it with my PC's hostname (e.g. mypc). But after i have created a user and tried to login in a client, it presented me with a certificate for 'localhost', not 'mypc'. So this creates a mismatch and errors during login. I think it should generate certificate for the domain name provided during setup.

**Comment by wrooot** [comment]
Maybe this script https://github.com/processone/ejabberd/blob/4ddee2d89b005dafb9d574aa82377cf80808f657/test/ejabberd_SUITE_data/gencerts.sh

**Comment by zinid** [comment]
It doesn't matter to what domain the certificate is issued as long as it's self-signed: certification path validation will still fail in any client.
During startup, ejabberd gives you a hint to request a valid certificate from Let's Encrypt, so you should do that if you want to provide the service in the Internet.
