### ISSUE TITLE
ejabberd does not comply to XEP-0060 § 7.1.3.6: notification + transient + item → bad-request error response

### ISSUE THREAD

**Issue by Flowdalic** [processone/ejabberd#2864]
Ejabberd allows PubSub publishes with item to a node that is set to notification and transient while it MUST not according to XEP-0060 § 7.1.3.6.:

> If the event type is notification + transient and the publisher provides an item, the service MUST bounce the publication request with a &lt;bad-request/> error and a pubsub-specific error condition of &lt;item-forbidden/>.

Smack now has an [integration test which checks for the correct behavior under those conditions](https://github.com/igniterealtime/Smack/blob/fc70484cf6f3f5a8dc95a6df92a139a106bdae67/smack-integration-test/src/main/java/org/jivesoftware/smackx/pubsub/PubSubIntegrationTest.java#L95). The test fails on ejabberd 18.12.1.

And yes, this issue is basically the stark trek mirror universe counterpart to #2799. :-)

**Comment by cromain** [comment]
we'll need to check if this is a XEP inconsistency then...

**Comment by Flowdalic** [comment]
No, I think the XEP is consistent in this regard. It is just a different requirement very similar to the one in #2799.

**Comment by cromain** [comment]
This relaxed test should now make us compliant. Still need to check this does not break another case.

**Comment by cromain** [comment]
our code was correct before that commit, and it seems this test was about publishing an *empty* `<item/>`.
