### ISSUE TITLE
site https://ejabberd.im not work

### ISSUE THREAD

**Issue by vladviolenty** [processone/ejabberd#2866]
NET::ERR_CERT_DATE_INVALID
Subject: ejabberd.im

Issuer: Let's Encrypt Authority X3

Expires on: 23 апр. 2019 г.

Current date: 23 апр. 2019 г.

**Comment by kolargol** [comment]
thanks for letting us know. It seems threre were some issues in the API of our provider resulting domain verification stuck. Issue is not resolved.
