### ISSUE TITLE
MS SQL schema: The maximum key length is 900 bytes. The index 'muc_online_users_i' has maximum length of 1250 bytes.

### ISSUE THREAD

**Issue by vkelman** [processone/ejabberd#2867]
I run SQL script for creating MS SQL database objects https://github.com/processone/ejabberd/blob/master/sql/mssql.sql

Objects were created, but I got the following warning:

Warning! The maximum key length is 900 bytes. The index 'muc_online_users_i' has maximum length of 1250 bytes. For some combination of large values, the insert/update operation will fail.

Googled for explanations:
https://stackoverflow.com/questions/22172251/warning-the-maximum-key-length-is-900-bytes-the-index-has-maximum-length-of-10
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms191241(v=sql.105)
https://stackoverflow.com/questions/12717317/900-byte-index-size-limit-in-character-length

**Comment by badlop** [comment]
Good news, as mentioned in https://stackoverflow.com/questions/12717317/900-byte-index-size-limit-in-character-length

> For those on SQLServer 2016, Index key size was increased to 1700 bytes..[What's new in Database Engine - SQL Server 2016](https://docs.microsoft.com/en-us/sql/database-engine/whats-new-in-sql-server-2016)
