### ISSUE TITLE
Unknown field 'token' of type

### ISSUE THREAD

**Issue by Ethica1Hack** [processone/ejabberd#2881]
Hello,

i have problem with pubsub on ejabberd reciving token string from push server (not apns or google push services ) its direct push notification to pubsub. See log below.
```erlang
[#xdata_field{
         label = <<>>,type = undefined,var = <<"FORM_TYPE">>,required = false,
         desc = <<>>,
         values = [<<"http://jabber.org/protocol/pubsub#publish-options">>],
         options = [],sub_els = []},
        #xdata_field{
         **label = <<>>,type = undefined,var = <<"token">>,required = false,**
         desc = <<>>,
         values = [<<"461f8084ad4b6d4c6f77815995511c9d64d360e3">>],
         options = [],sub_els = []},
        #xdata_field{
         label = <<>>,type = undefined,var = <<"endpoint">>,required = false,
         desc = <<>>,
         values =
          [<<"https://push-server-saint.herokuapp.com/api/v1/messages/">>],
         options = [],sub_els = []}]},
    subscribe = undefined,unsubscribe = undefined,options = undefined,
    items = undefined,retract = undefined,create = undefined,
    configure = undefined,default = undefined,delete = undefined,
    purge = undefined,rsm = undefined}]
```
20:04:16.948 [info] **pubsub.myserver.com rejected notification** for test@myserver.com (C16517A9-8095-4DFE-B67D-00CC8FE545BC) temporarily: **Unknown field 'token' of type 'http://jabber.org/protocol/pubsub#publish-options' (resource-constraint)**

Ive also entered to file: /ejabberd/deps/xmpp/specs/**pubsub_publish_options.xdata**

  **   field var='token'
         type='text-single'
         label='token**

Anyone have simillar issue ?

Thank you in advance.

**Comment by zinid** [comment]
First of all, it's a protocol violation to put third-party attributes in xdata forms defined by the XSF.
Secondly, modifying just *.xdata file is not enough: you need to recompile the xmpp codec itself using `make spec` and `make`.
