### ISSUE TITLE
Mysql Error when I Stop EJabberd

### ISSUE THREAD

**Issue by custodis-intestina** [processone/ejabberd#2883]
System: Ubuntu 18.04.2 with Plesk
Ejabberd: 19.02 installed with ejabberd_install.run
SQL: MariaDB 10.1.38

Ejabberd run stable without errors
When i stop ejabberd with "ejabberdctl stop" i become some errors.

[error.log](https://github.com/processone/ejabberd/files/3188001/error.log)
[crash.log](https://github.com/processone/ejabberd/files/3188002/crash.log)

**Comment by cromain** [comment]
was fixed by a4222fe9b (see #2541)
