### ISSUE TITLE
Latest code (pulled from 17f9ffb7e73e614630cf35c4eeaf9c2d1cf055f9) cannot be compiled

### ISSUE THREAD

**Issue by danesh-d** [processone/ejabberd#2888]
Latest code of ejabberd pulled from the commit:

**commit 17f9ffb7e73e614630cf35c4eeaf9c2d1cf055f9 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2b523030 63e9b82a
Author: Evgeny Khramtsov <ekhramtsov@process-one.net>
Date:   Sun May 19 11:23:29 2019 +0300

Merge branch 'master' of github.com:processone/ejabberd**

cannot be compiled and the error message is:

src/mod_muc_room.erl:4125: field nick undefined in record muc_subscription

I ran "git bisect" and it ended with the problematic commit which is:

**commit 7ab7390b9ce2dfd2213c181e31bad4402975fe19
Author: Paweł Dorofiejczyk <pawel.dorofiejczyk@rst.com.pl>
Date:   Thu Apr 25 13:31:08 2019 +0200

Fix #2540 Ejabberd doesnt compile as mix umbrella project dependency**

Apparently the dependencies manifest is incorrect. I executed:

$ ./rebase g-d
$ ./rebar co

to test each revision of the code.

Thanks,

Danesh Daroui

**Comment by licaon-kter** [comment]
Builds fine here (as standalone), what's your setup? OS? Plain build or some umbrella, mixs or whatnot elixir?

**Comment by zinid** [comment]
On and on this goes. Use `make distclean`.
