### ISSUE TITLE
Unable to connect ejjaberd server using pidgin

### ISSUE THREAD

**Issue by rjshk013** [processone/ejabberd#2890]

**Comment by rjshk013** [comment]
I was using ejjaberd chat service using pidgin in linux.But now it is not connecting .When I check ejabberd service is running without issue.But getting error that " Lost connection with server: Bad file descriptor" when connecting using pidgin .Using ejabberd-18.09 .

Indebug window i am getting error as below 
14:23:30) jabber: bosh: httpconn 0xb92f64e0 re-connected
(14:23:30) jabber: SendBOSH Boot (233): <body content='text/xml; charset=utf-8' secure='true' to='***.com' xml:lang='en' xmpp:version='1.0' ver='1.6' xmlns:xmpp='urn:xmpp:xbosh' rid='932984696931891' wait='60' hold='1' xmlns='http://jabber.org/protocol/httpbind'/>
(14:23:30) connection: Connection error on 0xb92d38d8 (reason: 0 description: Lost connection with server: Bad file descriptor)
(14:23:30) account: Disconnecting account *****@***.com/ (0xb8e63e28)
(14:23:30) connection: Disconnecting connection 0xb92d38d8
(14:23:30) connection: Destroying connection 0xb92d38d8

**Comment by licaon-kter** [comment]
Any errors in the ejabberd server logs?


Does a not-abandoned client like Dino or Gajim connect ok?

**Comment by rjshk013** [comment]
under ejjaberd.log I can see lines as below

2019-05-24 13:03:33.415 [info] <0.541.0> (tcp|<0.541.0>) Send XML on stream = <<"</stream:stream>">>
2019-05-24 13:09:47.319 [debug] <0.498.0>@mod_fail2ban:handle_info:134 cleaning failed_auth ETS table
2019-05-24 13:09:47.326 [debug] <0.508.0>@mod_fail2ban:handle_info:134 cleaning failed_auth ETS table
2019-05-24 13:19:47.320 [debug] <0.498.0>@mod_fail2ban:handle_info:134 cleaning failed_auth ETS table

**Comment by prefiks** [comment]
From that error (Bad file descriptor) it looks like pidgin tried to something that was not a socket as a socket, i don't see how that problem with ejabberd, it looks like a bug in pidgin. Also is there particular reason why you using bosh connection instead of native connection? It's introduces much more overhead, and i wouldn't be suprised that its tested more and much less bug prone.

**Comment by rjshk013** [comment]
Thanks guys for the prompt response.Let me investigate and will try to fix.Also is there any alternative for pidgin so that I can check with ?

**Comment by licaon-kter** [comment]
@rjshk013 
> Does a not-abandoned client like Dino or Gajim connect ok?

**Comment by prefiks** [comment]
You could try connecting with non bosh, in account setting in connection setting change port to 5222, and remove anything that in bosh url, or you could other client like dino, gajim, psi.

**Comment by zinid** [comment]
I would strongly advise against Pidgin. Use Dino or Gajim on desktop and Conversations on Android.

**Comment by rjshk013** [comment]
Under advanced settings I can see bosh url and domain link also.Do I need to remove ?Also  in file transfer proxies I can see some value like proxy.eu.jabber.org .Connection port =0.
@prefiks

**Comment by zinid** [comment]
Gosh, just DON'T use Pidgin. That file transfer proxy will not work reliably, the state of the art is to use HTTP Upload. Pidgin doesn't even support that because as said above it's ABANDONED.

**Comment by rjshk013** [comment]
ok.Let me try with the alternatives.Also can U confirm the above are open source .right?

**Comment by rjshk013** [comment]
Currenly I have ejjaberd server,For authentication LDAP is there.So Can I try these alternatives

**Comment by zinid** [comment]
Those are not the alternatives. Those are the only usable XMPP clients to date. Authentication backend is irrelevant to what client you're using.
