### ISSUE TITLE
captcha.sh doesn't work with GraphicsMagick (ImageMagick replacement)

### ISSUE THREAD

**Issue by runderwo** [processone/ejabberd#2891]
The captcha.sh does not work with GraphicsMagick, it seems to be parsing the `convert` arguments incorrectly:

`$ /usr/share/ejabberd/captcha.sh  111111`
`convert convert: Unable to open file (() [No such file or directory].`

There is an ancient bug that was "fixed" by excluding the dependency:
https://bugs.launchpad.net/ubuntu/+source/ejabberd/+bug/788575

My feeling is that the shell script could be modified to pass the arguments in a way that is compatible with both ImageMagick and GraphicsMagick.

Eventually I'll do it myself if no one grabs this first.  It's a pecularity of the host ejabberd is running on that GraphicsMagick must be installed there instead of ImageMagick.

**Comment by zinid** [comment]
Please note that `captcha.sh` is an example script. The whole idea of captcha is to use as unique captcha as possible, so server admins are supposed to write and use their own captcha generators. Accordingly, we never said the example script works with any ImageMagick forks.

**Comment by runderwo** [comment]
Perhaps a more reasonable response other than closed wontfix in response to an offer to fix it would have been to document that implicit assumption somewhere, then?

**Comment by licaon-kter** [comment]
@runderwo Feel free to open a Pull Request then, when you've fixed it. :+1:

**Comment by mremond** [comment]
@runderwo I have documented the assumptions in the script itself: https://github.com/processone/ejabberd/commit/b90fe4c5c93e9196b87d6ef2af1df76c5e08423b

Feel free to submit a PR that improve compliance of the example script, if you find this useful and relevant.

Thanks!
