### ISSUE TITLE
ejabberd pubsub messages are not acknowledged( gray tick), after restart the ejabberd service,then it is working

### ISSUE THREAD

**Issue by sumesh048** [processone/ejabberd#2892]
**Is your feature request related to a problem? Please describe.**
Ejabberd pubsub messages are not acknowledged( gray tick or crashed ) after a long time limit , restart the ejabberd service,then it is working. is there any server resources issue?

**Describe the solution you'd like**
after restart the ejabberd service,then it is working. messages are lost.

**Additional context**

* Ejabberd version: 18.09v
* OS: ubuntu 16.04v (production)
* Hardware: 2 core and 8GB ram.

PubSub details:

![image](https://user-images.githubusercontent.com/36732187/58400603-2fa12980-8079-11e9-8917-e7a8d197a5f1.png)

I look forward to being in touch. Please let me know if I can provide any additional information.

**Comment by licaon-kter** [comment]
Server logs? Client side?

**Comment by sumesh048** [comment]
* we haven't get any log from the server..after restart the service,then i got the logs.

![image](https://user-images.githubusercontent.com/36732187/58402683-8ceba980-807e-11e9-8d22-2656745eef1e.png)

![image](https://user-images.githubusercontent.com/36732187/58402737-abea3b80-807e-11e9-9a6b-89caac616eb2.png)

![image](https://user-images.githubusercontent.com/36732187/58402856-df2cca80-807e-11e9-94dd-52201fbfc214.png)

Please let me know if I can provide any additional information.

**Comment by licaon-kter** [comment]
Those pics have no related info.

Please include de output of: `grep -Ev '^$|^\s*#' ejabberd.yml` for your config.

**Comment by sumesh048** [comment]
* Please find the related PubSub configuration in our project.

![image](https://user-images.githubusercontent.com/36732187/58421393-701a9a80-80ad-11e9-8a4e-6ea61eb6156c.png)

![image](https://user-images.githubusercontent.com/36732187/58421429-89234b80-80ad-11e9-8b29-440ee19615a0.png)

* Mnesia database details already mentioned above.

Thanks in advance

**Comment by licaon-kter** [comment]
Whole config please, per the `grep` command (edit your sensitive data of course)

**Comment by sumesh048** [comment]
YAML:
-

loglevel: 3

log_rotate_size: 10485760
log_rotate_count: 0 

log_rate_limit: 1000

hosts:
  - "alpha.*********************"


certfiles:
  - "/DataVolume/ejabberd-18.12/ssl/alpha.*********************.pem"

ca_file: "/DataVolume/ejabberd-18.12/conf/cacert.pem"

listen:
  -
    port: 5222
    module: ejabberd_c2s
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
    ciphers: "DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA"
    starttls: true
    starttls_required: false
    tls_compression: false
    dhfile: "/DataVolume/ejabberd-18.12/ssl/dh2048.pem"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/ws": ejabberd_http_ws
    web_admin: true

  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      admin:
        commands: all
        options: []
  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
    web_admin: true
    register: true
    captcha: false
    tls: true
    dhfile: "/DataVolume/ejabberd-18.12/ssl/dh2048.pem"


s2s_use_starttls: optional


auth_method: internal
auth_password_format: plain #Sumesh Added
auth_use_cache: false
auth_cache_size: 10000
disable_sasl_mechanisms:
  - "digest-md5"
  - "X-OAUTH2"
  - "SCRAM-SHA-1"


shaper:
  normal: 10000

  fast: 50000

max_fsm_queue: 10000

acl:
  admin:
    user:
      - "admin": "alpha.*********************"
      - "deliveryack": "alpha.*********************"
      - "ack-hp1": "alpha.*********************"
      - "ack-hp2": "alpha.*********************"
      - "ack-mp1": "alpha.*********************"
      - "ack-mp2": "alpha.*********************"
      - "ack-lp1": "alpha.*********************"
      - "adminweb": "alpha.*********************"
  local:
    user_regexp: ""


shaper_rules:
  max_user_sessions:
    - 30: admin
    - 1
  max_user_offline_messages:
    - 5000: admin
    - 1000
  c2s_shaper:
    - normal: admin
    - normal
  s2s_shaper: fast

access_rules:
  local:
    - allow: local
  c2s:
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_admin:
    - allow: admin
  muc:
    - allow
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: admin
  register:
    - allow
  trusted_network:
    - allow
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
      - ejabberd_xmlrpc
      - mod_http_api
    who: all
    what: "*"
  "admin access":
    who:
      - access:
        - allow:
          - user: "admin@alpha.*********************"
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - access:
          - allow:
            - acl: local
    what:
      - "status"
      - "connected_users_number"
  


language: "en"

registration_timeout: infinity

acme:

   contact: "mailto:admin@alpha.*********************"


   ca_url: "https://acme-v01.api.letsencrypt.org"


modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_caps: {}
  mod_carboncopy:
    ram_db_type: mnesia
  mod_client_state:
    queue_chat_states: true
    queue_presence: false
  mod_configure: {} # requires mod_adhoc
  mod_bosh: {}
  mod_http_upload:
    docroot: "/DataVolume/ejabberd-18.12/upload"
    put_url: "http://@HOST@:5443/upload"
  mod_last:
    use_cache: false
    cache_size: 10000
  mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
    db_type: sql
  mod_ping:
    send_pings: true
    ping_interval: 120
    ping_ack_timeout: 32
    timeout_action: kill
  mod_pubsub:
    access_createnode: pubsub_createnode
    db_type: mnesia
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_register:
    access: register
  mod_time: {}
  mod_version: {}
  mod_stream_mgmt:
    resend_on_timeout: true
    resume_timeout: 120
  mod_http_api: {}


sm_db_type: mnesia

sql_type: pgsql
sql_server: "127.0.0.1"
sql_port: 5432
sql_database: "LK-XMPPDB"
sql_username: "postgres"
sql_password: "dwise@123"


allow_contrib_modules: true

**Comment by sumesh048** [comment]
Dear Mr.Licaon-kter.

Please find the whole YAML file for the current configuration.

Thanks in advance.

**Comment by licaon-kter** [comment]
Repro steps...what do you do? How?

**Comment by sumesh048** [comment]
Thanks in advance.
Can you share me the solutions?

**Comment by licaon-kter** [comment]
@sumesh048 
> Repro steps...what do you do? How? With what application?
???

**Comment by sumesh048** [comment]
Sorry for the inconvenience.
Can you help me..."Repro steps?"
* We have using mobile application and multiple of ejabberd server with same configuration. but one server having the issue.

* Is our ejabberd configuration right? Can i have to change any server side/Erlang configuration?

**Comment by licaon-kter** [comment]
Can you help me..."Repro steps?"

*Repro* = *reproduction*
How can I or anyone else reproduce this issue?

> We have using mobile application 

What application do we need?

> but one server having the issue.

What steps are we to follow to see the issue in action?

**Comment by sumesh048** [comment]
Sorry for unable to reproduce this same scenario.

* We are using PubSub chat node massaging. I have checked the subscription is working, but same time chat is not acknowledged.
* This is the scenario I have observed. Can you have any solutions/reason for this scenario?
* Can you help me, what is the reason to stuck in PubSub state/PubSub chat node?

**Comment by cromain** [comment]
I'm closing this topic as it's not precise enough to understand and not reproduceable.
I guess you expect subscribers to ack messages back to publisher and your client just sends ack to sender of the headline packet, which is pubsub service. 
You should have a look at this spec note: https://xmpp.org/extensions/xep-0060.html#impl-association
So your client can get publisher's jid and reply ack.
