### ISSUE TITLE
Error: cannot_register

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#2893]
When I update ejabber 19.02 to ejabberd 19.05.3 it does not let me create users from the console.

```
# ./ejabberdctl register javi suchat.org 12345
Error: cannot_register
```

There are no errors in the log

Thanks for the help

**Comment by prefiks** [comment]
Hello,

Could you tell me what auth method you have enabled on your server, this usually happen when you use method like external or anonymous, that don't have register functionality.

**Comment by suchatorg** [comment]
Hello

External Mysql

**Comment by prefiks** [comment]
You mean you have something like that in your config:
```
auth_method:
  - external
  - sql
```
?
And it worked in 19.02 but don't in 19.05?

**Comment by prefiks** [comment]
@zinid Possibly some fallout from that auth cache changes that you introduced? Maybe you changed how errors are propagated?

**Comment by suchatorg** [comment]
```
auth_method: sql
auth_password_format: scram
```
If it works on 19.02, it does not work on 19.05

**Comment by prefiks** [comment]
Can you tell me how you installed that new version? Did you build it manually? If so did you execute 'make update' before that? Recent change in auth code did require never version of cache_tab dependency, so if you still use old version it possibly may fail that way.

**Comment by suchatorg** [comment]
I built it manually like the previous versions, do not run 'make update'
```
git clone git://github.com/processone/ejabberd.git ejabberd
cd ejabberd
./configure --enable-user=suso --prefix=/home/suso --bindir=/usr/bin --enable-mysql --enable-zlib --enable-elixir --enable-stun
./autogen.sh
make
make install
```

**Comment by badlop** [comment]
Since ejabberd 19.05, the _register_ command respects the access rules defined in _mod_register_ configuration, see https://github.com/processone/ejabberd/issues/2837

So, it is important what you have configured in your configuration file, especially those sections:
```
acl:

access_rules:

modules:
  mod_register:
```

**Comment by prefiks** [comment]
Could you please try starting ejabberd console:
```
ejabberdctl debug
```
Then after you enter shell, copy/paste this and see what it returns:
```
ejabberd_admin:register(<<"javi">>, <<"suchat.org">>, <<"12345">>).
```

**Comment by suchatorg** [comment]
(ejabberd@localhost)2>  ejabberd_admin:register(<<"javi">>, <<"suchat.org">>, <<"12345">>).
{error,cannot_register,10001,
       [67,97,110,39,116,32,114,101,103,105,115,116,101,114,32,117,
        115,101,114,32,"javi",64,"suchat.org",32,97|...]}
(ejabberd@localhost)3>

**Comment by prefiks** [comment]
Yes this is probably related to access rules like badlop pointed above.

**Comment by suchatorg** [comment]
I check the access rules and comment on the result.
Thank you

**Comment by suchatorg** [comment]
The rules were well configured, for it to work I have to change
registration_timeout: 3600 for registration_timeout: 1
It seems that version 19.05 is affected by registration_timeout with the console or administrator.

**Comment by badlop** [comment]
> It seems that version 19.05 is affected by registration_timeout with the console or administrator.

Yes, because the `register` command now respects the `mod_register` options, and `registration_timeout` is also used by that module to accept or reject an account registration.

**Comment by suchatorg** [comment]
Gracias por la ayuda

**Comment by mremond** [comment]
I am reopening the issue, as I think the command-line should not have this restriction. Thanks for reporting the issue :)

**Comment by licaon-kter** [comment]
@mremond Wasn't this decided in https://github.com/processone/ejabberd/issues/2828 ?

**Comment by mremond** [comment]
Ah yes, maybe but was that really a good idea ? The API was designed to have the command line be a priviledge way of passing ejabberd commands. I am not sure users expect to have to set complex API options just to use the command-line normally...

**Comment by mremond** [comment]
The related ticket that is causing the original issue is: https://github.com/processone/ejabberd/issues/2837

**Comment by sumesh048** [comment]
Hi suchatorg,

Problem is hosts/hostname, which is mentioned in registration.

* Can you share the ejabberd config yaml file.
* Verify the hosts/hostname or is properly updated in config file.

Thanks in advance.

**Comment by suchatorg** [comment]
Hi sumesh048, the host is well configured, it always worked for me.
Now I have it solved with the configuration that commented badlop, configuring the register module.

**Comment by sumesh048** [comment]
Thanks for the updates Mr.suchatorg.

**Comment by badlop** [comment]
The changes introduced in the register command for #2837 were problematic, and have been reverted. So, this ticket can be closed.

**Comment by anasmorahhib** [comment]
> Could you please try starting ejabberd console:
> 
> ```
> ejabberdctl debug
> ```
> 
> Then after you enter shell, copy/paste this and see what it returns:
> 
> ```
> ejabberd_admin:register(<<"javi">>, <<"suchat.org">>, <<"12345">>).
> ```

that works, but why doesn't work directly from cmd.
