### ISSUE TITLE
Administration API: Getting CORS issue or Account does not have the right to perform the operation

### ISSUE THREAD

**Issue by andrisole92** [processone/ejabberd#2894]
Hi there,

I am running an eJabberd server on DigitalOcean droplet and trying to use an Administration API from my localhost.

I have 2 problems:

1. `register` request is getting ```Account does not have the right to perform the operation```. My config is: 
```    port: 5281
    http_bind: true
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api

...

api_permissions:
  "public commands":
    who: all
    what:
      - "status"
      - "register"
      - "connected_users_number"
```
2. `connected_users_number` returns ```Access to XMLHttpRequest at 'http://xxx.xxx.x.xx:5281/api/connected_users_number' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

So, I am just wondering is it possible to have administration API on one IP address and eJabberd on another? And if yes, how to set it up?

Looking forward to hearing from you.

**Comment by licaon-kter** [comment]
Try to add a `from` too: https://docs.ejabberd.im/developer/ejabberd-api/permissions/#rules-in-from-section

**Comment by andrisole92** [comment]
Hey,

Thanks for getting back.

I added `from`, and now my `.yml` looks like:

```
port: 5281
    http_bind: true
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
...
"public commands":
    who: all
    from: mod_http_api
    what:
      - "*"
      - "!stop"
      - "!start"
```

Which I suppose should mean that Administration API commands can be executed by anyone?

But I am getting CORS issue on most of my request:

<img width="818" alt="Screenshot 2019-05-28 at 19 03 47" src="https://user-images.githubusercontent.com/17086705/58518207-36649500-817c-11e9-97fb-f5967115b435.png">

And this issue on the register: `Can't register user borrb@example.com at node ejabberd@localhost: not_allowed`. Which I assume is due to this rule

```   
mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
```

So the biggest problem for me is CORS issue right now.

**Comment by andrisole92** [comment]
Actually, I have just registered a user, and the problem was that I was using a wrong host in the request body. It should have matched the one in `.yml` file I guess.

Still having CORS.

**Comment by andrisole92** [comment]
All works, I figured it! The problem was I had to send an empty body in `POST` request.

So, instead `a.post('http://xxx.xxx.x.xxx:5281/api/get_loglevel')`, it should be `a.post('http://xxx.xxx.x.xxx:5281/api/get_loglevel',{})` if using axios.
