### ISSUE TITLE
"Error: cannot_register" when trying to register second account

### ISSUE THREAD

**Issue by jameskentTX** [processone/ejabberd#2895]
Problem:

I can register one account only from console. If I try to register second user i have error: "Error: cannot_register".
So... I can register one user only. Then I have to restart ejabberd to register next user.

My ejabberd version is 19.02.131, compiled from source. Debian 10 (testing) as OS.
I can register more than one account using web admin service. 

Waiting more than 60 seconds (default registration_timeout) doesn't help - I still cannot register second consecutive user.

**Comment by licaon-kter** [comment]
Put `registration_timeout: 1` reload_config retry?

**Comment by jameskentTX** [comment]
> Put `registration_timeout: 1` reload_config retry?

Yep, it solved the problem. Thanks.
So I guess default registration_timeout is now 60 minutes, not 60 seconds.

**Comment by suchatorg** [comment]
To disable it
registration_timeout: infinity
