### ISSUE TITLE
Image conversion / thumbnail support gone - again - after updating from 18.12.1 to 19.05

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#2898]
See #2716. Same issue.

**Comment by badlop** [comment]
Last time was some library missing in the installers, chances are this problem is the same... In my test compiling from source code in linux, works correctly.

**Comment by mbirth** [comment]
Just for the record: I'm using the arm64 binary installer.

**Comment by cromain** [comment]
you're right. both armv7 and armv8 build environment has been rebuilt from scratch to lower glibc version dependencies (allow raspbian compatibility), and those extra libs are gone again. sorry for the trouble.

**Comment by cromain** [comment]
libgd re-installed on arm build environments

**Comment by mbirth** [comment]
arm64 binary installer versions 19.05 and 19.08 also complain about missing thumbnail support and refuse to start when the option is set.

```
2019-10-12 00:12:01.170 [warning] <0.275.0>@mod_http_upload:mod_opt_type:211 ejabberd is built without image converter support, option 'thumbnail' is ignored
2019-10-12 00:12:01.171 [error] <0.275.0>@gen_mod:module_error:595 Invalid value for option 'thumbnail' of module mod_http_upload: true
2019-10-12 00:12:01.172 [critical] <0.275.0>@gen_mod:maybe_halt_ejabberd:325 ejabberd initialization was aborted because a module start failed.
```

(Also the log messages are first talking about how the option is **ignored** and then the startup is aborted because it seems to **not** be ignored.)

**Comment by badlop** [comment]
I can reproduce that funny behaviour with ejabberd 19.05 compiled from source code in Debian. However, in 19.08 it doesn't happen, as that code  changed in: https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782
