### ISSUE TITLE
Youtube link invalid

### ISSUE THREAD

**Issue by ShalokShalom** [processone/ejabberd#2902]
Here is still the Youtube channel mentioned: https://www.process-one.net/en/ejabberd/downloads/

**Comment by mremond** [comment]
On which page / document do you see an invalid link ?

**Comment by ShalokShalom** [comment]
That one I linked. It says Video Tutorials. On the right side in the middle.

**Comment by mremond** [comment]
Ok, thanks I see it. We will fix that next week. It is supposed to point to ProcessOne YouTube channel: https://www.youtube.com/user/ProcessOneVideos

Thanks!

**Comment by ShalokShalom** [comment]
Sure :+1:

**Comment by f055** [comment]
Thanks for spotting this, there was a quotation typo. It's now fixed.
