### ISSUE TITLE
username validation api endpoint

### ISSUE THREAD

**Issue by mightyBroccoli** [processone/ejabberd#2903]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the problem explained in the #2837. Essentially the register api endpoint does not respect the acl rules imposed by ejabberd itself. That way accounts could be created that are not able to login due to those restrictions.

**Describe the solution you'd like**
I would like to propose a simple solution to that problem. Via the implementation of another api command doing exactly that. 

```
POST /api/validate_username
    {
      "user": "user1",
      "host": "myserver.com",
    }
    
    HTTP/1.1 200 OK
    ""
```
That hypothetical api command would check if the proposed username is conform to all imposed rules of the specified host. That way the amount of code that has to be implemented on a custom side would be minimized.

**Describe alternatives you've considered**
The alternative would be to implement the same rules, you impose on your ejabberd instance, to any custom product you design. The difficulty ranges from being fairly low to impossible to manage, additionally the maintenance effort increases every time a rule is modified/ removed or added.

**Comment by badlop** [comment]
This patch implements that command. However, as it seems it has little interest, I won't commit it. Anybody interested can apply it to his code:
```diff
From 6b18bc1a786e588ae5c1ac870f1043384858e77d Mon Sep 17 00:00:00 2001
From: Badlop <badlop@process-one.net>
Date: Mon, 10 May 2021 13:05:22 +0200
Subject: [PATCH] Implement validate_username command (#2903)

---
 src/ejabberd_admin.erl | 18 ++++++++++++++++++
 1 file changed, 18 insertions(+)

diff --git a/src/ejabberd_admin.erl b/src/ejabberd_admin.erl
index 84b85b061..0953dd9f8 100644
--- a/src/ejabberd_admin.erl
+++ b/src/ejabberd_admin.erl
@@ -42,6 +42,7 @@
 	 %% Erlang
 	 update_list/0, update/1,
 	 %% Accounts
+	 validate_username/2,
 	 register/3, unregister/2,
 	 registered_users/1,
 	 %% Migration jabberd1.4
@@ -168,6 +169,14 @@ get_commands_spec() ->
 			args = [{module, string}],
 			result = {res, restuple}},
 
+     #ejabberd_commands{name = validate_username, tags = [accounts],
+			desc = "Validate if a username can register and login",
+			policy = admin,
+			module = ?MODULE, function = validate_username,
+			args_desc = ["Username", "Local vhost served by ejabberd"],
+			args_example = [<<"bob">>, <<"example.com">>],
+			args = [{user, binary}, {host, binary}],
+			result = {res, rescode}},
      #ejabberd_commands{name = register, tags = [accounts],
 			desc = "Register a user",
 			policy = admin,
@@ -519,6 +528,15 @@ update_module(ModuleNameString) ->
 %%% Account management
 %%%
 
+%% Code copied from mod_register:check_access/3
+validate_username(User, Server) ->
+    JID = jid:make(User, Server),
+    Access = mod_register_opt:access(Server),
+    case acl:match_rule(Server, Access, JID) of
+	allow -> true;
+	deny -> false
+    end.
+
 register(User, Host, Password) ->
     case is_my_host(Host) of
 	true ->
-- 
2.20.1
```

**Comment by mightyBroccoli** [comment]
But it really is quite useful to someone with a custom registration form. Thank you very much :+1:
