### ISSUE TITLE
Allow to modify host when registering account in web

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#291]
I have ejabberd on separate machine, each vhost have SRV records with subdomain xmpp.domaind.tld but in ejabberd are configure as domain.tld. It's work fine but no with mod_register_web. I can't register any account by mod_register_web on vhost domain.tld by entering http://xmpp.domain.tld/register/new because mod_register_web say that I want to register account on vhost xmpp.domain.tld which is not exist. mod_register_web takes name of vhost from HTTP request address? Please change it ex. combobox with vhost to choose.

**Comment by Beherit** [comment]
Hello?! I'm still waiting for a solution to this problem.

**Comment by 7adietri** [comment]
The workaround I now use is to configure my webserver to proxy between `xmpp.example.net:443` and `127.0.0.1:5280`, forcing the `Host` header to `example.net`. That way mod_register_web always sees the correct Jabber domain.

Being able to restrict mod_register_web to `127.0.0.1` and using the standard HTTPS port in URLs is also nice.

**Comment by beherit** [comment]
@badlop could You fix that issue? P.S. Maybe it's time to realize all the ideas (that are described in source) for mod_register_web?

**Comment by weiss** [comment]
I think bug reports are much appreciated, but pushing developers to work on them seems quite inappropriate to me.

**Comment by beherit** [comment]
Chill out, I just asking - not pushing developers to work. I tried to fix that on my own but I don't have much knowledge in Erlang.

**Comment by badlop** [comment]
> mod_register_web takes name of vhost from HTTP request address?

Right, from the URL.

> Please change it ex. combobox with vhost to choose.

That's a bad idea, because then the register page reveals to the user what other hosts are served, and that may not be desired by the server admins.

Instead, I've make it editable text with default content.

> Maybe it's time to realize all the ideas (that are described in source) for mod_register_web?

If you are interested in those features, then do it, or get somebody capable to do it, or announce funding in the mailing list and somebody may appear.

**Comment by beherit** [comment]
> Instead, I've make it editable text with default content.

Thank You!

**Comment by beherit** [comment]
Now I have another problem described here https://github.com/processone/ejabberd/issues/294 I use the mod_register_web with https but now it work only for default vhost.

**Comment by beherit** [comment]
> Right, from the URL.

It's possible to get domain name from the URL? Now hostname is with subdomain.
