### ISSUE TITLE
Server does not automatically add roster items for MIX channels

### ISSUE THREAD

**Issue by lnjX** [processone/ejabberd#2912]
As specified by https://xmpp.org/extensions/attic/xep-0405-0.2.1.html#usecase-roster the server MUST add the MIX channel when the user joins it.

**Comment by mremond** [comment]
For the record, MIX entries in record are going to disappear in a future version.
More details here: https://mail.jabber.org/pipermail/standards/2019-June/036172.html

**Comment by zinid** [comment]
Yes, I didn't implement the feature due to the reasons outlined by @mremond
