### ISSUE TITLE
Wrong version number for mod_mix_pam

### ISSUE THREAD

**Issue by lnjX** [processone/ejabberd#2913]
The current implementation of mod_mix_pam implements at least the version 0.3.0 of MIX-PAM since the discovery works by bare JID instead of server JID.

**Comment by zinid** [comment]
In reality this was done prior to release of 0.3.0 after the discussion with other implementors, so strictly speaking it's neither 0.2.1 nor 0.3.0 :) I will bump it to 0.3.0 though.
