### ISSUE TITLE
More granularity for hide_sensitive_log_data

### ISSUE THREAD

**Issue by madmalkav** [processone/ejabberd#2914]
**Is your feature request related to a problem? Please describe.**
Currently hide_sensitive_log_data is a true/false config, hidding all information that can be considered sensible. I'm currently debugging some connectivity problems with wifi devices on a local network and have set logs to DEBUG, ,I can use the IP address information, but will like to hide the password data on the logs.

**Describe the solution you'd like**
Options to decide which information exactly is hidden.

**Describe alternatives you've considered**
Hire Process One and pay them a lot of money, but my boss won't allow me to -yet-.

**Comment by badlop** [comment]
Right now the option is used mainly to hide client's IP address in several services (C2S, S2S, webadmin, http_api, mqtt...), but also in a few cases to hide LDAP request, LDAP message, and http_api password.

You want to reveal IP from all services and hide everything else (passwords and messages). I suspect in the future somebody will want to reveal S2S IPs and hide IPs from everywhere else, ...

A DIY alternative, if you can recompile ejabberd: you can simply remove the two log lines that reveal passwords, during the time you are debugging.
