### ISSUE TITLE
certificate_verify_failed while transferring file

### ISSUE THREAD

**Issue by spajkee** [processone/ejabberd#2918]
Hello

When I'm trying to send file using f.e gajim client occurs:

CERTIFICATE_VERIFY_FAILED

Certificate exists, tried to uncomment no_sslv3 in conf - same result. What can cause it? In addition any info, about how file transfering works (can NAT effect on ssl) and is it possible to check if cert is correct would be great.

**Comment by licaon-kter** [comment]
ejabberd version? OS version? Where did you get the cert from? Did you try another client? What Gajim version? [Gist](https://gist.github.com) of your config?

**Comment by spajkee** [comment]
Ejabberd 17.09. OS - Windows 7 on Gajim client, Ubuntu - ejabberd.  This problem is on all clients, certificate is self-signed.

```
  port: 5222
  ip: "::"
  module: ejabberd_c2s
  starttls: true
  certfile: 'CERTFILE'
  protocol_options: 'TLSOPTS'


  'CERTFILE': "/opt/ejabberd-17.09/conf/server.pem"
'TLSOPTS':
##     - "no_sslv2"
    - "no_sslv3"
##     - "no_tlsv1"
##     - "no_tlsv1_1"
```

**Comment by spajkee** [comment]
Problem was in certificate. Self-signed certificates are not supported in mod_upload ejabberd. It is possible to set self-signed cert for sending messages in xmpp client, but uploading is forbidden. Maybe there is a parameter for applying all certs?

**Comment by licaon-kter** [comment]
@spajkee That's false, it works fine in my testing eg. with the Conversations client

**Comment by spajkee** [comment]
But settng on mobile version (there is a button to support all certs) solves this issue, this problem is only on pc.

**Comment by licaon-kter** [comment]
Yes, config your client to accept self-signed, report this to their devs, etc.

/close this if/as not actually an ejabberd issue
