### ISSUE TITLE
Ejabberd server closing connection  Closing c2s session for userName@localhost/101258162286700657932564: Connection failed: connection closed

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2926]
Hi,
Ejabberd server is closing the connections with the clients after sometime. I am getting these errors

![image](https://user-images.githubusercontent.com/16096109/60565102-dfa43980-9d7f-11e9-9423-186c3c8dfe9b.png)

Is there is any section in the configuration docs that i need to study. I am using defaults ejabberd.yml
 please help!!

**Comment by licaon-kter** [comment]
ejabberd version? OTP version? OS used? Did you try other clients like Conversations or Gajim or Converse.js?

**Comment by mailtosagar** [comment]
ejabberd version : 19.05
OS used: Linux(Ubuntu 18.04)
What can be the issues with my clients. I am using Strophe.

**Comment by licaon-kter** [comment]
@mailtosagar I don't know, try a normal client too...

**Comment by mailtosagar** [comment]
I think that the problem is on server side. because the session closing also occur sometime after login and also when 2 or 3 hits to the server . It is closing c2s connections with every client.

**Comment by prefiks** [comment]
Hello,

"Connection failed: connection closed" is generated when ejabberd receive "socket closed" on tcp socket that is used for c2s. Possibly problem with network? Anyway no option in ejabberd can "fix" this, this is generated at OS socket layer.

**Comment by chrzimmer** [comment]
Hello, can someone point me to a way how to investigate that i come a little further with this problem ? 
I dont understand that this is a network problem since on my side client and server are on the same machine ...

**Comment by prefiks** [comment]
Could you show logs from server ideally when sending loglevel to 5/debug? In this case above it looks like server did close connection because it didn't receive new request for 30 seconds (at least looking at timestamps, this is most likelly reason for that). With loglevel 5 we should be seeing all traffic that server receives.

**Comment by chrzimmer** [comment]
attached you find logs with loglevel 4 and 5. With loglevel 4 you can see that each time i hit something on my portal (Elgg) there appears "Connection failed: connection closed"

[ejabberd_log_loglevel4.log](https://github.com/processone/ejabberd/files/4971383/ejabberd_log_loglevel4.log)
[ejabberd_log_loglevel5.log](https://github.com/processone/ejabberd/files/4971385/ejabberd_log_loglevel5.log)

**Comment by prefiks** [comment]
Hello,

Ok so it appears that you are using websocket for your connection and not http-bind as was discussed earlier in this ticker.

If be "hitting something on my portal" you cause page reload in your webbrowser, then that is expected, this will cause browser to close any websocket connection that was estabilished on that page, and in normal situations that will end client session. There are a way to handle that properly though, if your client is able to handle stream management [https://xmpp.org/extensions/xep-0198.html], it can say server to keep session active even when connection get closed, and it should be able to resume that session after page reload on new websocket connection. But your client need to explictily configure that, and handle that protocol.

**Comment by chrzimmer** [comment]
Thank you man !
That pointed me in the right direction. I will investigate if converse.js is configurable that way.
