### ISSUE TITLE
non-standard vCard elements are not supported

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#2927]
According to DTD [draft-dawson-vcard-xml-dtd-01](http://www.watersprings.org/pub/id/draft-dawson-vcard-xml-dtd-01.txt) p.4.2 there is an ability to add custom elements with the prefix "X-"
but when I send a stanza with a vCard contains such elements I don't see it in the REST request ```get_vcard```

The request payload of get_vcard is: 
```
{
      "user": "user1",
      "host": "my.host",
      "name": "X-CAPABILITY"
    }
```
 The request payload of send_stanza_c2s is:
```
{
  "user": "user1",
      "host": "my.host",
      "resource": "conv",
      "stanza": "<iq id='v2' type='set'><vCard xmlns='vcard-temp'><FN>Peter Saint-Andre</FN><N><FAMILY>Saint-Andre</FAMILY><GIVEN>Peter</GIVEN><MIDDLE/></N><NICKNAME>stpeter</NICKNAME><URL>http://www.xmpp.org/xsf/people/stp.shtml</URL><X-CAPABILITY>SOS</X-CAPABILITY></vCard></iq>"
}
```

**Comment by badlop** [comment]
mod_vcard, included in ejabberd, implements latest version of XEP-0054: vcard-temp, and that doesn't mention support for non-standard extensions. The fact that this XEP was based in draft-dawson-vcard-xml-dtd-01.txt doesn't mean the XEP uses all the cases proposed in that Draft:

> ... with the <vCard/> element containing the actual vCard-XML elements as defined by the vCard-XML DTD (https://xmpp.org/extensions/xep-0054.html#dtd)
