### ISSUE TITLE
Question: XMPP user authentication

### ISSUE THREAD

**Issue by brobaniuc** [processone/ejabberd#2928]
Hi,

What version of ejabberd are you using?
18.09

What operating system (version) are you using?
Centos

How did you install ejabberd (source, package, distribution)?
package

We have a situation where we need to connect with two applications from the same device but with the same user. Would this be allowed in ejabberd.

**Comment by licaon-kter** [comment]
Yes, if you wish.

**Comment by brobaniuc** [comment]
Are there any special settings or configuration for this to be done on ejabberd?

**Comment by licaon-kter** [comment]
If you set limits... https://docs.ejabberd.im/admin/configuration/#limiting-opened-sessions-with-acl

What clients did you use?

**Comment by sezuan** [comment]
I think this also happens when both connections use the very same resource.

**Comment by brobaniuc** [comment]
Thanks, 
We will tr with different resources as well.

**Comment by Freyskeyd** [comment]
Hello,

This kind of error have two possible explaination:

- As said before, you used the same resource to connect (ex: `mike@example.com/desktop` on both `desktop` and `mobile`)
- When a JID overpass the max session define in ACL, the previous session are closed.

Keep in mind those two things and adapt your app/ACL to your needs.
