### ISSUE TITLE
Make mod_pubsub XEP-0060: Publish-Subscribe - Version 1.15.8 compatible

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#2931]
A new version of XEP-0060 was released a couple of days ago.

This change simply ask the Pubsub services to expose the node access model and publish model in the pubsub#metadata (see the related changes https://github.com/xsf/xeps/pull/758/files).

I would be really happy to see such information implemented in mod_pubsub.

**Comment by Neustradamus** [comment]
But it will be nice to know, what is the actual supported version because there are previous changes too ^^

And it is not for XEP-0060 only.

All versions are missing from https://www.process-one.net/en/ejabberd/protocols/.

**Comment by cromain** [comment]
@zinid this requires update in xmpp library
