### ISSUE TITLE
error accurs in try_register when using external authentication script

### ISSUE THREAD

**Issue by tim-chow** [processone/ejabberd#2932]
ejabberd version: 19.05.93
ejabberd.yml:
<pre>
...
listen:
  -
    port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
...
  -
    port: 5280
    ip: "0.0.0.0"
    module: ejabberd_http
    tls: false
    request_handlers:
      "/admin": ejabberd_web_admin
    web_admin: true
...
auth_method: [external]
extauth_program: "/usr/local/sbin/ext_auth.py"
extauth_instances: 3
auth_use_cache: false
...
</pre>
/usr/local/sbin/ext_auth.py:
<pre>
#!/usr/bin/python

import sys
import struct

def read():
    (pkt_size,) = struct.unpack('>H', sys.stdin.read(2))
    pkt = sys.stdin.read(pkt_size)
    cmd = pkt.split(':')[0]
    if cmd == 'auth':
        u, s, p = pkt.split(':', 3)[1:]
        if u == "wrong":
            write(False)
        else:
            write(True)
    elif cmd == 'isuser':
        u, s = pkt.split(':', 2)[1:]
        write(False)
    elif cmd == 'setpass':
        u, s, p = pkt.split(':', 3)[1:]
        write(True)
    elif cmd == 'tryregister':
        u, s, p = pkt.split(':', 3)[1:]
        write(True)
    elif cmd == 'removeuser':
        u, s = pkt.split(':', 2)[1:]
        write(True)
    elif cmd == 'removeuser3':
        u, s, p = pkt.split(':', 3)[1:]
        write(True)
    else:
        write(False)
    read()

def write(result):
    if result:
        sys.stdout.write('\x00\x02\x00\x01')
    else:
        sys.stdout.write('\x00\x02\x00\x00')
    sys.stdout.flush()

if __name__ == "__main__":
    try:
        read()
    except struct.error:
        pass
</pre>
error was:
<pre>
[root@n014.cms.msina.bx.sinanode.com ]: ~
0> /usr/local/sbin/ejabberdctl register user-abcde 10.13.0.35 password-abcde
WARNING: It is not recommended to run ejabberd as root
Problem 'error {case_clause,{ok,<<"password-abcde">>}}' occurred executing the command.
Stacktrace: [{ejabberd_auth,try_register,3,
                            [{file,"src/ejabberd_auth.erl"},{line,279}]},
             {ejabberd_admin,register,3,
                             [{file,"src/ejabberd_admin.erl"},{line,501}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,351}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,318}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,249}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,197}]}]
</pre>

Thank you.

**Comment by tim-chow** [comment]
ejabberd.log:
<pre>
255 2019-07-07 16:52:16.777 [debug] <0.383.0>@ejabberd_access_permissions:handle_call:108 Command 'register' execution allowed by
    rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
256 2019-07-07 16:52:16.777 [debug] <0.545.0>@ejabberd_commands:do_execute_command:445 Executing command ejabberd_admin:register w
    ith Args=[<<"user-abcde">>,<<"10.13.0.35">>,<<"password-abcde">>]
257 2019-07-07 16:52:16.777 [debug] <0.496.0>@extauth:handle_call:124 Received response from external authentication program: [0,0
    ]
258 2019-07-07 16:52:16.778 [debug] <0.497.0>@extauth:handle_call:124 Received response from external authentication program: [0,1
    ]
</pre>

**Comment by zinid** [comment]
I fixed it. You can either update master branch (`git pull`) or set `auth_use_cache: true` in the config.

**Comment by tim-chow** [comment]
> I fixed it. You can either update master branch (`git pull`) or set `auth_use_cache: true` in the config.

I just tested, it works!Thank you.
