### ISSUE TITLE
Failed RPC connection to the node 'ejabberd@nocs.cn': nodedown

### ISSUE THREAD

**Issue by zyfmix** [processone/ejabberd#2943]
**Is your feature request related to a problem? Please describe.**
when i run command `ejabberdctl status` ,it give me error:
```bash
# ejabberdctl status
Failed RPC connection to the node 'ejabberd@nocs.cn': nodedown
```

**Describe the solution you'd like**
when i add `127.0.0.1 nocs.cn` to `/etc/hosts`,and run command `ejabberdctl status` again, it was working:

``` bash
# ejabberdctl status
The node 'ejabberd@nocs.cn' is started with status: started
ejabberd 16.01.3144 is running in that node
```

**Describe alternatives you've considered**

I'm run ejabberd in a kubernetes cluster.I think it's may be ejabberd service run behind a subnet that cause this problem.

**Additional context**
similar question to [Failed RPC connection to the node ejabberd@personal: nodedown](https://www.ejabberd.im/forum/29747/failed-rpc-connection-node-ejabberdpersonal-nodedown/index.html)

**Comment by licaon-kter** [comment]
Can you update to a newer than 3 years version?

**Comment by zyfmix** [comment]
I compile ejabberd use a dockerfile with new version of `19.05` like below:

`
ENV OTP_VNO 22.0
ENV LIB_YAML_VNO 0.2.2
ENV EJABBERD_VNO 19.05

RUN git clone https://github.com/coam/ejabberd.git && git -C ejabberd checkout tags/${EJABBERD_VNO}
WORKDIR /data/opt/ejabberd
RUN ./autogen.sh
RUN ./configure --enable-user=coam --enable-group=coam --enable-odbc --enable-new-sql-schema --enable-mysql --enable-redis --enable-elixir --enable-zlib --enable-tools --enable-debug --enable-stun --enable-latest-deps --enable-full-xml --enable-roster-gateway-workaround --enable-erlang-version-check
RUN make debug=true -j `grep processor /proc/cpuinfo | wc -l`
RUN make install
`
I don't know why it show me ejabberd 16.01.3144.I hava found install dir `/usr/local/lib/ejabberd-16.01.3144`;

**Comment by zinid** [comment]
Sounds to me like DNS problem. Is `nocs.cn` available via DNS? Are all Erlang distribution ports opened on that IP?

**Comment by zyfmix** [comment]
@zinid Yes, the domain name was resolve to server 47.89.20.207 which i run the ejabberd server.and i had exports all ejabberd port by iptables like below: 

```bash
# Allow Ejabberd connections.
-A INPUT -p tcp --dport 4560 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 5222 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 5269 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 5280 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 5349 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 5443 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 34825 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 4369 -m state --state NEW -j ACCEPT
-A INPUT -p tcp --dport 7777 -m state --state NEW -j ACCEPT
```

I can telnet the nocs.cn port:

```bash
$ telnet nocs.cn 4560
Trying 47.89.20.207...
Connected to nocs.cn.
Escape character is '^]'.
```

**Comment by zinid** [comment]
When an ejabberd node is started it's assigned a random distribution port, defined in the `FIREWALL_WINDOW` variable (of ejabberdct.cfg). Just run `netstat -pant | grep beam.smp` to see what interfaces and port are assigned to the running ejabberd node to make sure.

**Comment by zyfmix** [comment]
@zinid thank you for help.when i defined in the `FIREWALL_WINDOW` variable (of ejabberdct.cfg) like below:

```bash
FIREWALL_WINDOW=34825
```
and restart ejabberd server again to check the port `34825` below:

```bash
$ sudo netstat -pant | grep beam.smp
tcp        0      0 0.0.0.0:4560            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:5443            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:5349            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 0.0.0.0:34825           0.0.0.0:*               LISTEN      58/beam.smp
tcp        0      0 172.31.141.97:53523     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:59697     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:43229     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:58667     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:58099     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:36055     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:44069     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:58547     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:58315     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 172.31.141.97:49717     47.89.20.207:30306      ESTABLISHED 58/beam.smp
tcp        0      0 127.0.0.1:44997         127.0.0.1:4369          ESTABLISHED 58/beam.smp
tcp6       0      0 :::7777                 :::*                    LISTEN      58/beam.smp
```
When I run command `ejabberdctl status` again:
```bash
$ sudo ejabberdctl status
Protocol 'inet_tcp': register/listen error: eaddrinuse
```

It's crashed error `Protocol 'inet_tcp': register/listen error: eaddrinuse`,i can telnet the port:

```bash
$ telnet nocs.cn 34825
Trying 47.89.20.207...
Connected to nocs.cn.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```
does i config wrong?

**Comment by mremond** [comment]
It is a window. If you are launching 2 nodes, you need more than one possible port.

**Comment by zyfmix** [comment]
@mremond Thank you,I will try later.
