### ISSUE TITLE
File transfer error

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2944]
Hi All,
I am attemptimg to send a file .
I am using :
Ubuntu: 18
XMPP Client: Strophe
My client is trying to send the following Iq stanza. 

![image](https://user-images.githubusercontent.com/16096109/61209238-cf447500-a716-11e9-9060-566e32f501bc.png)

server is accepting a connection . but neither it is storing the file onserver neither the file collected on the other end. 
 If you found somthing illogical or noobish. I am new to XMPP. but please tell me as it is taking too much my time.

Thanks in advance.

**Comment by zinid** [comment]
Use `mod_http_upload`.

**Comment by mailtosagar** [comment]
Use mod_http_upload.

As in i have to change that in URL. 
Or in ejabberd.yml. 
If in ".yml" .What changes i need to change.
