### ISSUE TITLE
Didn't append log after the log print  a debug lager_handler_watcher info

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#2945]
Hi,

What version of ejabberd are you using?
19.02

What operating system (version) are you using?
Ubuntu 16.04.5 LTS

How did you install ejabberd (source, package, distribution)?
source

Everything is normal when starting up, a few days later, found that the log(/usr/loca/var/log/ejabberd/ejabberd.log) is not appended, the last log is 
```[debug] <0.4297.21>@lager_handler_watcher:126 Lager installed handler {lager_file_backend,"/usr/local/var/log/ejabberd/ejabberd.log"} into lager_event```

The LOGGING setting is just change  loglevel from 4 to 5
```
loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
```

**Comment by licaon-kter** [comment]
You want only ONE 10Mb log? At level 5 it will be filled pretty quick.

Count...more...or Size larger.

**Comment by cisiqo** [comment]
@licaon-kter   
Thank you, i will try it.
But according to what you mean that the log filled pretty quick, so the error maybe appear soon, but why appear after a few days.

**Comment by licaon-kter** [comment]
What error?

**Comment by cisiqo** [comment]
Oh..... The error it's mean the last log
```
[debug] <0.4297.21>@lager_handler_watcher:126 Lager installed handler {lager_file_backend,"/usr/local/var/log/ejabberd/ejabberd.log"} into lager_event
```

**Comment by licaon-kter** [comment]
That's just some [debug] info... Anything in `error.log` ?

**Comment by cisiqo** [comment]
The ```error.log``` and ```crash.log``` has no info at the moment.

**Comment by badlop** [comment]
No news in this ticket for two months, I guess it's either solved or isn't relevant anymore.
