### ISSUE TITLE
Not receiving Stanzas on ejabberd reload

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2946]
I am facing a problem .
I have uninstalled and reinstalled ejabberd. Applied the same configurations .
Earlier when i was sending the subscribe/unsubscribe stanza , i was able to get in real time . But now i am not getting any subcription stanzas . Forget about subscription stanzas, I am not receiving any stanzas as all the messages i am sending are getting stored in offline messages . Even on the page refresh and relogin, server is not sending .

You can look at these images for clarity.

![image](https://user-images.githubusercontent.com/16096109/61361175-a39fc700-a89d-11e9-996f-51f9d26a673a.png)

![image](https://user-images.githubusercontent.com/16096109/61361304-e5c90880-a89d-11e9-9b92-785aff2dd0af.png)

![image](https://user-images.githubusercontent.com/16096109/61361360-06915e00-a89e-11e9-9460-dc893bf3d0cd.png)

However, I am able to login and register and receive response from the server.

What could be the error. Please help.

**Comment by badlop** [comment]
That's a strange problem, it could be privacy rules configured by the clients, or some weird module you have enabled...

I propose you investigate it yourself. First of all uninstall ejabberd, delete the Mnesia spool files, and forget about whatever configuration you have made. Then start from zero:

1. Install ejabberd, do not change its configuration
2. start ejabberd
3. register two accounts
4. and subscribe them. Does everything work perfectly?
5. Restart ejabberd. Sending messages still work perfectly?
6. Now make ONE change in the configuration (maybe you want to configure a module, or enable a new module, or set SQL database, or whatever). Restart ejabberd. Try to send messages. Does it work?
7. Repeat step 6. for each change you make i nthe configuration, check if everything still works perfectly.

At some moment, maybe the problem appears again. What change in the configuration provoked it? Comment here.

**Comment by zinid** [comment]
What XMPP client are you using? Did you try standard clients such as Gajim, Dino or Conversations?

**Comment by mailtosagar** [comment]
Hi,
thanks
@badlop 
@zinid 
 the problem is i am it is sending message stanzas to all clients exept for one client. 
I am maling my own client using strophejs.

here is the probelm in broad.
Both are web client but one is using react (it is a front end js library ) and other is normal js included in HTML.  But thats not the problem. 

The thing is i am ejabberd server is recognizing every resource(react) as i am able to login from there. It is particularly not sending messages to that resource. I want to know under what circumstances ejabberd is deny the delivering stanza to a  resource.
i have wasted the entire day figuring this out .

**Comment by zinid** [comment]
> i have wasted the entire day figuring this out

Probably because you're asking in a wrong place? This a bug tracker which means you need to describe the bug. Also, ejabberd implements standard XMPP protocol with its extensions. If you want to receive a message on all resources you need to implement [XEP-0280](https://xmpp.org/extensions/xep-0280.html) in your client.

Again, check the behavior with the standard clients I listed above first.

**Comment by mailtosagar** [comment]
Thanks @zinid 
Well the solution was like i have set priority of my resource to -1 . and i have resolved this now. 

Thanks a lot for helpling me. Everyone.
