### ISSUE TITLE
STUN/TURN Signaling server

### ISSUE THREAD

**Issue by madmath03** [processone/ejabberd#2948]
**Is your feature request related to a problem? Please describe.**
STUN/TURN is fun and all, but when we need to call several 4 or more people, or some of those have a poor connection, it can get pretty much impossible to use.
In such cases, WebRTC requires a signaling server to synchronize the clients and reduce the workload and bandwith. If the client supports XMPP, it should be okay, but what if the client app only supports web sockets (for instance NextCloud Talk).

**Describe the solution you'd like**
Add a web socket compatible Signaling Server that can be used by STUN/TURN clients that do not support XMPP.

**Describe alternatives you've considered**

**Additional context**
NA

**Comment by zinid** [comment]
> Add a web socket compatible Signaling Server that can be used by STUN/TURN clients that do not support XMPP.

The whole point of a built-in STUN/TURN implementation is to assist XMPP/SIP clients with VoIP. We don't have any plans or desire to support other types of clients. There are more general TURN servers for this I guess.
