### ISSUE TITLE
not connect ejabberd to mysql cluster for mod_mam

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#2949]
I can not  to connect from server to other server with mysql cluster

```yaml
sql_type: mysql
sql_server: "xxx.xxx.xxx.234"
sql_port: 3306
sql_database: "chat"
sql_username: "admin"
sql_password: "12345"
sql_pool_size: 50
```

```yaml
mod_mam:
    db_type: sql
    default: always

```

 the log is:
```
2019-07-17 17:10:08.407 [error] emulator Error in process <0.1045.0> on node 'ejabberd@master0001.bimbask.com' with exit value:
 {{case_clause,255},
  [{p1_mysql_conn,greeting,2,[{file,"src/p1_mysql_conn.erl"},{line,460}]},
   {p1_mysql_conn,mysql_init,5,[{file,"src/p1_mysql_conn.erl"},{line,429}]},
   {p1_mysql_conn,init,8,[{file,"src/p1_mysql_conn.erl"},{line,324}]}]}
2019-07-17 17:10:08.409 [error] emulator Error in process <0.1047.0> on node 
  'ejabberd@master0001.bimbask.com' with exit value:
```

```
2019-07-17 17:10:13.401 [error] <0.1106.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.401 [error] <0.1108.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.401 [error] <0.1110.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.401 [error] <0.1112.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.401 [error] <0.1114.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.401 [error] <0.1116.0>@ejabberd_sql:log:994 p1_mysql_conn: post_start timeout
2019-07-17 17:10:13.497 [warning] <0.1044.0>@ejabberd_sql:connecting:369 mysql connection failed:
** Reason: "timed out"
** Retry after: 30 seconds

```

I hope helps!!

Regards!!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by badlop** [comment]
Looking at the source code mentioned in the error message, it seems the protocol version number is not supported: https://github.com/processone/p1_mysql/blob/master/src/p1_mysql_conn.erl#L460

You didn't mention what ejabberd version and what MySQL version you are trying.

Anyway, I didn't find in ejabberd documentation what MySQL versions are supported... I can only mention that mod_mam works for me using MySQL 5.7.26

**Comment by mremond** [comment]
@badlop Support for MySQL 8 wasa added in october 2018: https://github.com/processone/p1_mysql/commit/8fc8c08657bebc761c83a6b07dc25824b76a2ecf

So, all release since then support MySQL 8.

I guess @dverdugo85 is using an old version of ejabberd with MySQL 8.

You need to update ejabberd to support latest MySQL versions.

**Comment by dverdugo85** [comment]
@mremond  and @badlop  thank for your helps!! I am using mysql 7.6.1 cluster and ejabberd 19.05.... @badlop I need to change the version of mysql?????

Regards!!

**Comment by dverdugo85** [comment]
I cant to use mysql cluster 8 because  in this moment  is dmr... regards!!

**Comment by mremond** [comment]
Are you sure this is standard MySQL ? I thought there was no version 6 and 7 in MySQL.

**Comment by dverdugo85** [comment]
@mremond  I solved the problem!! regards!! I use mysql 7.6 and In cluster and ejabberd 19.05

**Comment by mremond** [comment]
How did you solve it ? By using latest ejabberd ?

**Comment by dverdugo85** [comment]
@mremond  when I create the cluster I need to create an account in mysql with reference to the Ip with the privileges. Regards!! in this moment have other problem when export to other server with other server name.....

 I edit the dum file  and change with the new name.


```
root@mongo-router-1:~# ejabberdctl restore /usr/local/var/lib/ejabberd/ejabberd.dump
WARNING: It is not recommended to run ejabberd as root
Problem 'error {case_clause,
                   {aborted,
                       {not_a_log_file,
                           "/usr/local/var/lib/ejabberd/ejabberd.dump"}}}' occurred executing the command.
Stacktrace: [{ejabberd_admin,restore_mnesia,1,
                             [{file,"src/ejabberd_admin.erl"},{line,602}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,360}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,274}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,252}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,197}]}]

```

Regards!!
