### ISSUE TITLE
Receiving errors in staza when try to discover the MUCsub extension.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2951]
Hi all,
I am able to use the MUC service by sending a presence stanza. Here i am creating the room using the subdomain "conference"
e.g. roomJID: avengers@conference.localhost 

Now i want to use the MUCsub extension .
I am using strophejs as xmpp client.
I am sending the stanza as below:
![image](https://user-images.githubusercontent.com/16096109/61535099-03899f80-aa4f-11e9-92bd-e9a7110b9d13.png)

but in return i am getting the following stanza.
![image](https://user-images.githubusercontent.com/16096109/61535113-0d130780-aa4f-11e9-9826-95e137259390.png)

What can be the reason. If you feel this a noob doubt, that means i do not know the parameters significane . please answer this.

**Comment by mremond** [comment]
You are sending stanza to `muc.localhost` and your server seems to be configured as default with MUC service as `conference.localhost`. The service `muc.localhost` is unknown.
