### ISSUE TITLE
End to End Encryption

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2955]
Hi All, 
Thanks for helping me so far. 
I have just studied End to End encryption Protocols (signal, MTProto). 
I want to know whether it will support These protocols as they are not Directly included in any XEPs.

**Comment by weiss** [comment]
There is, for example, [XEP-0384][1].

Please note that this is a bug tracker for a server called ejabberd, not a general support venue for arbitrary XMPP questions..  The issues you're spamming this tracker with are not about ejabberd bugs.  You've been told several times already.

[1]: https://xmpp.org/extensions/xep-0384.html

**Comment by mailtosagar** [comment]
Sorry for that .
There are very few questions support for the ejabberd on stackoverflow. And on the forum also there are several questions which went un answered.

However I will keep that in mind from now onwards.
