### ISSUE TITLE
import to new server to 16.06 to 19.05

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#2957]
**Is your feature request related to a problem? Please describe.**

**when I try to import dump file in ejabberd 19.05 I have this problem**

I hope  helps!!

Regards!!
```
root@ejabberd-router-1:~# ejabberdctl restore /usr/local/var/lib/ejabberd/ejabberd.dump
WARNING: It is not recommended to run ejabberd as root
Problem 'error {case_clause,
                   {aborted,
                       {not_a_log_file,
                           "/usr/local/var/lib/ejabberd/ejabberd.dump"}}}' occurred executing the command.
Stacktrace: [{ejabberd_admin,restore_mnesia,1,
                             [{file,"src/ejabberd_admin.erl"},{line,602}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,360}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,324}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,274}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,252}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,197}]}]
```

**Comment by dverdugo85** [comment]
hello @badlop  any idea this problem???

**Comment by dverdugo85** [comment]
In this line is  issue!!

```
import_dir(Path) ->
    case jd2ejd:import_dir(Path) of
        ok ->
            {ok, ""};
        {error, Reason} ->
            String = io_lib:format("Can't import jabberd14 spool dir ~p at node ~p: ~p",
				   [filename:absname(Path), node(), Reason]),
	    {cannot_import_dir, String}
    end.
```

**Comment by badlop** [comment]
See https://docs.ejabberd.im/admin/guide/managing/#list-of-ejabberd-commands

After a **dump** comes a **load**:

> dump ejabberd.dump: Dump internal Mnesia database to a text file dump.
> 
> load ejabberd.dump: Restore immediately from a text file dump. This is not recommended for big databases, as it will consume much time, memory and processor. In that case it’s preferable to use backup and install_fallback.
> 

Another alternative: after a **backup** comes a **restore**:

> backup ejabberd.backup: Store internal Mnesia database to a binary backup file.
> 
> restore ejabberd.backup: Restore immediately from a binary backup file the internal Mnesia database. This will consume a lot of memory if you have a large database, so better use install_fallback.

But it seems you first **dumped**, and now you want to **restore**... That will not work. Use the proper command.
