### ISSUE TITLE
send_message does not work for MUC room

### ISSUE THREAD

**Issue by g0ldstrike** [processone/ejabberd#2959]
**ejabberd version:** 19.5.0
**OS:** Ubuntu 18.04.2 LTS
**Using the ejabberd/ecs docker container**

The following command works fine:
`ejabberdctl send_message chat user1@localhost user2@localhost TestSubject TestBody`

However, sending a message to a MUC room does not work. Also, no error whatsoever is logged. Command:
`ejabberdctl send_message groupchat user1@localhost room1@conference.localhost TestSubject TestBody`

I tried many variations, changing the message type to _normal_, _headline_, without any luck. I also tried it both through _ejabberdctl_ as well as the API.

Is this expected to work? If not, is there any other way to send a message to a MUC room, being an admin on the server?

Thank you in advance.

**Comment by licaon-kter** [comment]
So a normal client like Conversation or Dino or Gajim fails too?

**Comment by badlop** [comment]
I give you three alternatives:

**A) Join the room.** In XEP-0045, to send a stanza to a room, it is required that the sender of the stanza is participant in the room, see https://xmpp.org/extensions/xep-0045.html#roles-priv

So, if I join room1 with user2 account and tka1 resource, then this works:

> ejabberdctl send_message groupchat user2@localhost/tka1 room1@muc.localhost TestSubject TestBody

**B) Make MUC service admin.** mod_muc provides the option access_admin, see https://docs.ejabberd.im/admin/configuration/#mod-muc which allows this feature:

> The administrators can send a groupchat message to the JID of an active room, and the message will be shown in the room as a service message.

So, if you configure properly in ejabberd.yml, user2 would not need to join the room for this to work:

> ejabberdctl send_message groupchat user2@localhost room1@muc.localhost TestSubject TestBody

**C) MUC/Sub.** ejabberd implements this custom protocol: https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/

If user2 subscribes to the room 

> $ ejabberdctl subscribe_room user2@localhost User2 room1@muc.localhost 'urn:xmpp:mucsub:nodes:messages' 

then it will work:

> $ ejabberdctl send_message groupchat user2@localhost room1@muc.localhost TestSubject TestBody

**Comment by g0ldstrike** [comment]
Thank you for your extensive reply.

When adding the user resource as in your first command, I noticed that setting the MUC subject suddenly worked. However, still no message body. When providing an empty subject as follows, the message was sent correctly:

`ejabberdctl send_message groupchat user1@localhost/res1 room1@conference.localhost "" TestBody`

When doing the same for your second command (sending a message as admin) and leaving the subject empty, it also works:

`ejabberdctl send_message groupchat admin@localhost room1@muc.localhost "" TestBody`

Summarizing: for a present user the resource must be provided, and for sending a message the subject must be empty. Perhaps this could be clarified in the docs? Without the help of @badlop I would not have figured this out.

**Comment by badlop** [comment]
> I noticed that setting the MUC subject suddenly worked. However, still no message body. 

Right, when sending a message with subject, this applies: 
https://xmpp.org/extensions/xep-0045.html#subject-occupant

> When providing an empty subject as follows, the message was sent correctly:

Right, when sending only body, this applies:
https://xmpp.org/extensions/xep-0045.html#message

That is, send_message behaves like any other XMPP client, so XEP-0045 applies.

> Summarizing: for a present user the resource must be provided, and for sending a message the subject must be empty. Perhaps this could be clarified in the docs?

I consider the subject matter is explained in the XEP, and it is not the server's documentation task to explain again the protocols it implements.

On the other side, the other question you had: the full or bare JIDs to provide in the FROM attribute... that behaviour in ejabberd is dependent of some specific ejabberd implementation decisions (support for MUC service admins and support for experimental MUC/Sub feature), so I've documented that part in the command description.

**Comment by jnmayur** [comment]
@badlop we've a similar use case, wherein we need to send private messages to users in a room and we're using muc-sub.
However, when we use below API, we're not receiving messages unless we subscribe our admin user to the room. No errors observed on the server.
`curl -X POST \
  http://host:5281/api/send_stanza \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: e34cd685-a015-49d8-b2ae-c93acaf210b0' \
  -H 'cache-control: no-cache' \
  -d '{
  "from": "admin@host",
  "to": "room@conference.host/user1",
  "stanza": "<message type='\''chat'\''><body>Recommendation</body><recommendations><list><recommendation><text>Hello</text><templateType>plain</templateType><action>send_message</action></recommendation><recommendation><text>Hi</text><templateType>plain</templateType><action>send_message</action></recommendation></list></recommendations></message>"
}'`

And here is our config for muc
`mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
      persistent: true
      allow_subscription: true
    db_type: sql
`
Here is acl `acl:
  admin:
    user: "admin@host"
    ip: "0.0.0.0"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.1/8"
      - "::1"
access:
  configure:
    admin: allow
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: loopback
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
              - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
    what:
      - "status"
      - "register"
      - "connected_users_number"
      - "create_room"
      - "set_room_affiliation"
      - "subscribe_room"
      - "unregister"
      - "send_stanza"
      - "send_message"
`

**Comment by licaon-kter** [comment]
@jnmayur Which server version?

**Comment by jnmayur** [comment]
@licaon-kter 20.04.

**Comment by badlop** [comment]
What you explain looks similar to the topic described initially in this issue, and may be related... or maybe it isn't directly related.

In any case, this issue was marked as solved 18 months ago for ejabberd 19.08.

What you mention will require a new investigation, and will trigger new comments, so it requires a new issue. Please create a new issue, copy your explanation from here, and mention that "it may be related to #2959".
