### ISSUE TITLE
s2s certificate instead c2s certificate

### ISSUE THREAD

**Issue by SERIY1337** [processone/ejabberd#2964]
Hello!

When i connected to server on 5222 port, i received untrasted s2s certificate instead c2s certificate.

I checked it in next ejabberd versions: 18.01, 18.03. In versions 17.08,17.09,17.11 all worked.

`# lsb_release -a`
> `No LSB modules are available.`
> `Distributor ID: Debian`
> `Description:    Debian GNU/Linux 9.5 (stretch)`
> `Release:        9.5`
> `Codename:       stretch`

**ejabberd.yml configuration:**

`define_macro:`
&nbsp;&nbsp;&nbsp;&nbsp;`'APICERTFILE': "/opt/ejabberd/conf/api.pem"`
&nbsp;&nbsp;&nbsp;&nbsp;`'C2SCERTFILE': "/opt/ejabberd/conf/server.pem"`
&nbsp;&nbsp;&nbsp;&nbsp;`'S2SCERTFILE': "/opt/ejabberd/conf/s2s.pem"`

`listen:`
&nbsp;&nbsp;&nbsp;&nbsp;-
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`port: 5222`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ip: "::"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`module: ejabberd_c2s`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`starttls: true`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`certfile: 'C2SCERTFILE'`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`starttls_required: true`
&nbsp;&nbsp;&nbsp;&nbsp;-
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`port: 5269`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ip: "::"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`module: ejabberd_s2s_in`

`s2s_use_starttls: true`
`s2s_certfile: 'S2SCERTFILE'`

**subject server.pem cert**
`openssl x509 -in /opt/ejabberd/conf/server.pem -text -noout -subject`
&nbsp;&nbsp;&nbsp;&nbsp;`subject=C = FR, ST = Paris, L = Paris, O = ProcessOne, OU = IT, CN = localhost`

**subject s2s.pem cert**
``openssl x509 -in /opt/ejabberd/conf/s2s.pem -text -noout -subject``
&nbsp;&nbsp;&nbsp;&nbsp;`subject=C = RU, ST = MSK, L = MSK, O = C, OU = C, CN = conference.ejabberd`

**Screen from gajim**
![](https://i.imgur.com/Kk9kUAE.png)

Why when i autorize in my server via 5222 port i receiving s2s certificate?

**Comment by zinid** [comment]
In upcoming release there will no be longer ability to set different certificates for s2s and c2s. So I close the ticket: use a single certificate defined in `certfiles` section of `ejabberd.yml`.
