### ISSUE TITLE
Ejabberd from version 18.12 doesn't compile from hex package

### ISSUE THREAD

**Issue by pdorofiejczyk** [processone/ejabberd#2967]
I am getting following error when trying to compile mix project with ejabberd as dependency from hex package.

`==> ejabberd
Compiling 1 file (.erl)
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:59: illegal pattern
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Error' is unbound
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Stacktrace' is unbound
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:63: variable 'Stacktrace' unsafe in 'try' (line 60)
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Error' unsafe in 'try' (line 60)
/usr/local/Cellar/erlang/21.2/lib/erlang/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Stacktrace' unsafe in 'try' (line 60)`

When setting github source as dependency it compiles properly.

Tested on version 18.12, 19.02 and 19.05 and erlang/OTP version 20.3

**Comment by badlop** [comment]
Hi! I know very little about hex. What are the minimal steps to reproduce this problem, from scratch?

**Comment by badlop** [comment]
I am not able to reproduce that problem. Maybe it was solved in those years? I'll describe the precise steps to get it working. If anybody still faces this problem with a recent ejabberd or erlang or elixir version, please provide details.

I have installed Erlang/OTP 23.2 and Elixir 1.10.3, then:
```
git clone https://github.com/processone/ejabberd.git
cd ejabberd/
./autogen.sh
./configure --with-rebar=mix
make
mix hex.publish --dry-run
mix hex.build --unpack
cd ..

mix new example --umbrella

mkdir -p example/var/lib/ejabberd
mkdir -p example/etc/ejabberd/
cp ejabberd/ejabberd.yml.example example/etc/ejabberd/ejabberd.yml
cp ejabberd/config/runtime.exs to example/config/config.exs

cd example
```
Now edit mix.exs and add ejabberd as a dependency:  
```
  defp deps do
    [{:ejabberd, path: "/home/bernar/e/git/ejabberd-21.4.124"}]
  end
```  
Finally, compile and start it:
```
mix deps.get
mix compile
iex -S mix

Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]
Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> :ejabberd.start

2021-07-16 16:23:44.230868+02:00 [info] Loading configuration from etc/ejabberd/ejabberd.yml
2021-07-16 16:23:44.705595+02:00 [info] Configuration loaded successfully
...
2021-07-16 16:23:48.509527+02:00 [info] ejabberd 21.4.121 is started in the node nonode@nohost in 4.47s
2021-07-16 16:23:48.510525+02:00 [info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
...
{:ok,
 [:unicode_util_compat, :idna, :sasl, :base64url, :p1_utils, :fast_tls,
  :fast_xml, :fast_yaml, :xmerl, :jiffy, :jose, :stringprep, :stun, :yconf,
  :ejabberd]}
iex(2)> 
```
