### ISSUE TITLE
Incorrect error condition on certain invalid server names

### ISSUE THREAD

**Issue by ge0rg** [processone/ejabberd#2969]
When sending an IQ to a remote server that doesn't exist, the expected protocol flow is this:

Example with non-existing server `foo`:
```xml
S: <iq to='foo' id='i5Bf1-121' type='get'><query xmlns='http://jabber.org/protocol/disco#info'></query></iq>
R: <iq xml:lang='de-DE' to='me' from='foo' type='error' id='i5Bf1-121'>
    <query xmlns='http://jabber.org/protocol/disco#info'/>
    <error code='404' type='cancel'>
      <remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
      <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>DNS lookup failed: non-existing domain</text>
    </error>
</iq>
```
(This is the correct `remote-server-not-found` condition).

When sending a request to the also invalid server `foo-`, the response is an incorrect `remote-server-timeout`:
```xml
S: <iq to='foo-' id='i5Bf1-123' type='get'><query xmlns='http://jabber.org/protocol/disco#info'></query></iq><r xmlns='urn:xmpp:sm:3'/>
R: <iq xml:lang='de-DE' to='georg@conversations.im/yaxim.C65EEA6E' from='foo-' type='error' id='i5Bf1-123'>
    <query xmlns='http://jabber.org/protocol/disco#info'/>
    <error code='504' type='wait'>
      <remote-server-timeout xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
      <text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Remote domain is not an IDN hostname</text>
    </error>
</iq>
```
As opposed to the error code/type, this hostname will never become a valid IDN hostname ;-)

**Comment by TitusSun** [comment]
Hi I met this issue too, but I check above answer, can't find the how to resolve this problem.

xmpp DEBUG _handle_stream_stanza RECV: <iq id="active1" type="error" to="admin@sdt14523/148251412999643354512530" lang="en" from="http://192.168.199.100"><query xmlns="http://jabber.org/protocol/disco#items" node="sessions"/><error code="404" type="cancel"><remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Remote domain is not an IDN hostname</text></error></iq>

**Comment by licaon-kter** [comment]
@TitusSun with ejabberd 20.04? What OS? What config?

**Comment by Kalmuraee** [comment]
Got the same Issue here.

**Comment by TitusSun** [comment]
> @TitusSun with ejabberd 20.07? What OS? What config?

it's ejabberd20.04. windows. I resolved it by myself.  
this error caused by the demo code of active.

    if (status == XMPP_CONN_CONNECT) {
        fprintf(stderr, "DEBUG: connected\n");

        /* create iq stanza for request */
        iq = xmpp_iq_new(ctx, "get", "active1");
		if(JID_SERVER != NULL)
        	iRet = xmpp_stanza_set_to(iq, JID_SERVER);
		else
			iRet = xmpp_stanza_set_to(iq, "admin@sdt14523");
		
		fprintf(stderr, "DEBUG: xmpp_stanza_set_to iRet: %d\n", iRet);

The jabberid is incorrect. You Could try above modifcation.
