### ISSUE TITLE
[error] emulator Discarding message

### ISSUE THREAD

**Issue by satishdotpatel** [processone/ejabberd#2972]
I have 3 node rabbitMQ cluster in openstack and today when i restart all my cluster nodes one by one after that node-3 started flooding this error. 

OS: CentOS 7.6
RabbitMQ: 3.7.15
mnesia is cluster storage. 

> 2019-08-01 21:34:54.618 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486146.125675>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)
> 
> 2019-08-01 21:34:54.650 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486146.125740>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)
> 
> 2019-08-01 21:34:54.682 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486146.125781>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)
> 
> 2019-08-01 21:34:54.714 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486146.125824>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)
> 
> 2019-08-01 21:34:54.746 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486148.86543>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)
> 
> 2019-08-01 21:34:54.778 [error] emulator Discarding message {'$gen_call',{<0.442.0>,#Ref<0.3735088059.2228486145.133952>},stat} from <0.442.0> to <0.4312.12> in an old incarnation (1) of this node (2)

so far everything looks good not seeing any specific issue, i did restart all cluster nodes again but issue is still there. what option i have ?

**Comment by mremond** [comment]
Your report does not seem related to ejabberd but RabbitMQ, right ?
