### ISSUE TITLE
xep-0054 get VCard not working

### ISSUE THREAD

**Issue by sujankumar4593** [processone/ejabberd#2975]
Hi I have installed the ejabberd 19.05 with mysql db default get vcard iq not working for me

IQ Sent to server
`<iq id="idsujancTZDAjowSoECKGOn" to="user1@dev.local.xmpp.com" type="get" xmlns="jabber:client"><query xmlns="vcard-temp"/></iq>`

IQ Receiving  from server
```
<iq from="sujan@dev.local.xmpp.com" to="user2@dev.local.xmpp.com/Psi+" type="error" xml:lang="en" id="idsujancTZDAjowSoECKGOn">
<query xmlns="vcard-temp"/>
<error code="400" type="modify">
<bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Unknown tag &lt;query/&gt; qualified by namespace 'vcard-temp'</text>
</error>
</iq>
```

Any Help?

**Comment by mremond** [comment]
Your stanza does not seem to match the spec: https://xmpp.org/extensions/xep-0054.html#example-1

**Comment by sujankumar4593** [comment]
Thanks.
