### ISSUE TITLE
ejabberdctl uses an atom on each invocation

### ISSUE THREAD

**Issue by tijszwinkels** [processone/ejabberd#2977]
Our ejabberd crashed, with at the top of the dump-file:
`Slogan: no more index entries in atom_tab (max=1048576)`

further analysis of the dump-file showed many atoms in a format like:
`f1b56df2-ctl-ejabberd@localhost`

Turns out that ejabberdctl generates a new nodename on every invocation. These names get stored as an erlang atom. Since there can ever be at most ~1M atoms, and atoms are never garbage collected, erlang eventually runs out of atoms and crashes. 
Since we invoke ejabberdctl often for monitoring purposes, we run out after running for about five months without restarting.

This problem was originally fixed in: https://github.com/processone/ejabberd/commit/10c16b1cdf29799251f5ea19c1c004c60840b94d
However, in a more recent commit, the complexity to prevent this problem got refactored away: https://github.com/processone/ejabberd/commit/f7d4aae64db84e0a43fd9f5c446a6f77ebb07885

Proposed solution: Revert https://github.com/processone/ejabberd/commit/f7d4aae64db84e0a43fd9f5c446a6f77ebb07885, or reduce the uuid-part of the nodename to, for example, three hexadecimal characters, so at most 4096 atoms will ever be used for this purpose.

**Comment by zinid** [comment]
I don't know how this will be resolved, but for now you can use `+t` flag in `ERL_OPTIONS` of `ejabberdctl.cfg` to increase maximum number of atoms, see http://erlang.org/doc/efficiency_guide/advanced.html:
> By default, the maximum number of atoms is 1,048,576. This limit can be raised or lowered using the +t option.

**Comment by jsautret** [comment]
We now limit to 3 hexadecimal characters the random part used by ejabberdctl (762486d19)
