### ISSUE TITLE
[FreeTDS][SQL Server]Incorrect syntax near ';'.

### ISSUE THREAD

**Issue by cuongth** [processone/ejabberd#2978]
### Environment

Ejabberd-19.02
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
        Oct 28 2016 18:17:30 
        Copyright (c) Microsoft Corporation
        Express Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)

### Bug

```
[error] <0.370.0>@ejabberd_sql:check_error:1157 SQL query 'begin;' failed: <<"[FreeTDS][SQL Server]Incorrect syntax near ';'.">>
[error] <0.370.0>@ejabberd_sql:check_error:1157 SQL query 'commit;' failed: <<"[FreeTDS][SQL Server]The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.">>
```

### Suggestion

In MsSQL, it should use
```
begin transaction;
commit transaction;
```
in stead of current commands
```
begin;
commit;
```

**Comment by zinid** [comment]
SQL is awesome

**Comment by paul-charlton** [comment]
Hi,
I'm getting a similar issue connecting to an azure SQL instance using odbc:
host_config:
  "carbonlabs.tech":
    sql_type: odbc
    sql_server: "DSN=<DSN>;Driver=ODBC Driver 17 for SQL Server;UID=<USERNAME@HOST>;PWD=<PASSWORD>"

I was wondering if there was anything I could potentially be doing wrong?
