### ISSUE TITLE
Notification from MucSub coming without data

### ISSUE THREAD

**Issue by Chessekeks** [processone/ejabberd#2983]
Ejabberd version 19.05 , Windows 10 operating system.
I have external component which receive push notifications. With private messages it works fine, but notifications from subscribing on mucsub  coming without data
Here is example:
Notification from private message:
`<iq to='push.localhost' from='localhost' type='set' id='rr-1565238620808-6172871248889564935-YlCTDLmjzlA2dUN5tSv5KVoSm/U=-55238004'><pubsub xmlns='http://jabber.org/protocol/pubsub'><publish node='node1'><item><notification xmlns='urn:xmpp:push:0'><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE' type='hidden'><value>urn:xmpp:push:summary</value></field><field var='last-message-sender' type='jid-single' label='The sender of the last received message'><value>5@localhost/Psi+</value></field><field var='last-message-body' type='text-single' label='The body text of the last received message'><value>asasa</value></field></x></notification></item></publish><publish-options><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>8ka</value></field></x></publish-options></pubsub></iq>`

And notification from groupchat:
`<iq to='push.localhost' from='localhost' type='set' id='rr-1565238760183-15037600234277354438-UBSE1NY8r97Rzj19+G5pNndMusQ=-55238004'><pubsub xmlns='http://jabber.org/protocol/pubsub'><publish node='node1'><item><notification xmlns='urn:xmpp:push:0'/></item></publish><publish-options><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='secret'><value>8ka</value></field></x></publish-options></pubsub></iq>`

Is it possible include data to groupchat notification with any customizing ejabberd source code?

**Comment by toriqo** [comment]
@Chessekeks did you figure out a way to get the entire message in the notification?
Anyone else? :)

**Comment by Chessekeks** [comment]
@toriqo , sorry, we hadn't found solution =(

**Comment by toriqo** [comment]
@zinid any help on this one? thanks
