### ISSUE TITLE
 REST API Error timeout

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#2985]
Hi,

What version of ejabberd are you using?
**19.02**

What operating system (version) are you using?
**Ubuntu 16.04.5 LTS**

How did you install ejabberd (source, package, distribution)?
**source**

```
[error] <0.4843.92>@mod_http_api:handle:309 REST API Error: exit:
 {timeout,{p1_fsm,sync_send_all_state_event,[<0.685.0>,get_state]}}
 [{p1_fsm,sync_send_all_state_event,2,[{file,"src/p1_fsm.erl"},{line,253}]},
  {mod_muc_admin,get_room_affiliations,2,[{file,"src/mod_muc_admin.erl"},{line,1091}]},
  {mod_http_api,handle2,4,[{file,"src/mod_http_api.erl"},{line,323}]},
  {mod_http_api,handle,4,[{file,"src/mod_http_api.erl"},{line,281}]},
  {mod_http_api,perform_call,4,[{file,"src/mod_http_api.erl"},{line,238}]},
  {mod_http_api,process,2,[{file,"src/mod_http_api.erl"},{line,192}]},
  {ejabberd_http,process,2,[{file,"src/ejabberd_http.erl"},{line,404}]},
  {ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,522}]}]
```

When i user the api `get_room_affiliations` to get a muc affiliations, the error log appeared.
This error did not occur most of the time, just sometimes requesting frequently, this error can appeared. At this time the server's resources are still sufficient.

**Comment by licaon-kter** [comment]
Gist of the config?

**Comment by cisiqo** [comment]
My ejabberd config [ejabberd.yaml](https://gist.github.com/cisiqo/ca88d34e515fd9c5f9ec4ee145d6fa60)

The `ejabberdctl.cfg` file changed:
ERL_MAX_PORTS=1205536
ERL_PROCESSES=4062144
ERL_MAX_ETS_TABLES=4053

**Comment by badlop** [comment]
It seems, when calling the room to get its state, it takes too much time to reply. Maybe the room process is handling too much traffic (many occupants sending many messages or presences).

You can experiment by setting an acceptable timeout in the calling code, to see what happens. In this case it is 15 seconds. Of course, that doesn't solve the problem in the end, as the source of the timeout is still there:
```diff
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index cf4edeca2..6bb1496b9 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -196,7 +196,7 @@ change_item(Pid, JID, Type, AffiliationOrRole, Reason) ->
 
 -spec get_state(pid()) -> {ok, state()} | {error, notfound | timeout}.
 get_state(Pid) ->
-    try p1_fsm:sync_send_all_state_event(Pid, get_state)
+    try p1_fsm:sync_send_all_state_event(Pid, get_state, 15000)
     catch _:{timeout, {p1_fsm, _, _}} ->
 	    {error, timeout};
 	  _:{_, {p1_fsm, _, _}} ->
```

**Comment by cisiqo** [comment]
Thx, i will have a try.

**Comment by zinid** [comment]
The patch will work of course most of the time, but I'm not sure 15 seconds is enough in all cases.

**Comment by relbraun** [comment]
@badlop I don't use the source (I use the docker), how can I solve such a problem? (It occures for me when I try to set affiliation on a very large group [7000 users])

Thanks

**Comment by badlop** [comment]
Do you have a MUC room with 7000 simultaneous occupants? Or is it a room with 7000 affiliations (that may be offline, or may be joined in the room)?

For your use case, is it important that the clients get presence of all the other occupants? Or is presences irrelevant because you only care about message distribution?

**Comment by relbraun** [comment]
@badlop 
I have a room with 7000 affiliatios but 0 occupants because I'm using MUCSub. When I try to add new affiliation, it fails due to timeout error.

**Comment by badlop** [comment]
You have several ways to get some patched coded inside the container:

- A) Download ejabberd git, apply the patch, build your custom container image
- B) Download ejabberd git, apply the patch, compile ejabberd with Erlang/OTP 26 (the ejabberd 23.10 container image uses Erlang/OTP 26.1), and copy `mod_muc_room.beam` to the container replacing the existing file in `/opt/ejabberd-23.10/lib/ejabberd-23.10.0/ebin/mod_muc_room.beam`
- C) In the container, download `mod_muc_room.erl`, apply the change, then use `ejabberdctl debug` to compile that file, then move it to replace the existing file. See the guide later.

---

# How to compile a file inside the `ejabberd` container

This small text assumes you are using the [`ejabberd` container image](https://github.com/processone/ejabberd/pkgs/container/ejabberd), for example

```bash
docker run --name ejabberd -it -p 5222:5222 ghcr.io/processone/ejabberd live
```

However, if you are using the [`ecs` container image](https://hub.docker.com/r/ejabberd/ecs/), there are a few paths that are different, tell me and I'll update the instructions.

## Get the source code inside the container

As this is a small change, if you know how to use the `vi` text editor, you can download the upstream code and then edit it:
```bash
docker exec -it ejabberd wget https://raw.githubusercontent.com/processone/ejabberd/543404bcb8a5e263ae65fd4cfddf5a54ca7397d3/src/mod_muc_room.erl
docker exec -it ejabberd vi mod_muc_room.erl
```

If it is a heavily modified source code file or you don't know how to modify it inside the container, download it in your development machine, patch, and copy the desired source code inside the container with some other method.

## Compile the file

In the container open a debug console:
```bash
docker exec -it ejabberd ejabberdctl debug
```

In that console, compile the source code (notice the . at the end):
```erlang
ext_mod:compile_erlang_file("/opt/ejabberd/", "/opt/ejabberd/mod_muc_room.erl").
...
{ok,mod_muc_room}
```

To exit this debug shell, press: control+`g` and then `q`

## Copy the resulting *.beam file

This requires administrative privilege:

```bash
docker exec --user root ejabberd mv /opt/ejabberd/mod_muc_room.beam /opt/ejabberd-23.10/lib/ejabberd-23.10.0/ebin/
```

Finally, update the beam code in memory without need to restart the server:
```bash
docker exec -it ejabberd ejabberdctl update_list
mod_muc_room

docker exec -it ejabberd ejabberdctl update mod_muc_room
```

If code update is not enough to make your patch take effect, of course you can fully restart ejabberd inside the container:
```bash
docker exec -it ejabberd ejabberdctl restart
```

**Comment by relbraun** [comment]
I am reopening it because I have changed the way I use the MUC rooms and now I don't affiliate the members to the rooms (except admins) but the rooms are password protected and I only subscribe the users to the rooms.

I see that in some cases, I get timeout failure when trying to subscribe the user to the MUC. The rooms are with a few members (10~ not occupants but subscribers).

Is there any idea how can I get the reason for this timeout? 

I use ejabberd from docker-ecs version 23.1 over kubernetes only single instance.
