### ISSUE TITLE
A Question: How to add custom authentication logic

### ISSUE THREAD

**Issue by Zedonboy** [processone/ejabberd#2986]
Am new to XMPP servers, can you please suggest how am going to authenticate user(with payment referals) before they can use ejabberd im functionality

I wont lie in HTTP servers, i use middlewares that check all incoming requests whether they are with the payment referals, before allowing request

Some am still puzzled on how to do this logic(middleware) in ejabberd.
Thank you

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/admin/configuration/#external-script ?
