### ISSUE TITLE
mix complie fails

### ISSUE THREAD

**Issue by cnoldtree** [processone/ejabberd#2988]
ubuntu 18.04
Erlang/OTP 20
Elixir 1.6.6
Ejabberd 19.05

vagrant@homestead:~/code/erlang_code/ejabberd-19.05-mix$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.6 (compiled with OTP 20)

![image](https://user-images.githubusercontent.com/12471261/62909846-d52e8400-bdb0-11e9-9f01-dd16eadbece5.png)

**Comment by prefiks** [comment]
So this error is from missing libgd on that system or at least missing dev headers for it.
