### ISSUE TITLE
mod_pubsub exception error: undefined function node_hometree_sql:options/0

### ISSUE THREAD

**Issue by wahjava** [processone/ejabberd#2991]
I have upgraded ejabberd to 19.08, and started getting following errors.

On XMPP log-out:

    2019-08-16 05:22:17.805 [error] <0.618.0>@mod_pubsub:get_transaction_response:3895 Transaction aborted:
    ** exception error: undefined function node_hometree_sql:options/0
       in function  nodetree_tree_sql:raw_to_node/2 (src/nodetree_tree_sql.erl, line 294)
       in call from node_flat_sql:'-get_entity_affiliations/2-lc$^3/1-0-'/2 (src/node_flat_sql.erl, line 345)
       in call from node_flat_sql:get_entity_affiliations/2 (src/node_flat_sql.erl, line 346)
       in call from mod_pubsub:node_call/4 (src/mod_pubsub.erl, line 3803)
       in call from mod_pubsub:'-do_transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3856)
       in call from ejabberd_sql:execute_bloc/1 (src/ejabberd_sql.erl, line 545)
       in call from ejabberd_sql:run_sql_cmd/4 (src/ejabberd_sql.erl, line 462)
    2019-08-16 05:22:17.812 [info] <0.618.0>@ejabberd_c2s:process_terminated:294 (tls|<0.618.0>) Closing c2s session for user@domain.tld/resource: Stream reset by peer
    2019-08-16 05:22:18.609 [info] <0.420.0>@ejabberd_listener:accept:256 (<0.665.0>) Accepted connection 192.168.1.2:29274 -> 10.0.0.1:5269

On XMPP log-in:

    2019-08-16 05:23:05.914 [error] <0.667.0>@mod_pubsub:get_transaction_response:3895 Transaction aborted:
    ** exception error: undefined function node_hometree_sql:options/0
       in function  nodetree_tree_sql:raw_to_node/2 (src/nodetree_tree_sql.erl, line 294)
       in call from node_flat_sql:'-get_entity_subscriptions/2-fun-7-'/3 (src/node_flat_sql.erl, line 409)
       in call from lists:foldl/3 (lists.erl, line 1263)
       in call from node_flat_sql:get_entity_subscriptions/2 (src/node_flat_sql.erl, line 407)
       in call from mod_pubsub:node_call/4 (src/mod_pubsub.erl, line 3803)
       in call from mod_pubsub:'-do_transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3856)
       in call from ejabberd_sql:execute_bloc/1 (src/ejabberd_sql.erl, line 545)

I have removed `hometree` plugin from `mod_pubsub`, and am using MySQL as database.

Please let me know if you need more information.

Thanks!

**Comment by zinid** [comment]
That's because you have left `hometree` plugin written in `pubsub_node` table.

**Comment by wahjava** [comment]
Thanks, after purging the rows, it doesn't happen anymore.
