### ISSUE TITLE
Resource overwriting

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2992]
Hi,
I am using the "http-bind" in my web application. The thing is i want to limit WEB resource login. 
every time i connect(or refresh) server assign the new resource for the connection. i want to limit this and to show the user that you are "already login somwhere else" . 

Upon new login this is the behaviour i want to implement.
1. Show user you are login somwhere else and if user select to logout from there, resource should be disconnect.
2. Upon new login new resource should be assigned the same ID. as from the previous resource so that it should not receive the events or messages that it has already received earlier .

**Comment by licaon-kter** [comment]
So there's no actual issue?

Maybe join the conference instead: xmpp:ejabberd@conference.process-one.net?join

**Comment by mailtosagar** [comment]
ok
