### ISSUE TITLE
NO Virtual host on ejabberd web admin interface

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#2996]
Hi, 
I am building ejabberd from source .
OS: ubuntu 18

I can login into the web portal using admin username and password I created via ejabberdctl command. But on web interface i am not able to see localhost as a virtual host . Here is the screenshot .

![image](https://user-images.githubusercontent.com/16096109/63245126-e8dc5d80-c27c-11e9-9416-ce9faaaca696.png)

on ejabberdctl status.
![image](https://user-images.githubusercontent.com/16096109/63245167-090c1c80-c27d-11e9-8e5b-26034ddf7618.png)

Please Help this if i have missed something during installation

**Comment by licaon-kter** [comment]
Gist of the ejabberd.yml?

**Comment by badlop** [comment]
> But on web interface i am not able to see localhost as a virtual host 

That means the account you provided to login to the web interface does not have admin rights. Add the account to acl section of your ejabberd.yml configuration file, or use an account that already have admin rights.

**Comment by zinid** [comment]
I think the question is answered.

**Comment by zhouhao27** [comment]
How to add an account with admin rights?

**Comment by badlop** [comment]
See examples in https://docs.ejabberd.im/admin/configuration/basic/#acl-definition

```yaml
acl:
  admin:
    - user: "admin1@example.org"

access:
  configure:
    admin: allow
```
