### ISSUE TITLE
Module mod_offline_http_post not install ejabberd-18.12.1

### ISSUE THREAD

**Issue by laurohen** [processone/ejabberd#2999]
How do I install the module of this git below:

https://github.com/PH-F/mod_offline_http_post

What is the path to the mass of modules in ejabberd-18.12.1?

**Comment by licaon-kter** [comment]
Aren't the instructions there working?

**Comment by badlop** [comment]
> What is the path to the mass of modules in ejabberd-18.12.1?

It depends on how you install ejabberd: binary installer, in what operating system, package of some operating system, source package with some custom install options...

**Comment by zinid** [comment]
Not a bug.

**Comment by laurohen** [comment]
I can't put module http_offline in ejabberd version 18.12.1
What version of this http_offline module can I use and how do I use ejabberd 18.12.1?

Which path to module folder in this ejabberd version?

In 18.12.1 can I put this module?
https://github.com/PH-F/mod_offline_http_post

Where is ?
.ejabberd-module / sources /

**Comment by licaon-kter** [comment]
@laurohen did you try to make that folder and clone in it?

**Comment by licaon-kter** [comment]
How do you know it doesn't work? Did it install ok? What was the output of those commands? What messages do you see in ejabberd.log with `loglevel 4`?

**Comment by laurohen** [comment]
> How do you know it doesn't work? Did it install ok? What was the output of those commands? What messages do you see in ejabberd.log with `loglevel 4`?

installation is unsuccessful.

**Comment by licaon-kter** [comment]
@laurohen how do you know? You haven't provided any logs, info, anything

**Comment by laurohen** [comment]
@mremond 

Has anyone managed to make some http_offline module work on ejabberd 18.12.1?

I need a http_offline module working on ejabberd 18.12.1

**Comment by laurohen** [comment]
/opt/ejabberd-modules/sources/mod_offline_http_post/ebin/mod_offline_http_post.bea#: error writing file: no such file or directory
/opt/ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl:6: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/opt/ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl:6: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')
/opt/ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl:24: Warning: variable 'Action' is unused
Error: {compilation_failed,"/opt/ejabberd-modules/sources/mod_offline_http_post/src/mod_offline_http_post.erl"}

**Comment by licaon-kter** [comment]
This is the result of running `sudo -u ejabberd /opt/ejabberd-19.02/.ejabberd-module/bin/ejabberdctl module-install mod_offline_http_post` ?

**Comment by BoopathyRaja** [comment]
Hi,

Did anyone find solution for this?
I am also looking for the solution for same issue. (Ejabberd installed from binary source)
Did anyone find solution please post here. It will bo more helpfull.

Thanks in advance

**Comment by BoopathyRaja** [comment]
### Finally got the solution

**// Install Ejabberd 18.12.1 from source**
wget https://www.process-one.net/downloads/ejabberd/18.12.1/ejabberd-18.12.1.tgz

tar -xvf ejabberd-18.12.1.tgz

**// Clone mod_offline_http_post**
git clone https://github.com/PH-F/mod_offline_http_post.git;

cp mod_offline_http_post/src/mod_offline_http_post.erl ejabberd-18.12.1/src/

cd ejabberd-18.12.1

./autogen.sh

./configure -prefix=/opt/ejabberd --enable-user=ejabberd --enable-mysql

make

sudo make install

sudo chown -R ejabberd:ejabberd /opt/ejabberd

**// Login to ejabberd user**
cd /opt/ejabberd/sbin/

**// Update the yml file (As mentioned in https://github.com/PH-F/mod_offline_http_post)**
vi /opt/ejabberd/etc/ejabberd/ejabberd.yml
_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mod_offline_http_post:
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auth_token: "secret"
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;post_url: "http://example.com/notify"
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;confidential: true_

./ejabberdctl stop

./ejabberdctl start
