### ISSUE TITLE
ejabberd_config:get_option:161 Option 'auth_use_cache' is not defined for virtual host 

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd#3000]
Hi, trying to log in to web admin of ejabberd 19.08 with a virtual host that does not exist in the config results in the following log entry:

```
2019-08-21 20:53:45.842 [warning] <0.751.0>@ejabberd_config:get_option:161 Option 'auth_use_cache' is not defined for virtual host 'whatever.com'. This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {auth_use_cache,<<"whatever.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (ejabberd_config.erl, line 157)
   in call from ejabberd_auth:db_user_exists/3 (ejabberd_auth.erl, line 618)
   in call from ejabberd_auth:'-user_exists/2-fun-0-'/3 (ejabberd_auth.erl, line 393)
   in call from lists:any/2 (lists.erl, line 1225)
   in call from ejabberd_web_admin:get_auth_account/5 (ejabberd_web_admin.erl, line 272)
   in call from ejabberd_web_admin:process/2 (ejabberd_web_admin.erl, line 216)
   in call from ejabberd_http:process/2 (ejabberd_http.erl, line 374)
```

I guess this should be handled differently: unknown vhosts should simply be denied.

**Comment by zinid** [comment]
I think there are more places in ejabberd web admin code where input is not checked at all, leading to various crashes. This should be investigated in details and fixed.

**Comment by badlop** [comment]
Ok, I've added detection to login auth, and also in mod_shared_roster when adding members, which also crashed. 

> I think there are more places in ejabberd web admin code where input is not checked at all, leading to various crashes.

I haven't found other places, do you remember them?

**Comment by zinid** [comment]
@badlop I don't remember, in the past (during refactoring) I found a few places and fixed them. I'm just not confident that there are no such places left.
