### ISSUE TITLE
Separate databases for different modules.

### ISSUE THREAD

**Issue by ivanov-aleksander** [processone/ejabberd#3007]
**Describe the solution you'd like**
I want to use separate databases for different modules. For example:

- For mod-offline, I want to use Postgresql database name "offlinemessages"
- For mod_vcard, I want to use Postgresql database name "vcards" 
- For session management, I want to use Postgresql database name "sessions"

But as I see currently I could use only one Postgresql for all modules.

**Comment by zinid** [comment]
There is no such ability and it is not planned in the future.
