### ISSUE TITLE
How to install custom module (Ejabberd 18.12.1 from binary installation)

### ISSUE THREAD

**Issue by BoopathyRaja** [processone/ejabberd#3009]
**How to install custom module (Ejabberd 18.12.1 from binary installation)**

I installed ejabberd 18.12.1 from binary. 
Now I want to install my custom module.
Is there is a way to install? If so how?

**Comment by licaon-kter** [comment]
Did you read https://github.com/processone/ejabberd/issues/2999#issuecomment-524817343 yet?

**Comment by BoopathyRaja** [comment]
Finally got the solution
// Install Ejabberd 18.12.1 from source
wget https://www.process-one.net/downloads/ejabberd/18.12.1/ejabberd-18.12.1.tgz

tar -xvf ejabberd-18.12.1.tgz

// Clone mod_offline_http_post
git clone https://github.com/PH-F/mod_offline_http_post.git;

cp mod_offline_http_post/src/mod_offline_http_post.erl ejabberd-18.12.1/src/

cd ejabberd-18.12.1

./autogen.sh

./configure -prefix=/opt/ejabberd --enable-user=ejabberd --enable-mysql

make

sudo make install

sudo chown -R ejabberd:ejabberd /opt/ejabberd

// Login to ejabberd user
cd /opt/ejabberd/sbin/

// Update the yml file (As mentioned in https://github.com/PH-F/mod_offline_http_post)
vi /opt/ejabberd/etc/ejabberd/ejabberd.yml
      mod_offline_http_post:
            auth_token: "secret"
            post_url: "http://example.com/notify"
            confidential: true

./ejabberdctl stop

./ejabberdctl start

**Comment by LumiProj** [comment]
Hi,

Can you help me how to install this module ttps://github.com/PH-F/mod_offline_http_post) on windows machine.

Thanks
