### ISSUE TITLE
Admin api error when using jwt as auth_method

### ISSUE THREAD

**Issue by sha256** [processone/ejabberd#3012]
I'm trying to use `jwt` as `auth_method` option. I can authenticate normal users, register using `ejabberdctl` but when I go to the admin url or try to register user using the admin api I get the following error:

I'm using version **19.08**

```
[error] REST API Error:
 register([{<<"user">>,<<"testuser5">>},{<<"host">>,<<"localhost">>},{<<"password">>,<<"passw0rd">>}])
 -> error:undef [{ejabberd_auth_jwt,user_exists,[<<"testuser5">>,<<"localhost">>],[]},
 {ejabberd_auth,'-db_user_exists/3-fun-0-',3,[{file,"src/ejabberd_auth.erl"},{line,623}]},
 {ets_cache,lookup,3,[{file,"src/ets_cache.erl"},{line,166}]},
 {ejabberd_auth,db_user_exists,3,[{file,"src/ejabberd_auth.erl"},{line,620}]},
 {ejabberd_auth,'-user_exists/2-fun-0-',3,[{file,"src/ejabberd_auth.erl"},{line,393}]},
 {lists,any,2,[{file,"lists.erl"},{line,1225}]},
 {ejabberd_auth,try_register,3,[{file,"src/ejabberd_auth.erl"},{line,278}]},
 {ejabberd_admin,register,3,[{file,"src/ejabberd_admin.erl"},{line,505}]}]
```

I tried to use both `sql` and `jwt` at the same time (e.g. `auth_method: [sql, jwt]`), the error still persists.

Thanks a ton for adding the `jwt` auth method.

**Comment by alexeyshch** [comment]
Should be fixed now.  Note, that if you use `auth_method: [jwt, sql]`, then users can authenticate using their passwords from SQL DB instead of JWT.

**Comment by sha256** [comment]
@alexeyshch, thanks for the fix. Is there any way to authenticate admins using passwords from sql db but users using JWT token only?
