### ISSUE TITLE
Providing wrong certificate

### ISSUE THREAD

**Issue by jugendhacker** [processone/ejabberd#3015]
I serve my website from another server under my main domain (let's call it example.com) and then I copy the certificate to the server ejabberd is running on (xmpp.example.com). conference.example.com is also pointing to the server ejabberd is running on so the cert of it is generated on this machine. Now I put both of these in ejabberds config and when I try to do s2s on conference.example.com it offers the cert for example.com and so hardened servers do not want to connect to my MUC Service anymore.

**Comment by zinid** [comment]
What ejabberd version? Do you see any certificate related warnings in the config?

**Comment by zinid** [comment]
Also, show the related sections of the config (where you configure the certificates).

**Comment by jugendhacker** [comment]
> What ejabberd version?

19.08

> Do you see any certificate related warnings in the config?

No

**Comment by jugendhacker** [comment]
> Also, show the related sections of the config (where you configure the certificates).

```yaml
certfiles:
  - "/home/jnr/certs/jugendhacker.de.crt"
  - "/home/jnr/certs/jugendhacker.de.key"
  - "/home/jnr/.config/letsencrypt/live/conference.jugendhacker.de/fullchain.pem"
  - "/home/jnr/.config/letsencrypt/live/conference.jugendhacker.de/privkey.pem"
`

**Comment by zinid** [comment]
Run ejabberd in live mode (or attach to running ejabberd using `ejabberdctl debug`) and type in:
```
ets:tab2list(pkix_certfiles).
```
(don't forget the trailing dot).
Show the output here.

**Comment by jugendhacker** [comment]
```
[{<<"jugendhacker.de">>,
  {undefined,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/f081d51b1c48e807a40d60ba8316571dcd510355">>,
             undefined}},
 {<<"conference.jugendhacker.de">>,
  {undefined,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/6c52111e0fb4a3404c8d84042ef978de869d8f87">>,
             undefined}}]
```

**Comment by zinid** [comment]
Hum, this looks correct...

**Comment by zinid** [comment]
Two more commands:
```
fast_tls:get_certfile(<<"jugendhacker.de">>).
```
and
```
fast_tls:get_certfile(<<"conference.jugendhacker.de">>).
```

**Comment by zinid** [comment]
For the record:
```
$ openssl s_client -connect xmpp.jugendhacker.de:64253 -starttls xmpp-server -xmpphost conference.jugendhacker.de -servername conference.jugendhacker.de 
...
---
Certificate chain
 0 s:CN = conference.jugendhacker.de
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

**Comment by zinid** [comment]
Ah, it seems like it picks the wrong cert when it performs outbound s2s connection.

**Comment by jugendhacker** [comment]
Oh that's strange

**Comment by jugendhacker** [comment]
> Two more commands:
> 
> ```
> fast_tls:get_certfile(<<"jugendhacker.de">>).
> ```
> 
> and
> 
> ```
> fast_tls:get_certfile(<<"conference.jugendhacker.de">>).
> ```

Should I still do this?

**Comment by zinid** [comment]
Yes, please.

**Comment by jugendhacker** [comment]
```
(ejabberd@localhost)2> fast_tls:get_certfile(<<"jugendhacker.de">>).
{ok,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/f081d51b1c48e807a40d60ba8316571dcd510355">>}
(ejabberd@localhost)3> fast_tls:get_certfile(<<"conference.jugendhacker.de">>).
{ok,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/6c52111e0fb4a3404c8d84042ef978de869d8f87">>}
```

**Comment by zinid** [comment]
And also:
```
ejabberd_pkix:get_certfile(<<"jugendhacker.de">>).
```
and
```
ejabberd_pkix:get_certfile(<<"conference.jugendhacker.de">>).
```

**Comment by jugendhacker** [comment]
```
(ejabberd@localhost)4> ejabberd_pkix:get_certfile(<<"jugendhacker.de">>).
{ok,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/f081d51b1c48e807a40d60ba8316571dcd510355">>}
(ejabberd@localhost)5> ejabberd_pkix:get_certfile(<<"conference.jugendhacker.de">>).
{ok,<<"/home/jnr/ejabberd/var/lib/ejabberd/certs/6c52111e0fb4a3404c8d84042ef978de869d8f87">>}
```

**Comment by zinid** [comment]
I tried the following command:
```
$ openssl s_client -connect xmpp.jugendhacker.de:64253 -starttls xmpp-server -xmpphost conference.jugendhacker.de -servername conference.jugendhacker.de 
```
And your server just drops the connection and STARTTLS phase. Do you see any error/warnings in the config?

**Comment by jugendhacker** [comment]
The command you provided works for me....

**Comment by zinid** [comment]
Remove `-servername` option.

**Comment by jugendhacker** [comment]
Now I get
```
2019-09-06 19:51:07.455 [info] <0.31577.0>@ejabberd_s2s_in:process_closed:131 Closing inbound s2s connection hidden_by_ejabberd -> conference.jugendhacker.de: TLS failed: SSL_CTX_use_certificate_file failed: error:02001002:system library:fopen:No such file or directory
2019-09-06 19:51:07.455 [warning] <0.31577.0>@ejabberd_s2s_in:terminate:286 (tls|<0.31577.0>) Failed to secure inbound s2s connection: TLS failed: SSL_CTX_use_certificate_file failed: error:02001002:system library:fopen:No such file or directory
```

**Comment by zinid** [comment]
Wut? Check that both files exist and are readable by ejabberd:
- `/home/jnr/ejabberd/var/lib/ejabberd/certs/6c52111e0fb4a3404c8d84042ef978de869d8f87`
- `/home/jnr/ejabberd/var/lib/ejabberd/certs/f081d51b1c48e807a40d60ba8316571dcd510355`

**Comment by jugendhacker** [comment]
They exist and they are readable for the user I run ejabberd from

**Comment by zinid** [comment]
Also try
```
$ openssl x509 -text -noout -in $CERTFILE
```
for both certificates and check that the first certificate is signed for conference and the second one is for your virtual host

**Comment by jugendhacker** [comment]
Yes both are signed for the right domain

**Comment by zinid** [comment]
Did you restart ejabberd or just reloaded the config?

**Comment by jugendhacker** [comment]
Both
