### ISSUE TITLE
Custom Field in vCard .

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3017]
Hi, 
I am using ejabberd 19.05 from binaries. Server is configured to mySQL . 

I want to store additional data in vCard.

I have made an additional column in the table "vCard_search" in the ejabberd database.
 
![image](https://user-images.githubusercontent.com/54536845/64612334-29994380-d3f1-11e9-901a-6aefcf6e4f25.png)

and I am sending the This IQ stanza:
![image](https://user-images.githubusercontent.com/54536845/64612790-471add00-d3f2-11e9-8596-265676b26524.png)

It is returning success stanza. but When i get th stanza i am only getting two field like this:
![image](https://user-images.githubusercontent.com/54536845/64612963-a5e05680-d3f2-11e9-95ed-2e43825f67d1.png)

Please suggest any changes i have to do if i want to have any additional data stored as vcard in my Database .
Thank you

**Comment by zinid** [comment]
The XMPP prototocol doesn't allow putting random elements within predefined namespace (that is 'vcard-temp').

**Comment by shaggi7** [comment]
Thanks @zinid 
So i have to do some editing in source code in order to do so. right???

**Comment by zinid** [comment]
If you don't care about standards then yes.

**Comment by shaggi7** [comment]
Thanks @zinid for the help.
