### ISSUE TITLE
See admins in MUC/Sub rooms .

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3021]
Hi, 
I am making a chat applications for which i have to show admins to the group members Just like in Whatsapp everybody can see the group admins .
I am using MUC/SUB technique for the group chat system .

Is there a way to achieve this. 
Please Help!

**Comment by badlop** [comment]
So, you have a persistent room, several users subscribed to rooms messages, and now you want that their rosters show some specific accounts?

Do you need to show their presence (online, offline, busy, away...), or is it enought to show them as contacts?

**Comment by shaggi7** [comment]
Thanks @badlop for the reply.

```
So, you have a persistent room, several users subscribed to rooms messages, and now you want that their rosters show some specific accounts?
```
Yes, My rooms are persistant and all subscribers are subscribed to messages .
In my "CHAT APP" , I can show the subscribers of the group as group members . But just like in "Whatsapp" when we see group members list we see "Admins" also . It is indepandent of the fact that weather i am an "admin" or not . Admin list is available to every group subscriber .
  
```
Do you need to show their presence (online, offline, busy, away...), or is it enought to show them as contacts?
```
Nope, I don't want to show presence or status .
Just group subscribers and admins to every room subscriber .

**Comment by badlop** [comment]
In ejabberd WebAdmin, create a shared roster group called `admins` with members: the admin accounts.

Then create another shared roster group called `allaccounts` with members: `@all@`, and displayed groups: `admins`

When users login again, they will get the admin accounts in their rosters.

For details see https://docs.ejabberd.im/admin/configuration/#mod-shared-roster

**Comment by shaggi7** [comment]
@badlop 
In this ejabberd WebAdmin is involved. 
Whenever a group is created , can we update these shared roster group from the client's end ???

**Comment by badlop** [comment]
I don't understand your question, so I guess no. Try it as I described, maybe it solves the problem. If it doesn't solve your problem, then I see no other solution.

**Comment by shaggi7** [comment]
Ok @badlop i will try and let you know about my result.

**Comment by shaggi7** [comment]
May be this can help to illustrate my query clearly. In this I assume you use whatsapp .

![image](https://user-images.githubusercontent.com/54536845/64906053-c82de900-d6fe-11e9-9141-b405fb804541.png)


In this you can see i am just a member of the group. But i can see Who is admin . Same functionality i want in my chat app.  But when a normal particpent with "affiliation  = 'member' " query for getting admin list stanza, it shows me error "Administrative privilages required" . How can i provide group admin list to all participant . 

Does changing affiliation or role would help?? or changing somewhere in the code will?? 

Sorry that i am frustating you with the same question again, but this is very important for my propject .

Thanks.

**Comment by badlop** [comment]
Looking in lines https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L2784 I found that, to view the list of admins, the user must be a room owner, or a room admin, or... room member and room must be non-anonymous.

So, I configure the room to be nonanoymous (setting the room option that allows anyone to view real Jabber IDs). Then I add that account as room member. Finally, that user can get the list of admins, even if not subscribed:

```xml
<iq id='62:163616'
	type='get'
	to='room1@muc.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item affiliation='admin'/>
  </query>
</iq>
<iq to='user1@localhost/tka1'
	from='room1@muc.localhost'
	type='result'
	id='62:163616'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item jid='admin2@localhost'
	affiliation='admin'/>
    <item jid='admin3@localhost'
	affiliation='admin'/>
  </query>
</iq>
```

Alternatively, by applying this patch, the user can be either a room member or a room subscriber to get the list of admins:

```diff
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 808b8a246..5dafe0f7a 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -2776,6 +2776,7 @@ process_iq_admin(From, #iq{type = get, lang = Lang,
 		 StateData) ->
     FAffiliation = get_affiliation(From, StateData),
     FRole = get_role(From, StateData),
+    IsSubscriber = is_subscriber(From, StateData),
     case Item of
 	#muc_item{role = undefined, affiliation = undefined} ->
 	    Txt = ?T("Neither 'role' nor 'affiliation' attribute found"),
@@ -2783,7 +2784,7 @@ process_iq_admin(From, #iq{type = get, lang = Lang,
 	#muc_item{role = undefined, affiliation = Affiliation} ->
 	    if (FAffiliation == owner) or
 	       (FAffiliation == admin) or
-	       ((FAffiliation == member) and
+	       (((FAffiliation == member) or IsSubscriber) and
 		not (StateData#state.config)#config.anonymous) ->
 		    Items = items_with_affiliation(Affiliation, StateData),
 		    {result, #muc_admin{items = Items}};
```

**Comment by shaggi7** [comment]
Thanks @badlop .Lemme check and Then I'll get back to you.

**Comment by shaggi7** [comment]
Thanks @badlop  for the help so far . It worked.

Just one more suggestions then you can this issue.

I am working on a chat app which is required to sync messages across multiple devices. At any point of time some of them may be offline and also i don't want to save the messages on the server but devices should get the messages when tey come back online. 
So you recommend MIX or continue using MUC ??

**Comment by badlop** [comment]
I am not informed about MIX, so I cannot give advice about that question. Anyway, this is a bug tracker, not a forum for developer or admin advices. Try in stackoverflow.com, serverfault.com, the ejabberd chatroom or the ejabberd mailing list.
