### ISSUE TITLE
MUC: Apply default role after revoking admin affiliation

### ISSUE THREAD

**Issue by lovetox** [processone/ejabberd#3023]
## Environment

- ejabberd version: 19.05
- OS: Linux (Debian)
- Installed from: distro package

## Bug description

If a owner revokes admin status of an occupant with setting `affiliation=none`, ejabberd does not apply the default role "visitor" ( or at least participant for unmoderated MUCs).

The role of the occupant stays at `moderator` with an affiliation of `none`.

This is in contrast to revoking admin status with setting affiliation to `member`, this applies the default role `participant`.

```
<!-- Outgoing 15.09.2019 21:23:54 -->
<iq xmlns="jabber:client" to="test12@conference.temptatio.dev" type="set" id="aa7ab68a-b917-4097-8490-12e30e252f50" from="lovetox@temptatio.dev/gajim.GLEU3VID">
<query xmlns="http://jabber.org/protocol/muc#admin">
<item jid="lovetox@jabber.fr/gajim.YXQWWWC1" affiliation="none" />
</query>
</iq>

<!-- Incoming 15.09.2019 21:23:55 -->
<presence xmlns="jabber:client" to="lovetox@temptatio.dev/gajim.GLEU3VID" from="test12@conference.temptatio.dev/lovetox_" id="bb543755-3f6f-4753-803b-8bb554305b07">
<x xmlns="http://jabber.org/protocol/muc#user">
<item jid="lovetox@jabber.fr/gajim.YXQWWWC1" role="moderator" affiliation="none" />
</x>
</presence>
```

**Comment by badlop** [comment]
Ok, that's described in the first column of this table: https://xmpp.org/extensions/xep-0045.html#table-4
