### ISSUE TITLE
Mac OSX Binary-Install of 19.08 won't start due to libexpat / fxml_stream.so shared library version/misconfigure

### ISSUE THREAD

**Issue by scottcc** [processone/ejabberd#3026]
## Environment

- ejabberd version: 19.08
- Erlang version: `erl +V`
-- Binary/distribution:  ==> `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4`
-- OS/homebrew:  ==> `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.5`
- OS: Mac OSX (High Sierra, 10.12.6)
- Installed from: official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

I won't paste the whole config here unless needed - let me know.

```yaml
loglevel: 5
...
```

## Errors from error.log/crash.log

```
2019-09-17 16:29:42.554 [error] <0.177.0> failed to load NIF /Applications/ejabberd-19.08/lib/fast_xml-1.1.37/priv/lib/fxml_stream: Failed to load NIF library: 'dlopen(/Applications/ejabberd-19.08/lib/fast_xml-1.1.37/priv/lib/fxml_stream.so, 2): Library not loaded: /opt/local/lib/libexpat.1.dylib
  Referenced from: /Applications/ejabberd-19.08/lib/fast_xml-1.1.37/priv/lib/fxml_stream.so
  Reason: Incompatible library version: fxml_stream.so requires version 8.0.0 or later, but libexpat.1.dylib provides version 7.0.0'
2019-09-17 16:29:42.554 [error] <0.176.0> CRASH REPORT Process <0.176.0> with 0 neighbours exited with reason: {unable_to_load_nif,{fast_xml,start,[normal,[]]}} in application_master:init/4 line 138
2019-09-17 16:29:42.555 [error] <0.173.0> CRASH REPORT Process <0.173.0> with 0 neighbours exited with reason: {{fast_xml,{unable_to_load_nif,{fast_xml,start,[normal,[]]}}},{xmpp,start,[normal,[]]}} in application_master:init/4 line 138
2019-09-17 16:29:42.588 [error] <0.189.0> External eimp process (pid=84847) has terminated unexpectedly, restarting in a few seconds
2019-09-17 16:29:42.588 [error] <0.191.0> External eimp process (pid=84848) has terminated unexpectedly, restarting in a few seconds
2019-09-17 16:29:42.589 [error] <0.193.0> External eimp process (pid=84849) has terminated unexpectedly, restarting in a few seconds
2019-09-17 16:29:42.592 [error] <0.195.0> External eimp process (pid=84851) has terminated unexpectedly, restarting in a few seconds
2019-09-17 16:29:42.672 [critical] <0.106.0>@ejabberd_app:start:71 Failed to start ejabberd application: Exception occurred during configuration processing. This is most likely due to faulty/incompatible validator in third-party code. If you are not running any third-party code, please report the bug with ejabberd configuration file attached and the following stacktrace included:
** exception error: nif_not_loaded
   in function  erlang:nif_error/1
      called as erlang:nif_error(nif_not_loaded)
   in call from jid:string_to_usr/1 (src/jid.erl, line 121)
   in call from jid:decode/1 (src/jid.erl, line 136)
   in call from econf:'-domain/0-fun-0-'/1 (src/econf.erl, line 458)
   in call from yconf:'-list/2-fun-0-'/3 (src/yconf.erl, line 541)
   in call from lists:mapfoldl/3 (lists.erl, line 1354)
   in call from yconf:'-list/2-fun-1-'/3 (src/yconf.erl, line 537)
   in call from yconf:'-non_empty/1-fun-0-'/2 (src/yconf.erl, line 522)
```

## Bug description

It appears that compared to 19.05, the Mac Installer has changed the minimum requirement of libexpat to now need version 8.0.0, whereas the prior version was ok with version 7.0.0.

Here's an example of the 19.05 otool output:

```shell
> otool -L /Applications/ejabberd-19.05/lib/fast_xml-1.1.36/priv/lib/fxml_stream.so
/Applications/ejabberd-19.05/lib/fast_xml-1.1.36/priv/lib/fxml_stream.so:
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

When we look into the path expected for 19.08, it looks like it is searching in `/opt/local/lib/` which typically doesn't exist on Macs:

```shell
> otool -L /Applications/ejabberd-19.08/lib/fast_xml-1.1.37/priv/lib/fxml_stream.so
/Applications/ejabberd-19.08/lib/fast_xml-1.1.37/priv/lib/fxml_stream.so:
	/opt/local/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

I've tried using the homebrew version (has a current version of 8.10.0 and which lives in `/usr/local/opt/expat/lib/libexpat.1.dylib` but is keg-only so it's not a part of the path) but then I get a rolling pile of errors like `External eimp process (pid=18390) has terminated unexpectedly, restarting in a few seconds`, and /var/log/system.out is yelling about `no path for address 0x10e807000` so I suspect hacking in the library won't suffice.

**Comment by scottcc** [comment]
Thanks @badlop. Any idea of a workaround I could use until a new binary gets rolled, or do you think a new binary is sooner than later?

**Comment by ronsmithmd** [comment]
I'm having to reinstall ejabberd.... my host just died. What is the latest working installer version and which OS X  versions will ejabberd work with while we wait on the a fix for this?

**Comment by mremond** [comment]
Hi,

@ronsmithmd Which version of MacOS do you use ?

Since 19.08 we started to generate the installer on Mojave (10.14). Previously it was generated on High Sierra (10.13).

Installer has been tested on MacOS Mojave 10.14.

**Comment by ronsmithmd** [comment]
I’ve tried every version down to 15…on different machines with different operating systems. None of them open up port 5280 for the web admin like it did previously.

The installer won’t open  at all on Catalina, but it does on Mojave and previous versions. I do all the IT and development in my office so if there is any way I can help,. I would certainly do that. I’d actually love to have a FileMaker jabber plugin for my EMR.

Warmest regards,

Ron
Ron Smith, MD
Storybook Pediatrics

**Comment by scottcc** [comment]
Still waiting to hear what to do for OSX 10.12 too; I think the otool output I posted seems pretty clear that it is expecting the updated `libexpat` library exists in `/opt/local/lib`. Is there another build that can be used? This installer version is currently unusable.

**Comment by mremond** [comment]
The current plan regarding MacOS support is to move to Homebrew, which seems the de facto methods to install Open Source software these days.

We will prepare a patch to update ejabberd homebrew to latest version.

**Comment by scottcc** [comment]
Hey that's fantastic! Thanks for the update @mremond - do you have any idea of when we might see this?

**Comment by mremond** [comment]
@scottcc ejabberd 20.01 has just been added to Homebrew. 
You should be able to install it with `brew install ejabberd`

**Comment by scottcc** [comment]
Thanks @mremond  - by the time I tried, 20.02 was there! It however has a regression, so using `--HEAD` worked. Appreciate the updates!
