### ISSUE TITLE
19.08 Web admin config issues: Host not served

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#3033]
## Environment

- ejabberd version: 19.08
- OS: Linux (CentOS)
- Installed from: official rpm

## Bug description

Same configuration as in 19.05 (it works ok in this version) but now I can´t access Web Admin in 19.08.
It says **Host not served**

Any new config is needed?
As default config It doesn't work neither.

**Comment by zinid** [comment]
Duplicate of #2989
