### ISSUE TITLE
block user from server no library 

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#3034]
**Describe the solution you'd like**

I want the server to block users between users, I want the server to do everything I work for. 

I want to send a request to server with the info and the terminal block user!!

Regards!!!!!

**Comment by licaon-kter** [comment]
Can you detail? That's a local user? An user from another server?

**Comment by badlop** [comment]
> I want the server to block users between users, I want the server to do everything I work for.
> I want to send a request to server with the info and the terminal block user!!

https://docs.ejabberd.im/admin/configuration/#mod-block-strangers

```yaml
modules:
  mod_block_strangers:
    drop: true
    log: true
    allow_local_users: false
```
Result:
```
12:46:01.289 [info] Rejecting message from stranger userx2@localhost/tka1 to userx1@localhost
12:46:01.290 [info] Rejecting message from stranger userx1@localhost to userx2@localhost/tka1
```

**Comment by dverdugo85** [comment]
@badlop  thank!!... but I can to use the module mod_privacy for block user in the local server.. its posible  to block a particular  jabber_id for example  block from user1@localhost to user2@localhost

I try with 

1.-  first with but no work.
> `ejabberdctl send_stanza_c2s user1 abc.com 69890942764773790857148098 "<iq type='set' id='block' from='user1@abc.com'><block xmlns='urn:xmpp:blocking'><item jid='user2@abc.com'></item></block></iq>"`



2. Second  ejabberdctl  but no work.

`ejabberdctl  privacy_set user1 abc.com "<iq from='user1@abc.com' type='set' id='iq1'> <query xmlns='jabber:iq:privacy'> <list name='iq-jid-example'> <item type='jid' value='user2@abc.com' action='deny' order='29'> <iq/> </item> </list> </query> "`


not working... its posible?

Regards

**Comment by dverdugo85** [comment]
I managed to understand the sequence that worked for me.

1. **First need to create default list of  user with** 

   `ejabberdctl privacy_set user1 localhost.com "<query xmlns='jabber:iq:privacy'> <default 
  name='blocked'/></query>"`

2.  **Second block user with**
`ejabberdctl privacy_set user1 localhost.com <query xmlns='jabber:iq:privacy'><list name='blocked'><item type='jid' value='user2@localhost.com' action='deny' order='1'></item></list></query>`


3.  **third unblock user with**
`ejabberdctl privacy_set user1 localhost.com "<query xmlns='jabber:iq:privacy'><list 
    name='blocked'><item type='jid' value='user1@localhost.com' action='allow' order='1'></item> 
    </list></query>"`

that work perfectly!!!

Thanks for your time!!

Regards!! @licaon-kter @badlop @loe
