### ISSUE TITLE
Cannot revert from ACME back to standard certs

### ISSUE THREAD

**Issue by timeos** [processone/ejabberd#3036]
## Environment

- ejabberd version: 18.09
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (CentOS Linux release 7.7.1908 (Core))
- Installed from: official rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Bug description

Because of ACME issue (reported under #3035 ) I wanted to revert back to using my own certificates in configuration file "/opt/ejabberd/conf/ejabberd.yml". So I did this:
- comment out whole "acme" section (including "contact" and "ca_url")
- in section "certfiles" replaced the links to ACME certificates "/opt/ejabberd/database/ejabberd@localhost/certs/acme/example.com.pem" to my own certificate. 
- there are no "certfile" enabled in listeners
- there are no other cert-related directives enabled at all (s2s_certfile etc.)
- restart ejabberd proces via systemctl (my session get dropped and reconnected)

the problem is that ejabberd ignores all my config changes and keep using existing (already expired) ACME certificates. 
then I decided to be more radical and removed all content (backed up actually) from /opt/ejabberd/database/ejabberd@localhost/certs/ directory. but now ejabberd refused to connect of any client with following message:

2019-09-23 12:10:57.483 [warning] <0.633.0>@ejabberd_c2s:process_terminated:312 (tls|<0.633.0>) Failed to secure c2s connection: TLS failed: Failed to find a certificate matching the domain in SNI extension: error:1408A0E2:SSL routines:SSL3_GET_CLIENT_HELLO:clienthello tlsext

this would mean that ACME certificates were finally not read after process restart, but my new certificate defined using "certfile:" was still ignored. 

please how to instruct ejabberd to ignore ACME DB at all and to start use certificates what I have explicitly defined in yml config file?

thank you

**Comment by licaon-kter** [comment]
_certfile**S**:_ right?

**Comment by timeos** [comment]
yes, correct, my fault, "certfiles:"

more info: If I comment out all directives related to map certificates including global "certfiles" directive, then the ACME certs are still used. looks like the interconnection is still somehow defined in MNESIA.

**Comment by licaon-kter** [comment]
Do put your config (minus the commented lines: `grep -Ev '^$|^\s*#' ejabberd.yml` ) in a gist and link it here.

And do mention what happens with this config.

Also, what does `sudo -u ejabberd stat /path/to/cert/nameofyourcertfile.pem` says?

**Comment by timeos** [comment]
Config: https://gist.github.com/timeos/08c9f53e61dba90c9fe0254bbe3221cb

with this config, the "certfiles" directive is completely ignored and internal (originally enabled) ACME certs are still taken place.
if I manually remove everything from /opt/ejabberd/database/ejabberd@localhost/certs/ directory, then ejabberd will not load any certificate at all and all client connections will be refused as I stated in first post.

sudo -u ejabberd stat /opt/ejabberd/conf/server1.pem
  File: ‘/opt/ejabberd/conf/server1.pem’
  Size: 5250            Blocks: 16         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 45924       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1002/ejabberd)   Gid: ( 1002/ejabberd)
Context: unconfined_u:object_r:usr_t:s0
Access: 2019-09-25 06:43:53.695545105 +0200
Modify: 2019-09-25 06:39:20.450345533 +0200
Change: 2019-09-25 06:42:19.876477680 +0200
 Birth: -

sudo -u ejabberd stat /opt/ejabberd/conf/cacert.pem
  File: ‘/opt/ejabberd/conf/cacert.pem’
  Size: 226116          Blocks: 448        IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 45922       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1002/ejabberd)   Gid: ( 1002/ejabberd)
Context: unconfined_u:object_r:usr_t:s0
Access: 2019-09-25 07:35:16.547857401 +0200
Modify: 2019-09-17 22:00:55.852546810 +0200
Change: 2019-09-17 22:00:55.974546834 +0200
 Birth: -

**Comment by zinid** [comment]
Remove that `certs` directory, make sure you have certificates defined in `certfiles` and restart ejabberd.

**Comment by timeos** [comment]
ok, seems that removing directory "/opt/ejabberd/database/ejabberd@localhost/certs/" really helped. before I've removed just content of that directory without luck.... strange.
thank you guys for your help!
