### ISSUE TITLE
MUC: allow emitting muc#roominfo_logs disco#info form extension field

### ISSUE THREAD

**Issue by horazont** [processone/ejabberd#3040]
From my understanding, ejabberd supports writing logs in HTML format. Those can be served by a webserver (either mod_http_fileserver or an external one).

It is possible to advertise a URL to those logs via the disco#info form extension field ``muc#roominfo_logs``. It would be great if ejabberd supported advertising the URL to those logs for MUCs.

I’ll leave the implementation details up to you. Options which come to mind:

1. A domain-wide URL template (configured by the admin), such as ``https://process-one.net/logs/{jid}/``, where ejabberd substitutes placeholders like ``{jid}`` when generating the reply form.
2. A MUC configuration form option for users to fill in manually.
3. A combination of (1) and (2), where (1) is the default if the user has not set the option explicitly.

It might be desirable to have an room-level opt-out for this.

**Additional context**
- The search engine https://search.jabber.network will add the link to the result page if it is present in the room info
- Prosody supports this in the [mod_http_muc_log](https://modules.prosody.im/mod_http_muc_log.html) extension
- Example: the MUC xsf@muc.xmpp.org advertises the form field.

**Comment by zinid** [comment]
Looks okay. Except that I don't like an ability to configure that URL manually by room owners, due to privacy concerns.

**Comment by zinid** [comment]
I implemented it with a very basic configuration: it's only possible to configure a top URL for mod_muc_log.
Will improve the implementation if there is any demand.
