### ISSUE TITLE
not able to restore mnesia database after upgrade from 19.05 to 19.08

### ISSUE THREAD

**Issue by hemantlinux** [processone/ejabberd#3042]
Hi,
I have been using ejabberd 19.05 and today wanted to upgrade it to 19.08 version.
Before installing new version I have created backup of mnesia database. While restoring that backup to 19.08 , it is showing below error. 
"Can't restore backup from "/home/test/27_09_2019.backup" at node ejabberd@localhost: Table acl does not exist"
Since release notes showing that there is no change in database but I am getting this error.

**Comment by hemantlinux** [comment]
I have resolved the issue by taking dump of existing mnesia database and load into new mnesia. I don`t know why its not working with back but it may be possible that dump includes schema and data while backup includes data only.

**Comment by mremond** [comment]
Yes, indeed. I confirm that one process includes the schema will the other only reload the data in the existing schema.
