### ISSUE TITLE
store ejabebrd data into mongodb?

### ISSUE THREAD

**Issue by hackrole** [processone/ejabberd#305]
I want to know is there a way to config the ejabebrd to store data into mongodb, but not mysql or others.

**Comment by hackrole** [comment]
I would like to add something behind this issues.
if you donot need all the data of ejabberd store in mongodb. you may try two ways.

1) write a ejabberd service-component, let the client send requests to the component. and store data into mongodb(or your own database), and resend the msg to receiver or the server.

2) write a ejabberd  module with erlang. you may find help on the follow links.

https://www.process-one.net/en/wiki/ejabberd_module_development/
http://www.process-one.net/docs/ejabberd/guide_en.html#listened-options
https://metajack.wordpress.com/2008/08/28/writing-ejabberd-modules-presence-storms/

**Comment by Neustradamus** [comment]
@hackrole @rraptorr Have you found a solution for MongoDB?
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang

Linked to https://github.com/processone/ejabberd/issues/419
