### ISSUE TITLE
Failed to load NIF on erlang OTP 21

### ISSUE THREAD

**Issue by sujankumar4593** [processone/ejabberd#3051]
## Environment

- ejabberd version: 19.05
- Erlang version: `21`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Bug description

I am getting the following error when adding  ssl to the ejabberd with erlang otp version 21

LOGS
--------------------------------------------------------------------

IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue

Erlang/OTP 22 [erts-10.5.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.5.1  (abort with ^G)
(ejabberd@localhost)1> 19:34:05.531 [notice] Changed loghwm of /opt/ejabberd/var/log/ejabberd/error.log to 1000
19:34:05.531 [notice] Changed loghwm of /opt/ejabberd/var/log/ejabberd/ejabberd.log to 1000
19:34:05.582 [error] CRASH REPORT Process <0.179.0> with 0 neighbours crashed with reason: bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'li..."}) in erl_ddll:format_error/1 line 239
19:34:05.583 [error] Supervisor fast_tls_sup had child fast_tls started with fast_tls:start_link() at undefined exit with reason bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'li..."}) in erl_ddll:format_error/1 line 239 in context start_error
19:34:05.583 [error] CRASH REPORT Process <0.176.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},...]}}},...} in application_master:init/4 line 138
19:34:05.583 [info] Application fast_tls exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},...]}}},...} 
19:34:05.645 [error] CRASH REPORT Process <0.200.0> with 0 neighbours crashed with reason: bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'li..."}) in erl_ddll:format_error/1 line 239
19:34:05.646 [error] Supervisor fast_tls_sup had child fast_tls started with fast_tls:start_link() at undefined exit with reason bad argument in call to erl_ddll:format_error_int({load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'li..."}) in erl_ddll:format_error/1 line 239 in context start_error
19:34:05.646 [error] CRASH REPORT Process <0.197.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},...]}}},...} in application_master:init/4 line 138
19:34:05.646 [info] Application fast_tls exited with reason: {{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},...]}}},...} 
19:34:05.647 [error] CRASH REPORT Process <0.186.0> with 0 neighbours exited with reason: {{fast_tls,{{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{...}]},...]}}},...}},...} in application_master:init/4 line 138
19:34:05.647 [info] Application xmpp exited with reason: {{fast_tls,{{shutdown,{failed_to_start_child,fast_tls,{badarg,[{erl_ddll,format_error_int,[{load_failed,"Failed to load NIF library /opt/ejabberd/lib/fast_tls-1.1.1/priv/lib/fast_tls: 'libssl.so.1.0.0: cannot open shared object file: No such file or directory'"}],[]},{erl_ddll,format_error,1,[{file,"erl_ddll.erl"},{line,239}]},{fast_tls,load_nif,1,[{file,"src/fast_tls.erl"},{line,476}]},{fast_tls,init,1,[{file,"src/fast_tls.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{...}]},...]}}},...}},...}
19:34:05.718 [info] Loading configuration from /opt/ejabberd/etc/ejabberd/ejabberd.yml
19:34:06.467 [warning] Listening option 'web_admin' is deprecated, enable it via request handlers, e.g.:
listen:
  ...
  -
    module: ejabberd_http
    request_handlers:
      ...
      "/admin": ejabberd_web_admin
19:34:06.467 [warning] Listening option 'web_admin' is deprecated, enable it via request handlers, e.g.:
listen:
  ...
  -
    module: ejabberd_http
    request_handlers:
      ...
      "/admin": ejabberd_web_admin
19:34:06.467 [warning] Listening option 'captcha' is deprecated, enable it via request handlers, e.g.:
listen:
  ...
  -
    module: ejabberd_http 
    request_handlers:
      ...
      "/captcha": ejabberd_captcha
19:34:06.478 [error] CRASH REPORT Process <0.114.0> with 0 neighbours exited with reason: bad argument in call to ets:insert(xmpp_config, {{fqdn,global},[<<"b5af9f61aa5a">>]}) in p1_options:insert/4 line 62 in application_master:init/4 line 138
19:34:06.479 [info] Application ejabberd exited with reason: bad argument in call to ets:insert(xmpp_config, {{fqdn,global},[<<"b5af9f61aa5a">>]}) in p1_options:insert/4 line 62
19:34:06.479 [info] Application ssl exited with reason: stopped
19:34:06.480 [info] Application public_key exited with reason: stopped
19:34:06.480 [info] Application asn1 exited with reason: stopped
19:34:06.480 [info] Application crypto exited with reason: stopped
19:34:06.480 [info] Application sasl exited with reason: stopped

**Comment by zinid** [comment]
> libssl.so.1.0.0: cannot open shared object file: No such file or directory

Something is wrong with the installation.
