### ISSUE TITLE
captcha_url or captcha_host

### ISSUE THREAD

**Issue by xi1976github** [processone/ejabberd#3053]
## Environment

- ejabberd version: 19.09-1
- Erlang version: `erl +V` 10.5
- OS: Arch
- Installed from: pacman

## Bug description
when using
captcha_url in ejabberd.yml then captcha is not created/displayed
when using
captcha_host then captcha is working, but in the logfile it says that captcha_host
is deprecated and captcha_url is to be used

**Comment by licaon-kter** [comment]
ejabberd.log ?

**Comment by zinid** [comment]
Show ejabberd.yml, namely all `captcha` options and the relevant ejabberd_http listener.

**Comment by zinid** [comment]
Also, are you configuring as described [here](https://docs.ejabberd.im/admin/configuration/#captcha)?

**Comment by xi1976github** [comment]
I missed the trailing /captcha in the captcha_url,

thank you guys
