### ISSUE TITLE
Apache reverse proxy - no access

### ISSUE THREAD

**Issue by BlackWolfDEsign** [processone/ejabberd#3057]
OS: Ubuntu 18.04
ejabberd: [docker image](https://hub.docker.com/r/ejabberd/ecs/)
error: Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Hi, on my server runs an apache2 as reverse proxy. I run several Docker instances and wanted to integrate them(ejabberd). I tried without apache-integration, no success. With reverse proxy, no success ... I think the config of vhosts is just wrong, or incomplete ... i tried all locations /ws, ...

```<VirtualHost *:80>
        ServerName chat.domain.de
        ProxyPass / http://127.0.0.1:5280/
        ProxyPassReverse / http://127.0.0.1:5280/

        ProxyPass /admin http://127.0.0.1:5280/admin/
        ProxyPassReverse /admin http://127.0.0.1:5280/admin/

        #ProxyPass /upload http://127.0.0.1:5280/upload
        #ProxyPassReverse /upload http://127.0.0.1:5280/upload
        #ProxyPreserveHost On
        #ProxyAddHeaders On
        ProxyRequests Off
        #RequestHeader set X-Forwarded-Proto "http"

        #RequestHeader set Host $http_host;
        RequestHeader set X-Real-IP $remote_addr;
        RequestHeader set X-Forwarded-For $proxy_add_x_forwarded_for;
        #RequestHeader set X-Forwarded-Proto $scheme;
</VirtualHost>

<VirtualHost *:443>
        ServerName chat.domain.de
        ProxyPass / http://127.0.0.1:5443/
        ProxyPassReverse / http://127.0.0.1:5443/

        ProxyPass /admin http://127.0.0.1:5443/admin/
        ProxyPassReverse /admin http://127.0.0.1:5443/admin/

        #ProxyPass /upload http://127.0.0.1:5443/upload
        #ProxyPassReverse /upload http://127.0.0.1:5443/upload
        ProxyRequests Off
        #ProxyPreserveHost On
        #ProxyAddHeaders On
        #RequestHeader set X-Forwarded-Proto "https"

        SSLCertificateFile /etc/letsencrypt/live/chat.domain.de/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/chat.domain.de/privkey.pem

        # If you plan to proxy to a HTTPS host:
        SSLProxyEngine On
</VirtualHost>
```
i changed the host to chat.domain.de in ejabberd.yml

edit: i tried also [datentraeger.li](https://blog.datentraeger.li/?p=2246)

**Comment by licaon-kter** [comment]
What do you want to achive?

**Comment by BlackWolfDEsign** [comment]
Oh, sry :D, 
I would like to access the webclient / admin webpage ;)

for example http(s)://chat.mydomain.de/admin

**Comment by licaon-kter** [comment]
If the Apache proxy is ok, you might be seeing this issue: https://github.com/processone/ejabberd/issues/3050

**Comment by BlackWolfDEsign** [comment]
i think so... all other subdomains like mail.domain.de, ts.domain.de or
cloud.domain.de works fine ;) 

thx for this link!

**Comment by BlackWolfDEsign** [comment]
I checked the issue and  #3050 is for server error 402. i get a 503 server error.

**Comment by zinid** [comment]
Seems like you're jumping from one problem to another. Also, "Connection error, remote stream error" and "Accepted connection" gives us zero information.
