### ISSUE TITLE
Binary installer for armhf/arm64 missing for 19.09

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#3059]
A few weeks have passed since the release and there's still no armhf or arm64 binary installer on the [download page](https://www.process-one.net/en/ejabberd/archive/).

**Comment by mremond** [comment]
Yes, for now we are not building it anymore has it is quite some work and was not massively used ...

**Comment by mbirth** [comment]
:sob:

**Comment by mbirth** [comment]
> it is quite some work

Is there a documentation somewhere on how to create the binary installer? The normal `make install` uses /etc, /usr, ... I'd prefer the contained directory like with the binary installers.

**Comment by zinid** [comment]
@mbirth `make rel` is probably what you want: it will put everything into `rel` directory.

**Comment by mbirth** [comment]
@zinid Thanks, I'll try that.

**Comment by mbirth** [comment]
I finally got around to test this.

Is your release process documented somewhere?

What's your default `./configure` call? Is it just `--enable-all` or also e.g. `--enable-new-sql-schema` or `--enable-full-xml`?

And how can I get it to compile binaries without debug symbols?

**Comment by licaon-kter** [comment]
First time after cloning: 
`./autogen.sh && ./configure --enable-new-sql-schema --enable-pgsql --enable-user=ejabberd --enable-group=ejabberd  --prefix=/usr/local && make`

Then to update I just do `git pull && make update && ./autogen.sh && ./configure --enable-new-sql-schema --enable-pgsql --enable-user=ejabberd --enable-group=ejabberd  --prefix=/usr/local && make`

And don't forget to `sudo make install` 

No need to enable all, in my case, see `help` for options as the defaults already cover all that's needed...but maybe you need mysql and sip and whatever.

**Comment by mbirth** [comment]
I wanted to get something like the official binary package (currently using 19.05 arm64), if possible. I.e. all features enabled. Maybe I'll make a package for my Launchpad PPA for others to use.

Also, how does it determine if there's "thumbnail support" for the `mod_http_upload` or not? Which library do I need to install?

**Comment by licaon-kter** [comment]
libgd iirc, but I never enabled thumbnails

**Comment by zinid** [comment]
> Is Elixir needed for production?

No. Disable it with `--disable-elixir` configure flag.

**Comment by wck86** [comment]
With the recent release of a stable 64 bit OS for Raspberry Pi devices, the desire for ARM64 versions of ejabberd is probably going to grow rapidly... is an arm64 build of a current or recent release in the works?

**Comment by licaon-kter** [comment]
@wck86 did you see https://github.com/processone/ejabberd/pull/3781 ?
