### ISSUE TITLE
Can't edit users with non-latin characters

### ISSUE THREAD

**Issue by aznvkz** [processone/ejabberd#3066]
## Environment

- ejabberd version: 19.09
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.3
- OS: Windows Server 2019
- Installed from: official binary installer 

## Bug description

When i've added a user with non-latin characters in the name, i can't edit it (or delete it) from web interface. Trying to click on user link in userlist (i.e. http://localhost:5280/admin/server/server/user/%D0%BF%D0%BE%D0%BB%D0%B8%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F/) leads to "connection reset" in browser and nothing more happens.

**Comment by badlop** [comment]
This was introduced in https://github.com/processone/ejabberd/commit/5770946f03ba669ea867b787fbd546333a8a3814 and happens also in mod_offline.erl and mod_roster.erl that also provide webadmin pages . The problem is that
> str:format("User ~s",  [jid:encode({U, S, <<"">>})])

was replaced with
> str:format("User ~ts",  [jid:encode({U, S, <<"">>})])

which assumes that the result of jid:encode will be UTF-8, but it is not.

It's easy to reproduce:
1. install recent ejabberd
2. create an account with username user4-д
3. login to webadmin and go to Virtual Hosts -> virtoual host -> Users

In case of mod_offline, for example, the error message for account user4-д@localhost is:
```
12:15:34.626 [error] Hook webadmin_page_host crashed when running mod_offline:webadmin_page/3:
** exception error: bad argument
   in function  iolist_to_binary/1
      called as iolist_to_binary([[117,115,101,114,52,45,1076,64,108,111,99,
                                   97,108,104,111,115,116],
                                  39,115,32,79,102,102,108,105,110,101,32,77,
                                  101,115,115,97,103,101,115,32,81,117,101,
                                  117,101])
   in call from str:format/2 (src/str.erl, line 289)
   in call from mod_offline:user_queue/4 (src/mod_offline.erl, line 997)
   in call from mod_offline:webadmin_page/3 (src/mod_offline.erl, line 748)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 217)
   in call from ejabberd_web_admin:process_admin/3 (src/ejabberd_web_admin.erl, line 544)
   in call from ejabberd_http:process/2 (src/ejabberd_http.erl, line 366)
** Arg 1 = []
** Arg 2 = <<"localhost">>
...
```

Solutions:
* Go back to ~s
* Don't compose those strings at all, simply put the username as web page header (this also reduces the amount of strings to translate)
* Check if there is some internal problem in webadmin or in str formatting.

**Comment by zinid** [comment]
Yeah, thanks for the investigation, this is mostly a problem in str:format/2, I missed that part. I will revise it (and `~ts` formatting) asap.

**Comment by aznvkz** [comment]
Well, just installed 20.01 version from windows binary dist - bug still exists:
2020-01-30 00:35:20.861 [error] <0.605.0>@str:format:289 CRASH REPORT Process <0.605.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_to_binary([85,115,101,114,32,[1083,1077,1074,1072,1096,1086,1074,46,1089,1077,1088,1075,1077,1081,64,115,101,...]]) in str:format/2 line 289

How can it be possible if there is no more "iolist_to_binary" function in source code on this line?

**Comment by prefiks** [comment]
Hello,

Yes, that function should no longer be using iolist_to_binary, possibly you have another version of str somewhere in your system that is picked instead that from new ejabberd installation?

Could you please start debug console (by executing ejabberdctl debug) and type this in it:
```
code:which(str).
```
and see if path that it shows is in that ejabberd install?

**Comment by aznvkz** [comment]
Hello, Pawel!
It shows correct path to str lib:

```
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V10.3  (abort with ^G)
(ejabberd@localhost)1> code:which(str).
"C:\\ejabberd-19.09/lib/ejabberd-20.01/ebin/str.beam"

```
