### ISSUE TITLE
can't find register.css

### ISSUE THREAD

**Issue by wartjugger** [processone/ejabberd#3076]
ejabberd 16.09, installed on Debian 9 using apt-get.

Is this file available for changes with this type of installation or must I compile it from source?

**Comment by licaon-kter** [comment]
Please use a not-3 years old version first, eg. stretch-backports has 18.12.1

**Comment by zinid** [comment]
https://github.com/processone/ejabberd/blob/master/priv/css/register.css

**Comment by wartjugger** [comment]
lol you're right. I now installed 19.09.1 and it's all good (after 2 hours of figuring out all the required changes in the yml config file...)
