### ISSUE TITLE
Security improvements: Add warning about old SSL/TLS versions

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3077]
Add a warn if there is always SSLv2, SSLv3, TLSv1, TLSv1_1 instead of TLSv1_2 or TLSv1_3.

Please note that there are possibilities in ejabberd.yml for disable.
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1_1"
      - "no_tlsv1_2"

Example for Prosody:
- https://hg.prosody.im/prosody-modules/file/406b32b50457/mod_warn_legacy_tls

Last commits:
- https://hg.prosody.im/prosody-modules/rev/36023eb3254e
- https://hg.prosody.im/prosody-modules/rev/5073bbd86970
- https://hg.prosody.im/prosody-modules/rev/ec3eb426271e
- https://hg.prosody.im/prosody-modules/rev/406b32b50457

**Comment by licaon-kter** [comment]
So the module intercepts the connection and checks version then either messages the client or passes it to the server? On every connection? I feel this would be a burden on the server, extra work to do on each connection. How does it scale?

This is in order for the client to not just see a "raw TLS error" or whatever it would get if incompatible TLS version?

**Comment by zinid** [comment]
Add a warning to where? That Prosody module sends a warning to a client connected using "old" TLS version. I have no idea what a regular XMPP user will do with such a message.

**Comment by zinid** [comment]
I close the issue, because even if it's needed, it should be implemented as a contrib module.

**Comment by Neustradamus** [comment]
You can move this ticket and do not closed it in the other repository ;)

**Comment by zinid** [comment]
I would bother if someone would willing to implement this.
