### ISSUE TITLE
OMEMO not available

### ISSUE THREAD

**Issue by wartjugger** [processone/ejabberd#3078]
## Environment

- ejabberd version: 19.09.1
- Erlang version: 10.3.4
- OS: Linux (Debian 9)
- Installed from: official .deb file

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log
No errors

## Bug description

Can't get OMEMO to work. Client does not identify OMEMO (no issues using it in other servers).  It was also working for me in when I used version 16.09. Further, I don't find any reference whatsoever to OMEMO in the docs.

**Comment by wartjugger** [comment]
hosts:
  - "xxxxxxx.xxx"
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
certfiles:
  - "/opt/ejabberd/conf/server.pem"
ca_file: "/opt/ejabberd/conf/cacert.pem"
captcha_cmd: /opt/ejabberd-19.09.1/lib/ejabberd-19.09.1/priv/bin/captcha.sh
captcha_url: https://xxxxxxx.xxx:5280/captcha
captcha_limit: 10
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/captcha": ejabberd_captcha
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
  -
    port: 5281
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/register": mod_register_web
      "/captcha": ejabberd_captcha
s2s_use_starttls: optional
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@xxxxxxx.xxx"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
  register:
    allow: all
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
   contact: "mailto:admin@ff.xxxxxxx.xxx"
   ca_url: "https://acme-v01.api.letsencrypt.org"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco:
    server_info:
      -
        modules: all
        name: "abuse-addresses"
        urls: ["mailto:admin@xxxxxxx.xxx"]
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
      - hometree
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    captcha_protected: true
    registration_watchers:
      - "admin@xxxxxxx.xxx"
  mod_register_web: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

**Comment by zinid** [comment]
The config looks fine to me. Maybe there is a problem with the database. Try deleting all pubsub files in your Mnesia directory (the clients will re-create OMEMO content automatically), e.g. something like:
```
$ ejabberdctl stop
$ rm -rf /var/lib/ejabberd/*pubsub*
$ ejabberctl start
```

**Comment by licaon-kter** [comment]
Maybe try this: https://github.com/processone/ejabberd/blob/ae88be2011e49bcd6e8b9cb8656775eca878a0b9/ejabberd.yml.example

What client?

**Comment by wartjugger** [comment]
> The config looks fine to me. Maybe there is a problem with the database. Try deleting all pubsub files in your Mnesia directory (the clients will re-create OMEMO content automatically), e.g. something like:
> 
> ```
> $ ejabberdctl stop
> $ rm -rf /var/lib/ejabberd/*pubsub*
> $ ejabberdctl start
> ```
Can you be more specific as to what files need to be deleted? I don't have ejabberd under /var/lib. I have *pubsub* files at:

/opt/ejabberd-19.09.1/lib/xmpp-1.4.2/ - this will delete beam and hrl files
/opt/ejabberd-19.09.1/lib/ejabberd-19.09.1/ebin/ - this will delete beam files
/opt/ejabberd/database/ejabberd@localhost/ - this will delete DCD and DAT files

**Comment by zinid** [comment]
The DCD and DAT files.

**Comment by wartjugger** [comment]
I can send encrypted messages, but only receiving unecrypted messages. Seems like the other side doesn't identify there is an OMEMO options.

I am using Gajim.

**Comment by wartjugger** [comment]
> Maybe try this: https://github.com/processone/ejabberd/blob/ae88be2011e49bcd6e8b9cb8656775eca878a0b9/ejabberd.yml.example

This produces many errors and warnings. I guess I could make all the modifications that it will work, but then I'll be running another file..

Are there any direct tests on the server troubleshoot / verify OMEMO?

**Comment by zinid** [comment]
> This produces many errors and warnings.

It shouldn't as long as you use 19.09.01. What warnings and errors do you see?

> Are there any direct tests on the server troubleshoot / verify OMEMO?

I am not aware of any.

**Comment by wartjugger** [comment]
Ok, I now added (under "mod_pubsub:")

    ignore_pep_from_offline: false 
    last_item_cache: false
    max_items_node: 1000
    default_node_config:
      max_items: 1000

Looks ok, expect for the case where I have a chat between two users in my server. My server with another server, OMEMO works.

**Comment by zinid** [comment]
I wonder how this configuration could help, but whatever, if it works for you.

**Comment by wartjugger** [comment]
> I wonder how this configuration could help, but whatever, if it works for you.

Perhaps just restarting did the trick, I can't tell. I started using ejabberd 5 days ago. 
The issue when both accounts are from the same server was solved by clearing the devices in Gajim's OMEMO's plugin. Probably the whole thing somehow related to caching / refreshing etc.
