### ISSUE TITLE
Correct release process?

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#3079]
What's the correct release process to get *exactly* what you offer for [download](https://www.process-one.net/en/ejabberd/archive/) in the linux `.run` files?

There are conflicting information in your documentation, sometimes referring to the [Vagrant setup](https://github.com/processone/ejabberd-vagrant-dev) (that wasn't touched in the last 3 years) and there are instructions about a [Docker mix image](https://github.com/processone/docker-ejabberd). Also the [normal Makefile way](https://docs.ejabberd.im/admin/installation/#install-from-source-code).

The obvious process of doing `./configure && make` gets me beams with debug info and other metadata which are about 3-4x the size of the same files from your `.run` package. Doing `./configure --disable-debug` doesn't make any difference. Also `make rel` gives a different directory structure than that in your releases.

Trying to do what the Docker mix image does also compiles debug info into the beams. And `mix release` gives some error about `p1_utils` being an included app but also a regular app.

So what's the "official"/correct workflow here to get files without debug info or other metadata and end up with a `.run` file?

**Comment by weiss** [comment]
> Doing ./configure --disable-debug doesn't make any difference.

It does for me:

```console
$ ./configure --enable-debug && make
$ erl -noshell -pa ebin -eval 'io:write(proplists:get_value(debug_info, proplists:get_value(options, ejabberd:module_info(compile)))), io:nl(), halt()'
true

$ ./configure --disable-debug && make
$ erl -noshell -pa ebin -eval 'io:write(proplists:get_value(debug_info, proplists:get_value(options, ejabberd:module_info(compile)))), io:nl(), halt()'
undefined
```

The size of the `ejabberd.beam` file I end up with is 9212 bytes with debug info and 5412 bytes without.

ProcessOne's binary installer deploys a self-contained directory that holds ejabberd and all its Erlang dependencies including the (required parts of) Erlang/OTP itself.  You get something very similar when running `make rel`.

**Comment by mbirth** [comment]
@weiss While that works for the main BEAM, it doesn't for all the libraries. E.g. `lib/fast_xml-1.1.37/ebin/fast_xml.beam` is 1284 Bytes for me (with `--disable-debug`) and 358 Bytes in the `ejabberd-19.08-linux-aarch64.run` which ships the same version of fast_xml.

And even when manually removing `debug_info` from the rebar config for fast_xml, the resulting beam still contains metadata such as the complete path to the `fast_xml.erl` file in my local filesystem and thus is still slightly larger than the one shipped from ProcessOne that doesn't have a meta data (`Attr`) chunk at all.

And yes, `make rel` creates something *similar*, but, I mean, ProcessOne hopefully has a script or otherwise documented process to get **exactly** what they are shipping with each update. And that probably also includes a way to get small beam files without any debug info or other metadata.

**Comment by weiss** [comment]
> While that works for the main BEAM, it doesn't for all the libraries.

True.  I'm not sure there's currently a nicer way than applying the following diff before compiling:

```diff
--- a/rebar.config
+++ b/rebar.config
@@ -151,7 +151,9 @@
 {recursive_cmds, ['configure-deps']}.

 {overrides, [
-  {del, [{erl_opts, [warnings_as_errors]}]}]}.
+  {del, [{erl_opts, [warnings_as_errors]}]},
+  {del, [{erl_opts, [debug_info]}]},
+  {add, [{erl_opts, [no_debug_info]}]}]}.

 {post_hook_configure, [{"fast_tls", []},
                        {"stringprep", []},
```

> And even when manually removing `debug_info` from the rebar config for fast_xml, the resulting beam still contains metadata

Call `export ERL_COMPILER_OPTIONS='deterministic'` before compiling.

**Comment by mbirth** [comment]
With your suggested changes, my `fast_xml.beam` is now down to 724 Bytes. That's still twice the size of what ProcessOne achieved. Looking at it, it still contains `LocT`, `Attr`, `CInf` and `Dbgi` chunks for some reason. All of those are absent in the beam from the official ejabberd package. How do I, too, get rid of those?

**Comment by weiss** [comment]
Indeed.  [beam_lib][1]'s `strip()` functions get rid of those chunks.  After running `make rel`, you could run the following command (in which case you'll neither need the above diff nor the `deterministic` option, so that's probably the easiest solution anyway):

```console
$ erl -noshell -eval '{ok, _} = beam_lib:strip_release("rel/ejabberd"), halt()'
```

[1]: http://erlang.org/doc/man/beam_lib.html

**Comment by mbirth** [comment]
Ha, I just found the `strip`, `strip_files` and `strip_release` methods, too. And this now produces a result that very much looks like the one from the release. Even the chunks are reordered into the same order. (Before stripping, first chunk is `AtU8`; after stripping it's `Line` - just like in the release files.)

Looks like this really is the way to go.

Fun fact:
```
Before strip:
$ du -hs rel
36M     rel

After strip:
$  du -hs rel
19M     rel
```

Now the only open question is how to get the exact same directory/file structure that the binary installer unpacks?

`make rel` result:
```
.
├── bin
├── doc
├── erts-10.4.4
│   └── bin
├── etc
│   └── ejabberd
├── lib
│   ├── asn1-5.0.9
│   ├── base64url-1.0.1
│   ├── cache_tab-1.0.20
│   ├── compiler-7.4.4
│   ...
├── releases
│   └── 19.09
└── var
    ├── lib
    │   └── ejabberd
    ├── lock
    └── log
        └── ejabberd
```

Structure after unpacking `ejabberd-19.08-linux-aarch64.run`:
```
.
├── bin
├── conf
├── database
├── lib
│   ├── asn1-5.0.8
│   ├── base64url-1.0.1
│   ├── cache_tab-1.0.20
│   ├── cean-2.1
│   ├── compiler-7.3.2
│   ...
├── logs
└── usr
    ├── include
    └── lib
```

**Comment by zinid** [comment]
Why are you so obsessed with the exact installer's structure? The reason we don't publish our build scripts is because they are extremely tightened to our existing infrastructure and you will spend much more time to tame them to work on your machine (and will ask even more questions). Really, just strip the beams and stick to `make rel`.
