### ISSUE TITLE
support for XEP 0184

### ISSUE THREAD

**Issue by BaseMax** [processone/ejabberd#308]
can you implement http://www.xmpp.org/extensions/xep-0184.html  module?
i tried this https://github.com/Mingism/ejabberd-stanza-ack with latest ejabberd 14.x but compile error  original developer said he is no longer updating it.
thanks.

**Comment by STPKITT** [comment]
https://www.ejabberd.im/protocols lists XEP-0184 as not supported by ejabberd, which, without the knowledge that Holger posted here, is hugely missleading and nearly prevented me from using ejabberd. It would be nice to mention on https://www.ejabberd.im/protocols , that XEP-0184 is dependent only on the clients used.

**Comment by badlop** [comment]
I've fixed the protocols page. As explained by STPKITT, ejabberd does not need to implement anything about that XEP, so that XEP does not need to be listed in the page.

**Comment by STPKITT** [comment]
Thanks!
