### ISSUE TITLE
syntax problem on docs page

### ISSUE THREAD

**Issue by xvdessel** [processone/ejabberd#3080]
## Environment

- ejabberd version: 19.05
- Erlang version: 10.3.5.5
- OS: Fedora 30
- Installed from: official deb/rpm

## Errors from error.log/crash.log

```
2019-11-10 00:01:47.551 [error] <0.106.0>@ejabberd_config:transform_terms:1314
 Failed to transform terms by acl: {'EXIT',{function_clause,[
{lists,foldl,[#Fun<ejabberd_config.67.7810571>,{[],[]},<<>>],[{file,"lists.erl"},{line,1262}]},
{ejabberd_config,collect_options,1,[{file,"src/ejabberd_config.erl"},{line,1360}]},
{acl,'-transform_options/1-fun-5-',1,[{file,"src/acl.erl"},{line,710}]},
{lists,map,2,[{file,"lists.erl"},{line,1239}]},
{acl,transform_options,1,[{file,"src/acl.erl"},{line,708}]},
{ejabberd_config,transform_terms,2,[{file,"src/ejabberd_config.erl"},{line,1312}]},
{ejabberd_config,transform_terms,1,[{file,"src/ejabberd_config.erl"},{line,1309}]},
{ejabberd_config,'-transform_options/1-lc$^3/1-0-',1,[{file,"src/ejabberd_config.erl"},{line,1389}]}]}}
```

## Bug description

 When applying manually the proposed change from this docs page:
https://docs.ejabberd.im/admin/guide/managing/
more specifically the yaml code from the first example of the eb Admin section, my ejabberd would no longer start (see error above)

After some tests, it tunrs out the syntax in that example is wrong, or at least the way it is visualized causes problems:

The acl: admin tag and the subsequent user tag seem to be at the same level. In the code, the first one is preceded by 8 blanks, the second one by a tab. But that difference is not visible in the browser. 

Hence one could just put them both with 8 blanks, as I did, in which case ejabberd crashes on the syntax. By making that 2 more blanks for the user line and also for the next line, things worked again.

I would thus recommend to use only blanks in the indentation of the example to avoid confusion.

**Comment by badlop** [comment]
Thanks! I'll take a look. Yes, this ticket should be in the docs repository, but I'll handle it here, anyway.

**Comment by badlop** [comment]
I've applied your fixes, then reviewed documentation and found a few other cases where tabs in example code could produce problems.

All those problems are fixed in the upstream documentation repository, and they will be available in the online documentation for the next ejabberd release.
