### ISSUE TITLE
incoming_s2s_number in admin CP

### ISSUE THREAD

**Issue by member777** [processone/ejabberd#3081]
## Environment

- ejabberd version: 19.02
- OS: Linux (Debian) 10
- Installed from: distro package

## Bug description
In admin CP https://hereisjabber.site:5280/admin/stats/
We can see such info:
Totally registered: 1.000
Connected users: 10
Outcoming s2s-servers: 10
Incoming s2s connections: 0

And everytime this numer is 0. What does it mean? That I have no incoming s2s connections? Or this is bug?

**Comment by zinid** [comment]
This was already fixed in 7fc272918ac926ab895e89988fd757418d592530
Please update ejabberd version.
