### ISSUE TITLE
Installing SSL on ejabberd

### ISSUE THREAD

**Issue by joweste** [processone/ejabberd#3085]
## Environment
- ejabberd version: 19.09
- Erlang version: `erl +V`
- OS: Windows Server 2019

## Errors from error.log/crash.log

Cert is invalid is showing in browse

## Bug description
I am using zeroSSL with letsencrypt to generate a SSL.
I have the next files generated by zeroSSL and I installed in my website without problem.
My problem is how install it in ejabberd running into windows.
I have the next files generated by zeroSSL wizard.
account-key.txt
domain-key.txt
domain-crt.txt
domain-csr.txt

Please How could I set the certfiles and port to use SSL in ejabberd with windows with these files?

**Comment by licaon-kter** [comment]
Did you edit YML and point to those files?

**Comment by joweste** [comment]
I read the docs but until now I dont know what I have to put the files into yml.
I know I have to put into certfiles and use something as:

-
 port: 5281
    ip: "0.0.0.0"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/http-bind": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth

I dont have "fullchain.pem" because I used the wizard from zeroSSL site.
I´d like to know where I have to put each file in certfiles:
account-key.txt
domain-key.txt
domain-crt.txt
domain-csr.txt



certfiles:
  - "C:/ProgramData/ejabberd/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

 ca_file: "C:/ProgramData/ejabberd/conf/cacert.pem"

**Comment by zinid** [comment]
Try something like:
```yaml
certfiles:
  - account-key.txt
  - domain-key.txt
  - domain-crt.txt
```
Read warnings in ejabberd.log to understand whether ejabberd complains on your certificates or not.

**Comment by joweste** [comment]
> Try something like:
> 
> ```yaml
> certfiles:
>   - account-key.txt
>   - domain-key.txt
>   - domain-crt.txt
> ```
> 
> Read warnings in ejabberd.log to understand whether ejabberd complains on your certificates or not.

It works. Thank you very much
