### ISSUE TITLE
Using CORS with ejabberd

### ISSUE THREAD

**Issue by joweste** [processone/ejabberd#3087]
## Environment

- ejabberd version: 19.01
- Erlang version: `erl +V`
- OS: Windows
- Installed from: official binary installer
## Bug description
I use conversje.js and I use an api on my server to get credentials of a user.
When I execute a call to api, I  am getting a cors error, as showing below.

How could I enable cors in ejabberd yml file config?
`Access to XMLHttpRequest at 'https://techaboutweb.myvnc.com:5443/http-bind' from origin 'https://127.0.0.1' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

```
listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "0.0.0.0"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/http-bind": mod_bosh
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/oauth": ejabberd_oauth
             
  -
    port: 1883
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

```

**Comment by licaon-kter** [comment]
See my notes and example CORS: https://gist.github.com/54d4656cc753b98e1dc0d81a59a73faa

**Comment by joweste** [comment]
> See my notes and example CORS: https://gist.github.com/54d4656cc753b98e1dc0d81a59a73faa

Hi, I am using bosh and not ws.  And, I am not trying upload files.
Is possible change your example to use bosh?

**Comment by licaon-kter** [comment]
@joweste yeah, just imagine it says BOSH instead ;)


That's not the issue, how do you host your Converse files, ejabberd or nginx or what?

Include a [gist](https://gist.github.com) of your full config too, explaining what you've setup.

**Comment by joweste** [comment]
I am hosting converse files in my local server (127.0.0.1) to development and I have ejabberd installed in ec2 amazon windows server. Both https.
Here is my ejabberd setup: https://gist.github.com/joweste/bdb4eb07fde18bf34ec4a3ccce7a7845

**Comment by joweste** [comment]
I am geting this errors:
```
converse.js:35268 OPTIONS https://techaboutweb.myvnc.com:5443/http-bind 404 (Not Found)
sendFunc @ converse.js:35268
_processRequest @ converse.js:35283
_throttledRequestHandler @ converse.js:35429
_connect @ converse.js:34757
connect @ converse.js:32702
autoLogin @ converse.js:41282
tryCatch @ converse.js:3141
invokeCallback @ converse.js:3156
publish @ converse.js:3130
flush @ converse.js:2860
characterData (async)
(anonymous) @ converse.js:2832
asap @ converse.js:2784
fulfill @ converse.js:3083
handleMaybeThenable @ converse.js:3047
resolve @ converse.js:3060
resolvePromise @ converse.js:3191
xhr.onload @ converse.js:41119
load (async)
(anonymous) @ converse.js:41116
initializePromise @ converse.js:3190
Promise @ converse.js:3606
fetchLoginCredentials @ converse.js:41111
attemptNonPreboundSession @ converse.js:41227
logIn @ converse.js:41292
finishInitialization @ converse.js:41389
tryCatch @ converse.js:3141
invokeCallback @ converse.js:3156
publish @ converse.js:3130
flush @ converse.js:2860
characterData (async)
(anonymous) @ converse.js:2832
asap @ converse.js:2784
fulfill @ converse.js:3083
resolve @ converse.js:3062
resolvePromise @ converse.js:3191
xhr.onload @ converse.js:29659
load (async)
(anonymous) @ converse.js:29656
initializePromise @ converse.js:3190
Promise @ converse.js:3606
fetchTranslations @ converse.js:29647
_converse.initialize @ converse.js:41404
initialize @ converse.js:41572
inicializa_converse @ (index):1788
startChatConverse @ (index):1729
async function (async)
startChatConverse @ (index):1721
(anonymous) @ (index):1834
i @ IWLib__ED5676B5E.js:2
fireWith @ IWLib__ED5676B5E.js:2
ready @ IWLib__ED5676B5E.js:2
K @ IWLib__ED5676B5E.js:2
(index):1 Access to XMLHttpRequest at 'https://techaboutweb.myvnc.com:5443/http-bind' from origin 'https://127.0.0.1' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by licaon-kter** [comment]
You set CORS on your webserver, the one that hosts your Converse files, my gist explains this.

Why BOSH? Converse supports Stream Management on Websockets, it's recommended to uso it instead. 

Also, you hosting them on 127 might confuse some routing stuff, better use http://xip.io with a 192.168. or 10. address

**Comment by joweste** [comment]
Sorry, my I think I have to enable cors into ejabberd. I already have CORS enabled  into my local server.
How could I enable cors in ejabberd?

**Comment by joweste** [comment]
> You set CORS on your webserver, the one that hosts your Converse files, my gist explains this.
> 
> Why BOSH? Converse supports Stream Management on Websockets, it's recommended to use it instead.
> 
> Also, you hosting them on 127 might confuse some routing stuff, better use http://xip.io with a 192.168. or 10. address

Hi, I have following your tip and I am using websocket. All is working now. 
Thank you very much
