### ISSUE TITLE
mod_announce REST API control

### ISSUE THREAD

**Issue by thiras** [processone/ejabberd#3088]
**Is your feature request related to a problem? Please describe.**
It's really disappointment to not have REST endpoint to control announcements, especially at integration with other systems. 

**Describe the solution you'd like**
A REST endpoint to control mod_announce

Please let me know if I miss any endpoint that can control mod_announce or if any undocumented endpoint for it.

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#send-message  all these don't help?

**Comment by badlop** [comment]
Right, there is no specific commands for mod_announce. 

You can simply use **send_message** . Remember that the FROM address must be an account with admin rights in the server. For example:

> $ ejabberdctl send_message headline user1@localhost localhost/announce/all "Reminder" "This is justa reminder that..."

**Comment by thiras** [comment]
Thank you very much.
