### ISSUE TITLE
Completelly independent virtual host instances

### ISSUE THREAD

**Issue by MamasLT** [processone/ejabberd#3089]
Hello.
At the Ejabberd Architecture page (https://docs.ejabberd.im/developer/extending-ejabberd/architecture/) it says that:
"Instances can be made to be totally independent and invisible for each other if needed (or they can communicate as they would through federation).", but does not explain how to achieve this.

Could anyone tell me how to set multiple virtual hosts (domains), that have users, who cannot see each other, add to contacts and so on?
At this point, I have 2 virtual hosts present, but a user from 1 instance can add a user from another to his contacts and send messages as well. I would like to avoid that for certain domains (vhosts). Please, if you can tell me how to achieve this.

Thank you kindly!

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/admin/configuration/#global-options -> s2s_access...

**Comment by MamasLT** [comment]
Actually I think this might be the answer here: https://github.com/processone/ejabberd-contrib/tree/master/mod_isolation
I will check this out and post here how it worked.

Thanks

**Comment by zinid** [comment]
Yes, `mod_isolation` is what you need.

**Comment by MamasLT** [comment]
I entered these lines in ejabberd.yml configuration file, but now Ejabberd does not start, and I get this error: 
[critical] <0.28367.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option modules: unknown ejabberd module: mod_isolation. Did you mean mod_delegation?

Do I need somehow install this module for it to work? If so, could you give me a pointer on how to do that?
Thank you.

**Comment by MamasLT** [comment]
It's a bit messed up. I have found out how to install this module, I did that, but I can't start Ejabberd after this.
I have entered "mod_isolation: {}" to main config - it gave me error:
[critical] <0.788.0>@ejabberd_app:start:71 Failed to start ejabberd application: Configuration error: duplicated option: modules
I deleted that entry, and left only the one that is in module conf file, still got the same error.
Then I tried to comment out configuration lines in module configuration file, and re-entered "mod_isolation: {}" to main config again, now I get this error: 
[critical] <0.106.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option modules: unknown ejabberd module: mod_isolation. Did you mean mod_isolation?

Is this module new? i mean it seems like its not properly done. Is it approved by Ejabberd? Is this the only way to isolate vhosts and this is what Ejabberd means when they say ""Instances can be made to be totally independent and invisible for each other if needed (or they can communicate as they would through federation)."?
I am confused.
Help please?

**Comment by zinid** [comment]
The eaiest way to resolve your problem is to update ejabberd to `master` branch where all this was fixed.

**Comment by zinid** [comment]
> Is it approved by Ejabberd?

No. ProcessOne is not responsible for contributed modules and doesn't approve anything.

**Comment by MamasLT** [comment]
Hello. Im am using a newest Ejabberd version. I have installed aenigma, which comes with 19.05 version and then updated it using this method:

ejabberdctl stop
cd /opt
rm -r ejabberd-19.05
cd /opt/bitrock/
rm -R ejabberd-19.05-0
cd /tmp
wget -O ejabberd_19.09.1-0_amd64.deb https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/19.09.1/ejabberd_19.09.1-0_amd64.deb
sudo dpkg -i ejabberd_19.09.1-0_amd64.deb
cd /usr/sbin/
sudoedit ejabberdctl (Change root directory path to new version one)
rm /etc/systemd/system/ejabberd.service
cp /opt/ejabberd-19.09.1/bin/ejabberd.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ejabberd
ejabberdctl start

Is that not right way to update my aenigma/ejabberd instance? Could you give me an advice on how to do that properly, please?

And once again I would like just to confirm that when Ejabberd on their website says: "Instances can be made to be totally independent and invisible for each other if needed" - they mean mod_isolation, or some other method to achieve this? 
Thank You.
