### ISSUE TITLE
ejabberd and LDAP password problem

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3091]
If we change a password of an user on a LDAP server, the password does not work in ejabberd.
It is always the old password.

It works in all other applications.

**Comment by zinid** [comment]
```
$ ejabberdctl clear-cache
```

**Comment by Neustradamus** [comment]
@zinid: What is the difference between clear-cache and clear_cache?

And when we change the LDAP password and an ejabberd clear cache after it, the current XMPP session is not cutted. The XMPP session is always up.

How cut the XMPP session of the user?

**Comment by badlop** [comment]
@Neustradamus: What is the difference between clear-cache and clear_cache?

No difference, it's the same command, two ways to write it. Same with all other commands that have _:

```
$ ejabberdctl help clear-cache 
  Command Name: clear_cache
  Arguments: 
  Returns: res::rescode
  Tags:  server
  Description:  Clear database cache on all nodes
```

**Comment by Neustradamus** [comment]
Thanks @badlop for explaination.

But for the second part? In need to create a bug ticket?
-----------------------------------------------------------------
And when we change the LDAP password and an ejabberd clear cache after it, the current XMPP session is not cutted. The XMPP session is always up.

How cut the XMPP session of the user?

**Comment by Neustradamus** [comment]
@badlop: Thanks for your answer!
But it is not possible to kick all users without an ejabberd restart?
