### ISSUE TITLE
404 Not Found / mod_web_register on 19.09.1

### ISSUE THREAD

**Issue by StifflersMoM69** [processone/ejabberd#3092]
Hi, i am running ejabberd 19.09.1 on Ubuntu 18.04.3 LTS and enabled mod_register_web on port 5443

I am able to access the site through: https://HOST:5443/register

But when clicking on register, change password or delete accont i get the 404 error.

https://HOST:5443/admin instead works fine

Any ideas on that issues?

**Comment by licaon-kter** [comment]
ejabber.log has no info with loglevel 4?

**Comment by StifflersMoM69** [comment]
This is all i see $
2019-11-23 09:26:21.842 [info] <0.395.0>@ejabberd_listener:accept:256 (<0.541.0>) Accepted connection hidden_by_ejabberd ->

**Comment by StifflersMoM69** [comment]
Gist
https://gist.github.com/StifflersMoM69/0f5f48a2c30819dcd2e5cd573407decb

**Comment by licaon-kter** [comment]
Typo?
https://docs.ejabberd.im/admin/configuration/#mod-register-web
 > It is important to include the last / character in the URL, otherwise the subpages URL will be incorrect.

**Comment by StifflersMoM69** [comment]
Thanks. It really only was a typo.

**Comment by StifflersMoM69** [comment]
It is important to include the last / character in the URL, otherwise the subpages URL will be incorrect.
