### ISSUE TITLE
mod_register: Wrong FORM_TYPE value on register form

### ISSUE THREAD

**Issue by lovetox** [processone/ejabberd#3093]
## Environment

- ejabberd version: 19.08-2
- OS: Linux (Debian)

## Bug description

Example register form

```
<iq xmlns="jabber:client" xml:lang="de-DE" from="temptatio.dev" type="result" id="b67fdc30-5423-4adb-b7b0-32a878230b4b">
	<query xmlns="jabber:iq:register">
		<x type="form" xmlns="jabber:x:data">
			<instructions>Wählen sie zum Registrieren auf diesem Server einen Benutzernamen und ein Passwort</instructions>
			<field var="FORM_TYPE" type="hidden">
				<value>urn:xmpp:captcha</value>
			</field>
			<field var="username" type="text-single" label="Benutzer">
				<required />
			</field>
        ...
	</query>
</iq>
```
FORM_TYPE should be `jabber:iq:register` even if a captcha is included

**Comment by licaon-kter** [comment]
/duplicate https://github.com/processone/ejabberd/issues/3045 ?

**Comment by lovetox** [comment]
yeah it would be if that issue would be open

**Comment by licaon-kter** [comment]
Better add your arguments there then, to keep it in one place...

**Comment by lovetox** [comment]
It seems forgotten, as other people already asked to reopen it which was not done, and subsequently nobody cared anymore. Admin can do as he wishes with this issue, at least we have a response then.

**Comment by licaon-kter** [comment]
10 days have passed, why does it seem forgotten to you?

**Comment by zinid** [comment]
I reopened that issue.
