### ISSUE TITLE
Push notification workflow

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3094]
Hi All,
Ejabberd     - 19.09.1
Server OS   - Ubuntu 

I have been studying push notification in XMPP. So far i have got the clear picture of how this thing work . However I am using Ejabberd as my "App server" itself . So basically "App server" and "XMPP server" is single entity . Likewise my "App client and XMPP client " are the single entity. I want to implement push notification. mod_push is a bit confusing to me as i am not able to understand how ejabberd will identify the "App server" information and send it. So Here i am thinking about this approach

![image](https://user-images.githubusercontent.com/54536845/69522428-56d4a700-0f87-11ea-9d50-710071e2afd8.png)

1. While Registering client should send stanza for the allocation of the new node at pubsub service (mod_pubsub).
2. Server will create that node in return and inform the same to the client .
3. Client then again sends the IQ stanza including the node name/Id to ejabberd enable the push notification on that node .
4. Finally after these steps for sending the notification server will pick the token from the Database and then make API request to APNS/FCM to send notifications.

Can this approach work ?
Please suggest me about my approach and if there is any glitches please suggest . 

Thanks .

**Comment by shaggi7** [comment]
Any one, please ????

**Comment by weiss** [comment]
You're not describing an ejabberd, so this doesn't belong in this tracker.

The point of [XEP-0357][1] is making push notifications work in a federated network, where the XMPP service provider is not (necessarily) the app vendor.  In a closed environment where you control the app yourself, you don't need the "app server" proxy concept but could just let ejabberd generate APNS/FCM notifications directly, as supported by the Business Edition.  However, the Community Server neither supports APNS/FCM notifications nor does it ship an "app server", so if you're using it for a closed environment, you're on your own.

[1]: https://xmpp.org/extensions/xep-0357.html

**Comment by shaggi7** [comment]
Thanks @weiss for the suggestion. This help me a lot. Seems like i have to make a custom module for that.
