### ISSUE TITLE
Error on enable push notification stanza

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3095]
Hi,
Ejabberd - 19.09.1
Server OS - Ubuntu

I am working on a chat app using XMPP protocol and ejabberd as XMPP server. Considering this architecture

![image](https://user-images.githubusercontent.com/54536845/69606162-17ba5a80-1048-11ea-93c2-d53ec7d3f459.png)

I am using the same ejabberd server for XMPP server, App Server and XMPP push service. 
I am sending a stanza to enable the push notification from the client to ejabberd as follows:
```
<iq to="192.168.4.69" type="set" xmlns="jabber:client" id="4fec5817-8aa0-4ee2-ad8d-4940af7893f0:sendIQ">
       <enable xmlns="urn:xmpp:push:0" jid="pubsub.192.168.4.69" node="mynode_new"/>
</iq>
```

and i am getting error like this

```
<iq xmlns="jabber:client" xml:lang="en" to="tony@192.168.4.69/tony.webApp" from="192.168.4.69" type="error" id="4fec5817-8aa0-4ee2-ad8d-4940af7893f0:sendIQ">
     <enable xmlns="urn:xmpp:push:0" jid="pubsub.192.168.4.69" node="mynode_new"/>
     <error code="503" type="cancel">
          <service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
                <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">No module is handling this query
                </text>
     </error>
</iq>
``` 

Also if someone can tell me the jid(subdomain) of the push service in the ejabberd server. (I think that is the only thing that is creating issues)
Thanks .

**Comment by weiss** [comment]
You seem to be assuming ejabberd includes an "app server".  This assumption would be wrong, as mentioned in the first two sentences of the [`mod_push` documentation][1].  The main target audience of this module are public services running ejabberd's Community Server for users of standard clients such as Conversations or ChatSecure, where the app vendors (must) operate the "app servers" themselves.

[1]: https://docs.ejabberd.im/admin/configuration/#mod-push

**Comment by shaggi7** [comment]
Can i develop a custom module so that it can act as app server or can i write my own ejabberd module for the push notification ?

**Comment by weiss** [comment]
Yes, you could write an ejabberd module, or (if you'd prefer using a different programming language) an [external component][1].  See, for example, the [app server code][2] used for the Android client [Conversations][3], which is implemented as such a component.

[1]: https://xmpp.org/extensions/xep-0114.html
[2]: https://github.com/iNPUTmice/p2
[3]: https://conversations.im

**Comment by shaggi7** [comment]
Thanks @weiss for the help!!
