### ISSUE TITLE
inconsistent dependencies

### ISSUE THREAD

**Issue by darix** [processone/ejabberd#3102]
ejabberd and p1_acme have kinda conflicting dependencies:

ejabber:

- jiffy: 0.14.8
- jose: 1.8.4

p1_acme:

- jiffy: 1.0.1
- jose: 1.9.0

The good thing for me as a packager is that rebar allows system dependencies to be newer so it isnt a blocker. I just build ejabberd with the newer libs. 

The bad part is that it shows many of the dependency locks in the rebar.config might be referencing really old versions and could be bumped.

**Comment by badlop** [comment]
jose was updated to 1.9.0 in the latest release: https://github.com/processone/ejabberd/commit/0673b068e0f27afa7d731b54bc10ad521014f1e8
Regarding jiffy, I've now updated it to 1.0.1 in ejabberd's rebar.config

**Comment by darix** [comment]
what process have you put in place to prevent this kind of problem in 
the future?

**Comment by badlop** [comment]
I am not aware of any way to automate this, the only idea is to comment in ejabberd's rebar.config the crossed dependencies. Any other idea?

**Comment by darix** [comment]
A script that walks the rebar.config files of all dependencies and prints out such conflicts maybe?

I mean that could be even done in a rebar task and be useful for all rebar based projects?

**Comment by mremond** [comment]
@darix I think we would be willing to consider a PR with that change.

Thanks !
