### ISSUE TITLE
"cla-missing" label still attached to PRs although CLA was signed

### ISSUE THREAD

**Issue by lemenkov** [processone/ejabberd#3106]
Hello,
I've signed CLA for a while but some of my PRs still marked as cla-missing. Is it intentional?

**Comment by mremond** [comment]
Hi, no it is not intentional, which PR is it ?

**Comment by lemenkov** [comment]
> Hi, no it is not intentional, which PR is it ?

Look at #1595

**Comment by mremond** [comment]
ok I fixed it manually.
Sorry about that.
