### ISSUE TITLE
Menu items missing in web_admin

### ISSUE THREAD

**Issue by erik-de-neve** [processone/ejabberd#3110]
## Environment

- ejabberd version: 19.09.1
- Erlang version: 10.3.4
- OS: Linux (ubuntu)
- Installed from: official binary installer
- Using MySQL database

## Bug description
We upgraded from version 19.02 to 19.09.1

In webadmin a lot of menu items are disappeared (although we are loggeed in as 'admin' user).
For example: 
Access Control Lists, Access Rules, Last Activities (on server)
Listing ports (on nodes),...

For example: if we go directly to https://{{HOST}}:8443/admin/node/ejabberd@localhost/ports//
It gives 'Not Found'.

This was working in 19.02, is something changed between 19.02 and 19.09.1 regarding this items? (couldn't find something in the changelog)
![ejabber](https://user-images.githubusercontent.com/3438839/70524436-6cc89700-1b45-11ea-85c8-478f54bc5db3.png)

**Comment by zinid** [comment]
ACL, Access Rules and Listening Ports were broken a long time ago. Since there were no complaints they have been removed. Now only dynamic information is left in the web console and all static information is now configured via ejabberd.yml. Regarding Last Activity: it should be working I think.

**Comment by jeremiasdsa** [comment]
@erik-de-neve @zinid 

I'm using ejabberd-20.04 default installation on AWS EC2 linux instance.
And WebAdmin is missing some menu as @erik-de-neve told. 
How to fix it?
