### ISSUE TITLE
Ejabberd Module

### ISSUE THREAD

**Issue by WajahatAhmed9** [processone/ejabberd#3111]
## Environment

- ejabberd version: 19.09.1
- Erlang version: `erl +V`
- OS: Linux (Ubuntu)
- Installed from: ProcessOne

I installed mod_statsdx module. When I start ejabbed without and with putting yml configuration in main ejabberd.yml file, it shows an error "Duplicate option: modules".

**Comment by zinid** [comment]
Fixed in `master`. Will land in 20.01.

As a work-around find the configuration file in the module and move its content to main `ejabberd.yml`.
