### ISSUE TITLE
Room option `getmemberlist` in XEP-0045 but ejabberd does not have

### ISSUE THREAD

**Issue by conandung99** [processone/ejabberd#3112]
https://xmpp.org/extensions/xep-0045.html#roomconfig

This issue opened before but it does not resolve
https://github.com/processone/ejabberd/issues/2606

**Comment by badlop** [comment]
It seems quite obvious that there is not interest in implement that feature.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/processone/xmpp/issues/91
