### ISSUE TITLE
Load test issue with online users

### ISSUE THREAD

**Issue by sujankumar4593** [processone/ejabberd#3114]
## Environment

- ejabberd version: 19.05
- Erlang version: 21
- OS: Linux (Debian)
- Installed from: source 

**Ejabberd.yml File**
`
hosts:
        - "example.com"

loglevel: 3
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 1000

certfiles:
        - "/opt/ejabberd/certs/ejabberd.pem"

define_macro:
  CIPHERS_INTERMEDIATE: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
  PROTOCOL_OPTIONS_INTERMEDIATE:
    - "no_sslv2"
    - "no_sslv3"

  CIPHERS_MODERN: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
  PROTOCOL_OPTIONS_MODERN:
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"

c2s_ciphers: CIPHERS_INTERMEDIATE
c2s_protocol_options: PROTOCOL_OPTIONS_INTERMEDIATE

listen :
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 65535
    max_fsm_queue: 500000
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5281
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/websocket": ejabberd_http_ws
    web_admin: true
    captcha: true
    ciphers: CIPHERS_INTERMEDIATE
    protocol_options: PROTOCOL_OPTIONS_INTERMEDIATE
    tls: false
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    web_admin: true
   

s2s_use_starttls: optional

auth_method: sql
auth_use_cache: false

sql_type: mysql
sql_server: "localhost"
sql_database: "ejabberd_19"
sql_username: "ejabberd"
sql_password: "password"
sql_pool_size: 10

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - "192.168.0.0/24"
      - "::1/128"

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who: all
    what: "*"
  "public commands":
    who: all
    what:
      - "status"
      - "register"  
      - "connected_users_number"
      - "list_cluster"  
      - "join_cluster"   

shaper:
  normal: 100000000
  fast: 500000000

shaper_rules:
  max_user_sessions: 
      - 10: admin
      - 5
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

registration_timeout: infinity
modules:
  mod_blocking: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_last: 
    db_type: sql
    use_cache: false
  mod_mam:
    db_type: sql
    use_cache: false
    assume_mam_usage: true
    default: always
  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages 
  mod_privacy:
    db_type: sql 
    use_cache: false     
  mod_private: {}
  mod_mix: 
    db_type: sql
  mod_mix_pam:   
    db_type: sql
    use_cache: true
  mod_pubsub:
    db_type: sql
    ignore_pep_from_offline: true
    last_item_cache: false
    access_createnode: pubsub_createnode
    plugins: 
      - "pep"
    force_node_config:
      "storage:bookmarks":
        access_model: whitelist
  mod_register:
    ip_access: trusted_network
  mod_roster:
    db_type: sql
    versioning: true
    use_cache: false
  mod_vcard:
    db_type: sql
    search: false    
  mod_vcard_xupdate: {}
`

## Errors from error.log/crash.log

No errors in error.log

## Bug description

When I load test the ejabberd 19.05 with Tsung without enabling TLS I can achive 50k online users and message with the following Script
```<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd" []>
<tsung loglevel="notice" dumptraffic="false" version="1.0">
  <clients>
    <client host="localhost" maxusers="100000" use_controller_vm="true">
    </client>
  </clients>

<servers>
    <server host="example.com" port="5222" type="tcp"/>
</servers>

<monitoring>
          <monitor host="localhost" type="erlang"/>
  </monitoring>

<load>
  <arrivalphase phase="1" duration="10" unit="minute">
    <users maxnumber="50000" arrivalrate="500" unit="second"/>
  </arrivalphase>
  </load>

<options>
  <option type="ts_jabber" name="global_number" value="50000"/>
  <option type="ts_jabber" name="userid_max" value="50000"/>
  <option type="ts_jabber" name="domain" value="example.com"/>
 <option type="ts_jabber" name="username" value="tsung"/>
 <option type="ts_jabber" name="passwd" value="tsung"/>
</options>

<sessions>
    <session probability="100" name="jabber-example" type="ts_jabber">
    <transaction name="connect">
    <thinktime value="10"/> 
      <request> <jabber type="connect" ack="local"/> </request>
    </transaction>
    <transaction name="authenticate">
        <request> <jabber type="auth_sasl" ack="local"/> </request>
        <thinktime value="10"/>
        <request> <jabber type="connect" ack="local"/> </request>
        <request> <jabber type="auth_sasl_bind" ack="local"/></request>
	<request> <jabber type="auth_sasl_session" ack="local"/></request>
        <request> <jabber type="presence:initial" ack="global"/> </request>
    </transaction>
    <thinktime value="120"/>
    <for from="1" to="2" var="i">
    <transaction name="Chat">
    <request> <jabber type="chat" ack="global" size="10" destination="online"/> </request>
    </transaction>
    </for>
<thinktime value="60"/>
    <transaction name="close">
        <request> <jabber type="close" ack="local"/> </request>
    </transaction>
    </session>
</sessions>
</tsung>
```
But When I enabled the TLS in ejabberd 19 only 20k users coming online with the following script

```<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd" []>
<tsung loglevel="notice" dumptraffic="false" version="1.0">
  <clients>
    <client host="localhost" maxusers="100000" use_controller_vm="true">
    </client>
  </clients>

<servers>
    <server host="example.com" port="5222" type="tcp"/>
</servers>

<monitoring>
          <monitor host="localhost" type="erlang"/>
  </monitoring>

<load>
  <arrivalphase phase="1" duration="10" unit="minute">
    <users maxnumber="50000" arrivalrate="500" unit="second"/>
  </arrivalphase>
  </load>

<options>
  <option type="ts_jabber" name="global_number" value="50000"/>
  <option type="ts_jabber" name="userid_max" value="50000"/>
  <option type="ts_jabber" name="domain" value="example.com"/>
 <option type="ts_jabber" name="username" value="tsung"/>
 <option type="ts_jabber" name="passwd" value="tsung"/>
</options>

<sessions>
    <session probability="100" name="jabber-example" type="ts_jabber" bidi="true">
    <transaction name="connect">
    <thinktime value="10"/> 
      <request> <jabber type="connect" ack="local"/> </request>
      <request> <jabber type="starttls" ack="bidi_ack"/> </request>
      <request> <jabber type="connect" ack="local"/> </request>
    </transaction>
    <transaction name="authenticate">
        <request> <jabber type="auth_sasl" ack="local"/> </request>
        <thinktime value="10"/>
        <request> <jabber type="connect" ack="local"/> </request>
        <request> <jabber type="auth_sasl_bind" ack="local"/></request>
	<request> <jabber type="auth_sasl_session" ack="local"/></request>
        <request> <jabber type="presence:initial" ack="global"/> </request>
    </transaction>
    <thinktime value="180"/>
    <for from="1" to="2" var="i">
    <transaction name="Chat">
    <request> <jabber type="chat" ack="global" size="10" destination="online"/> </request>
    </transaction>
    </for>
<thinktime value="120"/>
    <transaction name="close">
        <request> <jabber type="close" ack="local"/> </request>
    </transaction>
    </session>
</sessions>
</tsung>
```
**These are the error from the Tsung**
```
stats: error_connection_closed 0 12276
stats: error_connect_etimedout 0 4778
stats: error_connect_closed 0 2
stats: error_timeout 0 9
stats: error_unknown_msg 0 12276
stats: error_send_einval 0 11
stats: error_unknown 0 13925

```
Any help?

**Comment by licaon-kter** [comment]
You don't need help...youo need more hardware, maybe some TLS offloading :)

Also, so use RTB instead for testing: https://github.com/processone/rtb

/close as not an issue

**Comment by zinid** [comment]
TLS creates an overhead, yes.
