### ISSUE TITLE
mod_muc_log html skips messages with non-Latin letters

### ISSUE THREAD

**Issue by yandrey** [processone/ejabberd#3115]
## Environment

- ejabberd: master
- Erlang version: Erlang/OTP 21 
- OS: Linux (Debian)

## Bug description

mod_muc_log writes latin symbols successfully in html logs, but skips every message with, say, russian symbols.

say in Psi client:
```
[21:27:45] <admin> привет! 
[21:38:33] <admin> hello
```

but the html log made by mod_muc_log included into the sources:
```
[21:27:43] admin joins the room
[21:38:33] <admin> hello
```
that is 
```html
<a id="21:27:43.884544" name="21:27:43.884544" href="#21:27:43.884544" class="ts">[21:27:43]</a> <font class="mj">admin joins the room</font><br/>
<a id="21:38:33.796709" name="21:38:33.796709" href="#21:38:33.796709" class="ts">[21:38:33]</a> <font class="mn">&lt;admin&gt;</font> hello<br/>

```

**Comment by yandrey** [comment]
same for chinese or any other symbols, say:
```
[23:47:22] <admin> 中國人 
```
nothing in the log

**Comment by yandrey** [comment]
minimal change of mod_muc_log.erl would be:
- to remove redundant list_to_binary at line 444
- to replace binary_to_list at line 532 to unicode:characters_to_list

**Comment by Neustradamus** [comment]
A nice bug :)
Have you seen same a problem in another modules too?
Maybe you can create here too:
- https://github.com/processone/ejabberd-contrib

**Comment by badlop** [comment]
Thanks for reporting! I've applied a slightly different fix.
