### ISSUE TITLE
ejabberd addition.js and style.css file not loaded in web admin 

### ISSUE THREAD

**Issue by AhsanFasihi** [processone/ejabberd#3117]
I download ejabberd source code in ubuntu and compiled 100% but when I login addition.js and style.css is not loaded in web admin.

Can anyone help me.
![2019-12-17_124435](https://user-images.githubusercontent.com/58970537/70975084-0c000800-20cb-11ea-9731-6319cb9250ce.png)

**Comment by licaon-kter** [comment]
Your permissions are ok?

**Comment by zinid** [comment]
There must be something in error.log/ejabberd.log

**Comment by AhsanFasihi** [comment]
[ejabberd.log.txt](https://github.com/processone/ejabberd/files/3972073/ejabberd.log.txt)

Error.log file is empty

**Comment by AhsanFasihi** [comment]
and thank you for prompt response

**Comment by zinid** [comment]
How did you install? [This](https://github.com/processone/ejabberd/tree/master/priv) directory must be copied to the installation path when running `make install`. Make sure you see this directory.

**Comment by AhsanFasihi** [comment]
This is my source code directory 
![2019-12-17_132114](https://user-images.githubusercontent.com/58970537/70977809-749db380-20d0-11ea-8745-e65a2cd97b33.png)
This is my installation directory
![2019-12-17_132312](https://user-images.githubusercontent.com/58970537/70977840-854e2980-20d0-11ea-840a-c0bb05c6084c.png)

**Comment by zinid** [comment]
That's not what I'm asking about.

**Comment by AhsanFasihi** [comment]
> How did you install? [This](https://github.com/processone/ejabberd/tree/master/priv) directory must be copied to the installation path when running `make install`. Make sure you see this directory.

@zinid I'm a newbie, can you explain do we need to copy manually priv directory in installation path or what ?

**Comment by zinid** [comment]
No, `make install` should have copied everything automatically, so I'm asking you to check that the copying was successful, which means you should see `priv` directory on your installation path (I guess your installation path is `/home/ahsan/my-ejabberd`).

**Comment by zinid** [comment]
Also, we don't support newbie questions here, it's a bugtracker, not help desk.

**Comment by AhsanFasihi** [comment]
> No, `make install` should have copied everything automatically, so I'm asking you to check that the copying was successful, which means you should see `priv` directory on your installation path (I guess your installation path is `/home/ahsan/my-ejabberd`).

indeed this is the installation path and I shown the files as well in above snapshot.

**Comment by badlop** [comment]
I see you visited URL **localhost:5280/admin** Try **localhost:5280/admin/** notice the / at the end.

**Comment by AhsanFasihi** [comment]
Thanks man..you are a star..solved my problem.
![2019-12-17_152514](https://user-images.githubusercontent.com/58970537/70987381-981d2a00-20e1-11ea-8b2a-17ebda107ae0.png)

**Comment by zinid** [comment]
@badlop shouldn't it be fixed?

**Comment by badlop** [comment]
I guess the next question is why that admin page shows no information. Quite simple: the account you used to login does not have admin rights. Solution: use an account with admin rights in ejabberd.yml.

**Comment by AhsanFasihi** [comment]
@badlop I know this thing to put rights in acl in ejabberd.yml
