### ISSUE TITLE
Import from Isode M-Link, Jackal, Metronome IM, Prosody 0.12.x, Tigase 8.0 do not work

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3118]
Currently, there is a problem to import data into ejabberd from:
- Isode M-Link XMPP server
- Jackal XMPP server
- Metronome IM XMPP server
- Prosody XMPP server 0.12.x
- Tigase XMPP server 8.0

I think it is linked to SCRAM-SHA-256 but I am not 100% sure.

**Comment by zinid** [comment]
We have no plans to support importing from anything except Prosody.

**Comment by Neustradamus** [comment]
@zinid: Nice any news for compatibility with Prosody 0.12.x?
