### ISSUE TITLE
After a password change, the XMPP session is always here

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3119]
When we change an user password, the current XMPP session is not cutted.
The XMPP session is always up.

How cut the XMPP session of the user?

**Comment by badlop** [comment]
What does the protocol say about that case?

**Comment by zinid** [comment]
@badlop [XEP-0077](https://xmpp.org/extensions/xep-0077.html#usecases-changepw) doesn't require anything like this.

In order to close the session one can use `kick_user` command.

**Comment by Neustradamus** [comment]
@zinid: Thanks!
