### ISSUE TITLE
store_offline_message triggered even if message limit has been reached

### ISSUE THREAD

**Issue by McPo** [processone/ejabberd#3120]
## Environment

- ejabberd version: 18.09
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 9.3
- OS: Linux (Alpine)
- Installed from: Docker

`store_offline_message` hook continues to be triggered even though the the offline storage is full and the message has been discarded. This results in the user being notified of a message despite that particular message not existing. (Other will have, but that wont).

Instead store_offline_message hook, should only be triggered when the message has been stored successfully, or report that the message was not stored due to an error (limit reached)

**Comment by zinid** [comment]
I don't see this in [the code](https://github.com/processone/ejabberd/blob/18.09/src/mod_offline.erl#L418-L419): `stop` is clearly returned, so the hook must be aborted.

**Comment by zinid** [comment]
Ah, sorry, you're talking about another hook.

**Comment by zinid** [comment]
Well, I agree that `store_offline_msg/1` function must be hooked on `store_offline_message` hook itself, so we will have flexibility, including stopping the hook when storing fails.
