### ISSUE TITLE
eJabberd - Botpress Integration

### ISSUE THREAD

**Issue by maniskec** [processone/ejabberd#3130]
Hello all,
I am chatbot developer and entirely new to ejabberd - XMPP server. I have deployed the server in my localmachine and used pidgin as a webclient , it is working fine. 

Now I want to deploy chatbot done in botpress. I dont have any idea to deploy it in ejabberd. 
can somebody help me out?
Let me know if you need any more information on this.

**Comment by licaon-kter** [comment]
This is not an advice site, join xmpp:ejabberd@conference.process-one.net?join for that

/close this

**Comment by sandeesaripalli** [comment]
did anybody figured out?
