### ISSUE TITLE
Import from Prosody 0.12.x do not work

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3134]
A new ticket because no reply on closed ticket:
- https://github.com/processone/ejabberd/issues/3118
- https://github.com/processone/ejabberd/issues/3118#issuecomment-568890821

Currently, there is a problem to import data into ejabberd from:
- Prosody XMPP server 0.12.x

I think it is linked to SCRAM-SHA-256 but I am not 100% sure.

**Comment by badlop** [comment]
Hi, can you provide some example files to import into ejabberd?

**Comment by zinid** [comment]
I close the issue until the data that fails to be exported is provided.
