### ISSUE TITLE
Ejabberd and Postgresql

### ISSUE THREAD

**Issue by BooneyNoobington** [processone/ejabberd#3135]
ejabberd 19.09.74 (erlang version is 23) works well with postgres 12.1. I have compiled all these programms from source on Ubuntu 19.10. Erlang with ssl-support and ejabberd with the --with-pgsql option.

Unfortunately ejabberd can only connect to the postgresql-server (localhost:5432) using the (plaintext) password authentification method. Using md5 or scram-sha-256 yields the error message.

`{authentication,{unknown,10}}`

I'm not sure if this is actually an issue with ejabberd or rather erlang since the following page states that the only supported driver for erlang is "epgsql" which I don't think my erlang installation is using (or is it?).

https://wiki.postgresql.org/wiki/List_of_drivers

I'm quite lost on this one and google isn't much help either since the mysql/maridb is well documented and postgres not so much.

Any idea what I'm doing wrong?

Additional information:
Portion of my ejabberd config.
```
sql_type: pgsql
sql_server: "localhost"
sql_database: "ejabberd"
sql_username: "ejabberd"
#sql_ssl: true
#sql_ssl_verify: true
#sql_ssl_cafile: /srv/ejabberd/etc/ejabberd/root.crt
#sql_ssl_certfile: /srv/ejabberd/etc/ejabberd/ejabberd.key
sql_password: ************************
## If you want to specify the port:
#odbc_port: 5432 
auth_method: [sql]
auth_password_format: scram
default_db: sql
```

Portion of pg_hba.conf (controls how postgres handles logins).
```

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local    ejabberd        ejabberd                                peer
local    all             postgresql                              peer
# IPv4 local connections:
host     ejabberd        ejabberd        127.0.0.1/32            password
# IPv6 local connections:
#host    all             all             ::1/128                 scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     all                                     scram-sha-256
#host    replication     all             127.0.0.1/32            scram-sha-256
#host    replication     all             ::1/128                 scram-sha-256
```

**Comment by zinid** [comment]
ejabberd is using https://github.com/processone/p1_pgsql driver (due to historical reasons). The driver only supports plain and md5 authentication.
