### ISSUE TITLE
MAM: Unable to get more than the 20 latest messages

### ISSUE THREAD

**Issue by Bonjour123** [processone/ejabberd#3137]
## Environment

- ejabberd version: 19.09.1
- Erlang version: 10.3
- OS: Windows 7 64 bit
- Installed from:installer

## Errors from error.log/crash.log

No errors

## Bug description

What I get: 

When requesting the last 100 MAM archives of a MUC from StropheJS, I always only get the 20 latest. I don't think it's related to Strophe, as the stanza (gotten from Chrome Dev Network tab) display valid stanzas + if I indicate a max number of 10, I indeed get only 10 message archives.

What I should get:

All messages, or at least 100 in there are more than 100.

Here is the mam request sent by Strophe to ejabberd:
`<iq id="367576e1-a597-4443-8cda-7624dc37a68b:sendIQ" to="0_2_2020nike_crew_neck_pink_t-shirt.dispute@muc.window-pc" type="set" xmlns="jabber:client"><query xmlns="urn:xmpp:mam:2"><x type="submit" xmlns="jabber:x:data"><field type="hidden" var="FORM_TYPE"><value>urn:xmpp:mam:2</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><max>100</max><before></before></set></query></iq>`

Here how looks the archives answered back by the ejabberd:
`<message xmlns='jabber:client' xml:lang='en' to='5e0e417fdc04e599f989bf7f@lucas-pc/141864563438180564503555' from='0_2_2020nike_crew_neck_pink_t-shirt.dispute@muc.window-pc/dsdsdasqsq' type='groupchat' id='1578005512557'><delay from='0_2_2020nike_crew_neck_pink_t-shirt.dispute@muc.window-pc' stamp='2020-01-02T22:39:15.416252Z' xmlns='urn:xmpp:delay'/><body>fdf</body></message>`

So Why can't I get more than 20 messages archives ? (I precise that I do have sent more than 20 messages to this MUC)

**Comment by licaon-kter** [comment]
Your config in a gist?

**Comment by Bonjour123** [comment]
Sure! https://gist.github.com/Bonjour123/5319c5803a6fed7ccd2658edac06e6c3

**Comment by prefiks** [comment]
I think in this case this room doesn't have mam flag switched on, so no messages are archived in db, and that query can only use data that room process uses for sending N latest messages for newly joining users - this means that it can have access to last 20 messages (or whatever value is configured).

You need to change room config and enable mam option to have persistent storage of muc messages.

**Comment by Bonjour123** [comment]
That's true, I didn't set mam flag at room creation. Going to try and let you know !
