### ISSUE TITLE
Native library for xcode 

### ISSUE THREAD

**Issue by dverdugo85** [processone/ejabberd#3138]
## Environment
Hello 

 I development a native app for iPhone and I need a library to connect to ejabbberd.. what recommend?? Regards!!
- ejabberd version: 19.09
- Erlang version: `erl +V`
- OS: Linux xcode
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)

**Comment by licaon-kter** [comment]
/close as not an issue

Do look at what Monal or ChatSecure use

**Comment by dverdugo85** [comment]
https://github.com/tigase/tigase-swift what its your Opinion?? Regards!!!

**Comment by mremond** [comment]
The main library for XMPP on iOS is [XMPPframework](https://github.com/robbiehanson/XMPPFramework).
