### ISSUE TITLE
mod_sip.erl:381: undefined macro 'T/1'

### ISSUE THREAD

**Issue by yandrey** [processone/ejabberd#3143]
## Environment
- ejabberd version: master

make
...
==> ejabberd (compile)
src/mod_sip.erl:381: undefined macro 'T/1'
src/mod_sip.erl:32: function mod_doc/0 undefined
Compiling src/mod_sip.erl failed:
ERROR: compile failed while processing /home/andrey/dev/ejabberd: rebar_abort
Makefile:112: recipe for target 'src' failed
make: *** [src] Error 1

the -include("translate.hrl"). is inside -ifndef(SIP)...endif but mod_doc() with ?T macro is outside.

maybe just to push that mod_sip ... :slightly_smiling_face:

**Comment by licaon-kter** [comment]
Share your setup? How did you compile?

**Comment by yandrey** [comment]
just pull master and do make

**Comment by yandrey** [comment]
and you can just browse the file mod_sip in the master here on github:
```
31: -ifndef(SIP).
...
56: -include("translate.hrl"). %% ?T defined
...
377: -endif.

379: mod_doc() ->
    #{desc =>
          [?T("This module adds SIP proxy/registrar support "
```

**Comment by licaon-kter** [comment]
Not seeing this on arm64

Do detail your setup, OS, erlang version, erlang packages installed, ett.

**Comment by yandrey** [comment]
Linux (Ubuntu 64 bit Bioinic),  Erlang/OTP 21 [erts-10.2.3]  

but this is irrelevant.

just look the sources, master src/mod_sip.erl here on github, it can't be compiled neither on amd64 nor arm64, x86 whatever, when SIP is defined this mod_sip.erl can't be compiled !

just do clean cloning like this and you'll see:
```
git clone https://github.com/processone/ejabberd.git
Cloning into 'ejabberd'...
cd ejabberd
...
./autogen.sh
...
./configure
...
make
.....
src/mod_sip.erl:381: undefined macro 'T/1'
src/mod_sip.erl:32: function mod_doc/0 undefined
Compiling src/mod_sip.erl failed:
ERROR: compile failed while processing /home/user1/tmp/ejabberd: rebar_abort
Makefile:111: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1
```
