### ISSUE TITLE
Ejabberd throws 'deps/.got' exception while installation

### ISSUE THREAD

**Issue by dineshrawat11** [processone/ejabberd#3144]
## Environment

- ejabberd version: 19
- Erlang version: 
`Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
 
Eshell V10.6.1
`
- OS: Linux (Ubuntu 16)

## Steps followed

- git clone ...

- ./autogen.sh

- ./configure --enable-mysql

Result:
--------

`
$ ./configure --enable-mysql

checking whether make sets $(MAKE)... yes

checking for a BSD-compatible install... /usr/bin/install -c

checking for a sed that does not truncate output... /bin/sed

checking for erl... /usr/bin/erl

checking for erlc... /usr/bin/erlc

checking for epmd... /usr/bin/epmd

checking for erl... /usr/bin/erl

checking for erlc... /usr/bin/erlc

checking Erlang/OTP version... ok

checking for Erlang/OTP root directory... /usr/lib/erlang

checking for escript... /usr/lib/erlang/bin/escript

checking for make... make

configure: creating ./config.status

config.status: creating Makefile

config.status: creating vars.config

config.status: creating src/ejabberd.app.src
`

- make

## Errors while installation

The last command make throws error everytime-

`
rm -rf deps/.got

rm -rf deps/.built

mkdir -p deps

/usr/lib/erlang/bin/escript rebar get-deps && :> deps/.got

WARN:  Directory expected to be an app dir, but no app file found 
in ebin/ or src/:

/media/dineshrawat/data/node-js/projects/ejabberd/deps/pkix

==> goldrush (get-deps)

==> lager (get-deps)

==> p1_utils (get-deps)

==> cache_tab (get-deps)

==> fast_tls (get-deps)

==> stringprep (get-deps)

==> fast_xml (get-deps)

==> unicode_util_compat (get-deps)

==> idna (get-deps)

==> ezlib (get-deps)

==> xmpp (get-deps)

==> fast_yaml (get-deps)

==> yconf (get-deps)

==> jiffy (get-deps)

WARN:  Missing plugins: [rebar3_hex]

==> p1_oauth2 (get-deps)

==> rel (get-deps)

==> ejabberd (get-deps)

WARN:  Directory expected to be an app dir, but no app file found 
in ebin/ or src/:

/media/dineshrawat/data/node-js/projects/ejabberd/deps/pkix
WARN:  Directory expected to be an app dir, but no app file found 
in ebin/ or src/:

/media/dineshrawat/data/node-js/projects/ejabberd/deps/pkix

ERROR: Dependency dir /media/dineshrawat/data/node-js/projects/ejabberd/deps/pkix failed application validation with reason:

{missing_app_file,"/media/dineshrawat/data/node-js/projects/ejabberd/deps/pkix"}.

ERROR: 'get-deps' failed while processing /media/dineshrawat/data/node-js/projects/ejabberd: rebar_abort

Makefile:105: recipe for target 'deps/.got' failed

make: *** [deps/.got] Error 1

`

[Stackoverflow link](https://stackoverflow.com/q/59717019/3704054)

**Comment by prefiks** [comment]
Hello,

It looks like you have empty or at least broken deps/pkix directory in your installation, could you check if deleting it or whole deps/ dir help with it?

**Comment by dineshrawat11** [comment]
@prefiks I did that already but no luck!

**Comment by dineshrawat11** [comment]
I reinstalled different version nothing was working then I cleaned everything and reinstalled the latest version and it worked!!

**Comment by dineshrawat11** [comment]
Hince. closing the issue
