### ISSUE TITLE
NS_CARBONS_RULES_0 is not defined and prevent ejabberd to compile

### ISSUE THREAD

**Issue by otiteca971** [processone/ejabberd#3146]
## Environment

- ejabberd version: master
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.6.1
- OS: Linux (Debian)
- Installed from: source 

## Bug description
Compiling 265 files (.erl)
src/mod_pubsub.erl:35: Warning: undefined callback function mod_doc/0 (behaviour 'gen_mod')
src/mod_shared_roster_ldap.erl:31: Warning: undefined callback function mod_doc/0 (behaviour 'gen_mod')
src/mod_carboncopy.erl:80: undefined macro 'NS_CARBONS_RULES_0'
src/mod_carboncopy.erl:37: function disco_features/5 undefined
src/mod_carboncopy.erl:74: spec for undefined function disco_features/5

**Comment by weiss** [comment]
You didn't update your `deps`.  Run `make update` or `make distclean` before rebuilding.

**Comment by otiteca971** [comment]
ok, it's working with the Makefile, but still struggling with mix.
I did verify the xmpp dependency and its version is 1.4.3 so the same than rebar is using.
But mix compile is still showing the error mentionned.

**Comment by otiteca971** [comment]
I succeed to compile with mix only by fetching xmpp from git and with the tag that you are using for rebar deps.
     {:xmpp, git: "https://github.com/processone/xmpp", tag: "f98a50eb4135"},
     instead of {:xmpp, "~> 1.4.0"}
So should be interested to let others know about it.
Cheers
