### ISSUE TITLE
2020 New Year copyright update in all ProcessOne projects

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3149]
Like each year, I request the new year copyright update for all ProcessOne projects ;)

Happy New Year 2020!

**Comment by badlop** [comment]
Ticket from last year: https://github.com/processone/ejabberd/issues/2756

Remaining libraries:
https://github.com/processone/cache_tab
https://github.com/processone/eimp
https://github.com/processone/epam
https://github.com/processone/erlang-sqlite3
https://github.com/processone/esip
https://github.com/processone/ezlib
https://github.com/processone/fast_tls
https://github.com/processone/fast_xml
https://github.com/processone/fast_yaml
https://github.com/processone/mqtree
https://github.com/processone/p1_acme.git
https://github.com/processone/p1_mysql
https://github.com/processone/p1_oauth2
https://github.com/processone/p1_pgsql
https://github.com/processone/p1_utils
https://github.com/processone/pkix
https://github.com/processone/rebar_elixir_plugin
https://github.com/processone/stringprep
https://github.com/processone/stun
https://github.com/processone/xmpp
https://github.com/processone/yconf

**Comment by Neustradamus** [comment]
Do not forget https://github.com/FluuxIO too :)

**Comment by Neustradamus** [comment]
Do not forget: https://github.com/processone/ejabberd-contrib too

**Comment by badlop** [comment]
> Do not forget https://github.com/FluuxIO too :)

Yes, that will be done when strictly required.

**Comment by Neustradamus** [comment]
@badlop: not for other projects?
Examples:
- https://github.com/processone/boxcar-ios-framework
- https://github.com/processone/rtb
- https://github.com/processone/iconv
- ...
