### ISSUE TITLE
Documentation:  put_url in mod_http_upload documentation out-of-sync with implementation

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#3152]
## Environment
- ejabberd version: master

## Bug description

src/mod_http_upload.erl:219: `{put_url, <<"https://", Host/binary, ":5443/upload">>},`
src/mod_http_upload.erl:323 (documentation) `"The default value is \"http://@HOST@:5444\".")}},`

I think the URL in the documentation should be `https://@HOST@:5443/upload` (http vs. https and port number).

**Comment by licaon-kter** [comment]
You can have any port there, you can host it on an external service too.

**Comment by Andy-2639** [comment]
I understand that.
My point is that the implemented default value should match the default value mentioned in the documentation.
