### ISSUE TITLE
host configuration option of mod_http_upload

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#3153]
## Environment

- OS: Windows 10 1909
- ejabberd: https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/20.01/ejabberd-20.01-windows.exe

## Description

I configured `mod_http_upload` without `host` option (= `upload.@HOST@`). In the log, the warning
```
2020-01-26 00:10:43.016 [warning] <0.328.0>@ejabberd_pkix:check_domain_certfiles:312 No certificate found matching upload.***
```
appears but http_upload works without problems with the conversations client.

When I configure `mod_http_upload` with `host: @HOST@`, I get the error message
```
2020-01-26 00:09:29.641 [critical] <0.105.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option modules->mod_http_upload->host: failed to reuse route '***' because it's already registered on a virtual host
```

Is this a XMPP limitation or an ejabberd limitation that I cannot just use `@HOST@` as value for the `host` option?

In the issue https://github.com/processone/ejabberd/issues/1386#issuecomment-359574752 , I found the information that the given domain only needs to exist for remote users. Could this information be put into the documentation (also for muc, pubsub, ...)?

**Comment by weiss** [comment]
> but http_upload works without problems with the conversations client.

Yes, it will work for local users, and usually you won't permit remote users to upload to your server anyway.  Not adding this subdomain to DNS and to your certificate can still lead to `[warning]`s in log files of remote servers (e.g., when remote clients try to perform a service discovery on your server), but apart from that everything will work fine.

> Is this a XMPP limitation or an ejabberd limitation that I cannot just use @HOST@ as value for the host option?

In theory, XMPP would allow for doing that, but it would be quite hacky.  ejabberd's way of enforcing separate JIDs for separate services so the server can route traffic based on the `to` address is the obvious/efficient way to do it.

> Could this information be put into the documentation (also for muc, pubsub, ...)?

I'm not quite sure where and how such things are best described.  Maybe in a separate section that discusses required and optional DNS settings.

Feel free to [make suggestions][1] and/or [send pull requests][2] against the [documentation repository][3].

[1]: https://github.com/processone/docs.ejabberd.im/issues/new
[2]: https://github.com/processone/docs.ejabberd.im/pulls
[3]: https://github.com/processone/docs.ejabberd.im
