### ISSUE TITLE
20.01 post/docs missing psql.new update block

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3157]
https://blog.process-one.net/ejabberd-20-01/
```
postgres=# \connect ejabberd 
You are now connected to database "ejabberd" as user "postgres".
ejabberd=# ALTER TABLE oauth_client RENAME COLUMN client TO client_id;
ERROR:  relation "oauth_client" does not exist
```
Umm, did I skip some upgrade step in ejabberd 19.xx or the blog post is missing the CREATE code block for "If you are using the newer pg.new.sql schema:" like MySQL has?

Hey, I'm right... https://github.com/processone/ejabberd/commit/5d549dca96c643345ba92e67504e67eb1b6b0681#diff-0227fb8e97e9895b7b5252cd1df5b2e3 not my fault 🙂

**Comment by madmalkav** [comment]
Also, the migration information is not linked in https://docs.ejabberd.im/admin/upgrade

**Comment by mremond** [comment]
Maybe related to #3164 ?

**Comment by mremond** [comment]
Blog post was updated, so I think we are good.

**Comment by licaon-kter** [comment]
@mremond And the docs?

**Comment by badlop** [comment]
Upgrade notes added to git... and it's cool the docs page is updated in 10 seconds :) https://docs.ejabberd.im/admin/upgrade
