### ISSUE TITLE
[Docker] Update to 20.01

### ISSUE THREAD

**Issue by Justinzobel** [processone/ejabberd#3160]
If someone can please update the docker image to the current release that would be great, thank you.

**Comment by Adiii717** [comment]
You can find `ejabberd 20.01` [here](https://hub.docker.com/repository/docker/adiii717/ejabberd/general).
I will generate pull request today for Ejabberd docker repository.
```
docker run -it --rm adiii717/ejabberd:20.01
```

**Comment by mremond** [comment]
Hi,

It should be okay now: https://hub.docker.com/layers/ejabberd/ecs/20.01/images/sha256-7675a7e5aef379fb9c9a4d330160f354a16dcb9b84afa51b9bdcc1801a06bb69

Do you confirm all is fine for you ?

**Comment by mremond** [comment]
While I was at it, I also published it on Github Package:
https://github.com/processone/ejabberd/packages/123046

**Comment by Justinzobel** [comment]
Thanks!
