### ISSUE TITLE
Support group unreachable, expired cert

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3163]
`conference.process-one.net
: Peer certificate rejected: certificate has expired; bouncing for 238 seconds`

 (╯°□°）╯︵ ┻━┻

**Comment by mremond** [comment]
Thanks, yes we are aware. We are having some issues to get let’s encrypt to renew them.
We are on it.

**Comment by mremond** [comment]
Hi,

This is now fixed. Sorry about the issue.
