### ISSUE TITLE
ejabberd-20.01.tgz in ProcessOne website is not 20.01 source code

### ISSUE THREAD

**Issue by madmalkav** [processone/ejabberd#3164]
As per title. Discovered because of missing sql_prepared_statements support.

**Comment by mremond** [comment]
Hi,

The source archive on Github should be right: https://github.com/processone/ejabberd/releases/tag/20.01

Possibly, we should link from ProcessOne download page to that one, as it will always reflect accurately the tagged version.

**Comment by f055** [comment]
We now link to the tagged release on GitHub from the ejabberd download page.

**Comment by weiss** [comment]
This means users will need to have GNU Autoconf installed and run `./autogen.sh` first, so [the docs][1] should probably be updated (though the [README file][2] does mention this).  Also, the version number [won't be set correctly][3] when using the repository archive.

I guess most people who compile from source will usually use Git anyway.  Package maintainers will probably have to adjust their packages, though.

[1]: https://docs.ejabberd.im/admin/installation/#install-from-source-code
[2]: https://github.com/processone/ejabberd/blob/20.01/README.md
[3]: https://github.com/processone/ejabberd/blob/20.01/configure.ac#L5

**Comment by mremond** [comment]
The correct package has been uploaded and signed today.

Please, reopen this ticket if there is still an issue with this.
