### ISSUE TITLE
Connect to PostgreSQL via unix socket.

### ISSUE THREAD

**Issue by MrSorcus** [processone/ejabberd#3165]
## Environment

- ejabberd version: 20.01
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.6.2`
- OS: Linux (Archlinux)
- Installed from: repository

## Configuration

```yaml
sql_server: /run/postgresql
```

## Errors

```
2020-02-07 22:06:24.909982+00:00 [warning] <0.332.0>@ejabberd_sql:handle_reconnect/2:471 pgsql connection failed:
** Reason: {init,{error,nxdomain}}
** Retry after: 30 seconds
```

## Bug description

Can't connect to PostgreSQL via unix socket.
`/run/postgresql`, `unix:/run/postgresql`, `localhost:/run/postgresql` - all variants failed.

**Comment by MrSorcus** [comment]
No ideas why does it happens?

**Comment by licaon-kter** [comment]
@MrSorcus it's not supported by Erlang iirc.

**Comment by prefiks** [comment]
Yes, unix socket connections are not supported by pgsql driver, this will require adding code for handling this. For long time erlang didn't even have library code for handling those, and i am even not sure if support for those is still experimental.

**Comment by MrSorcus** [comment]
If changes not so hard, can you tell me, what files i should change to make it working? Thanks.
