### ISSUE TITLE
export/import_piefxis breaks SCRAM passwords

### ISSUE THREAD

**Issue by michaelkuhn** [processone/ejabberd#3167]
## Environment

- ejabberd version: 19.09.1
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.6.2
- OS: Linux (Fedora)
- Installed from: distro package

## Errors from error.log/crash.log

No errors

## Bug description

I used export_piefxis on my old server and import_piefxis on my new server, afterwards no users could log in anymore due to mismatching passwords. It seems the problem is that the password components are base64 encoded in `format_scram_password` but are not decoded in `parse_scram_password` (see https://github.com/processone/ejabberd/blob/master/src/ejabberd_piefxis.erl#L184-L200). Manually decoding the password components within the XML file before importing it fixed the problem.

**Comment by prefiks** [comment]
Hello,

I will take a look at this, and will try to prepare fix (will have to check what data should be produced/accepted, maybe we don't need to have that base64 there).

**Comment by prefiks** [comment]
This issue should be fixed by 66a84b8d2bfcee92485bb9ea2e31f03d282f7b24
