### ISSUE TITLE
EjabberD installation failed on Windows Server 2012 (erl.exe has stopped working)

### ISSUE THREAD

**Issue by swifty94** [processone/ejabberd#3168]
## Environment

- ejabberd version: 20.01
- Erlang version: 
Erlang/OTP 22 [erts-10.5] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Eshell V10.5  (abort with ^G)
- OS: Windows Server 2012 R2 64bit
- Installed from: official website https://www.process-one.net/en/ejabberd/downloads/

Installation hangs and fails on the step of post-install script execution.

Screenshot attached. 
![ejabberd_install_fail](https://user-images.githubusercontent.com/49090543/74235730-591de600-4cd8-11ea-8d7b-3f270510dbdd.png)

Details about the error below:
---------------------------------------------------------------------------------------------------------------------------------
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	erl.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c86ce75
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f83ff
  Exception Code:	c0000005
  Exception Offset:	000000000003c798
  OS Version:	6.3.9600.2.0.0.16.79
  Locale ID:	9226
  Additional Information 1:	e91a
  Additional Information 2:	e91a6bd26807196ed21cb7c46c0b76ec
  Additional Information 3:	8924
  Additional Information 4:	892491a9552acccdeb582488560d0d7b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

--------------------------------------------------------------------------------------------------------------------------------------
I've installed the update for Visual C++ 2013 and Visual C++ Redistributable Package already (judging on MSVCR120.dll mentioning in error code), but no luck. I am facing exactly the same error code and I am not able to install the EjabberD at all.

Please advise.

**Comment by licaon-kter** [comment]
/duplicate https://github.com/processone/ejabberd/issues/3123

**Comment by swifty94** [comment]
> /duplicate #3123

How this can help me, please? You are referring to a similar issue, indeed, but there is no solution there!! I need the exact solution, apart from installing Visual C++ Redistributable Package.

**Comment by licaon-kter** [comment]
Close this and add your voice there, what did you try?

**Comment by swifty94** [comment]
> Close this and add your voice there, what did you try?

seriously? so you wish me to simply copy and paste all the stuff mentioned here to another ticket + asking me "what did you try" instead of simply READING what is written here?
actually, it is not funny. I've already mentioned what was done in order to solve the issue and it seems meaningless for me to copy my issue from here to the one you've mentioned above because:
1. how actually it will help to resolve it?
2. the issue you've mentioned on Dec 24, 2019, and don't see any positive results there.

**Comment by weiss** [comment]
> how actually it will help to resolve it?

Do you really need an explanation of how it helps to have all information regarding a given issue within a single ticket rather than having things scattered across multiple open issues in a bug tricker?

> the issue you've mentioned on Dec 24, 2019, and don't see any positive results there.

So you assume having a second open issue speeds things up?

**Comment by swifty94** [comment]
> Do you really need an explanation of how it helps to have all information regarding a given issue within a single ticket rather than having things scattered across multiple open issues in a bug tracker?
> My humble opinion - you can keep all similar open issues in your ticket/BT system in order to track their total number, to understand whether there are any differences between the similar cases,  analyzing the whole picture and prioritizing the items in case it's necessary. However, I can see that you have another system/workflow so okay, I can understand it. Sorry, but it is just a bit weird for me, however, if it will help to resolve this issue - I'll copy the details I have to the issue opened previously.
> So you assume having a second open issue speeds things up?
> In reply above I've described why I've posted an issue separately. As I said, I'll share the details.

**Comment by swifty94** [comment]
> > Do you really need an explanation of how it helps to have all information regarding a given issue within a single ticket rather than having things scattered across multiple open issues in a bug tracker?
> 
> My humble opinion - you can keep all similar open issues in your ticket/BT system in order to track their total number, to understand whether there are any differences between the similar cases,  analyzing the whole picture and prioritizing the items in case it's necessary. However, I can see that you have another system/workflow so okay, I can understand it. Sorry, but it is just a bit weird for me, however, if it will help to resolve this issue - I'll copy the details I have to the issue opened previously.
> 
> > So you assume having a second open issue speeds things up?
> 
> In reply above I've described why I've posted an issue separately. As I said, I'll share the details.

**Comment by weiss** [comment]
Thanks.
