### ISSUE TITLE
MucSub doesnt send affiliation changes while target user is subscribed to room

### ISSUE THREAD

**Issue by NtTestAlert** [processone/ejabberd#3172]
## Environment

- ejabberd version: 20.01
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1`
- OS: Linux (Debian)
- Installed from: official deb/rpm

## Bug description

- set up a member only room `test` with owner `admin@test.ing` and members `user1@test.ing` `user2@test.ing`
- `admin@test.ing` joins `test@conference.test.ing`
- `user1@test.ing` subscribes to all mucsub events for `test@conference.test.ing`
- `user2@test.ing` subscribes to all mucsub events ...
  > `user1` receives subscribe event
  > `admin@test.ing` sets affiliation for `user2@test.ing` to `admin`
  > `user1` **receives no events.**
- `user2@test.ing` unsubscribes from mucsub ...
  > `user1` receives unsubscribe event
  > `admin@test.ing` sets affiliation for `user2@test.ing` to `member`
  > `user1` receives affiliation event
  > `admin@test.ing` sets affiliation for `user2@test.ing` to `admin`
  > `user1` receives affiliation event

**Comment by prefiks** [comment]
Hello,

This is somewhat by design, if you are in room, no mucsub event will be sent to you, you will receive normal muc messages/notifications in that case.

**Comment by NtTestAlert** [comment]
> This is somewhat by design, if you are in room, no mucsub event will be sent to you, you will receive normal muc messages/notifications in that case.

The events about `user2`'s affiliation changes are not being sent to `user1` - who is not in the room, just subscribed.
They are sent as long as `user2` is not subscribed to the room. 
The only one present in the room at any time is `admin`.

**Comment by badlop** [comment]
Right. That is done in the function maybe_send_affilitation:
https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L2604

As you noticed, if the account subject to the affiliation change is occupant _or subscriber_, then notification of that affiliation change is not explicitely sent by that code, instead it's expected to be sent with a presence.

That is this way since years ago: https://github.com/processone/ejabberd/commit/3803a8de3c2ad70ef967bb6d7a47f20fcf82f859#diff-9e8ad34ba1ce71132f4de59d3e228997R2643

The change you propose is this one:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 4d8816e97..7b67cb9ba 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -2603,7 +2603,7 @@ send_nick_changing(JID, OldNick, StateData,
 -spec maybe_send_affiliation(jid(), affiliation(), state()) -> ok.
 maybe_send_affiliation(JID, Affiliation, StateData) ->
     LJID = jid:tolower(JID),
-    Users = get_users_and_subscribers(StateData),
+    Users = StateData#state.users,
     IsOccupant = case LJID of
 		     {LUser, LServer, <<"">>} ->
 			 #{} /= maps:filter(

```

**Comment by NtTestAlert** [comment]
A presence update is NOT sent either though, no notification is sent at all. This kind of beats the entire purpose of MUCSub. Currently I am left to sending a custom message to the chatroom after modifying affiliation status informing other clients that the affiliation has in fact changed and they need to resync manually with the room.

I don't understand however why would it be sent as a presence? Subscription to a room and presence in it are two different things. Users who are subscribed are not visible to clients who use regular MUC and are in the room as "present". Sending a presence there might even be a bug to those clients, since if he then unsubscribes the room no presence unavailable is sent either so he will stay in the room indefinitely.

**Comment by badlop** [comment]
OK. And did you try the small change that I mentioned earlier? Does it solve the problem?

**Comment by prefiks** [comment]
There may be another thing in play there, is that room set to anonymous?

Looks like we only send affiliation changes to moderators when room is set to anonymous, as affiliation changes contains jids in them, and having anonymous flags prevents showing real jids to normal members.
