### ISSUE TITLE
register_web error "Host not served"

### ISSUE THREAD

**Issue by ChaosKid42** [processone/ejabberd#3173]
## Environment

- ejabberd version: 20.01
- Official Docker Image

## Bug description

I have set up an ejabberd serving the domain `mydomain.tld`. The hosts DNS entry is `xmpp.mydomain.tld`.

Trying to access register_web by https://xmpp.mydomain.tld/register/ always fails with `Host not served`. It works if I create an DNS alias and access it via https://mydomain.tld/register/.

It seems to be a similar issue that was solved by https://github.com/processone/ejabberd/commit/8d571adca845285aa4928ada25d31cdbc32ef0a0.

**Comment by badlop** [comment]
Right, this is intentional. The Register, Change and Unregister pages contain formularies that request account information, and the Server field is hardcoded to the Host defined in the URL. This means that the form can only be used to modify accounts in the corresponding vhost.

**Comment by ChaosKid42** [comment]
But it's not true that it's hardcoded. There is even a field in the web form that allows to enter the host I want to register for.

And: It used to work with differing hostnames a few versions back ...

**Comment by badlop** [comment]
Ah, right. It was not hardcoded: it was pre-filled, and available to be edited. I've changed that.
