### ISSUE TITLE
Limit on mqtt

### ISSUE THREAD

**Issue by a-jahanshahlo** [processone/ejabberd#3174]
there is any way to limit messages for publisher per/minute? on MQTT?

**Comment by prefiks** [comment]
No there is no options that would allow to setting limits like that currently.

**Comment by a-jahanshahlo** [comment]
in fact i want create an app like uber to tracking cars but it's important to prevent send huge message to server ! have you any suggestion? I don't want to use firebase.

**Comment by mremond** [comment]
I guess, as the feature does not exist yet, it is to develop it 👍
