### ISSUE TITLE
Messages are dropped silently for no apparent reason.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [processone/ejabberd#3176]
## Environment

- ejabberd version: 20.01
- OS: Linux (Debian buster)
- Installed from: buster-backports

## Bug description

This started recently, I noticed it about 2 weeks ago.
Bob sent a message sent from his iphone (chatsecure, he also has chatsecure on ipad) Alice's gajim. Alice hasn't received this message.
Daria sent a message from her Conversations (she has only one client) to Alice's gajim. Same.
Gajim was switched to Dino, because I thought gajim is the culprit (it sometimes cannot connect unless restarted), but the same happened: Daria sent a message from Conversations to Alice's Dino (gajim wasn't running at this time), but Alice didn't receive it.
In all cases only one message wasn't delivered, later and previous messages were delivered properly.
All of them use OMEMO and creep.im public server which was solid until this. This is not my server, XMPP and email contact to admin: a@creep.im

What is failing here?

**Comment by mremond** [comment]
You need to ensure you are using a message reliability mechanism on both the client and the server) like for example stream management: https://xmpp.org/extensions/xep-0198.html

**Comment by gerg5c42g542g2c54g52c** [comment]
@mremond Stream Management is supported by all the clients and [the server](https://compliance.conversations.im/server/creep.im/) in question.

**Comment by mremond** [comment]
Then, I suggest you put your server in debug mode to analyse the reason of the message loss (check if that client had stream management enabled, etc).
