### ISSUE TITLE
 can't find include lib "kernel/include/logger.hrl"

### ISSUE THREAD

**Issue by relravtech** [processone/ejabberd#3178]
## Environment

- ejabberd version: 20.02
- Erlang version: 9.2
- OS: Linux (Ubuntu)
- Installed from: source

## Errors from error.log/crash.log

No errors

## Bug description

When I try to run `ejabberdctl install_module mod_name` I get error about the 
`-include("logger.hrl")` and the message is the message I put in the title:  `/usr/local/lib/ejabberd-20.02.6/include/logger.hrl:40: can't find include lib "kernel/include/logger.hrl"`.
The file `error.log` doesn't say anything about this error.

**Comment by licaon-kter** [comment]
Is that module updated?

**Comment by prefiks** [comment]
Looks like some flags aren't passed when that command compiles module, so i uses code paths that works only on newer erlang version. I will try to prepare fix for this.

**Comment by prefiks** [comment]
This should be fixed by 151b818af4d01b8afd979d43d1334be423560419
