### ISSUE TITLE
Server Component not receiving all MUC messages from ejabberd

### ISSUE THREAD

**Issue by PasqualePuzio** [processone/ejabberd#3179]
## Environment

- ejabberd version: 18.03
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 9.3
- OS: Linux (Ubuntu 16.04)
- Installed from: official deb/rpm

## Configuration:

```loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100
hosts:
  - "testjabber.fantamaster.it"
define_macro:
   'CERTFILE': "/opt/ejabberd/conf/cert.pem"
   'TLSOPTS':
     - "no_sslv2"
     - "no_sslv3"
listen:
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    certfile: 'CERTFILE'
    protocol_options: 'TLSOPTS'
    starttls_required: true
    zlib: true
    max_stanza_size: 65536
    shaper: none
    access: c2s
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    web_admin: true
    http_bind: true
    captcha: false
    certfile: 'CERTFILE'
    tls: true
  
  -
    port: 5233
    ip: "::"
    module: ejabberd_service
    password: "secret"
    access: all
  
auth_method: internal
host_config:
  "testjabber.fantamaster.it":
     auth_method:
       - external
     extauth_program: "python /opt/ejabberd/my_authentication.py"
     extauth_instances: 8
     auth_use_cache: false
shaper:
  normal: 1000
  fast: 100000
max_fsm_queue: 1000
acl:
  admin:
    user:
      - "localadmin@testjabber.fantamaster.it"
  local:
    user_regexp: ""
  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - fast
  s2s_shaper: fast
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"
  
language: "it"
modules:
  mod_admin_extra: {}
  mod_disco:
     extra_domains:
         - "testrooms.testjabber.fantamaster.it"
  mod_muc:
    host: "testrooms.testjabber.fantamaster.it"
    history_size: 1000
    max_users: 100000
    max_user_conferences: 1000
    default_room_options:
      mam: false
      max_users: 1000000
      members_by_default: true
      members_only: false
      password_protected: false
      persistent: true
      public: true
      moderated: false
      anonymous: false
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 7200
    c2s_max_auth_failures: 50
allow_contrib_modules: true
```

## Errors from error.log/crash.log

No errors

## Bug description

We want to build a simple server component for ejabberd which receives all messages sent to MUC rooms (we have many rooms and new ones are being created all the time) and, after filtering some of these messages, performs some operations (e.g. notify an external service via a HTTP request).

We don't want our server component to act like a bot, so we don't want it to reply to messages or things like that, we just want it to receive copies of all messages in order to process some of them.

To do so, we have created a server component with sleekxmpp following the tutorial available here: https://sleekxmpp.readthedocs.io/en/latest/getting_started/component.html

The problem is that the component seems to receive only some of the messages.
Also, we are observing a weird behavior: message delivery seems to be "exclusive", meaning that a message is delivered either to clients connected to the room or to the server component. In other words, some messages are delivered to the server component, and the others are delivered to clients as usual.

We have tried several values for the component JID (notifications.testrooms.testjabber.fantamaster.it, testrooms.testjabber.fantamaster.it, notifications.testjabber.fantamaster.it, notifications.fantamaster.it) but we always end up with the same problem.

Do you have any idea what might cause this weird behavior? Is there any particular plugin or module that should be enabled/disabled?

Of course, we have enabled debug logs on both sleekxmpp and ejabberd, but we don't see any errors, it's just that some messages are missing.

It looks like there is some routing issue at our jabber server, for some reason messages are not correctly delivered, we can't figure it out.

Here's the server component code:

```import sys
import logging
import slixmpp
from slixmpp.componentxmpp import ComponentXMPP

class NotificationsComponent(ComponentXMPP):

        def __init__(self):
                ComponentXMPP.__init__(self, "notifications.testrooms.testjabber.fantamaster.it", "secret", "testjabber.fantamaster.it", 5233)
                # add handler
                self.add_event_handler("message", self.message)
                self.add_event_handler("groupchat_message", self.message)

        def message(self, msg):
                if msg['type'] == 'groupchat':
                        print('Received group chat message')
                        print(msg)
                else:
                        print('Received another message')

if __name__ == '__main__':

        logging.basicConfig(level=logging.DEBUG,format='%(levelname)-8s %(message)s')

        xmpp = NotificationsComponent()
        xmpp.register_plugin('xep_0030') # Service Discovery
        xmpp.register_plugin('xep_0004') # Data Forms
        xmpp.register_plugin('xep_0060') # PubSub
        xmpp.register_plugin('xep_0199') # XMPP Ping
        xmpp.register_plugin('xep_0045') # MUC`

        # Connect to the XMPP server and start processing XMPP stanzas.
        xmpp.connect()
        xmpp.process()
```

**Comment by mremond** [comment]
I do not understand what you which to do. If you write a component to implement chat rooms, well, it should fully implement the chat room protocol. I do not think you can bridge the chatroom protocol with a component.

**Comment by PasqualePuzio** [comment]
Hi @mremond , probably I misunderstood the purpose of external components. I thought that by writing an external component I could have received "copies" of all events occurring within ejabberd, but I was wrong.

I managed to achieve the same result by using a module called "mod_post_log" which sends an http request for every message sent by a user.

**Comment by mremond** [comment]
Component are used to develop new services, like develop your own MUC. The client talks to the component and can reply to the client. With some new XEP it can interact with other services, but nothing has been defined to receive copy of MUC messages indeed.

Thanks for the update !
