### ISSUE TITLE
Module to prevent Message loss.

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3180]
Hi,
I am facing an issue where client disconnects from the server but it's still showing online and the messages sent during this interval by another client, they simply lost sometimes(i have enabled Stream Management so pretty much is covered in it) .

Since i feel there will always be a window when the messages can be lost in some circumstances, I decided to do an update in OFFLINE STORAGE module of the server . I want to delete messages in offline storage when i receive some kind of acknowlegdement . 

where i can handle this functionality . And would be very helpful if i get to know where the sending of these messges and then deleting them is handled .

**Comment by weiss** [comment]
> i feel there will always be a window when the messages can be lost in some circumstances

Just use [MAM][1] to address this issue.  (And/or set the [mod_stream_mgmt][2] option `resend_on_timeout: if_offline`.  There's an old [FAQ entry][3] that gives additional explanations on this topic.)

[1]: https://xmpp.org/extensions/xep-0313.html
[2]: https://docs.ejabberd.im/admin/configuration/#mod-stream-mgmt
[3]: https://www.ejabberd.im/faq/tcp/

**Comment by licaon-kter** [comment]
You've activated MAM and Carbons too, right?
