### ISSUE TITLE
Ejabberd threw error when compiled with mongodb-erlang. Does ejabberd use poolboy?

### ISSUE THREAD

**Issue by byteshiva** [processone/ejabberd#3185]
Many people have faced compilation error when compiling mongodb-erlang along with ejabberd. The author of mongodb-erlang 
Feels it might be with poolboy library.

My question is does Ejabberd still use poolboy library

Ref:

Can you please check if eJabberd is using poolboy?
because my driver is using it's fork and it can be a problem.

_Originally posted by @comtihon in https://github.com/comtihon/mongodb-erlang/issues/221#issuecomment-598113480_

**Comment by prefiks** [comment]
Ejabberd doesn't use poolboy library

**Comment by byteshiva** [comment]
> Ejabberd doesn't use poolboy library

When did they decide not use poolboy, what was the decision for not using poolboy

**Comment by prefiks** [comment]
I don't think we ever used it, at least i don't remember seeing it used.

**Comment by byteshiva** [comment]
> I don't think we ever used it, at least i don't remember seeing it used.

I see the mongodb-erlang author mentioning that he has taken a fork of Ejabberd that uses poolboy. Also I see the commits on his repo (mongodb-erlang) goes way back to 4years.

**Comment by mremond** [comment]
I suggest to use directly ejabberd and not a fork to work without poolboy, as ejabberd does not use it.

**Comment by comtihon** [comment]
yes, I took poolboy's fork, not ejabberd itself.

**Comment by mremond** [comment]
Well, I do not understand your question. You asked if ejabberd used poolboy and it does not.
