### ISSUE TITLE
Deprecation of `mod_http_upload` `service_url`

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#3187]
## Environment

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/20.02/ejabberd-20.02-windows.exe

Windows 10 Pro x64 Version 1909

## Description

I'm using `mod_http_upload` with `service_url` option. On ejabberd start, this deprecation message is written into the log:
```
2020-03-14 12:04:21.041 [warning] <0.105.0>@ejabberd_config_transformer:warn_deprecated_option:530 Option 'service_url' is deprecated. Use option 'external_secret' instead.
```
I don't find a deprecation hint in the documentation: https://docs.ejabberd.im/admin/configuration/#mod-http-upload

Please remove the deprecation log entry or mark the `service_url` option as deprecated in the documentation.

**Comment by licaon-kter** [comment]
Open an issue in docs repo then.

**Comment by Andy-2639** [comment]
https://github.com/processone/docs.ejabberd.im/issues/85

**Comment by badlop** [comment]
Right, thanks for reporting. I've updated the docs page.
