### ISSUE TITLE
CRASH 20.02, ejabberd_http_sup

### ISSUE THREAD

**Issue by scottcc** [processone/ejabberd#3190]
## Environment

- ejabberd version: 20.02
- Erlang version: `erl +V` -> Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.6.4
- OS: Mac OSX
- Installed from: 'brew install ejabberd'

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: debug  (instructions still say to use numbers, but OTP/existing now with names)
...
```

## Errors from error.log/crash.log

==> ./error.log <==
2020-03-16 21:14:10.236556+00:00 [error] <0.2147.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.2147.0>
    registered_name: []
    exception error: bad argument
      in function  maps:from_list/1
         called as maps:from_list([html])
      in call from ejabberd_http:apply_custom_headers/2 (src/ejabberd_http.erl, line 860)
      in call from ejabberd_http:process_request/1 (src/ejabberd_http.erl, line 495)
      in call from ejabberd_http:process_header/2 (src/ejabberd_http.erl, line 287)
      in call from ejabberd_http:parse_headers/1 (src/ejabberd_http.erl, line 212)
      in call from ejabberd_http:init/3 (src/ejabberd_http.erl, line 142)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.114.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1903.0>,#Port<0.193>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 32055
  neighbours:

## Bug description

Able to start up ejabberd by either `ejabberdctl foreground` or `ejabberdctl start`, but attempting to hit the web admin (ie, https://some-server.domain.com:5280/admin/) correctly asks for the password. We have previously used `ejabberdctl register USER FQDN PASS`, where the last three are actually set to something. This then matches the `acl:` entry, subentry `admin:` then `user:` with an entry like `USER@FQDN`.

**Comment by badlop** [comment]
Yes, that problem was introduced in ejabberd 20.02, and it's fixed in a recent git commit, specifically in 00abf5d. There isn't yet any release with the fix. Until the next version is release, you can either get ejabberd from git, or rollback to ejabberd 20.01

**Comment by scottcc** [comment]
thanks @badlop. I'll dig out how to move homebrew to a commit again.

**Comment by scottcc** [comment]
FYI, for others (or more likely, just future me) I was able to resolve this using git, with `brew install autoconf automaker's && brew install --HEAD ejabberd`
