### ISSUE TITLE
After start the ejabberd, cannot access admin dashboard.

### ISSUE THREAD

**Issue by plutonem-mobile** [processone/ejabberd#3191]
Hi, guys.

i just download ejabberd for windows and install it successfully. when i click the shortcut of start ejabberd and it direct me to a web page says successful also. but after this, when i follow the tutorial to open localhost:5280/admin it always return error page like following:

![image](https://user-images.githubusercontent.com/8728579/76861750-08ca1300-6898-11ea-98bd-21a92cd65b3b.png)

i tried so many times and i also try to open it in localhost:5443/admin, still got error.

wield

**Comment by plutonem-mobile** [comment]
i am pretty sure i am using the corrent username(administrator1@localhost) and correct password

**Comment by plutonem-mobile** [comment]
and in the install.log file, i see it tells me that User administrator1@localhost has been registered successfully

**Comment by licaon-kter** [comment]
Can you use `.../admin/` instead?

**Comment by plutonem-mobile** [comment]
do you mean enter url like this? http://localhost:5280/.../admin/

everytime i tried to enter the admin, it just returns me err_empty_response

**Comment by plutonem-mobile** [comment]
###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - "localhost"

loglevel: 5
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "C:/ProgramData/ejabberd/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

ca_file: "C:/ProgramData/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
  admin:
    user:
      - "administrator2@localhost"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
   contact: "mailto:admin@localhost"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8



this is my ejabberd.yml file

**Comment by licaon-kter** [comment]
Not with `...` :facepalm:

**Comment by plutonem-mobile** [comment]
:facepalm: i am not sure what's you mean about ...

can you specify it more clealy?

**Comment by plutonem-mobile** [comment]
still in trouble now, is it because my operating system is windows 10??   incompatibility??

**Comment by plutonem-mobile** [comment]
i just followed the guide in https://docs.ejabberd.im/admin/installation/ about windows and do it again, still got err_empty_response when trying to enter admin panel

i am sure i have followed everything this tutorial has told and did not change anything about ejabberd.yml configuration file

**Comment by licaon-kter** [comment]
`http://localhost:5280/admin/` or `https://localhost:5443/admin/`

**Comment by plutonem-mobile** [comment]
i tried it may be like ten times. and i check the file it appears like all is normal. so i really dont know why.

![image](https://user-images.githubusercontent.com/8728579/76887732-a71c9f80-68bd-11ea-8007-95aff50416f1.png)

this is the part of listen port

**Comment by plutonem-mobile** [comment]
i can type the username and password in the coming edittext box. but after i type the correct information and got ERR_EMPTY_RESPONSE.

this almost drives me crazy

**Comment by plutonem-mobile** [comment]
after i switch to centos system, encountering the same problem. really wish someone could help me with this issue

**Comment by badlop** [comment]
Did you install ejabberd 20.02? There was a problem introduced in ejabberd 20.02 that breaks WebAdmin and other HTTP services in ejabberd.

It is fixed in a recent git commit, specifically in 00abf5d, but there isn't yet any release with the fix.

Until the next version is release, you can either get ejabberd from git, or rollback to ejabberd 20.01

**Comment by plutonem-mobile** [comment]
Thank you, yeah, the version 20.02 is exactly what i installs, may be that's the main reason why.

i will give it a try to swich to another version later.

**Comment by plutonem-mobile** [comment]
Perfect! that's exactly the reason why before crashed.

after i switch to 20.01. everything goes back to work.

![5aa7319e8fb51a810f521fa090d3303](https://user-images.githubusercontent.com/8728579/76937214-5a71ac80-692f-11ea-8859-9ccf98200c01.png)

thank you guys.

**Comment by mremond** [comment]
We are preparing a fix release soon. Using master or 20.01 if you need to use the console, and it should be fine.

**Comment by Neustradamus** [comment]
It is possible to create a 20.03.1?
Linked to:
- https://github.com/processone/ejabberd/issues/3200
