### ISSUE TITLE
Unable to access ejabberd admin portal in localhost

### ISSUE THREAD

**Issue by byteshiva** [processone/ejabberd#3193]
## Environment

- ejabberd version: 20.02
- Erlang version: `erl +V`
- OS: Windows
- Installed from:  official binary installer 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log
```
2020-03-18 19:27:04 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {badarg,[{maps,from_list,[[html]],[]},{ejabberd_http,apply_cust
om_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_http,process
_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http,process_h
eader,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_header
s,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3,[{file,"s
rc/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib
.erl"},{line,249}]}]}
     Offender:   [{pid,<0.647.0>},{id,undefined},{mfargs,{ejabberd_http,start_li
nk,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]

2020-03-18 19:27:04 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.648.0>
    registered_name: []
    exception error: bad argument: [{maps,from_list,[[html]],[]},{ejabberd_http,
apply_custom_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_ht
tp,process_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http
,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,pa
rse_headers,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3
,[{file,"src/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file
,"proc_lib.erl"},{line,249}]}]
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.105.0>]
    message_queue_len: 0
    messages: []
    links: [<0.543.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2777
  neighbours:
```
## Bug description

I'm unable to login using admin credentials it fails when I put admin@computer and password.
http://localhost:5443/admin
http://localhost:5280/admin

ejabberd.yml and ejabberdctl.cfg available at 
https://gist.github.com/byteshiva/4eb204542ca4c563366bc0a6c744edb8

**Comment by badlop** [comment]
> ejabberd version: 18.09

Are you sure you installed ejaberd 18.09?

The error message that you get seems produced by a bug that was introduced in ejabberd 20.02, and it's fixed in a recent git commit, specifically in 00abf5d.

There isn't yet any release with the fix. Until the next version is release, you can either get ejabberd from git. Or an easier solution: uninstall 20.02 and install ejabberd 20.01.

**Comment by byteshiva** [comment]
> > ejabberd version: 18.09
> 
> Are you sure you installed ejaberd 18.09?
> 
> The error message that you get seems produced by a bug that was introduced in ejabberd 20.02, and it's fixed in a recent git commit, specifically in [00abf5d](https://github.com/processone/ejabberd/commit/00abf5d42c9b9c979b7ac69758a8f6745744f929).
> 
> There isn't yet any release with the fix. Until the next version is release, you can either get ejabberd from git. Or an easier solution: uninstall 20.02 and install ejabberd 20.01.

Thanks @badlop 
its `20.02` I'll uninstall 20.02 and install 20.01

**Comment by cfabio** [comment]
I have the same issue, *solved* by removing ejabberd 20.02 and reinstalling 20.01.  

@badlop what's the point of releasing a new version of the software if even BASIC functionalities like WEB admin are broken?  
At this point Ejabberd "versions" should just be considered random milestones.

**Comment by weiss** [comment]
What's the point in posting completely non-constructive rants about bugs in software you get for free?  At this point your issue tracker "contributions" should just be considered random gibberish.

**Comment by mremond** [comment]
Personally, I am never using the web interface and most of the people I know never use it as well, but use the command-line tools.
Anyway, the fix is already in master since a while and a new version will be release next week, with a couple of other fixes and improvements.

**Comment by badlop** [comment]
BTW, since now there are Common Test cases covering basic web admin usage: https://github.com/processone/ejabberd/commit/a2d1ffffe6f1068c6417006dfe7be3fab7d003e6
