### ISSUE TITLE
Tkabber throws Server hasnt provided SASL authentication

### ISSUE THREAD

**Issue by byteshiva** [processone/ejabberd#3194]
## Environment

- ejabberd version: 20.01
- Erlang version: `erl +V`
- OS: Windows
- Installed from: official binary installer 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
I'm unable to login using tkabber in localhost, throws "Server hasnt provided SASL authentication" 

![image](https://user-images.githubusercontent.com/10637299/76972492-aa169f00-6954-11ea-8560-fd691bab5a38.png)

**Comment by licaon-kter** [comment]
Upload the config to https://gist.github.com

**Comment by byteshiva** [comment]
> Upload the config to https://gist.github.com

Here it is
https://gist.github.com/byteshiva/4eb204542ca4c563366bc0a6c744edb8

**Comment by badlop** [comment]
I can reproduce that error message in Tkabber Login log. In those cases, Tkabber's XML Raw window shows:

```
<!-- 14:56:02.986 IN (::xmpp::1, user1@localhost/tka1) -->
<stream:stream  id='14521987283526703278' version='1.0' xml:lang='es' to='user1@localhost' from='localhost'>

<!-- 14:56:02.987 IN (::xmpp::1, user1@localhost/tka1) -->
<stream:features>
  <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
    <required/>
  </starttls>
</stream:features>
```

Then, in the Login window, I see that I have (Disclaimer: I have Tkabber in my language, so my translation to english may not be precise):
```
Authentication tab:
[v] Allow plain text auth mechanism
[v] SASL auth
and in the Cypher and compression:
[v] Plain text
[] Compression
[] Cipher (STARTTLS)
[] Cipher (old SSL)
```

If I change from Plaintext to Cypher (STARTTLS), the error goes away.
