### ISSUE TITLE
Ejabberd Windows installer Unattended mode installation is failing

### ISSUE THREAD

**Issue by kpsbhuvi** [processone/ejabberd#3199]
## Environment

- ejabberd version: 20.02
- OS: Windows Server 2019
- Installed from:  official binary installer 

## Bug description

Not able to install Ejabberd windows with unattended mode using options file.
Installation stuck with 'set up' pop up says Installing-executing final installation script.
Installation not at all completing.

**Comment by licaon-kter** [comment]
Does older one work?

**Comment by kpsbhuvi** [comment]
I am trying with 20.02 only. Older one not tried.

**Comment by mremond** [comment]
You should share the installer logs.
