### ISSUE TITLE
`ejabberdctl start` creates erl_crash_dump in the log directory

### ISSUE THREAD

**Issue by leoliu** [processone/ejabberd#320]
With ejabberd built from the master branch and as suggested by the title. The first invokation of `ejabberdctl start` stats the server, the second and the rest try to start a new node under `nonode@nohost` and crashed.

`Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
System version: Erlang/OTP 17 [DEVELOPMENT] [erts-6.2] [source-1aa1a4f] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:10] [hipe] [kernel-poll:true]`

**Comment by mremond** [comment]
If I understand well, it seems it is expected. Per design, you can only start one node per server, without tweaking the ejabberdctl script.
