### ISSUE TITLE
Broken links in virtual host page body

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3200]
In ejabberd version 20.03, more concretely since commit https://github.com/processone/ejabberd/commit/e9d1201ea813d19c6c7403c7aa883e314991d664 for the ticket https://github.com/processone/ejabberd/issues/3177 ,  there are some broken links in the webadmin. 

To reach them, go to -> Virtual Hosts -> then some host. The links in the page body are broken.

**Comment by prefiks** [comment]
In commit 5ec214386e3141e000fbcfaa53928c48f132c8fe i added code that will generate redirect for urls that don't end with /. That with e9d1201ea813d19c6c7403c7aa883e314991d664 reverted do make it works again even when passing url without /

**Comment by badlop** [comment]
Great! Your commit implements the feature, it's more clean, and doesn't have the drawbacks of my implementation :hugs:

**Comment by Neustradamus** [comment]
It is possible to create a 20.03.1?
