### ISSUE TITLE
Ejabberd windows uninstaller not deleting c:/ProgramData/ejabberd

### ISSUE THREAD

**Issue by byteshiva** [processone/ejabberd#3201]
## Environment

- ejabberd version: 20.03
- Erlang version: `erl +V`
- OS: Windows
- Installed from: official binary installer 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Ejabberd Windows Uninstaller not deleting old ProgramData/ Ejabberd files.  If I install new version of ejabberd say from 20.01 to 20.03, its taking old mnesia database configuration like users etc. And I dont want to manually delete ProgramData/ejabberd to fix this issue.

Expected:
The uninstaller should remove all the data corresponding to that particular ejabberd.

Please, give us a precise description (what does not work, what is expected, etc.)

![image](https://user-images.githubusercontent.com/10637299/77765215-ee482480-7063-11ea-9340-23902f8c2207.png)

**Comment by licaon-kter** [comment]
Users are stored there too? I'd find that bad that the installer would uninstall user data.

**Comment by byteshiva** [comment]
> Users are stored there too? I'd find that bad that the installer would uninstall user data.

In my case, I had installed ejabberd 20.01 and registered three users.

Now I uninstalled 20.01 and installed 20.03, During installation I gave new password for admin.

And I tried login with new admin password, it didn't work, I gave the old password of 20.01 version, it worked. Once after login I see three users but once I click it it's says 'unknown'.

I feel old mnesia data other configuration are not cleaned up.

**Comment by byteshiva** [comment]
> Users are stored there too? I'd find that bad that the installer would uninstall user data.

I'd find that bad that the installer would uninstall user data
-- then why is the latest installer not  updating the configuration file and mnesia db?

**Comment by licaon-kter** [comment]
That's not the point of the installer, user data is created/modified when running the daemon.

But I agree that a new dialogue could be nice to popup on uninstall asking if the user wants that deleted too.

**Comment by byteshiva** [comment]
> That's not the point of the installer, user data is created/modified when running the daemon.


> But I agree that a new dialogue could be nice to popup on uninstall asking if the user wants that deleted too.
-- I think that would be convenient,

**Comment by mremond** [comment]
I do not think the installer allow adding such pop up to prompt for deletion of data.
The principle is safety, the goal is not to delete data accidentally.
