### ISSUE TITLE
Query to find multiple user at once.

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3203]
Hi Guys,
I need to implement the user search in the user table from the ejabberd DB through an HTTP request .
So far i have done it running the query 
```
ejabberd_sql:sql_query(
  LServer,
  ?SQL("select @(username)s from users"
        "where username in %(LUser)s and %(LServer)H"))
```
Where LUser and LServer are the username and domain of the respective user . Client is sending me a list of usernames (around havng 2000+ usernames) . So for every user this query traverse the whole DB (i.e. For 2000, It search the same table 2000 times) . I want to run a query of this type
```
SELECT * FROM users WHERE username IN [userList] AND server=Lserver;
```
I know this is only for the Bugs and features but i tried to write the query and also search for it online but no success. 
It will be very helpful and kind if you guys help me or guide me where i can learn to make these queries for ejabberd .
Thanks

**Comment by badlop** [comment]
Something like this?
https://www.dofactory.com/sql/where-in
https://stackoverflow.com/questions/5803472/sql-where-id-in-id1-id2-idn

**Comment by shaggi7** [comment]
@badlop 
Like the first query (SELECT * FROM TABLE WHERE ID IN (id1, id2, ..., idn)) in the second link.

**Comment by badlop** [comment]
See example code in https://github.com/processone/ejabberd/blob/master/src/ejabberd_auth_sql.erl#L247
Notice also that this example call runs only with a list of 100 or less users.

This function:
```erlang
get_usernames(LServer, LUsers) ->
    ejabberd_sql:sql_query(
      LServer,
      ?SQL("select @(username)s from users "
	    "where username in %(LUsers)ls")).
```

calling like this:
```erlang
    LServer = <<"localhost">>,
    LUsers = [<<"user1">>, <<"user2">>, <<"user3">>],
    Res = get_usernames(LServer, LUsers),
```

returns:
`{selected,[{<<"user1">>},{<<"user2">>},{<<"user3">>}]}`
