### ISSUE TITLE
The stop_ejabberd test case fails due to missing stream close stanza

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3204]
Since commit https://github.com/processone/ejabberd/commit/7caec56e967ceae8fc773ba1ceec18fa08d1b8a3 the _stop_ejabberd_ case fails always with Erlang 19.3, and many times (not always!) with Erlang 20.2: https://travis-ci.org/github/processone/ejabberd/builds

The problem appears when ejabberd is stopping and it closes clients sessions. On the other hand, the client sessions are always correctly closed if they are manually closed with
`ejabberdctl kick_session user1 localhost tka1 asd`

How to reproduce the problem: start ejabberd, login with a client, then stop ejabberd with any method of
```
ejabberdctl stop
ejabberdctl stop_kindly 2 asd
or application:stop(ejabberd).
```

The client should receive this, but sometimes it only receives the stream:error stanza, not the `</stream:stream>`:
```
<stream:error>
  <system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>
</stream:error>
</stream:stream>
```

In fact, this problematic behaviour can be reproduced in previous ejabberd releases manually in most cases, this indicates that the problem was not introduced in that recent commit: the problem is there since some time ago, at least since 19.09.1 (the oldest that I tested).

Possible solutions that I can think:
 - If this is considered a big problem, investigate the root of this problem
 - If this is not a big problem, or in fact is expected due to ejabberd shutdown optimizations, then modify the stop_ejabberd case to not expect `</stream:stream>`

**Comment by prefiks** [comment]
I am reworking how session stopping is handled, and it may  fix this as well, at least i don't see that error here.

Some messages sent to c2s processes go missing when process is terminating, possible that this is reason for that.

This happen because xmpp_stream_in calling terminate() early, instead of relying on p1_server doing that, after it is able to do redeliver queued messages.

**Comment by prefiks** [comment]
I commited my changes in 1bd560f3f25d0a644bac3d06904ca97e20a6f7d9, i don't get those errors both on R19 and R22 with this, so possibly this is fixed?

**Comment by prefiks** [comment]
Ok, travis still show that error, i will probably change that test to handle both situation, i don't think this is big problem to get that on server stop.

**Comment by prefiks** [comment]
I commited that change and it seems it helped travis.
