### ISSUE TITLE
ejabberd-20.01 returns invalid mod_http_upload put_url

### ISSUE THREAD

**Issue by neildarlow** [processone/ejabberd#3205]
## Environment

- ejabberd version: 20.01
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.3.5.9
- OS: FreeBSD-12.1
- Installed from: Ports

## Configuration
hosts: ["darlow.co.uk"]
-
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /upload: mod_http_upload
      /ws: ejabberd_http_ws

mod_http_upload:
    docroot: /var/cache/ejabberd/
    dir_mode: "0755"
    file_mode: "0644"
    max_size: 10485760
  mod_http_upload_quota:
    max_days: 7

## Errors from error.log/crash.log

No errors

## Bug description

Using the above configuration with default put_url and attempting to upload an image locally using the Conversations client I get the following error:

Failed to connect to darlow.co.uk/aa.bb.cc.dd:5443

where aa.bb.cc.dd is the IP address of my server's external ethernet interface. Why would that IP address be added to the host in the put_url?

**Comment by weiss** [comment]
> Why would that IP address be added to the host in the put_url?

Are you sure that's the PUT URL returned by ejabberd and not just Conversations' way of formatting the error message? You could open an `ejabberdctl debug` shell and call:

```erlang
gen_mod:get_module_opt(<<"darlow.co.uk">>, mod_http_upload, put_url).
```
Don't forget the trailing `.`, and press `Ctrl`+`C` twice to get out of the shell.

**Comment by weiss** [comment]
(Clarified out of band that it's not an ejabberd issue.)
