### ISSUE TITLE
Rename opts->name to label in Shared Roster Groups

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3214]
## Environment

- ejabberd version: 20.03
- OS: Linux (Debian 10)
- Installed from: official deb

## Bug description

1. Shared Roster Group has two names: one that is given on creation next to "Add New" button, another in its details at "Name" input. However, for admin purposes the real name is the first one, and the second one is more like a label displayed in people's rosters. I propose changing the text in group details from "Name" to "Label". It is significant because of issue 2. below.
2. After creating a new Shared Roster Group, typing for example "Test" next to "Add New", and then editing its details to give it a "Name" and "Members", it does not show up in people's rosters upon them logging in. It will be shown if and _only_ if you type its admin name ("Test") in the "Displayed Groups" field, which makes sense but is not described anywhere, so is super confusing.
3. We really need to add helpful texts in web admin...

**Comment by badlop** [comment]
I made some changes. Before committing, let's take a look. How does it appear?
![cap1](https://user-images.githubusercontent.com/96807/79145984-e1486680-7dc1-11ea-88e8-6d5fcd43313a.png)
![cap2](https://user-images.githubusercontent.com/96807/79145997-e4435700-7dc1-11ea-897f-bf596358ea8b.png)

**Comment by f055** [comment]
@badlop this looks good for me, much clearer 👍
