### ISSUE TITLE
Chatrooms disappear from web admin list during errors

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3215]
## Environment

- ejabberd version: 20.03
- OS: Linux (Debian 10)
- Installed from: official deb

## Bug description

Scenario: using `ejabberdctl change_room_option` enable `logging true` on a chatroom, but don't load `mod_muc_log` in `ejabberd.yml`. When any user attempts to join this chatroom, it won't be possible and there will be errors in `error.log`. But, as tested with Siskin IM client, from the moment the user attempts to open this chatroom until he removes this chatroom from his contact list, that chatroom disappears from the web admin Chatrooms list.

**Comment by badlop** [comment]
Right. When a XMPP client tries to enable logging in the room config, mod_muc_room first checks if mod_muc_log is enabled.

However, that verification was not implemented when running the change_room_option command in mod_muc_admin, so running that command could crash the room completely.

I've implemented that check in the command, and now that scenario is prevented:

```
$ ejabberdctl change_room_option sala conference.localhost logging true
Error: mod_muc_log_not_enabled
```
