### ISSUE TITLE
Issue with multiple owner adding to muc room through matrix

### ISSUE THREAD

**Issue by kpsbhuvi** [processone/ejabberd#3216]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: official deb/rpm 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml
using default config

## Bug description
1. Room(room@conference.test.im) created with owner user1@test.im
2. Adding another owner (user2@test.im) with below iq, is failing with **"Changing role/affiliation is not allowed"**
```
<iq id="MX_1" to="room@conference.test.im" type="set" xmlns="jabber:client">
     <query xmlns="http://jabber.org/protocol/admin#muc">
       <item affiliation="owner" role="moderator" jid="user2@test.im" nick="user2@test.im"/>
     </query>
</iq>
```
3. Is there any config change required for muc_room/muc_room_admin modules, which allow me to add multiple owners?

**Comment by prefiks** [comment]
Who is sending this request? This requests will be accepted when it would be sent by someone who is already room owner or someone that is specified as muc admin. There is no option that changes that.

**Comment by kpsbhuvi** [comment]
Yes the request sent by the owner (user1@test.im) of the room. Still I am getting above error.

**Comment by kpsbhuvi** [comment]
Can someone help me on this. Still having this issue.

**Comment by badlop** [comment]
First of all, this namespace is wrong:
`http://jabber.org/protocol/admin#muc`
It should be:
`http://jabber.org/protocol/muc#admin`

Then, I tried in ejabberd 20.03 sending this query, and it returns the error you mentioned:
```xml
<iq id="MX_1" to="room@conference.test.im" type="set" xmlns="jabber:client">
     <query xmlns="http://jabber.org/protocol/muc#admin">
       <item affiliation="owner" role="moderator" jid="user2@test.im" nick="user2@test.im"/>
     </query>
</iq>
```

The problem is that you are setting both the _role_ and the _affiliation_ simultaneously.

Check the protocol: you set the _affiliation_ to _owner_, and the server will automatically grant the _role_ of _moderator_ (if the user is already occupant in the room, or when he joins the room):
https://xmpp.org/extensions/xep-0045.html#grantowner

So, for me this works correctly:
```xml
<iq id='131:568733' type='set' to='room@conference.test.im'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item affiliation='owner' jid='user2@test.im'/>
  </query>
</iq>
```

**Comment by kpsbhuvi** [comment]
@badlop **Thanks much for the response.
After removing the role, I am able to add the user as owner.**

But failing with same error '**Changing role/affiliation is not allowed**', on adding 'member' instead owner.

**Comment by badlop** [comment]
> But failing with same error 'Changing role/affiliation is not allowed', on adding 'member' instead owner.

And how do you send that query?
A) Using a well-known Jabber/XMPP client/library that probably adheres perfectly to the protocols?
B) Using a client/library still in early stages, that maybe has some bugs?
C) Or using your custom library/client, that may also have some bugs?

**Comment by kpsbhuvi** [comment]
Hi @badlop, I am using Matrix XMPP library. Have been started with open fire. Now decided to move Ejabberd.
The same code with Ejabberd failing now.

**Comment by badlop** [comment]
> But failing with same error 'Changing role/affiliation is not allowed', on adding 'member' instead owner.

It works for me using Tkabber client and ejabberd 20.03, and also 18.09.

It may be other problematic stanza that you are sending. This is what my client sends and works correctly, you can compare that with what your library sends:

Client user1, that is owner of the room, sends:
```xml
<iq id='24:424776'
	type='set'
	to='sala@conference.localhost'>
  <query xmlns='http://jabber.org/protocol/muc#admin'>
    <item affiliation='member'
	jid='user2@localhost'/>
  </query>
</iq>
```

Client receives:
```xml
<message to='user1@localhost/tka1'
	from='sala@conference.localhost'
	id='3378759539604828999'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item jid='user2@localhost'
	role='none'
	affiliation='member'/>
  </x>
</message>
```

**Comment by kpsbhuvi** [comment]
Hi @badlop tried with same stanza you used with send_stanza rest API. Same issue persists still.

Could you please share your muc module config. I could compare and proceed.

Thanks in Advance.

**Comment by badlop** [comment]
I'll provide you all the information I consider relevant to reproduce the success. I hope this helps you find how to solve your problem. I also expect that, if you are unable to solve it, you provide precise, detailed and reproducible instructions to reproduce the problem.

1. Installed ejabberd 18.09 from source code.
2. Used the default configuration with just a few changes:
```yaml
hosts:
  - "localhost"
  - "test.im"

listen:
  ...
  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api

api_permissions:
  "api commands":
    from:
      - ejabberd_ctl
      - mod_http_api
    who: all
    what: "*"

modules:
  ...
  mod_http_api: {}
  mod_muc:
    default_room_options:
      persistent: true
```

3. api-send.php script:
```php
<?php
$url='test.im:5443/api/send_stanza/';
$info=array("from"=>"user1@test.im",
            "to"=>"room@conference.test.im",
            "stanza"=>"<iq id='24:734239' type='set'><query xmlns='http://jabber.org/protocol/muc#admin'><item affiliation='member' jid='user2@test.im'/></query></iq>"
           );
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($info));
$output=curl_exec($ch);
curl_close($ch);
print_r($output);
?>
```

4. Steps to create accounts, room, call to the API:
```
ejabberdctl register user1 test.im somepass
ejabberdctl create_room room conference.test.im test.im
ejabberdctl set_room_affiliation room conference.test.im user1@test.im owner
php api-send_stanza.php 
```

5. Now I check the affiliation was changed:
```
ejabberdctl get_room_affiliations room conference.test.im
  user2   test.im member
  user1   test.im owner
```

**Comment by kpsbhuvi** [comment]
@badlop thanks for your inputs. I have tried set_room_affiliation via ejabberdctl & rest API.
Able to add that user as member successfully to that muc_room.

I have used the same stanza which you posted above with my user & service. I am getting 'Changing role/affiliation is not allowed' error only through the stanza. Not sure why it is failing only through stanza. could you help me here.

Thanks in advnace.

**Comment by badlop** [comment]
If you are doing something, and it produces unexpected results, it probably is because you are doing something wrong. But you don't show what you are doing. How am I suposed to know what you are doing wrong, if you don't explain what you are doing?
