### ISSUE TITLE
ejabberdctl start permission denied 

### ISSUE THREAD

**Issue by Danissss** [processone/ejabberd#3224]
Hi,

I install the ejabberdctl from the source.

```
./autogen.sh
./configure
make
sudo make install
```

When I execute `ejabberdctl start`, I got `bash: /usr/local/sbin/ejabberdctl: Permission denied`

And then it's not run-able with root.

I checked the code
```bash
...
# check the proper system user is used
case $(id -un) in
    "$INSTALLUSER")
        EXEC_CMD="as_current_user"
        ;;
    root)
        EXEC_CMD="as_current_user"
        if [ -n "$INSTALLUSER" ] ; then
            EXEC_CMD="as_install_user"
        else
            EXEC_CMD="as_current_user"
            echo "WARNING: It is not recommended to run ejabberd as root" >&2
        fi
        ;;
    *)
        echo "random user"
        if [ -n "$INSTALLUSER" ] ; then
...
``` 

Could I ask what is $INSTALLUSER? Should I create a new linux user for running ejabberd?

Thanks!

PS. 
Ubuntu: 18.04
ejabberd: latest from github

**Comment by licaon-kter** [comment]
`sudo -u ejabberd ejabberdctl` maybe?

Also, you can define your user, see what `./configure --help` says.

**Comment by badlop** [comment]
> Could I ask what is $INSTALLUSER? Should I create a new linux user for running ejabberd?

ejabberd does not strictly need _root_ access to run.

In this sense, you can create a normal user, specific for running ejabberd, let's call it _ejacount_ in this example, then tell the configure script to use that user:

```shell
sudo adduser ejacount
...
./autogen.sh
./configure --enable-user=ejacount
make 
sudo make install
```

And now ejabberdctl can be run using that user, no need to use root. For example, for testing purposes, you can start ejabberd in live mode, with an interactive shell, to see all the errors immediately:
```
su ejacount2
ejabberdctl live
```

**Comment by Danissss** [comment]
Thanks for the help!
