### ISSUE TITLE
Message lost in mobile chat application.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#3225]
Hi Guys,
I have some issues regarding message lost on dead connections. 
1.  A sends B a message
2.  B has gone offline, but still online on the server.
Consider these points

1. In mod_stream_mgmt
   1. if resend_on_timeout : true, then no error bounce back message will be sent until the user session does not time out. A will get the error message after stream resumption timeout.

  2. If resend_on_timeout : false. then error bounce back will be generated and send to the sender. But in the meanwhile before receiving the error stanza the sender connection is cut and it is online on server, then this message also lost .

 3. resend_on_timeout :  if_offline then it will not send the message error bounch back to the sender. It will store the message to archieves if no resource is online. But the main problem here is it remains online after connection intrupted by the client(net issues) . 

why??? suggestions how the ensure that the message do not lost in any case.
 
 thanks,

**Comment by mailtosagar** [comment]
Also it would be helpful if you just tell me the code of mod_mam where i can control the message deletion . 
I am thinking if i can get something from the receiver so then will delete it until then keep storing them in message archieve.

**Comment by prefiks** [comment]
Hello,

I am assuming talking about missing messages you are talking about those not being put in offline storage? So right now unacked messages that are bounced thanks to `resend_on_timeout` option aren't put in offline storage when they were already archived by mam. I am working on change that will modify this, so hopefuly this will help your issue.

**Comment by prefiks** [comment]
I commited 37226dd41fc2c3584e299cd80d3c4e1f3802450e with that change i was talking about.

**Comment by mailtosagar** [comment]
```I am assuming talking about missing messages you are talking about those not being put in offline storage? So right now unacked messages that are bounced thanks to resend_on_timeout option aren't put in offline storage when they were already archived by mam. I am working on change that will modify this, so hopefuly this will help your issue.
```
@prefiks pardon if i got you wrong. But i am not using mam (message not being stored anywhere except client's end and if reciver is offline). Earlier i used to think the offline storage and the MAM uses the same DB table. I need a functionality in which messages will be deleted from offline storage only when it receive something from the receiver.

the responsibility of the messages successfully send by the user to the server is now responsibity of server. So it should not tell sender this message is not send, Please send it again(bounce back messages ). Rather it should ask the receiver something that "if you have received this message then i should delete it. "

**Comment by prefiks** [comment]
So stream management has also ack feature for data that client sends, if client sends <r xmlns='urn:xmpp:sm:3'/> server will answer with <a h="number"/>, with that you can see which stanzas were received by server. Additionally if you enable resume feature on session, when you try to resume previous session you will also get number of stanzas acknowledged by server both in cases when you manage to resume session but also when previous session already expired, both success and failure stanzas will have h="..." in them to tell you which messages were seen by server.

I also fixed couple bugs in last weeks in that, so it quite possible that your scenario will work better with those changes.

**Comment by weiss** [comment]
There's an [old FAQ entry][1] (written without MAM clients in mind) that will probably answer most of your questions.  If you still think there's a bug or missing feature in ejabberd, please open a new issue and describe precisely what behavior should be changed in what way.

[1]: https://www.ejabberd.im/faq/tcp/

**Comment by mailtosagar** [comment]
New [Issue](https://github.com/processone/ejabberd/issues/3228) raised
