### ISSUE TITLE
Message Lost with every option of stream management resend on time out.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#3227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Neustradamus** [comment]
@mailtosagar: Why it is closed?

**Comment by licaon-kter** [comment]
@Neustradamus no details and the OP themselves closed it, why do you ask?

**Comment by weiss** [comment]
See #3225 and #3228.
