### ISSUE TITLE
Relative paths in erl.ini

### ISSUE THREAD

**Issue by NataliaDobryaeva** [processone/ejabberd#3231]
## Environment

- ejabberd version: 20.3
- Erlang version: `erl +V`
- OS: Windows
- Installed from: official binary installer

## Bug description

Is it possible to define relative paths in erl.ini file? I've tried the following:
```
[erlang]
Bindir=.
Progname=erl
Rootdir=..
```
But it does not work: when I run the command "ejabberdctl status" it returns "error spawning .\epmd -daemon".
I've used ejabberd 15.07 version before and such relative paths worked with it.

**Comment by patil-rahul** [comment]
Please let me know if you are able to figure it out.
Thanks.

**Comment by mremond** [comment]
Closing, as Windows installer support has been discontinued in favor of Docker: https://www.process-one.net/blog/install-ejabberd-on-windows-10-using-docker-desktop/
