### ISSUE TITLE
Ejabberd 20.03 in Docker Hub Does Not Exist

### ISSUE THREAD

**Issue by alamse** [processone/ejabberd#3233]
**Is your feature request related to a problem? Please describe.**
I am very enthusiast to update my Docker Ejabberd version to 20.03, to know, how the cache and optimizing queries in `mod_shared_roster` works. But i've problem, because the tag `20.03` in Docker Hub does not exist.

**Describe the solution you'd like**
Would be nice, if the maintainer could push the tag `20.03` to Docker Hub

**Comment by licaon-kter** [comment]
Can you try with `latest` ?

**Comment by alamse** [comment]
> Can you try with latest ?

yes i can. But i'm a bit worry if the `latest` tag, have an update in the future with some changing in the config and affecting our docker ejabberd. Would be safe if i can pointing it to specific version.

**Comment by alamse** [comment]
i was trying to pull the image through Github Package, such as following command :

```
> docker pull docker.pkg.github.com/processone/ejabberd/ecs:20.03
```

But, i got an error, like : 

```
Error response from daemon: Get https://docker.pkg.github.com/v2/processone/ejabberd/ecs/manifests/20.03: no basic auth credentials
```

**Comment by Neustradamus** [comment]
@alamse: Please look for 20.04...

**Comment by alamse** [comment]
thank you.
