### ISSUE TITLE
Dynamically adding vhosts does not shows on Admin

### ISSUE THREAD

**Issue by prafulbagai708** [processone/ejabberd#3238]
## Environment

- ejabberd version: 20.03.50
- Erlang version: `10.7.1`
- OS: Linux (Debian) Linux
- Installed from: source

## Errors from error.log/crash.log

No errors

## Bug description

Upon configuring a new virtual host via `ejabberd_config:set_options(hosts, [<<"host1">>, <<"host2">>]).`, it neither shows on Admin UI nor able to register a new user with the added host.

However, `ejabberd_config:get_options(hosts).` returns the updated list of virtual host. What's the issue?

**Comment by weiss** [comment]
Just add the new host to your configuration and run `ejabberdctl reload-config`.

**Comment by prafulbagai708** [comment]
@weiss - I know that! However, that's a manual step. I wish to add it dynamically via code. Hence tried using `ejabberd_config:set_options`. Is there a way to add a new virtual host programmatically?

**Comment by weiss** [comment]
You could obviously check the code for what is done on configuration reload.  If you can't figure it out on your own, you might ask in the ejabberd room (`ejabberd@conference.process-one.net`) or on the [mailing list][1], for example.  ejabberd's bug tracker is not the right place to ask questions on how to develop custom solutions.

[1]: http://lists.jabber.ru/mailman/listinfo/ejabberd
