### ISSUE TITLE
Getting added elements and tags from ejabberd server when message received.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#3242]
Hi Guys,
I am getting additional elements and tags within the message stanza when received at other end in android client .

Message stanza sent:
```
<message to='bob@chatserver.com' id='o4e4Y-35' type='chat'>
    <body>cvhj</body>
    <time xmlns='urn:xmpp:time'>
        <timestamp>1588139383872</timestamp>
    </time>
    <send xmlns='urn:xmpp:receipts'></send>
    <request xmlns='urn:xmpp:receipts'/>
</message>
```

Message Stanza Received:
```
<message to='bob@chatserver.com/bob' from='+917999997776@chatserver.com/+917999997776' 
                  id='o4e4Y-35' xml:lang='en' type='chat'>
    <body>cvhj</body>
    <archived xmlns='urn:xmpp:mam:tmp' xmlns:stream='http://etherx.jabber.org/streams' 
                  by='bob@chatserver.com' id='1588139384499682'></archived>
    <stanza-id xmlns='urn:xmpp:sid:0' xmlns:stream='http://etherx.jabber.org/streams' 
                  by='bob@chatserver.com' id='1588139384499682'></stanza-id>
    <time xmlns='urn:xmpp:time' xmlns:stream='http://etherx.jabber.org/streams'>
        <timestamp xmlns:stream='http://etherx.jabber.org/streams'>1588139383872</timestamp>	 
    </time>
    <send xmlns='urn:xmpp:receipts' xmlns:stream='http://etherx.jabber.org/streams'></send>		 
    <request xmlns='urn:xmpp:receipts'/>
</message>
```

1. I am getting <archieved/> but i do not want message to be archieved nor i want <stanza-id/>.
2. I am also getting **xmlns:stream='http://etherx.jabber.org/streams'** in <send/> and <time/> stanza. But they are the custom elements added by us to serve specific purposes .

Thanks

**Comment by weiss** [comment]
> i do not want message to be archieved

Disable `mod_mam` if you don't want messages archived for any user/group on your server.  (Alternatively, clients could [disable archiving individually][1].)

> `xmlns:stream='http://etherx.jabber.org/streams'`

Maybe this is added by your client-side library.

[1]: https://xmpp.org/extensions/xep-0313.html#prefs
