### ISSUE TITLE
Core docs contribution for JWT auth guide

### ISSUE THREAD

**Issue by ghenry** [processone/ejabberd#3243]
## Environment

- ejabberd version: 20.03

Hi all,

I'm on the latest ejabberd and have found the JWT auth docs somewhat lacking - https://docs.ejabberd.im/admin/configuration/authentication/#jwt-authentication

I've created this post https://stackoverflow.com/questions/61490726/jwt-secret-to-use-with-ejabberd and once I have the solution I'd like to update the core docs as the [ProccessOne JWT blog](https://www.process-one.net/blog/ejabberd-19-08/) post has some missing pieces, but not all the required info in my opinion.

What's the best way to submit a patch for docs once I'm sorted? PR?

Thanks,
Gavin.

**Comment by badlop** [comment]
> What's the best way to submit a patch for docs once I'm sorted? PR?

Yes, the usual method is a PR for https://github.com/processone/docs.ejabberd.im

But, if you are not fluent with the markdown syntax, or you don't want to mess with git and PRs for just proposing a few lines of text, you can simply provide here in a comment the paragraphs, examples, or corrections. I'll be happy to format them and commit to git.

**Comment by ghenry** [comment]
Thanks, that sounds ideal. I'll do my best either way.

**Comment by ghenry** [comment]
Do you have any ideas what I'm doing wrong here? https://stackoverflow.com/questions/61490726/jwt-secret-to-use-with-ejabberd

**Comment by badlop** [comment]
No idea about JWT, sorry
