### ISSUE TITLE
Ejabberd does not send "unavailable" presence for users after closing c2s session

### ISSUE THREAD

**Issue by NataliaDobryaeva** [processone/ejabberd#3245]
## Environment
- ejabberd version: 20.03
- OS: Windows server
- Installed from: official binary installer

## Bug description
When we are closing XMPP session, ejabberd.log shows that c2s session is closing, but "unavailable" presence for users is not send after it: uses are still connected to the muc room after closing the session:

`
2020-04-24 15:47:13.932 [info] <0.1822.0>@ejabberd_c2s:process_terminated:294 (tcp|<0.1822.0>) Closing c2s session for 9113983327415068954675@public.localhost/x: Stream reset by peer
`

We were using ejabberd 15.07 version before and with this ejabberd version right after closing the session the "unavailable" presence was sent for users and they were disconnected from the muc room. Could you please clarify why this behaviour was changed? Maybe some config settings could fix it with ejabberd 20.3?

**Comment by badlop** [comment]
I've tried that, and it works as expected:
1. I've installed ejabberd 20.04 in Windows 7 64bits
2. I keep the default configuration file with no changes from the default.
3. I register two accounts, user1 and user2 in localhost
4. user1@localhost joins a new room called room@conference.localhost
5. Then user2@localhost also joins that room, using the Tkabber client.
6. Then user2@localhost closes the connection:
```xml
</stream:stream>
```
7. In the log file I see in the log file a line like you showed, and also:
8. the MUC room correctly notices this and sends this stanza to the occupants of room, that is, user1@localhost:
```xml
<presence to='user1@localhost/tka1'
          from='room@conference.localhost/user2'
          type='unavailable'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item jid='user2@localhost/tka1'
          role='none'
          affiliation='none' />
  </x>
</presence>
```

**Comment by NataliaDobryaeva** [comment]
Thanks for the answer.
In my ejabberd.log I've found that the session is being closed before receiving </stream:stream> message:
```
2020-05-06 18:03:24.742 [debug] <0.5650.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_closed: ejabberd_c2s:process_closed/2
2020-05-06 18:03:24.742 [debug] <0.5650.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_terminated: ejabberd_c2s:process_terminated/2
2020-05-06 18:03:24.742 [info] <0.5650.0>@ejabberd_c2s:process_terminated:294 (tcp|<0.5650.0>) Closing c2s session for 614044645643682788352866@public.localhost/x: Stream reset by peer
2020-05-06 18:03:24.742 [debug] <0.5650.0>@ejabberd_hooks:safe_apply:231 Running hook sm_remove_connection_hook: ejabberd_auth_anonymous:unregister_connection/3
2020-05-06 18:03:24.746 [info] <0.5650.0> (tcp|<0.5650.0>) Received XML on stream = <<"</stream:stream>">>
...
2020-05-06 18:03:24.886 [info] <0.5650.0> (tcp|<0.5650.0>) Send XML on stream = <<"</stream:stream>">>
```
Could it be an issue with logging that "Received XML on stream = <<"</stream:stream>">>" is printed after closing session?

**Comment by prefiks** [comment]
Hello,

This may indeed be from processing close tcp socket event in synchronous way, where logging can happen asynchronous. I did change a bit how this is handled recently so in newer version this may be displayed correctly.

**Comment by NataliaDobryaeva** [comment]
Thanks Pawel.
Could it fix the issue of absence "unavailable" presence after closing the stream?

**Comment by prefiks** [comment]
After checking that code i think there may be issue when presence is being sent directly to muc room, but no general presence being sent (aka one without to attribute). I think it may be that in this case resending unavailable on c2s close is not being performed (but i need to check that). Is that scenario possible in your client?

**Comment by NataliaDobryaeva** [comment]
I've checked ejabberd.log and there are no presence was sent before or after closing the stream.

**Comment by prefiks** [comment]
I commited 51e45516a48faadb0b29a94ec2e3200ae6057fe1 that makes server send presence unavailable to all direct presence recipient even when in never received self presence from client. I believe this was true the in your case, as otherwise terminate hook (that from your log was called) would send that presence.

**Comment by NataliaDobryaeva** [comment]
Thank you.
