### ISSUE TITLE
Server does not send pong after sometime.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#3250]
Hi Guys,
I am using SMACK library on client side and EJABBERD on the server side.

Client is sending the <iq><ping/></iq> stanza regularly and server is responding to that always. 
But after somtime i receive ping from cleint but server not responding to that. 

Here are the logs of the client.
```
D/SMACK: RECV (1): <iq xml:lang='en' to='+919876543210@chatserver.com/+919876543210' from='chatserver.com' type='result' id='MxEkb-319'/><r xmlns='urn:xmpp:sm:3'/>
D/SMACK: SENT (1): <a xmlns='urn:xmpp:sm:3' h='154'/>
D/SMACK: SENT (1): <iq to='chatserver.com' id='MxEkb-321' type='get'><ping xmlns='urn:xmpp:ping'/></iq><r xmlns='urn:xmpp:sm:3'/>
D/SMACK: RECV (1): <a h='155' xmlns='urn:xmpp:sm:3'/><iq xml:lang='en' to='+919876543210@chatserver.com/+919876543210' from='chatserver.com' type='result' id='MxEkb-321'/><r xmlns='urn:xmpp:sm:3'/>
D/SMACK: SENT (1): <a xmlns='urn:xmpp:sm:3' h='155'/>
D/SMACK: SENT (1): <iq to='chatserver.com' id='MxEkb-323' type='get'><ping xmlns='urn:xmpp:ping'/></iq>
D/SMACK: RECV (1): <iq xml:lang='en' to='+919876543210@chatserver.com/+919876543210' from='chatserver.com' type='result' id='MxEkb-323'/>
D/SMACK: RECV (1): <r xmlns='urn:xmpp:sm:3'/>
D/SMACK: SENT (1): <a xmlns='urn:xmpp:sm:3' h='156'/>
D/SMACK: SENT (1): <iq to='chatserver.com' id='MxEkb-325' type='get'><ping xmlns='urn:xmpp:ping'/></iq>
D/Roster Connection Service:  Service start() function called. mactive :true
D/Roster Connection: desconnect from Server.
D/SMACK: SENT (1): <presence id='MxEkb-327' type='unavailable'></presence><a xmlns='urn:xmpp:sm:3' h='157'/>
D/SMACK: SENT (1): </stream:stream>
D/SMACK: RECV (1): </stream:stream>
``` 
We can see the ping with the **id="MxEkb-325"** has been sent. I am also able to log the ping stanza on the server. 
Here it is
```
16:30:46.087 [info] <<<<**************************GOT PING IQ*************************>>>>
16:30:46.087 [info] FORMAT ERROR: "Got the IQ: =====>>>>> " [{iq,<<"MxEkb-325">>,get,<<"en">>,{jid,<<"+919876543210">>,<<"chatserver.com">>,<<"+919876543210">>,<<"+919876543210">>,<<"chatserver.com">>,<<"+919876543210">>},{jid,<<>>,<<"chatserver.com">>,<<>>,<<>>,<<"chatserver.com">>,<<>>},[{ping}],#{ip => {0,0,0,0,0,65535,27351,35220}}}]
16:30:46.087 [info] <<<<**************************************************************>>>>
```
I am able to log these stanza by editing th this part of code on the in **mod_ping.erl**.
```
%%====================================================================
%% Hook callbacks
%%====================================================================
-spec iq_ping(iq()) -> iq().
iq_ping(#iq{type = get, sub_els = [#ping{}]} = IQ) ->
    ?INFO_MSG("<<<<**************************GOT PING IQ*************************>>>>",[]),
    ?INFO_MSG("Got the IQ: =====>>>>> ",[IQ]),
    ?INFO_MSG("<<<<**************************************************************>>>>",[]),
    xmpp:make_iq_result(IQ);
iq_ping(#iq{lang = Lang} = IQ) ->
    Txt = ?T("Ping query is incorrect"),
    xmpp:make_error(IQ, xmpp:err_bad_request(Txt, Lang)).

```

Why the server stops ping response all of a sudden??

Please help if ia m doing something wrong.

**Comment by badlop** [comment]
Just a wild idea: Do you observe this behaviour when using a desktop client like Gajim or Psi, and a human user? I can force ejabberd to delay responses several seconds if I limit the connection like this:
```yaml
shaper:
  normal: 100
```
In your case, if you are using a programmed client that sends pings like crazy, it would be expected that ejabberd eventually slows down ping response.

**Comment by mailtosagar** [comment]
@badlop Thanks for the reply. 
Yes we are using a programmed Client. And we sends Pings to server every **5 sec** . 
We  also sending pings from the server but that is a different aspect (project needs). 

Taking consideration that we are sending pings from both side. What time gap should be good for the client to send pings that should not delay the response from server. Or what configurations should be applied on the server side that it should not delay the response. I know it's a suggestion kind of question but getting answered to this is least likely to happen at stackoverflow .

Thanks.

**Comment by mailtosagar** [comment]
@badlop reponse awaited.

**Comment by badlop** [comment]
I don't know.

**Comment by liangdefeng** [comment]
Just curiosity, the reason behind both client and server sending ping every 5 seconds? I set it to 30 seconds in my server. No special reason 30 seconds is set, I want to know the interval I should set as well.

**Comment by weiss** [comment]
The Smack maintainer [suggests][1] a ping interval of 30 _minutes_ for mobile clients, and something similar for servers (the servers I operate myself ping their clients after 30 minutes of idle time).  Note that this suggestion was made a few years ago.  These days, many mobile clients rely on push notifications, in which case there's probably not much point in keep-alive pings at all.

Either way, on mobile, I'd avoid those much smaller intervals you mentioned.  I don't see what purpose such a ping flood might serve and it can easily drain the battery.  For desktop clients that do try to keep the connection alive, pinging once in a few minutes might be fine.

[1]: https://stackoverflow.com/a/22118001

**Comment by badlop** [comment]
Is there anything else to do before closing this ticket? Maybe increase mod_ping's ping_interval default value, that right now is 1 minute?
