### ISSUE TITLE
mod_muc_room:get_config(Pid) returns {error,notfound}

### ISSUE THREAD

**Issue by suf4dev** [processone/ejabberd#3253]
We have about 1000 rooms running and about 5000 active users. We have developed custom plugin to list rooms and sorting rooms according to occupants number. Some times rooms disappear . When returning to error log we found that get_config() returns {error,notfound} for some rooms. We should restart server to rooms appear again.

**Comment by licaon-kter** [comment]
What OS? What ejabberd version? What config? What custom plugin?

**Comment by suf4dev** [comment]
OS : ubuntu 18.04
Ejabberd ver: 20.03
The custom plugin for listing rooms and ordering for android app.
This is the code that returns {error,notfound}
`get_room_config(Name, Service) ->
  case mod_muc:find_online_room(Name, Service) of
    error ->
      room_not_found;
    {ok, Pid} ->
      mod_muc_room:get_config(Pid)
  end.`
MUC config: `  mod_muc:
    history_size: 0
    max_users: 30
    max_room_id: 128
    max_room_name: 128
    min_message_interval: 0.4
    min_presence_interval: 4
    access_create:
      - allow: admin
    access_persistent: muc_persistent
    access:
      - allow
    access_admin: muc_persistent
    access_mam:
      - allow: none
    default_room_options:
      mam: false
      allow_change_subj: false
      allow_query_users: false
      logging: false
      max_users: 30
      moderated: false
      anonymous: false
      persistent: true
      presence_broadcast: [moderator, participant, visitor]
  mod_muc_admin: {}`

**Comment by badlop** [comment]
> Some times rooms disappear . When returning to error log we found that get_config() returns {error,notfound} for some rooms. We should restart server to rooms appear again.

So, the room Pid is listed in the muc_online_room mnesia table, but the Pid stored in that table cannot be contacted. Two wild ideas:
A) Do you have several ejabberd nodes in a cluster, with mod_muc rooms distributed over them?
B) Maybe the room process crashed some time ago (and it should provide some relevant message in the ejabberd log file), but the room Pid was not removed from the table due to a bug in ejabberd.

You should check the ejabberd log files far before the notfound error, maybe there are room crashing errors.

Also, if you apply this small change, it will provide more internal details when the room isn't found:
```diff
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 03faa6a06..12841e1ca 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -170,8 +170,8 @@ get_config(Pid) ->
     try p1_fsm:sync_send_all_state_event(Pid, get_config)
     catch _:{timeout, {p1_fsm, _, _}} ->
 	    {error, timeout};
-	  _:{_, {p1_fsm, _, _}} ->
-	    {error, notfound}
+	  A:B ->
+	    {error, notfound, Pid, A, B}
     end.
 
 -spec set_config(pid(), config()) -> {ok, config()} | {error, notfound | timeout}.
```

**Comment by suf4dev** [comment]
> So, the room Pid is listed in the muc_online_room mnesia table, but the Pid stored in that table cannot be contacted. Two wild ideas:
> A) Do you have several ejabberd nodes in a cluster, with mod_muc rooms distributed over them?
> B) Maybe the room process crashed some time ago (and it should provide some relevant message in the ejabberd log file), but the room Pid was not removed from the table due to a bug in ejabberd.

No cluster only one node running. I have tried the patch and I got the following error
` {error,notfound,<0.32603.534>,exit,
                      {noproc,
                          {p1_fsm,sync_send_all_state_event,
                              [<0.32603.534>,get_config]}}}`

**Comment by badlop** [comment]
Now you can search the ejabberd log file for lines that mention the room name or the Pid <0.32603.534>, and they will give you some clue about the problem.

**Comment by suf4dev** [comment]
> Now you can search the ejabberd log file for lines that mention the room name or the Pid <0.32603.534>, and they will give you some clue about the problem.

I have searched for this but no crash information. I have downgraded OTP from 22 to 21.1. and the problem seems to be solved and the server now is stable

**Comment by Neustradamus** [comment]
@suf4dev: Have you tested Erlang OTP 23.0?
