### ISSUE TITLE
webadmin muc room sorting broken

### ISSUE THREAD

**Issue by mightyBroccoli** [processone/ejabberd#3256]
## Environment

- ejabberd version: 20.03
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4`
- OS: Linux (Debian)
- Installed from: source

## Configuration:
```yaml
  -
    port: 5443
    ip: "127.0.0.1"
    module: ejabberd_http
    request_handlers:
      /http-bind: mod_bosh
      /websocket: ejabberd_http_ws
      /register: mod_register_web
      /captcha: ejabberd_captcha
      /admin: ejabberd_web_admin
    tls: true
```
nginx reverse proxy configuration:

```nginx
# web admin endpoint
location ^~ /admin {
	include proxy_params;
	proxy_pass https://localhost:5443/admin;
}
```

## Errors from error.log/crash.log

No errors

## Bug description

On the page `/admin/muc/rooms/` the user has the ability to sort the rooms according to the given columns. But arrows to either sort decreasingly / increasingly only appends `?sort=2/` eg. to the end without changing the actual order.
Additionally if one might `/admin/muc/rooms?sort=2/` remove the slash between rooms and the URL parameter the ejabberd webserver stops serving the style.css and additionals.js file.

**Comment by badlop** [comment]
This fixes it for me using Firefox and Chrome. Do you confirm it's solved also in your cases?

**Comment by mightyBroccoli** [comment]
I will rebuild and try.

**Comment by mightyBroccoli** [comment]
I can confirm this fixes the issue. Thank you :unicorn:

**Comment by badlop** [comment]
Unfortunately string:take doesn't exist in Erlang/OTP 19.3, which ejabberd still supports, so I had to rewrite the fix.

http://erlang.org/documentation/doc-8.3/lib/stdlib-3.3/doc/html/string.html
