### ISSUE TITLE
Get multiple affiliations users of MUC in a stanza failed with Too many <item/> elements

### ISSUE THREAD

**Issue by kpsbhuvi** [processone/ejabberd#3258]
## Environment

- ejabberd version: 18.01
- Erlang version: `erl +V`
- OS: Linux (Redhat)
- Installed from: official deb/rpm 

## Bug description

I am trying to get the all users in the room who is having affiliation of 'owner, member, admin'.
Using Matrix XMPP from my application to interact with Ejabberd.

which sends IQ stanza to ejabberd as,

```
<iq from='user1@test.com/APP' to='room1@muc.test.com' id='mx_1' type='get'>
  <query xmlns='http://jabber.org/protocol/muc#admin' >
    <item affiliation='admin'/>
    <item affiliation='owner'/>
    <item affiliation='member'/>
  <query/>
</iq> 
```

Response from Ejabberd as,
error = 400, reason = bad request, data = Too many <item/> elements

Based on the XMPP specification,
muc#admin XML schema specifies maxOccurs='unbounded'. 

But for me the above stanza fails with Too many <item/> elements.

Can someone please revert ASAP. 
Thanks in Advance.

Note:
Passing one <item/> in the get stanza, successfully returns the result.

**Comment by badlop** [comment]
Looking at https://xmpp.org/extensions/xep-0045.html all the example `get` queries with namespace `muc#admin` include only one item element.

And looking at the source code, this is implemented in line 4770: if there are two or more items, then it returns that error https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl#L2770

**Comment by prefiks** [comment]
Yes, also i guess xsd allows multiple <item/> because this definition is also used for results, where multiple items are expected.

**Comment by kpsbhuvi** [comment]
Thanks for the quick response. 

Based on the reference of https://xmpp.org/extensions/xep-0045.html#schemas-admin
In the xml schema maxOccurs for item mentioned as 'unbounded' inside query element.

I am working on migration from openfire to ejabberd. our code with multiple item element are responding with out any issues to the openfire.
The same code with Ejabberd we are getting the error.

**Comment by prefiks** [comment]
Probably adding this is not that big deal, but as is currently we accept only one item on input for those queries.

**Comment by kpsbhuvi** [comment]
Thanks prefiks for the info.

I will proceed with the changes to work with one item in the queries for now.

Raising the feature request for the same and closing out this issue.
