### ISSUE TITLE
Missing a jlib.hrl erlang file

### ISSUE THREAD

**Issue by siddhant3030** [processone/ejabberd#3261]
## Environment

- ejabberd version: 20.04
- Erlang version: `Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]`
- OS: MacOs (Catalina)

## Bug description

I'm using an ejabberd version 20.04, I'm following this tutorial to work my way to understand ejabberd. But when I compile my file and ejabberd deps it doesn't have a jlib.hrl  and this file are being used in ejabberd controller. 

defmodule TestWeb.EjabberdController do
  use TestWeb, :controller

```
  # This is used to import the jid record structure from ejabberd:
  require Record
  Record.defrecord :jid, Record.extract(:jid, from: "deps/ejabberd/include/jlib.hrl")

  plug :action

  def index(conn, _params) do
    # get online jid, parse and extract the user part.
    online_users = :ejabberd_sm.connected_users
                      |> Enum.map &(jid(:jlib.string_to_jid(&1), :user))
    render conn, "index.html", users: online_users
  end
end
```

If this is being used here and it's not able to find this file "deps/ejabberd/include/jlib.hrl"
What should I do in this case?

**Comment by prefiks** [comment]
Hello,

This file was removed couple years ago, jid record is now defined in dependency xmpp in file jid.hrl. Also to convert string to jid object you need to use :jid.decode(my_jid).

**Comment by badlop** [comment]
> I'm following this tutorial

Can you mention what tutorial did you check?

It's based in an old ejabberd release, so either the tutorial examples get updated, or at least a disclaimer is added at the beginning.

**Comment by siddhant3030** [comment]
@badlop 

https://www.process-one.net/blog/embedding-ejabberd-into-an-elixir-phoenix-web-application/

This one

**Comment by siddhant3030** [comment]
@prefiks  Can you mention the dependency which I can use for XMPP? IT can help other also

**Comment by prefiks** [comment]
I was talking about this: https://hex.pm/packages/xmpp, this is used inside ejabberd

**Comment by siddhant3030** [comment]
@prefiks Thanks
