### ISSUE TITLE
get_option:163 Option 'sql_type' is not defined for virtual host

### ISSUE THREAD

**Issue by sinuzcode** [processone/ejabberd#3262]
## Environment

- ejabberd version: 20.03
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2
- OS: Linux (Ubuntu)
- Installed from: official deb/rpm | official binary installer

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 5
...
```

## Errors from error.log/crash.log

No errors

## Bug description

```
[debug] <0.5014.0>@ejabberd_config:get_option:163 Option 'sql_type'
 is not defined for virtual host 'conference.tst.testserver.com'.
 This is a bug, please report it with the following stacktrace included:
** exception error: bad argument
   in function  ets:lookup_element/3
      called as ets:lookup_element(ejabberd_options,
                                   {sql_type,<<"conference.tst.testserver.com">>},
                                   2)
   in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 159)
   in call from mod_mam_sql:store/8 (src/mod_mam_sql.erl, line 108)
   in call from mod_mam:store_mam_message/7 (src/mod_mam.erl, line 939)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 217)
   in call from mod_mam:store_muc/5 (src/mod_mam.erl, line 924)
   in call from mod_mam:muc_filter_message/3 (src/mod_mam.erl, line 437)
```

**Comment by prefiks** [comment]
Hello,

Would you be able to put here config file that you are using? That function should try to get sql_type for main domain instead fo conference.*, and i am not sure why it didn't work in your case.

**Comment by sinuzcode** [comment]
> Hello,
> 
> Would you be able to put here config file that you are using? That function should try to get sql_type for main domain instead fo conference.*, and i am not sure why it didn't work in your case.

###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - tst.testserver.com


###.  =======
###'  LOGGING

##
## loglevel: Verbosity of log files generated by ejabberd.
## 0: No ejabberd log at all (not recommended)
## 1: Critical
## 2: Error
## 3: Warning
## 4: Info
## 5: Debug
##

loglevel: 5
log_rotate_size: 10485760
log_rotate_count: 1

## If you already have certificates, list them here
certfiles:
  - "/etc/ssl/ejabberd/tst.testserver.com.pem"
#  - /etc/letsencrypt/live/domain.tld/privkey.pem


listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
    dhfile: "/etc/ssl/ejabberd/dh.pem"

  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "Thorin@tst.testserver.com"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: all
##=========================
## API & Permissions
##=========================
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who: all
#      ip: 127.0.0.1/8
    what:
      - status
      - unregister
      - connected_users_number
      - check_account
      - get_last

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    500: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

registration_timeout: infinity

max_fsm_queue: 10000

acme:
   contact: "mailto:support@one.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last:
    db_type: sql
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    db_type: sql
    assume_mam_usage: true
    default: never
    clear_archive_on_room_destroy: true
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    history_size: 0
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: true
      allow_change_subj: true
      allow_private_messages: true
      allow_private_messages_from_visitors: anyone
      allow_query_users: true
      allow_user_invites: true
      allow_visitor_nickchange: true
      allow_visitor_status: true
      logging: false
      members_by_default: true
      presence_broadcast: [moderator, participant, visitor]
      public: false
      public_list: true

  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
    registration_watchers:
      - bill@tst.testserver.com

  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:


  mod_vcard:
    host: internal.testserver.com
    search: true
    matches: infinity
    allow_return_all: true

  mod_vcard_xupdate: {}
  mod_version:
    show_os: false


##  ============
##  Custom Values

##
## Authentication using SQL
## Remember to setup a database in the next section.
##
auth_method: sql
default_db: sql


###.  ==============
###'  DATABASE SETUP

## ejabberd by default uses the internal Mnesia database,
## so you do not necessarily need this section.
## This section provides configuration examples in case
## you want to use other database backends.
## Please consult the ejabberd Guide for details on database creation.

##
## MySQL server:
##
sql_type: mysql
sql_server: "localhost"
sql_database: "ejabberdtest"
sql_username: "ejabberdtest"
sql_password: "dummypassword"


### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8

**Comment by badlop** [comment]
Using that configuration, I am not able to reproduce the problem. Anyway, it seems as if "conference.tst.testserver.com" was defined in the top-level "hosts" option.

I'll close now this ticket. If you still have this problem, please reopen.
