### ISSUE TITLE
Forbidden c2s session for XMPP Client

### ISSUE THREAD

**Issue by siddhant3030** [processone/ejabberd#3263]
## Environment

- ejabberd version: 20.04
-  Erlang version: Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
- OS: MacOs (Catalina)

## Errors from error.log/crash.log

```
[info] (#PID<0.1123.0>) Accepted connection 127.0.0.1:61129 -> 127.0.0.1:5222
[info] (tcp|<0.1123.0>) Accepted c2s DIGEST-MD5 authentication for mickael@localhost by mnesia backend from 127.0.0.1
[warn] (tcp|<0.1123.0>) Forbidden c2s session for mickael@localhost/Apples-MacBook-Air
```
 

## Bug description

I have registered a user using 

`:ejabberd_auth.try_register("mickael", "localhost", "mypass")`

But when I try to connect this user from PSI XMPP client it's giving me this error. I looked into issues where I found someone using Gajim and has the same error. But in that case, it was written
that it would get resolve in 18.09 version and I'm using the latest. 

I thought it's happening with PSI XMPP client only. But I got the same error when I used Adium. I don't know what this is about?

Please let me know how can I resolve this?

**Comment by licaon-kter** [comment]
Gist of the config?

**Comment by siddhant3030** [comment]
@licaon-kter 

https://gist.github.com/siddhant3030/2d5087456bdef85b6356e6bdc361ea22

**Comment by siddhant3030** [comment]
@licaon-kter  hey anything on the config?

**Comment by badlop** [comment]
> I have registered a user using
> :ejabberd_auth.try_register("mickael", "localhost", "mypass")

Well... you requested the account creation. But have you confirmed the account was created?

```
$ ejabberdctl register mickael localhost mypass
User mickael@localhost successfully registered

$ ejabberdctl registered_users localhost
mickael
user1

$ ejabberdctl check_account mickael localhost
$ echo $?
0

$ ejabberdctl check_password mickael localhost mypass
$ echo $?
0

$ ejabberdctl check_password mickael localhost mypasswrong
Error: false

$ ejabberdctl check_account mickaelwrong localhost
Error: false
```
