### ISSUE TITLE
Elixir application not started 

### ISSUE THREAD

**Issue by xi1976github** [processone/ejabberd#3267]
## Environment

- ejabberd version: 
20.04
- Erlang version: `erl +V`
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.6.4
- OS: Linux 
arch
- Installed from: source | distro package | official deb/rpm | official binary installer | other
package

## Errors from error.log/crash.log
2020-05-10 12:43:00.084971+02:00 [error] <0.115.0>@ejabberd_app:start_elixir_application/0:192 Elixir application not started.

ejabberd seems to run fine on first check, I thought this was solved in #1250

**Comment by siddhant3030** [comment]
Did you try mix deps.get and mix compile after using ejabberd in deps file?
