### ISSUE TITLE
TURN: Name external IPv6 IP address / "dual stack"

### ISSUE THREAD

**Issue by ThomasLeister** [processone/ejabberd#3268]
Hi,

I've configured my Ejabberd server to provide a TURN service similarly to this:

```
  -
    port: 3478
    transport: udp
    use_turn: true
    turn_ip: MY.EXTE.RNAL.IP
    module: ejabberd_stun
```

I wonder why there is only `turn_ip` as a setting, which seems to be for a single IPv4 address, only. Is there a way to also name an IPv6 address and run TURN dual stack? If this was not developed with IPv6 in mind, I'd be happy to have support for both IP versions :-)

**Comment by weiss** [comment]
The [TURN RFC][1] implemented by ejabberd has no IPv6.  There's a [separate extension][2] and a [feature request][3] to add support for that, you might want to subscribe it to be notified in case anybody implements it.

[1]: https://tools.ietf.org/html/rfc5766
[2]: https://tools.ietf.org/html/rfc6156
[3]: https://github.com/processone/stun/issues/27
