### ISSUE TITLE
captcha is very weak!

### ISSUE THREAD

**Issue by wkg** [processone/ejabberd#3269]
NOW captcha is very weak! i'm am using 20.04 and have many spammers...

please support "Google ReCaptcha" or, better yet, so that I can completely create my question and answer for captcha, please!

**Comment by licaon-kter** [comment]
Can you adapt the captcha generation to your needs maybe? https://docs.ejabberd.im/admin/configuration/basic/#captcha

**Comment by wkg** [comment]
> 
> 
> Can you adapt the captcha generation to your needs maybe? https://docs.ejabberd.im/admin/configuration/basic/#captcha

This is only generate image from numbers, and this is do not help do strong captcha...

**Comment by licaon-kter** [comment]
Yes, but it calls only a script...that you can make it output whatever you want, adapt the script.

**Comment by wkg** [comment]
> 
> 
> Yes, but it calls only a script...that you can make it output whatever you want, adapt the script.

Yes, i created my OWN IMAGE, very strong, i do not use numbers, BUT spammers answer anyway!
Need second script, where  i can generate my own anwser, not numbers...

**Comment by wkg** [comment]
Or maybe make it possible to generate a question not only with a picture ... Now I implemented RECAPTCHA with the help of transmitting the answer id through the database, but because there is only a picture there, this does not out very well ...:

$cod = (int)$argv[1];

$dbh->query("insert into mc set cod='{$cod}', time=NOW()");
$idP = $dbh->lastInsertId();

$img=imagecreatetruecolor(3, 3);
imagepng($img); 
echo "!!!!{$idP}!!!!";  //it's wrong.....

**Comment by wkg** [comment]
or just in captcha_cmd add second argument - id captcha.....

**Comment by wkg** [comment]
> So, did you end using reCaptcha during those months? In your experience, does it work correctly?

Works so far, no spam. But transferring id inside a picture is certainly not very good, but ejabberd doesn't provide a normal way

**Comment by badlop** [comment]
Sorry, your explanations are not simple and precise enought for me to follow them.

**Comment by wkg** [comment]
Могу по русски рассказать, английский плохо знаю
