### ISSUE TITLE
master - missing macro definition NS_EXTDISCO_2

### ISSUE THREAD

**Issue by yandrey** [processone/ejabberd#3274]
## Environment

- ejabberd version: master
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.2.3
- OS: Linux (Debian)
- Installed from: source

## Bug description
```
==> ejabberd (compile)
src/mod_stun_disco.erl:411: undefined macro 'NS_EXTDISCO_2'
src/mod_stun_disco.erl:451: undefined macro 'NS_EXTDISCO_2'
src/mod_stun_disco.erl:455: undefined macro 'NS_EXTDISCO_2'
```

if to search with github search through the master sources seems  there is no NS_EXTDISCO_2 definition indeed. forgotten push?

**Comment by licaon-kter** [comment]
Builds fine here, did you forget to `make update` first?

**Comment by prefiks** [comment]
Definition for this was added in xmpp 1.4.6, probably `make update` will fix this for you.

**Comment by yandrey** [comment]
indeed, thanks
