### ISSUE TITLE
Update default config file

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3275]
## Environment

- ejabberd version: 20.03-20.04
- OS: Linux (Debian Buster)
- Installed from: official deb

## Bug description

ejabberd log informs that we should:
1. remove `log_rotate_date` and `log_rate_limit`
2. update `acme` `ca_url` to `https://acme-v02.api.letsencrypt.org` (v01 -> v02)

**Comment by badlop** [comment]
I wonder where does that config file come from. It's not the main https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example because that doesn't mention those options at all, and I cannot find any other file in the repository that mentions those options.

**Comment by f055** [comment]
Hmm strange. Maybe it’s a recent change in 20.04 that removed these. I got these items from the config file of a clean install of 20.03.

**Comment by badlop** [comment]
log_rotate_size and date were removed from the example configuration file in 20.01: https://github.com/processone/ejabberd/commit/e4a8afb15d6c995b294a60ed150b86775e2f6805#diff-19e0c10699732f76181f70cfbec95d38
So, the configuration file bundled in the debian package is a different one, probably with customizations specific to debian and that package, and not found in this repository.

**Comment by f055** [comment]
Ah, ok. We need to check the build scripts then. Thanks for the info.

**Comment by badlop** [comment]
Changes proposed to the ejabberd.yml included in binary installers:

```diff
--- ejabberd.yml.txt	2021-03-09 16:32:34.114993140 +0100
+++ ejabberd.yml.txt	2021-03-09 16:34:59.063035866 +0100
@@ -15,13 +15,9 @@
 ###
 
 hosts:
-  - "@@DOMAIN@@"
+  - @@DOMAIN@@
 
-loglevel: 4
-log_rotate_size: 10485760
-log_rotate_date: ""
-log_rotate_count: 1
-log_rate_limit: 100
+loglevel: info
 
 certfiles:
   - "@@INSTALLDIR@@/conf/server.pem"
@@ -81,7 +77,7 @@
       - ::FFFF:127.0.0.1/128
   admin:
     user:
-      - "@@ADMIN@@@@@DOMAIN@@"
+      - @@ADMIN@@@@@DOMAIN@@
 
 access_rules:
   local:
@@ -147,7 +143,7 @@
 
 acme:
    contact: "mailto:@@ADMIN@@@@@DOMAIN@@"
-   ca_url: "https://acme-v01.api.letsencrypt.org"
+   ca_url: "https://acme-v02.api.letsencrypt.org"
 
 modules:
   mod_adhoc: {}
```

**Comment by badlop** [comment]
I expect this is already fixed, and will be correct in the next packages. Let's keep this issue open, and check it for sure when they are published.

**Comment by PaoloC68** [comment]
@badlop the changes you have made cause to break the process to get the certificates, the correct URI for them is `https://acme-v02.api.letsencrypt.org/directory"` and NOT `https://acme-v02.api.letsencrypt.org`!
I wasted a couple of hours for this. Please fix it!

**Comment by badlop** [comment]
Ohh, ok.

By the way, what's your opinion on setting "staging"?

As seen on
https://github.com/processone/docker-ejabberd/pull/70#issuecomment-875183098

---

El ds., 10 de jul. 2021, 12:41, Paolo Calvi ***@***.***> va
escriure:

**Comment by badlop** [comment]
Ok, I've updated it in ejabberd.yml like this:
```diff
-   ca_url: "https://acme-v02.api.letsencrypt.org"
+   ca_url: "https://acme-v02.api.letsencrypt.org/directory"
```
