### ISSUE TITLE
ejabberd_stun and sip not working latest version

### ISSUE THREAD

**Issue by spkan** [processone/ejabberd#3277]
## Environment

- ejabberd version: 20.03
- Erlang version: `erl +V`
- OS: Linux (Ubuntu 16.04)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

**Comment by licaon-kter** [comment]
Latest version is 20.0**4**

Do detail your setup and explain the issue better.
