### ISSUE TITLE
Issue with function gen_mod:get_module_opt

### ISSUE THREAD

**Issue by geniussy88** [processone/ejabberd#3283]
Hello, 

The function gen_mod:get_module_opt/4 is marked as undefined in Ejabberd 20.04. 

I saw some code changes in your source and default values shouldn't be there anymore. No prob. But when I go for gen_mod:get_module_opt/3, the module is not recognized anymore and Ejabberd interprets the name of the module as a typo by suggesting another name of an existent module. 

Do you have an idea about what's going on? Codes are posted here: https://stackoverflow.com/questions/61918443/ejabberd-custom-module-compiling-errors-unknown-option-auth-token.

Thank's.

**Comment by prefiks** [comment]
There were couple changes in config definitions, mod_opt_type should now use more declarative declaration instead of plain functions (just check other modules to see how that look), based on this calling `make options` will generate options module that should be used to get config, instead of calling gen_mod:get_module_opt(Host, auth_token) you will just call mod_offline_http_post_opt:auth_token(Host).

**Comment by geniussy88** [comment]
> 
> 
> There were couple changes in config definitions, mod_opt_type should now use more declarative declaration instead of plain functions (just check other modules to see how that look), based on this calling `make options` will generate options module that should be used to get config, instead of calling gen_mod:get_module_opt(Host, auth_token) you will just call mod_offline_http_post_opt:auth_token(Host).

Thank's prefiks for the reply. The thing is, I removed all that code to leave only basic ones like start and stop and the required functions. ?INFO_MSG is used everywhere inside but they are not displayed in the log file. It might mean the basic custom module is not called at all. I used ejabberdctl install module_name.

%% name of module must match file name
%% Update: info@ph-f.nl
-module(mod_offline_http_post).
-author("dev@codepond.org").

-behaviour(gen_mod).

-export([start/2,
        stop/1,
        depends/2,
        mod_opt_type/1,
        mod_options/1]).

-include("logger.hrl").
-include("xmpp.hrl").

start(_Host, _Opt) ->
  ?INFO_MSG("mod_offline_http_post loading", []),
  inets:start(),
  ?INFO_MSG("HTTP client started", []).

stop (_Host) ->
  ?INFO_MSG("stopping mod_offline_http_post", []).

depends(_Host, _Opts) ->
  [].

mod_opt_type(auth_token) ->
  fun iolist_to_binary/1;
mod_opt_type(post_url) ->
  fun iolist_to_binary/1;
mod_opt_type(confidential) ->
  fun (B) when is_boolean(B) -> B end.

mod_options(_Host) ->
  [{auth_token, <<"secret">>},
  {post_url, <<"http://example.com">>},
  {confidential, false}].

**Comment by geniussy88** [comment]
Let me give you the steps I used to follow:

The module is inside /opt/ejabberd/.ejabberd-modules/sources.

sources
│
│───ebin
│         └───modulename.beam
│───conf
│         └───modulename.yml
│───src
│        └───modulename.erl
│───README.txt
│───COPYING
│───modulename.spec

Afterwards, I hit /opt/ejabberd-20.04/bin/ejabberdctl module_install modulename
(the module being available when you hit ejabberdctl modules_available)

Once done, a directory with the same name as the module is created inside /opt/ejabberd/.ejabberd-modules/
Inside are the spec and the ebin directory containing the beam file. Basically, the beam file will be in that new directory and inside sources/modulename/ebin.

I tried, in some setups, to copy the beam file, whichever one, to the ejabberd beams directory which is /opt/ejabberd-20.04/lib/ejabberd-20.04/ebin If I'm not mistaken something because I'm writting all these commands by my head.

systemctl stop ejabberd (instead of a simple restart)
systemctl start ejabberd

No error displayed in /opt/ejabberd/logs/error.log or crash.log and everything's fine in ejabberd.log.

In the past, when I had problems like "Unknown module. Did you mean this other module?"
What was doing was this:
systemctl stop ejabberd
/opt/ejabberd-20.04/bin/ejabberdctl live
erl>code:ensure_load(modulename).
erl>ejabberd_config:reload().
#systemctl start ejabberd
And everything becomes fine.

Now once all of that done, I go and inspect the logs I mentionned above but don't see anywhere the messages inside the module that show it is at least executed.

I installed Ejabberd by your RPM package, guys. That's like the last thing that remains for the app to work for the world. I was on that problem for days but we will find the solution, though. 💯 sure!

**Comment by badlop** [comment]
> Once done, a directory with the same name as the module is created inside /opt/ejabberd/.ejabberd-modules/ Inside are the spec and the ebin directory containing the beam file. Basically, the beam file will be in that new directory and inside sources/modulename/ebin.

Ok, so it's correctly compiled and installed.

> I tried, in some setups, to copy the beam file, whichever one, to the ejabberd beams directory which is /opt/ejabberd-20.04/lib/ejabberd-20.04/ebin If I'm not mistaking something because I'm writting all these commands by my head.

Right, this is another way to ensure the *.beam file is available for ejabberd. But take care: if you copy different versions of your module *.beam file in different places of ejabberd, later you will not know which one is running, and will get confused: "why my latests changes do not appear in ejabberd?"

To be sure that ejabberd is loading and starting exactly the same *.beam file that you edited, compiled and installed, you can try to introduce a very specific error in your source code.

For example, in function start of your module, I add a line like:
```erlang
  error1 = thiswillcrash,
````
The compiler warns me that this will never match:
```
src/mod_offline_http_post.erl:6: Warning: undefined callback function mod_doc/0 (behaviour 'gen_mod')
src/mod_offline_http_post.erl:24: Warning: no clause will ever match
```
And finally, when I start ejabberd, it obviously crashes. This way I'm sure the module was compiled, installed, loaded and started correctly:
```
2020-05-22 19:28:22.419201+02:00 [info] Configuration loaded successfully
2020-05-22 19:28:22.822703+02:00 [info] Building language translation cache
2020-05-22 19:28:23.612453+02:00 [info] Loading modules for localhost
2020-05-22 19:28:23.878932+02:00 [info] mod_offline_http_post loading
2020-05-22 19:28:23.884620+02:00 [critical] Internal error of module mod_offline_http_post has occurred during start:
** Options: #{auth_token => <<"secret">>,confidential => false,
              post_url => <<"http://example.com/test">>}
** exception error: no match of right hand side value thiswillcrash
   in function  mod_offline_http_post:start/2 (src/mod_offline_http_post.erl, line 24)
```

**Comment by geniussy88** [comment]
It works. Check this to find out what I did thanks to you. Thank's for your help.
https://stackoverflow.com/questions/61918443/custom-module-in-ejabberd-is-not-called/61964723#61964723
