### ISSUE TITLE
Documentation : Several GET endpoints are listed as POST 

### ISSUE THREAD

**Issue by abbasidaniyal** [processone/ejabberd#3285]
## Environment

- ejabberd version: `20.04`
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.6.4`
- OS: Ubuntu 20.04
- Installed from: source

## Bug description

Several endpoints like /api/connected_users_info and /api/muc_online_rooms work via a GET request. The documentation at https://docs.ejabberd.im/developer/ejabberd-api/admin-api/ lists are the requests as POST. This leads to a 400 Bad Request Error.

**Comment by badlop** [comment]
umm, strange, POST queries work correctly for me:

Query:
```
POST /api/connected_users_info/ HTTP/1.1
Host: localhost:5443
Accept: */*
Content-Length: 2
Content-Type: application/x-www-form-urlencoded

[]
```
Reply:
```
HTTP/1.1 200 OK
Content-Length: 204
Access-Control-Allow-Headers: Content-Type, Authorization, X-Admin
Access-Control-Allow-Origin: *
Content-Type: application/json

[{"jid":"user1@localhost/tka1","connection":"c2s_tls","ip":"::ffff:127.0.0.1",
 "port":45205,"priority":8,"node":"ejabberd@localhost","uptime":3674,
 "status":"away","resource":"tka1","statustext":"Busysss"}]
```
Can you provide a minimal HTTP script to reproduce the problem?

**Comment by abbasidaniyal** [comment]
![image](https://user-images.githubusercontent.com/36009198/83004717-a0cd4100-a02d-11ea-9d65-8d23e515af0c.png)

Is this fine? @badlop

**Comment by abbasidaniyal** [comment]
I also did the same thing using Postman as well. Same response

**Comment by badlop** [comment]
Thanks to your example, I can reproduce that problem easily:

```
$ curl -X POST -d "{'host':'localhost'}" localhost:5280/api/registered_users/
"400 Bad Request"
```

Setting loglevel to 5 in ejabberd.yml, it gives a clue about the problem:

```
2020-05-29 10:59:42.047695+02:00 [debug] Bad Request: {2,invalid_json}
 [{jiffy,decode,2, [{file,"src/jiffy.erl"},{line,71}]},
```

It's easy to reproduce the problem in Erlang code:
```
jiffy:decode(<<"{'host':'localhost'}">>).
** exception error: {2,invalid_json}
```

Using " instead of ' solves the problem, for example:
```
$ curl -X POST -d "{\"host\":\"localhost\"}" localhost:5280/api/registered_users/
["user1"]
```

**Comment by abbasidaniyal** [comment]
Great! This works for me too! Thank you!
