### ISSUE TITLE
Online user recognition is not all users

### ISSUE THREAD

**Issue by unturtle** [processone/ejabberd#3287]
## Environment

- ejabberd version: 20.03

- Erlang version: 
```
# /usr/local/erlang21/bin/erl +V
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.2
```
- OS: CentOS 7
```
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```
- Installed from: source 

## Configuration (only if needed): 
```
grep -Ev '^$|^\s*#' /usr/local/ejabberd2003/etc/ejabberd/ejabberd.yml
```

<details>
<pre>
loglevel: 2
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 7
log_rate_limit: 1000
certfiles:
  - "/usr/local/ejabberd1909/etc/ejabberd/ssl/mydomain_com.pem"
acme:
  auto: false
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    shaper: c2s_shaper
    access: c2s
  -
    port: 7222
    ip: "::"
    module: ejabberd_c2s
    starttls: true
    shaper: c2s_shaper
    access: c2s
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
s2s_use_starttls: optional
acl:
  admin:
    user:
      - "myadmin@messenger.mydomain.com"
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 30000000
  fast: 50000000
max_fsm_queue: 10000000
shaper_rules:
  max_user_sessions:
    - 1: admin
    - 1
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
  max_s2s_connections: infinity
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: false
    max_user_conferences: 1000
    history_size: 0
  mod_muc_admin: {}
  mod_ping:
    send_pings: true
    ping_interval: 60
  mod_roster:
    versioning: true
    store_current_id: false
  mod_shared_roster: {}
sql_pool_size: 20
sql_keepalive_interval: 3600
use_cache: true
cache_size: infinity
cache_life_time: 3600
hosts:
  - "messenger.mydomain.com"
  - "mc.mydomain.com"
host_config: {"messenger.mydomain.com": {auth_method: sql, sql_type: pgsql, sql_server: "localhost", sql_port: 5432, sql_database: "ejabberd", sql_username: "ejabberd" }}
host_config: {"mc.mydomain.com": {auth_method: sql, sql_type: pgsql, sql_server: "localhost", sql_port: 5432, sql_database: "mydomain", sql_username: "mydomain" }}
</pre>
</details>

## Errors from error.log/crash.log

No errors

## Bug description

particularity
    - Use mod_shared_roster (EveryBody : @all@)
    - Use postgresql DB
    - **cluster (2 ejabberd server)**

benchmarking through tsung
    - 1000 tests
    - Login only test

```
# vi bsgw13.xml
--------------------------------------------------------------------------------
<!DOCTYPE tsung SYSTEM "/home/ubuntu/tsung-1.7.0/tsung-1.0.dtd" []>
<tsung loglevel="warning" dumptraffic="false" version="1.0">

    <clients>
        <client host="localhost" use_controller_vm="true" maxusers="2000"> </client>
    </clients>

    <servers>
        <server host="CLUSTER_SERVER_IP_ADDRESS_1" port="7222" type="tcp"/> 
        <server host="CLUSTER_SERVER_IP_ADDRESS_2" port="7222" type="tcp"/> 
    </servers>

    <load>
        <arrivalphase phase="1" duration="60" unit="minute">
          <users maxnumber="1000" arrivalrate="10" unit="second"></users>
          <session_setup name="jabber-login" probability="100"/>
        </arrivalphase>
    </load>

    <options>
        <option type="ts_jabber" name="global_number" value="100"></option>
        <option type="ts_jabber" name="userid_max" value="1000"></option>
        <option type="ts_jabber" name="domain" value="mc.mydomain.com"></option>
        <option type="ts_jabber" name="username" value="mytest_"></option>
        <option type="ts_jabber" name="passwd" value="password"></option>
    </options>

    <sessions>
        <session probability="100" name="jabber-login" type="ts_jabber" bidi="true">

            <transaction name="connect">
                <request> <jabber type="connect" ack="local" /> </request>
                <thinktime value="5"></thinktime>
                <request> <jabber type="starttls" ack="bidi_ack" /> </request>
                <request> <jabber type="connect" ack="local" /> </request>
            </transaction>

            <thinktime value="5"></thinktime>

            <transaction name="authenticate">
                <request> <jabber type="auth_sasl" ack="local"/> </request>
                <request> <jabber type="connect" ack="local"/> </request>
                <request> <jabber type="auth_sasl_bind" ack="local"/> </request>
                <request> <jabber type="auth_sasl_session" ack="local"/> </request>
            </transaction>

            <request> <jabber type="presence:initial" ack="no_ack"/> </request>

            <thinktime value="3000"></thinktime>

            <request> <jabber type="presence:final" ack="no_ack"/> </request>
            <thinktime value="30"></thinktime>

            <transaction name="close">
              <request> <jabber type="close" ack="local"> </jabber></request>
            </transaction>

        </session>
    </sessions>
</tsung>
--------------------------------------------------------------------------------
# tsung -f bsgw13.xml start
Starting Tsung
Log directory is: /root/.tsung/log/....
...
```

Online test user: Pidgin (XMPP Client) login
(Concurrent login with tsung)

```
$ /usr/local/ejabberd2003/sbin/ejabberdctl connected-users-number
1001
```
![online_users](https://user-images.githubusercontent.com/26269800/82777414-0633fd00-9e89-11ea-8f65-be482b0c1030.png)

Pidgin has 896 online users

**Why 1000 users are not online?**

(**I corrected my mistake**)

**Comment by badlop** [comment]
If you set 500 accounts, 500 are connected?
If you set 800 accounts, 800 are connected?

Maybe the problem with 1000 accounts is related to a system limit, like the "ulimit" mentioned in this tutorial: https://www.ejabberd.im/benchmark/index.html

**Comment by unturtle** [comment]
thank. badlop
This is the "ulimit" setting for servers.

* ejabberd server
```
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1031286
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1031286
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

# ps -ef | grep beam
root     12066 11589  0 08:58 pts/0    00:00:00 grep --color=auto beam
messeng+ 28101     1  4 May21 ?        05:35:19 /usr/local/erlang21/lib/erlang/erts-10.2/bin/beam.smp -K true -P 2500000 -- -root /usr/local/erlang21/lib/erlang -progname erl -- -home /home/messenger -- -sname ejabberd@intramessenger4 -smp auto -mnesia dump_log_write_threshold 50000 -mnesia dc_dump_limit 40 -kernel inet_dist_listen_min 4200 inet_dist_listen_max 4210 -mnesia dir "/usr/local/ejabberd2003/var/lib/ejabberd" -ejabberd log_rate_limit 1000 log_rotate_size 10485760 log_rotate_count 7 log_rotate_date "" -s ejabberd -noshell -noinput

# cat /proc/28101/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             65535                1031286              processes
Max open files            65535                65535                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       1031286              1031286              signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```
* tsung server 
```
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15080
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15080
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
* Pidgin xmpp client : My PC (windows 10)

* 500 connection test
```
# /usr/local/ejabberd2003/sbin/ejabberdctl connected-users-number
501
```
![online_users_500](https://user-images.githubusercontent.com/26269800/82850109-f0304600-9f35-11ea-9eca-03aeca742150.png)
* 500 connection second test
![online_users_500_2](https://user-images.githubusercontent.com/26269800/82850121-f7efea80-9f35-11ea-93ee-783aa4204dc5.png)

* 800 connection test
```
# /usr/local/ejabberd2003/sbin/ejabberdctl connected-users-number
801
```
![online_users_800](https://user-images.githubusercontent.com/26269800/82850130-0211e900-9f36-11ea-99ce-0c310234313f.png)

**Comment by unturtle** [comment]
Hi. badlop

It was tested with a single server without a cluster.
When testing 800 users, 800 people went online from Pidgin.
However, it took 35 minutes to reach 800 people.
It takes too long.

![s_online_users_800](https://user-images.githubusercontent.com/26269800/82978915-aff9c200-a020-11ea-8038-a404b32f6b2b.png)

**Comment by unturtle** [comment]
How to shorten the online recognition time of the other party in XMPP Client?
Previous versions (before version ejabberd 17) were fast

**Comment by licaon-kter** [comment]
Did you try https://github.com/processone/rtb yet?

**Comment by unturtle** [comment]
@licaon-kter 
No, I have neverli used rtb
Please tell me about usage or examples

**Comment by unturtle** [comment]
Tested using RTB.
The results were slow too.
It took **70~80 minutes** to recognize 1000 people online.
Below is the RTB test setup.

```
# grep -Ev '^$|^\s*#' rtb.yml
scenario: xmpp
interval: 100
capacity: 1000
certfile: mydomain_com.pem
jid: mytest_%@mc.mydomain.com
password: password%
servers:
  - tcp://SERVER_IP:7222
csi: false
sm: false
mam: false
carbons: false
blocklist: false
private: false
http_upload_interval: false
proxy65_interval: false
connect_timeout: 600
reconnect_interval: false
disconnect_interval: false
```
```
# ./rtb.sh
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V8.2  (abort with ^G)
(rtb@localhost)1> 13:14:14.494 [info] Application lager started on node rtb@localhost
13:14:14.494 [notice] Changed loghwm of log/rtb.log to 10000
13:14:14.502 [info] Application crypto started on node rtb@localhost
13:14:14.541 [info] Application inets started on node rtb@localhost
13:14:14.543 [info] Application p1_utils started on node rtb@localhost
13:14:14.571 [info] Application fast_yaml started on node rtb@localhost
13:14:14.572 [info] Application oneup started on node rtb@localhost
13:14:14.587 [info] Application asn1 started on node rtb@localhost
13:14:14.587 [info] Application public_key started on node rtb@localhost
13:14:14.603 [info] Application ssl started on node rtb@localhost
13:14:14.605 [info] Application cowlib started on node rtb@localhost
13:14:14.607 [info] Application gun started on node rtb@localhost
13:14:14.611 [info] Loading configuration from rtb.yml
13:14:14.655 [info] Application fast_xml started on node rtb@localhost
13:14:14.671 [info] Application stringprep started on node rtb@localhost
13:14:14.702 [info] Application fast_tls started on node rtb@localhost
13:14:14.714 [info] Application ezlib started on node rtb@localhost
13:14:14.736 [info] Application xmpp started on node rtb@localhost
13:14:14.737 [info] Capacity is 1000 sessions
13:14:15.077 [info] Found /usr/bin/gnuplot 4.6 patchlevel 2
13:14:15.077 [info] Arrival rate is 10.0 conn/sec
13:14:15.121 [info] Maximum available files from ulimit: 65535
13:14:15.121 [info] Maximum available files from fs.file-max: 100000
13:14:15.121 [info] Maximum available files from fs.nr_open: 1048576
13:14:15.121 [info] Maximum available Erlang processes: 65536
13:14:15.121 [info] Maximum available Erlang ports: 65536
13:14:15.195 [info] Accepting HTTP connections on port 8080
13:14:15.253 [info] Application sasl started on node rtb@localhost
13:14:15.275 [info] Application os_mon started on node rtb@localhost
13:14:15.275 [info] Application rtb started on node rtb@localhost

```

**Comment by licaon-kter** [comment]
What type of hardware? What type of network connection?


So this issue can be closed?

**Comment by unturtle** [comment]
"What type of hardware? What type of network connection? "

    ejabberd server 
        CPU : Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
        Memory : 256G
        Network : Gigabit Network 1G
    
    RTB server
        CPU : Intel(R) Xeon(R) CPU E5405  @ 2.00GH
        Memory : 32G
        Network : Gigabit Network 1G
    
    Pidgin (XMPP Client) 
        CPU : Intel(R) i5-3570
        Memory : 16G
        Network : intel Gigabit Network

"So this issue can be closed?"

    No.
    Can you shorten the online recognition time?

**Comment by licaon-kter** [comment]
What happens if you lower `interval:` ? Between the machines you have 1G bandwidth?

**Comment by unturtle** [comment]
thank, @licaon-kter 
I tested it.

In case of "interval: 3", only 600~700 users are connected.
In case of "interval: 30", 900~1000 users are connected.
Not all users (1000 users) are connected.
Even if the value of "interval:" is reduced, it takes 70 to 80 minutes for "Pidgin (XMPP Client)" to recognize the user online.
Time does not decrease at all.

**Comment by mremond** [comment]
I do not think this is a relevant issue there, as it seems to be a problem specific to benchmark tool and setup.

**Comment by unturtle** [comment]
thank @mremond 

It seems to me as a bug or performance issue with mod_shared_roster.
There was no problem with benchmarking in ejabberd versions before 17.04.
You can check if you test 1000 people online in the @all@ setting of the shared roster group.
It is not a problem with the benchmarking tool.

Please check it again

**Comment by mremond** [comment]
Shared roster were not designed to put thousands of users in it. Roster where not designed to put thousands of users in it. From your screenshot, it seems you have a roster with 6130 people. I would not do that.
