### ISSUE TITLE
OpenSSL error with Ejabberd 20.04

### ISSUE THREAD

**Issue by uli-a** [processone/ejabberd#3291]
I tried to install ejabberd 20.04 on openSUSE LEAP 15.1 using the installer. When starting the server I get the following error message:

`Failed to load NIF library: '/usr/lib64/libcrypto.so.1.0.0: version 'OPENSSL_1.0.1' not found`

I have openssl 1.1 installed on that server, but ejabberd 20.03 was running fine.

**Comment by badlop** [comment]
That's strange. From what I see comparing the installer files, I think that the file libcrypto.so.1.0.0 included in the ejabberd installers haven't changed since september 2018. Did you try with a recent installer?

**Comment by Neustradamus** [comment]
@uli-a: Can you try a recent installer?
