### ISSUE TITLE
Error - no match of right hand side value

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3295]
HEAD (https://github.com/processone/ejabberd/commit/482917348b0890cf656d7972abae0911d512debc), Debian Buster, arm64, erlang 21.2.6, 

```
[critical] <0.105.0>@ejabberd_app:start
:71 Failed to start ejabberd application: Exception occurred du
ring configuration processing. This is most likely due to fault
y/incompatible validator in third-party code. If you are not ru
nning any third-party code, please report the bug with ejabberd
 configuration file attached and the following stacktrace inclu
ded:
** exception error: no match of right hand side value
                  #{host => "upload.SOMEMACRO",path => [],schem
e => "https"}
   in function  yconf:uri_parse/1 (src/yconf.erl, line 369)
   in call from yconf:'-url/1-fun-0-'/2 (src/yconf.erl, line 37
7)
   in call from yconf:validate_option/3 (src/yconf.erl, line 12
27)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1
204)
   in call from yconf:'-and_then/2-fun-0-'/3 (src/yconf.erl, li
ne 629)
   in call from yconf:validate_option/3 (src/yconf.erl, line 12
27)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1
204)
   in call from yconf:validate_option/3 (src/yconf.erl, line 12
27)
```

Compiled as usual, git pull, make update, new libs versions appeared.

Went back to working 20.04.40 (https://github.com/processone/ejabberd/commit/7a37483307e1f62c750ecde8a088edacbe03c51f). 

Config like this: https://gist.github.com/dfc0b240754ed791d270a0c310730fed but also fails if I replace `@HOST@` with `mydomain.tld`.

**Comment by licaon-kter** [comment]
Same for 20.04.45 (https://github.com/processone/ejabberd/commit/cd336369a5691da8289574f402fa2311b6dc027c)
```
[critical] <0.270.0>@gen_mod:start_module:169 Internal error of module mod_http_upload has occurred during start:
** Options: #{access => local,custom_headers => [],dir_mode => undefined,
              docroot => <<"/var/www/ejabberd/upload">>,
              external_secret =>
                  <<"thiswasasecret">>,
              file_mode => undefined,get_url => undefined,
              host => <<"upload.mydomain.tld">>,hosts => [],jid_in_url => sha1,
              max_size => 104857600,name => <<"HTTP File Upload">>,
              put_url => <<"https://upload.@HOST@">>,rm_on_unregister => true,
              secret_length => 40,service_url => undefined,thumbnail => false,
              vcard => undefined}
** exception error: no match of right hand side value 
                  #{host => <<"upload.mydomain.tld">>,path => <<>>,
                    scheme => <<"https">>}
   in function  misc:uri_parse/1 (src/misc.erl, line 66)
   in call from mod_http_upload:get_proc_name/3 (src/mod_http_upload.erl, line 715)
   in call from mod_http_upload:start/2 (src/mod_http_upload.erl, line 129)
   in call from gen_mod:start_module/4 (src/gen_mod.erl, line 155)
   in call from lists:foreach/2 (lists.erl, line 1338)
   in call from gen_mod:start_link/0 (src/gen_mod.erl, line 82)
   in call from supervisor:do_start_child_i/3 (supervisor.erl, line 379)
   in call from supervisor:do_start_child/2 (supervisor.erl, line 365)
2020-06-04 22:17:10.363 [critical] <0.270.0>@gen_mod:maybe_halt_ejabberd:256 ejabberd initialization was aborted because a module start failed.
```
...but maybe this was known, given the following commits? @weiss

**Comment by lorddavidiii** [comment]
I also had this problem, adding a port number to the  `put_url` fix this, something like https://github.com/processone/ejabberd/commit/945a5cd09cf055a3acd08db8aebce11e8f88fe29 is missing https://github.com/processone/yconf/blob/8cf73f97715093939bce5f0d04d1c5ad9ea59109/src/yconf.erl#L369 I think

**Comment by weiss** [comment]
Yes.  I'm looking into a proper fix (both for `processone/yval` and for ejabberd's `src/misc.erl`).

**Comment by badlop** [comment]
Maybe something like this, that handles all the possible cases: being a binary, having @HOST@ and missing port number:

```erlang
uri_parse(URL) when is_binary(URL) ->
    uri_parse(binary_to_list(URL));
uri_parse(URL) ->
    case re:run(URL, "@([A-Z]+)@", [{capture, all, list}]) of
        nomatch ->
            uri_parse2(URL);
        {match, [AtMacroAt, Macro]} ->
            URL2 = re:replace(URL, "@[A-Z]+@", Macro),
            {ok, Scheme, Host, Port, Path} = uri_parse2(URL2),
            Host = Macro,
            {ok, Scheme, AtMacroAt, Port, Path}
    end.
uri_parse2(URL) ->
    case uri_string:parse(URL) of
	#{scheme := Scheme, host := Host, port := Port, path := Path} ->
	    {ok, Scheme, Host, Port, Path};
	#{scheme := "https", host := Host, path := Path} ->
	    {ok, "https", Host, 443, Path};
	#{scheme := "http", host := Host, path := Path} ->
	    {ok, "http", Host, 80, Path}
    end.
```

**Comment by weiss** [comment]
@badlop, the problems to solve are a bit different from those in `misc:uri_parse`:

- The validator doesn't need to come up with a default port (the goal is just rejecting invalid port numbers).
- The validator should fail gracefully on arbitrary invalid input, which includes input that `uri_string:parse/1` and/or `http_uri:parse/1` will reject with an `{error, Reason}`, as well as URIs that don't have a scheme and/or host component.  I have some fixes that I'm testing right now.

**Comment by licaon-kter** [comment]
Looks fixed, thanks.

@weiss Should I ignore `[warning] <0.521.0>@mod_stream_mgmt:log_resumption_error:805 Cannot resume session for user@domain.tld: Invalid 'previd' value` that I now get on restart?

**Comment by weiss** [comment]
@licaon-kter, yes, the `previd` format has changed in cd336369a5691da8289574f402fa2311b6dc027c, so if you're upgrading from a version before that commit, the warning is to be expected for attempts to resume sessions opened before the restart.  It's not to be expected in the future.
