### ISSUE TITLE
https://www.process-one.net is showing "403 Forbidden"

### ISSUE THREAD

**Issue by scott91e1** [processone/ejabberd#3298]
Just a heads up there seems to be a problem with the site.

**Comment by licaon-kter** [comment]
Works here, retry?

**Comment by f055** [comment]
Thanks @scott91e1 for the report – looked like a momentary glitch with our provider, but all is good for me.

**Comment by scott91e1** [comment]
Its still doing it from Australia.  https://www.ejabberd.im/ works OK but any of the links in the footer that such as https://www.process-one.net/en/company/contact/ return the 403 as well.  Its being returned from nginx.

**Comment by scott91e1** [comment]
Just FYI, on https://www.uptimia.com/website-availability-test its showing down for Sydney and Tokyo and working everywhere else.  Very odd.

**Comment by f055** [comment]
Hmm indeed there's something going on. Debugging :)

**Comment by f055** [comment]
Ok, it seems something is wrong in your region and/or with Uptimia. If you test other domains, even google.com, it always shows downtime for Tokyo and Sydney. I run a VPN via Australia and the site worked fine. Nonetheless, thanks for the report!

**Comment by scott91e1** [comment]
I checked the SSL fingerprints from the nginx 403 and a successful response and they match which suggests its the wpengine.com nginx that is miss configured.  I have downloaded the software OK using my mobile internet so its not causing me any issues but you might like to take the issue up with wpengine support...
