### ISSUE TITLE
ejabberd + mssql + rhel creating odbcinst.ini in /tmp/ejabbered - timing out

### ISSUE THREAD

**Issue by zxed** [processone/ejabberd#3299]
## Environment

- ejabberd version: 20.04
- OS: RHEL 8 (AWS)
- Installed from: rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
sql_type: mssql
sql_server: "some.public.host.name"
sql_database: "db"
sql_username: "ejabberd"
sql_password: "some$password"
sql_pool_size: 5
...
```

## Errors from error.log/crash.log

```
2020-06-12 02:18:14 =ERROR REPORT====
** Generic server <0.510.0> terminating
** Last message in was {<0.452.0>,
  {connect,1,1,2,2,2,1,1,"DRIVER=FreeTDS;SERVER=some.public.host.name;
  UID=ejabberd;DATABASE=db;PWD=some$password;
  PORT=1433;CLIENT_CHARSET=UTF-8;"],on,off},5000}
** When Server state == {state,#Port<0.53>,{<0.452.0>,#Ref<0.2789227436.861929474.261354>}, 
 <0.452.0>,undefined,on,undefined,undefined,off,connecting,undefined,0, 
 [#Port<0.51>,#Port<0.52>],undefined,undefined}
** Reason for termination ==
** timeout
```

## Bug description

I'm following https://computingforgeeks.com/how-to-install-ejabberd-xmpp-server-on-rhel-8/ to get ejabberd installed on RHEL 8 (using the latest 20.04).

I'm also following a steps (1-3) from https://zend18.zendesk.com/hc/en-us/articles/218197897-Configuring-a-Linux-Server-to-Connect-to-an-MSSQL-Database-Using-ODBC

I've installed MS SQL on AWS RDS, VM with Sql on Azure and a SQL Azure Db - all have the same issue, which is that - isql connects and works so does tsql - but not ejabberd

As part of setting up unixODBC+Freetds - it had me look for libtdsodbc  and update /etc/odbcinst.ini - which turns out to have two matches, /lib64/libtdsodbc.so.0 and /lib64/libtdsodbc.so (i used /lib64/libtdsodbc.so.0 and as I mentioned isql and tsql work., so id assume that ive set this up correctly)

I did notice that in /tmp/ejabberd there is another odbcinst.ini and this has 

```
[FreeTDS]
Driver = libtdsodbc.so
```

I do not know if this is the issue - it seems like this is being created by ejabberd https://github.com/processone/ejabberd/blob/20.04/src/ejabberd_sql.erl#L1155 instead of using the existing (and maybe correct?) file thats sitting at /etc/odbcinst.ini

I'm still trying to get a handle on this - but thought I'd ask if this could be causing the issue with connecting from ejabberd (but no issues when using isql)

**Comment by zxed** [comment]
I reinstalled 20.03 so that it would use DSN instead of DSN-less; and it wasnt working.

i notice that the crash log was telling me that it was using my host for DSN - but since it was on AWS the host was pretty long, or the format of it, was causing freetds to fail...

so i made it simple, matched my odbc.ini and freetds to it - and it still wasnt working

I re-read this whole thread again, and that got to this comment again https://github.com/processone/ejabberd/issues/2295#issuecomment-378623785

I figured I'd give it a go... the first one ran - the 2nd one said the file already existed

`ln -s /usr/lib64/libodbc.so.2.0.0 /usr/lib64/libodbc.so.1`

and trying it again - things worked..

So - Im going to go back to the most recent RHEL ,machine running 20.04 and will try this there too and see if it fixes it....

**Comment by zxed** [comment]
Verifying that running 

`ln -s /usr/lib64/libodbc.so.2.0.0 /usr/lib64/libodbc.so.1`

 solves it

**Comment by badlop** [comment]
Thanks for commenting it! This will help if somebody else gets that error message.
