### ISSUE TITLE
Getting error while installling ejabberd

### ISSUE THREAD

**Issue by RomitGandhi07** [processone/ejabberd#3300]
## Environment

- ejabberd version: 20.04
- OS: Windows 10
- Installed from: official binary installer 

![Error](https://user-images.githubusercontent.com/46276226/84497740-fc095f80-accc-11ea-87a5-4fa658239f28.PNG)

## Errors from error.log/crash.log
No errors

## Bug description

I'm trying to install ejabberd but getting the error that **Error Running Post Install Script**

**Comment by badlop** [comment]
@RomitGandhi07 have you tried the solution mentioned in the comment https://github.com/processone/ejabberd/issues/3292#issuecomment-649020711 ?

**Comment by mremond** [comment]
This is a known issue. We have to rework the windows installer.

**Comment by mremond** [comment]
Closing for now: The Windows installer has been discontinued in favor of Docker on Windows: https://www.process-one.net/blog/install-ejabberd-on-windows-10-using-docker-desktop/
