### ISSUE TITLE
Hook disco_local_features crashed when running mod_stun_disco:disco_local_features

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3304]
## Environment

- ejabberd version: 20.04
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4
- OS: Linux (Debian)
- Installed from: distro package

## Configuration (only if needed): 
Please request relevant parts is required.

## Errors from error.log
```
[error] <0.423.0>@ejabberd_hooks:safe_apply:240 Hook disco_local_features crashed when running mod_stun_disco:disco_local_features/5:
** exception error: bad argument
   in function  re:run/2
      called as re:run(<<>>,
                       {{re_pattern,0,1,0,
                                    <<69,82,67,80,71,0,0,0,0,8,0,0,1,128,0,0,
                                      255,255,255,255,255,255,255,255,0,0,0,0,
                                      0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,0,
                                      3,120,0,3,0>>},
                        <<"example\\.com$">>})
   in call from acl:match_regexp/2 (acl.erl, line 352)
   in call from lists:any/2 (lists.erl, ...
** Arg 1 = {result,[<<"jabber:iq:privacy">>,<<"urn:xmpp:carbons:2">>,<<"urn:xmpp:carbons:rules:0">>,<<"urn:xmpp:blocking">>,<<"msgoffline">>,<<"http://jabber.org/protocol/offline">>]}
** Arg 2 = {jid,<<>>,<<"example.com">>,<<>>,<<>>,<<"example.com">>,<<>>}
** Arg 3 = {jid,<<>>,<<"example.com">>,<<>>,<<>>,<<"example.com">>,<<>>}
** Arg 4 = <<>>
** Arg 5 = <<>>
```
and
```
[error] <0.436.0>@ejabberd_hooks:safe_apply:240 Hook disco_local_features crashed when running mod_stun_disco:disco_local_features/5:
** exception error: bad argument
   in function  re:run/2
      called as re:run(<<"myname">>,
                       {{re_pattern,0,1,0,
                                    <<69,82,67,80,71,0,0,0,0,8,0,0,1,128,0,0,
                                      255,255,255,255,255,255,255,255,0,0,0,0,
                                      0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,0,
                                      3,120,0,3,0>>},
                        <<"example\\.com$">>})
   in call from acl:match_regexp/2 (acl.erl, line 352)
   in call from lists:any/2 (lis...
** Arg 1 = {result,[<<"jabber:iq:privacy">>,<<"urn:xmpp:carbons:2">>,<<"urn:xmpp:carbons:rules:0">>,<<"urn:xmpp:blocking">>,<<"msgoffline">>,<<"http://jabber.org/protocol/offline">>]}
** Arg 2 = {jid,<<"myname">>,<<"example.com">>,<<"Conversations.F0Y0">>,<<"myname">>,<<"example.com">>,<<"Conversations.F0Y0">>}
** Arg 3 = {jid,<<>>,<<"example.com">>,<<>>,<<>>,<<"example.com">>,<<>>}
** Arg 4 = <<>>
** Arg 5 = <<"en">>
```

## Bug description

These appear in my log-files. Can't give more information, sorry.

**Comment by licaon-kter** [comment]
Your logfile...yes...,can't give your config either?

**Comment by htgoebel** [comment]
@licaon-kter I doubt publishing my whole config is of much use for tracking down an exception. I will provide relevant parts, of course.

**Comment by weiss** [comment]
> I doubt publishing my whole config is of much use for tracking down an exception.

It would help to see the access rule(s) referenced by your `mod_stun_disco` configuration (if you didn't specify an `access:` rule name explicitly, the default is `local`), plus the `acl`(s) referenced by those.

**Comment by htgoebel** [comment]
Here are the respective parts of the config:
```
  mod_disco:
    name: "servername" # enhance security by obscurity
    server_info:
      - modules: all
        name: abuse-addresses
        urls: [ ADMIN_MAIL_URL ]

access_rules:
  local:
    - deny: blocked
    - allow: local

acl:
  local:
    - user_regexp: "@example\\.com$"  # TODO better use user_glob?
  blocked:
    - user: []
```

**Comment by licaon-kter** [comment]
`mod_disco` is something else...attach the `mod_stun_disco` config as the error says.

**Comment by prefiks** [comment]
Hello,

Do you have example.com listed in your ejabberd hosts: section? In your case you probably can just use `server: "example.com"`, it will accept anything@example.com.

**Comment by prefiks** [comment]
I commited 768460b518ca77fb6cf4a38291610a218acd44a4 that should stop that crash.

But even with this fix you rule will not work as you expect in user_regexp part after @ is not regexp, so working equivalent would be `user_regexp: ".*@example.com"`, or even better just use `server: "example.com"`

**Comment by weiss** [comment]
```yaml
  local:
    - user_regexp: "@example\\.com$"  # TODO better use user_glob?
```

The domain part of a `user_regexp` is not a regular expression, as explained in [the documentation][1]:

> If Regexp is in the form of "regexp@server", the rule matches any JID with node part matching regular expression "regexp" as long as the server part of this JID is equal to "server".

To configure it the way you intended you could configure `user_regexp: "@example.com"`, or, better, follow @prefiks' suggestion.  However, `local` is the one `acl` where I'd just stick to the [default configuration][2] (`user_regexp: ""`), which lets the `local` `acl` match all local users.

[1]: https://docs.ejabberd.im/admin/configuration/toplevel/#acl
[2]: https://github.com/processone/ejabberd/blob/20.04/ejabberd.yml.example#L76-L77

**Comment by htgoebel** [comment]
@prefiks No matter what is wron in my config, I would expect ejabberd to no raise an exception but issue an error message. So please reopen.

**Comment by weiss** [comment]
> I would expect ejabberd to no raise an exception but issue an error message.

Of course.  Maybe you [overlooked][1] that @prefiks fixed that bug already?

[1]: https://github.com/processone/ejabberd/issues/3304#issuecomment-647367028

**Comment by htgoebel** [comment]
@licaon-kter Here is the part for mod_stun_disco:
```
mod_stun_disco: {}  
```

**Comment by htgoebel** [comment]
@weiss @prefiks Indeed I overlook the fixm sorry.  (I'm used to ready "closed this by <commit-id>")
