### ISSUE TITLE
Can't handle a custom IQ stanza

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3306]
## Environment

- ejabberd version: 20.02.06
- Erlang version: `10.6.4`
- OS: Linux (Debian)
- Installed from: source 

## I created a new module `mod_mymodule` for example, I did the all instructions according to the article here: [https://github.com/processone/xmpp/issues/9](https://github.com/processone/xmpp/issues/9)
and created a file `mymodule.erl`:
```
%% Created automatically by XML generator (fxml_gen.erl)
%% Source: xmpp_codec.spec

-module(mymodule).

-compile(export_all).

do_decode(<<"mymodule">>,
	  <<"custom:ns">>, El, Opts) ->
    decode_mymodule(<<"custom:ns">>,
			       Opts, El);
do_decode(Name, <<>>, _, _) ->
    erlang:error({xmpp_codec, {missing_tag_xmlns, Name}});
do_decode(Name, XMLNS, _, _) ->
    erlang:error({xmpp_codec, {unknown_tag, Name, XMLNS}}).

tags() ->
    [{<<"mymodule">>,
      <<"custom:ns">>}].

do_encode({mymodule} = Mymodule,
	  TopXMLNS) ->
    encode_mymodule(Mymodule,
			       TopXMLNS).

do_get_name({mymodule}) ->
    <<"mymodule">>.

do_get_ns({mymodule}) ->
    <<"custom:ns">>.

pp(mymodule, 0) -> [];
pp(_, _) -> no.

records() -> [{mymodule, 0}].

decode_mymodule(__TopXMLNS, __Opts,
			   {xmlel, <<"custom:ns">>, _attrs, _els}) ->
    {mymodule}.

encode_mymodule({mymodule},
			   __TopXMLNS) ->
    __NewTopXMLNS =
	xmpp_codec:choose_top_xmlns(<<"custom:ns">>,
				    [], __TopXMLNS),
    _els = [],
    _attrs = xmpp_codec:enc_xmlns_attrs(__NewTopXMLNS,
					__TopXMLNS),
    {xmlel, <<"mymodule">>, _attrs, _els}.
```

The function in the file `mod_mymodule.erl` is:
```
start(Host, Opts) ->
  ?DEBUG("module x-roster started", []),
  xmpp:register_codec(mymodule),
  gen_iq_handler:add_iq_handler(ejabberd_local, Host,
    ?NS_WB_XROSTER, ?MODULE, process_sm_iq),
  gen_iq_handler:add_iq_handler(ejabberd_sm, Host,
    ?NS_WB_XROSTER, ?MODULE, process_sm_iq).


stop(Host) ->

  xmpp:unregister_codec(mymodule),
  gen_iq_handler:remove_iq_handler(ejabberd_local, Host,
    ?NS_WB_XROSTER),
  gen_iq_handler:remove_iq_handler(ejabberd_sm, Host,
    ?NS_WB_XROSTER).
```
and when I send the stanza:
```
 <iq type='get'
                to='myname@my.xmpp.com'
                id='info1'>
  <mymodule xmlns='custom:ns'/>
</iq>
```
I get the error:
```
<error code="400" type="modify">
<bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">
Unknown tag &lt;mymodule/&gt; qualified by namespace 'custom:ns'</text>
</error>
```
Any idea?

**Comment by prefiks** [comment]
Did you start that module? It looks like xmpp:register_codec was not called for your spec.

**Comment by relbraun** [comment]
Yes. I started the module using: `ejabberdctl module_install mod_mymodule`.
I didn't understand what you mean "It looks like xmpp:register_codec was not called for your spec."
What should I do? @prefiks 
Thanks

**Comment by prefiks** [comment]
I mean did you put that module in modules section of your ejabberd config? This should start it, and trigger registration of that xmpp codec.

**Comment by relbraun** [comment]
Yes. I put it in `.ejabber-modules` direcory.
Now I noticed that in order to make the module handle the stanza, I have to:

1. remove it from the `ejabberd.yml` file and save
2. uninstall it using `uninstall_module` command
3. insert it to `ejabberd.yml` file and save
4. re-install using `install_module` command.

very weird.
