### ISSUE TITLE
Some simple documentation clarifications

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3307]
Please clarify in the documentation:
* Global options: Will `c2s_{protocoll_options,ciphers,dhfile}` provided defaults to the "listen" modules? Same for `s2s_*`
* Listen-options: Are ciphers, dhfile, protocoll_options defaulting to the global `c2s` resp. `s2s` options?
* What module/function is using `s2s_starttls`? Is this for outgoing messages, and thus needs to be defined here (as this is not a listening module)

* Hat is the meaning of `hosts` in mod_http_upload, mod_muc, mod_mix and others?
  What is this used for? Can one use `@HOST@` (without any prefix)?
  What is the benefit of listing more than one hosts / JIDs?

* mod_pres_counter: `interval`: Unit of value us not documented.

* Meaning of mod_register: `access_from` is unclear: Description lets assume this is for controlling registration of new accounts from s2s or existing c2s sessions. But This is not stated.

* `mod_stun` has an option to enable TLS, but what ciphers, dhfile, and protocoll_options are used?

Many thanks in advance for improving the documentation :-)

**Comment by licaon-kter** [comment]
Close this and reopen in https://github.com/processone/docs.ejabberd.im instead if this info is missing from https://docs.ejabberd.im

**Comment by htgoebel** [comment]
Moved to https://github.com/processone/docs.ejabberd.im/issues/94
