### ISSUE TITLE
How to attach etop?

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3308]
HEAD, Debian Buster, arm64

**$ sudo -u ejabberd ejabberdctl status**
```
The node ejabberd@localhost is started with status: started
ejabberd 20.04.64 is running in that node
```
ok...so...
**$ sudo /usr/lib/erlang/lib/observer-2.8.2/priv/bin/etop -node ejabberd@localhost -sort reductions**
```
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Error Couldn't connect to node ejabberd@localhost

Usage of the Erlang top program

Options are set as command line parameters as in -node my@host
or as parameters to etop:start([{node, my@host}, {...}]).

Options are:
  node        atom       Required   The erlang node to measure
  port        integer    The used port, NOTE: due to a bug this program
                         will hang if the port is not avaiable
  accumulate  boolean    If true execution time is accumulated
  lines       integer    Number of displayed processes
  interval    integer    Display update interval in secs
  sort        runtime | reductions | memory | msg_q
                         What information to sort by
                         Default: runtime (reductions if tracing=off)
  tracing     on | off   etop uses the erlang trace facility, and thus
                         no other tracing is possible on the node while
                         etop is running, unless this option is set to
                         'off'. Also helpful if the etop tracing causes
                         too high load on the measured node.
                         With tracing off, runtime is not measured!
  setcookie   string     Only applicable on operating system command
                         line. Set cookie for the etop node, must be
                         same as the cookie for the measured node.
                         This is not an etop parameter
{"init terminating in do_boot","connection error"}
init terminating in do_boot (connection error)

Crash dump is being written to: erl_crash.dump...done
```
...right...the log says: `[error] <0.9454.0> ** Connection attempt from disallowed node etop@rpi3 **` _(and erl_crash.dump is created)_ maybe it doesn't like to be run as root:
**$ sudo -u ejabberd /usr/lib/erlang/lib/observer-2.8.2/priv/bin/etop -node ejabberd@localhost -sort reductions**
```
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

{"init terminating in do_boot",{{badmatch,{error,nxdomain}},[{etop_tr,reader,1,[{file,"etop_tr.erl"},{line,62}]},{etop,init_data_handler,1,[{file,"etop.erl"},{line,146}]},{etop,start,1,[{file,"etop.erl"},{line,129}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,nxdomain}},[{etop_tr,reader,1,[{_},{_}]},{etop,init_data_handler,1,[{_},{_}]},{etop,start,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...
```
...but erl_crash.dump is NOT created

I'd like to see why Jicofo is hammering ejabberd continuously at 80% of one core while being idle...but...not sure how, there's no logging of stuff happening in loglevel 4 so far, also nothing in their logs.

**Comment by weiss** [comment]
The user running etop needs to have the `~ejabberd/.erlang.cookie` in his `$HOME` directory.

**Comment by prefiks** [comment]
In first case problem is with erlang cookie, usually it's #HOME/.erlang.cookie, just make sure they match on all users.

**Comment by badlop** [comment]
In my dev machine, where I run ejabberd locally:
```
$ ejabberdctl live
> observer:start().
```
and it opens a bunch of GUI tools

**Comment by licaon-kter** [comment]
So `status` works, so `register` works....but that user doesn't have the cookie when I run etop? Please detail some more then...

**Comment by licaon-kter** [comment]
@badlop what's a GUI? :)) c'mon...

**Comment by prefiks** [comment]
Comment about cookie was talking about first error, about disalowed node.

In second one i can't really help you, as i don't use etop, but i am guessing you have error in etop config or something as that crash is from gen_tcp:connect - it tries to connect to address that it can't resolve.

**Comment by weiss** [comment]
> So `status` works, so `register` works....

For root, `ejabberdctl` works without a cookie in root's `$HOME` directory, as `ejabberctl` does `su "$ejabberd" ...`.

**Comment by licaon-kter** [comment]
First one you mean as root? Ok, skip that

Second as user `ejabberd`...what address exactly? It's the localhost node....the same it spits when I do `status`, what am I supposed to enter?

**Comment by licaon-kter** [comment]
@weiss Everything works as user ejabberd for ejabberdctl, as my first quote shows.

**Comment by badlop** [comment]
Is this problem still present? This works correctly for me:

```shell
ejabberdctl etop
```

**Comment by licaon-kter** [comment]
@badlop is that a sekret command? Not sure where it's documented :-|

**Comment by jaspreet-android** [comment]
This can help I guess:
https://github.com/esl/MongooseIM/issues/3168
