### ISSUE TITLE
logger doesn't work on my module

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3311]
## Environment

- ejabberd version: 20.02.06
- Erlang version: `10.6.4`
- OS: Linux (Debian)
- Installed from: source 

I created a module in the local repository directory `.ejabberd-modules` and put in the code the syntax:

```
-include("logger.hrl").
-include("xmpp.hrl").
-include("ejabberd_commands.hrl").
-include("mod_privacy.hrl").
-include("mod_last.hrl").
-include("translate.hrl").
-include("ejabberd_sql_pt.hrl").

...

start(Host, Opts) ->
  ?DEBUG("module xxxx started", []),
  xmpp:register_codec(some_codec),
  gen_iq_handler:add_iq_handler(ejabberd_local, Host,
    ?NS_WB_XROSTER, ?MODULE, process_sm_iq),
  gen_iq_handler:add_iq_handler(ejabberd_sm, Host,
    ?NS_WB_XROSTER, ?MODULE, process_sm_iq).


stop(Host) ->

  xmpp:unregister_codec(some_codec),
  gen_iq_handler:remove_iq_handler(ejabberd_local, Host,
    ?NS_WB_XROSTER),
  gen_iq_handler:remove_iq_handler(ejabberd_sm, Host,
    ?NS_WB_XROSTER).

depends(_Host, _Opts) ->
  [].

mod_options(_Host) ->
  [].

process_sm_iq() ->
    ?ERROR_MSG("some message", []),
    xmpp:make_iq_result(IQ, Somestuff).
```
And I see nothing in the `ejabberd.log` file

**Comment by prefiks** [comment]
Is your module started? Is there any mention of your module in ejabberd.log? You should get info about started modules, but you may need to start ejabberd with loglevel:5 for that.

**Comment by relbraun** [comment]
the loglevel is 5 and the module is started. I see nothing in the ejabberd.log regarding to my module.

**Comment by prefiks** [comment]
I mean you don't have 'Loading mod_<mymodule>' in your log? If not then that module was not started, please make sure it's in modules section of your config file.

**Comment by relbraun** [comment]
I have this line in the log file:
```
2020-06-23 12:52:40.891 [debug] <0.19624.0>@gen_mod:start_module:153 Loading mod_my_module at my-server.com

**Comment by Kalmuraee** [comment]
I've similar issue, I've starter ejabberd inside docker , I've loaded the modules , the modules seems loaded according to the logs, but I've tried accessing web admin it's inaccessible and Yes, I've used host network mode. I'm trying to figure it out.  😧

**Comment by badlop** [comment]
Following the steps described in http://localhost:8080/developer/extending-ejabberd/modules/#add-your-module logging works for me. Try it, and reopen this ticket if it still fails.
