### ISSUE TITLE
Mysql connection failed, reason normal

### ISSUE THREAD

**Issue by gizmo15** [processone/ejabberd#3312]
Hi,

I have an installation with 2 ejabberd nodes connected on the same database (galera cluster via haproxy for load balancing).

## Environment

- ejabberd version: 20.04
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2
- OS: Ubuntu 18.04
- Installed from: official deb/rpm

All nodes have the same configuration :
<details>
<pre>
hosts:
  - "node1.ndd.loc"
  - "ndd1.com"
  - "ndd2.com"
loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 1
certfiles:
  - "/etc/ssl/node1.ndd.loc.cmb.pem"
  - "/etc/ssl/ndd.pem"
  - "/etc/ejabberd/ejabberd.pem"
ca_file: "/opt/ejabberd/conf/cacert.pem"
define_macro:
  'TLS_CIPHERS': "HIGH:!SHA1:!MD5:!RC4:!aNULL:!eNULL:!3DES:@STRENGTH"
  'TLS_OPTIONS':
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
    - "no_compression"
  'DH_FILE': "/etc/ssl/dhparams.pem"
c2s_dhfile: 'DH_FILE'
s2s_dhfile: 'DH_FILE'
c2s_ciphers: 'TLS_CIPHERS'
s2s_ciphers: 'TLS_CIPHERS'
c2s_protocol_options: 'TLS_OPTIONS'
s2s_protocol_options: 'TLS_OPTIONS'
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
    tls: true
    protocol_options: 'TLS_OPTIONS'
  -
    port: 1883
    ip: "::"
    module: mod_mqtt
    backlog: 1000
s2s_use_starttls: optional
default_db: sql
sql_type: mysql
sql_server: "haproxy.nd.loc"
sql_database: "ejabberd"
sql_username: "USER"
sql_password: "PASSWORD"
sql_port: 3306
sql_pool_size: 20
sql_keepalive_interval: 28800
acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128
      - ::FFFF:127.0.0.1/128
  admin:
    user:
      - "admin@node1.ndd.loc"
access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number
shaper:
  normal: 1000
  fast: 50000
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast
max_fsm_queue: 10000
acme:
   contact: "mailto:admin@node1.ndd.loc"
   ca_url: "https://acme-v02.api.letsencrypt.org/directory"
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
</pre>
</details>

The second node, no problem.
The first one, i have those entries in ejabberd.log :

```
2020-06-24 15:39:04.189 [error] <0.906.0>@ejabberd_sql:log:1082 p1_mysql_conn: Connection closed, exiting.
2020-06-24 15:39:04.189 [info] <0.906.0>@ejabberd_sql:log:1081 Closing connection {gen_tcp,#Port<0.162>}: ok
2020-06-24 15:39:04.189 [error] <0.907.0>@ejabberd_sql:log:1082 p1_mysql_conn: Connection closed, exiting.
2020-06-24 15:39:04.190 [info] <0.907.0>@ejabberd_sql:log:1081 Closing connection {gen_tcp,#Port<0.163>}: ok
2020-06-24 15:39:04.190 [warning] <0.565.0>@ejabberd_sql:handle_reconnect:471 mysql connection failed:
** Reason: normal
** Retry after: 30 seconds
```

It's confusing me, "reason : normal" so it's ok or i have a problem in my setup?

Haproxy configuration :
```
listen galera
    bind X.X.X.X:3306
    balance source
    mode tcp
    option tcplog
    option tcpka
    timeout client 5m
    timeout server 5m
    server galera1 XXXXXX:3306 check weight 100
    server galera2 XXXXXX:3306 check weight 100
    server galera3 XXXXXX:3306 check weight 80
    server galera4 XXXXXX:3306 check weight 80
```

Thanks!

**Comment by prefiks** [comment]
It's likely ok, it just inform that connection process was terminated (due to socket being closed), and that reconnect will be triggered.

**Comment by gizmo15** [comment]
So, i don't need to modify anything in the configuration?

**Comment by prefiks** [comment]
Should be ok, probably those connections are closed ocasionaly by mysql server from inactivity, but if that doesn't happen very often i don't think you need to make changes.

**Comment by gizmo15** [comment]
ok, thanks for the confirmation!
