### ISSUE TITLE
SSL ON Public IP

### ISSUE THREAD

**Issue by LumiProj** [processone/ejabberd#3314]
Hi,

I am running ejabberd on Windows server 2008 on static/public IP . Now I am looking to add secure certificate on IP .

Please guide me any reference or details that I can configure any free certificate to secure my ejabberd public IP.

Thanks

**Comment by licaon-kter** [comment]
Look for ACME: https://docs.ejabberd.im

**Comment by LumiProj** [comment]
Hi,
Thank you so much.
Well I have followed the docs and when I jump into certificate request command using Command Prompt of Windows I am getting this error.

C:\Program Files\ejabberd-20.04\bin>ejabberdctl request-certificate all
Error: error
Error: "You have no virtual hosts acceptable for ACME certification"

but I have one vhost is running on public IP.

PLEASE GUIDE ME IS THERE SOMETHING I AM MISSING.

Thanks

**Comment by licaon-kter** [comment]
Share your config, in a Github gist, remove sensitive stuff.

**Comment by LumiProj** [comment]
Hi,

I have already replaced the sensitive data.
###
###'           ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###

hosts:
  - "11.11.11.11"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

certfiles:
  - "C:/ProgramData/ejabberd/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
##  - "/etc/letsencrypt/live/localhost/privkey.pem"

ca_file: "C:/ProgramData/ejabberd/conf/cacert.pem"

listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: false
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: 5443
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/captcha": ejabberd_captcha
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/oauth": ejabberd_oauth
  -
    port: 5280
    module: ejabberd_http
    tls: true
    request_handlers:
      "/admin": ejabberd_web_admin
      "/ws": ejabberd_http_ws
      "/well-known/acme-challenge": ejabberd_acme
  -
    port: 1883
    module: mod_mqtt
    backlog: 1000

s2s_use_starttls: optional

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
  admin:
    user:
      - "admin@11.11.11.11"

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
  register:
    allow: all
    
api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          acl: loopback
          acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            acl: loopback
            acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000

acme:
     ca_url: https://acme-staging-v02.api.letsencrypt.org/directory
 

modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: never
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      mam: false
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  
  mod_register:
    access_from:
      register_from
    access: 
      register   
  
   ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    # ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8

**Comment by licaon-kter** [comment]
HostNAME right? You did not put an IP there, like the error says, right? You bought a domain, right?

**Comment by LumiProj** [comment]
Well client wanted to configure on IP Address they didn't bought the domain yet.
In first phase they wanted to integrate the ejabberd into their apps.
so currently I have configured their ejabberd server on public/static IP everything is working great except SSL.

So the bottom line is I am looking to add SSL on IP not on domain.
If their is way to achieve so that would be awesome. In future they would infidelity go for the domain.

Thanks

**Comment by licaon-kter** [comment]
So generate a local self-signed cert with openssl and that's all.

/close this

**Comment by weiss** [comment]
Thank you, @licaon-kter.

**Comment by LumiProj** [comment]
Hi,

I have successfully generated the certificate using **OpenSSL**.

Now I have 4 files.
1) Certificate.pem
2) key.pem
3) PublicCert.pem
4) cert.pfx

Now in ejabberd configuration I need to know which files should I copy to conf folder
and how to declare the reference inside configuration file.
There is a section of certfiles, 

**certfiles:**
  - "C:/ProgramData/ejabberd/conf/server.pem"
##  - "/etc/letsencrypt/live/localhost/fullchain.pem"
    "C:/ProgramData/ejabberd/conf/privkey.pem"
ca_file: "C:/ProgramData/ejabberd/conf/cacert.pem"



can you please help me on this regard.

I would really appreciate the positive response.

Thanks

**Comment by AtifShahzed** [comment]
Hi,

I followed this link which helped me but need help from someone.

https://ifconfigblog.wordpress.com/2016/03/01/how-to-generate-self-signed-certificate-for-ejabberd


Confusion is in the final lines which can be found from the above link as well.

**_"Final step is that you have to cat the certificate file and key file into one file (server.pem) and replace the server.pem file in the configuration directory of ejabberd"_**

Can someone guide me what does it mean open the certificate.pem and key.pem and copy the content create new file by name server.pem and paste the both file content into new file.

**Comment by licaon-kter** [comment]
@AtifShahzed no, see https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L24

**Comment by AtifShahzed** [comment]
I created self signed certificate with private key using OpenSSL and configured both of them inside ejabberd configuration file but after that ejabberd server is not starting.

**Comment by AtifShahzed** [comment]
@licaon-kter  Can you please share any resource which help to configure self signed certificate with ejabberd.

**Comment by licaon-kter** [comment]
@AtifShahzed what does ejabberd.log say? There's nothing special to be done for self-signed.

**Comment by AtifShahzed** [comment]
Failed to read PEM file c:/ProgramData/ejabberd/conf/xmpp.pem: no PEM encoded certificate or private key found
2020-07-01 17:46:09.088 [critical] <0.383.0>@ejabberd_pkix:stop_ejabberd:352 ejabberd initialization was aborted due to invalid certificates configuration.


Following are the steps to produce the PEM files using OPEN SSL self signed certificate.

openssl genrsa -out xmpp.key 2048

openssl req -out xmpp.csr -key xmpp.key -new -sha256


openssl x509 -req -days 365 -in  xmpp.csr -signkey  xmpp.key -out  xmpp.crt


# create PEM file with certificate
cat xmpp.crt > xmpp.pem

# add intermediate CA certificate to PEM
cat xmpp.crt >> xmpp.pem

cat xmpp.key >> xmpp.pem


Confusion is I don't know the configuration of certificate inside ejabberd config file secondly don't know what files do I need to copy inside the conf folder.

**Comment by licaon-kter** [comment]
Does the user that runs ejabberd has  permissions to read the files?

**Comment by AtifShahzed** [comment]
yes, 100% .

**Comment by licaon-kter** [comment]
Don't cat anything, add those 2 generated files to the list as the example shows.

**Comment by AtifShahzed** [comment]
Ok Without cat you means to say to add these two files "xmpp.csr" and "xmpp.key"?

**Comment by AtifShahzed** [comment]
Hi.

I placed both files inside conf folder and access the admin panel I saw the certificate but still I am getting an error **"This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store."**

**Comment by AtifShahzed** [comment]
certfiles:
  - "C:/ProgramData/ejabberd/conf/cert.pem"
  - "C:/ProgramData/ejabberd/conf/key.pem"

My Config file settings

**Comment by licaon-kter** [comment]
It's a self-signed certificate? So no error....that's just a fact

**Comment by AtifShahzed** [comment]
Hi,

I have purchased domain and paid certificate from Godady.
1) I have installed ejabberd server.
2) I have done DNS setting to access server from dmain name.

Now here comes the story of Certificate.

I have three files from Godady.
![image](https://user-images.githubusercontent.com/54445953/86541982-ec2b1700-bf2a-11ea-8318-6fe0edcb5a64.png)

Kindly guide me how I would do the configuration with these three files in my ejabberd configuration.

Thanks

**Comment by AtifShahzed** [comment]
I have following coniguration settings for certificate.

**certfiles:
    - "C:/ProgramData/ejabberd/conf/Bundle.crt"
    - "C:/ProgramData/ejabberd/conf/cert.crt"
    - "C:/ProgramData/ejabberd/conf/server.pem"**

I am getting this error.

**2020-07-11 05:12:50.599 [error] <0.381.0>@ejabberd_pkix:log_errors:401 Failed to read PEM file c:/ProgramData/ejabberd/conf/server.pem: at line 1: no matching private key found for this certificate
2020-07-11 05:12:50.599 [error] <0.381.0>@ejabberd_pkix:log_errors:401 Failed to read PEM file c:/ProgramData/ejabberd/conf/cert.crt: at line 1: no matching private key found for this certificate
2020-07-11 05:12:50.611 [critical] <0.381.0>@ejabberd_pkix:stop_ejabberd:352 ejabberd initialization was aborted due to invalid certificates configuration**

If someone guide me the issue so that would be great.

Thanks
