### ISSUE TITLE
Users are not allowed to register accounts so quickly

### ISSUE THREAD

**Issue by LumiProj** [processone/ejabberd#3316]
Hi,

I am doing registration from client API but I have to wait for 10 mins for each user registration.
I think there is infinity settings are required to bypass this limitation.

Can anybody guide me the configuration settings to remove this limitation.

Thanks

**Comment by badlop** [comment]
This is defined with the global option registration_timeout
https://docs.ejabberd.im/admin/configuration/toplevel/#registration-timeout

You can set it to infinity temporarily, but remember: if you allow unknown users to register at this speed, spammers will use your server.
