### ISSUE TITLE
SSL certificates are not refreshed when symlinked

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#3318]
## Environment

- ejabberd version: 20.04
- Installed from: our own docker image / k8s environment

## Bug description

We are using Lets encrypt certificates, that are not generated by eJabberd, but by Kubernetess certification manager. It generates certificate files and those files are "linked" into ejabberd filesystem. However, those files are symlinked from ejabberd filesystem and when certificate change (for example ../data/ca.crt) the simlink stays same and the ejabberd don't reload configuration.

<img width="685" alt="Screenshot 2020-07-02 11 13 58" src="https://user-images.githubusercontent.com/925756/86340412-252a6980-bc55-11ea-89e3-60fbbe4fb951.png">

What I checked is, that ejabberd should reload configuration whenever those files timestamp changes. Would be possible to check timestamp not only certificate file, that is written in configuration but in case it is symbolic link the date of actual file?

What is also strange that in web admin new certificate is used, but when I connect to 5222 port of ejabberd, the old certificate is used.

When I restart ejabberd, everything works as expected.

## Suggested chage
- when certificate configuration points to link, observer changes on not only the link, but on the file itself

**Comment by licaon-kter** [comment]
Why not trigger `ejabberdctl reload_config` after the update?

**Comment by weiss** [comment]
> What I checked is, that ejabberd should reload configuration whenever those files timestamp changes.

That's no longer true regardless of whether the PEM files are symlinked.  The mechanism to implement this turned out to be too cumbersome/unreliable/platform-dependent.  So @licaon-kter's advice is correct.
