### ISSUE TITLE
ACME is using identifier dns instead of http upon request_certificate

### ISSUE THREAD

**Issue by a-zen** [processone/ejabberd#3321]
## Environment

- ejabberd version: 20.04
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.2.1
- OS: Linux ???
- Installed from: docker ejabberd/ecs

## Errors from error.log/crash.log

No errors

## Bug description

The request_certificate command fails with the following error:

```
2020-07-05 06:31:11.248571+00:00 [error] Failed to request certificate for $domain, upload.$domain and 3 more hosts: HTTP error: etimedout
```

I turned on debugging to see what happens and noticed the following in the ACME communication:

```
2020-07-05 12:35:31.564345+00:00 [debug] HTTP response: {{"HTTP/1.1",200,"OK"},                                                                                           
                [{"cache-control","public, max-age=0, no-cache"},                                                                                                         
                 {"connection","keep-alive"},                                                                                                                             
                 {"date","Sun, 05 Jul 2020 12:35:31 GMT"},                                                                                                                
                 {"server","nginx"},                                                                                                                                      
                 {"content-length","343"},                                                                                                                                
                 {"content-type","application/json"},                                                                                                                     
                 {"link",                                                                                                                                                 
                  "<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""},                                                                              
                 {"replay-nonce",                                                                                                                                         
                  "0002v_FcnulcjE6eYWMnu1IVHkgTzZN52NQER8RWimc8t5Y"},                                                                                                     
                 {"x-frame-options","DENY"},                                                                                                                              
                 {"strict-transport-security","max-age=604800"}],
                <<"{\n  \"status\": \"pending\",\n  \"expires\": \"2020-07-12T12:34:57Z\",\n  \"identifiers\": [\n    {\n      \"type\": \"dns\",\n      \"value\": \"$domain\"\n    }\n  ],\n  \"authorizations\": [\n    \"https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/72607588\"\n  ],\n  \"finalize\": \"https://acme-staging-
v02.api.letsencrypt.org/acme/finalize/14528000/109895953\"\n}">>}
```

For some reason the identifier is set to dns which will not work. I need ACME to use the http-01 identifier which will then contact the ejabberd_acme exposed module.

Is there a way to force the http identifier? Does anybody know why the dns identifier is used?

**Comment by a-zen** [comment]
So turns out I was wrong and the issue is not with ejabberd.

I use traefik2 as a reverse proxy which also has built in support for lets encrypt / acme. So traefik2 was catching all the acme requests and thus they never reached ejabberd. 

Sorry :-)

**Comment by Dominion0815** [comment]
@a-zen how did you solved docker ejabberd with traefik2? can you please share your configs?
thanks in advanced

**Comment by Neustradamus** [comment]
@a-zen: Have you seen the @Dominion0815 comment?

**Comment by a-zen** [comment]
@Dominion0815  @Neustradamus sorry missed this.

My traefik2 is running inside Kubernetes so I'm not sure my templates will help you.

But what I did is basically hook up my traefik2 to port 5280 of ejabberd for upload, conference, so only SSL will terminate at traefik2.
And for port 5222 and 5269 I use a plain [TCP route](https://doc.traefik.io/traefik/v2.0/routing/services/#configuring-tcp-services) so that traefik2 will only do simple forwarding.

**Comment by Dominion0815** [comment]
mhh it doesn't work for me, ejabberd isn't able to get a cert.

My current workaround is https://github.com/ldez/traefik-certs-dumper with https://github.com/mcuadros/ofelia (ejabberd config reload)
