### ISSUE TITLE
cluster_join fails on ipv6-only hostnames

### ISSUE THREAD

**Issue by MEschenbacher** [processone/ejabberd#3327]
## Environment

- ejabberd version: 20.04 debian buster backports
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4`
- OS: Linux (Debian)
- Installed from: debian buster backports

## Errors from error.log/crash.log

No errors

## Bug description

I'm trying to join nodes which hostnames do resolve only to ipv6 addresses:

```
ejabberdctl --no-timeout join_cluster 'ejabberd@xmpp1.mydomain.local'
Error: error
Error: {no_ping,'ejabberd@xmpp1.mydomain.local'}
````

`tcpdump -ni any port 53 or host xmpp1.mydomain.local` shows only the DNS lookup for the `A` record, ignoring possible `AAAA` records:
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
23:52:41.029291 IP6 2001:db8::2.33672 > 2001:db8::3.53: 57464+ A? xmpp1.mydomain.local. (33)
23:52:41.030948 IP6 2001:db8::3.53 > 2001:db8::2.33672: 57464 0/1/0 (84)
```

```
$ host xmpp1.mydomain.local
xmpp1.mydomain.local has IPv6 address 2001:db8::4
```

**Comment by badlop** [comment]
To check if the Node is reachable, ejabberd runs this erlang call: 
> net_adm:ping('ejabberd@xmpp1.mydomain.local').

You can start ejabberd in _live_ mode (or attach an erlang shell with _debug_ mode) and try that erlang call to see the exact error message. Then check Erlang/OTP documentation and forums in the hope to find a way to get that working.

Once you know how to solve it in erlang, you can comment it here to try to include the changes in ejabberd.

**Comment by MEschenbacher** [comment]
Thanks for the detailed instructions. It appears that there is no error message:

```
(ejabberd@xmpp2)2> net_adm:ping('ejabberd@xmpp1.mydomain.local').
pang
```

and again, only a DNS lookup for the `A` record is performed.

I'm starting to think that `net_adm:ping` only really cares about IPv4 lookups and you are right digging into erlang itself, however, even if this is erlang behaviour, I consider this still a bug for ejabberd because I'm unable to join ejabberd nodes in an IPv6-only environment. Reading through the documentation of `net_adm`, `inet_res`, and so on, support for IPv6 seems to be there but I am unable to find a version of `net_adm:ping` which switches over to IPv6:

```
(ejabberd@xmpp2)3> inet:gethostbyname('xmpp1.mydomain.local', inet6).
{ok,{hostent,"xmpp1.mydomain.local",[],inet6,16,
             [{123,123,0,0,0,0,0,4}]}} %% i modified the first two parts of the tuple
```

**Comment by prefiks** [comment]
Could you try adding `ERL_OPTIONS="-proto_dist inet6_tcp"` to ejabberdctl.cfg that should be in same dir that ejabberd.yml is? You will need to restart ejabberd for that change to be active.

**Comment by MEschenbacher** [comment]
This suggestion solves the problem for my ipv6-only setup. Thank you!

Looking at the `tcpdump` once again, DNS resolution only asks for `AAAA` which is fine in my case. Out of curiosity: is there a way to attempt connections to both internet protocol versions?

**Comment by MEschenbacher** [comment]
And I noticed that `epmd` bound to `:::4369` (plus an additional random high port) with these options set instead of `0.0.0.0:4369`.

**Comment by prefiks** [comment]
I don't think you can have this, each node need to be reachable from each other, so you need to have common addressing anyway, and in that case there is no need to have duplicate listeners.

**Comment by iPPLE** [comment]
I'm having the same issue.. while trying to `join_cluster` from a different network.. is it possible for a different-network nodes to join the cluster which are not in the same network ?

**Comment by MEschenbacher** [comment]
Mixed (IPv4/IPv6) addressing is not supported (as explained in the previous message). Different networks (layer2 domains separated by routing) of the same IP type should be possible.

**Comment by iPPLE** [comment]
Yes, all nodes are using the same `IPv4`, but the ones in different network stil not able to join the cluster. all the nodes which are in the same network with master node are joined successfully.

* `ejabberd-21.01.7`
* Allowed ports in all nodes : `4369`, `5269`, `4200-4210`

In **slave IPv4 different-network node**:
> ejabberdctl --no-timeout join_cluster 'ejabberd@domain.com'

```erlang
Error: error
Error: {no_ping,'ejabberd@domain.com'}
```
> net_adm:ping('ejabberd@domain.com').
```erlang
pang
```

Please help to advice,
Thanks.

**Comment by iPPLE** [comment]
> Mixed (IPv4/IPv6) addressing is not supported (as explained in the previous message). Different networks (layer2 domains separated by routing) of the same IP type should be possible.

Thanks for your clarification.
