### ISSUE TITLE
Couldn't find any to add reactions to messages in muc

### ISSUE THREAD

**Issue by partikmadan** [processone/ejabberd#3328]
## Environment

- ejabberd version: 20.04
- OS: Mac 
- Installed from: source 

## Bug description

Hi,

Opening this as found no help from search engines. 

We're exploring some different ways to add metadata to our messages. In our case, we're talking about, for example, adding reactions to the messages, such as likes or unlikes. Let's say, in a muc room where anyone can add a like or an unlike to any message.

The implementation of this feature implies some tasks such as:

Communication to add/delete a new reaction
Communication to retrieve/get the reactions of a message
Mechanism to persist the metadata related with a message
What you consider a good way to implement this feature in Ejabberd and in the XMPP framework?

Any idea, suggestion or advice will be welcome.

Thanks a lot!

**Comment by licaon-kter** [comment]
This does not help?
https://xmpp.org/extensions/inbox/reactions.html

**Comment by partikmadan** [comment]
Yes this worked. I thought it was not supported. This is what i wanted. Thanks @licaon-kter :)
