### ISSUE TITLE
apple push notifications

### ISSUE THREAD

**Issue by Luticus** [processone/ejabberd#3334]
**Is your feature request related to a problem? Please describe.**
I have an ejabberd server hosted from a Debian 10 server and some of my users unfortunately have iPhones. When they use any clients on their phones, messaging works, until the messaging app is sent to the background at which point they quit receiving messages. I've read supporting apple push notifications is the solution for this, however, I've also read ejabberd business edition is the only edition of ejabberd that officially supports this. So my question is how are people dealing with this? This situation makes iphones basically unusable with ejabberd community edition. I'm not opposed to paying for ejabberd but business edition software is usually thousands of dollars and I'm not a business, I just want private chat for my friends and family, so I'm assuming it'll be out of my price range.  

**Describe the solution you'd like**
I want a way for iphones to be able to participate in the xmpp chat without it being completely frustrating for those users. They basically just don't use the chat server and resort to text messages, which completely invalidates my whole reason for using ejabberd in the first place, encrypted private chat. Maybe recommendations for how to work around the problem would be nice. Would be super nice if it could be done without having to recompile ejabberd from source, because that would make keeping ejabberd up-to-date a lot more difficult. 

**Describe alternatives you've considered**
Switching back to openfire? I mean I really don't want to do that, I like ejabberd WAY better, but I really need my xmpp server to support iphones properly. Really, REALLY, hoping there's a good alternative to doing that.

**Comment by Luticus** [comment]
It is a server issue, I'm asking if there's a work around for the server to support push notifications. Any advice, help, whatever would be great. If there's a better place to ask, please suggest it.

**Comment by weiss** [comment]
> I've read supporting apple push notifications is the solution for this, however, I've also read ejabberd business edition is the only edition of ejabberd that officially supports this. So my question is how are people dealing with this? This situation makes iphones basically unusable with ejabberd community edition. I'm not opposed to paying for ejabberd but business edition software is usually thousands of dollars and I'm not a business, I just want private chat for my friends and family, so I'm assuming it'll be out of my price range.

You're confusing two scenarios.

1. The main target audience of the Business Edition is "business" building closed solutions based on XMPP.  They usually control their chat clients and want ejabberd to generate APNS notifications directly.  Support for this is shipped with the Business Edition.

2. The main target audience of the Community Server is public services who's users use clients not under control of the service operator.  For that scenario, the APNS support shipped with the Business Edition wouldn't help, because the service operator doesn't have the credentials required to generate APNS notifications.  Only the client vendor has those.  The solution is using the [Push Notification extension][1] with clients supporting it.  The ejabberd side is implemented in [`mod_push`][2] which is also shipped and enabled by default in the Community Server.

[1]: https://xmpp.org/extensions/xep-0357.html
[2]: https://docs.ejabberd.im/admin/configuration/modules/#mod-push

**Comment by weiss** [comment]
> If there's a better place to ask, please suggest it.

If you need support regarding the server side, you could ask in our public channel, for example:

`ejabberd@conference.process-one.net`

**Comment by Luticus** [comment]
Ok so I have mod_push enabled, and I've read that it basically requires no configuration.  It's just enabled via mod_push: {} in the yaml file, which is done. This doesn't solve the problem with iphones though, so I'm assuming the iphone apns support isn't a thing with mod_push. How are xmpp users/server admins dealing with that?

**Comment by licaon-kter** [comment]
@Luticus The ejabberd server registers for push with the CLIENT developers push server.... the CLIENT developers push server sends those to Apple/Google.

Eg. for Android, the Conversations dev hosts this: https://github.com/iNPUTmice/p2
iOS client devs host their own servers for APNS.

**Comment by weiss** [comment]
> so I'm assuming the iphone apns support isn't a thing with `mod_push`

Several iOS apps such as [Monal][1], [Siskin][2], and [ChatSecure][3] support this extension.  But yes, so far they seem to be more buggy than clients on other platforms, unfortunately.  That said, if push notifications don't work at all for you, I wouldn't rule out a server-side issue.  (Then again, you didn't even mention which clients you tried.)  Either way, tracking this down is really outside the scope of this tracker, which is about bug reports (and feature requests) against ejabberd.

[1]: https://monal.im
[2]: https://siskin.im
[3]: https://chatsecure.org

**Comment by Luticus** [comment]
`Then again, you didn't even mention which clients you tried.`
Sorry, I don't use iphone myself so I personally haven't tried in a while, some of my users use monal, and I tried monal in the past. Basically they said it's still a problem and as the server admin, I thought I should check and see if there was something I could do to help.
` Either way, tracking this down is really outside the scope of this tracker, which is about bug reports (and feature requests) against ejabberd.`
I'm trying the suggestion you made earlier to see what happens, I definitely appreciate your help though. This seems to be a confusing thing to support.

`/LE: put logleve: 4, reload_config and tail -f ejabberd.log|grep -i push ;)` Thanks for this, I'll give it a shot and see what I can see.
