### ISSUE TITLE
MOD_MAM, MOD_MAM_SQL, filter by content into MUC.

### ISSUE THREAD

**Issue by lucastimotiofirmino** [processone/ejabberd#3336]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

I need to use the fields, specified in: [https://xmpp.org/extensions/xep-0313.html#example-14](https://xmpp.org/extensions/xep-0313.html#example-14)
```
<field type='text-single' var='urn:example:xmpp:free-text-search'/>
<field type='text-single' var='urn:example:xmpp:stanza-content'/>
```

However, when [consulting the server](https://xmpp.org/extensions/xep-0313.html#example-13), it does not provide support for these fields.

Taking a look at the module **mod_mam_sql**, I noticed that there are some mentions to a column called WithTextClause.

How can we make this type of filter by content?

Thanks.

**Comment by weiss** [comment]
This is not a bug report.

> I need to use the fields, specified in [...]

As you can see from the naming of the namespace (`urn:example:...`), those field names are just examples for a fulltext feature which is totally optional as per the spec.  You can see what fields are supported by the server by retrieving the form as in [example 13][1].  You'll see that ejabberd does indeed support fulltext search (if SQL is used for MAM storage), and that the fieldname is `withtext`.

[1]: https://xmpp.org/extensions/xep-0313.html#query-form
