### ISSUE TITLE
SQLite3 library >= 3.6.19 was not found when installed Ejabberd on Mac OS X Catalina

### ISSUE THREAD

**Issue by Jeel-Shah** [processone/ejabberd#3338]
## Environment

- ejabberd version: Not Installed
- Erlang version: `Erlang/OTP 23 [erts-11.0.2]`
- OS: Mac OS Catalina (10.15.3)
- Installed from: source (Github with `make`)

## Errors from error.log/crash.log

No errors

## Bug description

While attempting to install ejabberd, the following error comes after executing: `./configure --prefix=$HOME/my-ejabberd --enable-sqlite`

```
checking for SQLite3 library >= 3.6.19... yes
cat: /include/sqlite3.h: No such file or directory
./configure: line 4172: test: !=: unary operator expected
configure: WARNING: Cannot find SQLITE_VERSION macro in sqlite3.h header to retrieve SQLite version!
configure: error: SQLite3 library >= 3.6.19 was not found
```

I have sqlite installed via `brew`. The latest version via brew is `3.23.xx`. The latest version on sqlite shows that the latest version is `3.23.xx`. Is the error message referring to another aspect of sqlite3 that we have to install?

Thanks a lot for your time!

P.S. I ran `brew install erlang elixir openssl expat libyaml libiconv libgd sqlite rebar rebar3 automake autoconf` with success (no hiccups).

**Comment by licaon-kter** [comment]
Isn't there an ejabberd homebrew recipe that you can use instead?

**Comment by nosnilmot** [comment]
Use this to configure and find `sqlite` installed with `brew`:

`./configure --prefix=$HOME/my-ejabberd --enable-sqlite --with-sqlite3=/usr/local/opt/sqlite`
