### ISSUE TITLE
Set TLS ciphers for ejabberd_http 

### ISSUE THREAD

**Issue by oksjd** [processone/ejabberd#3341]
#### Version
* Debian 10.4
* ejabberd 20.04-1~bpo10+1 from buster-backports
#### Problem
Ciphers for c2s and s2s connection can be set with `c2s_ciphers` and `s2s_ciphers`. But there's currently no such option for ejabberd_http module. Consequently, when visiting webadmin or uploading files to server, an insecure cipher could be used by the client. 
Is there any cipher option available for the http module? The only viable options available now is to disable TLSv1.2 altogether (breaks a lot of older clients) or configure a reverse proxy.

**Comment by licaon-kter** [comment]
There's a ciphers option: https://docs.ejabberd.im/archive/20_04/listen/#ejabberd-http

/close this
