### ISSUE TITLE
Creating dynamic vhost fails

### ISSUE THREAD

**Issue by haimomesi** [processone/ejabberd#3345]
## Environment

- ejabberd version: 20.04
- Erlang version: OTP 22
- Elixir version: 1.10.3
- OS: Mac OSX
- Installed from: source

## Configuration: ejabberd.yml

```yaml
include_config_file: ./config/hosts.yml
# hosts:
#   - localhost
...
new_sql_schema: true
```

## Errors from error.log/crash.log

```
21:47:54.759 [error] Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
 
21:47:54.784 [error] Hook :host_up crashed when running :ejabberd_sql_sup::start/1:
** exception error: application_start_failed
   in function  ejabberd:exit_or_halt/2 (src/ejabberd.erl, line 150)
   in call from ejabberd_sql_sup:start/1 (src/ejabberd_sql_sup.erl, line 46)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 203)
   in call from lists:foreach/2 (lists.erl, line 1338)
   in call from ejabberd_config:reload/0 (src/ejabberd_config.erl, line 104)
   in call from mod_http_api:handle2/4 (src/mod_http_api.erl, line 268)
   in call from mod_http_api:handle/4 (src/mod_http_api.erl, line 229)
** Arg 1 = "localhost3"
```

## Bug description

I've implemented Ejabberd over Elixir.
My solution includes adding vhosts dynamically. I know it's not according to the cookbook, but it's a must for me.

I have an **ejabberd_command** to add a vhost, then, I override `hosts.yml` file with the new vhost and call ejabberd_config:reload(), and get error above.

Here is my code...

```
oldHosts = :ejabberd_config.get_option(:hosts) _// yields ["localhost", "localhost2"]_
addedHosts = ["localhost", "localhost2", "localhost3"]
File.write!("config/hosts.yml", addedHosts)
:ejabberd_config.reload()
```

Thank you in advance,
Haim

**Comment by badlop** [comment]
> 21:47:54.759 [error] Failed to start Erlang application 'odbc': no such file or directory: odbc.app.

I can't reproduce that error message, so I'll explain you how I tested it, maybe that gives you some clue about a missing step.

First of all, check you installed the ODBC library included in Erlang/OTP. That library includes `odbc.app` among other files. For example in Debian, this library is optional and you must remember to install it: https://packages.debian.org/buster/amd64/erlang-odbc/filelist

Then, enable the databases you will use in ejabberd compilation. In my case, I enabled all to be sure:
```
./configure --enable-mysql --enable-odbc --enable-pgsql --enable-sqlite
```

Then in ejabberd.yml
```yaml
new_sql_schema: true

sql_type: mysql
sql_server: "localhost"
sql_database: "ejaup"
sql_username: "ejabberd_test"
sql_password: "ejabberd_test"
```

I start ejabberd with `ejabberdctl live` so that I get an interactive erlang shell where I can check some functions:

```
ejabberd_option:sql_type("localhost").
mysql

ejabberd:start_app(p1_mysql).
ok

ejabberd:start_app(p1_pgsql).
ok

ejabberd:start_app(sqlite3).
ok

ejabberd:start_app(odbc).
ok

ejabberd_config:reload().
2020-07-29 10:54:39.695524+02:00 [info] Reloading configuration from /etc/ejabberd/ejabberd.yml
...
2020-07-29 10:54:39.847819+02:00 [info] Configuration reloaded successfully

```

**Comment by haimomesi** [comment]
Thank you for the fast response.

from my interactive Elixir console:

```
:ejabberd_option.sql_type("localhost")
:odbc

:ejabberd.start_app(:odbc)
12:36:03.991 [error] Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
** (ErlangError) Erlang error: :application_start_failed
    (ejabberd 20.4.0) src/ejabberd.erl:150: :ejabberd.exit_or_halt/2
```

So my question, is how come localhost (which is `odbc`) is indeed started and running, but the `start_app` command fails?

**Comment by badlop** [comment]
> how come localhost (which is odbc) is indeed started and running, but the start_app command fails?

Notice that the SQL connections are not established when ejabberd starts; they are established the first time they are needed: 

```
2020-07-29 14:05:21.507898+02:00 [info] ejabberd 20.04.90 is started
 in the node ejabberd@localhost in 2.58s

> ejabberd_sql_sup:is_started(<<"localhost">>).
false

2020-07-29 14:05:28.967973+02:00 [info] (<0.507.0>)
 Accepted connection [::ffff:127.0.0.1]:46257 -> [::ffff:127.0.0.1]:5222
2020-07-29 14:05:29.175114+02:00 [info] (tls|<0.507.0>)
 Accepted c2s DIGEST-MD5 authentication for user2@localhost by sql backend from ::ffff:127.0.0.1
2020-07-29 14:05:29.216319+02:00 [info] (tls|<0.507.0>)
 Opened c2s session for user2@localhost/tka1

> ejabberd_sql_sup:is_started(<<"localhost">>).
true
```

> when I restart the app from scratch, all the hosts in the modified hosts.yml file loads successfully.

The file _loads successfully_. But are the ODBC connections established correctly? Did you try to setup sql for some storage, and then trigger it with a client usage?
```yaml
auth_method: sql
```
and then register account and login, and check the new account appears in the ODBC database.

**Comment by haimomesi** [comment]
Okay.

I setup the mysql part in ejabberd.yml, and now the dynamic vhosts mechanism works for me.

I'm realizing now that this is not really an issue, and could easily be a stackoverflow question, so thank you for your help!

br,
Haim
