### ISSUE TITLE
Ejabberd cluster going down

### ISSUE THREAD

**Issue by biddwan09** [processone/ejabberd#3352]
We run ejabberd 19.05 in our cluster and it is going down frequently throwing the below error continuously. We have been restarting the server lately to fix this error. Any solution to this would be highly appreciated. 

```
020-08-06 06:34:35 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     killed
     Offender:   [{pid,<0.27515.1575>},{id,undefined},{mfargs,{ejabberd_http,start_link,undefined}},
                        {restart_type,temporary},{shutdown,1000},{child_type,worker}]

2020-08-06 06:34:57 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     killed
     Offender:   [{pid,<0.22434.1548>},{id,undefined},{mfargs,{ejabberd_http,start_link,undefined}},
                        {restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

**Comment by badlop** [comment]
Some wild ideas:

A) What HTTP services do you have enabled in ejabberd, and are being used? WebAdmin, BOSH, OAuth, ...?

B) Before all those error messages, does any other suspicious message appear, that may provide some clue about the problem?

C) OK, those error messages appear. But is ejabberd unusable? What exactly does not work: existing clients are kicked out? new clients cannot authenticate? ejabberd consumes all CPU? or all RAM? Or does the ejabberd node simply crashes completely?

D) From what you mention, it reproduces soon and frequently. But have you determined what causes it, or what event is correlated? Maybe some early log error found in B) gives the clue.

E) BTW, I can reproduce that error message in my ejabberd 20.07: start server, login to webadmin (it uses the http service), then kill the erlang process that handles that webadmin-http connection. The error message appears just once, and nothing else gets broken in that case.

**Comment by biddwan09** [comment]
Hi @badlop we have only few http services. Sending a list of them below
    module: ejabberd_http
    request_handlers:
      "/api": mod_http_api
      "/http-bind": mod_bosh
      "/upload": mod_http_upload
      "/websocket": ejabberd_http_ws
      "/oauth": ejabberd_oauth
      "/admin": ejabberd_web_admin

we have seen some strange behaviors from the ejabberd. Whenever this happens we can see that the number of users increases rapidly in the web admin interface. We are using ejabberd rest api extensively. And we have configured to some modules to subscribe to some events. The list of events that are subscribed are given below

set_presence_hook
unset_presence_hook
user_send_packet

after receiving any of these events we are making some http requests to our service. Ejabberd doesn't crash completely but none of the transactions happen unless we restart the server.

**Comment by prefiks** [comment]
Only think that i think can force that kill can be system_monitor, when it detect oveload/high memory pressure, but that should produce warning in log file, do you see those? They should be logged in ejabberd.log if you have loglevel set to at least warnings/4

**Comment by biddwan09** [comment]
Hi, @prefiks we didn't have loglevel set to warnings/4 before. we have set it now. Can share those logs if the incident repeats again. Whenever this happened I saw the online users were above 90000.  We have a 3 node set up where each of the machines has 32 GB RAM and 8 CPUs. We have tried changing the max ports size as the http sup was failing we thought it might be due to the number of ERL_MAX_PORTS . It was 32000 before and now we have set it to 320000 . Sending the configuration file as well for all the 3 nodes

#
# In this file you can configure options that are passed by ejabberdctl
# to the erlang runtime system when starting ejabberd
#

#' POLL: Kernel polling ([true|false])
#
# The kernel polling option requires support in the kernel.
# Additionally, you need to enable this feature while compiling Erlang.
#
# Default: true
#
#POLL=true

#.
#' SMP: SMP support ([enable|auto|disable])
#
# Explanation in Erlang/OTP documentation:
# enable: starts the Erlang runtime system with SMP support enabled.
#   This may fail if no runtime system with SMP support is available.
# auto: starts the Erlang runtime system with SMP support enabled if it
#   is available and more than one logical processor are detected.
# disable: starts a runtime system without SMP support.
#
# Default: enable
#
#SMP=enable

#.
#' ERL_MAX_PORTS: Maximum number of simultaneously open Erlang ports
#
# ejabberd consumes two or three ports for every connection, either
# from a client or from another Jabber server. So take this into
# account when setting this limit.
#
# Default: 32000
# Maximum: 268435456
#
ERL_MAX_PORTS=320000

#.
#' FIREWALL_WINDOW: Range of allowed ports to pass through a firewall
#
# If Ejabberd is configured to run in cluster, and a firewall is blocking ports,
# it's possible to make Erlang use a defined range of port (instead of dynamic
# ports) for node communication.
#
# Default: not defined
# Example: 4200-4210
#
FIREWALL_WINDOW=4370-4379

#.
#' INET_DIST_INTERFACE: IP address where this Erlang node listens other nodes
#
# This communication is used by ejabberdctl command line tool,
# and in a cluster of several ejabberd nodes.
#
# Default: 0.0.0.0
#
#INET_DIST_INTERFACE=127.0.0.1

#.
#' ERL_EPMD_ADDRESS: IP addresses where epmd listens for connections
#
# IMPORTANT: This option works only in Erlang/OTP R14B03 and newer.
#
# This environment variable may be set to a comma-separated
# list of IP addresses, in which case the epmd daemon
# will listen only on the specified address(es) and on the
# loopback address (which is implicitly added to the list if it
# has not been specified). The default behaviour is to listen on
# all available IP addresses.
#
# Default: 0.0.0.0
#
#ERL_EPMD_ADDRESS=127.0.0.1

#.
#' ERL_PROCESSES: Maximum number of Erlang processes
#
# Erlang consumes a lot of lightweight processes. If there is a lot of activity
# on ejabberd so that the maximum number of processes is reached, people will
# experience greater latency times. As these processes are implemented in
# Erlang, and therefore not related to the operating system processes, you do
# not have to worry about allowing a huge number of them.
#
# Default: 250000
# Maximum: 268435456
#
#ERL_PROCESSES=250000

#.
#' ERL_MAX_ETS_TABLES: Maximum number of ETS and Mnesia tables
#
# The number of concurrent ETS and Mnesia tables is limited. When the limit is
# reached, errors will appear in the logs:
#   ** Too many db tables **
# You can safely increase this limit when starting ejabberd. It impacts memory
# consumption but the difference will be quite small.
#
# Default: 1400
#
#ERL_MAX_ETS_TABLES=1400

#.
#' ERL_OPTIONS: Additional Erlang options
#
# The next variable allows to specify additional options passed to erlang while
# starting ejabberd. Some useful options are -noshell, -detached, -heart. When
# ejabberd is started from an init.d script options -noshell and -detached are
# added implicitly. See erl(1) for more info.
#
# It might be useful to add "-pa /usr/local/lib/ejabberd/ebin" if you
# want to add local modules in this path.
#
# Default: ""
#
#ERL_OPTIONS=""

#.
#' ERLANG_NODE: Erlang node name
#
# The next variable allows to explicitly specify erlang node for ejabberd
# It can be given in different formats:
# ERLANG_NODE=ejabberd
#   Lets erlang add hostname to the node (ejabberd uses short name in this case)
# ERLANG_NODE=ejabberd@hostname
#   Erlang uses node name as is (so make sure that hostname is a real
#   machine hostname or you'll not be able to control ejabberd)
# ERLANG_NODE=ejabberd@hostname.domainname
#   The same as previous, but erlang will use long hostname
#   (see erl (1) manual for details)
#
# Default: ejabberd@localhost
#
ERLANG_NODE=ejabberd@xmpp

#.
#' EJABBERD_PID_PATH: ejabberd PID file
#
# Indicate the full path to the ejabberd Process identifier (PID) file.
# If this variable is defined, ejabberd writes the PID file when starts,
# and deletes it when stops.
# Remember to create the directory and grant write permission to ejabberd.
#
# Default: don't write PID file
#
#EJABBERD_PID_PATH=/var/run/ejabberd/ejabberd.pid

#.
#' CONTRIB_MODULES_PATH: contributed ejabberd modules path
#
# Specify the full path to the contributed ejabberd modules. If the path is not
# defined, ejabberd will use ~/.ejabberd-modules in home of user running ejabberd.
#
# Default: $HOME/.ejabberd-modules
#
#CONTRIB_MODULES_PATH=/opt/ejabberd-modules

#.
#' CONTRIB_MODULES_CONF_DIR: configuration directory for contributed modules
#
# Specify the full path to the configuration directory for contributed ejabberd
# modules. In order to configure a module named mod_foo, a mod_foo.yml file can
# be created in this directory. This file will then be used instead of the
# default configuration file provided with the module.
#
# Default: $CONTRIB_MODULES_PATH/conf
#
#CONTRIB_MODULES_CONF_DIR=/etc/ejabberd/modules

#.
#'
# vim: foldmarker=#',#. foldmethod=marker:

**Comment by badlop** [comment]
> Can share those logs if the incident repeats again.

I guess the incident didn't repeat, then.
