### ISSUE TITLE
create_room hook isn't triggered when a room is created by an available presence

### ISSUE THREAD

**Issue by Freyskeyd** [processone/ejabberd#3353]
## Environment

- ejabberd version: 20.04
- Erlang version: `10.3 otp 21`
- OS: Linux (Debian)
- Installed from: source

## Bug description

The `create_room` hook isn't triggered when a room is created by an `available` presence received.
It seems that this hook is only available when creating room from ctl, not when people are actually joining the room.

The hook is triggered here: https://github.com/processone/ejabberd/blob/master/src/mod_muc.erl#L392
The room creation by presence is triggered here: https://github.com/processone/ejabberd/blob/master/src/mod_muc.erl#L549

I tagged it as bug but maybe it's done by pupose.
Let me know if you want more context!

**Comment by badlop** [comment]
That code was added in https://github.com/processone/ejabberd/commit/b66dab13130229268e070a0021f95733cb3aabac

I've tested now using ejabberd 20.07, it is not ran with a presence stanza (following XEP-0045), and it is not ran using ejabberdctl create_room command! Not even when recreating a persistent room after an ejabberd restart. So I wonder when it is ran.

This would solve the problem:
```diff
From 202fc42530a727398a0f989d89b7dd16538794ab Mon Sep 17 00:00:00 2001
From: Badlop <badlop@process-one.net>
Date: Tue, 18 Aug 2020 22:09:45 +0200
Subject: [PATCH 1/2] Run the create_room hook when room created using XEP-0045
 (#3353)

---
 src/mod_muc.erl | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/mod_muc.erl b/src/mod_muc.erl
index 718f29b3e..c91cecd4d 100644
--- a/src/mod_muc.erl
+++ b/src/mod_muc.erl
@@ -877,6 +877,7 @@ start_room(Mod, Host, ServerHost, Access, Room, HistorySize,
 			    HistorySize, RoomShaper,
 			    Creator, Nick, DefOpts, QueueType) of
 	{ok, Pid} ->
+	    ejabberd_hooks:run(create_room, ServerHost, [ServerHost, Room, Host]),
 	    Mod:register_online_room(ServerHost, Room, Host, Pid),
 	    {ok, Pid};
 	Err ->
-- 
2.20.1
```

**Comment by weiss** [comment]
> So I wonder when it is ran.

It's never triggered indeed, AFAICS.  The `mod_muc:create_room/5` function which triggers the hook was added in 2bd54854ecda5c7e7f3aeb1f48f9d6bc61ef0f14 but then never used (except by efb4fd0d1020faa105bf932c06cf4c67fb389952 which was later reverted).

**Comment by badlop** [comment]
Aha! And later its usage started in some custom modules, not published but probably in use.

**Comment by weiss** [comment]
Maybe leave the `create_room` function & hook in place then, and go for your fix except that you'd call the new hook `start_room` or something?  ("create" is slightly misleading anyway, as it's not just triggered on initial room creation but also on node restart, right?)

**Comment by badlop** [comment]
Umm, in fact, in order for the new hook to be ran in all cases, it must be placed in mod_muc_room. That way it's ran when user joins, when a persistent room is started at node start, and also when room is created using API.
