### ISSUE TITLE
Unable to build ejabberd as a project dependency

### ISSUE THREAD

**Issue by slezakattack** [processone/ejabberd#3354]
## Environment

- ejabberd version: 20.07
- Erlang version: OTP 21 `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.5.13`
- OS: Mac OSX
- Installed from: declared as dependency in erlang project.

## Bug description
My Erlang project is using rebar3 and pulling ejabberd as a dependency (I've tried both as a hex package and a git dependency). The hex package seems to only be available for Elixir. Is there any planned work to support this for Erlang?

Pulling it as a git dependency instead gives this error:
`===> Error building application ejabberd:
     No project builder is configured for type mix`

**Comment by prefiks** [comment]
Hello,

I commited ee76581b49b383429b7fcdfe484d959aa8f1f73c which should make future hex uploads have files that should allow building with rebar.
