### ISSUE TITLE
web-admin: Mark dangerous actions as such

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3363]
Again and again I find myself removing users, when In just wanted to see their roster. The reason is that the "Remove user" button is in no way offset from the other buttons. Related: For Offlline Messages the Link to get to the messages is small (only the few characters of the number), while the "Remove all offlice messages" beside is big.

I propose enhancing the Web UI as follows
* All dangerous actions will become button (if they are not already)
* Elements beside the dangerous action will be resized to be up to par with the dangerous action
* All dangerous buttons are visually marked as such
    * Adopting from github UI, they get a red text, and when hovering over, they become red
* Best would be to collect all dangerous actions in a "danger zone" (again adopted from github)

This is how it can look like:
![grafik](https://user-images.githubusercontent.com/784161/91013263-b1b72f80-e5e7-11ea-88fd-8fcba4a0bc06.png)
* Link for Offline Messages has become a Button too. (Here the number of messages in part of the button text, this might be done differently)
* "!Remove offline messages" has become "dangerous"
* Roster has become a headline plus a button - instead of just being a clickable headline
* "Remove user" has been put into the "danger zone"
    * Even if other dangerous buttons are not moved to the danger zone for now, I strongly suggest esp. emphasizing on Remove user being danger. 

Implementation notes:
* All dangerous buttons get CSS class "btn-danger"
* Add a view lines to the web-uis's style sheet

Here is the example from the screenshot:
```html
<h1>User jane@doe.com</h1><form action="" method="post">
<h3>Verbundene Ressourcen:</h3>
  <ul><li>XXX - tls://…ejabberd@localhost</li></ul><h3>Password</h3>
  <input type="text" name="password" data-kpxc-id="xxxx">
  <input type="submit" name="chpassword" value="Change Password">

<h3>Last Activity</h3> Online

<h3>Offline-Messgages</h3>
<a href="queue/"><button type="button">0 - View Offline messages</button></a>
<input type="submit" class="btn-danger"
       name="removealloffline" value="Remove all Offline messages">

<h3>Roster</h3>
<a href="roster/"><button type="button">Show Roster</button></a>

<div class="danger-zone"><h3>Danger zone</h3>
<p><input type="submit" class="btn-danger"
	    name="removeuser" value="Remove User"></p>
</div>
</form>
<style>
    .btn-danger:hover {
	color: #fff;
	background-color: #cb2431;
}
.btn-danger {
	color: #cb2431;
	transition: none;
}
.danger-zone {
    margin-top: 2em;
    padding: 0 1em;
    border: solid thin #cb2431;
    border-radius:1em;
}
</style>
```

**Comment by badlop** [comment]
Thanks for thinking and proposing! I've included some of your proposals that were quite easy to implement.

Only lacking are the Offline button (for design principle) and the Danger zone (too much effort right now, let's hope the new colors help enough and that isn't required).
