### ISSUE TITLE
Logging for ejabberd_service

### ISSUE THREAD

**Issue by siccegge** [processone/ejabberd#3364]
Configuring `ejabberd_service` (with tls) is next to impossible with the current version of ejabberd.
Problem is, there is basically no logging at all:

```
# gnutls-cli conference.example.org -p 5347
Processed 128 CA certificate(s).
Resolving 'conference.example.org:5347'...
Connecting to '...:5347'...
*** Fatal error: Error in the pull function.
```

But all I get in ejabberd.log (with loglevel 5) is

```
2020-08-24 09:19:11.266 [info] <0.362.0>@ejabberd_listener:accept:273 (<0.717.0>) Accepted connection [...]:58556 -> [...]:5347
```

and no indication at all that something even went wrong. Now I managed to puzzle the concrete (certificate related) problem together last time but after certificate renewal I'm totally lost again. Would be great if there was any sort of helpful logging

**Comment by weiss** [comment]
TLS works fine for me with the ejabberd 20.07 and the following `ejabberd_service` configuration:

```yaml
  -
    module: ejabberd_service
    port: 5347
    ip: "::"
    tls: true
    certfile: "/path/to/cert+key.pem"
```

The command `openssl s_client -connect example.com:5347` verified the certificate just fine.  What output do you get from that command?

BTW, does your component support TLS connections?  (I'm asking because that's not a common thing to do.)

**Comment by siccegge** [comment]
```
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 313 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by licaon-kter** [comment]
Paste your config too

**Comment by siccegge** [comment]
Current version:
https://gist.github.com/siccegge/514aa48e0f66a15cc35ec5f8318822d0

**Comment by weiss** [comment]
You might have to add `certfile: "/path/to/cert+key.pem"` (i.e., the PEM file should contain both the TLS certificate and the key; and must be readable by the user running ejabberd).

**Comment by siccegge** [comment]
FWIW it seems the certfile may contain a certificate chain but needs to contain the service certificate first.

Otherwise connections are *silently* dropped without any log message

**Comment by Neustradamus** [comment]
@badlop: Have you seen the @siccegge comment?
