### ISSUE TITLE
Missing default values cause mysql errors

### ISSUE THREAD

**Issue by 4i-helpynet** [processone/ejabberd#3365]
## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`
- OS: Linux (Debian) Ubuntu 16.04
- Installed from:  official deb/rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```
## Bug description

Register user with 
./ejabberdctl register "test" "example.com" "123Abc"
run error of 'No default value of server_host, and cannot be null', the user isn't inserted.
After add default value, the user inserted as normal.

**Comment by prefiks** [comment]
Issue here is probably using database created with schema from  `sql/mysql.new.sql` but not having option in your ejabberd config that's tell it that is should work with new schema: `use_new_schema: true`, i am guessing adding that will fix that problem.
