### ISSUE TITLE
while running it shows an error like this. Ldap authentication also failing.

### ISSUE THREAD

**Issue by nadeerck2020** [processone/ejabberd#3366]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (CentOS)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log
crasher:
    initial call: ejabberd_auth_ldap:init/1
    pid: <0.787.0>
    registered_name: []
    exception error: undefined function pg:start_link/0
      in function  eldap_pool:start_link/7 (src/eldap_pool.erl, line 69)
      in call from ejabberd_auth_ldap:init/1 (src/ejabberd_auth_ldap.erl, line 103)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [ejabberd_backend_sup,ejabberd_sup,<0.126.0>]
    message_queue_len: 0
    messages: []
    links: [<0.475.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 16452
  neighbours:

## Bug description

i can't able to login using LDAP authentication. it always shows an error like this. internal authentication is works fine
Failed c2s PLAIN authentication for xxxxxxx@xxxx.xxxx from ::ffff:192.168.34.56: Invalid username or password

Please, give us a precise description (what does not work, what is expected, etc.)

**Comment by weiss** [comment]
Why don't you answer _any_ of the questions regarding your environment as asked by the bug issue template?
