### ISSUE TITLE
LDAP authentication failed

### ISSUE THREAD

**Issue by nadeerck2020** [processone/ejabberd#3367]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (CentOS)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

xxx.xxx:
    auth_method: [ldap]
    ldap_servers: [xxx.xxx.xx.xxx]  # List of LDAP servers
    ldap_base: "DC=xxx,DC=xxx" # Search base of LDAP directory
    ldap_rootdn: "CN=xxxxx,OU=xxx xx,DC=xxx,DC=xxx" # LDAP manager
    ldap_password: "password" # Password to LDAP manager
    ldap_uids: [sAMAccountName]
    ldap_filter: "(objectClass=user)"

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

crasher:
    initial call: ejabberd_auth_ldap:init/1
    pid: <0.786.0>
    registered_name: []
    exception error: undefined function pg:start_link/0
      in function  eldap_pool:start_link/7 (src/eldap_pool.erl, line 69)
      in call from ejabberd_auth_ldap:init/1 (src/ejabberd_auth_ldap.erl, line 103)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [ejabberd_backend_sup,ejabberd_sup,<0.126.0>]
    message_queue_len: 0
    messages: []
    links: [<0.474.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 16452
  neighbours:

## Bug description
One week ago it is working. suddenly it stops working. internal authentication is working fine. when trying to login using ldap authentication it shows error like this. 

 Failed c2s PLAIN authentication for abcd@xxx.xxfrom ::ffff:192.168.34.56: Invalid username or password

Please, give us a precise description (what does not work, what is expected, etc.)

**Comment by weiss** [comment]
So you closed #3366, opened a new issue, and [still][1] refuse to answer the bug issue template's questions about your environment?  Let me repeat the questions:

- What ejabberd version are you using?
- What Erlang version are you using (if you don't know, type `erl +V`)?
- What OS/Linux distribution are you using?
- How did you install ejabberd? (E.g., from a distribution package, or using ProcessOne's official DEB/RPM, or using ProcessOne's official binary installer, or built from source?)

[1]: https://github.com/processone/ejabberd/issues/3366#issuecomment-680884891

**Comment by nadeerck2020** [comment]
i have used the  ejabberd/ecs:20.04 now. and it is worked fine
