### ISSUE TITLE
MUC: Unescape disco info identity name attribute

### ISSUE THREAD

**Issue by lovetox** [processone/ejabberd#3370]
Create a MUC with a JID: `friends&family@chat.yourserver.com`

The client escapes the JID (XEP-0106) and a MUC is created: `friends\26family@chat.yourserver.com`

Ejabberd has the habbit of setting the disco info identity name attribute to the localpart of the room jid

hence the muc name is `friends\26family`

muc identity name is a user exposed field, hence this string should be properly unescaped to `firends&family`

the second solution which would also be ok is to simply not set this attribute at all.
Clients can do that themself if they want to

before you get panic to dive into escaping JIDs, let me show that unescaping JIDs is rather trivial

here my python impl

```python
_localpart_escape_chars = ' "&\'/:<>@'

def unescape_localpart(localpart):
    if localpart.startswith('\\20') or localpart.endswith('\\20'):
        # Escaped localparts are not allowed to start or end with \20
        # so this localpart must be already unescaped
        return localpart

    for char in _localpart_escape_chars:
        seq = "\\{:02x}".format(ord(char))
        localpart = localpart.replace(seq, char)

    for char in _localpart_escape_chars + "\\":
        seq = "\\5c{:02x}".format(ord(char))
        localpart = localpart.replace(seq, "\\{:02x}".format(ord(char)))

    return localpart
```

**Comment by badlop** [comment]
> Create a MUC with a JID: `friends&family@chat.yourserver.com`

Those characters are not allowed in the username or server: " & ' / : < > @

**Comment by badlop** [comment]
From what I see, ejabberd doesn't take any specific action or implements anythin regarding XEP-0106. So, the easiest solution is the second:

```diff
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index a96f7ce35..6790d1aff 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -4059,7 +4059,7 @@ make_disco_info(_From, StateData) ->
 	   end,
     #disco_info{identities = [#identity{category = <<"conference">>,
 					type = <<"text">>,
-					name = get_title(StateData)}],
+					name = (StateData#state.config)#config.title}],
 		features = Feats}.
 
 -spec process_iq_disco_info(jid(), iq(), state()) ->
```

**Comment by lovetox** [comment]
Yes i think thats alright, what does `(StateData#state.config)#config.title}` mean?

**Comment by badlop** [comment]
It's the original room title, or empty string when not set. And the xmpp library hides the `name` attribute when the value is empty. So, for a room with title set, this is returned:
```xml
    <identity name='This is a room title'
	type='text'
	category='conference'/>
```
and a room without title set:
```xml
    <identity type='text'
	category='conference'/>
```

**Comment by lovetox** [comment]
yes i think thats much better
