### ISSUE TITLE
How to restrict ejabberd domain signup?

### ISSUE THREAD

**Issue by ModeFX22** [processone/ejabberd#3372]
Hello! I am about to make my XMPP server public but there is one problem, we use "staff.example.com" for server administrator accounts, I only want users to register using example.com so how could I do that?

Sincerely
ModeFX

**Comment by licaon-kter** [comment]
So you have 2 hosts? Use https://docs.ejabberd.im/archive/20_04/toplevel/#host-config and setup each as you wish.

**Comment by ModeFX22** [comment]
I'm kind of confused by this guide. I want to allow registrations only at bobelifx.pro, not in any other host. that's what I want
host_config:
bobelifx.pro
mod_register:
    ip_access: all
   password_strength: 32
  registration_watchers: [modefx@staff.bobelifx.pro, joshuaz@staff.bobelifx.pro, boat@staff.bobelifx.pro]

I tried doing this but got the following: Job for ejabberd.service failed because the control process exited with error code. See "systemctl status ejabberd.service" and "journalctl -xe" for details.

**Comment by licaon-kter** [comment]
Right, so do as it said or look in ejabberd.log, what's the actual error?

**Comment by ModeFX22** [comment]
Aug 28 21:51:16 bobelifx.pro ejabberdctl[7787]: Error: error
Aug 28 21:51:16 bobelifx.pro ejabberdctl[7787]: Error: "Failed to read YAML file '/opt/ejabberd/conf/ejabberd.yml': Syntax error on line 25 at position 1: could not find expected ':'"
Aug 28 21:51:16 bobelifx.pro systemd[1]: ejabberd.service: Control process exited, code=exited status=1
Aug 28 21:51:16 bobelifx.pro systemd[1]: Reload failed for XMPP Server.
-- Subject: Unit ejabberd.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit ejabberd.service has finished reloading its configuration
--
-- The result is failed.
Aug 28 21:51:16 bobelifx.pro sudo[7784]: pam_unix(sudo:session): session closed for user root
Aug 28 21:51:20 bobelifx.pro sudo[7847]:   modefx : TTY=pts/0 ; PWD=/home/modefx ; USER=root ; COMMAND=/bin/journalctl -xe
Aug 28 21:51:20 bobelifx.pro sudo[7847]: pam_unix(sudo:session): session opened for user root by modefx(uid=0)

**Comment by licaon-kter** [comment]
Right, so fix line 25 then add `:` after `.pro` or smth

**Comment by ModeFX22** [comment]
Done, another error:-- Subject: Unit ejabberd.service has begun reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit ejabberd.service has begun reloading its configuration
Aug 28 21:54:12 bobelifx.pro ejabberdctl[7951]: Error: error
Aug 28 21:54:12 bobelifx.pro ejabberdctl[7951]: Error: "Invalid value of option host_config: Expected map, got empty string instead"
Aug 28 21:54:12 bobelifx.pro systemd[1]: ejabberd.service: Control process exited, code=exited status=1
Aug 28 21:54:12 bobelifx.pro systemd[1]: Reload failed for XMPP Server.
-- Subject: Unit ejabberd.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit ejabberd.service has finished reloading its configuration
--
-- The result is failed.
Aug 28 21:54:12 bobelifx.pro sudo[7948]: pam_unix(sudo:session): session closed for user root
Aug 28 21:54:15 bobelifx.pro sudo[8009]:   modefx : TTY=pts/0 ; PWD=/home/modefx ; USER=root ; COMMAND=/bin/journalctl -xe
Aug 28 21:54:15 bobelifx.pro sudo[8009]: pam_unix(sudo:session): session opened for user root by modefx(uid=0)
lines 1153-1203/1203 (END)⏎

**Comment by licaon-kter** [comment]
Share that part of the config

**Comment by ModeFX22** [comment]
hosts:
  - "bobelifx.pro"
  - "boat1337.com"
  - "beaugholdsworth.pro"
  - "staff.bobelifx.pro"
  - "droidlogical.site"

host_config:
bobelifx.pro:
mod_register:
ip_access: all
password_strength: 32
registration_watchers: [modefx@staff.bobelifx.pro, joshuaz@staff.bobelifx.pro, boat@staff.bobelifx.pro]
Here is the config

**Comment by badlop** [comment]
In YAML, the spaces in the beginning of a line are very impotant. In the configuration examples you show, there aren't spaces. Please copy the lines as you have them, and use Github's formatting to show us the lines as you see them in your configuration file.
