### ISSUE TITLE
Create user PEP nodes using admin account

### ISSUE THREAD

**Issue by gsohn** [processone/ejabberd#3374]
## Environment

- ejabberd version: 20.04
- users are authenticated with jwt

We are trying to create pep nodes for users using a client connected with an admin account. Theses nodes have to be created when a user is added in our system, and can't be created by the xmpp client itself. We have no issue when we create nodes using our pubsub service domain as host. 

We have this error and don't figured out how to deal with that... :/ 

```
{
  "status" : 422,
  "code" : "error.nodeOperationException",
  "message" : "org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from gziqfxxswbcia4.1577630572043@im.XXX.XXX: XMPPError: subscription-required - auth [Not subscribed]"
}
```

Thanks

**Comment by mremond** [comment]
PEP nodes are by design assigned to account. Only its owner have permission to it.
Not sure what  you want to do but your use case, but maybe your are more looking for general pubsub use case.

**Comment by gsohn** [comment]
Thanks for your answer Mickael, you were right about the PEP.
I worked with Lance (from stanza.io) and we decided to create leaf node for our specific needs. (not so specific)
