### ISSUE TITLE
Send POST Http request If user offline

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3378]
Hi,

I am looking to the solution where I wanted to send the message as a PUSH Notification if receiving user is offline.

I don't need to configure PUSH Notification right on jabbered, I have another server which handles all the plumbing of iOS/Android PUSH Notification. What I am looking to send the message as a plain POST REQUEST to my server .

Looking forward for the suggestions and guidance.

Thanks

**Comment by licaon-kter** [comment]
There are all sorts of modules like https://github.com/PH-F/mod_offline_http_post but they tend to get stuck for old versions only.

**Comment by AtifShahzed** [comment]
Oh ho! so for new version is there any other way to achieve the desired task.
Thanks

**Comment by mremond** [comment]
The best approach is to update that contribution to work with newer version of ejabberd. If you have time to update it, this would be a welcome patch.

**Comment by laurohen** [comment]
I have used this module in previous versions.. Let's do it? @mremond @AtifShahzed  @licaon-kter

**Comment by Neustradamus** [comment]
@badlop: Nice!

Can you look for https://github.com/PH-F/mod_offline_http_post_group too?

**Comment by Neustradamus** [comment]
@badlop: Have you done a PR: https://github.com/PH-F/mod_offline_http_post/pulls?
