### ISSUE TITLE
MUC Message does not work from Rest API

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3380]
HI,

I have configure MUC with Rest Api working fine. I am able to create room through Rest Api and send invitation to the user to join the room and when user receive request they can join the MUC room
Whole workflow is working fine.

The only problem is when I use send message api and use MUC room JID to send room message so it does not work although I receive 200 status code with 0 in response which means success but message does not deliver to the MUC room.

Is there any special settings are required to make it working.

Thanks

**Comment by badlop** [comment]
> when I use send message api and use MUC room JID to send room message

Did you check this explanation in the send_message documentation?

```
$ ejabberdctl help send_message

  Command Name: send_message

  Arguments: type::binary
             from::binary
             to::binary
             subject::binary
             body::binary
             
  Returns: res::rescode

  Tags:  stanza

  Description:  Send a message to a local or remote bare of full JID

When sending a groupchat message to a MUC room,
 FROM must be the full JID of a room occupant,
 or the bare JID of a MUC service admin,
 or the bare JID of a MUC/Sub subscribed user.
```
