### ISSUE TITLE
Please clarify logging documentation

### ISSUE THREAD

**Issue by clavinet** [processone/ejabberd#3382]
ejabberd.log warns that two logging options are now deprecated and have no effect:

> [warning] <0.89.0>@ejabberd_config_transformer:warn_removed_option:557 Option 'log_rotate_date' is deprecated and has no effect anymore. Please remove it from the configuration.
> [warning] <0.89.0>@ejabberd_config_transformer:warn_removed_option:557 Option 'log_rate_limit' is deprecated and has no effect anymore. Please remove it from the configuration.

The documentation still mentions it in examples:
https://docs.ejabberd.im/admin/configuration/basic/#logging

Is time-based log rotation removed now?
For example, if I only want to keep logs for a week, is this possible with ejabberd or do I have to use an external tool?

**Comment by weiss** [comment]
This is no longer supported (with Erlang/OTP 22+).  You need to use an external tool indeed.

**Comment by clavinet** [comment]
Okay, thanks.

**Comment by clavinet** [comment]
Perhaps the examples for "log_rotate_date" could be removed, since they have no function anymore.

**Comment by badlop** [comment]
Right, those two options were removed in ejabberd 20.01, more concretely in e4a8afb15d6c995b294a60ed150b86775e2f6805
