### ISSUE TITLE
Protect ejabberd server

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3386]
Hi,

I have configured rest api but these api's can accessible from the IP which is another server which I have assigned but there is a lot of MUC rooms created and use by someone else.
I just wanted to know how they can create room if they have no have access to my server.
Can somebody help me to prevent these attacks.

Thanks

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im/admin/configuration/basic/#access-rules ?
