### ISSUE TITLE
Docs: Instructions in "Extending ejabberd / Modules Development" are not correct for ejabberd version 20.07

### ISSUE THREAD

**Issue by trampi** [processone/ejabberd#3389]
Hello everyone,

the official documentation for writing plugins does not work for version 20.07:
https://docs.ejabberd.im/developer/extending-ejabberd/modules/#introduction

Specifically, the sample code does not include the definition of `mod_doc/0`.

Also, the documented steps for compiling / running lazy loaded plugins (using ejabberd ecs docker images) do not work. The following steps do works:

1) create and fill the following directory structure:
```
$PROJECT_DIR/sources/mod_hello_world/COPYING
$PROJECT_DIR/sources/mod_hello_world/README.txt
$PROJECT_DIR/sources/mod_hello_world/mod_hello_world.spec
$PROJECT_DIR/sources/mod_hello_world/src/mod_hello_world.erl
```
2) run `git init` in `$PROJECT_DIR/sources/mod_hello_world´

3) mount the plugin like this, start the container:
```
- "./sources/mod_hello_world:/home/ejabberd/.ejabberd-modules/sources/mod_hello_world"
```

4) run `ejabberdctl module_install mod_hello_world` in the container, it will compile the module and fail with the following message:
```
Error: error
Error: {"ebin/mod_hello_world.beam",enoent}
```

5) shutdown the container, change the mount to match the following definition:
```
- "./sources/mod_hello_world:/home/ejabberd/.ejabberd-modules/mod_hello_world"
```

6) you now may add `mod_hello_world: {}` to ejabberd.yml in the plugin section and start ejabberd.

7) To update the plugin, remove the binary in `$PROJECT_DIR/sources/mod_hello_world/ebin/mod_hello_world.ebeam`, comment the definition from step 5 out, change the volume definition from step 4 to match step 2 and repeat everything described above.

I would like to update the documentation and will open a PR for that, but before that, I would like to know if the steps above can be shortened? It seems like a bug to me that I have to move the compiled plugin manually.

**Comment by licaon-kter** [comment]
Should this be in https://github.com/processone/ejabberd-contrib instead?

**Comment by trampi** [comment]
@licaon-kter I thought about rising it in https://github.com/processone/docs.ejabberd.im, because it is mostly a documentation issue. However, I was not really sure if it would be noticed anywhere except here.

**Comment by badlop** [comment]
> the sample code does not include the definition of mod_doc/0.

Right. I've now updated the sample code. And also added some minor corrections to the explanations.

> Also, the documented steps for compiling / running lazy loaded plugins (using ejabberd ecs docker images) do not work.

Well, the documented steps are for the binary installer, as mentioned in the first paragraph.

If that doesn't work when using Docker, then it would be nice to add a new section in that page, specific for Docker, with your detailed steps.

> I would like to update the documentation and will open a PR for that, 

I have no problem adding that to the git repo myself.

> but before that, I would like to know if the steps above can be shortened? It seems like a bug to me that I have to move the compiled plugin manually.

Unfortunately I have very little experience with Docker, so I cannot improve your steps. I will test them next week and I guess I can add your steps as they are to the docs site. If anybody can improve them now or later, it will be welcomed of course :)

**Comment by trampi** [comment]
Thank you for your response, @badlop!
Will keep an eye out for the improved documentation. Should I have anything to add I will not hesitate and open a PR :)

Have a nice day!
trampi

**Comment by badlop** [comment]
I finaly tried that. I was able to remove one of your steps... but found a problem with permissions to write in the volume, so I had to add another step to grant ownership.

The full list of steps would be something like this, in case you or anybody else can try them, find other problems, or improve:

1. Create a local directory for the contributed modules:
```
mkdir docker-modules
```

2. Then create the directory structure for your custom module:
```
cd docker-modules

mkdir -p sources/mod_hello_world/
touch sources/mod_hello_world/mod_hello_world.spec

mkdir sources/mod_hello_world/src/
mv mod_hello_world.erl sources/mod_hello_world/src/

mkdir sources/mod_hello_world/conf/
echo -e "modules:\n  mod_hello_world: {}" > sources/mod_hello_world/conf/mod_hello_world.yml

cd ..
```

3. Grant ownership of that directory to the UID that ejabberd will use inside the Docker image:
```
sudo chown 9000 -R docker-modules/
```

4. Start ejabberd in Docker:
```
sudo docker run \
  --name hellotest \
  -d \
  --volume "$(pwd)/docker-modules:/home/ejabberd/.ejabberd-modules/" \
  -p 5222:5222 \
  -p 5280:5280 \
  ejabberd/ecs
```

5. Check the module is available for installing, and then install it:
```
sudo docker exec -it hellotest bin/ejabberdctl modules_available
mod_hello_world []

sudo docker exec -it hellotest bin/ejabberdctl module_install mod_hello_world
```

6. If the module works correctly, you will see the Hello string in the ejabberd logs when it starts:
```
sudo docker exec -it hellotest grep Hello logs/ejabberd.log
2020-10-06 13:40:13.154335+00:00 [info]
  <0.492.0>@mod_hello_world:start/2:15 Hello, ejabberd world!
```

**Comment by alessandrojcm** [comment]
> I finaly tried that. I was able to remove one of your steps... but found a problem with permissions to write in the volume, so I had to add another step to grant ownership.
> 
> The full list of steps would be something like this, in case you or anybody else can try them, find other problems, or improve:
> 
>     1. Create a local directory for the contributed modules:
> 
> 
> ```
> mkdir docker-modules
> ```
> 
>     1. Then create the directory structure for your custom module:
> 
> 
> ```
> cd docker-modules
> 
> mkdir -p sources/mod_hello_world/
> touch sources/mod_hello_world/mod_hello_world.spec
> 
> mkdir sources/mod_hello_world/src/
> mv mod_hello_world.erl sources/mod_hello_world/src/
> 
> mkdir sources/mod_hello_world/conf/
> echo -e "modules:\n  mod_hello_world: {}" > sources/mod_hello_world/conf/mod_hello_world.yml
> 
> cd ..
> ```
> 
>     1. Grant ownership of that directory to the UID that ejabberd will use inside the Docker image:
> 
> 
> ```
> sudo chown 9000 -R docker-modules/
> ```
> 
>     1. Start ejabberd in Docker:
> 
> 
> ```
> sudo docker run \
>   --name hellotest \
>   -d \
>   --volume "$(pwd)/docker-modules:/home/ejabberd/.ejabberd-modules/" \
>   -p 5222:5222 \
>   -p 5280:5280 \
>   ejabberd/ecs
> ```
> 
>     1. Check the module is available for installing, and then install it:
> 
> 
> ```
> sudo docker exec -it hellotest bin/ejabberdctl modules_available
> mod_hello_world []
> 
> sudo docker exec -it hellotest bin/ejabberdctl module_install mod_hello_world
> ```
> 
>     1. If the module works correctly, you will see the Hello string in the ejabberd logs when it starts:
> 
> 
> ```
> sudo docker exec -it hellotest grep Hello logs/ejabberd.log
> 2020-10-06 13:40:13.154335+00:00 [info]
>   <0.492.0>@mod_hello_world:start/2:15 Hello, ejabberd world!
> ```

Hey! I tried this on the latest `ejabberd/ecs` image. On top of that, I needed to create an `ebin` folder inside my module's file structure; this is for the output of the compiled module. The module compiles ok, but when I try to `ejabberctl module_install my_module` I get:

```bash
~ $ ./bin/ejabberdctl module_install my_module
Error: error
Error: {"conf/my_module.yml",enoent}
```

Any ideas? I read somewhere that ejabberd looks for modules inside `/opt/.ejabberd-modules`, but if I bind to that location my module doesn't even get listed. I also tried by moving the `conf` to the root of the `.ejabberd-modules` folder (so it will look like `/home/ejabberd/.ejabberd-modules/conf/my_module.yml`) but no luck either.
