### ISSUE TITLE
ejabberd's clock doesn't sync after suspend

### ISSUE THREAD

**Issue by sonnyp** [processone/ejabberd#3390]
## Environment

- ejabberd version: 20.07
- Erlang version: V10.3.4
- OS: Linux (Fedora 32)
- Installed from: official rpm

## Bug description

When the computer comes out of suspend, ejabberd's clock remains out of sync (by the time the computer was suspended).

You can test by sending a simple

```
<iq type='get'>
  <time xmlns='urn:xmpp:time'/>
</iq>
```

before and after suspend.

Of course in real word conditions it's not expected to suspend ejabberd but on development environment and VMs it can lead to confusing issues, specially with mam.

If this isn't something you'd like to actively implement maybe I can send a PR with a "Troubleshooting" section to https://docs.ejabberd.im/developer/ ?

**Comment by sonnyp** [comment]
Related https://github.com/processone/ejabberd/issues/2834

**Comment by prefiks** [comment]
This should be fixed by b89f3c442c3c005c5cf66dbd75d52c68634d3ba8, previous time source was using time that was observing or not time warps depending of runtime flags, but in this case we really don't want this, so let's use better time source for this purpose.

**Comment by sonnyp** [comment]
many thanks

**Comment by sonnyp** [comment]
@prefiks correct me if I'm wrong but I understand your commit is only gonna solve the issue for `iq`s ?

What about timestamps for new `<message/>`.

To be clear, my main issue was with mam, I can share a test case if you like.

**Comment by prefiks** [comment]
Yes this only changes mod_time, with mam we can't use system time, as we need monotonic clock (as we use those for message ordering), so i need to see what can we use, and if this will not cause some problems.

**Comment by sonnyp** [comment]
I see, thank you for clarifying.

Then I would suggest to leave `mod_time` the way it was until a solution is found for mam and archives.

It allow clients/users to detect time drift and `<time xmlns='urn:xmpp:time'/>` is really about querying the entity time. If ejabberd internal clock is out of sync, it should be reflected in `<time xmlns='urn:xmpp:time'/>`.

Cheers!

**Comment by prefiks** [comment]
Ideally for mam you should be using data from last received stanza-id/archived, that way you should know exact id of message to get messages after that one, but indeed it would be nice to have correct time here. Looks like erlang is using linux CLOCK_MONOTONIC for timer that mam uses, and that seems to not account for time that system was suspended. There is CLOCK_BOOTTIME that count those, but i really don't see any flag in erlang that can make it use that, so that's can be a problem.

**Comment by sonnyp** [comment]
Unless the UI is time based (calendar for example) I agree however the issue documented at https://docs.modernxmpp.org/client/protocol/#ids-of-outgoing-messages prevents us from doing so reliably.

Not related to the issue directly and fairly common but in case it's of interest, here is how we use mam:

"Inbox" where we display the last message and number of unread messages. The way we do this is by storing the last read message timestamp in the client and request messages since then upon opening the app. 
It works fine for us as we don't have multi-devices for now but https://xmpp.org/extensions/inbox/inbox.html would be the way forward eventually.

"Load earlier". We load chat history as user scrolls up. We could use message ids with the workaround proposed in https://github.com/modernxmpp/modernxmpp/issues/32#issuecomment-690237832 but it's not worth it at this stage.

**Comment by weiss** [comment]
> we need monotonic clock (as we use those for message ordering)

Then again, we can't guarantee monotonicity across node restarts (nor across the cluster) anyway.  If an admin lets the OS clock perform backward time warps, MAM messages being out of order will just be one of many fuckups he's seeing.  Maybe we _could_ declare this problem to be out of our scope, whereas coping with hibernation isn't really (despite that obviously being uncommon on servers).  But yes, I'm aware this might not be what the customer who's clock goes mad wants to hear :smile:

Anyway, @sonnyp, maybe a quick solution for you would be to set [the run-time flag][1] @prefiks mentioned by adding `+C multi_time_warp` to the [`ERL_OPTIONS`][2] in your `ejabberdctl.cfg` file?  (This is [recommended][3] by the OTP people anyway, if the code is time-warp-safe.)

[1]: https://erlang.org/doc/apps/erts/time_correction.html#time-warp-modes
[2]: https://github.com/processone/ejabberd/blob/20.07/ejabberdctl.cfg.example#L105-L117
[3]: https://erlang.org/doc/apps/erts/time_correction.html#multi-time-warp-mode
