### ISSUE TITLE
Query paging flip urn:xmpp:mam:2#extended XEP-0313

### ISSUE THREAD

**Issue by lucastimotiofirmino** [processone/ejabberd#3398]
**Describe the solution you'd like**

I would like to rely on support for 'urn:xmpp:mam:2#extended' specified in xep-0313.

[https://xmpp.org/extensions/xep-0313.html#query-paging-flip](https://xmpp.org/extensions/xep-0313.html#query-paging-flip)

**Comment by penna-superlogica** [comment]
I have the same question!

**Comment by lucastimotiofirmino** [comment]
Can anyone offer an alternative?

My project depends a lot on this functionality.

**Comment by badlop** [comment]
I've implemented support for Flipped Pages as described in https://xmpp.org/extensions/xep-0313.html#query-paging-flip

Notice that #extended is not advertized, because that would require implementing other features, like https://xmpp.org/extensions/xep-0313.html#archive-metadata and https://xmpp.org/extensions/xep-0313.html#query-limit-id

**Comment by badlop** [comment]
I think there is no need to enable anything specific in the configuration for that feature to be available.

**Comment by alesito85** [comment]
I have the same problem. Installed ejabberd_24.07-1_amd64.deb and extended usage isn't advertised.

**Comment by badlop** [comment]
>  Installed ejabberd_24.07-1_amd64.deb and extended usage isn't advertised.

Right, `extended` is not advertised for a reason explained in comment https://github.com/processone/ejabberd/issues/3398#issuecomment-709554509

**Comment by skazi0** [comment]
@badlop are there any plans to implement full #extended?

**Comment by jeroenhabets** [comment]
@skazi0 (and other visitors) I've logged a feature request for #extended (https://github.com/processone/ejabberd/issues/4530) as this issue (#3398) asking for [query-paging-flip](https://xmpp.org/extensions/xep-0313.html#query-paging-flip) has been resolved and closed.
