### ISSUE TITLE
Avatar set and get  from Rest Api

### ISSUE THREAD

**Issue by LumiProj** [processone/ejabberd#3401]
Hi All,

I am looking to set the user Avatar from the rest api. I searched a lot on internet but not able to find the api with complete parameter details.

Can somebody help me on this regards so that would be great.

Thanks

**Comment by badlop** [comment]
There is an example PHP script to set the avatar in the vcard in https://github.com/processone/ejabberd/issues/3266#issuecomment-628662242

**Comment by LumiProj** [comment]
Thanks a lot.
