### ISSUE TITLE
Elixir Ejabberd Auth Module Support

### ISSUE THREAD

**Issue by dabslants** [processone/ejabberd#3404]
**Is your feature request related to a problem? Please describe.**
I am unable to use an Elixir module as an auth_method. 

**Describe the solution you'd like**
Line 840 of ejabberd_auth.erl should be modified with the support for the following format: EjabberdAuthModule 

https://github.com/processone/ejabberd/blob/d9cb6d1af719dd53c670aa4cfc08d927c5e1954f/src/ejabberd_auth.erl#L840

**Comment by badlop** [comment]
Hi! Can you provide an example of what doesn't work right now, that would work with the change you propose?
