### ISSUE TITLE
mod_muc_sql SQL queries timing out with 90 member groups being created

### ISSUE THREAD

**Issue by scottcc** [processone/ejabberd#3409]
## Environment

- ejabberd version: 20.07_1
- Erlang version: `erl +V` : Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.0.4
- OS: Mac OSX
- Installed from: distro package (homebrew, see below)

```
scottc@up-his-tree ~ % brew info ejabberd
ejabberd: stable 20.07 (bottled), HEAD
XMPP application server
https://www.ejabberd.im
Conflicts with:
  couchdb (because both install `jiffy` lib)
/usr/local/Cellar/ejabberd/HEAD-5ec2143 (786 files, 14.4MB)
  Built from source on 2020-03-26 at 17:50:19
/usr/local/Cellar/ejabberd/20.07_1 (806 files, 14.6MB) *
  Poured from bottle on 2020-09-14 at 20:13:14
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ejabberd.rb
License: GPL-2.0
==> Dependencies
Required: erlang@22 ✔, gd ✔, libyaml ✔, openssl@1.1 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
If you face nodedown problems, concat your machine name to:
  /private/etc/hosts
after 'localhost'.

To have launchd start ejabberd now and restart at login:
  brew services start ejabberd
Or, if you don't want/need a background service you can just run:
  /usr/local/sbin/ejabberdctl start
==> Analytics
install: 112 (30 days), 429 (90 days), 1,434 (365 days)
install-on-request: 112 (30 days), 425 (90 days), 1,391 (365 days)
build-error: 0 (30 days)
```

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: info
...
```

## Errors from error.log

2020-10-06 18:37:03.374734+00:00 [error] <0.348.0>@ejabberd_sql:check_error/2:1229 SQL query 'Q47509885' at {mod_muc_sql,71} failed: <<"timed out">>
2020-10-06 18:44:14.686667+00:00 [error] <0.351.0>@ejabberd_sql:check_error/2:1229 SQL query 'Q47509885' at {mod_muc_sql,71} failed: <<"timed out">>
2020-10-07 15:34:01.421242+00:00 [error] <0.490.0>@ejabberd_sql:check_error/2:1229 SQL query 'Q27190922' at {mod_muc_sql,413} failed: <<"timed out">>

## Bug description

Hi there. We are using the mod_muc plugin, and sometimes need to create large groups (ie, 90 members). Further, we're using a local (reasonably configured) PostgreSQL database (12.4) which connects via 127.0.0.1. No slow logs in the postgres logs that we can see - however, the above queries seem to be timing out. What we experience when the client is attempting to use a group soon after creation (say, posting a message or image to that group) is that the response coming back to the client times out. *However*, checking that group say, 60 seconds or so later, and the message (and media) are correctly there, and distributed to other members of the group.

Any areas we can look at? We also believe this may have degraded since 20.04, as we did this test then and did not experience the same effects then. We'd be happy to look a tables or queries, any suggestion at all!

Many thanks, fantastic product.

**Comment by licaon-kter** [comment]
Can you share a gist link of the config?

**Comment by scottcc** [comment]
Thanks - of course! Edited slightly to remove sensitive information only.

https://gist.github.com/scottcc/a6a610b4fb1e7159d5c1947056a12551

**Comment by licaon-kter** [comment]
Which .sql file did you use to setup?

**Comment by scottcc** [comment]
The non-multi-tenant one: https://raw.githubusercontent.com/processone/ejabberd/master/sql/pg.sql

**Comment by prefiks** [comment]
So those timed out queries are one for setting room options, and the other for getting list of subscribers, so i also don't see why those would get slow, possibly some other query before those get slow? I see you have mod_shared_roster loaded in you config, are you using shared roster for real? This module doesn't work too great with sql backend and can generate quite a bit of queries, adding `use_cache: true` option to that module can help with it though. You could also see if adding `sql_pool_size: N` will help, by default ejabberd will use 10 there (which will make it keep 10 concurrent connection active), possibly increasing this will help in you situation

**Comment by scottcc** [comment]
Thanks @prefiks - these are helpful suggestions! We do indeed use the `mod_shared_roster` module, and as these are dedicated machines/instances, I think increasing the `sql_pool_size` up to say 50 would be a good first step. We do have settings on for postgres to log slow queries (anything longer than 3 seconds currently) - and we're not seeing anything else show up so not sure how a slow query could be blocking in front. We'll let you know if these two settings improve things though, thanks very much for the suggestions!

**Comment by mremond** [comment]
I am closing it now as it seems addressed, but please, let us know how it goes.
