### ISSUE TITLE
LDAP/Active Directory shows only 1000 user

### ISSUE THREAD

**Issue by wurstdog** [processone/ejabberd#3417]
## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`
- OS: Linux CentOS 8 
- Installed from: official deb/rpm 

## Errors from error.log/crash.log

No errors

## Bug description

ldapsearch shows 1914 user entries in our active directory but ejabberdctl reegistered_users shows only 1000.
the same behavior we have also in the webadmin and on the clientside.
Everything else runs as expected.

**Comment by badlop** [comment]
Exactly 1000? That's a very precise number... it seems as if somebody is limiting it, but I didn't find any option in ejabberd to configure such a limit in LDAP, and not any limit in the source code related to LDAP.

Some wild ideas, Is it always 1000 returned? Are they always the same 1000 accounts? If you try to login with an account not shown in that list, does auth work for that account?

**Comment by wurstdog** [comment]
Hi badlop,
yes it seems like it works.

My test ad and my ugly powershell script:
`
foreach ($i in 1..10000){
    New-ADUser -Name "test$i" -AccountPassword(ConvertTo-SecureString "<secret password>" -AsPlainText -Force) -Enabled $True -Path "CN=Users,DC=test,DC=local" -OtherAttributes @{'Title'="test$i";'mail'="test$i@test.local"}
    Add-ADGroupMember -Identity ejabberd -Members test$i
}
`
 creates 10000 users in my ejabberd group
 `
$members = Get-ADGroupMember -Identity ejabberd
foreach ($i in $members){
$count += 1
Write-Host "login: $i"
}
Write-Host "$count"
`
Output:
...
Login: CN=test1491,CN=Users,DC=test,DC=local
...
10000

to remove test members
`
foreach ($i in 1..10000){
   Remove-ADUser test$i -Confirm:$False
}
 `

on my ejabberd:
`
ejabberdctl registered_users <ejabberd virthost>|wc -l
`
prints out 1000

on my client i can login with any account above 1000

test1491@<ejabberd virt host> works for me  and this account is not in the ejabberd registered list.

Some ideas?

**Comment by badlop** [comment]
I cannot reproduce that problem. I've installed ejabberd 21.04, OpenLDAP slapd 2.4.57, configured similar to you:

```yaml
ldap_servers:
  - "localhost"
ldap_port: 389
ldap_encrypt: none
ldap_rootdn: "cn=admin,dc=example"
ldap_password: "admin"
ldap_base: "dc=example"
ldap_uids:
  - "cn"
auth_method: ldap
```
and registered 4,000 accounts in ldap.

I get that number correctly, both in ejabberd's webadmin and in:
```
ejabberdctl registered_users ldap.localhost | wc -l
5000
```

**Comment by Neustradamus** [comment]
@wurstdog: Any news on it?
