### ISSUE TITLE
Can't change resume_timeout for Ejabberd

### ISSUE THREAD

**Issue by rahulchhabra07** [processone/ejabberd#3419]
## Environment

- ejabberd version: 16.09
- OS: Linux (Debian)
- Installed from: source 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_resume_timeout: 1
    stream_mgmt_resume_timeout: 1
    resume_timeout: 1
    resend_on_timeout: true

```yaml
loglevel: 5
...
```

## Errors from error.log/crash.log

15:29:34.759 [debug] Send XML on stream = {{{enabled xmlns='urn:xmpp:sm:3' id='g2gCbQAAAAdleGFtcGxlaANiAAAGRGIAAmndYQI=' resume='true' max='300'/}}}
( Had to change '<' to '{' and vice-versa )

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
Even if I set resume_timout to 1, the logs still show it as 300 and it's leading to unexpected behavior

**Comment by licaon-kter** [comment]
Can you update to a less than 4 years old version though?

**Comment by rahulchhabra07** [comment]
Yeah, I know, was this some bug that got fixed later? I read some forum posts w prev versions that had this working.

**Comment by licaon-kter** [comment]
I don't see that option is `listen:` but in a module: https://docs.ejabberd.im/archive/20_04/modules/#mod-stream-mgmt

Now, maybe that was changed in the last... 4 years

**Comment by weiss** [comment]
I don't remember such a bug, but if there was one, it likely has been fixed, as things were heavily refactored (as @licaon-kter says, stream management is now handled and configured by a separate module).
