### ISSUE TITLE
Windows Installer Missing for 20.07

### ISSUE THREAD

**Issue by stefanLeo** [processone/ejabberd#3420]
## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`
- OS: Windows Server
- Installed from: NOT AVAILABLE

## Bug description
The latest eJabberd Version 20.07 - community server - does not come with a Windows installer:
https://www.process-one.net/en/ejabberd/downloads/

Is that for a reason and will it stay that way going forward?

**Comment by licaon-kter** [comment]
Use the secret link, but don't tell anyone: https://www.process-one.net/downloads/downloads-action.php?file=/20.07/ejabberd-20.07-windows.exe

**Comment by stefanLeo** [comment]
Hi 

Thx for the link - As recently we got 20.12 and again no Windows link - is there another secret link? 

Br
Stefan

**Comment by licaon-kter** [comment]
We need more magic @mremond

**Comment by stefanLeo** [comment]
@licaon-kter, @mremond do you plan to fix this issue? Thx for your help & support!

**Comment by stefanLeo** [comment]
Hi  again

Seems like there also is no Windows package for 21.01.

BR

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by NataliaDobryaeva** [comment]
Hi @licaon-kter, @mremond,

Could you please provide a link to 21.01 windows installer?

Thanks in advance!

**Comment by badlop** [comment]
Hi @NataliaDobryaeva what Windows version do you use and what ejabberd version do you have installed?

I'm writting a tutorial to install ejabberd in Windows using Docker, and it would be nice if some people can test it before publishing.

**Comment by badlop** [comment]
> Thanks, it would be nice. I'm using Windows 10. Recently I've installed 20.07 (from the link above).

Ok, I've invited you to view a repository with a batch file that automatizes the installation, and the tutorial. When you try it, fill a new issue there with your results. Thanks for testing!

**Comment by Neustradamus** [comment]
And all other Windows machines < Windows 10?

**Comment by badlop** [comment]
Thanks to @NataliaDobryaeva and @f055 testing the Windows 10 tutorial, and confirming it works correctly, it's now published https://www.process-one.net/blog/install-ejabberd-on-windows-10-using-docker-desktop/

This allows to install any current, past and future ejabberd release from Docker Hub, so I guess this ticker can be closed.

**Comment by Neustradamus** [comment]
Dear badlop: No, how it is possible for all other Windows OS before Windows 10?

**Comment by stefanLeo** [comment]
Hi

And what about Windows Server? I would guess installing it on a server OS is much more common.

BR

**Comment by badlop** [comment]
> And what about Windows Server?

No idea, I don't have that operating system. Try it and report your findings. Does Docker Desktop run in it? If not, does Docker Toolbox run in it?

**Comment by badlop** [comment]
> And what about Windows Server? I would guess installing it on a server OS is much more common.

I got access to a Windows 7 to test the tutorial that uses Docker Toolbox.
https://www.process-one.net/blog/install-ejabberd-on-windows-7-using-docker-toolbox/

Were you able to test what Docker software works in your Windows Server machine?

> And all other Windows machines < Windows 10?

Do you have all other Windows machines to test it? Because I don't have them.

If you are able to test the tutorials with other Windows versions, comment here your results.
