### ISSUE TITLE
The muc room can't restart when the process went away 20.04

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#3421]
## Environment

- ejabberd version: 20.04
- Erlang version: 21.0
- OS: ubuntu 18.04
- Installed from: source 

## Errors from error.log/crash.log

 [error] <0.432.0> Supervisor 'mod_muc_room_sup_example.com' had child undefined started with {mod_muc_room,start_link,undefined} at <0.492.0> exit with reason killed in context child_terminated

## Bug description

In the debug model, we can do like this.
```
(ejabberd@localhost)1> mod_muc:get_online_rooms(<<"conference.example.com">>).
[{<<"abcdef">>,<<"conference.example.com">>,<0.492.0>}]
(ejabberd@localhost)2>
(ejabberd@localhost)2> exit(pid(0,492,0), kill).
```

**Comment by Freyskeyd** [comment]
I see a similar behaviour on my cluster where some rooms are present in `mod_muc_mnesia` as `online` with a PID that is no longer alive.

Any messages/presences/IQ sent to the room is ignored and the process isn't restarted.

**Comment by prefiks** [comment]
I fixed that recently, it should work as expected in next release.

**Comment by badlop** [comment]
In that case, let's close this issue now. If the problem is still observed in the future, please reopen this issue to continue the investigation.

**Comment by jordan-king** [comment]
@prefiks is this the commit you're referring to in your comment from Mar 30? https://github.com/processone/ejabberd/commit/ca5d5f3b4caf64be6de272e33617364c32465e6d

**Comment by prefiks** [comment]
Yes that's this commit.
