### ISSUE TITLE
ejabberd Core - Debug Filter

### ISSUE THREAD

**Issue by ghost** [processone/ejabberd#3424]
Currently the loglevel can be set to debug to investigate issues. On larger servers this could result in large logfiles. 

Debugging might be easier when loglevel settings could be applied to seperate hosts, users/JIDs or MUCs. 

Additional config options could be use for that purpose: 
- `log_s2s: "server.domain.tld"` : only log s2s connections to/from a certain server domain
- 'log_s2s_file: "/path/to/file" : logfile for s2s logs
- `log_jid: "jid@server.domain.tld"` : only log connections to/from a certain JID (remote or local)
- 'log_jid_file: "/path/to/file" : logfile for JID logging
- `log_muc: "muc@server.domain.tld"` : only log MUC events/messages
- 'log_muc_file: "/path/to/file" : logfile for MUC logs

Instead of "/path/to/file" the keyword "syslog" should also be supported to log via syslog. 

This would make debugging easier, especially when being asked to provide a debug log for a problem. Additionally it would maybe count as improvement for data protection because you can then only debug those connections you need instead of connections of all users. 
The resulting file could easily be provided to developers when investigating issues.

**Comment by mremond** [comment]
The problem with this approach is that we would still generate more load as we will execute all debug statements and test against specific conditions. Currently, we simply ensure that the debug commands are simply skipped if not in debug loglevel.

We would rather not decrease the overall production performance to handle development or staging possible need for debug logs.
