### ISSUE TITLE
undefined parse transform 'lager_transform' when compiling with Elixir 1.11.2

### ISSUE THREAD

**Issue by joudinet** [processone/ejabberd#3430]
## Environment

- ejabberd version: 20.07
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.6
- OS: Arm Linux (Buildroot)
- Installed from: source

## Bug description
When compiling ejabberd, I got the following error:
```
src/ejabberd_config.erl:none: undefined parse transform 'lager_transform'
Compiling src/ejabberd_config.erl failed:
```
Could this error happen because ejabberd requires elixir 1.4.4 (which is more than 3 years old!) and I have elixir 1.11.2 installed on my system?
If I understand correctly, the `parse_transform` function has been deprecated since elixir 1.5, but I'm not sure if it is related to the error above. Is there a way to fix this issue other than having to install such an old version of Elixir?

**Comment by defp** [comment]
phoenix & ejabberd with elixir 1.11.2

```
      {:phoenix, "~> 1.5.7"},
      {:ejabberd, ">= 20.07", github: "processone/ejabberd"}
```

error log

```
mix compile
==> ejabberd
Compiling 267 files (.erl)
src/mod_mam.erl:690: field flippage undefined in record mam_query
src/mod_mam.erl:693: variable 'RSM' is unbound
src/mod_mam.erl:694: variable 'FlipPage' is unbound
src/mod_mam_mnesia.erl:27: Warning: behaviour mod_mam undefined
src/mod_mam_sql.erl:28: Warning: behaviour mod_mam undefined
could not compile dependency :ejabberd, "mix compile" failed. You can recompile this dependency with "mix deps.compile ejabberd", update it with "mix deps.update ejabberd" or clean it with "mix deps.clean ejabberd"
```

**Comment by badlop** [comment]
> Could this error happen because ejabberd requires elixir 1.4.4 (which is more than 3 years old!) and I have elixir 1.11.2 installed on my system?

I have Elixir 1.10.2 installed using Debian packages.

But anyway, when compiling ejabberd, it downloads the version that it wants:

```
$ ./configure --enable-elixir
...
==> ejabberd (get-deps)
Pulling elixir from {git,"https://github.com/elixir-lang/elixir",
                         {tag,"v1.4.4"}}
S'està clonant a «elixir»...
...

$ make
==> ejabberd (compile)
...
Compiled src/ejabberd_config.erl
...
```
