### ISSUE TITLE
XEP-0317: Hats Support

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#3433]
This XEP seems pretty useful for some MUC where specific roles need to be distributed to the members.
Prosody is already having a module for it https://modules.prosody.im/mod_muc_hats_api.html

**Comment by licaon-kter** [comment]
But XEP-0317 is deferred and whatever Prosody (in the module) or Converse (https://github.com/conversejs/converse.js/blob/5a57ded243d202c8666ab6370e1a517888b02e6c/spec/hats.js#L23) has implemented is custom and needs to be moved in a proper namespace and XEP?

**Comment by Neustradamus** [comment]
Deferred = There is not update since one year.

-> Support can be added without problem.

**Comment by edhelas** [comment]
@licaon-kter True, this request is maybe a bit too early, some more work is required before asking XEP support in ejabberd. 
I'll resubmit a new ticket if things are moving in the right direction in the future (or not). :)

**Comment by licaon-kter** [comment]
No need to close imho, sometimes things move in code first then as XEPs.
