### ISSUE TITLE
DNS resolve code needs to be revised

### ISSUE THREAD

**Issue by tfl** [processone/ejabberd#3438]
## Environment

- ejabberd version: 20.07
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1.3
- OS: Linux (Arch)
- Installed from: distro package | Source

Could someone please look at the DSN/Resolve code? If my `/etc/resolv.conf` file contains "`search .`" all s2s connections will fail with `internal server error` and code `500`. No other software on my system has problems with that, also Prosody does work fine with it.

File: inet_dns.erl
Functions involved: encode_name, encode_query_section, encode, make_query, res_query, res_getby_query

```exception exit: {function_clause,
[{inet_dns,encode_labels,
[<<0,4,1,0,0,1,0,0,0,0,0,0,13,95,120,109,112,112,
115,45,115,101,114,118,101,114,4,95,116,99,112,
5,114,111,111,109,115,7,100,105,115,109,97,105,
108,2,100,101>>,
{5,
{[<<"_xmpps-server">>,<<"_tcp">>,<<"rooms">>,
<<"dismail">>,<<"de">>,<<>>],
12,
{[<<"_tcp">>,<<"rooms">>,<<"dismail">>,
<<"de">>,<<>>],
26,nil,nil},
{[<<"rooms">>,<<"dismail">>,<<"de">>,<<>>],
31,
{[<<"dismail">>,<<"de">>,<<>>],
37,
{[<<"de">>,<<>>],45,nil,nil},
nil},
nil}}},
48,
[<<>>]],
[{file,"inet_dns.erl"},{line,694}]},
{inet_dns,encode_name,4,
[{file,"inet_dns.erl"},{line,675}]},
{inet_dns,encode_query_section,3,
[{file,"inet_dns.erl"},{line,269}]},
{inet_dns,encode,1,
[{file,"inet_dns.erl"},{line,240}]},
{inet_res,make_query,5,
[{file,"inet_res.erl"},{line,646}]},
{inet_res,make_query,4,
[{file,"inet_res.erl"},{line,614}]},
{inet_res,res_query,6,
[{file,"inet_res.erl"},{line,598}]},
{inet_res,res_getby_query,4,
[{file,"inet_res.erl"},{line,565}]}]}
in function  p1_server:terminate/7 (src/p1_server.erl, line 878)
```

Its the same for any other server...

**Comment by prefiks** [comment]
You have literally "search ." in your resolve.conf? For curiosity sake could you tell me why? I think this shouldn't be doing anything...

It's not really something thats easy to change how we handling, this is inside erlang standard library and we won't roll our own dns resolver. Looks like standard library is expecting that value in search has at between 1 and 63 chars after striping traling ".", so it doesn't handle that value properly.

**Comment by tfl** [comment]
I think systemd wrote this line. And yes, it was literally "search ." (without the quotes of course). My last /etc backup is from Nov 25th and did not contain that line and ejabberd worked at that time. I now disabled systemd-resolved and removed that line from /etc/resolv.conf. All went fine again. BTW: you have to be on loglevel 5 to see the actual error message (internal server error and code 500), but you won't see that it is probably caused by some dns/resolver problems... that is only visible on loglevel 4 - which makes no sense in my opinion...

You are right: it may be a problem of the erlang standard library. With your OK I will close this issue.
But we should keep this in our minds I think ;)

**Comment by prefiks** [comment]
Thank you,

Having that just didn't make sense to me (as that command tells resolver to try to look up for subdomain of domain from search - but that doesn't make sense with just .), but maybe you did need that for something special. I will close that ticket, as if this is bug (but i am not really sure), it should be filled in erlang bug tracker.
