### ISSUE TITLE
MySQL Upgrade to new schema

### ISSUE THREAD

**Issue by mkl262** [processone/ejabberd#3439]
Hi,
The `mod_admin_update_sql`  module doesn’t support the MySQL db, and I cant find a guide to migrate the old schema to the new one manually.

Please update the module to support MySQL, or create a guide for manual migration.

Thanks.

**Comment by weiss** [comment]
What's your motivation to migrate to the "new" schema?

**Comment by mkl262** [comment]
I need to hosts multiple domains on the same server.

**Comment by weiss** [comment]
You can do that using the standard schema just fine.  Create separate MySQL databases per host and specify the [`sql_database`][1] via [`host_config`][2].

[1]: https://docs.ejabberd.im/admin/configuration/toplevel/#sql-database
[2]: https://docs.ejabberd.im/admin/configuration/toplevel/#host-config
