### ISSUE TITLE
Libs versions usage

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3445]
While trying to pinpoint https://github.com/processone/ejabberd/issues/3443 I was doing this:
* compile
* make install
* test new version, say .87
* something
* decide to go back to .77
* remove .87 folder
* starting .77 fine

But login still failed.
So I delete the user, thinking that the Mnesia table got screwed, dunno upgraded by the sha commits or smth
Try to create the user back... and crash.

My only fix was to remove all the deps and ejabberd and `make install` .77.

I'm retesting again for .88, go back to .77 fail as above. But now, I do something else, just remove the updated libs that .88 installed, and **now .77 works fine**.

So the question is: given that /libs has multiple versions of `dependency-X.Y.Z` ejabberd will be locked to those that it has been compiled (rebar) or (as I see it now) will just use the most recent version available (maybe incompatible)?

**Comment by prefiks** [comment]
I think it will always look for latest versions of libs, i don't think there is a way to limit versions that erlang will search for at runtime.

**Comment by licaon-kter** [comment]
Thanks
