### ISSUE TITLE
Check support for Erlang/OTP 23.2

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3450]
OTP 23.2 has just been released and its announcement https://www.erlang.org/news/143 says:

> Potential incompatibility
> stdlib
> 
> Improved the API and documentation of the uri_string module. Added a new chapter to the Users Guide about Uniform Resource Identifiers and their handling with the new API. Added two new API functions: uri_string:allowed_characters/0 and uri_string:percent_decode/1.
> 
> This change has been marked as potentially incompatible as uri_string:normalize/2 used to decode percent-encoded character triplets that corresponded to characters not in the reserved set. After this change, uri_string:normalize/2 will only decode those percent-encoded triplets that correspond to characters in the unreserved set (ALPHA / DIGIT / "-" / "." / "_" / "~").

ejabberd and its dependencies should be checked. At least test/webadmin_tests.erl contains a call to uri_string:normalize/1

**Comment by prefiks** [comment]
Yes that is result of my bug report, i think current code is ok (as it was resolved by just updating documentation, actual implementation was not changed), but probably worth checking - tests should catch if behaviour changed.

**Comment by badlop** [comment]
Common Test and manual test are perfect :)
