### ISSUE TITLE
Muc Admin crashed when we join 20k user in single muc

### ISSUE THREAD

**Issue by vavadiyahiren** [processone/ejabberd#3451]
## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from:  official deb/rpm 

```yaml
loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

...
```

## Errors from error.log/crash.log

2020-12-18 04:01:39.319 [warning] <0.87.0>@ejabberd_system_monitor:handle_event:94 Process <0.588.0> consumes more than 5% of OS memory (msgs = 9618520, memory = 4084255564, initial_call = mod_muc_room:init/1, current_function = jid:remove_resource/1, ancestors = ['mod_muc_room_sup_livechat.dhurina.in','mod_muc_sup_livechat.dhurina.in',ejabberd_gen_mod_sup,ejabberd_sup,<0.107.0>], application = ejabberd)
2020-12-18 04:01:39.338 [warning] <0.87.0>@ejabberd_system_monitor:handle_overload:138 The system is overloaded with 9619336 messages queued by 2 process(es) (0%) from the following applications: ejabberd (9619336 msgs); the top processes are:
** <0.588.0>: msgs = 9619335, memory = 4084327300, initial_call = mod_muc_room:init/1, current_function = erlang:setelement/3, ancestors = ['mod_muc_room_sup_livechat.dhurina.in','mod_muc_sup_livechat.dhurina.in',ejabberd_gen_mod_sup,ejabberd_sup,<0.107.0>], application = ejabberd
** <0.4100.0>: msgs = 1, memory = 13329592, initial_call = ejabberd_http:init/3, current_function = prim_inet:recv0/3, ancestors = [ejabberd_http_sup,ejabberd_sup,<0.107.0>], application = ejabberd
2020-12-18 04:01:39.338 [error] <0.87.0>@ejabberd_system_monitor:do_kill:290 Killed 1 process(es) consuming more than 4809668 message(s) each
2020-12-18 04:01:39.338 [error] <0.539.0> Supervisor 'mod_muc_room_sup_livechat.dhurina.in' had child undefined started with {mod_muc_room,start_link,undefined} at <0.588.0> exit with reason killed in context child_terminated

additional crashes

2020-12-18 04:08:10.684 [error] <0.12024.0>@ejabberd_hooks:safe_apply:240 Hook webadmin_page_main crashed when running mod_muc_admin:web_page_main/2:
** exception error: no match of right hand side value {error,notfound}
   in function  mod_muc_admin:get_room_config/1 (src/mod_muc_admin.erl, line 814)
   in call from mod_muc_admin:build_info_room/1 (src/mod_muc_admin.erl, line 558)
   in call from mod_muc_admin:'-build_info_rooms/1-lc$^0/1-0-'/1 (src/mod_muc_admin.erl, line 555)
   in call from mod_muc_admin:'-build_info_rooms/1-lc$^0/1-0-'/1 (src/mod_muc_admin.erl, line 555)
   in call from mod_muc_admin:make_rooms_page/3 (src/mod_muc_admin.erl, line 507)
   in call from mod_muc_admin:web_page_main/2 (src/mod_muc_admin.erl, line 474)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 236)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl, line 217)
** Arg 1 = []
** Arg 2 = {request,'GET',[<<"muc">>,<<"rooms">>],<<"/admin/muc/rooms/">>,[{nokey,<<>>}],{<<"admin">>,<<"livechat.dhurina.in">>},{<<"admin">>,<<"admin">>},<<"en-US">>,<<>>,{{0,0,0,0,0,65535,12580,17721},44040},<<"livechat.dhurina.in">>,5443,[{tls,true},{request_handlers,[{[<<"admin">>],ejabberd_web_admin},{[<<"api">>],mod_http_api},{[<<"bosh">>],mod_bosh},{[<<"captcha">>],ejabberd_captcha},{[<<"upload">>],mod_http_upload},{[<<"ws">>],ejabberd_http_ws},{[<<"oauth">>],ejabberd_oauth}]}],https,[{'Accept-Language',<<"en-US,en;q=0.9">>},{'Accept-Encoding',<<"gzip, deflate, br">>},{'Referer',<<"https://livechat.dhurina.in:5443/admin/muc/">>},{<<"Sec-Fetch-Dest">>,<<"document">>},{<<"Sec-Fetch-User">>,<<"?1">>},{<<"Sec-Fetch-Mode">>,<<"navigate">>},{<<"Sec-Fetch-Site">>,<<"same-origin">>},{'Accept',<<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>},{'User-Agent',<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36">>},{<<"Upgrade-Insecure-Requests">>,<<"1">>},{'Authorization',<<"Basic YWRtaW46YWRtaW4=">>},{'Connection',<<"keep-alive">>},{'Host',<<"livechat.dhurina.in:5443">>}],0,fast_tls,{tlssock,#Port<0.11208>,#Ref<0.1943776201.164233218.201075>}}

## Bug description

I created 4 server to test the load and run all the scripts in one go and after few user joined it got crashed i can' send/receive message and muc_admin panel show some crash and show not found as i attached in screen shot.

![image](https://user-images.githubusercontent.com/5488223/102602124-1a05c000-4147-11eb-9f57-faef2900c76f.png)

**Comment by licaon-kter** [comment]
How do you load test?

gist of the config?

**Comment by vavadiyahiren** [comment]
I am using tsung for testing

**Comment by Neustradamus** [comment]
@vavadiyahiren: Please change the title of this ticket, there is a bad name ;)

**Comment by vavadiyahiren** [comment]
@licaon-kter  any suggestions ?

**Comment by licaon-kter** [comment]
So the whole issue is that the web page can't handle so many users?

Servers works fine?

**Comment by vavadiyahiren** [comment]
Server doen't work fine at all there are so much delay while joining the room like the joining message i am getting after almost 30 sec

**Comment by licaon-kter** [comment]
Server hardware and server load?

**Comment by vavadiyahiren** [comment]
We are using m4.4x large instance of the aws and server load is like 175%

**Comment by badlop** [comment]
> @licaon-kter any suggestions ?

Use the proper tool for the proper task.

[XEP-0045: Multi-User Chat](https://xmpp.org/extensions/xep-0045.html)  says:

> This specification defines an XMPP protocol extension for multi-user text chat, whereby multiple XMPP users can exchange messages in the context of a room or channel, similar to Internet Relay Chat (IRC)

For your testing, you joined 20.000 accounts in a room... I imagine in production you don't plan to put 20.000 human beings chatting in the same room, right? That would be total madness. And their individual presence (join/leave/i'm away/...) is not important information for the other 19.999 human beings in that room.

Most probably, you plan to have a person run a conference or interview with a few persons, and the other 19.999 people will just listen the conversation. Or maybe you plan to have 20.000 bots sharing information. Or many other possibilities that involve millions of entities sharing messages, but do not require sharing presence.

For those cases maybe XEP-0045 is not the proper tool. Two alternatives you may want to check:

* [MUC/Sub](https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/): Instead of joining the room, subscribe to it: the client receives the room messages, and can send messages to the room, but no presence broadcast is involved.  

* [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html) which starts saying:
> This specification defines an XMPP protocol extension for generic publish-subscribe functionality. The protocol enables XMPP entities to create nodes (topics) at a pubsub service and publish information at those nodes; an event notification (with or without payload) is then broadcasted to all entities that have subscribed to the node.

**Comment by vavadiyahiren** [comment]
> * ning the room, subscribe to it: the client receives the room messages,

@badlop  thanks for your suggestions.

Anyway we are now migrated to the MUC/SUB but the use cases is like we need to handle 1000's of users to the same group and they will be chatting with them so in that case can MUC/SUB handle more then 20k users under the same group ?

If No what should the good limit for MUC to support it seamlessly without any problem. What is best solution to support 100k user in the same group?

**Comment by badlop** [comment]
If you finally made load testing and can comment what limits you found, please comment here, so we can all learn from your experiments.

**Comment by huohuoyan** [comment]
I have a question that  3k users join in same muc room, chatting with them(use tsung), when I set ejabberd cluster , I found the CPU load of clustering higher than single node ,There is large amount package between two nodes(use wireshark), any suggestions can help?. Is it use Muc/Sub to improve performance? How to use Muc/Sub by gloox, I cannot find way to use, Best regards
