### ISSUE TITLE
Dialyzer complains in mod_muc_admin: The variable Pid can never match

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3453]
Since recent improvements in mod_muc_admin, Dialyzer complains like this:

```erlang
mod_muc_admin.erl:713: Function destroy_room/2 has no local return
mod_muc_admin.erl:725: The variable Pid can never match since previous clauses completely covered the type 
          'invalid_service' | 'room_not_found'
```

The good news: this is a false alarm, and manual testing shows that the code works correctly.

The bad news: I couldn't find what exactly is the problem Dialyzer has with the code, or how to solve it.

PD: The error is repeated many times, but all due to the same unknown reason:
<details>
<pre>
mod_muc_admin.erl:713: Function destroy_room/2 has no local return
mod_muc_admin.erl:725: The variable Pid can never match since previous clauses completely covered the type 
          'invalid_service' | 'room_not_found'

mod_muc_admin.erl:731: Function destroy_room/1 has no local return
mod_muc_admin.erl:961: Guard test is_pid
         (Pid2 :: 'invalid_service' | 'room_not_found') can never succeed
mod_muc_admin.erl:975: Function get_room_occupants/2 has no local return
mod_muc_admin.erl:977: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed
mod_muc_admin.erl:981: Function get_room_occupants/1 will never be called
mod_muc_admin.erl:991: Function get_room_occupants_number/2 has no local return
mod_muc_admin.erl:993: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed
mod_muc_admin.erl:1005: Function send_direct_invitation/5 has no local return
mod_muc_admin.erl:1017: Function get_users_to_invite/2 has no local return
mod_muc_admin.erl:1051: Function send_direct_invitation/3 will never be called
mod_muc_admin.erl:1066: Function change_room_option/4 has no local return
mod_muc_admin.erl:1072: The variable Pid can never match since previous clauses completely covered the type 
          'invalid_service' | 'room_not_found'
mod_muc_admin.erl:1077: Function change_room_option/3 will never be called

mod_muc_admin.erl:1131: Function change_option/3 will never be called
mod_muc_admin.erl:1168: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1192: Function get_room_affiliations/2 has no local return
mod_muc_admin.erl:1194: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1216: Function get_room_affiliation/3 has no local return
mod_muc_admin.erl:1218: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1239: Function set_room_affiliation/4 has no local return
mod_muc_admin.erl:1242: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1262: Function subscribe_room/4 has no local return
mod_muc_admin.erl:1272: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1292: Function unsubscribe_room/2 has no local return
mod_muc_admin.erl:1298: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed

mod_muc_admin.erl:1317: Function get_subscribers/2 has no local return
mod_muc_admin.erl:1319: Guard test is_pid
         (Pid :: 'invalid_service' | 'room_not_found') can never succeed
</pre>
</details>

**Comment by prefiks** [comment]
I commited 9f851008f6d2d694c7781864b4b841667e581400 that i think will fix this.

**Comment by badlop** [comment]
That is obviously right! I was digging in mod_muc.erl, when the problem was right there. Dialyzer is now happy
