### ISSUE TITLE
Invalid timezone from mod_time

### ISSUE THREAD

**Issue by SamWhited** [processone/ejabberd#3454]
## Environment

- ejabberd version: 20.07
- Erlang version: `erl +V`: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1.3
- OS: Linux (Arch 5.9.14-arch1-1)
- Installed from: distro package

## Errors from error.log/crash.log

No errors

## Bug description

When sending a request for entity time:

```xml
<iq type="get" to="localhost" id="52b23deb3f96ad56"><time xmlns="urn:xmpp:time"></time></iq>
```

the response has an invalid timezone:

```xml
<iq xml:lang='en' to='me@localhost/18038167615807192258201' from='localhost' type='result' id='52b23deb3f96ad56'><time xmlns='urn:xmpp:time'><tzo>05:00</tzo><utc>2020-12-18T18:18:36.602507Z</utc></time></iq>
```
because we do not know which direction the offset is (+ or - 5?)

**Comment by prefiks** [comment]
This should be fixed by bd08f408cab577ec9d0c7791f20da44852b68f01 (and corresponding xmpp commit https://github.com/processone/xmpp/commit/c9aae1631abf4b1b569bda860d395c0be025edbd)
