### ISSUE TITLE
Add support for XEP-0045 7.10 "Registering with a room"

### ISSUE THREAD

**Issue by mdosch** [processone/ejabberd#3455]
Ejabberd supports registering a nick for the whole MUC service but according to [XEP-0045 7.10](https://xmpp.org/extensions/xep-0045.html#register) nicks are registered for specific MUCs (see also the comment from @weiss in https://github.com/profanity-im/profanity/issues/1210 ).

Ejabberd should change it's behavior to comply with XEP-0045 7.10

**Comment by Neustradamus** [comment]
Interesting :)

**Comment by marzoukali** [comment]
Nice to have

**Comment by Neustradamus** [comment]
@badlop: Thanks :)
