### ISSUE TITLE
User remains online

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#347]
I have enabled SM and i have C2S settings
    resend_on_timeout: true
    resume_timeout: 5
    stream_management: true
    timeout: 5000

When I disconnect the client from network by stopping Wifi the user is online even after 5sec ifact even after 15 mins becuase of this the presence to other roster items is always available.

I tried keeping Ping but i have many users so sending ping to all of them and every 5sec or less is very bad idea

How to effectively make user offline ASAP ?

**Comment by s251251251** [comment]
Hello weiss
can u describe how plain xmpp related to stream managment?

**Comment by weiss** [comment]
> can u describe how plain xmpp related to stream managment?

[Stream Management][1] is an [optional extension][2] which is only used if both the client and the server implement and enable it.

[1]: http://xmpp.org/extensions/xep-0198.html
[2]: http://xmpp.org/xmpp-protocols/xmpp-extensions/

**Comment by weiss** [comment]
@nOmi7, I'll close this issue for now.  If you have any further questions, feel free to add a comment.
