### ISSUE TITLE
Crash in mnesia on startup

### ISSUE THREAD

**Issue by SamWhited** [processone/ejabberd#3470]
## Environment

- ejabberd version: 20.12
- Erlang version: `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.5.14`
- OS: FreeBSD
- Installed from: package

## Errors from error.log/crash.log

```
    integration.go:410: 12:10:39.276 [error] gen_server ejabberd_sm_mnesia terminated with reason: bad argument in call to ets:select(session, [{{session,{'_','$1'},'_','_','_','_'},[{'==',{node,'$1'},{const,ejabberd@localhost}}],['$_']}]) in ejabberd_sm_mnesia:handle_info/2 line 116

    integration.go:410: 12:10:39.285 [error] CRASH REPORT Process ejabberd_sm_mnesia with 0 neighbours crashed with reason: bad argument in call to ets:select(session, [{{session,{'_','$1'},'_','_','_','_'},[{'==',{node,'$1'},{const,ejabberd@localhost}}],['$_']}]) in ejabberd_sm_mnesia:handle_info/2 line 116

    integration.go:410: 12:10:39.285 [error] Supervisor ejabberd_backend_sup had child ejabberd_sm_mnesia started with ejabberd_sm_mnesia:start_link() at <0.353.0> exit with reason bad argument in call to ets:select(session, [{{session,{'_','$1'},'_','_','_','_'},[{'==',{node,'$1'},{const,ejabberd@localhost}}],['$_']}]) in ejabberd_sm_mnesia:handle_info/2 line 116 in context child_terminated

    integration.go:410: 12:10:39.286 [error] CRASH REPORT Process <0.564.0> with 0 neighbours exited with reason: {aborted,{node_not_running,ejabberd@localhost}} in mnesia:abort/1 line 353

… similar lines repeated many more times …
```

## Bug description

Starting ejabberd on FreeBSD recently crashed with this error. Restarting with the same configuration I couldn't reproduce the problem, however I figured I'd better report it either way. If I can reproduce it I will try to provide more info.

**Comment by prefiks** [comment]
Hello,

Could you check first error/crash in your log? Do it have different message/stacktrace? That function probably crashes because mnesia/ets tables session was destroyed/not created, maybe this will point what caused that in first place?

**Comment by SamWhited** [comment]
Sorry, the build VM had already shut down before I saw this so this is the only log I have. If it happens again I'll be sure to pull the full log.

**Comment by maste9** [comment]
As I receive the same error after updating on Debian buster-backports on an armhf machine.
crash.log:
```
message_queue_len: 1
    messages: [{'EXIT',<0.230.0>,normal}]
    links: [<0.228.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 210
  neighbours:
```
error.log:
```
2021-01-09 01:30:15.624 [error] <0.232.0> Mnesia(ejabberd@localhost): ** ERROR ** mnesia_event got unexpected event: {'EXIT',<0.236.0>,killed}
2021-01-09 01:30:15.624 [error] <0.232.0> CRASH REPORT Process mnesia_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 354
2021-01-09 01:30:15.626 [critical] <0.219.0>@ejabberd:exit_or_halt:145 Failed to start Erlang application 'mnesia': {killed,{mnesia_app,start,[normal,[]]}}. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
2021-01-09 01:30:15.626 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: {killed,{mnesia_app,start,[normal,[]]}} in application_master:init/4 line 138
2021-01-09 01:31:36.730 [error] <0.232.0> Mnesia(ejabberd@localhost): ** ERROR ** (core dumped to file: "/var/lib/ejabberd/MnesiaCore.ejabberd@localhost_1610_152296_722534")
 ** FATAL ** {error,{"Cannot open dets table",last_activity,[{file,"/var/lib/ejabberd/last_activity.DAT"},{keypos,2},{repair,true},{type,set}],{not_a_dets_file,"/var/lib/ejabberd/last_activity.DAT"}}}
2021-01-09 01:31:46.724 [error] <0.232.0> Mnesia(ejabberd@localhost): ** ERROR ** mnesia_event got unexpected event: {'EXIT',<0.236.0>,killed}
```
Before update server worked well, after it I cannot start ejabberd anymore.

**Comment by licaon-kter** [comment]
Can you check the perms for /var/lib/ejabberd folders and files?

**Comment by prefiks** [comment]
Hello,
Looks like /var/lib/ejabberd/last_activity.DAT is corrupted in your instalation, error that you are getting happens when that file header is invalid.

**Comment by SamWhited** [comment]
I have had a handful of issues with Go programs on these same VMs where things that should be impossible happen. I had thought it might be memory corruption, but then it happened on another build machine on the same service. Maybe whatever is happening with their machines also randomly corrupted something in that file, because I haven't seen any similar problems since reporting this. That's just a wild guess though given the other weird behavior I saw.

**Comment by maste9** [comment]
> Can you check the perms for /var/lib/ejabberd folders and files?
> 
> Or maybe move that last_activity file and restart?

Sorry I didn't answer before. I also tried removing and restoring that file from backup, but it didn't help. 

I have meanwhile resetup my backuped database on a docker-based instance which works flawlessly now. So I can unfortunately help any further. Thanks for your support!

**Comment by mremond** [comment]
If I understand well the issue is solved and the problem is not reproducible at the moment.
Let's reopen it if there is something new pointing to a fix needed in ejabberd.
