### ISSUE TITLE
The module is not compiled with debug_info

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3472]
## Environment

- ejabberd version: 20.12.16
- Erlang version: 10.6.4
- OS: Linux (Ubuntu)
- Installed from: source 

No errors

## Bug description

When I compile a custom module by using command `ejbberdctl module_install mod_hello` the module is not compiled with `debug_info` option so I can't debug it with `ejabberdctl debug`.

**Comment by relbraun** [comment]
@badlop did I miss something?

**Comment by prefiks** [comment]
No, compiler is not called with debug_info flags, so output .beam files that are generated are not produced with them. This will require adding correct flags to ext_mod.erl compile function.

**Comment by relbraun** [comment]
How do I add this flag to the compile function?

**Comment by prefiks** [comment]
Should be fixed by 9be3d948b2c73bade59fcbf2d9f8e4c9f513b7eb
