### ISSUE TITLE
ejabberd.im Website link updates

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3475]
Can you update the ML links on the ejabberd.im website?
- Header and footer: http://lists.jabber.ru/mailman/listinfo/ejabberd -> https://lists.jabber.ru/mailman/listinfo/ejabberd

On https://docs.ejabberd.im/
- Header: http://stackoverflow.com/questions/tagged/ejabberd?sort=newest -> https://stackoverflow.com/questions/tagged/ejabberd?sort=newest
- Footer: http://docs.ejabberd.im/ -> https://docs.ejabberd.im/

On https://www.process-one.net/en/ejabberd/
- http://strophe.im/ -> https://strophe.im/

Maybe other links too.

**Comment by badlop** [comment]
Ok, I've updated the links in https://docs.ejabberd.im/.

**Comment by mremond** [comment]
Closing as it seems to be solved. Please reopen it, if I am wrong.
