### ISSUE TITLE
Define the source IP/interface for s2s connections

### ISSUE THREAD

**Issue by utopicdev** [processone/ejabberd#348]
<b>UPD:</b> I've made an error choosing a category, this topic should be in Pull Requests.

I am looking for a feature that would provide an option to select which IP or interface to use for all ejabberd's outgoing connections. Talked with Holger Weiss on freenode, he has confirmed that this feature is unimplemented in ejabberd at this moment.

A typical example situations requiring a such feature:
Situation 1)
A server with ejabberd has many public IP addresses (e.g. 17.15.18.3, 17.11.14.3, 17.15.18.56, ....) so we want to define which one to use for ejabberd's outgoing connections; we want it to be 17.15.18.56, while default route is set via 17.15.18.3.

Situation 2)
 We have servers A and B connected to each other via VPN link. ejabberd is installed on server A and we want all ejabberd's packets to go through the server B, in other words, all external connections from ejabberd will go out from the server B. Hence the server A has its own public IP address, we want to obscure it in s2s communications. 
In this example, the typical interface for ejabberd would be "tun" (with a proper routing set up), since it's used for most popular VPN software such as OpenVPN.

There are many software which support this feature, for example netcat (-s) or ping (-I)

**Comment by zinid** [comment]
I don't think selecting source IP helps in the situations you described. I close the ticket.
