### ISSUE TITLE
Delete two obsolete directories: transport examples and old win32 files

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3487]
Wild idea: delete two directories with obsolete content:

* [examples/transport-configs/](https://github.com/processone/ejabberd/tree/master/examples/transport-configs) contains example configuration for transports that no longer work, or are for networks no longer available: AIM, ILE, GG, JIT, MSN, Yahoo.

* [win32/](https://github.com/processone/ejabberd/tree/master/win32) contains the files that were used to build ejabberd installer for windows eight (or more) years ago. Quite probably it doesn't work at all nowadays

**Comment by Neustradamus** [comment]
@badlop: Thanks for this ticket with my removal requests.

**Comment by Neustradamus** [comment]
@badlop: Thanks.
