### ISSUE TITLE
JWT token based login not working with ejabbred 20.07

### ISSUE THREAD

**Issue by vavadiyahiren** [processone/ejabberd#3491]
## Environment

- ejabberd version: 20.07
- OS: Linux (Debian)
- Installed from: official deb

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 5

auth_method: [jwt, internal]
jwt_key: /home/ubuntu/mysecret.jwk

access_rules:
  jwt_only:
    deny: admin
    allow: all 
    ...

jwt_auth_only_rule: jwt_only

...
```

mysecret .jwk 

```

{
    "kty": "oct",
    "use": "sig",
    "k": "XckBSF7uaA5fTR4JK1QkLaguwh9MO70__kd3s8lPTWaVmbOLPE8JBIG1yPs3in9YSJER2QdxjerNaLT_6OhmX2JnB_zeUz1m7EN-ThtbKXUjwauUMoT4PE_fyuqPQMvW-rsAkBjkz0MM_rKm30IxNN3oeXdhEIhMHlVXNumMwzcG7rctUHuFZmxsNKB1CJhTgRSJA7u4Ol0Fm07KA9E4glwK-XdeYza0nMuv3CC8P72i_1eCwBs2UXRyj4VnRrdjZflY0IomZ7iDowdldJwx-WVN51xhtda8dlNMa-p_TJrKjNhBG6f_5afNWzLB9hYJ5-AZcMksZRPgafAvUAOiyw",
    "alg": "HS256"
}

```

Jwt Payload

```
{
  "jid": "test@domain",
  "exp": 1664436511
}

```

my generate token

```
eyJrdHkiOiJvY3QiLCJ1c2UiOiJzaWciLCJrIjoiWGNrQlNGN3VhQTVmVFI0SksxUWtMYWd1d2g5TU83MF9fa2QzczhsUFRXYVZtYk9MUEU4SkJJRzF5UHMzaW45WVNKRVIyUWR4amVyTmFMVF82T2htWDJKbkJfemVVejFtN0VOLVRodGJLWFVqd2F1VU1vVDRQRV9meXVxUFFNdlctcnNBa0Jqa3owTU1fckttMzBJeE5OM29lWGRoRUloTUhsVlhOdW1Nd3pjRzdyY3RVSHVGWm14c05LQjFDSmhUZ1JTSkE3dTRPbDBGbTA3S0E5RTRnbHdLLVhkZVl6YTBuTXV2M0NDOFA3MmlfMWVDd0JzMlVYUnlqNFZuUnJkalpmbFkwSW9tWjdpRG93ZGxkSnd4LVdWTjUxeGh0ZGE4ZGxOTWEtcF9USnJLak5oQkc2Zl81YWZOV3pMQjloWUo1LUFaY01rc1pSUGdhZkF2VUFPaXl3IiwiYWxnIjoiSFMyNTYifQ.eyJqaWQiOiJ0ZXN0QGRvbWFpbiIsImV4cCI6MTY2NDQzNjUxMX0.YG5vT_Nzzm6VMEBsncaRXfyZ7HOP96CgnTEaEkDKojE

```

## Errors from error.log/crash.log

Invalid Username or password while login with jwt token

```
2021-01-18 14:08:21.175 [debug] <0.516.0>@mod_bosh:process:70 Incoming data: <<"<body rid='3880420061' xmlns='http://jabber.org/protocol/httpbind' sid='13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>dGVzdEBjaGF0LmVudGh1emlhc3RpYy5jb20AdGVzdAB7ICAgImppZCI6ICJ0ZXN0QGV4YW1wbGUub3JnIiwgICAiZXhwIjogMTU2NDQzNjUxMSB9</auth></body>">>
2021-01-18 14:08:21.175 [debug] <0.522.0>@ejabberd_bosh:active:384 Got request:
** Request: {body,<<>>,[{sid,<<"13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1">>},{rid,3880420061}],[{xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"dGVzdEBjaGF0LmVudGh1emlhc3RpYy5jb20AdGVzdAB7ICAgImppZCI6ICJ0ZXN0QGV4YW1wbGUub3JnIiwgICAiZXhwIjogMTU2NDQzNjUxMSB9">>}]}}],305}
** From: {<0.516.0>,#Ref<0.1231748554.3898343425.51402>}
** State: {state,<<"domain">>,<<"13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1">>,{{[],[]},0,unlimited},{{[],[]},0,unlimited},{state,1000,1000,1000,1610978901022130},<0.523.0>,<<"1.0">>,#Ref<0.1231748554.3898343425.51388>,#Ref<0.1231748554.3898343425.51387>,60,30,3880420060,<<>>,undefined,unlimited,{1,{3880420060,{body,<<>>,[{sid,<<"13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1">>},{wait,60},{ver,<<"1.11">>},{polling,2},{inactivity,30},{hold,1},{'xmpp:restartlogic',true},{requests,2},{secure,true},{maxpause,120},{'xmlns:xmpp',<<"urn:xmpp:xbosh">>},{'xmlns:stream',<<"http://etherx.jabber.org/streams">>},{from,<<"domain">>}],[{xmlstreamstart,<<"stream:stream">>,[{<<"id">>,<<"12451967324874246561">>},{<<"version">>,<<"1.0">>},{<<"xml:lang">>,<<"en">>},{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},{<<"from">>,<<"domain">>},{<<"xmlns">>,<<"jabber:client">>}]},{xmlstreamelement,{xmlel,<<"stream:features">>,[],[{xmlel,<<"mechanisms">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"PLAIN">>}]},{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"X-OAUTH2">>}]}]},{xmlel,<<"register">>,[{<<"xmlns">>,<<"http://jabber.org/features/iq-register">>}],[]}]}}],0},nil,nil}},{0,nil},{{[],[]},0,1000},{{0,0,0,0,0,65535,12580,18074},50622},2}
2021-01-18 14:08:21.176 [debug] <0.522.0>@ejabberd_shaper:update:75 Shaper update:
#state{maxrate = 1000,burst_size = 1000,acquired_credit = 1000,
       lasttime = 1610978901022130} =>
{#state{maxrate = 1000,burst_size = 1000,acquired_credit = 848,
        lasttime = 1610978901175960},
 0}
2021-01-18 14:08:21.176 [debug] <0.523.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
2021-01-18 14:08:21.176 [debug] <0.523.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_auth_result: ejabberd_c2s:process_auth_result/3
2021-01-18 14:08:21.176 [warning] <0.523.0>@ejabberd_c2s:process_auth_result:276 (http_bind|<0.522.0>) Failed c2s PLAIN authentication for test@domain from ::ffff:49.36.70.154: Invalid username or password
2021-01-18 14:08:21.176 [debug] <0.523.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_auth_result: mod_fail2ban:c2s_auth_result/3
2021-01-18 14:08:21.176 [info] <0.523.0> (http_bind|<0.522.0>) Send XML on stream = <<"<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text xml:lang='en'>Invalid username or password</text></failure>">>
2021-01-18 14:08:21.177 [debug] <0.522.0>@ejabberd_bosh:do_reply:679 Send reply:
** RequestID: 3880420061
** Reply: {body,<<>>,[],[{xmlstreamelement,{xmlel,<<"failure">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{xmlel,<<"not-authorized">>,[],[]},{xmlel,<<"text">>,[{<<"xml:lang">>,<<"en">>}],[{xmlcdata,<<"Invalid username or password">>}]}]}}],0}
** To: {<0.516.0>,#Ref<0.1231748554.3898343425.51402>}
** State: {state,<<"domain">>,<<"13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1">>,{{[],[]},0,unlimited},{{[],[]},0,unlimited},{state,1000,1000,848,1610978901175960},<0.523.0>,<<"1.0">>,#Ref<0.1231748554.3898343425.51415>,#Ref<0.1231748554.3898343425.51406>,60,30,3880420061,<<>>,undefined,unlimited,{1,{3880420060,{body,<<>>,[{sid,<<"13e704a7ead1a2aef1c426b068d3ab1e9c05a8f1">>},{wait,60},{ver,<<"1.11">>},{polling,2},{inactivity,30},{hold,1},{'xmpp:restartlogic',true},{requests,2},{secure,true},{maxpause,120},{'xmlns:xmpp',<<"urn:xmpp:xbosh">>},{'xmlns:stream',<<"http://etherx.jabber.org/streams">>},{from,<<"domain">>}],[{xmlstreamstart,<<"stream:stream">>,[{<<"id">>,<<"12451967324874246561">>},{<<"version">>,<<"1.0">>},{<<"xml:lang">>,<<"en">>},{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},{<<"from">>,<<"domain">>},{<<"xmlns">>,<<"jabber:client">>}]},{xmlstreamelement,{xmlel,<<"stream:features">>,[],[{xmlel,<<"mechanisms">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"PLAIN">>}]},{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"X-OAUTH2">>}]}]},{xmlel,<<"register">>,[{<<"xmlns">>,<<"http://jabber.org/features/iq-register">>}],[]}]}}],0},nil,nil}},{1,{3880420061,{{<0.516.0>,#Ref<0.1231748554.3898343425.51402>},{body,<<>>,[],[],0}},nil,nil}},{{[],[]},0,1000},{{0,0,0,0,0,65535,12580,18074},50622},2}


```

![image](https://user-images.githubusercontent.com/5488223/104949640-4c743880-59e5-11eb-8abb-fd36091b9182.png)

## Bug description

- I have followed  blog from  https://www.process-one.net/blog/ejabberd-19-08/ and enabled the jwt token with ejabberd server 20.07.
- I tried to create a new jwt token from https://jwt.io/ this web as attached in screen shot but when i passed the  generated jwt token as a password it is giving me invalid username/password all the time.

**Comment by newpreneur** [comment]
Even I'm facing the same issue, Let me know if you have resolved it! Thanks.

**Comment by prefiks** [comment]
Hello,

It seems that you aren't sending correct "password'", after decoding what was sent inside `<auth/>` element we are getting, `"JID\0{   "jid": "test@example.org",   "exp": 1564436511 }"`, and this is just to short - it contains only header from jwt. You need to send everything that jwt.io outputs in encoded field.

I just checked that with latest version of ejabberd and it is working correctly here - tokens generated on jwt.io allow me to login to server.

**Comment by newpreneur** [comment]
loglevel: 5

I'm passing JID is the Username field and JWT Token in the password field. I copied everything from **encoded value** from jwt.io. Can you please look at it? 

`2021-01-20 13:50:06.798 [info] <0.511.0> (tls|<0.511.0>) Received XML on stream = <<"<auth mechanism=\"PLAIN\" xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\">AGhlbGxvAGV5SnJkSGtpT2lKdlkzUWlMQ0oxYzJVaU9pSnphV2NpTENKcmFXUWlPaUpVVjNKTFkzZFdWRmxuTUUxV09FVm5lVmw2YWpkTmNsVlhSRXBGYWw5RWNsZDBRak40V21wbGJESk5JaXdpYXlJNkltRjVaRGcyT0ZCS1l6WnBZV3RXU21GaGVXSnNVVzUxUzJJMmFWVTJPVTVoTUdkRlpUTklOVWhwYUhaeVNXTm9VVVp3T0RCTVkxWm5VbkZuV25CNFdUVldjV0pzWlRKeGQzRTFWa0o2YUhkS2FsbHdkSE00TTBGbmMwWjBNRE4zVHpWTE5VRmxaRkpIUmpSeU1USmxTazFLYjJadGNHMW1RbGxqU25CWmRUTkNTMjUxWWtkVkxUWldNa0UxV0Rkb2FVTXpZV2Q1WDFGRFIyeDFSbWhIVDBzeVpXazRVWGx0VmpWNlZHcDNNVTA1TjJkaWFXOUNjMlZ4WTJ4SU5rTmlVMVJRTXpGMlIwNHllVFZmUnpka2JXdFpUWFEyUlhsRE5GVnhPVGxGV2xBek5FTjFiRkJSWkRGalNERTVVMlpWZHpWeE1GSTNlWGRDV1hkek9XZFhiSHBpZUdoc2JIQjNWRGxRUTFCT2NFRjFlSHBUU1c5V1YzQnZjSGhxZFhSRk5XeHRWemhXY1RsQ1pFbHBkRjlUTjNGb1REUmtla2swT1hkNmEyUXlURE5KWDJ4c01ISnROMXA2ZVhKWmJHUXlUazV4VTI5WlFTSXNJbUZzWnlJNklraFRNalUySW4wLmV5SnFhV1FpT2lKMFpYTjBRR1ZqTWkwMU5DMHhORFl0TVRjMUxUSXpOUzVqYjIxd2RYUmxMVEV1WVcxaGVtOXVZWGR6TG1OdmJTSXNJbVY0Y0NJNk1UWTBNRGs1TlRJd01IMC55R1U3MmJubWFCNUhHRHlCX1puWGJ3Nkh2WHpYQmgxM1BUY1hWSHVJYTMw</auth>">>
2021-01-20 13:50:06.798 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_auth_result: mod_fail2ban:c2s_auth_result/3
2021-01-20 13:50:06.798 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push:c2s_stanza/3
2021-01-20 13:50:06.798 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push_keepalive:c2s_stanza/3
2021-01-20 13:50:06.798 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_stream_mgmt:c2s_handle_send/3
2021-01-20 13:50:06.798 [info] <0.511.0> (tls|<0.511.0>) Send XML on stream = <<"<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text xml:lang='en'>Invalid username or password</text></failure>">>
2021-01-20 13:50:07.123 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_closed: mod_stream_mgmt:c2s_closed/2
2021-01-20 13:50:07.123 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_closed: ejabberd_c2s:process_closed/2
2021-01-20 13:50:07.123 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_terminated: mod_stream_mgmt:c2s_terminated/2
2021-01-20 13:50:07.123 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_terminated: mod_pubsub:on_user_offline/2
2021-01-20 13:50:07.123 [debug] <0.511.0>@ejabberd_hooks:safe_apply:231 Running hook c2s_terminated: ejabberd_c2s:process_terminated/2
2021-01-20 13:50:07.124 [info] <0.511.0> (tls|<0.511.0>) Send XML on stream = <<"</stream:stream>">>`

**Comment by vavadiyahiren** [comment]
> ked that with latest version of ejabberd and it is w

Please refer my attached screen shot from jwt.io and can you point the possible area where i made a mistakes ?

**Comment by prefiks** [comment]
Please use
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```
as header in that generator

you also need to fill sha256 in verify signature with your key - you can find it as "k" in mysecret.jwk (and check "secret is base64 encoded")

**Comment by vavadiyahiren** [comment]
> Please use
> 
> ```
> {
>   "alg": "HS256",
>   "typ": "JWT"
> }
> ```
> 
> as header in that generator
> 
> you also need to fill sha256 in verify signature with your key - you can find it as "k" in mysecret.jwk (and check "secret is base64 encoded")

If you don't mind can you give me personal contact or email ?

**Comment by prefiks** [comment]
Please use this ticket, it can be helpful for others as well.

**Comment by nosnilmot** [comment]
> Please use this ticket, it can be helpful for others as well.

and others can help :)

Part of the problem is that the username JID provided does not match that in the JWT

In https://github.com/processone/ejabberd/issues/3491#issuecomment-763622548, Username JID is "hello" but the JID in the JWT is "test@ec2-54-146-175-235.compute-1.amazonaws.com" - they must match.

In https://github.com/processone/ejabberd/issues/3491#issuecomment-763636306, Username JID is "test@chat.enthuziastic.com\0test" (actually not sure if this will parse correctly at all, it looks like there are 3 \0 separated fields in &lt;auth/&gt; here) but the JID in the JWT is "test@chat.enthuziastic.com"

**Comment by vavadiyahiren** [comment]
> Please use
> 
> ```
> {
>   "alg": "HS256",
>   "typ": "JWT"
> }
> ```
> 
> as header in that generator
> 
> you also need to fill sha256 in verify signature with your key - you can find it as "k" in mysecret.jwk (and check "secret is base64 encoded")

Bingo it worked thanks for a help :)

**Comment by newpreneur** [comment]
> > Please use this ticket, it can be helpful for others as well.
> 
> and others can help :)
> 
> Part of the problem is that the username JID provided does not match that in the JWT
> 
> In [#3491 (comment)](https://github.com/processone/ejabberd/issues/3491#issuecomment-763622548), Username JID is "hello" but the JID in the JWT is "[test@ec2-54-146-175-235.compute-1.amazonaws.com](mailto:test@ec2-54-146-175-235.compute-1.amazonaws.com)" - they must match.
> 
> In [#3491 (comment)](https://github.com/processone/ejabberd/issues/3491#issuecomment-763636306), Username JID is "[test@chat.enthuziastic.com](mailto:test@chat.enthuziastic.com)\0test" (actually not sure if this will parse correctly at all, it looks like there are 3 \0 separated fields in <auth/> here) but the JID in the JWT is "[test@chat.enthuziastic.com](mailto:test@chat.enthuziastic.com)"

Kill me for such mistakes! Thank you so much.

**Comment by dilshans2k** [comment]
Hi everyone
I am facing the same problem but i am getting a different error output `Oauth Token is invalid or expired`.
I am using NestJS for my app backend.
```
const res = await firstValueFrom(
        this.httpService.post('http://127.0.0.1:5281/api/register', data, {
          headers: {
            'Content-Type': 'application/json',
            Authorization: 'Bearer ' + authToken,
          },
          method: 'POST',
        }),
      );
```

- For getting authToken, i first generated 
secret.jwk
```
{
    "kty": "oct",
    "use": "sig",
    "kid": "sig-1650868997",
    "k": "IFLkew8nH2jO2ZsLjmCJ8cNX_eypToHHzejBcxdLPeOxMk0m_EwvAl0QhlGCBHrin9bmi6d3Nfv1umRzjNfZ7W1xQKR1PMaUhsP6dH-Bte723IDj3dDPH3glDo-4bFRai0KIyGAqNohr7yEEIBWm_38FhdKl1Mo2C3qetAqbGL2Ln2Sfx7UhJg6RREdS3OAq_lV6w4QLYDuOk6rvpUYo7K1KXbTL92DyMslfwbFBsc5h3D41lG4eO6Ix-IhVM2G-o1RoOfQYmNI1f5J67hltjQm4iMdxL2ZUM5E1TUdgqWAORx9aAo85jXfe4Gulze5dJaLi8SrzgOl94-KR-tej5Q",
    "alg": "HS256"
}
```
- Then in jwt.io, i generated it like this
![image](https://user-images.githubusercontent.com/67574348/165216565-8f4fca71-e37d-4749-bff8-5261b63667f7.png)

- Since i am just testing right now, passed the authToken to postman and made a request to nestjs, where it will pass it in the first code snippet in this post.

- And i am getting this status code 401 error, saying `Oauth Token is invalid or expired.`

- For my ejabberd.yml configuration, i have added the following lines
```
----
auth_method: jwt
jwt_key: <path-to-secret.jwk>
jwt_auth_only_rule: jwt_only
----
access_rules:
  jwt_only:
    deny: admin
    allow: all
    ----
```

**Comment by badlop** [comment]
I've just tried JWT auth manually. I followed (and updated) the instructions provided in https://www.process-one.net/blog/ejabberd-19-08/ and works for me using ejabberd 22.05, following those instructions to the letter. Make sure to use a high enough "exp" value when testing.
