### ISSUE TITLE
Documentation for module development is missing important info about enabling logging

### ISSUE THREAD

**Issue by royrwood** [processone/ejabberd#3493]
## Environment

- ejabberd version: 20.12
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: distro package

## Errors from error.log/crash.log

No errors

## Bug description

The [(documentation for writing a custom module)](https://docs.ejabberd.im/developer/extending-ejabberd/modules/#mod-hello-world) is very helpful, but the sample logging calls the module make don't always result in output as expected.

If you are building ejabberd from source and place your module code in the ejabberd source tree, compile it, and install it via "make install", all the correct compilation flags are set and things work.  If you are doing something a little different, the flags may not be set, and logging calls don't generate any log output.

For example, I had ejabberd installed via the installer, and was compiling my test module code by hand and dropping it into the appropriate ejabberd directory something like this:

```
erlc -I ./ejabberd-20.12/include/  mod_hello_world.erl 
cp mod_hello_world.beam ~/ejabberd/lib/ejabberd-20.12/ebin/
~/ejabberd/bin/ejabberdctl start
tail -F -n +0 ~/ejabberd/logs/ejabberd.log
```
My module was loaded (remember to add the config to ~/ejabberd/conf/ejabberd.yml), but the logging output I expected to see was never shown in the log.

Similarly, no logging output was produced if I followed the instructions from the documentation and used `ejabberdctl module_install mod_cron` to source the module from my `~/.ejabberd-modules/sources` directory.

To get the logging output to appear as expected, I had to add the `-D LAGER` option when I compiled the module:

```
erlc -D LAGER +'{parse_transform, lager_transform}' -I ./ejabberd-20.12/include/  mod_hello_world.erl
```

I'm not sure if it was absolutely necessary to include the `+'{parse_transform, lager_transform}'`, though the lager docs suggested it.

So, it would be helpful to ejabberd newbies if the module development documentation included some information about getting logging to work.  For someone new, they'll be relying heavily on logging to help out as they develop a module.

Add `-D LAGER` worked for me, but I'm not sure if that's the best solution.  At the moment, it's really easy to tweak my code, recompile, copy to the installed ejabberd ebin directory, and restart ejabberd.  If there's a better approach, I'd love to hear that, and would suggest any such best practices be added to the module developer docs page, too.

**Comment by licaon-kter** [comment]
Did you read https://github.com/processone/ejabberd/issues/3472 yet?

**Comment by royrwood** [comment]
Thanks-- I didn't see that one.  #3472 seems to mostly be about debugging the code using `ejabberdctl debug`-- will the addition of the `debug_info` flag also mean that the definitions of `INFO_MSG` will result in actual logging output?  In the `logger.hrl` file, I see there is a check whether `LAGER` is defined like this...

```
-ifdef(LAGER).
-compile([{parse_transform, lager_transform}]).

-define(DEBUG(Format, Args),
        begin lager:debug(Format, Args), ok end).

-define(INFO_MSG(Format, Args),
        begin lager:info(Format, Args), ok end).
```

**Comment by badlop** [comment]
Ok, I took a look at ejabberd sources, and this is what I found:

ejabberd uses the **Lager** library when compiled with Erlang/OTP older than version 22 (e3962aea6e2b3a50e371a9e93c2cf161672598df). In that case log lines look like:
```
2021-01-19 21:15:54.142
 [info] <0.107.0>@ejabberd_app:start:62
 ejabberd 20.12 is started in the node ejabberd@localhost in 3.80s
```

And ejabberd uses the **Logger** library when compiled with Erlang/OTP 22 or newer, because that is included in OTP (http://erlang.org/doc/apps/kernel/logger_chapter.html). In that case, log lines look like:
```
2021-01-19 21:23:24.809609+01:00
 [info] <0.130.0>@ejabberd_app:start/2:63
 ejabberd 20.12 is started in the node ejabberd@localhost in 3.23s
```

From what I see, it seems the ejabberd 20.12 binary installers include Erlang/OTP 21.3 so... you had to define the LAGER macro manually. I guess it would be preferable if ext_mod detects this case itself. 

With this patch, ejabberd 20.12 binary installer compiled mod_hello_world, and it finally printed log lines correctly:
```diff
diff --git a/src/ext_mod.erl b/src/ext_mod.erl
index 916baf7f0..a6b793059 100644
--- a/src/ext_mod.erl
+++ b/src/ext_mod.erl
@@ -569,8 +569,15 @@ compile_result(Results) ->
         [Error|_] -> Error
     end.
 
+maybe_define_lager_macro() ->
+    case list_to_integer(erlang:system_info(otp_release)) < 22 of
+        true -> [{d, 'LAGER'}];
+        false -> []
+    end.
+
 compile_options() ->
     [verbose, report_errors, report_warnings, debug_info, ?ALL_DEFS]
+    ++ maybe_define_lager_macro()
     ++ [{i, filename:join(app_dir(App), "include")}
         || App <- [fast_xml, xmpp, p1_utils, ejabberd]]
     ++ [{i, filename:join(mod_dir(Mod), "include")}
```

@prefiks when you have some spare time, do you confirm this patch makes sense?
