### ISSUE TITLE
Files cleanup tries to delete files or folders that don't exist

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3497]
## Environment

- ejabberd version: not a new thing, 20.12.56
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.2.4
- OS: Debian Buster, arm64
- Installed from: git

External upload via https://github.com/weiss/ngx_http_upload

No external cleanup script, max_days 30 or 60

Usually seen at ejabberd restarts.

## Errors from error.log/crash.log

```
[info] <0.411.0>@mod_http_upload_quota:del_file_and_dir:376 Removed /path/to/ejabberd/files/hash/hash
[error] <0.454.0>@mod_http_upload_quota:gather_file_info:359 Cannot stat(2) /path/to/ejabberd/files/hash/hash: no such file or directory
```

or

```
[info] <0.411.0>@mod_http_upload_quota:del_file_and_dir:376 Removed /path/to/ejabberd/files/hash/hash/file.ext
[warning] <0.454.0>@mod_http_upload_quota:del_file_and_dir:385 Cannot remove /path/to/ejabberd/files/hash/hash/file.ext: no such file or directory
```

...so basically it deletes the file, as expected, but 0.5sec later tries again and fails.

**Comment by mremond** [comment]
@weiss Mentioning you, as one of your contribution is referred to here.

**Comment by weiss** [comment]
I guess there's two (or more) virtual domains using the same `docroot` (without `@HOST@` in the path), so this ends up with two (or more) `mod_http_upload_quota` processes trying to clean up the same directory tree concurrently.

**Comment by licaon-kter** [comment]
Two domains, yes (only one uses file uploads, secondary one is for Jitsi Meet)
Same `docroot`, yes
`put_url: "https://upload.@HOST@"`
