### ISSUE TITLE
ejabberd.service not updated in .deb

### ISSUE THREAD

**Issue by mtdcr** [processone/ejabberd#3501]
## Environment

- ejabberd version: 20.12
- OS: Linux (Debian)
- Installed from: official deb

## Bug description

`/opt/ejabberd-20.12/bin/ejabberd.service` from `ejabberd_20.12-0_amd64.deb` does not include https://github.com/processone/ejabberd/pull/3429, even though it's mentioned in the changelog.

**Comment by nerijus** [comment]
Same problem with rpm - /opt/ejabberd-20.12/bin/ejabberd.service from ejabberd-20.12-0.x86_64 does not include #3429.

**Comment by nerijus** [comment]
And it would be nice to have ejabberd.service file in /usr/lib/systemd/system/, so we would not need to copy file manually. CentOS 7 and 8 both have systemd, and CentOS 6 is EOL.

**Comment by badlop** [comment]
> /opt/ejabberd-20.12/bin/ejabberd.service from ejabberd_20.12-0_amd64.deb does not include #3429, 

If you are able to test the new ejabberd 21.01 deb and rpm installers, please comment if it's finally solved.

> And it would be nice to have ejabberd.service file in /usr/lib/systemd/system/, so we would not need to copy file manually.

Those binary installers write everything to /opt, so I guess that isn't an option. That's why it is mentioned in the documentation, so the administator decides what to do: https://docs.ejabberd.im/admin/installation/#autostart-on-linux

**Comment by nerijus** [comment]
Having `ejabberd.service` in `/usr/lib/systemd/system` would not autostart service by default (`systemctl enable ejabberd` is needed), so it would not be a problem, but if would be big help for us, because now we need another step - copying the file.

**Comment by nerijus** [comment]
> If you are able to test the new ejabberd 21.01 deb and rpm installers, please comment if it's finally solved.

Not quite yet - `/opt/ejabberd-21.01/bin/ejabberd.service` in rpm has `@@INSTALLDIR@@` instead of `/opt/ejabberd-21.01`.

**Comment by nerijus** [comment]
Another problem - `${msg(ejabberd.desc)}` and `${msg(ejabberd.desc)}` here:
```
$ rpm -qi ejabberd
Name        : ejabberd
Version     : 21.01
Release     : 0
Architecture: x86_64
Install Date: Fri Jan 29 17:21:16 2021
Group       : Applications
Size        : 30533126
License     : Other
Signature   : (none)
Source RPM  : ejabberd-21.01-0.src.rpm
Build Date  : Fri Jan 29 13:16:32 2021
Build Host  : build.process-one.net
Relocations : (not relocatable)
Vendor      : ProcessOne
URL         : https://www.process-one.net/en/ejabberd
Summary     : ${msg(ejabberd.desc)}
Description :
${msg(ejabberd.desc)}
```

**Comment by nerijus** [comment]
> > If you are able to test the new ejabberd 21.01 deb and rpm installers, please comment if it's finally solved.
> 
> Not quite yet - `/opt/ejabberd-21.01/bin/ejabberd.service` in rpm has `@@INSTALLDIR@@` instead of `/opt/ejabberd-21.01`.

Oh, sorry, it is ok - while a file in the rpm has `@@INSTALLDIR@@`, but after installing the rpm package, the actual file `/opt/ejabberd-21.01/bin/ejabberd.service` is OK, with correct paths. It seems rpm postinstall script changes it.
