### ISSUE TITLE
API should return error, when something fails

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#3502]
## Environment
- ejabberd version: 20.12

## Bug description
Ejabberd API should return error response, when something fails. For example, the api call `set_vcard` failed with SQL error. But the result from API call was Http 200, return code 0. Same as if everything was successful. 

## Errors from error.log/crash.log

In this case, there was DB error:
```
ejabberd_1             | 19:54:03.158 [error] SQL query 'Q76516637' at {:mod_vcard_sql, 100} failed: [{:severity, :ERROR}, {86, "ERROR"}, {:code, "22021"}, {:message, "invalid byte sequence for encoding \"UTF8\": 0xf8"}, {:file, "wchar.c"}, {:line, 2017}, {:routine, "report_invalid_encoding"}]
```

and the vcard was not set for that user.

But the result from API call was:
```
HTTP/1.1 200 OK
Content-Length: 1
Access-Control-Allow-Headers: Content-Type, Authorization, X-Admin
Access-Control-Allow-Origin: *
Content-Type: application/json
```

**Comment by badlop** [comment]
I've committed a fix for that command. If you find others API with the same problem, please open a new issue with them.
