### ISSUE TITLE
delete_old_messages: syntax error in SQL statement

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3503]
When using a sqlite database, `ejabberdctl delete_old_messages 32` fails with
```
jabberd_sql:check_error:1236 SQL query 'DELETE FROM spool WHERE created_at < NOW() - INTERVAL 32 DAY'
failed: "near \"32\": syntax error"
```
The reasons seems to be: sqlite does not support INTERVAL. Thus the SQL statement needs to read
`DELETE FROM spool WHERE created_at < datetime('now', '- 32 days');`

Remark: `ejabberdctl delete_old_mam_messages all 32` does not fail.

**Comment by prefiks** [comment]
Should be fixed by commit f7004f793d0d15f7213be14e31f2ae0dc5c0783b
