### ISSUE TITLE
CAPTCHA improvements

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3505]
The patch has been added on ML:
- http://lists.jabber.ru/pipermail/ejabberd/2021-January/009677.html

Thanks in advance.

**Comment by mightyBroccoli** [comment]
This already has been merged as https://github.com/processone/ejabberd/pull/3533.

**Comment by Neustradamus** [comment]
@mightyBroccoli, @weiss: Yes after my issues.
Thanks all.

There is a comment here: https://github.com/processone/ejabberd/commit/b41ce8828c579f06a33ca93a7af4fd5984997e16#r47461104
