### ISSUE TITLE
filter_packet module

### ISSUE THREAD

**Issue by dabslants** [processone/ejabberd#3509]
What version of ejabberd are you using?

lastest (from the master branch)

    What operating system (version) are you using?

Ubuntu 20.04

    How did you install ejabberd (source, package, distribution)?

mix dependency (hex.pm)

    What did not work as expected? Are there error messages in the log? What
    was the unexpected behavior? What was the expected result?

The packet got filtered and the destination changed but the presence subscribe is not being delivered. Code is below, please point or my mistake or offer a fix. Thanks

`defmodule ModPresenceRequest do

    use Ejabberd.Module

    @behaviour :gen_mod

    @hook :filter_packet
    @func :on_filter_packet

    require EjabberdModule.Utility

    alias MyCircle.AccountManager
    alias Helper.StringUtils

    # require jid record from xmpp library
    require Record
    Record.defrecord :jid, Record.extract(:jid, from_lib: "xmpp/include/jid.hrl")
    Record.defrecord :presence, Record.extract(:presence, from_lib: "xmpp/include/xmpp_codec.hrl")
    Record.defrecord :mtext, Record.extract(:text, from_lib: "xmpp/include/xmpp_codec.hrl")

    def start(host, _opts) do
        info('Starting ejabberd module MyCircle Presence Request')
        Ejabberd.Hooks.add(@hook, :global, __MODULE__, @func, 30)
        :ok
    end

    def stop(host) do
        info('Stopping ejabberd module MyCircle Presence Request')
        Ejabberd.Hooks.delete(@hook, :global, __MODULE__, @func, 30)
        :ok
    end

    def on_filter_packet(packet) do
        type = :xmpp.get_type(packet)
        case type do
            :subscribe ->
                info("Mapping presence subscribe destination")
                to = :xmpp.get_to(packet)
                phone_number = jid(to, :user)
                case AccountManager.get_by_phone_number(phone_number) do
                    {:ok, account} ->
                        phone_number = to_string(account.id)
                        to = jid(to, user: phone_number, luser: phone_number)
                        packet = :xmpp.set_to(packet, to)

                        info("Presence Subscribe destination mapped successfully")
                        packet
                    {:error, message} ->
                        info(message)
                        :drop
                end
            _ ->
                packet #    |> IO.inspect()

        end
    end

    def depends(_host, _opts) do
        []
    end

    def mod_options(_host) do
        []
    end
end
`

**Comment by prefiks** [comment]
In general changing destination will affect routing of package (filter_packet is called early enough that changed `to` will be used to select target). But i don't think this approach will work correctly - packet sender will act on original data that it sends before routing and your hook gets called, so it own roster update will be using old data.

To be able to handle that in sender process you probably want to use `user_send_packet` hook, this will allow you to change packet before it gets processed by associated c2s process. Be aware, that this hook gets called with different argument, it gets {Packet, C2SState} tuple (and should return that as well).
