### ISSUE TITLE
Create annotated tags instead of lightweight tags

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3512]
## The problem

Since ejabberd 2.1.8 released in June 2011, we have 59 tags in the git repository that were created "lightweight", not "annotated", with a command similar to:
```git tag 21.01```

For reference, `git help tag` explains:

>   Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is simply a name for an object (usually a commit object).
> 
>   Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

This is explained in many other places, for instance [Git Tag Does the Wrong Thing by Default](http://www.rockstarprogrammer.org/post/2008/oct/16/git-tag-does-wrong-thing-default/)

Those tags are slightly annoying when using some git tools, because git gives more importance to annotated tags, use them for identifying intermediate commits, and other tasks. 

For example, you can go to your up-to-date ejabberd git respository, and get perplexed with:
```
$ git describe HEAD
v2.1.12-5294-g527b662fe
```

Or see `tig refs`... the old releases are displayed first!
![tig-refs1](https://user-images.githubusercontent.com/96807/106516203-ffa95b00-64d6-11eb-8720-fb091d181af4.png)

## The solutions

The solution for next releases is to create annotated tags, for example with a command like this:
```git tag 21.01 -m "Tag for release ejabberd 21.01"```

But what about the existing tags? Well, if you want the existing tags in your ejabberd git repository to get fixed, you can use this script. First of all, obviously, backup your git repository, just in case something gets screwed.

```bash
git tag -l --format="%(objecttype) %(refname:strip=2) %(objectname:short) %(creatordate:iso-strict) %(authoremail)" | grep "^commit " >workplan.txt
WORKSIZE=`cat workplan.txt | wc -l`
cat workplan.txt | less
read -p "Press ENTER to delete those $WORKSIZE lightweigth tags and create annotated tags, or Ctrl+C to cancel: "

while read -r type name coid date tager; do
    export TYPE=$type NAME=$name COID=$coid DATE=$date TAGER=$tager;
    MESSAGE="Tag for release ejabberd $NAME"
    git tag -d $NAME
    GIT_AUTHOR_DATE="$DATE" GIT_COMMITTER_DATE="$DATE" git tag $NAME -m "$MESSAGE" $COID
done <workplan.txt
```

And the results:

```
$ git describe HEAD
21.01-7-gbb397bb4
```

And `tig refs` now displays the most recent tags first, correctly:
![tig-refs2](https://user-images.githubusercontent.com/96807/106516464-5c0c7a80-64d7-11eb-8446-04aa53c6278c.png)

## How to get this update

If you download the ejabberd git repository now, you will get the new annotated tags directly.

If you want to get the new annotated tags in your existing copy of ejabberd repository, simply run:
```
$ git fetch origin --tags --force
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 59 (delta 0), reused 59 (delta 0), pack-reused 0
S'estan desempaquetant els objectes: 100% (59/59), fet.
De github.com:processone/ejabberd
 t [actualització d'etiqueta] 13.03-beta1 -> 13.03-beta1
 t [actualització d'etiqueta] 13.06       -> 13.06
 t [actualització d'etiqueta] 13.09       -> 13.09
 ...
 t [actualització d'etiqueta] 21.01       -> 21.01
 t [actualització d'etiqueta] v2.1.8      -> v2.1.8
 t [actualització d'etiqueta] v3.0.0-P003 -> v3.0.0-P003
 t [actualització d'etiqueta] v3.0.0-P004 -> v3.0.0-P004
```

**Comment by prefiks** [comment]
It worth mention that `git descirbe --tags` work with lighweight tags
