### ISSUE TITLE
File upload using POSTMAN

### ISSUE THREAD

**Issue by AtifShahzed** [processone/ejabberd#3522]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Windows)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

I have configured mod_http and tested from ConverseJs online app for file upload it works fine but I am looking to upload file on server using Http from my app.
Can someone share the sample POSTMAN settings to upload file on server so that would help me to easily incorporate in my app.

Thanks

**Comment by weiss** [comment]
This issue tracker is meant for bug reports against (recent versions of) ejabberd.
