### ISSUE TITLE
Delete of group-messages and messages from server

### ISSUE THREAD

**Issue by omexlu** [processone/ejabberd#3530]
Hello, 

I wanted to set up a cronjob that does the following:
- Delete messages older than X days from the server. 
- Delete group messages older than X days from the server. 

Is there somehow a command to do this in docker-compose?

Thanks in advance.

**Comment by licaon-kter** [comment]
This is not an issue, see ejabberdctl commands on https://docs.ejabberd.im

/close this

**Comment by prefiks** [comment]
You are looking for 'ejabberdctl delete_old_messages NUMBER_OF_DAYS' and 'ejabberdctl delete_old_mam_messages NUMBER_OF_DAYS'.

**Comment by omexlu** [comment]
> You are looking for 'ejabberdctl delete_old_messages NUMBER_OF_DAYS' and 'ejabberdctl delete_old_mam_messages NUMBER_OF_DAYS'.

Thank you, there also a command to delete old offline messages too?

Or some other messages that also maybe need to be deleted for a clean System? 😊

**Comment by prefiks** [comment]
First command cleans offline storage, second mam (message archives).

**Comment by omexlu** [comment]
So to be clearly:
First command: offline storage min. x days old
Second command: group-chat storage min. x days old

If "all" is not defined in both commands, messages and group-messages are included? 

No other command needed to clean something else?

Many thanks.

**Comment by prefiks** [comment]
I don't think there is more data to clean.

**Comment by omexlu** [comment]
> I don't think there is more data to clean.

Thank you :) I don't think so because I have 30 days rentation policy for file uploads.

I think so that is all I need to do :)

**Comment by licaon-kter** [comment]
@omexlu I use these 3 mentioned here: https://github.com/processone/ejabberd/issues/2695

Also, don't forget to VACUUM (or whatever is that called for) your database (if not Mnesia).

**Comment by omexlu** [comment]
> @omexlu I use these 3 mentioned here: #2695
> 
> Also, don't forget to VACUUM (or whatever is that called for) your database (if not Mnesia).

I testet the commands if no output all went good?
How can I check if something has changed and are deleted?

**Comment by licaon-kter** [comment]
`echo $?` can confirm after each one, also watch out your ejabberd.log just in case

**Comment by omexlu** [comment]
I will get a watch in ejabberd log tomorrow after Cronjob was done, I think there must be a [info] I suggest :)
