### ISSUE TITLE
Presence subscribe request fails when using JWT auth

### ISSUE THREAD

**Issue by dabslants** [processone/ejabberd#3537]
Presence subscription request don't get to destination for JWT with users.
Is it not possible to handle presence request manually when using JWT auth?

Tried with sql auth users and it works fine. Only face issue when it's JWT users.

**Comment by prefiks** [comment]
Hello,

I don't think this is the case in general, possibly you have module that blocks that active? I think mod_block_strangers can be configured to do that, do you have it in your config?

**Comment by prefiks** [comment]
Ok, there may be different reason for that. We perform check for user existence before subscription is routed (possibly only when user is offline?), but with jwt we don't have list of users that are registered (they are managed outside ejabberd), which make that check fail.

**Comment by dabslants** [comment]
So there's no way out of this.
External auth has methods for this right why not jwt?

**Comment by prefiks** [comment]
With external auth, you we ask external program for that (there is query in extauth protocol that can answer that), but with jwt there is nothing that can tell us for what users tokens were generated. Probably best way for that would be trying to add database to keep info about users that we already seen, and use that to answer this question, but we don't have that yet.
