### ISSUE TITLE
Does mod-mqtt support clustering?

### ISSUE THREAD

**Issue by simon-fu** [processone/ejabberd#3543]
## Environment

- ejabberd version: 20.07
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1.7
- OS: MacOS 10.15.7
- Installed from: brew

## Steps
- User A connect to Node1 and subscribe topic t1
- User B connect to Node2 and publish message to topic t1
- User A receive nothing

## Description
- From the source code of nif mqtree, it seems that the topic tree only store at local node and never sync to other nodes. Is  that right?

**Comment by badlop** [comment]
Hi. I didn't check the module source code, and didn't test it. But at first look, I see that the module uses the mnesia tables mqtt_pub, mqtt_sub and mqtt_session. So, if you set those tables to replicate on the nodes, I imagine clustering should work. Notice that mnesia sync is implemented in mnesia itself, no need to implement synching code.

> From the source code of nif mqtree, it seems that the topic tree only store at local node and never sync to other nodes.

What file and line number are you reading?

**Comment by mremond** [comment]
I think @badlop explained it right: ejabberd supports clustering for MQTT.

**Comment by youngmort** [comment]
Hi @badlop  I have the same problem. I would like to replicate the mqtt_pub, mqtt_sub and mqtt_session tables on the node. 
If I want to achieve this requirement, do I need to modify the source code or modify the configuration file？(ejabberd.yml)

I have read the file below and I can’t find the settings.
https://docs.ejabberd.im/admin/configuration/modules/#mod-mqtt

I am looking forward to your reply.

**Comment by badlop** [comment]
First of all, if you plan to have a big server, it's recommended to use a powerful SQL database... Mnesia is only for small servers.



I don't know about MQTT, but did a simple test and mnesia replication worked:
1. I installed ejabberd (compiled from recent source code) in two paths
2. Configured each node with a different erlang node name, and listening different port numbers
3. Started both nodes
4. In the second node: run "join_cluster" to join the first node
5. In the first node I run: mod_mqtt_mnesia:subscribe({<<"user1">>, <<"localhost">>, <<"tka">>}, "aa", [], "abc").
6. Now in both nodes I see the mqtt_sub mnesia table with that item. I see it in ejabberd WebAdmin -> Nodes -> my node -> Database

**Comment by youngmort** [comment]
Hi @badlop Thanks for your reply.
