### ISSUE TITLE
Mod_conversejs

### ISSUE THREAD

**Issue by omexlu** [processone/ejabberd#3544]
Hello, 

Please make a easy way to implement conversejs into ejabberd like other servers can do with mod_conversejs. 

Same for the docker version :)

Thanks in advance.

**Comment by licaon-kter** [comment]
You can just host it
https://gist.github.com/54d4656cc753b98e1dc0d81a59a73faa

**Comment by omexlu** [comment]
I don't know how to do this, I use mailcow and they rely on a Ready to use docker image of ejabberd, so I would prefer if this was already anchored in the image.

Since I can't/shouldn't change much manually here.

**Comment by paulmenzel** [comment]
Since ejabberd 21.12, [mod_conversejs](https://docs.ejabberd.im/archive/21_12/modules/#mod-conversejs) is available.
