### ISSUE TITLE
CRASH REPORT -     initial call: lager_handler_watcher:init/1

### ISSUE THREAD

**Issue by jainygaurav** [processone/ejabberd#3547]
Please help me fix this issue:

> With OTP 22 and ejabberd 16.03

```
EJABBERD_CONFIG_PATH=ejabberd.yml erl -pa ebin -pa deps/*/ebin -pa test -pa deps/elixir/lib/*/ebin/ -s ejabberd
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Eshell V10.6.4  (abort with ^G)
1> =CRASH REPORT==== 8-Mar-2021::07:24:55.067647 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.112.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.97.0>]
    message_queue_len: 0
    messages: []
    links: [<0.100.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 228
  neighbours:

```

> However with OTP 19.3.6 and ejabberd-16.03, it works

```
EJABBERD_CONFIG_PATH=ejabberd.yml erl -pa ebin -pa deps/*/ebin -pa test -pa deps/elixir/lib/*/ebin/ -s ejabberd
Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3.5  (abort with ^G)
1> 07:24:05.903 [info] Application lager started on node nonode@nohost
07:24:05.910 [info] Application crypto started on node nonode@nohost
07:24:05.919 [info] Application sasl started on node nonode@nohost
07:24:05.930 [info] Application asn1 started on node nonode@nohost
...
```

**Comment by prefiks** [comment]
Hello,

I don't think you will make this work, this version is just not compatible with OTP22. You can't just reuse version that was build with older OTP with newer OTP, the are parts that aren't binary compatible. You would need to recompile this, but i am pretty sure that will not success either - there were changes in language that will require modification of source files.

If you need to use newer OTP you will just need to use never version of ejabberd - one that was prepared to work with that version of erlang.

**Comment by jainygaurav** [comment]
@prefiks I did compile with OTP 22. However, I understand that ejabberd-16.03 may not work with OTP 22.

My concern is that I have data in mnesia tables created under 16.03. 

* Do you have tools to transfer mnesia data from ejabberd-16.03 ---> ejabberd-latest.
* Can you provide any other tip?

Just a note......I have very limited understanding of erlang.

**Comment by licaon-kter** [comment]
Make a backup first, then update version by version, afaik Mnesia support autoupgrades.

**Comment by jainygaurav** [comment]
@licaon-kter do you mean from ejabberd-16.03 ----> ejabberd-20.x.....that will be like 20-30 updates?

Is that what you mean?

**Comment by prefiks** [comment]
I would you try with newest version and your data, only schema changes i found should autoupgrade, but of course please do backup first

**Comment by licaon-kter** [comment]
I'm thinking that small incremental steps would be safer, but I don't know the full Mnesia power :)

**Comment by jainygaurav** [comment]
@licaon-kter is it possbile to:

* Read all the data/tuples from mnesia-ejabberd-16.03
* Write to a file
* Then read the file and put data in mnesia-ejabberd-latest.

**Comment by prefiks** [comment]
Structure of mnesia database records didn't change, so this will not give you much, only problem may be that those tuples may not be recognized by newer version, but doing that dance will not help with that.

**Comment by jainygaurav** [comment]
@prefiks When ejabberd-16.09 was out, I did try to upgrade from 16.03 ----> 16.09. 

But it did not succeed. If I remember correctly, it was related to corrupted mnesia DB. So, I stayed on 16.03 since then. I never tried updating again.

So, per your suggestion, 

* I should take the backup and 
* Update directly to latest version
* According to you, it should work

Right?

**Comment by prefiks** [comment]
It may work, i won't give you guarantee, at least i didn't notice any incompatibility in schemas from brief check.

**Comment by badlop** [comment]
In any case, you can install a recent ejabberd version in a test machine (not in the deployment server), copy the mnesia backup, check if it starts correctly... and once you're sure, repeat in the definitive server.

**Comment by jainygaurav** [comment]
@badlop ok...I will update accordingly.
