### ISSUE TITLE
A modified module_sql.erl is not loading immediately when I install a module using installer. 

### ISSUE THREAD

**Issue by marcelinojung** [processone/ejabberd#3548]
## Environment
- ejabberd version: 21.01.14
- Erlang version: Erlang/OTP 23 [erts-11.1.7]
- OS: Linux (Ubuntu)
- Installed from: source 

When I install and uninstall a module using installer for developing,
the modified 'module.erl' is confirmed immediately, but the 'module_sql.erl' is recognized old version.
When I restart the ejabberd server, everything is recognized normally.
can I fix it?

**Comment by badlop** [comment]
Instead of module_uninstall and install, maybe this command helps:
```
$ ejabberdctl help module_upgrade
  Command Name: module_upgrade
  Arguments: module::binary
  Returns: res::rescode
  Tags:  admin modules
  Description:  Upgrade the running code of an installed module
 In practice, this uninstalls and installs the module
```

Or you can try those two commands
```
$ ejabberdctl help update_list
  Command Name: update_list
  Arguments: 
  Returns: modules::[ module::string ]
  Tags:  server
  Description:  List modified modules that can be updated

$ ejabberdctl help restart_module
  Command Name: restart_module
  Arguments: host::binary
             module::binary
  Returns: res::integer
  Tags:  erlang
  Description:  Stop an ejabberd module, reload code and start
```

If that doesn't help, it would help if you provide the steps to reproduce the problem, including the required source code.

**Comment by marcelinojung** [comment]
Thanks badlop. 
But, the 'module_upgrade, update_list' commands works same with uninstall-install(loading old module just module_sql.erl). 


I just make a template 'mod_mam_custom' using 'mod_mam' in ejabberd 21.01.14.
It just works same with mod_mam.

https://github.com/marcelinojung/mod_mam_custom.git

For test, 
- mark % mod_mam config in the ejabberd.yml. 
- copy the mod_mam_custom to $CONTRIB_MODULES_PATH/sources/

ejabberdctl module_install mod_mam_custom
ejabberdctl module_uninstall mod_mam_custom

* change something 'mod_mam_custom_sql.erl'. 
I just change 106 line, 
Body = fxml:get_subtag_cdata(Pkt, <<"body">>)  ----> Body = "body" 

ejabberdctl module_install mod_mam_custom

And, the inserted txt is 'fxml:get_subtag_cdata(Pkt, <<"body">>)'. 
After restarting ejabberd server, the inserted txt is "body". 

But, when I modified the mod_mam_custem.erl, it is confirmed immediately after uninstall-install.

**Comment by badlop** [comment]
Aha! With your example instructions, I can reproduce the problem.

### Explanation of the problem

Your project is called mod_mam_custom, but you noticed that ejabberd compiles and installs **all** the erlang modules that it can find in src/, see 
https://github.com/processone/ejabberd/blob/14c8e1226fe05434b1438b7e7c80ab4a7a50c565/src/ext_mod.erl#L558

Later, when you run uninstall_module, **only** the erlang module called mod_mam_custom is removed from the erlang node, see https://github.com/processone/ejabberd/blob/14c8e1226fe05434b1438b7e7c80ab4a7a50c565/src/ext_mod.erl#L248

### One easy solution

In mod_mam_custom.erl add a small function that tells ext_mod to remove your other erlang modules too. This way, when later you install it again, all the new modules are loaded.

```diff
diff --git a/src/mod_mam_custom.erl b/src/mod_mam_custom.erl
index 3c38f22..72c7a49 100644
--- a/src/mod_mam_custom.erl
+++ b/src/mod_mam_custom.erl
@@ -44,6 +44,8 @@
 	 is_empty_for_user/2, is_empty_for_room/3, check_create_room/4,
 	 process_iq/3, store_mam_message/7, make_id/0, wrap_as_mucsub/2, select/7]).
 
+-export([pre_uninstall/0]).
+
 -include_lib("xmpp/include/xmpp.hrl").
 -include("logger.hrl").
 -include("mod_muc_room.hrl").
@@ -92,6 +94,12 @@
 %%%===================================================================
 %%% API
 %%%===================================================================
+pre_uninstall() ->
+    [{code:purge(M), code:delete(M)}
+     || M <- [mod_mam_custom_mnesia,
+              mod_mam_custom_opt,
+              mod_mam_custom_sql]].
+
 start(Host, Opts) ->
     case mod_mam_custom_opt:db_type(Opts) of
 	mnesia ->
```

**Comment by marcelinojung** [comment]
It works nicely! Very thanks badlop! 
The burden of restarting was reduced.
