### ISSUE TITLE
user gets kicked, no idea why

### ISSUE THREAD

**Issue by frederikbosch** [processone/ejabberd#355]
We made a chat room for error logging. When some error occurs on one of our services, this printed in this room. Sometimes the error logging is kicked from the room. I cannot resolve why this happends.

```
Error Logger left the room (This participant is kicked from the room because he sent an error message to another participant: service-unavailable).
```

I tried to look this up in the code, and I have found line 1296 in https://github.com/processone/ejabberd/blob/master/src/mod_muc_room.erl, but that does not help me what to do to fix this. The logs also do not help me. It could be the message, but when I send the same message with my own user, I am not kicked. It has to do with connection, or something like that. The error logging user disconnects immediately after he has sent the mesage.

We are running Debian Wheezy, ejabberd (2.1.10-4+deb7u1) . Anyone any idea?

**Comment by mremond** [comment]
Is this user from a remote server ?
The error means that when trying to send a message to the user resource, it was not online. Thus, the MUC module is doing the right thing and need to clean the participant list for consistency.

**Comment by frederikbosch** [comment]
Its a logger bot, who connects, puts a message in a room and disconnects. But 50% of the times, the bot is kicked before he is done sending his message. Is there a setting to prevent this?

**Comment by mremond** [comment]
No, there is no setting for that, but I guess this is an issue with bots as we do not see that with the bot we used.
The best approach however is more likely to have a module or command that accept the bot messages without requiring the bot to be in the room.

**Comment by mremond** [comment]
Is the XMPP bot code public ?

**Comment by frederikbosch** [comment]
Actually, it is an implementation on public code. See [the following gist](https://gist.github.com/frederikbosch/eaa21b844a1523c4e3b2). It requires [Monolog](https://github.com/Seldaek/monolog) and [a php implementation of xmpp](https://github.com/fabiang/xmpp).
