### ISSUE TITLE
How to do a select on Mnesia

### ISSUE THREAD

**Issue by juancar0505** [processone/ejabberd#3552]
I want to do a select on the tables of the databse. Can someone help me pls. Thanks

**Comment by badlop** [comment]
You are not proposing a feature improvement, so I'll remove the Kind:Feature.

**Comment by badlop** [comment]
This is a bug tracker, used to report bugs, or feature proposals, or provide improvements. You are simply asking how to use mnesia, this is a programming question about a programming language, unrelated to ejabberd. So this is not the place to ask.

**Comment by badlop** [comment]
If you want to learn how to use Mnesia, read the Mnesia documentation, or read tutorials about Mnesia, or tutorials about Erlang/OTP, or books about them.
