### ISSUE TITLE
pkix with millions reductions

### ISSUE THREAD

**Issue by Freyskeyd** [processone/ejabberd#3553]
## Environment

- ejabberd version: 20.12
- Erlang/Elixir version: `Erlang/OTP 21 [erts-10.3] - Elixir 1.10.4`
- OS: Linux (Debian)
- Installed from: source

## Bug description

After upgrading from elixir 1.8 to 1.10 I noticed an important amount of `reductions` in the grafana dashboard BEAM. After some explorations I discover that the `pkix` was holding the most of them. The `gen_server` of `pkix` seems to have 13 millions of reductions.

```elixir
%{
  current_function: {:gen_server, :loop, 7},
  name: :pkix,
  reductions: 13881142
},
```

I don't know if it's a normal behaviour for this module, it seems a little weird. Does someone encounter the same thing and should I do something to reduce this amount of reductions?

Thank's for reading!

**Comment by badlop** [comment]
Offtopic: what steps do you use to get ejabberd use a newer version of elixir? I think by default ejabberd downloads an old elixir version, and uses that even if a newer one is installed.

**Comment by Freyskeyd** [comment]
@badlop I've just added ejabberd as elixir dependency with a minimum Elixir version of 1.10.

**Comment by prefiks** [comment]
That pretty strange, pretty much this process gets only called when certs are getting updated, and that usually happens only when issuing reload_config, or from acme (unless you have some other code that calls it, only other call that sends work to that process is `pkix:get_cert_info()`), i will see if something like that happens on our servers.

**Comment by Freyskeyd** [comment]
@prefiks Does `pkix` is used to validate new tcp/ws connection by doing something with the certs?

**Comment by prefiks** [comment]
Yes pkix does this ,but it shouldn't generate work in that process, certificate check afaik uses in-memory table that is just updated by that process, but validation should hit that process at all.

**Comment by Freyskeyd** [comment]
@prefiks do you see any related issue on your side?

**Comment by prefiks** [comment]
I checked couple servers, and there were not that much as yours, but some had quite a bit of them (but those servers were running for quite a bit of time so maybe not that strange? will have to see how fast those are increasing).

**Comment by Freyskeyd** [comment]
For me it happens at start. I have a cluster with more than 3k users connected at the moment of restart. I don't really know how to debug that things or if it's a real issue or a BEAM things that can't be fix.

**Comment by prefiks** [comment]
Ok, i just checked one more thing, i started fresh server on debian vm, and just after startup pkix process shower 14 milions reductions, i guess reading and parsing all system certificates just takes some work (and since this code i think is 100% erlang, everything is counted in reductions). So i think this is not really a problem, unless it increases at huge rate for you all the time.

**Comment by prefiks** [comment]
But processing that all just takes second or two, so i guess not a big problem, after that initial burst that process will almost all the time sits idle.

**Comment by Freyskeyd** [comment]
The reductions counts shouldn't decrease over time? 

What's weird is that I didn't had as much as reductions on the last version of Elixir. I can't explain why, I've checked all the changelog without any clue. You're talking about certificates but I only have one on my cluster.

**Comment by prefiks** [comment]
No, reduction count is showing how much operations were generated since process started, it can only go up. Initial number that pkix will show will mostly depends on number of cert that it had to parser (so if you added extra cert or maybe system added new ca cert it will increase).
