### ISSUE TITLE
Windows Server 2012 R2 and ejabber 2.1.11 installation problem

### ISSUE THREAD

**Issue by thoehn352** [processone/ejabberd#356]
When installing 2.1.11 onto a 64-bit Windows 2012 R2 environment, I get an error message stating that the post installation script failed. I've tried running it in compatibility mode, but the message is the same.  Has anyone else encountered this error and found a solution?  Thanks in advance.

**Comment by mremond** [comment]
Windows ejabberd installer is for the moment outdated. We are trying to find "volunteers" to revive the Windows support, if there is enough request for an ejabberd Windows installer.

**Comment by cromain** [comment]
Windows server in now supported in 15.07.
