### ISSUE TITLE
ejabberdctl.cfg SMP=disabled no longer supported

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3560]
ejabberd 21.01, and many previous versions, include in the ejabberdctl.cfg file the option SMP which is said to be configurable to "disabled".

However, when setting SMP=disabled, erlang complains:
```
Argument '-smp disable' not supported. Use "+S 1" instead.
...
```

In fact, it seems "-smp disabled" was deprecated in Erlang/OTP 20.0 https://github.com/erlang/otp/pull/1416 and removed in 21.0 https://github.com/erlang/otp/pull/1515

So, it's time to rewrite the SMP option, or simply remove it.

From OTP 19.3 documentation http://erlang.org/documentation/doc-8.3/erts-8.3/doc/html/erl.html

> -smp [enable|auto|disable]
>
> -smp enable and -smp start the Erlang runtime system with SMP support enabled. This can fail if no runtime system with SMP support is available. -smp auto starts the Erlang runtime system with SMP support enabled if it is available and more than one logical processor is detected. -smp disable starts a runtime system without SMP support.
> 
> Note
> The runtime system with SMP support is not available on all supported platforms. See also flag +S.

> +S Schedulers:SchedulerOnline
>
> Sets the number of scheduler threads to create and scheduler threads to set online when SMP support has been enabled. The maximum for both values is 1024. If the Erlang runtime system is able to determine the number of logical processors configured and logical processors available, Schedulers defaults to logical processors configured, and SchedulersOnline defaults to logical processors available; otherwise the default values are 1. Schedulers can be omitted if :SchedulerOnline is not and conversely. The number of schedulers online can be changed at runtime through erlang:system_flag(schedulers_online, SchedulersOnline).
> 
> If Schedulers or SchedulersOnline is specified as a negative number, the value is subtracted from the default number of logical processors configured or logical processors available, respectively.
> 
> Specifying value 0 for Schedulers or SchedulersOnline resets the number of scheduler threads or scheduler threads online, respectively, to its default value.
> 
> This option is ignored if the emulator does not have SMP support enabled (see flag -smp).

**Comment by badlop** [comment]
@Neustradamus What is this?

![stalker](https://user-images.githubusercontent.com/96807/113431372-f146c500-93db-11eb-85c5-f235998a4f36.png)

**Comment by Neustradamus** [comment]
@badlop: It is an emoji: to say that it's interesting, I'm listening but I have not e-mail notification.
I have only looked your comment because I haved searched update of tickets....
