### ISSUE TITLE
Wrong field names in the REST API documentation

### ISSUE THREAD

**Issue by DanielBachmann** [processone/ejabberd#3563]
## Environment

- ejabberd version: docker hub rroemhild/ejabberd latest
- OS: Linux (Debian)
- Installed from: docker image

I had problems calling /api/add_rosteritem and /api/delete_rosteritem on the REST API

From the documentation ( [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#add-rosteritem](url) ):
```
POST /api/add_rosteritem
    {
      "localuser": "user1",
      "localhost": "myserver.com",
      "user": "user2",
      "host": "myserver.com",
      "nick": "User 2",
      "group": "Friends",
      "subs": "both"
    }
```
From the log I learned that it has to be ("server" instead of "host"):
```
{
    "localuser": "user1",
    "localserver": "myserver.com",
    "user": "user2",
    "server": "myserver.com",
    "nick": "User 2",
    "group": "Friends",
    "subs": "both"
}
```
Same for /api/delete_rosteritem. I didn't check other commands.
(I hope I'm reporting this the right way)

**Comment by badlop** [comment]
You may be using an old ejabberd version? Server was renamed to Host in ejabberd 19.08, more concretely in https://github.com/processone/ejabberd/commit/c318b5f8a235d5c5d26146f2ec28a1bf0aba7b82 for  #2908

**Comment by DanielBachmann** [comment]
I assumed the version used in the above mentioned docker image would be at least somewhat more recent and... I was wrong apparently.

Thanks for the answer and sorry for the effort.
