### ISSUE TITLE
Hot-code update when using Erlang/OTP 24.0 is broken

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3568]
## Environment

- ejabberd version: 21.04, or any previous version
- Erlang version: 12.0 (OTP 24.0-rc2)
- OS: Linux (Debian)
- Installed from: source

## Errors from error.log/crash.log

```
$ ejabberdctl update_list
Unhandled exception occurred executing the command:
** exception error: no match of right hand side value 
                  {error,systools_rc,
                      {function_clause,
                          [{systools_rc,get_lib,
                               [mod_vcard,
                                [{application,ejabberd,permanent,[],[],[],
                                     [mod_vcard],
                                     [],[],[],[],infinity,infinity,[],[],[]}]],
                               [{file,"systools_rc.erl"},{line,659}]},
...
```

## Bug description

Hot-code update when using Erlang/OTP 24.0 is broken

The 'application' record definition changed in OTP 24.0, see: https://github.com/erlang/otp/commit/791467116fdfabacb80d33cb458f22982e4f32ae

**Comment by prefiks** [comment]
Looks like application record definition in ejabberd_update.erl is no longer compatible.

**Comment by badlop** [comment]
Yes, I already got it working with a minor change, will commit later
