### ISSUE TITLE
install from source  error

### ISSUE THREAD

**Issue by markray** [processone/ejabberd#357]
I am using otp 17 to install ejabberd from source. when I run ./configure --prefix=/usr/local/ejabberd --enable-all --disable-pam --disable-mssql --disable-pgsql, error comes as following:
==> meck (compile)
Compiled src/meck_code.erl
Compiled src/meck_history.erl
Compiled src/meck_code_gen.erl
Compiled src/meck_expect.erl
Compiled src/meck.erl
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:51: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:345: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:382: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:383: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:415: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:416: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:422: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:423: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:429: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
/data/qitan/users/malei/ejabberd/deps/meck/src/meck_proc.erl:430: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
ERROR: compile failed while processing ***/ejabberd/deps/meck: rebar_abort

please have a check

**Comment by mremond** [comment]
Closing, as it seems it should be ok with proper option.
