### ISSUE TITLE
Checksums of 21.04 source archive change between two fetches

### ISSUE THREAD

**Issue by triaxx** [processone/ejabberd#3570]
## Environment

- ejabberd version: 21.04
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.2
- OS: NetBSD 9.0
- Installed from: source

## Bug description

I packaged ejabberd-21.04 on 13/04/2021 for pkgsrc, the package management framework for UNIX-like that is the default one for NetBSD: https://mail-index.netbsd.org/pkgsrc-changes/2021/04/13/msg232359.html
During this process, the source archive has been fetched from https://static.process-one.net/ejabberd/downloads/21.04/ejabberd-21.04.tgz and checksums have been computed.
But shortly after, the checksums mismatch the one computed during the packaging process as we can see in this log: http://www.ki.nu/pkgsrc/reports/current/NetBSD-9.0/20210413.1449/ejabberd-21.04/checksum.log
I tried to recompute the sums by refetching the archive and they had indeed changed.

### On 13/04/2021
SHA1 (ejabberd-21.04.tgz) = 9941c3c8662eeb3370dd211788f0be548d2ae3a3
RMD160 (ejabberd-21.04.tgz) = 413ead7aee419344238ce1d595b3868284ca7681
SHA512 (ejabberd-21.04.tgz) = d30642e90be1feb8673e9d7b3b513a17d54d94405057034c706bbd43d288e89479adb0ebaf8a4e8ff0f7e394f027d01bf171690c00e4169951ceecfbc0af4dc2
Size (ejabberd-21.04.tgz) = 1560926 bytes

### Now
SHA1 (ejabberd-21.04.tgz) = 139bd49fe8159619a2df745859ac0481b3821598
RMD160 (ejabberd-21.04.tgz) = 98b9b9ae3d6766ff74c10369c64d4fac9c6f39ee
SHA512 (ejabberd-21.04.tgz) = 4f7f645dbca35187c412e75fe90bcb96b87fc71beb073e0b913155e78832499f57218b1c42e0adf139a24cf1e235b4d1d123214a472aabf093a65f5d136b9579
Size (ejabberd-21.04.tgz) = 1560934 bytes

**Comment by licaon-kter** [comment]
There were some packaging fixer for cert.pem (see support MUC history), maybe those are at fault.

**Comment by badlop** [comment]
Yes, past Thursday, 7th April, when 21.04 was released, a problem in the three binary installers (`*.run, *.deb and *.rpm`) was detected: the conf/cacert.pem file, was like this:
```xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://curl.se/ca/cacert.pem">here</a>.</p>
<hr>
<address>Apache Server at curl.haxx.se Port 80</address>
</body></html>
```

So, all the packages were rebuild, and uploaded. That included the source code *.tgz, even if doesn't include that file and was not affected by the problem.

I've compared the checksums of the old (7 April) and the newly downloaded (right now) tgz file, and they are different. But, if you unpack them and compare their contents, you will see their contents are identical.

**Comment by gdt** [comment]
It would be really nice if the project was able to refrain from re-publishing different distfiles with the same names.  This interacts badly with packaging systems that seek to pin the particular file as a defense against upstream malware injection.  Thus, I suggest a policy that if a distfile, once published, has to be changed at all for any reason, that a new version number be used.

**Comment by mremond** [comment]
> Thus, I suggest a policy that if a distfile, once published, has to be changed at all for any reason, that a new version number be used.

Yes, I agree. This is also a better way to know that something has changed.
