### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by raphael10-collab** [processone/ejabberd#3586]
Yesterday I tried to install Ejabberd first through souce code, and then with Ubuntu specific packages.
I guess I made a mess, because now I'm getting this threatening `Crash dump` error.

    (base) marco@pc01:~$ sudo aptitude install ejabberd
    The following NEW packages will be installed:
      ejabberd erlang-asn1{a} erlang-base{a} erlang-base64url{a} 
      erlang-crypto{a} erlang-edoc{a} erlang-fs-listener{a} erlang-goldrush{a} 
      erlang-inets{a} erlang-jiffy{a} erlang-jose{a} erlang-lager{a} 
      erlang-mnesia{a} erlang-odbc{a} erlang-os-mon{a} erlang-p1-cache-tab{a} 
      erlang-p1-eimp{a} erlang-p1-iconv{a} erlang-p1-stringprep{a} 
      erlang-p1-tls{a} erlang-p1-utils{a} erlang-p1-xml{a} erlang-p1-xmpp{a} 
      erlang-p1-yaml{a} erlang-p1-zlib{a} erlang-proper{a} erlang-public-key{a} 
      erlang-runtime-tools{a} erlang-snmp{a} erlang-ssl{a} 
      erlang-syntax-tools{a} erlang-xmerl{a} inotify-tools{a} 
      libinotifytools0{a} libodbc1{a} libsctp1{a} 
    0 packages upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/22,9 MB of archives. After unpacking 40,9 MB will be used.
    Do you want to continue? [Y/n/?] Y
    Extracting templates from packages: 100% 
    Preconfiguring packages ...
    (Reading database ... 395356 files and directories currently installed.)
    Preparing to unpack .../00-erlang-base_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-base (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-asn1.
    Preparing to unpack .../01-erlang-asn1_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-asn1 (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-crypto.
    Preparing to unpack .../02-erlang-crypto_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-crypto (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-mnesia.
    Preparing to unpack .../03-erlang-mnesia_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-mnesia (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-runtime-tools.
    Preparing to unpack .../04-erlang-runtime-tools_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-runtime-tools (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-public-key.
    Preparing to unpack .../05-erlang-public-key_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-public-key (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-ssl.
    Preparing to unpack .../06-erlang-ssl_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-ssl (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-inets.
    Preparing to unpack .../07-erlang-inets_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-inets (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package libodbc1:amd64.
    Preparing to unpack .../08-libodbc1_2.3.4-1.1ubuntu3_amd64.deb ...
    Unpacking libodbc1:amd64 (2.3.4-1.1ubuntu3) ...
    Selecting previously unselected package erlang-odbc.
    Preparing to unpack .../09-erlang-odbc_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-odbc (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-syntax-tools.
    Preparing to unpack .../10-erlang-syntax-tools_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-syntax-tools (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package libinotifytools0.
    Preparing to unpack .../11-libinotifytools0_3.14-2_amd64.deb ...
    Unpacking libinotifytools0 (3.14-2) ...
    Selecting previously unselected package inotify-tools.
    Preparing to unpack .../12-inotify-tools_3.14-2_amd64.deb ...
    Unpacking inotify-tools (3.14-2) ...
    Selecting previously unselected package erlang-fs-listener.
    Preparing to unpack .../13-erlang-fs-listener_4.1-1_amd64.deb ...
    Unpacking erlang-fs-listener (4.1-1) ...
    Selecting previously unselected package erlang-xmerl.
    Preparing to unpack .../14-erlang-xmerl_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-xmerl (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-proper.
    Preparing to unpack .../15-erlang-proper_1.2+git988ea0ed9f+dfsg-1_amd64.deb ...
    Unpacking erlang-proper (1.2+git988ea0ed9f+dfsg-1) ...
    Selecting previously unselected package erlang-jiffy.
    Preparing to unpack .../16-erlang-jiffy_0.14.11+dfsg-2_amd64.deb ...
    Unpacking erlang-jiffy (0.14.11+dfsg-2) ...
    Selecting previously unselected package erlang-base64url.
    Preparing to unpack .../17-erlang-base64url_1.0-2_amd64.deb ...
    Unpacking erlang-base64url (1.0-2) ...
    Selecting previously unselected package erlang-jose.
    Preparing to unpack .../18-erlang-jose_1.8.4-2_amd64.deb ...
    Unpacking erlang-jose (1.8.4-2) ...
    Selecting previously unselected package erlang-goldrush.
    Preparing to unpack .../19-erlang-goldrush_0.1.9-4_amd64.deb ...
    Unpacking erlang-goldrush (0.1.9-4) ...
    Selecting previously unselected package erlang-lager.
    Preparing to unpack .../20-erlang-lager_3.5.2-2_amd64.deb ...
    Unpacking erlang-lager (3.5.2-2) ...
    Selecting previously unselected package erlang-snmp.
    Preparing to unpack .../21-erlang-snmp_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-snmp (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-os-mon.
    Preparing to unpack .../22-erlang-os-mon_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-os-mon (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-edoc.
    Preparing to unpack .../23-erlang-edoc_1%3a20.2.2+dfsg-1ubuntu2_amd64.deb ...
    Unpacking erlang-edoc (1:20.2.2+dfsg-1ubuntu2) ...
    Selecting previously unselected package erlang-p1-utils.
    Preparing to unpack .../24-erlang-p1-utils_1.0.10-2_amd64.deb ...
    Unpacking erlang-p1-utils (1.0.10-2) ...
    Selecting previously unselected package erlang-p1-cache-tab.
    Preparing to unpack .../25-erlang-p1-cache-tab_1.0.12-2_amd64.deb ...
    Unpacking erlang-p1-cache-tab (1.0.12-2) ...
    Selecting previously unselected package erlang-p1-eimp.
    Preparing to unpack .../26-erlang-p1-eimp_1.0.2-2_amd64.deb ...
    Unpacking erlang-p1-eimp (1.0.2-2) ...
    Selecting previously unselected package erlang-p1-iconv.
    Preparing to unpack .../27-erlang-p1-iconv_1.0.6-2_amd64.deb ...
    Unpacking erlang-p1-iconv (1.0.6-2) ...
    Selecting previously unselected package erlang-p1-stringprep.
    Preparing to unpack .../28-erlang-p1-stringprep_1.0.10-2_amd64.deb ...
    Unpacking erlang-p1-stringprep (1.0.10-2) ...
    Selecting previously unselected package erlang-p1-tls.
    Preparing to unpack .../29-erlang-p1-tls_1.0.20-1ubuntu0.2_amd64.deb ...
    Unpacking erlang-p1-tls (1.0.20-1ubuntu0.2) ...
    Selecting previously unselected package erlang-p1-xml.
    Preparing to unpack .../30-erlang-p1-xml_1.1.28-1_amd64.deb ...
    Unpacking erlang-p1-xml (1.1.28-1) ...
    Selecting previously unselected package erlang-p1-xmpp.
    Preparing to unpack .../31-erlang-p1-xmpp_1.1.19-1_amd64.deb ...
    Unpacking erlang-p1-xmpp (1.1.19-1) ...
    Selecting previously unselected package erlang-p1-yaml.
    Preparing to unpack .../32-erlang-p1-yaml_1.0.12-2_amd64.deb ...
    Unpacking erlang-p1-yaml (1.0.12-2) ...
    Selecting previously unselected package erlang-p1-zlib.
    Preparing to unpack .../33-erlang-p1-zlib_1.0.3-2_amd64.deb ...
    Unpacking erlang-p1-zlib (1.0.3-2) ...
    Preparing to unpack .../34-ejabberd_18.01-2_amd64.deb ...
    Generating SSL certificate /etc/ejabberd/ejabberd.pem...
    Unpacking ejabberd (18.01-2) ...
    dpkg: warning: unable to delete old directory '/opt/ejabberd-21.04/logs': Directory not empty
    dpkg: warning: unable to delete old directory '/opt/ejabberd-21.04': Directory not empty
    Selecting previously unselected package libsctp1:amd64.
    Preparing to unpack .../35-libsctp1_1.0.17+dfsg-2_amd64.deb ...
    Unpacking libsctp1:amd64 (1.0.17+dfsg-2) ...
    Processing triggers for ufw (0.36-0ubuntu0.18.04.1) ...
    Setting up libinotifytools0 (3.14-2) ...
    Setting up libodbc1:amd64 (2.3.4-1.1ubuntu3) ...
    Setting up inotify-tools (3.14-2) ...
    Setting up erlang-base (1:20.2.2+dfsg-1ubuntu2) ...
    Searching for services which depend on erlang and should be started...none found.
    Setting up libsctp1:amd64 (1.0.17+dfsg-2) ...
    Processing triggers for ureadahead (0.100.0-21) ...
    ureadahead will be reprofiled on next reboot 
    Setting up erlang-xmerl (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-crypto (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-asn1 (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-mnesia (1:20.2.2+dfsg-1ubuntu2) ...
    Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
    Setting up erlang-base64url (1.0-2) ...
    Processing triggers for systemd (237-3ubuntu10.46) ...
    Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
    Setting up erlang-runtime-tools (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-syntax-tools (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-odbc (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-proper (1.2+git988ea0ed9f+dfsg-1) ...
    Setting up erlang-fs-listener (4.1-1) ...
    Setting up erlang-p1-zlib (1.0.3-2) ...
    Setting up erlang-jiffy (0.14.11+dfsg-2) ...
    Setting up erlang-public-key (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-snmp (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-ssl (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-inets (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-goldrush (0.1.9-4) ...
    Setting up erlang-jose (1.8.4-2) ...
    Setting up erlang-os-mon (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-edoc (1:20.2.2+dfsg-1ubuntu2) ...
    Setting up erlang-lager (3.5.2-2) ...
    Setting up erlang-p1-utils (1.0.10-2) ...
    Setting up erlang-p1-stringprep (1.0.10-2) ...
    Setting up erlang-p1-yaml (1.0.12-2) ...
    Setting up erlang-p1-iconv (1.0.6-2) ...
    Setting up erlang-p1-tls (1.0.20-1ubuntu0.2) ...
    Setting up erlang-p1-cache-tab (1.0.12-2) ...
    Setting up erlang-p1-xml (1.1.28-1) ...
    Setting up erlang-p1-eimp (1.0.2-2) ...
    Setting up erlang-p1-xmpp (1.1.19-1) ...
    Setting up ejabberd (18.01-2) ...

    (base) marco@pc01:~$ ejabberdctl
    {"init terminating in [do_boot",{undef,[{ejabberd_ctl,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}](url)
    init terminating in do_boot ({undef,[{ejabberd_ctl,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

    Crash dump is being written to: /usr/local/var/log/ejabberd/erl_crash_20210427-084312.dump...done
This is the complete dump file: 
[erl_crash_20210427-084312dump.txt](https://github.com/processone/ejabberd/files/6382514/erl_crash_20210427-084312dump.txt)

    O.S: Ubuntu 18.04.4. Deskotp
    Erlang Version: 

      cat /usr/lib/erlang/releases/RELEASES
     %% coding: utf-8
      [{release,"Erlang/OTP","20","9.2",
          [{kernel,"5.4.1","/usr/lib/erlang/lib/kernel-5.4.1"},
           {stdlib,"3.4.3","/usr/lib/erlang/lib/stdlib-3.4.3"},
           {sasl,"3.1.1","/usr/lib/erlang/lib/sasl-3.1.1"}],

How to recover from this bad error `Crash dump` in order to restart from scratch the installation?
Looking forward to your kind help

**Comment by badlop** [comment]
Silently cross-posted in https://stackoverflow.com/questions/67278444/ejabberd-crash-dump-during-installation

**Comment by prefiks** [comment]
Possibly removing ejabberd in /opt/ejabberd-21.04 will help?
