### ISSUE TITLE
Monitoring for Ejabberd with Prometheus

### ISSUE THREAD

**Issue by sacgov** [processone/ejabberd#3590]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
There is no standard way of calculating metrics. i see that grapherl is archived. Please suggest if developing this is in the roadmap. I'm a newbie to Erlang. But this is needed at the place i work. I can work on developing this plugin.

**Describe the solution you'd like**
A http /metrics endpoint through which we can scrape common metrics. Which are theseare common and needs to be worked on could be discussed in this issue. Is it possible a newbie like me to develop this.

**Describe alternatives you've considered**
We run ejabberdctl through nrpe. and pass the metrics to nagios. This works for alerting but not really for actual metrics.

**Additional context**
We tried another approach which is to run ejabberdctl, parse stdout and pass the info to a database. It doesn't feel elegant and is quite hacky.

**Comment by licaon-kter** [comment]
This is not an issue.

Maybe better join the support room instead

xmpp:ejabberd@conference.process-one.net?join

**Comment by sacgov** [comment]
Closing the issue. Will join support instead. Thanks @licaon-kter .
