### ISSUE TITLE
Add ability to run ejabberd in development mode with `make run`

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#3596]
It is convenient to be able make and run ejabberd in development mode using `make run`, with a default development config.

**Comment by badlop** [comment]
Something like that is possible since 0fe2aea70969ea36bd4fe40997c261e5a3e974d2:

1. It requires rebar3 installed, and setting it: 
```
./configure --with-rebar=`which rebar3`
```
2. Compile, build the development release and prepare it: `make dev`
3. Finally use the script to start in detached or live mode:`./ejabberdctl live`
