### ISSUE TITLE
Undocumented JID disclosure

### ISSUE THREAD

**Issue by SkewedZeppelin** [processone/ejabberd#3609]
It seems that the owners of a room are automatically added to the `Contact` field of a MUC.
MUC owners likely don't expect this to happen, and might unknowingly open themselves up to eg. spam.

https://github.com/processone/ejabberd/blob/7b334998116316d1772b1ce1395818d755308bf0/src/mod_muc_room.erl#L4135

Can this be considered for removal? Or altered to only be added in non-anonymous MUCs?

CC @licaon-kter

**Comment by weiss** [comment]
I'm not quite sure how to address this, but publishing this only for non-anonymous MUCs makes no sense to me.  I think the point of this feature is: If you run a public room, you have take some responsibility for that room, so people should be able to contact you.  In contrast, private groups are only relevant to their members, and those can see the owner JIDs anyway.  (Therefore, the opposite patch would make some sense to me: Don't leak owner JIDs of private groups.)

I don't think hiding JIDs is the way to fight spam, and if it is, I think owners running public rooms should use a separate JID for that purpose.

Anyway, I take it others will disagree and insists on hiding contact data even for public rooms.  So I guess there's no way around either adding another room configuration option, or just removing this field altogether.

**Comment by licaon-kter** [comment]
@mwild1 Prosody doesn't have this, there were some thoughts put into this or just not implemented?

@Holger Given that XEP-0045 does not make it clear (and half the ecosystem ahem Prosody ahem does not leak the owners JIDs to everyone), I'd err on the safe side and not expose the JIDs.

**Comment by mwild1** [comment]
Prosody has never implemented this, and yes, it's (IMHO) clear why :)

As someone who has previously been victim to various abuse from random people I've banned from MUCs, I would definitely lean towards not publishing JIDs, especially without explicit consent.

If you want to contact the owners PM them, if they're not present then contact the server admin. I'm not personally sure what the general use-case is for this field.

**Comment by licaon-kter** [comment]
Should I just propose a `case` in the meantime and whenever the XEP is clarified this can be updated?
