### ISSUE TITLE
MUC nick registration allows registering unlimited nicks

### ISSUE THREAD

**Issue by SkewedZeppelin** [processone/ejabberd#3610]
Testing nick registration, I was able to register multiple nicks to a first test account and unable to use them on the second test account.

Given that you can register nick without any permission by default it seems ripe for abuse.

The delete query should always be called in the allow case it seems.

https://github.com/processone/ejabberd/blob/7b334998116316d1772b1ce1395818d755308bf0/src/mod_muc.erl#L1055-L1065
https://github.com/processone/ejabberd/blob/7b334998116316d1772b1ce1395818d755308bf0/src/mod_muc_mnesia.erl#L113-L145
https://github.com/processone/ejabberd/blob/7b334998116316d1772b1ce1395818d755308bf0/src/mod_muc_sql.erl#L223-L253

**Comment by badlop** [comment]
I cannot reproduce that weird behaviour using ejabberd git version and mnesia: when a client re-registers a new nick, the old one is removed. That is done directly in mnesia:write.

I also tried it manually:
```erlang
mnesia:dirty_write({muc_registered,{{<<"user11">>,<<"localhost">>},<<"conf.localhost">>}, <<"user1xxxd">>}).
ok

ets:tab2list(muc_registered).
[{muc_registered,{{<<"user11">>,<<"localhost">>}, <<"conf.localhost">>}, <<"user1xxxd">>}]

mnesia:dirty_write({muc_registered,{{<<"user11">>,<<"localhost">>},<<"conf.localhost">>}, <<"user1yyyyyy">>}).
ok

ets:tab2list(muc_registered). 
[{muc_registered,{{<<"user11">>,<<"localhost">>}, <<"conf.localhost">>}, <<"user1yyyyyy">>}]
```

So, I wonder:
* What ejabberd version are you using? Try with recent one
* Using some custom code, in mnesia or elsewhere? Or highly custom configuration?
* Check in the mnesia table if the old record is removed or not.

**Comment by SkewedZeppelin** [comment]
I just tested again and was unable to reproduce.
Apologies for the report.

- 20.07
- None
- Indeed it is removed
