### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by danielcliffordmiller** [processone/ejabberd#3611]
Hello, I am running ejabberd 21.01 on Debian (with erlang-p1-sqlite3 package version of 1.1.11)

I am trying to use an sqlite backend for the `mod_mam` message archiving but I keep getting an error `attempt to write to a readonly database` whenever messages are sent through ejabberd (crash report at the bottom of this issue).

My relevant configuration looks like this:
```
# sql related info                                                                                                                                                                                      
new_sql_schema: true
sql_type: sqlite
sql_database: /usr/share/ejabberd/data/ejabberd.data

modules:
  mod_mam:                                                                                                                                  
    db_type: sql
    assume_mam_usage: true
    default: always
```

I initially created the `ejabberd.data` database via executing:
```
sqlite3 -i /usr/share/ejabberd/sql/lite.new.sql ejabberd.data
```
It would appear that ejabberd can find the database and read it since when I run with the pre-populated schema, the case comparison here: https://github.com/processone/ejabberd/blob/7b334998116316d1772b1ce1395818d755308bf0/src/ejabberd_sql_sup.erl#L177 does not cause the schema to be created.

I have tried:
* changing the `user:group` of `ejabberd.data` to be `ejabberd:ejabberd` since it appears that is who systemd runs the daemon as (everything in those folders though, are owned by `root:root` and ejabberd does not appear to have any problem reading them)
* setting the write bit permissions on that file for group and all (`chmod 666 ejabberd.data`).
* changing the owner and bit permissions of the containing folder to `ejabberd:ejabberd` and `+w` for everyone
* running `erl` as user `ejabberd` and executing commands through the erlang sqlite3 driver that create tables (this works fine)
* creating an empty `ejabberd.data` "database" (but is actually an empty file) in an attempt to let ejabberd provision the schema itself. This also fails and is the source of the crash report found below.

Here are some of the error logs I receive on a pre-provisioned schema when messages were attempted to be archived:
```
2021-05-22 11:42:54.782936-05:00 [error] <0.554.0>@ejabberd_sql:check_error/2:1237 SQL query 'INSERT INTO archive(username, server_host, timestamp, peer, bare_peer, xml, txt, kind, nick) VALUES ('danmiller', 'danielcliffordmiller.com', 1621701774782402, 'danmiller@danielcliffordmiller.com/gajim.YOG1VEGD', 'danmiller@danielcliffordmiller.com', '<message xml:lang=''en'' to=''danmiller@danielcliffordmiller.com'' from=''danmiller@danielcliffordmiller.com/gajim.YOG1VEGD'' type=''chat'' id=''ad9a5372-50e2-4617-94e9-e16a9d8ce3a7'' xmlns=''jabber:client''><origin-id xmlns=''urn:xmpp:sid:0'' id=''ad9a5372-50e2-4617-94e9-e16a9d8ce3a7''/><markable xmlns=''urn:xmpp:chat-markers:0''/><body>fooo</body></message>', 'fooo', 'chat', '');' failed: "attempt to write a readonly database"
2021-05-22 11:42:54.783301-05:00 [error] <0.554.0>@ejabberd_sql:check_error/2:1230 SQL query 'Q37448423' at {mod_mam_sql,142} failed: "attempt to write a readonly database"
```

Here is my crash report and error logs for when ejabberd failed to write to the sqlite database on schema init:
```
2021-05-22 11:44:56.209105-05:00 [error] <0.586.0>@proc_lib:crash_report/4:525 CRASH REPORT:
  crasher:
    initial call: supervisor:ejabberd_sql_sup/1
    pid: <0.586.0>
    registered_name: []
    exception error: no match of right hand side value {error,8,
                                                        "attempt to write a readonly database"}
      in function  ejabberd_sql_sup:'-create_sqlite_tables/1-lc$^0/1-0-'/2 (ejabberd_sql_sup.erl, line 196)
      in call from ejabberd_sql_sup:create_sqlite_tables/1 (ejabberd_sql_sup.erl, line 196)
      in call from ejabberd_sql_sup:check_sqlite_db/1 (ejabberd_sql_sup.erl, line 179)
      in call from ejabberd_sql_sup:init/1 (ejabberd_sql_sup.erl, line 97)
      in call from supervisor:init/1 (supervisor.erl, line 301)
      in call from gen_server:init_it/2 (gen_server.erl, line 417)
      in call from gen_server:init_it/6 (gen_server.erl, line 385)
    ancestors: [ejabberd_db_sup,ejabberd_sup,<0.120.0>]
    message_queue_len: 0
    messages: []
    links: [<0.389.0>,<0.587.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 28
    reductions: 161275
  neighbours:
    neighbour:
      pid: <0.587.0>
      registered_name: 'ejabberd_sqlite_danielcliffordmiller.com'
      initial call: sqlite3:init/1
      current_function: {gen_server,loop,7}
      ancestors: ['ejabberd_sql_sup_danielcliffordmiller.com',ejabberd_db_sup,
                  ejabberd_sup,<0.120.0>]
      message_queue_len: 0
      links: [<0.586.0>,#Port<0.41>]
      trap_exit: false
      status: waiting
      heap_size: 610
      stack_size: 12
      reductions: 662
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,437}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,226}]}]
2021-05-22 11:44:56.233107-05:00 [error] <0.582.0>@ejabberd_sql_sup:start/1:60 Failed to start ejabberd_sql_sup: {{noproc,
                                    {gen_server,call,
                                     ['ejabberd_sqlite_danielcliffordmiller.com',
                                      {sql_exec,"begin"}]}},
                                   {child,undefined,
                                    'ejabberd_sql_sup_danielcliffordmiller.com',
                                    {ejabberd_sql_sup,start_link,
                                     [<<"danielcliffordmiller.com">>]},
                                    transient,infinity,supervisor,
                                    [ejabberd_sql_sup]}}
2021-05-22 11:44:56.232819-05:00 [error] <0.589.0>@proc_lib:crash_report/4:525 CRASH REPORT:
  crasher:
    initial call: supervisor:ejabberd_sql_sup/1
    pid: <0.589.0>
    registered_name: []
    exception exit: {noproc,
                        {gen_server,call,
                            ['ejabberd_sqlite_danielcliffordmiller.com',
                             {sql_exec,"begin"}]}}
      in function  gen_server:call/2 (gen_server.erl, line 238)
      in call from ejabberd_sql_sup:create_sqlite_tables/1 (ejabberd_sql_sup.erl, line 195)
      in call from ejabberd_sql_sup:check_sqlite_db/1 (ejabberd_sql_sup.erl, line 179)
      in call from ejabberd_sql_sup:init/1 (ejabberd_sql_sup.erl, line 97)
      in call from supervisor:init/1 (supervisor.erl, line 301)
      in call from gen_server:init_it/2 (gen_server.erl, line 417)
      in call from gen_server:init_it/6 (gen_server.erl, line 385)
    ancestors: [ejabberd_db_sup,ejabberd_sup,<0.120.0>]
    message_queue_len: 0
    messages: []
    links: [<0.389.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 28
    reductions: 161203
  neighbours:
```

**Comment by badlop** [comment]
I cannot reproduce that problem. I installed ejabberd 21.04 and configured like this:

```yaml
hosts:
  - localhost
  - sqlite.localhost

host_config:
  sqlite.localhost:
    sql_type: sqlite
    sql_database: /tmp/ejab.db
    sql_pool_size: 1
    auth_method: sql
    default_db: sql
    sm_db_type: sql
```

Then start ejabberd, and register new accounts in that vhost. Using the WebAdmin, and sqlitebrowser, I verify that file gets updated.

No need to manually create the file or the database.

No need to manually set file permissions: it's ejabberd who creates it!

Furthermore, removing that line, the database file is created in the same path that Mnesia is already being created by ejabberd:
```yaml
    sql_database: /tmp/ejab.db
```

**Comment by danielcliffordmiller** [comment]
Okay so my issue was resolved by correctly setting the permissions:
The database file set to `644` and owned by `ejabberd:ejabbered`,
*and* the directory that contains that database file needs to have permissions set to `777`  ( I had previously had the permissions a `755` ).

Ejabberd also appears to only successfully create a new database file when using the old version of the schema: https://docs.ejabberd.im/admin/configuration/toplevel/#new-sql-schema

Meaning when I had `new_sql_schema` set to true, and no database file existed at whatever I had under the `sql_database` parameter, it appears that ejabberd instantiated a database with the old schema and then failed with a `sql query failed: "no such column: server_host"`. I am not sure if this is a deviation from the desired behavior.

Whatever the case, my issue is resolved, thank you for looking into this and steering me in the right direction. I am marking this issue as closed.

**Comment by licaon-kter** [comment]
@badlop 
> it appears that ejabberd instantiated a database with the old schema
Is this the intended behaviour?

**Comment by badlop** [comment]
That was fixed a month ago in https://github.com/processone/ejabberd/commit/160cd11c8300a6dccb564b743b6dc250dfd8daa5
