### ISSUE TITLE
extauth.py fails in test suite with Python 3

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3612]
The [extauth.py](https://github.com/processone/ejabberd/blob/master/test/ejabberd_SUITE_data/extauth.py) included in ejabberd's test suite works correctly with Python 2, which is apparently the one included in Travis.

But now that I'm playing with Github Actions, specifically the [Ubuntu 20.04 virtual environment](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md), it includes Python 3.8.5.

I run something like this:
```shell
export CT_BACKENDS=extauth
DEBUG=1 rebar3 ct -v
```

and the extauth backend test fails with:
```
...
Testing lib.ejabberd: TEST COMPLETE, 175 ok, 1 failed, 1410 skipped of 1586 test cases

Traceback (most recent call last):
  File "extauth.py", line 45, in <module>
    read()
  File "extauth.py", line 5, in read
    (pkt_size,) = struct.unpack('>H', sys.stdin.read(2))
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "extauth.py", line 45, in <module>
    read()
  File "extauth.py", line 5, in read
    (pkt_size,) = struct.unpack('>H', sys.stdin.read(2))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by prefiks** [comment]
I am not python expert but i think sys.stdin.buffer.read(2) will return bytes object that unpack is expecting.

**Comment by prefiks** [comment]
But of course stdin don't have buffer on python2...

**Comment by prefiks** [comment]
```python
def read_from_stdin(bytes):
  if hasattr(sys.stdin, 'buffer'):
    return sys.stdin.buffer.read(bytes)
  else:
    return sys.stdin.read(bytes)
```

**Comment by badlop** [comment]
Your solution works great, thanks!

Now we can use Ubuntu 20.04 for testing
https://github.com/processone/ejabberd/runs/2667520722?check_suite_focus=true
