### ISSUE TITLE
Message acknowledgement is slow by using mod_mix

### ISSUE THREAD

**Issue by Shankaresakki** [processone/ejabberd#3617]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 19.0
- Erlang version: `erl +V`
- OS:  CentOS
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Problem: Acknowledgement of messages is slow when the number of participants in a group is high.

We use mod_mix for group chat. When the ejabberd receives the messages, it triggers a hook (user_send_packet) and when tried to acknowledge the message, the acknowledgment is sent very late. (It is slow as the no of participants increases)

Kindly help us to fix this issue. Please point out how we can overcome this issue. Any leads will be highly appreciated.

**Comment by badlop** [comment]
> ejabberd version: 19.0

What are the results using the most recent released ejabberd version?

> when the number of participants in a group is high.

What is "high" exactly?

> and when tried to acknowledge the message

How was that tried? Using some custom software?

**Comment by Shankaresakki** [comment]
ejabberd version: 19.0

What are the results using the most recently released ejabberd version? 
**<We are using 19.05 ejabberd version and we are not tried with new version>**

when the number of participants in a group is high.

What is "high" exactly? 
**In the group we have 200 participants in the group, when we sent a message in that group its takes more than 6 secs to message acknowledge the message**

and when tried to acknowledge the message

How was that tried? Using some custom software?
**No we are using default ejabberd there is no custom software used.**

**Comment by badlop** [comment]
Are there any MIX clients out there to try that, or a https://en.wikipedia.org/wiki/Minimal_working_example?

**Comment by licaon-kter** [comment]
@Shankaresakki which client do you use?

Siskin supports MIX, maybe Kaidan too.

**Comment by Shankaresakki** [comment]
We are using the user_send_packet hook to send an acknowledgment for the message. It works one-to-one and group chat( mod_mix) with less participants. which means the message sender received acknowledgment stanza  from the server takes some milli-seconds. But, if the group has large participants then the acknowledgment stanza for the message received time is increased. ex: 50 participants - 2 secs,100 participants - 4 secs,150 participants - 6 secs ..

**Comment by licaon-kter** [comment]
Hardware used? SQL DB (which?) or Mnesia?

**Comment by Shankaresakki** [comment]
We are ussing MySql Version 5.7 and Hardware  "OS : CentOS, 1 vCPU 8 GB RAM "

**Comment by Shankaresakki** [comment]
Hi Team, Could you update me on the status.

**Comment by badlop** [comment]
> We are using the user_send_packet hook to send an acknowledgment for the message.

> when we sent a message in that group its takes more than 6 secs to message acknowledge the message

So, you wrote custom software to send messages, right?

If you disable that, does everything else work correctly?
