### ISSUE TITLE
Index is wrong when getting last page of pubsub items with RSM

### ISSUE THREAD

**Issue by goffi-contrib** [processone/ejabberd#3618]
## Environment

- ejabberd version: 20.12

- OS: unix/linux 4.19.0
- Installed from: other

## Bug description

Hello,
This has been seen on a running instance of Movim. When I request last page of items of a blog, RSM index is 0 while it should be `[TOTAL number of items] - [number of items in this page]`.
Here is the relevant stream capture:
```xml
<iq id="H_83" type="get" to="edhelas@movim.eu">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <items node="urn:xmpp:microblog:0"/>
    <set xmlns="http://jabber.org/protocol/rsm">
      <max>3</max>
      <before/>
    </set>
  </pubsub>
</iq>

<iq xmlns="jabber:client" id="H_83" type="result" to="goffi@goffi.org/sat.bEvcAjs8XSVUfcfjG5HCxS" from="edhelas@movim.eu">
  <pubsub xmlns="http://jabber.org/protocol/pubsub">
    <set xmlns="http://jabber.org/protocol/rsm">
      <count>167</count>
      <first index="0">2021-05-27T22:41:35.266278Z</first>
      <last>2021-04-04T15:18:12.443634Z</last>
    </set>
    <items node="urn:xmpp:microblog:0">
  [IRRELEVANT, cut for readability]
    </items>
  </pubsub>
</iq>
```
As you can see, the `index` attribute on `first` element is `0` when it should be `167 - 3` thus `164`.
This count is specified at https://xmpp.org/extensions/xep-0059.html#forwards, here is the relevant text:

> The <first/> element SHOULD include an 'index' attribute. This integer specifies the position within the full set (which MAY be approximate) of the first item in the page. If that item is the first in the full set, then the index SHOULD be '0'. If the last item in the page is the last item in the full set, then the value of the <first/> element's 'index' attribute SHOULD be the specified count minus the number of items in the last page.

Thanks!

**Comment by badlop** [comment]
Thanks! I fixed this and other two small problems related to RSM in PubSub.
