### ISSUE TITLE
Setting vcard is not working in elixir app

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#3623]
## Environment
- ejabberd version: git master version
## Bug description

The original bug #3587 was fixed using new method of stringprep - `tolower_nofilter` in `mod_vcard.erl`. However, the package stringprep was not updated on hex.pm and the mix.exs depencency still point to:

`{:stringprep, "~> 1.0"}` 

that means version 1.0.25 from Mar 24. The commit that have this new `tolower_nofilter` implemented is from Apr 29 (commit 6d143ebcacaafe3a8adc669300a8ad001402b3d8).

Workaround, that changes ejabberd's mix.exs depencency to: `{:stringprep, git: "https://github.com/processone/stringprep.git", ref: "6d143ebcacaafe3a8adc669300a8ad001402b3d8", override: true},` solved the issue, but it would be better to create new version of stringprep on hex.pm.

**Comment by prefiks** [comment]
Hello,

I released new stringprep version and update ejabberd to use it in 2458f55837be8b6aa7599293577bc4535c8b89c1
