### ISSUE TITLE
Ejabberd Cloud hosting with AWS RDS and S3 support

### ISSUE THREAD

**Issue by armor009** [processone/ejabberd#3624]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

**Is your feature request related to a problem? Please describe.**
If ejabberd can support hosting on the cloud with AWS RDS and AWS S3, it will further increase adoptability and adoption of ejabberd.
Ejabberd is a fantastic open source project. I hope it gets adopted more. 

I for one will be able to adopt it the moment it supports cloud hosting and mobile features. 
 
**Describe the solution you'd like**
Ejabberd supporting cloud hosting with AWS RDS and AWS S3

**Describe alternatives you've considered**
There aren't other alternatives.

**Additional context**

**Comment by licaon-kter** [comment]
MariaDB/Mysql/Postgres and Redis, can already be used for storage,c what's the usecase for RDS and S3?

**Comment by mayank-mundhra-2012** [comment]
RDS- cloud hosting - EBS is expensive, RDS is cheaper.
S3 - file (image amd video) hosting

**Comment by ArtemisPseudo** [comment]
@licaon-kter @badlop  I too am facing this. Some information I could find.

S3- https://github.com/processone/ejabberd-contrib/issues/122
https://www.google.com/amp/s/www.process-one.net/blog/whats-new-in-ejabberd-business-edition-and-ejabberd-saas-in-october/%3famp
Wondering why the S3 or minio part hasn't been open sourced yet.

RDS- https://github.com/processone/ejabberd/issues/2054

**Comment by mayank-mundhra-2012** [comment]
Any response?

**Comment by Neustradamus** [comment]
@armor009, @ArtemisPseudo: Can you test it?
- https://github.com/processone/ejabberd-contrib/pull/314
