### ISSUE TITLE
failed to decode from DER format

### ISSUE THREAD

**Issue by NilucanAT** [processone/ejabberd#3629]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 20.7
- Erlang version: 10.6
- OS: Windows Server 2019
- Installed from: official binary installer

## Errors from error.log/crash.log

2021-06-21 07:40:31.041 [critical] <0.105.0>@ejabberd_app:start:71 Failed to start ejabberd application: Invalid value of option listen->4->certfile: Failed to read PEM file 'C:/ProgramData/ejabberd/conf/test.pem': at line 41: failed to decode from DER format

Running
[_|_] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/test.pem"),  
[{'PrivateKeyInfo', Der, _}|_] = public_key:pem_decode(Data),
#'PrivateKeyInfo'{privateKey = Key} = public_key:der_decode('PrivateKeyInfo', Der),
public_key:der_decode('RSAPrivateKey', Key).
gives:
** exception error: no match of right hand side value 
                    #'RSAPrivateKey'{
                        version = 'two-prime',
                        modulus = ... ,
                        publicExponent = 65537,
                        privateExponent = ... ,
                        prime1 = ... ,
                        prime2 = ... ,
                        exponent1 = ... ,
                        exponent2 = ... ,
                        coefficient = ... ,
                        otherPrimeInfos = asn1_NOVALUE}

## Bug description

I cannot get ejabberd to run because of the error mentioned above. With the certificate of a college of mine it is working fine, but I don't know why ejabberd refuses mine. 

I use an certificate with a self signed windows certificate authority as my college does, too.

[https://github.com/processone/ejabberd/issues/2488](url) seems like a similar problem, but I am not completely sure. However just with the private key I am able to start the service, but not with the full chain, since the error in line 41 occurs with the start of the public certificate of the server. When using only the private key I of course cannot connect because of: 

2021-06-21 08:32:46.742 [error] <0.564.0>@ejabberd_http:init:122 CRASH REPORT Process <0.564.0> with 0 neighbours crashed with reason: no match of right hand value {error,no_certfile} in ejabberd_http:init/3 line 122
2021-06-21 08:32:46.742 [error] <0.526.0>@ejabberd_http:init:122 Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.564.0> exit with reason no match of right hand value {error,no_certfile} in ejabberd_http:init/3 line 122 in context child_terminated

However with deactivating tls it obviously works.

Thanks for your help, Lukas

**Comment by prefiks** [comment]
Could you tell me what header your file have ( ===== BEGiN ....)?

**Comment by NilucanAT** [comment]
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
Bag Attributes
    localKeyID: 01 00 00 00 
    friendlyName: ....
subject=/CN=...
issuer=/C=.../DC=.../DC=..../O=..../OU=IT/CN=....
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
Bag Attributes: <Empty Attributes>
subject=/DC=.../C=.../O=.../OU=IT/CN=....
issuer=/.../C=.../O=..../OU=IT/CN=....
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
Bag Attributes: <Empty Attributes>
subject=/C=..../DC=.../DC=..../O=..../OU=IT/CN=....
issuer=/DC=..../C=.../O=..../OU=IT/CN=....
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----

**Comment by NilucanAT** [comment]
It is: private key --> certificate of this server --> certificate of root ca --> certificate of sub ca

**Comment by prefiks** [comment]
Can you check if you have \n at end of file? Not sure missing one will cause problem but from brief code check it could be it. Also could you see if you split your file into separate parts you will be able to pem_decode each part?

**Comment by NilucanAT** [comment]
1. Yes, there is a new line at the end of the cert chain
2. I run the following command for the private key and each cert-section individually:

[_|_] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/cert.pem"), 
[{'PrivateKeyInfo', Der, _}|_] = public_key:pem_decode(Data),
public_key:der_decode('RSAPrivateKey', Key).

On priv-key it outputs the exception mentioned in errors and on the certificates it outputs:
** exception error: no match of right hand side value [{'Certificate',<<...>>,
                                                                      not_encrypted}]

Is that what you wanted to see?

**Comment by prefiks** [comment]
For certificate files could you execute `public_key:pkix_decode_cert(element(2, public_key:pem_decode(Data)), otp)` (Data should be from read_file).

**Comment by NilucanAT** [comment]
So you mean: 

[_|_] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/sca.pem"), 
public_key:pkix_decode_cert(element(2, public_key:pem_decode(Data)), otp).

Then I get:
** exception error: bad argument
     in function  element/2
        called as element(2,
                          [{'Certificate',<<...>>,
                                          not_encrypted}])

I am sorry, but I'm a complete Erl-noobi^^

**Comment by prefiks** [comment]
Ah, make it `public_key:pkix_decode_cert(element(2, hd(public_key:pem_decode(Data))), otp).` - didn't spot that it's list with tuple inside

**Comment by NilucanAT** [comment]
Okay thanks: 

for the cert of the server and for the root-ca I get: 
exception error: no match of right hand side value {ok,<<"-----BEGIN CERTIFICATE-----\r\n..........\r\n........"...>>}

for the sub ca i get a lot of output about the certificate.

**Comment by prefiks** [comment]
Ok, so looks like something is not ok with that part, could you export it once more and if you will be able to read it?

**Comment by NilucanAT** [comment]
Did it, but it doesnt change anything. I exported it with the private key and got the .pfx file. after that i converted it via "openssl.exe pkcs12 -in C:\Users\admin\Desktop\sha512.pfx -out C:\Users\admin\Desktop\sha512.pem -nodes" to a pem cert and rerun the tests you mentioned above, but there is no change in the error messages.

**Comment by NilucanAT** [comment]
my openssl runs on a windows machine with version 1.1.1a

**Comment by prefiks** [comment]
Could you show me that server cert content?

**Comment by prefiks** [comment]
Er root cert content

**Comment by NilucanAT** [comment]
[certs.zip](https://github.com/processone/ejabberd/files/6685344/certs.zip)

**Comment by prefiks** [comment]
Hm, i can decode both of those on my machine. I am not sure what can can cause that problem for you.

**Comment by NilucanAT** [comment]
you are able to decode them in erl with the command:

[|] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/sca.pem"),
public_key:pkix_decode_cert(element(2, hd(public_key:pem_decode(Data))), otp).

?

**Comment by prefiks** [comment]
Yes (well with different file names)

**Comment by NilucanAT** [comment]
Yeah of course...then I will try to redeploy my whole machine for once and see if works then, but thanks for your help for now :)

**Comment by NilucanAT** [comment]
Hm, even after redeploying my machine there is no change in the behaviour. Still the error on decoding the priv-key and on decoding the cert of root and sub ca. 

What version of Erlang do you use?

**Comment by prefiks** [comment]
i tested on 23.3, but let me see if it works on different version

**Comment by NilucanAT** [comment]
okay, I am on version 22 as far as I know

**Comment by prefiks** [comment]
i was able to decode on 22.3, but got some errors on 21.3

**Comment by NilucanAT** [comment]
How do you get excact version? With "erlang:display(erlang:system_info(system_version))." I get: 

"Erlang/OTP 22 [erts-10.6] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]\n"

**Comment by prefiks** [comment]
I have erts-10.5, but close enough.

Now that i did looks at your error message, it may be just unrelated proble, could you try repeat those instructions for that cert again in clean shell? It looks like your error was caused by having old data already loaded. Or just execute this `public_key:pkix_cert_decode(element(2,hd(public_key:pem_decode(element(2, file:read_file("mycert.pem")))))).` which should also not hit that problem.

**Comment by NilucanAT** [comment]
Yeah you where right. In a clean environment I can decode the server, sca and rca certificate. 

How can I check the private again? With 

[_|_] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/key.pem"),
[{'PrivateKeyInfo', Der, _}|_] = public_key:pem_decode(Data),
public_key:der_decode('RSAPrivateKey', Key).

I still get the error mentioned at the beginning. 

PS.: Your command returns "** exception error: undefined function public_key:pkix_cert_decode/1"

**Comment by prefiks** [comment]
Ah, sorry, pkix_cert_decode takes two arguments, please add `, otp` just before the last bracket

**Comment by NilucanAT** [comment]
Now your command `public_key:pkix_decode_cert(element(2,hd(public_key:pem_decode(element(2, file:read_file("C:/Users/frqadmin/Desktop/test.pem"))))), opt).` gives a "** exception error: no function clause matching", but anyway, thats not the problem because with 

`[_|_] = rr(public_key),
{ok, _} = application:ensure_all_started(public_key),
{ok, Data} = file:read_file("C:/Users/admin/Desktop/rca.pem"),
public_key:pkix_decode_cert(element(2, hd(public_key:pem_decode(Data))), otp).` 

I can decode the certfile accordingly but not the private key of course.

**Comment by prefiks** [comment]
For private key you need to replace pkix_decode_cert(..., otp) with public_key:der_decode('PrivateKeyInfo', ....)

**Comment by NilucanAT** [comment]
Hm, the command does output normal infos regarding the private key. So now we are back to knowing nothing, right?

**Comment by NilucanAT** [comment]
On the machine of my college my certificate doesn't work, too. But his works on mine. I don't get what's wrong with my certificate...

**Comment by NilucanAT** [comment]
Does anyone have information regarding the issue?

**Comment by prefiks** [comment]
Would you be able to give me that non working cert so i could do some test on it myself?

**Comment by NilucanAT** [comment]
Hm, since it's only for testing purposes I think it's okay. I have sent it to you via mail, since I don't want it to be that publicly accessible.

**Comment by NilucanAT** [comment]
Now I have split up the certfile in individual files and get the DER-Decode Error for every public certificate. Like for Sub-Ca, Root-Ca and public host cert. Only the private key produces no error.

2021-06-24 10:00:56.489 [error] <0.371.0>@ejabberd_pkix:add_file:265 Failed to read PEM file c:/ProgramData/ejabberd/conf/sca.pem: at line 1: failed to decode from DER format
2021-06-24 10:00:56.489 [error] <0.371.0>@ejabberd_pkix:add_file:265 Failed to read PEM file c:/ProgramData/ejabberd/conf/rca.pem: at line 1: failed to decode from DER format
2021-06-24 10:00:56.489 [error] <0.371.0>@ejabberd_pkix:add_file:265 Failed to read PEM file c:/ProgramData/ejabberd/conf/pub.pem: at line 1: failed to decode from DER format

Any idea on that?

**Comment by badlop** [comment]
Hi! Did you find some solution to the problem?

**Comment by prefiks** [comment]
It was read correctly on linux/macos,  i tested with couple versions of erlang, but there was problem on reporter's windows machine, not sure why.
