### ISSUE TITLE
Problems in make rel and make dev

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3633]
ejabberd git master includes support for rebar3 in "make rel" and "make dev".

How to use it:
```
./configure --with-rebar=`rebar3`
make rel

make dev
./ejabberdctl live
```

List of known problems:

---

> Licaon_Kter: some files are doubled in the tar.gz (lib/ejabberd/priv/sql)

Right. Apparently the _copy_ and _template_ operations in `relx->overlay` are execute twice: one for `release`, and the other for `tar`, thus resulting in two instances of those files included in the tar file.

https://github.com/processone/ejabberd/blob/ac06161f30f5617d98cf29cf02331ae8d3f70b54/rebar.config#L192-L194

```
❯ tar --list -f ejabberd-21.04.83.tar.gz | sort | uniq -c | sort -r | head -n 12
      2 lib/ejabberd-21.04.83/priv/sql/pg.sql
      2 lib/ejabberd-21.04.83/priv/sql/pg.new.sql
      2 lib/ejabberd-21.04.83/priv/sql/mysql.sql
      2 lib/ejabberd-21.04.83/priv/sql/mysql.old-to-new.sql
      2 lib/ejabberd-21.04.83/priv/sql/mysql.new.sql
      2 lib/ejabberd-21.04.83/priv/sql/mssql.sql
      2 lib/ejabberd-21.04.83/priv/sql/lite.sql
      2 lib/ejabberd-21.04.83/priv/sql/lite.new.sql
      2 etc/ejabberd/inetrc
      2 etc/ejabberd/ejabberd.yml
      2 etc/ejabberd/ejabberdctl.cfg
      1 var/log/ejabberd/
```

Right now I see no way to solve that, or where exactly is the problem (probably in https://github.com/erlware/relx/blob/master/src/rlx_tar.erl)

Anway, I think this isn't a big problem, as the files are small, and both copies of each file are identical.

---

> Licaon_Kter:  and some files are missing (lib/ejabberd/priv/bin/captcha and include/)

captcha: right, they weren't copied. I've fixed in b5b2ad560ad8d2cd4be6a86cd8fa4ae9f84c5715

include/: right, include/ is copied in _build/prod/rel/ejabberd/lib/ejabberd-21.04.86/include
but is not included in the tar file! That means install modules from ejabberd-contrib with "ejabberdctl module_install" fails:
```
❯ ./bin/ejabberdctl module_install mod_isolation
/home/badlop/.ejabberd-modules/sources/ejabberd-contrib/
mod_isolation/src/mod_isolation.erl:26:14:
 can't find include lib "xmpp/include/xmpp.hrl"
%   26| -include_lib("xmpp/include/xmpp.hrl").
%     |              ^
...
```

The reason is that relx only adds "include" directories if include_src is enabled, see https://github.com/erlware/relx/blob/5a9f6ebbc30244d281d8e99aa3c9295b75efa975/src/rlx_tar.erl#L225

---

> Licaon_Kter: Also, normal install has only lite and lite new in lib/ejabberd/priv/sql while tar.gz has all

Right, and that is on purpose:

A) When using the ejabberd source package, the procedure is: download source code, create the databases, compile, install, configure, run. The admin already has all the source code, and also the _*.sql_ files, so installing _*.sql_ files is not necessary.

Even if "make install" does not install the _*.sql_ files, it does install _lite*.sql_ files, because those are used by ejabberd itself to create the SQLite database.

B) The result of "make rel" is a .tar.gz that can be copied to some other machine, or published, so it must contain all the _*.sql_ files.
 
---

> Holger: 'odbc' app is included in relx, should be included only when really needed.

Right. Fixed in 774de2bdc5f557a9a5e7375175db2e715db368f8

---

> Licaon_Kter: one odd thing about rebar as prod tar, seen in eturnal too, the _build/ folder will gather more and more releases and time goes by, as I update the repo, and... each new release will contain past ones too.
> *each new .tar.gz

Right, the release directory and tar contain all the versions
https://erlang.org/doc/design_principles/release_handling.html
https://adoptingerlang.org/docs/production/releases/

Any of them can be started anytime
```
./_build/prod/rel/ejabberd/bin/ejabberd-21.04.87 console
```
and, in theory, it is possible to upgrade at runtime from one to other.

**Comment by badlop** [comment]
The problems that could be solved are already solved. Others are inconvenience that, from what I know, we can't solve in ejabberd source code...

**Comment by licaon-kter** [comment]
> Even if "make install" does not install the *.sql files, it does install lite*.sql files, because those are used by ejabberd itself to create the SQLite database.

`./configure help` says `--enable-sqlite         enable SQLite support (default: no)`, so it's default **yes** here actually?
