### ISSUE TITLE
mod_push logging errors and deadlocks

### ISSUE THREAD

**Issue by umarniz** [processone/ejabberd#3635]
## Environment

- ejabberd version: 20.04
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.5`
- OS: Linux (Debian)
- Installed from: distro package

## Errors from error.log/crash.log

`Cannot enable push for <id>: database error`
`SQL query '...' at {mod_push_sql,53} failed: "#23000Duplicate entry ... for key 'i_push_usn'"`
`SQL query 'commit;' failed: "#40001Deadlock found when trying to get lock; try restarting transaction"`

## Bug description

I am uncertain what functionality is not working within Ejabberd but I am investigating complaints related to our current end to end chat + real-time signalling solution that is based on Ejabberd.

We are hearing problems related to signals intermittently being lost and other Ejabberd modules (mod_muc) responding out of order or with a delay. We are not sure if Ejabberd is to blame or our implementation at this moment.

The above errors are concerning none the less.

**Comment by badlop** [comment]
What's the status of this problem?
