### ISSUE TITLE
How to send unavailable presence after some time after WebSocket connection is closed after a web browser page refresh

### ISSUE THREAD

**Issue by MostafaSalama** [processone/ejabberd#3638]
I have an XMPP chat  application running 
Agents are chatting with visitors to the website 

I'm using JSJaC on the client-side 
 https://github.com/sstrigler/JSJaC/ 
 
 **Ejabberd version**:  20.04
 
 and we're running `Ejabberd` on the server
 application is using the `Webscoket` module 
 
 we're having Agents who can log in and start chatting with Visitors that visit the website 
 
 previously visitors to the website were using `mod_bosh` 
 and the `Ejabberd` server will send unavailable after 40sec if the client is not sending any HTTP Binding requests 
 
 now we moved to WebSockets for the visitors 
 and we removed the `mod_bosh`
 
 after a visitor starts the chat on the website with an agent,  
 if the visitor refreshes the page 
 the web browser will close the WebSocket connection 
 
and `Ejabberd` will send unavailable presence for the visitor as the WebSocket connection is closed 

**so my question is it possible to  config `Ejabberd`  to send the unavailable presence after some time 
after the WebSocket connection is closed?** 

so the  WebSocket connection is closed and then after for example 40sec 
Ejabberd will send the unavailable presence after the configured timeout? 

we need to find a solution for that, please let us know if there is a way to do it
as we don't want to send the unavailable presence after page refresh immediately. 

I tried to use `websocket_timeout` but it isn't working as the connection is closed by the browser 

here is the nginx config we use for the websocket routing 

```
location ~ ^/websocket {

  set $backend http://xmpp-svc.__namespace__.svc.__cluster_domain__:5280;
  proxy_pass $backend;

  proxy_set_header      Host $http_host;
  proxy_redirect        off;
  proxy_buffering       off;
  proxy_connect_timeout 5s;
  proxy_read_timeout    320s;
  tcp_nodelay           on;
  keepalive_timeout     320s;
  send_timeout          320s;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;

  add_header X-Frame-Options SAMEORIGIN always;
  add_header X-Content-Type-Options nosniff always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Pragma no-cache always;
  add_header Cache-Control 'no-cache="Set-Cookie, Set-Cookie2", no-store, must-revalidate, private' always;
}

```
to describe exactly the scenario we want:- 

if the visitor leaves the website or closes the browser we need to wait for 40sec before Ejabberd sends the unavailable presence 
we were able to do so with `mod_bosh` but we can't do it now with `WebSockets` 

with WebSockets is closing the connection after a page refresh or leaving the site immediately
we need to wait 40 sec   

Thank you

**Comment by licaon-kter** [comment]
@MostafaSalama That's rather old, does it support https://xmpp.org/extensions/xep-0198.html ?

Eg. https://github.com/conversejs/converse.js/ supports it

**Comment by MostafaSalama** [comment]
> @MostafaSalama That's rather old, does it support https://xmpp.org/extensions/xep-0198.html ?
> 
> Eg. https://github.com/conversejs/converse.js/ supports it

can you explain how this is related to the unavailable presence 
and what we can do? 

as I said we don't want to send the unavailable presence after the page is refreshed and the WebSocket 
connection is closed 
we need to wait at least 40sec

**Comment by licaon-kter** [comment]
Don't you want it to reconnect ?

**Comment by MostafaSalama** [comment]
> Don't you want it to reconnect?

what I want is to config Ejabberd to only send the unavailable presence after some time 
if the WebSocket connection is closed the unavailable presence is sent immediately 
I don't want this behavior 
I need to wait sometime after the WebSocket connection is closed

so it could be like this 
Visitor refreshes the page -> WebSocket connection is closed from the browser -> Ejabberd waits some time for example 40sec -> Ejabberd sends unavailable presence

**Comment by weiss** [comment]
> I need to wait sometime after the WebSocket connection is closed

Why?

**Comment by MostafaSalama** [comment]
> > I need to wait sometime after the WebSocket connection is closed
> 
> Why?

That's how our software works 
we tell the agents that the visitor has left the website after 40 sec if the visitor didn't come back to the site 
previously with `mod_bosh` Ejabberd would know that and will send the unavailable presence if Ejabberd didn't receive any HTTP binding requests 
so with the unavailable  presence, we tell the agent that the visitor left the website 

we need to make the same with the WebSockets protocol 
but the problem that 
after the visitor refresh the page or leaves the website  immediately
the WebSocket connection will be closed and the  unavailable presence  will be sent
and the agents will receive that the visitor left the website immediately not after a  timeout like 40 sec

we need to implement the behaviour of `mod_bosh` with WebSockets also 
we need to tell Ejabberd:- 
```please wait 40 sec after the connection is closed and then send the unavailable presence of the visitor node 
```
to keep our business logic the same.

**Comment by weiss** [comment]
> we tell the agents that the visitor has left the website after 40 sec *if the visitor didn't come back to the site*

So the reason you want the server to wait before sending unavailable presence is to give the client a chance to reconnect.  That's precisely what @licaon-kter suggested above, and the reason he pointed you to [XEP-0198][1], which [does just that][2].  ejabberd [supports that extension][3], and [so do][4] web clients such as Converse.js.  (BOSH has such a functionality built-in; but WebSocket hasn't, as that's not an XMPP-specific technology.)

[1]: https://xmpp.org/extensions/xep-0198.html
[2]: https://xmpp.org/extensions/xep-0198.html#resumption
[3]: https://docs.ejabberd.im/admin/configuration/modules/#mod-stream-mgmt
[4]: https://conversejs.org/docs/html/configuration.html#enable-smacks

**Comment by MostafaSalama** [comment]
> > we tell the agents that the visitor has left the website after 40 sec _if the visitor didn't come back to the site_
> 
> So the reason you want the server to wait before sending unavailable presence is to give the client a chance to reconnect. That's precisely what @licaon-kter suggested above, and the reason he pointed you to [XEP-0198](https://xmpp.org/extensions/xep-0198.html), which [does just that](https://xmpp.org/extensions/xep-0198.html#resumption). ejabberd [supports that extension](https://docs.ejabberd.im/admin/configuration/modules/#mod-stream-mgmt), and [so do](https://conversejs.org/docs/html/configuration.html#enable-smacks) web clients such as Converse.js. (BOSH has such a functionality built-in; but WebSocket hasn't, as that's not an XMPP-specific technology.)

so I can't do that with `WebSockets` I can only do it with BOSH?

**Comment by weiss** [comment]
> I can only do it with BOSH?

Or with [XEP-0198][1].

[1]: https://xmpp.org/extensions/xep-0198.html

**Comment by webtoucher** [comment]
Guys, one more case. I am using XEP-0198. The user closes the page, ejabberd waits for the session to resume and then closes the session with a timeout error. But other users in the room will not be aware of the unavailability until they send a message. Why?

**Comment by licaon-kter** [comment]
@webtoucher which client? What type of room?

**Comment by webtoucher** [comment]
@licaon-kter, client @xmpp/client. What do you mean about type?
I see in websocket messages list that ejabberd sends unavailable presence only after one of room occupants sends a message

**Comment by weiss** [comment]
> I see in websocket messages list that ejabberd sends unavailable presence only after one of room occupants sends a message

That's not the expected behavior.  Maybe enable `[debug]` logging (`ejabberdctl set-loglevel debug`) and watch the traffic in the `ejabberd.log` file.

**Comment by weiss** [comment]
> That's not the expected behavior.

Unless your client enabled [XEP-0352: Client State Indication][1].  In that case the behavior would be expected.

[1]: https://xmpp.org/extensions/xep-0352.html
