### ISSUE TITLE
Failed when start using systemd: /etc/rc.d/init.d/ejabberd: line 39: /usr/bin/su: Permission denied

### ISSUE THREAD

**Issue by riupie** [processone/ejabberd#3643]
## Environment

- ejabberd version: 17.11
- Erlang version: `erl +V`
- OS: Linux (Centos 8)
- Installed from: official deb/rpm

## Bug description

Fresh install using RPM package. When I want to start ejabberd using systemd using `sudo systemctl start ejabberd` it failed.
I get this error:
`/etc/rc.d/init.d/ejabberd: line 39: /usr/bin/su: Permission denied`

Maybe need some fix? But how?

**Comment by licaon-kter** [comment]
That's >3.5 years old, can you use a newer version though?

**Comment by riupie** [comment]
> That's >3.5 years old, can you use a newer version though?

I hope so, but it was  used by  our prehistoric apps 😅. Btw, I've been resolved this issue after running it on systemd.
