### ISSUE TITLE
Sm cache shrinks happen a lot

### ISSUE THREAD

**Issue by Freyskeyd** [processone/ejabberd#3645]
## Environment

- ejabberd version: 21.04
- Erlang version: `Erlang/OTP 21 [erts-10.3] - Elixir 1.10.4`
- OS: Linux Debian
- Installed from: source

## Configuration (only if needed):

```yaml
sm_cache_size: 40000
```

## Errors from error.log/crash.log

```
Shrinking cache 'sm_cache' (current size = 40001, max size = 40000, life time = 3600000, memory = 9525632 bytes); you should increase maximum cache size if this message repeats too often
```

## Bug description

As described in the documentation `sm_cache_size` should be defined to the maximum amount of connected users at the same time. However, my cluster have a maximum of 20k users connected at the same time, but this log appears anyway. I tried to understand how the cache was calculating his size and it appears that when a session is closed, the cache entry isn't deleted. 
Is it a desired behaviour?
Should this kind of entry deleted when TTL expire?

After some tests, I define the `sm_cache_life_time: 10`.
I connected a session, we see the relative entry in the ets, after disconnection the ets hold an `error` and after 15sec the ets still hold this value. (The cache is clear after sometimes but no 10 sec as expected)

```
iex(1)> {"time":"2021-07-19T10:33:48.490Z","severity":"info","message":"(<0.1229.0>) Accepted connection 127.0.0.1:60755 -> 127.0.0.1:5222","metadata":{"node":"nonode@nohost"}}
{"time":"2021-07-19T10:33:48.535Z","severity":"info","message":"(tcp|<0.1229.0>) Accepted c2s PLAIN authentication for admin@localhost by sql backend from 127.0.0.1","metadata":{"node":"nonode@nohost"}}
{"time":"2021-07-19T10:33:48.555Z","severity":"info","message":"(tcp|<0.1229.0>) Opened c2s session for admin@localhost/profanity.pV6u","metadata":{"node":"nonode@nohost"}}
iex(1)> :ets.lookup(:sm_cache, {"admin", "localhost"})
[
  {{"admin", "localhost"},
   {:ok,
    [
      {:session, {{1626, 683628, 5}, #PID<0.1229.0>},
       {"admin", "localhost", "profanity.pV6u"}, {"admin", "localhost"}, 0,
       [
         ip: {{127, 0, 0, 1}, 60755},
         conn: :c2s,
         auth_module: :ejabberd_auth_sql
       ]}
    ]}, 1626683628590}
]
iex(2)> {"time":"2021-07-19T10:34:07.257Z","severity":"info","message":"(tcp|<0.1229.0>) Closing c2s session for admin@localhost/profanity.pV6u: Stream reset by peer","metadata":{"node":"nonode@nohost"}}
iex(2)> :ets.lookup(:sm_cache, {"admin", "localhost"})
[{{"admin", "localhost"}, :error, 1626683647273}]
iex(3)> :ets.lookup(:sm_cache, {"admin", "localhost"})
[{{"admin", "localhost"}, :error, 1626683647273}]

```

**Comment by prefiks** [comment]
This may happen when clients setup session resume using stream management protocol, in that case i think we could store some information in that cache about sessions that expire without any attempt to restore them (we keep some extra information in that, used to construct error message if client eventually tries to resume expired session). So it's possible to get to that state, and if that's a problem for you, it probably should be possibly to tweak`sm_cache_life_time` to value that would expire old entries without hitting cache limits - but that would mostly depend on how often sessions are recycled.

**Comment by Freyskeyd** [comment]
In my cases I've a huge amount of people that connect but stay for 10minutes before disconnecting for life. So I should increase the `sm_cache_size` and the `sm_cache_life_time` ?

However, why does expired sessions doesn't get removed when the ttl hit the clock?

**Comment by prefiks** [comment]
You should decrease `sm_cache_life_time`, so expired sessions are cleared earlier from cache.
