### ISSUE TITLE
Date ISO format

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3648]
It is possible to use the date ISO format?
- https://www.w3.org/QA/Tips/iso-date

`YYYY-MM-DD`

**Comment by badlop** [comment]
Where?

**Comment by Neustradamus** [comment]
@badlop: Sorry for the delay!

Linked to: https://github.com/docbook/xslt10-stylesheets/issues/236

Can you change it in P1 projects?

**Comment by Neustradamus** [comment]
@badlop: Have you seen my previous comment?

**Comment by Neustradamus** [comment]
@badlop: Do not forget my answer to solve it.

**Comment by Neustradamus** [comment]
@processone team, @badlop: More 2 years after, in 2023, this ticket is always here.

**Comment by Neustradamus** [comment]
@processone team, @badlop: More 2 years after, in 2023, this ticket is always here.

`<l:context name="datetime"><l:template name="format" text="m/d/Y"/>`
to
`<l:context name="datetime"><l:template name="format" text="Y-m-d"/>`

Source:
- https://doccookbook.sourceforge.net/html/en/dbc.common.dbtimestamp.html
- http://www.sagehill.net/docbookxsl/Datetime.html
- https://lists.oasis-open.org/archives/docbook/201004/msg00033.html
- https://lists.oasis-open.org/archives/docbook/201004/msg00036.html
