### ISSUE TITLE
SIP issue connect and call no audio

### ISSUE THREAD

**Issue by phongnh8792** [processone/ejabberd#3671]
Ejabberd version: 21.01
OS: Windows
Docker - ejabberd/ecs

SIP issue when I will use client app login by sip connection tls and udp it show log for me
![image](https://user-images.githubusercontent.com/89837256/131484198-f3115bc4-6b4d-40ba-a738-59c9bf28e323.png)
only TCP can connected but when voice/video call it no audio
update: I used client Linphone & WengoPhone & Zoiper
 got some strange connection from a France IP, it has user-agent Avaya. don't know why  have this connection because  didn't request it
![image](https://user-images.githubusercontent.com/89837256/131490384-873d0ea5-012d-4da3-a00e-40a5381d39ca.png)
Update My Config
listen port
```
-
    port: 5060
    transport: udp
    module: ejabberd_sip
  -
    port: 5060
    module: ejabberd_sip
  -
    port: 5061
    module: ejabberd_sip
    tls: true
    certfile: /home/ejabberd/conf/cert2.pem
```
module config
```
mod_sip:
    always_record_route: false
    record_route: "sip:delivereetech.com;lr"
    routes:
      - "sip:myaddress.com;lr"
    flow_timeout_udp: 30 sec
    flow_timeout_tcp: 1 min
    via:
      -
        type: tls
        host: "myaddress.com"
        port: 5061
      -
        type: tcp
        host: "myaddress.com"
        port: 5060
      -
        type: udp
        host: "myaddress.com"
        port: 5060
```
Log
```
2021-09-01 08:47:52.244321+00:00 [info] (<0.722.0>) Accepted connection 171.250.162.105:40802 -> 172.17.0.3:5061
2021-09-01 08:47:52.246721+00:00 [debug] SIP [tls/in] 171.250.162.105:40802 -> 172.17.0.3:5061:

2021-09-01 08:47:52.415835+00:00 [info] (<0.723.0>) Accepted connection 171.250.162.105:10454 -> 172.17.0.3:5061
2021-09-01 08:47:52.441109+00:00 [debug] SIP [tls/in] 171.250.162.105:10454 -> 172.17.0.3:5061:

2021-09-01 08:47:56.402733+00:00 [info] (<0.724.0>) Accepted connection 172.31.13.218:59087 -> 172.17.0.3:5061
2021-09-01 08:47:56.410545+00:00 [debug] SIP [tls/in] 172.31.13.218:59087 -> 172.17.0.3:5061:
```
when use UDP to login it show in progress long time until no response

**Comment by licaon-kter** [comment]
Which client? Tried Linphone too?

**Comment by phongnh8792** [comment]
yep i tried in Linphone

**Comment by phongnh8792** [comment]
> Which client? Tried Linphone too?

I used client Linphone & WengoPhone & zoiper it same issue

**Comment by phongnh8792** [comment]
@licaon-kter can you help me :(

**Comment by licaon-kter** [comment]
Regarding the rogue connections to 5060/5061, it will happen a lot, as with STUN servers too, random internet users try to hop on your service. But they can't do much since you use user/passwords, right?

**Comment by phongnh8792** [comment]
> Regarding the rogue connections to 5060/5061, it will happen a lot, as with STUN servers too, random internet users try to hop on your service. But they can't do much since you use user/passwords, right?

yep @licaon-kter li
