### ISSUE TITLE
TCP accept: too many open files

### ISSUE THREAD

**Issue by gerhardVDW1983** [processone/ejabberd#3672]
## Environment

- ejabberd version: 18.01
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1
- OS: Debian GNU/Linux 9 (stretch)
- Installed from: official binary installer 

## Errors from error.log/crash.log

2021-09-07 08:27:52.092 [error] <0.353.0>@ejabberd_listener:accept:311 (#Port<0.19757>) Failed TCP accept: too many open files
2021-09-07 08:27:52.092 [error] <0.353.0>@ejabberd_listener:accept:311 (#Port<0.19757>) Failed TCP accept: too many open files
2021-09-07 08:27:52.092 [error] <0.353.0>@ejabberd_listener:accept:311 (#Port<0.19757>) Failed TCP accept: too many open files

## Bug description

ejabberd is crashing

**Comment by licaon-kter** [comment]
A 4 years old version? Wow... Any chance to update a bit? 

Looks like a TCP sockets issue, see ulimits iirc

**Comment by gerhardVDW1983** [comment]
I checked on how to do an update on ejabberd, not able to find a clear guide, any guide or steps available to update ejabberd?

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im has an upgrade section

**Comment by gerhardVDW1983** [comment]
Thanx, I came across https://docs.ejabberd.im/admin/upgrade/

It mentions an upgrade note, where do I find that?

Thanx for your help so far.

**Comment by licaon-kter** [comment]
Scroll down for each upgrade note, start at 18.01 to .03, see if it applies etc.

Remember to have backups, of course ;)

**Comment by gerhardVDW1983** [comment]
okey, think I am getting it now, so best will be to do incremental updates, not one bog upgrade to latest version.

**Comment by prefiks** [comment]
You probably getting this error because of small limit of allowed handles that ejabberd process is allowed to use. You can check what number OS allows ejabberd to use by checkiing `/proc/$PID/limit` where $PID you can find with `ps -A |grep beam`. You can increase limits in  /etc/security/limits.conf file

**Comment by weiss** [comment]
> best will be to do incremental updates, not one bog upgrade to latest version.

Assuming you're using SQL storage, you should apply the schema changes mentioned for the releases leading up to the current one.  But there's no need to install the intermediate releases.

> You can increase limits in /etc/security/limits.conf file

Right, or [in the unit file][1], if ejabberd is started by systemd (e.g., by calling `systemctl edit ejabberd`).

[1]: https://github.com/processone/ejabberd/blob/21.07/ejabberd.service.template#L9
