### ISSUE TITLE
mod_muc's access_{create,mam,persistent} documentation for 21.01 is wrong

### ISSUE THREAD

**Issue by dseomn** [processone/ejabberd#3675]
## Environment

- ejabberd version: 21.01
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 11.1.8`
- OS: Debian GNU/Linux 11 (bullseye)
- Installed from: distro package

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

https://github.com/dseomn/system-configs/blob/6e2c8c19a7f205028a58cc1ece9d491d64fe3d5b/salt/file/xmpp/ejabberd.yml.jinja#L81-L85

## Errors from error.log/crash.log

No errors

## Bug description

For access_create, https://docs.ejabberd.im/archive/21_01/modules/#mod-muc says:
> By default any account in the local ejabberd server is allowed to create rooms.

I left that option out, and somebody on a different server was able to create a room. Setting it to this access rule fixed that: https://github.com/dseomn/system-configs/blob/6e2c8c19a7f205028a58cc1ece9d491d64fe3d5b/salt/file/xmpp/ejabberd.yml.jinja#L27-L29

**Comment by dseomn** [comment]
Comparing https://docs.ejabberd.im/archive/21_01/modules/#mod-muc to [what I think are the defaults in the code](https://github.com/processone/ejabberd/blob/fca41796c035897b38695a4eb8a004675977835b/src/mod_muc.erl#L1235-L1292), it looks like these settings have defaults that don't match the documentation:
* access_create
* access_mam
* access_persistent

**Comment by badlop** [comment]
Thanks for reporting!

The source code says in mod_muc.erl
```yaml
{access_create, all},
```

But the example configuration file provided with the ejabberd source code package (which may be customized later when packaged for the ProcessOne binary installers, and in other operating system packages) says:
```yaml
modules:
  mod_muc:
    access_create: muc_create

access_rules:
  muc_create:
    allow: local
```

As you noticed, the option documentation says

>   By default any account in the local ejabberd server is allowed to create rooms.


So, the option documentation is not describing the option implementation, but the example configuration file.

In addition to those three, I'll check all the other options, in all modules and top-level options, just in case there are more confusions like this.
