### ISSUE TITLE
MUC doesn't handle well big load (error on get_room_occupants_number)

### ISSUE THREAD

**Issue by dancosta93** [processone/ejabberd#3684]
## Environment

- ejabberd version: 21.7.0
- Installed from: docker hub (ejabberd/ecs)

## Errors from error.log/crash.log

`2021-09-22 23:13:40.247905+00:00 [error] <0.20783.2>@mod_http_api:handle/4:258 REST API Error: get_room_occupants_number([{<<"name">>,<<"global-test14">>},
                                           {<<"service">>,
                                            <<"conference.rushchat">>}]) -> error:{badmatch,
                                                                                   {error,
                                                                                    timeout}} [{mod_muc_admin,
                                                                                                get_room_state,
                                                                                                1,
                                                                                                [{file,
                                                                                                  "src/mod_muc_admin.erl"},
                                                                                                 {line,
                                                                                                  895}]},
                                                                                               {mod_muc_admin,
                                                                                                get_room_occupants_number,
                                                                                                2,
                                                                                                [{file,
                                                                                                  "src/mod_muc_admin.erl"},
                                                                                                 {line,
                                                                                                  1018}]},
                                                                                               {mod_http_api,
                                                                                                handle2,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "src/mod_http_api.erl"},
                                                                                                 {line,
                                                                                                  268}]},
                                                                                               {mod_http_api,
                                                                                                handle,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "src/mod_http_api.erl"},
                                                                                                 {line,
                                                                                                  229}]},
                                                                                               {mod_http_api,
                                                                                                perform_call,
                                                                                                4,
                                                                                                [{file,
                                                                                                  "src/mod_http_api.erl"},
                                                                                                 {line,
                                                                                                  189}]},
                                                                                               {mod_http_api,
                                                                                                process,
                                                                                                2,
                                                                                                [{file,
                                                                                                  "src/mod_http_api.erl"},
                                                                                                 {line,
                                                                                                  142}]},
                                                                                               {ejabberd_http,
                                                                                                process,
                                                                                                2,
                                                                                                [{file,
                                                                                                  "src/ejabberd_http.erl"},
                                                                                                 {line,
                                                                                                  373}]},
                                                                                               {ejabberd_http,
                                                                                                process_request,
                                                                                                1,
                                                                                                [{file,
                                                                                                  "src/ejabberd_http.erl"},
                                                                                                 {line,
                                                                                                  496}]}]`

## Bug description

I found this old post https://github.com/processone/ejabberd/issues/1964, was this ever optimized? Looking at the code it looks like it's still sends a message with the whole room instead of just getting the count of users.

I am testing with 2000+ users in a room and all the room apis fail with that. The error above happens when calling get_room_occupants_number API. The Multi-User Chat page in the admin dashboard also fails to load when there is this load.

**Comment by badlop** [comment]
> I am testing with 2000+ users in a room

Do you really want 2.000 persons in a room, all of them sharing their presence and chatting? If you don't really have multiple users chatting, then maybe "Multi-User Chat" is not the tool for your task.

If you only have one, or a few chatting, and the other 2000 reading, try MucSub or PubSub

If you don't care about the users presence, and only care about the messages, try MucSub or PubSub.

https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/

**Comment by weiss** [comment]
> If you don't care about the users presence, and only care about the messages

In this case, you could also disable presence delivery in the room configuration ("roles for which presence is broadcasted").  This might help quite a bit already.

**Comment by dancosta93** [comment]
These are good points but the error is on the get_room_occupants_number API. I disabled the presence broadcast already but from the admin side I still wanted to get the occupants (using the API) and I can't get the list or the number.

But I got curious about what you said, my use case is not like Whatsapp or something like that, that the users wouldn't even have the app open.

It is a lobby in which the users are actively using the website (so I'm expecting huge rooms), but it's true that a good part of them would be just spectators. What do you suggest to optimize this use case?
