### ISSUE TITLE
15 year old documentation - Clients

### ISSUE THREAD

**Issue by ShalokShalom** [processone/ejabberd#3694]
Considering this list is 15 years old, somebody might like to update it - or take it down.

https://www.ejabberd.im/client-suggestions/index.html

**Comment by badlop** [comment]
Did you read the disclaimer, with yellow background, that redirects the reader to check the updated documentation?

**Comment by badlop** [comment]
> So could we remove these links from the search engines?

How can that be done?

Anyway, that post also has a date: 2005.

**Comment by ShalokShalom** [comment]
https://www.google.com/search?q=remove%20url%20search%20engine&ie=utf-8&oe=utf-8&client=firefox-b-m
