### ISSUE TITLE
Support OpenSSL 3

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#3697]
[OpenSSL](https://www.openssl.org/) 3 has been released ([RC announcement](https://www.openssl.org/blog/blog/2021/06/17/OpenSSL3.0ReleaseCandidate/)) and will eventually be available in operating systems (see [Debian experimental](https://tracker.debian.org/pkg/openssl)).

List of problem reports when updating to OpenSSL 3:
* In Erlang/OTP bug tracker: [openssl 3.0.0 compatible erlang version](https://github.com/erlang/otp/issues/4577)
* In debian's fast_tls package bug tracker: [erlang-p1-tls: FTBFS with OpenSSL 3.0](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996274)

Current state in Erlang (as explained in [this comment](https://github.com/erlang/otp/issues/4577#issuecomment-790576501)):
> support for OpenSSL 3.0 API is planned, but not before OTP-25.0.

The current solution is simple: continue using OpenSSL 1 until Erlang/OTP 25

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by mremond** [comment]
We do not rely on Erlang OpenSSL support. Probably, we should be able to adapt processone/fast_tls to use openSSL 3.

**Comment by badlop** [comment]
fast_tls got OpenSSL 3 support in version 1.1.14, see https://github.com/processone/fast_tls/pull/56
