### ISSUE TITLE
xep_0045 muc, user go offline will also leave the room, even if the user has been the room member.

### ISSUE THREAD

**Issue by hackrole** [processone/ejabberd#370]
I would to build a gourpchat app. I use the muc. but I found what I really need is the group-chat, not a room-chat. 
the user will always leave the room then go-offline, even I set it the the room-member.
and when the user go-online again, it not goto the same room auto.

does that any solution or hooks for this?

**Comment by hensem** [comment]
If user leave before going online, of course they will not rejoin. They already left the group chat. Try to go offline while still in the group chat. User will auto join when they go online.

**Comment by shyaken** [comment]
I'm having the same problem, User still in room when go offline, just some minutes after that, he will auto leave room chat. I don't know how to keep user in room roster when they go offline. Anybody know to do this?

**Comment by hackrole** [comment]
there seems to be no ways but to modify the ejabberd source-code. and implement the group by yourself.

**Comment by hensem** [comment]
Isn't that the "nature" of XMPP?

By the way, in my case, the user will auto join the room when they become
online. Don't really know if the client or ejabberd itself handle the auto
join thing.

**Comment by mremond** [comment]
Yes, that's by design in the current version of the XMPP MUC specification.

**Comment by hackrole** [comment]
@hensem  the auto-join may be described in the xep-0048. http://xmpp.org/extensions/xep-0048.html.
but it does not change the chat-room(xep_0045) to chat-group. when the use go offline, not only he will leave the room, but also he would miss all the message during the whole offline-time.

at last, Is there any xep about group-chat  now?

**Comment by hensem** [comment]
This is my experienced. I don't know if anybody got this too: after I
offline about 2 minutes and come back online, I'll auto join the room and
get flooded with messages that was in the room while I'm offline. I never
offline longer than around 2 minutes though, so not sure if this "offline"
messages is part of the design or maybe it was buffered somewhere and get
delivered after I'm online.

Later if I'm free I will try to stay offline longer and see if I'll get the
"offline" messages. Will update later.

**Comment by mremond** [comment]
Yes, this is by design.
There is a default history when you join MUC Room. It can be set to 0 when you enter the room.

**Comment by devendrawebdeveloper** [comment]
Hello All,

We are facing same issue?Can you please help us ?the users are always leave the room when will go-offline, even they joined room.

**Comment by weiss** [comment]
If you're building a custom solution, you could look at [MUC/Sub][1], for example.

[1]: https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/

**Comment by vincentwlau** [comment]
I don't use ejabberd, but use openfire.  I implemented chat-group using pubsub and it worked very well.  The owner created a persistent node, let participants subscribe to it and publish items to it. The major work was to add device management and integrate APNS/GCM in openfire to notify the offline mobile subscribers.

**Comment by mremond** [comment]
@vincentwlau One of the drawback of this approach is that you cannot mix client supporting MUC with client supporting your own specification for groupchat. That's the main benefit of MubSub. Both clients can participate in the same group discussion. It aims  to be very close to the XMPP standards, not to roll out a brand new way of doing groupchat.
