### ISSUE TITLE
MSSQL new SQL schema is missing

### ISSUE THREAD

**Issue by karimhm** [processone/ejabberd#3702]
The [ejabberd/sql/](https://github.com/processone/ejabberd/tree/master/sql) directory contains `*.new.sql` file for each database supported except for MSSQL where the new SQL schema file (`mssql.new.sql`) is missing.

`pg.new.sql` file did appear first with release [17.11](https://github.com/processone/ejabberd/tree/17.11/sql)
`mysql.new.sql` and `lite.new.sql` file did appear first with release [17.12](https://github.com/processone/ejabberd/tree/17.12/sql).

**Comment by badlop** [comment]
Right. The MS SQL is not much used, and apparently nobody cared about this.

As you may have noticed, the only substantial difference between default and new schemas are the addition of `server_host` column in each table that has a `username` column. Then of course primary keys, indexes, ... are updated accordingly.

So, if you want to give it a try and implement it, in theory it shouldn't be hard. That's _in theory_.

**Comment by wahur666** [comment]
I use MSSQL as the database, and this issue was solved for me by the bellow thicket, for version 21.04.

https://github.com/processone/ejabberd/issues/3097
