### ISSUE TITLE
mod_register does not create new user and restart of ejabberd crashed

### ISSUE THREAD

**Issue by GentleRV** [processone/ejabberd#3706]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 21.07
- Erlang version: `erl +V`
- OS: Linux (Ubuntu)
- Installed from: source | distro package | official deb/rpm | official binary installer | other
- .deb package 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)

adding under port 5223 
-module mod_register
restart ejabberd: sudo systemsctl restart ejabberd.service 

give restart failed. 
remove module mod_register
ejabberd will work

what is expected that a user will be created in the provided domain using spark as client
this user is not created.

**Comment by licaon-kter** [comment]
https://docs.ejabberd.im describes where to setup mod_register, and it's not under port settings.

**Comment by GentleRV** [comment]
This i read and tried to implement. The few examples i see are backdated to
v2.1.1 and are many years old. Up to date configuration settings with
examples are missing. Also when changed a setting in the ejabberd.yml file
result in undocumented errors after exit with a code during a restart.

**Comment by licaon-kter** [comment]
Please start with the default .yml: https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

Verify if it works... then adapt to your needs.
