### ISSUE TITLE
Strictly allow only a single device to register for Axolotl/OMEMO

### ISSUE THREAD

**Issue by orlyjamie** [processone/ejabberd#3709]
I have a specific functionality I would like to achieve regarding axolotl.

Basically I want to run my Android client in a single device mode when it comes to OMEMO meaning that on the backend server (ejabberd) I want to only allow a single device to be registered in the device list so if a second, third, fourth or any other subsequent device tries to register for the device list it will not be accepted.

Is anyone interested to help me look into this or know anyone who would be interested? (Will pay for time)

For example:

```
<items node="eu.siacs.conversations.axolotl.devicelist">
	<item id="current">
	<list xmlns="eu.siacs.conversations.axolotl">
	<device id="174235744"/>
	<device id="71071234"/>                      <-------------------------- DO NOT ALLOW                      
	<device id="22318128"/>                      <-------------------------- DO NOT ALLOW
	</list>
	</item>
</items>
```

**Comment by weiss** [comment]
What's the use case?  If it is in any way security-related, it sounds wrong to have an E2EE mechanism rely on the server for that, no?

**Comment by orlyjamie** [comment]
Good question, please let me elaborate ~ 

So basically there is a client-side way to resolve this but its a little more complex and doesn't necessarily fit my use-case (for example MFA when users wish to add/trust additional devices such as the case with Signal)

**Background**

I'm working on an XMPP client (kiosk based) that has a set of controls both client side and server side (API) that currently allow users to register using a one-time activation code. 

Once this code is accepted by the API a set of XMPP credentials will be returned and when the user eventually communicates with an OMEMO supported device the client will do its usual thing and complete the axolotl/OMEMO process. 

Given the pretence, users in this group would never be authenticating to the server from additional devices using the same credentials - this is because the credentials are never known to the user (they are received by the API response and stored in secure storage on-device). 

Now as the device/client-side has a one-time activation API call on app install/activation, there is no trusted scenario in which the originally registered device would regenerate a new device ID for that specific user (such as app reinstall or data cache clearing) which in turn means that there is no way a single user should be registering a new device ID - hence my intentions of handling this server-side. 

The only case would be in that where a user has extracted their XMPP creds and authenticated directly OR someone has obtained the credentials through other means. 

I know its an edge case but its my case so if you have any ideas on how to enforce new devices being added to the device list `eu.siacs.conversations.axolotl.devicelist` please do share your thoughts.

**Comment by licaon-kter** [comment]
Why not PGP then?

**Comment by orlyjamie** [comment]
That's easy. Multi-User/device comms.

**Comment by weiss** [comment]
> there is no trusted scenario in which the originally registered device would regenerate a new device ID for that specific user (such as app reinstall or data cache clearing) which in turn means that there is no way a single user should be registering a new device ID

Even in such an environment, there's probably no gain in having the server prevent additional devicelist entries, as an attacker could attempt to initiate new OMEMO sessions without adding his device to the list.
