### ISSUE TITLE
archiving + file tranfer support for ejabberd 14.07

### ISSUE THREAD

**Issue by jayeshjain24** [processone/ejabberd#371]
Since this is the latest release from ejabberd,the documentaion specifically related to ejabberd 14.07 is minimal.
I want to know are there any modules for archiving chat history and dealing with file transfer(audio/video/images)??.
The problem is all other versions of ejabberd are obsolete and the newest version does not support old odbc/mod_archive2 modules.So do I need to write my own custom modules for storing chats and transfering file or is it the other way?

I want to develop a chat sysytem but I am noob at erlang.

**Comment by mremond** [comment]
I am not sure what you plan to do regarding file transfer. File transfer in XMPP are generally out of band: XMPP is used for negotiation / signaling but the file itself is transferred client to client or through a proxy.

Moreover, you mention about logging muc room. There is a module for that included in ejabberd: mod_muc_log.erl
