### ISSUE TITLE
21.07: pgsql_proto can't authenticate, then crashes

### ISSUE THREAD

**Issue by scottcc** [processone/ejabberd#3715]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 21.07
- Erlang version: `erl +V` --> `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 12.1.5`
- OS: OSX `sw_vers`:

- Installed from: homebrew: 
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1519
```
## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: debug
...
host_config:
  "some-host.binnj.com":
    sql_type: pgsql
    sql_server: "localhost"
    sql_database: "ejabberd"
    sql_username: "ejabberd"
    sql_password: "this-is-not-the-password"
    acl:
      admin:
        user:
          - "someuser@some-host.binnj.com"
```

## Errors from error.log/crash.log

```
2021-11-20 13:51:37.514884+00:00 [warning] <0.470.0>@ejabberd_sql:handle_reconnect/2:472 pgsql connection failed:
** Reason: {authentication,{unknown,10}}
** Retry after: 30 seconds
2021-11-20 13:51:37.515922+00:00 [warning] <0.474.0>@ejabberd_sql:handle_reconnect/2:472 pgsql connection failed:
** Reason: {authentication,{unknown,10}}
** Retry after: 30 seconds
2021-11-20 13:51:37.509663+00:00 [error] <0.521.0>@proc_lib:crash_report/4:508 CRASH REPORT:
  crasher:
    initial call: pgsql_proto:init/1
    pid: <0.521.0>
    registered_name: []
    exception exit: {authentication,{unknown,10}}
      in function  gen_server:init_it/6 (gen_server.erl, line 358)
    ancestors: ['ejabberd_sql_some-host.binnj.com_37',
                  'ejabberd_sql_sup_some-host.binnj.com',ejabberd_db_sup,
                  ejabberd_sup,<0.115.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.65>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1984
  neighbours:
```

## Bug description

This is an OSX distribution from homebrew - it was upgraded using `brew upgrade ejabberd` from a prior 20.07_1 version (which was fine), and brew shows:

```
someuser@some-host ~ % brew info ejabberd
ejabberd: stable 21.07 (bottled), HEAD
XMPP application server
https://www.ejabberd.im
Conflicts with:
  couchdb (because both install `jiffy` lib)
/usr/local/Cellar/ejabberd/HEAD-8694517 (783 files, 14.4MB)
  Built from source on 2020-04-09 at 19:25:32
/usr/local/Cellar/ejabberd/21.07 (814 files, 15.6MB) *
  Poured from bottle on 2021-11-20 at 12:47:29
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ejabberd.rb
License: GPL-2.0-only
==> Dependencies
Required: erlang@22 ✔, gd ✔, libyaml ✔, openssl@1.1 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
If you face nodedown problems, concat your machine name to:
  /private/etc/hosts
after 'localhost'.

To start ejabberd now and restart at login:
  brew services start ejabberd
Or, if you don't want/need a background service you can just run:
  /usr/local/sbin/ejabberdctl start
==> Analytics
install: 100 (30 days), 303 (90 days), 1,337 (365 days)
install-on-request: 100 (30 days), 303 (90 days), 1,337 (365 days)
build-error: 0 (30 days)
```

I have checked the user/password and port by copying/pasting exactly what is in ejabberd.yml and am certain the password and permissions are fine:

```
someuser@some-host % psql -h localhost -p 5432 -U ejabberd ejabberd
Password for user ejabberd:
psql (14.1)
Type "help" for help.

ejabberd=> \dt;
                   List of relations
 Schema |          Name           | Type  |   Owner
--------+-------------------------+-------+------------
 public | archive                 | table | ejabberd
 public | archive_prefs           | table | ejabberd
 public | bosh                    | table | ejabberd
 public | caps_features           | table | ejabberd
 public | last                    | table | ejabberd
 public | mix_channel             | table | ejabberd
 public | mix_pam                 | table | ejabberd
 public | mix_participant         | table | ejabberd
 public | mix_subscription        | table | ejabberd
 public | motd                    | table | ejabberd
 public | mqtt_pub                | table | ejabberd
```

Is there any way to get more information about why the `pgsql` connection is not working?

**Comment by licaon-kter** [comment]
Postgresql log does not give any info? Postgresql was not changed/updated?

**Comment by scottcc** [comment]
Postgres *was* upgraded - automatically somehow with the result of `brew update` - it went from 12 -> 14.1. Regardless, I have checked and rechecked using `psql` as stated above. Also, there are zero errors in postgres logs... is there any chance the postgres libraries being used by ejabberd are pre-compiled in some way? I have tried doing `brew reinstall`, but maybe I should remove it entirely?

**Comment by licaon-kter** [comment]
The postgres upgrade did dump and restore the actual DB data?

**Comment by badlop** [comment]
> Postgres was upgraded - automatically somehow with the result of brew update - it went from 12 -> 14.1

> exception exit: {authentication,{unknown,10}}

Check https://github.com/processone/ejabberd/issues/3691

**Comment by scottcc** [comment]
> The postgres upgrade did dump and restore the actual DB data?

I actually had to `brew install postgres@12`, manually `pg_dump` it, then `pg_restore` it with 14.1 (which was fine, not uncommon to be doing those).

**Comment by scottcc** [comment]
> > Postgres was upgraded - automatically somehow with the result of brew update - it went from 12 -> 14.1
> 
> > exception exit: {authentication,{unknown,10}}
> 
> Check #3691

WOW - this is VERY interesting! I'll try that out (thanks!) and report back here.

**Comment by scottcc** [comment]
Have confirmed, changing `postgresql.conf` setting such that `password_encryption = md5` (and then resetting the password again) allows ejabberd 21.07 to start up with no issue. Thanks again, closing ticket!
