### ISSUE TITLE
Images missing from docs

### ISSUE THREAD

**Issue by ari** [processone/ejabberd#3720]
On this page: https://docs.ejabberd.im/admin/configuration/ldap/#shared-roster-in-ldap

All the images are missing. For the LDAP roster config, those pictures are essential to understanding what is happening. Instead we just see text like:

    For example in a layout shown in figure [fig:msrl-dit-flat], the group of each user is stored in its ou attribute.

**Comment by badlop** [comment]
Right! The documentation was moved from ejabberd git reporistory to https://github.com/processone/docs.ejabberd.im but it seems those images were not copied, and they were eventually removed here in https://github.com/processone/ejabberd/commit/1854b5e411445beeece621a4058941ba0266704d

I've copied them, thanks for reporting!

**Comment by badlop** [comment]
Once you take a look, if something is still missing please comment. If it looks correct, please close this issue.

**Comment by ari** [comment]
Looks good. That ldap module is still incredibly confusing and I can't make it work despite having worked with LDAP for over a decade, but at least it has pictures now :-)
