### ISSUE TITLE
Huge amount of logs dumped regularly in eJabberd during a particular period

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3721]
## Environment

- ejabberd version: 20.04
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 9.2
- OS: Linux (Debian)
- Installed from: source 

loglevel: 4

No errors

## Bug description

We are running ejabberd in our production with 3 node cluster. We started analysing the ejabberd logs by counting ejabberd_listener.accept events. The number of connect events varies between 10K to 20K every hour throughout the day. A sample log line used is given below:

2021-12-06 10:39:29.734 [info] <0.315.0>@ejabberd_listener:accept : 239 (<0.6761.3040>) Accepted proxied connection [::ffff:157.31.24.18]:48130 -> [::ffff:10.xxx.xxx.xxx]:5222

However we started observing that every day between 6:25 AM and 6:35 AM, an astounding amount of user connect events (info) are dumped into the log files (around 5M connect events). This is recurring every single day at the exact same time interval and we have confirmed that these were not real connects, as the the HAproxy used for load balancing eJabberd instances did not saw any increase in TCP connects. On analysing some of the connect events, we found that those connects (jid/ip address) happened during the previous day.

Any idea why this is happening?

**Comment by licaon-kter** [comment]
Is that jid valid? Is that IP connecting during the other hours? Is it connecting or just trying?

**Comment by logicwonder** [comment]
JID and IP are valid also valid since the record can traced back to an old connect record which was genuinely already logged few hours back.

**Comment by licaon-kter** [comment]
Maybe their client and.or network has issues?! Contact that JID and ask them :)

**Comment by logicwonder** [comment]
I am not talking about one or two user's connect log, I got the connect logs from over 50K users replayed during this 10 min window with distinct IP addresses. This is a weird issue as it is impossible that all these users connected together. I have asked them and some of those clients were in fact offline during this period. Is there any possibility of logs being cached in Mnesia and replayed? The current memory utilisation in eJabberd nodes is around 20 GB.

**Comment by logicwonder** [comment]
The issue was related to log rotation. Thanks for the help.
Closing the issue.

**Comment by licaon-kter** [comment]
@logicwonder explain?

**Comment by logicwonder** [comment]
We were parsing the eJabberd log files for injestion into elastic search. As part of the process, we created some intermediate log files. The data for elastic search indexes were pushed from these intermmediate files. During the log rotation schedule for these intermmediate files, the log files were getting renamed with the extension (*.log). This casued the rotated file to be indexed again to elastic search.

Anyway the issue was not related to eJabberd but left us scratching our heads. Thanks @licaon-kter for your instant replies which triggered us to rethink upon the issue.
