### ISSUE TITLE
Join cluster is not working

### ISSUE THREAD

**Issue by zenpol** [processone/ejabberd#3725]
Ejabberd version - 20.07
OS - ubuntu

I've two nodes running in same aws region with remote mysql database, when am trying to join node A from node B using ejabberdctl --no-timeout join_cluster node A. Its failing with error Failed RPC connection to node B (which is where am running the command) as ejabberd user. After running the command ejabberd is stopping in node B without any errors in logs.

**Comment by sujankumar4593** [comment]
can you check 4369 port  of node A is accessible from node B  using telnet command.  $ telnet nodeA 4369

**Comment by zenpol** [comment]
> can you check 4369 port of node A is accessible from node B using telnet command. $ telnet nodeA 4369

yeah it is accessible from node B

**Comment by sujankumar4593** [comment]
erlang cookie's are same in both the nodes?

**Comment by zenpol** [comment]
> erlang cookie's are same in both the nodes?

yeah both are same

**Comment by sujankumar4593** [comment]
can set debug mode on node A and try to run ejabberdctl --no-timeout join_cluster node A  command on node B and check the node A logs

**Comment by zenpol** [comment]
> 

tried the same but didn't get any logs

**Comment by zenpol** [comment]
> can you set debug mode on node A and try to run ejabberdctl --no-timeout join_cluster node A command on node B and check the node A logs

tried the same but didn't get any logs specific to it

**Comment by prefiks** [comment]
Could you start 'ejabberdclt debug' shell and enter `net_adm:ping('ejabberd@THE_OTHER_HOST_NAME').` and see if it returns pong as response? You can also try running `net_adm:names().` after this.

**Comment by zenpol** [comment]
> net_adm:ping(

got response as pong for the former command and {ok,[{"ejabberd",38091},{"f4d52bc9-debug-ejabberd",36061}]} for the latter one

**Comment by zenpol** [comment]
> Could you start 'ejabberdclt debug' shell and enter `net_adm:ping('ejabberd@THE_OTHER_HOST_NAME').` and see if it returns pong as response? You can also try running `net_adm:names().` after this.

got response as pong for the former command and {ok,[{"ejabberd",38091},{"f4d52bc9-debug-ejabberd",36061}]} for the latter one

**Comment by prefiks** [comment]
OK, so it probably can comminicate with the other side, could you also show output from debug shell for `mnesia:info().` and  `ejabberd_cluster:get_nodes().`

**Comment by zenpol** [comment]
> ejabberd_cluster:get_nodes().

---> Processes holding locks <---
---> Processes waiting for locks <---
---> Participant transactions <---
---> Coordinator transactions <---
---> Uncertain transactions <---
---> Active tables <---
route          : with 10       records occupying 530      words of mem
ejabberd_commands: with 154      records occupying 55202    words of mem
mod_register_ip: with 0        records occupying 300      words of mem
bosh           : with 0        records occupying 300      words of mem
mqtt_session   : with 0        records occupying 300      words of mem
mqtt_sub       : with 0        records occupying 94       words of mem
schema         : with 15       records occupying 2159     words of mem
session        : with 0        records occupying 300      words of mem
pubsub_last_item: with 0        records occupying 300      words of mem
bytestream     : with 0        records occupying 300      words of mem
temporarily_blocked: with 0        records occupying 300      words of mem
s2s            : with 0        records occupying 300      words of mem
session_counter: with 0        records occupying 300      words of mem
muc_online_room: with 769      records occupying 17788    words of mem
route_multicast: with 0        records occupying 300      words of mem
===> System info in version "4.15.6", debug level = none <===
opt_disc. Directory "/opt/ejabberd/database/ejabberd@nodeB" is used.
use fallback at restart = false
running db nodes   = ['ejabberd@nodeB']
stopped db nodes   = []
master node tables = []
remote             = []
ram_copies         = [bosh,bytestream,ejabberd_commands,mod_register_ip,
                      mqtt_session,mqtt_sub,muc_online_room,pubsub_last_item,
                      route,route_multicast,s2s,session,session_counter,
                      temporarily_blocked]
disc_copies        = [schema]
disc_only_copies   = []
[{'ejabberd@nodeB',disc_copies}] = [schema]
[{'ejabberd@nodeB',ram_copies}] = [route_multicast,
                                                                     muc_online_room,
                                                                     mod_register_ip,
                                                                     session_counter,
                                                                     s2s,
                                                                     temporarily_blocked,
                                                                     bosh,
                                                                     bytestream,
                                                                     pubsub_last_item,
                                                                     session,
                                                                     mqtt_sub,
                                                                     mqtt_session,
                                                                     ejabberd_commands,
                                                                     route]
783 transactions committed, 6 aborted, 0 restarted, 4 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok

**Comment by zenpol** [comment]
['ejabberd@nodeB] for ejabberd_cluster:get_nodes().

**Comment by prefiks** [comment]
So looks like there is no any leftovers from join cluster attempt. You can try to join cluster from debug shell as well - use `ejabberd_cluster:join('ejabberd@OTHER_HOST').`

**Comment by zenpol** [comment]
> ejabberd_cluster:join(



> So looks like there is no any leftovers from join cluster attempt. You can try to join cluster from debug shell as well - use `ejabberd_cluster:join('ejabberd@OTHER_HOST').`

tried the same, but ejabberd stopped running with no errors in logs

**Comment by prefiks** [comment]
Did just that debug shell stop responding (you can terminate it with ctrl+c twice), or server did stop as well?

**Comment by zenpol** [comment]
> Did just that debug shell stop responding (you can terminate it with ctrl+c twice), or server did stop as well?

debug shell stopped responding, terminated it with ctrl+c. and on checking ejabberd status it is stopped

**Comment by zenpol** [comment]
> ejabberd_cluster:join('ejabberd@OTHER_HOST').

does above command restarts ejabberd server?

**Comment by prefiks** [comment]
It should restart ejabberd server, it stops it, then setup cluster and tries to estabilish connection to other nodes, and if that success it starts server again. I guess it get stuck at node setup/mnesia table replication.

**Comment by zenpol** [comment]
> ejabberd_cluster:get_nodes().

below are the logs in debug node

2021-12-08 07:39:59.480 [debug] <0.278.0>@ejabberd_access_permissions:handle_call:108 Command 'join_cluster' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
2021-12-08 07:39:59.480 [debug] <0.1333.0>@ejabberd_commands:do_execute_command:250 Executing command ejabberd_admin:join_cluster with Args=[<<"ejabberd@nodeA">>]
2021-12-08 07:39:59.491 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TCP connections at [::]:5222 for ejabberd_c2s
2021-12-08 07:39:59.491 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TCP connections at 0.0.0.0:5269 for ejabberd_s2s_in
2021-12-08 07:39:59.491 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TLS connections at [::]:5443 for ejabberd_http
2021-12-08 07:39:59.493 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TCP connections at [::]:5280 for ejabberd_http
2021-12-08 07:39:59.493 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TCP connections at [::]:1883 for mod_mqtt
2021-12-08 07:39:59.493 [info] <0.106.0>@ejabberd_listener:stop_listener:402 Stop accepting TCP connections at [::]:4560 for ejabberd_xmlrpc

**Comment by zenpol** [comment]
> It should restart ejabberd server, it stops it, then setup cluster and tries to estabilish connection to other nodes, and if that success it starts server again. I guess it get stuck at node setup/mnesia table replication.

here in this set up am using mysql database, for s2s connection is it going to use mnesia itself?

**Comment by prefiks** [comment]
There are couple tables that will use mnesia anyway (for example routing table), you can see list of tables in `mnesia:info()` output.

**Comment by licaon-kter** [comment]
Two thoughts, the data (messages and more) are in the sql db, and state is in mnesia. By default.

And second, see the Web admin panel, you can control if Mnesia is used or not for some state.

**Comment by zenpol** [comment]
> It should restart ejabberd server, it stops it, then setup cluster and tries to estabilish connection to other nodes, and if that success it starts server again. I guess it get stuck at node setup/mnesia table replication.

when am trying to stop ejabberd its not stopping, it's stopping only after killing beam. Is that causing issue ?

**Comment by prefiks** [comment]
In this state ejabberd server is already stopped, so killing beam will rather do nothing problematic.

**Comment by zenpol** [comment]
> In this state ejabberd server is already stopped, so killing beam will rather do nothing problematic.

is there any other way to fix this?

**Comment by prefiks** [comment]
Possibly starting another `ejabberdctl debug` and executing `init:stop().` will work

**Comment by zenpol** [comment]
> Possibly starting another `ejabberdctl debug` and executing `init:stop().` will work
is there any other method to join cluster as this approach is failing?

**Comment by prefiks** [comment]
Not really, it just setup basic blocks for cluster. Could you show what `mnesia:info().` shows on other node? Maybe there is some problem on other node.

**Comment by zenpol** [comment]
> mnesia:info().

---> Processes holding locks <---
---> Processes waiting for locks <---
---> Participant transactions <---
---> Coordinator transactions <---
---> Uncertain transactions <---
---> Active tables <---
route_multicast: with 0        records occupying 300      words of mem
s2s            : with 0        records occupying 300      words of mem
route          : with 10       records occupying 530      words of mem
ejabberd_commands: with 154      records occupying 55202    words of mem
mod_register_ip: with 0        records occupying 300      words of mem
bosh           : with 0        records occupying 300      words of mem
mqtt_session   : with 0        records occupying 300      words of mem
mqtt_sub       : with 0        records occupying 94       words of mem
schema         : with 15       records occupying 2173     words of mem
session        : with 0        records occupying 300      words of mem
pubsub_last_item: with 0        records occupying 300      words of mem
bytestream     : with 0        records occupying 300      words of mem
temporarily_blocked: with 0        records occupying 300      words of mem
session_counter: with 0        records occupying 300      words of mem
muc_online_room: with 769      records occupying 17788    words of mem
===> System info in version "4.15.6", debug level = none <===
opt_disc. Directory "/opt/ejabberd/database/ejabberd@nodeA" is used.
use fallback at restart = false
running db nodes   = ['ejabberd@nodeA']
stopped db nodes   = []
master node tables = []
remote             = []
ram_copies         = [bosh,bytestream,ejabberd_commands,mod_register_ip,
                      mqtt_session,mqtt_sub,muc_online_room,pubsub_last_item,
                      session,session_counter,temporarily_blocked]
disc_copies        = [route,route_multicast,s2s,schema]
disc_only_copies   = []
[{'ejabberd@nodeA',disc_copies}] = [schema,
                                                                       route,
                                                                       s2s,
                                                                       route_multicast]
[{'ejabberd@nodeA',ram_copies}] = [muc_online_room,
                                                                      mod_register_ip,
                                                                      session_counter,
                                                                      temporarily_blocked,
                                                                      bosh,
                                                                      bytestream,
                                                                      pubsub_last_item,
                                                                      session,
                                                                      mqtt_sub,
                                                                      mqtt_session,
                                                                      ejabberd_commands]
786 transactions committed, 33 aborted, 0 restarted, 10 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok

**Comment by zenpol** [comment]
> Ok, i don't see anything strange here, i don't have any ideas why mnesia don't want to cooperate right now.

 application:stop(ejabberd) command is not responding in the node B, is that causing the issue?

**Comment by prefiks** [comment]
I don't know

**Comment by licaon-kter** [comment]
Sorry, wrong mention, meant @zenpol
