### ISSUE TITLE
Ejabberdctl stop isn't working

### ISSUE THREAD

**Issue by zenpol** [processone/ejabberd#3729]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 20.07
- OS: Linux (Debian)
- Installed from:  official deb/rpm 

Ejabberdctl stop isn't stopping ejabberd completely, as I am getting  the ejabberd node 'ejabberd@slave' is already running  error when I run ejabberdctl start after stopping it.

Ejabberd is starting only after killing beam process manually and starting it

**Comment by licaon-kter** [comment]
So `sudo ejabberdctl stop` does not stop it?

**Comment by zenpol** [comment]
> So `sudo ejabberdctl stop` does not stop it?

ejabberd server stopped responding but wont be able to start it again unless I kill beam process

**Comment by licaon-kter** [comment]
ejabberd.log on loglevel 4 says what when you stop?

**Comment by zenpol** [comment]
> ejabberd.log on loglevel 4 says what when you stop?

nothing is coming up when I stop in logs

**Comment by prefiks** [comment]
Is server working ok before you are stop is called? Are you able to join with a client to it?

**Comment by zenpol** [comment]
> Is server working ok before you are stop is called? Are you able to join with a client to it?

yes it's working fine before stop is called and also able to connect with a client

**Comment by licaon-kter** [comment]
@zenpol what was the issue/solution?
