### ISSUE TITLE
Support for XEP-0425: Message Moderation

### ISSUE THREAD

**Issue by raucao** [processone/ejabberd#3730]
> Occasionally, a Multi-User Chat (XEP-0045) [1] moderator might wish to moderate certain groupchat messages by, for example, retracting them from the groupchat history as part of an effort to address and remedy issues such as message spam, indecent language for the venue or exposing private third-party personal information. Alternatively, a moderator might want to correct a message on another user's behalf, or flag a message as inappropriate without requiring that it be retracted.

https://xmpp.org/extensions/xep-0425.html

refs #3340

**Comment by poVoq** [comment]
Given yesterdays events, maybe time to prioritize this one? Thanks!

**Comment by pravi** [comment]
Is someone willing to work on this feature if there was some funding? Conversations[1] and Monal[2] got funds from NLNet for specific feature development. We could think of crowd funding as well - spam waves are happening very frequently these days and it is really annoying. Prosody already has a module for this[3].

[1] https://nlnet.nl/project/Conversations-3.0/
[2] https://monal-im.org/post/00003-nlnet-funding/
[3] https://modules.prosody.im/mod_muc_moderation.html

**Comment by pravi** [comment]
@prefiks I have built the deb from master branch (available here https://repo.process-one.net/deb/pool/main/e/ejabberd/) but when testing with gajim, I don't see a retract option in gajim (I see such option in prosody hosted mucs).

**Comment by badlop** [comment]
>  I have built the deb from master branch

Have you build the deb using a recent ejabberd git, or did you download ejabberd 23.01 deb file from that page?

There are installers available for each commit in
https://github.com/processone/ejabberd/actions/workflows/installers.yml
and the runs #232 and newer include the new XEP support.

**Comment by pravi** [comment]
I can now see the retract option in the gajim menu, but it seems to be not working (the message don't get deleted).

**Comment by pravi** [comment]
Sorry, I copy pasted wrong link earlier. I took a snapshot of the github repo and modified the official debian package https://salsa.debian.org/praveen/ejabberd The debs I built is available at https://people.debian.org/~praveen/ejabberd/

**Comment by prefiks** [comment]
I will take look at this, i didn't test it with gajim, maybe something is missing here.

**Comment by prefiks** [comment]
Looks like generated payload was missing one of required attributes, this was fixed by d12e5a44b82451b68d33bd3e36eced233428af37

**Comment by pravi** [comment]
@prefiks thanks, I can confirm retractions are now working! For people who are impatient till there is an official release, I have uploaded the debs to https://people.debian.org/~praveen/ejabberd/

**Comment by badlop** [comment]
> For people who are impatient till there is an official release, I have uploaded the debs to https://people.debian.org/~praveen/ejabberd/

BTW, installers (run, deb and rpm for amd64 and arm64) are automatically generated for every commit, and available for two weeks in https://github.com/processone/ejabberd/actions/workflows/installers.yml -> enter a recent commit, on the bottom download `ejabberd-packages` and unzip it :)

**Comment by poVoq** [comment]
This seems to be still undocumented in the official docu. Is it enabled by default?

**Comment by badlop** [comment]
> This seems to be still undocumented in the official docu.

It was automatically added in [xmpp.org](https://xmpp.org/software/ejabberd/), but the manual addition in [process-one](https://www.process-one.net/en/ejabberd/protocols/) was not done yet. Is that  the documentation you refer to? Or is there somewhere else where it is lacking?

> Is it enabled by default?

I would say yes, because there is no option to configure or enable/disable it.

**Comment by poVoq** [comment]
I was referring to: https://docs.ejabberd.im/admin/configuration/modules/#mod-mam

But I guess if there is no option to enable or disable it, then there is no point to document it as a configuration option.
