### ISSUE TITLE
XEP-0045: muc#roomconfig_allowpm does not exist in ejabberd

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3736]
In XEP-0045, there is muc#roomconfig_allowpm but it is not in ejabberd:
- https://xmpp.org/extensions/xep-0045.html

Version 1.34.5 (2022-12-01).

This point has been added in 1.25.

Other points can be looked too.

Thanks in advance.

Changes:
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.21.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.22.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.22.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.23.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.23.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.24.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.24.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.25.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.25.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.26.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.26.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.27.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.27.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.28.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.28.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.29.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.29.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.30.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.30.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.31.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.31.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.31.1.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.31.1.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.31.2.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.31.2.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.32.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.32.0.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.33.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.33.0.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.34.0.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.1.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.34.1.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.2.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.34.2.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.3.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.34.3.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.4.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0045-1.34.4.html&newfile=https://xmpp.org/extensions/attic/xep-0045-1.34.5.html

**Comment by badlop** [comment]
XEP-0045 proposes an option to configure who can send PM:
`muc#roomconfig_allowpm : anyone | participants | moderators | none`

ejabberd implements two options:
* Can everybody send private messages to everybody?
`allow_private_messages : true | false`
* Can visitors send private messages to ...
`allow_private_messages_from_visitors : anyone | moderators | visitors`

With those options, it is possible to configure `muc#roomconfig_allowpm : anyone` with:
```
allow_private_messages : true
allow_private_messages_from_visitors : anyone
```

It is possible to configure `muc#roomconfig_allowpm : none` with:
```
allow_private_messages : false
```

And a configuration similtar to `muc#roomconfig_allowpm : participants` can be achieved with:
```
allow_private_messages : true
allow_private_messages_from_visitors : visitors
```
The only option  that has no equivalent is `muc#roomconfig_allowpm : moderators`

**Comment by licaon-kter** [comment]
> The only option that has no equivalent is muc#roomconfig_allowpm : moderators

This is odd as both Dino and Gajim have such a setting and it does not error out when used, yet it's pretty clear that it doesn't do anything, basically `moderators` behaves like `none`

Use case? A moderated room, new users are not voice enabled, so they need to either request for voice _(no such thing in Conversations)_ or PM a moderator to do this. But, since MUC PMs are disabled _(to avoid 'invisible' trolling/grieving/etc)_ this makes the room harder to manage.

@badlop any plans to implement this?

**Comment by Neustradamus** [comment]
@badlop: Thanks a lot! :)

Have you looked other changes too?
I have given you diff files to easy found changes.
