### ISSUE TITLE
Official Fedora / RedHat ejabberd 20.07+ package request (2 years without changes)

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3742]
There is no update since a long time (20.07) in official Fedora / Red Hat package.

It is possible to help @lemenkov, @bowlofeggs?

Thanks in advance.

There is a ticket here:
- https://bugzilla.redhat.com/show_bug.cgi?id=1928213

The failed test:
- https://koji.fedoraproject.org/koji/taskinfo?taskID=79782126

Source code:
- https://src.fedoraproject.org/rpms/ejabberd

Bugs:
- https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=ON_QA&component=ejabberd

Koschei:
- https://koschei.fedoraproject.org/package/ejabberd

Remi repo:
- https://rpms.remirepo.net/rpmphp/zoom.php?rpm=ejabberd

**Comment by lemenkov** [comment]
Hey!
I'm on it.

**Comment by Neustradamus** [comment]
@lemenkov: Have you progressed?
Do you need help?

**Comment by Neustradamus** [comment]
@lemenkov: Do you need help?
- https://src.fedoraproject.org/rpms/ejabberd/commits/rawhide

**Comment by Neustradamus** [comment]
@lemenkov: Have you progressed?
Do you need help?

We are 17th July 2022, today.

**Comment by Neustradamus** [comment]
@lemenkov: I think that ejabberd 22.10 will be released soon, have you progressed?

A lot of users wait improvements since more two years with 20.07!

What it the problem?

cc: @bowlofeggs.

**Comment by Neustradamus** [comment]
@lemenkov, @bowlofeggs: ejabberd 22.10 has been released...
