### ISSUE TITLE
Non-ASCII characters in passwords lead to Auth error in web_admin

### ISSUE THREAD

**Issue by flasheater** [processone/ejabberd#375]
Present in ejabberd 14.07. Tested on Ubuntu 14.04 using the binary installer. Tested with Chrome and Firefox. 

If an admin user has non-standard characters ( tested German umlauts), he/she cannot login through the Web interface, even though credentials are correct. 

Workaround: Don't use crazy chars 😉. 

This issue is minor but cost me unnecessary time, grief and confusion.

**Comment by mremond** [comment]
@badlop It seems it should be already fixed. What do you think ?

**Comment by badlop** [comment]
The problem is still there. At least in Mnesia, the password is stored in urt8, but webadmin receives it in other encoding, and it isn't converted before checking it.
