### ISSUE TITLE
ejabberd cluster mod_mqtt(MQTT) cannot receive messages in certain situations

### ISSUE THREAD

**Issue by youngmort** [processone/ejabberd#3750]
## Environment

- ejabberd version: 21.12 (docker image ejabberd/ecs:21.12)
- Erlang version:  docker image ejabberd/ecs:21.12
- OS: alpine:3.11
- Installed from: https://hub.docker.com/r/ejabberd/ecs

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: debug
...
```

## Errors from error.log/crash.log

No errors

## Bug description

In some cases, when I publish messages, subscribers cannot receive the messages.
But I just to do one action, and the subscriber can successfully receive the message.

For short, node1、node2 is ejabberd node. 
client1、client2 is mqtt client user.

PS : the mqtt client tool I use(https://mqttx.app/) v1.7.0
I have tried other mqtt clients and the same problem occurs, for example MQTT.fx、MQTT Explorer

Steps to reproduce this situation：
1. Run two ejabberd containers from docker hub.
2. In the second node(node2): run "join_cluster" to join the first node.(They are now a ejabberd cluster).
3. Client1 connects to node1
4. Client2 connects to node2
5. Client2 subscribes the topic "abc"
6. Now in both nodes I see the mqtt_sub mnesia table with that item. I see it in ejabberd WebAdmin -> Nodes -> my node -> Database.
7. Client1 publish a message to topic "abc"
8. Client2 cannot receive the message from topic "abc"
The magical thing is coming, I just do one step to make it work normally
9. Client1 also subscribes the topic "abc".  <= only do this
10. Client1 publish a message to topic "abc"
11. then client2 can receive messages from topic "abc"

Assume that both client1 and client2 are connected to the same ejabberd node. They will not have the above problems, and they will normally work.
The above problem only occurs when client1 and client2 are connected to different ejabberd nodes.But as long as the any client at node1 subscribe the same topic as node2, they seem to be able to broadcast the message.

logs for reference (step 7) 7. Client1 publish a message to topic "abc"
```
2022-01-06 16:18:35.464271+00:00 [debug] <0.1284.0>@mod_mqtt_session:handle_info/2:240 Got MQTT packet:
#publish{id = undefined,dup = false,qos = 0,retain = false,topic = <<"abc">>,
         payload = <<"aaaaad">>,properties = #{},meta = #{}}
```

logs for reference (step 9) 9. Client1 also subscribes the topic "abc". 
```
2022-01-06 16:22:25.667878+00:00 [debug] <0.1284.0>@mod_mqtt_session:handle_info/2:240 Got MQTT packet:
#subscribe{id = 36881,
           filters = [{<<"abc">>,
                       #sub_opts{qos = 0,no_local = false,
                                 retain_as_published = false,
                                 retain_handling = 0}}],
           properties = #{},meta = #{}}
2022-01-06 16:22:25.670407+00:00 [debug] <0.1284.0>@mod_mqtt_session:do_send/2:871 Send MQTT packet:
#suback{id = 36881,codes = ['granted-qos-0'],properties = #{}}
```

logs for reference (step 10) 10. Client1 publish a message to topic "abc"
```
2022-01-06 16:23:32.951864+00:00 [debug] <0.1284.0>@mod_mqtt_session:handle_info/2:240 Got MQTT packet:
#publish{id = undefined,dup = false,qos = 0,retain = false,topic = <<"abc">>,
         payload = <<"aaaaad">>,properties = #{},meta = #{}}
2022-01-06 16:23:32.952092+00:00 [debug] <0.1284.0>@mod_mqtt:route/6:375 Route to <0.1284.0>: abc
2022-01-06 16:23:32.952294+00:00 [debug] <0.1284.0>@mod_mqtt:route/6:375 Route to <28063.1728.0>: abc
2022-01-06 16:23:32.952558+00:00 [debug] <0.1284.0>@mod_mqtt_session:do_send/2:871 Send MQTT packet:
#publish{id = 24273,dup = false,qos = 0,retain = false,topic = <<"abc">>,
         payload = <<"aaaaad">>,properties = #{},
         meta = #{expiry_time => 4294967295}}
```

**Comment by badlop** [comment]
I can reproduce the problem using Mnesia storage.

Right now it is required that **at least one** account is subscribed to the topic **in the local node** (not necessarily the same account that is publishing). If at least one is subscribed in the local node, then all the remaining subscribers in local node and remote nodes will be found and notified about the publication.

Internal details: MQTT subscriptions and publications are stored in mnesia tables, which are replicated over the nodes. Additionally, ejabberd uses "mqtree" to count how many accounts are subscribed to any given topic... and that data storage is independent for each node, not replicated. And there's a function that uses mqtree and requires that at least one account is subscribed according to its local mqtree storage.

https://github.com/processone/ejabberd/blob/9ba20d26cb67a0c6adcfb7d5fbbb3ba23c6cc9fd/src/mod_mqtt_mnesia.erl#L252

I'll check if there's some solution

**Comment by badlop** [comment]
I wrote that small patch at https://github.com/badlop/ejabberd/commit/6aa89301a851b7e791237328c453ecd2d39f49a7 , and seems to fix the problem with my tests. If you can apply that patch to your server, and test it, tell me if it solves this problem for you too.

---

By the way, to use mqttx with "MQTT 5.0" option enabled, I had to apply this small patch too https://github.com/badlop/ejabberd/commit/20de092141da97a9bebab91cce6af5bd1f20600f If you are interested in it, please notice: this patch modifies the mqtt_pub table, so you would need to destroy the old one... And I'm looking for a better solution, so maybe in the next ejabberd version there's a different solution, that requires you to again destroy mqtt_pub table. So, use this patch only on a testing server.

**Comment by youngmort** [comment]
Hi @badlop 

I try to apply the patch to my server.  Now there is no required that at least one account is subscribed to the topic in the local node. But this patch causes other problems. Subscribers receive the same message repeatedly.

Steps to reproduce this situation：
1. Run two ejabberd containers from docker hub.
2. In the second node(node2): run "join_cluster" to join the first node.
3. Client1 connects to node1
4. Client2 connects to node2
5. Client1 subscribes the topic "abc"
6. Client2 subscribes the topic "abc" (So both clients are subscribed to the same topic on different nodes)
7. Client1 publish a message to topic "abc"
8. Either client1 or client2 received a duplicate message twice

If there is a client3 that also subscribes to the topic "abc", then client1, client2, and client3 will all receive the same message three times.

**Comment by badlop** [comment]
Ah, right. Here is a little fix, it's just one word in mod_mqtt_mnesia.erl line 258:
```diff
-    lists:flatten(Res).
+    lists:umerge(Res).
```

**Comment by youngmort** [comment]
Hi @badlop  Thank you for your prompt reply.

I tried it and it works as expected.  I will try testing the functionality of MQTT 5.0 and let you know the results.

**Comment by youngmort** [comment]
Hi @badlop  

[badlop@6aa8930](https://github.com/badlop/ejabberd/commit/6aa89301a851b7e791237328c453ecd2d39f49a7)  This patch works well.

But in my local server environment I don't get "MQTT 5.0 option enabled" error.

**Comment by badlop** [comment]
> But in my local server environment I don't get "MQTT 5.0 option enabled" error.

I don't understand. Does MQTT 5.0 work correctly? Does MQTT 5 fail with some error? Or MQTT5 is not available in your client for testing?

**Comment by youngmort** [comment]
Hi @badlop ,

MQTT 5.0 works fine on my local server without errors.  I used a client library that supports MQTT 5.0 and can connect to ejabberd publish and subscribe messages normally. ex: [paho](https://github.com/eclipse/paho.mqtt.golang)、MQTTX
