### ISSUE TITLE
Missing lower/upper case check: crashed when running mod_shared_roster:unset_presence

### ISSUE THREAD

**Issue by ingoj** [processone/ejabberd#3752]
## Environment

- ejabberd version: 21.12
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 11.1.8
- OS: Linux Debian Bullseye
- Installed from: personal repo from Debian package maintainer for testing new 21.12 packages

## Errors from error.log/crash.log
```

2022-01-14 19:20:12.268266+01:00 [error] <0.16560.1>@ejabberd_hooks:safe_apply/4:240 Hook unset_presence_hook crashed when running mod_shared_roster:unset_presence/4:
** exception error: {module_not_loaded,mod_shared_roster,<<"xmpp.Social">>}
   in function  gen_mod:get_module_opts/2 (gen_mod.erl, line 338)
   in call from gen_mod:get_module_opt/3 (gen_mod.erl, line 318)
   in call from gen_mod:db_mod/3 (gen_mod.erl, line 352)
   in call from mod_shared_roster:groups_with_opts/1 (mod_shared_roster.erl, line 408)
   in call from mod_shared_roster:'-get_groups_with_wildcards/2-fun-1-'/2 (mod_shared_roster.erl, line 610)
   in call from ets_cache:lookup/3 (ets_cache.erl, line 174)
   in call from mod_shared_roster:get_groups_with_wildcards/2 (mod_shared_roster.erl, line 599)
   in call from mod_shared_roster:unset_presence/4 (mod_shared_roster.erl, line 888)
** Arg 1 = <<"XXXXX">>
** Arg 2 = <<"xmpp.Social">>
** Arg 3 = <<"iPhone von XXXXX">>
** Arg 4 = <<"Stream reset by peer">>
```

## Bug description

Just saw this crash by chance when looking at my log. Take a look at the capital "S" in the domain name. There seems to be a missing normalization of the domain name in that routine. Most likely not dependent on the reported package/ejabberd version.

**Comment by weiss** [comment]
Thanks!

> Take a look at the capital "S" in the domain name. There seems to be a missing normalization of the domain name in that routine. Most likely not dependent on the reported package/ejabberd version.

Exactly.  `ejabberd_sm:unset_presence/5` hands `User`, `Server`, `Resource` over to hook callbacks without normalization, `mod_shared_roster:unset_presence/4` expects them to be normalized.  I guess we want to change the latter (rather than the former).
