### ISSUE TITLE
Phantom user after update ejabberd 20.01 to 21.12

### ISSUE THREAD

**Issue by Plachey** [processone/ejabberd#3755]
Hello, get problem after update ejabberd 20.01 to 21.12. MUC not kicked user after 30 sec., when I turn off internet on devices.  I can check it using request api/get_room_occupants. 

Please, help me

**Comment by licaon-kter** [comment]
Operating system? Install method? Did you follow the upgrade steps: https://docs.ejabberd.im/admin/upgrade/ ?

**Comment by Plachey** [comment]
use docker FROM ejabberd/ecs:21.12

**Comment by licaon-kter** [comment]
Now read the upgrade path and...see what you didn't do right

Using sql too? There are special instructions for that too... 

Using Docker does not magically fix your config or database. :(

**Comment by Plachey** [comment]
Yes, but I tryed delete everything and reinstall one. After that I get the same error

**Comment by prefiks** [comment]
Typically server doesn't get info that connection is broken immediatelly when that happen, usually we get that info when we try to send something to client and then we receive error that packed could not be delivered. So possibly some mechanism that trigger pinging client is not enabled or server? Could also be that client setups resume session mechanism, in that case server will wait for some time when connection is lost for session resume on new connection. It's not possible to say what happens without logs from server and client.

**Comment by Neustradamus** [comment]
Maybe good to publish your conf (without password), logs...
