### ISSUE TITLE
User Always Online

### ISSUE THREAD

**Issue by praveenoms** [processone/ejabberd#376]
I have ejabberd setup to be the xmpp server between mobile apps , ie. custom iPhone and Android app.
We are using XEP-0198 Stream management
But I've seemingly run into a limitation of the way ejabberd handles online status's.

Scenario:

```
User A Enable Stream on mobile.
User A loses all connectivity, so client can't disconnect from server.
ejabberd still lists User A as online.
```

CASE 1 (Only appears on network fluctuation) : we tried Enable 
     mod_ping:
            send_pings: true
            ping_interval: 30
            timeout_action: <b>kill</b>
as stated in the documentation the ping will wait 32 seconds for a response before disconnecting the user.

If we tried to reconnect with the stream between Kill session process the roster through connection reset error On Ejabberd Web Admin and A can send messages which was delivered fine to other users
 but  A cant receive any messages from EJD ,then we need to wait for 3-4 mins or more till A is not offline on server, after that every thing works good.

CASE 2:
 mod_ping:
            send_pings: true
            ping_interval: 30
            timeout_action:<b> None</b>  
Case 1 not appear,But User is always Online on server

Ideal Solution:
a) Is there a way that ejabberd can make user Offline or set presence to Unavailable if he is not        connected or lost all connectivity.

b) can't we just put user to offline instead of kill using the ping? this will solve the problem

c) Is it possible to write a hook to solve this problem?

d)  is there a simple setting I've missed somewhere?

FYI: I am not using BOSH., Stream Expiration is 5 Days

**Comment by InheritX** [comment]
Hello Praveen,

How to implement following stuff ?
-----------------------------------
As for mod_ping, it currently has only two options: none or kill. On the timeout it calls ejabberd hook 'user_ping_timeout' (see the source code for details). You could try setting the timeout_action to 'none' and then implement whatever you want in the hook.
-----------------------------------

Please can you share steps to install and enable "mod_ping" and where to pass hook URL ?

Thanks,
KT

**Comment by rraptorr** [comment]
You enable mod_ping in ejabberd configuration, please read ejabberd guide for detailed description (section "ejabberd for administrators").

As for the hook, there is no URL. The hook as an Erlang code that will be called. So you must write your own ejabberd module in Erlang that will implement what you want. Then you can configure it as a mod_ping hook. Again, see ejabberd guide for details (section "ejabberd for developers").

**Comment by InheritX** [comment]
Thanks @rraptorr for your quick response.

@praveenoms : How you have solved the above issue ? As I am not familiar with "Erlang code" , So I would be grateful If you can help me out with code and methods .

Many Thanks @rraptorr @praveenoms

**Comment by pmehul55** [comment]
Hello everyone,

I am currently working with MongooseIM server 2.0.0
@praveenoms : I am having same issue but in my case user never disconnected to server until and unless he reconnect and disconnect itself.

Following below configuration for ping manager 

 http://mongooseim.readthedocs.io/en/2.0.0/modules/mod_ping/

Can anyone help me out to fix this issue ?
