### ISSUE TITLE
ejabberd start failing due to memory limits

### ISSUE THREAD

**Issue by zenpol** [processone/ejabberd#3765]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 19.09
- OS: Linux (RHEL)
- Installed from: official deb/rpm 

`

## Errors from error.log/crash.log

eheap_alloc: Cannot allocate 177423032 bytes of memory (of type "heap").

## Bug description

ejabberd is not starting with below error

eheap_alloc: Cannot allocate 177423032 bytes of memory (of type "heap").

**Comment by licaon-kter** [comment]
RAM available? erlang version? Config in a https://gist.github.com ? Did it ever work?

**Comment by zenpol** [comment]
> RAM available? erlang version? Config in a https://gist.github.com ? Did it ever work?

RAM available : 459512 kilobytes
erlang version : 21.0
It used to work earlier, but after getting more load it crashed and from then its giving above error

**Comment by badlop** [comment]
> It used to work earlier, but after getting more load it crashed and from then its giving above error

Your system has less than 500 MB of RAM, and ejabberd can't allocate 177 MB to start...

Let's suppose that the internal mnesia database is so big that erlang can't load it. 

In that case, you can move to a safe and hidden place your mnesia spool directory (see https://docs.ejabberd.im/admin/installation/#system-install).

The idea is to try to start ejabberd using an empty mnesia spool dir: ejabberd will create a new database, and hopefully it will start correctly.

If that works, then we know where is the problem (in your old mnesia database), and we can investigate your old mnesia database.
