### ISSUE TITLE
Problem with Shared Roster

### ISSUE THREAD

**Issue by sherlock9712** [processone/ejabberd#3766]
Hello, in the company where I work there are a large number of users, more than a thousand. I set up the Ejabberd server and everything worked perfectly for me, but a few days ago when I tried to add a new user in the Admin Web, this happened to me, which shows the photo, I can make changes to the Group Name, description and the groups to display, but I It gives the problem when I add or delete a user. What I can do?

![Sin título](https://user-images.githubusercontent.com/53910995/153268862-15ef64e3-63a1-4dcc-8a78-81001148c5d9.png)

**Comment by licaon-kter** [comment]
Any errors in the browser console? In ejabberd.log? Which ejabberd version? Which OS&version? Which erlang version?

**Comment by sherlock9712** [comment]
The version that I am using is the one that comes in the debian 10 repositories

**This is what the web console shows:**

`Cookie “PHPSESSID” will be soon treated as cross-site cookie against “https://x.x.x.x:5280/admin/server/test.domain.com/shared-roster/Comunicaciones/” because the scheme does not match.`


**This show ejabberd.log (that's what it shows me when trying to add a new user on the web):** 
`2022-02-09 15:54:11.879 [error] <0.3203.0>@ejabberd_hooks:safe_apply:384 Hook webadmin_page_host crashed when running mod_shared_roster:webadmin_page/3:
** Reason = {error,{case_clause,undefined},[{mod_roster,push_item,3,[{file,"src/mod_roster.erl"},{line,478}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_shared_roster,'-push_user_to_displayed/6-lc$^0/1-0-',6,[{file,"src/mod_shared_roster.erl"},{line,649}]},{mod_shared_roster,'-push_user_to_displayed/6-lc$^0/1-0-',6,[{file,"src/mod_shared_roster.erl"},{line,651}]},{mod_shared_roster,add_user_to_group,3,[{file,"src/mod_shared_roster.erl"},{line,553}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_shared_roster,shared_roster_group_parse_query,3,[{file,"src/mod_shared_roster.erl"},{line,941}]},{mod_shared_roster,shared_roster_group,4,[{file,"src/mod_shared_roster.erl"},{line,805}]}]}
** Arguments = [[],<<"test.domain.com">>,{request,'POST',[<<"shared-roster">>,<<"Comunicaciones">>],[{<<"name">>,<<"Comunicaciones">>},{<<"description">>,<<>>},{<<"members">>,<<"alejo@test.domain.com\r\nariel@test.domain.com\r\ncindy@test.domain.com\r\nelier@test.domain.com\r\nelizabeth@test.domain.com\r\nernesto.s@test.domain.com\r\ngiselle@test.domain.com\r\nharold@test.domain.com\r\njunior@test.domain.com\r\nleonardo@test.domain.com\r\nliz@test.domain.com\r\nnoemi@test.domain.com\r\nosmel@test.domain.com\r\ntasia@test.domain.com\r\nyassel@test.domain.com\r\nyelsiney@test.domain.com\r\nuser@test.domain.com">>},{<<"dispgroups">>,<<"Atencion a la Poblacion\r\nAuditoria\r\nBanca Corporativa\r\nBanca Electronica\r\nBanca Particular\r\nCapital Ilicito\r\nCentro Distribuidor de Efectivo\r\nCentro Informativo\r\nCentros Contables\r\nComunicaciones\r\nContabilidad\r\nCuadros\r\nDirecciones Territoriales\r\nDireccion ATM\r\nDirectivos\r\nEfectivo\r\nGestion de Tarjetas\r\nHardware\r\nJuridico\r\nMarketing\r\nMensajeria\r\nOCD\r\nPlanificacion\r\nPresidente\r\nProcedimientos\r\nRecursos Humanos\r\nRed Sucursales\r\nRiesgo\r\nSeguridad Informatica\r\nServicios Generales\r\nSistema\r\nSucursal Electronica\r\nSucursales\r\nTelebanca\r\nVicepresidencia\r\n">>},{<<"submit">>,<<"Enviar">>}],{<<"user">>,<<"test.domain.com">>},{auth_jid,{<<"user@test.domain.com">>,<<"passwd">>},{jid,<<"user">>,<<"test.domain.com">>,<<>>,<<"user">>,<<"test.domain.com">>,<<>>}},<<"es-ES">>,<<"name=Comunicaciones&description=&members=alejo%40test.domain.com%0D%0Aariel%40test.domain.com%0D%0Acindy%40test.domain.com%0D%0Aelier%40test.domain.com%0D%0Aelizabeth%40test.domain.com%0D%0Aernesto.s%40test.domain.com%0D%0Agiselle%40test.domain.com%0D%0Aharold%40test.domain.com%0D%0Ajunior%40test.domain.com%0D%0Aleonardo%40test.domain.com%0D%0Aliz%40test.domain.com%0D%0Anoemi%40test.domain.com%0D%0Aosmel%40test.domain.com%0D%0Atasia%40test.domain.com%0D%0Ayassel%40test.domain.com%0D%0Ayelsiney%40test.domain.com%0D%0Auser%40test.domain.com&dispgroups=Atencion+a+la+Poblacion%0D%0AAuditoria%0D%0ABanca+Corporativa%0D%0ABanca+Electronica%0D%0ABanca+Particular%0D%0ACapital+Ilicito%0D%0ACentro+Distribuidor+de+Efectivo%0D%0ACentro+Informativo%0D%0ACentros+Contables%0D%0AComunicaciones%0D%0AContabilidad%0D%0ACuadros%0D%0ADirecciones+Territoriales%0D%0ADireccion+ATM%0D%0ADirectivos%0D%0AEfectivo%0D%0AGestion+de+Tarjetas%0D%0AHardware%0D%0AJuridico%0D%0AMarketing%0D%0AMensajeria%0D%0AOCD%0D%0APlanificacion%0D%0APresidente%0D%0AProcedimientos%0D%0ARecursos+Humanos%0D%0ARed+Sucursales%0D%0ARiesgo%0D%0ASeguridad+Informatica%0D%0AServicios+Generales%0D%0ASistema%0D%0ASucursal+Electronica%0D%0ASucursales%0D%0ATelebanca%0D%0AVicepresidencia%0D%0A&submit=Enviar">>,{{192,168,157,251},1560},<<"192.168.23.31">>,5280,[{web_admin,true},{protocol_options,<<"no_sslv3|no_tlsv1|no_tlsv1_1|cipher_server_preference|no_compression">>},{tls,true},{request_handlers,[{[<<"api">>],mod_http_api},{[<<"bosh">>],mod_bosh},{[<<"ws">>],ejabberd_http_ws}]}],https,[{<<"Sec-Fetch-User">>,<<"?1">>},{<<"Sec-Fetch-Site">>,<<"same-origin">>},{<<"Sec-Fetch-Mode">>,<<"navigate">>},{<<"Sec-Fetch-Dest">>,<<"document">>},{<<"Upgrade-Insecure-Requests">>,<<"1">>},{'Cookie',<<"PHPSESSID=i...">>},...],...}]`

**Comment by licaon-kter** [comment]
> The version that I am using is the one that comes in the debian 10 repositories

18.12 from Buster or
21.01 from Buster-backports?

**Comment by sherlock9712** [comment]
18.12 from buster

**Comment by prefiks** [comment]
Hello,

I think this is result of having made mistake in domain name of one of added user (that i think belongs to different group, but which group you try to edit is displayed to). This i think should be fixed in newer version of ejabberd.

To rescue current state without update you could use ejabberd debug console (on machine where ejabberd is running you can execute `ejabberdctl debug` to enter it).

In console you can type:
```
rp((fun(H)->lists:flatmap(fun(G)->lists:filtermap(fun({_,H2}=U) when H /= H2 ->{true,{G,U}}; (_) ->false end, mod_shared_roster:get_group_explicit_users(H, G)) end, mod_shared_roster:list_groups(H)) end)(<<"test.domain.com">>)).
```
(please replace "test.domain.com" with what you are really using).
This should produce list with entries like `{<<"test.domain.com">>, {<<"user">>, <<"bad.domain.com">>}, <<"test">>}`, now if that data is indeed wrong you can use `mod_shared_roster:remove_user_from_group(<<"test.domain.com">>,  {<<"user">>, <<"bad.domain.com">>}, <<"test">>)` to remove that user (after replacing it with data that you really see).

To exit console press ctrl-c twice.

**Comment by ticktostick** [comment]
This problem was present in versions 20 to 21.04 
I am not sure if its in 21.07 or not 
don't know the cause
