### ISSUE TITLE
Stream management still working from clients

### ISSUE THREAD

**Issue by praveenoms** [processone/ejabberd#378]
Hi 
I disable stream management support in Yml file
## XEP-0198

stream_management: false
resend_on_timeout: true
resume_timeout: 60
max_ack_queue: 1000
But my Clients still able to connect with  stream..
is there something wrong with EJD 14.07? or there is any other way to Stop SM support on server

**Comment by Nitin3588** [comment]
in my case i set it true but not getting expected results

**Comment by Nitin3588** [comment]
i am still loosing messages while i was disconnected from internet 

listen:
  -
    port: 5222
    module: ejabberd_c2s
    stream_management: true
   resend_on_timeout: true
   resume_timeout: 60
   max_ack_queue: 1000

**Comment by weiss** [comment]
> in my case i set it true but not getting expected results

Does your client support [Stream-Management][1]?  If so, are you loosing messages when the client that's *sending* the messages is disconnected, or when the client that's *receiving* messages is disconnected?  Is there an easy way for you to get a dump of the corresponding XMPP stream?

[1]: http://xmpp.org/extensions/xep-0198.html

**Comment by Nitin3588** [comment]
Thanks weiss, 

 my client is yaxim and it  does , my sender is connected but the receiver loosing connectivity after it  reconnects and comes online it  gets nothing even from sender all messages those are not acknowledged are as it is.i have mod_archive module which is having all those unacknowledged messages too that means all those unack are at server .

**Comment by weiss** [comment]
I see.  I haven't seen such an issue with Yaxim personally yet.

I'd suggest setting `loglevel: 5` and then grepping for the relevant log lines when this happens again, e.g.:

    egrep '(Send|Received) XML' ejabberd.log

Of course, only the communication with the client in question is interesting, and only the last few packets transmitted over the old connection plus the first few sent over the new connection.

*Note: This will include authentication credentials which you should of course filter out before showing the log output to anyone.*

**Comment by Nitin3588** [comment]
you mean that server  be sending those messages but  my client is not showing it  after receiving them , i will go through log and would share with you  too.

**Comment by weiss** [comment]
Am 6. August 2015 16:50:27 MESZ, schrieb Nitin3588 <notifications@github.com>:
>you mean that server  be sending those messages but  my client is not
>showing it  after receiving them

I don't mean anything, I have no idea what's happening.  Looking at the traffic will probably help.

**Comment by Nitin3588** [comment]
Thanks weiss

**Comment by Nitin3588** [comment]
Hi,

Weiss , 
I am using mod_post_log for logging ,but in my log file i am not receiving data in body ,my Body parameter is empty ?

**Comment by mremond** [comment]
It seems that the ticket is diverging, as it does not seem your latest comment is related to stream management. Am I wrong ?

**Comment by weiss** [comment]
>I am using mod_post_log for logging ,but in my log file i am not
>receiving data in body ,my Body parameter is empty ?

I don't use mod_post_log and can't help with that; but according to the README file, it's only meant to log message stanzas. In order to debug your issue, you would want to look at the complete XMPP traffic transmitted during the relevant time frame.

**Comment by Nitin3588** [comment]
Sorry to put this issue here, but i was looking for the related ones but didn't  get any .
thanks .
