### ISSUE TITLE
Compiling 21.12 on Ubuntu 20.4 ARM

### ISSUE THREAD

**Issue by cvele** [processone/ejabberd#3783]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 21.12
- Erlang version: 10.6.4
- OS: Ubuntu 20.4 **ARM**
- Installed from: source 

## Errors from error.log/crash.log

No errors

## Bug description

I am trying to set up ejabberd server on AWS. Latest image available of Ubuntu is 20.4 which sadly has Ejabberd 20.1 in package repository. This version does not support http auth as stated in contrib readme:

>This module requires ejabberd 20.02 or higher.
compile 21.12 
>https://github.com/processone/ejabberd-contrib/blob/master/ejabberd_auth_http/README.md

As a workaround I am trying to compile from source. (if there are other workarounds I'm happy to try)

This is what I have tried:

```
apt-get install -y gcc make rebar build-essential nghttp2  erlang-dev  erlang-eunit libnghttp2-dev libssl-dev libncurses5-dev openssl libssl-dev fop xsltproc unixodbc-dev libwxbase3.0 libwxgtk3.0-gtk3-dev autoconf libz-dev libexpat1-dev libyaml-dev

cd /opt
wget https://static.process-one.net/ejabberd/downloads/21.12/ejabberd-21.12.tgz
tar xvfz ejabberd-21.12.tgz 
cd ejabberd-21.12
./configure
make
```

This results with error:

```
==> ejabberd-21.12 (configure-deps)
/usr/lib/erlang/bin/escript rebar compile && :> deps/.built
==> base64url (compile)
==> p1_utils (compile)
==> cache_tab (compile)
==> eimp (compile)
==> ezlib (compile)
==> fast_tls (compile)
==> fast_xml (compile)
==> fast_yaml (compile)
==> unicode_util_compat (compile)
==> idna (compile)
Killed
make: *** [Makefile:154: deps/.built] Error 137
```

Looking at makefile:

```
sed -n 154p Makefile
gives:
$(REBAR) compile && :> $(DEPSDIR)/.built
```

Running rebar compile with verbose on results in:

```
/usr/lib/erlang/bin/escript rebar compile -vvv && :> $(DEPSDIR)/.built
```

Result: https://gist.github.com/cvele/f84c530d0490c90f283491771e6e405a

At this point CPU reaches 100% on both cores. I am unsure if it is related. Any advice?

**Comment by cvele** [comment]
Following that last remark I've increased to slightly larger instance and compile passed that step so I guess KILL was due to no resources.

However, there is a new error:

```INFO:  Looking for yconf-.* ; found yconf-1.0.12 at /opt/ejabberd-21.12/deps/yconf
DEBUG: Starting 3 compile worker(s)
DEBUG: Worker exited cleanly
DEBUG: Worker exited cleanly
Compiling src/eldap_filter_yecc.yrl failed:
DEBUG: Worker compilation failed: {{error,
                                    {'EXIT',
                                     {undef,
                                      [{yecc,file,
                                        ["src/eldap_filter_yecc.yrl",
                                         [{parserfile,
                                           "src/eldap_filter_yecc.erl"},
                                          {return,true}]],
                                        []},
                                       {rebar_erlc_compiler,compile_xrl_yrl,
                                        5,
                                        [{file,"src/rebar_erlc_compiler.erl"},
                                         {line,585}]},
                                       {rebar_base_compiler,compile_worker,3,
                                        [{file,"src/rebar_base_compiler.erl"},
                                         {line,216}]}]}}},
                                   {source,
                                    {"src/eldap_filter_yecc.yrl",
                                     "src/eldap_filter_yecc.erl"}}}
ERROR: compile failed while processing /opt/ejabberd-21.12: rebar_abort``

**Comment by cvele** [comment]
Adding `libyaml-dev` resolved the issue

**Comment by badlop** [comment]
> Adding libyaml-dev resolved the issue

That packge is surely required... But you had already installed it, right? It's mentioned in the line `apt-get install ...`  that you showed before.

> As a workaround I am trying to compile from source. (if there are other workarounds I'm happy to try)

Compiling is usually preferable, as you have full control of what's going on. An alternative was:
https://ejabberd.messaging.one/
