### ISSUE TITLE
Merge chat history from different clients

### ISSUE THREAD

**Issue by taiBsu** [processone/ejabberd#3787]
Hi,
I would like to know if if's possible to merge the chat history of multiple clients. For example, when using Gajim on one machine A with another machine B being shutdown, when chatting, my chat history won't be shown on machine B when turning that one on afterwards. Is there a way to get around this?

Thanks in advance.

**Comment by licaon-kter** [comment]
The example config has MAM and Carbons enabled, that covers having messages in both clients no matter their state.

Did you read these 3-4 articles? They cover everything you'd need:

 https://www.process-one.net/blog/how-to-move-the-office-to-real-time-im-on-ejabberd/

https://www.process-one.net/blog/how-to-set-up-ejabberd-video-voice-calling/

https://www.process-one.net/blog/how-to-configure-ejabberd-to-get-100-in-xmpp-compliance-test/

https://www.process-one.net/blog/ejabberd-xmpp-server-useful-configuration-steps/

**Comment by taiBsu** [comment]
Hi @licaon-kter,
thanks a lot for the quick answer! I adjusted some settings (e.g. set `mam: true` and added some other settings at `mod_mam`) and will see how it works out. I'll close this issue as soon as I find it working! Thanks.

**Comment by licaon-kter** [comment]
Note that MAM is an account setting, so you need a client that can enable it, then any client can retrieve the messages (if it supports MAM of course)

**Comment by taiBsu** [comment]
Perfect, it works! Thanks a lot again for helping out a newbie.
