### ISSUE TITLE
Problems migrating Mnesia to MariaDB/MySQL in Docker container

### ISSUE THREAD

**Issue by taiBsu** [processone/ejabberd#3789]
## Environment

- ejabberd version: latest
- Erlang version: ?
- OS: Linux (Ubuntu) running Docker
- Installed from: Docker Hub

## Bug description

I'm running ejabberd as a Docker container with docker-compose. When installing it I decided to use Mnesia, but now I want to switch to MySQL. I already imported the `mysql.sql` file successfully, however trying to execute one of the functions given in [the docs](https://docs.ejabberd.im/tutorials/mysql/#migrating-data-from-internal-database-to-mysql) always gives me an error:

```
~/docks/xmpp/data $ docker exec -it xmpp ejd2sql:export("myhost", sql).
zsh: no matches found: ejd2sql:export(myhost, sql).

~/docks/xmpp/data $ docker exec -it xmpp ejd2sql
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ejd2sql": executable file not found in $PATH: unknown
```

What am I doing wrong here? 
I'm sorry if this is the wrong place for this kind of question.

**Comment by licaon-kter** [comment]
You should exec `ejabberdctl live` and then, inside that shell.... do the export

See the docs again.

**Comment by taiBsu** [comment]
I'm sorry, I missed to put this information in my first post: trying to call `ejabberdctl live` gives me a similar error:
```
~/docks/xmpp/data $ docker exec -it xmpp ejabberdctl live
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ejabberdctl": executable file not found in $PATH: unknown
```

It appears that none of the ejabberd command-line commands can be called through docker-compose, is that correct?

**Comment by taiBsu** [comment]
Addition: I've found out that the executable path was not correct.
```
~/docks/xmpp/data  docker exec -it xmpp bin/ejabberdctl live
ERROR: The ejabberd node 'ejabberd@taibsu' is already running.
```
So I should probably shutdown the container first and manually call `bin/ejabberdctl live` after rebooting it with something like `command: sleep 999999`?

**Comment by taiBsu** [comment]
Alright, I got as far as being able to access the Erlang console:

```
~/docks/xmpp $ docker exec -it xmpp bin/ejabberdctl debug
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

*** ERROR: Shell process terminated! (^G to start new job) ***

User switch command
 --> s
 --> c
Eshell V10.5  (abort with ^G)
(4fd-debug-ejabberd@myhost)1> ejd2sql:export(<<"myhost">>, sql).
** exception error: nif_not_loaded
     in function  erlang:nif_error/1
        called as erlang:nif_error(nif_not_loaded)
     in call from stringprep:nameprep/1 (/ejabberd/deps/stringprep/src/stringprep.erl, line 60)
     in call from jid:nameprep/1 (/ejabberd/deps/xmpp/src/jid.erl, line 194)
     in call from ejd2sql:export/2 (src/ejd2sql.erl, line 67)
(4fd-debug-ejabberd@myhost)2>
```

That's the farthest I get. Is this supposed to happen?

**Comment by licaon-kter** [comment]
Which ejabberd version exactly?

**Comment by taiBsu** [comment]
According to the docker-hub latest tag, this would be `21.12`.

**Comment by prefiks** [comment]
Strange, not sure if ejabberd is running correctly... You probably can fix that exact error by executing `stringprep:start().` in debug console.

**Comment by taiBsu** [comment]
That solved one problem, however it brought up another:

```
(a84-debug-ejabberd@myhost)1> stringprep:start().
ok
(a84-debug-ejabberd@myhost)5> ejd2sql:export(<<"myhost">>, sql).
** exception error: bad argument
     in function  ets:lookup_element/3
        called as ets:lookup_element(ejabberd_options,{sql_type,global},2)
     in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 162)
     in call from ejabberd_config:get_option/1 (src/ejabberd_config.erl, line 165)
     in call from ejd2sql:export/4 (src/ejd2sql.erl, line 167)
     in call from ejd2sql:'-export2/4-fun-0-'/5 (src/ejd2sql.erl, line 91)
     in call from lists:foreach/2 (lists.erl, line 1338)
     in call from ejd2sql:export2/4 (src/ejd2sql.erl, line 89)
     in call from lists:foreach/2 (lists.erl, line 1338)
```

**Comment by prefiks** [comment]
Yes, it doesn't look like ejabberd finished initialization. Could you check if is there something in logs? Maybe it tries read something from sql db?

**Comment by taiBsu** [comment]
No, unfortunately not:
```
xmpp    | 2022-03-08 13:37:49.177461+00:00 [info] Loading configuration from /home/ejabberd/conf/ejabberd.yml
xmpp    | 2022-03-08 13:37:49.688665+00:00 [info] Configuration loaded successfully
xmpp    | 2022-03-08 13:37:51.040916+00:00 [info] Got no NOTIFY_SOCKET, notifications disabled
xmpp    | 2022-03-08 13:37:51.489036+00:00 [info] Loading modules for localhost and myhost.org
xmpp    | 2022-03-08 13:37:51.716791+00:00 [info] Going to offer STUN/TURN service: 172.24.0.12:3478 (udp)
xmpp    | 2022-03-08 13:37:51.952130+00:00 [info] Building MQTT cache for localhost, this may take a while
xmpp    | 2022-03-08 13:37:51.967943+00:00 [info] Going to offer STUN/TURN service: 172.24.0.12:3478 (udp)
xmpp    | 2022-03-08 13:37:51.971083+00:00 [info] Building MQTT cache for myhost.org, this may take a while
xmpp    | 2022-03-08 13:37:52.063269+00:00 [info] Waiting for Mnesia synchronization to complete
xmpp    | 2022-03-08 13:37:52.074380+00:00 [warning] Invalid certificate in /etc/letsencrypt/live/localhost/fullchain.pem: at line 71: certificate is signed by unknown CA
xmpp    | 2022-03-08 13:37:52.251812+00:00 [warning] No certificate found matching localhost
xmpp    | 2022-03-08 13:37:52.252067+00:00 [warning] No certificate found matching conference.localhost
xmpp    | 2022-03-08 13:37:52.252310+00:00 [warning] No certificate found matching upload.localhost
xmpp    | 2022-03-08 13:37:52.252688+00:00 [warning] No certificate found matching conference.myhost.org
xmpp    | 2022-03-08 13:37:52.253009+00:00 [warning] No certificate found matching pubsub.localhost
xmpp    | 2022-03-08 13:37:52.253382+00:00 [warning] No certificate found matching proxy.myhost.org
xmpp    | 2022-03-08 13:37:52.253813+00:00 [warning] No certificate found matching pubsub.myhost.org
xmpp    | 2022-03-08 13:37:52.254041+00:00 [warning] No certificate found matching proxy.localhost
xmpp    | 2022-03-08 13:37:52.254204+00:00 [info] ejabberd 21.12.0 is started in the node ejabberd@taibsu in 3.26s
xmpp    | 2022-03-08 13:37:52.254726+00:00 [info] Start accepting UDP connections at 0.0.0.0:3478 for ejabberd_stun
xmpp    | 2022-03-08 13:37:52.255019+00:00 [info] Start accepting TCP connections at 172.24.0.12:7777 for mod_proxy65_stream
xmpp    | 2022-03-08 13:37:52.255047+00:00 [info] Start accepting TCP connections at [::]:5269 for ejabberd_s2s_in
xmpp    | 2022-03-08 13:37:52.255078+00:00 [info] Start accepting TLS connections at [::]:5443 for ejabberd_http
xmpp    | 2022-03-08 13:37:52.255458+00:00 [info] Start accepting TCP connections at [::]:1883 for mod_mqtt
xmpp    | 2022-03-08 13:37:52.255684+00:00 [info] Start accepting TLS connections at 0.0.0.0:5349 for ejabberd_stun
xmpp    | 2022-03-08 13:37:52.255682+00:00 [info] Start accepting TCP connections at [::]:5280 for ejabberd_http
xmpp    | 2022-03-08 13:37:52.255620+00:00 [info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
xmpp    | 2022-03-08 13:37:52.255719+00:00 [warning] No HTTP listeners for ACME challenges are configured, automatic certificate requests are aborted. Hint: configure the listener and restart/reload ejabberd. Or set acme->auto option to `false` to suppress this warning.
xmpp    | 2022-03-08 13:37:57.363572+00:00 [info] (<0.845.0>) Accepted connection [::ffff:1.2.3.4]:53041 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:37:57.463386+00:00 [warning] (tls|<0.845.0>) Failed c2s SCRAM-SHA-256 authentication for user2@myhost.org from ::ffff:1.2.3.4: Invalid username or password
xmpp    | 2022-03-08 13:38:04.347454+00:00 [info] (<0.848.0>) Accepted connection [::ffff:1.2.3.4]:36702 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:38:04.411457+00:00 [info] (<0.849.0>) Accepted connection [::ffff:1.2.3.4]:45556 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:38:04.487602+00:00 [warning] (tls|<0.848.0>) Failed c2s SCRAM-SHA-512 authentication for user1@myhost.org from ::ffff:1.2.3.4: Invalid username or password
xmpp    | 2022-03-08 13:38:04.504358+00:00 [warning] (tls|<0.849.0>) Failed c2s SCRAM-SHA-512 authentication for user2@myhost.org from ::ffff:1.2.3.4: Invalid username or password
xmpp    | 2022-03-08 13:38:48.110570+00:00 [info] (<0.850.0>) Accepted connection [::ffff:1.2.3.4]:45562 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:38:48.165727+00:00 [warning] (tls|<0.850.0>) Failed c2s SCRAM-SHA-512 authentication for user2@myhost.org from ::ffff:1.2.3.4: Invalid username or password
xmpp    | 2022-03-08 13:38:49.172999+00:00 [info] (<0.851.0>) Accepted connection [::ffff:5.6.7.8]:28553 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:38:49.400445+00:00 [warning] (tls|<0.851.0>) Failed c2s SCRAM-SHA-512 authentication for user3@myhost.org from ::ffff:5.6.7.8: Invalid username or password
xmpp    | 2022-03-08 13:38:49.537337+00:00 [info] (<0.852.0>) Accepted connection [::ffff:5.6.7.8]:28577 -> [::ffff:172.24.0.12]:5222
xmpp    | 2022-03-08 13:38:49.773745+00:00 [warning] (tls|<0.852.0>) Failed c2s SCRAM-SHA-512 authentication for user3@myhost.org from ::ffff:5.6.7.8: Invalid username or password
```

**Comment by taiBsu** [comment]
I'm getting the same behavior when moving the database of my existing installation to the fresh one. could this be a configuration issue?

**Comment by taiBsu** [comment]
Maybe the question is which steps to do first on migration.
My ejabberd docker instance is running permanently so I would like to have as short as possible of a shutdown here.

My approach so far was:

1. shutdown the ejabberd docker container (`docker-compose down`)
2. add following into `ejabberd.yml` below `hosts: - ...`:
```
sql_type: mysql
sql_server: "databaseserver"
sql_database: "mydatabase"
sql_username: "myuser"
sql_password: "myp4$$w0rd"

default_db: sql

auth_method:
  - sql
```
3. start ejabberd docker container (which will result in every client getting an error message complaining about false credentials): `docker-compose up -d`
4. enter Erlang shell `docker exec -it ejabberd bin/ejabberdctl debug` 
5. error message will pop up: `*** ERROR: Shell process terminated! (^G to start new job) ***`
6. Press `Ctrl+G`; `--> s`, `--> c`
7. `(6ec-debug-ejabberd@myhost)1>` --> enter `ejd2sql:export(<<"myhost">>, sql).`
8. `** exception error: nif_not_loaded` (etc.)
9. `(6ec-debug-ejabberd@myhost)2>` --> enter `stringprep:start().`
10. `** exception error: bad argument` (etc., see above)

Maybe this helps debugging the issue.

**Comment by prefiks** [comment]
Ah, so you aren't really connecting to remote node (that ctrl+g, s starts local shell), that would explain that error.

Could you see if  ctrl+g -> r ejabberd goes further?

**Comment by taiBsu** [comment]
Here's what happens when using `r ejabberd` instead of `s`:
```
~/docks/xmpp $ docker exec -it xmpp bin/ejabberdctl debug
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

*** ERROR: Shell process terminated! (^G to start new job) ***

User switch command
 --> r ejabberd
 --> c
*** ERROR: Shell process terminated! (^G to start new job) ***

```
Is it possible that this is an issue of some data inside the database? I have setup two databases, one is mostly empty with only one admin user and nothing else, the other one is my productive one. For the **empty one**, the migration works completely flawless without even having that `ERROR: Shell process terminated!` error popping up when starting the Erlang prompt.

**Comment by prefiks** [comment]
Did you initialize sql schema in mysql db?

**Comment by taiBsu** [comment]
> Are you able to run debug shell when sql is not configured?

no, same problem when using the productive database.
By the way, when talking about "database" I mean the ejabberd internal database (Mnesia), in this case my productive database is ejabberd@myhost and the empty database is ejabberd@xmpp_test.

> Did you initialize sql schema in mysql db?

Yes I am. As stated before, I can also flawlessly migrate to this SQL DB from the empty test database ejabberd@xmpp_test.

**Comment by taiBsu** [comment]
@prefiks is it possible that I can only migrate an empty Mnesia database (with no messages etc. at all) to SQL?

**Comment by prefiks** [comment]
Well i didn't test that code in ages, so it can be buggy, but you didn't even get to stage where that update could be attempted as i understand. You need to be able attach remote debug shell to running ejabberd to do that, and it's not working for you. I did test with latest ejabberd/ecs container, and i didn't have problem with starting debug shell, so not sure why this is not working in your installation.

One more thing are you able to run `ejabberdctl export2sql /path/to/somewhere/dump.sql`? Or is that failing as well. That path must be somewhere that ejabberd can write (and i think it will write that inside docker volume?)

**Comment by taiBsu** [comment]
Tested it:
```
~/docks/xmpp $ docker exec -it xmpp bin/ejabberdctl export2sql /tmp/dump.sql
Failed RPC connection to the node ejabberd@myhost: nodedown

Commands to start an ejabberd node:
(...)
```
Note that both containers are up and running at that time.

Same error comes up for both the productive container with no SQL connection and for the test container with SQL connection configured (they use the same Mnesia database `ejabberd@myhost`).
For the test container with the almost **empty** Mnesia database (`ejabberd@xmpp_test`, nothing but a single user), I get following output:
```
~/docks/xmpp_test $ docker exec -it xmpp_t bin/ejabberdctl export2sql /tmp/dump.sql
  Command Name: export2sql

  Arguments: host::string
             file::string

  Returns: res::rescode

  Tags: mnesia

  Module: unknown

  Description: Export virtual host information from Mnesia tables to SQL file

 Configure the modules to use SQL, then call this command. After correctly exported the database of a vhost, you may
want to delete from mnesia with the http://./#delete-mnesia[delete_mnesia] command.

Error: the command 'export2sql' requires 1 more argument.
```

**Comment by prefiks** [comment]
Could you see if docker exec -it xmpp bin/ejabberdctl --node ejabberd@127.0.0.1 export2sql /tmp/dump.sql works on that first node?

**Comment by taiBsu** [comment]
Unfortunately it doesn't, I get an instant `nodedown` error message.

**Comment by prefiks** [comment]
Then looks like ejabberd is not working correctly or something is blocking network communicaiton...

**Comment by taiBsu** [comment]
So it looks like I will have to setup the whole server from scratch to be able to use it with MySQL?

**Comment by taiBsu** [comment]
Do I maybe need to open a certain port to be able to use this command?
I opened:
```
ports:
      - 5222:5222
      - 5280:5280
      - 5443:5443
      - 1884:1883
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
```

**Comment by prefiks** [comment]
You are running ejabberdctl inside docker container so it shouldn't require port mapping for that. Possibly server trying to communicate with sql server but is not able thanks to port mapping issues, and it get stuck in initialization when doing this?

Could you try doing `docker exec -it xmpp sh` and in that `ps -A|grep beam` and `bin/epmd -names`?

**Comment by taiBsu** [comment]
output:

```
~ $ ps -A | grep beam
    1 ejabberd  0:04 /home/ejabberd/bin/beam.smp -K true -P 250000 -- -root /home/ejabberd -progname erl -- -home /home/ejabberd -- -sname ejabberd@myhost -smp enable -kernel inet_dist_listen_min 4370 inet_dist_listen_max 4379 -mnesia dir "/home/ejabberd/database/ejabberd@myhost" -ejabberd log_rotate_size 10485760 log_rotate_count 1 -s ejabberd -noshell -noinput --
 1260 ejabberd  0:00 grep beam
```

and:
```
~ $ bin/epmd -names
epmd: up and running on port 4369 with data:
name 8c4-ctl-ejabberd at port 4371
name ejabberd at port 4370
```

**Comment by prefiks** [comment]
Just for completness what happen if you execute `bin/ejabberdctl debug` in that shell?

**Comment by taiBsu** [comment]
of course:
```
~ $ bin/ejabberdctl debug
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

*** ERROR: Shell process terminated! (^G to start new job) ***
```

**Comment by prefiks** [comment]
Ok, i don't know at that point what could cause it, sorry.

**Comment by taiBsu** [comment]
Alright, I have now rebuilt the infrastructure from scratch in SQL. very unfortunate but who knows what caused the issue in the end. if someone's interested I could maybe share some of the unimportant database files for debugging purposes.
