### ISSUE TITLE
Are self-signed certificates valid or not ?

### ISSUE THREAD

**Issue by shodanx2** [processone/ejabberd#3793]
```
2022-03-13 23:12:15.940 [warning] <0.380.0>@ejabberd_pkix:log_warnings:393 Invalid certificate in /etc/ejabberd/ejabberd.pem: at line 1: self-signed certificate
```

It says "Invalid certificate" but it's also just a warning.. ..

But also, nothing works, do I need to do something else to make ejabberd accept this certificate ?

Both pidgin and UWPX report error "UNKNOWN_HOST" with no further explanations. 

We won't be depending on any other external infrastructure. The self-signed certificate is "it". 

No choice but to disable more  and more security features until it works. It would have been nice to have descriptive error messages to debug this setup !

**Comment by licaon-kter** [comment]
Depends, how did you generate the cert? It's for the host defined in `hosts:` right?

**Comment by shodanx2** [comment]
Certificates created with these commands

openssl req -new -newkey rsa:4096 -nodes -keyout mycert.key -out mycert.csr
openssl x509 -req -sha256 -days 365 -in mycert.csr -signkey mycert.key -out mycert.pem

mycert.pem and mycert.key we copied over as /etc/ejabberd/ejabberd.pem and /etc/ejabberd/ejabberd.key

error message should say

@ejabberd_pkix:log_warnings:393 Using valid but self-signed certificate /etc/ejabberd/ejabberd.pem, 

As this would remove ambiguity between invalid as in "containing an error"  versus invalid as in "self-signed certificates are not valid"

**Comment by licaon-kter** [comment]
Unknown host means DNS issue, not ejabberd issue I guess.

Do get the full error from a client, eg. Better test Gajim or Conversations.
