### ISSUE TITLE
Ssl for Ejabberd

### ISSUE THREAD

**Issue by hyperedgesystems** [processone/ejabberd#3798]
I have setup an Ejabberd server on a old buntu 20.04 server, and it works in everything but ssl..

Thats where I run into problems, you see, prosody and other xmpp servers will let you use certbot (Opensll), but for some reason when I link to my certificates, it wont work.

I wouldn't really care so much about ssl, because I can use most xmpp clients on it, such as pidgon, but I am trying to use conversions, witch requires a ssl connection.

I would really appreciate it if someone would take the time to help me figure this out. Thanks!

**Comment by weiss** [comment]
> it wont work.

Could you describe what's happening?  For example, are you seeing any error messages in your `ejabberd.log` and/or on the client-side and if so, what messages exactly?  (Don't we have an issue template asking for such things?)

**Comment by licaon-kter** [comment]
TLS is a core requirement for XMPP.

Pidgin2 is an old program that is no longer developed, try to use Gajim or Dino, and of course Conversations and Siskin.

Which ejabberd version? How did you install? Certbot for Let's Encrypt or selfsigned? What error does ejabberd.log or error.log have listed?

**Comment by hyperedgesystems** [comment]
Certbot for Let's Encrypt. How do I tell the version?

**Comment by hyperedgesystems** [comment]
I just would like to know how to isuue a ssl certificate for ejabberd, I couldn't find anything online.

**Comment by licaon-kter** [comment]
`sudo ejabberdctl status`

`sudo apt policy ejabberd`

**Comment by hyperedgesystems** [comment]
● ejabberd.service - XMPP Server
     Loaded: loaded (/etc/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-05 19:04:34 UTC; 53min ago
   Main PID: 7526 (ejabberdctl)
      Tasks: 30 (limit: 4599)
     Memory: 50.7M
     CGroup: /system.slice/ejabberd.service
             ├─7526 /bin/sh /opt/ejabberd-21.07/bin/ejabberdctl foreground
             ├─7555 /opt/ejabberd-21.07/bin/beam.smp -K true -P 250000 -- -root /opt/ejabberd-21.07 -progname /opt/ej>
             ├─7575 /opt/ejabberd-21.07/bin/epmd -daemon
             ├─7579 erl_child_setup 65536
             ├─7600 inet_gethost 4
             ├─7601 inet_gethost 4
             └─7602 /opt/ejabberd-21.07/lib/os_mon-2.4.7/priv/bin/memsup

Apr 05 19:21:01 c.ehvengate.com ejabberdctl[7555]: 19:21:01.727 [info] Created MUC room test@conference.c.ehvengate.c>
Apr 05 19:22:08 c.ehvengate.com ejabberdctl[7555]: 19:22:08.075 [info] (<0.605.0>) Accepted connection [::ffff:192.16>
Apr 05 19:27:08 c.ehvengate.com ejabberdctl[7555]: 19:27:08.640 [info] (<0.611.0>) Accepted connection [::ffff:192.16>
Apr 05 19:32:11 c.ehvengate.com ejabberdctl[7555]: 19:32:11.048 [info] (<0.616.0>) Accepted connection [::ffff:192.16>
Apr 05 19:37:12 c.ehvengate.com ejabberdctl[7555]: 19:37:12.981 [info] (<0.621.0>) Accepted connection [::ffff:192.16>
Apr 05 19:41:09 c.ehvengate.com ejabberdctl[7555]: 19:41:09.751 [info] (<0.626.0>) Accepted connection [::ffff:45.132>
Apr 05 19:42:13 c.ehvengate.com ejabberdctl[7555]: 19:42:13.545 [info] (<0.627.0>) Accepted connection [::ffff:192.16>
Apr 05 19:47:15 c.ehvengate.com ejabberdctl[7555]: 19:47:15.537 [info] (<0.633.0>) Accepted connection [::ffff:192.16>
Apr 05 19:52:17 c.ehvengate.com ejabberdctl[7555]: 19:52:17.566 [info] (<0.637.0>) Accepted connection [::ffff:192.16>
Apr 05 19:53:52 c.ehvengate.com ejabberdctl[7555]: 19:53:52.721 [info] (<0.640.0>) Accepted connection [::ffff:45.132>
lines 1-25/25 (END)

**Comment by hyperedgesystems** [comment]
ejabberd:
  Installed: 21.07-0
  Candidate: 21.07-0
  Version table:
 *** 21.07-0 100
        100 /var/lib/dpkg/status
     20.01-1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

**Comment by hyperedgesystems** [comment]
Does that help? I am not sure, but it does not look like there
 is any errors here

**Comment by hyperedgesystems** [comment]
your welcome to try it out on conversations for yourself if you want

**Comment by hyperedgesystems** [comment]
I am actually pressed for time, as I am trying to switch from one server to the next, so please help.

**Comment by licaon-kter** [comment]
So what does not work exactly? What error does Conversations show?

`grep error ejabberd.log` outputs nothing?

Did you read any guides on how to setup?

Eg.

https://www.process-one.net/blog/how-to-move-the-office-to-real-time-im-on-ejabberd/

https://www.process-one.net/blog/how-to-set-up-ejabberd-video-voice-calling/

https://www.process-one.net/blog/how-to-configure-ejabberd-to-get-100-in-xmpp-compliance-test/

https://www.process-one.net/blog/ejabberd-xmpp-server-useful-configuration-steps/  

Also put a bookmark on https://docs.ejabberd.im

**Comment by hyperedgesystems** [comment]
yes, I looked at some documentations of installation and configuration, but none of them says really anything about ssl, which is my problem::

Here are a few screenshots of converstions and the error:

![Caphture](https://user-images.githubusercontent.com/101427977/161845663-fe0d4a2c-1f69-479b-9f1c-9497717077d9.JPG)
![Capture](https://user-images.githubusercontent.com/101427977/161845665-2785f705-e308-4d68-8dfb-8b2254a28048.JPG)

**Comment by hyperedgesystems** [comment]
Really I could reinstall Ejabberd again, configuring ssl correctly if I knew how.

**Comment by hyperedgesystems** [comment]
My two choices were Zulip or Ejabberd, I chose Ejabberd as it seemed alot faster to install and configure, and import the messages and databases from the other server... If I cannot figure this out tonight, I guess I'll have to go with zulip, although I really like Ejabberd.

**Comment by badlop** [comment]
> Domain not verifiable

Yes, I get that same error message when using a certificate that Conversations detects like this:

`Valid for: *.localhost`

I created a self-signed certificate for the domain "localhost", and now Conversations says this, and accepts it, and I can login:

`Valid for: localhost`

> how to isuue a ssl certificate for ejabberd

You can let ACME do it

https://docs.ejabberd.im/admin/configuration/basic/#acme

**Comment by licaon-kter** [comment]
> Here are a few screenshots of converstions and the error:

Did you enable DNSSEC in Expert settings in Conversations?

**Comment by licaon-kter** [comment]
No, no, don't touch it. See advice above.

**Comment by hyperedgesystems** [comment]
ok, I am installing it again, I will se if that fixed the error

**Comment by hyperedgesystems** [comment]
now I am running into a problem installing Ejabberd: 

 sudo cp $(sudo find / -name ejabberd.service) /etc/systemd/system
service@chat:~$ sudo systemctl daemon-reload
service@chat:~$ sudo systemctl enable --now ejabberd
Synchronizing state of ejabberd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ejabberd
Created symlink /etc/systemd/system/multi-user.target.wants/ejabberd.service → /etc/systemd/system/ejabberd.service.
Job for ejabberd.service failed because the control process exited with error code.
See "systemctl status ejabberd.service" and "journalctl -xe" for details.
service@chat:~$ systemctl status ejabberd.service
● ejabberd.service - XMPP Server
     Loaded: loaded (/etc/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-04-06 16:23:41 UTC; 1s ago
    Process: 5887 ExecStart=/opt/ejabberd-21.07/bin/ejabberdctl foreground (code=exited, status=1/FAILURE)
   Main PID: 5887 (code=exited, status=1/FAILURE)
service@chat:~$

**Comment by licaon-kter** [comment]
ejabberd.log says what?

**Comment by hyperedgesystems** [comment]
Same thing

**Comment by hyperedgesystems** [comment]
systemctl status ejabberd.service
● ejabberd.service - XMPP Server
Loaded: loaded (/etc/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Wed 2022-04-06 16:23:41 UTC; 1s ago
Process: 5887 ExecStart=/opt/ejabberd-21.07/bin/ejabberdctl foreground (code=exited, status=1/FAILURE)
Main PID: 5887 (code=exited, status=1/FAILURE)

**Comment by hyperedgesystems** [comment]
ok, I would use a newer version, but haven't a documentation to help for that version

**Comment by hyperedgesystems** [comment]
ok, I figured out the problem, had something to do with the a record on my domain name... Going on to certificate testing...

**Comment by hyperedgesystems** [comment]
There was a problem running the ACME  command:

root@uosib:~# ejabberdctl request-certificate all
Error: error
Error: "HTTP error: unexpected content type: text/html"
root@uosib:~# ejabberdctl request-certificate uosib.ehvengate.com,pubsub.uosib.ehvengate.com,conference.uosib.ehvengate.com,
Error: error
Error: "HTTP error: unexpected content type: text/html"
root@uosib:~#

**Comment by hyperedgesystems** [comment]
is there a full in depth tutorial on how to setup ACME on Ejabberd?

**Comment by licaon-kter** [comment]
> ejabberd.log says what?

Could you please show the contents of THE FILE named `ejabberd.log` and NOT systemd tools output?

**Comment by hyperedgesystems** [comment]
ok
