### ISSUE TITLE
Ejabberd Push Notifications Progress

### ISSUE THREAD

**Issue by salihgenctan** [processone/ejabberd#3802]
Hello everyone, i want to ask the how ejabberd manages the pushing notification? How does the progress work? If i can, how can i configured my ejabberd to manage the notifications? Thanks for your replies :)

**Comment by licaon-kter** [comment]
You are publishing your own app to Google Play or Apple Store?

Or just have users that have clients from Google Play and Apple Store?

**Comment by salihgenctan** [comment]
> You are publishing your own app to Google Play or Apple Store?
> 
> Or just have users that have clients from Google Play and Apple Store?

For now, I am working on my own local, i developing a chat app and want to reach more people. I want to understand teh progress because i researched and i found a few information about FCM and APNS but i dont understand the progress.

**Comment by licaon-kter** [comment]
Well, in the app you setup the tokens and what's needed (see Play or Store docs) & you host your own push server like this [one for ejabberd](https://github.com/iNPUTmice/p2) or the [other for prosody](https://github.com/tmolitor-stud-tu/mod_push_appserver/).

**Comment by salihgenctan** [comment]
Thanks. I'll look at these :)
