### ISSUE TITLE
eJabberd crash mod_offline_sql

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3805]
## Environment

- ejabberd version: 21.04
- Erlang version: 9.2
- OS: Linux (Debian)
- Installed from: source 

## Errors from error.log/crash.log

2022-04-16 19:32:07 =ERROR REPORT====
** State machine 'ejabberd_sql_xxxxx.xxx.xxx.xxx_17' terminating
** Last message in was {'$gen_sync_event',{<0.24214.625>,#Ref<0.2951023328.42729477.128882>},{sql_cmd,{sql_transaction,#Fun<mod_offline_sql.58.44929770>},-576003144779}}
** When State == session_established
**      Data  == {state,<0.17566.0>,pgsql,120008,<<"xxxxx.xxx.xxx.xxx">>,{{[],[]},0,10000},undefined}
** Reason for termination =
** {killed,{gen_server,call,[<0.17566.0>,{squery,[<<"begin;">>]},59000]}}
2022-04-16 19:32:07 =CRASH REPORT====
  crasher:
    initial call: ejabberd_sql:init/1
    pid: <0.17565.0>
    registered_name: 'ejabberd_sql_xxxxx.xxx.xxx.xxx_17'
    exception exit: {{killed,{gen_server,call,[<0.17566.0>,{squery,[<<"begin;">>]},59000]}},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: ['ejabberd_sql_sup_xxxxx.xxx.xxx.xxx',ejabberd_db_sup,ejabberd_sup,<0.11157.0>]
    message_queue_len: 2
    messages: [{'$gen_sync_event',{<0.1165.591>,#Ref<0.2951023328.145489921.25716>},{sql_cmd,{sql_bloc,#Fun<mod_pubsub.90.24759915>},-576003141138}},{'EXIT',<0.17566.0>,killed}]
    links: [<0.17532.0>]
    dictionary: [{{ejabberd_sql_prepare,<<"Q122129639">>},prepared},{{ejabberd_sql_prepare,<<"Q3958015">>},prepared},{{ejabberd_sql_prepare,<<"Q90846017">>},prepared},{{ejabberd_sql_prepare,<<"Q127760301">>},prepared},{{ejabberd_sql_prepare,<<"Q23537011">>},prepared},{{ejabberd_sql_prepare,<<"Q101622520">>},prepared},{{ejabberd_sql_prepare,<<"Q31669562">>},prepared},{ejabberd_sql_state,{state,<0.17566.0>,pgsql,120008,<<"xxxxx.xxx.xxx.xxx">>,{{[],[]},0,10000},undefined}},{{ejabberd_sql_prepare,<<"Q2159096">>},prepared},{{ejabberd_sql_prepare,<<"Q116946964">>},prepared},{{ejabberd_sql_prepare,<<"Q10433863">>},prepared},{{ejabberd_sql_prepare,<<"Q123145603">>},prepared},{{ejabberd_sql_prepare,<<"Q46452909">>},prepared},{{ejabberd_sql_prepare,<<"Q11337792">>},prepared},{{ejabberd_sql_prepare,<<"Q11720729">>},prepared},{{ejabberd_sql_prepare,<<"Q78569084">>},prepared},{{ejabberd_sql_prepare,<<"Q69351967">>},prepared},{{ejabberd_sql_prepare,<<"Q79638816">>},prepared},{'$internal_queue_len',0},{{ejabberd_sql_prepare,<<"Q69042354">>},prepared},{{ejabberd_sql_prepare,<<"Q120500223">>},prepared},{{ejabberd_sql_prepare,<<"Q115430510">>},prepared},{{ejabberd_sql_prepare,<<"Q130601109">>},prepared},{{ejabberd_sql_prepare,<<"Q69011250">>},prepared},{{ejabberd_sql_prepare,<<"Q4627495">>},prepared},{{ejabberd_sql_prepare,<<"Q74001322">>},prepared},{{ejabberd_sql_prepare,<<"Q67071337">>},prepared},{{ejabberd_sql_prepare,<<"Q60683484">>},prepared},{{ejabberd_sql_prepare,<<"Q65586287">>},prepared},{ejabberd_sql_nesting_level,0},{{ejabberd_sql_prepare,<<"Q37448423">>},prepared},{{ejabberd_sql_prepare,<<"Q56832057">>},prepared},{{ejabberd_sql_prepare,<<"Q44259032">>},prepared},{{ejabberd_sql_prepare,<<"Q22965591">>},prepared}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 51421223
  neighbours:
2022-04-16 19:32:07 =SUPERVISOR REPORT====
     Supervisor: {local,'ejabberd_sql_sup_xxxxx.xxx.xxx.xxx'}
     Context:    child_terminated
     Reason:     killed
     Offender:   [{pid,<0.13683.0>},{id,76},{mfargs,{ejabberd_sql,start_link,[<<"xxxxx.xxx.xxx.xxx">>,76]}},{restart_type,transient},{shutdown,2000},{child_type,worker}]

## Bug description

eJabberd crashed and killed multiple pids. Which DB query could be the root cause of this issue.

**Comment by licaon-kter** [comment]
So this worked before but not today?

**Comment by logicwonder** [comment]
Intermittent crashes simlar to this has happened previously too. Can you provide an approach to debug the root cause?

**Comment by logicwonder** [comment]
Can you provide an approach to debug this issue?

**Comment by licaon-kter** [comment]
Put your config on https://gist.github.com and paste the link

**Comment by logicwonder** [comment]
https://gist.github.com/logicwonder/9c4252de93e7cfd4c2abfe93e8c0c09a

**Comment by licaon-kter** [comment]
Can you lower the sql pool size to the default 10 _(both places I mean)_ ? Why did you raise it so high? How many users are you serving?

**Comment by prefiks** [comment]
That process was probably killed by memory pressure service (aka almost running out of memory), could you check error.log and see if there is some mention about that?

**Comment by logicwonder** [comment]
@licaon-kter I have kept a high limit since the number of actve users are arounf 100K
@prefiks There was free memory when this issue occoured. A fragment of error log during the crash is given below:

2022-04-16 19:31:40.952 [error] <0.24893.635>@ejabberd_sql:check_error:1230 SQL query 'Q127760301' at {node_flat_sql,399} failed: <<"timed out">>
2022-04-16 19:31:40.966 [error] <0.23849.630>@ejabberd_sql:check_error:1230 SQL query 'Q127760301' at {node_flat_sql,399} failed: <<"timed out">>
2022-04-16 19:31:41.046 [error] <0.1395.590>@ejabberd_sql:check_error:1230 SQL query 'Q127760301' at {node_flat_sql,399} failed: <<"timed out">>
2022-04-16 19:31:41.341 [error] <0.17703.0>@ejabberd_sql:check_error:1230 SQL query 'Q101622520' at {nodetree_tree_sql,158} failed: <<"timed out">>
2022-04-16 19:31:43.694 [error] <0.28153.630>@ejabberd_sql:check_error:1230 SQL query 'Q2159096' at {mod_last_sql,62} failed: <<"timed out">>
2022-04-16 19:31:45.754 [error] <0.9985.620>@ejabberd_sql:check_error:1230 SQL query 'Q127760301' at {node_flat_sql,399} failed: <<"timed out">>
2022-04-16 19:31:47.624 [error] <0.17535.0>@ejabberd_sql:check_error:1230 SQL query 'Q101622520' at {nodetree_tree_sql,158} failed: <<"timed out">>
2022-04-16 19:31:47.670 [error] <0.8475.634>@ejabberd_sql:check_error:1230 SQL query 'Q101622520' at {nodetree_tree_sql,158} failed: <<"timed out">>
2022-04-16 19:31:59.952 [error] <0.17727.0>@ejabberd_sql:sql_query_internal:645 Internal error while processing SQL query:
** exception exit: {noproc,
                     {gen_server,call,
                         [<0.17728.0>,
                          {execute,
                              {<<"Q3958015">>,
                               [<<"xxxxxx@xxxx.xxx.xxx.xx">>,
                                <<"pubsub.xxxxxx@xxxx.xxx.xxx.xx">>]}}]}}
   in function  gen_server:call/2 (gen_server.erl, line 206)
   in call from ejabberd_sql:pgsql_execute_sql_query/2 (src/ejabberd_sql.erl, line 804)
   in call from ejabberd_sql:sql_query_internal/1 (src/ejabberd_sql.erl, line 626)
   in call from ejabberd_sql:sql_query_t/1 (src/ejabberd_sql.erl, line 181)
   in call from node_flat_sql:get_entity_affiliations/2 (src/node_flat_sql.erl, line 340)
   in call from mod_pubsub:node_call/4 (src/mod_pubsub.erl, line 3821)
   in call from mod_pubsub:'-do_transaction/4-fun-0-'/3 (src/mod_pubsub.erl, line 3876)
   in call from ejabberd_sql:execute_bloc/1 (src/ejabberd_sql.erl, line 570)
2022-04-16 19:32:01.434 [error] <0.19384.0> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.15844.626> exit with reason killed in context child_terminated

**Comment by logicwonder** [comment]
The issue seems to be related to concurrent queries being fired on SQL DB. Closing the issue.
