### ISSUE TITLE
Logs to ELK

### ISSUE THREAD

**Issue by eliteaz** [processone/ejabberd#3807]
as I understand ejabberd uses standard Erlang logging output
I would like to know if there is any solution ejbberd service `error` and `crash` logs send to elastic or journalctl ?
even i see that info notices is sending to journal.

**Comment by logicwonder** [comment]
This would be a great feature addition. A structured log format that could be parsed using a grok expression would be ideal for logstash. The eJabberd.log, error.log and crash.log formats may be allowed to be user defined in configuration.

**Comment by logicwonder** [comment]
Currently I am parsing the eJabberd logs in realtime and preparing logs in structured format compatible with Logstash. However the structure of the log needs to be such that every event in the log is contained in a single line. But the log record for mod_http_api request is spanning multiple lines as there are new lines used for formatting. See an example below:

2022-06-24 16:57:45.511712+05:30 [info] <0.13521.2285>@mod_http_api:log/3:511 API call change_password [{<<"host">>,<<"xxxx.xxxx.xxx.xxx">>},
                          {<<"newpass">>,
                           <<"xxxxxxxxxxxxxxxxxxxx">>},
                          {<<"user">>,<<"yyyyyyyyyyyyy">>}] from ::ffff:xxxx.xxx.xxx.xxx:62004

2022-06-24 16:56:23.005693+05:30 [info] <0.15324.1512>@mod_http_api:log/3:511 API call stats_host [{<<"host">>,<<"xxxx.xxxx.xxx.xx">>},
                     {<<"name">>,<<"onlineusers">>}] from ::ffff:xxxx.xxx.xxx.xxx:36668


It would be great if the log is made parsable by wrapping this into a single line. A basic setting for log format with values like standard, pretty etc. would be a great feature.

**Comment by logicwonder** [comment]
Thanks @badlop. Will explore the logstash libraries. Where do I need to apply these changes in eJabberd for writing logs in standard syntax?

**Comment by badlop** [comment]
I pushed this commit to my fork repository. It works for me: https://github.com/badlop/ejabberd/commit/8c0da87012a9f72f2e869e93b733bead168febb5

[0001-Experimental-support-to-send-logs-to-logstash-using-.patch](https://github.com/user-attachments/files/22465161/0001-Experimental-support-to-send-logs-to-logstash-using-.patch)

I just learned about logstash, so you may need to update configuration, etc for a real production usage.

Please comment your results, and whatever improvements you make for a real usage.

**Comment by badlop** [comment]
Apparently this was an error generated by Erlang/OTP's SASL application. I could not reproduce that case. If anybody has a clue to reproduce that problem, please give some instructions.

**Comment by rhclayto** [comment]
Apparently this patch was never merged, but the issue is closed. Is there a way to log to journald in the official ejabberd?

**Comment by Neustradamus** [comment]
@rhclayto: I think it is better to open a new ticket.
