### ISSUE TITLE
Vcard4 LDAP 

### ISSUE THREAD

**Issue by ticktostick** [processone/ejabberd#3811]
ejabbered 21.12
Currently LDAP vcard only supports vcard v1 I think
Please consider support vcard4 for ldap vcard map

**Comment by lovetox** [comment]
This seems to be a duplicate https://github.com/processone/ejabberd/issues/3535

**Comment by ticktostick** [comment]
its duplicate

**Comment by Neustradamus** [comment]
@badlop, @prefiks: Can you look?
