### ISSUE TITLE
Importing users from prosody fails for those with SCRAM

### ISSUE THREAD

**Issue by Lykos153** [processone/ejabberd#3814]
## Environment

- ejabberd version: 22.05
- OS: Linux (Debian)
- Installed from: github docker image

## Errors from error.log
`2022-05-17 00:45:49.009784+00:00 [error] <0.1040.0>@prosody2ejabberd:convert_data/4:154 Failed to register user ****@****: {error,invalid_password}`

## Bug description
Importing from prosody fails for all users that have SCRAM enabled. It only works for those that still have the plain password in their .dat file.

An example .dat file that does not import:

```
return {
        ["server_key"] = "2a4db7e344c9b1636d7bb0621b03fe1e4638e06b";
        ["salt"] = "06b6cd9e-6843-47cd-9d13-67d694ee7186";
        ["iteration_count"] = 10000;
        ["stored_key"] = "92f737a95d3f16609ede274bd3aa06f374a4b8d8";
};
```

**Comment by licaon-kter** [comment]
ejabberd config?

**Comment by prefiks** [comment]
Could you try editing one of those .dat files, and change '["iteration_count"] = 10000;' to '["iteration_count"] = 10000.0;' and see if this makes it be properly imported?

**Comment by Lykos153** [comment]
That did, indeed, work! 🎉

**Comment by prefiks** [comment]
Ok, looks like update of library that we use to parse lua files (that prosody used) did lead to change in type of data it produces, and that made us not correctly detecting scram passwords (and use empty string as password instead). I prepared 99064548e85d6eed9bfbe27fb5a4aee2d04836fe that should improve this.
