### ISSUE TITLE
DESTDIR leaks into installed ejabberdctl starting with 22.05

### ISSUE THREAD

**Issue by arekm** [processone/ejabberd#3819]
## Environment

- ejabberd version: 22.05
- (version 21.12 was  ok)
- OS: Linux
- Installing from source tarball

## Bug description

````
cd 22.05
./configure --prefix=/usr [additional options, paths...]
rm -f ejabberdctl.example # just to be sure since it doesn't get recreated on subsequent make installs
make install DESTDIR=/tmp/testing CHOWN_COMMAND=true O_USER="" G_USER=""
````

and unfortunately DESTDIR leaks into installed ejabberdctl:

````
$ grep /tmp/testing ejabberdctl.example
: "${CONFIG_DIR:="/tmp/testing/etc/jabber"}"
: "${LOGS_DIR:="/tmp/testing/var/log/ejabberd"}"
: "${SPOOL_DIR:="/tmp/testing/var/lib/ejabberd"}"
$ grep /tmp/testing /tmp/testing/usr/sbin/ejabberdctl
: "${CONFIG_DIR:="/tmp/testing/etc/jabber"}"
: "${LOGS_DIR:="/tmp/testing/var/log/ejabberd"}"
: "${SPOOL_DIR:="/tmp/testing/var/lib/ejabberd"}"
````

DESTDIR should never leak into installed files. It's job is to only install in different directory (like /tmp/testing) BUT application is supposed to be in a state like DESTDIR never existed.
 
Above should be:
````
: "${CONFIG_DIR:="/etc/jabber"}"
: "${LOGS_DIR:="/var/log/ejabberd"}"
: "${SPOOL_DIR:="/var/lib/ejabberd"}"
````

Docs about DESTDIR: https://www.gnu.org/software/automake/manual/automake.html#DESTDIR

"The package should be configured as if it was going to be installed in its final location (e.g., --prefix /usr), but when running make install, the DESTDIR should be set to the absolute name of a directory into which the installation will be diverted."

**Comment by Flowdalic** [comment]
FWIW, [I ran into the same issue when packaging ejabberd for Gentoo](https://github.com/gentoo/gentoo/blob/770a0460a98e9245802321714ee2350fd230497d/net-im/ejabberd/ejabberd-22.05-r1.ebuild#L146-L152).

**Comment by badlop** [comment]
It seems I introduced this problem in 45c7fbb5ae3760073691dd25745ba415283d920c

This patch works for me, both `make rel` and your example `make install DESTDIR=...`. If you can give it a try to confirm it works, or somebody wants to provide an alternative solution, before committing:

<details>

```diff
From a75ad174f2d2c5f27470278b7987ef45b92ef99d Mon Sep 17 00:00:00 2001
From: Badlop <badlop@process-one.net>
Date: Thu, 19 May 2022 12:05:50 +0200
Subject: [PATCH] Fix to not leak DESTDIR into ejabberdctl (#3819)

---
 Makefile.in | 15 +++++++++------
 1 file changed, 9 insertions(+), 6 deletions(-)

diff --git a/Makefile.in b/Makefile.in
index 16e713ebe..06472ac8d 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -10,7 +10,8 @@ exec_prefix = @exec_prefix@
 DESTDIR =
 
 # /etc/ejabberd/
-ETCDIR = $(DESTDIR)@sysconfdir@/ejabberd
+ETCDIRRAW = @sysconfdir@/ejabberd
+ETCDIR = $(DESTDIR)$(ETCDIRRAW)
 
 # /bin/
 BINDIR = $(DESTDIR)@bindir@
@@ -66,10 +67,12 @@ SQLDIR = $(PRIVDIR)/sql
 LUADIR = $(PRIVDIR)/lua
 
 # /var/lib/ejabberd/
-SPOOLDIR = $(DESTDIR)@localstatedir@/lib/ejabberd
+SPOOLDIRRAW = @localstatedir@/lib/ejabberd
+SPOOLDIR = $(DESTDIR)$(SPOOLDIRRAW)
 
 # /var/log/ejabberd/
-LOGDIR = $(DESTDIR)@localstatedir@/log/ejabberd
+LOGDIRRAW = @localstatedir@/log/ejabberd
+LOGDIR = $(DESTDIR)$(LOGDIRRAW)
 
 INSTALLUSER=@INSTALLUSER@
 # if no user was enabled, don't set privileges or ownership
@@ -299,9 +302,9 @@ ejabberdctl.relive:
 
 ejabberdctl.example: vars.config
 	$(SED)  -e "s*{{installuser}}*@INSTALLUSER@*g" \
-		-e "s*{{config_dir}}*${ETCDIR}*g" \
-		-e "s*{{logs_dir}}*${LOGDIR}*g" \
-		-e "s*{{spool_dir}}*${SPOOLDIR}*g" \
+		-e "s*{{config_dir}}*${ETCDIRRAW}*g" \
+		-e "s*{{logs_dir}}*${LOGDIRRAW}*g" \
+		-e "s*{{spool_dir}}*${SPOOLDIRRAW}*g" \
 		-e "s*{{bindir}}*@bindir@*g" \
 		-e "s*{{libdir}}*@libdir@*g" \
 		-e "s*{{erl}}*@ERL@*g" \
-- 
2.34.1
```
</detail>

**Comment by prefiks** [comment]
@badlop 
Ah didn't seen your comment before commiting 75a771bfec3626145d404349fdaec4f0eef83bbc.
My change is a bit more complex (Instead of just changing what we feed to sed, i did change to all $(INSTALL) lines.
If you think your version is better (it simpler for sure), we could revert this and commit what you did.

**Comment by prefiks** [comment]
And my change also need to update paths in ejabberdctl.relive, so probably we should just apply your patch

**Comment by nosnilmot** [comment]
My 2c: the approach in https://github.com/processone/ejabberd/commit/75a771bfec3626145d404349fdaec4f0eef83bbc is more standard and preferable (and I'm not sure there are additional changes needed for ejabberdctl.relive, but I am only looking at the diff, have not tried it).

**Comment by prefiks** [comment]
I was wrong about ejabberdctl.relive, it didn't use any path that had DESTDIR prefix, so my commit didn't change anything here.

**Comment by badlop** [comment]
Right, with your already committed fix, all works for me: `make relive`, `make rel` and `make install DESTDIR=...`.

**Comment by arekm** [comment]
The nice fix would be also to get these .example files created at 'make' time now, cleaned up at 'make clean' and 'make install' only installs what was done at 'build' stage.

**Comment by badlop** [comment]
That's a different problem, let's track it independently in https://github.com/processone/ejabberd/issues/3821
