### ISSUE TITLE
Blocklists and Privacy Lists incompatible

### ISSUE THREAD

**Issue by SamWhited** [processone/ejabberd#382]
According to XEP-0191 (Blocking Command):

> When implementing both XEP-0191 and XEP-0016, a service SHOULD map the blocklist to the default privacy list, where each blocked JID is represented as a privacy list item of type "jid" and action "deny". [8] If this is done and none of the user's clients ever use the privacy lists protocol, then the blocklist will always apply.

However, when I block a contact using Gajim (which uses XEP-0016), and then sign in using another client (eg. Pidgin) which uses XEP-0191, I am sent an empty blocklist.

I've also noticed that if I block a contact using both methods (first with XEP-0191, then with XEP-0016) and then request the default privacy list with XEP-0016, the contact is listed in the list twice.

**Comment by zinid** [comment]
> Modify mod_block to work independantly of mod_privacy so that server admins can decide if they want this incomptibility
Too much of a hassle, given that Privacy Lists are already deprecated. I close the issue.
