### ISSUE TITLE
Delete all messages of ONE muc Room

### ISSUE THREAD

**Issue by cesar-cardinale** [processone/ejabberd#3834]
**Describe the solution i'd like**
I'm trying to find a nice solution to delete all the history (messages) of a MUC Room, is that possible ?
Like there is a command 'delete_old_mam_messages_batch' but there is no possibility to define the MUC Room of which messages to delete are related.
Is there something that I don't understand or this feature is really not possible actually in Ejabberd 22.05 ?

Thank you.

**Comment by prefiks** [comment]
Ah, indeed it uses server part to lookup config file, which will not work for subdomains.

Looking at it i see there is `clear_archive_on_room_destroy: true` option on mod_mam, that should delete room history when room is destroyed for example with command `destroy_room room conference.localhost` (you need to have mod_muc_admin enabled for that) or just from client.

**Comment by cesar-cardinale** [comment]
Thank you for your help, I used that.
