### ISSUE TITLE
Listen config, no bind on reload if address was (detected) in use once

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3850]
## Environment

- ejabberd version: 46c947bc76c34bd6b1d09347828acaa685d76795
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.0.1` _(self build Erlang 25.0.1)_
- OS: Debian Bullseye arm64
- Installed from: source

## Configuration

```yaml
  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      "/ws": ejabberd_http_ws
      "/http-bind": mod_bosh
    tls: true
    protocol_options: 'TLS_OPTIONS'
    dhfile: 'DH_FILE'
    ciphers: 'TLS_CIPHERS'
```

## Bug description

Wanted to simplify setup, so XEP-0156 via https://docs.ejabberd.im/admin/configuration/modules/#mod-host-meta, reloaded
```
[info] <0.11179.0>@ejabberd_config:reload/0:98 Reloading configuration from /usr/local/etc/ejabberd/ejabberd.yml
[info] <0.11179.0>@ejabberd_listener:stop_listener/3:402 Stop accepting TLS connections at 0.0.0.0:5443 for ejabberd_http
[info] <0.11186.0>@ejabberd_listener:init/4:160 Start accepting TLS connections at 0.0.0.0:5443 for ejabberd_http
[info] <0.11179.0>@ejabberd_config:reload/0:115 Configuration reloaded successfully
```
... decided against since it's all nginx/sslh/turtles down.

So I delete the added lines, reload...
```
[info] <0.11218.0>@ejabberd_config:reload/0:98 Reloading configuration from /usr/local/etc/ejabberd/ejabberd.yml
[info] <0.11218.0>@ejabberd_listener:stop_listener/3:402 Stop accepting TLS connections at 0.0.0.0:5443 for ejabberd_http
[error] <0.11225.0>@ejabberd_listener:report_socket_error/3:470 Failed to open socket at 0.0.0.0:5443 for ejabberd_http: address already in use
[info] <0.11218.0>@ejabberd_config:reload/0:115 Configuration reloaded successfully
```
Converse fails, error 502 for the websockets endpoint `/ws`
ejabberd is NOT listening on the port anymore.

**Oh wait, there's an error there...**

Now, the config reloads fine, yet ejabberd, after that initial error, doesn't even TRY to bind to that port, no error, no warning, has just given up without notice.

Note: There's no other program listening on that port, nor has ever been any other than ejabberd _(well `beam.smp` technically)_ I guess it tripped over its own feet at that moment.

_/PS: I bet a restart would fix this but I'd like for reload to do it._

**Comment by prefiks** [comment]
Strange, we do set reuseaddr flag when creating socket, so i would think that we should hit that problem. We are doing close/open in sequence, but maybe some parts are async and we do trip on that?

**Comment by prefiks** [comment]
I commited change that should at least allow to make second reload try to start listeners that wasn't started first time.

**Comment by licaon-kter** [comment]
I'll rebuild and retest asap

**Comment by licaon-kter** [comment]
Restarted, re-tested, reloaded, works so far.
