### ISSUE TITLE
User has multiple client presence to group chat room, return wrong presence response

### ISSUE THREAD

**Issue by cisiqo** [processone/ejabberd#3852]
## Environment

- ejabberd version: 21.12
- Erlang version: 25.0
- OS: ubuntu
- Installed from: source 

## Bug description

For example:
A Client JID: test1@example.com/Desktop
B Client JID: test1@example.com/Android

A Client login and presence to the room `test_room1@conference.example.com` with nick `test1`, then B Client login and presence to the room `test_room1@conference.example.com` with nick `test1` too.

After few seconds, A Client re-presence  to the room `test_room1@conference.example.com` with nick `test1`, then the server return wrong presence response.

I think the function `find_jid_by_nick` of mod_muc_room can not return correct current presence user.

```
find_jid_by_nick(Nick, StateData) ->
    try maps:get(Nick, StateData#state.nicks) of
	[User] -> jid:make(User);
	[FirstUser | Users] ->
	    #user{last_presence = FirstPresence} =
		maps:get(FirstUser, StateData#state.users),
	    {LJID, _} = lists:foldl(
			  fun(Compare, {HighestUser, HighestPresence}) ->
				  #user{last_presence = P1} =
				      maps:get(Compare, StateData#state.users),
				  case higher_presence(P1, HighestPresence) of
				      true -> {Compare, P1};
				      false -> {HighestUser, HighestPresence}
				  end
			  end, {FirstUser, FirstPresence}, Users),
	    jid:make(LJID)
    catch _:{badkey, _} ->
	    false
    end.
```

**Comment by badlop** [comment]
Can you update your problem description with those details?

> After few seconds, A Client re-presence to the room test_room1@conference.example.com with nick test1, 

What exact presence stanza does the client send.

> then the server return wrong presence response.

What exact error stanzas does the server return.

**Comment by cisiqo** [comment]
It's mean that A Client repeated presence to the room `test_room1@conference.example.com`, what I described above are the steps for this bug to appear.

The steps is:
A Client presence to test_room1@conference.example.com
B Client presence to test_room1@conference.example.com
A Client again presence to test_room1@conference.example.com


Presence stanza client send, A client:
```
<presence id="91f34e2611b244c1" from='test1@example.com/Desktop' to="test_room1@conference.example.com/test1"><show>chat</show><status>Online Now</status><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://github.com/qxmpp-project/qxmpp" ver="yIXIXdko2qIIpBMTUqc1VmFuvDo="/></presence>
```

B client:
```
<presence id="a5b7d1e25a66c550" from='test1@example.com/Android' to="test_room1@conference.example.com/test1"><show>chat</show><status>Online Now</status><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://github.com/qxmpp-project/qxmpp" ver="TUqc1VmFuvDo="/></presence>
```


When the A Client attends the second time the server returns B client presence info, like this:
```
<presence id='a5b7d1e25a66c550' to='test1@example.com/Desktop' from='test_room1@conference.example.com/test1'><x xmlns='http://jabber.org/protocol/muc#user'><item jid='test1@example.com/Android' role='moderator' affiliation='owner'/><status code='110'/></x></presence>
```

The correct return should be：
```
<presence id='91f34e2611b244c1' to='test1@example.com/Desktop' from='test_room1@conference.example.com/test1'><x xmlns='http://jabber.org/protocol/muc#user'><item jid='test1@example.com/Desktop' role='moderator' affiliation='owner'/><status code='110'/></x></presence>
```

They are different with `id` and `jid` of the item.

**Comment by cisiqo** [comment]
The client was in a weak network situation and it thinks it might be down away. So it will be repeated to presence.

My client presence does not set the priority node.

**Comment by badlop** [comment]
The ability to have several account sessions join a MUC room with the same nick is experimental, not defined in XEP-0045.

From what I see, the ejabberd implementation determines the exact session by:

-  X) XMPP priority (if it's defined in the presence stanza sent to the room)
-  Y) otherwise picks the most recent session that joined the room.

Example of case X) would be this presence sent to the MUC room:
```xml
<presence id='40:501689'
	to='test_room1@conference.example.com/test1'>
  <x xmlns='http://jabber.org/protocol/muc'>
    <password/>
    <history maxchars='10000000000000'
	maxstanzas='200000000'/>
  </x>
  <show>xa</show>
  <priority>99</priority>
  <status>Busysssdfdf</status>
</presence>
```

Otherwise, in case Y) this happens:
- A joins, B joins, A sends presence --> B presence is sent, because that's the one most recent to join the room
- A joins, B joins, B sends presence --> B presence is sent, because that's the one most recent to join the room
- A joins, B joins, A leaves, A joins, A sends presence --> A presence is sent, because that's the one most recent to join the room
- A joins, B joins, A leaves, A joins, B sends presence --> A presence is sent, because that's the one most recent to join the room

I wrote a small patch, that uses the sender resource. This patch is for ejabberd 21.12:

<details>

```diff
From 94d52bda5c6a7a3b29e13b7ad3718a009b370899 Mon Sep 17 00:00:00 2001
From: Badlop <badlop@process-one.net>
Date: Mon, 4 Jul 2022 11:21:22 +0200
Subject: [PATCH] Experimental code to determine session per resource, not
 priority (#3852)

---
 src/mod_muc_room.erl | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index e8b0d1bce..fdf16be1e 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -2015,6 +2015,16 @@ find_jid_by_nick(Nick, StateData) ->
 	    false
     end.
 
+find_jid_by_nick(Nick, Resource, StateData) ->
+    try maps:get(Nick, StateData#state.nicks) of
+	[User] -> jid:make(User);
+	Users when is_list(Users) ->
+	    LJID = lists:keyfind(Resource, 3, Users),
+	    jid:make(LJID)
+    catch _:{badkey, _} ->
+	    false
+    end.
+
 -spec higher_presence(undefined | presence(),
 		      undefined | presence()) -> boolean().
 higher_presence(Pres1, Pres2) when Pres1 /= undefined, Pres2 /= undefined ->
@@ -2453,7 +2463,7 @@ is_ra_changed(JID, _IsInitialPresence = false, NewStateData, OldStateData) ->
 send_new_presence(NJID, Reason, IsInitialPresence, StateData, OldStateData) ->
     LNJID = jid:tolower(NJID),
     #user{nick = Nick} = maps:get(LNJID, StateData#state.users),
-    LJID = find_jid_by_nick(Nick, StateData),
+    LJID = find_jid_by_nick(Nick, NJID#jid.lresource, StateData),
     #user{jid = RealJID, role = Role0,
 	  last_presence = Presence0} = UserInfo =
 	maps:get(jid:tolower(LJID), StateData#state.users),
-- 
2.34.1
```
</details>

**Comment by cisiqo** [comment]
Thanks ❤️

**Comment by Neustradamus** [comment]
@badlop and @cisiqo: The patch will be integrated in master?

It is possible to have an option to choice if "priority" (default) or "resource"?

**Comment by cisiqo** [comment]
Yes，i think it will be integrated in master.
The same resource and same priority will be appear the problem, so i think it may choice priority.
