### ISSUE TITLE
Unexpected Mysql Data

### ISSUE THREAD

**Issue by benni1516** [processone/ejabberd#3875]
Hello,
my Logs are flooded with this:
```
`2022-08-02 10:59:42.497273+02:00 [error] <0.2069.0>@ejabberd_sql:log/3:1082 p1_mysql_conn: Received MySQL data when not expecting any (num 0) - ignoring it
2022-08-02 10:59:42.497696+02:00 [error] <0.2069.0>@ejabberd_sql:log/3:1082 p1_mysql_conn: Unexpected MySQL data (num 0) :
<<255,191,48,84,103, 102,111,114,32,99,111,110,102,105,
  103,117,114,105,110,103,32,116,104,105,115,32,98,101,105,111,114,
  46>>
2022-08-02 10:59:42.498186+02:00 [error] <0.2069.0>@ejabberd_sql:log/3:1082 p1_mysql_conn: Connection closed, exiting.
2022-08-02 10:59:42.498374+02:00 [info] <0.2069.0>@ejabberd_sql:log/3:1081 Closing connection {gen_tcp,#Port<0.921>}: ok

2022-08-02 10:59:42.498540+02:00 [warning] <0.437.0>@ejabberd_sql:handle_reconnect/2:471 mysql connection failed:
** Reason: normal
** Retry after: 30 seconds`
```
Behavior doesn't seem to be influenced by this, ejabberd works as normal and uses the database (registered users are added in the database - seems to work as normal for me)
I have deleted many numbers from the mysql packet since i dont know what they even mean. (can someone explain?)
I've searched on the web but I can't find anything about those error messages.
Can anyone help please?

MySQL: 8.0.29
Debian 11
Ejabberd: 21.01-2

**Comment by licaon-kter** [comment]
ejabberd version?
mysql?
OS?
Details?

**Comment by badlop** [comment]
> I have deleted many numbers from the mysql packet since i dont know what they even mean. (can someone explain?)

In erlang, strings are sometimes represented as list of integers. For example, 97 is "a", etc. However, some numbers represent characters that cannot be printed in the erlang shell or erlang logs (usually small or big numbers). When a string contains such characters, erlang shows the list of integers, instead of the corresponding string:
```
$ erl
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Eshell V13.0.2  (abort with ^G)

1> [97, 98, 99, 100, 101].
"abcde"

2> [255,191,48,84,103, 102,111,114,32,99,111,110,102,105,
2>   103,117,114,105,110,103,32,116,104,105,115,32,98,101,105,111,114,
2>   46].
"ÿ¿0Tgfor configuring this beior."

3> [97, 98, 99, 100, 101, 20]. 
[97,98,99,100,101,20]

```
You can try this with parts of your list of integers, maybe there you get a clue about where does that problem come from.

**Comment by benni1516** [comment]
@badlop 
Thank you very much for this info!
I've tried this now, but I only get back other numbers.
```
root@ssljabber:/etc/ejabberd# erl
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V11.1.8  (abort with ^G)
1> [255,191,15,35,72,89,48,48,48,84,104,101,32,99,108,105,101,110,116,32,119,97,
1>   115,32,100,105,115,99,111,110,110,101,99,116,101,100,32,98,121,32,116,104,
1>   101,32,115,101,114,118,101,114,32,98,101,99,97,117,115,101,32,111,102,32,105,
1>   110,97,99,116,105,118,105,116,121,46,32,83,101,101,32,119,97,105,116,95,116,
1>   105,109,101,111,117,116,32,97,110,100,32,105,110,116,101,114,97,99,116,105,
1>   118,101,95,116,105,109,101,111,117,116,32,102,111,114,32,99,111,110,102,105,
1>   103,117,114,105,110,103,32,116,104,105,115,32,98,101,104,97,118,105,111,114,
1>   46].
[255,191,15,35,72,89,48,48,48,84,104,101,32,99,108,105,101,
 110,116,32,119,97,115,32,100,105,115,99,111|...]
2>
```

This is my list of integers:

255,191,15,35,72,89,48,48,48,84,104,101,32,99,108,105,101,110,116,32,119,97,
  115,32,100,105,115,99,111,110,110,101,99,116,101,100,32,98,121,32,116,104,
  101,32,115,101,114,118,101,114,32,98,101,99,97,117,115,101,32,111,102,32,105,
  110,97,99,116,105,118,105,116,121,46,32,83,101,101,32,119,97,105,116,95,116,
  105,109,101,111,117,116,32,97,110,100,32,105,110,116,101,114,97,99,116,105,
  118,101,95,116,105,109,101,111,117,116,32,102,111,114,32,99,111,110,102,105,
  103,117,114,105,110,103,32,116,104,105,115,32,98,101,104,97,118,105,111,114,
  46

Did I do something wrong?

**Comment by badlop** [comment]
Right. In fact, The string starts with some code number:
`ÿ¿#HY000The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior`

That error message may be generated by the mysql server, reported to ejabberd's mysql client, that doesn't know how to handle it?

**Comment by prefiks** [comment]
This is message from mysql server, try adding  `sql_keepalive_interval: 120s` to ejabberd config, this should make us issue dummy request each 2 minutes. If that will not help try decreasing value here (best just check what you mysql config has set in wait_timeout).

**Comment by benni1516** [comment]
Hello thank you all for writing back.

I have looked into the config of mysql, wait_timeout is 180 and interactive_timeout is 300

I have set sql_keepalive_interval to 120 seconds but I still get the same errors with the same mysql message

**Comment by benni1516** [comment]
Everything is working now.
After Reloading with the new config, there still were those same errors. Restarting worked tho:

```
2022-08-02 16:00:25.529657+02:00 [info] <0.2341.0>@ejabberd_config:reload/0:98 Reloading configuration from /etc/ejabberd/ejabberd.yml
2022-08-02 16:00:25.625981+02:00 [info] <0.2341.0>@ejabberd_config:reload/0:115 Configuration reloaded successfully
2022-08-02 16:01:00.919533+02:00 [error] <0.2317.0>@ejabberd_sql:log/3:1082 p1_mysql_conn: Received MySQL data when not expecting any (num 0) - ignoring it
2022-08-02 16:01:00.919983+02:00 [error] <0.2317.0>@ejabberd_sql:log/3:1082 p1_mysql_conn: Unexpected MySQL data (num 0) :
<<255,191,15,35,72,89,48,48,48,84,104,101,32,99,108,105,101,110,116,32,119,97,
  115,32,100,105,115,99,111,110,110,101,99,116,101,100,32,98,121,32,116,104,
  101,32,115,101,114,118,101,114,32,98,101,99,97,117,115,101,32,111,102,32,105,
  110,97,99,116,105,118,105,116,121,46,32,83,101,101,32,119,97,105,116,95,116,
  105,109,101,111,117,116,32,97,110,100,32,105,110,116,101,114,97,99,116,105,
  118,101,95,116,105,109,101,111,117,116,32,102,111,114,32,99,111,110,102,105,
  103,117,114,105,110,103,32,116,104,105,115,32,98,101,104,97,118,105,111,114,
  46>>
```

**Comment by benni1516** [comment]
Thank you all for helping me :)

**Comment by prefiks** [comment]
Looks like this option is only read when sql connection is initializing, so indeed just reload config will not work, workers would need to be restarted as well.
