### ISSUE TITLE
Ejabberd MQTT Session and Subscriptions Are Expiring After Some time

### ISSUE THREAD

**Issue by syedzahidulla** [processone/ejabberd#3887]
I have an app which subscribers to mqtt broker of ejabberd. if iam coming online very often then iam able to receive offline messages.

But if i close the app and come online after 3 -4 hrs then iam not able to receive messages and when i check in webadmin mqtt_session tables doesn't have any session.

**Comment by badlop** [comment]
See https://docs.ejabberd.im/admin/configuration/modules/#mod-mqtt

```
session_expiry: timeout()
 The option specifies how long to wait for an MQTT session resumption.
 When 0 is set, the session gets destroyed when the underlying client connection is closed.
 The default value is 5 minutes.
```

**Comment by syedzahidulla** [comment]
It takes value in seconds or minutes..I have kept 100 thinking minutes but its now working

**Comment by prefiks** [comment]
It takes both, you can use for example `5mins` for 5 minutes

**Comment by syedzahidulla** [comment]
Ok Thanks
