### ISSUE TITLE
mod_privilege is outdated

### ISSUE THREAD

**Issue by truenicoco** [processone/ejabberd#3889]
mod_privilege does not implement the latest revision of [XEP-0356](https://xmpp.org/extensions/xep-0356.html#revision-history-v0.4), which notably includes a namespace version bump, making it incompatible with components relying on this latest revision.

**Comment by ravermeister** [comment]
Any chance this will be implemented soon™?

**Comment by trungnt2910** [comment]
Any chances for this being updated?

I specifically need the [IQ permission](https://xmpp.org/extensions/xep-0356.html#iq) part, which was added in version 0.4.

Not opening a new issue to prevent duplicates...

**Comment by badlop** [comment]
I wrote a [small patch in the xmpp library](https://github.com/badlop/xmpp/commit/5e35b0308a7eb99382e2b7683de35c35114a8f21), and pointed ejabberd to use that one. Can you check if it works as expected?

- [ejabberd source code](https://github.com/badlop/ejabberd/tree/xep356ver041)
- [ejabberd binary installers](https://github.com/badlop/ejabberd/actions/runs/9210281402)
- [ejabberd container](https://github.com/badlop/ejabberd/pkgs/container/ejabberd/220195683?tag=xep356ver041)

**Comment by Neustradamus** [comment]
@truenicoco, @ravermeister, @trungnt2910: Have you tested?

It is good, it can be merged?

**Comment by mremond** [comment]
@badlop As we have no feedback at the moment, do you think the patch is good enough for inclusion in 24.07 ?

**Comment by sezuan** [comment]
I've tested the latest update. The server reports now iq permissions to the slidge gateway:

    <message to="whatsapp.<redacted>" from="<redacted>.de">
      <privilege xmlns="urn:xmpp:privilege:2">
        <perm type="outgoing" access="message"/>
        <perm type="both" access="roster"/>
        <perm type="both" access="iq"/>
        <perm type="none" access="presence"/>
      </privilege>
    </message>

Slidge still complains:

    WARNING:slidge.core.gateway.base:IQ privileges not granted for pubsub namespace, we cannot create the MDS node of matthias@<redacted>
    WARNING:slidge.core.gateway.base:IQ privileges not granted for pubsub#owner namespace, we cannot listen to the MDS events of matthias@<redacted>
    /venv/lib/python3.11/site-packages/slidge/group/room.py:901:UserWarning:IQ privileges (XEP0356) are not set, we cannot fetch the user bookmarks
    /venv/lib/python3.11/site-packages/slidge/group/room.py:924:UserWarning:IQ privileges (XEP0356) are not set, we cannot add bookmarks for the user

That might be because the iq permissions must be advertised per namespace.

**Comment by truenicoco** [comment]
Indeed, cf https://xmpp.org/extensions/xep-0356.html#example-8

```xml
<message from='capulet.net' to='pubub.capulet.lit' id='iq_perm_1'>
  <privilege xmlns='urn:xmpp:privilege:2'>
    <perm access='iq'>
      <namespace ns='http://jabber.org/protocol/pubsub' type='set' />
    </perm>
  </privilege>
</message>
```

**Comment by truenicoco** [comment]
Well, after all it seems that what this patch does is illegal, authorized IQ namespaces MUST be specified:

> To grant an "iq" permission, authorised namespaces must be specified 

> Server adversites "iq" permission by using a <perm> element with an 'access' attribute of the value "iq" and wihout 'type' attribute

I did push a patch in slidge that allows it anyway, so someone can test anyway if they want!

**Comment by badlop** [comment]
I've improved the previous patch: now it handles IQ permissions per namespace, sends and receives the forwarded stanza correctly, and I've tested it manually with a script. Now it should work correctly.

The ejabberd patch is https://github.com/badlop/ejabberd/commit/2f5ff8bacfb555a959f78baca4f2e27f77af75c9, which requires some [changes in the xmpp library](https://github.com/badlop/xmpp/commits/3889-privilege-iq/)

It would be great if somebody can test it with a real component:
- ejabberd can be compiled from that branch
- there are [installers](https://github.com/badlop/ejabberd/actions/runs/11109736986)
- and a [container](https://github.com/badlop/ejabberd/pkgs/container/ejabberd/281716215?tag=3889-privilege-iq)
