### ISSUE TITLE
'User Avatar' extension as defined in XEP-0084 deleted in 22.05?

### ISSUE THREAD

**Issue by Vladimir7i** [processone/ejabberd#3898]
Ejabberd 22.05 does not have XEP-0084 anymore? (for sync changed Avatar to your Roster)

on Ejabberd 18.09 it's worked, but after update to 22.05 is not anymore=(

**Comment by licaon-kter** [comment]
This config? https://gist.github.com/Vladimir7i/38774eb7d83afe9fd603c17619e60f6d

What error do you see? What's in error.log? How do you set ti?

**Comment by Vladimir7i** [comment]
my fault - it's work=)
