### ISSUE TITLE
does ejabberd support xmpp whitespace keepalive.

### ISSUE THREAD

**Issue by hackrole** [processone/ejabberd#390]
I saw  the rfc6120 suggest use keepalive for the long connection. 

and the xep-0304 was used to negotiating how to send keepalives in XMPP.

but I get the info by xep-0030 to the ejabberd c2s host, the return features not include keepalive.

so I want to know does the ejabberd suppert whitespace keepalive? and didnot this feature important?

**Comment by hackrole** [comment]
@rraptorr, I think the mod_ping and whitespace ping doesnot do the same things. and the whitespace ping is really needed, especially when use in the mobile which have a more unstable network env.

thanks both of you for your answter and time.

**Comment by nOmi7** [comment]
It does support i am using it

Sent from Yahoo Mail on Android
