### ISSUE TITLE
mod_http_upload with fixed URI

### ISSUE THREAD

**Issue by luke-jr** [processone/ejabberd#3906]
```
2022-09-15 21:41:03.055950+00:00 [error] <0.363.0>@mod_http_upload:start/2:133 Multiple virtual hosts can't use a single 'put_url' without the @HOST@ keyword
```

Why is this rule in place? All virtual hosts use the same `A` DNS record, and `@HOST@` does not point at the server...

**Comment by weiss** [comment]
> Why is this rule in place?

Because ejabberd needs a way to map HTTP queries to virtual host configurations.

> All virtual hosts use the same A DNS record, and @HOST@ does not point at the server...

Just use `put_url: "https://share.example.com/@HOST@/"` or whatever.

**Comment by mkassir95** [comment]
Hello @weiss 
I have a virtual host "localhost" so my put_url should be:  `"http://localhost/@HOST@/"` ?

**Comment by licaon-kter** [comment]
@mkassir95 `https://@HOST@`

**Comment by mkassir95** [comment]
@licaon-kter  thank you very much , I was confused because I saw different people are adding this parameter in a different way

**Comment by licaon-kter** [comment]
@mkassir95 each with their own needs and limitations, yes
