### ISSUE TITLE
Move `get_room_pid` from `mod_muc_admin` to `mod_muc`

### ISSUE THREAD

**Issue by sloonz** [processone/ejabberd#3908]
I would like to call `mod_muc_room:change_item` from a module I’m writing, but I need to get room's PID for that. `mod_muc_admin` has a `get_room_pid` function that does exactly that, but it’s unexported and I don’t plan to enable `mod_muc_admin` module anyway, so I have just copy-pasted the function in my module.

Would it be possible to move `mod_muc_admin:get_room_pid` to `mod_muc` module and export it ?

**Comment by prefiks** [comment]
We can export it, you don't need to enable mod_muc_admin in modules to use that function, it will work regardless

**Comment by prefiks** [comment]
And it was done in 4a22604701edea85519ee565f8cb23265db6f76b

**Comment by sloonz** [comment]
Thanks !
