### ISSUE TITLE
ejabberd website source download link returns 403

### ISSUE THREAD

**Issue by ian-kelling** [processone/ejabberd#3910]
https://www.process-one.net/en/ejabberd/downloads/ links to "Source Code Archive" https://www.process-one.net/downloads/downloads-action.php?file=/22.05/ejabberd-22.05.tgz which gives 403

**Comment by badlop** [comment]
Umm, right. It's strange, because the file is correctly linked in the [Archive](https://www.process-one.net/en/ejabberd/archive/) section, and can be downloaded from that other place.

**Comment by Metalhearf** [comment]
Hi. 
Good catch, thanks for the feedback!
The link should be fixed now.
