### ISSUE TITLE
Expose the pubsub#type field

### ISSUE THREAD

**Issue by edhelas** [processone/ejabberd#3914]
XEP-0060 exposes `pubsub#type`. This field has been recently redefined in Version [1.23.0](https://xmpp.org/extensions/attic/xep-0060-1.23.0.html) (2022-01-14)

It would be great to expose the configuration of this field and display in in the node metadata.

This change will be really useful for this XEP proposal that uses it extensively: https://github.com/xsf/xeps/pull/1211

**Comment by badlop** [comment]
Do you mean this simple patch:

```diff
diff --git a/src/mod_pubsub.erl b/src/mod_pubsub.erl
index 7b01c4af0..861b502db 100644
--- a/src/mod_pubsub.erl
+++ b/src/mod_pubsub.erl
@@ -969,6 +969,7 @@ node_disco_info(Host, Node, _From, _Identity, _Features) ->
 			  _ -> []
 		       end,
 		Meta = [{title, get_option(Options, title, <<>>)},
+			{type, get_option(Options, type, <<>>)},
 			{description, get_option(Options, description, <<>>)},
 			{owner, [jid:make(LJID) || {LJID, Aff} <- Affs, Aff =:= owner]},
 			{publisher, [jid:make(LJID) || {LJID, Aff} <- Affs, Aff =:= publisher]},
```

**Comment by edhelas** [comment]
Yes, it should also be set using the pubsub node configuration. 
Not sure if this patch is taking care of it 🤔

**Comment by badlop** [comment]
Probably doesn't take care of that. What exact XEP section and/or XEP example are you referring to?

**Comment by edhelas** [comment]
Sorry, my link was wrong, here is the correct one: https://xmpp.org/extensions/xep-0060.html#revision-history-v1.23.0
The pubsub#type field was redefined and clarified in this 0060 change. It is basically no more than a string from the XMPP server perspective (except if you want to apply the constraints related to the namespace set in the node pubsub#types).

**Comment by edhelas** [comment]
Basically from the server side, it is exactly the same thing as `pubsub#title`, set in the Pubsub node configuration.

You can check if the element has been set correctly using this kind of request: https://xmpp.org/extensions/xep-0060.html#example-18
And you can configure it this way: https://xmpp.org/extensions/xep-0060.html#owner-configure-submit

That's mostly it :)

**Comment by edhelas** [comment]
Redundant with #3820

**Comment by badlop** [comment]
Ok, let's see:

1. I install ejabberd from git
2. Create a node with https://xmpp.org/extensions/xep-0060.html#example-126
3. Submit node configuration with https://xmpp.org/extensions/xep-0060.html#example-147
4. Query node info with https://xmpp.org/extensions/xep-0060.html#example-17
5. I see the response contains
```xml
        <field var='pubsub#type'
	type='text-single'
	label='...'>
          <value>urn:example:e2ee:bundle</value>
        </field>
```

6. And, after applying the small patch mentioned in https://github.com/processone/ejabberd/issues/3914#issuecomment-1271485688, a disco#info query gets as result:

```xml
<iq xml:lang='es'
	to='hamlet@denmark.lit/elsinore'
	from='pubsub.shakespeare.lit'
	type='result'
	id='78:481808'>
  <query node='princely_musings'
	xmlns='http://jabber.org/protocol/disco#info'>
      ...
      <field var='pubsub#type'
	type='text-single'
	label='Payload type'>
        <value>urn:example:e2ee:bundle</value>
      </field>
```

Does that solve the problem?

**Comment by edhelas** [comment]
Looks good for me ! 
Thanks a lot for your time :)
