### ISSUE TITLE
Unable to read data from the transport connection: Connection reset by peer.

### ISSUE THREAD

**Issue by Vladimir7i** [processone/ejabberd#3916]
## Environment

- ejabberd version: 22.05
- Erlang version: `erl +V`
- OS: Linux (Debian 11)
- Installed from: official binary installer

No errors

## Bug description

On own client(from Unity) sometime I have error connection:
"One or more errors occurred. (Unable to read data from the transport connection: Connection reset by peer.)"

after that error I can't send any msg from client but ejabberd server show what my client is online(even if I close the build game client/unity editor). That error comeup from parse the tcp stream - it's just going to [catch (Exception e)], 
I use System.Net.SecurityProtocolType.Tls connection;

on ejabberd version 18.09 I don't saw this error/connection break;
by googling, changin tls etc = I have no idea how to fix it=( can someOne help me please?

**Comment by licaon-kter** [comment]
Server logs?

**Comment by Vladimir7i** [comment]
thare no any error on the server in log:

`2022-10-17 10:07:12.345441+02:00 [info] <0.9773.3>@ejabberd_c2s:process_auth_result/3:268 (tls|<0.9773.3>) Accepted c2s SCRAM-SHA-1 authentication for player5@blablaServer.com by sql backend from ::ffff:XX.XX.X.XX
2022-10-17 10:07:12.499426+02:00 [info] <0.9773.3>@ejabberd_c2s:bind/2:446 (tls|<0.9773.3>) Opened c2s session for player5@blablaServer.com/694271606351944445660XXX
2022-10-17 10:17:09.443890+02:00 [info] <0.539.0>@ejabberd_listener:accept/7:273 (<0.9792.3>) Accepted connection [::ffff:XXX.XXX.XXX.XXX]:PORT -> [::ffff:XXX.XXX.XXX.XXX]:PORT`

and after that client broke connection on itself(Connection reset by peer.)
any ideas why it's possible and how to fix that?

**Comment by Vladimir7i** [comment]
solution is: send Ping every 60 sec. because Router drop external TCP connections after some period of inactivity
