### ISSUE TITLE
export_piefxis jid duplicates, best practice?

### ISSUE THREAD

**Issue by paradisaeidae** [processone/ejabberd#392]
export_piefxis is pretty handy when massaging test data then moving to live.
Only thing is, ejabberd sees each online presence as a jid.
So if there are jid's with multiple logins with different resources, multiple user elements are created in the piefxis.
The http://xmpp.org/extensions/xep-0227.html document does not make mention of uniqueness.
So as a procedure it appears necessary to run a xslt on the export to gain unique jid's.
Either that or logout all users, disable logins with firewall (not good)... make export.... re-enable logins.

MarkT

**Comment by badlop** [comment]
What do you mean? If the server has one account, it produces one "user" element, regardless of how many resources are logged in at any time:
```
<host jid="localhost">
  <user name="user1" password="mypass1">
    ...
  </user>
  <user name="user2" password="mypass2">
    ...
  </user>
</host>
```
