### ISSUE TITLE
Mac OS X 10.10 ejabberd 14.12 Cannot Enable TLSv1.1 or v1.2

### ISSUE THREAD

**Issue by Caboose700** [processone/ejabberd#393]
Hello all.

I have complied Erlang and ejabberd 14.12 on OSX. When launching the server (with the configuration file set to disable sslv2 and v3), when I check xmpp.net for my security settings, it displays that I am only able to connect with TLSv1.0.

I have updated OpenSSL to version 1.0.1j using Homebrew and linked it to the main directory for OSX. Even after recompiling ejabberd, I still can only connect over TLSv1.0.

So if there is a way to enable TLSv1.1 / TLSv1.2 on OSX with ejabberd 14.12, I would appreciate any help setting that up. I can provide more information if required.

xmpp.net result: https://xmpp.net/result.php?id=101267

**Comment by weiss** [comment]
> I have complied Erlang and ejabberd 14.12 on OSX. When launching the
> server (with the configuration file set to disable sslv2 and v3), when I
> check xmpp.net for my security settings, it displays that I am only able
> to connect with TLSv1.0.
> 
> I have updated OpenSSL to version 1.0.1j using Homebrew and linked it to
> the main directory for OSX. Even after recompiling ejabberd, I still can
> only connect over TLSv1.0.

Are you sure you're not seeing cached xmpp.net results?

If so: Are you sure ejabberd's TLS driver is now actually linked against
the OpenSSL version from Homebrew?  (You'd have to search for ejabberd's
"p1_tls_drv.so" file and run something like "otool -L p1_tls_drv.so" to
check.)

**Comment by Caboose700** [comment]
I have used your method and it confirms that it was built pointing at the 0.9.8 (OSX Default Openssl) version of the libcrypto and libssl. I have found the paths for the new ones, but am at a loss how to modify the p1_tls. 

I am assuming right now that I would have to edit something then re-build ejabberd.

**Comment by mremond** [comment]
Did you finally find the option to link to your custom openssl ?

**Comment by cromain** [comment]
to build with your homebrew version of openssl, you need something like this
p=$(brew info openssl | sed -e '/^\//!d;s/ .*//' | tail -n 1) 
CFLAGS="-I$p/include" LDFLAGS="-L$p/lib" make all
