### ISSUE TITLE
if A link B and monitor B, what will A do if B is exit?  if A receive exit signal from B, will A exit as well and not execute the monitor 'Down' logic?

### ISSUE THREAD

**Issue by pangxiaozhen77** [processone/ejabberd#3934]
https://github.com/processone/ejabberd/blob/3b3d3eaa04bbacc8c03f1d0c050e348ad84f9d0e/src/ejabberd_websocket.erl#L141

**Comment by prefiks** [comment]
I believe monitor messages are generated before link is processing, so this should be working fine. We probably could use trap_exit and listen for messages from link, but with curent setup, handler process will get killed if connection fails in some unexpected way.

**Comment by pangxiaozhen77** [comment]
> I believe monitor messages are generated before link is processing, so this should be working fine. We probably could use trap_exit and listen for messages from link, but with curent setup, handler process will get killed if connection fails in some unexpected way.

I got an answer [here](https://stackoverflow.com/questions/74345653/what-happens-when-link-and-monitor-the-same-process-in-erlang), and in my test, also link message may be arrived earlier than monitor message

**Comment by pangxiaozhen77** [comment]
And just want to know, why we need link and monitor the same process?  seems they can do the same thing(when B exit, A will exit as well)

**Comment by badlop** [comment]
This got another reply in https://stackoverflow.com/questions/74345653/what-happens-when-link-and-monitor-the-same-process-in-erlang

There's a very detailed article: [Link and Monitor differences in Erlang](https://marcelog.github.io/articles/erlang_link_vs_monitor_difference.html)

> Erlang has a built-in feature for error handling between processes. Terminating processes will emit exit signals to all linked processes, which may terminate as well or handle the exit in some way. 

> [Monitors](http://www.erlang.org/doc/reference_manual/processes.html#id82854) are not links, they are a more relaxed way of knowing what happened to a process.
