### ISSUE TITLE
mod_vcard_ldap -> ldap_vcard_map configuration not supported in YAML?

### ISSUE THREAD

**Issue by sandinak** [processone/ejabberd#394]
The documentation doesn't detail how to make this work, and it appears tied to the fact that the config atoms are triple entries: 

     [{"NICKNAME", "%u", []}, % just use user's part of JID as his nickname

THere's no good way to represent that in YAML.  Please either update the documentation to reflect the correct methodology or mark this module unusable.

**Comment by siavashs** [comment]
I'm also having problems using this module which is shipped with ejabberd by default.
I converted the old configuration using convert_to_yaml command but the module does not work!

**Comment by mute---** [comment]
Yeah. It's pretty tangled explanation in guide. But there is a working example
```
    ldap_vcard_map:
     "NICKNAME": {"%u": []} # just use user's part of JID as his nickname
     "GIVEN": {"%s": ["givenName"]}
     "FAMILY": {"%s": ["sn"]}
     "FN": {"%s, %s": ["sn", "givenName"]}, # example: "Smith, John"
     "EMAIL": {"%s": ["mail"]}
     "BDAY": {"%s": ["birthDay"]}
```

**Comment by badlop** [comment]
Guide updated so mod_vcard_ldap config examples use YAML format.
