### ISSUE TITLE
Unknown MUC room option, will be discarded: hibernation_time

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3946]
## Environment

- ejabberd version: 3b50cd36ba7e915b13da24d33d4466e60a26bae1
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.1.2`
- OS: Linux (Debian), arm64
- Installed from: source

## Errors from error.log/crash.log

At ejabberd start, for each local MUC:
`[info] <X.XXX.X>@mod_muc_room:set_opts/1:4037 Unknown MUC room option, will be discarded: hibernation_time`

**Comment by badlop** [comment]
Right. This option was silently discarded before 4d3875f4ff1c274c26c56344a3d07360065c8521, and now I've silenced it again.
