### ISSUE TITLE
Invalid byte sequence for encoding 

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#3947]
## Environment

- ejabberd version: 3b50cd36ba7e915b13da24d33d4466e60a26bae1
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.1.2`
- OS: Linux (Debian), arm64, psql
- Installed from: source

error.log
```
[error] <0.450.0>@ejabberd_sql:check_error/2:1282 SQL query 'Q42726653' at {mod_mam_sql,{193,17}} failed: [{severity,'ERROR'},
                                                         {86,<<"ERROR">>},
                                                         {code,<<"22021">>},
                                                         {message,
                                                          <<"invalid byte sequence for encoding \"UTF8\": 0x00">>},
                                                         {file,
                                                          <<"mbutils.c">>},
                                                         {line,1593},
                                                         {routine,
                                                          <<"report_invalid_encoding">>}]
```

postgresql log
```
ERROR:  invalid byte sequence for encoding "UTF8": 0x00
ejabberd@ejabberd STATEMENT:  INSERT INTO archive(username, server_host, timestamp, peer, bare_peer, xml, txt, kind, nick) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9);
```

afaik, before current commit , on e58920b2c6d1af873df3c85eb91709fe6efe0419 and older I was seeing this regarding this query _(not sure if related)_:
`[error] <0.479.0>@ejabberd_sql:check_error/2:1290 SQL query 'Q42726653' at {mod_mam_sql,{193,17}} failed: <<"timed out">>`

**Comment by nosnilmot** [comment]
Can you reproduce? if so, please:

1. get debug log to see what message stanza causes this
2. check if reverting https://github.com/processone/ejabberd/commit/a1cfae8c981e8e957eb79bfda94cc45ccf35b316 gets rid of the 'invalid byte sequence' error

I don't _think_ the timeout is related, but it might be.

**Comment by licaon-kter** [comment]
I've updated and saw this in the log after 5 or so hours.

Will keep an eye and report if I see it again, no idea on how to repro.

**Comment by mremond** [comment]
@licaon-kter Should we close this issue ? Do you still think there could be a problem ?

**Comment by licaon-kter** [comment]
Will reopen if seen again.
