### ISSUE TITLE
generating token

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3957]
Hello,

I am using the **latest ejabberd** docker image and **windows 10**
I am trying to generate token using the documentation https://docs.ejabberd.im/developer/ejabberd-api/simple-configuration/

but I am getting these errors while running the docker container
 I have the following logs

> ejabberd  | 2022-12-14 07:46:40.469068+00:00 [error] ** Generic server ejabberd_access_permissions terminating
ejabberd  | ** Last message in was show_current_definitions
ejabberd  | ** When Server state == {state,none}
ejabberd  | ** Reason for termination ==
ejabberd  | ** {function_clause,
ejabberd  |        [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |             [{<<"admin access">>,
ejabberd  |               {[],
ejabberd  |                [{oauth,
ejabberd  |                     {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                      [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                []}}],
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,161}]},
ejabberd  |         {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |         {ejabberd_access_permissions,get_definitions,1,
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,160}]},
ejabberd  |         {ejabberd_access_permissions,handle_call,3,
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,128}]},
ejabberd  |         {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},
ejabberd  |         {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},
ejabberd  |         {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
ejabberd  | ** Client <0.643.0> stacktrace
ejabberd  | ** [{gen,do_call,4,[{file,"gen.erl"},{line,233}]},
ejabberd  |     {gen_server,call,2,[{file,"gen_server.erl"},{line,235}]},
ejabberd  |     {ejabberd_access_permissions,'-show_current_definitions/0-fun-0-',0,
ejabberd  |                                  [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                                   {line,110}]},
ejabberd  |     {ets_cache,lookup,3,
ejabberd  |                [{file,"/ejabberd/deps/cache_tab/src/ets_cache.erl"},
ejabberd  |                 {line,174}]},
ejabberd  |     {ejabberd_access_permissions,can_access,2,
ejabberd  |                                  [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                                   {line,75}]},
ejabberd  |     {ejabberd_commands,execute_command2,4,
ejabberd  |                        [{file,"src/ejabberd_commands.erl"},{line,254}]},
ejabberd  |     {ejabberd_ctl,call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,334}]},
ejabberd  |     {ejabberd_ctl,try_call_command,4,
ejabberd  |                   [{file,"src/ejabberd_ctl.erl"},{line,295}]}]
ejabberd  |
ejabberd  | 2022-12-14 07:46:40.472714+00:00 [error] CRASH REPORT:
ejabberd  |   crasher:
ejabberd  |     initial call: ejabberd_access_permissions:init/1
ejabberd  |     pid: <0.489.0>
ejabberd  |     registered_name: ejabberd_access_permissions
ejabberd  |     exception error: no function clause matching
ejabberd  |                      ejabberd_access_permissions:'-get_definitions/1-fun-0-'({<<"admin access">>,
ejabberd  |                                                                               {[],
ejabberd  |                                                                                [{oauth,
ejabberd  |                                                                                  {[<<"ejabberd:admin">>,
ejabberd  |                                                                                    <<"registered_users">>],
ejabberd  |                                                                                   [{access,
ejabberd  |                                                                                     [{allow,
ejabberd  |                                                                                       [{acl,
ejabberd  |                                                                                         apicommands}]}]}]}}],
ejabberd  |                                                                                []}}) (src/ejabberd_access_permissions.erl, line 161)
ejabberd  |       in function  lists:map/2 (lists.erl, line 1243)
ejabberd  |       in call from ejabberd_access_permissions:get_definitions/1 (src/ejabberd_access_permissions.erl, line 160)
ejabberd  |       in call from ejabberd_access_permissions:handle_call/3 (src/ejabberd_access_permissions.erl, line 128)ejabberd  |       in call from gen_server:try_handle_call/4 (gen_server.erl, line 721)
ejabberd  |       in call from gen_server:handle_msg/6 (gen_server.erl, line 750)
ejabberd  |     ancestors: [ejabberd_sup,<0.189.0>]
ejabberd  |     message_queue_len: 0
ejabberd  |     messages: []
ejabberd  |     links: [<0.420.0>]
ejabberd  |     dictionary: []
ejabberd  |     trap_exit: false
ejabberd  |     status: running
ejabberd  |     heap_size: 10958
ejabberd  |     stack_size: 28
ejabberd  |     reductions: 45386
ejabberd  |   neighbours:
ejabberd  |
ejabberd  | 2022-12-14 07:46:40.524780+00:00 [error] SUPERVISOR REPORT:
ejabberd  |     supervisor: {local,ejabberd_sup}
ejabberd  |     errorContext: child_terminated
ejabberd  |     reason: {function_clause,
ejabberd  |                 [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |                      [{<<"admin access">>,
ejabberd  |                        {[],
ejabberd  |                         [{oauth,
ejabberd  |                              {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                               [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                         []}}],
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,161}]},
ejabberd  |                  {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |                  {ejabberd_access_permissions,get_definitions,1,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,160}]},
ejabberd  |                  {ejabberd_access_permissions,handle_call,3,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,128}]},
ejabberd  |                  {gen_server,try_handle_call,4,
ejabberd  |                      [{file,"gen_server.erl"},{line,721}]},
ejabberd  |                  {gen_server,handle_msg,6,
ejabberd  |                      [{file,"gen_server.erl"},{line,750}]},
ejabberd  |                  {proc_lib,init_p_do_apply,3,
ejabberd  |                      [{file,"proc_lib.erl"},{line,226}]}]}
ejabberd  |     offender: [{pid,<0.489.0>},
ejabberd  |                {id,ejabberd_access_permissions},
ejabberd  |                {mfargs,{ejabberd_access_permissions,start_link,[]}},
ejabberd  |                {restart_type,permanent},
ejabberd  |                {significant,false},
ejabberd  |                {shutdown,60000},
ejabberd  |                {child_type,worker}]
ejabberd  |
ejabberd  | Unhandled exception occurred executing the command:
ejabberd  | ** exception exit: {{function_clause,
ejabberd  |                    [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |                      [{<<"admin access">>,
ejabberd  |                        {[],
ejabberd  |                         [{oauth,
ejabberd  |                           {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                            [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                         []}}],
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,161}]},
ejabberd  |                     {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |                     {ejabberd_access_permissions,get_definitions,1,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,160}]},
ejabberd  |                     {ejabberd_access_permissions,handle_call,3,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,128}]},
ejabberd  |                     {gen_server,try_handle_call,4,
ejabberd  |                      [{file,"gen_server.erl"},{line,721}]},
ejabberd  |                     {gen_server,handle_msg,6,
ejabberd  |                      [{file,"gen_server.erl"},{line,750}]},
ejabberd  |                     {proc_lib,init_p_do_apply,3,
ejabberd  |                      [{file,"proc_lib.erl"},{line,226}]}]},
ejabberd  |                   {gen_server,call,
ejabberd  |                    [ejabberd_access_permissions,show_current_definitions]}}
ejabberd  |    in function  gen_server:call/2 (gen_server.erl, line 239)
ejabberd  |    in call from ejabberd_access_permissions:'-show_current_definitions/0-fun-0-'/0 (src/ejabberd_access_permissions.erl, line 110)
ejabberd  |    in call from ets_cache:lookup/3 (/ejabberd/deps/cache_tab/src/ets_cache.erl, line 174)
ejabberd  |    in call from ejabberd_access_permissions:can_access/2 (src/ejabberd_access_permissions.erl, line 75)
ejabberd  |    in call from ejabberd_commands:execute_command2/4 (src/ejabberd_commands.erl, line 254)
ejabberd  |    in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 334)
ejabberd  |    in call from ejabberd_ctl:try_call_command/4 (src/ejabberd_ctl.erl, line 295)
ejabberd  |    in call from ejabberd_ctl:process2/4 (src/ejabberd_ctl.erl, line 235)
ejabberd  | :> ejabberdctl registered_users localhost
ejabberd  | 2022-12-14 07:46:41.265130+00:00 [error] ** Generic server ejabberd_access_permissions terminating
ejabberd  | ** Last message in was show_current_definitions
ejabberd  | ** When Server state == {state,none}
ejabberd  | ** Reason for termination ==
ejabberd  | ** {function_clause,
ejabberd  |        [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |             [{<<"admin access">>,
ejabberd  |               {[],
ejabberd  |                [{oauth,
ejabberd  |                     {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                      [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                []}}],
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,161}]},
ejabberd  |         {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |         {ejabberd_access_permissions,get_definitions,1,
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,160}]},
ejabberd  |         {ejabberd_access_permissions,handle_call,3,
ejabberd  |             [{file,"src/ejabberd_access_permissions.erl"},{line,128}]},
ejabberd  |         {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},
ejabberd  |         {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},
ejabberd  |         {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
ejabberd  | ** Client <0.647.0> stacktrace
ejabberd  | ** [{gen,do_call,4,[{file,"gen.erl"},{line,233}]},
ejabberd  |     {gen_server,call,2,[{file,"gen_server.erl"},{line,235}]},
ejabberd  |     {ejabberd_access_permissions,'-show_current_definitions/0-fun-0-',0,
ejabberd  |                                  [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                                   {line,110}]},
ejabberd  |     {ets_cache,lookup,3,
ejabberd  |                [{file,"/ejabberd/deps/cache_tab/src/ets_cache.erl"},
ejabberd  |                 {line,174}]},
ejabberd  |     {ejabberd_access_permissions,can_access,2,
ejabberd  |                                  [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                                   {line,75}]},
ejabberd  |     {ejabberd_commands,execute_command2,4,
ejabberd  |                        [{file,"src/ejabberd_commands.erl"},{line,254}]},
ejabberd  |     {ejabberd_ctl,call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,334}]},
ejabberd  |     {ejabberd_ctl,try_call_command,4,
ejabberd  |                   [{file,"src/ejabberd_ctl.erl"},{line,295}]}]
ejabberd  |
ejabberd  | 2022-12-14 07:46:41.266642+00:00 [error] CRASH REPORT:
ejabberd  |   crasher:
ejabberd  |     initial call: ejabberd_access_permissions:init/1
ejabberd  |     pid: <0.644.0>
ejabberd  |     registered_name: ejabberd_access_permissions
ejabberd  |     exception error: no function clause matching
ejabberd  |                      ejabberd_access_permissions:'-get_definitions/1-fun-0-'({<<"admin access">>,
ejabberd  |                                                                               {[],
ejabberd  |                                                                                [{oauth,
ejabberd  |                                                                                  {[<<"ejabberd:admin">>,
ejabberd  |                                                                                    <<"registered_users">>],
ejabberd  |                                                                                   [{access,
ejabberd  |                                                                                     [{allow,
ejabberd  |                                                                                       [{acl,
ejabberd  |                                                                                         apicommands}]}]}]}}],
ejabberd  |                                                                                []}}) (src/ejabberd_access_permissions.erl, line 161)
ejabberd  |       in function  lists:map/2 (lists.erl, line 1243)
ejabberd  |       in call from ejabberd_access_permissions:get_definitions/1 (src/ejabberd_access_permissions.erl, line 160)
ejabberd  |       in call from ejabberd_access_permissions:handle_call/3 (src/ejabberd_access_permissions.erl, line 128)ejabberd  |       in call from gen_server:try_handle_call/4 (gen_server.erl, line 721)
ejabberd  |       in call from gen_server:handle_msg/6 (gen_server.erl, line 750)
ejabberd  |     ancestors: [ejabberd_sup,<0.189.0>]
ejabberd  |     message_queue_len: 0
ejabberd  |     messages: []
ejabberd  |     links: [<0.420.0>]
ejabberd  |     dictionary: []
ejabberd  |     trap_exit: false
ejabberd  |     status: running
ejabberd  |     heap_size: 10958
ejabberd  |     stack_size: 28
ejabberd  |     reductions: 45248
ejabberd  |   neighbours:
ejabberd  |
ejabberd  | 2022-12-14 07:46:41.269727+00:00 [error] SUPERVISOR REPORT:
ejabberd  |     supervisor: {local,ejabberd_sup}
ejabberd  |     errorContext: child_terminated
ejabberd  |     reason: {function_clause,
ejabberd  |                 [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |                      [{<<"admin access">>,
ejabberd  |                        {[],
ejabberd  |                         [{oauth,
ejabberd  |                              {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                               [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                         []}}],
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,161}]},
ejabberd  |                  {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |                  {ejabberd_access_permissions,get_definitions,1,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,160}]},
ejabberd  |                  {ejabberd_access_permissions,handle_call,3,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,128}]},
ejabberd  |                  {gen_server,try_handle_call,4,
ejabberd  |                      [{file,"gen_server.erl"},{line,721}]},
ejabberd  |                  {gen_server,handle_msg,6,
ejabberd  |                      [{file,"gen_server.erl"},{line,750}]},
ejabberd  |                  {proc_lib,init_p_do_apply,3,
ejabberd  |                      [{file,"proc_lib.erl"},{line,226}]}]}
ejabberd  |     offender: [{pid,<0.644.0>},
ejabberd  |                {id,ejabberd_access_permissions},
ejabberd  |                {mfargs,{ejabberd_access_permissions,start_link,[]}},
ejabberd  |                {restart_type,permanent},
ejabberd  |                {significant,false},
ejabberd  |                {shutdown,60000},
ejabberd  |                {child_type,worker}]
ejabberd  |
ejabberd  | Unhandled exception occurred executing the command:
ejabberd  | ** exception exit: {{function_clause,
ejabberd  |                    [{ejabberd_access_permissions,'-get_definitions/1-fun-0-',
ejabberd  |                      [{<<"admin access">>,
ejabberd  |                        {[],
ejabberd  |                         [{oauth,
ejabberd  |                           {[<<"ejabberd:admin">>,<<"registered_users">>],
ejabberd  |                            [{access,[{allow,[{acl,apicommands}]}]}]}}],
ejabberd  |                         []}}],
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,161}]},
ejabberd  |                     {lists,map,2,[{file,"lists.erl"},{line,1243}]},
ejabberd  |                     {ejabberd_access_permissions,get_definitions,1,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,160}]},
ejabberd  |                     {ejabberd_access_permissions,handle_call,3,
ejabberd  |                      [{file,"src/ejabberd_access_permissions.erl"},
ejabberd  |                       {line,128}]},
ejabberd  |                     {gen_server,try_handle_call,4,
ejabberd  |                      [{file,"gen_server.erl"},{line,721}]},
ejabberd  |                     {gen_server,handle_msg,6,
ejabberd  |                      [{file,"gen_server.erl"},{line,750}]},
ejabberd  |                     {proc_lib,init_p_do_apply,3,
ejabberd  |                      [{file,"proc_lib.erl"},{line,226}]}]},
ejabberd  |                   {gen_server,call,
ejabberd  |                    [ejabberd_access_permissions,show_current_definitions]}}
ejabberd  |    in function  gen_server:call/2 (gen_server.erl, line 239)
ejabberd  |    in call from ejabberd_access_permissions:'-show_current_definitions/0-fun-0-'/0 (src/ejabberd_access_permissions.erl, line 110)
ejabberd  |    in call from ets_cache:lookup/3 (/ejabberd/deps/cache_tab/src/ets_cache.erl, line 174)
ejabberd  |    in call from ejabberd_access_permissions:can_access/2 (src/ejabberd_access_permissions.erl, line 75)
ejabberd  |    in call from ejabberd_commands:execute_command2/4 (src/ejabberd_commands.erl, line 254)
ejabberd  |    in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 334)
ejabberd  |    in call from ejabberd_ctl:try_call_command/4 (src/ejabberd_ctl.erl, line 295)
ejabberd  |    in call from ejabberd_ctl:process2/4 (src/ejabberd_ctl.erl, line 235)
ejabberd  | :> ejabberdctl status
ejabberd  | The node ejabberd@daeed4f477ca is started with status: started
ejabberd  | ejabberd 22.10.0 is running in that node

This is my **docker-compose.yml** file
![image](https://user-images.githubusercontent.com/72728047/207537931-a07fd315-09c4-452a-b04a-32970e2be17b.png)

This is my **ejabberd.yml** file: 
![image](https://user-images.githubusercontent.com/72728047/207537836-f309e7f5-f14d-4a3d-a313-3db912ca36e1.png)

**Comment by prefiks** [comment]
Also you don't have what: section in "admin access" or is that just cut in that picture?

**Comment by prefiks** [comment]
So this issue was probably caused by missing `who:` section in your config i commited bc063b8f9734e523030290175e61cef2610d6f7e that should fix this, but you can also make this work if you add `what:` to your config like in https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L130.
