### ISSUE TITLE
no cert file

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3960]
Hello,

I am using ejabberd latest version usinf Docker

I have this error
`Failed to secure c2s connection: TLS failed: no_certfile`

This is my docker-compose file

> version: '3.7'

services:

  main:
    image: ejabberd/ecs
    container_name: ejabberd
    environment:
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=registered_users localhost ;
                     status
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "5281:5281"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./database:/home/ejabberd/database

and this my ejabberd.yaml file

`
hosts:
  - localhost

loglevel: info

listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    starttls_required: true
    certfile: "/xmpp_example_com.pem"

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth
  

     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "some playing":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    
modules:
  mod_admin_extra: {}
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
`

**Comment by licaon-kter** [comment]
Where's the certs volume?

**Comment by mkassir95** [comment]
@licaon-kter  
hello, can you please put an example how should I add the cert volumes?

**Comment by mkassir95** [comment]
@licaon-kter 

I added this 
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./database:/home/ejabberd/database
      - ./xmpp_example_com.pem:/home/ejabberd/conf
but now i have new error 
`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/Users/user/Desktop/flutter_local_notifications-master/xmpp_example_com.pem" to rootfs at "/home/ejabberd/conf": mount /run/desktop/mnt/host/c/Users/user/Desktop/flutter_local_notifications-master/xmpp_example_com.pem:/home/ejabberd/conf (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by mkassir95** [comment]
@licaon-kter 

I fixed it  and my docker-compose become like this:

version: '3.7'

services:

  main:
    image: ejabberd/ecs
    container_name: ejabberd
    environment:
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=registered_users localhost ;
                     status
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "5281:5281"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./database:/home/ejabberd/database
      - ./xmpp_example_com.pem:/home/ejabberd/conf/cacert.pem

but still giving me 'Failed to secure c2s connection: TLS failed: no_certfile'

**Comment by licaon-kter** [comment]
You need to add the proper certificate, the one you got from Lets Encrypt or some other CA. `cacert.pem` is not it.

**Comment by mkassir95** [comment]
ok thank you
