### ISSUE TITLE
using mod_offline

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3963]
Hello,

How to use mod_offline, I am trying to get the offline count but it is 0

![image](https://user-images.githubusercontent.com/72728047/209522660-da7b4b12-ebaa-406b-bbbb-6676f383dbc8.png)

**Comment by mkassir95** [comment]
> 
hosts:
  - localhost

loglevel: info


  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth
  

     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "admin api permsions":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    
shaper_rules:
  max_user_offline_messages: 1000
    
modules:
  mod_admin_extra: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages

**Comment by badlop** [comment]
It works for me using ejabberd 22.10, the default configuration, and also using your configuration. Those are the steps I used to test it:

Register two accounts and check count of offline messages, obviously it's zero:
```
ejabberdctl register user1 localhost asd
ejabberdctl register user2 localhost asd
ejabberdctl get_offline_count user2 localhost
0
```

Send a message and check offline messages of the receiver account says one:
```
ejabberdctl send_message chat user1@localhost user2@localhost AA Hello
ejabberdctl get_offline_count user2 localhost
1
```

Send another message and check offline messages of the receiver account says two:
```
ejabberdctl send_message chat user1@localhost user2@localhost AA Hello2
ejabberdctl get_offline_count user2 localhost
2
```

Try something like that. Does it work?

**Comment by mkassir95** [comment]
Thank you very much, you saved me. I figured out the problem with the help of your example, the problem was that i was using message type `headline` which is not stored offline.
Thank you again
