### ISSUE TITLE
pushing a notification to offline users

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3964]
Hello,

I want to push a notification to offline users, I read that I have to add an external component to ejabberd which will receives a notification when the user is offline, and then I can use a back end service to retreive the user 's token from the database and push him a FCM notification. 

I checked open sources for this external component but they are outdated, is there any recommended updated one?

**Comment by licaon-kter** [comment]
You need to setup https://github.com/iNPUTmice/p2 too for eg.

**Comment by mkassir95** [comment]
Thank you
