### ISSUE TITLE
Using mod_http_upload

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3966]
Hello,
I am using `ejabberd version 22.10`, operating system `windows 10`
I need to use  `mod_http_upload`, but I am getting  this error

![image](https://user-images.githubusercontent.com/72728047/210344410-a2e8a757-a097-43e0-832c-bf1d2a07cebd.png)

**Comment by mkassir95** [comment]
This is my ejabberd.yml file

> 
hosts:
  - localhost

loglevel: info


  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth

  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      /upload: mod_http_upload
  
  -
    port: 5347
    ip: "::"
    module: ejabberd_service
    hosts:
      "mymuc.domain.tld":
        password: "mysecret"

   
     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "admin api permsions":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    




    
modules:
  mod_admin_extra: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push_keepalive: 
    wake_on_start: true
  mod_offline: {}
  mod_push: {}
  mod_http_upload:
    docroot: /ejabberd/upload
    put_url: "http://localhost:5443/upload"

  #mod_offline_notify: {}

**Comment by mkassir95** [comment]
These are my ejabberd logs

![image](https://user-images.githubusercontent.com/72728047/210344579-e45082b9-050e-4b7b-b35a-9d94a4d7539d.png)

**Comment by licaon-kter** [comment]
OS/ejabberd version/gist of thu config?

The template is not there for you to delete...

**Comment by mkassir95** [comment]
I am sorry, I updated these information and I will use the template the next time

**Comment by licaon-kter** [comment]
Windows 10 means you run ejabberd on Windows via WSL or?

`stat -u ejabberd /ejabberd/upload` says what?S replace `ejabberd` with your actual user that is used to run ejabberd

**Comment by mkassir95** [comment]
I am run ejabberd using docker compose `docker-compose up`

This my docker-compose.yml file
`version: '3.7'

services:

  main:
    image: ejabberd/ecs
    container_name: ejabberd
    environment:
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=registered_users localhost ;
                     status
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "5281:5281"
      - "5347:5347"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./database:/home/ejabberd/database
 #     - ./xmpp_example_com.pem:/home/ejabberd/conf/cacert.pem
      - ./modules:/home/ejabberd/.ejabberd-modules`

**Comment by mkassir95** [comment]
and this my ejabberd.yml file

> 
hosts:
  - localhost

loglevel: info


  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth

  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      /upload: mod_http_upload
  
  -
    port: 5347
    ip: "::"
    module: ejabberd_service
    hosts:
      "mymuc.domain.tld":
        password: "mysecret"

   
     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "admin api permsions":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    




    
modules:
  mod_admin_extra: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push_keepalive: 
    wake_on_start: true
  mod_offline: {}
  mod_push: {}
  mod_http_upload:
    docroot: /ejabberd/upload
    put_url: "https://@HOST@:5443/upload"

  #mod_offline_notify: {}

**Comment by mkassir95** [comment]
The upload folder is empty

![image](https://user-images.githubusercontent.com/72728047/210370771-cad75ffd-54db-4be2-8891-42981443dd62.png)

**Comment by licaon-kter** [comment]
So it's `/ejabberd/upload` like in the .yml config or `~/upload` like in your picture?

**Comment by mkassir95** [comment]
like in the picture

**Comment by licaon-kter** [comment]
Umm, your config .yml says `docroot: /ejabberd/upload` which in NOT the same thing

**Comment by mkassir95** [comment]
the path in my  should be like this ` docroot: /home/ejabberd/upload,` true?

![image](https://user-images.githubusercontent.com/72728047/210410960-a200b96d-9f3e-4828-b4b9-d6c6cd5fdfa9.png)

**Comment by mkassir95** [comment]
I changed the log level to `debug`  and I got these logs
![image](https://user-images.githubusercontent.com/72728047/210422577-ad38cdcf-969d-48bd-a612-3997b99e97d3.png)

**Comment by mkassir95** [comment]
I think the problem is in the put request 's paramtersm, but I did figured out what paramters I should send
![image](https://user-images.githubusercontent.com/72728047/210544508-ae9e18ff-cfd6-4f82-b4b2-f2a0746517f5.png)

**Comment by licaon-kter** [comment]
Can you test with a proper client too, eg. Dino or Gajim, Siskin or Monal, Conversations?
