### ISSUE TITLE
file transfer in smack is not working

### ISSUE THREAD

**Issue by mkassir95** [processone/ejabberd#3968]
- ejabberd version: 22.10
- Erlang version: 13.1.3
- OS: Windows 10
- Installed from: Docker(ejabberd/ecs image)

ejabberd.yml

> 
hosts:
  - localhost

loglevel: debug

  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth

  -
    port: 5443
    module: ejabberd_http
    request_handlers:
      /upload: mod_http_upload
  
  -
    port: 5347
    ip: "::"
    module: ejabberd_service
    hosts:
      "mymuc.domain.tld":
        password: "mysecret"

   
     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "admin api permsions":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    

    
modules:
  mod_admin_extra: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push_keepalive: 
    wake_on_start: true
  mod_offline: {}
  mod_push: {}
  mod_http_upload:
    docroot: /home/ejabberd/upload
    put_url: "http://@HOST@:5443/upload"

  #mod_offline_notify: {}

**Comment by mkassir95** [comment]
The problem is that I am trying to send a file using smack library and  I am getting this error `feature-not-implemented`

**Comment by mkassir95** [comment]
This is my smack 

>                     BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(new
                            File(getFilesDir()+File.separator+"MyFile.txt")));
                    bufferedWriter.write("lalit poptani");
                    bufferedWriter.close();
                    FileTransferManager manager = FileTransferManager.getInstanceFor(conn1);
                    OutgoingFileTransfer transfer = manager.createOutgoingFileTransfer("rawad@localhost/Smack");
                    transfer.sendFile(new File(getFilesDir()+File.separator+"MyFile.txt"), "You won't believe this!");

**Comment by licaon-kter** [comment]
Can you test with a proper client too, eg. Dino or Gajim, Siskin or Monal, Conversations?

If that works it means it's not a server issue so you can close this and continue elsewhere like https://igniterealtime.atlassian.net/jira/software/c/projects/SMACK/issues
