### ISSUE TITLE
XEP-0440: SASL Channel-Binding Type Capability support

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3972]
Dear @processone team,

Can you add "XEP-0440: SASL Channel-Binding Type Capability" support?
- https://xmpp.org/extensions/xep-0440.html

Thanks in advance.

**Comment by prefiks** [comment]
This was added when i implemented tls-exporter.

**Comment by Neustradamus** [comment]
@prefiks, @badlop: Good :)

Please add the XEP version supported in the code like other XEPs :)

**Comment by Neustradamus** [comment]
@prefiks: Good job!

Please add the XEP version supported in the code like other XEPs :)
