### ISSUE TITLE
XEP-0386: Bind 2.0 support

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3973]
Dear @processone team,

Can you add "XEP-0386: Bind 2.0" support?
- https://xmpp.org/extensions/xep-0386.html

Thanks in advance.

**Comment by prefiks** [comment]
This was implemented recently

**Comment by Neustradamus** [comment]
@prefiks: Good job!

Here exactly:
- https://github.com/processone/xmpp/commit/b6c0d6310b03939aab4db7aebc0f5fe323dadc51
- https://github.com/processone/xmpp/commit/717ef34e35871fff0adf5377e242f80adc888055
