### ISSUE TITLE
Checksum doesn't match when installing from RPM repo

### ISSUE THREAD

**Issue by johnassel** [processone/ejabberd#3984]
## Environment

- ejabberd version: 23.01
- OS: Linux (Fedora)
- Installed from: official deb/rpm

Hi,

when installing ejabberd from the official rpm  repo dnf stops with
`Downloading Packages:
[MIRROR] ejabberd-23.01-1.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 4e63084289a9e8aca3d095ab717dd541be9f13637a6009fb29cf06de609bf75c(sha256)  Expected: e2a9726cf3439b0ece63b5a8a785ef7e19442d31cff8a4d12d390a6f7d536ff6(sha256)`

When downloading the rpm manually from https://repo.process-one.net/rpm/ejabberd-23.01-1.x86_64.rpm and checking its checksum it is indeed 4e63084289a9e8aca3d095ab717dd541be9f13637a6009fb29cf06de609bf75c.

When downloading the file from https://www.process-one.net/en/ejabberd/downloads/ I get the hash dnf expected e2a9726cf3439b0ece63b5a8a785ef7e19442d31cff8a4d12d390a6f7d536ff6.
So both files I get are different. 

Anyone got the same problem?

**Comment by badlop** [comment]
Quite strange. I can reproduce it. Summary:
- The sum file in [Downloads](https://www.process-one.net/en/ejabberd/downloads/) section **Checking code integrity and signature** says   `e2a97`
- The checksum in the primary.xml.gz file [in repodata](https://repo.process-one.net/rpm/repodata/) says `e2a97`
- And the file available to download in [Downloads](https://www.process-one.net/en/ejabberd/downloads/) has sha256sum:  `e2a97`
- However, as you noticed, when downloading the rpm from [the repo](https://repo.process-one.net/rpm/), it has sha256sum `4e630`

**Comment by nosnilmot** [comment]
The RPM in [the repo](https://repo.process-one.net/rpm/) is signed, the one in [Downloads](https://www.process-one.net/en/ejabberd/downloads/) is not. It looks like the repo metadata was generated, and then the RPMs were signed.

**Comment by johnassel** [comment]
Hi!
Yes, can confirm, it now works.
Thank you!
