### ISSUE TITLE
Merge chat local history, to sql.

### ISSUE THREAD

**Issue by jcbmca** [processone/ejabberd#3996]
Hello, excuse my English..

I have configured ejabberd 23.01-1, with mariadb. It's working fine, with gajim and pidgin I can read the history.

I need to merge chat that I have in cvs, I extracted from gajim's db, from an old jabber configuration that had to be updated.

Now with version 23.01-1 I have enabled the registry in mariadb.

I tried inserting records into the "archive" table. These insertions are not displayed in gajim nor in pidgin, which is the procedure I must follow to have a successful function.

It is necessary that it can perform this function, since users need to make queries.

thank you.

**Comment by mremond** [comment]
Closing as the discussion stalled.
