### ISSUE TITLE
Pushing notifications to android

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [processone/ejabberd#4000]
Well, I am creating an android chatting application, I want to push notifications to those users who are currently to active, through google's [fcm](https://firebase.google.com/docs/cloud-messaging)  how can I implement that?  if it isn't possible, are there any other mechanisms to perform such operations?

Well I checked some issues earlier, i found
 ```
mod_push :{}

 mod_push_keepalive: {}
```
But i dont know how to use them can someone give some pointers.
Thanks in advance.

**Comment by licaon-kter** [comment]
You have a special app that you published on Play or App Store, or you use Converasations or Monal or some app that are on Play or App Store?

**Comment by Yogesh-Dubey-Ayesavi** [comment]
> You have a special app that you published on Play or App Store, or you use Converasations or Monal or some app that are on Play or App Store?

I haven't published it yet just playing around with it and testing in local environments.

**Comment by licaon-kter** [comment]
Great, so you need an XMPP server like ejabberd, and a component to talk with Google/Apple, like https://github.com/iNPUTmice/p2
