### ISSUE TITLE
host-unknown error wth hosts configuration as *

### ISSUE THREAD

**Issue by pinanklakhani** [processone/ejabberd#4004]
Chat application is as module in my platform and users with any email domain can use chat module after login. I am using user's email as jid and kept hosts value as * but in that case its giving following error.

`ejabberd.yml`

```
hosts:
  - "*"
  - localhost
  ```

error

```
2023-03-02 10:51:11.890583+05:30 [notice] <0.2932.0> (websocket|<0.2931.0>) Send XML on stream = <<"<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>">>
```

**Comment by licaon-kter** [comment]
You should define an actual host, wildcard is not a valid value :)

**Comment by pinanklakhani** [comment]
Ok but users will be dynamic for me with different domains in their email

**Comment by licaon-kter** [comment]
Then setup hosts for those domains, you need to provide certs for those domains too.

**Comment by pinanklakhani** [comment]
@licaon-kter Practically it is not possible as there can be n number of domains as my platform is for enterprises they can signup any time and use

**Comment by licaon-kter** [comment]
When they sign up you add another domain in `hosts:`, put the domain certs in the proper place and run `ejabberdctl reload_config` to be able to serve it.

You can automate this...

**Comment by pinanklakhani** [comment]
@licaon-kter Okay. Let me check for other ways as well

**Comment by badlop** [comment]
> Chat application is as module in my platform and users with any email domain can use chat module after login. I am using user's email as jid and kept hosts value as * but in that case its giving following error.

Umm, try this idea:

For example, if you configure:
```yaml
hosts:
  - yourdomain.com
```

Tell your users to define their XMPP JID like this:
- username: email address, replacing @ with #
- hostname: `yourdomain.com`

Let's imagine my email address is `john@gmail.com`. I can register an account in your server with
- username: `john#gmail.com`
- hostname: `yourdomain.com`
- my account JID will be `john#gmail.com@yourdomain.com`

This works in ejabberd (and any other XMPP server), and works with all Jabber/XMPP clients:

```
2023-03-02 14:01:01.472163+01:00 [info] (<0.1297.0>)
  Accepted connection [::ffff:127.0.0.1]:36137 -> [::ffff:127.0.0.1]:5222
2023-03-02 14:01:02.316141+01:00 [info] (tls|<0.1297.0>)
  Accepted c2s DIGEST-MD5 authentication for john#gmail.com@yourdomain.com by mnesia backend from ::ffff:127.0.0.1
2023-03-02 14:01:02.384197+01:00 [info] (tls|<0.1297.0>)
  Opened c2s session for john#gmail.com@yourdomain.com/tkabber
```

**Comment by pinanklakhani** [comment]
Thanks @badlop I moved with the similar type of implementation where i took users unique id as username and appended my domain.
