### ISSUE TITLE
Upgrade Riak from 1.4 to 2.0?

### ISSUE THREAD

**Issue by toopay** [processone/ejabberd#401]
I wonder if we gonna upgrade it (or at least plan to do so)  in anytime soon. 

Thanks.

**Comment by zinid** [comment]
Did you try to build ejabberd with recent riakc? It's pain in ass.

**Comment by toopay** [comment]
@zinid Could you be more specific on the difficult part? I'm not say its a piece of cake, but i want to see if there are intention to upgrade. I could roll a branch on my fork if you interesting to support 2.0

**Comment by zinid** [comment]
https://github.com/basho/riak_pb/issues/46#issuecomment-58982146

**Comment by toopay** [comment]
Gotcha. I'll start diggin on this issue next week.

**Comment by zinid** [comment]
That would be great :)

**Comment by mremond** [comment]
Closing, ejabberd already supports Riak 2.0
