### ISSUE TITLE
xmppbl.org - Real-time blocklists for XMPP

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#4017]
Dear ejabberd team,

It is possible to add the Real-time blocklists for XMPP?
- https://xmppbl.org/

It exists already for:
- Prosody IM: https://modules.prosody.im/mod_muc_rtbl
- Openfire: https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=mucrtbl

Thanks in advance.

**Comment by licaon-kter** [comment]
And a server agnostic bot

**Comment by prefiks** [comment]
This is module that i plan to work on soon

**Comment by Neustradamus** [comment]
@prefiks: Good job! :)

**Comment by poVoq** [comment]
Is it possible to add more than one source to this?

**Comment by prefiks** [comment]
Should be doable i think, let me see how much work this will require.
