### ISSUE TITLE
ejabberd_http HTTP2

### ISSUE THREAD

**Issue by jpds** [processone/ejabberd#4021]
**Describe the solution you'd like**

Feature request for `ejabberd_http` to gain HTTP2 support - this would allow clients to enable more efficient data transfers with file uploads, and other things.

For Erlang, there's an implementation available at https://github.com/joedevivo/chatterbox and a presentation for it is at https://joedevivo.github.io/euc2015/

**Comment by licaon-kter** [comment]
Or use external, say nginx?

**Comment by jpds** [comment]
I know that using an external web server is possible, however I'd prefer not to introduce another element into my XMPP infra and more importantly: the Erlang implementations/ecosystem need to at some point evolve - even HTTP3 is a standard now.

**Comment by badlop** [comment]
This fork of chatterbox is more frequently updated: https://github.com/tsloughter/chatterbox

**Comment by jpds** [comment]
https://github.com/ninenines/cowboy also has HTTP2 support:

- https://ninenines.eu/docs/en/cowboy/2.10/guide/modern_web/

**Comment by mremond** [comment]
Implementing HTTP/2 inside ejabberd would be a huge, probably multiyear project. We have no plan for that at the moment, especially, as HTTP/2 can be supported by front specialized HTTP servers.
