### ISSUE TITLE
Ejabberdctl command not found error returned

### ISSUE THREAD

**Issue by Vikram-ksingh** [processone/ejabberd#4022]
I have installed the ejabberd with run package `ejabberd-23.01-1-linux-x64.run` on ec2 instance. The status is showing active however the commands to create new user is not working. Following command returns error mentioned below

```
sudo ejabberdctl register admin bkstg adm1npass

sudo: ejabberdctl: command not found
```

Not sure what is the issue here, it worked properly on the local though. Please help to get it resolved.

**Comment by Vikram-ksingh** [comment]
@licaon-kter  find command showing it under ```/opt/ejabberd-23.01/bin/ejabberdctl`

**Comment by Vikram-ksingh** [comment]
@licaon-kter  I am not much familiar with this, can you please guide with instruction or share an article.

**Comment by licaon-kter** [comment]
Search for `linux add a directory to PATH`

But, if that's your very first issue you'll have way more problems going forward :(

/close this

**Comment by AftabUfaq** [comment]
on Ubuntu system it has issue .


add your path like this 

open file with sudo nano ~/.bashrc 

and add this line 


`export PATH=$PATH:/opt/ejabberd-24.07/bin`   remember change your version 

`sudo visudo`

it has this 

`Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"`

**modify it like this** 

`Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/ejabberd-24.07/bin"`
