### ISSUE TITLE
Official Debian Package appears Broken(No configuration files or binaries)

### ISSUE THREAD

**Issue by heliophane** [processone/ejabberd#4024]
## Environment

- ejabberd version: 18.09
- OS: Linux (Debian)
- official deb/rpm

## Bug description
Howdy, I installed ejabberd through the repo and no configuration files were created. when I run ejabberdctl help debian says that ejabberd is not installed, when it is indeed installed. there is also no /etc/ejabberd folder created, and thus no ejabberd.yml file
![image](https://user-images.githubusercontent.com/35747043/233710844-d5995b69-e183-4df0-bfec-a0a8f8627f04.png)
![image](https://user-images.githubusercontent.com/35747043/233710977-012dba5e-c37c-45f5-9e16-de4ec9f4a41f.png)

**Comment by licaon-kter** [comment]
You can't find ejobberdctl in /opt/ maybe or anywhere on the filesystem?

**Comment by heliophane** [comment]
Didn't realize it would unpack to /opt/. any chance of having the directory moved back to /etc/? I was following the guide on landchad.net to configure it.

**Comment by badlop** [comment]
> any chance of having the directory moved back to /etc/?

The [ejabberd package provided by the Debian packagers](https://tracker.debian.org/pkg/ejabberd), which integrate perfectly with all the other Debian operating system, and take very detailed care to have such a great integration, installs itself in `/etc`. Similarly do the packages provided by packagers in Ubuntu, and many other operating systems.

So, the packages generated by ejabberd's tools install in a different place, in `/opt`, on purpose to not have unexpected interactions with packages built by Debian maintainers. Same with the `ejabberd` container images which uses `/opt`, and also the `ecs` container image which installs in `/home/ejabberd`
