### ISSUE TITLE
how to merge the ejabberd roster with my old user tables

### ISSUE THREAD

**Issue by hackrole** [processone/ejabberd#403]
I have develop a mobile-application now. it use http for normal request and have a chat-features which use xmpp. I use ejabberd as the chat server. 

  but I really have no ideas how to store the roster data in my mongodb, and how make it works with the <presence> stanza is also a headache to me.

  does anyone can give some idea or advice? 

I am not good at erlang now. so to me, the most easy way is to write a ejabberd componont with python(sleekxmpp). but I did not know the logic behind the ejabberd-roster and the presence, so I come here for some help, does there any documents about xmpp-roster or example to do this?

**Comment by mremond** [comment]
XMPP roster in general is a quite complex topic and as such, this is a complex feature. It cannot unfortunately teached by just a comment on a ticket.
As a starting point you need to get familiar with _mod_roster.erl_. However, if you do not know Erlang, this is not the easiest place to get started. You should look at simpler modules like mod_echo.erl, then mod_offline.erl for example.

We do not support Mongodb yet, but you already have quite a large choice of back-end: MySQL, Postgresql, generic ODBC, LDAP, Riak. You may also probably consider starting with one of them.
