### ISSUE TITLE
Error in installing ejabberd

### ISSUE THREAD

**Issue by heelll-boooy** [processone/ejabberd#4040]
Hello

- ejabberd version: 15.6
- Erlang version: `` 17.5
- OS: Linux  Ubuntu 16.4

when i installing ejabberd i have the proplem in command make :

```bash
root@123:~/ejabberd-15.06# make
rm -rf deps/.got
rm -rf deps/.built
/usr/local/lib/erlang/bin/escript rebar get-deps && :> deps/.got
==> p1_utils (get-deps)
==> p1_cache_tab (get-deps)
==> p1_tls (get-deps)
==> p1_stringprep (get-deps)
==> p1_xml (get-deps)
==> p1_stun (get-deps)
==> esip (get-deps)
==> p1_yaml (get-deps)
==> ehyperloglog (get-deps)
==> p1_zlib (get-deps)
==> lager (get-deps)
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.6"}}
Cloning into 'goldrush'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

ERROR: git clone -n git://github.com/DeadZen/goldrush.git goldrush failed with error: 128 and output:
Cloning into 'goldrush'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
ERROR: 'get-deps' failed while processing /root/ejabberd-15.06/deps/lager: rebar_abort
Makefile:82: recipe for target 'deps/.got' failed
make: *** [deps/.got] Error 1
```

Me server cant connect to github.com
Some Body Help me?
Thanks

**Comment by licaon-kter** [comment]
Latest version is 23.04, can you upgrade to a newer than 8 years version maybe?

**Comment by heelll-boooy** [comment]
hello
thank for you
i try version 18.1
also same the proplem
i think an error to connect the server
thanks

**Comment by heelll-boooy** [comment]
Can I upgrade to the latest version and my server specifications are
Ram 1 Gb
Erlang version: `` 17.5
OS: Linux Ubuntu 16.4

I am experimenting with it now to get the best version and the best performance

Thanks

**Comment by heelll-boooy** [comment]
Hello
@licaon-kter 
Man Can u Help me?
please
Thanks

**Comment by badlop** [comment]
> Can I upgrade to the latest version and my server specifications are
> Ram 1 Gb

That small RAM probably is not a problem for ejabberd, I imagine it should work correctly.

> Erlang version: `` 17.5

Erlang 17.5 is supported by ejabberd 18.12, that is the newest ejabberd version supported by that erlang. You can try compiling ejabberd 18.12 with erlang 17.5.

If compiling does not work, show here the log message.

**Comment by heelll-boooy** [comment]
Hello
Thanks badlop 
 i well try now and update you

**Comment by heelll-boooy** [comment]
Hello
I try it and Write This :

root@hell.boy:~# cd /root/ejabberd-18.12
root@hell.boy:~/ejabberd-18.12# ./configure --enable-odbc
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking for epmd... /usr/local/bin/epmd
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking Erlang/OTP version... Compiler function compile:compile/3 failed:
{undef,[{code,ensure_modules_loaded,
              [[beam_a,beam_asm,beam_block,beam_bool,beam_bs,beam_bsm,
                beam_clean,beam_dead,beam_dict,beam_except,beam_flatten,
                beam_jump,beam_opcodes,beam_peep,beam_receive,beam_reorder,
                beam_split,beam_trim,beam_type,beam_utils,beam_validator,
                beam_z,cerl,cerl_clauses,cerl_sets,cerl_trees,core_lib,epp,
                erl_bifs,erl_expand_records,erl_lint,erl_parse,erl_scan,
                sys_core_dsetel,sys_core_fold,sys_pre_expand,v3_codegen,
                v3_core,v3_kernel,v3_life]],
              []},
        {compile,compile,3,[{file,"compile.erl"},{line,1835}]},
        {erl_compile,compile_file,4,[{file,"erl_compile.erl"},{line,302}]},
        {erl_compile,compile3,3,[{file,"erl_compile.erl"},{line,283}]},
        {erl_compile,'-compiler_runner/1-fun-0-',1,
                     [{file,"erl_compile.erl"},{line,90}]}]}
configure: error: "Could not compile Erlang/OTP version check program using '/usr/local/bin/erlc'"

**Comment by badlop** [comment]
Oh, sorry, it seems I didn't read correctly the code: it seems ejabberd 18.12 requires erlang 19.0

Now looking again, ejabberd 18.09 requires Erlang 17.5, so maybe with some luck you can compile that one.

If that doesn't work, an alternative would be that you download and compile a recent Erlang version. It will take one or two hours, but that way you will be able to use a recent ejabberd.

Another alternative would be to use the container images from https://hub.docker.com/r/ejabberd/ecs/tags

**Comment by badlop** [comment]
I see that [Ubuntu 20.04LTS (Focal) includes Erlang 22.2](https://packages.ubuntu.com/focal/erlang). The most recent ejabberd 23.04 requires Erlang 20.0 or higher...

So yes, the Erlang included in Ubuntu 20.04 will be supported by ejabberd and newer versions for quite some time.

**Comment by heelll-boooy** [comment]
i well try it
and update you

**Comment by heelll-boooy** [comment]
since 1 hour
i re install srever to ubuntu 16.4
and install Otp 17.5
when i install ejabberd.18.12 in command "make" 

Pulling goldrush from {git,"https://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.9"}}
Cloning into 'goldrush'...
==> goldrush (get-deps)
==> p1_utils (get-deps)
==> cache_tab (get-deps)
==> fast_tls (get-deps)
==> stringprep (get-deps)
==> fast_xml (get-deps)
==> ezlib (get-deps)
==> xmpp (get-deps)
==> fast_yaml (get-deps)
==> jiffy (get-deps)
WARN:  Missing plugins: [rebar3_hex]
==> p1_oauth2 (get-deps)
==> pkix (get-deps)
==> jose (get-deps)
Pulling base64url from {git,"git://github.com/dvv/base64url.git",
                            {branch,"master"}}
Cloning into 'base64url'... 

* The old problem has been solved, but it is now repeated with another folder. I downloaded the files manually to the desired path, but there is a file missing :
* root@hell.boy:~/ejabberd-18.12# make
rm -rf deps/.got
rm -rf deps/.built
mkdir -p deps
/usr/local/lib/erlang/bin/escript rebar get-deps && :> deps/.got
ERROR: More than one .app.src file in /root/ejabberd-18.12/deps/jose/src
WARN:  Directory expected to be an app dir, but no app file found
in ebin/ or src/:
/root/ejabberd-18.12/deps/jose
==> goldrush (get-deps)
==> lager (get-deps)
==> p1_utils (get-deps)
==> cache_tab (get-deps)
==> fast_tls (get-deps)
==> stringprep (get-deps)
==> fast_xml (get-deps)
==> ezlib (get-deps)
==> xmpp (get-deps)
==> fast_yaml (get-deps)
==> jiffy (get-deps)
WARN:  Missing plugins: [rebar3_hex]
==> p1_oauth2 (get-deps)
==> pkix (get-deps)
==> eimp (get-deps)
==> rel (get-deps)
==> ejabberd-18.12 (get-deps)
ERROR: More than one .app.src file in /root/ejabberd-18.12/deps/jose/src
WARN:  Directory expected to be an app dir, but no app file found
in ebin/ or src/:
/root/ejabberd-18.12/deps/jose
ERROR: More than one .app.src file in /root/ejabberd-18.12/deps/jose/src
WARN:  Directory expected to be an app dir, but no app file found
in ebin/ or src/:
/root/ejabberd-18.12/deps/jose
ERROR: Dependency dir /root/ejabberd-18.12/deps/jose failed application validation with reason:
{missing_app_file,"/root/ejabberd-18.12/deps/jose"}.
ERROR: 'get-deps' failed while processing /root/ejabberd-18.12: rebar_abort
Makefile:102: recipe for target 'deps/.got' failed
make: *** [deps/.got] Error 1

Can you help me with this?

**Comment by badlop** [comment]
```
apt-get install libexpat1-dev libgd-dev libpam0g-dev libsqlite3-dev libwebp-dev libyaml-dev
```

This is my last contribution in this thread, because compiling ejabberd with ubuntu 20.04 and erlang 20.0 works correctly, as demonstrated in 
https://github.com/processone/ejabberd/actions/runs/5067449138/jobs/9098518945

**Comment by heelll-boooy** [comment]
Thanks he is working but now write :
==> p1_oauth2 (compile)
Compiled src/oauth2_token_generation.erl
Compiled src/oauth2_priv_set.erl
Compiled src/oauth2_config.erl
Compiled src/oauth2.erl
Compiled src/oauth2_response.erl
Compiled src/oauth2_backend.erl
Compiled src/oauth2_token.erl
==> pkix (compile)
Compiled src/pkix_sup.erl
Compiled src/pkix_app.erl
/root/ejabberd-18.12/deps/pkix/src/pkix.erl:355: illegal use of variable 'Cert' in map
/root/ejabberd-18.12/deps/pkix/src/pkix.erl:365: illegal use of variable 'Key' in map
/root/ejabberd-18.12/deps/pkix/src/pkix.erl:680: illegal use of variable 'Domain' in map
/root/ejabberd-18.12/deps/pkix/src/pkix.erl:681: illegal use of variable 'Domain' in map
/root/ejabberd-18.12/deps/pkix/src/pkix.erl:682: illegal use of variable 'Domain' in map
Compiling /root/ejabberd-18.12/deps/pkix/src/pkix.erl failed:
ERROR: compile failed while processing /root/ejabberd-18.12/deps/pkix: rebar_abort
Makefile:108: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1

now i try with ubuntu 16.4

later i well buy another server and try with your contribution

**Comment by heelll-boooy** [comment]
Hello
@badlop
Please Can U Help me??
Im Waiting You
