### ISSUE TITLE
Push notifications stop working on iOS

### ISSUE THREAD

**Issue by tigransimonyan** [processone/ejabberd#4045]
## Environment

- ejabberd version: 21.01-2 amd64
- Erlang version: 11.1.8
- OS: Linux (Debian)
- Installed from: official deb/rpm

## Configuration

https://gist.github.com/tigransimonyan/0641fcc27c9bbd6c3ef1d1f6593baac0

## Errors from error.log/crash.log

https://gist.github.com/tigransimonyan/f49076d5c67d488c6e758489d106f55d

## Bug description

After installing ejabberd on iPhone, push notifications worked. But after a while it stopped working.

**Comment by licaon-kter** [comment]
There's no ejabberd on iPhone :)

Did you read https://eversten.net/en/blog/notification/ yet? 

Also, fyi, Debian Stable backports has ejabberd 23.01 already ;)

**Comment by tigransimonyan** [comment]
I am using Siskin IM clinet and notifications was worked in short period after server installation.

**Comment by licaon-kter** [comment]
Ok, so attach your server config link from gist.github.com (don't forget to clean the private stuff)

**Comment by licaon-kter** [comment]
Do read the upgrade notes of course, start with `from ejabberd 21.01 to 21.04`: https://docs.ejabberd.im/admin/upgrade/#specific-version-upgrade-notes and work your way up.

**Comment by mremond** [comment]
Closing, as the discussion stalled.
