### ISSUE TITLE
ejabberdctl_access_commands

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#405]
In guide there is no example for ejabberdctl_access_commands in new YAML format:

http://www.process-one.net/docs/ejabberd/guide_en.html#ectl-commands

How to create this restriction in YAML? I need this to configure mod_rest in YAML (https://github.com/processone/ejabberd-contrib/issues/45).

**Comment by badlop** [comment]
I don't know how to set access_commands in YAML format, but you can use the old Erlang formatting in another small config file, and later include it in your main YML file. I've now described it in the Guide. Take a look to confirm it works correctly.

**Comment by Beherit** [comment]
Already I have config file in new YAML format combine with old cfg format, where I placed mod_rest configuration. Everything work perfect but still I want to have all in one YAML configuration file.

**Comment by beherit** [comment]
Please add support for ejabberdctl_access_commands in YAML.

**Comment by beherit** [comment]
Fixed https://github.com/processone/ejabberd/commit/7ab6c4b4fd65d75e670152c38551d4311e1b481b :)
