### ISSUE TITLE
Prevent users from sending messages in particular public channel or room

### ISSUE THREAD

**Issue by ali-imanpour** [processone/ejabberd#4053]
I need to prevent users from sending messages in particular public channel or room, just admin can send message. 
How do I do this?

**Comment by licaon-kter** [comment]
Remove Voice with Dino or Gajim?

**Comment by ali-imanpour** [comment]
Would you please explain in detail? Is it better to the do this in ejabberd server?

**Comment by licaon-kter** [comment]
open the Dino or Gajim client, login as the room admin/owner, go to room properties

**Comment by ali-imanpour** [comment]
Thank you.
I've building custom app based on conversation-android, but never see any related options in it. Is it possible to do it via api or module? Only way is doing by mentioned clients?

**Comment by licaon-kter** [comment]
Conversations has "moderated" toggle in room settings, yes

**Comment by ali-imanpour** [comment]
Sorry, but I changed room config but regular user can send message to room|channel.
![image](https://github.com/processone/ejabberd/assets/18607289/f75598ed-a7fc-42ef-85ff-7cea4cb285fa)

**Comment by ali-imanpour** [comment]
It's possible to revoke write permission for specific user in dino, not in room or channel setting.  I need to do that for all users.

**Comment by licaon-kter** [comment]
You changed something related...but not what I said.

Toggle off Moderated above there and test, then toggle off "default users as participats" below it too.

**Comment by ali-imanpour** [comment]
Much appreciated. Exactly what i want.
