### ISSUE TITLE
Web Admin: Hitting enter on the "View Roster" page removes a contact.

### ISSUE THREAD

**Issue by egnun** [processone/ejabberd#4067]
## Environment

- ejabberd version: 23.04
- OS: GNU+Linux
- Installed from:  official deb/rpm

## Bug description

When I'm in the "Web Admin" interface and I go to "Users" > choose a user > "View Roster". When I then enter a JID there in the add contact field and press enter, it removes one of the already existing contacts.
So to be able to add a contact there, I have to manually press the button "Add Jabber-ID".

Expected behaviour: In general just pressing enter on that page, shouldn't remove a contact. 
When the cursor is focused on the input field, pressing enter should add a contact.

**Comment by Neustradamus** [comment]
@egnun: Have you seen the @badlop commit?

**Comment by egnun** [comment]
Looks good? I don't really speak Erlang. ;-)
But thanks for fixing this, @badlop. 

You can close this issue on your own accord.
