### ISSUE TITLE
Typo error in api reference affiliations

### ISSUE THREAD

**Issue by arthurchumak** [processone/ejabberd#4080]
## Bug description

https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#create-room-with-opts

method `create_room_with_opts` has error in description 

> To set affilitions string value must have format 'Type:JID,Type:JID' for example 'owner:bob@example.com,member:peter@example.com'. Subscribers can be define with string

should be
affili**a**tions

also move please Subscribers to new line, to make it more readable

**Comment by badlop** [comment]
Thanks! I've fixed the typo. I found no way to add newlines to the long command description, so i rewrote that paragraph and moved the examples to the examples section
https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#create-room-with-opts
