### ISSUE TITLE
I try to write query with in_array_string and get error

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#4081]
I have created a module that tries to run this query:
`ejabberd_sql:sql_query_t(?SQL("update some_table set col=%(Val)s where jid=%(LJid)s and username in (%(ItemIds)ls)"))`.
The `ItemIds` variable is a list of binary.

I get the following error: `function_clause`.

What wrong with that syntax?

## Environment

- ejabberd version: 22.05
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: docker

**Comment by prefiks** [comment]
Maybe try `update some_table set col=%(Val)s where jid=%(LJid)s and username in %(ItemIds)ls` (without embeding that in ())

**Comment by relbraun** [comment]
@prefiks  I have just tried it and it doesn't help. The same error.

**Comment by prefiks** [comment]
Do you have -include("ejabberd_sql_pt.hrl"). in that file?

**Comment by relbraun** [comment]
@prefiks 
Yes.

**Comment by prefiks** [comment]
So for testing i used `ejabberd_sql:sql_query(Host, ?SQL("update last set seconds=%(Val)s where username in %(ItemIds)ls")` and it worked when called with [<<"user1">>, <<"user2">>] as itemsids.

Do you get full stacktrace with that error?

**Comment by relbraun** [comment]
@prefiks you were right. There was another problem in my code syntax. Thank you for assistance.

**Comment by relbraun** [comment]
@licaon-kter the fix is that you have to use this syntax: `ejabberd_sql:sql_query(Host, ?SQL("update last set seconds=%(Val)s where username in %(ItemIds)ls")`. And it will work properly .
