### ISSUE TITLE
muc#roomconfig_changesubject is reported in disco info under nonstandard name muc#roominfo_changesubject

### ISSUE THREAD

**Issue by singpolyma** [processone/ejabberd#4085]
When doing disco on a MUC I expect to see the standard form field `muc#roomconfig_changesubject` to indicate if participants can change the subject.  Instead I see `muc#roominfo_changesubject` which is not part of https://xmpp.org/extensions/xep-0045.html#registrar

**Comment by badlop** [comment]
Thanks for reporting! I've fixed it in the `xmpp` library, and updated ejabberd to use that fixed version.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/processone/xmpp/issues/91
