### ISSUE TITLE
Relay pubsub/PEP to bare JID for MUC occupant JIDs

### ISSUE THREAD

**Issue by mwild1** [processone/ejabberd#4093]
**Is your feature request related to a problem? Please describe.**

- When sending stanzas to a MUC occupant JID (i.e. `room@service/nick`), those stanzas are typically forwarded to the occupant's *real full JID*. This behaviour is usually correct.
- However, certain `<iq/>` requests to a user should be addressed to the user's account (bare JID) instead of one of their devices (full JID).
- Such requests include `vcard-temp`, as well as requests to PEP nodes.
- ejabberd [already routes vcard-temp requests to the bare JID](https://github.com/processone/ejabberd/blob/a3f4a05b0cfab8917788caf60e29b504b4022ac1/src/mod_muc_room.erl#L1275) :+1: 
- ejabberd does not currently route pubsub/PEP queries to the bare JID :-1: 

**Describe the solution you'd like**

The current behaviour implemented for the `vcard-temp` namespace should be extended to include at least `http://jabber.org/protocol/pubsub` and possibly `urn:ietf:params:xml:ns:vcard-4.0` (Prosody also does the latter, but general consensus has been to remove the custom iq from the vcard4 XEP, so it may be deprecated soon).

This change would allow clients to support OMEMO, vCard4 and other PEP-based protocols within MUCs.

**Comment by poVoq** [comment]
Specifically, this would allow sending OMEMO encrypted PMs in an unencrypted public channel, which already works on Prosody hosted MUCs and some clients.

**Comment by licaon-kter** [comment]
This is when one user is a moderator/admin/owner so they see real XMPP address of the other?

**Comment by prefiks** [comment]
So does this require anything else than relying of <pubsub xmlns="http://jabber.org/protocol/pubsub"> queries?

**Comment by prefiks** [comment]
I commited d961f7f667b0c21f5256c1ba0c61878ea6754d74 that should be doing this.

**Comment by prefiks** [comment]
Make that 62d3d7a32d2dbae84dc16a85cd389ab814cefc15

**Comment by mwild1** [comment]
> So does this require anything else than relying of `<pubsub xmlns="http://jabber.org/protocol/pubsub">` queries?

Nope, that should be all :)

**Comment by mremond** [comment]
As I understand it, it should work now with ejabberd 23.10.
