### ISSUE TITLE
Add support for 'tls-exporter' channel binding method

### ISSUE THREAD

**Issue by mwild1** [processone/ejabberd#4105]
**Is your feature request related to a problem? Please describe.**

Ejabberd has supported channel binding (SCRAM-*-PLUS) for a long time, using the `tls-unique` method. Unfortunately this method is not compatible with TLS 1.3, which has seen rapid adoption over the past few years.

**Describe the solution you'd like**

Two things need to happen:

1. ejabberd should support `tls-exporter` for TLS 1.3 connections, as defined by [RFC 9266](https://www.rfc-editor.org/rfc/rfc9266)
2. Because multiple channel binding methods are possible, and SCRAM does not inform the client which one to use, authentication will fail if there is a mismatch. Therefore ejabberd **also** needs to advertise the channel binding methods in stream:features using [XEP-0440](https://xmpp.org/extensions/xep-0440.html). There is already a feature request at #3972 .

**Additional context**

Channel binding is an important defence against TLS MITM attacks, which as demonstrated in recent days are actively being used against XMPP services, and probably others.

**Comment by Neustradamus** [comment]
@mwild1: Thanks for your ticket, it is already in XMPP repository :)

Happy to see that SCRAM and TLS Channel Binding have more interest in this period.

It is linked to:
- https://github.com/processone/xmpp/issues/69
- https://github.com/processone/xmpp/issues/39
- https://github.com/processone/ejabberd/issues/2742
- https://github.com/processone/ejabberd-contrib/issues/279

**Comment by prefiks** [comment]
Do you guys know a client that supports this, so i would be able to test implementation for it?

**Comment by licaon-kter** [comment]
I think Conversations does since last year

**Comment by iNPUTmice** [comment]
We discovered yesterday that all released versions of Conversations only support Channel Binding when using Direct TLS so either keep that in mind when testing or use the master branch and/or [contact me directly](https://gultsch.de) if you either need an APK or someone to test this.

**Comment by Neustradamus** [comment]
@prefiks: Excellent, good job! :)
