### ISSUE TITLE
Improve authentication document to mention SCRAM plus support and SCRAM supported version

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#4108]
This page needs improvements: https://docs.ejabberd.im/admin/configuration/authentication/

The doc on SCRAM should also mention that option `auth_scram_hash: sha|sha256|sha512` can be used to tell what SCRAM method should be used.

Probably, we should move the SCRAM section upper in the auth document.

**Comment by Neustradamus** [comment]
Good point :)

**Comment by badlop** [comment]
OK, all done in https://github.com/processone/docs.ejabberd.im/commit/3e8b55c7232030fef0dd485e81b49b7d51029500, except this one:

> Probably, we should move the SCRAM section upper in the auth document.
