### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by samsunix** [processone/ejabberd#4114]
I installed ejabberd with `sudo apt install ejabberd`
How ever this didn't work out box with nginx so uninstalled and installed from latest x64 deb package.

This time I was able to enter and login with admin account. How ever admin privaledges were missing (as expected I guess)
so I head /opt/ejabberd/conf/ejabberd.yml but this configuration file doesn't correspond configuration examples on :
https://docs.ejabberd.im/admin/guide/managing/

For the record as writing this I still have not figured out this.

**Comment by licaon-kter** [comment]
You don't need nginx...

Peruse the guides first

https://www.process-one.net/blog/how-to-move-the-office-to-real-time-im-on-ejabberd/

https://www.process-one.net/blog/how-to-set-up-ejabberd-video-voice-calling/

https://www.process-one.net/blog/how-to-configure-ejabberd-to-get-100-in-xmpp-compliance-test/

https://www.process-one.net/blog/ejabberd-xmpp-server-useful-configuration-steps/

Then finish up with the [docs](https://docs.ejabberd.im).

**Comment by Neustradamus** [comment]
@samsunix: I think that you have done an error, it is `sudo apt install ejabberd`.
Can you edit?

**Comment by licaon-kter** [comment]
@samsunix close this then

**Comment by samsunix** [comment]
Workaround in comments
