### ISSUE TITLE
Compile error on ejabberd 23.10 with src/mod_muc_room.erl

### ISSUE THREAD

**Issue by itzzenxx** [processone/ejabberd#4116]
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 23.10
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.1`
- OS: Linux (Arch Linux)
- Installed from: source

## Errors from error.log/crash.log

No errors

## Bug description

When attempting to compile the latest version of ejabberd, this error appears:
```
src/mod_muc_room.erl:4418:8: undefined macro 'NS_OCCUPANT_ID'
src/mod_muc_room.erl:2581:17: function make_disco_info/2 undefined
src/mod_muc_room.erl:4389:2: spec for undefined function make_disco_info/2
src/mod_muc_room.erl:4442:17: function make_disco_info/2 undefined
src/mod_muc_room.erl:4521:14: function make_disco_info/2 undefined
Compiling src/mod_muc_room.erl failed:
ERROR: compile failed while processing /opt/ejabberd: rebar_abort
make: *** [Makefile:170: deps/.built] Error 1
```

**Comment by licaon-kter** [comment]
Was this a first compile or an update and compile? If an update did you run `make update` too before `make`?

**Comment by itzzenxx** [comment]
Running `make update` seemed to have fixed the issue, thank you!
