### ISSUE TITLE
Question about push notification?

### ISSUE THREAD

**Issue by taqveemahsan** [processone/ejabberd#4120]
Hello,

I am looking to push notifications to offline users in ejabberd. I've read that I need to add an external component to ejabberd to receive a notification when the user is offline. Afterward, I plan to use a backend service to retrieve the user's token from the database and send them a Firebase Cloud Messaging (FCM) notification.

I have explored open-source options for this external component, but many seem outdated. Could you please recommend an updated and reliable external component for ejabberd that supports this functionality?

Additionally, if there are any specific steps or examples for integrating OneSignal with ejabberd, I would greatly appreciate the guidance.

Thank you!

**Comment by licaon-kter** [comment]
If you use clients that are already in Play or AppStore (like Conversations or Siskin or Monal) all you need to do is:
```
modules:
  ...
  mod_push: {}
  mod_push_keepalive:
    wake_on_start: true
```

**Comment by licaon-kter** [comment]
If you'll deploy your own app on Play or AppStore, then you need a component like https://github.com/inputmice/p2 or  https://github.com/monal-im/fpush

**Comment by taqi121** [comment]
Because I am using 3rd party one signal to push notifications can you suggest one signal is better or I have to go with these https://github.com/inputmice/p2 or https://github.com/monal-im/fpush,?

**Comment by licaon-kter** [comment]
> Can i use this one?

...for ejabberd 2 from 200x? No

You need to setup notifications to Google and Apple, not to OneSignal or some third party that's NOT a system push provider or users devices.

Test them both and choose one of those two (p2 as used by Conversations for Play or fpush as used by Monal for AppStore)

**Comment by amit-ideasand** [comment]
How to setup https://github.com/monal-im/fpush in ejabberd , can someone help me in this.
