### ISSUE TITLE
Notify Socket Disable?

### ISSUE THREAD

**Issue by taqveemahsan** [processone/ejabberd#4122]
Hello, I'm encountering an error while installing the mod_push module in ejabberd.
root@chat:$ ejabberdctl module_install mod_push
WARNING: It is not recommended to run ejabberd as root
Error: error
Error: not_available

I have configured the p2 proxy module with ejabberd and am receiving logs from the ejabberd server. It gives log about <handshake><handshake> but didn't receive notifications on devices. 
2023-12-15 09:25:47.907284+00:00 [warning] <0.13127.0>@ejabberd_s2s_out:process_closed/2:157 Failed to establish outbound s2s conns connection chat.example.tech -> push.chat.example.tech: Connection failed: network is unreachable; bouncing for 214>
When a user attempts to send an SMS, ejabberd initiates a connection to "push.example.com," but encounters a connection refusal. How can both systems effectively address this situation?

**Comment by licaon-kter** [comment]
`mod_push` is already included, no need to 'install' anything

You've read https://github.com/iNPUTmice/p2/blob/master/docs/install.md#xmpp-server yet?

**Comment by taqi121** [comment]
Dec 15 10:51:48 chat.example.tech java[470355]: IN  (7483801069514495246): <iq from="0.0.0.0" id="714d7883-964b-46b6-be18-f235d24b84d1" to="0.0.0.0" type="result"></iq>
Dec 15 11:06:48 chat.example.tech java[470355]: OUT (7483801069514495246): <iq from="0.0.0.0" id="de1cafc8-003c-46c8-a4b9-6e678428b618" to="0.0.0.0" type="get"><ping xmlns="urn:xmpp:ping"></ping></iq>
Dec 15 11:06:48 chat.example.tech java[470355]: IN  (7483801069514495246): <iq from="0.0.0.0" id="de1cafc8-003c-46c8-a4b9-6e678428b618" to="0.0.0.0" type="get"><ping xmlns="urn:xmpp:ping"></ping></iq>
Dec 15 11:06:48 chat.example.tech java[470355]: OUT (7483801069514495246): <iq from="0.0.0.0" id="de1cafc8-003c-46c8-a4b9-6e678428b618" to="0.0.0.0" type="result"></iq>
Dec 15 11:06:48 chat.example.tech java[470355]: IN  (7483801069514495246): <iq from="0.0.0.0" id="de1cafc8-003c-46c8-a4b9-6e678428b618" to="0.0.0.0" type="result"></iq>
Dec 15 11:21:48 chat.example.tech java[470355]: OUT (7483801069514495246): <iq from="0.0.0.0" id="13eaa157-883a-41e7-9e9e-b8138ecb17d6" to="0.0.0.0" type="get"><ping xmlns="urn:xmpp:ping"></ping></iq>
Dec 15 11:21:48 chat.example.tech java[470355]: IN  (7483801069514495246): <iq from="0.0.0.0" id="13eaa157-883a-41e7-9e9e-b8138ecb17d6" to="0.0.0.0" type="get"><ping xmlns="urn:xmpp:ping"></ping></iq>
Dec 15 11:21:48 chat.example.tech java[470355]: OUT (7483801069514495246): <iq from="0.0.0.0" id="13eaa157-883a-41e7-9e9e-b8138ecb17d6" to="0.0.0.0" type="result"></iq>
Dec 15 11:21:48 chat.example.tech java[470355]: IN  (7483801069514495246): <iq from="0.0.0.0" id="13eaa157-883a-41e7-9e9e-b8138ecb17d6" to="0.0.0.0" type="result"></iq>

I got this kind of logs from p2 service.
