### ISSUE TITLE
XEP-0485: PubSub Server Information support

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#4125]
Can you add the "XEP-0485: PubSub Server Information" support?
- https://xmpp.org/extensions/xep-0485.html

You can see the demo here:
- https://xmppnetwork.goodbytes.im/

Openfire PubSub Server Info Plugin:
- https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pubsubserverinfo

Thanks in advance.

**Comment by Neustradamus** [comment]
Commits:
- @guusdk: https://github.com/processone/ejabberd-contrib/commit/f4472eda84f37df7622e5c0b98e7cb6d1e3b478c (https://github.com/processone/ejabberd-contrib/pull/327)
- @guusdk: https://github.com/processone/ejabberd-contrib/commit/9b9a6ec8900fc262ffef305176c5a4c6f64fad64 (https://github.com/processone/ejabberd-contrib/pull/328)
- @prefiks: https://github.com/processone/ejabberd-contrib/commit/d32347d6b3b359986d403841dcb9ef6bb09b660b
- @prefiks: https://github.com/processone/ejabberd-contrib/commit/80f503b274ae11c363c5f66bcebbf5de1587138f

**Comment by guusdk** [comment]
@Neustradamus As I've asked you a million times before: Please stop mentioning me!

**Comment by Neustradamus** [comment]
@prefiks: You have done a good job with this "ProtoXEP: PubSub Server Information" support.

Do you think that this ticket can be closed?
If yes, can you do it?

Note: Maybe there will be some little changes when the real XEP will be published.

**Comment by Neustradamus** [comment]
This ProtoXEP has now a number: XEP-0485: PubSub Server Information
- https://xmpp.org/extensions/xep-0485.html

**Comment by prefiks** [comment]
This is implemented by module in contrib.

**Comment by Neustradamus** [comment]
@badlop, @prefiks: Can you add in doap file with contrib module info?

**Comment by badlop** [comment]
> @Neustradamus Can you add in doap file with contrib module info?

Already done in https://github.com/processone/ejabberd/commit/103a30df2c25edbc99e4df6c5f11a2e99ed51a15
