### ISSUE TITLE
latest rpm from repo doesn't work via PAM

### ISSUE THREAD

**Issue by jhaar** [processone/ejabberd#4138]
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: ejabberd-23.10-1.x86_64
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.2.2.5
- OS: Linux (Fedora 38)
- Installed from:  official deb/rpm 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

I am trying to migrate from our old jabberd2 (PAM integrated) server to ejabberd. I got it installed and running with a local account, and then "flipped" it to PAM via adding the following lines to ejabberd.yml

```yaml
auth_method: 
  - pam
pam_service: ejabberd
```

Restarted, and tried logging in with local user "user1@domain.name". (ie the Linux username is "user1"). Failed login generated the following in ejabber.log

```
2024-01-03 18:46:59.815927+13:00 [warning] <0.739.0>@ejabberd_c2s:process_auth_result/3:280 (tls|<0.739.0>)
 Failed c2s PLAIN authentication for user1@domain.name from 1.2.3.4:
 Invalid username or password
```

..and the following PAM errors via syslog

```
Jan  3 18:39:22 domain.name epam[45099]:
 PAM unable to dlopen(/home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_deny.so):
 /home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_deny.so:
 cannot open shared object file: No such file or directory
Jan  3 18:39:22 domain.name epam[45099]: PAM adding faulty module:
 /home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_deny.so
```

So it looks like the ejabber binary in the repo is hard-linked to use some dev-installed version of PAM rather than the OSes version?

 e.g.  pam_deny.so is /usr/lib64/security/pam_deny.so under Fedora. I added a /etc/pam.d/ejabberd file and tried again - didn't make a difference.

**Comment by badlop** [comment]
You are right. For reference, I used those reproduction steps:

It's easy to reproduce the problem:

1. Install ejabberd 24.07 using any binary installer (RPM, DEB, RUN)

2. Configure ejabberd as you did

3. Setup PAM like this (in Debian it's `/etc/pam.d/ejabberd`):

``` sh
#%PAM-1.0
account     requisite  pam_unix.so audit
auth        requisite  pam_unix.so audit
```

4. Try to login. It will be rejected, and epam log shows:

```
journalctl -t epam -f

de set. 04 13:03:56 atenea epam[1067527]:
 PAM unable to dlopen(/home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_unix.so):
 /home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_unix.so:
 cannot open shared object file: No such file or directory
de set. 04 13:03:56 atenea epam[1067527]:
 PAM adding faulty module:
 /home/runner/build/ejabberd/x86_64-linux-gnu/lib/security/pam_unix.so
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) illegal module type: @include
de set. 04 13:03:56 atenea epam[1067527]: PAM pam_parse: expecting return value; [...common-auth]
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) no module name supplied
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) illegal module type: @include
de set. 04 13:03:56 atenea epam[1067527]: PAM pam_parse: expecting return value; [...common-account]
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) no module name supplied
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) illegal module type: @include
de set. 04 13:03:56 atenea epam[1067527]: PAM pam_parse: expecting return value; [...common-password]
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) no module name supplied
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) illegal module type: @include
de set. 04 13:03:56 atenea epam[1067527]: PAM pam_parse: expecting return value; [...common-session]
de set. 04 13:03:56 atenea epam[1067527]: PAM (other) no module name supplied
```

That same configuration works perfectly when ejabberd is compiled from source code!

> So it looks like the ejabber binary in the repo is hard-linked to use some dev-installed version of PAM rather than the OSes version?

Right, seems so. The path `/home/runner/` looks like the paths used by Github Actions, where the binary installers are generated.

This solution works for me: set the explicit path to the *.so file in my machine. With those settings, authentication works correctly:

``` sh
#%PAM-1.0
account     requisite  /usr/lib/x86_64-linux-gnu/security/pam_unix.so audit
auth        requisite  /usr/lib/x86_64-linux-gnu/security/pam_unix.so audit
```

> e.g. pam_deny.so is /usr/lib64/security/pam_deny.so under Fedora. I added a /etc/pam.d/ejabberd file and tried again - didn't make a difference.

Did you provide the full path to the *.so file, like I did?

**Comment by jhaar** [comment]
sorry, I reported this back in Jan and never found a fix, so I went back to jabberd-2

**Comment by badlop** [comment]
Ah, ok. Anyway, thanks to your problem report, I've updated the documentation about [PAM auth](https://docs.ejabberd.im/admin/configuration/authentication/#pam-authentication) to mention this problem and solution.

Thanks!
