### ISSUE TITLE
Need help in p2 push notification

### ISSUE THREAD

**Issue by Hamzify** [processone/ejabberd#4140]
Greetings!
I'm getting this error while sending notifications from the android app using fcm. anyone guide me?

failed to enable push. invalid response from app server <iq type="error" xml:lang="en" xmlns="jabber:client" id="n6t0nqBg_T0-" from="chat.woooo.world" to="+928794894948@chat.woooo.world/Woooo.b13C"><command node="register-push-fcm" xmlns="http://jabber.org/protocol/commands"><x type="submit" xmlns="jabber:x:data"><field var="token" xmlns="jabber:x:data"><value xmlns="jabber:x:data">cHn-x-y4T4CWeKqnVr0Dp4:APA91bE70iKq4XKRHZh6rRYnqWbgFZcCCPLclauJRF1qtP5JUmHxjjzyROPcADt0wfAlvLGuzV_aVMMgLT7SEAQ9onpKY_XKBmYVSIhJ07r26g9wSvqzCf5wRP_IfFCGFmgtrBgtwpr_</value></field><field var="android-id" xmlns="jabber:x:data"><value xmlns="jabber:x:data">de94b44f12fc91ab</value></field></x></command><error type="cancel" xmlns="jabber:client"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">No hook has processed this command</text></error></iq>

**Comment by Hamzify** [comment]
@licaon-kter

**Comment by licaon-kter** [comment]
I think both ProcessOne and Daniel Gultsch (p2) are available for hire.
