### ISSUE TITLE
Error While Sending Push Notification

### ISSUE THREAD

**Issue by Hamzify** [processone/ejabberd#4141]
Greeting.
I'm using P2 push proxy for sending notifications through FCM and APNS but when I try  to send from Application i receive this error 

failed to enable push. invalid response from app server <iq type="error" xml:lang="en" xmlns="jabber:client" id="n6t0nqBg_T0-" from="chat.woooo.world" to="+928794894948@chat.woooo.world/Woooo.b13C"><command node="register-push-fcm" xmlns="http://jabber.org/protocol/commands"><x type="submit" xmlns="jabber:x:data"><field var="token" xmlns="jabber:x:data"><value xmlns="jabber:x:data">cHn-x-y4T4CWeKqnVr0Dp4:APA91bE70iKq4XKRHZh6rRYnqWbgFZcCCPLclauJRF1qtP5JUmHxjjzyROPcADt0wfAlvLGuzV_aVMMgLT7SEAQ9onpKY_XKBmYVSIhJ07r26g9wSvqzCf5wRP_IfFCGFmgtrBgtwpr_</value></field><field var="android-id" xmlns="jabber:x:data"><value xmlns="jabber:x:data">de94b44f12fc91ab</value></field></x></command><error type="cancel" xmlns="jabber:client"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">No hook has processed this command</text></error></iq>

and in ejabberd logs it shows 
<0.1875.0>@mod_push:notify/5:539 push.tigase.im rejected notification for +244123456789@chat.woooo.world (01#0411330DA6D7BC8BBC11EE19F653DB6BF73D7935E4332FB86D119857A0F3473C), disabling push: XMPP error condition: item-not-found  (<tem-not-found) (cancel)

this error.
what's the issue?

**Comment by Hamzify** [comment]
@licaon-kter  do you know what's the issue?

**Comment by licaon-kter** [comment]
> push.tigase.im

So you are using Siskin from App Store? if so... you don't need to setup a push server locally

ONLY set in ejabberd.yml
```
modules:
  ...
  mod_push: {}
  mod_push_keepalive:
    wake_on_start: true
```

IF you have your own app that you'll publish in Play store or App Store.... then, and only then you'll need p2 and whatever. BUT then... tigase.im should not be contacted... because it's not YOUR server... you need to set IN YOUR APP a different address for your P2 instance

**Comment by Hamzify** [comment]
I'm using P2 and I send messages from the android app I already made all the changes but again this error is coming.

**Comment by Hamzify** [comment]
I already did what you told but we are sending a request to p2 and ejabberd from the Android App conversation.

**Comment by Hamzify** [comment]
> > push.tigase.im
> 
> So you are using Siskin from App Store? if so... you don't need to setup a push server locally
> 
> ONLY set in ejabberd.yml
> 
> ```
> modules:
>   ...
>   mod_push: {}
>   mod_push_keepalive:
>     wake_on_start: true
> ```
> 
> IF you have your app that you'll publish in the Play Store or App Store.... then, and only then you'll need p2 and whatever. But then... tigase.im should not be contacted... because it's not YOUR server... you need to set IN YOUR APP a different address for your P2 instance


I already did what you told but we are sending a request to p2 and ejabberd from the Android App conversation.
