### ISSUE TITLE
Clustering Issue: User Creation Not Synchronized Across Nodes in Ejabberd

### ISSUE THREAD

**Issue by taqveemmalik** [processone/ejabberd#4147]
Hello,

I've followed the clustering documentation (https://docs.ejabberd.im/admin/guide/clustering/#title) to successfully create a cluster with joined nodes. When I execute the 'ejabberdctl list_cluster' command, both nodes are listed, and I can also see them in the admin panel. I've set up the cluster using two different servers with IPs, for example, ejabberd01 (23.23.23.23) and ejabberd02 (24.24.24.24), and added hosts to the /etc/hosts file. I've ensured that everything is configured correctly as per the documentation.

However, I'm facing an issue where creating a user through the terminal using the command 'ejabberdctl register usman eb-stage01' or through the admin panel only results in the user existing on ejabberd01 and not on ejabberd02. It seems there is a lack of synchronization between my two nodes. I've set the same domain and hosts for both nodes.

How can I resolve this synchronization issue?

**Comment by prefiks** [comment]
And you have domain eb-stage01 defined in config file of both nodes?

**Comment by Taqveemammag** [comment]
Do you mean to say ejabberdctl.cfg or ejabberd.yml file?

**Comment by Taqveemammag** [comment]
Yes I've set hosts and domains also same for both nodes.
