### ISSUE TITLE
default_host is forgotten between consecutive HTTP requests

### ISSUE THREAD

**Issue by 7adietri** [processone/ejabberd#416]
In ejabberd 14.12, the setting `default_host` is not reliably being used in `ejabberd_http`. I noticed that the function `get_host_really_served()` often receives `undefined` as the first parameter, even if `default_host` is set in the config file.

This always seems to happen during the `POST` request to `/register/new`, which means that `mod_register_web` is not supporting virtual hosts at all right now.

**Comment by Beherit** [comment]
https://github.com/processone/ejabberd/issues/294 and https://github.com/processone/ejabberd/issues/291 ?

**Comment by 7adietri** [comment]
Fixing the handling of `default_host` won't add general support for virtual hosts to `mod_register_web`, so it's not the same issue, IMHO.
