### ISSUE TITLE
Getting error while adding new user to ejabberd server using admin commands "add-user"

### ISSUE THREAD

**Issue by rajeshbk042** [processone/ejabberd#418]
I am using sleekxmpp django package to communicate with ejabberd server.When I using admin command "add-user" to add user in ejabberd server  with the code snippet described in https://raw.githubusercontent.com/fritzy/SleekXMPP/develop/examples/admin_commands.py, getting error like this.

Username: usertrt@localhost
Password: 
Admin command: add-user
WARNING  DNS: dnspython not found. Can not use SRV lookup.
ERROR    Could not connect to [::1]:5222. Socket Error #111: Connection refused
connected True
INFO     Negotiating TLS
INFO     Using SSL version: TLS 1.0
WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
INFO     Authentication failed: not-authorized
INFO     Authentication failed: not-authorized
ERROR    No appropriate login method.
INFO     Waiting for </stream:stream> from server
ERROR    Error reading from XML stream.
Done

Please help me to fix this.

**Comment by mremond** [comment]
This is not an issue with ejabberd.

**Comment by rajeshbk042** [comment]
I am not able to add user into ejabberd with python.

**Comment by mremond** [comment]
Well it is not an ejabberd issue, likely your approach is incorrect: They are many restriction to add users over XMPP for obvious reasons that you should understand first. You should try ejabberdctl first to add users as this requires much less XMPP background.

**Comment by waghangad** [comment]
How can I create user JID, rooms in ejabberd using python. Which python library should I use please help.
