### ISSUE TITLE
Docs link not working

### ISSUE THREAD

**Issue by iamdanajr** [processone/ejabberd#4187]
The link for the docs of ejabberd isn't working, could please look into that. The page getting me a 502 Error which see to be server.

The link i'm currently browsing  is : https://docs.ejabberd.im

**Comment by badlop** [comment]
Yes, that is the correct URL. It seems to work right now, maybe it was some temporary server maintenance... Can you try again?

**Comment by licaon-kter** [comment]
Saw the same 4h or so ago :shrug: 

works fine now
