### ISSUE TITLE
store ejabebrd data into mongodb

### ISSUE THREAD

**Issue by HiteshSongra** [processone/ejabberd#419]
How can I store ejabberd data in MongoDB.

I tried this link https://github.com/kongo2002/ejabberd-mod-mam, but no luck.

Please let me know is it actually possible to store data in MongoDB? or i have to go with MySql, I also not got success with the MySql.

Please guide me for more.

Thanks.

**Comment by zinid** [comment]
There is no support for MongoDB. You should use either mysql or pgsql or riak.

**Comment by HiteshSongra** [comment]
Ok, Where can i found the well documentation for MySql.?

**Comment by zinid** [comment]
ejabberd configuration for mysql is described in the official guide.

**Comment by HiteshSongra** [comment]
Hi,

**Comment by zinid** [comment]
You're using too old version of ejabberd. And you should not use odbc driver. Use mysql driver directly. There is a working example of mysql in the documentation.

**Comment by HiteshSongra** [comment]
Can you please send me that documentation link.

On Thu, Jan 29, 2015 at 12:33 PM, Evgeny Khramtsov <notifications@github.com
> wrote:

> You're using too old version of ejabberd. And you should not use odbc
> driver. Use mysql driver directly. There is a working example of mysql in
> the documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/419#issuecomment-71979783>.
>



-- 
Thanks,
Hitesh Songra

**Comment by mremond** [comment]
http://www.process-one.net/docs/ejabberd/guide_en.html

**Comment by Neustradamus** [comment]
@hgsongra Have you found a solution for MongoDB?
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang
