### ISSUE TITLE
Return type of get_vcard API call changed (and is different from docs)

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#4198]
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 24.02
- OS: Linux (Debian)
- Installed from: source 

## Bug description

We have updated ejabberd from 21.04 to 24.04. 

We are now testing our application and we found that there are some API call changes. We updated our app according to current docs, however, we found change it `get_vcard`, which doesn't work as should according to docs. The `get_vcard` should return JSON like this:

```
HTTP/1.1 200 OK
        {"content": "User 1"}
```
but this is not true, currently it just returns a value like

```
HTTP/1.1 200 OK
User 1
```

Sure, we can update our application, but I'm not sure if this change is a bug or a feature, because the docs at https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#get-vcard don't reflect this change.

**Comment by badlop** [comment]
Right. That was changed in API v1, introduced in ejabberd 24.02. It is mentioned in the [24.02 release notes](https://www.process-one.net/blog/ejabberd-24-02/), in the section named `mod_http_api not named results`.

You can continue using API v0, which behaves as previous ejabberd versions, until you are able to update your ReST client.

What confused you is a problem in the documentation: the examples were not updated! Thanks for reporting, i'll investigate why they didn't get updated.

**Comment by badlop** [comment]
Documentation is updated, now it reflects the current behaviour, for example https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#get-vcard
