### ISSUE TITLE
Store data into nick column on archive table.

### ISSUE THREAD

**Issue by vietnguyen87** [processone/ejabberd#4200]
Sorry if i have a duplicate for this issue.!

I have a mysql database to stored message. I see **nick column on archive table**. How can i store and get data on **nick column** ? i using go xmpp library https://pkg.go.dev/github.com/xmppo/go-xmpp 
and send message by call **send_message API** https://docs.ejabberd.im/archive/24_02/admin-api/#send-message
 
![image](https://github.com/processone/ejabberd/assets/3839506/0b314406-cd59-4842-ba09-644b7e98b32f)

Thanks,

**Comment by badlop** [comment]
The `nick` field is only used to store the "room nickname" of the sender of a message in that chatroom that has archiving enabled. See [XEP-0045](https://xmpp.org/extensions/xep-0045.html). In the archive table, you will see only the `nick` stored when `type=groupchat`

Quite probably what you wanted is to know the nickname of a user that sent you a personal message. That information is not stored by mod_mam. In that case look in 
https://xmpp.org/extensions/xep-0054.html or https://xmpp.org/extensions/xep-0172.html
