### ISSUE TITLE
How to get the current date for created_at when create a Multi-User Chat.

### ISSUE THREAD

**Issue by vietnguyen87** [processone/ejabberd#4202]
I created a room with API https://docs.ejabberd.im/archive/24_02/admin-api/#create-room-with-opts . But column created_at in table muc_room was not getting the current date. 

![image](https://github.com/processone/ejabberd/assets/3839506/34197d98-4eb5-4c45-8ad7-1de0926bb708)

Help me fix this. Please.

**Comment by prefiks** [comment]
This column got repurposed, and now it keeps info about date of room hibernation (or sentinel value of 1970 when room is alive).

**Comment by prefiks** [comment]
So what you see here is correct behaviour per current code.

**Comment by vietnguyen87** [comment]
In case I want to know when this room was created, where can I get it? @prefiks

**Comment by prefiks** [comment]
You can't any more.

**Comment by vietnguyen87** [comment]
By the way, can you tell me? Can I get a list of members in the room with their roles via admin api ?

**Comment by vietnguyen87** [comment]
yes, i got it. But i get nothing when user disconnect.

**Comment by prefiks** [comment]
So you don't want to see roles but what affiliations are stored in a room (roles are only set for online users). Check https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#get-room-affiliations

**Comment by vietnguyen87** [comment]
Yeah, thanks so much. I also get another issue. Please help me. When i join a room, it's created many chat records in archive for all users in room like the image below. kind = chat. 

![image](https://github.com/processone/ejabberd/assets/3839506/6bd93a53-4ab2-401b-b24e-23c0fe690e14)

Please....

**Comment by prefiks** [comment]
What those messages contain? Could you expand xml of one of those?

They look like messages to individual room member (and not sent to all members of a room), and as such are stored in sender and recipient archive.

**Comment by prefiks** [comment]
This message have type "chat" so it's handled like regular message between two peers (as it in fact is), so it get stored in recipient and sender archive. What do you expect to happen with those message, they never get stored?

**Comment by prefiks** [comment]
Ah, those are mucsub events that are generated for muc messages. This is how mucsub works, it notifies subscribers that aren't in room, by sending those. And those message are allowed to be stored in archive or offline storage, because this is only way that offline user can know about those.

**Comment by vietnguyen87** [comment]
thanks @prefiks. Let's me clarify something
1. Multi User Chat in XMPP is presence based. When you are online you get the message. When you get offline, you leave the room and will not get anymore message until you join the room again by sending a presence message. The only way that offline user can receive message is use MUC/Sub protocol to subscribe to chat rooms.  And those message are allowed to be stored in archive or offline storage like a message between two peers.
2. To get history of user from the last message at (timestamp) in MUC/Sub i have to parse the xml column, right? in case, taking full control of the message management on the client side.

**Comment by prefiks** [comment]
Generally you don't need to parse anything, as there is already code in ejabberd that handles all this in mod_mam module, that respond to request described in https://xmpp.org/extensions/xep-0313.html.

Are you trying add external management of those outside ejabberd?

**Comment by vietnguyen87** [comment]
I'm talking with ejabberd by golang. and clients (Web/App) connect with Chat Service (golang) use go xmpp library https://pkg.go.dev/github.com/xmppo/go-xmpp

**Comment by prefiks** [comment]
Then you should send something like this: https://xmpp.org/extensions/xep-0313.html#filter-time (ideally example 8 from that), with time from last message that you seen, and you should receive messages that were archived after that one.

**Comment by vietnguyen87** [comment]
Thanks @prefiks, let's me try.

**Comment by Neustradamus** [comment]
@vietnguyen87: What are your news since your latest comment?

**Comment by vietnguyen87** [comment]
hi @Neustradamus ,
because i'm using ejabberd like a core chat system and golang service to communicate with client (Mobile app). So, i can handle something like: add created_at, get history chat... on my golang service.

**Comment by badlop** [comment]
I guess at this time, all the remaining questions were answered, or you have found an alternative solution.
