### ISSUE TITLE
Stream closed by local host: has been kicked (policy-violation)

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#4203]
## Environment

- ejabberd version: 22.05
- Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.1.4
- OS: Linux (Debian)
- Installed from: source

## Bug description

I am intermittently observing the following log line in ejabberd.yml for few users:

`2024-04-18 10:40:36.673207+05:30 [info] <0.27487.1212>@ejabberd_c2s:process_terminated/2:291 (tls|<0.27487.1212>) Closing c2s session for xyz@xxxx.yyyy.zzz/client: Stream closed by local host: has been kicked (policy-violation)`

I am observing this message multiple times during a certain time period during the day. I tried disabling mod_fail2ban for last 24 hours. But the message still keeps coming.

Does anyone know the reason behind this or how to debug the root cause?

Please help.

**Comment by prefiks** [comment]
This error would suggest that this was done with `kick_user` command (or server admin mod_adhoc invocation for kicking, which does use that internally).

**Comment by logicwonder** [comment]
Thanks @prefiks 
You were right. I was using the kick_user API. Need to investigate further.
