### ISSUE TITLE
Cannot compile ejabberd from source if yaml and expat are installed in custom prefixes

### ISSUE THREAD

**Issue by satnash** [processone/ejabberd#422]
Issue:

checking for erl... /opt/xmpp/erlang/lib/erlang/erts-5.10.1/bin/erl
checking for erlc... /opt/xmpp/erlang/lib/erlang/erts-5.10.1/bin/erlc
checking for yaml_parser_initialize in -lyaml... no
checking yaml.h usability... no
checking yaml.h presence... no
checking for yaml.h... no
configure: error: libyaml library was not found
ERROR: Command ['get-deps'] failed!
make: *** [deps/.got] Error 1

Steps
1. Installed erlang from source /opt/xmpp/erlang
2. Installed yaml from source in /opt/xmpp/yaml
3. Installed expat from source in /opt/xmpp/expat
4.  export PKG_CONFIG_PATH="/opt/xmpp/yaml/lib/pkgconfig:/opt/xmpp/expat/lib/pkgconfig"
5. export PATH=$PATH:/opt/xmpp/erlang/bin
6. .download ejabberd-14.12 from source.
7. cd ejabberd-14.12
8. ./configure --prefix=/opt/xmpp/ejabberd (No issues)
9. make 
10. Results in error above .

When I install expat and yaml in default prefix the compilation succeeds.

Am I missing something very basic? Any help is appreciated.

**Comment by weiss** [comment]
On Linux (and some BSD systems), this should do the trick:

    export CFLAGS='-I/opt/xmpp/expat/include -I/opt/xmpp/yaml/include'
    export LDFLAGS='-Wl,-L/opt/xmpp/expat/lib -Wl,-rpath,/opt/xmpp/expat/lib -Wl,-L/opt/xmpp/yaml/lib -Wl,-rpath,/opt/xmpp/yaml/lib'
    export PATH="$PATH:/opt/xmpp/erlang/bin"
    ./configure --prefix=/opt/xmpp/ejabberd 
    make
    make install

**Comment by satnash** [comment]
Weiss, thanks a lot, i had to do something similar --- 

./configure --prefix=/opt/pace/xmpp/ejabberd --with-erlang=/opt/pace/xmpp/erlang 
export CFLAGS="-I/opt/pace/xmpp/yaml/include -I/opt/pace/xmpp/expat/include" 
export LDFLAGS="-L/opt/pace/xmpp/yaml/lib -L/opt/pace/xmpp/expat/lib"  
make
