### ISSUE TITLE
Messages not getting send while receiving client is offline

### ISSUE THREAD

**Issue by egnun** [processone/ejabberd#4232]
## Environment

- ejabberd version: 24.02
- Erlang version: `erl +V`
- OS: Linux 
- Installed from:  official rpm

## Errors from error.log/crash.log

No errors

## Bug description

1. Since the update to the latest version there seems to be a bug, that when I am trying to send a message to a contact, who is offline, the messages doesn't get send at all.  I have to wait for the contact to be online again, so I can manually resend the message. Although this only really seems to be a problem with contacts, that are on my server. 

This bug also appears in MUCs, where all the contacts now have to be online at the same time, to receive the message. This also applies to contacts on other servers.

2. I have also noticed, that when one of my two clients is offline, that when I receive a message and then go online with the other client, the missing messages do not get synchronized.

It would be really good, if you could help. Because it has gotten to a point now, where a contact, who went to the German city of Celle was missing out on these fine remarks I have made in a reply:

> Are you going there for a party? Celle-bration time, come on!
And
> Or are you perhaps going to a concert? Is Célle-n Dion playing?

So, your help would be appreciated. ;-)

**Comment by licaon-kter** [comment]
Which clients are used? What error do they show? 

Do clean up and put your config on https://gist.github.com

**Comment by Neustradamus** [comment]
@egnun: Have you seen the @licaon-kter comment?

Can you add more details?

Thanks in advance.

**Comment by egnun** [comment]
Sorry, I was busy.

@licaon-kter here, is my config:

https://gist.github.com/egnun/f621edeb43598aaf2f706f5c8a74ace5

The clients don't really matter, as the bugs appear on all the different platforms. (Android, iOS, Windows, GNU+Linux)
As far as I can tell they don't show any errors. They just don't receive/send the messages.

**Comment by licaon-kter** [comment]
What do they show for a message that is not sent? They show it AS SENT? 

Try clarify who sees what, pics help.

Logs from clients?

**Comment by egnun** [comment]
I have just updated to 24.06 and it seems, that what ever caused the the problem, seems to be fixed.

So, thank you for the help, @licaon-kter and thank you, ejabberd folks, for you sedulous activity. 

But next time please don't make me open an issue first, before you push the update. 😉️

I am closing this issue now.

**Comment by licaon-kter** [comment]
Nobody understood your issue in the first place, not sure anyone did anything here :)
