### ISSUE TITLE
received messages latency too high

### ISSUE THREAD

**Issue by zzzZLRzzz** [processone/ejabberd#4235]
## Environment

- ejabberd version: 21.07
- OS: Linux 

## Bug description

I build a server **A** as an xmpp client to connect to ejabberd
sending messages to every other clients(one to many)
As **A**'s messages grows, ejabberd received message from **A**'s latency grows.
I found that ejabberd sent many "TCP ZeroWindow" to **A** when receiving messages.
I want to know where is the limit?

**Comment by licaon-kter** [comment]
Clean up your config and put it on https://gist.github.com

Which Linux exactly? Are you stuck on 21.07? Latest is 24.02, which is 3 years newer.

Which clients did you use? Are they from Google Play or Apple Appstore? Is Push being used?

Any errors in ejabberd.log with `loglevel: info` ?

Do you use Mnesia or SQL? If SQL, any logs there?

etc, add more details

**Comment by prefiks** [comment]
Your client may be hitting traffic shaper limits (default config limits how much bandwidth each client can use, and it just slows rate of processing of messages from client when limit is reached). Check https://docs.ejabberd.im/admin/configuration/basic/?h=shaper#shapers for a way to change them.

**Comment by zzzZLRzzz** [comment]
thanks, I edit the shaper config and it works!
