### ISSUE TITLE
Implement version 0.3.0 of XEP-0425: Moderated Message Retraction

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [processone/ejabberd#4237]
The DOAP file says that only version 0.2.1 of this XEP is supported which uses an old syntax based on XEP-0422 Message Fastening.

However, the same DOAP file says that [XEP-0424: Message Retraction](https://xmpp.org/extensions/xep-0424.html) is supported in version 0.4.0 which removed the dependency on message fastening, too.
Maybe only the DOAP file is wrong and the XEP-0425 implementation got modernized when XEP-0424 was implemented.

If not, please implement XEP-0425 without dependency on message fastening.

**Comment by licaon-kter** [comment]
This is not a duplicate of https://github.com/processone/ejabberd/issues/4193 ?

**Comment by badlop** [comment]
Ahh, the source code was updated, but the DOAP file isn't yet updated. I'll update later in a few minutes and report here, so you can verify if everything is up to date.

**Comment by badlop** [comment]
The DOAP file should now correctly describe the XEP version implemented.

**Comment by tmolitor-stud-tu** [comment]
Great, thanks!
