### ISSUE TITLE
mod_mam

### ISSUE THREAD

**Issue by prabhugithubme** [processone/ejabberd#4252]
mod_mam messages are deleted within 20 days (i mean in ejabberd arrive table  maintained only last 20 days messages only). How to increase or hot manage this messgae delete operation?.

**Comment by weiss** [comment]
ejabberd doesn't delete MAM messages automatically.  Maybe you created a Cronjob or systemd timer that calls `ejabberdctl delete_old_mam_messages`, or something?

**Comment by prabhugithubme** [comment]
Okay Thank you  got the reason as you are suggested.
