### ISSUE TITLE
Ejabberd service is responding slow

### ISSUE THREAD

**Issue by prabhugithubme** [processone/ejabberd#4253]
Hello team ,
           I am using  - ejabberd version: 21.12.0

## Environment:
- OS: Linux (Debian)
- Installed from:  package 

## Issue:
1)       When run any ejabberdctl commnad its responding after 12~15 seconds. (like ./ejabberdctl status / ./ejabberdctl reload_config etc) 
2) And also when i send any chat message from client 1 to cleint 2 its take minutes together to reach other client (checked by monitoring the port 5443 its recieved immedialty but sending the same takes time)

How to debug this issue please any suggestion for the same.

**Comment by licaon-kter** [comment]
Remember the issue template?
```
Before creating a ticket, please consider if this should fit the [discussion forum](https://github.com/processone/ejabberd/discussions) better.

## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
```

do that...

**Comment by Neustradamus** [comment]
@prabhugithubme: Can you give more informations, it is needed for ejabberd team?
