### ISSUE TITLE
24.06 rebar3 compatibility

### ISSUE THREAD

**Issue by AIIleG** [processone/ejabberd#4254]
Hi,

the 24.06 docs say:

> The lowest supported Erlang/OTP version continues being 20.0, and the recommendation is using 26.2

But trying to build it with Erlang 23 (official SUSE package) failed with:

```
configure: unlocking disabled rebar3 dependencies: epam,eredis,esip,p1_mysql,p1_pgsql,sqlite3,
=ERROR REPORT==== 12-Jul-2024::04:15:48.121119 ===
beam/beam_load.c(1886): Error loading module rebar3:
  This BEAM file was compiled for a later version of the run-time system than 23.
  To fix this, please recompile this module with an 23 compiler.
  (Use of opcode 172; this emulator supports only up to 170.)

escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
configure: unlocking rebar3 dependencies for old Erlang/OTP: jose,
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3

```
So it seems I have to rebuild rebar3 first. Where do I get the sources of the one that ships with the ejabberd source package?

**Comment by licaon-kter** [comment]
You're building from source? Is this a new, clean code clone or an old tree you just pull today?

**Comment by prefiks** [comment]
You will need to download older version of rebar3 i think https://github.com/erlang/rebar3/releases/tag/3.19.0 is the last version that supports r23, just replace existing one or point to it with `./configure --with-rebar=/path/to/rebar3`

**Comment by badlop** [comment]
> But trying to build it with Erlang 23 (official SUSE package) failed with:
> So it seems I have to rebuild rebar3 first. Where do I get the sources of the one that ships with the ejabberd source package?

Ah, right, when the rebar3 binary included with the ejabberd source code was updated, it was [mentioned in the commit message](https://github.com/processone/ejabberd/commit/081cab821b9fec3433236015a01b916511925fde) what Erlang versions are supported by that rebar3, and how to obtain an older rebar3 in case you want to compile with an older Erlang.

Unfortunately, that explanation was not copied into the ejabberd 24.06 release notes.

Here is the explanation

> Rebar/Rebar3: Update binaries to work with Erlang/OTP 24-27
> They are compiled from their git repositories, main branches,
> using erlang:24-slim docker image.
> 
> To compile ejabberd using rebar/rebar3 and Erlang 20.0 up to 23.3,
> you can download the old binaries from ejabberd 21.12, available at:
>   https://github.com/processone/ejabberd/raw/21.12/rebar
>   https://github.com/processone/ejabberd/raw/21.12/rebar3

**Comment by badlop** [comment]
I guess a paragraph explaining this should be included in the proper place (maybe in COMPILE.md, or Docs page, or release notes,...).

Let's keep the issie open to remember that task.
