### ISSUE TITLE
APNS push notification with p2 Proxy

### ISSUE THREAD

**Issue by Hamzify** [processone/ejabberd#4255]
I have configure p2 with our xmpp server and with android app and push notifications are working fine with android but in https://github.com/iNPUTmice/p2 no configuration is provided for APNS. I am trying to send the same stanza but the node name register-push-fcm i sent register-push-apns but it still not working kindly guide me how push notifications with apns will work?

**Comment by weiss** [comment]
This is a `p2` support request, not an ejabberd bug report.
