### ISSUE TITLE
Creating Default Chat Rooms via Ejabberd Config File.

### ISSUE THREAD

**Issue by gpadbidri** [processone/ejabberd#428]
I am new to the CHAT / MUC Development. I am using ConverseJS as my Chat Client and Ejabberd as my XMPP Server.
I have the following 2 queries :

1.
I want to create a "DEFAULT Chat Room named 'Lobby' for instance" using Ejabberd Config File. How can I do that ?

2.
When a user registers, I want ALL REGISTERED users to be part of the DEFAULT CHAT ROOM automatically. How can I achieve this ?

Can you kindly let me know how I can achieve this ? Any pointers could be great help. Thanks !

Best Regards,
Gauri Padbidri

**Comment by mremond** [comment]
1: You can simply create the chatroom as an admin and make it persistent. I will also be recreated after you restart the server.

2: Do you mean force users that have an account on the server to join the MUC room when they connect ? There is no standard way to do that as joining a MUC room is a client side operation. It requires either client cooperation and / or change in ejabberd code.

**Comment by gpadbidri** [comment]
Thanks for you reply...
For Point #2 : I mean, I want ALL registered users to be part of a "DEFAULT Chat Room" silently (in the background)...My need to do so is, I eventually want to list down ALL Registered Users, when the user logs in. Unlike the default behavior where you see only Users in your contact / roaster list after log in.

For Point #1 : If possible, Can you let me know the steps to create a Chat Room as an Admin and make it persistent ?

**Comment by mremond** [comment]
Creating a chat room can be done in an XMPP client. It depends on your client. Use Psi for example, join the room and edit the config.
Regarding point 2: This is not XMPP standard behaviour (And seems a hack ...)

**Comment by weiss** [comment]
@gpadbidri, do you _only_ need group chat (as opposed to 1:1 chat)?  If so, did you look into [Candy][1]?

[1]: https://candy-chat.github.io/candy/

**Comment by ranjeetlbsimds07** [comment]
Hello All, 
I have queries. How to create group on ejabberd sever(xmpp server ) and how to add member in the group.

Please help me.

Thanks in advance.

**Comment by mremond** [comment]
@ranjeetlbsimds07 Please do not post the same question on all tickets you find that may relate to your topic. Be kind with our team and our work.

**Comment by arpitmurkya** [comment]
I am also using ConverseJS as my Chat Client and Ejabberd as my XMPP Server. 
Similar query, i am unable to create persistent rooms.
default settings are for temporary(when all exit,room gets deleted) and i couldn't find where these can be changed.
please reply soon.

**Comment by gauripadbidri** [comment]
@arpitmurkya : I think using PSI is the best solution for this configuration as suggested by @mremond

**Comment by acarstoiu** [comment]
Sorry for reviving this thread, but @mremond says something that I fail to verify in practice:
> You can simply create the chatroom as an admin and make it persistent. I will also be recreated after you restart the server.

I've been struggling with this matter for a few days now and it all comes down to this: is there any reason why upon restart _ejabberd_ **deletes the existing contents of mnesia table `muc_room`**? It's as if this statement
``` erlang
            mnesia:create_table(muc_room,
                                [{disc_copies, [node()]},
                                 {attributes,
                                  record_info(fields, muc_room)}]),
```
in `mod_muc` erases the former disc contents :confused:

**Comment by badlop** [comment]
Are you sure your rooms are stored in the muc_room mnesia table? If you configure other backend, or the rooms aren't persistent, then they aren't stored there.

**Comment by acarstoiu** [comment]
Damn sure I am. The rooms are configured persistent, I even placed log messages to ensure that they get saved; I also connected to the same node and inspected mnesia.

I noticed that the data is actually written only in the `muc_room.DCL` and after a restart the contents of this file is gone. A manual `dump_log()` helps, nevertheless. Must be something trivial, but I'm out of ideas.
Doesn't mnesia replay logs upon restart?

**Comment by acarstoiu** [comment]
In case anyone wonders, mnesia is idiot enough to save data onto what it deems another node's schema and work hapily with it until restart, when it wipes everything in all tables, just because the node name was changed once upon a time.
Not my discovery.

**Comment by shajunr88** [comment]
In case anyone wonders, mnesia is idiot enough to save data onto what it deems another node's schema and work hapily with it until restart, when it wipes everything in all tables, just because the node name was changed once upon a time.
Not my discovery.
