### ISSUE TITLE
Remove Erlang R18 deprecation

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#430]
Here is an example of deprecation to remove before Erlang R18:

Warning: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
Warning: type gb_set/0 is deprecated and will be removed in OTP 18.0; use use gb_sets:set/0 or preferably gb_sets:set/1
Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2

**Comment by cromain** [comment]
fixed in 0c0947a
