### ISSUE TITLE
doap XEP-0384 support

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#4305]
reading https://xmpp.org/extensions/#xep-0384-implementations and I don't see ejabberd there

looks like Prosody says: https://hg.prosody.im/trunk/file/tip/doc/doap.xml#l780

and Mongoose says: https://github.com/esl/MongooseDocs/blob/gh-pages/latest/mongooseim.doap#L390-L394

can this be added here too, if ready? Ready by https://xmpp.org/extensions/xep-0384.html#server-side standards or by nature of the XEP being more of a client thing :shrug:

**Comment by badlop** [comment]
> reading https://xmpp.org/extensions/#xep-0384-implementations 

What a cool feature! That page shows, for each XEP, which software has announced its support! That will save a lot of time searching in each client website :)

> Ready by https://xmpp.org/extensions/xep-0384.html#server-side standards

Looking at mod_pubsub.erl and node_pep.erl, the four requirements are implemented, so yes, I'll add support for this XEP to the DOAP

Thanks!

**Comment by Neustradamus** [comment]
I use the xmpp.org website to see XEP supported version in projects, to request an update...
The .doap file is really important to be up-to-date and it permits to update easily the code when there is a new version...
