### ISSUE TITLE
SCRAM now breaks when client specifies incorrect channel binding options

### ISSUE THREAD

**Issue by mzealey** [processone/ejabberd#4322]
- ejabberd version: master + some custom patches
- Erlang version: erlang:26.2.5.2 docker container

## (updated) Bug description

At some point between 23.10 and 24.10, SCRAM (non-PLUS) is broken if client specifies `y,,` as gs2 in either stage 2 or 4 of the SCRAM auth process when connection is not on TLS and https://github.com/processone/ejabberd/commit/47232838 is applied and activated.

```
2024-12-03 14:19:37 [   DEBUG] SEND: <stream:stream to='user.moya' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'> (client.py:277)
2024-12-03 14:19:37 [   DEBUG] RECV: <stream:stream id="8070137133443078756" version="1.0" xml:lang="en" from="user.moya"> (xmlstream.py:574)
2024-12-03 14:19:37 [   DEBUG] RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-256</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features> (xmlstream.py:1422)
2024-12-03 14:19:37 [   DEBUG] SEND: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-256">eSwsbj11c2VyMixyPTk2Mjc5NjAxMzAyNjM0MTc=</auth> (client.py:277)
2024-12-03 14:19:37 [   DEBUG] RECV: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj05NjI3OTYwMTMwMjYzNDE3QWtUSndsNWV2emlFTjlwNWREQ1AvZz09LHM9U0JPNUFMUXlTMnN3NFRSYXdCNHdXQT09LGk9NDA5NixkPTB3Q0t6NFYzSE1BM3EyenhYamFDdmZkTVNuckZHV3Fna3Y3OTV6M3o3SFE9</challenge> (xmlstream.py:1422)
2024-12-03 14:19:37 [   DEBUG] SEND: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1lU3dzLHI9OTYyNzk2MDEzMDI2MzQxN0FrVEp3bDVldnppRU45cDVkRENQL2c9PSxwPStKR1lOZmdIMmE2R0dIRVlOZ1lNMWlLRlhCY0RMRExFT0pJeDVoS2pqaTg9</response> (client.py:277)
2024-12-03 14:19:37 [   DEBUG] RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized /><text xml:lang="en">Invalid channel binding</text></failure> (xmlstream.py:1422)
```

**Comment by mzealey** [comment]
It's been pointed out to me that the initial <auth stanza is requesting channel binding due to a bug in slixmpp library that I am using. However even when the initial SASL message is hacked to be `n,,n=user2,r=19739574602860177` it has the same result:

```
DEBUG    xmpp_tester.client:client.py:277 SEND: <stream:stream to='user.moya' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
DEBUG    slixmpp.xmlstream.xmlstream:xmlstream.py:574 RECV: <stream:stream id="11839171240327467659" version="1.0" xml:lang="en" from="user.moya">
DEBUG    slixmpp.xmlstream.xmlstream:xmlstream.py:1422 RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-256</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms></stream:features>
DEBUG    xmpp_tester.client:client.py:277 SEND: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-256">biwsbj11c2VyMixyPTc4NTUzNjQ2ODc1MjMyMTY=</auth>
DEBUG    slixmpp.xmlstream.xmlstream:xmlstream.py:1422 RECV: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj03ODU1MzY0Njg3NTIzMjE2U2hDZFZydzZ1VXd4NlhMc2VBcWJLdz09LHM9U0JPNUFMUXlTMnN3NFRSYXdCNHdXQT09LGk9NDA5NixkPTB3Q0t6NFYzSE1BM3EyenhYamFDdmZkTVNuckZHV3Fna3Y3OTV6M3o3SFE9</challenge>
DEBUG    xmpp_tester.client:client.py:277 SEND: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1lU3dzLHI9Nzg1NTM2NDY4NzUyMzIxNlNoQ2RWcnc2dVV3eDZYTHNlQXFiS3c9PSxwPTNIRnVpQ1pDNDAxaStmVHR6eXF0MTA4QW5sR2FRSXBqYUVtSnlqRlBCM1k9</response>
DEBUG    slixmpp.xmlstream.xmlstream:xmlstream.py:1422 RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized /><text xml:lang="en">Invalid channel binding</text></failure>
```

**Comment by mzealey** [comment]
OK as I didn't know the SCRAM protocol I couldn't see the bug in this 2nd issue which is that the 2nd send base64 decoded is:

```
c=eSws,r=7855364687523216ShCdVrw6uUwx6XLseAqbKw==,p=3HFuiCZC401i+fTtzyqt108AnlGaQIpjaEmJyjFPB3Y=
```

that `c` is base64 decoded as `y,,` meaning client is sending invalid data requesting channel binding 2nd time round.

So it's a bug in my program/library, however it was working just fine against ejabberd 23.10 - perhaps ejabberd should just ignore channel binding scram requests if client is not on a TLS connection? And I may not be aware of the spec fully but I *thought* that only -PLUS variants should handle channel-binding so perhaps it is more "if requested mech is not -PLUS then ignore channel binding requests" ?

**Comment by prefiks** [comment]
We can't ignore that really, as that would negate channel binding completely - it's there to ensure that there is no middle man between two endpoints, and if we would ignore that, everything that middle man would need switch to non-encrypted connection.

**Comment by prefiks** [comment]
This is what RFC 5802 says about it (that cover this protocol):

         If the flag is set to "y" and the server supports channel
         binding, the server MUST fail authentication.  This is because
         if the client sets the channel binding flag to "y", then the
         client must have believed that the server did not support
         channel binding -- if the server did in fact support channel
         binding, then this is an indication that there has been a
         downgrade attack (e.g., an attacker changed the server's
         mechanism list to exclude the -PLUS suffixed SCRAM mechanism
         name(s)).

**Comment by mremond** [comment]
From what I understand, I agree with @prefiks 
The issue seems related to client library (it should not require -plus). Adding an option in the server that to work around a client issue does not seem appropriate to me in terms of added complexity (to an already wide configuration spectrum) and commitment to maintain the workaround.

**Comment by mzealey** [comment]
OK thanks for the thoughts if that's what the RFC says then it sounds fair enough.

**Comment by prefiks** [comment]
After rethinking this, i commited change 06303ae7ab1ff7ce2d320561f2a0000d7a91d9ea (but real fix was in https://github.com/processone/xmpp/commit/28e4556353fbe57807a5d2f753f6ea8b707412c2) that do relax checks around channel binding when used external encryption with `allow_unencrypted_sasl2`. With that flag we look like server that doesn't know how to handle channel bindings, so probably checks that we perform in that mode should look like something that this server should do.

**Comment by prefiks** [comment]
Is  that on connection that is using allow_unencrypted_sasl2?

**Comment by mzealey** [comment]
correct

**Comment by prefiks** [comment]
Pushed another commit to master, please try it.

**Comment by mzealey** [comment]
Still no change - `Failed c2s SCRAM-SHA-256 authentication from 172.22.0.1: Invalid channel binding`

**Comment by prefiks** [comment]
Hm, ok, need to write proper test app then, my manual attempts show that working...

**Comment by mzealey** [comment]
Thanks, and the original reason I opened this ticket was because I believe it's a regression of sorts - if client was doing this against ejabberd 2 years ago it would have been accepted in without issue I believe.

**Comment by prefiks** [comment]
I added another commit that should make it work when authentication with sasl1 (as in your case).

**Comment by mzealey** [comment]
Many thanks; initial checks indicate this is working correctly

**Comment by mzealey** [comment]
@prefiks Another bug I'm afraid - it seems that your patch only works if `allow_unencrypted_sasl2: true` is applied to the listener. But this is (on a protocol level at least) nothing to do with sasl2, it's about SCRAM.

**Comment by prefiks** [comment]
That's by design, name of that option may be unfortunate, but what this does is a special case, and i don't plan to enable it in general case, as that would disable protection offered by channed bindings. This is something that server admin should enable just in special cases (like when having tls terminated outside ejabberd), and that option has already something with tihs.

**Comment by tmolitor-stud-tu** [comment]
> But how should it interact with -PLUS - as I understood it, channel binding only applies if -PLUS is specified. In this case server is not advertising it? Even in the case where -PLUS is advertised, if an adversary could mitm, if they could remove the -PLUS and change to a normal SCRAM request, they could presumably also alter messages from the client requesting channel binding?

@mzealey  You can find a nice writeup about how everything works and what flaws might be there over here: https://monal-im.org/post/00004-sasl/ and especially in this XEP, which includes a huge explanation section: https://xmpp.org/extensions/xep-0474.html
