### ISSUE TITLE
Can we convert/rewrite sslprotocol TLSv1.0 coming from client to TLSv1.1 or TLSv1.2 and forward with sslprotocol as TLSv1.1 or TLSv1.2 using Apache

### ISSUE THREAD

**Issue by Shahbazakhter** [processone/ejabberd#433]
Hello , 

I don't know whether this is the right place for my query, anyways it goes like.

I want to convert TLSv1.0 to TLSv1.1 or TLSv1.2, So that my outgoing request from my Proxy server is TLSv1.1/TLSv1.2. I can use Apache server.

Can someone Please Help !!

Any kind of Help is highly appreciated.

**Comment by mremond** [comment]
I do not think this opened issue is specific to ejabberd.

I am very sorry.
