### ISSUE TITLE
Systemd start script

### ISSUE THREAD

**Issue by tuxmaster** [processone/ejabberd#434]
Hello,
in install package, only an init.d start script is included.
To use systemd, the following can be used:
/usr/lib/systemd/system/ejabberd.service
[Unit]
Description=XMPP Server
After=network.target

[Service]
User=ejabberd
Group=ejabberd
LimitNOFILE=16000
RestartSec=5
ExecStart=/usr/bin/bash /opt/ejabberd/bin/ejabberdctl start
ExecStop=/opt/ejabberd/bin/ejabberdctl stop
Type=oneshot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

This was used under Fedora.

**Comment by mremond** [comment]
Thanks :)

**Comment by tuxmaster** [comment]
simple add on for the new reload function:
[Service]
...
ExecReload=/opt/ejabberd/bin/ejabberdctl reload_config

**Comment by cromain** [comment]
Added in e0ffcbe
Thanks.
