### ISSUE TITLE
Is mod_muc_log still working?

### ISSUE THREAD

**Issue by ways** [processone/ejabberd#447]
All mentions of it on the website seems years old, but I see it in /opt/ejabberd/lib/ejabberd-15.02/ebin/mod_muc_log.beam

When attempting to activate it using:
>   mod_muc_log: {[
>    {access_log, muc},
>    {outdir, "/var/www/muclogs"}
>  ]}

I get:
> 15:23:35.744 [error] CRASH REPORT Process <0.40.0> with 0 neighbours exited with reason: {undefined_macro,''} in application_master:init/4 line 133
> 15:23:35.744 [info] Application ejabberd exited with reason: {undefined_macro,''}

**Comment by badlop** [comment]
Where did you find that configuration example? Its syntax is wrong. See the ejabberd Guide.

**Comment by ways** [comment]
Ah, you're right. It was from the old config format.
>   mod_muc_log: 
>    access_log: muc
>    outdir: "/var/www/muclogs"
worked much better.
