### ISSUE TITLE
Ejabberd with riak db

### ISSUE THREAD

**Issue by singhalavi** [processone/ejabberd#451]
I am getting below exception while trying to use riak db with mod_muc

[critical] <0.38.0>@ejabberd:exit_or_halt:123 failed to start application 'riakc': {error,
                                      {"no such file or directory",
                                       "riakc.app"}

i added db_type: riak in ejabberd.yml file

I am using ejabberd community edition installed from binaries
ejabberd version 14.12
riak version 2.0.5

Please help ?

**Comment by zinid** [comment]
Do you have any riak related BEAM files in `ebin` directory? For example, `riakc_obj.beam`.

**Comment by singhalavi** [comment]
Thanks for quick response

yes i have three beam files in this folder ejabberd-14.12/lib/ejabberd-14.12/ebin

ls | grep riak
ejabberd_auth_riak.beam
ejabberd_riak.beam
ejabberd_riak_sup.beam

**Comment by mremond** [comment]
It means you are missing the riak client library. Did you build ejabberd yourself ? Did you make sure you enabled Riak in the build ?

**Comment by zinid** [comment]
@mremond he installed it from binary installer, I think the installer lacks Riak support. I reassign to @cromain

**Comment by mremond** [comment]
@singhalavi At the moment, you need to build ejabberd from source to enable Riak client support. However, we plan to package Riak client library in installer for next release.
Thanks for your feedback !

**Comment by cromain** [comment]
riak support is now enabled by default in our installer, i'll close this ticket when next installer will be released.

**Comment by cromain** [comment]
riak included in installer since 15.03
