### ISSUE TITLE
Add options for not logging IPs

### ISSUE THREAD

**Issue by schwindp** [processone/ejabberd#452]
Could we please have an option for not logging IPs in module ejabberd_c2s in ejabberd.log?

**Comment by mremond** [comment]
Maybe we should only log the IP in debug mode ? Did that make sense ?

**Comment by weiss** [comment]
> Maybe we should only log the IP in debug log level ?

IP addresses should always be included with debug messages, but I think many admins would also like to see the IP addresses in their normal `[info]` level log files.  So I'd prefer to to make this configurable.

I can add an option if everyone is fine with that.  If so: Should hiding of IP addresses be restricted to c2s connections?  Or do we want both an `ejabberd_c2s` option and a global one?

**Comment by mremond** [comment]
I see your point. Maybe then we just want a global option that is "hide IP in log files". We could call a method to wrap IP address to decide if we should log them or not. What do you think ?

@schwindp Would that do what you want ?

**Comment by schwindp** [comment]
*nodnod* that's exactly what I wished for.

**Comment by mremond** [comment]
I would call the option "hide_sensitive_log_data" in configuration file. We could force hide password as well with that option, no matter what is log level, as suggested on #471.

**Comment by cromain** [comment]
+1
