### ISSUE TITLE
Help! Messages dont get delivered to Online users - They just go to offline

### ISSUE THREAD

**Issue by altagar-asaf** [processone/ejabberd#457]
hi guys,

i'm having a very weird problem,

all the messages that i send , Even to Online users, are never sent to the user.
ejabberd just saves them to the offline messages list and never forwards them the online user.

anyone encountered something like that?

p.s - web admin's "Last Activity" always displays "Never", even if the user was logged in ( previously displayed "Online" ) - any thoughts?

thank you!
asaf

**Comment by beherit** [comment]
Maybe just check on other IM ;)

**Comment by mremond** [comment]
Which client are you using ? Is it a custom one ? Did you try with another client ?

**Comment by altagar-asaf** [comment]
i'm using my own client. 

the thing is, i do receive iq stanzas.  only messages gets queued to the offline queue.

when i log-in, the web admin displays "Online" status in the last activity. but when i log-out it displays "Never". 

i'm really frustrated by this issue which i encounter for the first time today. it used to work fine.

any thoughts on to why this happens?

**Comment by mremond** [comment]
You should check your traffic logs. Did you send a presence packet ?

**Comment by mremond** [comment]
As this is not an issue with ejabberd, but with your client, can we please continue the discussion on the thread you also opened in ejabberd.im forum ?

For reference the post is: 
https://www.ejabberd.im/node/24792#comment-65312

**Comment by altagar-asaf** [comment]
of course :)

sorry for the double booking, its a production critical issue for me :)

**Comment by altagar-asaf** [comment]
OMG!
thank you! 

i didnt realize that i HAVE to manually send a presence after log-in, and i tried to lower connection negotiations by removing that element from my log-in process.

i will close both issues.

tnx again @mremond :)
