### ISSUE TITLE
mod_irc may use the wrong nick to join a channel

### ISSUE THREAD

**Issue by ehuelsmann** [processone/ejabberd#464]
When a user requests to join an irc channel on a server that he's already connected to, mod_irc doesn't check what nick the user uses in the room jid. For each different nick, there should be a different IRC connection. However, currently any join request from the same user JID will re-use the existing connection, which means second and subsequent joins may ignore a different nickname if/when requested.

(Note: I've only discovered the above by accident. I have currently no personal need to see this fixed, but if/when someone works on refactoring/cleaning up mod_irc, it'd be something to take into account.)

**Comment by kousu** [comment]
I do have a personal need to see this fixed and I would like to collaborate!

I think that one connection per nick is confusing: it should either be one per room or one per user. And one per room will explode into too many TCP connections, and doesn't get along with IRC semantics, which assume that you will be on multiple rooms at once and can be PM'd from any of them, so I favour one per user.

As for UI, mod_irc provides XMPP services that let you configure the nick, server, port, password (but only for the PASS command, not for SASL or NickServ), and text encoding. There is an XMPP Registration form buried in get_form/5, and a series of XMPP Ad Hoc commands in generate_adhoc_register_form/3 amd adhoc_join/3, but Pidgin only supports the first and only if you turn on a plugin (and it tacitly assumes you're trying to configure a MUC), Xabber and Conversations definitely support neither, and of what I've tested only Gajim supports both. In principle, using the XMPP form interface is correct, but the client UI just isn't there to make it usable. Also the current design that hangs your entire IRC connection off of a MUC is awkward---I can see why it seemed like a good idea, but IRC supports PM just as well as XMPP and while mod_irc will do PMs, it has  glitches that make PMs second class.

Instead, keeping in the spirit of IRC, I would like IRC slash commands to work via XMPP: a message to irc.xmppserver.tld should be like typing at a blank irssi session, so sending "/server irc.freenode.net" to irc.xmppserver.tld opens an IRC connection to freenode *and* opens a chat with JID "irc.freenode.net@irc.xmppserver.tld", where the MOTD and other info should show up (it currently gets eaten as "unrecognized IRC command"). "/join #channel" spoken to "((.+)(!|%))?irc.freenode.net@irc.xmppserver.tld" -- that is, the server window or any PM or channel window that xmppserver.tld is proxying to freenode -- should send the appropriate IRC commands and open a window for channel%irc.freenode.net@irc.xmppserver.tld. The MUC UI ("Add Conference" in Xabber, "Join Chat" in Pidgin) should just be shortcuts to this structure. What do you think? Crazy? An overwhelming rewrite?

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
