### ISSUE TITLE
Check if under some circumstances make install could fail

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#468]
This is the relevant error in ejabberd make install log:
 
```
/usr/bin/install: `inetrc' and `//etc/ejabberd/inetrc' are the same file
make: *** [install] Error 1
```
Reference: https://www.ejabberd.im/node/20609

Could it happen as comment suggested if you try installing the app several times ?

**Comment by cromain** [comment]
yes its due to install twice without uninstall first. but that's odd cause we use install -b, which should move old inetrc to inetrc.old before copy new file instead of complain. will need to run some tests here and make install more tolerant in this case.

**Comment by cromain** [comment]
prevent errors cases when test fail. this is cosmetic but improve normal operation anyway.

**Comment by chazdiezal** [comment]
how do you fix this? make install and make clean did not work
