### ISSUE TITLE
XEP-0309: Service Directories support

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#469]
Can you add the XEP-0309 support in ejabberd?

It was requested in the JIRA ticket : https://support.process-one.net/browse/EJAB-1528 (with other requests) : 05/01/12 04:39.

It is for the XMPP auto server list.

**Comment by drixter** [comment]
Any update?

**Comment by mremond** [comment]
It is a feature request. We are well aware of It but it looks like nobody had the time to work on it yet.

That said, if you want to give a try and work on that feature, please go ahead. We will definitely review and give feedback on your PR.

Thanks !

**Comment by drixter** [comment]
Sorry, but i'm not a developer :-/ also I can't see any option of possible donation (paypal?) for devs to faster develop this feature.

**Comment by badlop** [comment]
XEP-0309 is deferred.
