### ISSUE TITLE
Make install - missing destination file

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd#474]
```text
[vagrant@localhost ~]$ cd /usr/src
[vagrant@localhost src]$ sudo git clone --quiet git://github.com/processone/ejabberd.git ejabberd-src
[vagrant@localhost src]$ sudo chown -R vagrant.vagrant ejabberd-src
[vagrant@localhost src]$ cd ejabberd-src
[vagrant@localhost ejabberd-src]$ ./autogen.sh
[vagrant@localhost ejabberd-src]$ ./configure --prefix=/opt/ejabberd
....
[vagrant@localhost ejabberd-src]$ sudo make install
....
#
# Binary system libraries
/usr/bin/install -c -d /opt/ejabberd/lib/ejabberd/priv/lib
/usr/bin/install -c -m 644   /opt/ejabberd/lib/ejabberd/priv/lib
/usr/bin/install: missing destination file operand after `/opt/ejabberd/lib/ejabberd/priv/lib'
Try `/usr/bin/install --help' for more information.
make: *** [install] Error 1
[vagrant@localhost ejabberd-src]$ 
```

**Comment by mremond** [comment]
Thanks, we are having a look.

**Comment by mremond** [comment]
It seems that it means your .so file where not built. Do you have more info before in the log ?
Did you run the make command before ? What is the result of the make command ?

**Comment by cromain** [comment]
in your Makefile, the following line just matches nothing
DLLs := $(wildcard deps/*/priv/*.so) $(wildcard deps/*/priv/lib/*.so)
this means dependencies did not compiled (for example you miss deps/p1_xml/priv/lib/expat_erl.so)
and so, make install complains

**Comment by RobertLarsen** [comment]
I followed the guide at http://docs.ejabberd.im/admin/guide/
Running 'make' without arguments yields no problems.

Gist for separete 'make' and 'make install':
./configure && make && sudo make install -> https://gist.github.com/RobertLarsen/37003e1a1414b9ab05bb

Gist for only 'make install'
./configure && sudo make install ->  https://gist.github.com/RobertLarsen/76e4a8dcbb05b87c3241

**Comment by mremond** [comment]
Glad you have it working. We will have a look to see why "make install" does not have same result that "make && make install".

Thanks !

**Comment by RobertLarsen** [comment]
@mremond I don't have it working yet. The 'make' command alone did not yield problems, but 'make install' still does as you can see in my gist.

@cromain There are obj files in those folders (following './configure && sudo make install):
```
# Binary system libraries
/usr/bin/install -c -d /opt/ejabberd/lib/ejabberd/priv/lib
/usr/bin/install -c -m 644   /opt/ejabberd/lib/ejabberd/priv/lib
/usr/bin/install: missing destination file operand after `/opt/ejabberd/lib/ejabberd/priv/lib'
Try `/usr/bin/install --help' for more information.
make: *** [install] Error 1
[vagrant@localhost ejabberd-src]$ ls deps/*/priv/*.so deps/*/priv/lib/*.so
deps/esip/priv/esip_drv.so
deps/p1_iconv/priv/lib/iconv.so
deps/p1_stringprep/priv/lib/stringprep.so
deps/p1_tls/priv/lib/p1_sha.so
deps/p1_tls/priv/lib/p1_tls_drv.so
deps/p1_xml/priv/lib/expat_erl.so
deps/p1_yaml/priv/lib/p1_yaml.so
deps/p1_zlib/priv/lib/ezlib_drv.so
```

**Comment by cromain** [comment]
are you using bsd make or gnu make ?

**Comment by weiss** [comment]
FWIW, I can reproduce the issue by running `make install` without `make`.

> The 'make' command alone did not yield problems, but 'make install' still does as you can see in my gist.

As far as I can see, that Gist looks fine.  There are a few messages because some optional components were omitted, but `make install` succeeded.

**Comment by mremond** [comment]
What I see in the Gist is that doing make and then make install work. 
Based on this Gist: https://gist.github.com/RobertLarsen/37003e1a1414b9ab05bb

It seems you can compile and install the server properly, no ?

From what I see: The .so file are generated and installed properly.
What you see is 'ignored' error. It is ignored because it can be safely ignored:

```
make: [install] Error 1 (ignored)
```

If you see in the Makefile, the issue is recoverable. We will try hiding those recoverable errors totally, but you can try starting ejabberd it should be installed already.

**Comment by RobertLarsen** [comment]
@cromain I use GNU Make 3.81

@mremond Ok, you may be right...got confused by the errors.
```
[vagrant@localhost ~]$ sudo /opt/ejabberd/sbin/ejabberdctl start
[vagrant@localhost ~]$ sudo /opt/ejabberd/sbin/ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 15.02.76 is running in that node
```

I think it would be a good idea to hide the errors if they could be safely ignored.

**Comment by mremond** [comment]
Thanks, @RobertLarsen 
Sure, we will improve that part.
