### ISSUE TITLE
Existing items in pubsub database contains old XML records after migration from ejabberd 2.1

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#479]
This commit is not enough to fully convert the pubsub table:  cc958f77

We need to convert xmelement to the new xmlel record.

This is reported on ejabberd forum: https://www.ejabberd.im/node/24805

**Comment by idl0r** [comment]
I upgraded from 14.x and I had similar issues. I disabled mod_pubsub for now so clients are able to connect again. I'm not 100% sure yet if that is exactly the same error though.

**Comment by btittelbach** [comment]
Had similar problem and used same "solution" as idl0r.

On "https://www.ejabberd.im/node/24805" someone suggested this command to clean out old data:
```
[mnesia:delete_table(T) || T<-[pubsub_last_item,pubsub_state,pubsub_item,pubsub_node,pubsub_subscription]].
```
Unfortunately ```ejabberctl debug``` doesn't easily connect to my jabber server (on gentoo), so I couldn't test it.

**Comment by miracle2k** [comment]
I upgraded from 14.07 / 15.04 and my error was this:

     exception exit: {{badarg,[{xml,element_to_binary,[{xmlel,<<"message">>,[{<<"from">>,<<"michael@example.com">>},{<<"to">>,<<"blumen@example.com/SkyLand">>},{<<"type">>,<<"headline">>}],[{xmlel,<<"event">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/pubsub#event">>}],[{xmlel,<<"items">>,[{<<"type">>,<<"headline">>},{<<"node">>,<<"http://jabber.org/protocol/tune">>}],[{xmlel,<<"item">>,[{<<"id">>,"559B924B1D811"}],[{xmlelement,"tune",[{"xmlns","http://jabber.org/protocol/tune"}],[]}]}]}]},{xmlel,<<"delay">>,[{<<"xmlns">>,<<"urn:xmpp:delay">>},{<<"from">>,<<"michael@example.com/notebook">>},{<<"stamp">>,<<"2013-05-28T16:25:47Z">>}],[{xmlcdata,<<>>}]}]}],[]},{ejabberd_c2s,send_element,2,[{file,"src/ejabberd_c2s.erl"},{line,1908}]},{ejabberd_c2s,send_stanza,2,[{file,"src/ejabberd_c2s.erl"},{line,1923}]},{ejabberd_c2s,handle_info,3,[{file,"src/ejabberd_c2s.erl"},{line,1770}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

Disabling mod_pubsub seems to have fixed it.

**Comment by cromain** [comment]
i'll try to add function in pubsub_migrate which reads all items payload and switch from old xmlelement to new xmlel.

**Comment by kepi** [comment]
You can delete content of those tables through web interface. No need to use debug console. Worked for us even without ejabberd restart.

**Comment by cromain** [comment]
i added pubsub_migrate:update_item_database to help on this. it can be called manually when need to migrate very old database.
i could not get old entries with 14.07 anyway so did not tested it out of simple manual test.
