### ISSUE TITLE
 Can't register user after changing the auth_method to odbc ejabberd 15.02

### ISSUE THREAD

**Issue by azimsai** [processone/ejabberd#480]
I had installed ejabberd 15.02 on ubuntu 14.04.After changing to mysql i tried to register a user using ejabberdctl its showing an error "Can't register user admin@localhost at node ejabberd@localhost: not_allowed" . If the auth_method is internal registration is working properly.

Error log
```2015-03-18 16:49:42.729 [info] <0.38.0>@ejabberd_app:start:71 ejabberd 15.02.78 is started in the node ejabberd@localhost
2015-03-18 16:49:42.730 [info] <0.7.0> Application ejabberd started on node ejabberd@localhost
2015-03-18 16:50:27.648 [debug] <0.606.0>@ejabberd_commands:execute_command2:319 Executing command ejabberd_admin:register with Args=[<<"admin">>,<<"192.168.0.35">>,<<"admin">>]
2015-03-18 16:53:49.540 [debug] <0.610.0>@ejabberd_commands:execute_command2:319 Executing command ejabberd_admin:register with Args=[<<"admin">>,<<"localhost">>,<<"admin">>]```

In ejabberd.yml 

``` 
###   SERVED HOSTNAMES
hosts:
  - "xmpp.local"
  - "localhost"
  - "192.168.0.35"

## MySQL server:
  -
   auth_method: odbc
   odbc_type: mysql
   odbc_server: "127.0.0.1"
   odbc_database: "ejabberd"
   odbc_username: "root"
   odbc_password: "root"

###   ACCESS RULES
access:
  max_user_sessions: 
    all: 10
  max_user_offline_messages: 
    admin: 5000
    all: 100
  local: 
    local: allow
  c2s: 
    blocked: deny
    all: allow 
  c2s_shaper: 
    admin: none
    all: normal 
  s2s_shaper: 
    all: fast
  announce: 
    admin: allow 
  configure: 
 admin: allow
    muc_admin: 
    admin: allow 
  muc_create: 
    local: allow 
  muc: 
    all: allow
    admin: allow
  pubsub_createnode: 
    local: allow
  register: 
    all: allow
###   MODULES
modules: 
  mod_adhoc: []
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_caps: []
  mod_carboncopy: []
  mod_configure: [] 
  mod_disco: []  
  mod_http_bind: []  
  mod_last: [{db_type: odbc}]
  mod_muc:
    db_type: odbc  
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_offline:
    db_type: odbc 
    access_max_user_messages: max_user_offline_messages
  mod_privacy: [{db_type: odbc}]
  mod_private: [{db_type: odbc}]  
  mod_pubsub:
    db_type: odbc 
    access_createnode: pubsub_createnode   
    ignore_pep_from_offline: true   
    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
 - "pep" 
  mod_register:     
    welcome_message: 
      subject: "Welcome!"
 body: |-
        Hi.
        Welcome to this XMPP server. 
    ip_access: trusted_network 
 access: register
  mod_roster: []
  mod_shared_roster: []
  mod_vcard: [{db_type: odbc}]
  mod_version: []

```

**Comment by mremond** [comment]
Do you have more input in your log ? I do not see any error in your posted log snippet.

**Comment by mremond** [comment]
It seems the indentation of your odbc section is wrong. The odbc element are at the global level.

I think it should be:

```yaml
## MySQL server:
auth_method: odbc
odbc_type: mysql
odbc_server: "127.0.0.1"
odbc_database: "ejabberd"
odbc_username: "root"
odbc_password: "root"
```
