### ISSUE TITLE
ERROR: compile failed while processing /home/pi/ejabberd/deps/p1_stun: rebar_abort

### ISSUE THREAD

**Issue by zarere** [processone/ejabberd#482]
Hi there,

I'm trying to install the latest ejabberd 15.02 from git  on raspberry pi.I'm doing the following steps:

    git clone git://github.com/processone/ejabberd.git ejabberd
    cd ejabberd
    ./autogen.sh
    ./configure

and I got the following error on the ./configure step:

    ERROR: compile failed while processing /home/pi/ejabberd/deps/p1_stun: rebar_abort
    Makefile:84: recipe for target 'deps/.built' failed
    make: *** [deps/.built] Error 1

Please advise
Best Regards

**Comment by weiss** [comment]
Could you paste the last few lines that preceeded the `ERROR: compile failed` message?

**Comment by zarere** [comment]
Hi there,

Actually I was able to fix the issue with installing the correct erlang package as described in the install guide and the error is gone now.Thanks for the fast response.

**Comment by miradnan** [comment]
I am getting same error too

**Comment by Jethvasagar** [comment]
remove deps dir and rerun make command
