### ISSUE TITLE
epmd command not found after ejabberd install

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#484]
Symptom is error: "/sbin/ejabberdctl: lint 356: epmd: command not found"

There is a discussion on forum on possible quick fix:
> The problem is epmd isn't in the path of the ejabberdctl script.
> The (quick fix) is at the top of bin/ejabberdctl, add in:
> PATH=$PATH:$(dirname $(readlink -f $0))
> under INSTALLUSER=

Reference: https://www.ejabberd.im/node/5748

**Comment by cromain** [comment]
best fix is to set EPMD={{bindir}}/epmd on top ej ejabberdctl.template then call $EPMD in place of epmd.
fixed in 7976d3e

**Comment by jonluechen** [comment]
there is no epmd on path {{bindir}}, if you use --prefix to install ejabberd to different path
actually, the epmd is always located at the same path with erl
so set EPMD=${ERL%/*}/epmd maybe better
