### ISSUE TITLE
Support for XEP-0079: Advanced Message Processing

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#485]
There was a patch long ago with partial support for XEP-0079.
Includes a patch against r1049 to add a new hook (filter_local_packet).

Reference ticket was: https://support.process-one.net/browse/EJAB-449

**Comment by shyaken** [comment]
is there any patch for this? I really need AMP on my server, but I don't know how :'(

**Comment by mremond** [comment]
No patch, yet, no, but AMP is not really the trend in XMPP world. The trend is more to build on top of MAM. Did you look into MAM ? Can't you build your features on top of Message Archiving ?

**Comment by shyaken** [comment]
oh, I didn't look into MAM yet, Let me have a look. Thanks for your suggestion.
