### ISSUE TITLE
[15.03] Binary Install ]ejabberdctl module* missing description and not working

### ISSUE THREAD

**Issue by CyrilPeponnet** [processone/ejabberd#487]
Using latest ejabberd 15.03 Binary install under linux 64bits (centos7)

`ejabberdctl` give me:

```
   mnesia_change_nodename oldnodename newnodename oldbackup newbackup   Change the erlang node name in a backup file
   module_check module
   module_install module
   module_uninstall module
   module_upgrade module
   modules_available
   modules_installed
   modules_update_specs
   outgoing_s2s_number                                                  Number of outgoing s2s connections on the node
```

and I tested every cmds, the output is empty:

```
[root@central-server bin]# ./ejabberdctl modules_installed
[root@central-server bin]# ./ejabberdctl modules_available
[root@central-server bin]# ./ejabberdctl module_install mod_admin_extra
Error: not_available
[root@central-server bin]#
```

**Comment by CyrilPeponnet** [comment]
Oh `ejabberdctl modules-update-specs` need to be done before other commands... This is not ovbisous

**Comment by mremond** [comment]
Yes we should probably add a message to tell the user about it if we do not have any data.

**Comment by CyrilPeponnet** [comment]
Also once built, you have to be aware that the result is located under `~/.ejabberd-modules/` and that you have to deploy the module to `lib/ejabberd-xx.xx/ebin/` in order to make it work.

**Comment by mremond** [comment]
This is a bug. It should work from the place where it is installed. We will have a look.

**Comment by sezuan** [comment]
Probably fixed by https://github.com/processone/ejabberd/commit/8b23727cc6db571b9d1dcc6119e39a602fe37279

**Comment by CyrilPeponnet** [comment]
Waiting for 15.04 now :)

**Comment by CyrilPeponnet** [comment]
Just one caveat with this method, ejabberd need to be up and running in order to install modules. But in order to activate modules, I need to set the proper configuration in the yml. BUT if I do that before installing the modules, ejabberd wont start. 

So if you try to deploy an automatic ejabberd configuration through puppet for example, this could be an issue.

**Comment by mremond** [comment]
I think @cromain plan is to make it possible to install and start module with config snippet in a next release.

**Comment by cromain** [comment]
The aim is to install module (so ejabberd is running) that comes with a default configuration to let it running.
then you can change the module configuration (ejabberd.yml remains untouched and ejabberd known how to automatically include module configuration snippets) and tell ejabberd to restart the module with it's new configuration.

**Comment by cromain** [comment]
to cover the few remaining points:
1/ need to think if adding automation to call modules_update_specs when trying a module which is not referenced on local store is good idea or not.
2/ README now includes procedure to build modules yourself without ejabberd running
3/ auto include of configuration snippets should be ready for 15.05

**Comment by cromain** [comment]
i created EJAB-1741 to follow include of config snippet improvement.
other items are covered, and i think we should keep explicit call of modules_update_specs
so i suggest to close this issue as description is not accurate, and module functions are working correctly.
feel free to open a dedicated issue if explicit call of modules_update_specs is not clear for everyone.
