### ISSUE TITLE
BOSH HTTPS port

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#490]
In the XEP-0124: https://xmpp.org/extensions/xep-0124.html

There is:
"5280 tcp port"

"All communications between a client and a BOSH service SHOULD occur over encrypted HTTP connections."

It is possible to change 5281 to 5280?

**Comment by beherit** [comment]
You can change port on Your own.

~~~~
listen:
  - ip: "::"
    port: 5280
    module: ejabberd_http
    access: local
    http_bind: true
    http_poll: true
    tls: true
    protocol_options: 'TLS_OPTIONS'
    ciphers: 'TLS_CIPHERS'
    certfile: 'CERT_LOCATION'
~~~~
