### ISSUE TITLE
tls in ejabberd_http and protocol_options

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#492]
Could You add an option protocol_options for ejabberd_http? When we use SSL the connection is leaky e.g. SSL3 is still enabled and there is "POODLE" vulnerability. Now I using TLS Interposer to fix that, but it will be nice to see the protocol_options in ssl for ejabberd_http just like it is for  ejabberd_c2s.

**Comment by cromain** [comment]
indeed, we're working on it

**Comment by alexeyshch** [comment]
Should be fixed in master now.
