### ISSUE TITLE
ODBC MySql Not Work for some Module

### ISSUE THREAD

**Issue by ariqbanihardi** [processone/ejabberd#496]
Hi, Can anyone help me. I'm using External Database for my ejabberd 14.12 and I have been config my ejabberd.yml. I can create users and ejabberd store it to the mySql database normally. but I can see the data for shared roster group and the muc after I created it in client. this is my configuration 

###
###
###

loglevel: 4

log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1

log_rate_limit: 100

hosts:
  - "perangkatlunak.org"

listen: 
  - 
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    starttls: true
    certfile: "/opt/ejabberd-14.12/conf/certificate/perangkatlunak.pem"
  - 
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 131072
    shaper: s2s_shaper
  - 
    port: 5280
    module: ejabberd_http
    web_admin: true
    http_poll: false
    http_bind: true
    tls: true
    certfile: "/opt/ejabberd-14.12/conf/certificate/perangkatlunak.pem"
    captcha: false

auth_method: odbc

##
##
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "username"
odbc_password: "password"

odbc_pool_size: 10

###   TRAFFIC SHAPERS

shaper:
  normal: 1000
  fast: 50000

max_fsm_queue: 1000

###.   ====================
###'   ACCESS CONTROL LISTS
acl:
  admin:
    user:
      - "admin": "perangkatlunak.org"
      
  local: 
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"

###   ACCESS RULES
access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions: 
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages: 
    admin: 5000
    all: 100
  ## This rule allows access only for local users:
  local: 
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s: 
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper: 
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper: 
    all: fast
  ## Only admins can send announcement messages:
  announce: 
    admin: allow
  ## Only admins can use the configuration interface:
  configure: 
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin: 
    admin: allow
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create: 
    local: allow
  ## All users are allowed to use the MUC service:
  muc: 
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode: 
    local: allow
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register: 
    all: allow
  ## Only allow to register from localhost
  trusted_network: 
    loopback: allow
  ## Do not establish S2S connections with bad servers
  ## s2s:
  ##   bad_servers: deny
  ##   all: allow

##
##
language: "en"

modules: 
  mod_announce: 
    db_type: odbc
    access: local
  mod_blocking: 
    db_type: odbc
  mod_caps: 
    db_type: odbc
  mod_last: 
    db_type: odbc
  mod_muc: 
    db_type: odbc
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_offline: 
    db_type: odbc
  mod_privacy: 
    db_type: odbc
  mod_private: 
    db_type: odbc
  mod_pubsub_odbc: 
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: true
    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
      - "pep"
  mod_roster: 
    versioning: true
    store_current_id: true
    db_type: odbc
  mod_shared_roster: [{db_type: odbc}]
  mod_vcard: 
    db_type: odbc
  mod_vcard_xupdate:
    db_type: odbc
  mod_adhoc: []
  mod_configure: []
  mod_disco: []
  mod_ping: []
  mod_proxy65: []
  mod_register: 
    welcome_message: 
      subject: "Welcome!"
      body: "Hi.Welcome SCA XMPP server."
  mod_stats: []
  mod_time: []
  mod_version: []

thank you very much

**Comment by seraphjiang** [comment]
i'm trying to connect ejabberd to postgresql, however i didn't get any luck. i'm able to create db by schema. but i can't register user and there is no any data in database at all.

it seem from your try, mysql support is better than postgresql, i'll try. thanks for share the ejabberd.yml

**Comment by ariqbanihardi** [comment]
I have not found the solution..in my system, mysql only accomodate the users data. I want to save all of data like muc, offline message, etc to mysql database too, but until now I don't know why..

**Comment by zinid** [comment]
ejabberd is working with MUC and Offline messages. I see no issue, I close the ticket.
