### ISSUE TITLE
join_cluster fails to run for a non-root user

### ISSUE THREAD

**Issue by 7adietri** [processone/ejabberd#497]
It seems that the `tools/joincluster` script expects to be run by a root user. At least I ran into problems with these lines:
https://github.com/processone/ejabberd/blob/8cf4ef0aac43bd0bec02efd9b17676f52d6955d9/tools/joincluster#L97-L98

My server is built with `--enable-user` and that user has no permission to remove or create `$SPOOL_DIR`. It might be sufficient to delete everything in that directory and check for write permission.

**Comment by cromain** [comment]
thanks reporting this, recent changes in ejabberdctl make this check useless and broken. i'll fix this.

**Comment by cromain** [comment]
cluster scripts have been improved in 63926ef.
if you directly call joincluster, you must do it with same unix user running ejabberd.
if you call it through 'ejabberdctl join_cluster' command, then it should already be running with the right user.
usually, you should have an 'ejabberd' user which runs ejabberd server, and that user must have write permission on directory pointed by $SPOOL_DIR

**Comment by 7adietri** [comment]
The problem is not `$SPOOL_DIR`, but its parent. As the ejabberd user, I cannot create or delete directories in `/var/lib` (or wherever you point `--prefix`).

**Comment by cromain** [comment]
got it, so it would be safer joincluster not removing SPOOL_SIR if already exists.
let replace those two lines

**Comment by 7adietri** [comment]
I didn't test this on my live server, only with a copy of the directories, but yes, this clears out the content of `$SPOOL_DIR` when being the ejabberd user.
