### ISSUE TITLE
join_cluster needs more exported global variables

### ISSUE THREAD

**Issue by 7adietri** [processone/ejabberd#498]
I had to export more global variables in `ejabberdctl` for the `join_cluster` command to work:
https://github.com/processone/ejabberd/blob/8f46ca48c122d43de8fadb2d6e5ed88d14899409/ejabberdctl.template#L157

In its current state, I am getting "unbound variable" errors. Adding `ERLANG_NODE`, `KERNEL_OPTS` and `SPOOL_DIR` did the trick for me.

**Comment by cromain** [comment]
there is a glitch in the packaging. joincluster and leavecluster should be in bin directory instead of lib/ejabberd-15.03/priv/bin to make it able to eval variables correctly. i'll fix this.

**Comment by cromain** [comment]
script moved to bin directory on installer, and improved to find ejabberdctl on standard installation.
fixed in 63926ef

**Comment by 7adietri** [comment]
This is still necessary for me in 15.10 (I compile from source with `--prefix=/opt/ejabberd`). In addition, I now have to export `ERL` as well.
