### ISSUE TITLE
ejabberd_socket: Timeout on tls:send and auto disconnecting users when logged in

### ISSUE THREAD

**Issue by mckaygerhard** [processone/ejabberd#50]
when users login into  recently updated 2.1.11 disconect in seconds after login, and into log on server i see Timeout on tls:send 

behavior problem:
* **The problem occurs when there are more than 50 users online at the same time**

some notes:
* **no network firewall,** 
* only one redirection from public ip to internal ip, valid domain certified etc, 
* dedicated server, unmilitarized network, 
* **no clients firewalls, clients used psi+, spark or pidgin.**
* the networking are 5222 redirected port of public ip to internally ip
* jabberd used 2.1.10 erlang 15.b and then later try **jabberd 2.1.11, erlang 15.b.1**
* enabled smp and lot of resources into server (delll t110-II 4cores, 4Gram, raid0)

sorry for my english, i have reported also in process one, https://support.process-one.net/browse/EJAB-1617, **due there's no info related and documentation are very limited on networking**

LOG EJABBERD:
<pre><code>
=INFO REPORT==== 2013-02-18 14:15:14 ===
I(<0.404.0>:ejabberd_listener:281) : (#Port<0.5481>) Accepted connection {{200,62,27,27},9580} -> {{37,10,254,10},5222}

=INFO REPORT==== 2013-02-18 14:15:14 ===
I(<0.2107.0>:ejabberd_c2s:767) : ({socket_state,tls,{tlssock,#Port<0.5481>,#Port<0.5483>},<0.2106.0>}) Accepted authentication for 20563522 by ejabberd_auth_odbc

=INFO REPORT==== 2013-02-18 14:15:14 ===
I(<0.2107.0>:ejabberd_c2s:938) : ({socket_state,tls,{tlssock,#Port<0.5481>,#Port<0.5483>},<0.2106.0>}) Opened session for 20563522@syscatalogo/Spark 2.6.3

=INFO REPORT==== 2013-02-18 14:15:22 ===
I(<0.2100.0>:ejabberd_socket:175) : Timeout on tls:send

=INFO REPORT==== 2013-02-18 14:15:22 ===
I(<0.2100.0>:ejabberd_c2s:1502) : ({socket_state,tls,{tlssock,#Port<0.5474>,#Port<0.5476>},<0.2099.0>}) Close session for guacara@syscatalogo/Spark 2.6.3

=INFO REPORT==== 2013-02-18 14:15:30 ===
I(<0.404.0>:ejabberd_listener:281) : (#Port<0.5488>) Accepted connection {{186,93,139,212},2305} -> {{37,10,254,10},5222}

=INFO REPORT==== 2013-02-18 14:15:47 ===
I(<0.641.0>:ejabberd_socket:175) : Timeout on tls:send

=INFO REPORT==== 2013-02-18 14:15:47 ===
I(<0.641.0>:ejabberd_c2s:1502) : ({socket_state,tls,{tlssock,#Port<0.3092>,#Port<0.3094>},<0.640.0>}) Close session for mpastora@syscatalogo/Spark 2.6.3
</code></pre>

CONFIG FILE:

<pre><code>
{acl, admin, {user, "admin", "syscatalogo"}}.
{hosts, ["syscatalogo"]}.
{loglevel, 4}.

{watchdog_admins, ["piccorodaemon@syscatalogo"]}.

{listen,
 [
  {5222, ejabberd_c2s, [
			{access, c2s},
			{shaper, c2s_shaper},
			{max_stanza_size, 32768000},
			zlib,
			starttls, {certfile, "/etc/ssl/certs/syscatalogo.pem"}
		       ]},
  {5269, ejabberd_s2s_in, [
  			   {shaper, s2s_shaper},
  			   {max_stanza_size, 32768000}
  			  ]},
  {5280, ejabberd_http, [
			 {request_handlers,
			  [
			   {["catalogo", "archivos"], mod_http_fileserver}
			  ]},
			 %%captcha,
			 http_bind,
			 http_poll,
			 web_admin,
			 register,
			 tls, {certfile, "/etc/ssl/certs/syscatalogo.pem"}
			]}

 ]}.
{s2s_use_starttls, true}.
{s2s_certfile, "/etc/ssl/certs/syscatalogo.pem"}.

{s2s_default_policy, deny}.
{{s2s_host,"syscatalogo"},allow}.

{auth_method, odbc}.
{odbc_server, "DSN=PSQLejabberdb;UID=ejabberdb;PWD=ejabberdb"}.
{odbc_pool_size, 6}.
{odbc_keepalive_interval, 3600}.

{shaper, normal, {maxrate, 50000}}.
{shaper, fast, {maxrate, 50000}}.

{acl, admin, {user, "admin", "syscatalogo"}}.

{acl, local, {user_regexp, ""}}.
{access, max_user_sessions, [{2, all}]}.
{access, max_user_sessions, [{4, admine@syscatalogo}]}.
{access, max_user_offline_messages, [{10, admin}, {5, all}]}. 
{access, c2s, [{deny, blocked},
	       {allow, all}]}.
{access, c2s_shaper, [{none, admin},
		      {normal, all}]}.
{access, s2s_shaper, [{fast, all}]}.
{access, announce, [{deny, all},{allow, admin}]}.
{access, configure, [{allow, admin}]}.
{access, muc_admin, [{allow, admin}]}.
{access, muc, [{allow, admin},{allow, gerencia}]}.
{access, register, [{deny, all}]}.

{registration_timeout, 6000}.

{access, pubsub_createnode, [{deny, all}]}.
{access, pubsub_createnode, [{allow, admin}]}.

{language, "es"}.

{modules,
 [
  {mod_adhoc,    []},
  {mod_announce, [{access, announce}]}, % requires mod_adhoc
  {mod_caps,     []},
  {mod_configure,[]}, % requires mod_adhoc
  {mod_admin_extra, []},
  {mod_disco,    []},
  {mod_echo,   [{host, "echo.syscatalogo"}]},
  {mod_http_bind,    []},
  {mod_http_fileserver, [
                         {docroot, "/var/www/catalogo/archivos/"}, 
                         {accesslog, "/var/log/ejabberd/access.log"},
                         {custom_headers, [{"X-Powered-By", "VNXDE Ejabberd"},{"X-Fry", "www.venenux.org"}]},
                         {content_types, [{".pdf","application/pdf"},
                                          {".odt","application/vnd.oasis.opendocument.text"},
                                          {".ods","application/vnd.oasis.opendocument.spreadsheet"},
                                          {".ogv","video/ogv"},
                                          {".mpeg","video/mpeg"},
                                          {".html","text/html"},
                                          {".kate","text/plain"},
                                          {".sql","text/plain"},
                                          {".7z","application/x-7z-compresed"},
                                          {".gz","application/x-gtar"},
                                          {".tar","application/x-tar"}
                         ]}
                        ]},
  {mod_last_odbc,     []},
  {mod_muc,      [
		  {access, muc_admin},
		  {access_create, muc_admin},
		  {access_persistent, muc_admin},
		  {access_admin, muc_admin},
		  {max_users, 10},
		  {max_user_conferences, 4}
		 ]},
  {mod_muc_log,[]},
  {mod_offline,  [{access_max_user_messages, max_user_offline_messages}]},
  {mod_privacy_odbc,  []},
  {mod_private_odbc,  []},
  {mod_proxy65,  [
		  {access, all},
		  {shaper, c2s_shaper}
		 ]},
  {mod_register, [
		  {welcome_message, {"Welcome!",
				     "Para informacion vistie http://syscatalogo "}},
		  {registration_watchers, ["admin@syscatalogo"]},
		  {access, register}
		 ]},
  {mod_register_web, []}, %% must enabled into http 5280 port http access
  {mod_roster_odbc,   []},
  {mod_service_log,[]},
  {mod_shared_roster,[]},
  {mod_stats,    []},
  {mod_time,     []},
  {mod_vcard,    [{search, true}, {matches, infinity}, {allow_return_all, true}, {search_all_host, true}]},
  {mod_vcard_xupdate, []},
  {mod_version,  []}
 ]}.

%%% Local Variables:
%%% mode: erlang
%%% End:
%%% vim: set filetype=erlang tabstop=8:
</code></pre>

**Comment by chorsley** [comment]
I'm running into a similar issue with 2.1.10, though with very few users and a high message throughput. Did you ever find a resolution to this?

**Comment by mckaygerhard** [comment]
processone lie, its not fixed! i have same problem with 2.1.13 but minimized

**Comment by mremond** [comment]
@mckaygerhard :-1: Please, be kind and respectful. We will be happy to consider your patch if you wish to contribute ;) And for the record 2.1.13 is 2 years old, let's all move to 15.03+

**Comment by mckaygerhard** [comment]
well, its not me, its the ticket in the processone, was change to "fixed" and the user @chorsley comfirms not fixed! and the bug has many days now, my rpoduction system does not have the requeriments for the lasted release!

**Comment by chorsley** [comment]
@mremond I'd like to help where I can, thought unfortunately I'm not literate in erlang. I'm stuck with the packages available on Ubuntu 12.04 for now, though I'd love to upgrade if I could.

If there is any advice you could give about troubleshooting, or more detailed logs I could provide, I'd greatly appreciate that.

**Comment by zinid** [comment]
@mckaygerhard chill out dude. 2.1.x is not supported.
I can only suggest increasing sending timeout here: https://github.com/processone/ejabberd/blob/2.1.x/src/ejabberd_listener.erl#L44 and recompile the file.

**Comment by mckaygerhard** [comment]
i 'll take the suggestion.. i'll make a rebuild of the debian package and report feedback here..

**Comment by beherit** [comment]
@mckaygerhard check out jabber.at repository for Debian and Ubuntu - they have ejabberd 15.03.

**Comment by mckaygerhard** [comment]
they not have ejabberd for lenny.. i'll backported ejabberd to squeeze that now its LTS, du that repository have ejabberd for squeeze?  NOT

https://www.jabber.at/en/apt-repository here said that its not supporte, and i have proper support from debian, a good support

**Comment by cromain** [comment]
We have found a case which seems to happen only under rare circumstances. This *only* seems to happen when epoll(7) is used, i.e. when "+K true" is specified on Linux.  "+K false" makes the issue go away. From the very rare cases we could get it seems disabling epoll is enough. We're investigating for a permanent fix for 15.05 with epoll enabled.

**Comment by mremond** [comment]
More stuff were commited, even if it still not reproducible.
