### ISSUE TITLE
mod_multicast strange error

### ISSUE THREAD

**Issue by shyaken** [processone/ejabberd#506]
My multicast service has just stop with a strange error, I can't find how to fix it :'( please help me to point this bug out. 
the error message: gen_server 'ejabberd_mod_multicast_unityappstudio.com' terminated with reason: bad record jid in mod_multicast:'-group_dests/1-fun-0-'/2 line 519
![image](https://cloud.githubusercontent.com/assets/158163/6962344/fda752d6-d95d-11e4-87a8-6ab15786f9b7.png)

**Comment by mremond** [comment]
Mod_multicast is a contributed module, not a main ejabberd one, right ?

**Comment by shyaken** [comment]
ah yeah sorry I posted in wrong section :( could you please delete this issue or move it?

**Comment by mremond** [comment]
I do not think Github allow delete or move of tickets, sorry.

**Comment by shyaken** [comment]
so please close this :( I were unconcentrated when post this. Really sorry.

**Comment by mremond** [comment]
Frankly, no problem. If you do not have time, I will try copy paste later.

**Comment by mremond** [comment]
Moved discussion to processone/ejabberd-contrib#91
