### ISSUE TITLE
Outgoing messages are not delivered, until a message from the target is received

### ISSUE THREAD

**Issue by masscream** [processone/ejabberd#511]
Hello,

I have a following issue with my fresh ejabberd server. I will show an example.
Node A = account on my ejabberd server
Node B = external jabber account on another server
I authenticate to Node A, as well as to Node B on another computer and try to send a message. If I send the message from node A to B first, it's never delivered and lost without error message. And I can send even more of them, if they are first from A to B, they won't come. When I send the message from B to A, it is delivered immediately and the situation looks like this helped then to Node A to send next messages to Node B which are delivered successfully. If I restart the Node A connection, the problem appears again, so it seems I can't use my ejabberd server for outgoing messages which are sent first in session. Does anybody know please, what could be the cause? Tried to search online but with no relevant results. Thanks

Tomas

**Comment by weiss** [comment]
Please set the `loglevel` to at least `4` and then grep the `ejabberd.log` file for the host name of server B.

What ejabberd version are you using?

**Comment by masscream** [comment]
It is ejabberd 2.1.11; I think I found something in the log file. It describes the procedure - trying to send from A to B at first, then sending from B to A and then the connection is established.

=INFO REPORT==== 2015-04-04 15:01:41 ===
I(<0.462.0>:ejabberd_listener:281) : (#Port<0.4360>) Accepted connection {{MyTestingLocationIP},49284} -> {{192,168,2,30},5222}

=INFO REPORT==== 2015-04-04 15:01:44 ===
I(<0.1492.0>:ejabberd_c2s:767) : ({socket_state,tls,{tlssock,#Port<0.4360>,#Port<0.4362>},<0.1491.0>}) Accepted authentication for tomas by ejabberd_auth_internal

=INFO REPORT==== 2015-04-04 15:01:45 ===
I(<0.1492.0>:ejabberd_c2s:938) : ({socket_state,tls,{tlssock,#Port<0.4360>,#Port<0.4362>},<0.1491.0>}) Opened session for tomas@a*****.net/***********************

=INFO REPORT==== 2015-04-04 15:01:46 ===
I(<0.1492.0>:ejabberd_s2s:404) : New s2s connection started <0.1493.0>

=INFO REPORT==== 2015-04-04 15:01:46 ===
I(<0.1493.0>:ejabberd_s2s_out:1203) : Trying to open s2s connection: a*****.net -> proxy.eu.jabber.org with TLS=true

=INFO REPORT==== 2015-04-04 15:01:48 ===
I(<0.1493.0>:ejabberd_s2s_out:235) : s2s connection: a*****.net -> proxy.eu.jabber.org (remote server not found)

=INFO REPORT==== 2015-04-04 15:02:03 ===
I(<0.1493.0>:ejabberd_s2s_out:887) : Reconnect delay expired: Will now retry to connect to proxy.eu.jabber.org when needed.

=INFO REPORT==== 2015-04-04 15:03:54 ===
I(<0.463.0>:ejabberd_listener:281) : (#Port<0.4372>) Accepted connection {{NodeB-IP1},46780} -> {{192,168,2,30},5269}

=INFO REPORT==== 2015-04-04 15:03:54 ===
I(<0.463.0>:ejabberd_listener:281) : (#Port<0.4383>) Accepted connection {{NodeB-IP2},51319} -> {{192,168,2,30},5269}

=INFO REPORT==== 2015-04-04 15:03:54 ===
I(<0.1504.0>:ejabberd_s2s_out:365) : Connection established: a*****.net -> jabber.cz with TLS=true

**Comment by masscream** [comment]
The first log was generated by establishing connections of these 2 accounts in Pidgin, now there is a log from the same situation, but I use for Node A Java ojsxc client (runing on same server) to connect to node B (pidgin). Behavior is exactly the same. 

=INFO REPORT==== 2015-04-04 15:27:30 ===
I(<0.464.0>:ejabberd_listener:281) : (#Port<0.4453>) Accepted connection {{127,0,0,1},60389} -> {{127,0,0,1},5280}

=INFO REPORT==== 2015-04-04 15:27:30 ===
I(<0.1554.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.4453>}

=INFO REPORT==== 2015-04-04 15:27:31 ===
I(<0.1556.0>:ejabberd_c2s:785) : ({socket_state,ejabberd_http_bind,{http_bind,<0.1555.0>,{{MylocationIP},60389}},ejabberd_http_bind}) Accepted authentication for tomas by []

=INFO REPORT==== 2015-04-04 15:27:32 ===
I(<0.1556.0>:ejabberd_c2s:938) : ({socket_state,ejabberd_http_bind,{http_bind,<0.1555.0>,{{MyLocationIP},60389}},ejabberd_http_bind}) Opened session for tomas@a*****.net/Tomas

=INFO REPORT==== 2015-04-04 15:27:46 ===
I(<0.464.0>:ejabberd_listener:281) : (#Port<0.4460>) Accepted connection {{127,0,0,1},60392} -> {{127,0,0,1},5280}

=INFO REPORT==== 2015-04-04 15:27:46 ===
I(<0.1557.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.4460>}

=INFO REPORT==== 2015-04-04 15:27:47 ===
I(<0.464.0>:ejabberd_listener:281) : (#Port<0.4462>) Accepted connection {{127,0,0,1},60394} -> {{127,0,0,1},5280}

=INFO REPORT==== 2015-04-04 15:27:47 ===
I(<0.1558.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.4462>}

=INFO REPORT==== 2015-04-04 15:27:47 ===
I(<0.463.0>:ejabberd_listener:281) : (#Port<0.4464>) Accepted connection {{NodeB-IP},49621} -> {{192,168,2,30},5269}

=INFO REPORT==== 2015-04-04 15:28:52 ===
I(<0.464.0>:ejabberd_listener:281) : (#Port<0.4487>) Accepted connection {{127,0,0,1},60397} -> {{127,0,0,1},5280}

=INFO REPORT==== 2015-04-04 15:28:52 ===
I(<0.1577.0>:ejabberd_http:146) : started: {gen_tcp,#Port<0.4487>}

**Comment by weiss** [comment]
In order to track down the issue, I'd test whether it works as expected when you set `{s2s_use_starttls, false}.`  My guess is that it does, and that would indicate a certificate issue combined with a [bug in old ejabberd versions][1].

[1]: https://github.com/processone/ejabberd/pull/174

**Comment by masscream** [comment]
For some reason, after 4 days of no work on it, the issue is not occurring. I'm glad that it works, but hate when I don't know what was causing it for the future possible impact... :-/ Anyway I can not continue testing when it's not occurring.

**Comment by mremond** [comment]
Thanks, for the update. I think anyway Holger was right about s2s starttls. It is possible that setting changed on the other end as well.
And also, do not forget to upgrade to a new ejabberd version, as ejabberd 2.1.11 is very very old.
