### ISSUE TITLE
[websockets] crashes when used with jappix

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#515]
When using Jappix 1.1.3 and the new ejabberd websocket implementation, Jappix does seem to connect (so the roster shows up, and I can eventually even chat), but I do get messages that I've been disconnected all the time. Whenever Jappix reconnects, I get these messages in ejabberds error.log (timestamps stripped for readability):

```
<0.20886.0> gen_fsm <0.20886.0> in state loop terminated with reason: bad argument in call to erlang:'++'(<<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_0\"><services xmlns=\"urn:xmpp:ex...">>, <<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_1\"><services xmlns=\"http://jabb...">>) in ejabberd_http_ws:handle_info/3 line 200
<0.20886.0> CRASH REPORT Process <0.20886.0> with 1 neighbours exited with reason: bad argument in call to erlang:'++'(<<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_0\"><services xmlns=\"urn:xmpp:ex...">>, <<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_1\"><services xmlns=\"http://jabb...">>) in ejabberd_http_ws:handle_info/3 line 200 in gen_fsm:terminate/7 line 611
<0.661.0> Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.20885.0> exit with reason bad argument in call to erlang:'++'(<<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_0\"><services xmlns=\"urn:xmpp:ex...">>, <<"<iq xmlns=\"jabber:client\" to=\"jabber.at\" type=\"get\" id=\"JSJaCID_1\"><services xmlns=\"http://jabb...">>) in ejabberd_http_ws:handle_info/3 line 200 in context child_terminated
```

... I see the same log messages also for other log-messages (e.g. presence stanzas).

**Comment by mathiasertl** [comment]
(I should add that this is not proxied via a an Apache proxy, as in the second websockets issue earlier today)

**Comment by prefiks** [comment]
Hello Mathias,

I did just pushed commit that i think should fix this problem. I am not able to reproduce this bug, so if you would have a moment to test it and verify that it indeed fixes it, i would be grateful.

**Comment by mathiasertl** [comment]
Hi prefiks,

Thanks for the reply! Just so I don't get things mixed up, are you referring to 81b0643036b7a9ab62b247d8110b42f5b303606e ?

**Comment by mathiasertl** [comment]
And out of curiousity: what is an "old style" websocket connection? As opposed to a "new style"?

**Comment by prefiks** [comment]
Yes, this is this commit.

New style = connection using protocol specified in RFC7395 (for example <open/>, <close/> replace <stream:stream> used in native protocol), old style is just using native protocol wrapped in websocket frames.

**Comment by mathiasertl** [comment]
We just deployed the change and it now everything seems to work!
