### ISSUE TITLE
join_cluster requires interaction

### ISSUE THREAD

**Issue by highlyunavailable** [processone/ejabberd#516]
The `ejabberdctl join_cluster` command requires interaction to pass in a "yes" to the warning, which means it's very hard to use with an automated deployment script.

Can we please have a variable like `$EJABBERD_BYPASS_WARNINGS` for `ejabberdctl debug` to disable the interaction and just exit with a non-zero exit code if the ping check fails? Also, ICMP Echo Request is blocked between my jabber nodes anyway, so a "ping" test is not a good one - a check using `net_adm:ping` would probably be better since it also tests jabber cookie configuration as far as I can tell.

This is the hacked together module I use:

https://gist.github.com/highlyunavailable/7cd9d716d1f8b2a273fe

I realize there's a bunch of stuff that probably is bad form and doesn't work right, but it was something I smashed together with no knowledge of Erlang and lots of Google.

**Comment by cromain** [comment]
we won't touch ejabberdctl interface, but you can now dirrectly call cluster script this way:
NO_WARNINGS=true joincluster ejabberd@nodename
