### ISSUE TITLE
ejabberd_xmlrpc

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#519]
Hi,

I'm running ejabberd 15.03 (with ejabberd_xmlrpc enabled, running on port 4560) and I'm having issues with calling a simple XMLRPC command:

```java
import java.net.URL;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;

public class EjabberdAPIProxy {
	public boolean createAccount(String user, String host, String password){
		try {
		    XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
		    config.setServerURL(new URL("http://127.0.0.1:4560/"));
		    XmlRpcClient client = new XmlRpcClient();
		    client.setConfig(config);

		    /* Command string */
		    String command = "create_account";

		    /* Parameters as struct */
		    Map<String, Object> struct = new LinkedHashMap<String, Object>();
		    struct.put("user", "test");
		    struct.put("host", "test.com");
		    struct.put("password", "test");

		    List<Object> params = new ArrayList<Object>();
		    params.add(struct);
		    
		    Integer result = (Integer) client.execute(command, params);
		    System.out.println(result);
		    return true;
		} catch (Exception e) {
			System.out.println(e);
			return false;
		}
	}
}
```

Error response:

```erlang
Unknown call: {call,create_account,
                    [{struct,[{user,<<"test">>},
                              {host,<<"test.com">>},
                              {password,<<"test">>}]}]}
```

I've tried the same in Python

```python
from __future__ import unicode_literals
import xmlrpclib

class EjabberdAPIProxy(object):
    def create_account(self, username, server, password):
        client = xmlrpclib.ServerProxy("http://127.0.0.1:4560")

        try:
            response = client.create_account({
                'user': username,
                'server': server,
                'password': password
            })
            return response.get('res') == 0
        except:
            return False

if __name__ == '__main__':
    proxy = EjabberdAPIProxy()
    print proxy.create_account('test', 'test.com', 'test')
```

Also here, I get an error response:

```erlang
Unknown call: {call,create_account,
                    [{struct,[{password,<<"test">>},
                              {user,<<"test">>},
                              {server,<<"test.com">>}]}]}

```

What am I doing wrong here?

**Comment by dirkmoors** [comment]
I found out that I need to create the account differently....

```python
from __future__ import unicode_literals
import xmlrpclib

class EjabberdAPIProxy(object):
    def create_account(self, username, host, password):
        client = xmlrpclib.ServerProxy("http://127.0.0.1:4560")

        try:
            response = client.register({
                'user': username,
                'host': host,
                'password': password
            })
            return response.get('res') == 0
        except:
            return False

if __name__ == '__main__':
    proxy = EjabberdAPIProxy()
    print proxy.create_account('test', 'test.com', 'test')
```

This seems to be the correct call.

Can anyone point me to a document that contains all the valid API calls?

**Comment by dirkmoors** [comment]
Essentially, I would like to user mod_xmlrpc (https://www.ejabberd.im/ejabberd+integration+with+XMLRPC+API)

I though that the builtin xmlrpc server...

```yaml
    port: 4560
    module: ejabberd_xmlrpc
```

...would be mod_xmlrpc, but it appears I'm mistaken? 

Are there any tutorials/guides/testimonials on how to install mod_xmlrpc on Ejabberd 15.X ?

**Comment by mremond** [comment]
I think this document is obsolete.
We unified the commands from ejabberdctl command line, xml-rpc, etc and now all commands have the same name.

As shown in documentation the name of the command to create a user is 
```
register user host password
```

Please read this page for details:
http://docs.ejabberd.im/admin/guide/managing/

**Comment by mremond** [comment]
I put a warning at top of the page and created a follow up task to update task on #520

**Comment by dirkmoors** [comment]
Does this mean that all MUC related commands are no longer available now?
Or do I have to install something like 'mod_muc_admin' first?

**Comment by mremond** [comment]
To get the list of available commands, you can use ejabberdctl help.

Then you can indeed install extra command provider if you need some like mod_admin_extra and mod_muc_admin.

Note that both modules have been added to ejabberd main repository and will be part of the defaut installation starting from version 15.04.

**Comment by dirkmoors** [comment]
That sounds good! When is version 15.04 planned to be released? (Is there a public roadmap I can keep an eye on?)

**Comment by mremond** [comment]
ejabberd community versioning scheme is based on year and month. It means it will be release in april 2015. Roadmap is tracked on Github. For example: https://github.com/processone/ejabberd/issues?utf8=✓&q=milestone%3A%22ejabberd+15.04%22+

**Comment by dirkmoors** [comment]
Ok thanks a lot! I'll keep an eye on that!
