### ISSUE TITLE
Create group on ejabberd server((xmpp server )

### ISSUE THREAD

**Issue by ranjeetlbsimds07** [processone/ejabberd#526]
Hello All, 
I have queries. How to create group on ejabberd sever(xmpp server ) and how to add member in the group in Android.

Please help me.

Thanks in advance.

**Comment by mremond** [comment]
What do you mean by group ? chat room ?
Please, note that this is a pure usage question not related to ejabberd dev and would fit better on our forum :) https://www.ejabberd.im/forum

Thanks for helping us keep the development roadmap clean :+1:

**Comment by ranjeetlbsimds07** [comment]
yes, I talking about chat room.

**Comment by mremond** [comment]
Chatroom management is done though XMPP protocol as defined in XEP-0045 Multi User Chat. Here are the specifications: http://xmpp.org/extensions/xep-0045.html
