### ISSUE TITLE
mod_shared_roster_ldap problem

### ISSUE THREAD

**Issue by dbr1337** [processone/ejabberd#531]
Hello Community,
i installed ejabberd 15.03 on debian 7. I've connected my ldap-server with ssl but cannot configurate mod_shared_roster_ldap plugin sucessfully. This is how my ldap is configured:

USERS:
cn: Users
description: Default container for upgraded user accounts
distinguishedName: CN=Users,DC=int,DC=censored,DC=com
objectCategory: CN=Container,CN=Schema,CN=Configuration,DC=int,DC=censored,DC=com

GROUPS:
ou: Groups
description: Organizational Structure
distinguishedName: OU=Groups,DC=int,DC=censored,dc=com
objectCategory: CN=Organizational-Unit,CN=Schema,CN=Configuration,DC=int,DC=censored,DC=com

Group structure: http://www11.pic-upload.de/15.04.15/fnp8uc19ykw.png

How i can import the Groups with all Users?
I tried many configurations, but no one will work.

I hope anyone can help me,
Greetings

**Comment by btv** [comment]
I also seem to be having problems with mod_shared_roster_ldap. I have a working config from 2.1.13, but it doesn't seem to be working.

**Comment by ailin-nemui** [comment]
the mod_shared_roster_ldap is not really useful, check https://support.process-one.net/browse/EJAB-1480 if you're lucky it won't be too difficult to port it to 15.03
