### ISSUE TITLE
Ejabberd On SqlServer Database

### ISSUE THREAD

**Issue by BenJaziaSadok** [processone/ejabberd#533]
I'm Using Ejabberd 15.03 on CentOs and i want to connect it via SqlServer On WindowsServer. i installed the database from mssql2012

In ejabberd.yml i added this

> host_config:   "example.com":
>     odbc_type: odbc
>     odbc_server: "ip adress"
>     odbc_port: 1433 # the default
>     odbc_database: "ejjaberd"
>     odbc_username: "username"
>     odbc_password: "password"
I'm getting this error when starting ejabberd

/opt/ejabberd-15.03/lib/odbc-2.10.19/priv/bin/odbcserver: error while loading shared libraries: libodbc.so.1: cannot open shared object file: No such file or directory

Let me precise that direct connection using tsql works perfectly

**Comment by mremond** [comment]
There is two possible issues:
- We did not maintain the SQL server schema and queries since year, as we never had the use for it.
- In your case you are missing Erlang ODBC module. We do not package it in installer, as we do not need SQL server support.

**Comment by zinid** [comment]
I'm not sure MSSQL will work with ejabberd.
This hasn't been tested for years.

**Comment by BenJaziaSadok** [comment]
i installed erlang-odbc-R16B-03.10.el7.x86_64 but this did not fix the issue. same error

**Comment by mremond** [comment]
It seems there is still missing a reference odbc libraries on Linux. Maybe it is not installed or version number changed. As @zinid said, we did not use MSSQL in years.

**Comment by BenJaziaSadok** [comment]
what is the latest ejabberd 's version that support sqlserver that i can use. and is it adviced or not

**Comment by mremond** [comment]
No idea. That would be at least 4 years old. This is really not recommended, no.

The best approach would be that you could contribute MSSQL support on the master branch.

**Comment by BenJaziaSadok** [comment]
I think you should remove sql server support in the documentation

**Comment by mremond** [comment]
We serre hoping to have MSSQL users to help, but right, as it seems it is not very used , we will completely remove the support, fine.

**Comment by cromain** [comment]
MSSQL support is back in ejabberd since 15.09
