### ISSUE TITLE
 auth_method: odbc got error - position 2: did not find expected key

### ISSUE THREAD

**Issue by dongmai** [processone/ejabberd#537]
Hi Ejabberd team,
Currently I am facing this problem when trying to config to use MySQL. My config file as bellow (just the mysql config)

auth_method: odbc
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "database"
odbc_username: "username"
odbc_password: "password"

After do some google searches I found out that I need to have to enable odbc module by the command line: ./configure --enable-odbc (it runs OK).
But when I try to restart ejabberd I still get this error: Syntax error on line 250 at position 2: did not find expected key. Line 250 is auth_method: odbc.

Can anyone help to resolve this.
Thanks.

**Comment by zinid** [comment]
You should run
```
./configure --enable-mysql
```

**Comment by zinid** [comment]
Also, seems like you have indentation problems in your config or something.

**Comment by dongmai** [comment]
Thank for your help Zinid.
Yes, I had a syntax error. Now I got another error:

123 failed to start application 'p1_mysql': {error,
                                         {"no such file or directory",
                                          "p1_mysql.app"}}
Any idea?
Thanks.

**Comment by zinid** [comment]
Yes, see my previous comment about mysql configuration at compile time

**Comment by dongmai** [comment]
I did ./configure --enable-mysql and then make and got the error:

Dependency not available: p1_mysql-.* ({git,
                                        "git://github.com/processone/mysql"})
ERROR: compile failed while processing /root/ejabberd: rebar_abort
Makefile:90: recipe for target 'src' failed
make: *** [src] Error 1

Do you know why? Sorry, I am new to Ejabberd. It takes me about two days to config :(

**Comment by zinid** [comment]
Clean sources and repeat

**Comment by dongmai** [comment]
How can I clean sources?

**Comment by zinid** [comment]
`make distclean`

**Comment by dongmai** [comment]
Still no luck.

123 failed to start application 'p1_mysql': {error,
                                         {"no such file or directory",
                                          "p1_mysql.app"}}

**Comment by cclam0827** [comment]
./configure--enable-mysql 
./rebar get-deps
./rebar compile 
make install

**Comment by dongmai** [comment]
Work like a charm. Thank you cclam.

**Comment by ArunKumarNV** [comment]
hello,
As I started exploring about ejabberd I found there are different ways to install ejabberd.
please check this link.

[https://stackoverflow.com/questions/45476206/configuring-mysql-with-ejabberd-via-yml-configuration](url)

I am stuck with issue.
