### ISSUE TITLE
Logout user from ejabberd server in android

### ISSUE THREAD

**Issue by ranjeetlbsimds07** [processone/ejabberd#538]
Hello All,
I am working on xmpp server(ejabberd). How can logout from ejabberd server in Android. I am using code given below.
              Presence pr=new Presence(Presence.Type.unavailable);
                pr.setStanzaId(chatApp.getUsername());
                try {
                    connection.sendStanza(pr);
                } catch (SmackException.NotConnectedException e) {
                    e.printStackTrace();
                }
           connection.disconnect();

Please help me.

**Comment by mremond** [comment]
This is an ejabberd related issue.
