### ISSUE TITLE
Can not start mod_message_log

### ISSUE THREAD

**Issue by dongmai** [processone/ejabberd#539]
Hi everyone, 
I am trying to config to use the module mod_message_log, my steps as below:
1- Build mod_message_log.beam from source
2- Copy the beam file: ln -s ~/ejabberd-contrib/mod_message_log/ebinmod_message_log.beam
3- Restart ejabberd
and got this error:

Problem starting the module mod_message_log for host <<"myhost.com">> 
 options: [{filename,<<"/var/log/ejabberd/ejabberd-message.log">>}]
 error: undef
[{mod_message_log,start,
                  [<<"myhost.com">>,
                   [{filename,<<"/var/log/ejabberd/ejabberd-message.log">>}]],
                  []},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,69}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]

Can anyone help me to fix this?
Many thanks.

**Comment by mremond** [comment]
It cannot find the beam file. It seems that this line is on a correct syntax:
ln -s ~/ejabberd-contrib/mod_message_log/ebinmod_message_log.beam

**Comment by dongmai** [comment]
I've moved manually the beam file to /root/ejabberd/ebin but stil got this error. Any idea?
p/s: I installed ejarbberd from source.

**Comment by mremond** [comment]
undef means the module is not found. So either it is not properly compiled, not in right place. Why don't you use the plugin installer that is now part of ejabberd 15.03: https://blog.process-one.net/easy-installer-and-structure-for-ejabberd-contributed-modules/

**Comment by dongmai** [comment]
Thank mremond,
It helps me alot.

Just one question: What is the best way to install ejabberd on my server Ubuntu. I've done some googles searches and the most suggestion is using apt-get, but its the old version. So I have to build from source code to have the latest version.
So are there any alternative to install latest ejabberd without building from source?

Thanks.

**Comment by mremond** [comment]
You should download binary installer from ProcessOne ejabberd page: https://www.process-one.net/en/ejabberd/downloads/
