### ISSUE TITLE
ejabberdctl modules_update_specs' crash

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#541]
As reported in ejabberd chat room:

> consus> I have ejabberd 15.03 running on Gentoo linux. I want to add mod_mam to my setup via ejabberdctl but I have a problem. I put contribs to /opt/ejabberd-modules and adjusted ejabberdctl.cfg. But whenever I'm calling `ejabberdctl modules_update_specs' I see this in error.log:
```
2015-04-20 21:07:56.158 [error] <0.409.0> gen_fsm <0.409.0> in state
hello terminated with reason: no match of right hand value <<>> in
ssl_handshake:dec_hello_extensions/2 line 1737
2015-04-20 21:07:56.159 [error] <0.409.0> CRASH REPORT Process
<0.409.0> with 0 neighbours exited with reason: no match of right hand
value <<>> in ssl_handshake:dec_hello_extensions/2 line 1737 in
gen_fsm:terminate/7 line 611
2015-04-20 21:07:56.159 [error] <0.95.0> Supervisor tls_connection_sup
had child undefined started with {tls_connection,start_link,undefined}
at <0.409.0> exit with reason no match of right hand value <<>> in
ssl_handshake:dec_hello_extensions/2 line 1737 in context
child_terminated
```
> 
> Any ideas? Other queries via ejabberdctl work fine.

**Comment by cromain** [comment]
I can not reproduce this ssl issue.
How did you installed 15.03 ?

**Comment by cromain** [comment]
ext_mod uses inets. i guess there is something wrong with erlang installation on the platform that reported this. i'd check if inets and ssl are working correctly.
