### ISSUE TITLE
Resending existing MUC room subject on join should include a delay tag

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#542]
At the moment, we do not include a delay tag. However, it would be more consistent to add delay tag when sending the message subject stanza to define at which time the subject was set.

**Comment by badlop** [comment]
Right, I confirm that behaviour remains: the room sends to a new occupant the recent history messages with Delay elements, but the Subject message without Delay element. This follows the examples shown in https://xmpp.org/extensions/xep-0045.html#enter-subject

**Comment by badlop** [comment]
As ejabberd follows the XEP, and there was no more follow-up in this change proposal, I suggest to close the ticket.
