### ISSUE TITLE
Can not configure VOIP support in ejabberd

### ISSUE THREAD

**Issue by axcl** [processone/ejabberd#544]
Am trying to add voip support to ejabberd server i tried configuring SIP module but i can not find it in Service discovery . If any one know how to fix and add VOIP support to the server

**Comment by zinid** [comment]
The module is pure SIP, it has no interaction with XMPP, so you won't find it in the disco.

**Comment by axcl** [comment]
that mean it can be used to make Calls without any authentication?

**Comment by zinid** [comment]
No, authentication is done agains ejabberd database.
That means that only SIP calls between SIP clients can be established.

**Comment by axcl** [comment]
Can you please guide me how to configure my Client to use ejabberd SIP Proxy am little stuck.

**Comment by zinid** [comment]
Take a regular SIP client and configure it with ejabberd as a SIP proxy and SIP registrar.

**Comment by axcl** [comment]
Ok i will try to Code my client with SIP Protocols . And one thing more i need to customize the server to accept some extra fields at time of registration , i did it by a PHp script and adding my extra fields in table but i want to edit the mod_register and mod_register_web for that
