### ISSUE TITLE
Install ejabberd from source in another folder

### ISSUE THREAD

**Issue by santiagopoli** [processone/ejabberd#545]
I don't know if there is already a way to do this, but it would be great if there was a possibility to install ejabberd in a custom folder (with **make install**).

I want to have a single folder with logs, ebin, deps, config and the ejabberdctl binary so I can easily deploy it into my server without polluting the filesystem.

I made my own Makefile and I was able to do this, but the ejabberdctl binary looks for the ejabberd files in the default location (/lib/ejabberd for libs, /var/log/ejabberd for logs, /etc/ejabberd for config). Also, I don't want to modify the ejabberd source files directly (Makefile for example) so I can pull the source every time a new version arrives and reduce my conflicts.

This is a request rather than an issue, but a good one.

Thanks!

**Comment by weiss** [comment]
> I don't know if there is already a way to do this, but it would be great if there was a possibility to install ejabberd in a custom folder

    ./configure --prefix=/custom/folder
    make
    make install

... should do the trick.
