### ISSUE TITLE
Documentation doesn't cover 15.04's new mod_muc_admin commands

### ISSUE THREAD

**Issue by frizull** [processone/ejabberd#548]
We're having trouble setting up rooms with ejabberctl. Specifically, create_room and create_rooms_file are returning cryptic errors. Would be great to know the official way to use them so we can file bugs if need be.

Documentation: http://docs.ejabberd.im/admin/guide/managing/

**Comment by badlop** [comment]
The documentation for each command, the "official" way to call it, is embedded in the code and can be consulted in your deployment with:
> ejabberdctl help create_room

The webpage shows a list of basic commands, it doesn't attempt to be comprehensive.

Maybe you found a bug, please show your call and the result you get. For me it works:
```
$ ejabberdctl help create_room

  Command Name: create_room

  Arguments: name::binary
             service::binary
             host::binary
             
  Returns: res::rescode

  Tags:  muc_room

  Description:  Create a MUC room name@service in host

$ ejabberdctl create_room room11 conference.localhost localhost
$ 
```
