### ISSUE TITLE
A mysql pool size bug ?

### ISSUE THREAD

**Issue by yuan2006open** [processone/ejabberd#550]
Hi, My jabbed version is 15.03 with MySQL5,when  i set the odbc_pool_size > 500,such as 1000,some error issues.But set odic_pool_size =< 300 is ok. Is a Bug ? Help me.I test it on Mac os and Ubutu14, have the same errors.

 MySQL's max_connect is 10000.
mysql> show variables like '%max_connections%';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 10000 |
+-----------------+-------+
1 rows in set (0.00 sec)

System open file is 10000
bash-3.2# ulimit -n
10000

371 ##
372 ## Number of connections to open to the database for each virtual host
373 ##
374 odbc_pool_size: 300

bash-3.2# ejabberdctl live
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:true]
Eshell V6.4  (abort with ^G)
(ejabberd@localhost)1> 11:40:42.838 [info] Application lager started on node ejabberd@localhost
11:40:42.844 [info] Application sasl started on node ejabberd@localhost
11:40:42.852 [info] Application crypto started on node ejabberd@localhost
11:40:42.860 [info] Application asn1 started on node ejabberd@localhost
11:40:42.860 [info] Application public_key started on node ejabberd@localhost
11:40:42.866 [info] Application ssl started on node ejabberd@localhost
11:40:42.869 [info] Application p1_yaml started on node ejabberd@localhost
11:40:42.875 [info] Application p1_tls started on node ejabberd@localhost
11:40:42.880 [info] Application p1_xml started on node ejabberd@localhost
11:40:42.883 [info] Application p1_stringprep started on node ejabberd@localhost
11:40:42.885 [info] Application p1_zlib started on node ejabberd@localhost
11:40:42.887 [info] Application p1_cache_tab started on node ejabberd@localhost
11:40:43.009 [info] Application mnesia started on node ejabberd@localhost
11:40:43.577 [info] Application p1_mysql started on node ejabberd@localhost
11:40:44.801 [info] cyrsasl_digest:57--FQDN used to check DIGEST-MD5 SASL authentication: baideMacBook-Pro
11:40:44.820 [warning] lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 100 messages/sec
11:40:44.849 [info] Application inets started on node ejabberd@localhost
11:40:44.872 [info] Application p1_iconv started on node ejabberd@localhost
11:40:44.893 [info] mod_demo:21--mod_demo start...,redis 'get fafaim:foo' = {ok,<<"12">>}
11:40:44.893 [info] mod_mb_echo:39--Hello, mod_mb_echo, <<"fafacn.com">>
11:40:44.896 [info] mod_mb_echo:43--set Redis cache ---> Max_im_group_id = 1
11:40:44.896 [info] ejabberd_listener:194--Reusing listening port for 5222
11:40:44.896 [info] ejabberd_listener:194--Reusing listening port for 5269
11:40:44.896 [info] ejabberd_listener:194--Reusing listening port for 5280
11:40:44.896 [info] ejabberd_app:71--ejabberd 0.0 is started in the node ejabberd@localhost
11:40:44.896 [info] Application ejabberd started on node ejabberd@localhost

371 ##
372 ## Number of connections to open to the database for each virtual host
373 ##
374 odbc_pool_size: 1000

bash-3.2# ejabberdctl live
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V6.4  (abort with ^G)
(ejabberd@localhost)1> 11:41:58.648 [info] Application lager started on node ejabberd@localhost
11:41:58.654 [info] Application sasl started on node ejabberd@localhost
11:41:58.661 [info] Application crypto started on node ejabberd@localhost
11:41:58.668 [info] Application asn1 started on node ejabberd@localhost
11:41:58.668 [info] Application public_key started on node ejabberd@localhost
11:41:58.674 [info] Application ssl started on node ejabberd@localhost
11:41:58.677 [info] Application p1_yaml started on node ejabberd@localhost
11:41:58.684 [info] Application p1_tls started on node ejabberd@localhost
11:41:58.689 [info] Application p1_xml started on node ejabberd@localhost
11:41:58.692 [info] Application p1_stringprep started on node ejabberd@localhost
11:41:58.695 [info] Application p1_zlib started on node ejabberd@localhost
11:41:58.697 [info] Application p1_cache_tab started on node ejabberd@localhost
11:41:58.814 [info] Application mnesia started on node ejabberd@localhost
11:41:59.381 [info] Application p1_mysql started on node ejabberd@localhost
11:41:59.660 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:41:59.660 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:41:59.660 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:41:59.660 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:41:59.682 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:41:59.683 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:41:59.683 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:41:59.683 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:41:59.704 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:41:59.705 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:41:59.705 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:41:59.705 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:41:59.708 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:41:59.708 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:41:59.708 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:41:59.708 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:41:59.753 [info] cyrsasl_digest:57--FQDN used to check DIGEST-MD5 SASL authentication: baideMacBook-Pro
11:41:59.860 [info] mod_demo:21--mod_demo start...,redis 'get fafaim:foo' = {ok,<<"12">>}
11:41:59.861 [info] mod_mb_echo:39--Hello, mod_mb_echo, <<"fafacn.com">>
11:41:59.863 [info] mod_mb_echo:43--set Redis cache ---> Max_im_group_id = 1
11:41:59.863 [info] ejabberd_listener:194--Reusing listening port for 5222
11:41:59.863 [info] ejabberd_listener:194--Reusing listening port for 5269
11:41:59.863 [info] ejabberd_listener:194--Reusing listening port for 5280
11:41:59.863 [info] ejabberd_app:71--ejabberd 0.0 is started in the node ejabberd@localhost

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Cbash-3.2# 
bash-3.2# 
bash-3.2# ejabberdctl live
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V6.4  (abort with ^G)
(ejabberd@localhost)1> 11:42:05.769 [info] Application lager started on node ejabberd@localhost
11:42:05.775 [info] Application sasl started on node ejabberd@localhost
11:42:05.782 [info] Application crypto started on node ejabberd@localhost
11:42:05.790 [info] Application asn1 started on node ejabberd@localhost
11:42:05.790 [info] Application public_key started on node ejabberd@localhost
11:42:05.797 [info] Application ssl started on node ejabberd@localhost
11:42:05.800 [info] Application p1_yaml started on node ejabberd@localhost
11:42:05.806 [info] Application p1_tls started on node ejabberd@localhost
11:42:05.811 [info] Application p1_xml started on node ejabberd@localhost
11:42:05.814 [info] Application p1_stringprep started on node ejabberd@localhost
11:42:05.817 [info] Application p1_zlib started on node ejabberd@localhost
11:42:05.819 [info] Application p1_cache_tab started on node ejabberd@localhost
11:42:05.931 [info] Application mnesia started on node ejabberd@localhost
11:42:06.475 [info] Application p1_mysql started on node ejabberd@localhost
11:42:06.531 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.532 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.532 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.532 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.742 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.2773.0>,normal}
11:42:06.743 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.743 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.747 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.747 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.747 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.747 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.747 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.748 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.748 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.748 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.755 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.755 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.755 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.755 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.757 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.757 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.757 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.757 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.757 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.757 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.758 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.758 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.763 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.763 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.763 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.763 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.765 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.765 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.765 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.765 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.766 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.767 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.767 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.767 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.775 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.775 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.776 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.776 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.778 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.778 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.778 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.778 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.787 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.787 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.788 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.788 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.831 [info] cyrsasl_digest:57--FQDN used to check DIGEST-MD5 SASL authentication: baideMacBook-Pro
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.882 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.882 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.882 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3038.0>,normal}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3044.0>,normal}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3014.0>,normal}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3089.0>,normal}
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.883 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.883 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3031.0>,normal}
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3094.0>,normal}
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3077.0>,normal}
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3085.0>,normal}
11:42:06.884 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.884 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.891 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.892 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3182.0>,normal}
11:42:06.899 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.902 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.902 [error] ejabberd_odbc:544--p1_mysql_conn: p1_mysql_recv: socket was closed {<0.3275.0>,normal}
11:42:06.903 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.904 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.905 [error] ejabberd_odbc:544--p1_mysql_recv: Failed connecting to "127.0.0.1":3306 : {error,econnreset}
11:42:06.929 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.929 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.929 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.930 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.930 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.932 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.932 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.932 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.933 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.933 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.933 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.933 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error login_failed
11:42:06.933 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: login_failed
** Retry after: 30 seconds
11:42:06.934 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.934 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.934 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.934 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.934 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.934 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.935 [error] ejabberd_odbc:544--p1_mysql_conn: Failed connecting to "127.0.0.1":3306 : {error,"connect failed : {error,econnreset}"}
11:42:06.935 [error] ejabberd_odbc:544--p1_mysql_conn: post_start error connect_failed
11:42:06.935 [info] ejabberd_odbc:246--mysql connection failed:
** Reason: connect_failed
** Retry after: 30 seconds
11:42:06.959 [info] mod_demo:21--mod_demo start...,redis 'get fafaim:foo' = {ok,<<"12">>}
11:42:06.959 [info] mod_mb_echo:39--Hello, mod_mb_echo, <<"fafacn.com">>
11:42:06.961 [info] mod_mb_echo:43--set Redis cache ---> Max_im_group_id = 1
11:42:06.962 [info] ejabberd_listener:194--Reusing listening port for 5222
11:42:06.962 [info] ejabberd_listener:194--Reusing listening port for 5269
11:42:06.962 [info] ejabberd_listener:194--Reusing listening port for 5280
11:42:06.962 [info] ejabberd_app:71--ejabberd 0.0 is started in the node ejabberd@localhost

**Comment by zinid** [comment]
I would not recommend using pool size more than 50.
The pool is not optimized to handle such many connections.

**Comment by yuan2006open** [comment]
Hi,zinid, Our application queries aways timeout,if pool size less than 50 connections,we aways set 100~300.Such big size is for register test with Tsung.

**Comment by zinid** [comment]
Well, picking an element from the pool has O(N) complexity, so eventually your pool will degrade.

**Comment by yuan2006open** [comment]
Thank you,you are right. Pool size can't set too big.

**Comment by karlmendes** [comment]
Hi @yuan2006open, how many pool u recommend to 1000 users ?

**Comment by trimbakgopalghare** [comment]
Hello,
for ejabberd > 18 
in ejabberd.yml  sql_pool_size = 1
Increase ulimit
for redhat base system :
ulimit -n 100000 (ru n yhis command on terminal for temporary change)
or
open file vim /etc/security/limits.conf
and add bellow line

          soft     nofile          200000
          hard     nofile          200000
if any query ask  ....
