### ISSUE TITLE
muc ghost users: is this a bug?

### ISSUE THREAD

**Issue by liudanking** [processone/ejabberd#551]
Hi, all,

After running ejabbed (14.07) for several days, ets table *muc_online_users* generated many users that are not online at all which seems to be *ghost* users. Other information is as follows:

1. Ejabberd cluster consists of 3 servers serving the same domain;
2. I have ~3000 online users and ~4000 permanent muc rooms everyday.

This problem makes some user can NOT join rooms because of limitation of *max_user_conferences* configuration.

Did anyone meet the same problem before? Or is this a bug?

Daniel

**Comment by cromain** [comment]
this is a feature. you can still raise max_user_conferences value if this match your needs
