### ISSUE TITLE
mod_admin_extra can not set vcard with local characters

### ISSUE THREAD

**Issue by tomasz-c** [processone/ejabberd#552]
In version 15.04, you can not add NICKNAME with local language characters, for example:
`./ejabberdctl set_nickname jablonski domain.com "Jablonski"`
It is working properly.

`./ejabberdctl set_nickname jablonski domain.com "Jabłoński"`
This causes an error:
http://pastebin.com/mSSyvy2D

This issue occurs on the embedded module mod_admin_extra and that's built manually.

In version 15.03 it is working properly. Can you please repair?

P.S.
Is it possible to set NICKNAME of two words?

**Comment by cromain** [comment]
do you mean you did not used mod_admin_extra included in 15.04 but manually installed from ejabberd-contrib ?
If yes, please check without building anything, just use raw 15.04 and its own mod_admin_extra

**Comment by tomasz-c** [comment]
I tried on both modules, included in 15.04 and installed manually. The effect was the same.

**Comment by badlop** [comment]
> In version 15.03 it is working properly.

I get that problem using git master, and 15.03 git tag, and 15.03 linux binary installer.

**Comment by tomasz-c** [comment]
>Umm, I get that problem using git master, and 15.03 git tag, and 15.03 linux binary installer.

In the installer version of ejabberd-15.03-linux-x86_64-installer.run with mod_admin_extra (built 04-26 23:21) this works for me.
Currently, the module is not available in the 'modules_available' so I check on the built earlier.
If you need it I share mod_admin_extra.beam where it works for me.

**Comment by badlop** [comment]
Maybe the problem appears when using Erlang OTP 17, which includes changes related to Unicode, and ejabberd_ctl gets the arguments in Unicode, which later can't be converted to binary for processing.

**Comment by badlop** [comment]
In the last months there were changes in ejabberd_ctl. Now testing ejabberd git master I don't get the problem, so the ticket can be closed.
