### ISSUE TITLE
Can not connect from Jabber client. Error message : Service unavailable.

### ISSUE THREAD

**Issue by dongmai** [processone/ejabberd#553]
Hi Ejabberd team,

I am currently facing the issue, that is after I've setup Ejabberd successfully on our server. Can add new users normally by access the link http://myhos:5280/admin . But when I try to connect using those accounts from a client tool I got the error message (service unavailable).

Details:
- I've installed Ejabberd from binary installer.
- Check for port 5222 and its open.

Can anyone tell me why? and how to fix this?
Many Thanks.

**Comment by zinid** [comment]
If your client has XML console, you should look into it to check what packet gets 503 response.

**Comment by dongmai** [comment]
I've tried on the site: https://habahaba.im/ checked firebug and got this response:
<body xmlns='http://jabber.org/protocol/httpbind' type='terminate' condition='remote-connection-failed'
/>
Any ideas?

Thanks.

**Comment by zinid** [comment]
No ideas, you should provide XML console snippet, otherwise we close ticket as lacking debug info.

**Comment by dongmai** [comment]
I has found the problem. That is I has been used a virtual host that wasnt setup before.
Closed.
