### ISSUE TITLE
mod_pubsub.erl missing jlib: --> won't compile on RPI

### ISSUE THREAD

**Issue by seishinryohosha** [processone/ejabberd#554]
In mod_pubsub.erl line 3665

integer_to_binary should be jlib:integer_to_binary

else compiling on a Raspberry Pi doesn't work.
On another plattform works although.

**Comment by zinid** [comment]
I actually depends on Erlang version. You can try to update it on RPI if possible.

**Comment by seishinryohosha** [comment]
Okay, thank you very much.

**Comment by zinid** [comment]
Well, anyway this should be changed to jlib:integer_to_binary call, so I reopen
