### ISSUE TITLE
mod_roster or mod_shared_roster  - 100% CPU

### ISSUE THREAD

**Issue by tomasz-c** [processone/ejabberd#563]
Steps to reproduce the problem:

Create users:
user1, user2, user3, user4

Add two groups:
group1 (members, user1, user2)
group2 (members, user3, user4)

group1 (displayed groups: group1, group2)
group2 (displayed groups: group1, group2)

Login to user1 from jabber client and move example user3 to group1. This action will jump 100% CPU by beam.smp until you restart ejabberd, or restarted mod_roster and mod_shared_roster.
This is confirmed using the psi and pidgin,

It also causes user1 disconnect and not allow him to use jabber.
Transfer roster to another group may be done by the user accidentally, that's what this has been discovered.

**Comment by badlop** [comment]
This may be related to #556 which I fixed yesterday. Please try again to see if your problem is solved too.

**Comment by tomasz-c** [comment]
Yes, it's the same bug. Please close this report.
Sorry for the duplicate.
