### ISSUE TITLE
ejabberdctl connected_users_info lists websocket connections as unknown

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#564]
Currently `ejabberdctl connected_users_info` lists websocket connections as unknown. Example (private information stripped):

```
$ ejabberdctl connected_users_info
.../Gajim    c2s_tls ::FFFF:...   32986   50      ejabberd@...  8664
.../Jappix (1431202699914)   unknown ...  59423   10      ejabberd@...  89
```

where of course the Jappix resource is tthe websocket connection.

**Comment by badlop** [comment]
Apply this patch and login with that client. And search in the log, it will point us what we should add to the source code:
```
--- a/src/ejabberd_c2s.erl
+++ b/src/ejabberd_c2s.erl
@@ -2028,7 +2028,9 @@ get_conn_type(StateData) ->
            p1_tls -> c2s_compressed_tls
        end;
     ejabberd_http_bind -> http_bind;
-    _ -> unknown
+    Other ->
+       ?INFO_MSG("Unknown conn_type: ~p", [Other]),
+       unknown
     end.
 
 process_presence_probe(From, To, StateData) ->
```

**Comment by mathiasertl** [comment]
I have applied the patch, but the message does not show up in stdout or any of the logfiles. Not even if I set the loglevel to debug using `ejabberd_logger:set(5).`.

**Comment by badlop** [comment]
Ok, then apply also this patch:
```
--- a/src/ejabberd_c2s.erl
+++ b/src/ejabberd_c2s.erl
@@ -2009,6 +2009,7 @@ get_auth_tags([], U, P, D, R) ->
 -record(socket_state, {sockmod, socket, receiver}).
 
 get_conn_type(StateData) ->
+    ?INFO_MSG("Will get the conn_type of ~p.", [jlib:jid_to_string(StateData#state.jid)]),
     case (StateData#state.sockmod):get_sockmod(StateData#state.socket) of
     gen_tcp -> c2s;
     p1_tls -> c2s_tls;
```

Login with a typical desktop client, you should get
```
12:33:24.513 [info] Will get the conn_type of <<"user1@localhost/tka1">>.
```

Then login with a websocket client, you should get the above message, also another message about Unknown, then call ctl to confirm the connection and its type match.

**Comment by weiss** [comment]
FWIW, I can't reproduce the issue with the [current Git code][1].  After logging in with [Kaiwa][2], `ejabberdctl connected_users_info` lists the connection type as `websocket`.  And it still so that after [resuming][3] the session.

[1]: https://github.com/processone/ejabberd/commit/f6b892b36623bb35b1140682544202c52583dd0b
[2]: http://getkaiwa.com/
[3]: http://xmpp.org/extensions/xep-0198.html#resumption
