### ISSUE TITLE
Web Admin can't be access

### ISSUE THREAD

**Issue by anhcoi123** [processone/ejabberd#565]
When benchmark with Tsung, I set about 100k concurrent user to connect to ejabberd, when reaching 65k connection to server, Tsung still running (more TCP connection still be establish) but I can't access the web-admin (before reaching 65k connection, I still can access web-admin).

After using mod_muc_admin to check how many user in a test room (joined by Tsung), I found that gen_fsm timeout, also the mod_admin_extra get connected_users_vhost display the max 65528 user.

I still don't know why new TCP connection still established (as I check the server, there are over 162k established TCP connection), connected user still can send/recv message but ejabberd only show a list of 65k user and can't access web-admin.

P/S: I already set ulimit, max erlang port, ets table,...... and I using Tsung on the same machine with ejabberd (with 3 additional IP address)

**Comment by mremond** [comment]
It seems to me purely related to TCP and Linux optimisation question and not directly ejabberd related.
