### ISSUE TITLE
Ejabberdctl command 'change_room_option' for multiple options

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#567]
Would it be possible to implement a method to change multiple room options at once (WRITE), and to retrieve current room options (READ), by using ejabberdctl (and XMLRPC plugin)?

Currently, I only found 'change_room_option' but it is pretty inefficient to change all room settings one by one. It also doesn't work for 'title', 'description', 'subject', 'subject_author'...

**Comment by badlop** [comment]
> Currently, I only found 'change_room_option' but it is pretty inefficient to change all room settings one by one. Would it be possible to implement a method to change multiple room options at once (WRITE),

I'll consider how much effort would that take to implement.

> It also doesn't work for 'title', 'description', 'subject', 'subject_author'...

For title it works correctly:
```
$ ejabberdctl change_room_option room conf.localhost title \"This is title\"
$
```

For description, there was a bug, I've fixed in git and works correctly now.

For subject, that isn't implemented in ejabberd as room configuration, it is room state (like the list of occupants, and history of messages, so it isn't stored. It would take too much changes to implement subject get&set.

> and to retrieve current room options (READ), by using ejabberdctl (and XMLRPC plugin)?

I'll check how much it would take to implement.

**Comment by badlop** [comment]
I don't like how the command "change_room_options" would work.

But I've implemented the other suggestion you pointed:
```
$ ejabberdctl get_room_options room2 conference.localhost
title   This is room title
description     This is room description.
allow_change_subj       true
allow_query_users       true
allow_private_messages  true
allow_private_messages_from_visitors    anyone
allow_visitor_status    true
allow_visitor_nickchange        true
public  true
public_list     true
...
```

**Comment by dirkmoors** [comment]
Ok thanks!

**Comment by skippy** [comment]
FYI, in the above example, `ejabberdctl change_room_option room conf.localhost title \"This is title\"
` does not work.  you need to use `ejabberdctl change_room_option room conf.localhost title \'This is title\' ` (single quotes)... At least this is what I found using the bash shell
