### ISSUE TITLE
TLS connections die with "decryption failed or bad record mac"

### ISSUE THREAD

**Issue by weiss** [processone/ejabberd#568]
### Problem descripton

TLS connections sometimes die with a "decryption failed or bad record mac" message on the client side.  (I've only tested c2s, but I guess this can happen to any of ejabberd's TLS connections.)  The issue is triggered when the server is flooded with stanzas, but those floods need not be excessive.  That is, it happens during normal operation (I often run into this while logging in with Gajim).  The problem goes away if I define a traffic shaper, which is probably the reason we don't receive more complaints.

### What I found out so far

This issue is only triggered with Erlang/OTP R16 or newer.  According to `git bisect`, the problem has been introduced with commit erlang/otp@6027f852217f0014f1892fbbfa45c69e104da652.  Unfortunately, this is a massive merge commit with more than 10,000 lines of diff output.  That is, the merge commit _itself_ adds those lines, presumably to fix lots of merge conflicts.  _Both_ parents of the merge commits are fine.  So the issue isn't introduced by the commits that were merged into the main branch as such, but by the merge itself.  The merged branch tries to optimize port management and port task scheduling (OTP-10336), so the issue _might_ be related to how [processone/tls][1] is implemented as a port driver.

### What I tried so far

Some of the changes introduced by that merged branch can be reverted by:

* Adding the `ERL_DRV_FLAG_NO_BUSY_MSGQ` [flag][2] to [the driver entry structure][3].
* Adding the `ERL_DRV_FLAG_USE_PORT_LOCKING` flag to the driver entry structure.
* Calling `erl(1)` with [`+n s`][4].

Unfortunately, neither of these settings make the issue go away.

### How to reproduce the problem

When no c2s shaper is enabled, the issue seems easily reproducible with a [simple script][5] that logs in a user with two resources and has each of them flood the other one with messages.  It's harder to reproduce with just one resource flooding itself.

### Acknowledgements

Many thanks go to [Stefan Karlsson][6] for providing a test environment and for all his help with tracking down the issue.

[1]: https://github.com/processone/tls
[2]: http://www.erlang.org/doc/man/driver_entry.html#driver_flags
[3]: https://github.com/processone/tls/blob/e231cbde546c2e2200f6dae01d13cf743d253c6d/c_src/p1_tls_drv.c#L720
[4]: http://erlang.org/doc/man/erl.html#+n
[5]: https://gist.githubusercontent.com/weiss/2d64ecac01eb08a22428/raw/627fb65bbdd0b589e7e9a4bc65e4ba865c81cf16/xmpp-flood.py
[6]: https://github.com/stefandxm

**Comment by weiss** [comment]
I tracked it down, the problem is that a single operation (such as encrypting or decrypting a chunk of data) requires multiple `port_control/2` calls.  E.g., `p1_tls:send/2` first runs [`?SET_DECRYPTED_OUTPUT`][1] to feed the driver with the plaintext and then runs [`?GET_ENCRYPTED_OUTPUT`][2] to receive the ciphertext.  If two processes (`ejabberd_c2s` and `ejabberd_receiver`) use the same TLS port at the same time, the `port_control/2` calls might be interleaved and the TLS stream will be garbled.  Due to the improved parallelism in R16, this now happens in practice.

A quick fix would be to [run the encryption/decryption operations in a transaction][3], but that's a bit ugly and somewhat inefficient, I guess.  I'd rather change the driver so that encryption and decryption are each done using a single `port_control/2` call, though that change is a bit more intrusive.

While at it, maybe we want to switch to using `erlang:port_call/3` instead of `port_control/3`?  The receive operation must return two values ([input][4] and [output][5] data), and that's nicer with the `erlang:port_call/3` interface.  But that's an even more intrusive change, of course.

I can prepare a patch.

[1]: https://github.com/processone/tls/blob/049c0616c0bebb05ad1491ecafece42991a47929/src/p1_tls.erl#L231
[2]: https://github.com/processone/tls/blob/049c0616c0bebb05ad1491ecafece42991a47929/src/p1_tls.erl#L235
[3]: https://github.com/weiss/tls/commit/0e270f4b5bd8c09d762a6651c78a1e488a18916a
[4]: https://github.com/processone/tls/blob/049c0616c0bebb05ad1491ecafece42991a47929/src/p1_tls.erl#L206
[5]: https://github.com/processone/tls/blob/049c0616c0bebb05ad1491ecafece42991a47929/src/p1_tls.erl#L211

**Comment by alexeyshch** [comment]
Please check is this commit solves the issue: https://github.com/processone/tls/commit/a6971fcf6df0e2c0c23e1bf366d478a8ed5ef52c

**Comment by weiss** [comment]
Looks good!

I didn't suggest that because I thought it could still go wrong during TLS renegotiations, but I missed that we [refuse renegotiation requests][1] anyway, so that should be fine.

Thanks!

[1]: https://github.com/processone/tls/blob/049c0616c0bebb05ad1491ecafece42991a47929/c_src/p1_tls_drv.c#L632

**Comment by alexeyshch** [comment]
Great, thanks!
