### ISSUE TITLE
Python client for Ejabberd XMLRPC API

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#572]
Hello,

I'm currently working on an open source library for Python, that implements the Ejabberd XMLRPC API.
I will be updating the library in the upcoming week(s) to support the entire API. 
It would be cool if you guys could support/mention my library so other developers that are interested jump on board and contribute (since I cannot spend my entire time on this project). It would be even cooler if we could let this library evolve to be the 'official' open source Ejabberd XMLRPC API library for Python!

You can checkout the library at PyPi:
https://pypi.python.org/pypi/pyejabberd

And on GitHub:
https://github.com/dirkmoors/pyejabberd

Thanks in advance!
Cheers

**Comment by mremond** [comment]
Hello,

Sure I should mention that library in the documentation. I need to create a place for libraries in various languages.

**Comment by mremond** [comment]
Hi, the reference was added here:
http://docs.ejabberd.im/admin/contrib/

Thanks !

**Comment by dirkmoors** [comment]
Awesome! Thanks for adding nu lib to the docs!

Op vrijdag 23 oktober 2015 heeft Mickaël Rémond <notifications@github.com>
het volgende geschreven:

**Comment by dirkmoors** [comment]
My*

Op vrijdag 23 oktober 2015 heeft Dirk Moors <dirkmoors@gmail.com> het
volgende geschreven:
