### ISSUE TITLE
send_message with mod_admin_extra

### ISSUE THREAD

**Issue by shyaken** [processone/ejabberd#575]
I'm new to ejabberd and I'm finding how to send message to other user using send_message in mod_admin_extra but I don't receive anything at client.
I cannot find any guide about using this function from any resource online, this is how I tried to send message:

![image](https://cloud.githubusercontent.com/assets/158163/7718484/46360446-fedb-11e4-85bc-53742213eb38.png)

please tell me if I'm doing something wrong?

**Comment by sezuan** [comment]
Try something like:

    ejabberdctl send_message headline bar@foos.org bar@foos.org \"That\'s the title\" \"Hi. Spaces are possible.\"
    ejabberdctl send_message chat bar@foos.org bar@foos.org \"\" \"Hi. Spaces are possible.\"

**Comment by shyaken** [comment]
I've tested, client receive nothing :'(

**Comment by shyaken** [comment]
![image](https://cloud.githubusercontent.com/assets/158163/7721664/8f3bd90e-ff03-11e4-84fc-a3389a11173d.png)
this is what I called and what my log printed out when it receive that calling. Please help me, I think it maybe caused by my mod s2s?

**Comment by weiss** [comment]
Is `debug.beta.sembangchat.com` the name of the server you're running that `ejabberdctl` command on?  Or are you running it from a different server?

**Comment by shyaken** [comment]
oh, that's my mistake :'( my ejabberdctl is running with another host. Big thanks to Weiss
