### ISSUE TITLE
Reset admin password ejabberd14.12

### ISSUE THREAD

**Issue by drakesjoy** [processone/ejabberd#579]
Hello,

Please provide me the way to reset the admin password for the ejabberd. I  have installed the ejabberd /opt/ejabberd-14.12 and I have forgot the admin password. Please provide me the steps to reset the admin password?

I have tried via erlang shell but getting the error. Is there any other way to reset it?

**Comment by lefam** [comment]
1. Make sure ejabberd is not running (`ejabberdctl stop`);

2. Start ejabberd in live mode with this command: `ejabberdctl live`

3. Finally run this command in erlang shell to update the password:
`ejabberd_auth:set_password(<<"admin">>, <<"localhost">>, <<"new_password">>).`

**Comment by beherit** [comment]
Uhm, it is simpler method:
``
ejabberdctl change_password admin localhost new_password
``

**Comment by drakesjoy** [comment]
For the ejabberctl change_password getting the below error. It seems the change_password option is not available with 14.12 ejabberd version.

/opt/ejabberd-14.12/bin/ejabberdctl  change_password admin chatline.mykuwaitnet.net newpassword
Error: command "change_password" not known.

**Comment by drakesjoy** [comment]
Hello,

I have tried using the erlang shell and getting the below error,
 /opt/ejabberd-14.12/bin/ejabberdctl live
--------------------------------------------------------------------

IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press any key to continue


Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:24:4] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V5.10.4  (abort with ^G)
(ejabberd@localhost)1> 21:59:37.533 [info] Application lager started on node ejabberd@localhost
21:59:37.548 [info] Application sasl started on node ejabberd@localhost
21:59:37.580 [info] Application crypto started on node ejabberd@localhost
21:59:37.595 [info] Application asn1 started on node ejabberd@localhost
21:59:37.595 [info] Application public_key started on node ejabberd@localhost
21:59:37.624 [info] Application ssl started on node ejabberd@localhost
21:59:37.648 [info] Application p1_yaml started on node ejabberd@localhost
21:59:37.741 [info] Application p1_tls started on node ejabberd@localhost
21:59:37.763 [info] Application p1_xml started on node ejabberd@localhost
21:59:37.771 [info] Application p1_stringprep started on node ejabberd@localhost
21:59:37.775 [info] Application p1_zlib started on node ejabberd@localhost
21:59:37.783 [info] Application p1_cache_tab started on node ejabberd@localhost
21:59:38.120 [info] Application mnesia started on node ejabberd@localhost
21:59:39.808 [info] FQDN used to check DIGEST-MD5 SASL authentication: vps2
21:59:39.968 [info] Reusing listening port for 5222
21:59:39.970 [info] Reusing listening port for 5269
21:59:39.970 [info] Reusing listening port for 5280
21:59:39.970 [info] ejabberd 14.12 is started in the node ejabberd@localhost
21:59:39.972 [info] Application ejabberd started on node ejabberd@localhost
21:59:40.089 [info] Application inets started on node ejabberd@localhost
(ejabberd@localhost)4> ejabberd_auth:set_password(<<"admin">>, <<"localhost">>, <<"new_password">>).
** exception error: bad argument
     in function  extauth:call_port/2 (src/extauth.erl, line 99)
     in call from ejabberd_auth_external:set_password/3 (src/ejabberd_auth_external.erl, line 90)
     in call from lists:foldl/3 (lists.erl, line 1248)
(ejabberd@localhost)5>

**Comment by mremond** [comment]
Well, you are using external authentication. Change your password in your external storage as ejabberd will not be able to change it. external authentication is read-only.
