### ISSUE TITLE
registration_timeout not working as expected

### ISSUE THREAD

**Issue by gauripadbidri** [processone/ejabberd#580]
Hi All,

We have the LATEST Ejabberd installed on our Ubuntu instance. We want users to be able to register themselves using In Band registration i.e XEP 0077...However, seems like the default timeout is 10 minutes. We have tried to set <code>"registration_timeout:infinity"</code> but it does not work as expected...(The same property worked with the older versions of ejabberd)...Can you tell us a way to achieve the <code>"registration_timeout:infinity"</code> behavior...

There is no adequate documentation around this one...we have tried configuring registration_timeout property under mod_register / etc as follows : 

<span>## By default the freq of acct reg frm the same IP is ltd to 1 account evry 10 min. To disable,     ##specify: infinity
 registration_timeout: infinity</span>

OR 

<span>## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
    all: allow
    registration_timeout: infinity</span>

NOTE : Above settings were enabled only 1 at a time (not both were activated at the same time)...Yet none of them worked for us.

Can you help us on this one ? It is holding us back from our release. Thanks !

**Comment by badlop** [comment]
It should work when set as your first example. Just replacing 600 with infinity.

If you set other values in this option, do they take effect? I mean if you put 10 seconds, or 30 seconds.

Another simple test you can make to understand what is happening: try putting an invalid value, for example
> registration_timeout: wrongvalue

Then start ejabberd, try to register an account, and you should get an error like this in the logs:
```
(ejabberd@localhost)1> 10:08:32.732 [info] Configuration problem:
** Option: {registration_timeout,global}
** Invalid value: wrongvalue
** Using as fallback: 600
```

**Comment by satishck1992** [comment]
@gauripadbidri were you able to resolve this issue ??

**Comment by Suvitruf** [comment]
Have same problem on last version of ejabberd builded from sources.

`infinity` doesn't work
I tried invalid values, and server failed with error. So, ejabberd reads this option, but `infinity` doesn't have anyeffect =/

**Comment by prefiks** [comment]
Are you correctly indenting `registration_timeout: infinity`? it should be placed without in main section (without any spaces before), i just checked that a moment ago and it's working.

Additionally default config is allowing only to register from loopback network (it's specified by ip_access rule in mod_register section), so you may be possibly hitting this limitation.

**Comment by Suvitruf** [comment]
Oh, I had 2 spaces before this option.

I removed all spaces and it works. Thanks )

**Comment by zinid** [comment]
Can you please show the diff between the configs? I wonder why registration_timeout was not detected as an unknown option.

**Comment by Suvitruf** [comment]
was like this:
`  registration_timeout: infinity`
now
`registration_timeout: infinity`

**Comment by zinid** [comment]
That's not a diff, I wanted to see the option location relatively to other configuration options.

**Comment by Suvitruf** [comment]
Don't have access for servers now. But as I remember `registration_timeout` rule is after `access` in deffault config file. So, when I wrote `registration_timeout` with 2 spaces, ejabberd thought thats it's custom rule for `access` option, I think.

**Comment by rbhangale1** [comment]
I am facing same issue with ejabberd 16.01. 
registration_timeout field does not work.

**Comment by badlop** [comment]
@rbhangale1 That option works correctly for me using 17.09. Maybe you have set the option wrong, or whatever problem was fixed in those year and half that has passed.

**Comment by rbhangale1** [comment]
We can not update Ejabberd to 17.09 now, can you please tell us alternative solution, I have set registration_timeout: 1, as per doc it should work. 

Still we observe users get registered after 600 seconds from single jid.
