### ISSUE TITLE
Mod_multicast: Add config option to allow relaying

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#583]
Mod_multicast only support local dispatch at the moment and does not allow relaying.

See: http://stackoverflow.com/questions/30476527/ejabberd-mod-multicast-wont-allow-relaying

**Comment by gsnarawat** [comment]
Hello @mremond

 We are facing another issue that it generates the same error message when we are trying mod_multicast with ejabberd 2.1.11 and sending messages more frequently. 

Note : Sender and all recipients are on same domain. 

I have posted on StackOverflow for the same : http://stackoverflow.com/questions/31072762/time-limit-issue-in-mod-multicast-ejabberd

**Comment by mremond** [comment]
I am sorry, we do not "support" ejabberd 2.1.11 anymore.
It is more that 3 years old.

**Comment by gsnarawat** [comment]
That's Ok, but can you please guide me with something. I appreciate your quick response.

**Comment by badlop** [comment]
> Packet relay is denied by service policy

mod_multicast does not support packet relay. XEP-0033 explains this:

> The server MAY choose to limit whether non-local servers can send address headers that require the local server to send to third parties (relaying). In either case, if the server chooses to disallow the request, the server MUST return a Forbidden error (see the Error Conditions section below).

**Comment by gsnarawat** [comment]
@mremond  & @badlop  ... Never mind, I have resolved this at my Level.  The actual problem is with Check Relay Section in mod_multicast.erl 

thanks.

**Comment by teledna** [comment]
I am also facing the same issue but with latest ejabberd version 15.06.How to resolve this

**Comment by badlop** [comment]
Hi Teledna, can you describe how to reproduce the problem you see? What is your mod_multicast configuration, what queries you send, when the problem appears, what is logged...?

**Comment by teledna** [comment]
I need to send single  message to multiple users. I want to use mod_multicast. in ejabberd.yml i have configured the below
mod_multicast:
    host: "multicast.172.16.11.155"
i have sent the following message
<message from="john@172.16.11.155/mobile" id="328fcdda-1d55-462f-be8d-afdffa3749d6" to="multicast.172.16.11.155"><addresses xmlns="http://jabber.org/protocol/address"><address type="to" jid="jim@172.16.11.155"/><address type="to" jid="tim@172.16.11.155" /><address type="to" jid="rony@172.16.11.155"/></addresses><body>Hello</body></message>

i am getting error as "Packet relay is denied by service policy"

**Comment by teledna** [comment]
@gsnarawat  how did you resolve this issue

**Comment by badlop** [comment]
teledna, what do you configured in the global option hosts?

Maybe the problem you suffer was fixed by this commit included in ejabberd 15.09: https://github.com/processone/ejabberd/commit/4125dfd166067b4c613bd8d49eef5f876fdb1b94

**Comment by teledna** [comment]
i have configured host: "multicast.172.16.11.155"

**Comment by badlop** [comment]
You should configure something like this:
```
hosts:
  - "172.16.11.155"

modules:
  ...
  mod_multicast: {}
  ...
```

**Comment by teledna** [comment]
Thanks it is working now
