### ISSUE TITLE
ejabberdctl push-alltoall

### ISSUE THREAD

**Issue by sts** [processone/ejabberd#586]
We are running into issues when trying to push our ldap roaster to all users. When running ```ejabberdctl push-alltoall example.com example.com``` on our server, the command exists successfully, but it shows up the following log entries:

```
2015-06-01 15:19:06.415 [warning] <0.2960.0>@ejabberd_config:get_option:674 Option {default_db,error} has invalid (outdated?) format. This is likely a bug
2015-06-01 15:19:06.415 [warning] <0.2960.0>@ejabberd_config:get_option:674 Option {auth_method,error} has invalid (outdated?) format. This is likely a bug
```

When running the same command using the ejabber debug shell it returns 'ok':

```
ejabberdctl debug --node ejabberd@ixo-jabber01
mod_admin_extra:push_alltoall(<<"example.com">>, <<"example.com">>).
ok
```

So the problem seems to be in ejabberdctl handling the arguments. We are also using ```mod_shared_roaster_ldap```.

Running the lastest jabber.at packages on Debian/Wheezy with Erlang from Debian backports.

* ejabberd             1:15.04-2~afa70
* erlang-asn1          1:17.1-dfsg-4~bpo70+1
* erlang-base          1:17.1-dfsg-4~bpo70+1
* erlang-crypto        1:17.1-dfsg-4~bpo70+1
* erlang-eunit         1:17.1-dfsg-4~bpo70+1
* erlang-goldrush      0.1.6-2~afa70
* erlang-hyperloglog   0.2013.10.12-1~afa70
* erlang-inets         1:17.1-dfsg-4~bpo70+1
* erlang-jiffy         0.13.3+dfsg-1~afa70
* erlang-lager         2.0.3.26-2~afa70
* erlang-mnesia        1:17.1-dfsg-4~bpo70+1
* erlang-odbc          1:17.1-dfsg-4~bpo70+1
* erlang-proper        1.1+dfsg-1~afa70
* erlang-public-key    1:17.1-dfsg-4~bpo70+1
* erlang-runtime-tools 1:17.1-dfsg-4~bpo70+1
* erlang-ssl           1:17.1-dfsg-4~bpo70+1
* erlang-syntax-tools  1:17.1-dfsg-4~bpo70+1
* erlang-tools         1:17.1-dfsg-4~bpo70+1
* erlang-webtool       1:17.1-dfsg-4~bpo70+1
* erlang-xmerl         1:17.1-dfsg-4~bpo70+1

**Comment by badlop** [comment]
Right, the argument types in those commands are wrong, as also reported in https://github.com/processone/ejabberd/pull/585
