### ISSUE TITLE
SSL Authentication doesn't work via service ejabberd start but does via ejabberdctl start

### ISSUE THREAD

**Issue by donileo** [processone/ejabberd#587]
Using FreeBSD 10.1

Pretty much what the subject line says.. If i start ejabberd via ejabberctl start then I am able to authenticate with SSL. If i use service ejabberd start then I get Client Authentication Failed in the error.log

UPDATE: I fixed the issue. The problem was that I ran the ejabberdctl register user command while being root. which somehow added the mnesia db files in the /root directory. In my specific case (fresh install of ejabberd on FreeBSD the register user command must be run while logged in as the ejabberd user which can only be done by first su to root.. then su to ejabberd  user then finally running the ejabberdctl register user command. Now running the service ejabberd start works perfect.

**Comment by mremond** [comment]
Very glad it is finally working fine for you :)

**Comment by donileo** [comment]
@mremond is there a guide to to properly setting up postgresql with ejabberd. i have it working but the memory consumption for the ejabberd daemon is still ~40mb with no users. just want to make sure im not missing any cfg file changes.

**Comment by mremond** [comment]
The public documentation is here: http://docs.ejabberd.im
Make sure you move all the storage you want to postgres and that the Mnesia database is not taking space.
However, 40mb seems small. An empty Erlang VM is taking 16m of resident memory. Depending on option / preallocation of port, ets tables, etc, you can reach 40mb with a stock Erlang VM.
