### ISSUE TITLE
mod_proxy options marked as "unknown"

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#588]
Here is the feedback on that module:

    > I got some warnings with mod_proxy65. But I guess the options are correct.
    > Like: 2015-06-03 06:46:40.057 [error] <0.38.0>@gen_mod:validate_opts:251 ignoring unknown option 'ip' for module 'mod_proxy65', available options are:

**Comment by zinid** [comment]
Fixed in c1119b1f3945a37f656934ef530f8c7bf158530f
