### ISSUE TITLE
Possible memory leak in SCRAM passwords and ODBC

### ISSUE THREAD

**Issue by schwindp** [processone/ejabberd#590]
Given: ejabberd 15.03+git20150414, erlang 17.3-dfsg-4, Kernel 3.2.0-4-amd64

We're using MySQL as ODBC storage for ejabberd, right now still plaintext passwords.

After setting ```auth_password_format: scram``` and restarting the server it nearly instantly went to using 32GB of RAM (and counting^Wswapping). I did not dare waiting for an ejabberdctl debug shell to spawn to really convert the passwords.

**Comment by badlop** [comment]
With a mysql database created some weeks ago, when I call 
> ejabberd_auth_odbc:convert_to_scram(<<"localhost">>).

I get this in the error log:
```
12:07:25.295 [error] SQL transaction restarts exceeded
** Restarts: 10
** Last abort reason: "#42S22Unknown column 'iterationcount' in 'where clause'"
** Stacktrace: [{ejabberd_odbc,sql_query_t,1,
      [{file,"src/ejabberd_odbc.erl"},{line,167}]},
...
```
I guess this is done for each account, so in your case it would consume a lot of resources. Did you get something similar in your log?

**Comment by schwindp** [comment]
> ** Last abort reason: "#42S22Unknown column 'iterationcount' in 'where clause'"

None of these, since I didn't want to wait until all the available memory was gone when starting up the server - so I didn't start the ```convert_to_scram``` process.

**Comment by badlop** [comment]
But, when you started ejabberd, the users already started to attempt to login? You should disable listening ports until the server is ready to accept connections.

Also, read mysql.sql for comments, because the 'users' table requires three manual changes to support SCRAM.

Anything else relevant in the logs?

**Comment by haegar** [comment]
Aditionally, the database table is already prepared for the scram passwords:

mysql> show create table users \G
*************************** 1. row ***************************
       Table: users
Create Table: CREATE TABLE `users` (
  `username` varchar(250) NOT NULL,
  `password` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `serverkey` text NOT NULL,
  `salt` text NOT NULL,
  `iterationcount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

**Comment by schwindp** [comment]
Checking the logs I only see a single ODBC user login error, but way more of s2s ones like:
```
2015-06-03 10:28:23.631 [error] <0.14891.867>@ejabberd_s2s:route:100 {shutdown,{gen_server,call,[ejabberd_s2s_out_sup,{start_child,[<<"jabber.ccc.de">>,<<"jmt.gr">>,{new,<<"3409688241">>}]},infinity]}}
when processing: {{jid,<<"kaktusfeigling">>,<<"jabber.ccc.de">>,<<"home">>,<<"someuser">>,<<"jabber.ccc.de">>,<<"home">>},{jid,<<"someuserelse">>,<<"jmt.gr">>,<<>>,<<"someuserelse">>,<<"jmt.gr">>,<<>>},{xmlel,<<"presence">>,[{<<"type">>,<<"unavailable">>}],[]}}

or

2015-06-03 10:28:23.630 [error] <0.25566.943>@ejabberd_s2s:route:100 {shutdown,{gen_server,call,[ejabberd_s2s_out_sup,{start_child,[<<"jabber.ccc.de">>,<<"jabber.org">>,{new,<<"790658973">>}]},infinity]}}
when processing: {{jid,<<"foo">>,<<"jabber.ccc.de">>,<<"862549041433316746335365">>,<<"polypoid">>,<<"jabber.ccc.de">>,<<"862549041433316746335365">>},{jid,<<"bar">>,<<"jabber.org">>,<<>>,<<"bar">>,<<"jabber.org">>,<<>>},{xmlel,<<"presence">>,[{<<"type">>,<<"unavailable">>}],[]}}

```

**Comment by badlop** [comment]
So, if you start ejabberd with "auth_password_format: scram", then ejabberd goes crazy. If your start with plain, all is good. The table schema is updated, but the passwords not yet converted. Right?

Try to do this (simply avoid step 3):
0. Backup your mysql database
1. Disable listening ports in ejabberd.yml
2. Restart ejabberd
3. Update manually the SQL table schema to support SCRAM, see comments in mysql.sql
4. Run ejabberdctl debug and call: ejabberd_auth_odbc:convert_to_scram(<<"yourdomain.org">>).
5. In ejabberd.yml set auth_password_format: scram
6. Enable listening ports in ejabberd.yml
7. Restart ejabberd

**Comment by schwindp** [comment]
Yes, it's behaving as you said.
I'll try the mentioned steps on friday morning, thanks so far. Will keep you posted.
