### ISSUE TITLE
XEP-0178 Best practices for SASL EXTERNAL

### ISSUE THREAD

**Issue by huguesb** [processone/ejabberd#593]
According to https://www.process-one.net/en/ejabberd/protocols/ both the Community and Business editions support XEP-0178 Best practices for SASL EXTERNAL.

However a recent StackOverflow answer suggests that this feature is only available in the Business edition: http://stackoverflow.com/questions/30297464/ejabberd-sasl-external-authentication-for-client-ssl-authentication-using-certif

A quick glance at release notes and the source seems to confirm the StackOverflow answer.

Could you clarify the current status of ejabberd support of XEP-0178?

If it is currently only available in the Business edition, do you expect this to change anytime soon? If not, how likely is it that a PR for this feature would be accepted?

**Comment by mremond** [comment]
Hello,

As explained here: http://docs.ejabberd.im/ejabberd-faq/

The business edition is THE big strength of ejabberd. We develop features for customers and they are thus entitled to get a head start and a business advantage from their investment. This benefit to the community as the community version get production ready advanced features after a while.
The Business Edition process benefits also to new customers, so if AeroFS becomes customers of ProcessOne they will get access to this features in advance and both help contributing to the continuous development of ejabberd.

That said, as mentioned on the same page:
- The feature will actually end up being integrated in ejabberd community edition when the commitment to keep it for customers only expires.
- Our commitment does not prevent us to consider quality contributions from third party developers. If you submit a PR it would be considered. As you understand, we cannot commit on accepting it, as it is highly dependant on the quality of what you will submit.

I hope to have clarified the status of that feature.

**Comment by huguesb** [comment]
Can you confirm whether XEP-0178 is a business-only feature? If so please update https://www.process-one.net/en/ejabberd/protocols/ accordingly to avoid confusion.

**Comment by mremond** [comment]
Actually, it is a bit of both. XEP-0178 server to server authentication is supported by both version. Client certificate authentication part is not in community edition yet.

**Comment by f055** [comment]
I've updated the list to reflect that XEP-0178 in Community Server is S2S Auth only.

**Comment by mremond** [comment]
Thanks @f055  !
