### ISSUE TITLE
check_account doesn't return results

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#596]
After executed command check_account no results are returned - I can't determine from external script that account exists or not.

**Comment by weiss** [comment]
Are you using `ejabberdctl` to execute that command?  If so, note that the command produces no output but communicates the result via the exit status:

    $ ejabberdctl check_account existent example.com; echo $?
    0
    $ ejabberdctl check_account nonexistent example.com; echo $?
    1

This works for me with the current Git code.  If it doesn't work for you: What ejabberd version are you using?

**Comment by beherit** [comment]
Thank you for the explanation :)
