### ISSUE TITLE
Error building on debian 8

### ISSUE THREAD

**Issue by vittico** [processone/ejabberd#598]
hi guys!

Any ideas on what Im missing? This error while Im builing on debian 8

Compiled asn1/XmppAddr.asn1
unexpected error compiling src/eldap_filter_yecc.yrl
{'EXIT',{undef,[{yecc,file,
                      ["src/eldap_filter_yecc.yrl",
                       [{parserfile,"src/eldap_filter_yecc.erl"},
                        {return,true}]],
                      []},
                {rebar_erlc_compiler,compile_xrl_yrl,5,
                                     [{file,"src/rebar_erlc_compiler.erl"},
                                      {line,512}]},
                {rebar_base_compiler,compile,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,121}]},
                {rebar_base_compiler,compile_worker,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,194}]}]}}
ERROR: compile failed while processing /home/administrador/work/centralvirtual/Build/ejabberd/ejabberd-15.04: rebar_abort
Makefile:87: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1

**Comment by prefiks** [comment]
Please try installing erlang-asn1 and erlang-parsetools, i think one of those two two is not available on your system.

**Comment by vittico** [comment]
Thanks you! I was missing asn1 and sox packages,
