### ISSUE TITLE
Ejabberd install script allows passwords with ';' in them, even though it cannot parse them properly.

### ISSUE THREAD

**Issue by markehammons** [processone/ejabberd#599]
I installed my server with a password with ; in it, and the post install gave an error about a failed command that contained the last half of my password in it.

**Comment by cromain** [comment]
this will be fixed in next installer, arguments passed to postinstall were not quoted.

**Comment by markehammons** [comment]
Please note this issue is present with ejabberctl too when registering users.

**Comment by cromain** [comment]
yes i noticed this and it should be fixed for 15.06
