### ISSUE TITLE
Crash after installation on raspi 2 running raspbian

### ISSUE THREAD

**Issue by charliemaiors** [processone/ejabberd#600]
I've tried to install ejabberd on my raspi 2 running raspbian just giving the simple
sudo apt-get install ejabberd but after installation the server won't start, here is the crash dump:

=erl_crash_dump:0.1
Thu Jan  1 04:21:22 1970
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
System version: Erlang R15B01 (erts-5.9.1) [source] [smp:4:4] [async-threads:0] [kernel-poll:false]
Compiled: Sat Apr 26 16:47:24 2014
Taints:
Atoms: 4085
=memory
total: 2837720
processes: 292409
processes_used: 292354
system: 2545311
atom: 94821
atom_used: 68070
binary: 148016
code: 1101606
ets: 29532
=hash_table:atom_tab
size: 3203
used: 2304
objs: 4085
depth: 6
=index_table:atom_tab
size: 4096
limit: 1048576
entries: 4085
=hash_table:module_code
size: 47
used: 30
objs: 44
depth: 3
=index_table:module_code
size: 1024
limit: 65536
entries: 44
=hash_table:export_list
size: 3203
used: 1471
objs: 1977
depth: 6
=index_table:export_list
size: 2048
limit: 524288
entries: 1977
=hash_table:secondary_export_table
size: 97
used: 0
objs: 0
depth: 0
=hash_table:process_reg
size: 11
used: 3
objs: 4
depth: 2
=hash_table:fun_table
size: 197
used: 137
objs: 247
depth: 5
=hash_table:node_table
size: 11
used: 1
objs: 1
depth: 1
=hash_table:dist_table
size: 11
used: 1
objs: 1
depth: 1
=allocated_areas
sys_misc: 59220
static: 499712
atom_space: 65544 38793
atom_table: 29277
module_table: 4368
export_table: 21088
export_list: 94896
register_table: 108
fun_table: 850
module_refs: 1024
loaded_code: 979380
dist_table: 311
node_table: 131
bits_bufs_size: 0
bif_timer: 40028
link_lh: 0
process_table: 131072
ets_misc: 24972
=allocator:sys_alloc
option e: true
option m: libc
option tt: 131072
option tp: 0
=allocator:sbmbc_alloc
option e: false
=allocator:temp_alloc[0]
versions: 2.1 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 10
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option mbsd: 3
option as: gf
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 180 180
mbcs blocks size: 0 28600 28600
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131104 131104 131104
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131104
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 8981
temp_free calls: 8981
temp_realloc calls: 2
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[1]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 10
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option as: af
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 1 1
mbcs blocks size: 0 16 16
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131104 131104 131104
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131104
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 1
temp_free calls: 1
temp_realloc calls: 0
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[2]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 10
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option as: af
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 264 264
mbcs blocks size: 0 65544 65544
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131104 131104 131104
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131104
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 36343
temp_free calls: 36343
temp_realloc calls: 4
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[3]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 10
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option as: af
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 1 1
mbcs blocks size: 0 16 16
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131104 131104 131104
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131104
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 1
temp_free calls: 1
temp_realloc calls: 0
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:temp_alloc[4]
versions: 0.9 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 90
option rsbcmt: 80
option rmbcmt: 100
option mmbcs: 131072
option mmsbc: 256
option mmmbc: 10
option lmbcs: 10485760
option smbcs: 1048576
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option as: af
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 1 1
mbcs blocks size: 0 16 16
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 131104 131104 131104
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 131104
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
temp_alloc calls: 1
temp_free calls: 1
temp_realloc calls: 0
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:sl_alloc[0]
versions: 2.1 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 80
option rsbcmt: 80
option rmbcmt: 50
option mmbcs: 32768
option mmsbc: 256
option mmmbc: 3
option lmbcs: 5242880
option smbcs: 262144
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option mbsd: 3
option as: gf
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 0 0
mbcs blocks size: 0 0 0
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 32792 32792 32792
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 32792
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
sl_alloc calls: 0
sl_free calls: 0
sl_realloc calls: 0
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:sl_alloc[1]
versions: 2.1 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 80
option rsbcmt: 80
option rmbcmt: 50
option mmbcs: 32768
option mmsbc: 256
option mmmbc: 3
option lmbcs: 5242880
option smbcs: 262144
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option mbsd: 3
option as: gf
sbmbcs blocks: 0 0 0
sbmbcs blocks size: 0 0 0
sbmbcs carriers: 0 0 0
sbmbcs carriers size: 0 0 0
mbcs blocks: 0 0 0
mbcs blocks size: 0 0 0
mbcs carriers: 1 1 1
mbcs mseg carriers: 0
mbcs sys_alloc carriers: 1
mbcs carriers size: 32792 32792 32792
mbcs mseg carriers size: 0
mbcs sys_alloc carriers size: 32792
sbcs blocks: 0 0 0
sbcs blocks size: 0 0 0
sbcs carriers: 0 0 0
sbcs mseg carriers: 0
sbcs sys_alloc carriers: 0
sbcs carriers size: 0 0 0
sbcs mseg carriers size: 0
sbcs sys_alloc carriers size: 0
sl_alloc calls: 0
sl_free calls: 0
sl_realloc calls: 0
sbmbc_alloc calls: 0
sbmbc_free calls: 0
mseg_alloc calls: 0
mseg_dealloc calls: 0
mseg_realloc calls: 0
sys_alloc calls: 1
sys_free calls: 0
sys_realloc calls: 0
=allocator:sl_alloc[2]
versions: 2.1 3.0
option e: true
option t: 5
option ramv: false
option sbct: 524288
option asbcst: 4145152
option rsbcst: 80
option rsbcmt: 80
option rmbcmt: 50
option mmbcs: 32768
option mmsbc: 256
option mmmbc: 3
option lmbcs: 5242880
option smbcs: 262144
option mbcgs: 10
option sbmbcs: 0
option sbmbct: 0
option mbsd: 3
option as: gf
...

**Comment by badlop** [comment]
Ohh, that dump gives no clue to me, and I'm unable to reproduce your setup to try it.

In other cases, the dump's Slogan offers some clue looking at this list of common errors: https://www.ejabberd.im/common-errors

**Comment by cromain** [comment]
there is either something missing (otp dependencies?) or broken. nothing in ejabberd logs ?
moreover, depending on version of ejabberd you want to run, raspbian's erlang R15 may be too old.
you'd better try our arm7hf installer which includes erlang 17 and latest ejabberd here: https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/15.04/ejabberd-15.04-linux-armhf-installer.run
