### ISSUE TITLE
File transfer fails

### ISSUE THREAD

**Issue by aserrr** [processone/ejabberd#602]
Hi, I have a problem with file transfer (ejabberd on AmazonAWS) through mod_proxy65 in case when both clients are in different sub-networks. But it works fine when both are in the same wi-fi.

mod_disco: []
mod_proxy65: []

Also tried to setup a valid host for proxy manually and 0.0.0.0 IP address

**Comment by HB-Dimple** [comment]
Any update on this ?

**Comment by licaon-kter** [comment]
@HB-Dimple State your setup. OS, version, clients tested and paste your config on https://gist.github.com

**Comment by HB-Dimple** [comment]
OS: Linux
Version 19.02
Clients: iOS 
Config: 

https://gist.github.com/HB-Dimple/fbc56aabee0ecaf6da81971240073a7c

**Comment by licaon-kter** [comment]
@HB-Dimple ChatSecure or Monal or Beagle?

Tried Conversations or Gajim too?

Why do you need the proxy exactly?

**Comment by HB-Dimple** [comment]
XMPPFramework. 
It works if I use on same network, but it don't work when I use different network. I am using mod_proxy65 for file transfers.

**Comment by zinid** [comment]
Have you read the documentation? https://docs.ejabberd.im/admin/configuration/#mod-proxy65
Sounds like NAT/firewall problem to me.

**Comment by licaon-kter** [comment]
@HB-Dimple before making your own client do test with an existing one

**Comment by HB-Dimple** [comment]
I checked in Adium, it worked. However, I had to change firewall for the same. Unfortunately I now need to check why it is not working in my own client.
