### ISSUE TITLE
PubSub: /home node created even with hometree plugin disabled

### ISSUE THREAD

**Issue by weiss** [processone/ejabberd#609]
Since commit e0563e3918984d151fbea45a5f6fc8255913726d, the `/home` and `/home/$domain` nodes are auto-created during startup even if `node_hometree` is not enabled in the configuration.  This happens because `node_hometree:init/3` (which [creates the nodes][1]) is also [called by other `node_*` plugins][2].

With the current code, the `mod_pubsub:create_node/5` calls could simply be removed from `node_hometree:init/3`, because `mod_pubsub` also has [calls to auto-create those nodes][3], and those are only executed if the `hometree` plugin is actually enabled.  But I guess the idea might've been to remove those calls from `mod_pubsub`?

[1]: https://github.com/processone/ejabberd/blob/fc0754c609cfecf567a712602c94716fbacc5712/src/node_hometree.erl#L78
[2]: https://github.com/processone/ejabberd/blob/fc0754c609cfecf567a712602c94716fbacc5712/src/node_pep.erl#L52
[3]: https://github.com/processone/ejabberd/blob/fc0754c609cfecf567a712602c94716fbacc5712/src/mod_pubsub.erl#L391

**Comment by cromain** [comment]
yes, the idea was to remove such calls from mod_pubsub.
I think i'll remove from mod_pubsub anyway and move all default plugin code in mod_flat instead of node_hometree, so node_hometree:init will call node_flat:init and then create the two root nodes.

**Comment by weiss** [comment]
> I think i'll remove from mod_pubsub anyway and move all default plugin code in mod_flat instead of node_hometree, so node_hometree:init will call node_flat:init and then create the two root nodes.

Sounds good.  Thanks!

**Comment by cromain** [comment]
hometree init done only if related plugin is configured
