### ISSUE TITLE
Roster is lower cased

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd#610]
Rosters provided through ejabberd have the node part lower cased even thou I know that the query that generated it provided mixed casing.

Since we show the received list to the user it would be nice if the original casing would be preserved. Otherwise we will have to make another lookup for each received item which will be wasteful.

This could be configurable so that the default behaviour is the current one.

**Comment by zinid** [comment]
In order to do this we need to add additional fields in all databases and perform data conversion on the first run to update it. That's pretty much of work. I don't know if any of the developers are motivated that much because I treat this feature as not very important.
