### ISSUE TITLE
ejabberdctl join_cluster doesn't respect --node option

### ISSUE THREAD

**Issue by szymonpk** [processone/ejabberd#612]
- ejabberd 15.04 (compiled from source with --enable-user=ejabberd --enable-tools --enable-pgsql --enable-zlib --enable-nif --enable-iconv --enable-elixir)
- ubuntu 14.04

This time I've looked if there is no known fix in master. I'm trying:
```
root@xmpp2:~# ejabberdctl join_cluster 'ejabberd@xmpp1.<domain>' --node 'ejabberd@xmpp2.<domain>'
```
In result I'm getting:
```
...
Remote node name is ejabberd@xmpp1.<domain>
Local node name is ejabberd@localhost
...
```

`ERLANG_NODE="xmpp2.<domain>"` command... and `export ERLANG_NODE="xmpp2.<domain>"` are ignored too. Only option to get this working is editing `/sbin/ejabberdctl`.

**Comment by cromain** [comment]
you should try
ejabberdctl --node 'ejabberd@xmpp2.<domain>' join_cluster 'ejabberd@xmpp1.<domain>'

**Comment by szymonpk** [comment]
Same thing.

**Comment by cromain** [comment]
joincluster takes ERLANG_NODE from ejabberdctl.cfg by evaluating standard execution of ejabberctl.
you can not define local node name as you want to do.

to enable cluster
1/ you must have local ejabberdctl.cfg correctly defined
2/ then you call joincluster script or ejabberdctl join_cluster command.
