### ISSUE TITLE
15.06 import mysql.sql

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#614]
Using mysql 5.5.43 to import the file mysql.sql gives me the following error:

Error
consulta SQL:
CREATE FULLTEXT INDEX i_text ON archive(
txt
);
MySQL ha dicho: Documentación
#1214 - The used table type doesn't support FULLTEXT indexes

**Comment by jsautret** [comment]
FULLTEXT indexes are supported by InnoDB engine in MySQL 5.6 and up. You should upgrade to a more recent version of MySQL (or you can try to change the engine of the 'archive' table to MyISAM at your own risk).

**Comment by suchatorg** [comment]
I solved by adding the following line:
ALTER TABLE archive ENGINE = MYISAM;
