### ISSUE TITLE
Native Mysql on ejabberd 15.04

### ISSUE THREAD

**Issue by dragondark** [processone/ejabberd#617]
Hi,
I would like to ask,
I am newbie in this,
I have create ejabberd database through mysql and import the ejabberd database, add ejabberd user on mysql,
I have followed everything from website and I have do the configuration through the ejabberd.yml,
 this is my configuration

auth_method: internal
auth_method: odbc

odbc_type: mysql
odbc_server: "127.0.0.1"
odbc_database: "ejabberd"
odbc_username: "ejabberd"
odbc_password: "mdn"
modules:
  mod_offline: 
    db_type: odbc
    .....
  mod_pubsub: 
    db_type: odbc
    ......
    so on

my odbc.ini

[ejabberd]
Driver		= MySQL
DATABASE	= ejabberd
PWD		= ejabberd
SERVER		= 127.0.0.1
SOCKET		= /var/run/mysqld/mysqld.sock
UID		= ejabberd

the problem when i just auth only odbc ejabberd error log 
2015-06-26 08:57:24.003 [warning] <0.609.0>@ejabberd_web_admin:process:238 Access of <<"admin@technopark">> from <<"127.0.0.1">> failed with error: <<"inexistent-account">>
and I try to uncomment auth internal, I can enter the ejabberd server, but data aren't store in mysql database.

are there something missing in my configuration?
Thank You Very Much
I appreciate your help

**Comment by aleczadikian** [comment]
Did you runt he mysql.sql file on your MySQL database?

**Comment by dragondark** [comment]
yes, off course, i have import the ejabberd database into my database with an ejabberd account,

**Comment by badlop** [comment]
If you have this in your ejabberd.yml
```
hosts:
  - "example.com"
```
and you can login with a Jabber client using the user joe@example.com, then you must also be able to login to ejabberd's WebAdmin using the user joe@example.com and the same password.
