### ISSUE TITLE
External SCRAM Authentication

### ISSUE THREAD

**Issue by aleczadikian** [processone/ejabberd#619]
Looking at the code, I see that SCRAM authentication is only supported by internal and ODBC auth methods. The documentation doesn't say this anywhere, which is a problem in itself. Also, any plans to add SCRAM support to external auth?

**Comment by mremond** [comment]
We have no plan to add SCRAM to external auth. external auth is supposed to be use for small domains and is somewhat a hack. The way to go is almost always native Erlang auth. I think it is not worth the effort, but if you want to submit a pull request, we will consider it.
That said, we will also make sure the scope of SCRAM is clearer in the documentation.
Thanks !

**Comment by aleczadikian** [comment]
Thanks for the reply. I'll look into using native authentication then.

**Comment by mremond** [comment]
Good. If you can, yes, that's the best option.
