### ISSUE TITLE
elixir embedding issues lately

### ISSUE THREAD

**Issue by knewter** [processone/ejabberd#621]
I cannot embed ejabberd successfully in an elixir app lately.  It worked in tag "b67af5e036e359f6cfc877c2617d9b3c3d877c89" but master has been broken for a little bit.  I didn't report it earlier because I thought it was likely just a random failure, but since 15.06 release just happened I'm assuming it is an actual issue.

This repo outlines the issues and makes it easy to reproduce the problem.

https://github.com/knewter/ejabberd_embed

I'm pasting the README here so the issues are easy to track and find in this github issue if someone searches for them:

---

EjabberdEmbed
=============

This is a repo to reproduce some issues I have with ejabberd lately as it
relates to embedding in an elixir application.

First off, if you clone this repo and just `mix deps.get; mix test` you'll run
into an issue as some of the dependencies reference http for their git
dependencies, and some reference git.  Mix doesn't know these are the same, so
you have to override.  You get the following error:

```
[jadams:~/elixir/ejabberd_embed] 1m31s $ mix test
Unchecked dependencies for environment test:
* p1_utils (https://github.com/processone/p1_utils)
  the dependency p1_utils in deps/ejabberd/rebar.config is overriding a child dependency:

  > In deps/ejabberd/rebar.config:
    {:p1_utils, ~r/.*/, [git: "https://github.com/processone/p1_utils"]}

  > In deps/p1_cache_tab/rebar.config:
    {:p1_utils, ~r/.*/, [git: "git://github.com/processone/p1_utils.git"]}

  Ensure they match or specify one of the above in your EjabberdEmbed.Mixfile deps and set `override: true`
* p1_tls (https://github.com/processone/tls)
  the dependency p1_tls in deps/ejabberd/rebar.config is overriding a child dependency:

  > In deps/ejabberd/rebar.config:
    {:p1_tls, ~r/.*/, [git: "https://github.com/processone/tls"]}

  > In deps/esip/rebar.config:
    {:p1_tls, ~r/.*/, [git: "git://github.com/processone/tls.git"]}

  Ensure they match or specify one of the above in your EjabberdEmbed.Mixfile deps and set `override: true`
* p1_stun (https://github.com/processone/stun)
  the dependency p1_stun in deps/ejabberd/rebar.config is overriding a child dependency:

  > In deps/ejabberd/rebar.config:
    {:p1_stun, ~r/.*/, [git: "https://github.com/processone/stun"]}

  > In deps/esip/rebar.config:
    {:p1_stun, ~r/.*/, [git: "git://github.com/processone/stun.git"]}

  Ensure they match or specify one of the above in your EjabberdEmbed.Mixfile deps and set `override: true`
** (Mix) Can't continue due to errors on dependencies
```

If you then add the needed overrides:

```elixir
  defp deps do
    [
      {:ejabberd, github: "processone/ejabberd"},
      {:p1_utils, github: "processone/p1_utils", override: true},
      {:p1_tls, github: "processone/tls", override: true},
      {:p1_stun, github: "processone/stun", override: true}
    ]
  end
```

...then try to run the tests, it will fail with no ejabberd.app:

```
[jadams:~/elixir/ejabberd_embed] 24s $ mix test
==> rel (compile)
==> ejabberd (compile)
Unchecked dependencies for environment test:
* ejabberd (git://github.com/processone/ejabberd.git)
  could not find an app file at _build/test/lib/ejabberd/ebin/ejabberd.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

**Comment by mremond** [comment]
Thanks for detailed report. I think the first step is to get rid of the override by having a more consistent way to pass Github URL. We should always use https and not git. I will first fix this issue.

**Comment by mremond** [comment]
It seems better now after making URL schemes in rebar.config more consistent across dependencies.
Could you please give it another try ?

I have an issue compiling phoenix_ecto here, but at least ejabberd is properly installed and built.

**Comment by knewter** [comment]
I updated the sample repo and removed the overrides.  I still get the error re: ejabberd.app.  Can you pull it down and run `mix deps.get; mix test` and see if you have the same error?

**Comment by mremond** [comment]
What is `mix test` supposed to do ? Why don't you run `mix compile` before ?

**Comment by mremond** [comment]
And also note that you need to force redownload the deps repositories that changed. You can rename deps dir in case of doubt to force redownload.

**Comment by knewter** [comment]
I removed the deps and _build directories as I always do if I worry about
dependency funkiness.  mix test just compiles and runs the tests.  It
failed to compile with the error outlined above - here's the latest run:

```
θ65° [jadams:~/elixir/ejabberd_embed] master ± mix compile
==> p1_utils (compile)
==> p1_cache_tab (compile)
==> p1_yaml (compile)
==> ehyperloglog (compile)
==> p1_stringprep (compile)
==> p1_tls (compile)
==> p1_stun (compile)
==> esip (compile)
==> p1_xml (compile)
==> rel (compile)
==> ejabberd (compile)
Unchecked dependencies for environment dev:
* ejabberd (git://github.com/processone/ejabberd.git)
  could not find an app file at _build/dev/lib/ejabberd/ebin/ejabberd.app.
This may happen if the dependency was not yet compiled, or you specified
the wrong application name in your deps, or the dependency indeed has no
app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies

```

On Mon, Jun 29, 2015 at 8:55 AM, Mickaël Rémond <notifications@github.com>
wrote:

> And also note that you need to force redownload the deps repositories that
> changed. You can rename deps dir in case of doubt to force redownload.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/621#issuecomment-116668681>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by mremond** [comment]
I do not have this issue. Which version of mix are you using ?

**Comment by knewter** [comment]
1.0.4

On Mon, Jun 29, 2015 at 10:59 AM, Mickaël Rémond <notifications@github.com>
wrote:

> I do not have this issue. Which version of mix are you using ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/621#issuecomment-116741613>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by mremond** [comment]
I did not see the issue as I was pointing to an older tag.
I found the issue however. It is caused by this commit:
https://github.com/processone/ejabberd/commit/6cba7bf83459be24e384e016c017c639ecc8226c

Basically, mix.exs was removed expecting generation by configure script. However, mix tools does not run configure and mix.exs is not generated and the project is not built.

**Comment by mremond** [comment]
I think with HEAD of master, you should not have any problem anymore.

**Comment by knewter** [comment]
confirmed, that fixed it.  Thanks!

On Mon, Jun 29, 2015 at 4:37 PM, Mickaël Rémond <notifications@github.com>
wrote:

> I think with HEAD of master, you should not have any problem anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/621#issuecomment-116854172>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by nrako** [comment]
I can confirm that fixed the issue thanks. But as a beginner in erlang/elixir/mix this kind of issue gives me a hard time and a bitter DX. Practices makes perfect, but since the issue was already fixed in master I would have expected a patch release.

Right now my ejabberd deps look like this:
```elixir
     # pending issue on 15.06 tag https://github.com/processone/ejabberd/issues/621 need to use unreleased sha
     #{:ejabberd, github: "processone/ejabberd", tag: "15.06"}
     {:ejabberd, github: "processone/ejabberd", ref: "0474804d4baa6449d498e5403d1ac450245bcd55"}
```

But I really wish it looked more like this:
```elixir
     {:ejabberd, "~> 15.06.1"}
```
@mremond are you considering following semver with what that may involves?  And what about hex.pm support? Over there ejabberd is stuck on  [15.03](https://hex.pm/packages/ejabberd).

**Comment by mremond** [comment]
We expect to release a 15.07 version. The problem as you mention is not blocking, especially as Elixir support is bleeding you can always use HEAD.

Regarding mix, we were not involved in making the 15.03 version. No idea who did this.

**Comment by nrako** [comment]
I understand, by the way :+1: on Elixir support! That really ease a bit the learning curve...

Running HEAD now since I'm still learning I guess I can live dangerously.

I also tried to find the owner info on hex.pm or via various mix hex commands but nothing... I'll investigate a bit more.

**Comment by mremond** [comment]
Thanks, please let us know about your finding about mix.hex.
