### ISSUE TITLE
Ejabberd 16.05 startup and post install script issue with macos 10.7.5

### ISSUE THREAD

**Issue by kartikpatel11** [processone/ejabberd#622]
I am trying to start ejabber 16.05 server on mac os 10.7.5. while starting up, it gives error. on further investigation, I found that "erl" executor file shipped with ejabber is throwing "Segmentation Fault:11" while running independently. I firmly believe that resolving issue with "erl" file execution will solve server start up issue. can anyone please help. Below is the code from "erl" that is causing segmentation fault error

#!/bin/sh
ROOTDIR=/Applications/ejabberd-15.06

export ROOTDIR

BINDIR=$ROOTDIR/bin

export BINDIR

EMU=beam

export EMU

PROGNAME=$BINDIR/erl

export PROGNAME

PATH=$BINDIR:$PATH

export PATH

arch() {

case `uname -m` in

i[3456]86 ) echo x86 ;;

i86pc) echo x86 ;;

armv7*) echo armhf ;;

arm*l) echo armel ;;

* ) echo `uname -m | tr A-Z a-z` ;;

esac
}

os=uname -s | tr A-Z a-z

cpu=arch

ARCHDIR=${os}-${cpu}

export ARCHDIR

Dynamic libraries

LD_LIBRARY_PATH=$ROOTDIR/lib/$ARCHDIR

export LD_LIBRARY_PATH

DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH

export DYLD_LIBRARY_PATH

exec $BINDIR/erlexec ${1+"$@"}

**Comment by mremond** [comment]
Thanks for the report.

I noticed that you are using OSX 10.7. We do not test ejabberd binary installer on version of OS that are so old.
Unfortunately, I do not even expect the binary installer to run on such an old release.

If you have to run ejabberd on that OSX version, you have to build it from source.
ejabberd source are available on official ejabberd Github.

Documentation for installation and build is here: http://docs.ejabberd.im/admin/guide/installation/#installing-ejabberd-from-source-code
