### ISSUE TITLE
Send notifications when MUC configuration is changed

### ISSUE THREAD

**Issue by weiss** [processone/ejabberd#623]
XEP-0045 [says][1]:

> A room MUST send notification to all occupants when the room configuration changes in a way that has an impact on the privacy or security profile of the room. This notification shall consist of a `<message/>` stanza containing an `<x/>` element qualified by the `'http://jabber.org/protocol/muc#user'` namespace, which shall contain only a `<status/>` element with an appropriate value for the `'code'` attribute. [...] For any other configuration change, the room SHOULD send status code 104 so that interested occupants can retrieve the updated room configuration if desired.

Currently, `mod_muc_room` generates no such notifications.

[1]: http://xmpp.org/extensions/xep-0045.html#roomconfig-notify

**Comment by mremond** [comment]
:+1: Good catch, @weiss
