### ISSUE TITLE
MySQL complains table type doesn't support FULLTEXT indexes

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#624]
Since commit 83cce468a573d3ca58a0c6653a2ccc17c7b4dbc3 that added mod_mam and SQL table definitions, Travis CI complains (see https://travis-ci.org/processone/ejabberd/builds/67842922) with this error:
```
failed: {test_case_failed,
            {failed_to_create_sql_tables,mysql,
                {aborted,
                    "#HY000The used table type doesn't support FULLTEXT indexes"}}},
[{ejabberd_SUITE, init_per_group, 54},
 {test_server, ts_tc, 1415},
 {test_server, run_test_case_eval1, 1092},
 {test_server, run_test_case_eval, 976}]
```

Apparently it doesn't like those lines in sql/mysql.sql:
```
CREATE TABLE archive (
    username varchar(250) NOT NULL,
    timestamp BIGINT UNSIGNED NOT NULL,
    peer varchar(250) NOT NULL,
    bare_peer varchar(250) NOT NULL,
    xml text NOT NULL,
    txt text,
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARACTER SET utf8;

CREATE FULLTEXT INDEX i_text ON archive(txt);
CREATE INDEX i_username USING BTREE ON archive(username);
CREATE INDEX i_timestamp USING BTREE ON archive(timestamp);
CREATE INDEX i_peer USING BTREE ON archive(peer);
CREATE INDEX i_bare_peer USING BTREE ON archive(bare_peer);
```

I wonder what should be done here: change the table definition, require another MySQL version, forget the complain... ?

**Comment by zinid** [comment]
Update the mysql version should help

**Comment by badlop** [comment]
Aha, InnoDB engine supports FULLTEXT indexes only since MySQL 5.6.
http://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html

And before that version, only MyISAM engine supported full text search.

Travis only provides a specific MySQL server version
http://docs.travis-ci.com/user/database-setup/#MySQL

Solutions I can think:
* Simply wait Travis to update MySQL to 5.6
* In .travis.yml, add a line to update mysql server, maybe 5.6 is available
* Switch the Archive table to MyISAM

**Comment by mremond** [comment]
MySQL 5.6 should be coming soon on Travis CI, but it seems they are having issues with the update:
http://blog.travis-ci.com/2015-05-29-this-week-in-travis-ci/
