### ISSUE TITLE
Writing Elixir modules

### ISSUE THREAD

**Issue by dapriett** [processone/ejabberd#625]
Hello,

I'm new to both writing modules for Ejabberd as well as Elixir (and erlang).  I'm trying to follow the blog post here: https://blog.process-one.net/elixir-sips-ejabberd-with-elixir-part-1/

I'm using the Mac OSX installer of ejabberd (https://www.process-one.net/en/ejabberd/downloads/) - how would I add a custom Elixir module into it?  Do I just create a .ex Elixir module and dump it into the lib directory?  Is there some sort of compilation I have to do first?  Do you have a sample Elixir module project out there?

Thanks, and sorry for the newbie questions.

**Comment by mremond** [comment]
Well, if you want to develop on Elixir with ejabberd, basically, the blog post shows that you need a development environment, source code, etc.
We never tried yet developing Elixir module from the binary installer. It is intended to be a small, ready to use package for users, not for developers. Probably you will be missing development tool.

My recommendation is thus to install Erlang, Elixir on your machine and to build ejabberd from source. At the moment, that's the best approach.

I will keep the ticket open to see if we can test the build chain for Elixir and see if we can make it work.

**Comment by dapriett** [comment]
Ok thanks. 

I tried copying my elixir project to my ~/.ejabberd-modules/sources.  I had to create a .spec file to make it see it, and I was able to do module_install but it looks like the install creates an empty ebin directory.  So guessing the build chain doesn't support it yet.

**Comment by mremond** [comment]
Yes the module installer does not yet support Elixir module.

**Comment by nrako** [comment]
I'd love to see support of Elixir module by the module installer. Or else some guide to compile a Elixir module for ejabberd independently `elixirc -o ebin -I ....` without having to rely on the main ejabberd build would also help people like me who are new to this env.

**Comment by KadekM** [comment]
+1 on support from module installer :)

**Comment by sebyx07** [comment]
also a better documentation on behaviours and other basic stuff you can do from erlang/elixir would be great

**Comment by cromain** [comment]
Feature added by #1193 thanks to Gabriel
