### ISSUE TITLE
Setting up https with http-bind

### ISSUE THREAD

**Issue by Hexatise** [processone/ejabberd#635]
Hello

I have HSTS setup on my domain that forces https across the domain. Im having issues trying to load the http bosh url in my website as it breaks the https certificates. So i have been looking into how to make the ejabberd bosh manager work in https 

So right now here is my config files :

  {5222, ejabberd_c2s, [
                        {access, c2s},
                        {shaper, c2s_shaper},
                        {max_stanza_size, 65536},
                        %%zlib,
                        starttls, {certfile, "/etc/ejabberd/ejabberd.pem"}
]},

  {5280, ejabberd_http, [
                         tls,
                         {certfile, "/etc/ejabberd/ejabberd.pem"}
                         http_bind,
                         http_poll,
                         web_admin
                        ]}
 ]}.

This is not wokring, so if i visit the url 

https://example.com:5280/http-bind

I get a error : ERR_CONNECTION_REFUSED

it used to work before i added the tls and certfile stuff.

I really need this fixed, also for the certificates, am i meant to use the .pem file for my domain ssl or do i use the one i was given with ejabberd?

**Comment by badlop** [comment]
In your example you lack a comma at the end of the certfile line. After you fix that, the options you set should work correctly as you expect.

In ejabberd 15.06, I set equivalent options:
```
listen:
  - 
    port: 5280
    module: ejabberd_http
    certfile: "/etc/ejabberd/server.pem"
    tls: true 
    http_bind: true
```
Then in a web browser I can visit https://localhost:5280/http-bind/ and see an informative page

If you are using an old ejabberd version, maybe you are seeing an old bug that is already fixed.

**Comment by Hexatise** [comment]
Ahh okay this fixed my problem :)
