### ISSUE TITLE
[Development setup] How to import the project source into common IDEs

### ISSUE THREAD

**Issue by ilike69** [processone/ejabberd#636]
Dear folks,
As far as i know Eclipse and IntellJ support Erlang, how to import current source base into the IDEs ? What is the best IDE for Ejabberd development ?. Is module development a seperated sub-project (not related to the main Ejabberd project) ?

**Comment by zinid** [comment]
The main development is being done in Emacs.
Regarding modules: there is a contribution project [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) which is community driven.

**Comment by mremond** [comment]
Some people also use vim, but basically, I am not sure there is a good "IDE" approach to develop in Erlang.

Note also that we have a special Github project to help you set your Linux environment for development and testing:
https://github.com/processone/ejabberd-vagrant-dev
