### ISSUE TITLE
set_vcard2_multi cannot work

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#637]
The arg type of the command `{content, {list, binary}}` is invalid:

See this line: https://github.com/processone/ejabberd/blob/master/src/mod_admin_extra.erl#L303

It means the command cannot work as the triggered function expect [binary()].

**Comment by badlop** [comment]
Dou you mean that instead of
> {contents, {list, binary}}

it should say this?
> {contents, {list, {content, binary}}}

**Comment by mremond** [comment]
Yes, I do not know if it will work, but at least, it seems more correct.

**Comment by badlop** [comment]
The current code works correctly with a Python query like this:
```
import xmlrpclib

server_url = 'http://127.0.0.1:4560';
server = xmlrpclib.Server(server_url);

contents = ['aaa', 'bbb', 'ccc']

params = {}
params["user"] = "user1"
params["host"] = "localhost"
params["name"] = "N"
params["subname"] = "MIDDLE"
params["contents"] = contents

result = server.set_vcard2_multi(params)
print result
```

**Comment by mremond** [comment]
ok, strange, because it makes dialiyzer unhappy as `{contents, {list, binary}}` seems unexpected.
