### ISSUE TITLE
Webadmin guide

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#638]
After update from ejabberd 15.04 to 15.06 I have problem with webadmin guide, shows an error
`
Not found /usr/share/doc/ejabberd/guide.html - Try to specify the path to ejabberd documentation with the environment variable EJABBERD_DOC_PATH. Check the ejabberd Guide for more information.
`

**Comment by cromain** [comment]
I guess you're installing from official sources tarball. at install, ejabberdctl should set doc dir to /usr/share/doc/ejabberd/
did you checked guide.html is installed there ?
else, how did you installed ejabberd ?

**Comment by beherit** [comment]
I installed ejabberd directly from sources, run file and package - everywhere is this same problem.

**Comment by badlop** [comment]
Well, from what I see, ejabberd-15.06.tgz didn't include the guide.html so, the error shown makes sense. The next ejabberd release, when the guide.html isn't found, will redirect to the online version at http://docs.ejabberd.im/admin/guide/configuration/
