### ISSUE TITLE
Problem with installing modules

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#639]
After update from ejabberd 15.04 to 15.06 is not impossible to install modules that use xml.hrl. Example:
```
root@virtualbox:~# ejabberdctl module_install mod_restful
/usr/lib/ejabberd/include/jlib.hrl:23: can't find include file "xml.hrl"
/usr/lib/ejabberd/include/jlib.hrl:430: record xmlel undefined
/usr/lib/ejabberd/include/jlib.hrl:470: type xmlel() undefined
src/mod_restful_admin.erl:63: Warning: behaviour gen_restful_api undefined
src/mod_restful_mochijson2.erl:585: can't find include lib "eunit/include/eunit.hrl"
src/mod_restful_mochinum.erl:269: can't find include lib "eunit/include/eunit.hrl"
src/mod_restful_register.erl:32: Warning: behaviour gen_restful_api undefined
Error: {compilation_failed,"src/gen_restful_api.erl"}
```

**Comment by cromain** [comment]
i can not reproduce include error of xml.hrl on 15.06, ext_mod uses NO_EXT_LIB flag and so loads lib/ejabberd-15.06/include/xml.hrl correctly on build. 
but i get error on eunit cause it is not included in ejabberd package.
we need to check if it's worth including eunit as well.

**Comment by beherit** [comment]
@cromain uhm maybe it's problem with ejabberd package - I install ejabberd via unofficial repository (apt.jabber.at). I try to copy xml.hrl to /usr/lib/ejabberd/include/ but it doesn't work.

**Comment by cromain** [comment]
I confirm we don't get error if eunit is in the path. I added eunit to official ejabberd package.
