### ISSUE TITLE
Compile error in OTP/18, please add a ifdef to fixed

### ISSUE THREAD

**Issue by developerworks** [processone/ejabberd#640]
**type dict/0 is deprecated and will be removed in OTP 18.0**

```
git clone https://github.com/processone/ejabberd.git
./autogen
./configure --enable-odbc --enable-mysql --enable-iconv --enable-lager --enable-nif --enable-elixir --enable-json
```
All above commands is OK, except `make`, the following is my os distribution and error output:

```
root@storage:~/sources/ejabberd# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

```
root@storage:~/sources/ejabberd# make
/usr/lib/erlang/bin/escript rebar compile && :> deps/.built
==> p1_utils (compile)
==> p1_cache_tab (compile)
==> p1_tls (compile)
==> p1_stringprep (compile)
==> p1_xml (compile)
==> p1_stun (compile)
/root/sources/ejabberd/deps/p1_stun/src/stun_listener.erl:39: type dict() undefined
ERROR: compile failed while processing /root/sources/ejabberd/deps/p1_stun: rebar_abort
make: *** [deps/.built] Error 1
```

**Comment by mremond** [comment]
The fix was already made during the week. Can you please retry with up to date dependancies ?

**Comment by EugeneNews** [comment]
still getting this on Debian today...
/home/ejabberd/ejabberd/deps/p1_stun/src/turn.erl:69: type dict() undefined
...
ERROR: compile failed while processing /home/ejabberd/ejabberd/deps/p1_stun: rebar_abort
Makefile:87: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1

**Comment by mremond** [comment]
It should be fixed now. Could you please have another try ?
Thanks !

**Comment by EugeneNews** [comment]
problem solved.
but the same appeared in /deps/esip/src/esip_listener.erl:40: type dict() undefined
need separate issue?

**Comment by EugeneNews** [comment]
compiled. fixed. thnx
