### ISSUE TITLE
Installation Fails on OSX

### ISSUE THREAD

**Issue by xmppjingle** [processone/ejabberd#641]
After make succeed: 
...
Compiled src/ejabberd_c2s.erl
/usr/local/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
...

I execute:
$ sudo make install
Password:
/usr/local/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
#
# Configuration files
/usr/bin/install -c -d -m 750  //etc/ejabberd
[ -f //etc/ejabberd/ejabberd.yml ] \
		&& /usr/bin/install -c -b -m 640  ejabberd.yml.example //etc/ejabberd/ejabberd.yml-new \
		|| /usr/bin/install -c -b -m 640  ejabberd.yml.example //etc/ejabberd/ejabberd.yml
/usr/bin/sed -e "s*{{rootdir}}*/*" \
		-e "s*{{installuser}}**" \
		-e "s*{{bindir}}*//bin*" \
		-e "s*{{libdir}}*//lib*" \
		-e "s*{{sysconfdir}}*//etc*" \
		-e "s*{{localstatedir}}*//var*" \
		-e "s*{{docdir}}*//share/doc/ejabberd*" \
		-e "s*{{erl}}*/usr/local/bin/erl*" ejabberdctl.template \
		> ejabberdctl.example
[ -f //etc/ejabberd/ejabberdctl.cfg ] \
		&& /usr/bin/install -c -b -m 640  ejabberdctl.cfg.example //etc/ejabberd/ejabberdctl.cfg-new \
		|| /usr/bin/install -c -b -m 640  ejabberdctl.cfg.example //etc/ejabberd/ejabberdctl.cfg
/usr/bin/install -c -b -m 644  inetrc //etc/ejabberd/inetrc
#
# Administration script
[ -d //sbin ] || /usr/bin/install -c -d -m 755 //sbin
/usr/bin/install -c -m 550  ejabberdctl.example //sbin/ejabberdctl
# Elixir binaries
[ -d //bin ] || /usr/bin/install -c -d -m 755 //bin
[ -f deps/elixir/bin/iex ] && /usr/bin/install -c -m 550  deps/elixir/bin/iex //bin/iex
make: [install] Error 1 (ignored)
[ -f deps/elixir/bin/elixir ] && /usr/bin/install -c -m 550  deps/elixir/bin/elixir //bin/elixir
make: [install] Error 1 (ignored)
[ -f deps/elixir/bin/mix ] && /usr/bin/install -c -m 550  deps/elixir/bin/mix //bin/mix
make: [install] Error 1 (ignored)
#
# Init script
/usr/bin/sed -e "s*@ctlscriptpath@*//sbin*" \
		-e "s*@installuser@*root*" ejabberd.init.template \
		> ejabberd.init
chmod 755 ejabberd.init
#
# Binary Erlang files
/usr/bin/install -c -d //lib/ejabberd/ebin
/usr/bin/install -c -m 644 ebin/*.app //lib/ejabberd/ebin
/usr/bin/install -c -m 644 ebin/*.beam //lib/ejabberd/ebin
/usr/bin/install -c -m 644 deps/*/ebin/*.app //lib/ejabberd/ebin
/usr/bin/install -c -m 644 deps/*/ebin/*.beam //lib/ejabberd/ebin
# Install Elixir and Elixir dependancies
/usr/bin/install -c -m 644 deps/*/lib/*/ebin/*.app //lib/ejabberd/ebin
install: deps/*/lib/*/ebin/*.app: No such file or directory
make: [install] Error 71 (ignored)
/usr/bin/install -c -m 644 deps/*/lib/*/ebin/*.beam //lib/ejabberd/ebin
install: deps/*/lib/*/ebin/*.beam: No such file or directory
make: [install] Error 71 (ignored)
rm -f //lib/ejabberd/ebin/configure.beam
#
# ejabberd header files
/usr/bin/install -c -d //lib/ejabberd/include
/usr/bin/install -c -m 644 include/*.hrl //lib/ejabberd/include
/usr/bin/install -c -m 644 deps/*/include/*.hrl //lib/ejabberd/include
#
# Binary C programs
/usr/bin/install -c -d //lib/ejabberd/priv/bin
/usr/bin/install -c -m 750  tools/captcha.sh //lib/ejabberd/priv/bin
/usr/bin/install -c -m 750  tools/joincluster //lib/ejabberd/priv/bin
/usr/bin/install -c -m 750  tools/leavecluster //lib/ejabberd/priv/bin
[ -f deps/p1_pam/priv/bin/epam ] \
		&& /usr/bin/install -c -m 750  deps/p1_pam/priv/bin/epam //lib/ejabberd/priv/bin
make: [install] Error 1 (ignored)
#
# Binary system libraries
/usr/bin/install -c -d //lib/ejabberd/priv/lib
/usr/bin/install -c -m 644 deps/esip/priv/esip_drv.so deps/p1_iconv/priv/lib/iconv.so deps/p1_stringprep/priv/lib/stringprep.so deps/p1_tls/priv/lib/p1_sha.so deps/p1_tls/priv/lib/p1_tls_drv.so deps/p1_xml/priv/lib/expat_erl.so deps/p1_xml/priv/lib/xml.so deps/p1_yaml/priv/lib/p1_yaml.so deps/p1_zlib/priv/lib/ezlib_drv.so //lib/ejabberd/priv/lib
[ -f //lib/ejabberd/priv/lib/jiffy.so ] && (cd //lib/ejabberd/priv; ln -s lib/jiffy.so; true)
make: [install] Error 1 (ignored)
[ -f //lib/ejabberd/priv/lib/sqlite3_drv.so ] && (cd //lib/ejabberd/priv; ln -s lib/sqlite3_drv.so; true)
make: [install] Error 1 (ignored)
#
# Translated strings
/usr/bin/install -c -d //lib/ejabberd/priv/msgs
/usr/bin/install -c -m 644 priv/msgs/*.msg //lib/ejabberd/priv/msgs
#
# Copy lite.sql
[ -d deps/sqlite3 ] && /usr/bin/install -c -d //lib/ejabberd/priv/sql
make: [install] Error 1 (ignored)
[ -d deps/sqlite3 ] && /usr/bin/install -c -m 644 sql/lite.sql //lib/ejabberd/priv/sql
make: [install] Error 1 (ignored)
#
# Spool directory
/usr/bin/install -c -d -m 750  //var/lib/ejabberd
echo -R  //var/lib/ejabberd >/dev/null
chmod -R 750 //var/lib/ejabberd
[ ! -f //var/lib/ejabberd/.erlang.cookie ] || { echo  //var/lib/ejabberd/.erlang.cookie >/dev/null ; chmod 400 //var/lib/ejabberd/.erlang.cookie ; }
#
# ejabberdctl lock directory
/usr/bin/install -c -d -m 750  //var/lock/ejabberdctl
echo -R  //var/lock/ejabberdctl >/dev/null
chmod -R 750 //var/lock/ejabberdctl
#
# Log directory
/usr/bin/install -c -d -m 750  //var/log/ejabberd
echo -R  //var/log/ejabberd >/dev/null
chmod -R 750 //var/log/ejabberd
#
# Documentation
/usr/bin/install -c -d //share/doc/ejabberd
[ -f doc/guide.html ] \
		&& /usr/bin/install -c -m 644 doc/guide.html //share/doc/ejabberd \
		|| echo "Documentation not included in sources"
Documentation not included in sources
/usr/bin/install -c -m 644 COPYING //share/doc/ejabberd

**Comment by cromain** [comment]
you more likely need to define installation directory when running configure
./configure --prefix=/usr/local
or
./configure --prefix=/usr/local/ejabberd-15.06

**Comment by xmppjingle** [comment]
Sorry. But the issue persists. I tried on OS X and also a fresh Ubuntu Server.

**Comment by mremond** [comment]
What is the issue exactly ?

From what I see the referred error are ignored (This is related to options that are disabled).

**Comment by cromain** [comment]
the is related to #468. 
actually make install can report some errors but this does not means installation failed. you can start ejabberd and see it running.
the make install procedure has to be improved to come with disabled features and overwriting files, and show this as warning instead of error.

**Comment by xmppjingle** [comment]
Indeed. Was a permission error. Install works even though reports some errors.
