### ISSUE TITLE
Can you tell me the different between f1_server and gen_server ? 

### ISSUE THREAD

**Issue by yuan2006open** [processone/ejabberd#643]
I have read ejabberd's code yet, I notice that,some mod's behavior is f1_server,such as mod_offline.
Can you tell me the different between f1_server and gen_server ? Why do that ?
Thank you!

**Comment by yuan2006open** [comment]
And also different between f1_fsm and gen_fsm.  
Thank you!

**Comment by weiss** [comment]
You mean `p1_server` and `p1_fsm`, and you can find a [list of differences][1] in the source code.

Next time, I'd suggest using the [mailing list][2] or the [forums][3] for support requests.

[1]: https://github.com/processone/p1_utils/blob/c771348ad2c76bb9e9f7075aaafc3bbde2895665/src/p1_fsm.erl#L20
[2]: http://lists.jabber.ru/mailman/listinfo/ejabberd
[3]: https://www.ejabberd.im/forum

**Comment by yuan2006open** [comment]
OK，Thank you!
