### ISSUE TITLE
ejabberd_http crash

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#646]
With our current configuration (full config is available [here](https://github.com/jabber-at/config)), we currently get `ejabberd_http` tracebacks:

```
2015-07-10 09:06:29 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.12712.6>
    registered_name: []
    exception error: {{badmatch,{error,ebadf}},[{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,430}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,289}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,205}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.376814>,<0.667.0>,#Port<0.279768>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 69598
  neighbours:
2015-07-10 09:06:29 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {badmatch,{error,ebadf}}
     Offender:   [{pid,<0.12712.6>},{name,undefined},{mfargs,{ejabberd_http,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

**Comment by prefiks** [comment]
Hello Mathias,

Could you give me more information about your setup? What OS and which erlang version is your server using? Do you get lot of those errors?

From what i see this is result of receiving system error when trying to get peer IP address from socket, and i am not sure how thats happens, probably socket was closed before this code was executed?

**Comment by mathiasertl** [comment]
Hello prefiks,

We use:

* Debian 8.1 Jessie
* Stock Debian Erlang (Debian version `1:17.3-dfsg-4`)
* Self-build packages (several other servers use them as well) of ejabberd 15.06 (see [here](https://github.com/jabber-at/ejabberd) for the github repo).
* Full ejabberd config: https://github.com/jabber-at/config

I hope I got everything? And yes, we're seeing a lot of those errors.

**Comment by badlop** [comment]
ebadf means "The file is not opened for reading." As Prefiks said, it may be the socket got closed before. Looking in the logs for previous lines that mention <0.12712.6> may give some clue.

**Comment by mathiasertl** [comment]
I've checked the log files and unfortunately there is nothing there. In the current most recent instance of this crash, there is nothing else in crash.log except another instance of the crash 40 minutes earlier. Here is the content of my ejabberd.log:

```
2015-07-13 20:51:43.856 [error] <0.20389.7> CRASH REPORT Process <0.20389.7> with 0 neighbours crashed with reason: no match of right hand value {error,ebadf} in ejabberd_http:process_request/1 line 430
2015-07-13 20:51:43.856 [error] <0.678.0> Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.20389.7> exit with reason {badmatch,{error,ebadf}} in context child_terminated
```

**Comment by c0d3runn3r** [comment]
We're seeing the same issue 

CRASH REPORT Process <0.28191.55> with 0 neighbours crashed with reason: no match of right hand value {error,ebadf} in ejabberd_http:process_request/1 line 430

running 15.06 installed from the processone installer on Debian 7.8

**Comment by ertdfgcb** [comment]
@c0d3runn3r - the SSL error is because they disabled SSLv3 for security reasons, see here:
https://github.com/processone/ejabberd/issues/679

**Comment by kishoreacesurf** [comment]
So what's the solution?

**Comment by weiss** [comment]
> So what's the solution?

The solution is to ignore the `ebadf` message.  I guess the code should be changed to catch that case in order to prevent the crash report.

**Comment by prefiks** [comment]
I added code that should catch this error in f89db30d7740b38ce942c2e05cb6a6f16fa0812a.
