### ISSUE TITLE
Stream management, ack received but still message not there on server.

### ISSUE THREAD

**Issue by amperesoft** [processone/ejabberd#648]
Hi, I am using the following:
Smack 4.1.2,
ejabberd 15.06
 
I have enabled Stream management.
On ejabberd server:
stream_management: true
resend_on_timeout: true
resume_timeout: 300
max_ack_queue: 1000
 
I have also used mod_mam in 15.06 and configured it to save message in mysql db.
mod_mam:
    iqdisc: one_queue
    db_type: odbc
    default: always

I also have mod_offline enabled.

Mostly it works fine but a few times when facing network issues on mobile, we do get an event for a message in addStanzaAcknowledgedListener : processPacket but neither the message is there in the db nor it is delivered to receiver. Are we missing something? It is really hard to reproduce.
 
This issue came on 4.1.0 of smack as well as ejabberd 14.12. With or without mod_mam.
 
Thanks!
Gaurav

**Comment by weiss** [comment]
> we do get an event for a message in addStanzaAcknowledgedListener : processPacket but neither the message is there in the db nor it is delivered to receiver

I don't use Smack, so I'm unsure I understood the situation.  Your Smack client sent a message to ejabberd, Smack says that ejabberd acknowledged it, but it doesn't show up e.g. in the MAM database?  Is the recipient on the same server?

Either way, it's hard to make any useful comment without seeing a stream dump of such a session, I'm afraid.

**Comment by mremond** [comment]
Closing as we need more info.
