### ISSUE TITLE
Storing duplicate message in chat table [PostgreSQL]

### ISSUE THREAD

**Issue by yashwanthbabu** [processone/ejabberd#649]
I am able to store the messages in the postgres database. But when i try to make the chat between two users, the messages are saving two times in my database. You can find the screenshot here

![screen shot 2015-07-10 at 3 46 12 pm](https://cloud.githubusercontent.com/assets/7446464/8617240/a02522c2-271f-11e5-9a32-35f0f7ec1b46.png)

In this screenshot, I am just sending two messages. From yashwanth to shabda (1 msg) and from shabda to yashwanth (1 msg). But saving the message two times in my database. I dont know where is the problem. Please help

**Comment by weiss** [comment]
> But when i try to make the chat between two users, the messages are saving two times in my database.

Each sent message and each received message is stored to the MAM database, so if both the sending and the receiving user are on the same server, you'll have two copies of the same message.

**Comment by yashwanthbabu** [comment]
@weiss Thank you. I was confused with this saving the chat history. My suggestion to change the table structure to identify the sent and received messages easily (if possible to change the table structure).
