### ISSUE TITLE
Page direction of web interface is not set to RTL for Hebrew

### ISSUE THREAD

**Issue by GreenLunar** [processone/ejabberd#650]

**Comment by badlop** [comment]
This is a feature to implement in the ejabberd WebAdmin, right? Do you know where should it be added? For example, this is a minimal WebAdmin page, where should the RTL code be added?
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'
      xml:lang='es'
      lang='es'>
  <head>
    <title>ejabberd Web Admin</title>
    <meta http-equiv='Content-Type'
          content='text/html; charset=utf-8' />
    <script src='/admin//additions.js'
            type='text/javascript'></script>
    <link href='/admin/favicon.ico'
          type='image/x-icon'
          rel='shortcut icon' />
    <link href='/admin/style.css'
          type='text/css'
          rel='stylesheet' />
  </head>
  <body>
    <div id='container'>
      <div id='header'>
        <h1>
          <a href='/admin/'>ejabberd Web Admin</a>
        </h1>
      </div>
      <div id='navigation'>
        <ul> <li> <div id='navitem'>
              <a href='/admin/muc/'>Multi-User Chat</a>
            </div> </li> </ul>
      </div>
      <div id='content'>
        <h1>Administraci&#195;&#179;n</h1>
        <div class='guidelink'>
          <a href='/admin/doc/guide.html#toc'
             target='_blank'>[Guide: Contents]</a>
        </div>
        <ul> <li>
            <a href='/admin/acls/'>Listas de Control de Acceso</a>
          </li> </ul>
      </div>
      <div id='clearcopyright'></div>
    </div>
    <div id='copyrightouter'>
      <div id='copyright'>
        <p>ejabberd (c) 2002-2015 ProcessOne</p>
      </div>
    </div>
  </body>
</html>
```

**Comment by GreenLunar** [comment]
Try in a `</div>` in `</body>`.

Please provide me a [demo page](https://www.ejabberd.im/online-demo-webadmin) to see it in action.

**Comment by GreenLunar** [comment]
Try replacing `<div id='container'>` with `<div id='container'  dir='rtl'>`.

**Comment by GreenLunar** [comment]
I think doing so using CSS would be better http://www.w3schools.com/cssref/pr_text_direction.asp

**Comment by badlop** [comment]
Looking at the wikipedia as example, you can try this change:
1. Open some WebAdmin page, and save it to disk
2. See how it looks when saved. Some colours may be missing
3. Edit the html file, and replace
```<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='he' lang='he'>```
with 
```<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='he' lang='he' dir='rtl'>```
4. Open that saved page, and see if it looks better than in step 4.

**Comment by GreenLunar** [comment]
That works, too.

Providing a live demo would be the best way for me to test WebAdmin.

**Comment by badlop** [comment]
Here is a zip file with a dump of webadmin with the patch and HE language forced: https://www.wetransfer.com/downloads/fa197d2184e6f46676fac38e6316ecf320150714152249/c466fe26a40c7c360b901899e4b7fd7420150714152249/e5083b

If you have an ejabberd already installed, I can provide you a patched beam file so you can try yourself.

**Comment by GreenLunar** [comment]
WIP


Page `/admin/acls/index.html`
Page `/admin/access/index.html`
Page `/admin/server/*/access/index.html`
Force LTR on `</table>`. Table should be LTR, because it is always in English.

Page `/admin/acls-raw/index.html`
Page `/admin/access-raw/index.html`
Page `/admin/access/*/index.html`
Page `/admin/node/ejabberd@localhost/ports/index.html` (multiple lined text boxes)
Force LTR in `</textarea>`.  Default text direction inside text area should be LTR, because it is always in English.

Page `/admin/muc/index.html' (`Statistics`)
Page `/admin/nodes/index.html' (`ממסרים שמורצים כעת` and `ממסרים שנפסקו`)
Strings in </h3> is place at left side, instead of right side.

Need more data in:
`/admin/server/*/online-users/index.html`


WIP

**Comment by GreenLunar** [comment]
I love eJabberD WebAdmin (a real KISS web interface)

Pages
`/admin/acls/index.html`
`/admin/server/*/acls/index.html`
`/admin/access/index.html`
`/admin/server/*/access/index.html`
Force LTR on `</table>`.
Table should be LTR, because it is always in English.

Pages
`/admin/acls-raw/index.html`
`/admin/access-raw/index.html`
`/admin/access/*/index.html`
`/admin/node/ejabberd@localhost/ports/index.html`
Force LTR in `</textarea>` (multiple lined text boxes).
Default text direction inside text area should be LTR, because it is always in English.

Page `/admin/muc/index.html` (`Statistics`)
Page `/admin/nodes/index.html` (`ממסרים שמורצים כעת` and `ממסרים שנפסקו`)
Strings in `</h3>` is place at left side, instead of right side.

I need more writings in the following pages to better examine them:
`/admin/server/*/online-users/index.html`
`/admin/server/*/shared-roster/index.html`

**Comment by GreenLunar** [comment]
I need more writings in the following pages to better examine them:
/admin/server/*/last-activity/index.html
/admin/server/*/online-users/index.html
/admin/server/*/shared-roster/index.html

**Comment by GreenLunar** [comment]
Pages
`/admin/muc/index.html` (`Statistics`)
`/admin/nodes/index.html` (`ממסרים שמורצים כעת` and `ממסרים שנפסקו`)
`/admin/node/*/update/index.html` (`מודולים שהותאמו` `Update script` `Low level update script` `Script check`)
Strings in `</h3>` are placed at left side, instead of right side.

**Comment by GreenLunar** [comment]
Strings in `</h3>` are placed at left side, instead of right side (unless it is reversed also for LTR users).

!!! unless it is reversed also for LTR users !!!

**Comment by badlop** [comment]
I've uploaded a new zip file in http://we.tl/rDVQansWLu 

See the changes:
* Fixed #659 
* Fixed all you mentioned in the comment
* Added some users and groups to my test server
* I've included an updated he.po, it misses 23 translations

You can improve he.po with any text editor. Recommended is a gettext-type editor, for example I use Poedit. If you improve that file, send it to badlop AT processone.net

**Comment by GreenLunar** [comment]
Pages
`/admin/server/*/node/*/modules/index.html`
Force LTR on </table>.
Table should be LTR, because it rarely has Semitic characters.

**Comment by GreenLunar** [comment]
Thank you.  I will examine it later.

> I've included an updated he.po, it misses 23 translations

I think the Supreme Khan of the Mongols is doing a good job, already ^_^

**Comment by GreenLunar** [comment]
`/admin/server/*/muc/index.html`
Strings in `</h3>` are placed at left side, instead of right side (unless it is reversed also for LTR users).

**Comment by GreenLunar** [comment]
It looks great!

Pages:
`/admin/acls/index.html`
`/admin/access/index.html`
`/admin/server/*/acls/index.html`
`/admin/server/*/access/index.html`
I suggest to place hyper-link `Raw` at the left. This is an exception, for the sake of comfortable access using a mouse.

What exactly is being displayed at `/admin/server/*/last-activity/index.html` and what

**Comment by GreenLunar** [comment]
What exactly is being displayed at `/admin/server/*/last-activity/index.html` and what would be displayed when clicking on *Show Ordinary Table* and *Show Integral Table*?

**Comment by GreenLunar** [comment]
Please provide me a ejabberd.pot in the next zip file, if you will. [THIS MESSAGE WILL BE DELETED]

**Comment by GreenLunar** [comment]
Page `/admin/server/*/muc/index.html` is fine.  Did you modify it?  I have mentioned it by mistake.

**Comment by badlop** [comment]
> I suggest to place hyper-link Raw at the left.

Ok, fixed now.

> What exactly is being displayed at /admin/server/*/last-activity/index.html and what would be shown when clicking on Show Ordinary Table and Show Integral Table?

Number of users that connected in the last X days. Clicking in those buttons simply changes from day-by-day number and total amount number. From what I see, both look similar.

> Page /admin/server/*/muc/index.html is fine. Did you modify it? I have mentioned it, earlier, by mistake.

Yes, it got modified to look similar to /admin/muc/rooms

**Comment by GreenLunar** [comment]
> Yes, it got modified to look similar to /admin/muc/rooms

Please keep it intact from specific modifications.

**Comment by GreenLunar** [comment]
There is a minor issue on some page which I hope to post tomorrow. Thank you for your efforts.

**Comment by GreenLunar** [comment]
Page `/admin/server/localhost/user/*/index.html`
![user1 localhost](https://cloud.githubusercontent.com/assets/2053884/8705481/8eb4e330-2b32-11e5-8193-e782225738c6.png)

Am I correct to assume that *tka1* is a resource (i.e. *JID/tka1*)?

`tka1 (plain://127.0.0.1:47120#ejabberd@localhost)` is displayed like `(tka1 (plain://127.0.0.1:47120#ejabberd@localhost`, because `)` is a neutral character, a character with no direction assigned.

You can solve it in two ways.
* Add `&lrm;` tag after `)`, `tka1 (plain://127.0.0.1:47120#ejabberd@localhost)&lrm;`.
* Set alignment (not direction) to LTR, so that the list would remain at the right direction.

I prefer the 2nd solution, if feasible.

---

I think this issue is solved.
I would be glad to have another dump of WebAdmin to examine.

If I find more problems, I will open a new issue.

**Comment by GreenLunar** [comment]
If am I correct by assuming that *tka1* is a resource (i.e. *JID/tka1*), then maybe the solution should be as follows:

Add `&rlm;` tag before `tka1` and before `(`.
Result `&rlm;tka1 &rlm;(plain://127.0.0.1:47120#ejabberd@localhost)`.

I still prefer the 2nd solution above (setting alignment), because I do not like to pollute text that is potentially copied, with *invisible* Unicode Control Characters.

The optimal solution would be to turn this list (`</li></ul>`) into two a table with two cells, one cell for `tka1` and the other for `plain://`.

Honestly, do not bother.  Implement the 2nd solution (setting alignment), if possible.

**Comment by badlop** [comment]
> Please keep it intact from specific modifications.

I've looked with more detail to my changes: in reality I made no changes related to LTR in the MUC pages.

> Honestly, do not bother. Implement the 2nd solution (setting alignment), if possible.

In fact there was another solution: to not use ( ) at all, instead separate with - and sort depending on language.

> I would be glad to have another dump of WebAdmin to examine.

See http://we.tl/zAr7T8baFC

**Comment by GreenLunar** [comment]
Wonderful!

> In fact there was another solution: to not use ( ) at all, instead separate with - and sort depending on language.

A table would be better. Rename `tka1` to `חופש`.  You should see the text as depicted in "Current" in the table below, which is not in a desired position, I think.

✱ | text
------------ | -------------
Original | plain://127.0.0.1:50971#ejabberd@localhost - tka1
Desired | plain://127.0.0.1:50971#ejabberd@localhost - חופש
Current | **חופש - plain://127.0.0.1:50971#ejabberd@localhost**

---

P.S. I am not certain, yet, but, maybe, I will ask you to set The module table to LTR,
Page `/admin/server/*/node/*/modules/index.html`

**Comment by GreenLunar** [comment]
> Set alignment (not direction) to LTR, so that the list would remain at the right direction.

I think, attribute `align` is deprecated.  Is there an alternative to `<div align="left">`?

**Comment by badlop** [comment]
I cannot invest much more time in those changes. If you find some minimal change that doesn't involve major changes in the code, I can still try to do it. Otherwise I'll consider the task satisfied.

**Comment by GreenLunar** [comment]
Please use a table with two columns, one for *plain://127.0.0.1:50971#ejabberd@localhost* and the other for *tka1*.

Other than that, this task is satisfied indeed!

**Comment by GreenLunar** [comment]
Maybe `<div style="direction:rtl; text-align:left">` would work for `tka1 (plain://127.0.0.1:47120#ejabberd@localhost)`.

**Comment by GreenLunar** [comment]
What did you pick, `text-align:left` or a table?

**Comment by badlop** [comment]
None of them, as apparently it was displayed correctly, and time was gone for the release.

**Comment by GreenLunar** [comment]
I suggest you take care of it!
I will bother you in future on this concern.

Nonetheless, I think, you did a good job.
