### ISSUE TITLE
Use Weblate as translation platform

### ISSUE THREAD

**Issue by GreenLunar** [processone/ejabberd#651]
CopyQ, Exaile, Money Manager EX and even Gammu are currently being translated at https://hosted.weblate.org/ using [Weblate](http://weblate.org/) which provides integration with Git.

It would be easier to me and to other non experienced git users to provide up to date translations tod ejabberd.

**Comment by badlop** [comment]
ejabberd has less than 400 strings, and they change or are added infrequently, so I consider that providing additional methods for contributing translations is not necessary.

Knowledge in git is not required at all: simply download the file from this website. When you finish editing the PO file, open a ticket mentioning you have an improved file. I'll contact you to get the file, take a look, and commit it.

There's a page mentioning this in more detail:
https://www.ejabberd.im/translate

**Comment by GreenLunar** [comment]
Try.

**Comment by GreenLunar** [comment]
Comment by nijel
> Currently this feature is available only for commercial (non public) translations. This might change once nijel/weblate/issues/516 is implemented.

When restricting access would be possible, I will ask, again, to migrate to Weblate.
