### ISSUE TITLE
SSL and DNS errors clutter logfiles

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#652]
Our error.log file is cluttered with error messages hardly relevant to the `error` loglevel, one is related to TLS handshakes:

```
2015-07-10 17:02:16.197 [error] <0.3637.9>@ejabberd_receiver:handle_info:248 TLS error = SSL_do_handshake failed: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

The other is because of a DNS lookup of some really broken zone:

```
2015-07-10 17:01:30.703 [error] <0.3283.9>@ejabberd_s2s_out:srv_lookup:1203 The DNS servers
  [{{64512,0,0,0,0,0,0,23},53},{{28,130,4,3},53},{{128,131,4,3},53}]
timed out on request for "thesecure.biz" IN SRV. You should check your DNS configuration.
```

Both messages (especially the first one) occur VERY frequently. Would it be possible to lower the log-level to e.g. INFO? Both messages are actually an error of course, but are hardly relevant in daily operations, only when an admin wants to debug the server.

**Comment by weiss** [comment]
TLS handshake issues are now logged as `[debug]` messages only.

It would be nice if you could open a separate issue for the DNS lookup issue.
