### ISSUE TITLE
Ejabberd no such file or directory “p1_pgsql.app” [PostgreSQL]

### ISSUE THREAD

**Issue by yashwanthbabu** [processone/ejabberd#655]
I am trying the authenticate with the ODBC authentication method. I setted up with the database like

```
createdb ejabberd
psql ejabberd < /path/to/pg.sql
createuser ejabberd
ALTER ROLE ejabberd WITH PASSWORD 'ejabberd';

```
and in the ejabberd.yml file, i just enable the odbc auth method and configured the pgsql settings like

```
auth_method: odbc
odbc_type: pgsql
odbc_server: localhost
odbc_database: ejabberd
odbc_username: ejabberd
odbc_password: ejabberd
```
while starting the ejabberd server I see the error

```
ejabberd:exit_or_halt:133 failed to start application 'p1_pgsql': {error,
                                         {"no such file or directory",
                                          "p1_pgsql.app"}}
```
Anyone help please

**Comment by mremond** [comment]
You did not compile ejabberd with pgsql support (./configure --enable-pgsql) Please read the compilation options for more information: http://docs.ejabberd.im/admin/guide/installation/#installing-ejabberd-from-source-code

If you did not build it yourself, you should download binary installer or packages from ProcessOne. They contains all the needed dependencies: https://www.process-one.net/en/ejabberd/downloads/

**Comment by yashwanthbabu** [comment]
@mremond I compiled with pgsql support as ./configure --enable-pgsql while installing. Even thought its not working

**Comment by mremond** [comment]
Are you sure you started clean ? The dependancies are downloaded only on the first clean build.
The error says you do not have the dependencies.

**Comment by yashwanthbabu** [comment]
@mremond Yeah I am sure.I removed the ejabberd entirely and started the clean build.

**Comment by zinid** [comment]
@yashwanthbabu remove `deps/p1_pgsql` and re-run `make`.

**Comment by yashwanthbabu** [comment]
@zinid Thanks. It worked. But now I cant able to register the user with
` sbin/ejabberdctl register yashwanth localhost password`.
It raise the error
```
@ejabberd_auth:is_user_exists:315 The authentication module ejabberd_auth_odbc returned an error
when checking user <<"ejabberd">> in server <<"localhost">>
Error message: [{severity,'ERROR'},{code,<<"42501">>},{message,<<"permission denied for relation users">>},{file,<<"aclchk.c">>},{line,3371},{routine,<<"aclcheck_error">>}]

```

**Comment by zinid** [comment]
```{message,<<"permission denied for relation users">>}```
Is it something you don't understand?
It's not related to ejabberd. Please configure PostgreSQL permissions.

**Comment by yashwanthbabu** [comment]
@zinid Yeah. Got that. Thanks for your help. Got my answer and closing the issue :)
