### ISSUE TITLE
Craete new user using node-xmpp

### ISSUE THREAD

**Issue by pokal4u** [processone/ejabberd#656]
Hi,

How to create a new user using node-xmpp?

Thanks
Pokal

**Comment by badlop** [comment]
I don't know what node-xmpp is, so my response to your question is: check node-xmpp manual, and node-xmpp tutorials.

**Comment by pokal4u** [comment]
I mean create JID.

**Comment by mremond** [comment]
If you mean how to create a JID using XMPP, you can refer to [XEP-0077: In-Band Registration](http://xmpp.org/extensions/xep-0077.html).

However, I am afraid, you cannot find help here on how to use those in features in node-xmpp.
