### ISSUE TITLE
Username and Token (instead of password) Authentication [Django]

### ISSUE THREAD

**Issue by yashwanthbabu** [processone/ejabberd#657]
I was able to connect to the Ejabberd with this [Django extauth script](https://www.ejabberd.im/files/contributions/ejabberd_auth_bridge.py.txt). My question is "Can I able to pass token instead of password for User Authentication?? ". For example, If I tried to login the user with social authentication, say with twitter. Then twitter authentication generates the token and tries to login. So is it possible to send the token as password for authenticating with ejabberd? If possible, Please let me know how can I do that??

**Comment by yashwanthbabu** [comment]
@mremond Hi Mickael. Need a help regarding this

**Comment by nOmi7** [comment]
Token auth in ejabberd will be really valuable as this can be used in mobiles as well without storing the passwords.

**Comment by mremond** [comment]
Well, if you put a token in password field during auth, that can work indeed. That would just depends on the backend you check your auth against.

**Comment by yashwanthbabu** [comment]
@mremond I have tried using the token in password. But the authentication fails for me. Ejabberd doesn't support [XEP-0235](http://xmpp.org/extensions/xep-0235.html) so because of this I think it is not working. Am I correct? Or does It work with xmpp-sasl authentication method?

**Comment by mremond** [comment]
To use token in password, your authentication backend need to interpret password as token. It is possible but it really depends on which back end you plugged ejabberd authentication.

**Comment by mremond** [comment]
Already possible currently.
