### ISSUE TITLE
[WIP] Untranslatable string

### ISSUE THREAD

**Issue by GreenLunar** [processone/ejabberd#659]
WIP (I need to compare against he.po file)

I guess, the following strings are untranslatable, by reading web pages of ejabberd WebAdmin from #650

Page `/admin/muc/index.html`
String `<h3>Statistics</h3>`

Page ``
String ``

Page ``
String ``

**Comment by badlop** [comment]
Right, there were some strings untranslatable in mod_muc_admin's WebAdmin pages. Fixed now.

**Comment by GreenLunar** [comment]
It appears `/admin/server/localhost/muc/index.html` is new.  This issue is invalid.

**Comment by GreenLunar** [comment]
Are strings in `/admin/muc/rooms` translatable yet?

**Comment by badlop** [comment]
No, those strings are not translatable, and by now I won't bother with them.

**Comment by GreenLunar** [comment]
Will they ever be translatable?
