### ISSUE TITLE
xmlrpc api 'delete_room' sometimes doesn't work right away, or needs multiple calls

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#660]
When I try to delete a MUC room via the API 'destroy_room (name service host)', it sometimes happens that the room still exists after the call (when I query the server for rooms). How can I be sure that the room gets destroyed properly, without looping (and sleeping) until the room is no longer in the existing room list?

**Comment by badlop** [comment]
When you call to destroy the room, this is logged:
```
11:20:09.240 [info] Destroyed MUC room room1@conference.localhost
11:20:09.241 [info] Destroyed MUC room room1@conference.localhost with reason: none
11:20:09.241 [info] Stopping MUC room room1@conference.localhost
```
When you call it and isn't destroyed at the first try, what is logged?

**Comment by nunohorta** [comment]
I've seen this happening before. I had to call 2 or 3 times until it's deleted. I'll post my logs when it happens again.

**Comment by dirkmoors** [comment]
@badlop sorry for the late response; I didn't yet have the time to check the logs in that case. I'll post back as soon as I have.
