### ISSUE TITLE
WebAdmin has no accessible links to ejabberd and ProcessOne

### ISSUE THREAD

**Issue by GreenLunar** [processone/ejabberd#661]
From reading web pages of ejabberd WebAdmin from #650, it appears that neither the top banner `/admin/logo.png` nor bottom Copyright line `ejabberd (c) 2002-2015 ProcessOne` link to ejabberd or to ProcessOne.

I suggest to add the links to the Copyright line at the bottom.

**Comment by badlop** [comment]
Proposed patch:
```
diff --git a/src/ejabberd_web_admin.erl b/src/ejabberd_web_admin.erl
index da16658..4a1ccbb 100644
--- a/src/ejabberd_web_admin.erl
+++ b/src/ejabberd_web_admin.erl
@@ -340,8 +340,11 @@ make_xhtml(Els, Host, Node, Lang, JID) ->
 				 [{xmlcdata, <<"">>}])]),
 		      ?XAE(<<"div">>, [{<<"id">>, <<"copyrightouter">>}],
 			   [?XAE(<<"div">>, [{<<"id">>, <<"copyright">>}],
-				 [?XC(<<"p">>,
-				      <<"ejabberd (c) 2002-2015 ProcessOne">>)])])])]}}.
+				 [?XE(<<"p">>,
+				  [?AC(<<"https://www.ejabberd.im/">>, <<"ejabberd">>),
+				   ?C(<<" (c) 2002-2015 ">>),
+				   ?AC(<<"https://www.process-one.net/">>, <<"ProcessOne">>)]
+                                 )])])])]}}.
 
 get_base_path(global, cluster) -> <<"/admin/">>;
 get_base_path(Host, cluster) ->
```

**Comment by cromain** [comment]
badlop i think you can apply your patch, it make sense.

**Comment by GreenLunar** [comment]
Hyperlink colors and underline are ugly.  I suggest to keep the links, of course, while remaining the previous style intact.

**Comment by GreenLunar** [comment]
See *Styling Links* (color) and *Text Decoration* (text-decoration).
http://www.w3schools.com/css/css_link.asp

Set `color` to be consistent with the original color.
Set `text-decoration` to none for all states (a:link, a:visited, a:hover, a:active).

**Comment by GreenLunar** [comment]
Add this code to *style.css*.

```
#copyright a:link {
  color: #ffffff;
  text-decoration: none;
}
#copyright a:hover {
  color: #ffffff;
  text-decoration: underline;
}
```
