### ISSUE TITLE
XEP-0191::Sending list of JIDs to Unblock

### ISSUE THREAD

**Issue by praveenoms** [processone/ejabberd#663]
Hi ,
does XEP-0191 supports unblocking of multiple Jids? , when i am sending multiple JIDs for blocking it works like a charm but in case of unblock it returns "feature-not-implemented"

![unblking](https://cloud.githubusercontent.com/assets/7972032/8702072/196f6e8c-2b33-11e5-8419-806a104f8fd6.png)

**Comment by badlop** [comment]
What ejabberd version are you using? What options do you have for mod_blocking: are you using Mnesia, ODBC, or other storage?

It works correctly for me, see this example:

First I get list of blocked:
```
<iq type='get' id='blocklist1'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>

<iq from='juliet@capulet.com'
	to='juliet@capulet.com/chamber'
	id='blocklist1'
	type='result'>
  <blocklist xmlns='urn:xmpp:blocking'>
    <item jid='romeo2@montague.net'/>
    <item jid='romeo3@montague.net'/>
    <item jid='romeo4@montague.net'/>
  </blocklist>
</iq>
```

Then I unblock romeo2 and romeo3:
```
<iq type='set' id='unblock1'>
  <unblock xmlns='urn:xmpp:blocking'>
    <item jid='romeo2@montague.net'/>
    <item jid='romeo3@montague.net'/>
  </unblock>
</iq>

<iq from='juliet@capulet.com'
	to='juliet@capulet.com/chamber'
	id='unblock1'
	type='result'/>
```

Finally I check only romeo4 remains blocked:
```
<iq type='get' id='blocklist1'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>

<iq from='juliet@capulet.com'
	to='juliet@capulet.com/chamber'
	id='blocklist1'
	type='result'>
  <blocklist xmlns='urn:xmpp:blocking'>
    <item jid='romeo4@montague.net'/>
  </blocklist>
</iq>
```
