### ISSUE TITLE
Windows Installer bug: wrong userprofile path calculation

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#664]
Hello

I installed ejabberd on Windows 8.1 Professional x64 and Windows 7 Professional SP1 x64. The installer said in both cases that the post installation script failed.

I found that the variable EJABBERD_HOME in install-dir\bin\ejabberdctl was set incorrectly.
It was set to c:\Users\\\<username of Administrator profile> but I changed the username of the profile.

By default Windows uses C:\Users\\\<username> as the profile dir but if the username is changed later the profile dir is kept unchanged. So the start of ejabberd always faild because it did not find the ejabberd.yml.
Changing  EJABBERD_HOME to the right path made ejabberd working fine.

The path to the profile of the current user is stored in the environment variable %USERPROFILE%.

Edit: I used ejabberd-15.06-windows-installer.exe.

**Comment by cromain** [comment]
Thanks for this feedback
I generated an installer using %USERPROFILE% in both EJABBERD_HOME and start.cmd, installing as administrator is OK, running as user is OK. Tested on a windows 8 box. so it should be fixed for 15.07.
