### ISSUE TITLE
Windows: %HOMEDRIVE%%HOMEPATH% undefined when Run As Administrator

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#665]
Hello

The environment variables %HOMEDRIVE% and %HOMEPATH% are not defined if I run a program with context menu "Run As Administrator" (I use a German Windows so the name can be different).
However, the environment variable %USERPROFILE% is defined and contains the expected path.
I saw this behavior with  Windows 8.1 Professional x64 and Windows 7 Professional SP1 x64.

I tried to replace the variables in \<install dir>\\bin\\start.cmd to %USERPROFILE%. It opend the website saying ejabberd was started successfully but no erlang-coockie file was created in the user profile.

I use ejabberd-15.06-windows-installer.exe.

Kind regards

**Comment by cromain** [comment]
Thanks for this feedback
I generated an installer using %USERPROFILE% in both EJABBERD_HOME and start.cmd, installing as administrator is OK, running as user is OK. Tested on a windows 8 box. so it should be fixed for 15.07.
