### ISSUE TITLE
Windows: do not save ejabberd config in user profile

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#666]
Hello

ejabberd uses %APPDATA%\ejabberd to save the configuration files. This path is inside the user profile of the account which was used to install ejabberd - which is with high probability an administrator account. On Windows a programm does not need administrator privileges to create sockets but to access the config files it must be run with these privileges (or other users must get permission to access files in the administrator's user profile).

An alternative path would be %ALLUSERSPROFILE% or %ProgramData% (which both point to c:\ProgramData by default) \ejabberd. This path is independent to any user profile and with the right NTFS access rights unautorized users still cannot access this data.

I briefly testet it by changing the path in EJABBERD_HOME in <install dir>\bin\ejabberdctl. ejabberd started and used the files in c:\ProgramData\ejabberd. As I am still new to ejabberd and still experimenting (--> not using it productive) I only started ejabberd.

If changing the default config path is not an option, the user could be offered to choose between %APPDATA%\ejabberd and %ProgramData%\ejabberd during the install.

Kind regards

**Comment by Neustradamus** [comment]
Like I said some years ago: %APPDATA%\ejabberd is perfect.

**Comment by Andy-2639** [comment]
Installing ejabberd as admnistrator is fine.
But I'm not talking about installing I'm talking about running ejabberd. I do *not* want to run this software with unnecessary priveleges just because the config data is stored in an user profile directory.

In my opinion the user profile is for user related data only and the ejabberd config is not user related. For other data (related to all users or to none) there is the Directory %ProgramData%. Other programs (e.g. MySQL and BOINC) are using this Directory, too.

**Comment by cromain** [comment]
(i know nothing about windows, so please correct me if i'm wrong)
as i understand %ProgramData% is global and accessible to any users on the system, while %AppData% is private to user running ejabberd. So ejabberd database and logs must be in %AppData% anyway.
1/ What is the point to put ejabberd config in %ProgramData% ? ejabberd will always run under the same user account. and if you need several users to run their own ejabberd, each will need it's own configuration (at least to set different listener ports).
2/ What unnecessary privileges are needed to run ejabberd with config data stored in user profile ?

**Comment by Andy-2639** [comment]
> as i understand %ProgramData% is global and accessible to any users on the system

Yes, %ProgramData% itself is global and by default subdirectories inherit the permissions. But NTFS allows to set the permissions individually and much more fine granular than Linux with rwx for user, group and world. In the following article the NTFS permissions are described: https://msdn.microsoft.com/en-us/library/bb727008.aspx Be aware that you can set the permissions for many users and groups - your are **not** limited to 1 user and 1 group.
I'm going to allow 2 users access to the config folder: a test user (because in the ejabberd guide it is recommended to test the ejabberd config before running it as a service) and the user "LocalService". With the test user I can also read the logfiles in case of problems.

> ejabberd will always run under the same user account.

As I already mentioned I will have to accounts which are running ejabberd - but not simultaniously. While testing the config I use the test user and for production use it will run under the user "LocalService". Another possibility for the use case would be copying the config files ...

> if you need several users to run their own ejabberd, each will need it's own configuration 

I didn't though about running two ejabberd instances on the same machine. Does this use case appear in practice? This use case indeed needs two or more independent configurations.

> What unnecessary privileges are needed to run ejabberd with config data stored in user profile ?

As I have to install ejabberd as administrator the config files are written to the administrators profile. So I would have to run ejabberd as administrator to access the config files. Another option would be to copy the files into the user profile of another user ...
The user "LocalService" has very few priviledges: https://msdn.microsoft.com/de-de/library/windows/desktop/ms684188(v=vs.85).aspx It's user account is somewhere in a subdirectory of the windows directory. I think not many users are aware about this profile.

**Comment by cromain** [comment]
that make sense. we have to check how ejabberd can be installed as LocalService (i guess installer will always run as administrator or running user, so we have to adapt depending of installation type). maybe this can be an option in the installer. i push this to 15.10 so we have time to experiment and test.

**Comment by cromain** [comment]
Moved files from %APPDATA% to %ProgramData% looks good.
note: postinstall will move existing %APPDATA%\ejabberd (if exists) to %ProgramData% so upgrade will not loose old setup.
