### ISSUE TITLE
Weird unknown option

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#667]
In log file I have a lot errors:
```
2015-07-20 16:54:28.681 [error] <0.21606.16> ignoring unknown option inet6
2015-07-20 16:54:28.681 [error] <0.21606.16> ignoring unknown option {access,local}
2015-07-20 16:59:28.683 [error] <0.21561.16> ignoring unknown option inet6
2015-07-20 16:59:28.683 [error] <0.21561.16> ignoring unknown option {access,local}
```
In my config file I don't have anywhere "inet6". An entry in the log occurs every 5 minutes - is very weird, I don't know what is it.

**Comment by zinid** [comment]
What ejabberd version are you running? I cannot even grep this message in the source code.

**Comment by beherit** [comment]
I running ejabberd 15.06, I cannot find this option in my config file.

**Comment by zinid** [comment]
Seems like you have stun configured and have indentation problems.
Show your config AS IS.

**Comment by beherit** [comment]
Yes, I have stun configured:
```
listen:
  - ip: "::"
    port: 5349
    module: ejabberd_stun
    tls: true
    certfile: 'CERT_LOCATION'
    use_turn: true
    turn_ip: "37.187.177.85"
    turn_min_port: 49152
    turn_max_port: 50000
    access: local
```

**Comment by zinid** [comment]
`access` is indeed an undefined option for ejabberd_stun module.

**Comment by beherit** [comment]
I fixed it, now I have only problem with inet6.

**Comment by badlop** [comment]
I suspect this: when using "::", ejabberd is adding the inet6 option, and later ejabberd itself complains that it isn't supported.

**Comment by Andy-2639** [comment]
ejabberd is new for me so I rather guess than knowing exactly.

The documentation says that with
ip: "::"
the module listens on all ipv6 interfaces. stun/turn is for nat traversal - and nat is forbidden in ipv6 afaik. That means that registering stun to ipv6 interfaces makes no sense.
Try
ip: "0.0.0.0"
instead, which registers stun/turn to listen on all ipv4 interfaces.

**Comment by beherit** [comment]
@Andy-2639 you right, thanks ;)
