### ISSUE TITLE
Stream Management in ejabberd - please clarify

### ISSUE THREAD

**Issue by EugeneNews** [processone/ejabberd#668]
Have a good day!

Thank you very much for _ejabberd_ and community! I'm using _ejabberd_ for over year and we base our mobile messenger over it. This makes me to learn Erlang and it is fun)

I have just one request and greatly appreciate if you have a minute to clarify it!
The "Stream Management" feature is not described in details in Ejabberd Docs. Does Ejabberd __really stores__ stanzas that to be resent ("resend_on_timeout: true") - when recipient dropped internet connection (still shows "online"). It is written in Docs that after resumption and syncing acknowledgements - stanzas "will be resent". 
So, does Ejabberd __stores__ stanzas?

​There are implementations like [​mod_confirm_delivery](https://github.com/johanvorster/ejabberd_confirm_delivery) which stores stanzas if server sure that they were not delivered. Do i need additional module like this or just tune application up to "Stream Management" ?

Thank you in advance!

**Comment by weiss** [comment]
> So, does Ejabberd stores stanzas?

The stanzas are queued in memory until the client acknowledges them.  If the connection is lost, the stanza queue remains alive in memory for _n_ seconds (where _n_ is 300 by default) to give the client a chance to resume the session.  If the session is not resumed, the stanzas are either resent or bounced with an error message depending on the `resend_on_timeout` setting.  Either way, the queue is destroyed at that point.

See [XEP-0198][1] for more details.

[1]: http://xmpp.org/extensions/xep-0198.html

**Comment by EugeneNews** [comment]
Thank you very much!
