### ISSUE TITLE
stun_listener.erl breaks compile

### ISSUE THREAD

**Issue by dakom** [processone/ejabberd#669]
with fresh clone: 

ejabberd/deps/p1_stun/src/stun_listener.erl:39: referring to built-in type dict as a remote type; please take out the module name

**Comment by mremond** [comment]
Which Erlang version are you using ?

**Comment by zinid** [comment]
This is now fixed.

**Comment by dakom** [comment]
@mremond - Erlang version is "R16B03"

Confirmed- this is now fixed :)

**Comment by mremond** [comment]
Thanks !

For the record, we will deprecate R16 in a not too soon future, making R17 the minimal version to use latest version of ejabberd. The goal is to be able to stick to latest Erlang feature and limit validation process to two major versions.

**Comment by dakom** [comment]
Ah, good to know! Was going to roll back to R16 due to ticket #670 - but will hold off. I didn't even know Ubuntu was so far behind till today ;)
