### ISSUE TITLE
doesn't compile with erlang version 18

### ISSUE THREAD

**Issue by dakom** [processone/ejabberd#670]
On fresh 14.04 Ubuntu VM:

Install newest erlang ("18"):

1. wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
2. sudo dpkg -i erlang-solutions_1.0_all.deb
3. sudo apt-get update

Install required packages:

1. sudo apt-get install make autoconf libssl-dev libyaml-dev libexpat-dev zlib1g-dev libpam-dev erlang erlang-dev erlang-eunit erlang-parsetools

Compile ejabberd:

1. git clone https://github.com/processone/ejabberd
2. cd ejabberd
3. ./autogen.sh
4. ./configure --enable-mysql
5. make

Result:

`ejabberd/deps/esip/src/esip_listener.erl:40: type dict() undefined`

**Comment by EugeneNews** [comment]
the same on Ubuntu 15.04 and on Debian testing
latest Erlang...

**Comment by allran** [comment]
the same on Centos 6.6 

erlang version:

[root@allran ejabberd]# erl --version
Erlang/OTP 18 [erts-7.0] [source-4d83b58] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.0  (abort with ^G)

**Comment by zinid** [comment]
Fixed
