### ISSUE TITLE
mod_muc not updating room records in  muc_room in pgsql odbc

### ISSUE THREAD

**Issue by satishck1992** [processone/ejabberd#671]
I have used the following configuration : 
  mod_muc:                                                                                                  
    host: "conference.@HOST@"                                                                            
    access: muc                                                                                              
    access_create: muc_create                                                                               
    access_persistent: muc_create                                                                           
    access_admin: muc_admin                                                                                   
    db_type: odbc
Everything is working correctly except the fact that new rooms created are not stored in the pgsql table named muc_room or for the matter of fact anywhere else.

**Comment by mremond** [comment]
Have you set the MUC room as persistent ? Only persistent MUC room are stored on database.

**Comment by satishck1992** [comment]
Ahh ... thanks a lot for the quick reply :) :+1:  i tried searching for a way to resolve this but couldn't find it . Have a good day !
