### ISSUE TITLE
./rebar compile error, please help me.

### ISSUE THREAD

**Issue by allran** [processone/ejabberd#672]
Erlang/OTP 18 [erts-7.0] [source-4d83b58] [64-bit]

```
$ git clone https://github.com/processone/ejabberd.git
$ cd /Users/allran/SDK/chart/ejabberd 
$ chmod +x autogen.sh 
$ ./autogen.sh  
$ ./configure --prefix=/Users/allran/SDK/chart/my-ejabberd --enable-all     //附加所有
$ ./rebar get-deps
$ ./rebar compile
```

And then, i get follow error:

....
==> p1_utils (compile)
==> p1_cache_tab (compile)
==> p1_tls (compile)
==> p1_stringprep (compile)
==> p1_xml (compile)
==> p1_stun (compile)
==> esip (compile)
==> p1_yaml (compile)
==> meck (compile)
==> p1_mysql (compile)
==> p1_pgsql (compile)
==> sqlite3 (compile)
==> p1_pam (compile)
==> p1_zlib (compile)
==> protobuffs (compile)
==> riak_pb (compile)
....
...
Compiled src/protobuffs_scanner.xrl
Compiled src/protobuffs_parser.yrl
Compiled src/protobuffs_scanner.erl
Compiled src/protobuffs_parser.erl
Compiled src/protobuffs_file.erl
/root/chart/ejabberd/deps/protobuffs/src/pokemon_pb.erl:206: Warning: variable 'FNum' exported from 'case' (line 188)
Compiled src/pokemon_pb.erl
Compiled src/protobuffs.erl
Compiled src/protobuffs_compile.erl
==> riak_pb (compile)
Compiling src/riak_kv.proto

=INFO REPORT==== 22-Jul-2015::23:06:50 ===
Writing header file to "riak_kv_pb.hrl"

=INFO REPORT==== 22-Jul-2015::23:06:50 ===
Writing beam file to "riak_kv_pb.beam"
Compiling src/riak_search.proto

=INFO REPORT==== 22-Jul-2015::23:06:50 ===
Writing header file to "riak_search_pb.hrl"

=INFO REPORT==== 22-Jul-2015::23:06:50 ===
Writing beam file to "riak_search_pb.beam"
Compiling src/riak.proto

=INFO REPORT==== 22-Jul-2015::23:06:50 ===
Writing header file to "riak_pb.hrl"

=INFO REPORT==== 22-Jul-2015::23:06:51 ===
Writing beam file to "riak_pb.beam"
Compiled src/riak_pb_codec.erl
Compiled src/riak_pb_search_codec.erl
/root/chart/ejabberd/deps/riak_pb/src/riak_pb_kv_codec.erl:52: type dict() undefined
ERROR: compile failed while processing /root/chart/ejabberd/deps/riak_pb: rebar_abort

**Comment by allran** [comment]
#640 looks like the same error, but i don't know how to fix it , please help, thanks.

**Comment by mremond** [comment]
The problem is that Erlang R18 does not support dict(). it now supports dict:dict(). Either use Erlang R17 or update dict() to dict:dict().

We cannot update it ourself, as this is Riak dependency.

**Comment by allran** [comment]
@mremond  Thank you. I will change to use Erlang R17.
