### ISSUE TITLE
Adding XEP-0313 support in 15.06 breaks definition of user_send_packet hook

### ISSUE THREAD

**Issue by mick-h** [processone/ejabberd#673]
Commit 83cce468a573d3ca58a0c6653a2ccc17c7b4dbc3 added support for XEP-0313. In the process it changed the `user_send_packet` hook signature in a non-backwards-compatible way, re-arranging and adding function parameters and changing from a `run` hook to a `run_fold` hook.

This seems problematic - 15.06 was a minor release, so users might have an expectation that there were no breaking changes to APIs, and the [public documentation](http://docs.ejabberd.im/developer/hooks/) still shows the old signature.

**Comment by mremond** [comment]
I agree we need to document that, that you for pointing this out.

However, please, note the version scheme is YEAR.MONTH of release. This was described in this blog post: https://blog.process-one.net/ejabberd-community-server-13-03-is-launched-in-beta/

> We decided to switch to an Ubuntu-like version numbering for ejabberd community server. The next releases will be numbered as "Year.Month-Revision", instead of "Major.Minor.Bugfix-Revision".

It means that ejabberd Community Edition is made for fast change and experimentation and thus yet, we iterate quickly on it and improve and change stuff in that Community version.

But, as I said, change should be documented, so we will take care of that. Thanks !

**Comment by mick-h** [comment]
OK that makes more sense on the versioning front, I had not twigged to that scheme.

I've just had another look through the release notes, and the change to `user_send_packet` is not there either.  That might be helpful for module developers if breaking changes were explicit items in the release notes also.

Thanks for the prompt response!

**Comment by mremond** [comment]
Yes, we still need to document it, but we are discussing if the run_fold change was really need actually. It is likely that just the c2s state was needed and in that case, we should probably revert it to be still a "run" hook.
