### ISSUE TITLE
ejabberdctl: bad path to epmd on Ubuntu

### ISSUE THREAD

**Issue by dakom** [processone/ejabberd#677]
` /etc/init.d/ejabberd restart`

> Stopping ejabberd...
> //sbin/ejabberdctl: 421: //sbin/ejabberdctl: //bin/epmd: not found

maybe path should be /usr/bin/epmd on Ubuntu 12.04?

**Comment by mremond** [comment]
Which ejabberd are you using and how did you install it ?

**Comment by dakom** [comment]
Version is latest from github, here's the build/install I ran as a regular user:

**build**
>git clone https://github.com/processone/ejabberd
cd ejabberd
./autogen.sh
./configure --enable-mysql
make

**install**
>sudo make install
sudo cp ./ejabberd.init /etc/init.d/ejabberd
sudo update-rc.d -f ejabberd remove
sudo update-rc.d -f ejabberd defaults

**Comment by mremond** [comment]
Well, yes, the init script is provided as example. I guess it need to be adapted on case by case basis. Not sure if there is something we can add to be a bit more flexible on the path.

**Comment by badlop** [comment]
ejabberdctl.template uses bindir:
> EPMD={{bindir}}/epmd

Which by default is /bin, but you can change here:
```
$ ./configure --help
...
  --bindir=DIR            user executables [EPREFIX/bin]
```

**Comment by dakom** [comment]
That fixed it! (./configure --bindir=/usr/bin)
