### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#679]
08:55:54.507 [error] TLS error = SSL_do_handshake failed: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

Getting this error all time

**Comment by prefiks** [comment]
Hello,

I think this is from your client trying to connect using SSL3 that we disabled in ejabberd for security purposes. What client are you using? Maybe it can be configured to at least use TLS?

**Comment by nOmi7** [comment]
We are using Smack 4.1.2 and its using TLS i blv.

    // If the user didn't specify a SSLContext, use the default one
        if (context == null) {
            context = SSLContext.getInstance("TLS");
            context.init(kms, null, new java.security.SecureRandom());
        }
        Socket plain = socket;
        // Secure the plain connection

**Comment by nOmi7** [comment]
Still the same issue can anyone help us please ?

**Comment by prefiks** [comment]
Wpuld you be able to provide me with config file of your ejabberd server and if possible source code of your client?

**Comment by beherit** [comment]
@prefiks this problem is really related with client? I have this same error on my public server and in log file I see new s2s connections in same time.

**Comment by beherit** [comment]
I checked and error appears when I discovering some bad server e.g. dobreprogramy.im. Then I have error:
```
2015-07-27 10:31:13.411 [error] <0.4827.7>@ejabberd_receiver:handle_info:248 TLS error = SSL_do_handshake failed: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

**Comment by nOmi7** [comment]
listen:
port: 5222
    module: ejabberd_c2s
    ##
    ## If TLS is compiled in and you installed a SSL
    ## certificate, specify the full path to the
    ## file and uncomment these lines:
    ##
    certfile: "/etc/lighttpd/lighttpd.pem"
    starttls: true
    ##
    ## To enforce TLS encryption for client connections,
    ## use this instead of the "starttls" option:
    ##
    starttls_required: true
    ##
    ## Custom OpenSSL options
    ##
    ## protocol_options:
    ##   - "no_sslv3"
    ##   - "no_tlsv1"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    resend_on_timeout: false
    resume_timeout: 7
    stream_management: true



This is the client side code related to ssl from SMACK 4.1.2

// If the user didn't specify a SSLContext, use the default one
    if (context == null) {
        context = SSLContext.getInstance("TLS");
        context.init(kms, null, new java.security.SecureRandom());
    }
    Socket plain = socket;
    // Secure the plain connection

**Comment by prefiks** [comment]
Could you also tell me Java version is your client using?

**Comment by prefiks** [comment]
@beherit
In general this error is generated when ssl/tls versions recognized by both client and server don't match (but i think we also see something similar when someone try to use plain text to connect to ssl listening server)

**Comment by nOmi7** [comment]
I am using Smack over android - http://www.igniterealtime.org/projects/smack/index.jsp (4.1.2)
