### ISSUE TITLE
password_strength in mod_register

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#680]
I trying to use password_strength in mod_register but on ejabberd 15.06 this option doesn't work - on ejabberd 15.04 it working correctly.

**Comment by badlop** [comment]
In my tests it works correctly. Please note 15.06 introduced config validation.

Do you configure it like this?
```
modules:
  mod_register: 
    password_strength: 32
```

When ejabberd starts, do you see any warning about unused options in the logs?

How do you test the option: using in-band registration, or changing password with a client, or using mod_register_web, or some other way...?

For me, using in-band registration with a small password, I get:
```
<iq from='localhost'	id='1:872540'	type='error'>
  <query xmlns='jabber:iq:register'>
    <username>user1www22</username>
    <password>aaa</password>
  </query>
  <error code='406'	type='modify'>
    <not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    <text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>The password is too weak</text>
  </error>
</iq>
```

**Comment by beherit** [comment]
Weird, after machine restart the problem disappeared.
