### ISSUE TITLE
Issue setting up ejabberd with Riak

### ISSUE THREAD

**Issue by mingqlin** [processone/ejabberd#681]
I follow ejabberd installation and configuration document, but still could not get Riak to property setup with ejabberd.

Latest Riak KV (2.1.1) is installed on same host as ejabberd and along with redis. and make sure Riak is running properly

in ejabberd.yml added following configuration:

default_db: riak
sm_db_type: redis
riak_server: "localhost"
riak_port: 8087

i have changed "storage_backend = leveldb", Riak starts successfully with only this change.
Riak start FAILED after I create /etc/riak/vm.args with -pz /opt/ejabberd-15.06/lib/ejabberd-15.06/ebin

if I remove vm.args file, and Riak able to start, and run ejabberd, i get following:

when I do " curl -i http://localhost:8098/buckets?buckets=true" I see following buckets are created:
{"buckets":["private_storage","offline_msg","caps_features","last_activity"]}

but as you can see there are missing a lot of buckets like "user" bucket and some others.

Please help and let me know how I could configure ejabberd with riak as database.

Thanks a lot

**Comment by Suvitruf** [comment]
Same here. After creating /etc/riak/vm.args with `-pz /lib/ejabberd/ebin` Riak start FAILED.

Riak 2.1.1

**Comment by Suvitruf** [comment]
1) delete vm.args
2) create /etc/riak/advanced.config with

[
    {riak_kv, [{add_paths, ["/opt/ejabberd-15.06/lib/ejabberd-15.06/ebin"]}]}
].

**Comment by stevenlivz** [comment]
The last answer from @Suvitruf  was also what I needed to do. Would be useful to update the docs.

**Comment by clintonm9** [comment]
This fixed my issue as well.
