### ISSUE TITLE
mod_http_ws / ejabberd_http_ws

### ISSUE THREAD

**Issue by hydrosine** [processone/ejabberd#683]
Could there be placed some examples in the docs on how to configure "websocket_ping_interval: Seconds" and "websocket_timeout: Seconds" for the mod_http_ws.

I tried through:
```
modules:
  mod_http_ws:
    websocket_timeout: 0
```

but this resulted in:
```
2015-07-30 11:17:48.307 [warning] <0.2397.0>@gen_mod:validate_opts:256 module 'mod_http_ws' doesn't export mod_opt_type/1 
2015-07-30 11:17:48.309 [critical]<0.2397.0>@gen_mod:start_module:107 Problem starting the module mod_http_ws for host <<"test.com">> options: [{websocket_timeout,0}] 
error: undef
```

Something else that i found is that mod_http_ws is not in the module overview section:
http://docs.ejabberd.im/admin/guide/configuration/#modules-overview

**Comment by hydrosine** [comment]
Apparantly i have to set it in the root. and not under modules and mod_http_ws part.
Docs could definitely need some improvements on this part :)

**Comment by mremond** [comment]
Finally, did you manage to configure it right ? Any suggestion on what to change in doc to make this clearer and less error prone ?

**Comment by prefiks** [comment]
I pushed information about this to our docs git repository, so this should get updated when docs update script will run next time

**Comment by mremond** [comment]
Thanks, the updated documentation is deployed.
