### ISSUE TITLE
problem with using tsung to register 200000 users,only one user be successfully registed.

### ISSUE THREAD

**Issue by h264g729** [processone/ejabberd#685]
hello everyone,I have a problem. when I run tsung's example(jabber_register.xml),the result is that only one user be created. what is wrong ,help me plz,thanks advance. there are the scripts:
-----------------------------------------
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/local/tsung/share/tsung/tsung-1.0.dtd">
<tsung loglevel="notice" dumptraffic="false" version="1.0">

  <clients>
    <client host="localhost" use_controller_vm="true" maxusers="600" >
    </client>
  </clients>

<servers>
   <server host='localhost' port='5222' type='tcp'/>
</servers>

<load>
  <arrivalphase phase="1" duration="15" unit="minute">
    <users maxnumber="200" interarrival="0.025" unit="second"></users>
  </arrivalphase>
  </load>

<options>
  <option type="ts_jabber" name="global_number" value="200"></option>
  <option type="ts_jabber" name="userid_max" value="200"></option>
  <option type="ts_jabber" name="domain" value="localhost"></option>
  <option type="ts_jabber" name="username" value="tsung"></option>
  <option type="ts_jabber" name="passwd" value="tsung"></option>
</options>

<sessions>
  <session probability="100" name="jabber-example" type="ts_jabber">

    <request>
      <jabber type="connect" ack="local"></jabber>
    </request>

    <request>
      <match do="abort" when="match">error</match>
      <jabber type="register" ack="local" id="new"></jabber>
    </request>

    <request>
      <jabber type="close" ack="local"></jabber>
    </request>

  </session>
</sessions>
</tsung>

#tsung_controller@localhost.log#

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(5:<0.51.0>) Config server started, logdir is "/root/.tsung/log/20150421-1109"

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
              ts_mon:(5:<0.50.0>) starting monitor, global 

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
           ts_config:(5:<0.51.0>) Reading config file: jabber_register.xml

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
      ts_user_server:(5:<0.66.0>) Reset offline and online lists (maxid=200)

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
           ts_config:(5:<0.51.0>) Session name for id 1 is "jabber-example"

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
      ts_user_server:(5:<0.66.0>) Reset offline and online lists (maxid=200)

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(4:<0.51.0>) SYSINFO:Tsung version: 1.5.1

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(4:<0.51.0>) SYSINFO:Erlang version: Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:16] [hipe] [kernel-poll:true]

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(4:<0.51.0>) SYSINFO:System architecture x86_64-unknown-linux-gnu

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(4:<0.51.0>) SYSINFO:Current path: /usr/local/tsung/lib/erlang/lib/tsung-1.5.1/ebin/tsung.beam

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
           ts_os_mon:(5:<0.48.0>) os_mon disabled
=INFO REPORT==== 21-Apr-2015::11:09:06 ===
              ts_mon:(5:<0.52.0>) Activate clients with text backend

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
              ts_mon:(5:<0.52.0>) Starting tsung clients on hosts: [localhost]

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(5:<0.51.0>) Start a launcher on the controller beam localhost

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
  ts_launcher_static:(5:<0.83.0>) Launch msg receive ("localhost")

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
         ts_launcher:(5:<0.84.0>) Launch msg receive ("localhost")

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(5:<0.51.0>) All remote beams started, syncing 

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(5:<0.51.0>) Undefined ports_range config 

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
    ts_config_server:(5:<0.51.0>) New arrival phase 1 for client "localhost" (last ? true): will start 200 users

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
         ts_launcher:(5:<0.84.0>) Expected duration of first phase: 900.0 sec (200 users) 

=INFO REPORT==== 21-Apr-2015::11:09:06 ===
         ts_launcher:(5:<0.84.0>) Activate launcher (200 users) in 983 msec 

=INFO REPORT==== 21-Apr-2015::11:09:13 ===
         ts_launcher:(5:<0.84.0>) This was the last phase, wait for connected users to finish their session

=INFO REPORT==== 21-Apr-2015::11:09:18 ===
     ts_launcher_mgr:(5:<0.79.0>) No more active users tsung_controller@localhost "12772"

=INFO REPORT==== 21-Apr-2015::11:09:18 ===
              ts_mon:(5:<0.52.0>) stopping monitor (normal)

#tsung.log#

# stats: dump at 1429585756
stats: users 0 4
stats: session 200 9.99697875976563 11.816601055145759 134.97998046875 2.526123046875 0 0
stats: users_count 200 200
stats: finish_users_count 200 200
stats: request 401 3.4125093759741274 6.419080058220296 88.15087890625 0.197998046875 0 0
stats: page 1 82.1630859375 0.0 82.1630859375 82.1630859375 0 0
stats: connect 200 1.3886572265624997 3.442436301013272 46.936767578125 0.287109375 0 0
stats: match_stop 199 199
stats: nomatch 1 1
stats: size_rcv 197363 197363
stats: match 199 199
stats: size_sent 59892 59892
stats: connected 0 0
# stats: dump at 1429585758
stats: users 0 4
stats: session 0 0 0 134.97998046875 2.526123046875 9.99697875976563 200
stats: users_count 0 200
stats: finish_users_count 0 200
stats: request 0 0 0 88.15087890625 0.197998046875 3.4125093759741274 401
stats: page 0 0 0 82.1630859375 82.1630859375 82.1630859375 1
stats: connect 0 0 0 46.936767578125 0.287109375 1.3886572265624997 200
stats: match_stop 0 199
stats: nomatch 0 1
stats: size_rcv 0 197363
stats: match 0 199
stats: size_sent 0 59892
stats: connected 0 0
EndMonitor:{1429,585758,181923}

**Comment by h264g729** [comment]
the jabber_register.xml is below:
![tsung](https://cloud.githubusercontent.com/assets/13571700/8983426/d09a2988-36fc-11e5-9ef9-e880c5a3fdd9.png)

**Comment by mremond** [comment]
This is a ticket relating to Tsung, not to ejabberd.

**Comment by h264g729** [comment]
I think it is the problem of ejabberd,I tried the same script(jabber_register.xml) to connect to openfire,the result is that:lots of users be created .but when connecting to ejabberd,only one user be created.

**Comment by sezuan** [comment]
I think you have to use SASL authentication. Try something like:

    <request><jabber type="connect" ack="local"></jabber> </request>
    <thinktime value="5"></thinktime>
    <transaction name="authenticate">
      <request><jabber type="auth_sasl" ack="local"></jabber></request>
      <request><jabber type="connect" ack="local"></jabber></request>
      <request><jabber type="auth_sasl_bind" ack="local" ></jabber></request>
      <request><jabber type="auth_sasl_session" ack="local" ></jabber></request>
    </transaction>

**Comment by mremond** [comment]
I think the question is more accurately: "How can I create create 200k accounts in ejabberd"

The default behaviour is that you cannot, because it is bad to let anyone create 200k accounts on your server. It is likely for spam.

My guess is that you did not configure ejabberd to remove that spam prevention mechanism. You should look at `mod_register` documentation: http://docs.ejabberd.im/admin/guide/configuration/#modregister

> This module reads also another option defined globally for the server:
> `registration_timeout: Timeout`. This option limits the frequency of
> registration from a given IP or username. So, a user that tries to
> register a new account from the same IP address or JID during this
> number of seconds after his previous registration will receive an error
> `resource-constraint` with the explanation: “Users are not allowed to
> register accounts so quickly”. The timeout is expressed in seconds, and
> it must be an integer. To disable this limitation, instead of an integer
> put a word like: `infinity`. Default value: 600 seconds.

**Comment by h264g729** [comment]
I come to say thank you this time ,thank you very very much! I add {registration_timeout, infinity} in ejabberd.cfg,then it works!!

**Comment by mremond** [comment]
Very good news and thanks for the feedback :+1:
