### ISSUE TITLE
Need to drop user nickname tag on groupchat messages

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#686]
Reading [XEP-0172 User Nickname](http://xmpp.org/extensions/xep-0172.html#former), I think it may be wise to drop user nickname packet extension on groupchat messages send to MUC.

If a receiving client receive a user nickname tag inside the message, it may choose to render it instead of the room nick itself. This could cause some nick spoofing issues.

**Comment by badlop** [comment]
Do you mean that a client with XEP-0172 support maybe sends message stanzas to a room with Nick extension, and it would confuse the other room occupants clients to receive this?
```
<message from='room1@conference.localhost/ishma'
	to='user2@localhost/tka'
	type='groupchat'>
  <body>message</body>
  <nick xmlns='http://jabber.org/protocol/nick'>Ishmael</nick>
</message>
```

**Comment by zinid** [comment]
@badlop exactly.

**Comment by devilankur18** [comment]
@badlop @zinid  This change have affected my usecase. I am new to this so please bear with me.

My usecase is of a public chat with a custom xmpp client, in which nickname is sets by the client automatically. So if someone join a public chat, and add a message, others should be able to see the nickname, right away.

Is there any other way I can enable nick names with messages or fetch fetch nicknames for a specific jid.

**Comment by badlop** [comment]
If you administer that server, the most obvious workaround is that you revert that change, so the nick isn't removed.

If the nickname is stored by that client in the user's vcard, another client can query the user's vcard, see http://xmpp.org/extensions/xep-0054.html#sect-idp655232
