### ISSUE TITLE
Wrong packet created no closing element

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#687]
I am creating custom packet where as 
XmlBody =#xmlel{name = <<"custom">>,
    attrs = [{<<"to">>, To},{<<"t">>, "dummy"},{<<"id">>, ReceiptId},{<<"time">>,getTimeInt()},{<<"q">>, Isquick}],
    children =[]
    },

When it sends over the connection it sends as 
 Send XML on stream = '\<custom from='dummy.com' to='xxxxx@server/resoucerce:' t='sa' id='6177764630472404992-3' time='1438372915' q='0'/\>'

should it not be instead

 Send XML on stream = "\<custom from='dummy.com' to='xxxxx@server/resoucerce:' t='sa' id='6177764630472404992-3' time='1438372915' q='0 \<'/custom\>"

what wrong am i doing ?

**Comment by weiss** [comment]
> When it sends over the connection it sends as
>
> `Send XML on stream = "<custom from='dummy.com' to='xxxxx@server/resoucerce:' t='sa' id='6177764630472404992-3' time='1438372915' q='0'/>"`

Quoting the [Wikipedia article on XML][1]:

> A markup construct that begins with `<` and ends with `>`. Tags come in three flavors:
>
> * start-tags; for example: `<section>`
> * end-tags; for example: `</section>`
> * empty-element tags; for example: `<line-break />`

What you quoted above is an example of an empty-element tag.

[1]: https://en.wikipedia.org/wiki/XML#Key_terminology

**Comment by nOmi7** [comment]
thanks for the info but how do i get  \</section\>  instead of line breakl in ejabberd

**Comment by zinid** [comment]
@nOmi7 put empty `{xmlcdata, <<>>}`.
