### ISSUE TITLE
Installer should show the hostname define at install time in HTML summary launch file

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#688]
It seems people sometime have ejabberd configured with an host which is not the one they expect when they try to authenticate on admin interface.

It seems to be a source of confusion. Adding the host on the main generated HTML (or someone else) may help those users.

**Comment by cromain** [comment]
the generated start.html, which is displayed in browser if ejabberd has been started with the 'start' script, include this information already:
<p>Users can connect to your server '@@DOMAIN@@' with any Jabber/XMPP client.
Direct registration from the user client is enabled by default.</p>
<p>The name of the current ejabberd node is <i>ejabberd@@@HOSTNAME@@</i>.</p>

this is not displayed by command line tool 'ejabberdctl start' anyway. maybe can we let ejabberdctl start or status display configured vhosts.

**Comment by cromain** [comment]
ejabberdctl start can not display feedback as it just trigger ejabberd application start.
and we have a function for this to get the list of registered vhosts on command line:
ejabberdctl registered_vhosts

so we already have the info at several layer of the application.
