### ISSUE TITLE
Why deps repositories configured without version number?

### ISSUE THREAD

**Issue by zhuzhang** [processone/ejabberd#689]
The deps repository is configured in *rebar.config.script* file, but without version number. So when I rebuild the project, it will always pull the newest repositories.  
So the question comes: how can it make sure that the build will always be successful with different version of deps?

**Comment by weiss** [comment]
> The deps repository is configured in _rebar.config.script_ file, but without version number.

If you build from the Git repository, yes.  In the [official release tarball][1], the dependency versions are fixed.

> how can it make sure that the build will always be successful with different version of deps?

You might want to use the [tools/set-dep-versions][2] script, which specifies the currently downloaded dependency versions in the rebar.config.script file. 

[1]: https://www.process-one.net/en/ejabberd/downloads/
[2]: https://raw.githubusercontent.com/processone/ejabberd/master/tools/set-dep-versions
