### ISSUE TITLE
Problems in SIP module.

### ISSUE THREAD

**Issue by S-o-T** [processone/ejabberd#690]
I am trying to use ejabberd sip module and have i some problems. I am using the example config from http://docs.ejabberd.im/admin/guide/configuration/#sip and mod_sip: [] in modules list. When i am trying to connect to my server (via MicroSIP client) i get "Wrong Password" message if i pass the nonexistent username. If i am passing any existent username i get "Internal server error" and in the error log file the next lines are appears (i made some replacements):

2015-08-01 19:36:57.487 [error] <0.589.0> (<0.589.0>:esip:599) failed to process callback:
** Function: mod_sip:message_in/2
** Args: [{sip,request,{2,0},<<"REGISTER">>,[{via,[{via,<<"SIP">>,{2,0},<<"TLS">>,<<"my_internal_ip">>,26077,[{<<"branch">>,<<"z9hG4bKPj1d7128f15eaf43f196c76dca1f3e98db">>},{<<"alias">>,<<>>},{<<"received">>,<<"my_external_ip">>},{<<"rport">>,<<"26077">>}]}]},{route,[{<<>>,{uri,<<"sip">>,<<>>,<<>>,<<"my_server_adress">>,undefined,[{<<"transport">>,<<"tls">>},{<<"lr">>,<<>>}],[]},[]}]},{'max-forwards',70},{from,{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_server_adress">>,undefined,[],[]},[{<<"tag">>,<<"775f050bbf09421c9c74e290c9af469d">>}]}},{to,{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_server_adress">>,undefined,[],[]},[]}},{'call-id',<<"4e5eda3a174347cb958ad8469b639843">>},{cseq,47174},{'user-agent',<<"MicroSIP/3.10.1">>},{supported,[<<"outbound">>,<<"path">>]},{contact,[{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_internal_ip">>,26077,[{<<"transport">>,<<"TLS">>},{<<"ob">>,<<>>}],[]},[{<<"reg-id">>,<<"1">>},{<<"+sip.instance">>,<<"\"<urn:uuid:00000000-0000-0000-0000-00003ed6b8ba>\"">>}]}]},{expires,300},{allow,[<<"PRACK">>,<<"INVITE">>,<<"ACK">>,<<"BYE">>,<<"CANCEL">>,<<"UPDATE">>,<<"INFO">>,<<"SUBSCRIBE">>,<<"NOTIFY">>,<<"REFER">>,<<"MESSAGE">>,<<"OPTIONS">>]},{authorization,{<<"Digest">>,[{<<"username">>,<<"\"test1\"">>},{<<"realm">>,<<"\"my_server_adress\"">>},{<<"nonce">>,<<"\"9c9aa1b080e8f27ceb1459c0ea506da559620da9\"">>},{<<"uri">>,<<"\"sip:my_server_adress;transport=tls\"">>},{<<"response">>,<<"\"c8add20a8a34e5742a7a223143dc7b10\"">>},{<<"cnonce">>,<<"\"eeb0ce89caa1418596f507a0bd5935b2\"">>},{<<"qop">>,<<"auth">>},{<<"nc">>,<<"00000001">>}]}},{'content-length',0}],<<>>,{uri,<<"sip">>,<<>>,<<>>,<<"my_server_adress">>,undefined,[{<<"transport">>,<<"tls">>}],[]},undefined,undefined},{sip_socket,tls,{tlssock,#Port<0.4004>,#Port<0.4005>},{{my_server_ip},5061},{{my_external_ip},26077},<0.589.0>}]
** Reason: {'EXIT',{badarg,[{erlang,md5,[[<<"test1">>,58,<<"my_server_adress">>,58,{<<172,63,206,245,147,148,121,173,233,202,2,143,43,21,56,161,218,139,196,147>>,<<146,127,172,210,172,242,82,28,144,216,247,95,39,18,213,19,40,163,200,17>>,<<223,234,65,116,35,96,80,138,159,0,21,68,176,45,77,47>>,4096}]],[]},{esip,md5_digest,1,[{file,"src/esip.erl"},{line,841}]},{esip,compute_digest,11,[{file,"src/esip.erl"},{line,861}]},{esip,check_auth,4,[{file,"src/esip.erl"},{line,542}]},{mod_sip,action,2,[{file,"src/mod_sip.erl"},{line,191}]},{mod_sip,message_in,2,[{file,"src/mod_sip.erl"},{line,83}]},{esip,callback,3,[{file,"src/esip.erl"},{line,594}]},{esip_transport,recv,2,[{file,"src/esip_transport.erl"},{line,58}]}]}}
2015-08-01 19:36:57.488 [error] <0.592.0> (<0.592.0>:esip:599) failed to process callback:
** Function: mod_sip:request/3
** Args: [{sip,request,{2,0},<<"REGISTER">>,[{via,[{via,<<"SIP">>,{2,0},<<"TLS">>,<<"my_internal_ip">>,26077,[{<<"branch">>,<<"z9hG4bKPj1d7128f15eaf43f196c76dca1f3e98db">>},{<<"alias">>,<<>>},{<<"received">>,<<"my_external_ip">>},{<<"rport">>,<<"26077">>}]}]},{route,[{<<>>,{uri,<<"sip">>,<<>>,<<>>,<<"my_server_adress">>,undefined,[{<<"transport">>,<<"tls">>},{<<"lr">>,<<>>}],[]},[]}]},{'max-forwards',70},{from,{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_server_adress">>,undefined,[],[]},[{<<"tag">>,<<"775f050bbf09421c9c74e290c9af469d">>}]}},{to,{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_server_adress">>,undefined,[],[]},[]}},{'call-id',<<"4e5eda3a174347cb958ad8469b639843">>},{cseq,47174},{'user-agent',<<"MicroSIP/3.10.1">>},{supported,[<<"outbound">>,<<"path">>]},{contact,[{<<>>,{uri,<<"sip">>,<<"test1">>,<<>>,<<"my_internal_ip">>,26077,[{<<"transport">>,<<"TLS">>},{<<"ob">>,<<>>}],[]},[{<<"reg-id">>,<<"1">>},{<<"+sip.instance">>,<<"\"<urn:uuid:00000000-0000-0000-0000-00003ed6b8ba>\"">>}]}]},{expires,300},{allow,[<<"PRACK">>,<<"INVITE">>,<<"ACK">>,<<"BYE">>,<<"CANCEL">>,<<"UPDATE">>,<<"INFO">>,<<"SUBSCRIBE">>,<<"NOTIFY">>,<<"REFER">>,<<"MESSAGE">>,<<"OPTIONS">>]},{authorization,{<<"Digest">>,[{<<"username">>,<<"\"test1\"">>},{<<"realm">>,<<"\"my_server_adress\"">>},{<<"nonce">>,<<"\"9c9aa1b080e8f27ceb1459c0ea506da559620da9\"">>},{<<"uri">>,<<"\"sip:my_server_adress;transport=tls\"">>},{<<"response">>,<<"\"c8add20a8a34e5742a7a223143dc7b10\"">>},{<<"cnonce">>,<<"\"eeb0ce89caa1418596f507a0bd5935b2\"">>},{<<"qop">>,<<"auth">>},{<<"nc">>,<<"00000001">>}]}},{'content-length',0}],<<>>,{uri,<<"sip">>,<<>>,<<>>,<<"my_server_adress">>,undefined,[{<<"transport">>,<<"tls">>}],[]},undefined,undefined},{sip_socket,tls,{tlssock,#Port<0.4004>,#Port<0.4005>},{{my_server_ip},5061},{{my_external_ip},26077},<0.589.0>},{trid,<0.592.0>,server}]
** Reason: {'EXIT',{badarg,[{erlang,md5,[[<<"test1">>,58,<<"my_server_adress">>,58,{<<172,63,206,245,147,148,121,173,233,202,2,143,43,21,56,161,218,139,196,147>>,<<146,127,172,210,172,242,82,28,144,216,247,95,39,18,213,19,40,163,200,17>>,<<223,234,65,116,35,96,80,138,159,0,21,68,176,45,77,47>>,4096}]],[]},{esip,md5_digest,1,[{file,"src/esip.erl"},{line,841}]},{esip,compute_digest,11,[{file,"src/esip.erl"},{line,861}]},{esip,check_auth,4,[{file,"src/esip.erl"},{line,542}]},{mod_sip,action,2,[{file,"src/mod_sip.erl"},{line,191}]},{mod_sip,request,3,[{file,"src/mod_sip.erl"},{line,113}]},{esip,callback,3,[{file,"src/esip.erl"},{line,594}]},{esip_server_transaction,trying,2,[{file,"src/esip_server_transaction.erl"},{line,90}]}]}}

**Comment by zinid** [comment]
Seems like the password is scrammed, so it won't be possible to use the same credentials via SIP.

**Comment by S-o-T** [comment]
So, what is the way to use that configuration (as i mentioned, when i trying to login with new username and pass my sip client is saying "Wrong password" and the logs on the server-side are clear)? Or it is impossible to use a sip module when a "auth_password_format: scram" was stated?

**Comment by zinid** [comment]
Yes, it's impossible to use mod_sip when auth format is scram

**Comment by zinid** [comment]
I fixed the crash and added a log message reporting that SIP authentication is not available when password is scrammed (f37799223209e428310017829129dbf7f986bb1e).

**Comment by mremond** [comment]
@zinid Thanks. I also made it clear in ejabberd guide: https://github.com/processone/docs.ejabberd.im/commit/6fc962df8b13e6eeddc428c557ca0c92ed9afd03

**Comment by zinid** [comment]
@mremond I would add more general note to SCRAM authentication section that any foreign auth methods (SIP, TURN and any others added in the future) will not be working with SCRAM.

**Comment by mremond** [comment]
Done: https://github.com/processone/docs.ejabberd.im/commit/6f4cd73dca05f808c03555caa5b9d2675b80ad3c

Is that fine ?

**Comment by zinid** [comment]
@mremond  Yes, absolutely. Thank you very much.
