### ISSUE TITLE
Ubuntu 14.04 LTS installer issue

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#691]
Issue reported here: https://www.ejabberd.im/forum/25032/ejabberd-1507-has-been-released

> I am having following issue while trying to install Ejabberd 15.07 on Ubuntu server. I have tried on two different machines. I have tried both with SU user and without SU user.

```
./ejabberd_15.07-0_amd64.deb
./ejabberd_15.07-0_amd64.deb: line 1: syntax error near unexpected token `newline'
./ejabberd_15.07-0_amd64.deb: line 1: `!< arch >'
```

**Comment by naeems** [comment]
In addition to this I have tried .run file also and got following error.

Please wait while Setup installs ejabberd on your computer.

 Installing
 0% ______________ 50% ______________ 100%
 ########################################
Error: Error running Post Install Script.
The installation may have not completed correctly
Press [Enter] to continue:

**Comment by timpisti** [comment]
This appear at Debian8, and Ububntu 15.05 too.

**Comment by MurzNN** [comment]
Confirm this problem on Ubuntu 14.04. Package extract sucessfully, but after this - fails on `postinst` script:
```
/opt/bitrock/ejabberd-15.07-0/helperBinary --mode unattended --rpmstage postinstall
Error running Post Install Script.
The installation may have not completed correctly
```
Is there any debug or verbose mode available for `helperBinary`  to understand where is the problem?

**Comment by MurzNN** [comment]
Here is same issue on Debian: https://github.com/processone/ejabberd/issues/710

**Comment by cromain** [comment]
fixed: 15.09 package will include the fix

**Comment by mk-pmb** [comment]
"Error running Post Install Script." ejabberd_16.01-0_amd64.deb on Ubuntu 14.04.3 LTS

```text
root@…# dpkg -i ejabberd_16.01-0_amd64.deb
Selecting previously unselected package ejabberd.
(Reading database ... 115575 files and directories currently installed.)
Preparing to unpack ejabberd_16.01-0_amd64.deb ...
Unpacking ejabberd (16.01-0) ...
Setting up ejabberd (16.01-0) ...
Error running Post Install Script.
The installation may have not completed correctly

root@…# service ejabberd start
ejabberd: unrecognized service

root@…# lsb_release -sd
Ubuntu 14.04.3 LTS
```

How do I enable failure reasons in installer error messages?

I also tried the *.run installer, same problem.

**Comment by mk-pmb** [comment]
I tried changing my `/bin/sh.distrib` symlink to `bash` as suggested in #710, still same error.

**Comment by mk-pmb** [comment]
> fixed: 15.09 package will include the fix

Even tried that, no luck either.
```text
# dpkg -i ejabberd_15.09-0_amd64.deb
[…]
Setting up ejabberd (15.09-0) ...
Error running Post Install Script.
The installation may have not completed correctly
```

**Comment by mremond** [comment]
Why don't you try 16.01 ?

**Comment by mk-pmb** [comment]
> Why don't you try 16.01 ?

I thought I did? At least I expected that's what I expected to get in `ejabberd_16.01-0_amd64.deb` (my initial report above).

**Comment by cromain** [comment]
i'll do some more tests on few different linux flavours

**Comment by cromain** [comment]
i tested ejabberd-16.02 on Ubuntu 14.04.4 LTS, Debian wheezy, Debian jessie, CentOS 7.1.
I could not reproduce post-installation issue.
Anyway, i patched post-install script so it does not raise error if ejabberd could not start, as this can be due to several reasons, and does not mean installation failed. This will also enforce unattended installs.
