### ISSUE TITLE
Multicast: is empty addresses tag correct? ?

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#693]
When sending a multicast packet with multiple BCC recipient, the resulting multicast packet ends up containing and empty addresses tag.

For example, sending:

```xml
<presence to='multicast.localhost'>
    <addresses xmlns='http://jabber.org/protocol/address'>
        <address type='bcc' jid='user1@localhost'/>
        <address type='bcc' jid='user2@localhost'/>
    </addresses>
</presence>
```

is received as:

```xml
<presence from="admin@localhost/laptop" xml:lang="en" to="user1@localhost/laptop">
   <addresses xmlns="http://jabber.org/protocol/address">
   </addresses> 
</presence>
```

I think when the addresses is empty, it should not be attached to XMPP packet. This also hide complexity for client, avoiding leaking [XEP-0033 Extended Stanza Addressing](http://xmpp.org/extensions/xep-0033.html) support. In that case, receiving client does not need to know about it.

**Comment by badlop** [comment]
This got fixed in recent commit 4125dfd166067b4c613bd8d49eef5f876fdb1b94.
