### ISSUE TITLE
multiple packtes rcvd when doing multicast route

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#695]
I created a custom packet where i need to send it to all users subscriptions
for which i used
```erlang
 {Fs, Ts} = ejabberd_hooks:run_fold(roster_get_subscription_lists,Server,{[], []},[User, Server]),
  LJID = jlib:jid_tolower(jlib:jid_remove_resource(_From)),
  Fs1 = [LJID | Fs],
  Ts1 = [LJID | Ts],
  IFollow = (?SETS):from_list(Fs1),
  Followers = (?SETS):from_list(Ts1),

create_and_broadcast(From, Server, Packet ,Followers,IFollow,State)->
  #xmlel{name = Name , attrs = Attrs,children = Child } = Packet,
  To = xml:get_attr_s(<<"to">>,Attrs),
  NewAttrs =lists:delete({<<"to">>,To},Attrs),
  NewPacket=#xmlel{name = Name,attrs=NewAttrs,children =Child},
  JIDs = ?SETS:to_list(Followers),
  JIDs2 = format_and_check_privacy(From, State, NewPacket, JIDs, out),
  ?DEBUG("New broadcast Packet ~p",[JIDs2]),
  ejabberd_router_multicast:route_multicast(From, Server, JIDs2, NewPacket).
```

When i do this if the users subcription is online it send the packet which what i expected 
however when all are offline it send the multiple packet the to the  From (user which send the custom packet)

When i do this it sends packet back to the person who sent the packet.

Send XML on stream = \<\<"\<collecter from='testsource@s.mycompany.com/A:1.0:' to='testsource@s.mycompany.com/A:1.0:' xml:lang='en' id='6178779665019795456-389' t='n' ln='pand' fn='col' time='0'/\>"\>\>

Send XML on stream = \<\<"\<collecter from='testsource@s.mycompany.com/A:1.0:' to='testsource@s.mycompany.com/A:1.0:' xml:lang='en' id='6178779665019795456-389' t='n' ln='pand' fn='col' time='0'/\>"\>\>

Send XML on stream = \<\<"\<collecter from='testsource@s.mycompany.com/A:1.0:' to='testsource@s.mycompany.com/A:1.0:' xml:lang='en' id='6178779665019795456-389' t='n' ln='pand' fn='col' time='0'/\>"\>\>

Send XML on stream = \<\<"\<collecter from='testsource@s.mycompany.com/A:1.0:' to='testsource@s.mycompany.com/A:1.0:' xml:lang='en' id='6178779665019795456-389' t='n' ln='pand' fn='col' time='0'/\>"\>\>

**Comment by mremond** [comment]
Can you please explain your issue ? Your description is empty.

**Comment by nOmi7** [comment]
Sorry ti was by mistake

**Comment by nOmi7** [comment]
@mremond  added the desc thanks for the fast response

**Comment by zinid** [comment]
@nOmi7 please use Markdown syntax highlighting for code snippets. I fixed your comment partially.

**Comment by nOmi7** [comment]
Sure thanks will take care next time . @zinid 
Any ideas why its sending packet multiple times ? any pointers will relaly help my to sovle my issue @mremond  , @zinid

**Comment by mremond** [comment]
Are you really sure you want to route multicast ? multicast router is internal. I expect that you should use ejabberd_router.

**Comment by nOmi7** [comment]
@mremond  i used it looking at the c2s code for presence broadcast 
```
send_multiple(From, Server, JIDs, Packet) ->
    ejabberd_router_multicast:route_multicast(From, Server, JIDs, Packet)
```
and i used the same 
as u see above in my code .

**Comment by mremond** [comment]
Well, so you did not pick the right example probably. You need to use `ejabberd_route:route/3`.

**Comment by nOmi7** [comment]
@mremond  if i use  ``` ejabberd_route:route/3 ``` will this do the broadcast to multiple jids? 
i thougth route multicast is meant for it

**Comment by mremond** [comment]
You should iterate on your list of JID using ejabberd_router. Multicast is purely an internal optimisation.

**Comment by nOmi7** [comment]
ok thanks @mremond  this helps
