### ISSUE TITLE
Issue with Client status indicator extension (XEP-0352)

### ISSUE THREAD

**Issue by aparna-v** [processone/ejabberd#700]
As per documentation, https://www.ejabberd.im/protocols , XEP-0352 is supported.
But I get the 'Client State Indication not supported by server' exception with Smack android client when I try to indicate inactive status, like so:
       try {
            ClientStateIndicationManager.inactive(connection);
          }
            catch (SmackException e) {
            e.printStackTrace();
            }
                catch ( InterruptedException e){
        }
I am using ejabberd 15.06.

**Comment by weiss** [comment]
> As per documentation, <https://www.ejabberd.im/protocols>, XEP-0352 is supported.

Indeed, it is.  Just to make sure: Is `mod_client_state` enabled in your configuration?  I.e.:

    modules:
      # [...]
      mod_client_state:
        drop_chat_states: true
        queue_presence: true

**Comment by aparna-v** [comment]
That's exactly what I was missing. Verified.
Thanks

**Comment by weiss** [comment]
Thanks for the feedback.
