### ISSUE TITLE
Building an ejabberd release in an elixir app complains because there are multiple idna modules defined

### ISSUE THREAD

**Issue by knewter** [processone/ejabberd#701]
I'm not sure if there's an easier way to reproduce this, but I have an app with ejabberd embedded alongside phoenix, and when I try to use `exrm` to build a release, I get the following error when I do `mix release --verbosity=verbose`

```
===> Including Erts from /home/jadams/erlang/erlangs/18.0
===> Provider (release) failed with: {error,
                                             {rlx_prv_assembler,
                                              {release_script_generation_error,
                                               systools_make,
                                               {duplicate_modules,
                                                [{{idna,idna,
                                                   "/home/jadams/projects/some_app/rel/some_app/lib/idna-1.0.2/ebin"},
                                                  {idna,ejabberd,
                                                   "/home/jadams/projects/some_app/rel/some_app/lib/ejabberd-15.06.0/ebin"}}]}}}}
==> Failed to build release. Please fix any errors and try again.
```

I'm not sure how to go about resolving this but thought you might have pointers.

**Comment by mremond** [comment]
We did not yet play with Elixir release, but we will have a look as soon as possible.

**Comment by knewter** [comment]
OK.  Is it true that similar errors don't crop up when embedding ejabberd in another erlang application and building a release?  I haven't tried that yet.

**Comment by mremond** [comment]
No idea, tried release of embedded ejabberd into another application either. Possible that this causes the same error.

**Comment by scrogson** [comment]
@knewter it only complains when making a release? What about on `mix compile`? Generally I've had to add `override: true` to some deps to get it to compile.

**Comment by knewter** [comment]
@scrogson nope, not during compile.  Just on the release.

On Mon, Aug 10, 2015 at 11:33 AM, Sonny Scroggin <notifications@github.com>
wrote:

> @knewter <https://github.com/knewter> it only complains when making a
> release? What about on mix compile? Generally I've had to add override:
> true to some deps to get it to compile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/701#issuecomment-129518844>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by rhalukongor** [comment]
I'm experiencing the same problem in a different scenario:

I use HTTPoison for one of my modules. The problem is HTTPoison depends on Hackney which depends on [erlang-idna](https://github.com/tim/erlang-idna). Now I have 2 Idna modules. Somehow my local build works (not throughly tested though; may be overriding p1 version) but I can't move my code to server. I'll be happy to come with a PR in case you guys decide on a new module name. Also I'd be super happy if you Erlang masters let me know if VM provides a way to allow multiple modules with the same name. I'm stuck with this and have deadline approaching.

**Comment by badlop** [comment]
Similar idna module name duplication in #702.

**Comment by mremond** [comment]
@knewter does your app depends on httpoison ? Doing a release on an empty elixir ejabberd project works well from my test.

**Comment by knewter** [comment]
i'm actually going to modify my strategy and not embed ejabberd itself into
my application, and just interact with clients of it via hedwig.  any other
behaviour i need i'll build in but won't be pulling in other dependencies,
so i shouldn't run into problems here.  but in general, the problem was
related to idna module name duplication.

On Tue, Sep 1, 2015 at 12:08 PM, Mickaël Rémond <notifications@github.com>
wrote:

> @knewter <https://github.com/knewter> does your app depends on httpoison
> ? Doing a release on an empty elixir ejabberd project works well from my
> test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd/issues/701#issuecomment-136798754>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by mremond** [comment]
@knewter Thanks for feedback. Anyway, we have avoided the possible name clash with idna in that commit: https://github.com/processone/ejabberd/commit/6740b1f0e1e96fb7ee04fd4046c180c35c9f370d
