### ISSUE TITLE
Can't use Hackney for module development because of duplicate module name: idna

### ISSUE THREAD

**Issue by rhalukongor** [processone/ejabberd#702]
I use HTTPoison for one of my modules. The problem is HTTPoison depends on Hackney which depends on [erlang-idna](https://github.com/tim/erlang-idna). Now I have 2 Idna modules.

Somehow my local build works (not throughly tested though; may be overriding p1 version) but I can't move my code to server. I had to fork the source to get around this renaming the idna module and its refs. I'll be happy to come with a PR in case you guys decide on a new module name.

Also I'd be super happy if you Erlang masters let me know if VM provides a way to allow multiple modules with the same name.

**Comment by zinid** [comment]
Renamed in 6740b1f0e1e96fb7ee04fd4046c180c35c9f370d
