### ISSUE TITLE
mod_mam (Message Archive Management, XEP-0313) doesnt work correctly

### ISSUE THREAD

**Issue by Myppomeu** [processone/ejabberd#703]
Debian 8 x64, Ejabberd 15.07, MySQL 5.6.25-3. Clean install.
Mysql base structure imported from this file:
[https://github.com/processone/ejabberd/blob/master/sql/mysql.sql](https://github.com/processone/ejabberd/blob/master/sql/mysql.sql)
with mysql -D ejabberd -h localhost -p -u ejabberd < ./mysql.sql (no errors appears).
```
# cat /opt/ejabberd-15.07/conf/ejabberd.yml
...
auth_method: internal
...
odbc_type: mysql
odbc_server: "localhost"
odbc_port: 3306
odbc_database: "ejabberd"
odbc_username: "ejabberd"
odbc_password: "PASSWORD"
...
mod_mam:
    default: always
    db_type: odbc
...
```
Clients:
1. Ilia
a. Gajim 0.16.3 on Debian 8 x64
b. Conversations 1.5.2 on Android 4.1.2
2. Psi
a. Gajim 0.16.3 on Debian 8 x64

Messages correctly writes in database in archive table (I can see them through phpmyadmin, for example). No new errors in /opt/ejabberd-15.07/logs/error.log appears.
But clients (Gajim and Conversations) dont receive messages from database. Tried to clean all Gajim profile folders and create new profile - same result.
Same result if I choose to store messages in mnesia database.
Mod_mam_mnesia from contrib works, but I'd like to use official module.

I can give you log (with loglevel 5) from starting ejabberd to stopping it.

**Comment by zinid** [comment]
There were tons of bugs fixed since then. You may want to try the version from git or wait for the new release.

**Comment by Myppomeu** [comment]
Cant compile, it ends with
```
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
```
and no ejabberd binary appears.
So will wait for next version or fix for this issue.

**Comment by Myppomeu** [comment]
In git version (compiled with --enable-mysql of course) doesnt work too. It even not writes messages in DB (version 15.07 writes).

**Comment by langzi88** [comment]
Use ejabberd-contrib mod_mam_mnesia.erl module，I test it ok！

**Comment by FlowerWrong** [comment]
I am using ejabberd 15.07 and the mod_mam worked.

```ruby
auth_method: odbc

  ## http://docs.ejabberd.im/admin/guide/configuration/#modmam
  mod_mam:
    db_type: odbc
    default: always
```

**Comment by NeoElit** [comment]
mod_mam is working fine with personal messaging.
However I'm unable to retrieve muc mam messages through usual iq queries. It return empty result.
While sending... iq like following:
```xml
<iq type='set' id='juliet1'>
  <query xmlns='urn:xmpp:mam:0'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:mam:0</value>
      </field>
      <field var='with'>
        <value>room@conference.999network.com</value>
      </field>
    </x>
  </query>
</iq>
```
will generate an archive search for matching username=<iq senders id> and bare_peer=room@conference.999network.com'. But for muc archives the recipient username will be the <room id>.... which results in returning empty result. 
Is this a bug or is there any other way to query an muc archive?

**Comment by zinid** [comment]
@NeoElit you should send that `iq` to MUC room jid directly, e.g.
```xml
<iq type='set' id='juliet1' to='room@conference.999network.com'>
  <query xmlns='urn:xmpp:mam:0'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:mam:0</value>
      </field>
    </x>
  </query>
</iq>
```

**Comment by NeoElit** [comment]
i tried that, but then server is returning feature not implemented error.

**Comment by zinid** [comment]
You should use codebase from `master` branch, no releases support this.

**Comment by NeoElit** [comment]
I tried that too.. now its not even archiving.
My conf file is as in this link: http://pastie.org/10381316

**Comment by zinid** [comment]
Did you enable archiving in your conference? There is a new configuration option should be occured in a room configuration "Enable message archiving". You can also set it by default via default configuration options for mod_muc.

**Comment by Myppomeu** [comment]
FlowerWrong, tried to change from my variant of configuration to yours, gain same results as I described in issue.
NeoElit, what programms you use? (SQL and xmpp client)

**Comment by FlowerWrong** [comment]
@Myppomeu I am using smack 4.1.3, mysql 5 and ejabberd 15.07.

1. If you are using muc, you can not get any offline message at all. There is no way. It is described in [XEP-45](http://xmpp.org/extensions/xep-0045.html).
2. If you are using just one-to-one chat. I can get offline message. Tomorrow I will show you the log.

**Comment by FlowerWrong** [comment]
There are two users named `registeruser` and `registeruser2`. Maybe it is a badname. :disappointed: 
And they are boty offline. Then `registeruser` sent a message to `registeruser2`. Then `registeruesr2` login and `addChatListener`.
```java
        ChatManager.getInstanceFor(connection).addChatListener(new ChatManagerListener() {
            @Override
            public void chatCreated(Chat chat, boolean createdLocally) {
                chat.addMessageListener(new ChatMessageListener() {
                    @Override
                    public void processMessage(Chat chat, Message message) {
                        System.out.println("========================" + message.getFrom() + " : " + message.getBody());
                    }
                });
            }
        });
```
The log is:
![2015-08-29 10 26 02](https://cloud.githubusercontent.com/assets/5362640/9560148/698747be-4e38-11e5-9d43-b3d8166b6050.png)

In mysql, the log is:
![2015-08-29 10 21 16](https://cloud.githubusercontent.com/assets/5362640/9560149/775dc408-4e38-11e5-8fd6-ffd790514276.png)

But I have a quesiton, why there are two messages?

**Comment by zinid** [comment]
> But I have a quesiton, why there are two messages?

Because the first message belongs to `registeruser` and the second to `registeruser2`, you can see that in the first column.

**Comment by NeoElit** [comment]
@zinid where do i get new config options. It's not listed in http://docs.ejabberd.im/admin/guide/configuration/#modmuc and I have mod_mam conf as follows:
```yaml
  mod_mam:
    iqdisc: one_queue
    db_type: odbc
    default: always
```

**Comment by NeoElit** [comment]
@Myppomeu I'm using mysql for db and smack as client on android.

**Comment by FlowerWrong** [comment]
@NeoELit The official smack does not support XEP-313 of mam. You can use the [fock one](https://github.com/Flowdalic/Smack) which support it.

**Comment by NeoElit** [comment]
Ya, but i'm using custom iq to query my archive.
But my problem is with server not archiving the sent messages 😞

**Comment by zinid** [comment]
@NeoElit the option is `mam: true`. Regarding direct message archiving: did you alter SQL table after the update from `master` branch?

**Comment by NeoElit** [comment]
Yup.. good it's working.
But it's even archiving the chat-states 😞
And is there anyway to disable mam for direct messages?

**Comment by nunohorta** [comment]
@NeoElit what did you ended up doing to query the archive for muc messages? I'm getting the same results as you, either its 0 or feature-not-implemented. But I couldn't understand what did you change.

**Comment by NeoElit** [comment]
@nunohorta as @zinid said, ejabberd master branch supports mam for muc. Just set flag mam: true inside muc default config options and enable mod_mam. Also update db tables.

Now I'm stuck with smack where MAM is not yet supported.
I tried https://github.com/Flowdalic/Smack as @FlowerWrong suggested, still i couldn't get it working as the provider for mam result was not yet implemented (empty class only). Also that branch is based on old version of smack and importing without maven repo found very difficult.

**Comment by nunohorta** [comment]
ok my problem is that I'm on 15.07 release. I will install the master branch..thanks

**Comment by nunohorta** [comment]
I've updated everything and I can now query the archive for muc messages. Somehow the messages are not on the archive mysql table anymore. Any idea why? My config:

mod_mam:
    db_type: odbc
    default: always

  mod_muc:
    db_type: odbc
    host: "chat.@HOST@"
    access: all
    access_create: muc_admin
    access_persistent: muc
    access_admin: muc_admin
    mam: true

**Comment by zinid** [comment]
@nunohorta did you alter SQL table?

**Comment by zinid** [comment]
Your config looks correct. Check your mysql database log for queries. Is ejabberd making any queries to `archive` table at all?

**Comment by zinid** [comment]
For the record, `mam: true` option will be enabled for newly created conferences only.

**Comment by nunohorta** [comment]
I created a new chat room but mam is false by default. Running the command ejabberdctl change_room_option testroom chat.localhost mam true throws an error:

Stacktrace: [{mod_muc_admin,change_option,3,
                            [{file,"src/mod_muc_admin.erl"},{line,787}]},
             {mod_muc_admin,change_room_option,3,
                            [{file,"src/mod_muc_admin.erl"},{line,771}]},
             {mod_muc_admin,change_room_option,4,
                            [{file,"src/mod_muc_admin.erl"},{line,754}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,292}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,268}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,217}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,202}]}]

Sending a message to a chat room does not call MySQL. Individual messages are saved on the archive table.

**Comment by zinid** [comment]
`ejabberdctl` command is broken in mod_muc_admin, we will fix that.
Regarding `mam: true` option: did you try to configure room to enable it? Is MAM enabled in that case for this particular room?

**Comment by nunohorta** [comment]
With the config above (mam: true in mod_muc) all rooms that I create have mam set to false (looking at muc_room table), so that's probably why is not saving any messages on the database. Since the command is broken I'm not sure how to enable MAM for a room

**Comment by zinid** [comment]
Ah, there is a problem in your config, `mam` option should be defined in under `default_room_options`, for example:
```yaml
mod_muc:
    ...
    default_room_options:
        mam: true
    ...
```

**Comment by zinid** [comment]
> Since the command is broken I'm not sure how to enable MAM for a room

So far, you can set it manually via room configurator.

**Comment by nunohorta** [comment]
ahhh you're right! now every room that I create has MAM set to true. Thank you!

**Comment by alexpetroaica** [comment]
Will this be released in the next version of ejabberd?

**Comment by zinid** [comment]
What exactly? Everything that was already commited will be released in 15.09.

**Comment by nunohorta** [comment]
Since this issue is still opened...has anyone ever noticed the archive table on mysql having duplicated entries with the exact same message(date, id, etc) but the username, peer and bare_peer are reverted? As in, user1 sends "hello" to user 2. On the archive table, I have this entry and then a duplicated one, with the same message, id and datetime, but from user2 to user1.

This is the log from ejabberd.log when I send a message https://gist.github.com/nunohorta/2f5865cd47a2a1085590

**Comment by mremond** [comment]
@nunohorta This is expected. When the two users are on the same server, a message is send and added to sender archive and a message is received and added to the recipient archive. This is two independant archives.

**Comment by nunohorta** [comment]
ah okay then. Not a problem, thanks!

**Comment by sclamage** [comment]
@zinid Sorry to belabor the point, but can you please clarify your last comment? You're saying that MUC support for MAM WILL be in 15.09? Or did I misunderstand?

**Comment by zinid** [comment]
@sclamage yes, it will be in 15.09.

**Comment by sclamage** [comment]
Thanks!!

**Comment by alexpetroaica** [comment]
I managed to activate it on 15.07 by cloning and compiling the current master branch and replacing the ebin files for mod_mam, mod_muc and mod_muc_room in my installation with the new ones. Also don't forget to alter your sql schema if you're using sql and to activate the module by adding mam: true to the default room config.

**Comment by alexpetroaica** [comment]
Is security supposed to be working in muc? I am able to retrieve the history of a room with an user which is not in the room.

**Comment by zinid** [comment]
@alexpetroaica you are right, that probably requires improvements. However, it's unclear what should they look like. I'm thinking of making archive available for affiliated users in member-only rooms and for participating users in password-protected rooms.

I am not sure why a user should not be able to retrieve archive from a public room when he's not in the room. Any reason for that?

**Comment by alexpetroaica** [comment]
I completely agree: for public rooms they can be public and for members only rooms, only the members should be allowed to retrieve them.

**Comment by cromain** [comment]
closing this thread as 15.09 covers all topics it seems.

**Comment by Myppomeu** [comment]
Checked with Ejabberd 15.09, Gajim 0.16.4 and Conversations 1.6.11 and can confirm: all works correctly.
Thanks!

**Comment by proton5000** [comment]
I get an error when working with base
@ejabberd_sql:check_error:1039 SQL query 'SELECT timestamp, xml, peer, kind, nick FROM (SELECT  timestamp, xml, peer, kind, nick FROM archive WHERE username='test' and bare_peer='misha@freldo' ORDER BY timestamp DESC  limit 21) AS t ORDER BY timestamp ASC;' failed: "#42S22Unknown column 'kind' in 'field list'"

**Comment by Ahmadhaj111** [comment]
How could I delete archived messages partially or comletely

**Comment by badlop** [comment]
> How could I delete archived messages partially or comletely

If you use Mnesia, open the ejabberd Web Admin page, go to Nodes -> your node -> Database -> and change archive_msg to delete content, then click Send.
