### ISSUE TITLE
[Feature Request] XEP-0305

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#712]
We are moving more mobile and network drops are frequent issues.
Can we have  XEP-0305  or something  like this for faster auths and reconnections it will be really helpful.

If no can there be any pointers for me to attempt faster auths in current 15.X versions which i can try to implement

**Comment by rraptorr** [comment]
XEP-0305 is deferred and seems dead. What you should be interested in is probably XEP-0198, which ejabberd supports I believe.

**Comment by nOmi7** [comment]
@rraptorr  I understand but if you XEP-0198 - http://xmpp.org/extensions/xep-0198.html#resumption 
it process of auth is still long and time consuming  198 does elminate the roster retrival and other stanza exchange however the stream opening and auth is still the same .
where as piplining is only for auths and session establishment

**Comment by rraptorr** [comment]
Well, XMPP was never really designed for mobile network and it performs rather poorly on mobile.
