### ISSUE TITLE
libyaml-0.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#713]
When trying to start ejabberd I see this error:
> "Failed to load NIF library /lib/ejabberd/priv/lib/p1_yaml: 'libyaml-0.so.2: cannot open shared object file: No such file or directory'"},

But there is file  /lib/ejabberd/priv/lib/p1_yaml.so

I build ejabberd from source with --enable-all option.

What's the problem?

**Comment by badlop** [comment]
In debian, the file libyaml-0.so.2 is provided by the package libyaml-0-2. Do you have it installed?

**Comment by Suvitruf** [comment]
I tried to install this manually:

    cd /tmp
    wget http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
    tar -xzvf yaml-0.1.6.tar.gz
    cd yaml-0.1.6
    ./configure
    make
    make install

And I got this error.

But after install from repo `sudo apt-get install libyaml-dev` error disappeared.
