### ISSUE TITLE
seems to be in use by another Erlang node

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#715]
1) I changed node name (for creating cluster) in ejabberdctl.cfg and /sbin/ejabberdctl to ejabberd@10.117.174.24
2) Removed all files in /var/lib/ejabberd
3) Removed /root/.erlang-cookie
4) Stop beam process
5) Tried to start ejabberd
6) Got error: `seems to be in use by another Erlang node",["inet_tcp"]}e name ejabberd@10.117.174.24`

Did I miss something? How can I start ejabberd with new node name?

In dump:
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}}$
System version: Erlang/OTP 17 [erts-6.1] [source-d2a4c20] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true]

But I can connect to ejabberd server with, for example, pidgin.

**Comment by Suvitruf** [comment]
Problem was cause of Windows encoding -_-

Don't use Windows editors for editing config files =/

**Comment by FlowerWrong** [comment]
:smile:
