### ISSUE TITLE
ejabberdctl registered_users returns empty list with riak backend

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#716]
`ejabberdctl registered_users localhost` shows me empty list
but `ejabberdctl connected_users` shows me:
>admin1@localhost/127.0.0.1
admin2@localhost/127.0.0.1

What could be the problem?

**Comment by FlowerWrong** [comment]
On my server is ok with ejabberd 15.07. In ejabberd.yml
Note this
```ruby
hosts:
  - "localhost"
  #- "192.168.33.10"
  - "ejabberddemo.com"
```
```ruby
vagrant@vagrant:~$ sudo ejabberdctl registered_users localhost
registeruser
registeruser2
yang
```

**Comment by prefiks** [comment]
Did you register those users? Maybe you just have anonymous auth enabled, so you were able to connect, but didn't register those?

**Comment by Suvitruf** [comment]
Yeh, I registered this users with ejabberdctl.

**Comment by zinid** [comment]
What database is in use?

**Comment by Suvitruf** [comment]
Riak

**Comment by cromain** [comment]
in debug console, what is output of this command
ejabberd_riak:get_keys_by_index(passwd, <<"host">>, <<"localhost">>).

**Comment by Suvitruf** [comment]
Hm, yesterday our servers where rebooted. And after that `ejabberdctl registered_users localhost` works fine. 

Don't know what was the problem =/

**Comment by cromain** [comment]
closing issue then. please reopen if you get problem back.

**Comment by tufguy** [comment]
Hi,

I am also getting the similar problem. I was not sure if i can reopen so created new issue.( https://github.com/processone/ejabberd/issues/815).
