### ISSUE TITLE
Not able to restart ejabber server. Getting Error. Urgent help required!

### ISSUE THREAD

**Issue by pranay-mathur** [processone/ejabberd#717]
Command that I ran:
su - ejabberd -c /usr/sbin/ejabberd

OUTPUT:
Erlang R15B01 (erts-5.9.1) [source] [64-bit] [async-threads:0] [kernel-poll:false]

Eshell V5.9.1  (abort with ^G)
(ejabberd@localhost)1> 
=ERROR REPORT==== 27-Aug-2015::11:58:22 ===
Mnesia(ejabberd@localhost): ** ERROR ** (core dumped to file: "/var/lib/ejabberd/MnesiaCore.ejabberd@localhost_1440_676702_530105")
 ** FATAL ** {error,{"Cannot open dets table",offline_msg,
                     [{file,"/var/lib/ejabberd/offline_msg.DAT"},
                      {type,bag},
                      {keypos,2},
                      {repair,true}],
                     {file_error,"/var/lib/ejabberd/offline_msg.DAT",eacces}}}

=ERROR REPORT==== 27-Aug-2015::11:58:32 ===
Mnesia(ejabberd@localhost): ** ERROR ** mnesia_event got unexpected event: {'EXIT',
                                                                            <0.67.0>,
                                                                            killed}

=INFO REPORT==== 27-Aug-2015::11:58:32 ===
    application: mnesia
    exited: killed
    type: permanent
{error_logger,{{2015,8,27},{11,58,33}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.39.0>},{registered_name,[]},{error_info,{exit,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{"{application_terminated,mnesia,killed}",{gen_server,call,[application_controller,{load_application,crypto},infinity]}}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}},{ancestors,[<0.38.0>]},{messages,[{'EXIT',<0.40.0>,normal}]},{links,[<0.38.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,24},{reductions,153}],[]]}
{"Kernel pid terminated",application_controller,"{application_terminated,mnesia,killed}"}
Kernel pid terminated (application_controller) ({application_terminated,mnesia,killed})

**Comment by zinid** [comment]
There is no solution to the problem, you should restore it from backup.

**Comment by zinid** [comment]
On the other hand you have "eacces" error, which means insufficient rights to the database. This probably could be the issue.

**Comment by pranay-mathur** [comment]
Thanks. I found the solution. It was permission issue with followings files:
1. /var/lib/ejabberd/offline_messages.DAT
2. /var/lib/ejabberd/vcacrd.DAT
