### ISSUE TITLE
Ejabberd is disconnecting the user randomly

### ISSUE THREAD

**Issue by pranay-mathur** [processone/ejabberd#718]
There is strange issue that randomly the users are being disconnected from the server while other users at the same time are connected.

Any clue why this is happening?

**Comment by anhcoi123** [comment]
I think it maybe cause by these problem (with my experiences):
- 2 user using the same account & resource
- mod_ping
- Network problem (lagging randomly)
- Malformed packet -> server will close the XMPP stream
....
Please check the log or use debug/live mode and give your problem details

**Comment by pranay-mathur** [comment]
Thanks. I am looking into this. Will come back up any update.
