### ISSUE TITLE
whatsapp-like group chat and chat must be friends

### ISSUE THREAD

**Issue by FlowerWrong** [processone/ejabberd#719]
I know this is not an issue. But it maked me confused for a long time.

###### How to implement a whatsapp-like group chat without hackcore?
As we know, the definition of [XEP-45](http://xmpp.org/extensions/xep-0045.html) is that after joined user goes to offline, the room will remove he or she. He or she can not get the offline messages. I do not what to that. In my requirement, he or she will not leave the room after it goes to offline, and he or she cat get all offline messages. Is there some `customed module` or `new way` to implement this?

###### Can chat but we must be friends.

In xmpp, we cat chat with each other if only know someone's jid. I do not want to this. They can chat when they are friends. If they are not friends, they can not chat. How can I implement this?

**Comment by zinid** [comment]
> How to implement a whatsapp-like group chat without hackcore?

I never used chatrooms in Whatsapp, but I think you can implement it using MAM: when enabled in the conference, you can load chunks of history. Such functionality is implemented in development builds of Sawim for example.

> Can chat but we must be friends

I don't think this could be done without hacks, XMPP is not designed for this, alas.

**Comment by FlowerWrong** [comment]
@zinid Thanks for reply.
I agree with the second question. XMPP is not design for this.
In the first question, I can get the offline messages, But there is another problem, I can not hold the users of the room. I need to know the user list of the room at any time, the list included both online and offline users in this room. People can join and leave the room(not go offline). May be I can store it to another table, when someone joined, I joined it to this table, when someone leave(not go offline, just leave this room, he does not want to in it.), I delete it from the table.
Any other ways?

**Comment by zinid** [comment]
Just don't go offline. I don't think Whatsapp even has a concept of offline. If you're using a mobile app you can be always "almost online" due to new session management support.

**Comment by FlowerWrong** [comment]
Could you give me a link which means `new session management support`. Is it a module or some otherthing?

**Comment by zinid** [comment]
This is XEP-0198 and is implemented in ejabberd since 14.05 and is enabled by default.

**Comment by FlowerWrong** [comment]
@zinid I am using XEP-198. It can keep session for a while. But after I resume this session, the jid off this session had changed. And muc_online_users table in mnesia will also del this user after resume this session. So I can not keep the group users.
![2015-09-01 16 11 47](https://cloud.githubusercontent.com/assets/5362640/9599209/8d9e0672-50c4-11e5-83cd-7ea6f52c4b04.png)
![2015-09-01 16 15 53](https://cloud.githubusercontent.com/assets/5362640/9599236/cb900a02-50c4-11e5-938e-578c9f5c62f2.png)

The client code wriote with smack 4.1.3.
```java
package cc.onecampus;

import org.jivesoftware.smack.*;
import org.jivesoftware.smack.tcp.XMPPTCPConnection;
import org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration;

import java.io.IOException;

/**
 * Created by yy on 15-9-1.
 */
public class LoginWithResume {
    public static void main(String[] args) {
        SmackConfiguration.DEBUG = true;
        SmackConfiguration.setDefaultPacketReplyTimeout(1000);
        // Open the StreamManagement support
        XMPPTCPConnection.setUseStreamManagementDefault(true);
        XMPPTCPConnection.setUseStreamManagementResumptiodDefault(true);

        // Create the configuration for this new connection
        XMPPTCPConnectionConfiguration.Builder configBuilder = XMPPTCPConnectionConfiguration.builder();
        configBuilder.setSecurityMode(ConnectionConfiguration.SecurityMode.disabled);

        configBuilder.setUsernameAndPassword("registeruser2", "123456");
        configBuilder.setServiceName("ejabberddemo.com");
        configBuilder.setDebuggerEnabled(true).build();

        AbstractXMPPConnection connection = new XMPPTCPConnection(configBuilder.build());

        ReconnectionManager reconnectionManager = ReconnectionManager.getInstanceFor(connection);
        reconnectionManager.enableAutomaticReconnection();

        try {
            connection.connect().login();
        } catch (SmackException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (XMPPException e) {
            e.printStackTrace();
        }
        while (true) ;
    }
}
```

Thanks a lot.

**Comment by zinid** [comment]
I don't understand the question. The session pid will be indeed changed, but it's unrelated to `muc_online_users` table. Also, in screenshot you showed `sm` table, not `muc_online_users`.

**Comment by FlowerWrong** [comment]
Yes, I means the session keeped user will be removed after resume this session.
Desc:
1. I joined a room with enabled stream management. And then broken the internet. The `sm` and `muc_online_users` tables still have this session.
2. I resume this session. This session has changed the pid. and this user had be delete from `muc_online_users` table.
![2015-09-01 17 34 02](https://cloud.githubusercontent.com/assets/5362640/9600843/0e340682-50d0-11e5-8f38-314862bb252c.png)
![2015-09-01 16 15 53](https://cloud.githubusercontent.com/assets/5362640/9600846/1595dc84-50d0-11e5-95e8-2bb21c7fa794.png)

**Comment by zinid** [comment]
I still don't understand. There is no session pid in `muc_online_users` table. Why should it be deleted?

**Comment by FlowerWrong** [comment]
In `sm` table, The pid of this session changed, not in `muc_online_users` table.
![2015-09-01 16 11 47](https://cloud.githubusercontent.com/assets/5362640/9599209/8d9e0672-50c4-11e5-83cd-7ea6f52c4b04.png)
![2015-09-01 16 15 53](https://cloud.githubusercontent.com/assets/5362640/9599236/cb900a02-50c4-11e5-938e-578c9f5c62f2.png)

The `muc_online_users` table delete the user who joined this room after resume the session.
Before resume.
![2015-09-01 17 34 02](https://cloud.githubusercontent.com/assets/5362640/9600843/0e340682-50d0-11e5-8f38-314862bb252c.png)
###### After resme. The `muc_online_users` table is empty.
![2015-09-01 16 15 53](https://cloud.githubusercontent.com/assets/5362640/9600846/1595dc84-50d0-11e5-95e8-2bb21c7fa794.png)

**Comment by zinid** [comment]
Probably someone else can look into that, I don't have a client with XEP-0198 support to check.

**Comment by weiss** [comment]
> The `muc_online_users` table delete the user who joined this room after resume the session.

I can't reproduce that issue, sorry.  My own personal sessions are resumed multiple times per day, and I'm never kicked out of any of the MUC rooms I've joined.

As @zinid said, the session PID is unrelated to the MUC presence.  The MUC service may even be running on a remote server, that server won't be notified of successful XEP-0198 resumes in any way.

So there's probably something else going on.  My guess would be that either your client is not only resuming the session but also sending some `<presence/>` stanza(s), or the session resume simply isn't successful.  Did you check the `ejabberd.log` file?  With `loglevel: 4` (or `5`), ejabberd generates two messages per successful resume, e.g.:

    Closing former stream of resumed session for juliet@example.com/Foo
    Resumed session for juliet@example.com/Foo

Do you see those?

**Comment by FlowerWrong** [comment]
@zinid I am reading the source code. The main file is `ejabberd_listener`, `ejabberd_socket`, `ejabberd_receiver` and `ejabberd_c2s`. 
After print plenty of log, I know the message from pid to pid (like one-to-one chat send message) was using [do_route/3](https://github.com/processone/ejabberd/blob/master/src/ejabberd_sm.erl#L424) function in `ejabberd_sm` file, but I can not see any `receive` code in ejabberd with [search github](https://github.com/processone/ejabberd/search?p=1&q=receive&utf8=%E2%9C%93).  
Like:
```erlang
receive
    chat ->
        ok.
end
```
Can you help me?

**Comment by zinid** [comment]
There are not `receive`s. The code is written based on OTP principles. You better read something about Erlang, it's offtopic here. See http://www.erlang.org/doc/design_principles/gen_server_concepts.html and http://www.erlang.org/doc/design_principles/fsm.html

**Comment by FlowerWrong** [comment]
I see, thanks a lot.
