### ISSUE TITLE
one account login from multi device same time

### ISSUE THREAD

**Issue by changloong** [processone/ejabberd#72]
Hi,

I have setup a simple Ejabberd server,   I try to disable one account login from multi device at same time. 

 I think maybe I can change configure file, then when one account from device A, will kick out this same account login from device B.  

I try set allow_multiple_connections to false for my host, but it not work.

thanks in advance.

**Comment by mremond** [comment]
File transfer is peer to peer by design in XMPP (sometimes negotiating a proxy). There is no wiretapping feature.
