### ISSUE TITLE
xmlrpc request failed

### ISSUE THREAD

**Issue by simpleg** [processone/ejabberd#722]
Hello,
I have installed recently an ejabberd 15.06 server on a debian jessie, I have activate xmlrpc module, and when I send any request I got a crash.

Here the crash report when trying to get registered_users.

2015-08-28 15:08:21 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.527.0>
    registered_name: []
    exception error: {undef,[{p1_xmlrpc,decode,[{xmlel,<<"methodCall">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"methodName">>,[],[{xmlcdata,<<"registered_users">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"params">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"param">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"struct">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"member">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"name">>,[],[{xmlcdata,<<"password">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"string">>,[],[{xmlcdata,<<"XXX">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"member">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"name">>,[],[{xmlcdata,<<"user">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"string">>,[],[{xmlcdata,<<"xmlrpc-robot">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"member">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"name">>,[],[{xmlcdata,<<"server">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"string">>,[],[{xmlcdata,<<"mydomain.example.com">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"param">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"struct">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"member">>,[],[{xmlcdata,<<"\n">>},{xmlel,<<"name">>,[],[{xmlcdata,<<"host">>}]},{xmlcdata,<<"\n">>},{xmlel,<<"value">>,[],[{xmlel,<<"string">>,[],[{xmlcdata,<<"mydomain.example.com">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>}]}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>}]},{xmlcdata,<<"\n">>}]}],[]},{ejabberd_xmlrpc,process,2,[{file,"src/ejabberd_xmlrpc.erl"},{line,236}]},{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,367}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,451}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,289}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,205}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.37.0>]
    messages: []
    links: [#Port<0.9056>,<0.369.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 1681
  neighbours:
2015-08-28 15:08:21 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     undef
     Offender:   [{pid,<0.527.0>},{name,undefined},{mfargs,{ejabberd_http,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

I don't known exactly where is the problem.
Thanks in advance for your help.
Jerome

**Comment by badlop** [comment]
Apparently you don't have the file p1_xmlrpc.beam, which is included in the library p1_xml, which is downloaded when compiling from source, or is included if you installed a binary ejabberd package. Can you check if you have that library, and that file?

**Comment by simpleg** [comment]
Thanks for you answer.
I found the solution an hour, p1_xml in debian jessie is outdated (version 0.2014.08.27-1) decode function has been integrated in Octobre 2014, so I have build a new erlang_p1_xml package from sources and now I got it work fine.
