### ISSUE TITLE
mod_muc

### ISSUE THREAD

**Issue by teledna** [processone/ejabberd#724]
Hi, We are using mod_muc for group chat, and we are using storage:bookmarks for persisting group names. How can we retrieve all the groups joined by user? When we query storage:bookmarks we will get only groups created by the user. Need help on how to retrieve all groups where user is a member or owner

**Comment by FlowerWrong** [comment]
May this [issue 719](https://github.com/processone/ejabberd/issues/719) can help you. I still do not find a better way.

**Comment by teledna** [comment]
Hi can you please tell us where do ejabberd server store the member details of a group. We have configured mysql database

**Comment by FlowerWrong** [comment]
@teledna Just save to mnesia muc_online_users table.
You can see it via
```bash
ejabberdctl debug
observer:start().
```
![2015-09-01 14 46 44](https://cloud.githubusercontent.com/assets/5362640/9597868/7a15371c-50b8-11e5-89bc-c1378af2c5cd.png)

**Comment by teledna** [comment]
We have deployed server on cloud , I am unable to use this observer:start().

I am getting following error



{error,{{load_driver,"No driver found"},

        [{wxe_server,start,1,[{file,"wxe_server.erl"},{line,64}]},

         {wx,new,1,[{file,"wx.erl"},{line,114}]},

         {observer_wx,init,1,[{file,"observer_wx.erl"},{line,91}]},

         {wx_object,init_it,6,[{file,"wx_object.erl"},{line,299}]},

         {proc_lib,init_p_do_apply,3,

                   [{file,"proc_lib.erl"},{line,237}]}]}}

Is there any way I can access mnesia tables and view the content stored

**Comment by badlop** [comment]
> How can we retrieve all the groups joined by user?

Enable mod_muc_admin, and then you can call this command:
```
$ ejabberdctl get_user_rooms user1 localhost
room1@conference.localhost
room2@conference.localhost
```

**Comment by teledna** [comment]
Hi,
Thanks for your reply. I have enabled mod_muc_admin module
Following are the commands shown when I enter ejabberdctl command

   get_room_affiliations name service                                   Get the list of affiliations of a MUC room
   get_room_occupants name service                                      Get the list of occupants of a MUC room
   get_room_occupants_number name service                               Get the number of occupants of a MUC room

It shows error  “Error: command "get_user_rooms" not known”

Thanks&Regards
Vijaya

**Comment by badlop** [comment]
The command get_user_rooms was added 29 May 2015, and was first available in ejabberd 15.06.

**Comment by teledna** [comment]
Hi,

Thank you very much .We are using ejabberd 15.04.  How to upgrade ejabberd without removing the current one

**Comment by badlop** [comment]
The only file modified for that feature apparently is mod_muc_admin.beam You can try to install the newest ejabberd in another machine, then copy that file to your old ejabberd installation, update it with
> $ ejabberdctl update mod_muc_admin

And then restart the module using webadmin.

I've NOT tested, so maybe it does not work: if the feature requires other new ejabberd features, or if the installers are built with different Erlang versions. If it doesn't work, you can put back your old beam file, repeat, and wait until you can update all ejabberd.

**Comment by teledna** [comment]
Thank you

Regards
Vijaya

**Comment by teledna** [comment]
Hi,

I have one more query.  We have upgraded ejabberd to 15.07 . Now get_user_rooms is working fine. But I need user permanently available in conference. Currently server is removing the user from conference whenever user goes offline. So how to make user available always in conference.

Regards
Vijaya

**Comment by zinid** [comment]
@teledna this is a very popular question. Simple anwer: there is no solution to the problem. As a workaround you can stay always online using session resumption (XEP-0198). This is suitable for mobile applications.

**Comment by teledna** [comment]
How to enable this session resumption and make user available always online.

**Comment by zinid** [comment]
The feature is enabled by default in ejabberd, but a client application should support it.

**Comment by teledna** [comment]
stream_management: true|false


I have gone through the ejabberd document and found that default  stream_management is set to true.
I have gone through the XEP-198. But I am not understanding clearly that what client needs to do to support this feature. Can you please elaborate on this

Thanks
Vijaya

**Comment by zinid** [comment]
@teledna I didn't understand your question. The whole spec should be supported. Probably <a/> and <r/> tags can be ommited (not sure), but session resumption should be implemented.

**Comment by teledna** [comment]
OK Thanks for your reply. Now I understood client need to support XEP 198. But my only doubt is when user goes offline do we get the rooms that user is joined earlier using get_user_rooms

**Comment by zinid** [comment]
If I understand correctly, when joining a groupchat in the case you want it to be permanent from your standpoint, you can add it to private xml storage, see http://xmpp.org/extensions/xep-0049.html.

**Comment by teledna** [comment]
Thanks for your reply.

**Comment by zinid** [comment]
Sorry, wrong XEP, this one is valid for conference bookmarks: http://xmpp.org/extensions/xep-0048.html

**Comment by teledna** [comment]
Thank you
