### ISSUE TITLE
no match of right hand value false in ejabberd_auth_http:start/1 line 51

### ISSUE THREAD

**Issue by rrigoni** [processone/ejabberd#727]
I compiled the module ejabberd_auth_http from source using ejabberd 15.07 branch and copied the compiled files to ebin directory. 

Now I'm getting the following error.

My settings is as follows:
```
auth_method:
  - http
auth_opts:  
  - host: "http://localhost:8080"
  - path_prefix: "/api/"
```
Any suggestion or workaround?

ejabberd_1 | 06:15:56.584 [error] unknown option 'auth_opts' will be likely ignored
ejabberd_1 | 06:15:58.049 [info] FQDN used to check DIGEST-MD5 SASL authentication: f22a5031bed1
ejabberd_1 | 06:15:58.104 [info] Application inets started on node ejabberd@f22a5031bed1
ejabberd_1 | 06:15:58.107 [error] CRASH REPORT Process <0.38.0> with 0 neighbours exited with reason: no match of right hand value false in ejabberd_auth_http:start/1 line 51 in application_master:init/4 line 133
ejabberd_1 | 06:15:58.108 [info] Application ejabberd exited with reason: no match of right hand value false in ejabberd_auth_http:start/1 line 51

**Comment by badlop** [comment]
The syntax that you used to provide the options is wrong. I've added an example configuration to the module README file, see and copy it from https://github.com/processone/ejabberd-contrib/tree/master/ejabberd_auth_http#configuration-options
