### ISSUE TITLE
ldap - external user subscriptions are lost during restart

### ISSUE THREAD

**Issue by tbeitter** [processone/ejabberd#732]
We use ldap as auth_method and we use mod_shared_roster_ldap to add all company users to all user's roster. That works fine for years now, but since we opened our server to the public some time ago I experienced this problem:

Our users are able to add external users to their roster, which works fine. But with every server restart this affiliations get deleted. After the reconnect I can no longer see my external contacts and some time later I get subscription requests from them and I can add them again. As far as I know this is not recognised by the external users, only on our side.

Thanks
Til

**Comment by mremond** [comment]
What is the backend for your main roster ? Is that internal Mnesia database ?

**Comment by tbeitter** [comment]
yes, it's mnesia

**Comment by mremond** [comment]
I suspect that your Mnesia database is not configured to write data on disk. Strangely, this is the default.
