### ISSUE TITLE
Sharing roster with different vhost

### ISSUE THREAD

**Issue by tklein** [processone/ejabberd#737]
I figured out that this issues was filed already at https://support.process-one.net/browse/EJAB-506 and marked as solved.
It was commited to master with 262157c88d43b1fc42780c2f94aca38c76610777, but removed later (wasn't able to find the commit) since it's not in the current code (or at least I wasn't able to see it...)

I'd like to see that feature again. Any chances to re-apply the patch?

**Comment by badlop** [comment]
The code is there, see that function:
https://github.com/processone/ejabberd/blob/master/src/mod_shared_roster.erl#L1368

and it is also documented in the ejabberd guide, where it says:
> Displayed groups
>    A list of groups that will be in the rosters of this group’s members. A group of other vhost can be identified with groupid@vhost

**Comment by tklein** [comment]
Yes, you're right, 

Re-read the docs and fixed my config now.

Thanks again for pointing me into the right direction
