### ISSUE TITLE
If 15.09 milestone reached why don't you make setup available for download?

### ISSUE THREAD

**Issue by turalsprofile** [processone/ejabberd#741]
If 15.09 milestone reached why don't you make setup available for download?

also is there any way to get it through apt-get in debian systems?

I remember, when I tried to install 15.07 about month ago using shell command``apt-get install ejabberd`` in debian 8.1,  it was installing 14.07 version. Will 15.09 version be available in apt-get?

Thank you

**Comment by zinid** [comment]
@turalsprofile we're not maintaining `ejabberd` package in Debian, please contact the corresponding maintainer.

**Comment by mremond** [comment]
Please, that when ready (when 15.09 is published), you will have a working up to date .deb package on ProcessOne download page: https://www.process-one.net/en/ejabberd/downloads/
