### ISSUE TITLE
Failed to load NIF library: '/lib/ejabberd/priv/lib/lib/xml.so

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#743]
I'm using ejabberd from sources.

And after `ejabberdctl start` I see this errors: 

`09:23:30.843 [error] unable to load xml NIF: {error,{load_failed,"Failed to load NIF library: '/lib/ejabberd/priv/lib/lib/xml.so: cannot open shared object file: No such file or directory'"}}
09:23:30.844 [error] failed to load NIF /lib/ejabberd/priv/lib/lib/xml_stream: Failed to load NIF library: '/lib/ejabberd/priv/lib/lib/xml_stream.so: cannot open shared object file: No such file or directory'
`

Don't understand why he tries to find files in `/lib/ejabberd/priv/lib/lib/`. Cause this files are in `/lib/ejabberd/priv/lib/` folder.

**Comment by mremond** [comment]
Please update to latest version of xml, it was fixed already this morning.

**Comment by Suvitruf** [comment]
I `clone git://github.com/processone/ejabberd.git` 30 min ago.

**Comment by mremond** [comment]
Thanks, we are having a look.

**Comment by prefiks** [comment]
Hi, if you pull updated version now, you should be able to get this working.
