### ISSUE TITLE
Add ability to define ejabberd server version to display in config file

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#745]
This was suggested on ejabberd forum to make harder to leverage hypotethical issues on a given version: https://www.ejabberd.im/forum/25137/hide-ejabberd-version-info

**Comment by badlop** [comment]
As Evgeniy mentioned in the forum, the admin can simply disable mod_version, which basically only provides that feature. Let's wait if the original poster agrees on this solution, and then we'll close this ticket.

**Comment by mremond** [comment]
yes, good point.
