### ISSUE TITLE
DNS errors clutter logfiles

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#746]
Our log files are cluttered with DNS lookup errors of some really broken zone:

2015-07-10 17:01:30.703 [error] <0.3283.9>@ejabberd_s2s_out:srv_lookup:1203 The DNS servers
  [{{64512,0,0,0,0,0,0,23},53},{{28,130,4,3},53},{{128,131,4,3},53}]
timed out on request for "thesecure.biz" IN SRV. You should check your DNS configuration.

This message occurs VERY frequently. Currently, about 500 of those messages in the last six hours. The message is also annoying because it's split over multiple lines, so I cannot easily filter it with something like `grep -v ...`. 

The zone itself seems broken: It is registered (there is whois info) but it does not have a SOA, let alone a NS record. Namerservers are not very happy about this domain :-). To me it would make sense to 
- Merge the log message into one line (like all other messages).
- Move it to a higher loglevel (we use loglevel 2), since it isn't any error on my part
- Also possible: do not query the domain that often, if it's so misconfigured, e.g. cache such an error for a e.g. 15 minutes or something.

**Comment by zinid** [comment]
This is fixed in the upcoming `new_stream` branch
