### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#750]
Hello,

Please help me i am facing this below error i am using ubuntu 14.04 LTS 

/root/ejabberd/deps/oauth2/src/oauth2_response.erl:174: type map(_,_) undefined
ERROR: compile failed while processing /root/ejabberd/deps/oauth2: rebar_abort
make: *** [deps/.built] Error 1

**Comment by weiss** [comment]
You need an Erlang version between 17.1 and 17.5 to use ejabberd's current Git code.

**Comment by hassanzreik** [comment]
should i uninstall erlang 18 before re-install erlang 17.5?

Thank you

**Comment by weiss** [comment]
Your error message sounds like you're using an older Erlang version, not Erlang 18.  What's the output of `erl -version`?

Either way, you can have multiple Erlang versions installed if you adjust the `PATH` accordingly (e.g., before building ejabberd).

**Comment by hassanzreik** [comment]
Erlang (ASYNC_THREADS,HIPE) (BEAM) emulator version 7.1
this is the output of erl -version

**Comment by hassanzreik** [comment]
i installed everything just like the documentation 

root@ubuntu:~/ejabberd# ./autogen.sh
root@ubuntu:~/ejabberd# ./config
config/        config.status  configure
root@ubuntu:~/ejabberd# ./configure
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking for erl... /usr/local/bin/erl
checking for erlc... /usr/local/bin/erlc
checking Erlang/OTP version... ok
checking for Erlang/OTP root directory... /usr/local/lib/erlang
checking for escript... /usr/local/lib/erlang/bin/escript
checking for make... make
checking whether Erlang is using deprecated types... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
config.status: creating src/ejabberd.app.src
root@ubuntu:~/ejabberd# make
/usr/local/lib/erlang/bin/escript rebar compile && :> deps/.built
==> goldrush (compile)
==> lager (compile)
==> p1_utils (compile)
==> p1_cache_tab (compile)
==> p1_tls (compile)
==> p1_stringprep (compile)
==> p1_xml (compile)
==> p1_stun (compile)
==> esip (compile)
==> p1_yaml (compile)
==> oauth2 (compile)
/root/ejabberd/deps/oauth2/src/oauth2_response.erl:174: type map(_,_) undefined
ERROR: compile failed while processing /root/ejabberd/deps/oauth2: rebar_abort
make: *** [deps/.built] Error 1

**Comment by weiss** [comment]
Ah, then this is a [different problem][1] than I assumed initially.  But I think Erlang 18.x won't work for other dependencies anyway, so I'd retry with Erlang 17.5 and reopen the issue if compilation still fails.

[1]: https://github.com/kivra/oauth2/issues/59
