### ISSUE TITLE
Ejabberd version

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#752]
How can i know the ejabberd version that is running on my server? and how can i upgrade it? 

Thank you

**Comment by hassanzreik** [comment]
kindly note that the delayed messages stored in spool table it has a wrong timestamp it is greater than server time by about 7 mins is there any solution for it?
Thanks you

**Comment by zinid** [comment]
Do you mean to say you always have inconsistent timestamps in the spool table?

**Comment by hassanzreik** [comment]
Thanks @zinid 

created_at column in spool table is correct but when a delayed message stored in it the stamp attribute is greater than server's time by 10 mins.
Please find the xml example below:

 <message from='nuvbcyd7bcb16786d1d47b9f9bd4d4605b69da@***/**.iOS' to='nuvbcy91d0977daa61e71b0aa3bc5ef7cff542@**/**.iOS'><received xmlns='urn:xmpp:receipts' id='A7F3391D-3C6D-4071-85AB-3BA946CC5BD3'/><delay xmlns='urn:xmpp:delay' from='***' stamp='2015-09-18T10:55:41Z'>Offline Storage</delay><x xmlns='jabber:x:delay' stamp='20150918T10:55:41'/></message>

**Comment by zinid** [comment]
Do you have your server name in `from` attribute?

**Comment by hassanzreik** [comment]
yes but i replace it by " * "

**Comment by zinid** [comment]
Could you run Erlang and time the following command:
```
$ erl
...
1> {date(), time()}.
```
Don't forget to set the trailing dot.
Do you have the valid time with this command?

**Comment by hassanzreik** [comment]
the result is valid it is the same time of the server

**Comment by zinid** [comment]
Well, seems like your system time has changed significantly and running ejabberd doesn't detect that (in fact it detects and an adjustment is taking a place, but it may take lots of time to complete). There is no solution to the problem, you better avoid huge system time shifts.

**Comment by hassanzreik** [comment]
also how can i know ejabberd version that is running and how can i upgrade it?

Thank you @zinid

**Comment by zinid** [comment]
```
$ ejabberdctl status
```
The upgrade procedure depends on how your ejabberd was installed. Basically you need to obtain and install newer version and restart ejabberd.

**Comment by hassanzreik** [comment]
the version is ejabberd 2.1.11 what is the latest version?

**Comment by zinid** [comment]
No, that is a very ancient version. The latest version is 15.07 and 15.09 is coming this week.

**Comment by hassanzreik** [comment]
thank you @zinid for your help

**Comment by hassanzreik** [comment]
kindly that i cant take the version now because there is an error in it right? i see  Build Status: Error

**Comment by zinid** [comment]
The error only relates to Riak, you can ignore it.
