### ISSUE TITLE
Error install ejabberd-15.09

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#757]
./configure OK
make:
checking for Expat XML Parser headers in /usr/include... not found
checking for Expat XML Parser... no
configure: error: Expat XML Parser was not found
ERROR: Command ['get-deps'] failed!
make: *** [deps/.got] Error 1

debian 7 + libexpat1-dev + libexpat1 + Erlan 17.5

ejabber-15-07 does not give the error

thanks

**Comment by zinid** [comment]
This is a known issue, see https://github.com/processone/xml/issues/14
We're working on it.

**Comment by suchatorg** [comment]
thanks

**Comment by mremond** [comment]
Fixed by processone/xml#14
