### ISSUE TITLE
gen_mod and 'protocol' atribute

### ISSUE THREAD

**Issue by Zarratustra** [processone/ejabberd#763]
I was recently implementing my own draft module and
I found out that all XEP ejabberd gen_mod modules have this 'protocol' atribute with
reference to adequate xep docs. How is it processed by ejabberd? Is there any 
consequence of not placing it because there is no official documentation for my
draft.

**Comment by prefiks** [comment]
This is just purely informational tag, you don't need to have one. I think we have tool somewhere that append those to documentation, but it is not used for anything more.
