### ISSUE TITLE
untrusted certificate gives false error message

### ISSUE THREAD

**Issue by toralf** [processone/ejabberd#764]
In level "Debug" I could read ::
Your server&apos;s certificate is invalid, expired, or not trusted by <snip>
later I read ::
code='404' type='cancel'><remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas
but the message "Remote server not found."  misleads the user.

**Comment by mremond** [comment]
remote-server-not-found is conform to XMPP standard as I understand it. What else would you suggest ?

**Comment by toralf** [comment]
well - strong argument - so no chance to give more details to the user I fear.
