### ISSUE TITLE
Ejabberd upgrade on Debian (from 7.0 to 8.0 Jessie)

### ISSUE THREAD

**Issue by NicOOM** [processone/ejabberd#767]
After the upgrade of Debian, config file was convert to YAML and is working like before except 1 thing: 

```
mod_shared_roster_ldap:
    ldap_base: "dc=antidot,dc=prv"
    ldap_filter: ""
    ldap_rfilter: "(&(structuralObjectClass=posixGroup)(cn=antidot))"
    ldap_groupattr: "memberUid"
    ldap_groupdesc: "description"
    ldap_memberattr: "memberUid"
    ldap_memberattr_format: "%u"
    ldap_ufilter: "(&(objectClass=inetOrgPerson)(uid=%u))"
    ldap_useruid: "uid"
    ldap_userdesc: "displayName"
```

in the logs : 

```
2015-10-07 15:24:17.433 [debug] <0.483.0>@eldap:recvd_packet:893
 {searchResEntry,{'SearchResultEntry',<<"cn=antidot,ou=groups,dc=antidot,dc=prv">>,
  [{'PartialAttributeList_SEQOF',<<"memberUid">>,
    [<<"antidot">>,<<"arnaud">>,<<"barsene">>,<<"dvanderelst">>,<<"estels">>,  BALBALBLA ]}]}}
```

But when logged in, user don't have any other user in roster.

**Comment by mremond** [comment]
@badlop @zinid This was already fixed, right ?

**Comment by NicOOM** [comment]
No i worked around it by creating a shared roster that i add to everyone and add manually to every new user. I have a small user base so it's not too annoying.

I will have a another crack at it later, upgrading new server or doing a fresh setup so guess we could close that ticket.

Thanks
