### ISSUE TITLE
join_cluster not working on windows 

### ISSUE THREAD

**Issue by nlphacker** [processone/ejabberd#770]
ejabberdctl join_cluster 'ejabberd@first'

Error: command "join_cluster" not known.

**Comment by mremond** [comment]
Which version of ejabberd are you using ? How did you install it ?

**Comment by wangzengyangV** [comment]
It doesn't work on CentOS too. 
Error: command "join_cluster" not known.

**Comment by cromain** [comment]
this is due to file permissions. i'll change it in the package.
as ejabberd can be installed as root and executed as ejabberd user, used scripts in bin such as joincluster and leavecluster must have rx flags for all

**Comment by cromain** [comment]
permissions fixed and script added for windows. will be included in 15.10
