### ISSUE TITLE
Support for postgresql schemas.

### ISSUE THREAD

**Issue by adarshphilip** [processone/ejabberd#772]
It would be much more convenient for postgres to be able to not being forced to use different databases but rather to just use different schemas within the same database. That way one can keep stuff together where it belongs.
I dont know whether this functionality exists. If yes, then how can we configure the odbc-postgres driver in ejabberd to use the tables in a given schema?

**Comment by mremond** [comment]
We do not have a feature to support any arbitrary existing postgresSQL schema. Usually, when we have an existing user base you want to use, we develop a custom authentication module. Existing schema may have limitation or may not perform well with existing ejabberd data structure expectations.

**Comment by adarshphilip** [comment]
Thank you! Just some final clarifications:
So creating a whole new database for authentication and archiving is the only option under the current scheme of things?
Can the developers expect a support for schemas anytime in the near future? That would be a big help for small time applications which have only scope for one database.

**Comment by adarshphilip** [comment]
Using the schema name as username in the ejabberd.yml config file worked! Thank you!
