### ISSUE TITLE
ejabberd_http: Global host_config should be used instead of certfile to enable SNI

### ISSUE THREAD

**Issue by jkufner** [processone/ejabberd#773]
When specifying listening ports, there is option to enable TLS and set certfile which should be used. But when such port should be able to handle multiple domains, single certfile is not enough. Since correct certfiles for all domains are already specified in `host_config`/`domain_certfile`, they should be used automatically. So `tls: true` alone should be enough to get TLS on given port working.

This will simplify mod_http_upload setup without proper web server (see https://github.com/processone/ejabberd-contrib/issues/127) and I guess there are more services that will benefit from this feature.

**Comment by badlop** [comment]
From what I know, the web browser connects to the listened IP address, then setups the TLS encrypted connection, and later transfers the HTTP headers (including the Host one). So, ejabberd doesn't know the host at the time it is reading the certificate file.

**Comment by jkufner** [comment]
This is solved by SNI -- the server name is sent before setting up TLS, so server knows which certificate is expected by a client.

**Comment by zinid** [comment]
@jkufner yes, but the TLS driver used in ejabberd doesn't support SNI.

**Comment by jkufner** [comment]
But SNI works on port 5222. It is configured by `host_config`/`domain_certfile` options.

**Comment by zinid** [comment]
@jkufner it's not SNI, it's STARTTLS

**Comment by jkufner** [comment]
@zinid Ah... you are right. Sorry. But point still stands -- per-domain certificates are configured, mod_http_upload should use it.

**Comment by badlop** [comment]
Maybe this advances in the next release, thanks to commits like https://github.com/processone/ejabberd/commit/cc58ce6301a6a60d5b3f67fb17731200572fff4b and related ones.
