### ISSUE TITLE
ejabberd_oauth errors 

### ISSUE THREAD

**Issue by alanpich** [processone/ejabberd#774]
`version: 15.09`
I'm trying to set up oauth logins. Tokens can be generated fine but I'm hitting an error whenever I try and authenticate from a client when using the token. 

##### Error Message
`[error] CRASH REPORT Process <0.477.0> with 0 neighbours exited with reason: call to undefined function cyrsasl_oauth:mech_new(<<"chatter.local">>, #Fun<ejabberd_c2s.2.44283593>, #Fun<ejabberd_c2s.3.44283593>, #Fun<ejabberd_c2s.4.44283593>) in p1_fsm:terminate/8 line 760`

##### Steps to reproduce
- Enable `ejabberd_oauth` endpoint and ACLs in  `ejabberd.yml`
- Generate a token by authenticating against the oauth login endpoint
- Attempt to authenticate with xmpp server by passing the following stanza: 
  -  Element value is generated according to docs (`\0[user]\0[token]`)
  ```xml
  <auth mechanism="X-OAUTH2" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
      AGFsYW5AY2hhdHRlci5sb2NhbABLRXIxR1hvdEs4T0FWSVBmT3k1MnZUcUJPN0k5RUdKRg==
  </auth>
  ```

##### Initial Findings
My erlang knowledge is next to nonexistant, but after poking around in the source a bit there seems to be a discrepancy between `crysasl_oauth.erl` and the other `crysasl_*.erl` modules. All other auth type adapter modules export [`mech_new/4`](https://github.com/processone/ejabberd/blob/master/src/cyrsasl_plain.erl#L30) whereas the oauth module exports [`mech_new/6`](https://github.com/processone/ejabberd/blob/master/src/cyrsasl_oauth.erl#L30).

The error I've posted above seems to come about when the auth module is invoked in [`crysasl.erl`](https://github.com/processone/ejabberd/blob/master/src/cyrsasl.erl#L179) and the `mech_new` function is called with specifically 4 arguments. If this is the case it would imply that the oauth module will never work?!

Am i doing something wrong when configuring the server here? How can this be resolved?

**Comment by alexeyshch** [comment]
Sorry, a wrong version of cyrsasl_oauth got in the repo, it should be fixed now.
