### ISSUE TITLE
why erlang:memory() 's total is much smaller than the top ? memory Leak ?

### ISSUE THREAD

**Issue by zhuoyikang** [processone/ejabberd#775]
after i eval gc manually: 
X=[erlang:garbage_collect(P) || P <- erlang:processes(), {status, waiting} == erlang:process_info(P, status)].

top res -> 8.3g
erlang:memory() -> 3.6G
[{total,3694253080},
 {processes,3301211768},
 {processes_used,3300343808},
 {system,393041312},
 {atom,744345},
 {atom_used,715567},
 {binary,254047488},
 {code,18840350},
 {ets,61244696}]

wow..  does memory Leak in ejabberd or erlang 17.5 erts-6.4

**Comment by mremond** [comment]
This is a known issue of Erlang.

**Comment by zhuoyikang** [comment]
would you give some http link about how the solve this issue abount erlang .

**Comment by weiss** [comment]
> would you give some http link about how the solve this issue abount erlang .

http://erlang.org/pipermail/erlang-questions/2012-September/069337.html

**Comment by zhuoyikang** [comment]
i get , it's erlang's problem ,and i my ejabberd node ,the binary allocactor allocated almost 5G mbcs_carriers_size  memory ，but the usage is very low , not greater than  1% , it's a big waste

would u give some advise to avoid it or make the usage it better , because ejabberd is a very big custom of binary alloctor.

 rp(recon_alloc:fragmentation(current)).

[{{binary_alloc,1},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.09427699263575272},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,135659064},
   {mbcs_carriers_size,1438941360}]},
 {{binary_alloc,4},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.010110173004349157},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,9183696},
   {mbcs_carriers_size,908361904}]},
 {{binary_alloc,2},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.05721490350125805},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,53111728},
   {mbcs_carriers_size,928284848}]},
 {{binary_alloc,3},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.03553723173589733},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,29038744},
   {mbcs_carriers_size,817135792}]},
 {{binary_alloc,5},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.0037855806051078915},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2105928},
   {mbcs_carriers_size,556302512}]},
 {{binary_alloc,6},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.002756687503618395},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,1321816},
   {mbcs_carriers_size,479494320}]},
 {{binary_alloc,7},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.0015088825673492223},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,602464},
   {mbcs_carriers_size,399278256}]},
 {{binary_alloc,8},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.0015768937717374615},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,428720},
   {mbcs_carriers_size,271876272}]},
