### ISSUE TITLE
mod_mam generates an error when requesting archive

### ISSUE THREAD

**Issue by budhead** [processone/ejabberd#776]
I'm sending this IQ:
<iq type="get" id="queryForMessages"><query xmlns="urn:xmpp:mam:tmp" queryid="0"><with>557996033@chat.example.com</with></query></iq>

I'm not receiving anything as response iq on the client. But this is the error from the log on the server.

2015-10-13 16:28:01.861 [error] <0.423.0>@gen_iq_handler:process_iq:120 {{badmatch,{error,{3,<<"no element found">>}}},[{mod_mam,'-select/6-fun-1-',2,[{file,"src/mod_mam.erl"},{line,578}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{mod_mam,select,6,[{file,"src/mod_mam.erl"},{line,576}]},{mod_mam,select_and_send,8,[{file,"src/mod_mam.erl"},{line,521}]},{gen_iq_handler,process_iq,6,[{file,"src/gen_iq_handler.erl"},{line,119}]},{gen_iq_handler,handle_info,2,[{file,"src/gen_iq_handler.erl"},{line,191}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]}]}

The SQL queries from the log are OK and returning the correct data, but mod_mam is throwing this error after the queries.

This problem is with ejabberd-15.07.
With ejabberd-15.09 the server almost with every requests answers ... but always with 0 results.

Additional ... when

**Comment by zinid** [comment]
> The SQL queries from the log are OK and returning the correct data, but mod_mam is throwing this error after the queries.

It seems like there is malformed XML stored in your database.

**Comment by budhead** [comment]
But why the new version 15.09 returns always 0 results?

**Comment by zinid** [comment]
Probably you didn't ALTER the table.

**Comment by budhead** [comment]
I did some more tests and found that Emoji icons are the problem. They are popular in iOS and lately in Android ... so maybe it's reasonable to take a look at it. I'll continue digging on this.
If I sent an emoji in one conversation I can't get this conversation from the server anymore. If I delete the messages from the DB, everything is normal.


This is how the xml is breaking when I add Emoji:

    <message from='1534902839@chat.doppels.com/24981258181444753514459326' to='108461742818946@chat.doppels.com' type='chat' id='1444808754651'><body>Hi mate 

After mate, there should be an EMoji and after that more text.

**Comment by zinid** [comment]
That's basically MySQL problem.

**Comment by rraptorr** [comment]
Storing emojis requires mysql server to be properly configured with utf8mb4 character set. This includes proper client/connection character set and proper database schema. By default mysql will use utf8, which cannot store emojis. That's mysql specific caveat, details can be found in documentation: https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

**Comment by budhead** [comment]
You are write, but even with utf8mb4 it's not enough. We changed all the "xml" fields in the database to BLOB and it works well now.

10x to this post: https://github.com/processone/ejabberd/issues/723
