### ISSUE TITLE
Ejabberd 15.09 fails to run - NIF error

### ISSUE THREAD

**Issue by SafwatHalaby** [processone/ejabberd#777]
I compiled Ejabberd 15.09 from the source code which was [obtained here](https://www.process-one.net/downloads/ejabberd/15.09/ejabberd-15.09.tgz).
It should be noted that Ejabberd 15.07 works just fine when compiled from the [source code](https://www.process-one.net/downloads/ejabberd/15.07/ejabberd-15.07.tgz).

#743 is a similar issue which was resolved and closed recently.

Here is the error when running 15.09
```
2015-10-14 20:25:22.691 [info] <0.7.0> Application lager started on node ejabberd@raspberrypi
2015-10-14 20:25:22.955 [info] <0.7.0> Application crypto started on node ejabberd@raspberrypi
2015-10-14 20:25:23.112 [info] <0.7.0> Application sasl started on node ejabberd@raspberrypi
2015-10-14 20:25:23.352 [info] <0.7.0> Application asn1 started on node ejabberd@raspberrypi
2015-10-14 20:25:23.356 [info] <0.7.0> Application public_key started on node ejabberd@raspberrypi
2015-10-14 20:25:23.571 [info] <0.7.0> Application ssl started on node ejabberd@raspberrypi
2015-10-14 20:25:23.624 [info] <0.7.0> Application p1_yaml started on node ejabberd@raspberrypi
2015-10-14 20:25:23.770 [info] <0.7.0> Application p1_tls started on node ejabberd@raspberrypi
2015-10-14 20:25:23.828 [error] <0.111.0> unable to load xml NIF: {error,{load_failed,"Failed to load NIF library: '/usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml.so: cannot open shared object file: No such file or directory'"}}
2015-10-14 20:25:23.859 [error] <0.111.0> failed to load NIF /usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml_stream: Failed to load NIF library: '/usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml_stream.so: cannot open shared object file: No such file or directory'
```

**Comment by mremond** [comment]
This is already fixed in master and will be also in ejabberd next release.
Thanks !

**Comment by SafwatHalaby** [comment]
Thank you.

I installed ejabberd in a non-standard location using `./configure prefix=/home/ejab/ejabberd`.
It seems that it's simply not finding a file, will the following fix it?:
`xml_stream.so /usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml_stream.so`

**Comment by zinid** [comment]
@SafwatHalaby yes, before new version coming out you can use it as a temporary work-around.

**Comment by prefiks** [comment]
In your case it looks like it locates global p1_xml package before the bundled one. We plan to change the way we are bundling our dependences in next release that should make it pick local version first. 

To fix this you could try to use p1_xml version that didn't have new *.so finding code (if you download source code from http://www.process-one.net/downloads/ejabberd/15.09/ejabberd-15.09.tgz instead of getting one from git, it would have pinned dependences instead of taking one from latest version), uninstalling global p1_xml or use that hack that you did ;)

**Comment by SafwatHalaby** [comment]
Thank you. Btw, Is there a stable git branch somewhere? On one hand, I don't want bleeding edge, on the other hand, having to use the .tgz files is less convenient than `git fetch`, plus it means I have to recompile from scratch (unless I move around object files).

**Comment by SafwatHalaby** [comment]
This isn't resolved in `master`.

```
2015-10-14 21:32:15.140 [info] <0.7.0> Application lager started on node ejabberd@raspberrypi
2015-10-14 21:32:15.326 [info] <0.7.0> Application crypto started on node ejabberd@raspberrypi
2015-10-14 21:32:15.543 [info] <0.7.0> Application sasl started on node ejabberd@raspberrypi
2015-10-14 21:32:15.824 [info] <0.7.0> Application asn1 started on node ejabberd@raspberrypi
2015-10-14 21:32:15.828 [info] <0.7.0> Application public_key started on node ejabberd@raspberrypi
2015-10-14 21:32:16.043 [info] <0.7.0> Application ssl started on node ejabberd@raspberrypi
2015-10-14 21:32:16.123 [info] <0.7.0> Application p1_yaml started on node ejabberd@raspberrypi
2015-10-14 21:32:16.266 [info] <0.7.0> Application p1_tls started on node ejabberd@raspberrypi
2015-10-14 21:32:16.318 [error] <0.111.0> unable to load xml NIF: {error,{load_failed,"Failed to load NIF library: '/usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml.so: cannot open shared object file: No such file or directory'"}}
2015-10-14 21:32:16.350 [error] <0.111.0> failed to load NIF /usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml_stream: Failed to load NIF library: '/usr/lib/erlang/lib/p1_xml-0.2014.08.27/priv/lib/xml_stream.so: cannot open shared object file: No such file or directory'
2015-10-14 21:32:16.353 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: {unable_to_load_nif,{xml_app,start,[normal,[]]}} in application_master:init/4 line 133
2015-10-14 21:32:16.358 [critical] <0.38.0>@ejabberd:exit_or_halt:133 failed to start application 'p1_xml': {error,
                                       {unable_to_load_nif,
                                        {xml_app,start,[normal,[]]}}}
2015-10-14 21:32:16.359 [info] <0.7.0> Application p1_xml exited with reason: {unable_to_load_nif,{xml_app,start,[normal,[]]}}
```

**Comment by prefiks** [comment]
Commit 70606667c60bfc3196defe86056a5eb77841dfd5 did switch `make install` to use structure that should help with this issue. Current master should work without this workaround.

**Comment by asimrazakhan** [comment]
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V9.3  (abort with ^G)
(ejabberd@localhost)1> 13:12:01.035 [notice] Changed loghwm of /Applications/ejabberd-18.03/logs/error.log to 100
13:12:01.111 [info] Application lager started on node ejabberd@localhost
13:12:01.111 [notice] Changed loghwm of /Applications/ejabberd-18.03/logs/ejabberd.log to 100
13:12:01.121 [info] Application crypto started on node ejabberd@localhost
13:12:01.147 [info] Application sasl started on node ejabberd@localhost
13:12:01.156 [info] Application asn1 started on node ejabberd@localhost
13:12:01.156 [info] Application public_key started on node ejabberd@localhost
13:12:01.202 [info] Application ssl started on node ejabberd@localhost
13:12:01.210 [info] Application p1_utils started on node ejabberd@localhost
13:12:01.233 [info] Application fast_yaml started on node ejabberd@localhost
13:12:01.312 [info] Application fast_tls started on node ejabberd@localhost
13:12:01.405 [warning] unable to load fxml NIF: {error,{load_failed,"Failed to load NIF library: 'dlopen(/Applications/ejabberd-18.03/lib/fast_xml-1.1.29/priv/lib/fxml.so, 2): Library not loaded: /usr/local/opt/expat/lib/libexpat.1.dylib\n  Referenced from: /Applications/ejabberd-18.03/lib/fast_xml-1.1.29/priv/lib/fxml.so\n  Reason: Incompatible library version: fxml.so requires version 8.0.0 or later, but libexpat.1.dylib provides version 7.0.0'"}}
13:12:01.408 [error] failed to load NIF /Applications/ejabberd-18.03/lib/fast_xml-1.1.29/priv/lib/fxml_stream: Failed to load NIF library: 'dlopen(/Applications/ejabberd-18.03/lib/fast_xml-1.1.29/priv/lib/fxml_stream.so, 2): Library not loaded: /usr/local/opt/expat/lib/libexpat.1.dylib
  Referenced from: /Applications/ejabberd-18.03/lib/fast_xml-1.1.29/priv/lib/fxml_stream.so
  Reason: Incompatible library version: fxml_stream.so requires version 8.0.0 or later, but libexpat.1.dylib provides version 7.0.0'
13:12:01.408 [error] CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {unable_to_load_nif,{fast_xml,start,[normal,[]]}} in application_master:init/4 line 134
13:12:01.408 [info] Application fast_xml exited with reason: {unable_to_load_nif,{fast_xml,start,[normal,[]]}}
13:12:01.408 [error] CRASH REPORT Process <0.153.0> with 0 neighbours exited with reason: {{fast_xml,{unable_to_load_nif,{fast_xml,start,[normal,[]]}}},{xmpp,start,[normal,[]]}} in application_master:init/4 line 134
13:12:01.408 [critical] failed to start application 'xmpp': {error,
                                     {{fast_xml,
                                       {unable_to_load_nif,
                                        {fast_xml,start,[normal,[]]}}},
                                      {xmpp,start,[normal,[]]}}}
13:12:01.408 [info] Application xmpp exited with reason: {{fast_xml,{unable_to_load_nif,{fast_xml,start,[normal,[]]}}},{xmpp,start,[normal,[]]}}
failed to start application 'xmpp': {error,
                                     {{fast_xml,
                                       {unable_to_load_nif,
                                        {fast_

Crash dump is being written to: /Applications/ejabberd-18.03/logs/erl_crash_20180514-131155.dump...done

```

**Comment by Hayyk** [comment]
@asimrazakhan I have the same issue. have you solved this yet?

**Comment by Hayyk** [comment]
@licaon-kter I am trying to get ejabberd working on docker using this [repo](https://github.com/processone/docker-ejabberd/tree/master/ecs). I am running ./build.sh 18.06 with some changes. I have forked processone/ejabberd repo, made some changes to enable riak. got riak working but came into this. what I'm missing?

logs of crashed container:
20:14:22.146 [info] Application lager started on node ejabberd@89e5a44cd47a
20:14:22.133 [notice] Changed loghwm of /home/ejabberd/logs/error.log to 100
20:14:22.133 [notice] Changed loghwm of /home/ejabberd/logs/ejabberd.log to 100
20:14:22.167 [info] Application p1_utils started on node ejabberd@89e5a44cd47a
20:14:22.187 [info] Application fast_yaml started on node ejabberd@89e5a44cd47a
20:14:22.221 [info] Application fast_tls started on node ejabberd@89e5a44cd47a
20:14:22.250 [info] Application fast_xml started on node ejabberd@89e5a44cd47a
20:14:22.270 [info] Application stringprep started on node ejabberd@89e5a44cd47a
20:14:22.307 [warning] unable to load xmpp_lang NIF: {error,{load_failed,"Failed to load NIF library: 'Error loading shared library /home/ejabberd/lib/xmpp-1.2.1/priv/lib/xmpp_lang.so: No such file or directory'"}}
20:14:22.307 [error] CRASH REPORT Process <0.159.0> with 0 neighbours exited with reason: {unable_to_load_nif,{xmpp,start,[normal,[]]}} in application_master:init/4 line 134
20:14:22.307 [critical] failed to start application 'xmpp': {error,
                                     {unable_to_load_nif,
                                      {xmpp,start,[normal,[]]}}}
20:14:22.307 [info] Application xmpp exited with reason: {unable_to_load_nif,{xmpp,start,[normal,[]]}}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

**Comment by licaon-kter** [comment]
`You run ejabberd in another context than build one. the host running ejabberd doesn't have XXXX installed.` from #2472

Where XXXX in your case is the erlang xmpp lib.

That docker pulls a prebuild version from the Hub, did you replace that with a new image of your build with Riak and whatnot?

**Comment by Hayyk** [comment]
@licaon-kter Sure replaced as the riak works, if it pulls from hub riak doesn't work. also when I have any image locally, it won't look for hub. 
here is what I've done step by step
1. downloaded 18.06 release from [here](https://github.com/processone/ejabberd/releases)
2. created repo under my account named 'ejabberd', pushed files of downloaded release on master,
changed mix.exs file (added riak in cond_apps), changed configure.ac file (riak default enabled) created tag 18.06
3. cloned https://github.com/processone/docker-ejabberd/tree/master/ecs
4. changed Dockerfile line 9 from `RUN git clone https://github.com/processone/ejabberd.git` to `RUN git clone https://github.com/Hayyk/ejabberd.git`
5. run ./build.sh 18.06 - image successfully created
6. when running container using that image I got the logs pasted above
What I am missing?

**Comment by licaon-kter** [comment]
And you tested the plain Docker (no modifications) and that works fine, right?

If all you do is enable Riak, wouldn't it be easier to add `{riak, true}.` [here](https://github.com/processone/docker-ejabberd/blob/master/ecs/vars.config) instead?

**Comment by Hayyk** [comment]
@licaon-kter  with no modifications (building image from repo) riak doesn't work. the first thing I did was to add `{riak, true}.` in vars.config file as you mentioned - but it didn't work as well (I mean riak wasn't enabled as expected).
when using docker image from docker hub riak doesn't work as well.
In this situation I would like to know the best way to enable riak in docker image, without making changes in other files. what wold you advice?

**Comment by licaon-kter** [comment]
>  with no modifications (building image from repo) riak doesn't work.

That's not what I've asked, does ejabberd work ok otherwise in that Docker image when you don't modify it? Ignore Riak for a minute...

**Comment by Hayyk** [comment]
yes, that's right. ejabberd works fine in that case.

**Comment by Hayyk** [comment]
[image_build.log](https://github.com/processone/ejabberd/files/2346722/image_build.log)
