### ISSUE TITLE
Request: "Stable" branch

### ISSUE THREAD

**Issue by SafwatHalaby** [processone/ejabberd#778]
Currently, the only way to obtain stable releases is through downloading tarballs from the ProcessOne site.

Having a stable branch would be more convenient. It also comes with incremental compilations out of the box: When a previous version was already compiled, the next `make` command takes considerably less time.

**Comment by weiss** [comment]
> Currently, the only way to obtain stable releases is through downloading tarballs from the ProcessOne site.

Well, you could checkout the release tags, e.g. `git checkout 15.0`, and build those.

**Comment by SafwatHalaby** [comment]
Oh, sorry.

**Comment by prefiks** [comment]
Unfortunately i don't think we pin dependences before tagging, so you still would get floating deps when checking out tag, but not when downloading tarball.

**Comment by SafwatHalaby** [comment]
I see. What about fetching and compiling `master` branch just after a release is tagged? I guess it would provide something nearly identical to the tarballs, wouldn't it?

**Comment by weiss** [comment]
> Unfortunately i don't think we pin dependences before tagging, so you still would get floating deps when checking out tag, but not when downloading tarball.

Ah, indeed.

And you must also take care the other way round: If the dependencies are downloaded already, just rerunning `make` won't update them (but `make update all` will).

**Comment by weiss** [comment]
> What about fetching and compiling master branch just after a release is tagged? I guess it would provide something nearly identical to the tarballs, wouldn't it?

Yes.  And you can run `tools/set-dep-versions` at that point to pin the dependencies to their current versions.

**Comment by SafwatHalaby** [comment]
`make update all` doesn't seem to be a valid command.

**Comment by weiss** [comment]
> `make update all` doesn't seem to be a valid command.

What happens if you run it?

**Comment by SafwatHalaby** [comment]
Sorry, I invoked `make update all` before ever doing a `make`.
```
git clone https://github.com/processone/ejabberd.git && cd ejabberd && ./autogen.sh && ./configure && make update all
...
Makefile:96: recipe for target 'update' failed
make: *** [update] Error 2
```
it all works fine if I `make` before `make update all`.

So, in summary, is this the right way to obtain a stable branch from the repo?:
```
1. Fetch the master branch just after a `release` is tagged
2. autogen
3. make update all
4. make
```

My make skills are unimpressive, so I may have got it wrong.

**Comment by weiss** [comment]
Ah right, `make update` won't download the dependencies if they aren't there yet.  `make deps update all` would work if you need a single command line that also works for this case.

Anyway, for the `15.10` tag, the dependencies were fixed, so the following commands should yield the same results as when building from the source tarball:

    git checkout 15.10
    ./autogen
    ./configure
    make

**Comment by SafwatHalaby** [comment]
Thank you. You might want to put that somewhere in the README for others to see.

**Comment by SafwatHalaby** [comment]
This might be a new issue, but running the sequence above yields this:
This happens both in `HEAD` and in `15.10`.

```
********* AUTO GEN *********
********* CONFIGURE *********
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for erl... /usr/bin/erl
checking for erlc... /usr/bin/erlc
checking for erl... /usr/bin/erl
checking for erlc... /usr/bin/erlc
checking Erlang/OTP version... ok
checking for Erlang/OTP root directory... /usr/lib/erlang
checking for escript... /usr/lib/erlang/bin/escript
checking for make... make
checking whether Erlang is using deprecated types... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
config.status: creating src/ejabberd.app.src
********* MAKE *********
rm -rf deps/.got
rm -rf deps/.built
/usr/lib/erlang/bin/escript rebar get-deps && :> deps/.got
==> goldrush (get-deps)
==> lager (get-deps)
==> p1_utils (get-deps)
==> p1_cache_tab (get-deps)
==> p1_tls (get-deps)
==> p1_stringprep (get-deps)
==> p1_xml (get-deps)
==> esip (get-deps)
ERROR: Dependency dir /home/ejabserver/sources/ejabberd/deps/p1_stun failed application validation with reason:
{missing_app_file,"/home/ejabserver/sources/ejabberd/deps/p1_stun"}.
ERROR: 'get-deps' failed while processing /home/ejabserver/sources/ejabberd/deps/esip: rebar_abort
Makefile:85: recipe for target 'deps/.got' failed
```

**Comment by SafwatHalaby** [comment]
This sequence works:

```
git checkout 15.10
git submodule update --init 
./autogen.sh 
./configure
make
```

Would this install the proper dependencies even as more commits are pushed to master?

**Comment by weiss** [comment]
> This might be a new issue, but running the sequence above yields this: [...]

Weird, I can't reproduce this.  The following sequence works just fine for me:

    cd `mktemp -d`
    git clone https://github.com/processone/ejabberd.git
    cd ejabberd
    git checkout 15.10
    ./autogen.sh
    ./configure
    make

> his sequence works: [...] `git submodule update --init `

That's even more weird.  There's no submodules in the ejabberd repository.

**Comment by SafwatHalaby** [comment]
That's very interesting. I'll test this thoroughly and report back the results.

**Comment by SafwatHalaby** [comment]
Sorry. The sequence is working fine. `git submodule update --init` must have done nothing. 

I still can't explain why it failed the first time nor reproduce that. Could it be some network error? I tried disconnecting the network cable while `make` is being performed, but the printed error was different.

Anyways, it's all good now. Consider this resolved.
