### ISSUE TITLE
ejabberd JSON parsing error?

### ISSUE THREAD

**Issue by harshsuri** [processone/ejabberd#780]
Situation: backend windows application <--> ejabberd server <--> android chat client side

client side send a custom iq query in JSON format via ejabberd server to backend windows app and it parses it correctly. When the backend windows app sends back a response to the client the single quotes in the JSON response are converted to &quot.

Configuration:

backend app - windows app (.net based application)
backend - Azure SQL
xmpp server - ejabberd 15.07
ejabberd server OS - Ubuntu Trusty
client side - android app using "asmack"

I am not sure what can be causing the error. Any help is appreciated.

Thanks.

**Comment by prefiks** [comment]
This is standard XML escape sequence, you pretty much expect to have any of this characters &<>" to be replaced by one of special entities. Your xml parsing library should replace those automatically, maybe you are not using correct method to not get raw values? It may also be problem on producing end, where it escapes values twice (' -> &quot; -> &amp;quot;) which after unescaping will give you &quot; string, you would need to check what is actually send in network packet to be able to determine this.
