### ISSUE TITLE
Cannot compile mod_multicast module.

### ISSUE THREAD

**Issue by userException** [processone/ejabberd#782]
I am trying to add mod_multicast module to my ejabberd 15.09.

Steps:
1. Get the repo from 'svn co https://svn.process-one.net/ejabberd-modules/'
2. Run ./build.sh command in the directory for mod_multicast '../ejabberd-modules/mod_multicast/trunk'.
3. A .beam file should be created in the ebin directory, but no file is created in my case.

I am following this tutorial for ref: http://www.gettechgo.com/how-to-install-mod_admin_extra-in-ejabberd/#comment-128

**Comment by mremond** [comment]
`mod_multicast` is integrated in ejabberd since quite some time. There is nothing special to install. You can refer to official documentation: http://docs.ejabberd.im/admin/guide/configuration/#modmulticast

**Comment by userException** [comment]
I tried to add:

 mod_multicast:
	  host: "multicast.nipun.local"
	  access: multicast
	  all: allow

in th ejabberd.yml file in the conf folder. But ejabberd starts with errror
![screen shot 2015-10-16 at 12 25 14 pm](https://cloud.githubusercontent.com/assets/3499123/10535496/f56c907a-7400-11e5-9c59-0d853d9749b2.png)

**Comment by userException** [comment]
added: mod_multicast: [] and it worked
