### ISSUE TITLE
[Feature Request] mod_mam message lifetime

### ISSUE THREAD

**Issue by SafwatHalaby** [processone/ejabberd#783]
Currently, it is not possible to control the lifetime of messages stored via`mod_mam`. Sometimes, removing old messages is desired, either automatically or manually.

For automatic removal, I propose a new option:

```
mod_mam:
  [...]
  max_message_age: <Age Here>
```

For manual removal, a new `ejabberdctl` command can be added, which removes messages which are older than the specified age.

```
ejabberdctl remove_mam_messages <Age here> <Possibly other options such as domain, etc>
```

**Comment by SafwatHalaby** [comment]
It's worth noting that ejabberd-contrib's [mod_mam_mnesia](https://github.com/processone/ejabberd-contrib/tree/master/mod_mam_mnesia) has an option called `access_max_user_messages` which does something similar. It doesn't have manual deletions though.

**Comment by volga629** [comment]
I asked too for this feature +1. Might be better add module for future options expansions.

```
mod_mam_quota:
     missed db_type: odbc
     max_days_message_disposal: 45

```

**Comment by pinkolin** [comment]
+1 for this.

**Comment by badlop** [comment]
The command was added some time ago here: https://github.com/processone/ejabberd/commit/3dccc20d8bce2d70c321810faa808a00204b6c02

For automatic periodical removal, mod_cron can be setup.
