### ISSUE TITLE
Auto create nodes don't contain node identity.

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#784]
When using auto create with smack for PEP I am getting following error. It seems that smack always expect the node type. I can work around it by locally creating the node instead of relying on auto_create.

<iq from='xyz@ejabberd.sandwitch.in' to='xyz@ejabberd.sandwitch.in/smack' id='5Y15r-46' type='result'><query xmlns='http://jabber.org/protocol/disco#info' node='xyz'><identity category='account' type='registered'/></query></iq><r xmlns='urn:xmpp:sm:3'/>
06:45:44 PM SENT (0): <a xmlns='urn:xmpp:sm:3' h='27'/>
Exception in thread "main" java.lang.AssertionError: PubSub service 'xyz@ejabberd.sandwitch.in' returned disco info result for node 'xyz', but it did not contain an Identity of type 'leaf' or 'collection' (and category 'pubsub'), which is not allowed according to XEP-60 5.3.

**Comment by cromain** [comment]
this note in XEP-0060 references XEP-0248 leaf/collection distinction, but this XEP is deferred.
i'll investigate deeper for 15.11 to check if we want to force leaf type.

**Comment by cromain** [comment]
While it's OK to force leaf node type by default, i see nothing related to auto-create feature that can trigger this lack of type in disco. function node_disco_info/5 clearly set leaf by default already.

I would need full xmpp stanza in order to reproduce this. but from a quick review i could not reproduce nor find issue in the code.

**Comment by cromain** [comment]
maybe you can try this patch, and check if it fix your problem:
`
--- a/src/mod_pubsub.erl
+++ b/src/mod_pubsub.erl
@@ -486,7 +486,10 @@ disco_local_identity(Acc, _From, To, <<>>, _Lang) ->
   true ->
       [#xmlel{name = <<"identity">>,
          attrs = [{<<"category">>, <<"pubsub">>},
-        {<<"type">>, <<"pep">>}]}
+        {<<"type">>, <<"pep">>}]},
+       #xmlel{name = <<"identity">>,
+         attrs = [{<<"category">>, <<"pubsub">>},
+        {<<"type">>, <<"leaf">>}]}
      | Acc];
   false ->
       Acc
`

**Comment by bangarharshit** [comment]
Thanks. I tried the patch but it is still not working. Here is the reply - <iq to='bf5cac12-80bd-49dd-97f5-f41178edd864@ejabberd.sandwitch.in/smack' from='bf5cac12-80bd-49dd-97f5-f41178edd864@ejabberd.sandwitch.in' id='48l0w-30' type='result'><query xmlns='http://jabber.org/protocol/disco#info' node='bf5cac12-80bd-49dd-97f5-f41178edd864'><identity category='account' type='registered'/></query></iq>

Smack is expecting pubsub leaf or pubsub collection as node type while we are getting account registered. Let me know if you need code sample for the same.

**Comment by cromain** [comment]
this is reply from disco on main vhost, not from pubsub service.
did you enabled PEP plugin in mod_pubsub configuration ?

**Comment by bangarharshit** [comment]
This is my  config file 

```
 mod_pubsub: access_createnode: pubsub_createnode 
## reduces resource comsumption, but XEP incompliant 
ignore_pep_from_offline: true 
## XEP compliant, but increases resource comsumption
## ignore_pep_from_offline: false 
last_item_cache: false 
plugins: - "flat" 
- "hometree" 
- "pep" 
# pep requires mod_caps
  mod_caps: []
```

It is already enabled.

**Comment by cromain** [comment]
I can not reproduce. Using Psi client, i publish a PEP event without creating the node first (auto-create does it) just by publishing a mood on a fresh clean new account.
Then i query my mood node

```
<iq to='test1@localhost' type='get'>
<query xmlns='http://jabber.org/protocol/disco#info' node="http://jabber.org/protocol/mood"/>
</iq>
```
and i got response as expected

```
...
<identity category="pubsub" type="pep"/>
<identity category="pubsub" type="leaf"/>
...
```

there should be something wrong on smack side i guess.
