### ISSUE TITLE
make install is broken

### ISSUE THREAD

**Issue by sezuan** [processone/ejabberd#786]
https://github.com/processone/ejabberd/commit/70606667c60bfc3196defe86056a5eb77841dfd5 seems to break `make install`:

    # make install
    /usr/lib/erlang/bin/escript rebar skip_deps=true compile
    ==> rel (compile)
    ==> ejabberd (compile)
    make: *** No rule to make target `/lib/esip/ebin/esip_app.beam', needed by `copy-files'.  Stop.

**Comment by prefiks** [comment]
Hi, 97a93263c14aec7bfcddf995160c153947f9bfba that i just commited may help with this, if not could you tell me what os, and make command are you using? make -v may tell you this.

**Comment by sezuan** [comment]
Not working. It's Ubuntu 12.04.

    # make -v
    GNU Make 3.81
    Copyright (C) 2006  Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.
    There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
    PARTICULAR PURPOSE.
    
    This program built for x86_64-pc-linux-gnu

**Comment by weiss** [comment]
FWIW, I've now [added][1] a `make install` call to our `.travis.yml` file, so that the [build status][2] turns red if that call yields a non-zero exit code.

[1]: https://github.com/processone/ejabberd/commit/ff4a00b1f3ccf573e2038197444e5f587524f02e
[2]: https://travis-ci.org/processone/ejabberd

**Comment by prefiks** [comment]
Thanks Holger, thats a good thing to have.

**Comment by prefiks** [comment]
So i think commit 06701b126bc704823e5bc4edd0cff578f6229765 should fix this, one of rules i added didn't want to work on gmake 3.8, but worked without problem on 4+.
