### ISSUE TITLE
[Advice] for multicast

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#787]
Hello I created custom MUC type module where i need to send 2 type of packets
1) is presence  --- which is common to all members so i can use out of the box route multicast ,  as the packet is same for all the members

2) Message -- has 2 parts  a) actual message (common for all members )  b) metadata like message id and other custom info (differs per member of the group)

for message packet i need to send it to all members as well ,  but as the metadata part of packet changes for each members due to our custom implementation I dont think  i can readily use  route multicast as it loops for same packet

describing the problem 2 things that comes to my mind would like to which will be better for the system and performance 
1) can  loop  normal route() ? looping across all the members and send them the diff packet

2) Is there a way i can modify multicast or implement custom multicast which will accept Key - as jid to whom to  send and values as packet for that user.  unlike in current multicast where we are sending one packet and list of jids.
     Any help on part 2 will be really appreciated.  Thanks a lot for the support.

**Comment by mremond** [comment]
I do not see the point in modifying multicast to have variable in packets. There is no benefit compared to routing each packet.
