### ISSUE TITLE
`ejabberdctl ping` returning `pang,` even though `ejabberdctl join_cluster` works without issue.

### ISSUE THREAD

**Issue by richardardrichard** [processone/ejabberd#797]
I'm currently trying to automate starting Ejabberd, and having a second node join a cluster (the second node would know the first node is up by getting a successful response from `ejabberdctl ping`). I can't seem to get a successful `pong` response, even though running `ejabberdctl join_cluster` to the exact same node is actually working just fine. I can provide more details if needed. I believe this is happening in both v15.07, and v15.09.

**Comment by cromain** [comment]
I can not reproduce this. maybe docker specific case ?
do you use special settings in ejabberdctl.cfg ?
what's output of epmd -names ? is it different after calling join_cluster ?

ejabberctl ping fires an erlang node with exact same network kernel settings than ejabberd, so if ejabberd cluster is fine, ping should also be ok.
