### ISSUE TITLE
Windows install fails when user profile folder contains a space

### ISSUE THREAD

**Issue by bstremel** [processone/ejabberd#798]
If the user profile folder has a space in it (ex. C:\Users\First Last) the post-installation script will fail.  Installation to an account without a space, on the same machine, succeeds.

**Comment by cromain** [comment]
what is output at end of install.log ?
does file %APPDATA%\ejabberd\conf\inetrc exists after postinstall failed ?

**Comment by cromain** [comment]
i fixed a variable escaping on ejabberdctl on windows, but don't ability to test user env with space for now.
I think it should be fixed anyway. Please reply if you still have problems with 16.01.
