### ISSUE TITLE
mod_http_upload: "Invalid slot"

### ISSUE THREAD

**Issue by alexara** [processone/ejabberd#800]
Hi! 

Whenever I try to upload a file from Conversations 1.7.0 via Nginx 1.8.0 and mod_http_upload to ejabberd 15.10 I receive the following error, which keeps me puzzled:

#### ejabberd.log
```
2015-10-29 17:22:02.092 [info] <0.414.0>@mod_http_upload:create_slot:562 Got HTTP upload slot for alex@jabber.domain.told/mobile (file: 0b8576c2-d1dd-43b9-ba02-96a41f880648.jpg)
2015-10-29 17:22:07.461 [info] <0.617.0>@ejabberd_listener:accept:299 (#Port<0.16876>) Accepted connection 127.0.0.1:33960 -> 127.0.0.1:8284
2015-10-29 17:22:07.462 [info] <0.641.0>@ejabberd_http:init:157 started: {gen_tcp,#Port<0.16876>}
2015-10-29 17:22:07.469 [info] <0.641.0>@mod_http_upload:process:368 Rejecting file from 92.204.xx.xxx for jabber.domain.tld: <<"Invalid slot">>
```
#### nginx.domain.conf
```
	server {
		listen 443 ssl;

		server_name jabber.domain.tld;
		server_tokens off;

		root /var/www/jabber.domain.tld/htdocs/;
	
		# SSL
		ssl_certificate ...;
		ssl_certificate_key ....;
		include /etc/nginx/configs/ssl.conf;

           access_log  ...;
	        error_log ...;
    
		client_max_body_size 20m;

		location /upload {
			limit_except GET {
				proxy_pass http://localhost:8284;
			}
			proxy_set_header Host $host;
			if ($request_method = GET) {
            	add_header X-Frame-Options DENY;
	              }
    	 add_header Strict-Transport-Security "max-age=31536000";
		}
	}
```
#### ejabberd.yml
```
listen:
  -
    module: ejabberd_http
    port: 8284
    request_handlers:
      "": mod_http_upload

access:
   # [...]
   soft_upload_quota:
     all: 1000 # MiB
   hard_upload_quota:
     all: 1100 # MiB

modules:
  mod_http_upload:
    docroot: "/var/www/jabber.domain.tld/htdocs/upload"
    host: "upload.jabber.domain.tld"
    put_url: "https://jabber.domain.tld/upload"
  mod_http_upload_quota:
    max_days: 100
```

Kind Regards

**Comment by weiss** [comment]
With `put_url: "https://jabber.domain.tld/upload"`, you must change the `request_handlers` line to look like this:

    "upload": mod_http_upload

**Comment by alexara** [comment]
Thanks for your reply. I'm afraid you closed this issue too quickly. ;-)
I changed the ```request_handlers``` definition accordingly and restarted ejabberd but unfortunately I keep getting the same error. :-(

**Comment by weiss** [comment]
Weird.  You could set `loglevel: 5` and then grep the `ejabberd_http` and `mod_http_upload` lines from your `ejabberd.log` file, though I'm not sure that reveals the issue.  Maybe you could also test without Nginx and/or omit the `upload` part from the URL just to track the issue down a bit.  

Do you build ejabberd from source so that I could give you a patch that adds debug output to the relevant parts of the code?

**Comment by alexara** [comment]
I will try your suggestions.
>Do you build ejabberd (or the module) from source, so that I could give you a patch that adds debug output to the relevant parts of the code?

Yes, I do. I would appreciate that very much!

**Comment by alexara** [comment]
I am very sorry that I took your time!!!! I found the issue: The mod_http_upload from the contrib folder survived the upgrade and interfered the whole time! I ain't know why I forgot about that. Shame on me!

**Comment by weiss** [comment]
No problem :-)  Glad to hear it's working now.
