### ISSUE TITLE
ejabberdctl requires insane quoting (send_stanza_c2s)

### ISSUE THREAD

**Issue by cweiske** [processone/ejabberd#804]
I'm trying to send a message via `ejabberdctl send_stanza_c2s`, which requires 4 parameters:

    $ ejabberdctl |grep send_stanza
    send_stanza_c2s user host resource stanza 

    $ ejabberdctl send_stanza_c2s alice example.org resource '<message type="chat" to="bob@example.org" from="alice@example.org"><body>World</body></message>'
    Error: the command "send_stanza_c2s" requires 3 less argument.

It works when you quote the space within the command strangely:

    $ ejabberdctl send_stanza_c2s alice example.org "Psi+" "<message' 'type=\"chat\"' 'to=\"bob@example.org\"' 'from=\"alice@example.org\"><body>World</body></message>"

This is not friendly at all. Please make normal shell quoting work.

**Comment by badlop** [comment]
You're right, using that command is quite difficult. Please make a suggestion for improving it.

**Comment by cweiske** [comment]
using standard shell quoting should be enough:

    $ ejabberdctl send_stanza_c2s alice example.org resource '<message type="chat" to="bob@example.org" from="alice@example.org"><body>World</body></message>'

**Comment by badlop** [comment]
As alternative, you can use mod_rest and wget client, see this example: https://github.com/processone/ejabberd-contrib/issues/142#issuecomment-167985782

**Comment by prefiks** [comment]
This should be fixed by commit 98bad73d562f202c606f1aa8e51e1c2756cba15f
