### ISSUE TITLE
Running `ejabberdctl join_cluster node@host` with the -noshell

### ISSUE THREAD

**Issue by richardardrichard** [processone/ejabberd#805]
To get `join_cluster` to work in a script I had to add the `-noshell` option in the `joincluster` script here https://github.com/processone/ejabberd/blob/master/tools/joincluster#L148, otherwise you get an erlang terminated error message. Can this get added to the `joincluster` script?

**Comment by cromain** [comment]
We're not using scripts anymore for clustering. So this issue is fixed and obsolete now.
see 15.11 blogpost

**Comment by BradErz** [comment]
Hey there,

We are using an older version of ejabberd (15.07), would it be possible to let me know which part of the joincluster script you edited to include -noshell?

Thanks

**Comment by richardardrichard** [comment]
https://github.com/processone/ejabberd/blob/15.07/tools/joincluster#L148 add it as an argument to the $ERL command
