### ISSUE TITLE
join_cluster exits after finding ejabberdctl

### ISSUE THREAD

**Issue by 7adietri** [processone/ejabberd#807]
In 15.10, the join_cluster command exits after displaying:

    Using commands:
    /opt/ejabberd/sbin/ejabberdctl

I can get it to continue by removing the `exec` on this line: https://github.com/processone/ejabberd/blob/15.10/tools/joincluster#L70

The server is compiled from source with `--prefix=/opt/ejabberd`.

**Comment by cromain** [comment]
We're not using scripts anymore for clustering. So this issue is fixed and obsolete now.
see 15.11 blogpost
