### ISSUE TITLE
mod_http_upload error bad argument erlang,list_to_binary

### ISSUE THREAD

**Issue by suchatorg** [processone/ejabberd#808]
In ejabberd-15.10 gives the error:

exception error: bad argument: [{erlang,list_to_binary,[<<"/home/ejabberd/upload/f8880dc99ebe09e1d66e209cc39e1d7edf234653/H7MSmRjskPajCRO9wksnZwxncwmE34HtGUfy9Wl6/2293713551.jpeg">>],[]},{mod_http_upload,thumb_el,2,[{file,"src/mod_http_upload.erl"},{line,893}]},{mod_http_upload,store_file,7,[{file,"src/mod_http_upload.erl"},{line,743}]},{mod_http_upload,process,2,[{file,"src/mod_http_upload.erl"},{line,372}]},{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,360}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,448}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,290}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,210}]}]
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.37.0>]
	
In ejabberd-15.09 adding  mod_http_upload no have error.
Thank you

**Comment by weiss** [comment]
Ah, I see the problem and will fix it tomorrow.  As a quick workaround, you can disable thumbnail creation if you don't need that feature:

    modules:
      # [...]
      mod_http_upload:
        thumbnail: false
        # [...]

**Comment by shajunr88** [comment]
Iam using ejabberd 16.09 and mod_http_upload is enabled with thumbnail: true.Thumbnail of the image is generated in the server and can be viewed in server.But the thumbnail generated is not passing to the client using <thumnail> tag as said in the protocol.
