### ISSUE TITLE
Setting up mod_carboncopy, nothing is coming through. 

### ISSUE THREAD

**Issue by clarklight** [processone/ejabberd#811]
Hi 

   I am wondering if i am configuring my mod_carboncopy correctly. As i am not getting any input back for carboncopy but i am for all the other functions like sending/receiving messages. Just got a few questions. 

1.) I read the document that it is on by default? 
1.) If i can config mod_carboncopy in the web admin panel in the options inside module tab??
2.) Or do i have to config it in config.yml
3.) After i config it do i have to reboot the server??
4.) After that is set up. Would i see the copy straight away in a (my client side i have a RAW xml input/output) for device 2, if device 1 sends out a message?? Or would i have to request it again from the client side?? 

Thanks

**Comment by weiss** [comment]
> I read the document that it is on by default?

The module is [enabled in the example configuration file][1].  Did you check whether it's enabled in your `ejabberd.yml`?

> Or would i have to request it again from the client side?

The client must support [the extension][2] to receive carbon copies.

If you have further questions, please ask on the [mailing list][3], in the [forums][4], or in the [conference room][5].

[1]: https://github.com/processone/ejabberd/blob/9d2f1d5f0d8215142d53e3d095f4f3638b172abb/ejabberd.yml.example#L579
[2]: http://xmpp.org/extensions/xep-0280.html
[3]: http://lists.jabber.ru/mailman/listinfo/ejabberd
[4]: https://www.ejabberd.im/forum
[5]: https://www.ejabberd.im/chatroom
