### ISSUE TITLE
[Feature request] Implement XMPP XEP-0194 User Chatting support in ejabberd Jabber server

### ISSUE THREAD

**Issue by Qseo** [processone/ejabberd#812]
Will be good to have XEP-0194 User Chatting support in future ejabberd server releases, discussion about this in forum https://www.ejabberd.im/forum/25234/support-xmpp-xep-0194-user-chatting-ejabberd-jabber-server

**Comment by rraptorr** [comment]
XEP-0194 is deferred since 2008. I doubt it would be wise to implement it.

**Comment by prefiks** [comment]
Also, looks like this is no server component required for it, it only requires pubsub/pep that ejabberd already have, that client conforming to this xep, should use to put informations about connected rooms.

**Comment by MurzNN** [comment]
Seems that this must be implemented in server side, not on client, here is Jabber bots that do same thing: https://github.com/javiermon/xmpp-muc-bot
http://sleekxmpp.com/getting_started/muc.html
https://github.com/javiermon/xmpp-muc-bot
https://github.com/twonds/palaver

**Comment by MurzNN** [comment]
If this must be impelemented not in server side, how Prosody impement XEP-0194 in his server? http://prosody.im/doc/xeplist
http://i.imgur.com/aSNQCG4.png
Seems that clients see this users chat like classic conference in roster, but this conference server send all offline messages to client directly when client is offline.

**Comment by rraptorr** [comment]
It is on a list of supported protocols, I doesn't mean that there is any special code in the server. In fact, I've checked Prosody source code, there is not a single line related to XEP-0194. Please read http://xmpp.org/extensions/xep-0194.html for details, it clearly describes how it works and what must be done by the client.

**Comment by weiss** [comment]
> how Prosody impement XEP-0194 in his server?

The client uses the server's [PEP][1] component to publish that information.  Presumably, XEP-0194 was added to that list because Prosody supports PEP.  In that sense, ejabberd supports XEP-0194 as well.  Your "client MAY publish that fact to a PEP node whose NodeID is 'urn:xmpp:chatting:0'" as [described][2] in that XEP.

> Seems that clients see this users chat like classic conference in roster, but this conference server send all offline messages to client directly when client is offline.

This sounds totally unrelated to XEP-0194.

[1]: http://xmpp.org/extensions/xep-0163.html
[2]: http://xmpp.org/extensions/xep-0194.html#protocol-transport
