### ISSUE TITLE
missing captcha.sh with 15.10

### ISSUE THREAD

**Issue by erik-de-neve** [processone/ejabberd#817]
Hello,

I used the Linux x86 64-bits installer package on a Ubuntu Server but the captcha.sh is not deployed.
If I install the 15.09 version the captcha file is deployed correctly (lib/ejabberd-15.09/priv/tools/captcha.sh).

Thanks,
Erik

**Comment by cromain** [comment]
This is fixed in 15.11. path of the file changed to lib/ejabberd-15.11/priv/bin/captcha.sh  (to more tools library)
