### ISSUE TITLE
mod_mam on ejabberd  15.10.7 not working  with Riak as backend?

### ISSUE THREAD

**Issue by tufguy** [processone/ejabberd#818]
Hi, 

I was trying mod_mam message archiving with ejabberd 15.10.7. it works without any issues on MySQL but with Riak it doesn't work as i was under impression it will work 0.3 mam version. I know the doc doesn't mention riak as supported but docs may not be updated so just checking.

**Comment by zinid** [comment]
Riak is not supported in current MAM implementation.
