### ISSUE TITLE
How can I   checking whether user existing or not

### ISSUE THREAD

**Issue by kevinsir** [processone/ejabberd#822]
I am trying to send a request to find a user is existing  with server through DiscoInfo query.
 if user (JID) is not registered with server, we will get response with Type="error", error code="404"
"Item-not-found",If user is registered with server, we will get  with Type="result" with feature list irrespective.when i tested with Ejabberd it is giving response type="error" error code=“503” “service-unavailable” no matter user is registered or not . But when i tested with Openfire i am getting proper responses, for user exist or not.
Is it a bug in ejabberd? or some proper reason for this?

**Comment by kevinsir** [comment]
openfire  has a ‘Search Service’ Properties 
which as follows 
Use the form below to restrict the search scope so users can search for anyone or only users in the same group. 

  Anyone - Clients will be able to search for all users.  
  Group - Clients will be able to only search for users in their group.  
Is there any Property about ejabberd？

**Comment by badlop** [comment]
> when i tested with Ejabberd it is giving response type="error" error code=“503” “service-unavailable” no matter user is registered or not .

That behaviour is expected, and follows this paragraph:
> In response to a disco#info request, the server MUST return a <service-unavailable/> error if one of the following is true:
> - The target entity does not exist (no matter if the request specifies a node or not).
> - The requesting entity is not authorized to receive presence from the target entity (i.e., via a presence subscription of type "both" or "from") or is not otherwise trusted (e.g., another server in a trusted network).

See http://xmpp.org/extensions/xep-0030.html#security

**Comment by kevinsir** [comment]
Thanks for your reply. However, how can I check that   a user is existing with server or not? Is there any other way to do ?

**Comment by badlop** [comment]
Not using XMPP. However, if you administer the server, probably it provides some method. In ejabberd, you can run an ejabberd command, for example:
```
$ ejabberdctl check_account user1 localhost 
$ echo $?
0

$ ejabberdctl check_account user666 localhost 
$ echo $?
1
```

**Comment by joanlopez** [comment]
There's any XMPP option with the latests versions? Maybe something related with the XEP-055 @badlop

**Comment by kevinsir** [comment]
With the reason,maybe it is difficult to me. I turn to the openfire!
