### ISSUE TITLE
Pubsub normal chat message having type=headline when published from offline storage

### ISSUE THREAD

**Issue by kartikpatel11** [processone/ejabberd#827]
Hi,
I seem to have observerd weird behavior with offline messages(type=normal) when they get published on pubsub node. Not sure if its intentional but want to highlight it. shouldn't the pubsub offline message also get published as type=normal instead of type=headline?

Below is the scenario:
1. Create pubsub node with notification_type as normal using smack library
```
2015-11-08 00:42:46.591 [debug] <0.602.0>@mod_pubsub:tree_call:4067 tree_call <<"pubsub.abc.example.com">> set_node [{pubsub_node,{<<"pubsub.abc.example.com">>,<<"630461e0c584464096849dd451343b60">>},29,[],<<"flat">>,[{<<"+999999">>,<<"abc.example.com">>,<<>>}],[{presence_based_delivery,false},{notification_type,normal},{publish_model,open},{access_model,open},{persist_items,false},{notify_retract,false},{deliver_payloads,true},{notify_config,false},{notify_delete,false},{purge_offline,false},{max_items,10},{subscribe,true},{roster_groups_allowed,[]},{max_payload_size,60000},{send_last_published_item,on_sub_and_presence},{deliver_notifications,true}]}]
```
2. publisher publishes message to pubsub node. 
```
<iq to='pubsub.chat.votesup.com' id='Jk749-95' type='set'>
  <pubsub xmlns='http://jabber.org/protocol</pubsub'>
  <publish node='630461e0c584464096849dd451343b60'>
     <item>
       <x xmlns=\"jabber:x:oob\">
         <file1url>1446923856478961000.jpeg</file1url>
         <postuuid>a3f75ef0-9d39-42b8-8c86-91aa497b56ca</postuuid>
         <from>+888888</from>
       </x>
    </item>
  </publish>
 </pubsub>
</iq>
```
3. The message is deliverd to online users of pubsub node as normal chat message (without type=headline tag)
```
<message from='pubsub.chat.votesup.com' to='+777777@abc.example.com'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
     <items node='630461e0c584464096849dd451343b60'>
        <item id='5A6E18D118E80'>
          <x xmlns='jabber:x:oob'>
            <file1url>1446923856478961000.jpeg</file1url>
            <postuuid>a3f75ef0-9d39-42b8-8c86-91aa497b56ca</postuuid>
            <from>+888888</from>
         </x>
       </item>
    </items>
  </event>
</message>
```
3. receiver is offline so message goes to offline queue of receiver.

4. receiver become online and message pulled from offline storage. however, this time , the same message has type=headline

```
<message from='pubsub.abc.example.com' to='+999999@abc.example.com'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
      <items type='headline' node='630461e0c584464096849dd451343b60'>
         <item id='5A6E18D118E80'>
            <x xmlns='jabber:x:oob'>
               <file1url>1446923856478961000.jpeg</file1url>
               <postuuid>a3f75ef0-9d39-42b8-8c86-91aa497b56ca</postuuid>
               <from>+888888</from>
           </x>
         </item>
      </items>
  </event>
  <delay xmlns='urn:xmpp:delay' from='+888888@abc.example.com/+888888' stamp='2015-11-07T19:17:37Z'></delay>
</message>
```

**Comment by cromain** [comment]
with notification_type=normal, message is stored offline. when receiver becomes online, it receives the message twice:
1/ from offline spool, without headline attribute
2/ from pubsub send loop (as node is still configured with send_last_published_item=on_sub_and_presence)

this is the send_last_published_item feature which adds headline type.

when configuring pubsub node with notification_type=normal, it's best to disable send_last_published_item or set it to on_sub only in order to avoid receiving the message twice.

I'm checking the send_last_published loop to let it use configured notification type

**Comment by nivan22** [comment]
http://jabber.org/protocol/pubsub#event'>
      <items type='headline' node='630461e0c584464096849dd451343b60'>
         <item id='5A6E18D118E80'>
            <x xmlns='jabber:x:oob'>
               <file1url>1446923856478961000.jpeg</file1url>
               <postuuid>a3f75ef0-9d39-42b8-8c86-91

**Comment by cromain** [comment]
can you please edit your post and escape the payload to display code as described here
https://guides.github.com/features/mastering-markdown/

**Comment by cromain** [comment]
last commit fix notification type on send last items.
you still have to alter send_last_published_item value to avoid receiving message twice in your case (i.e. not use offline storage but keep pubsub storage)

**Comment by brokeniceinteractive** [comment]
@cromain is there a possibility to use offline storage instead of pubs storage? see this my issue https://github.com/processone/ejabberd/issues/903 thanks!
