### ISSUE TITLE
ejabberd does not validate xmppAddr in client certificates

### ISSUE THREAD

**Issue by hitched97** [processone/ejabberd#829]
[RFC 6120](http://tools.ietf.org/html/rfc6120) says, in section [10.7.1.3](https://tools.ietf.org/html/rfc6120#section-13.7.1.3):

> In a PKIX certificate to be presented by an XMPP client controlled by
> a human user (i.e., a "client certificate"), it is RECOMMENDED for
> the certificate to include one or more JIDs associated with an XMPP
> user.  If included, a JID MUST be represented as an XmppAddr as
> specified under Section 13.7.1.4.

ejabberd will look for an xmppAddr and validates it in s2s connections, but does not look for or validate an xmppAddr when a jabber client connects.

I'd like to suggest three modes of operation:
1.  Ignore xmppAddr (current behavior).
2.  If an xmppAddr appears in a client certificate, it must match the user login.
3.  xmppAddr _must_ appear in client certificates, and must match user login.

I do not know erlang, else I would make an attempt at implementing this on my own.

**Comment by zinid** [comment]
This is implemented a long time ago.
