### ISSUE TITLE
dhfile/s2s_dhfile parameter no longer working

### ISSUE THREAD

**Issue by 7adietri** [processone/ejabberd#830]
xmpp.net started reporting that I am using only 1024 bit DH parameters from the `RFC 5114 1024-bit MODP Group`. This sounds like ejabberd is no longer loading my generated 2048 bit DH parameter file, as it did previously.

**Comment by weiss** [comment]
I can't really make any useful comment without additional information.  Does xmpp.net report the same thing for client and server connections, for example?

**Comment by 7adietri** [comment]
Yes, we are using the same parameter file for both settings.

**Comment by weiss** [comment]
I was asking whether xmpp.net reports this issue both for client and for server connections.

**Comment by 7adietri** [comment]
Yes, both tests (client and server) report the same issue.

Also interesting: I passed a non-existent file to `dhfile`, but there was no error message (still the same test result from xmpp.net, though). As if the parameter wasn't even used.

**Comment by weiss** [comment]
What ejabberd version are you using, and how did you install it?

**Comment by 7adietri** [comment]
It's 15.10 built from source.

On November 10, 2015 11:49:17 PM CET, "Holger Weiß" <notifications@github.com> wrote:
>What ejabberd version are you using, and how did you install it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/processone/ejabberd/issues/830#issuecomment-155592740

-- 
Sent from my toaster

**Comment by weiss** [comment]
And `git --git-dir deps/p1_tls/.git rev-parse HEAD` (called from the ejabberd source directory) says `e56321afd974e9da33da913cd31beebc8e73e75f`?

Just to make sure: It's not a permission issue?  I.e. the user running ejabberd can read the DH parameters file?

**Comment by 7adietri** [comment]
The commit I'm seeing is `e97b7bb6a6fbba789d7b5f0d253438637caef329`. Did I miss some command to update the dependencies?

The file permissions are ok.

**Comment by weiss** [comment]
> The commit I'm seeing is `e97b7bb6a6fbba789d7b5f0d253438637caef329`.

That explains the issue, but it doesn't explain why it worked before.

> Did I miss some command to update the dependencies?

`make update` should do the trick.
