### ISSUE TITLE
mod_multicast does not trigger offline_message_hook when send message to offline user

### ISSUE THREAD

**Issue by shyaken** [processone/ejabberd#832]
I have a module that hook to offline_message_hook, it work ok with 1-1 chat and multicast in 14.12 version
after I udgrade to ejabberd 15.09, the 1-1 chat still trigger offline_message_hook but multicast does not trigger it.
Is this a bug or multicast message cannot trigger offline_message_hook?
Thanks.

**Comment by badlop** [comment]
I'm testing with ejabberd git mast, which is similar to 15.10. When sending a muticast stanza, one function that is hooked to the event gets called, at least in this example:
```
mod_offline:store_packet(
  {jid,<<"user1">>,<<"localhost">>,<<"tka1">>,<<"user1">>,<<"localhost">>,<<"tka1">>},
  {jid,<<"user2">>,<<"localhost">>,<<"tka1">>,<<"user2">>,<<"localhost">>,<<"tka1">>},
  {xmlel,<<"message">>,
       [{<<"xml:lang">>,<<"es">>},{<<"to">>,<<"multicast.localhost">>}],
       [{xmlel,<<"addresses">>,
               [{<<"xmlns">>,<<"http://jabber.org/protocol/address">>}],
               [{xmlel,<<"address">>,
                       [{<<"type">>,<<"cc">>},
                        {<<"jid">>,<<"user2@localhost/tka1">>},
                        {<<"desc">>,<<"Jeremie Miller">>}],
                       []}]},
        {xmlel,<<"body">>,[],[{xmlcdata,<<"Hello, world!">>}]},
        {xmlcdata,<<"\n">>}]})
```

**Comment by shyaken** [comment]
I'm sorry this problem caused by my module, it cannot parsed multicast messages. I resolved it already.
Thanks very much
