### ISSUE TITLE
remote-server-not-found

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#833]
<pre>
<code>
"presence xmlns='jabber:client' from='nxp199eebfe4fbed8eb5769d6307696e0c7b78@hihayati.com' to='nxp199d37ef97ad50ae0ed82af9d677a868c7d@api.hihayati.com/Hayati.iOS' type='error'
	error code='404' type='cancel'
		remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'
		remote-server-not-found
	error
presence"
</code>
</pre>

what it could be the error 

thank you,

**Comment by mremond** [comment]
You are trying to reach "api.hihayati.com" XMPP server, but s2s session could not be established.

**Comment by hassanzreik** [comment]
@mremond  i want to check the presence of other users so it should be from c2s right?
also the xml should be like the below: 
presence xmlns='jabber:client' from='nxp199eebfe4fbed8eb5769d6307696e0c7b78@api.hihayati.com' to='nxp199d37ef97ad50ae0ed82af9d677a868c7d@api.hihayati.com/Hayati.iOS' type='error'
presence

is it correct? they should be the same host name 

thanks again
