### ISSUE TITLE
install ejabberd on Centos

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#834]
Dears, 

Kindly note that i was searching how to install ejabberd on Centos OS but no one is working, is there an installation and configuration tutorial for it?

Thanks :D

**Comment by nunohorta** [comment]
if you go to the downloads page https://www.process-one.net/en/ejabberd/downloads there's an installer...just run that and its pretty straight forward. What have you tried so far? Why is it not working(errors?)?

**Comment by hassanzreik** [comment]
i downloaded the run script and it didnt work i dont know why i cant get ejabberdctl command... i will re-install it again and send the output... kindly question when i run the installer should i download the ejabberd from github and install it? and how i will connect to database 

thanks

**Comment by badlop** [comment]
> kindly question when i run the installer should i download the ejabberd from github and install it?

No need, in fact don't mix them or you will get confused. Each one is a different way to get ejabberd binaries, install and run. See
http://docs.ejabberd.im/admin/guide/installation/
