### ISSUE TITLE
not-authorized error when try to login 

### ISSUE THREAD

**Issue by dongmai** [processone/ejabberd#838]
Hello everyone, 

I'm facing a problem that is when trying to connect to Ejabberd accounts and get this error:
<img width="627" alt="screen shot 2015-11-13 at 4 51 53 pm" src="https://cloud.githubusercontent.com/assets/3855966/11143333/de39c1f2-8a26-11e5-895b-078b8d38fcc3.png">

Please help me to resolve this.
Thanks.

**Comment by mremond** [comment]
It seems self explanatory to me. You could not login because user does not exist or password is incorrect.

**Comment by dongmai** [comment]
I've added these accounts via Admin panel successfully.

**Comment by VitorCioletti** [comment]
@zinid helped me solve a similar issue. See #2762
