### ISSUE TITLE
ejabberd@api seems to be in use by another Erlang node

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#839]
Dears,

Im getting the below errors while running ejabberd commend please help, thank you

{error_logger,{{2015,11,16},{9,42,26}},"Protocol: ~tp: the name ejabberd@api seems to be in use by another Erlang node",["inet_tcp"]}
{error_logger,{{2015,11,16},{9,42,26}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.101>,<0.17.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,756}],[]]}
{error_logger,{{2015,11,16},{9,42,26}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[[ejabberd,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2015,11,16},{9,42,26}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2015,11,16},{9,42,26}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2015,11,16},{9,42,26}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump was written to: /var/log/ejabberd/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k

**Comment by hassanzreik** [comment]
Also i want to activate mod_webpresence, thanks again

**Comment by hassanzreik** [comment]
Any one can help me to solve this issue please

**Comment by sameer17cs** [comment]
You have an Erlang node already running. Check your processes using ps.  If
you are unable to locate its pid, run pkill -f erl

**Comment by hassanzreik** [comment]
thank you @sameer17cs  it works..
other error now

C(<0.40.0>:ejabberd_check:63) : ejabberd is configured to use 'mysql', but the following Erlang modules are not installed: '[mysql,
                                                                                                                             mysql_auth,
                                                                                                                             mysql_conn,
                                                                                                                             mysql_recv]'

=INFO REPORT==== 17-Nov-2015::08:39:11 ===
    application: ejabberd
    exited: {bad_return,{{ejabberd_app,start,[normal,[]]},
                         {'EXIT',database_module_missing}}}
    type: temporary

do you have a solution for it?

**Comment by sameer17cs** [comment]
You can specify enable mysql while doing ./configure (check configure --
help). Alternatively, you can modify the file rebar.config.script to have
p1_mysql downloaded to your deps folder everytime

**Comment by hassanzreik** [comment]
i installed ejabberd using apt-get install ejabberd where can i find the configure that you are talking about?

**Comment by hassanzreik** [comment]
i searched for rebar is not found

**Comment by sameer17cs** [comment]
Should be in the folder where binaries have been downloaded by apt.
I will suggest to pull the ejabberd source from github and build it
yourself, it is easy and well documented.

**Comment by hassanzreik** [comment]
so i should remove the current ejabberd and install the source code this is better right?

**Comment by hassanzreik** [comment]
i should remove everything related such as erlang version and make it fresh install?

**Comment by sameer17cs** [comment]
Yes that would be better. Make sure you install the dependencies as
mentioned in the document

**Comment by sameer17cs** [comment]
No erlang installation is fine. You Dont need to remove that

**Comment by hassanzreik** [comment]
thank you very much @sameer17cs you saved me

**Comment by sameer17cs** [comment]
Anytime :)

**Comment by hassanzreik** [comment]
Dear @sameer17cs 

Do you have any idea about the below? 
root@api:/home/ubuntu/ejabberd# ./autogen.sh
./autogen.sh: line 2: aclocal: command not found
./autogen.sh: line 3: autoconf: command not found

thank you

**Comment by hassanzreik** [comment]
done i installed them lol

**Comment by sameer17cs** [comment]
Why do you need to run this script?

I think configure with mysql,make, make install.. these will do for you.

**Comment by hassanzreik** [comment]
after make install i run ejabberdctl start i get the below
bash: /usr/sbin/ejabberdctl: No such file or directory

is there any error? i install as the documentation

**Comment by sameer17cs** [comment]
Did you compile as root? If yes then run it with sudo.
If not, you need to create soft link in /usr folder:   ln -s
/sbin/ejabberdctl  /usr/sbin/ejabberdctl

Otherwise use  /sbin/ejabberdctl start

**Comment by hassanzreik** [comment]
thank you @sameer17cs it works 

if i want to change from localhost to api.domain.com and to add the mysql connection i should edit the ejabberd.yml or ejabberdctl.cfg?

**Comment by hassanzreik** [comment]
also question should i stop ejabberdctl before editing the configuration?

**Comment by sameer17cs** [comment]
ejabberd.yml for mysql ip

ejabberdctl.cfg for hostname

**Comment by sameer17cs** [comment]
Yes you have to restart after making the changes

**Comment by hassanzreik** [comment]
i changed host name in ejabberdctl i get the below
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by sameer17cs** [comment]
Remove old mnesia database.
rm -rf /var/lib/ejabberd/*;
rm -rf /lib/ejabberd/*

**Comment by hassanzreik** [comment]
i get the below 

root@api:/etc/ejabberd# ejabberdctl restart
{"init terminating in do_boot",{undef,[{ejabberd_ctl,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: //var/log/ejabberd/erl_crash_20151117-104002.dump
init terminating in do_boot ()

**Comment by sameer17cs** [comment]
Do make install again

**Comment by hassanzreik** [comment]
to create admin for the web interface i should use ejabberdctl regiter right?

**Comment by hassanzreik** [comment]
sorry for disturbing and thank you for your help @sameer17cs but why im still getting the below
root@api:/home/ubuntu/ejabberd# ejabberdctl restart
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by sameer17cs** [comment]
Do a stop and again start. Or get to live mode and check what is the exact
error

**Comment by hassanzreik** [comment]
there is no error occur i run ejabberdctl live i get the below and it freezes  

Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V6.4  (abort with ^G)
(ejabberd@api.hihayati.com)1> 11:05:06.157 [info] Application lager started on node 'ejabberd@api.hihayati.com'
11:05:06.171 [info] Application crypto started on node 'ejabberd@api.hihayati.com'
11:05:06.187 [info] Application sasl started on node 'ejabberd@api.hihayati.com'
11:05:06.208 [info] Application asn1 started on node 'ejabberd@api.hihayati.com'
11:05:06.208 [info] Application public_key started on node 'ejabberd@api.hihayati.com'
11:05:06.224 [info] Application ssl started on node 'ejabberd@api.hihayati.com'
11:05:06.227 [info] Application p1_yaml started on node 'ejabberd@api.hihayati.com'
11:05:06.233 [info] Application p1_tls started on node 'ejabberd@api.hihayati.com'
11:05:06.244 [info] Application p1_xml started on node 'ejabberd@api.hihayati.com'
11:05:06.247 [info] Application p1_stringprep started on node 'ejabberd@api.hihayati.com'
11:05:06.249 [info] Application p1_zlib started on node 'ejabberd@api.hihayati.com'
11:05:06.264 [info] Application p1_cache_tab started on node 'ejabberd@api.hihayati.com'
11:05:06.453 [info] Application mnesia started on node 'ejabberd@api.hihayati.com'
11:05:07.665 [info] Application inets started on node 'ejabberd@api.hihayati.com'
11:05:08.379 [info] Application p1_mysql started on node 'ejabberd@api.hihayati.com'
11:05:08.444 [info] FQDN used to check DIGEST-MD5 SASL authentication: api
11:05:08.448 [info] Application oauth2 started on node 'ejabberd@api.hihayati.com'
11:05:08.478 [info] Application p1_iconv started on node 'ejabberd@api.hihayati.com'
11:05:08.545 [info] Reusing listening port for {5222,{0,0,0,0},tcp}
11:05:08.546 [info] Reusing listening port for {5269,{0,0,0,0},tcp}
11:05:08.546 [info] Reusing listening port for {5280,{0,0,0,0},tcp}
11:05:08.546 [info] ejabberd 15.10.32 is started in the node 'ejabberd@api.hihayati.com'
11:05:08.546 [info] Application ejabberd started on node 'ejabberd@api.hihayati.com'

**Comment by hassanzreik** [comment]
then i abort it and run ejabberdctl status is still get 
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by hassanzreik** [comment]
also other question how can i create user to login into web interface 

great thanks for you @sameer17cs

**Comment by sameer17cs** [comment]
Your ejabberd has started fine. can you run `hostname -f` and print the
result


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by sameer17cs** [comment]
If your system hostname and ejabberd hostname doesnot match, ejabberdctl
will not be able to connect to shell.

Better you specify your ejabberd host as ERLANG_NODE=ejabberd@`hostname -f`
and then change your system hostname to whichever you want


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
they are matching  when i am adding the user for web this occur

root@api:/home/ubuntu/ejabberd# ejabberdctl register admin api.hihayati.com ****
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by sameer17cs** [comment]
what is your system hostname?

how have you specified ERLANG_NODE ?

repeat these steps and see if it works:
pkill -f erl; pkill -f epmd
rm -rf /var/log/ejabberd/* ; rm -rf /var/lib/ejabberd/* ; rm -rf
/etc/ejabberd/* ; rm -rf /lib/ejabberd/*

./configure *--enable-mysql*
make

make install

Make changes in ctl and cfg

/sbin/ejabberdctl start

/sbin/ejabberdctl status


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
my hostname is api.hihayati.com.. i will repeat the steps and reconfigure mysql connection in ejabberd.yml and erlang node in ejabberdctl.cfg??

**Comment by sameer17cs** [comment]
yes.

use ERLANG_NODE=ejabberd@`hostname -f` in ejabberdctl.cfg


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
there is something weird i do the steps you requested and i still get the below whats wrogn?

root@api:/home/ubuntu/ejabberd# ejabberdctl register admin api.hihayati.com  ******
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by sameer17cs** [comment]
run /sbin/ejabberdctl live and send the results


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
i guess it is working properly here

Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V6.4  (abort with ^G)
(ejabberd@api.hihayati.com)1> 13:37:49.297 [info] Application lager started on node 'ejabberd@api.hihayati.com'
13:37:49.303 [info] Application crypto started on node 'ejabberd@api.hihayati.com'
13:37:49.318 [info] Application sasl started on node 'ejabberd@api.hihayati.com'
13:37:49.335 [info] Application asn1 started on node 'ejabberd@api.hihayati.com'
13:37:49.335 [info] Application public_key started on node 'ejabberd@api.hihayati.com'
13:37:49.351 [info] Application ssl started on node 'ejabberd@api.hihayati.com'
13:37:49.366 [info] Application p1_yaml started on node 'ejabberd@api.hihayati.com'
13:37:49.380 [info] Application p1_tls started on node 'ejabberd@api.hihayati.com'
13:37:49.384 [info] Application p1_xml started on node 'ejabberd@api.hihayati.com'
13:37:49.386 [info] Application p1_stringprep started on node 'ejabberd@api.hihayati.com'
13:37:49.397 [info] Application p1_zlib started on node 'ejabberd@api.hihayati.com'
13:37:49.399 [info] Application p1_cache_tab started on node 'ejabberd@api.hihayati.com'
13:37:49.590 [info] Application mnesia started on node 'ejabberd@api.hihayati.com'
13:37:50.563 [info] Application inets started on node 'ejabberd@api.hihayati.com'
13:37:51.203 [info] Application p1_mysql started on node 'ejabberd@api.hihayati.com'
13:37:51.261 [info] FQDN used to check DIGEST-MD5 SASL authentication: api
13:37:51.263 [info] Application oauth2 started on node 'ejabberd@api.hihayati.com'
13:37:51.271 [info] Application p1_iconv started on node 'ejabberd@api.hihayati.com'
13:37:51.326 [info] Reusing listening port for {5222,{0,0,0,0},tcp}
13:37:51.327 [info] Reusing listening port for {5269,{0,0,0,0},tcp}
13:37:51.327 [info] Reusing listening port for {5280,{0,0,0,0},tcp}
13:37:51.327 [info] ejabberd 15.10.32 is started in the node 'ejabberd@api.hihayati.com'
13:37:51.327 [info] Application ejabberd started on node 'ejabberd@api.hihayati.com'

**Comment by hassanzreik** [comment]
root@api:/home/ubuntu/ejabberd# hostname -f
api.hihayati.com

**Comment by hassanzreik** [comment]
root@api:/home/ubuntu/ejabberd# ejabberdctl status
Failed RPC connection to the node 'ejabberd@api.hihayati.com': nodedown

**Comment by hassanzreik** [comment]
Dear @sameer17cs  

why it still appears like that?

Thank you,

**Comment by sameer17cs** [comment]
Can you revert the hostname back to localhost and check if it is working?


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
it works, so what was the problem, also i cant find complete menu in the web admin interface 
![untitled](https://cloud.githubusercontent.com/assets/4625505/11237228/31ed23de-8de7-11e5-9ef8-12b75ac5494f.png)

**Comment by hassanzreik** [comment]
i will use the chatting server to develop an ios app will it works if we use @localhost? other question will users be inserted to database automatic or i should insert them?

**Comment by sameer17cs** [comment]
No i asked to use localhost just to check where the problem is. If it works
fine with localhost then there is something wrong the way you are updating
your erlang hostname.

Also, to change hostname for user, you have to modify it in ejabberd.yml
file, hosts key.
Changing hostname in ejabberdctl.cfg is not necessary.

For user registration, you can do it either directly using ejabberdctl or
through xmpp packets(see xmpp protocol to register users)


*Sameer Deshmukh**Hyderabad*

*07680997872*

**Comment by hassanzreik** [comment]
the side menu of the web admin panel is empty? do you know why? it appears just virtual hosts and it is empty

**Comment by badlop** [comment]
> the side menu of the web admin panel is empty? do you know why? it appears just virtual hosts and it is empty

You can see the WebAdmin, which means the account and password you provided is correct. However, you can not see all the WebAdmin pages, which means the account you provided does not have admin rights in your ejabberd config.

**Comment by hassanzreik** [comment]
thank you @badlop and @sameer17cs for your help
