### ISSUE TITLE
Offline muc invite not working

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#841]
HI Guys, 

I am using mod_muc to implement chat room. When I am inviting users and if the user is online it is working fine. In case the user is offline it is dropping the packet.

I have enabled offline messages and resend_on_timeout:true so messages are not send back to my client. Are these packets not stored in offline storage.

Here is my stanza
```xml
<message to='arbit4@conference.ejabberd.sandwitch.in' id='36l0H-60'><x xmlns='http://jabber.org/protocol/muc#user'><invite to='c07fc9f1-15d9-41e2-aece-f778c115532e@ejabberd.sandwitch.in'><reason>Join me</reason></invite></x></message><r xmlns='urn:xmpp:sm:3'/>

12:01:16 PM SENT (0): <message to='arbit6@conference.ejabberd.sandwitch.in' id='81VV6-67' type='normal'><x xmlns='http://jabber.org/protocol/muc#user'><invite to='harshit@ejabberd.sandwitch.in'>
<reason>Join me</reason></invite></x></message><r xmlns='urn:xmpp:sm:3'/>
```

**Comment by bangarharshit** [comment]
Edited since xml was not escaped. Looks to me that the message is not saved in offline (spool table). XE-0160  states  that normal or no type message should be stored offline - http://xmpp.org/extensions/xep-0160.html. 
I can't set body or change type of invites as the server throw modify content invitation.

**Comment by bangarharshit** [comment]
My error. The client was online with one resource.

**Comment by edukondalugorla** [comment]
Hi when i am inviting user to group server is not  giving response and also muc_invite event also not working


<message  
    to='edukondalu22@conference.myhost.com'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <invite to='58ec7113f7e43f11cee552ce@myhost.com'>    
      <reason>Hey Hecate, this is the place for all good witches!</reason>
    </invite>    
  </x>
</message>
