### ISSUE TITLE
Chat state offline 

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#842]
Hi Guys,

I am working on an android app with smack. The problem is that chat states are stored offline. So if a user is offline and when he come online along with message he also get is typing notification. I can handle on my end by checking urn:xmpp:delay element but wanted to know if there is a better way.

Thanks,
Harshit

**Comment by bangarharshit** [comment]
Generalizing it. Is there a way to discard some messages from offline storage? Example - webrtc call  signaling. It surely should be real time.

**Comment by bangarharshit** [comment]
I verified it is added in spool table

Here is the packet
```xml
<message to='7ea4bed4-7edc-4f4e-ae65-69ddb49f08d6@ejabberd.sandwitch.in/smack' id='Z9PWb-72' type='chat'><thread>8796cf99-ad35-411f-8283-0ece1c565040</thread><composing xmlns='http://jabber.org/protocol/chatstates'/></message><r xmlns='urn:xmpp:sm:3'/>
```

XEP-160 says that chat state notifications should not be stored offline - http://xmpp.org/extensions/xep-0160.html

**Comment by zinid** [comment]
Probaby mod_offline's `store_empty_body: true|false` option is something you can use.

**Comment by bangarharshit** [comment]
Thanks. I will try but I believe I have other messages with no body like muc invites which I want in offline storage.  If it doesn't work I believe client side filtering will be the solution.

**Comment by zinid** [comment]
Regarding XEP-160, I don't think we claim its support.

**Comment by badlop** [comment]
In fact some months ago I added to mod_offline.erl a claim that it supports XEP-0160. But now that I check, ejabberd stores message stanzas of type chat that only contain xep-160 content, contrary to what the XEP recommends. So there's a bug, either in the code or in the claim I added.

On the other hand, I wonder if the example can be considered to contain only XEP-160 content: it contains a 'thread' element.

**Comment by badlop** [comment]
You should check the option mentioned by Zinid, it works better than what the XEP says, for example:

This is stored offline: 
```
<message type='chat' to='user1@localhost/tka1'>
  <composing xmlns='http://jabber.org/protocol/chatstates'/>
  <body>some body</body>
</message>
```
Those are not stored offline:
```
<message type='chat' to='user1@localhost/tka1'>
  <composing xmlns='http://jabber.org/protocol/chatstates'/>
</message>

<message type='chat' to='user1@localhost/tka1'>
  <composing xmlns='http://jabber.org/protocol/chatstates'/>
  <thread>123456</thread>
</message>

<message type='groupchat' to='user1@localhost/tka1'>
  <body>some body</body>
  <composing xmlns='http://jabber.org/protocol/chatstates'/>
</message>

<message to='room1@conference.localhost'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <invite to='user1@localhost'>
      <reason>Por favor, entra en room1@conference.localhost</reason>
    </invite>
  </x>
</message>
```

**Comment by bangarharshit** [comment]
Thanks @badlop and @zinid . I agree that the approach is much neater than xep-060. I tried setting body in muc invite but it throws 400 bad modify exception. I think there can be other stanzas which doesn't have body.

Client side filtering looks neater to me and I have submitted a patch for smack. I can close the issue if you guys don't want to keep it open for reference.

**Comment by weiss** [comment]
> On the other hand, I wonder if the example can be considered to contain only XEP-160 content: it contains a 'thread' element.

I think the answer is "yes", as XEP-0085 [defines][1] a "standalone notification" as a stanza that "contains only a child element qualified by the 'http://jabber.org/protocol/chatstates' namespace (or possibly also the XMPP `<thread/>` element [&hellip;])."

[1]: http://xmpp.org/extensions/xep-0085.html#definitions

**Comment by bangarharshit** [comment]
Thanks guys.  Copying xnyphs comment from smack pr:

There is no easy way to distinguish offline messages from messages that have gotten delayed for a different reason, the presence of <delay/> is not enough. For example, a XEP-0198 resume somewhere along the line often also leads to messages being stamped with <delay/> too. There might even be some clients out there that add a <delay/> to every outgoing message.
XEP-0160 is only "Informational", there might be good reasons to store chat states, for example to determine whether you message has been seen by your contact.

Do you guys think it is possible to add a boolean flag to drop offline chat states in mod_offline with default to true? I have also modified smack since in some case especially the clients which wants read receipts they can use active and inactive state. It will  be upto client then.

**Comment by weiss** [comment]
> Do you guys think it is possible to add a boolean flag to drop offline chat states in mod_offline with default to true?

In ejabberd 15.12, `mod_offline`'s `store_empty_body` option [will default to][1] `unless_chat_state`, which implements [the XEP-0160 behavior][2].  Setting it to `true` tells ejabberd to also store chat states.

[1]: https://github.com/processone/ejabberd/commit/3397a9be5e89e4142ab5385f3f946539d9877d89
[2]: http://xmpp.org/extensions/xep-0160.html#types

**Comment by themoonlitknight** [comment]
Hi, is it normal that I receive an error for each chat state I send? I'm using version 16.03. This is the error:

<message xmlns="jabber:client" from="userA@mydomain" to="userB@mydomain/EFDD1485-10C7-48C3-A38C-A9451C3F38AA" type="error"><composing xmlns="http://jabber.org/protocol/chatstates"/><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></message>

Thanks,
Francesco

**Comment by weiss** [comment]
I guess you're sending the chat state to an offline user?

Did you specify `mod_offline`'s `store_empty_body` option?

**Comment by themoonlitknight** [comment]
Thanks for the reply.

Yes, I'm sending it to an offline user, it is the case I'm interested in.

I didn't set `store_empty_body` because, as you said above, it defaults to `unless_chat_state`.

My goal is not to store chat state to offline storage, but I don't want to receive an error for each chat state sent.

**Comment by weiss** [comment]
I tested this just to double-check, but I can't reproduce your problem.

I assume you do have `mod_offline` enabled and the recipient does exist?  If so, could you paste the exact stanza you're sending?

**Comment by themoonlitknight** [comment]
These are the stanzas, both returning the error

`<message type="chat" to="iphone2@x.dev.vms.me"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>`

`<message type="chat" to="iphone2@x.dev.vms.me"><active xmlns="http://jabber.org/protocol/chatstates"/></message>`

**Comment by weiss** [comment]
Ah, thanks.  I failed to reproduce the error due to a bug I [fixed][1] now.  That is, ejabberd would now consistently return error stanzas for standalone chat states sent to offline users, as you described.

I'm not 100% certain we want to change this behavior (and thereby violate a `SHOULD` clause [in the RFC][2]).

[1]: https://github.com/processone/ejabberd/commit/beeb1c82d92dabd37462db051fe9eb024ae12c41
[2]: https://tools.ietf.org/html/rfc6121#section-8.5.2.2

**Comment by themoonlitknight** [comment]
Ah ok, thank you for the clear explanation. I will handle the error then.
