### ISSUE TITLE
If MySQL has AUTOCOMMIT enabled pubsub and archive seems to stop working

### ISSUE THREAD

**Issue by nunohorta** [processone/ejabberd#844]
I've just installed Ejabberd 15.10 and I'm getting errors with pubsub. Logs:

this is the logs adding a bookmark:
https://gist.github.com/nunohorta/2f1d879c9ba7a99cdb97

this is the error:
https://gist.github.com/nunohorta/87f5dd9cdb7d5991c368

On the database pubsub_item is empty but not pubsub_node. I'm not sure what's happening since I have another server running 15.10 with the exact same configuration and bookmarks are added and deleted with no errors. Also mod_mam is not working, not sure if it's related.

**Comment by nunohorta** [comment]
I have some news on this issue which actually solves temporarily all the issues that I was having with the database. If MySQL has AUTOCOMMIT enabled pubsub and archive for mam stops working. Disabling autocommit seems to solve both. Should I raise a new issue? Do you guys need any more logs or information?

I can't have autocommit disabled forever but for now it seems to fix things

**Comment by cromain** [comment]
yes please, post here anything you think it can be relevant, like simple way to reproduce.

**Comment by nunohorta** [comment]
It's quite simple actually. Requesting archive for rooms or adding bookmarks causes transactions errors. The logs on the first post it all that I can see for now. Not sure if it's relevant but here's my system and mysql version:

mysql 5.6.23
CentOS Linux release 7.1.1503 (Core)

**Comment by cromain** [comment]
By default, MySQL runs with autocommit mode enabled, and ejabberd always worked with default MySQL setup. there should be something else.
your error states mysql does not respond, so there should be something else with your setup. autocommit is not the problem.

**Comment by nunohorta** [comment]
I'll try to find out more logs that could help resolve this issue

**Comment by cromain** [comment]
I suggest to close this issue as AUTOCOMMIT is not a problem.
