### ISSUE TITLE
unable to install zabbix

### ISSUE THREAD

**Issue by nirrr** [processone/ejabberd#846]
Hi,
Im trying to install Zabbix on my redhat-5.4 machine but im getting this error. but same thing worked in the redhat-6.4 machine.

[root@bld opt]# rpm -ivh zabbix-2.0.0-1.el5.x86_64.rpm
warning: zabbix-2.0.0-1.el5.x86_64.rpm: Header V4 DSA signature: NOKEY, key ID 79ea5ed4
Preparing...                ########################################### [100%]
   1:zabbix                 ########################################### [100%]
error: unpacking of archive failed on file /usr/share/doc/zabbix-2.0.0/ChangeLog;56545b45: cpio: MD5 sum mismatch

i also tried all the latest  version 2.2 to 2.4.7
please help...

**Comment by badlop** [comment]
From what I see, Zabbix is a program completely unrelated to ejabberd. Maybe you sent this question to the wrong page?

**Comment by nirrr** [comment]
sorry its my mistake.
