### ISSUE TITLE
Retrieving archiving preferences for MAM is not allowed

### ISSUE THREAD

**Issue by neurolit** [processone/ejabberd#848]
Hi!

I'm using Ejabberd 15.11 and trying, with my client, to retrieve MAM archiving preferences. I'm using this stanza:

```xml
<iq xmlns="jabber:client" type="get"><prefs xmlns="urn:xmpp:mam:tmp"/></iq>
```

but Ejabberd answers with an error:

```xml
<iq xmlns="jabber:client" from="neurolit" to="neurolit/Jappix (1448397425064)" id="257" type="error">
   <prefs xmlns="urn:xmpp:mam:tmp"/>
   <error code="405" type="cancel">
      <not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
   </error>
</iq>
```

I tried with "urn:xmpp:mam:0" namespace too, same answer.

Is there a way to allow archiving preferences retrieving?

**Comment by mremond** [comment]
Thanks for the report. We found an issue related to multiple XEP version support. Thanks for reporting the issue. It will be fixed in next release.

**Comment by neurolit** [comment]
Thank you @mremond !
