### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#850]
Dears,

Kindly note that i configured ejabberd to access mysql database and i added mod_offline_odbc to let the offline messages to store in table spool,, but if i put mod_offline the offline messages arent stored in table spool. also in ejabberd.log i found the below warning:

@ejabberd_config:emit_deprecation_warning:1177 Module mod_offline_odbc is deprecated, use mod_offline with 'db_type: odbc' instead

please find the below configuration section for mysql:

##auth_method: internal
auth_method: odbc
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "*****"
odbc_password: "******"

**Comment by badlop** [comment]
Where in the ejabberd documentation did you find any reference to mod_offline_odbc? Since some months ago, mod_offline supports the option db_type, see the ejabberd Guide:
http://docs.ejabberd.im/admin/guide/configuration/#modoffline

So, depending on the value you put in the db_type option, the internal Mnesia database or the external ODBC database will be used.

You can see the size of Mnesia tables in WebAdmin -> Nodes -> your node -> Database, so you can see if the offline messages are stored in the table offline_msg at the Mnesia database, or in the table spool at your external ODBC database.

**Comment by hassanzreik** [comment]
so mod_offline should be as below:
  mod_offline_odbc:
    access_max_user_messages: max_user_offline_messages
    db_type: odbc

so it will store in database, is this right?

aslo please @badlop can you describe for me the below image 
![untitled](https://cloud.githubusercontent.com/assets/4625505/11425698/63e620a6-945f-11e5-8eca-15901d9e1ea4.png)


thanks for helping

**Comment by hassanzreik** [comment]
RAM copy
RAM and disc copy
disc only copy

which one is better?

**Comment by badlop** [comment]
With this config:
```
mod_offline:
  access_max_user_messages: max_user_offline_messages
  db_type: odbc
```
it should store new offline messages only in your ODBC database, not in MySQL.

In that page, offline_msg is storing 4 messages. It should not store new messages, because new messages should be stored in your ODBC database.

**Comment by hassanzreik** [comment]
@badlop i didnt get it, i configured mysql database so using ODBC it will store in MySQL, am i right?

**Comment by zinid** [comment]
@hassanzreik right

**Comment by hassanzreik** [comment]
@zinid how can i solve this error
[error] <0.1997.0>@ejabberd_odbc:log:663 p1_mysql_conn: Connection closed, exiting.

**Comment by mremond** [comment]
MySQL is generally autoclosing connection when there is no traffic after a while. This is not harmful as ejabberd will automatically reconnect. However, if you want to generate a keep alive the connection to avoid closing the socket from MySQL side, you can using the option `odbc_keepalive_interval`.

This is described in ejabberd documentation: http://docs.ejabberd.im/admin/guide/configuration/#relational-databases
