### ISSUE TITLE
upgrade from ejabberd 15.10.32 to latest version

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#851]
how can i upgrade without losing data and configuration

**Comment by badlop** [comment]
It depends on how you install them. If you use the binary installers built by ProcessOne, then I can think of this simple way:
1. Stop ejabberd
2. Install new ejabberd in a new directory
3. Copy the configuration files and Mnesia spool files from old to new path
4. Start the new ejabberd
