### ISSUE TITLE
TLS session resumption start

### ISSUE THREAD

**Issue by bangarharshit** [processone/ejabberd#852]
Hi Guys,
I am using ejabberd (xmpp) with slow client internet connection. Due to ssl it is sending 900 bytes packet everytime it's reconnecting (irrespective of resume). I wanted to know if TLS session resumption is implemented in ejabberd. - http://xmpp.org/extensions/xep-0198.html#resumption (though it is not part of  xep but it looks to me a great optimization.)

**Comment by bangarharshit** [comment]
Hey Guys,
Any idea if ejabberd supports session tickets or session id? I tried sending session id using smack (by caching the sslcontext) but it is not working. Handshakes are still there.

**Comment by bangarharshit** [comment]
Actually verified using this command - python sslyze.py --tlsv1 --sslv2 --sslv3 --tlsv1_1 --tlsv1_2 --hide_rejected_ciphers --certinfo=basic --reneg --resum --starttls=xmpp ejabberd.sandwitch.in . Looks to me that both session tickets and id are not supported.  I also verified with talk.google.com and it seems both these mechanisms are supported.

Session id need to be supported across clusters while I am not sure how many clients can implement tickets (I am quite sure that is not possible in java and so in any java client) so it may not be trivial.

I will try to go through code to see if I can contribute :)

**Comment by nOmi7** [comment]
I completely agree with @bangarharshit  this will really be a great optimization to resumptions .

**Comment by cromain** [comment]
closing this old thread. resumption is part of stream management which is implemented.

**Comment by cromain** [comment]
I was misreading, TLS session resumption is not implemented.

**Comment by mremond** [comment]
I am not sure this is still revelant:

1. We now implement TLS 1.3, that reduce the number of round-trip to establish a session.
2. We support Stream management

The TLS negotiation time is probably a small fraction of the time to establish a session and reattach.

I propose to close this for now.
