### ISSUE TITLE
Mod Mam archive issue between multiple resources

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#853]
I have two login with different resource for my xmpp account , now i came across a situation wherein if i am login i received all the messages sent/received to both resources , Now  when one of my resource(desktop) goes offline and if any messages sent to me will be delivered  to resource(mobile) which is online . this goes perfect till this point.

Now when i logged in back to my another resource(desktop) and try to retrieve archive chat  history it is resulting into messages those were sent by me and not getting messages sent to me .Messages sent are there but received Messages are not there .
Messages those were received by my resource(mobile) which was online , did not return to resource(desktop) .

I have ejabberd 15.09 and mod_mam 0.3 version for archive .
Is ejabberd has implementation like if you have acknowledged the message sent to you it won't be available for further retrieval from archive ?
 
could anyone please suggest me where i am wrong.

**Comment by mremond** [comment]
Issue is discussed on Stackoverflow and pending user info: http://stackoverflow.com/questions/33950828/mod-mam-archive-issue-between-multiple-resources-issue-opened-in-github
