### ISSUE TITLE
How to update ejabberd  2.1.11 to the lastest version on Ubuntu 14.04?

### ISSUE THREAD

**Issue by jasomdotnet** [processone/ejabberd#855]
Hi there,
I run ejabberd on Ubuntu 14.04 VPS. When I use following command 

>admin@vps:/etc/ejabberd# sudo ejabberdctl status
>The node ejabberd@vps is started with status: started
>ejabberd 2.1.11 is running in that node

I guess, the ejabberd version installed on the server is displayed. How can I update ejabberd  to the latest version? Commands:
>sudo apt-get update 
>sudo apt-get upgrade
>sudo apt-get update ejabberd
>sudo apt-get upgrade ejabberd

return no result.

Can you point me to some good tutorial or write down some command hints?

**Comment by mremond** [comment]
The best way to stick to latest version is probably to back up your Mnesia directory, config file and database. You can then install ejabberd for example from ProcessOne packages / installers from ProcessOne site. Then you can replace your configuration file, points Mnesia dir to a copy you made for db and make sure you use the right database back-end.

Basically, the idea is as follow: copy your data so that new install environment will use it.

**Comment by jasomdotnet** [comment]
1) Thanks for an answer
2) What and where is "Mnesia directory"
3) Where/How I can find database?

Config file is on the path /etc/ejabberd/ejabberd.cfg I think

**Comment by mathiasertl** [comment]
@jasomdotnet 

ad (2) and (3): Mnesia is the database ejabberd uses, it's located in `/var/lib/ejabberd`.
ad (4) Yes, you're right.

The standard Ubuntu repositories only have the ejabberd version you already have in them (assuming you installed from there). If you want a newer version, you need a different source. You can either use official packages (see ejabberd homepage) or the packages (see [here](https://jabber.at/en/apt-repository)) we use at jabber.at.

**Comment by Langlife2** [comment]
@mathiasertl I can't find any file named mnesia in /var/lib/ejabberd, does it has a different name?

Thanks in advance

**Comment by mathiasertl** [comment]
@Langlife2 not really sure why you're answering on a two year old long-closed ticket.

But in any case: The whole directory is the mnesia db, similar to /var/lib/mysql for MySQL databases.
