### ISSUE TITLE
Disable inband registration, but not via e.g. xmlrpc

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#857]
We currently only allow registration via a homepage (https://accounts.jabber.at) that uses `mod_xmlrpc` and we do not allow In Band Registration. Our issue is that 

* Without `mod_register` the commands are no longer available via the xmlrpc interface
* With `mod_register` (and an ACL to forbid any registration) ejabberd always advertises IBR as a stream feature, which confuses some clients.

Is there any configuration that allows us to use registration via XMLRPC but *not* have ejabberd advertise IBR as a stream feature? If not, could a e.g. `no_ibr` option be added to `mod_register`?

**Comment by badlop** [comment]
Try this patch. If you set mod_register's option access_from to 'none', then IBR isn't announced. Of course you still have to set your access rules to actually prevent registration.

```
--- a/src/mod_register.erl
+++ b/src/mod_register.erl
@@ -72,8 +72,11 @@ stop(Host) ->
     gen_iq_handler:remove_iq_handler(ejabberd_sm, Host,
                                     ?NS_REGISTER).

-stream_feature_register(Acc, _Host) ->
-    case lists:keymember(<<"mechanisms">>, 2, Acc) of
+stream_feature_register(Acc, Host) ->
+    AF = gen_mod:get_module_opt(Host, ?MODULE, access_from,
+                                          fun(A) when is_atom(A) -> A end,
+                                         all),
+    case (AF /= none) and lists:keymember(<<"mechanisms">>, 2, Acc) of
        true ->
            [#xmlel{name = <<"register">>,
                    attrs = [{<<"xmlns">>, ?NS_FEATURE_IQREGISTER}],
```

**Comment by mathiasertl** [comment]
I can confirm that this patch works, we have it deployed at jabber.at. Can this patch be included in mainline?
