### ISSUE TITLE
Virtual Host with odbc

### ISSUE THREAD

**Issue by volga629** [processone/ejabberd#858]
Hello Everyone,
I have 3 virtual hosts defined  and all information stored in mysql. When I am creating user in web interface or cli it appear under each VirtualHost. Same with shared roster group. I guess I should be able create users per virtualhost (domain) include shared roster groups another domain should isolated.
Any advise thank you.

ejabberd version ejabberd-15.11-0.x86_64

**Comment by volga629** [comment]
Based on what I see in mysql database is no any indication to which virtual host ( domain ) user belong.

```
| username       | varchar(250) | NO   | PRI | NULL              |       |

```

**Comment by badlop** [comment]
You are right, and what you noticed is expected. It is explained in the ejabberd Guide:

```
Important note about virtual hosting: if you define several domains in ejabberd.yml
(see section Host Names), you probably want that each virtual host uses a different
configuration of database, authentication and storage, so that usernames do not
conflict and mix between different virtual hosts. For that purpose, the options described
in the next sections must be set inside a host_config for each vhost (see section
Virtual Hosting).
```
http://docs.ejabberd.im/admin/guide/configuration/#database-and-ldap-configuration

**Comment by volga629** [comment]
As far I understand I  will need  define for each vhost separate database ?  So if I have 100 vhost it should be 100 databases ? Is there are specific reason why users are not associated with virtual host numeric id in database. 
1. Create in database vhost with numeric id.
2. User should be associated with vhost numeric id.

**Comment by badlop** [comment]
> As far I understand I will need define for each vhost separate database ? So if I have 100 vhost it should be 100 databases ?

Right.

> Is there are specific reason why users are not associated with virtual host numeric id in database. 

Yes, the reason is that this ejabberd database schema and code is designed to support better many users in few hosts. Your design would work better for few users in many hosts.

**Comment by volga629** [comment]
Thank for you comments.  Last my question different topic, just don't want open another issue. 
Is possible configure in mod_mam polices for messages retention. 

For how long save messages in days
After how many days purge archived messages from database.

**Comment by badlop** [comment]
Looking at the mod_mam documentation, the retention policy is forever. There isn't configuration option or a defined way to delete old ones. I guess, if you store in an ODBC database, you can write your own method to remove old messages.
http://docs.ejabberd.im/admin/guide/configuration/#modmam

**Comment by volga629** [comment]
I see, will be nice to have this module as part of ejabberd.
Mod_http_upload have it.

mod_http_upload_quota:
    max_days: 100

New module for mam

mod_mam_quota:
    max_days_message_disposal: 45 

I will need find some one who can do it, because I am not developer a specially for erl.

**Comment by volga629** [comment]
missed db_type: odbc

mod_mam_quota:
missed db_type: odbc
max_days_message_disposal: 45
