### ISSUE TITLE
trusted_proxies option not parsed correctly

### ISSUE THREAD

**Issue by richardardrichard** [processone/ejabberd#860]
When the trusted_proxies option is set to `all`, the ejabberd_http module does seem to be correctly looking up the setting. Adding the following debug here https://github.com/processone/ejabberd/blob/master/src/ejabberd_http.erl#L482,

```
TrustedProxies = ejabberd_config:get_local_option(
                       {trusted_proxies, Host},
                       fun(TPs) ->
                               [iolist_to_binary(TP) || TP <- TPs]
                       end, []),
    ?INFO_MSG("TrustedProxies::", []),
    ?INFO_MSG(TrustedProxies, []),
    ?INFO_MSG("___", []),
```

logs:
```
22:28:43.821 [info] TrustedProxies
22:28:43.821 [info]
22:28:43.821 [info] ___
```

example truncated config:

```
  -
    port: 5280
    module: ejabberd_http
    trusted_proxies: all
```

**Comment by badlop** [comment]
Looking at the code, I think this option is expected to be used outside the listen section. I've updated the documentation, but I guess it doesn't appear in the website yet. I've also fixed support for 'all'.
Example:
```
trusted_proxies: ["127.0.0.1", "192.168.1.11"]

listen:
    ...
```
