### ISSUE TITLE
Archive retreieval issue 

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#862]
I have  recently updated to 15.11 latest release of ejabberd , there is a problem with mod_mam(0.3),
whenever i am querying  archive table the response i am getting contains only messages which i have sent. 
Messages sent to me from my friends are not there in response and all the messages (Sent/received) ) are stored  in archive table properly .
previously i introduce this issue as archive  retrieve problem between multiple resources but now it is there even with a one client and one resource .
The query which i am sending to retrieve is :
```
 <iq type='set' id='juliet1'>
  <query xmlns='urn:xmpp:mam:1'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:mam:1</value>
      </field>
      <field var='start'>
        <value>2010-08-07T00:00:00Z</value>
      </field>
    </x>
  </query>
</iq>
```

**Comment by badlop** [comment]
I've tested your report, and the query works correctly for me: I get messages I sent, and also messages sent to me.

Did this work correctly in previous releases? Which one do you remember that worked correctly?

**Comment by Nitin3589** [comment]
After failed to find out reason i just reconfigured my server and it start working normal with my old configuration .still don't know what was the cause which resulted that awkward behavior.

I would close this issue  for now .Thanks
