### ISSUE TITLE
mod_mam.erl doesn't support CHATSTATES

### ISSUE THREAD

**Issue by sudo2012** [processone/ejabberd#863]
mod_mam.erl doesn't support CHATSTATES  There is no easy way to implement this. My db is currently running out of memory because every chatstate is logged!
Maybe smbd could tell me how to solve this issue. 
Thanks

**Comment by shaljam** [comment]
I think you want to stop logging chatstates. By default mod_mam will not archive messages without body, so you might be adding body to your chatstates, so  they are being logged.

**Comment by sudo2012** [comment]
Thank you for your comment. I already saw that chatstates are not logged if body is empty. Yet this is no good solution to the chatstates issue. What if user A writes an offline message to user B; user A drops offline, user B drops online, so the message was received and displayed. Yet the current chatstate is not logged to the database and therefore user A won't be able to see displayed icons on the message. This is still a big issue and needs to be fixed. Please let me know what function inside the erlang code needs to be modified and how. 
In my opinion this function has to be changed to cover an adaequate logging to chatstates like markable, received, delivered and acknowledged:

user_send_packet(Pkt, C2SState, JID, Peer) ->
    LUser = JID#jid.luser,
    LServer = JID#jid.lserver,
    case should_archive(Pkt) of
	true ->
	    NewPkt = strip_my_archived_tag(Pkt, LServer),
	    store_msg(C2SState, jlib:replace_from_to(JID, Peer, NewPkt),
		      LUser, LServer, Peer, send),
	    NewPkt;
	false ->
	    Pkt
    end.

**Comment by shaljam** [comment]
There is another extension for message delivery http://www.xmpp.org/extensions/xep-0184.html and chatstates is not meant for that.
This functionality is per message, and saved in database.

**Comment by sudo2012** [comment]
Thank you for your answer. Still XEP-0184 doesn't solve the db issue. What I want to acchieve is a Whatsapp like behaviour. Therefore XEP-0333 seems to be the best choice. 
Would you please point me out how to modify the mod_mam.erl to get it started. I think it would be senseful to implement those changes in the ejabberd trunk anyways to support meaningful dilivery statuses! I can try to fix it on my own, yet I will need some hours to get it going as I am no professional erlang developer. 
Here is my proposal: alter the archive table (in my case in mysql) and add a message-id field to hold the unique message id. 
Then the mod_archive management should react to a stanza like so: 
<message
    from='kingrichard@royalty.england.lit/throne'
    id='message-2'
    to='northumberland@shakespeare.lit/westminster'>
  <thread>sleeping</thread>
  <received xmlns='urn:xmpp:chat-markers:0' 
               id='message-1'/>
</message>

There has to be a if clause, checking for a <received/> tag and extract the message id. And then update the stanza in the db accordingly doing an update command on the archive table where the message-id and jid are fitting. The same should happen for a <displayed/> and <acknowledged/> tag inside the stanza. That way only one message will be saved to the db for each user. 
Please help me to fix this issue inside the user_send_packet function. My proposed implementation could support XEP-0333 as well as XEP-0184, would reduce the load on the server-side db dramatically and would enable offline message delivery receipts to ejabberd. 
I googled a lot about this issue; there is no solution to this issue currently, yet many developers are facing it. So I guess my proposal would be a big step solving this issue. 
Thanks

**Comment by sudo2012** [comment]
Sorry, github killed my stanza structure. You can see the correct structure here under Example 4:
http://xmpp.org/extensions/xep-0333.html
      
< message
    from='kingrichard@royalty.england.lit/throne'
    id='message-2'
    to='northumberland@shakespeare.lit/westminster'>
  < body>This is my message< /body>
  < received xmlns='urn:xmpp:chat-markers:0' 
               id='message-1'/>
< /message>

**Comment by shaljam** [comment]
I didn't see XEP-0333, that was good, but it does not have anything to do with server. The server just archives the messages that include a marker. Moreover the XEP-0333 notes the following:
Note: Chat Markers do not mark each individual message, nor do they assume a reliable transport. This means that Chat Markers can only provide a heuristic solution, but this is often satisfactory for the majority of use cases.
which is telling it is not marking every message.
About your proposal, the message id is not unique and added by creating entity. So updating database based on that id is not possible. Also using chat markers the marking messages rate would be low and not affecting database. I think adding a delivery for every message isn't either a problem. The mod_mam implementation on ejabberd provides XEP-0359 which adds unique ids to archived messages.

**Comment by sudo2012** [comment]
Well, thanks for your answer. It seems like you don't fully get what I would like to acchieve. Let me try to rephrase it: User A is online, User B offline
User A sends a markable message to User B which is stored to the db
Next User A drops offline. 
In the meantime User B goes online. So he receives the message sent by user A. 
mod_mam.erl should now alter the message stored inside the db and change the markable tag to a received tag. Next if user B reads the message, the db should log the message accordingly with a delivered stamp. And if User B answers user A, the message sent by user A should get an acknowledged stamp. 
So when User B drops offline and user A goes online again, he can receive a message stanza with the < acknowledged/> tag. 
That way only two messages are saved inside the db. Right now there would be 8 messages saved to the db to acchieve the same results, which is not a good practice. 
So the store_msg function inside the mod_mam.erl should be altered like so:
If message sent by user A has a body, check if message has an < markable/> tag. If so, extract the unique message ID generated to XEP-0359 accordingly and store it in a field to db. 
Next User B goes online and receives, displayes and acknowledges the message sent by user A. So user B sends a message stanza to the server with a < received/>, < delivered/> or < acknowledged/> tag but an empty body. mod_mam.erl should check if a message has an empty body and recognize the < received/>, < delivered/> or < acknowledged/> tags. It extracts the unique message id and alters the stanza of the message sent by user A accordingly. 
Do you see what I would like to acchieve?
Thanks

**Comment by sudo2012** [comment]
Please just help me change the erlang file. That's madbe 20 lines of code so really not that much. As I mentioned I could try it on my own, but it would be a lot of work for me as I never worked with the erlang structure. I would have to test and recompile the module a lot. So maybe you could give me a hand and tell me how to save the unique message id to the db and how to extract the message received delivered and acknowledged stanzas. How to write the changes to the db. But as I said, I think the whole module should support chatstates like I proposed. Thanks in advance.

**Comment by sudo2012** [comment]
I guess Mr. @weiss solved my issue, so this can be marked as closed. It was important to activate mod_offline to get correct results. Thanks for the help.

**Comment by weiss** [comment]
FTR, my main concern with the suggestion was the idea of having the client that sent the original message extract the XEP-0333 status from his own outgoing message as returned by `mod_mam`.  That's non-standard, and it's inefficient to have clients query the same set of MAM messages repeatedly just to get their current XEP-0333 status.

**Comment by weiss** [comment]
> By default mod_mam will not archive messages without body, so you might be adding body to your chatstates, so they are being logged.

You can [now][1] also add a `<store/>` [hint][2] to tell `mod_mam` to store messages without body.

[1]: https://github.com/processone/ejabberd/commit/5ce0b062ffb804bb81ec4e68bd0f9656a5ce3f3e
[2]: http://xmpp.org/extensions/xep-0334.html
