### ISSUE TITLE
Ejabberd crashes with bad argument in call to ets:lookup(access, {c2s_shaper,global})

### ISSUE THREAD

**Issue by adarshphilip** [processone/ejabberd#868]
I am using Ejabberd 15.09 and it was working all fine when suddenly it started crashing on login to web admin console with this error:
 Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.1870.0> exit with reason bad argument in call to ets:lookup(access, {c2s_shaper,global}) in acl:match_rule/3 line 262 in context child_terminated

The tail crash log is as follows:
```
=SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_c2s_sup}
     Context:    child_terminated
     Reason:     {badarg,[{ets,lookup,[access,{c2s_shaper,global}],[]},
{acl,match_rule,3,[{file,"src/acl.erl"},{line,262}]},
{ejabberd_c2s,change_shaper,2,[{file,"src/ejabberd_c2s.erl"},{line,1886}]},
{ejabberd_c2s,wait_for_stream,2,[{file,"src/ejabberd_c2s.erl"},{line,386}]},
{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
     Offender:   [{pid,<0.6909.0>},{name,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

I checked and the override_global options are only available for ejabberd 13 and before.

Any suggestions?

**Comment by badlop** [comment]
That error probably indicates that the Mnesia table "access" does not exist. It is created at ejabberd start if it doesn't exist, and never deleted.

See in the logs if there is any previous error message with other clue. Does the problem happen after every server start, or it only happened once?

BTW, webadmin and c2s are unrelated.

**Comment by adarshphilip** [comment]
The problem started all of a sudden but it did not kill the server. While checking logs, it kept creating a new PID and terminated the old one. 
The issue has been fixed though. I deleted the whole mnesia spool and ran the server again. Working again. Can you explain though why it happened suddenly? Because if I am planning to deploy this then I would like to avoid a scenario like this.

**Comment by badlop** [comment]
I don't have information to know why it complained about 'access' table not existing.

The next time you have a problem, you should try the least aggressive solutions first:
* Restart the server, the table should be recreated automatically
* If problem persists, then delete the table (using WebAdmin -> Nodes -> your node -> database), and then restart the server
* If problem persists, then dump the mnesia database to text file, do what you did, and then load the mnesia text file.
* If problem persists, delete again the mnesia dump, start and check it works. If so, edit the text file to load only the barely essential to your server (roster, offline, ...).
