### ISSUE TITLE
Remove mandatory session open post-bind to conform to RFC 6121

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#869]
RFC 6121 removed the post bind session open IQ.

However, ejabberd requires it to actually open the session.

As proposed in this draft, it should be optional:
http://tools.ietf.org/html/draft-cridland-xmpp-session-01

**Comment by mremond** [comment]
RFC 6121 removed the post bind session open IQ.

However, ejabberd requires it to actually open the session.

As proposed in this draft, it should be optional:
http://tools.ietf.org/html/draft-cridland-xmpp-session-01

**Comment by zinid** [comment]
This is fixed like a year ago.
