### ISSUE TITLE
How to specify trusted CAs for s2s certificate verification?

### ISSUE THREAD

**Issue by rfc2822** [processone/ejabberd#871]
How do you specify a list of CAs which are accepted by ejabberd? [FreeBSD's OpenSSL doesn't trust anybody by default](https://forums.freebsd.org/threads/openssl-etc-ssl-cert-pem-not-honoured-by-default.54176/), and if I understood that correctly, that behavior is by design and to choose a trusted CA list is an application-level thing. However, I couldn't find an option for that in ejabberd (in opposite to some other servers)… any advice?

**Comment by zinid** [comment]
Configuring CA pool for openssl doesn't help? Because ejabberd relies on openssl configuration.

**Comment by rfc2822** [comment]
> Configuring CA pool for openssl doesn't help? Because ejabberd relies on openssl configuration.

As far as I have understood, applications should provide a setting for the trusted CA storage because this OpenSSL setting is on application level.
