### ISSUE TITLE
Account registrations not working over BOSH

### ISSUE THREAD

**Issue by frh** [processone/ejabberd#872]
When I try to register a new user with mod_register over BOSH, the connection simply times out with no reply from the ejabberd server. The log does not indicate that it received the registration stanza, despite Pidgin's debug log showing that it sent it. Registrations over regular XMPP (not BOSH) work just fine, and BOSH connections for already registered users work (although BOSH connections don't get any replies to pings, and as such they time out after a few minutes).

Running ejabberd 15.10-3~bpo8+1 on Debian 8.

[ejabberd.yml](https://github.com/processone/ejabberd/files/60529/ejabberd.yml.txt)
[ejabberd.log](https://github.com/processone/ejabberd/files/60528/ejabberd.log.txt)
[pidgin.log](https://github.com/processone/ejabberd/files/60530/pidgin.log.txt)

**Comment by badlop** [comment]
Problem confirmed with ejabberd 15.11, Erlang R17.2 and Pidgin 2.10.11. However, in-band account registration over BOSH works correctly when using Tkabber and Gajim.
