### ISSUE TITLE
Typing errors

### ISSUE THREAD

**Issue by GreenLunar** [processone/ejabberd#876]
1. Persist items to __storage__
 * Did you mean to "store"?

2. __Disc__ only copy
 * Did you mean to "disk"?

3. Some Jabber clients can store your password in your computer. Use that feature only if you __trust your computer is safe__.
 * Do you like to refine the last part of this string?

**Comment by badlop** [comment]
1. Right, it means "to store". That weird sentence comes from the protocol definition, see http://xmpp.org/extensions/xep-0060.html#example-139 So, better keep it that way even if it is strange.

2. It is equivalent, but not exactly the same. Disk is used in american English, Disc is used in British English and in computer terms, see LaserDisc, MiniDisc, Compact Disc...

3. Yes, what about this alternative?
> Some Jabber clients can store your password in the computer, but you should do this only in your personal computer for safety reasons.

If you can think a more simple explanation, please tell me :)

**Comment by GreenLunar** [comment]
2. I suggest to add a short Developer Comment for translators.
 3. Sounds good.
