### ISSUE TITLE
Support a different user name for shared LDAP rosters

### ISSUE THREAD

**Issue by jceb** [processone/ejabberd#880]
In this configuration for ejabberd (https://github.com/it25gmbh/plucs/issues/13) we discovered that `ldap_useruid` and `ldap_memberattr` have to match.  It makes total sens to have a link between LDAP groups and LDAP users but this basically force the `ldap_membarattr` to also be the ejabberd user name.  This is undesirable in some situations, e.g. when the e-mail address should be exposed via ejabberd instead of the user name that I'd regard as rather internal.

I suggest adding another configuration option, e.g. `ldap_usermemberattr`, which will be set to the value of `ldap_useruid` by default.  It creates the link between group and user objects.  `ldap_useruid` could be set to a different attribute, e.g. `mailPrimaryAddress`, which stores the user name that should actually be exposed.  The behavior would be similar to `ldap_userdesc`.

**Comment by badlop** [comment]
Apparently this proposal didn't get more interest, so let's close it as "Won't Fix".
