### ISSUE TITLE
Rpm packaging  + -home not set correctly.

### ISSUE THREAD

**Issue by volga629** [processone/ejabberd#882]
Hello Everyone,
After from 15.07 to 15.11 -home set incorrectly.

```
[root@ns508284 logs]# systemctl status ejabberd.service
● ejabberd.service - A distributed, fault-tolerant Jabber/XMPP server
   Loaded: loaded (/usr/lib/systemd/system/ejabberd.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sun 2015-12-20 10:53:40 CST; 1s ago
  Process: 7860 ExecStop=/opt/ejabberd-15.11/bin/ejabberdctl stop (code=exited, status=0/SUCCESS)
  Process: 7928 ExecStart=/bin/sh /opt/ejabberd-15.11/bin/ejabberdctl start (code=exited, status=0/SUCCESS)
 Main PID: 7928 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ejabberd.service
           ├─7962 /opt/ejabberd-15.11/bin/epmd -daemon
           ├─7964 /opt/ejabberd-15.11/bin/beam.smp -K true -P 250000 -- -root /opt/ejabberd-15.11 -progname /opt/ejabberd-15.11/bin/erl -- -home /opt/ejabberd-15.07 -- -n...
           ├─7987 inet_gethost 4
           └─7988 inet_gethost 4
```

**Comment by cromain** [comment]
to avoid running ejabberd as root, if installed as root, we handle creation of ejabberd user in postinstall.
when installer is run as root, or when installing rpm/deb, we create ejabberd account if it does not exists.
then we change ejabberd's home to installation directory (/opt/ejabberd-XX.YY) using usermod command.

i can not reproduce this issue running installers as root (having all installed in /opt/ejabberd-XX.YY)
ejabberd's home is modified as expected by postinstall.

**Comment by volga629** [comment]
Hello Everyone,
Finally I got time upgrade and show what the issue.
We run Fedora 22 Server x86_64

**Also main problem that none of the configuration include production certificates are not moved or not preserved by rpm. That cause by incorrect tree of delivered software in this case ejabberd should match proper tree in  order package manager can track the differences and act accordingly.**

Here are upgrade 

````
[root@canlmsg01 ~]# cp -rp /opt/ejabberd-15.11/ /opt/ejabberd-15.11.bak-16-Apr-2016
[root@canlmsg01 ~]# dnf install https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.03/ejabberd-16.03-0.x86_64.rpm
Last metadata expiration check performed 0:47:21 ago on Fri Apr 15 23:25:34 2016.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                      Arch                                       Version                                       Repository                                        Size
==============================================================================================================================================================================================
Upgrading:
 ejabberd                                     x86_64                                     16.03-0                                       @commandline                                      17 M

Transaction Summary
==============================================================================================================================================================================================
Upgrade  1 Package

Total size: 17 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Upgrading   : ejabberd-16.03-0.x86_64                                                                                                                                                   1/2 
  Cleanup     : ejabberd-15.11-0.x86_64                                                                                                                                                   2/2 
  Verifying   : ejabberd-16.03-0.x86_64                                                                                                                                                   1/2 
  Verifying   : ejabberd-15.11-0.x86_64                                                                                                                                                   2/2 

Upgraded:
  ejabberd.x86_64 16.03-0                                                                                                                                                                     

Complete!

After upgrade old directory is still in place 

[root@canlmsg01 ~]# cd /opt/ejabberd-1
ejabberd-15.11/                 ejabberd-15.11.bak-16-Apr-2016/ ejabberd-16.03/    

Then check status and it fail, because service file are still point to old install.

[root@canlmsg01 conf]# lsof -i :5222
[root@canlmsg01 conf]# systemctl restart ejabberd.service 
Job for ejabberd.service failed. See "systemctl status ejabberd.service" and "journalctl -xe" for details.
[root@canlmsg01 conf]# systemctl status ejabberd.service 
● ejabberd.service - XMPP Server
   Loaded: loaded (/usr/lib/systemd/system/ejabberd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2016-04-16 00:16:59 CDT; 10s ago
  Process: 11290 ExecStop=/opt/ejabberd-15.11/bin/ejabberdctl stop (code=exited, status=203/EXEC)
  Process: 11294 ExecStart=/bin/sh /opt/ejabberd-15.11/bin/ejabberdctl start (code=exited, status=127)
 Main PID: 11294 (code=exited, status=127)

After manually updating service file and ran systemctl daemon-reload. Ejabberd started, but home directory still point to old installation.

[root@canlmsg01 conf]# systemctl status ejabberd.service -l
● ejabberd.service - XMPP Server
   Loaded: loaded (/usr/lib/systemd/system/ejabberd.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sat 2016-04-16 00:18:09 CDT; 11min ago
  Process: 11322 ExecStart=/bin/sh /opt/ejabberd-16.03/bin/ejabberdctl start (code=exited, status=0/SUCCESS)
 Main PID: 11322 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ejabberd.service
           ├─11354 /opt/ejabberd-16.03/bin/beam.smp -K true -P 250000 -- -root /opt/ejabberd-16.03 -progname /opt/ejabberd-16.03/bin/erl -- -home /opt/ejabberd-15.11 -- -sname ejabberd@localhost -noshell -noinput -noshell -noinput -mnesia dir "/opt/ejabberd-16.03/database/ejabberd@localhost" -ejabberd log_rate_limit 100 log_rotate_size 10485760 log_rotate_count 1 log_rotate_date "" -s ejabberd -smp enable start 
           ├─11355 /opt/ejabberd-16.03/bin/epmd -daemon
           ├─11372 inet_gethost 4
           └─11373 inet_gethost 4

Apr 16 00:18:09 canlmsg01.networklab.prod systemd[1]: Starting XMPP Server...
Apr 16 00:18:09 canlmsg01.networklab.prod systemd[1]: Started XMPP Server.


.````

**Comment by volga629** [comment]
Also I was need move all configuration and data to new installed directory. Ejabberd is not starting any more give some yml error, which not make any sense, because this server was running in production at least 1 year. 


`
2016-04-16 01:17:23.772 [critical] <0.37.0>@gen_mod:start_module:122 Problem starting the module mod_proxy65 for host <<"mydomain.com">> 
 options: [{host,<<"proxy.@HOST@">>},
           {hostname,<<"proxy.@HOST@">>},
           {name,<<"File Transfer Proxy">>},
           {ip,<<"10.18.130.29">>},
           {port,7777},
           {max_connections,5},
           {access,proxy65_access},
           {shaper,proxy65_shaper}]
 error: function_clause
[{lists,map,
        [#Fun<ejabberd_http.29.4347689>,<<>>],
        [{file,"lists.erl"},{line,1236}]},
 {ejabberd_http,transform_listen_option,2,
                [{file,"src/ejabberd_http.erl"},{line,874}]},
 {ejabberd_listener,'-transform_option/1-fun-1-',3,
                    [{file,"src/ejabberd_listener.erl"},{line,638}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1261}]},
 {ejabberd_listener,transform_option,1,
                    [{file,"src/ejabberd_listener.erl"},{line,635}]},
 {lists,map,2,[{file,"lists.erl"},{line,1237}]},
 {lists,map,2,[{file,"lists.erl"},{line,1237}]},
 {ejabberd_listener,add_listener,3,
                    [{file,"src/ejabberd_listener.erl"},{line,456}]}]
2016-04-16 01:17:23.772 [critical] <0.37.0>@gen_mod:start_module:127 ejabberd initialization was aborted because a module start failed.
`

**Comment by volga629** [comment]
Here output for variable INSTALLUSER_HOME

```
[root@canlmsg01 bin]# getent passwd ejabberd | cut -d: -f6
/opt/ejabberd-15.11
[root@canlmsg01 bin]# 

```

After looking closer in ejabberdctl home definition is rely on this code which in question based on output above.

```
    for GID in `id -G`; do
        if [ $GID -eq 0 ] ; then
            INSTALLUSER_HOME=$(getent passwd "$INSTALLUSER" | cut -d: -f6)
            if [ -n "$INSTALLUSER_HOME" ] && [ ! -d "$INSTALLUSER_HOME" ] ; then
                mkdir -p "$INSTALLUSER_HOME"
                chown "$INSTALLUSER" "$INSTALLUSER_HOME"
            fi
            EXEC_CMD="su $INSTALLUSER -c"
        fi
    done
```

**Comment by volga629** [comment]
Here are another good example where ejabberdctl  run in debug mode for bash and it try use wrong directory.

```
+ cpu=x86_64
+ ARCHDIR=linux-x86_64
+ export ARCHDIR
+ LD_LIBRARY_PATH=/opt/ejabberd-16.03/lib/linux-x86_64
+ export LD_LIBRARY_PATH
+ DYLD_LIBRARY_PATH=/opt/ejabberd-16.03/lib/linux-x86_64
+ export DYLD_LIBRARY_PATH
+ exec /opt/ejabberd-16.03/bin/erlexec -name ctl-ejabberd@canlmsg01.networklab.prod -noinput -hidden -s ejabberd_ctl -extra ejabberd@canlmsg01.networklab.prod
{error_logger,{{2016,5,25},{10,0,54}},"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[]}
{error_logger,{{2016,5,25},{10,0,54}},crash_report,[[{initial_call,{auth,init,['Argument__1']}},{pid,<0.19.0>},{registered_name,[]},{error_info,{exit,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,330}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[<0.17.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,1032}],[]]}
{error_logger,{{2016,5,25},{10,0,54}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{offender,[{pid,undefined},{name,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2016,5,25},{10,0,54}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2016,5,25},{10,0,54}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,165}],[]]}
{error_logger,{{2016,5,25},{10,0,54}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{\"Failed to create cookie file '/opt/ejabberd-15.11/.erlang.cookie': enoent\",[{auth,init_cookie,0,[{file,\"auth.erl\"},{line,285}]},{auth,init,1,[{file,\"auth.erl\"},{line,139}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump was written to: /opt/ejabberd-16.03/logs/erl_crash_20160525-100054.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Failed to create cookie file '/opt
+ result=1
+ '[' '' ']'
+ case $result in
+ :
+ return 1
```

**Comment by cromain** [comment]
several points in this ticket

- systemd/initv scripts (ejabberd.service and ejabberd.init) are provided in ejabberd's bin directory but never installed by rpm or installer in the system. If you install them in the system and start ejabberd with this system integrated scripts, then it's up to you to stop ejabberd and remove that files before installing a new version of ejabberd. there is nothing we can do about this as our installer is generic (can even be run by user) and is not supposed to alter the system out of the installation directory. the rpm package is just an export bitrock produces from our standard/generic binary installer. it is not supposed to alter the system out of ejabberd installation directory, and every ejabberd version should be hosted in its own directory as you should be able to have several version installed (for live upgrade for example)

- files still in place after package removal is a packaging choice and the behaviour of our generic binary installer (so the rpm package act the same). uninstalling ejabberd triggers call of postinstall.sh script (which copy configuration directory with a timestamp) then only untouched files are removed. As a result, after uninstall filesystem still have copies of configuration backup, database and logs. This allows user to restart configured server after a clean re-install. We should consided adding an option to force removal of all files so rpm/deb uninstall could use that. Using /opt/ejabberd as main directory is not an option to store config and runtime files as it forces to stop ejabberd before installing any new version.

- ejabberd's home directory not updated. This occurs when you install ejabberd while a process of previous version is still running (ejabberd itself or epmd for example) so usermod fails.
with RPM, you must stop ejabberd before upgrading or installing it. and if stop takes more than 30s then epmd process is not killed. so this occurs when ejabberd is running or stop took more than 30s. I'll raise this timeout to 60s to push limits higher and give more chance to kill epmd on stop.

**Comment by cromain** [comment]
After that small change, upgrade with rpm looks good in any cases i could test with ejabberd being long to stop:
- install version A, home set to A
- ejabberdctl start
- ejabberdctl stop
- ejabberdctl stopped  (this is mandatory, don't forget 'stop' is asynchronous)
- check beam and epmd not running => ok
- install version B, home set to B

if you first uninstall version A, no need to manually stop before install a new one (see preuninstall.sh)

your issue just appreas when upgrading ejabberd with rpm, without uninstalling previous version first. in this case ejabberd may be running, and you may not want to stop it while installing a new one. in such a case, just manually run postinstall.sh as root when old version of ejabberd is stopped, and ejabberd's home should be set correctly.
at install, our rpm based on generic binary installer will not stop running ejabberd by itself if already running. but we can consided adding an option to force stop of running ejabberd at install so we can fully proceed with postinstall on new instance.

to summary, i think we can close this topic as rpm package actually act the same as our generic installer and is ok in most situation.
there are 2 possible new feature anyway to fix "upgrade"
- option to force clean of all files at uninstall
- option to force stop of running ejabberd (if any) at install for automated packaging upgrade

if you think this can improve rpm/deb usage, please create dedicated ticket.

**Comment by cromain** [comment]
small note: option to stop running ejabberd at install will fix postinstall when upgrading with rpm (and so, the setting of ejabberd's home directory), but will not help upgrading a running system. this is not a solution.
best option would be to set ejabberd's home to /opt/ejabberd, and only keep backups in this directory. but this solution have one problem: it put stuff out of installation directory.

**Comment by volga629** [comment]
The main point that rpm upgrade process should be tracked by package manager like yum of dnf. All required information should be putted into spec file during the build.  Configuration files structure will match only if top directory match like /opt/ejabberd. You don't need do you self and any backups of configuration yum or dnf will do *.rpmnew   *.rpmsave. Regard process, that controlled in spec file %pre sections.  Where you can stop service or kill. That will allow  upgrade match simpler.
