### ISSUE TITLE
Issue with allow_visitor_nickchange

### ISSUE THREAD

**Issue by mithunraman** [processone/ejabberd#885]
Hi Team,

I have a use case were i need to disable changing of nicknames when an user enters an MUC. I have tried setting the allow_visitor_nickchange value to false in the config file but it does not seem to be working.

When i get the registration form i can see the "Allow visitors to change nickname" value is set to false which means the change in the config file is being reflected. When some other user joins the group, he is able to change his nick. Is there any way that his nick can be his username itself ??

Thanks,
Mithun

**Comment by badlop** [comment]
That option affects only visitors. Notice that visitor is a lower grade than participant.

So, for that option to make sense in your room, you need to also disable an option that is usually enabled by default in ejabberd: "Default users as participants". When you disable this option, new occupants are visitors only, not participants. And then they can't change their nickname if you disable also the option that you mentioned.

In the config file, it's like this:
```
modules:
  mod_muc:
    default_room_options:
      allow_visitor_nickchange: false
      members_by_default: false
```
