### ISSUE TITLE
support mysql ssl connections

### ISSUE THREAD

**Issue by skippy** [processone/ejabberd#888]
encrypting the db connection is required for a number of regulatory and compliance purposes.  My specific use-case is HIPAA, HiTech, and eventually FedRamp on AWS, connecting to the Mysql RDS service.

I'm trying to use the ODBC connection, but it keeps crashing (e.g. connect string `odbc_server: "dsn=mysqldb;database=ejabberd;server={{ env['MYSQL_SERVER'] }};uid={{ env['MYSQL_USERNAME'] }};pwd={{ env['MYSQL_PASSWORD'] }};sslca=/opt/rds/rds-combined-ca-bundle.pem;sslverify=1"`)  

Using the mysql driver directly seems to be more stable.  However, it doesn't support any of the mysql ssl flags.  Is it possible to add them?

Thank you

**Comment by skippy** [comment]
I opened an issue at https://github.com/processone/mysql/issues/6

**Comment by mremond** [comment]
You are using ODBC driver, but we are not using it for MySQL. processone/mysql is a native driver that has nothing to do with ODBC and does not use ODBC string at all.

**Comment by skippy** [comment]
hey @mremond,
yep!  I understand both cases.  If the https://github.com/processone/mysql supported ssl I would drop odbc in a heart beat.  The ask here isn't about odbc stability, but about supporting ssl connections.  
thank you

**Comment by nOmi7** [comment]
is there any plan to support SSL ? that will be really great @mremond

**Comment by mremond** [comment]
@nOmi7 We have plans, but it is not yet scheduled for developments. If you want to work on it, you can go ahead, no problem.

**Comment by eldridge** [comment]
@skippy were you ever able to get ODBC working with MySQL via TLS?

**Comment by cromain** [comment]
let's track this on https://github.com/processone/mysql/issues/6 to avoid duplications.
there are no plans to implement this yet. if tls is mandatory you should use an ssh tunnel for now.

**Comment by eldridge** [comment]
Unfortunately, Amazon does not permit SSH access to managed MySQL database instances (e.g., RDS, Aurora).  It is unfortunate that using a MySQL database backend with ejabberd results in data transiting the network in the clear.
