### ISSUE TITLE
mod_http_offline yaml configuration

### ISSUE THREAD

**Issue by brokeniceinteractive** [processone/ejabberd#895]
I have installed this module:

ejabberdctl module_install mod_http_offline

anyone has a configuration yaml for this module?

mod_http_offline{}

thanks!

**Comment by badlop** [comment]
Looking at the module documentation, there are no options to configure, just set
>  mod_http_offline: {}

See https://github.com/raelmax/mod_http_offline

**Comment by brokeniceinteractive** [comment]
And how can i set the url api rest?

**Comment by badlop** [comment]
Looking at the source code, it seems you edit the file and put the URL there:
https://github.com/raelmax/mod_http_offline/blob/master/mod_http_offline.erl#L44
