### ISSUE TITLE
www.ejabberd.im HTTPS/TLS certificate uses deprecated SHA1 algorithm in signature

### ISSUE THREAD

**Issue by hannob** [processone/ejabberd#896]
Currently the certificate of https://www.ejabberd.im/ shows a certificate warning in Chromium. The certificate uses a SHA1 signature and is valid until 2017.

Browsers are gradually introducing warnings and plan to fully deprecate support for SHA1-signed certificates soon. You should replace your certificate.
![ejabberd-cert](https://cloud.githubusercontent.com/assets/990588/12140464/7c5b600a-b468-11e5-9e7b-27b59223541f.png)

**Comment by cromain** [comment]
was fixed long time ago
