### ISSUE TITLE
MUC ignore disconnects user

### ISSUE THREAD

**Issue by satanasov** [processone/ejabberd#897]
Hello all.

I have the following issue with ejabberd (tested versions 15.11 and 15.10 (and I was unable to compile 15.09 or older) release and master):

If user in MUC sets ignore to other user and this user sends a message to the room, the user that has added the ignore is disconnected.

The following message is displayed in admin client:

User1 left the room (This participant is kicked from the room because he sent an error message to another participant: service-unavailable)

There is nothing I can find in logs.

I will try older releases until I find this option working.

Regards.

**Comment by weiss** [comment]
> If user in MUC sets ignore to other user and this user sends a message to the room, the user that has added the ignore is disconnected.

What client are you using and how are you telling it to ignore a user?

**Comment by satanasov** [comment]
Strophe.js based muc client called Candy.

Users are added to ignore privacy list.

The row added in the database is:

Table - privacy_list_data

Id -> user_id
t-> j
value -> room_jid (room@conference.server.tld/user)
action -> d
ord -> 0
match_all -> 0
match_iq -> 0
match_message -> 1
match_presence_in -> 0
match_presence_out -> 0

Output of the client IQ:

```
SENT: <body rid='3411306003' xmlns='http://jabber.org/protocol/httpbind' sid='3a40d3d20053fe5d0a01e375490f5eaa82cb2836'><iq type='set' from='user1@server.tld' id='edit1' xmlns='jabber:client'><query xmlns='jabber:iq:privacy'><list name='ignore'><item type='jid' value='room@conference.server.tld/user2' action='deny' order='0'><message/></item></list></query></iq></body>
```

**Comment by weiss** [comment]
The problem is that the privacy rule [generates an error][1], and the MUC service kicks participants when receiving error messages from them.  I guess this is a corner case the authors of the privacy lists extension haven't thought of.

[1]: http://xmpp.org/extensions/xep-0016.html#protocol-error

**Comment by satanasov** [comment]
Thanks! Sorry for the additional work, but this is great.
