### ISSUE TITLE
mod_pubsub offline message

### ISSUE THREAD

**Issue by brokeniceinteractive** [processone/ejabberd#903]
Hi, i want to intercept the offline message of mod_pusbub, if i send a normal message in ejabberd to offline user, i see that message in offline odbc table, if user reconnect the message arrive.

If i publish to a node, and some user are offline, i see nothing in offline message table, but if the user reconnect the item node is sent correctly so the message is saved somewhere.

Can i send the item offline to offline message odbc table? or can i intercept the offline item of mod_pubsub like for message, in fact for message from plugin i can do this:

```javascript
start(_Host, _Opt) ->
        inets:start(),
        ejabberd_hooks:add(offline_message_hook, _Host, ?MODULE, create_message, 50).

stop (_Host) ->
        ejabberd_hooks:delete(offline_message_hook, _Host, ?MODULE, create_message, 50).


this is my yaml of mod_pubsub

  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    db_type: odbc
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps

**Comment by mremond** [comment]
Please, do not cross post to many sites. I already replied here: http://stackoverflow.com/questions/34774112/ejabberd-mod-pubsub-offline-message/34784781#34784781
