### ISSUE TITLE
problem with node and notification type = normal

### ISSUE THREAD

**Issue by brokeniceinteractive** [processone/ejabberd#904]
Hi, i'v configured a node from swift with this code:

`func xmppPubSub(sender: XMPPPubSub!, didCreateNode node: String!, withResult iq: XMPPIQ!){
xmppPubSub?.configureNode(node, withOptions: ["pubsub#notification_type": "normal"])
}`

But the server crash with this log: (if i set options with: [] every work fine but the messages are not stored by mod_offline) any help?

09:56:54.489 [info] Stream management with resumption enabled for 154@xxxx.xxxxx.xxxxx/7746577521236262136732885874641416397280407570401287166
09:59:23.502 [info] (#Port<0.16576>) Accepted connection 151.41.3.89:54028 -> 172.31.63.73:5285
09:59:23.502 [info] started: {gen_tcp,#Port<0.16576>}
09:59:44.631 [info] Created MUC room 251@conference.xxxx.xxxxx.xxxxx by 154@xxxx.xxxxx.xxxxx/7746577521236262136732885874641416397280407570401287166
09:59:44.860 [info] ({socket_state,p1_tls,{tlssock,#Port<0.16574>,#Port<0.16575>},<0.466.0>}) Close session for 154@xxxx.xxxxx.xxxxx/7746577521236262136732885874641416397280407570401287166
09:59:44.869 [info] 1 stanzas were not acknowledged by 154@xxxx.xxxxx.xxxxx/7746577521236262136732885874641416397280407570401287166
09:59:44.869 [error] gen_fsm <0.467.0> in state session_established terminated with reason: bad argument in call to xml:element_to_binary({xmlel,<<"iq">>,[{<<"from">>,<<"pubsub.node0.frind.it">>},{<<"to">>,<<"154@xxxx.xxxxx.xxxxx/77465775...">>},...],...}) in ejabberd_c2s:send_element/2 line 1856
09:59:44.870 [error] CRASH REPORT Process <0.467.0> with 0 neighbours exited with reason: bad argument in call to xml:element_to_binary({xmlel,<<"iq">>,[{<<"from">>,<<"pubsub.node0.frind.it">>},{<<"to">>,<<"154@xxxx.xxxxx.xxxxx/77465775...">>},...],...}) in ejabberd_c2s:send_element/2 line 1856
09:59:44.870 [info] Destroyed MUC room 251@conference.xxxx.xxxxx.xxxxx because it's temporary and empty
09:59:44.870 [info] Stopping MUC room 251@conference.xxxx.xxxxx.xxxxx

**Comment by brokeniceinteractive** [comment]
this is the string sent for configure:

<iq type="set" to="pubs.xxxx.xxxxx.xxxxx/" id="85A57469-0E24-4B7D-B710-CCDAAF575F8F">
   <pubsub xmlns="http://jabber.org/protocol/pubsub#owner">
      <configure node="263">
         <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE" type="hidden">
               <value>http://jabber.org/protocol/pubsub#node_config</value>
            </field>
            <field var="pubsub#notification_type">
               <value>normal</value>
            </field>
            <field var="pubsub#send_last_published_item">
               <value>never</value>
            </field>
         </x>
      </configure>
   </pubsub>
</iq>

**Comment by cromain** [comment]
I can not reproduce your issue. your swift library should be doing something wrong

SENT:
<iq type='set' to='pubsub.localhost'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <create node='263'/>
  </pubsub>
</iq>

RECV:
<iq from="pubsub.localhost" type="result" to="test1@localhost/mba">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<create node="263"/>
</pubsub>
</iq>

SENT:
<iq type="set" to="pubsub.localhost" id="85A57469-0E24-4B7D-B710-CCDAAF575F8F">
   <pubsub xmlns="http://jabber.org/protocol/pubsub#owner">
      <configure node="263">
         <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE" type="hidden">
               <value>http://jabber.org/protocol/pubsub#node_config</value>
            </field>
            <field var="pubsub#notification_type">
               <value>normal</value>
            </field>
            <field var="pubsub#send_last_published_item">
               <value>never</value>
            </field>
         </x>
      </configure>
   </pubsub>
</iq>

RECV:
<iq from="pubsub.localhost" type="result" to="test1@localhost/mba" id="85A57469-0E24-4B7D-B710-CCDAAF575F8F"/>

stored node configuration:
 [{send_last_published_item,never},
  {notification_type,normal},
 ...

I see nothing wrong there.
