### ISSUE TITLE
erl_crash.dump with startssl.com certificate

### ISSUE THREAD

**Issue by improvethings** [processone/ejabberd#910]
$ dpkg -l | grep ejabber
ii  ejabberd                                 2.1.11-1ubuntu2.1                   amd64        distributed, fault-tolerant Jabber/XMPP server written in Erlang

$ uname -srm
Linux 3.19.0-43-generic x86_64

$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

$ sudo ls -lart /etc/ejabberd/ejabberd.pem
-r-------- 1 ejabberd ejabberd 3010 Jan 11 23:45 /etc/ejabberd/ejabberd.pem

$ sudo openssl verify /etc/ejabberd/ejabberd.pem
/etc/ejabberd/ejabberd.pem: C = IL, O = StartCom Ltd., OU = Secure Digital Certificate Signing, CN = StartCom Certification Authority
error 18 at 0 depth lookup:self signed certificate
OK

$ date
Thu Jan 14 17:36:40 PST 2016

$ sudo service ejabberd start
Starting jabber server: ejabberd.

$ sudo ls -lart /var/log/ejabberd/
total 316
drwxrwxr-x 12 root     syslog   4096 Jan 14 06:28 ..
-rw-r-----  1 ejabberd adm     41192 Jan 14 17:05 erlang.log
-rw-r-----  1 ejabberd adm      5112 Jan 14 17:05 ejabberd.log
drwxr-s---  2 ejabberd adm      4096 Jan 14 17:12 .
-rw-r-----  1 ejabberd adm    259718 Jan 14 17:27 erl_crash.dump

$ sudo head -5 /var/log/ejabberd/erl_crash.dump
=erl_crash_dump:0.3
Thu Jan 14 17:27:38 2016
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
System version: Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [kernel-poll:false]
Compiled: Tue Aug 19 16:45:11 2014

**Comment by zinid** [comment]
ejabberd 2.1.11? Really?
