### ISSUE TITLE
where does ejabberd store user avatar images,mnesia or file?

### ISSUE THREAD

**Issue by zyfmix** [processone/ejabberd#912]
I have lookup ejabberd src but don't found which script does ejabberd deal with user pubsub avatar data and where does ejabberd store user avatar images? 
But it works all right with android conversations.my iq set packet like below:
``` xml 
    <packet or="send" ljid="zyf@coopens.com/mobile" ts="20160116T16:56:28">
        <iq xml:lang='en' from='zyf@coopens.com/mobile' id='af456mnjo7' type='set'>
            <pubsub xmlns='http://jabber.org/protocol/pubsub'>
                <publish node='urn:xmpp:avatar:data'>
                    <item id='cdb3708a643112ab5c51577d9677a0fb398c956d'>
                        <data xmlns='urn:xmpp:avatar:data'>
                            UklGRgQ...
                        </data>
                    </item>
                </publish>
            </pubsub>
        </iq>
    </packet>
```
and who can help me to figure out how to update user's avatar image with my php script?

**Comment by weiss** [comment]
> I have lookup ejabberd src but don't found which script does ejabberd deal with user pubsub avatar data and where does ejabberd store user avatar images?

[`mod_pubsub`][1] stores avatars and any other PEP/PubSub data in an [Mnesia][2] table, unless you've set `db_type: odbc` to use an SQL backend.

> and who can help me to figure out how to update user's avatar image with my php script?

[XEP-0084][3] describes how to do this for PEP avatars.

[1]: https://github.com/processone/ejabberd/blob/master/src/mod_pubsub.erl
[2]: http://www.erlang.org/doc/apps/mnesia/
[3]: http://www.xmpp.org/extensions/xep-0084.html
