### ISSUE TITLE
Privacy list not working 

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#918]
user login with id - loginuser
blocks contact - contactc1 with following IQ 

```
<iq from='loginuser@example.net/orchard' type='set' id='all1'>
<query xmlns='jabber:iq:privacy'>
  <list name='all-jid-example'>
    <item type='jid'
          value='contactc1@example.net'
          action='deny'
          order='23'/>
  </list>
</query>
</iq>
```
I set the default list to  all-jid-example
I see new rows created in mysql table for privacy list data however i still get the communications from Contactc1

I was checking code and i noticed one thing 
in ejabberdc2s.erl - 
 ```
PrivList =		ejabberd_hooks:run_fold(
			  privacy_get_user_list, NewState#state.server,
			  #userlist{},
			  [U, NewState#state.server]),
```
the user is the login user in short it get the right privacy list 

however in ejabbedSm
it uses to user is it correct ? should it not be from user the user who is sending the communication should be checked for outgoings ?

```
is_privacy_allow(From, To, Packet) ->
    User = To#jid.user,
    Server = To#jid.server,
    PrivacyList =
	ejabberd_hooks:run_fold(privacy_get_user_list, Server,
				#userlist{}, [User, Server]),
    is_privacy_allow(From, To, Packet, PrivacyList).
```
if no then why i am getting stanzas from the contact even when i have blocked it.

Thanks
Jeet

**Comment by badlop** [comment]
That function you mentioned in ejabberd_sm is not called when sending messages or normal presences, so even if there were a bug there, it isn't the source of your problem.

Try using the privacy list feature with some well known Jabber client, like Psi, Gajim or Tkabber. Then, if the feature works correctly for them, use their XML consoles (that let you see what stanzas they are sending) to compare their stanzas with what you send.
