### ISSUE TITLE
Wrong path to epmd in /sbin/ejabberdctl

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#921]
Wrong path to epmd in /sbin/ejabberdctl.

After build I have `EPMD=/bin/epmd`. But epmd installed to /usr/bin/epmd.

So, when I'm trying to `restart service ejabberd` I got error:

     Stopping ejabberd...
     //sbin/ejabberdctl: line 434: //bin/epmd: No such file or directory

Version 16.01

**Comment by Suvitruf** [comment]
Mb better to do:

     EPMD=/usr/bin/epmd:/bin/epmd

**Comment by badlop** [comment]
Right, in that case use this:
> ./configure --bindir=/usr/bin

**Comment by petmue** [comment]
> Right, in that case use this:
    ./configure --bindir=/usr/bin

Unfortunately this is not mentioned in the docs: http://docs.ejabberd.im/admin/guide/installation/
It only says
> -–prefix=/: Specify the path prefix where the files will be copied when running the make install command.
So, in my opinion the documentation should be updated adequately.
