### ISSUE TITLE
Ejabberd iexlive throws 'bad "K" value: \ ' error.

### ISSUE THREAD

**Issue by kinghadi** [processone/ejabberd#922]
Hi 
I installed `ejabberd` correctly( I configure it with `--enabled-all`) without any error. But when I want to run it in elixir mode I get this error:

    # ejabberdctl iexlive
    bad "K" value: \
    Usage: beam.smp [flags] [ -- [init_args] ]
    The flags are:
    
    -a size        suggested stack size in kilo words for threads
                   in the async-thread pool, valid range is [16-8192]
    -A number      set number of threads in async thread pool,
                   valid range is [0-1024]
    -B[c|d|i]      c to have Ctrl-c interrupt the Erlang shell,
                   d (or no extra option) to disable the break
                   handler, i to ignore break signals
    -c bool        enable or disable time correction
    -C mode        set time warp mode; valid modes are:
                   no_time_warp|single_time_warp|multi_time_warp
    -d             don't write a crash dump for internally detected errors
                   (halt(String) will still produce a crash dump)
    -fn[u|a|l]     Control how filenames are interpreted
    -hms size      set minimum heap size in words (default 233)
    -hmbs size     set minimum binary virtual heap size in words (default 32768)
    -hpds size     initial process dictionary size (default 10)
    -K boolean     enable or disable kernel poll
    -n[s|a|d]      Control behavior of signals to ports
                   Note that this flag is deprecated!
    -M<X> <Y>      memory allocator switches,
                   see the erts_alloc(3) documentation for more info.
    -pc <set>      Control what characters are considered printable (default latin1)
    -P number      set maximum number of processes on this node,
                   valid range is [1024-134217727]
    -Q number      set maximum number of ports on this node,
                   valid range is [1024-134217727]
    -R number      set compatibility release number,
                   valid range [16-18]
    -r             force ets memory block to be moved on realloc
    -rg amount     set reader groups limit
    -sbt type      set scheduler bind type, valid types are:
    -stbt type     u|ns|ts|ps|s|nnts|nnps|tnnps|db
    -sbwt val      set scheduler busy wait threshold, valid values are:
                   none|very_short|short|medium|long|very_long.
    -scl bool      enable/disable compaction of scheduler load,
                   see the erl(1) documentation for more info.
    -sct cput      set cpu topology,
                   see the erl(1) documentation for more info.
    -secio bool    enable/disable eager check I/O scheduling,
                   see the erl(1) documentation for more info.
    -sub bool      enable/disable scheduler utilization balancing,
                   see the erl(1) documentation for more info.
    -sws val       set scheduler wakeup strategy, valid values are:
                   default|legacy.
    -swct val      set scheduler wake cleanup threshold, valid values are:
                   very_lazy|lazy|medium|eager|very_eager.
    -swt val       set scheduler wakeup threshold, valid values are:
                   very_low|low|medium|high|very_high.
    -sss size      suggested stack size in kilo words for scheduler threads,
                   valid range is [4-8192]
    -spp Bool      set port parallelism scheduling hint
    -S n1:n2       set number of schedulers (n1), and number of
                   schedulers online (n2), maximum for both
                   numbers is 1024
    -SP p1:p2      specify schedulers (p1) and schedulers online (p2)
                   as percentages of logical processors configured and logical
                   processors available, respectively
    -t size        set the maximum number of atoms the emulator can handle
                   valid range is [8192-0]
    -T number      set modified timing level, valid range is [0-9]
    -V             print Erlang version
    -v             turn on chatty mode (GCs will be reported etc)
    -W<i|w|e>      set error logger warnings mapping,
                   see error_logger documentation for details
    -zdbbl size    set the distribution buffer busy limit in kilobytes
                   valid range is [1-2097151]
    -zdntgc time   set delayed node table gc in seconds
                   valid values are infinity or intergers in the range [0-100000000]
    
    Note that if the emulator is started with erlexec (typically
    from the erl script), these flags should be specified with +.

I can run the ejabberd server correctly. I created user and everything went well. I don't know the what is going wrong.

**My config** `Elixir 1.1.1` and `Erlang R18`.

I didn't pass any argument to it. What I did is as follows:

 - Download source file and untar it.
 
 - `./autogen` then `./configure --enable-all` then `make && make install`
 - Everything went well. I can run start it successfully and stop it successfully. Also I can run it in live mode(`ejabberdctl live`). 

The problem is when I run in with this `ejabberdctl iexlive`. Before I download the `ejabberd` I've installed `Elixir 1.1.1`. I don't know maybe this is the problem.

I went through the code of `ejabberdctl` and  I found the problem in this line of code:

    ERLANG_OPTS=" +K $POLL -smp $SMP +P $ERL_PROCESSES $ERL_OPTIONS"

I change it to 

    ERLANG_OPTS=""

And it worked. But I don't know it will make any further problem or not. I will open an issue at their repository. Can anyone help me.

**Comment by doorbash** [comment]
I have the same problem with the same configuration as @kinghadi

**Comment by prefiks** [comment]
Taking, i think this i broke something when fixing #804

**Comment by prefiks** [comment]
Fixed in 842d52352a52e504e9be858302443252b7cf07d4

**Comment by xlarsx** [comment]
Thank you!
