### ISSUE TITLE
Ejabberdctl missing, while ejabberd is installed.

### ISSUE THREAD

**Issue by scuba323** [processone/ejabberd#923]
[Paste  of terminal](https://scuba323.com/url/Kr5K7)

Also the docs seem to be missing. I believe I installed it from source, but it's been so long. I rebooted my server yesterday and now I can't get ejabberd to start.

    service ejabberd start

returns nothing. Just a blank output. Any help? I am going to post this to the forums as well. I am not sure this is the right place to post this.

**Comment by badlop** [comment]
It depends on what version you have installed. 13.xx and recent versions do not include the Guide.

Regarding ejabberdctl, it depends how you compiled where it was copied, typically it's 
> /sbin/ejabberdctl 

The Debian package may copy it to a more convenient way consdiering the Debian dir structure. Looking at https://packages.debian.org/jessie/amd64/ejabberd/filelist it seems to go to
> /usr/sbin/ejabberdctl

**Comment by scuba323** [comment]
Well, I decided to try
    apt-get remove ejabberd
then downloaded the .deb and installed the latest version, and that worked. Documents and ejabberdctl are back! :+1: thanks!
