### ISSUE TITLE
What is the rationale behind wrapping ejabberd_hooks and lager with Elixir modules?

### ISSUE THREAD

**Issue by lpil** [processone/ejabberd#924]
Hello!

Great to see Elixir as a first class language for ejabberd development. :)

I was wondering what was the rational for wrapping these modules in Elixir modules, as seen in these files:

https://github.com/processone/ejabberd/blob/9c82f160e5565b0cbd3b942979004bc4b50559b2/lib/ejabberd/hooks.ex
https://github.com/processone/ejabberd/blob/9c82f160e5565b0cbd3b942979004bc4b50559b2/lib/ejabberd/logger.ex

They don't add any extra functionality or Elixir inline documentation, so they seem to do nothing than to slightly remove clarity as to where these modules & functions are. It's normal to call Erlang style modules when writing Elixir.

I could make a pull request removing these and updating the Elixir example to use the regular ejabberd Erlang modules, would that be welcome?

Cheers,
Louis

**Comment by mremond** [comment]
No special rationale. We are reworking the Elixir part and this will disappear.

**Comment by lpil** [comment]
Great, thank you for the reply. Looking forward to seeing how this develops :)

**Comment by mremond** [comment]
@gabrielgatu For your information
