### ISSUE TITLE
Does Ejabberd support calling MySQL stored procedure?

### ISSUE THREAD

**Issue by pkarn** [processone/ejabberd#927]
I need to call MySQL store procedure from one of my module, but it keeps failing with error:
"#0A000PROCEDURE procedure_name can't return a result set in the given context".

To repro this, here is test store procedure:
```sql
DELIMITER $$
CREATE PROCEDURE helloWorld ()
BEGIN
SELECT NOW();
END $$
```
and then calling it as:
```erlang
ejabberd_odbc:sql_query(Server, [<<"CALL helloWorld();">>])
```

I am using MySQL 5.6.27 and Ejabberd 16.01.

**Comment by badlop** [comment]
No responses in so many time, it seems it isn't possible.
