### ISSUE TITLE
RPM spec file / SRPM

### ISSUE THREAD

**Issue by champtar** [processone/ejabberd#929]
Hi,

I'm looking for the rpm spec file of https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/16.01/ejabberd-16.01-0.x86_64.rpm for exemple

Thanks
Etienne

**Comment by mremond** [comment]
We do not have RPMS specifications. We generate our installers with a proprietary packaging tool taht generate those package for use from the binary installer.
