### ISSUE TITLE
Add/Remove vhosts dynamically

### ISSUE THREAD

**Issue by smansur** [processone/ejabberd#932]
Hi ,
I followed the ejabberd (version 14.12) compiling from source by replacing the following files
ejabberd_app.erl, ejabberd_auth.erl, ejabberd_config.erl, ejabberd_local.erl, ejabberd_service.erl, mod_shared_roster.erl

from https://github.com/Iperity/ejabberd/commit/6ba3f3ea6c9e4bc47e7475a7145ddf0ffbbddf7e.

I'm able install ejabberd successfully but now, please suggest me that how can i add/remove vhost dynamically to ejabberd by using this patch.

your immediate help on this would be appreciated.

**Comment by badlop** [comment]
That's a good question you can do to the author of the patch, do you agree?
