### ISSUE TITLE
Provide an update mechanism for OpenSSL on Windows

### ISSUE THREAD

**Issue by nappy** [processone/ejabberd#934]
The Windows Release of ejabberd is built in a way where OpenSSL is compiled into the p1_tls_drv.dll.
For ejabberd 16.01 it is using OpenSSL 1.0.2a 19 Mar 2015, which is kind of outdated.
If this is not kept up to date, I think its pretty much not usable in production.

Currently my only option is to rebuild the P1 Erlang TLS driver for Windows. Is there any source code or documentation on how to do that?

With older ejabberd releases, I was able to build just OpenSSL alone and replace ssleay32.dll / libeay32.dll, which was more comfortable. Can the build process maybe adjusted to support that option?

In my opinion however, if OpenSSL is statically linked, it should be updated on every release anyway, that would also the easiest solution for me.

**Comment by cromain** [comment]
openssl was statically included in p1_tls for convenience when we switched to new packaging. i'll check which option is best to make sure every release includes the latest openssl.

**Comment by cromain** [comment]
16.02 tls driver for windows will be build against openssl-1.0.2f.
then for next version, we'll more likely get back to the tls driver dynamically loading libssl.dll fo simpler openssl upgrade.

**Comment by nappy** [comment]
@cromain What the modus operandi on this now?
Im not reading "Installers include latest OpenSSL patches." in the changelogs since 16.02, given the next major version is released by now, have you switched to dymaic linking?

Tbh. you should implement one of those options asap, either put out releases each time there is a vulnerability in OpenSSL fixed, or switch to dynamic linking.
