### ISSUE TITLE
Webadmin - footer problem

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#935]
There is a problem with webadmin footer in many locations, e.g.:

/admin/server/domain.tld/
/admin/server/domain.tld/node/ejabberd@node/
/admin/server/domain.tld/webpresence/

![2016-01-31_092616](https://cloud.githubusercontent.com/assets/5073817/12701086/9afbfda0-c7fd-11e5-898f-dd80a171a6dd.png)

**Comment by badlop** [comment]
Aparently, the footer positions itself to the bottom of the content part, but not to the bottom of the left menu part. I can reproduce with Firefox 43

It's some CSS thing. Marek, ping me if you need example HTMLs, or testing.

**Comment by petmue** [comment]
Hi! I played around with the CSS and I think I found a decent solution, if you like it please feel free to cherry pick: [ejabberdhtml.zip](https://github.com/processone/ejabberd/files/119687/ejabberdhtml.zip)

Kind Regards
