### ISSUE TITLE
MUC Presence Contain a Status Code of 170

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#936]
Initially I filed a bug at the Gajim's bugtracker, but they pointed out that this issue is actually an ejabberd bug. Original ticket is here: https://trac.gajim.org/ticket/8254

The issue is as following. ejabberd's mod_muc module sends the presence with a status code 170 each time participant changes status. However, this should be done only in the initial presence when you enter the room.

Due to this behavior, once someone has his status changed, you get the "Room logging is enabled" message and this is really distracting, since in the large conferences this message floods the room.

For your reference here is an XML console Gajim logs: http://pastebin.com/bsDzSbxf

Screenshot of a room in Gajim:

![room logging flood](https://cloud.githubusercontent.com/assets/3958145/12713773/a8d97846-c8e1-11e5-9f1e-ba42dcd22403.png)

**Comment by prefiks** [comment]
Should be fixed by commit dc52ec904c439f2fbd399939fb9442281986a361

**Comment by IUnderstandLetsChangeMyUsername** [comment]
Wow, what a response speed. Thanks.
