### ISSUE TITLE
Client get disconnected on server restart.

### ISSUE THREAD

**Issue by Nishant-Pathak** [processone/ejabberd#938]
Hi,

When we are doing server restart after adding/modifying any configure in conf. Clients (java - smack) are not able to reconnect even after the retry logic. Did we missed something ?

**Comment by mremond** [comment]
It is normal for client to get disconnected on server restart. They have to reconnect.
 You need to investigate your client connection / reconnection code, connection loss detection and check ejabberd log to make sure restart was correctly perform.
