### ISSUE TITLE
make install may create problematic directory names

### ISSUE THREAD

**Issue by mgpld** [processone/ejabberd#940]
The make install process can create directory with a wrong name (see the '{vsn' thing) : 

shell> ls lib
cache_tab-1.0.2  goldrush-0.1.2  lager-2.0.0  oauth2-0.6.0    p1_stringprep-0.1.0  p1_tls-0.2.0  p1_utils-1.0.3  p1_yaml-0.1.0  xmlrpc-eb40f68
ejabberd-16.01.77  esip-0.1.0  jiffy-0.8.5     luerl-1      p1_iconv-0.1.0  p1_stun-0.1.0        p1_utils-1    p1_xml-0.1.0    p1_zlib-0.1.0 ** {vsn,**

To fix that, the related .app.src or .app file needs to have 
{vsn,"1.0"} without any space between {vsn, and "1.0".

The string manipulation code inside the Makefile don't handle that case.

**Comment by badlop** [comment]
Thanks for reporting!

In fact, better than modifying app files, I improved the string manipulation code to handle that case.

**Comment by mgpld** [comment]
You're right ! 
Thank you
