### ISSUE TITLE
Loading old messages when user signs in

### ISSUE THREAD

**Issue by mohit3081989** [processone/ejabberd#941]
Hi,

I am using mysql for messages on ejabberd, when I do message transfer using ejabberd, I am able to retrieve messages. But I had to migrate few of the messages and manually add them to mysql due to prod migration, I am not able to fetch such messages. Can anyone help here ? What is the beahvior of ejabberd in such use cases ?

**Comment by mremond** [comment]
Closing as it is a usage question and is a duplicate of: http://stackoverflow.com/questions/35176068/ejabberd-syncing-message-from-mysql-archive
