### ISSUE TITLE
[Question] Users Client Policy...

### ISSUE THREAD

**Issue by karlmendes** [processone/ejabberd#942]
Hi everyone, i'm new on ejabberd and i have a confused question...

I finish the  configure ejabberd on mysql with success. I can add and display all or partial users for any client only insert on table. 

But i realy need block users can add/edit/delete their accounts list.. It's possible.. ??

Thanks in advanced

Best regards

**Comment by mremond** [comment]
"accounts list" => Do you mean XMPP roster ?

**Comment by karlmendes** [comment]
For example, the user logs into the PSI, to log in pulling the contact list (roster) of database, but in the PSI if it aperar right and delete, he can remove from the database ...

What I thought was to remove permission DELETE of the ejabberd user in the database (MySQL) ...

More I wonder if this functionality is no longer available, any module or configuration.

In short, I want as an administrator to force the user to have that contact list as I set for him.

**Comment by mremond** [comment]
You should look into `mod_shared_roster` to see if it fits your need. Otherwise, you need to create a custom plugin to manage the roster the way you want, as what you describe is not standard XMPP.
