### ISSUE TITLE
How to connect nosql(Cassandra) from ejabbert

### ISSUE THREAD

**Issue by AmitShrivastav** [processone/ejabberd#948]

**Comment by zinid** [comment]
Cassandra is not supported.

**Comment by AmitShrivastav** [comment]
We are planning to store chat message in Nosql(Cassandra/Hbase) that why eager to know any solution. Can you please provide me alternate approach/custom solution ?

**Comment by mremond** [comment]
ejabberd backend modules are based on ejabberd Hook API. You can always develop your own module to persist and read the data as you wish.

**Comment by AmitShrivastav** [comment]
please provide me document to deploy custom module and module be any language

**Comment by mremond** [comment]
ejabberd is developed in Erlang. Extensions will have to be developed in Erlang or Elixir.

**Comment by jnanendraveer** [comment]
Can you provide doc for connect with any nsql document?. I have conncet with mysql but want to connect with nosql

Thank you

**Comment by kamal141** [comment]
@mremond : Do you have any specific sets of instruction how to connect Ejabberd 16.x with any sql(say mysql) or any nosql (say raik or mongodb or cassandra) for storing messages (mod_mam). 

A step by step document will be a great help.

Thanks in Advance.

**Comment by Neustradamus** [comment]
@AmitShrivastav @jnanendraveer @kamal141 Have you found a solution for MongoDB?
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang

Linked to:
- https://github.com/processone/ejabberd/issues/419
- https://github.com/processone/ejabberd/issues/305
