### ISSUE TITLE
protocol options and ciphers setting has no effect

### ISSUE THREAD

**Issue by funkenstrahlen** [processone/ejabberd#954]
I try to secure my ejabberd by configuring openssl ciphers like this for s2s communication:

```
    {s2s_use_starttls, required}.
    {s2s_certfile, "/etc/ejabberd/mycert.pem"}.
    {s2s_protocol_options, ["no_sslv3", "no_sslv2"]}.
    {s2s_ciphers, "HIGH" }.
```

However the [test shows the server still serves RC4 and sslv3](https://xmpp.net/result.php?id=158487). Why do these settings not show any effect?

I use `ejabberd 2.1.11-1ubuntu2.1 amd64`.

**Comment by beherit** [comment]
In ejabberd 2.1.x it's not possible to turn off SSLv2/SSLv3 via config file. You have two solutions: update ejabberd or use tlsinterposer (https://github.com/Netfuture/tlsinterposer/).

**Comment by funkenstrahlen** [comment]
@beherit I also can not set s2s_ciphers with this version of ejabberd?

**Comment by beherit** [comment]
Unfortunately this is not possible too.

**Comment by funkenstrahlen** [comment]
Ok thank you! Now I know what's my problem.
