### ISSUE TITLE
ejabberd 14 breaks ejabberd_ munin plugin

### ISSUE THREAD

**Issue by PF4Public** [processone/ejabberd#958]
Since ejabberd 14 installation `ejabberd_` munin plugin stopped working.
I'll cross-link two issues
[munin bugreport](https://github.com/munin-monitoring/munin/issues/488)

Any help in resolving is greatly appreciated.

**Comment by mremond** [comment]
@kolargol Do you think this issue still valid ?

**Comment by PF4Public** [comment]
This is still broken with ejabberd 16.03-1

**Comment by mremond** [comment]
Well, I think the change will have to be made on munin plugin, as I do not think the issue is in ejabberd. From the ticket you link it seems unrelated to ejabberd.

**Comment by PF4Public** [comment]
I believe it has something to do with both munin and ejabberdctl:

> Still I believe that root cause is not setting gid by munin. At least it could be the first obstacle.
 Should I fool  ejabberdctl  by replacing  -g  with  -u  in  id  checks it no longer complains and seems to pass given arguments forward to  erl , however this still fails with a bunch of access denied
...
Therefore I think that gid check ( -g ) in  ejabberdctl  was made on purpose.

**Comment by rraptorr** [comment]
Why don't you simply configure munin to change group to ejabberd?

**Comment by PF4Public** [comment]
@rraptorr Because it does not change a thing.
Just tried to configure munin with root user and root group and it worked. But not with ejabberd user/group. Using cli with ejabberd user however still works fine.

**Comment by rraptorr** [comment]
In your other bug report you indicate that you put 'user ejabberd' in munin plugin config. There is no mention if you also put 'group ejabberd' in that config. Have you? If you put 'group ejabberd' and it still does not set it, then it is clearly a bug in munin.

**Comment by PF4Public** [comment]
Consider the code

> echo $(whoami)
echo
echo $(id -G)
echo
echo $(id -g)
echo
echo $(id -g ejabberd)
echo
echo $(id -g munin)

If I put 

> user root
group root

I get proper statistics and

> root
139 0
139
123
139

Otherwise if I put 

> user ejabberd
group ejabberd 

I got no statistics and 

> ejabberd
139 123
139
123
139

So, what is the difference here and why it works with root and does not with ejabberd?

**Comment by rraptorr** [comment]
I have no idea, ask munin guys as it really seems like some problem with munin and its handling of user/group. Especially since ejabberdctl with sudo works.

**Comment by PF4Public** [comment]
OK, I've got it.
Here is the missing part of this puzzle:
Setting 
>user root
 group root

Effectively adds GID=0 to GID list, which via
`if [ $GID -eq 0 ] ; then`
mandates 
`EXEC_CMD="su $INSTALLUSER -c"`
making it all work fine. Crucial thing here is that both user and group defined. Group bypasses check for effective GID to be equal to ejabberd, while user root allows for succesfull `su`

Using ejabberd is different in that munin does not change effective GID, instead it just adds it to GID list or so it seems, thus GID check fails. However for this particular use having ejabberd GID in GID list is sufficient to get statistics out of ejabberd, so adding `EXEC_CMD="bash -c"` right after `EXEC_CMD="false"`  does the trick.

**Comment by cromain** [comment]
I have simplified the user check, dropping gid matching and opted for a simpler uid only approach as described in #1716
This case allows to run ejabberdctl either by root or install_user (if defined) and only allow current user if install_user not defined (development install for example). It's up to caller to su install_user or root.
