### ISSUE TITLE
ejabberd jlid.erl resourceprep check

### ISSUE THREAD

**Issue by nonexu** [processone/ejabberd#959]
Hi, ejabberd experts
     I encounter  an issue about the nick name.
     It returns a error when user named a special nick name such as "ᴵᴬᴹƤ๏łคгเร".
     And user can't be add into group and send message due to the errror.
     I checked the code, it is checked in stringprep.c. Some special character is not support.
     To fix this issue, I skip the resourceprep check, Is it correct?
   
    And do you have some other suggestion about this issue? 
    Thank you very much!

resourceprep(S) when byte_size(S) < 1024 ->
    R = stringprep:resourceprep(S),
    if byte_size(R) < 1024 -> R;
       true -> error
    end;

**Comment by mremond** [comment]
If you do not pass resource check, you should not disable it. Unless you found a bug and think this nick should pass resource prep, I think it means this nick is invalid as per XMPP specification.

Do you have reason to believe this nick is a valid and should pass resource prep ?

**Comment by nonexu** [comment]
I find there is some limited for xml.
Char     ::=     #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
Thanks for your reply.
Have a nice day!
