### ISSUE TITLE
msvcr100.dll missing

### ISSUE THREAD

**Issue by agnauck** [processone/ejabberd#960]
The msvcr100.dll is not present by default on Windows. When this dll is missing the postinstall fails and ejabberd cannot be started.
I suggest to distribute this dll to the bin directory with the installer.

Alex

**Comment by mremond** [comment]
@agnauck Is it allowed to redistribute that dll ?

**Comment by agnauck** [comment]
yes, Microsoft usually suggest to run the C runtime redist package within your installer.
However in many cases just xcopy install of this dll is fine.

See also:
https://msdn.microsoft.com/en-us/library/ms235299.aspx

**Comment by mremond** [comment]
Thanks @agnauck We will do out best to package it.
Do you know on which kind of system we can expect to find it already and were we can expect to have it missing ?

**Comment by agnauck** [comment]
I did testing on a fresh install of W7 and W8.1, and it was missing on both systems.
I would just put the dll in the binary folder and you should be fine.
If you want to run the Windows redist installer you can check whether it exist in the system dir or not. But the installer should do this as well, So you could just run it silent during the install.

**Comment by davehocking** [comment]
I have the same problem on 2012R2, msvcr100.dll was missing from the System32 folder and erl.exe and epmd.exe crashed on start. 

I first installed the x64 Visual C++ 2005 Redistributable, but this didn't work for me,
I then installed the x64 Visual C++ 2010 Redistributable and noticed that the required .dll file was supplied to the system.

After installing these packages, the ejabberd installer completed successfully (v16.02)

**Comment by cromain** [comment]
msvcr100.dll included in ejabberd's bin directory for 16.03
