### ISSUE TITLE
[Sugestion ?] mod_mam list of users

### ISSUE THREAD

**Issue by karlmendes** [processone/ejabberd#965]
I can define one list of users what wll save the messages ? Or not will save ?

default is always, never or roster.... but i like to select who users saved on archive table...

(I'm using odbc Mysql, powered by Debian)

Thanks in advance

**Comment by zinid** [comment]
Even if we implement something like that, it won't be standard compliant, because such functionality is not described in XEP-313.

**Comment by karlmendes** [comment]
Hmmm, that's right, i thing adjust the my trigger to save the log...

**Comment by zinid** [comment]
Ah, wait, seems like I'm wrong. Take a look at 'Example 20' of XEP-0313.

**Comment by zinid** [comment]
So it seems like this should work for you:
```xml
<iq type='set' id='juliet3'>
  <prefs xmlns='urn:xmpp:mam:1' default='never'>
    <always>
      <jid>romeo@montague.lit</jid>
    </always>
    <always>
      <jid>montague@montague.lit</jid>
    </always>
  </prefs>
</iq>
```

**Comment by karlmendes** [comment]
Archive preferences, interesting....

**Comment by karlmendes** [comment]
@zinid thanks for ur help, but i'm never program on erlang, i'm only install and configure a server... Thats implementation is on client side, right ?

**Comment by zinid** [comment]
Yes, that request should be sent by a client.

**Comment by karlmendes** [comment]
On the server side, i think don't have a parameters to this...
