### ISSUE TITLE
how affiliation value in opts variable is set

### ISSUE THREAD

**Issue by jalaramsuthar** [processone/ejabberd#969]
Hi,

We are having some doubts in group-chat.

Scenarios are: 
1-if user  A and B initially started group chat, affiliation value in opts variable will have only 2 users - Which is working as expected :+1: 
2-if user C is also invited for the group now whatever conversion should happen affiliation value in opts variable should have 3 users - which is working as expected :+1: 
3-now if user A left the group, B and C will have some chat, affiliation value in opts variable expected value is only 2 users (B and C) but we are also able to see all 3 users(A, B and C) :-1: 

Source: get_members(get_affiliation_value(Opts)))
Could you please provide your inputs.
Thanks,
Suthar Joy

**Comment by badlop** [comment]
I don't find the source code you refer to. What file, and what line, and what ejabberd version?

**Comment by jalaramsuthar** [comment]
Hey,
Thanks for your time.

actually we are using ejabbered14.5 ->mod_muc_log.erl

Sorry for the confusion about the source function provided earlier. It was actually written by one of the developer in our team.

My doubt is, I tried to read the value of "affiliations" present in "Opts" variable. According to my observation, the affiliations contains a list of participants present in the chat room at that particular instance when the message was being sent. However, when a particular member leaves the room, the affiliations still contains the information of that member, which shouldn't be the case according to what I feel.
For example, if there are 3 participants in group chat say A,B,C, then the affiliations has the value -> A,B,C. Now when B leaves the chat room, the affiliations still contains the value  -> A,B,C. However, I feel it should contain only A & C.

Can you please look into it? Or is it that I am making a wrong assumption?

Thanks,
Suthar Joy

**Comment by badlop** [comment]
> when a particular member leaves the room, the affiliations still contains the information of that member, which shouldn't be the case according to what I feel.

The concepts of Participant and Affiliation are unrelated, notice that:
> These affiliations are long-lived in that they persist across a user's visits to the room and are not affected by happenings in the room.

The concept of Participant is relevant to Roles, check http://xmpp.org/extensions/xep-0045.html#associations

**Comment by jalaramsuthar** [comment]
Okay, Thank you for your inputs.

Is there any existing feature in ejabbered14.5 ->mod_muc_log.erl to keep track on available list of user are active for particular group?

**Comment by badlop** [comment]
Not that I remember.
