### ISSUE TITLE
Offline message count with <body>

### ISSUE THREAD

**Issue by galambalazs** [processone/ejabberd#970]
Idea: Indexed field on messages (e.g. `has_body`) to quickly count the ones with content in body.

This would be the most efficient way to send back unread counts from the server (e.g. along with *Push Notifications*).

Currently, as I understand it, you'd have to get all the offline messages and filter those that are proper text messages with body.

There's `mod_offline`'s `store_empty_body` which can be set to `false` but then you may lose other messages that you want to be stored but not counted against the unread count.

Related discussion: https://github.com/processone/ejabberd/issues/842

e.g. messages with out of band data but no body would be thrown away by `store_empty_body=false`

```
<message from='stpeter@jabber.org/work'
         to='MaineBoy@jabber.org/home'>
  <x xmlns='jabber:x:oob'>
    <url>http://www.jabber.org/images/psa-license.jpg</url>
  </x>
</message>
```

http://www.xmpp.org/extensions/xep-0066.html

**Comment by galambalazs** [comment]
I started looking into how to implement this.

What's the difference between `count_offline_messages` and `get_queue_length` in *mod_offline.erl*?

**Comment by badlop** [comment]
As you can see, there's no difference:
```
get_queue_length(LUser, LServer) ->
    count_offline_messages(LUser, LServer).
```

**Comment by galambalazs** [comment]
Haha sure there is no difference *now*.

I think that commit only appeared on Github after I asked this question :)

https://github.com/processone/ejabberd/commits/9a049442fff958ff01730575b8db011b16ee30d3/src/mod_offline.erl

**Comment by galambalazs** [comment]
I actually opened another issue for the `store_empty_body=false` not being enough to control what messages get dropped: https://github.com/processone/ejabberd/issues/976

For push notifications I took another route by getting the unread counts from the client and storing them server-side.

**Comment by badlop** [comment]
>  sure there is no difference now.

Ah, right, so the next step is to mark one of them deprecated and stop using it. Finally, it should be removed in a future ejabberd version.
