### ISSUE TITLE
Could not get XEP-0023 message expiration to work

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#971]
i am trying to implement xep-0023 message expiration but it is not working .below is the xml which i used to test .

http://xmpp.org/extensions/xep-0023.html#sect-idp1196128

**Comment by mremond** [comment]
Do you have more details on how you perform the test, despite add an expire tag ?
Can you please share what lead you to conclude the feature does not work ?

Thanks !

**Comment by Nitin3589** [comment]
After sending this message , i checked it into my database as it should get removed but  it was there even after the specified expire time .

**Comment by mremond** [comment]
You have to call periodically ejabberdctl remove_expired_message (for example from cron) to trigger expired message clean-up.
