### ISSUE TITLE
unexpected error compiling src/luerl_scan.xrl

### ISSUE THREAD

**Issue by YugalXD** [processone/ejabberd#972]
make
/usr/lib/erlang/bin/escript rebar compile && :> deps/.built
==> goldrush (compile)
==> lager (compile)
==> p1_utils (compile)
==> cache_tab (compile)
==> fast_tls (compile)
==> stringprep (compile)
==> fast_xml (compile)
==> stun (compile)
==> esip (compile)
==> fast_yaml (compile)
==> jiffy (compile)
==> p1_oauth2 (compile)
==> p1_xmlrpc (compile)
==> luerl (compile)
unexpected error compiling src/luerl_scan.xrl
{'EXIT',{undef,[{leex,file,
                      ["src/luerl_scan.xrl",
                       [{scannerfile,"src/luerl_scan.erl"},{return,true}]],
                      []},
                {rebar_erlc_compiler,compile_xrl_yrl,5,
                                     [{file,"src/rebar_erlc_compiler.erl"},
                                      {line,512}]},
                {rebar_base_compiler,compile,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,121}]},
                {rebar_base_compiler,compile_worker,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,194}]}]}}
ERROR: compile failed while processing /root/ejabberd/deps/luerl: rebar_abort
make: *** [deps/.built] Error 1

**Comment by mremond** [comment]
You need to get latest dependencies after you do a git pull. Rebar does not do that automatically if they have been already downloaded.

**Comment by YugalXD** [comment]
on first run when it downloaded the dependencies it showed the same error.

**Comment by zinid** [comment]
It seems like you don't have `parsetools` installed. It's a part of standard Erlang OTP, but in some linux distributives it's a separate package (e.g. `erlang-parsetools` in Debian).

**Comment by YugalXD** [comment]
thanks it worked
