### ISSUE TITLE
store_empty_body=false deletes messages with out of band data?

### ISSUE THREAD

**Issue by galambalazs** [processone/ejabberd#976]
Messages with out of band data but no body would be thrown away by `store_empty_body=false`, right?

```
<message from='stpeter@jabber.org/work'
         to='MaineBoy@jabber.org/home'>
  <x xmlns='jabber:x:oob'>
    <url>http://www.jabber.org/images/psa-license.jpg</url>
  </x>
</message>
```

http://www.xmpp.org/extensions/xep-0066.html

I like the setting of dropping useless messages from offline storage but the level of control seems insufficient.

**Comment by badlop** [comment]
You are right, the stanza you show would not be stored with the option set to false.

However the example in the XEP shows a message with Body and with the X element. It doesn't say the Body element is mandatory, but it makes sense that it is included, as the X only provides additional information to the Body. Do current XMPP clients send the X element without Body in Messages?

And looking to the subject in other terms: XMPP is extensible, there are infinite namespaces that can be potentially included in Message stanzas. We are not to define which ones are "worth" storing offline and which ones not. We are only sure that they include Body or do not. So, following your line of thinking, the only proper way to implement that option would be to let the sysadmin configure what X namespaces to store and what not. But that only solves the problem for you. Then, following your line of thinking, users of your server would complain that some namespace is stored and should not, or isn't stored and should be.

To prevent all this, the current implementation breaks your line of thinking, and just takes care about Body, and considers that only messages with Body are worth storing. This lets the user decide the fate of the message: if the message is important to him, he provides a Body and it will be stored offline.

**Comment by galambalazs** [comment]
I'm with you here if `<body></body>` is enough to be stored.

Is it?

**Comment by galambalazs** [comment]
Ok found it. `<body></body>` seems to be enough.
https://github.com/processone/ejabberd/blob/e95cf420a2671c0f381724ee4af719a27ce5873d/src/mod_offline.erl#L515


Doesn't it make more sense to rename this option to something more straightforward?

`store_without_body`
`store_when_body_missing`

etc?

**Comment by badlop** [comment]
The option name and its documentation in the guide refer to "empty body", so that was the original purpose, but later got implemented in an easier way: just check if the body element is present, which looks equivalent but isn't exactly the same.

It got added more than a year ago (in https://github.com/processone/ejabberd/commit/74b67fa0dcdcc9a609b9dd5f9b3baec18a7980e2), and this is the first time somebody bothers with it. So, changing the option name isn't urgent (and would bother a little existing users), but of course at least the documentation should be correct. Something like this:

```
store_empty_body: true|false|unless_chat_state
 
Whether or not to store messages that lack a <body/> element.
The default value is unless_chat_state, which tells ejabberd to store messages
even if they lack the <body/> element,
unless they only contain a chat state notification (as defined in XEP-0085).
```

In my opinion, it is still slightly weird to understand because there are many negations, but at least it's correct now.

**Comment by galambalazs** [comment]
better :+1: 

I believe this option is not part of the default configuration file so most people don't bother with it? :)

**Comment by badlop** [comment]
Fixed in https://github.com/processone/docs.ejabberd.im/commit/d43237d288fc2635cd76100ddc3cde3e08036dfa
