### ISSUE TITLE
brew install support for 16.02 

### ISSUE THREAD

**Issue by devilankur18** [processone/ejabberd#981]
I tried pointing the url and hash to 16.02 binary in the brew formular for ejabberd.

On running `brew install ejabberd --enable-bar`

It keep throwing errors like this for multiple packages

```
Error: inreplace failed
rebar.config:
  expected replacement of /(?:https:\/\/|git(?::\/\/|@))github\.com[:\/]processone\/xml(?:\.git)?/ with #<Pathname:/Library/Caches/Homebrew/ejabberd--p1_xml--git>
```

Even I tried installing from the dmg package, even that is giving some post install script error.

**Comment by mremond** [comment]
No idea who created the homebrew package, but it is not us...
