### ISSUE TITLE
ldap shared roster regression in 16.02

### ISSUE THREAD

**Issue by p5n** [processone/ejabberd#986]
In 16.02 ejabberd cannot create LDAP shared roster (however LDAP auth and vcard work):

2016-03-07 00:37:14 =ERROR REPORT====
Error searching: {error,invalidDNSyntax} [{scope,baseObject},{base,<<"jabber-group">>},{filter,{and,[{equalityMatch,{'AttributeValueAssertion',<<"cn">>,<<"jabber-group">>}},{present,<<"objectClass">>}]}},{timeout,5},{deref_aliases,never},{attributes,[<<"description">>,<<"member">>]}]

Downgrading to 16.01 fixes this issue.

here is package build script for 16.02 - https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/ejabberd

and here is for 16.01 - https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/ejabberd&id=3d31c70e6504bcd9c09b7db5840c88cae5ab0fcc

config:
 mod_shared_roster_ldap:
    ldap_base: "dc=root"
    ldap_rfilter: "(cn=jabber-group)"
    ldap_filter: "(objectClass=*)"
    ldap_gfilter: "(cn=jabber-group)"
    ldap_ufilter: "(&(uid=%u)(memberOf=cn=jabber-group,dc=root))"
    ldap_groupattr: "cn"
    ldap_groupdesc: "description"
    ldap_memberattr: "member"
    ldap_userdesc: "displayName"
    ldap_useruid: "uid"
    ldap_memberattr_format_re: "cn=([\\w\\.\\-]*),ou=.*,dc=root"

**Comment by mremond** [comment]
@p5n Do you have ldif (anonymized or minimal version) you can share and full configuration so that we can check your case ?

**Comment by mremond** [comment]
I added some tests and rollbacked some broken changes.
This should be fixed in this commit: https://github.com/processone/ejabberd/commit/4afe0b195cfb15fb07129e02e674837edb44f65e

Please, let us know if this is not the case.

Thanks !

**Comment by p5n** [comment]
16.03 looks working, thank you
