### ISSUE TITLE
how to active the mod_mam in ejabberd? 

### ISSUE THREAD

**Issue by MetalZoa0** [processone/ejabberd#987]
how to active the `mod_mam` in ejabberd? 
i need to active this module because i need that it save the messages in a relational database mysql.

**Comment by weiss** [comment]
[Create the archive and achive_prefs tables][1], add `mod_mam` to the list of `modules`, and [read the guide][2] to find out which `mod_mam` options you might want to set (e.g., `default: always` to store all messages by default).

[1]: https://raw.githubusercontent.com/processone/ejabberd/master/sql/mysql.sql
[2]: https://docs.ejabberd.im/admin/guide/configuration/#modmam

**Comment by MetalZoa0** [comment]
I can not activate `mod_mam`, it's like he did not exist, because the ejabberd does not recognize the `mod_mam` syntax. iam using ejabberd 15.03.

**Comment by rraptorr** [comment]
mod_mam is not available in ejabberd 15.03, update your ejabberd installation to the latest version.

**Comment by MetalZoa0** [comment]
@rraptorr  there is a way to do this using Linux repository?

**Comment by MetalZoa0** [comment]
i am using linux ubuntu sheel 15.10

**Comment by beherit** [comment]
https://jabber.at/en/apt-repository

**Comment by rraptorr** [comment]
I have no idea.

**Comment by MetalZoa0** [comment]
thank you all
