### ISSUE TITLE
i dont can active the mod_mam, when i insert the mod_mam syntax in ejabberd.yml file the ejabberd don't works. what the problem? i am using ejabberd 15.03.

### ISSUE THREAD

**Issue by MetalZoa0** [processone/ejabberd#990]
i dont can active the mod_mam, when i insert the mod_mam syntax in ejabberd.yml file the ejabberd don't works. what the problem? i am using ejabberd 15.03.

**Comment by weiss** [comment]
ejabberd 15.03 didn't include `mod_mam` yet, it's shipped with [ejabberd 15.06][1] and newer.

[1]: https://blog.process-one.net/ejabberd-15-06/

**Comment by MetalZoa0** [comment]
@weiss  thank you so much
