### ISSUE TITLE
Migration tool for mod_mam mnesia to SQL

### ISSUE THREAD

**Issue by darix** [processone/ejabberd#992]
not talking about the mod_mam_mnesia from Holger but the module in core. it would be nice to be able to migrate messages when the mnesia table gets too big.

**Comment by mathiasertl** [comment]
Since we already hit the 2GB mnesia limit once, I +1 this request!

**Comment by mremond** [comment]
I think if we write migration tool it will be for mod_mam configured with Mnesia to mod_mam configured for SQL database. Probably not directly (or at least at first) for the contributed module.

**Comment by weiss** [comment]
FWIW, there's a tool to migrate from mod_mam_mnesia to mod_mam's Mnesia schema in the ejabberd-contrib repository, so it could still be done in two steps.

**Comment by mathiasertl** [comment]
@mremond that's what the original issue requested!

**Comment by badlop** [comment]
There's a module commented in https://github.com/processone/ejabberd/issues/1510 to export mnesia mam to sql, it could be rewritten as an internal function.
