### ISSUE TITLE
Stream management inefficient: don't send <r/> after every single stanza

### ISSUE THREAD

**Issue by galambalazs** [processone/ejabberd#993]
I'm very happy that Stream Management got some love in ejabberd. There's one big problem though:

Currently [`send_stanza_and_ack_req`](https://github.com/processone/ejabberd/blob/6e40573c136d0ff496a9899afc4b83bda361b769/src/ejabberd_c2s.erl#L1855) is called for *every* single stanza.

I think there's no need for that, it's also very inefficient.   
The standards recommend a more reasonable approach:
http://xmpp.org/extensions/xep-0198.html#scenarios-efficient

There should be an option to set up stream management ack requests:

- `request_ack_stanza_count`
- `request_ack_timeout`

So whichever happens first will trigger a request from the server.
e.g. (count: 0, timeout : 0) would mean that the server *never* sends `<r/>`'s automatically
e.g. (count: 1, timeout: 0) would match the current behavior (`<r/>` after every stanza)
e.g. (count: 10, timeout: 5) would send `<r/>` after every 10 stanza, or if the 5s timeout happens

**Comment by weiss** [comment]
> Currently [`send_stanza_and_ack_req`](https://github.com/processone/ejabberd/blob/6e40573c136d0ff496a9899afc4b83bda361b769/src/ejabberd_c2s.erl#L1855) is called for *every* single stanza.

Right.

> there's really no need for that

Where do you see the need for acknowledgments at all, given you see no value in having every message acknowledged immediately?

If the connection is lost and not resumed by the client, unacknowledged messages are either resent or error messages are bounced back to the sender (depending on the configuration and circumstances).  In both cases, you want to keep false positives to a bare minimum.  If you don't request an acknowledgment before sending, say, four messages, you will (on average) generate two unnecessary duplicates and/or bogus error messages whenever this happens, which results in a really bad user experience.

> The standards recommend a more reasonable approach

The XEP's reasoning is that message acknowledgments are an efficiency issue for mobile devices.  I don't think that's true.  You want to avoid waking the mobile's radio if possible, but when an acknowledgment is requested, the radio is up anyway.  I doubt that sending the (tiny) acknowledgement has a measurable impact in that situation.

Therefore, I believe it makes sense to have every chat message acknowledged.  For other stanza types, the trade-off might be different, but I'm not sure avoiding a few acknowledgments is worth the hassle of complicating the code.

**Comment by galambalazs** [comment]
> Where do you see the need for acknowledgments at all, given you see no value in having every message acknowledged immediately?

Requesting acknowledgment for every *message* immediately is a fine use case. It shouldn't be mandatory though. And requesting ACK after every stanza is way too chatty.

XMPP is a client-server protocol. Not requesting ACK for every single stanza doesn't mean that the client is not sending back ACKs.  There needs to be a level of control on the server side.

One notable example is:
I come online and receive 20 messages *at once* I don't need to get 20 `<r/>`'s and send 20 `<a/>`'s
I come online and receive 10 presences *at once* I don't need to get 10 `<r/>`'s and send 10 `<a/>`'s

But there are other examples like IQ pings, chatstates where it doesn't make any sense to do <r/><a/> roundtrips.

The easy to implement yet powerful way I see for ejabberd:
- a hook: `should_request_ack_after_packet`
- an option: `stream_request_ack`: *all | messages_with_body | none*

The first one would cover all use cases the second one would be for those who can't or don't want to write modules but still need some level of control.

**Comment by weiss** [comment]
> And explicitly requesting ACK after every stanza is way too chatty.

Is this an academic discussion or are you trying to solve an actual problem you have in practice?

> I come online and receive 20 messages *at once*, I don't need to get 20 `<r/>`'s and send 20 `<a/>`'s
> I come online and receive 10 presences *at once*, I don't need to get 10 `<r/>`'s and send 10 `<a/>`'s

But does it really hurt?  For 30 stanzas, we're talking about something like 1.5 kB worth of XEP-0198 traffic in addition to the, say, 10 kB of payload.  Changing the logic to avoid some of those bytes increases complexity, so I wouldn't do that without good cause.

> But there are other examples like IQ pings, chatstates where it doesn't make any sense to do <r/><a/> roundtrips.

As I said, the trade-off might be different, but I disagree with your stance that it makes no sense at all.  Those stanzas must be kept in the server's outgoing queue until they are acknowledged, for example.

> The easy to implement yet powerful way I see for ejabberd:
> - a hook: `should_request_ack_after_packet({From, To, Packet})`
> - an option: `stream_request_ack`: *all | messages_with_body | none*

If you simply stop requesting ACKs for certain stanza types, remote users can easily kill your session by flooding you with such stanzas.  So you can only do that up to a certain limit (which would probably have to depend on the configured `max_ack_queue` size).  You also don't want to wait an unlimited amount of time before requesting an acknowledgment.  So you have to install a timer.  When that triggers, you'd send the ACK request.  This might wake the mobile's radio, and might not play nicely with [push support][1].

And as I mentioned, you will generate way more duplicates and/or bogus error bounces this way, which is undesirable for some non-chat stanzas as well.  And those error bounces might wake the sender's radios, BTW :-)

> *(on the flip side: even explicitly requesting ACKs gives no guarantee that the client will send those ACKs)*

I don't see how this fact is relevant to the question whether it makes sense to requesting ACKs for every stanza.

Don't get me wrong.  If there's a real issue to solve, I'll happily look into it.  But so far I'm not conviced there is one, and I'd like to avoid premature optimization.

[1]: http://xmpp.org/extensions/xep-0357.html

**Comment by weiss** [comment]
> I come online and receive 20 messages `at once`, I don't need to get 20 `<r/>`'s and send 20 `<a/>`'s
> I come online and receive 10 presences `at once`, I don't need to get 10 `<r/>`'s and send 10 `<a/>`'s

This will no longer happen with ejabberd 16.09, as a new acknowledgement [won't][1] be requested before the response to the previous request is received.

[1]: https://github.com/processone/ejabberd/commit/621f0e2b7cbb6c431e2c26ad6561c6c0eb74c065
