### ISSUE TITLE
Question: IQ result 'from' attribute semantics

### ISSUE THREAD

**Issue by galambalazs** [processone/ejabberd#995]
Ejabberd seems to be using the user's bare JID as the `from` attribute for  IQ results coming *from the server*.

Any specific reason to include the `from` attribute in these cases?

I know that the protocol *allows* this, just curious what's the *reasoning* behind it.

rfc3920

> **9.1.2.  from**
> When a server generates a stanza from the server itself for delivery to a connected client, 
  the stanza MUST either (1) not include a 'from' attribute or (2) include a 'from' attribute whose 
  value is the account's bare JID (node@domain) or client's full JID (node@domain/resource). 
   [...] When a client receives a stanza that does not include a 'from' attribute, it MUST assume 
  that the stanza is from the server to which the client is connected.

*http://tools.ietf.org/html/rfc3920*

In the XMPP or XMPP Core RFC and every XEP I checked I found no `from` attribute for IQ results coming from the server (which to my eyes seems the better way to do it) or maybe sometimes containing the server's hostname (which is still good just a bit verbose).
http://xmpp.org/rfcs/rfc3921.html
http://xmpp.org/extensions/xep-0054.html
http://xmpp.org/extensions/xep-0199.html

Thanks

---------------

Example: Client receives roster from server:
```
<iq to='juliet@example.com/balcony' type='result' id='roster_1'>
  <query xmlns='jabber:iq:roster'>
    <item jid='romeo@example.net'
          name='Romeo'
          subscription='both'>
      <group>Friends</group>
    </item>
   ...
  </query>
</iq>
```

Privacy list result
```
<iq type='result' id='getlist1' to='romeo@example.net/orchard'>
  <query xmlns='jabber:iq:privacy'>
    <active name='private'/>
    <default name='public'/>
    <list name='public'/>
    <list name='private'/>
    <list name='special'/>
  </query>
</iq>
```

Example: Server acknowledges success of active list change:
```
<iq type='result' id='active1' to='romeo@example.net/orchard'/>
```

Pong response to a client Ping request
```
<iq from='capulet.lit' to='juliet@capulet.lit/balcony' id='c2s1' type='result'/>
```

**Comment by zinid** [comment]
Yet another stupid crap in the RFC.
Assume you send a disco request with 'to=your-server.com' and then will receive a result with 'from=user@your-server.com'. Really??

**Comment by galambalazs** [comment]
ejabberd currently sends back a bare JID like that inside the `from` attribute as far as I know.
Don't you think that could be dropped?

**Comment by weiss** [comment]
>ejabberd currently sends back a bare JID like that inside the `from`
>attribute as far as I know.
>Don't you think that could be dropped?

What problem are you trying to solve?
