### ISSUE TITLE
How to connect to room from another server in cluster?

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#998]
I have cluster of 5 ejabberd nodes.

I have created room on 1 server. And can see it via:
`ejabberdctl muc_online_rooms localhost`

But if i try this command on another server in cluster this command return empty list. Is it possible to access same room from different server in cluster or I can access room only on server where this room was created?

**Comment by badlop** [comment]
You must distribute to all the nodes the Mnesia tables: muc_room and muc_online_room, so the other nodes know that this room exist, and in what remote node it is alive.

**Comment by Suvitruf** [comment]
I'm using Riak as backend.

**Comment by badlop** [comment]
Ahh, I see. The persistent rooms are stored in the table _muc_rooms_, which can be stored in mnesia, odbc or riak. The temporary tables are only stored in the mnesia table _muc_online_rooms_.

When you call that command, obviously you want to get the list of all the currently existing rooms, both persistent and temporary, and this is only available in the mnesia table _muc_online_rooms_.

Consequently, even if you configured _db_type: riak_, to cluster the MUC service, you still must distribute the _muc_online_room_ table to the other nodes.

**Comment by Suvitruf** [comment]
But how can I do this? I thought that configure ejabberd as cluster is enough and all Mnesia data will be replicated automatically.

**Comment by badlop** [comment]
Right, it should. How did you add the other nodes to the cluster?

**Comment by Suvitruf** [comment]
`ejabberdctl join_cluster '{{ejabberd_leader}}'`

**Comment by badlop** [comment]
Ok, I setup two nodes, joined the second to the first. In the first I create account, login, join new room. In the second I run this:
```
$ /tmp/eja2/sbin/ejabberdctl muc_online_rooms localhost
room1@conference.localhost

$ /tmp/eja2/sbin/ejabberdctl dump_table /tmp/rooms.txt muc_online_room

$ cat /tmp/rooms.txt 
{tables,[{muc_online_room,[{record_name,muc_online_room},
                           {attributes,[name_host,pid]}]}]}.
{muc_online_room,{<<"room1">>,<<"conference.localhost">>},<13368.473.0>}.

$ /tmp/eja2/sbin/ejabberdctl debug
(ejabberd2@localhost)1> mnesia:info().
---> Active tables <--- 
...
muc_online_room: with 1        records occupying 322      words of mem
...
===> System info in version "4.12.3", debug level = none <===
opt_disc. Directory "/tmp/eja2/var/lib/ejabberd" is used.
use fallback at restart = false
running db nodes   = [ejabberd1@localhost,ejabberd2@localhost]
...
[{ejabberd1@localhost,ram_copies},{ejabberd2@localhost,ram_copies}] = [route_multicast,
                                                                       muc_online_room,
                                                                       session_counter,
                                                                       s2s,
                                                                       temporarily_blocked,
                                                                       iq_response,
                                                                       pubsub_last_item,
                                                                       session,
                                                                       reg_users_counter,
                                                                       http_bind,
                                                                       carboncopy,
                                                                       route]
```
So, all looks perfect. I used ejabberd 16.02, which one do you use?

Also, I am using default configuration, so all is stored in Mnesia. In your case even if you use Riak for most modules, muc_online_room should be stored in mnesia too, and should be replicated to all nodes when you called join_cluster.

Try the commands I showed you, and see if you find some clue in your system about your problem.

**Comment by Suvitruf** [comment]
Hm...

On server5 (where rooms were created) `ejabberdctl muc_online_rooms localhost` shows me rooms. But on server4 (another ejabberd node in cluster) this command returns empty list.

But `ejabberdctl dump_table /tmp/rooms.txt muc_online_room` on both nodes works correct and shows me list of rooms.

**Comment by badlop** [comment]
And, if you login to node4 (the one which command returns empty list), and request the list of rooms in the MUC service, do the rooms appear? I suspect the problem is only in the command, not in your setup.
